### ISSUE TITLE
[RFE] Ability for extensions to add functionality to record editor in the backend

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#1004]
I am putting my hand up for this if it is a reasonable RFE...

**Use case:**
A user wants a small piece of functionality in the edit record page for a particular contenttype that is not common to all Bolt users, either only their site or sites like them.  Rather than adding a feature that is not needed by 100% of users, they simply use an extension to dynamically add said button.

The button(s) itself update some of the records in-edit fields with AJAX.

Bolt core adds to the sidebar in `app/view/` something like:
```html
<section>
        <h2><i class="icon-ext-buttons"></i>Extension Buttons</h2>
        <div id=ext-buttons></div>
</section>
```

Extension developer adds something like the following in their `initialize()` method:
```php
$this->app['dispatcher']
           ->addListener(
                  AdminEvents::ADD_BUTTONS, 
                  array($this, 'myhookAddButtons'));
```

A real life example of how I, personally, intend to make use of such functionality is that our site reviews books available on Amazon and we have a contenttype 'Books'.  We would enter an Amazon product ID (ASIN) press a button and that would use the Amazon API in our homemade extension to look up the book's title, image (download it and store it), price, page count, publisher, etc and store that in fields.

This in all use cases would save content editors a lot of error-prone cut and pasting from another source and save them time, they just want to do a job fast!

**Comment by bobdenotter** [comment]
Functionality added a while ago.
