### ISSUE TITLE
workaround necessary: Firefox client bug causes file uploading problems

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#1019]
I have a content with a file type field in. Because of Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=373621 the chosen file type should contains `text/html` mime type in https://github.com/bolt/bolt/blob/master/app/view/js/bolt.js#L382. Therefore uploading PDF is impossible. Workaround is necessary.
(back reference #902)

**Comment by sergiocallegari** [comment]
Still cannot upload binary (.exe) files to releases with firefox on linux. Can upload with other browsers on linux.
