### ISSUE TITLE
[RFE] back end taxonomy filter for entry listing

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#1023]
Feature request for a couple of taxonomy (category, chapter, etc.) select dropdowns, above the entries listing in the backend, to quickly filter for a category etc.

**Comment by bobdenotter** [comment]
haha, GDmac. You actually duplicated yourself in #1023.

**Comment by bobdenotter** [comment]
See #2046

**Comment by GDmac** [comment]
pffft, march -> november
i guess it was still nagging me
Lol @ 1023 * 2 = 2046
