### ISSUE TITLE
Live / Exposed Filters possible?

### ISSUE THREAD

**Issue by klickreflex** [bolt/bolt#1063]
Hey there,

coming from the Drupal world I quickly fell in love with Bolt's performance and configuration management. Besides multilanguage content there's only one thing I'm missing, or rather I'm not sure if it's possible / how to achieve it: 

Is there a (proposed) way to apply live filters (known as exposed filters in Drupal Views) to a list of content? Say to have a select field that can narrow down a list of blog entries to a certain taxonomy term or filtering date ranges of events.

Thanks for any hints,
Daniel

**Comment by SahAssar** [comment]
I've done similar things using JS before. While that solution might not work for thousands of records it should be sufficient for most use cases.

Closing this since it seems better suited for an extension and there hasn't been movement in a long time.
