### ISSUE TITLE
Bolt ckeditor images

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1088]
The ckeditor in Bolt allows for selection of images from the server, but not to directly upload them through the pop-up. Is there anyway of enabling such functionality?

**Comment by quodroc** [comment]
If anyone is still interested in this, I've figured out a way to do it in a bit of a hacky way.

config.yml
```yaml
wysiwyg:
    images: true
```
app/view/js/ckeditor/config.js
```javascript
CKEDITOR.on('dialogDefinition', function (ev) {
  var dialogName = ev.data.name;
  var dialogDefinition = ev.data.definition;
  if (dialogName == 'image') {
    dialogDefinition.removeContents('Upload');
    dialogDefinition.addContents({
      title: "Upload",
      id: "upload",
      label: "Upload",
      elements: [{
        type: "html",
        html: '<iframe name="ck_upload_iframe" style="height:0;width:0;border:none;" onload="try{var url=JSON.parse((this.contentDocument||this.contentWindow.document).body.textContent)[0].url;CKEDITOR.dialog.getCurrent().getContentElement(\'info\',\'txtUrl\').setValue(\'/\'+url);}catch(e){}"></iframe><form action="/upload" method="post" enctype="multipart/form-data" target="ck_upload_iframe"><input type="file" name="files[]" accept=".gif,.jpg,.jpeg,.png" onchange="this.parentElement.submit()"/></form>'
      }]
    }, 'Link');
   }
});
```

Here is the formatted html from above
```html
<iframe name="ck_upload_iframe" style="height:0;width:0;border:none;" onload="
try {
	var url = JSON.parse((this.contentDocument || this.contentWindow.document).body.textContent)[0].url;
	CKEDITOR.dialog.getCurrent().getContentElement('info', 'txtUrl').setValue('/' + url);
} catch (e) { }
"></iframe>
<form action="/upload" method="post" enctype="multipart/form-data" target="ck_upload_iframe">
	<input type="file" name="files[]" accept=".gif,.jpg,.jpeg,.png" onchange="this.parentElement.submit()"/>
</form>
```

I'm basically just adding an Upload tab to the image dialog with a simple file input that submits to /upload in a hidden iframe, parses the response, and sets the image url in the dialog. It assumes your bolt site is at the root of the domain. I'm not sure how this should be coded properly (ie to be accepted in a pull request) but feel free to use this as a starting point.

**Comment by rarila** [comment]
With CKEditor 4.5 (which we have switched to recently) direct file upload is [possible](http://docs.ckeditor.com/#!/guide/dev_file_upload). So I'm sure as soon someone finds some time this will find it's way into Bolt. Probably in the course of a coming CKE config refactoring. No timeframe yet, sorry.

**Comment by chloroformiate** [comment]
I need this feature too ... this will be nice
