### ISSUE TITLE
Setting a menu parent per content type

### ISSUE THREAD

**Issue by klickreflex** [bolt/bolt#1090]
Say we have a menu item 'News' that links to the listing of all content of type 'news'. When visiting the news listing the menu item is given a class called `active`using ` {% if item|current %} active{% endif %}`.

When we open a single record of type news that information is lost. Is there any chance to configure something like "Menu Parents" on a per-content-type basis? Having an option like 

    news: 
        parent_menu_item:
            menu: Main
            title: News

This would result in setting the menu item "News" of the menu "Main" to "activ when viewing any news record.

Or is there a way I just havent found out yet? How do you manage this task? 
I can't imagine being the sole person to need this as it's quite a bad user experience not to indicate the current position inside a navigation tree.

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
