### ISSUE TITLE
category and subcategories

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#1096]
Is it possible to use nested category from taxonomy?
EXAMPLE.
![cat2](https://cloud.githubusercontent.com/assets/6233822/2659662/fa65241a-c016-11e3-9479-091dcb55c198.png)

OR 
video:
- Sub: DVR
- Sub: DVD
- Sub: TV

Thank you very much :-)

**Comment by antoine64** [comment]
Hi serweb-labs, have you found a solution (or gadget) to make subcategories ? I'm interested too !

**Comment by serweb-labs** [comment]
I'm working on it, but do not decide whether place as an extension (which would
cause some problems) or make a pull request to add it as a route controller in
the Bolt core, I'm not sure the team Bolt is open to this proposal .

2015-05-19 12:33 GMT-03:00 Antoine Rouault de Coligny <
notifications@github.com>:

> Hi serweb-labs, have you found a solution (or gadget) to make
> subcategories ? I'm interested too !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bolt/bolt/issues/1096#issuecomment-103554791>.
>



-- 
Atte. Luciano Rodríguez
SerWeb.
