### ISSUE TITLE
[Feature] Portal like layout editing functions

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#1111]
_Because I had to replace a working resource vampire java based portal and decided to implement it under Bolt, I have to make try to extend Bolt's functionality with layout editing. Because it is a quite large bite I think it is a good idea talk about it 'cause I don't want to reinvent any warm water. Is there a work in progress under this chapter? Do you have better idea, or suggestions? Please share..._

Current status: *under development* 

### Terminology

**Units** are HTML fragments of any of next items.
**Content** is a Bolt contettype element which describes a specific visual unit to be displayed. Contents can be placed on a layouted web page within a container element called **portlet**. 
**Portlets** has some attributes that can control visual look of its content instance. Portlet instances can be placed in a container ~~area~~ **slot**.
~~Areas~~ **Slots** are placeholders in a **layout**.
**Layouts** are HTML fragments may have multiple ~~areas~~ slots should be ordered and rendered by different ways.
Each **page** can be addressed by a URI and should contain a layout that finally determines the look of each contained portlets that can be sorted as you like.

#### Structure

* This feature is planned to implement as a Bolt extension
* Because of some kind of HTML structural requirements - like being of portlet and area units - it will shipped with a portal theme and it won't work without.
* Required schema of any unit is described as Bolt contenttype, therefore whole data structure is handled by the core.

#### Frontend

* Early versions I'm focusing on constructing pages via templates as much as possible. Then could see weaknesses...
* In next versions the user logged in has option to adjust properties of portlets on the frontend, remove or reposition them with drag&drop too.

#### Backend

* Currently I have a working structure and each unit can be managed by hand on the backend now.
* Just planning a visual admin interface to manage page-layout-portlets-contents assignement and there is good chance for a D&D style interface.
* Container units should be switched off from backend menu (either by permissions' view option) after DD ui begins to work.

**Comment by bobdenotter** [comment]
Rix, is this still something you're working on? 

Closing this, but if you feel this is still an issue, feel free to re-open it.
