### ISSUE TITLE
 suggestion: language files

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#1117]
I like that the language file (message.XX.yml) supports overwriting the update version (message.es.yml.dist example) of the problem is to "translate" custom content types and other things I must add lines to these files, but to update I get the unpleasant surprise that these lines were lost completely because the file was overwritten.

Or create a separate file that is customizable and not overwritten.
Much we escribimimos code words in English to share and reuse regardless of the language of the next project.

Also would be interesting to define a language for each user if desired.

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
