### ISSUE TITLE
Loading a custom config file.

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1118]
I'm integrating my Bolt website with mailchimp and as a result I need to be able to use the mailchimp functionality in a few places. When using the API it requires keys for identifying the user, mailing lists, etc.

Ideally I would like to create a mailchimp.yml file which can be used to store these info. However I'm not sure how Bolt loads it's config files.

Instead for now I've added the keys to main config.yml file but if someone could tell me how to load it in if it were a separate config file then that would be great.

I've tried: `$this->app['config']->get('mailchimp/api_key');` but it just came back `false`.

**Comment by antonio-polastri** [comment]
$config = Yaml::parse($app['resources']->getPath('extensionsconfig') . '/'.$this::CONF_NAMEFILE) ;
