### ISSUE TITLE
Meta in body and  insertAfterMeta

### ISSUE THREAD

**Issue by truffo** [bolt/bolt#1129]
You can have meta tag in html body, for example : 

```
<body>
 ... 
 <meta itemprop="datePublished" content="2011-03-25">March 25, 2011
</body>
```

If you use insertAfterMeta method, this tag is matched and the data add in the body but not in the html header.

**Comment by SahAssar** [comment]
I ran into the same issue when using microdata (#2786). Since bolt adds it's own meta tags in "after meta" that are not valid to use in body and since HTML5 allows for meta tags in body this is clearly an issue in my mind.

**Comment by jadwigo** [comment]
pinging myself as this is related to an extension I'm writing

**Comment by bobdenotter** [comment]
I've taken the liberty of assigning you to this issue, then. ;-)

**Comment by jadwigo** [comment]
In that case...
My opinion is that 'aftermeta' should insert code after the last meta tag **in the head** of the html document.

**Comment by jadwigo** [comment]
and maybe 'beforecss', 'aftercss', 'beforejs' and 'afterjs' should know about the head too

**Comment by SahAssar** [comment]
I'd agree about beforecss and aftercss, but since js is often last in the body beforejs and afterjs should maybe be treated differently.

**Comment by bobdenotter** [comment]
fixed in https://github.com/bolt/docs/pull/179
