### ISSUE TITLE
How do I call an extension function from another class?

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1133]
I'm just writing an extension to manage site members as there's going to be a lot more than originally thought. Rather than having Bolt eagerly load them all I'd rather optimize and load them when required. I've therefore created a `members` extension.

I now need to call this extension to use it's functions from other classes in the system.

Do I use `$this->app['extensions']` somehow?

**Comment by bobdenotter** [comment]
Fixed by rewrite in 2.0.
