### ISSUE TITLE
Backend templating

### ISSUE THREAD

**Issue by ntomka** [bolt/bolt#1173]
We can adjust some minor branding option in config.yml, but we can't change the template. I bet this has been discussed somewhere but I can't find it's trails. :)

I know this shouldn't implemented a way that one can literally change everything on the Bolt branding, but it would be great if parts could be changed, like widgets and twig blocks should be used. So we could update Bolt's core for new features and bugfixes without conflicts.

Anyway, I found a way I can replace the whole backend template from a simple extension:

```PHP
public function initialize()
{
    $paths = $this->app['twig.loader.filesystem']->getPaths();
    array_unshift($paths, __DIR__ . '/template');

    $this->app['twig.loader.filesystem']->setPaths($paths);
}
```

If I copy parts or the whole backend template to the directory 'template' twig uses it first. What I mean with this is if someone wants to change the template there was a way he/she can achieved this.

**Comment by bobdenotter** [comment]
I'm going BDFL on this. Wontfix.

**Comment by blaues0cke** [comment]
I am still stuck with this (bolt 3.5). Does someone has a working solution he can share with me? 

https://stackoverflow.com/questions/52754936/overwrite-backend-template-in-bolt-cms
