### ISSUE TITLE
multi-site -feature

### ISSUE THREAD

**Issue by ghost** [bolt/bolt#1191]
Are there any plans to allow a single install of Bolt to manage multiple websites?

**Comment by leggewie** [comment]
JFTR, there is https://docs.bolt.cm/3.2/howto/multi-site-setup

**Comment by jaehocho** [comment]
I had used single bolt 3.2 instance to run multiple sites. 
I am upgrading to 3.7 and I cannot find any documentation on installing the version for multi-sites.
Do you have any recommendation for me?

**Comment by rixbeck** [comment]
> I had used single bolt 3.2 instance to run multiple sites.
> I am upgrading to 3.7 and I cannot find any documentation on installing the version for multi-sites.
> Do you have any recommendation for me?

Hey @jaehocho 

try here: https://github.com/bolt/docs/blob/3.2/docs/howto/multi-site-setup.md or here https://github.com/bolt/docs/blob/3.7/docs/howto/multi-site-setup.md

**Comment by jaehocho** [comment]
Thanks @rixbeck ! I will give this a shot.

**Comment by develth** [comment]
Hello!
Is multisite currently possibe with 5.2?

**Comment by bobvandevijver** [comment]
The referenced documentation and this repository is for 3.7, which isn't maintained anymore. I am not aware of such setup documentation for 5.2.

**Comment by develth** [comment]
Thanks for the quick answer @bobvandevijver !
But would it be possible if i would go with the old docs within the repo that are linked here?

**Comment by bobvandevijver** [comment]
No, I do not think so. But to be honest, I also see very little advantage of using such a setup as it only complicates configuration to save a couple of bytes of disk/RAM.

**Comment by develth** [comment]
Ok, just going through some cases. 
A project that uses a bolt.cm currently want to migrate the current wordpress to bolt and i try to migrate it into one system, so users need to login only once & can manage both pages there

**Comment by bobvandevijver** [comment]
That is not the goal of the multi-site setup described here. You're looking for federated authentication, which bolt does not support out of the box. You might be able to implement it yourself, but this ticket is not the place to discuss that.

**Comment by develth** [comment]
Was more like the TYPO3 based Setup / Logic: one Login within the CMS, multiple Sites etc. Not regarding federated authentication.
Just a "simple" use to manage multiple pages with different domains without the need to setup a whole CI pipeline to deploy changes or have mutliple code bases
