### ISSUE TITLE
Dynamic Hierarchical Structure. Be able to go deeper than just one level in the url structure, allow for child pages or sub pages. 

### ISSUE THREAD

**Issue by bzerangue** [bolt/bolt#1205]
I want to create a dynamic tree structure like this:

	page 1
	page 2
	page 3
	  subpage 1
	    subsubpage 1
	    subsubpage 2
	      subsubsubpage 1
	  subpage 2
	  subpage 3
	page 4
	etc.
	
It would be nice to be to sort and order via drag & drop interface, especialy with the hierarchical structure. 

For instance on the `page 3` portion of the structure, it would make the following pages/urls...

	/page-3
	/page-3/subpage-1
	/page-3/subpage-1/subsubpage-1
	/page-3/subpage-1/subsubpage-2
	/page-3/subpage-1/subsubpage-2/subsubsubpage-1
	/page-3/subpage-2
	/page-3/subpage-3
	/page-4

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.

**Comment by bzerangue** [comment]
Has this issue been solved? If not, I still feel it's an issue since you can't build a url structure that goes beyond one deep.

**Comment by bzerangue** [comment]
Unfortunately, my PHP skills are fairly lackluster. How difficult would it be to add this as an extension?
