### ISSUE TITLE
makeSlug() vs.slugify()

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1232]
So we have ``makeSlug()`` and ``util::slugify()`` where the latter isn't used at all (as ``util::remove_accents()``

So, is ``util::slugify()`` somehow left over and could/should be removed or already there for future use?

Another thing: both doesn't seem to handle umlauts right/nice. I'd like to have the slug ``bratwuerste`` when I input ``Bratwürste``. Instead I get ``bratwurste``.

So the next question is, would changing the behavior of ``makeSlug()`` break existing installations? Some ``strtr()`` in front of that code would do the least. Also ``iconv("UTF-8", "ASCII//TRANSLIT", $slug)`` and ``Transliterator::transliterate`` would be worth a consideration.

**Comment by bobdenotter** [comment]
Is this still an issue? If not, please close this one, @rarila or @GawainLynch

**Comment by rarila** [comment]
Perhaps we should move that point to the roadmap?
