### ISSUE TITLE
Bug: Upload files/images behaviour (re)naming and/or overwriting

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#1249]
- In some instances (from the uploaded files page) it seems that dashes are converted to underscores. 
- From the uploaded files page, if you upload a file with the same name, the file is then overwritten (which can be desired or non-desired)
- When uploading from a Image field, the file is not overwritten (e.g. number attached: ``image (1).jpg``)

I think this can be thought out a bit and imho handled by a file-manager (see also #1024 )

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.

**Comment by GDmac** [comment]
I have not tested the original issues again for 2.x
Would appreciate if this could be left open until able to verify.

**Comment by GawainLynch** [comment]
I have some pending fixes... I have pushed some of the pre-requisites upstream in late November, but they haven't been merged, so I might try to merge with @rossriley's (current) fork instead.
