### ISSUE TITLE
Feature proposal: relation in where parameters of getContent and corresponding twig tag

### ISSUE THREAD

**Issue by kkriehl** [bolt/bolt#1301]
A feature I am missing right now is the possibility to fetch content that is related to a specific record.

For example if I have a content type "location" and a content type "event" - which is related to "location" - I can select the corresponding location for each event. If I want to display a list of events for a specific location I might use an if condition in the twig template and check the name of the related location for each record (and need to fetch the related location for each record while skipping a possibly big amount of unnecessary rows). But I can't use Bolt's integrated paging to browse the records because It's using the result of the getContent-method to calculate the page count.

My proposal would be to allow keys like "location.name" for the where map, with the dot indicating a field in a related record:

```twig
{% setcontent location_events = '/events' where { 'location.name' = 'Köln' } allowpaging %}
```

That would make the query creation a little bit more complex because of the optional joins though.

(For now I added a twig function for that specific query that also creates a pager that is usable by the pager twig function from Bolt...)

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
