### ISSUE TITLE
New extension (Elasticsearch integration), ask for review

### ISSUE THREAD

**Issue by revollat** [bolt/bolt#1317]
Hello everyone !
Following the open source paradigm "Release early, release often" I would like to have your ideas, opinions, testing on the extension I just wrote.

https://github.com/revollat/bolt-elasticseach-extension

It's about integrating elasticsearch a fantastic full text search engine in Bolt CMS (see https://github.com/FriendsOfSymfony/FOSElasticaBundle in Symfony2 full stack framework)

So for now it's very basic but it works (at least at my house :)

For people who already know elasticsearch the config file should be straightforward (for the other who want to test it , just ask me, I'll be glad to let you discover elasticsearch with Bolt)

So 2 main feature for the moment : 

- Add admin menu to recreate the index entierly (you need to lauch this at the first use)
- Add listener so when a content is added/updated/deleted the index is updated accordingly.

IMPORTANT : to make the extension work, of course you have to run elasticsearch service somewhere on your network :), but your also have to add elasticsearch-php API in composer.json and install it :

        "elasticsearch/elasticsearch": "~1.0"

Now the next work is to design a front to be able to search in the index ... 

So any tester, enthusiast, ... would be welcome !

**Comment by bobdenotter** [comment]
Please update your extenion for Bolt 2.0, and add it to extensions.bolt.cm if you haven't yet. 

See the docs on how to proceed:  https://docs.bolt.cm/extensions/config
