### ISSUE TITLE
Paging of file list does not work

### ISSUE THREAD

**Issue by skanel** [bolt/bolt#1350]
for managing the files uploaded page I found a few issues.
1) paging not works
2) shoud not allow to duplicated upload( the bug or not?)
3) the "index.html" should not display in the file list.
4) If I check in `app\config.yml`
```php
accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]
```

But When I upload the file within MP3 extension I got message 

``` 
File '' could not be uploaded
```

EDIT:

(4) To understand how a form can be invalid I ***fixed*** the code by using :$form->getErrorsAsString();
And then I know why I can not upload the file from error message.

```
ERROR: The CSRF token is invalid. Please try to resubmit the form. ERROR: The uploaded file was too large. Please try to upload a smaller file.
```

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
