### ISSUE TITLE
PHP built-in server broken. (was: "Error "Template "editconfig.twig" is not defined")

### ISSUE THREAD

**Issue by h4cc** [bolt/bolt#1351]
I have installed bolt using these instructions `http://docs.bolt.cm/installation#option-3-the-developer-way-using-git-and-composer` and get the following error:
```
Error "Template "editconfig.twig" is not defined"
```
when accessing one of the urls

* `/bolt/file/edit/theme/index.twig`.
* `/bolt/file/edit/app/config/config.yml`
* `/bolt/file/edit/app/config/contenttypes.yml`
* `/bolt/file/edit/app/config/taxonomy.yml`
* `/bolt/file/edit/app/config/menu.yml`

To run the site i have been using this command and php version:

```
$ php -S localhost:8000 -t . index.php
PHP 5.5.3-1ubuntu2.3 Development Server started at Fri Jul  4 13:42:25 2014
Listening on http://localhost:8000
Document root is /home/julius/silpion/Speedpool/2014-07-04_Basis_CMS/bolt/bolt
Press Ctrl-C to quit.
```

**Comment by bobdenotter** [comment]
Closing this, since it is a bug in PHP, not in Bolt.
