### ISSUE TITLE
[RFE] Definition of upload prefix in contenttypes.yml needed

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1393]
We have to agree on a format which defines into which directory uploads should go.

See: #1391, #1306 and  #574.

Field types that could/should make use of a configurable upload directory:
- ``html``
- ``image``
- ``imagelist``
- ``file``
- ``filelist``

Perhaps there could be a general entry direct below the contenttype that defines the directory for all upload fields that have no explicit definition. So we get that order:
- field definition
- contentype definition
- default definition (``date('Y-m')``)

:question: First question: how should that parameter be named: ``upload_dir``, ``upload_path``, ``upload_format``, ``upload_prefix``, ``upload_destination``, ``destination``, ...?

:question: Next question: how can upload namespaces integrated? Should perhaps the path simply given as relative to the root path like ``files/images``, ``uploads/flyer``, ..?

:question: And last: should there be some variable substitution? Perhaps we could start with a static value and add the dynamic one later as needed.

:unlock: Discussion is opened!! :smiley:

**Comment by bobdenotter** [comment]
Is this still something we'd want? If so, please label and assign it appropriately :-)
