### ISSUE TITLE
Get slug from contenttype on listing pages

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#1395]
Most of the times I give listing pages a title so readers know what sort of content they are reading. Because you cannot use `{{ record.title }}` obviously, I use: 
`{{ paths.current|replace({'/':''}) }}`
Yes, sloppy. I can use this instead:
`{{ records|first.contenttype.slug }}`
Equally sloppy...

In my opinion you want to be able to get the `singular_slug`, `slug` of a contenttype on a listing page.
What do you all think?

**Comment by bobdenotter** [comment]
Actually, `{{ records|first.contenttype.slug }}` is the correct way to do this.

**Comment by peterboorsma** [comment]
O.K.

**Comment by Pinpickle** [comment]
I would consider this method not optimal because it doesn't work if there are no records. There are the variables `search` and `taxonomytype` defined so we can distinguish between them in a listing template, why can't we have `contenttype` defined as well?
