### ISSUE TITLE
simpleforms update

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#1399]
The simpleforms extension has some problems which should be fixed.

In the 'advanced' use cases it's showing it's limitations a lot because storing content in databases needs database magic, it has no mechanisms to extend it, it's missing a lot of client side and server side validation and people often need more control over the display of the form html with fieldsets and such.

There are two ways to do this:
 - refactor, cleanup and extend simpleforms to do a lot of this (the name simpleforms does not apply anymore)
 - abandon it and make two extensions: the first small-contact-forms and the other huge-advanced-forms

Because I'm not a fan of refactoring my preferred solution would be the two replacement extensions.

The contact forms would be an extension that is safe and secure for small sites and does `{{ form('mycustomformname', {'to': 'me@example.com', 'from': 'site@example.com', 'cc': 'myfriends@example.com', 'fields': {'subject': 'text', 'message': 'textarea', 'another text box': 'text',  'sender': 'email', 'ok': 'submit'} }) }}` or something similar

And the  advanced form would be the one that can be configured with `config.yml` and do all the things we want it to do like
- other field types
- extensible event handlers
- save stuff in the database
- browse database results
- complicated email rules
- control over display (prefix, suffix, markup)
- custom templates
- javascript client side validation
- server side validation and error messages
- multi step processes
- a drop in replacement for the contact form, so the minimal syntax should be the same

Does anyone have some extra ideas?

**Comment by bobdenotter** [comment]
This is in 2.0. Closing.
