### ISSUE TITLE
bolt update overrides custom settings in .htaccess (https)

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#1406]
if you update a bolt to a new version your .htaccess will be overwritten

this will reset all customizations like the RewriteBase, custom redirects, always https, memory flags

I suppose this also happens with other servers than apache

I'm not sure how this could be solved, but it's something that should be improved

**Comment by bobdenotter** [comment]
I'm not sure how we could fix this. Please close the issue, or self-assign, if you'd like to work on it.

**Comment by GawainLynch** [comment]
Going to add this one to the "issue clean up" list.
