### ISSUE TITLE
Repeating fields

### ISSUE THREAD

**Issue by danielgamage** [bolt/bolt#1420]
I often find myself wanting to add minor bits of content that aren't complex enough to merit their own content type (in my opinion).

Repeating fields are my proposed solution. Repeating fields would be declared by a field definition. Stealing from drupal's convention, a `limit` field could accept non-negative integers, 0 being unlimited, and 1 being the default value (i.e. no repeat).

```
html:
    type: html
    height: 150px
    limit: 10
```

In this way, the abilities of specialized fields like imagelist and filelist to hold more than one value could be extended to other field types.

To make this even more powerful, I could see this being paired with the ideas in #1115 to have repeating _groups_ of fields, similar to repeating field collections in drupal:

![](http://www.commonplaces.com/sites/commonplaces.com/files/images/blog/example-field-collection.png)

Does anyone have ideas on this or where to begin?

**Comment by jeff-h** [comment]
I'm very new to Bolt, but from what I'm seeing, it seems that what @khromov said in https://github.com/bolt/bolt/issues/1420#issuecomment-50524619 holds most true to Bolt's philosophy (and would keep the db schema very clean).

In the particular use-case I have right now for repeating field groups, it could definitely be argued that each repeating field group's content is a distinct "entity" (i.e. contenttype) that is related back to the "parent" record.
