### ISSUE TITLE
Storage::getContent()

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1454]
Just had a look a that funktion.
```php
public function getContent(
    $textquery,
    $parameters = '',
    &$pager = array(),
    $whereparameters = array()
)
```
Dokumentation says:
```php
     /*
     * @param string $parameters
     * @param array  $whereparameters
     */
```
If I haven't overseen something, in all calls to that function the variable type passed to $parameters is an ``array``. So at least in the docu there should be ``@param mixed $parameters``.

* As there are only two calls –  ``Content::next()`` and  ``Content::previous()`` –  which possibly call that function with a ``$whereparameters`` 
* and ``$parameters`` often is used with values I would classify as _where_-parameters 
* and as both are mixed together with ``array_merge`` in that case

I would suggest refactoring the whole thing to a simple and hinted:

```php
public function getContent($textquery, array $parameters = array(), &$pager = array())
```

I also couldn't find one place, where a _returned_ pager is used or even one is passed. The pager is set in that function anyway so let's kill :hocho: that one too:

```php
public function getContent($textquery, array $parameters = array())
```
\*sing\* What a wonderful world this would be…  :grinning:

**Comment by bobdenotter** [comment]
I think this was fixed by @rixbeck a while ago. 

Closing this, but if you feel this is still an issue, feel free to re-open it.
