### ISSUE TITLE
Images should easily be editable in an online image-editor.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#15]

**Comment by SahAssar** [comment]
@bobdenotter Is this still something that we'd like in bolt core or is this more in extension territory now?

If nothing else I'm considering keeping it open since in three days it will be three years old :)

**Comment by GawainLynch** [comment]
Ha!I asked @bobdenotter the same thing a couple of days ago about this one!

**Comment by SahAssar** [comment]
Closing since this seems to be extension territory nowadays. Please reopen if deemed to belong in bolt core.
