### ISSUE TITLE
Discussion: ContentType field option for "show in dashboard overview table"

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#1565]
OHAI everyone.

So I'm on a project right now, and aside of "news" and "pages", this restaurant is some special one we have in my local area. They have weekly opening times, and are opened just every now and then. So I created this openings contenttype, which only has one text field: title. This title is almost the same for almost every event, except being special events. So what does that give me? Right. A dashboard overview with the same title. Doesn't help.

The index'd and slug'd fields are the timestamps for opening and closing dates. How could I bring those to the dashboard?

a ) hardcode some crap @ https://github.com/bolt/bolt/blob/master/app/src/Bolt/Content.php#L710 (DO. NOT. WHANT).
b ) deviate from index'd and/or slug'd fields (might make the logic behind this even more hackish || doesn't sound flexible enough).
c ) make a special field type option to "view in overview" or something (probably the best solution).
d ) for fields with similar text fields: just display the slug (just came to mind, disregarding the thought as I'm typing this).

So I set this up for discussion: Gimme ur thoughts!

Greetings from the land of "Besenwirtschaften" (http://en.wikipedia.org/wiki/Strausse).

**Comment by bobdenotter** [comment]
This was fixed in 2.0 (see "viewless" contenttypes)
