### ISSUE TITLE
Routing question: how to combine pages and listing template for blogposts

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#1570]
I have an existing site with only pages (paginas, in Dutch) and in the routing:
```paginabinding:
  path:           /{slug}
  defaults:       { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'pagina' }
  contenttype:    paginas
```

Now I have to add a blog section. How and where should I add the proper routing setting so the blogpost-listing (e.g. /nieuwsitems?page=1 ) gives no errors in the browser? It's no problem if the blog-URLs contain a '/' or a '?' somewhere.

Probably an easy question if you actually understand the routing syntax - which I don't :-(

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
