### ISSUE TITLE
Feature request: generator meta tag enable/disable option in config

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1629]
By default Bolt adds a meta tag to the HTML head showing that the page was generated by Bolt. From a security side of things I believe it is better that this is not shown, as it informs any potential attackers of the underlying software.

It would be quite easy to add an option to the config.yml to enable/disable this. Then you'd just need to update the code in the `Bolt\Application afterHandler()` function to:

``` php
// Perhaps add the generator
if ($this['config']->get('general/show_generator')) {
    $this['extensions']->insertSnippet(Extensions\Snippets\Location::AFTER_META, '<meta name="generator" content="Bolt">');
}
```

**Comment by zomars** [comment]
When I call any URL via AJAX, also returns this dirty code, this option could help me a lot.
```
<meta name="generator" content="Bolt">
<link rel="canonical" href="http://ocalhost:3000/listing">
```

**Comment by GawainLynch** [comment]
The option is not going to be made available, however it is fixed in the upcoming v3.0

**Comment by bobdenotter** [comment]
I think it should also be fixed in the latest 2.2.x. 

@zomars What version is this on?

**Comment by MikSDigital** [comment]
Hello!
I am using Bolt 3.2.14. What is the best way to remove 

> <meta name="generator" content="Bolt">
from resulting HTML?

**Comment by GawainLynch** [comment]
> The option is not going to be made available

:smile:

**Comment by MikSDigital** [comment]
@GawainLynch , that's ok. I suppose to remove some code from the source file containing this part but I do not know where to look at.

**Comment by SahAssar** [comment]
@MikSDigital That'd be right here: https://github.com/bolt/bolt/blob/release/3.2/src/EventListener/SnippetListener.php#L76-L79

**Comment by iskyd** [comment]
I've got the same issue in bolt 3.3.
This is a workaround without changing any vendor files.

In your index.php before $app->run();

```$app->after(function (\Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response) {
        $pattern = '/(<meta name="generator" content="Bolt">\s?<link rel="canonical" href.+?">)/';
        $content = preg_replace($pattern, '', $response->getContent());
        $response->setContent($content);
}, \Silex\Application::LATE_EVENT);```

If you need (as I read in comment) to disable only in some specific ajax call you can do something like that

```
$app->after(function (\Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response) {
    $path = $request->getPathInfo();
    if(strpos('whatyouwant', $path) !== null) {
        $pattern = '/(<meta name="generator" content="Bolt">\s?<link rel="canonical" href.+?">)/';
        $content = preg_replace($pattern, '', $response->getContent());
        $response->setContent($content);
    }
}, \Silex\Application::LATE_EVENT);
```

**Comment by mclucario** [comment]
> When I call any URL via AJAX, also returns this dirty code, this option could help me a lot.
> 
> ```
> <meta name="generator" content="Bolt">
> <link rel="canonical" href="http://ocalhost:3000/listing">
> ```

Yeah I have the same problem.

**Comment by dhalucario** [comment]
> When I call any URL via AJAX, also returns this dirty code, this option could help me a lot.
> 
> ```
> <meta name="generator" content="Bolt">
> <link rel="canonical" href="http://ocalhost:3000/listing">
> ```

For further reference, if you want to send JSON from your controller you can return a JsonResponse instead of Response. Example: 
```
    public function callbackGetManuals(Application $app, Request $request) {
        $myvar = $this->doThings;
        return new JsonResponse($myVar);
    }
```
Further explaination here: https://symfony.com/doc/current/components/http_foundation.html#creating-a-json-response

**Comment by iskyd** [comment]
You can just add in your index.php an after \Silex\Application::LATE_EVENT event and remove those tags:

```php
$app->after(function (\Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response) {
    $path = $request->getPathInfo();
    if(strpos('/fallback', $path) !== null) {
        $pattern = '/(<meta name="generator" content="Bolt">\s?<link rel="canonical" href.+?">)/';
        $content = preg_replace($pattern, '', $response->getContent());
        $response->setContent($content);
    }
}, \Silex\Application::LATE_EVENT);
```
