### ISSUE TITLE
[Extension] AddThis integration, ask for review

### ISSUE THREAD

**Issue by choomz** [bolt/bolt#1634]
Hi there,

We have created a really small extension for AddThis integration inside Bolt templates.
Feel free to review & use it :)

https://github.com/V-labs/VlabsBoltAddThis

Cheers

**Comment by bobdenotter** [comment]
Please update your extenion for Bolt 2.0, and add it to extensions.bolt.cm if you haven't yet. 

See the docs on how to proceed:  https://docs.bolt.cm/extensions/config
