### ISSUE TITLE
[Extension] Google group integration, ask for review

### ISSUE THREAD

**Issue by choomz** [bolt/bolt#1635]
Hi there,

We have created a small extension to embed google groups as an iframe inside your bolt templates.

Feel free to use it :-)

https://github.com/V-labs/VlabsBoltGoogleGroup

Cheers,

**Comment by bobdenotter** [comment]
Please update your extenion for Bolt 2.0, and add it to extensions.bolt.cm if you haven't yet. 

See the docs on how to proceed:  https://docs.bolt.cm/extensions/config
