### ISSUE TITLE
Image uploaded in an entry but displayed thumbnail is "ERROR"

### ISSUE THREAD

**Issue by taylorren** [bolt/bolt#1695]
I created an entry in bolt and uploaded an image "IMG_1331.jpg". The thumbnail is an "ERROR" but clicking on the thumbnail gives me the correct large picture. 
![ashampoo_snap_2014 09 05_07h20m26s_002_ - -- -- - cms - mozilla firefox](https://cloud.githubusercontent.com/assets/3853711/4158289/2551b6b0-348a-11e4-87e7-64155587b9f3.png)

**Comment by bobdenotter** [comment]
We've rewritten the entire thumbnail library, so i wager this is fixed now.

Closing this, but if you feel this is still an issue, feel free to re-open it.
