### ISSUE TITLE
[RFE] Ability to get multiple contenttypes using {% setcontent %}

### ISSUE THREAD

**Issue by andyjessop** [bolt/bolt#1721]
Ability to get multiple contenttypes using `{% setcontent %}`, perhaps using taxonomies.

I can't find this anywhere in the docs, but for example, I have two contenttypes that both come under the taxonomy "event" - I need to have a way to create a list containing both contenttypes in chronological order.

**Comment by fredaffini** [comment]
raising from the deads....

Is this feature planned for any future release?

**Comment by bobdenotter** [comment]
This is something we'd still like, but not very high on the priority list. 

If this is something you need, and are willing to put the time into implementing it, we'll happily help you get started on it. :-)

**Comment by SahAssar** [comment]
This is actually already implemented, like this: `{% setcontent results = '(pages,entries)' orderby '-datepublish' limit 5 %}`

**Comment by bobdenotter** [comment]
Hmm, then we should probably document that here: https://docs.bolt.cm/3.0/templates/content-fetching

**Comment by SahAssar** [comment]
It's sorta implied here: https://docs.bolt.cm/3.0/templates/content-search#code-setcontent-code-search but getting it properly documented would be very good :)

**Comment by rossriley** [comment]
Note that in the current implementation the multiple contenttypes only works on search, and not on normal `setcontent` queries.

In the new storage layer, this distinction is removed and multiple contenttypes will work in any query, not just search, but this won't work in twig `setcontent` queries until we switch from legacy to the new storage layer.

If you can use PHP code, ie do the fetch in your controller then you can force use the new system by doing `$app['query']->getContent('(pages,entries)/latest/10', [])` where the second array is a parameter of normal options... eg where, orderby etc.

Be warned that if you do use this then whilst you should get the correct rows back, the format returned from the new storage system may be very slightly different to the current implementation.

**Comment by SahAssar** [comment]
rossriley: really? cause that example I posted worked, and that's not a search query, right? It didn't work with `latest/5` though, that's why I did the limit manually.

**Comment by rossriley** [comment]
@SahAssar Intersting if that is the case, I'm sure when I first started porting it didn't work, but maybe it did and was just never documented.

**Comment by fredaffini** [comment]
I'm running Bolt 3.0. I can do some quick tests using @SahAssar suggestion so we can properly document it.
