### ISSUE TITLE
pager for taxonomy does stays at first page 

### ISSUE THREAD

**Issue by ArdKuijpers** [bolt/bolt#1725]
The pager for taxonomy emits the wrong hrefs. For example with tags, currently `pager()` emits: `http://[domain]/tags/<tagname>?page_tags.<tagname>=2`. But this doesn't bring me to page two. I found out that `http://[domain]/tags/<tagname>?page=2` does bring me to the second page.

This problem also occurs with other taxonomies (e.g. categories).

**Comment by mr-klaatu** [comment]
This seems to have returned...

1. http://bolt/categories/accommodation?page_category_accommodation=2 : FAILED - 1st page showing

2. http://bolt/categories/accommodation?page=2 : SUCCESS - paging works as expected.

The pager only generates the 1st type of link, so paging fails for me.

I am using Bolt V2.02
