### ISSUE TITLE
content types in extensions

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#1758]
I understand that is probably not the direction we want to take, but I can not help propose, it is very convenient for webmasters and even makes it easier to write extensions.

The idea is that each extension has its optionally "contenttype.yml" bolt and display it as a content type anymore, so something in app / src / Bolt / config.php.
You Sorry for my poor coding:

```php
foreach ($extensionList as $ext){

        $fileWay = $this->app['resources']->getPath('app').'/config/extensions/'.$ext.'/contenttypes.yml';
        $myTemp = $this->parseConfigYaml($fileWay, array(), false);

            if (!empty($myTemp)){
            $tempContentTypes = array_merge_recursive_distinct($tempContentTypes, $myTemp);
            }

        }
```
An advantage I can mention that this encourages you to keep visual consistency Bolt, the downside would be that in the first niver appear on the menu (though that's fixable).

For example: I created a shopping easy shopping and this allowed me to only have to create the driver for POST and SQL inserts orders should not have to worry about the integrity of the database or the templating on the backend, since the view content (products and orders) handled the bolt.
Also allowed me to easily add fields to request.

Sorry if I'm wasting your time.
With respect, an enthusiastic of Bolt. (^_^)/

**Comment by bobdenotter** [comment]
Ok, I'm going to call this as "wontfix" now. Adding _contenttypes_ in extensions will severely complicate the model of "simple" contenttypes, and is considered out of scope. 

You _can_ add custom fields in extensions, though. ;-)
