### ISSUE TITLE
[RFC] Eliminate strict_variables setting

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1797]
Having the ``strict_variables`` setting does more harm than good. It makes no sense to have a setting, that starts to break things, when just on one place something was checked in with this setting set to false.

It's quite easy with twigs ``default()`` filter to circumvent unset variables, so why not force strict variables all the time.

One setting less, one source of problems less, one step more k.i.s.s.

**Comment by bobdenotter** [comment]
BDFL says no.
