### ISSUE TITLE
[RFC] Title field

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1812]
At the moment the title field is not treated a html field rather than a text field and so in the backend outputted as raw. This is probably used by some to format the title, otherwise can cause problems inserting characters with special html meaning or different output in backend and frontend as the template author possibly does not know about the special treatment of the title field.

Also the field used as title is guessed at he moment.

_My proposal:_

1. Let the behavior for backward compatiblity as is if 2. is not present
2. Add two new field types:
 - ``type: title-html``
 - ``type: title-text``
3. Treat the new types in the backend respectively (raw or escape).
 - ``title-text`` is edited in a text field
 - ``title-html`` is edited with a special CK-Editor, that only allows a specific set of options (no block tags, and only a defined set of non block level tags, perhaps definable in options)
4. Deprecate having no defined title field for 3.0
5. Remove ``Content::getTitleColumnName()`` and replace with defined behavior for 3.0

[PS: there's a similar issue if tags in exerpt()]

**Comment by bobdenotter** [comment]
Let's leace this as-is.
