### ISSUE TITLE
Feature Request: Labels for contenttype taxonomies

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1832]
I was thinking if possible it would be good to have a label per taxonomy when assigning them to contenttypes. In my current project I have a taxonomy which I use with a few contenttypes. The actual implementation (meaning) for it varies per contenttype so it would be good if I had a way of explaining this in the admin system via a custom label.

Maybe in future taxonomies could be added in a similar fashion to relations.

**Comment by SahAssar** [comment]
Reopening this as this is something that I'd like to see in bolt and was reported as an issue by nealmarques on IRC.

**Comment by SahAssar** [comment]
I'm going to close this again... Sorry, but I just haven't had the time, and this does not exactly seem like an active/requested enhancement. If it comes up in the future or if anyone PR's a fix that'd be very welcome. :)
