### ISSUE TITLE
Force LF line endings

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1851]
As discussed on IRC I suggest changing ``* text=auto`` to ``* text eol=lf`` in ``.gitattributes`` to hopefully solve line ending problems finally as described in "[Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/)"

**Comment by bobdenotter** [comment]
This is fixed, right? 

Closing this, but if you feel this is still an issue, feel free to re-open it.

**Comment by rarila** [comment]
Still an issue: #2393 :-(

**Comment by rarila** [comment]
In this case I guess it has to to with new grunt-sass using libsass…

**Comment by bobdenotter** [comment]
@rarila Can this one be closed? We :fire: all the `\CR`, right?

**Comment by rarila** [comment]
Hopefully!

**Comment by bobdenotter** [comment]
Cool, closing then! #springcleaning
