### ISSUE TITLE
contentsCss is initialized with non existing file

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1877]
In ``Config::setCKPath()`` and ``Config::setDefaults()`` contentsCss is initialized with ``'view/css/ckeditor.css'``, but the file doesn't exists. So an error is triggered in the browser console.

So we should either remove this entry, add an empty file or check for its existance before adding.

Don't know what it's for, but I make an educated guess that there must be somone here who knows :-)

**Comment by bobdenotter** [comment]
Old issue, closing.
