### ISSUE TITLE
Updating page/record content in extension

### ISSUE THREAD

**Issue by phazen** [bolt/bolt#1905]
I'm trying to create an extension that will update the content of a page before a template file shows it. Maybe it's my lack of silex experience but I'm stuck on how to actually update the variable:

The basics of what I'm trying to do:

      function initialize() {

        $this->app->after(array($this, "updateContent"), 1);

       }

       function updateContent()  {

           $record = $this->getRecord(); // returns $this->app['twig']->getGlobals('record') if found

           if(!empty( $record->values['body'] ) ) {
            $record->values['body'] = str_replace("[token]", "token replacement text", $record->values['body']);

            return $record; // update app['twig'] global var 'record'?
           }

        }

Any pointers on what I should be doing in order to update the global record variable?

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
