### ISSUE TITLE
[RFC] Dispatchers & listeners

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#1914]
@bobdenotter raised the topic of event handlers at BoltCamp.

The vision being that extensions should be able to interface with core Bolt events and respond accordingly.

Location suggestions welcome ;-)

### Suggestions
* Asset creation
* Field type values, e.g. select fields

**Comment by GawainLynch** [comment]
Moving this to the new [forums](https://discuss.bolt.cm/d/9-dispatchers-listeners)

**Comment by GDmac** [comment]
The hasListeners is mostly useful when it might be costly to setup an event object

```php
$data = '';
if ($app['dispatcher']->hasListeners('content_edit.load')) {
    $event = new CostlyEventObject();
    // give data to listeners
    $event->setData($data)
    // listeners might modify data
    $event = $app['dispatcher']->dispatch('my.event', $event);
    // so, retrieve modified data
    $data = $event->getData();
}
// continue normal operation
// $data ....
```
