### ISSUE TITLE
from pivotx/pivot flatfile database content to bolt

### ISSUE THREAD

**Issue by jult** [bolt/bolt#1945]
Would be grand to have an easy to use import script of some sort.. I know there's this;
http://forum.pivotx.net/viewtopic.php?f=17&t=3578&start=10
but still, seems to me the target dev is the place for this.

**Comment by bobdenotter** [comment]
The importWXR extension works well, now. The exporter in PivotX has been upated too..

Closing this, but if you feel this is still an issue, feel free to re-open it.

**Comment by jult** [comment]
The exporter in PivotX, do you have a link for that? Also, what if you don't have a pivotx site active, but still have the /db/ folder and its contents in tact? Is it required to repair pivotx before doing an export? I ask this since it is broken in nginx php-fpm over TLS, it's pretty hard to get a functional pivotx in https with nginx.

**Comment by tobias2k** [comment]
How about running a pivotx on a dev server and importing the /db into
that, then exporting from there?

On Mon, Feb 09, 2015 at 05:51:27AM -0800, Julius Thyssen wrote:
> The exporter in PivotX, do you have a link for that? Also, what if you don't have a pivotx site active, but still have the /db/ folder and its contents in tact? Is it required to repair pivotx before doing an export? I ask this since it is broken in nginx php-fpm over TLS, it's pretty hard to get a functional pivotx in https with nginx.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/1945#issuecomment-73511084

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by jult** [comment]
Sure, but I've learned that "importing the /db" isn't quite the easy plug and play thing to do, if server-config is different from the original.

**Comment by jult** [comment]
Tried the WXR Eport extension (version 0.1 from 2013-05-21) but it doesn't let me change its config (I see the screen flash by after pressing 'edit configuration'). This is in latest pivotx with fully functional db etc. Any ideas?
