### ISSUE TITLE
Selective extension loading

### ISSUE THREAD

**Issue by phazen** [bolt/bolt#1952]
I was curious if it's possible to selectively load extensions based on contentTypes and/or Taxonomy. Can this be done with the current setup in Bolt2? 

If not, I would *love* to see this kind of feature added to Bolt. Maybe adding an optional field in composer.json for extensions where we can declare which contentTypes will load the extension. 

Maybe something like this added to composer:

       "selective_loading": [{"Pages", "Kitchensink" }
       ],

And then the extension would only run on those contentTypes

**Comment by bobdenotter** [comment]
Nope. Extensions should be built to be "silent" when not applicable.

This would give way to a _LOT_ more complexity? would the extensions be loaded in the backend? What if it's defined as a contenttype that gets fetched on `{% setcontent %}` in a sidebar, or as a 'related' item. 
The benefits of this will not outweigh the added complexity.
