### ISSUE TITLE
 behavior at login

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#1979]
I want to suggest a feature, when you access a link that leads to the backend (or a screen extender requesting login), if you have not logged in will lead to the screen login after putting corresponding username and password leads us to overview the backend, never take us where the link pointed we follow.

It would be great to store the destination url and send us the loguearnos there.

improve the experience when putting links to edit the content in the frontend and enhance integration with extensions that we need logged.

**Comment by bobdenotter** [comment]
Bolt already does this. Closing this, but if you feel this is still an issue, feel free to re-open it.
