### ISSUE TITLE
view permissions problem?

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2021]
From my understanding the following entry
```
contenttypes:
    kitchensink:
       view: [ owner ]
```
in permissions.yml should list all kitchensinks the logged in user owns. Instead the kitchensink entry in the menu disappears and no list at all is shown. Is the the intended behavior or is that a bug?

**Comment by bobdenotter** [comment]
Is this actionable? If so, please self-assign, if you'd like to work on it.

**Comment by bobdenotter** [comment]
No reply in two months, closing! Feel free to re-open, if you feel this is still an issue, and it should be worked on. :-)
