### ISSUE TITLE
[RFC] feature - overview filter / sort / etc.

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2046]
Some thoughts on being able to filter and search more detailed in the backend.
Optionally even store some filters for re-use.
![bolt-rfc-overview-filters](https://cloud.githubusercontent.com/assets/156334/4871184/ffcb37e6-61a1-11e4-95e0-de9ad43c3b09.png)

**Comment by bobdenotter** [comment]
This has been brought up a few times. Going to leave this one open, as it has nice mockups. 

Also, the filters should be in the sidebar. Not at the top.

**Comment by bobdenotter** [comment]
By the way, what are the odds? 1023 * 2 = 2046.. Did you do this on purpose? ;-)

**Comment by rarila** [comment]
Wait for #3069…

**Comment by Pinpickle** [comment]
I've been wishing for this for a while, and I think it may be good to take to [Keystone](http://keystonejs.com) for inspiration. Their filter system in the backend is really powerful

![image](https://cloud.githubusercontent.com/assets/3238878/8792706/ea6f6fc0-2fbe-11e5-99db-c668149a3bbf.png)

Each field can expose a filter and you can add them as you see fit. This way, you won't clog up the UI by including every possible field to filter on at the top of a listing.

Implementation shouldn't need to be too complex now that we have a class for every field. Here's what I'm thinking

- A field has a method, `canFilter` which will return true if it makes sense to filter by this field. It makes sense to filter by a date, but not by an image. This will dictate what appears in the "add filter" dropdown
- A field has a template (as well as its editcontent template) that is the filter template. For example, it has the "after/before" buttons. Everything relevant ends up in a form which will go to the controller
- The controller initially splits up all of the separate field filters, and sends the appropriate parameters to the field's `generateFilterQuery` method, which will add the appropriate `WHERE` stuff to a query builder with the parameters it is given.
- The controller serves the results based on the query

**Comment by rarila** [comment]
@bobdenotter let's  have a look in my crystal ball… :crystal_ball: 

>Pull request "#4092 Implemented overview filter / sort / etc."

;-)

**Comment by Mariyo** [comment]
Hi all,

I propose to start think, how to rewrite this Legacy\Storage method https://github.com/bolt/bolt/blob/release/3.1/src/Legacy/Storage.php#L1811-L1817 and hardcoded SQL statement in it:
~~~
$statement = sprintf(
                'SELECT %s.* %s %s %s',
                $query['tablename'],
                $query['from'],
                $query['where'],
                $query['order']
            );
~~~

I would rewrite it by Doctrine\DBAL\Query\QueryBuilder and add possibility to filter that query or filter arguments going to statement. Generated query by Doctrine Query Builder can be filtered before execution by some event, which can be affected in custom Extension.

Than I think, it does not matter, how will overview filter looks like, cause there will be space to start build varied Extensions from which could final users choose :)

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue soon. That is, unless somebody steps up to help out with implementing it, in which case we'll leave it open until the feature is finished. 

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
