### ISSUE TITLE
2.0 Beta: Colours for activity log

### ISSUE THREAD

**Issue by DevonshireCow** [bolt/bolt#2057]
When looking down the activity log, it's difficult to tell from a glance the creation of new content, the editing of said content, and errors which have occurred, so how about adding a status int to each log item from which when shown, the log can take on different colours for easier visual parsing.

**Comment by bobdenotter** [comment]
I'll take this one on.

**Comment by GawainLynch** [comment]
@bobdenotter I have a whole [new feature branch](https://github.com/GawainLynch/bolt/compare/feature/monolog) incoming for the logger...  Can we coordinate?

**Comment by bobdenotter** [comment]
Sure! I wasn't going to jump on this right away. :-)

**Comment by rarila** [comment]
@GawainLynch when can we expect it to hit?

**Comment by GawainLynch** [comment]
I was waiting until I got back to the EU, circa 12th.  It should be good to go as-is, but I wanted to have a discussion (when Ross is back too) on a finalised approach.

**Comment by rarila** [comment]
@GawainLynch is this just for internal event logging or does this make monolog useable for dump/krumo so that these can be redirected to eg. Firebug?

**Comment by GawainLynch** [comment]
Currently there are logging interfaces for:
* Record changes `$app['logger.change']`
* Internal system events `$app['logger.system']`
* Silex event debugging `$app['monolog']` (standard out-of-the-box Monolog for Silex)

**Comment by rarila** [comment]
@GawainLynch Is a ´´dump()´´/´´krumo()´´ refactoring planned so we can get their output somewhere not in html?

**Comment by GawainLynch** [comment]
Well that sort of thing is what I wanted to discuss with everyone...  Monolog comes with the FirePHPHandler handler class, so it is a trivial addition.

**Comment by rarila** [comment]
So it's weekend, nothing to do in the land of nowhere except squashing empty beer cans … ;-)

**Comment by GawainLynch** [comment]
Tagging #693 so I won't lose this!

**Comment by GawainLynch** [comment]
Change log handling has been redone for 2.1-aplha
