### ISSUE TITLE
[RFE] Use require.js to manage javascript includes

### ISSUE THREAD

**Issue by tobias2k** [bolt/bolt#2109]
See #1030.

**Goal**: clean up the mess that is Bolt's current javascript inclusion
management, and provide a sane framework for require.js-based script loading.
This takes care of:

* loading javascript files on-the-fly, as needed
* modularity
* avoiding duplicate includes
* avoiding version conflicts (different versions of the same module can
  coexist)

**How to get there**.

The first thing we'll need is a generated requirejs configuration. Because
require.js uses JSON for its configuration, this is a matter of keeping a list
of javascript includes, massaging it into the right format, json_encode()ing
it, and serving it as a javascript file. Since that file will also act as our
main js entry point, it will also need to contain some bootstrapping
boilerplate. Requirejs doesn't run anything but the main entry point directly,
so when things register scripts, they need a way to hook themselves into the
main entry point. This can be done by generating a list of calls in the
generated main.js directly, or we can just generate a simple list of modules
that expect to be hooked up, and then the hard-coded bootstrapping part would
go through that list and set up all the hooks. This is what I imagine the
generated main.js might look like:

    requirejs.config({
        // json dump of config as collected by Bolt's javascript manager, e.g.:
        paths: {
            app: '/js/app',
            extensions: '/js/extensions'
        }
        // etc. yadda yadda

    });

    (function(){
        var __startup_scripts = [
            // json dump of the module names of all the modules that have
            // registered themselves as having a startup hook, e.g.:
            'foobar',
            'baz'
        ];

        require(__startup_scripts, function(){
            // Using 'magic' arguments array here so we can just iterate over
            // the required modules.
            // Note that all entry point modules are loaded asynchronously (and
            // thus in parallel) before the iteration begins; order of
            // execution, however, is determined by the order in which they are
            // declared.
            var modules = arguments;
            for (var i = 0; i < modules.length; ++i) {
                modules[i].run();
            }
        });
    )();

This script needs to be generated on the fly, and hooked up to a silex route;
we probably need separate routes for frontend and backend, because the frontend
is going to use a different set of scripts than the backend.

Then we need a few routines in the JS manager to register scripts in various
ways, most importantly:

* require-aware entry point (to be added to the startup scripts, and
  facilitated in the require config with the assumption that it is an AMD
  module)
* require-aware module (only added to require config)
* non-AMD script with extra options controlling import behavior. This is needed
  for scripts that aren't AMD aware, or that don't play 100% nice with AMD
  (such as jQuery).

We also need to distinguish between frontend- and backend scripts here, either
by passing an extra parameter to the registration methods, or by having two
completely independent script managers.

The final bit we need is something that injects a `<script>` tag into our page to
bootstrap require.js; this is pretty much a one-liner, but it needs to be
somewhat dynamic in that it needs to point to the correct URL for require.js
and main.js. Not rocket science though.

Finally, existing javascript will need to be converted, or we need to come up
with some sort of compatibility shimming to keep those scripts working.

**Comment by bobdenotter** [comment]
Let's not forget that the same applies to CSS loading, and RequireJS does not support CSS.. IMHO that would make RequireJS less than ideal. We should get one solution that will fix this for both JS and CSS

**Comment by GeoDom** [comment]
I don't know if this is closed.
How about a php task-runner like Taskphp [http://taskphp.github.io/ ] or Robo [http://codegyre.github.io/Robo/tasks/Assets/] ? 
That way there is no need for Grunt or Gulp. Maybe port as a bolt extension ?
That way bolt community can avoid this: https://www.happyassassin.net/2014/12/29/adventures-in-php-web-asset-minimization/

**Comment by tobias2k** [comment]
> Let's not forget that the same applies to CSS loading, and RequireJS does not support CSS.. IMHO that would make RequireJS less than ideal. We should get one solution that will fix this for both JS and CSS

It's not really the same problem though.

Requirejs addresses the fact that browser-based JS implementations provide insufficient support for modular code and lazy-loading includes. Assetic provides a framework for managing and pre-processing static assets. There are contact points between the two areas, but they are really separate problems.

**Comment by tobias2k** [comment]
> How about a php task-runner like Taskphp [http://taskphp.github.io/ ] or Robo [http://codegyre.github.io/Robo/tasks/Assets/] ?

This is basically grunt implemented in PHP; I don't see a significant advantage there, and meanwhile grunt enjoys a much larger user base...

**Comment by GeoDom** [comment]
That was an answer for bobdenotter  : [Let's not forget that the same applies to CSS loading, and RequireJS does not support CSS.. IMHO that would make RequireJS less than ideal. We should get one solution that will fix this for both JS and CSS]. Sorry for that

**Comment by bobdenotter** [comment]
This one supports CSS as well: http://webpack.github.io/

**Comment by cdowdy** [comment]
> This one supports CSS as well: http://webpack.github.io/  

The only issue I see with webpack is if you were to give this functionality to template/theme authors, extension authors or even the end user who edits their own temples then node js / iojs become a dependency for everyone to install on their server (I'm not overtly familiar with webpack but this is my understanding... Am I wrong?). Once a file were to change the whole this would probably need to be rebuilt it it affects something higher/lower in the chain (ie JavaScript  and jquery order)    

Which is why I mentioned assetic. It's php. Does js,CSS, images cache busting all this stuff we are talking about and if you're advanced enough to know you have imagmagick on your system you can enable it through a yaml setting

**Comment by SahAssar** [comment]
Tagging this for closing on the 8th if no more info comes in since it's been stagnant for a year and no real progress. If anyone feels it would be productive to open the discussion after that feel free to reopen the issue!

**Comment by SahAssar** [comment]
Closing per my comment on the 5th. Feel free to reopen if anyone feels productive in this area :)
