### ISSUE TITLE
Better Extension access for getContent()

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#2129]
There's a slightly unintuitive situation at the moment where it's impossible to call $app['storage']->getContent() in the initialize() block of an extension. 

It seems that there's an unnecessary call to $this->app['request'] in the organizeQueryParameters() method, and this throws an exception if you call storage->getContent() before the $app->run() has taken place.

Ideally we should make sure that the Storage class works independently from the http request, but if not then we could perhaps formalise a workaround for use by extension devs.

For example @GawainLynch has a workaround in use here: https://github.com/GawainLynch/bolt-extension-opengraph/blob/master/Extension.php

**Comment by bobdenotter** [comment]
Should go hand in hand with #691

**Comment by GDmac** [comment]
> becomes an academic debate
Initialise is called on EVERY request, including front-end, nothing academic about that.
I think it gets time to look into the dispatcher functionality #1914 to call out for action and hooks

**Comment by GawainLynch** [comment]
> nothing academic about that.

If you read what I wrote in the preceding sentence, you'll see it is at the point that I defined it.

**Comment by GDmac** [comment]
Ok, sorry. I also like ross' suggestion: "make sure that the Storage class works independently from the http request". This effort could go hand in hand with modularisation of user and permission classes, fields, etc.

**Comment by GawainLynch** [comment]
This close-worth now @rossriley?

**Comment by rossriley** [comment]
yes
