### ISSUE TITLE
Better Path Composition

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#2140]
At the moment there's quite a few places where we are using code like this... `$app['resources']->getPath('rootpath') . 'src'`

Since we now have the path library built into the ResourceManager I'd suggest that we bake this functionality into the class itself so that we standardise path management.

Suggesting the following syntax instead: `$app['resources']->getPath('rootpath/src')` or `$app['resources']->getPath('extensions/local')`

**Comment by CarsonF** [comment]
Closed?

**Comment by rossriley** [comment]
Closed
