### ISSUE TITLE
[RFE] Including psr0 in our extension autoloading mechanism

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#2142]
Currently we are including `autoload_psr4.php`, `autoload_classmap.php` and `autoload_files.php` in `Extension::autoload()` therefore any extension that has a dependent package that defines psr0 loading, it won't be loaded automatically. As we touched the issue on IRC it worth to be included, moreover it can be simplify the code result too with just fetch `autoload.php`.
Thoughts?

**Comment by bobdenotter** [comment]
Is this still an issue?

**Comment by GawainLynch** [comment]
Yes

**Comment by rossriley** [comment]
Adding this as a reminder. There's a duplicate class bug triggered when installer.php gets included via the autoload_files.

**Comment by bobdenotter** [comment]
Sooo... who's going to fix this? ;-)

**Comment by rossriley** [comment]
What's everyone's thoughts. If we are going to support PSR-0 then we can just include the autoload.php file. The other idea was to find some way to get rid of the separation between standard and local extensions, which although I initially wasn't keen on, it seems it's a well used pattern so I think we should support them as first class citizens within Bolt.

If we do, then the ideal solution would be to pass autoloading responsibility out of Extensions.php and into the extension base class, BaseExtension where the autoloading can be handled either by loading baseDir /vendor/autoload.php or in the case of a local extension using the file path introspection currently used in Extensions::localload.

**Comment by GawainLynch** [comment]
We could probably to just including `extensions/vendor/autoload.php` as a first step. I will solve the PSR-0 loading.

I like the idea of making the local extensions first class citizens, and looked at it for 2.1 but backed off as my approach was initially to get Composer to build autoloaders for local extensions but at that time we were on Composer alpha9 and it was missing bits.

The other side to the coin is that we currently have a tangled web of loading and initialising that @CarsonF and I [hashed over recently](https://github.com/bolt/bolt/wiki/Bolt-2.x-Refactoring#extensions) with the near-breaking changes to the client IP stuff. (#3031 & #3093), that we probably should look at as part of this. But if you think your suggestion covers that approach too: :+1:

**Comment by jadwigo** [comment]
@rossriley / @bobdenotter  I think I've hit the duplicate installer class lots of times - when deploying from git to engineyard

```
PHP Fatal error:  Cannot redeclare class Bolt\Composer\ExtensionInstaller in /{path redacted}/extensions/installer.php on line 5
```

Usually the error goes away after a cache clear and / or some page refreshes

It's a bolt 2.2.8 site still, so it might be fixed already in later versions.

**Comment by GawainLynch** [comment]
That is a site that has been upgraded from <2.2.0 as I migrated that installer into a class that is now added to the extension's autoloader.

**Comment by rossriley** [comment]
This one can pretty much be retired now, the new extension loading mechanism will supercede the default autoloaders.
