### ISSUE TITLE
Manually changed publication date not saved

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#2152]
When I try to change the publication date of a newsitem, the date is not saved, but instead set to the current date and time. (you can only see that when you refresh the page in FF)

It may or may not be related with the jQuery UI calendar and showing a 'written' date in the date field?

Error occurs at least on FF33 and Chrome38 (and the browser of my client, possibly IE10)
Bolt 1.6.12

It may be related to a similar issue (posted by me as well) from a couple of months back, but I don't know how to search for that one.

**Comment by errskipower** [comment]
I'm using Bolt 2.2.0 and still having this issue.
