### ISSUE TITLE
Interference between extensions?

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#2174]
I noticed that one extension won't load when another extension is loaded and vice versa. It's RSS Aggregator and Autolink. They both work separately, though. Think it's strange, but might it be because the functions Initialize and getName are public? That's the only thing I can think of. The extensions are quite similar, but they have different names in all relevant places so they shouldn't interfer.

Using beta 4.

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by GawainLynch** [comment]
Not one that we can fix specifically.  With extensions tagged and stability requirement moved off dev this doesn't affect standard users.  We *might* be wanting to look at better UI interaction in the future, but that should be a separate issue.
