### ISSUE TITLE
Want to report a Security Issue 

### ISSUE THREAD

**Issue by narendrabhati** [bolt/bolt#2197]
Hey ,
Can you provide me your email , want to report some of security issues along with bypasses 
dont want to disclosure here !

**Comment by bobdenotter** [comment]
Closing this one. One issue has been fixed, one couldn't be reproduced, and the third was "Not a bug, but a feature".

**Comment by narendrabhati** [comment]
hey bro ,

i am not talking about the stored xss attack ,
i am talking about the csrf attack , did you are also talking about the
same as feature !

On Sat, Jan 3, 2015 at 4:21 PM, Bob den Otter <notifications@github.com>
wrote:

> Closed #2197 <https://github.com/bolt/bolt/issues/2197>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bolt/bolt/issues/2197#event-213651199>.
>



-- 
*Narendra Bhati "CEH" **( Facebook
<http://www.facebook.com/narendradewsoft> , Twitter
<http://www.twitter.com/NarendraBhatiB> , LinkedIn
<https://www.linkedin.com/profile/view?id=115146074> , Personal Blog
<http://hacktivity.websecgeeks.com> )*
*Security Analyst - IT Risk & Security Management Services*
Suma Soft Pvt. Ltd. | Suma Center | Near Mangeshkar Hospital | Erandawane
Pune: 411004 | *+919923397301*

*======================================================================*

**Comment by narendrabhati** [comment]
Did you mention this update about iframe preventing in any security release ?

**Comment by GawainLynch** [comment]
https://github.com/bolt/bolt/commit/3f1b488f981c01c18e76f91273f6eab9119cd835

**Comment by narendrabhati** [comment]
Thanks !
