### ISSUE TITLE
Config getWhichEnd not working for backend with bolt in a subfolder and url rewriting

### ISSUE THREAD

**Issue by leup** [bolt/bolt#2214]
Ok, really bad title and I have a weird setup for my website.

Let me explain the context. I have a webfolder (DocumentRoot) named `www` in my user dir, this `www` folder contains a LOT of subfolders. To avoid mixing the bolt folders with them and because of legacy constraints I put my bolt website within its own subfolder (let's call it `/www/myboltsite`). 

Note, my bolt website is setup via composer based on this:
https://github.com/rossriley/bolt-composer-webroot/

So my folder hierarchy is:
```
/userdir/www/
|- .htaccess     (which redirects to /myboltsite/web/)
|- /myboltsite/
|--- app/
|--- extensions/
|--- vendor/
|--- web/          (<- public folder where lies the index.php and bolt .htaccess file)
```

In my `/userdir/www` folder I have an .htaccess which redirects input to the bolt site except for existing files and directories, like this:
```
<IfModule mod_rewrite.c>
  RewriteEngine on
# Not sure if this is really needed
  RewriteBase /myboltsite/web/

  RewriteRule ^$ /myboltsite/web/ [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ /myboltsite/web/$1 [L]
</IfModule>
```

With this setup, whenever I try to access the /bolt backend I have a Twig template error "template %s not defined".

This is because the `getWhichEnd` method from the `vendor\bolt\bolt\src\Config.php` [class](https://github.com/bolt/bolt/blob/master/src/Config.php#L873) return the end as 'frontend' instead of 'backend'.
This happens on these lines:
```
$scriptdirname = '#' . str_replace("\\", "/", dirname($scriptname));
$scripturi = str_replace($scriptdirname, '', '#' . $_SERVER['REQUEST_URI']);
// make sure it starts with '/', like our mountpoint.
if (empty($scripturi) || ($scripturi[0] != '/')) {
    $scripturi = '/' . $scripturi;
}

// If the request URI starts with '/bolt' or '/async' in the URL, we assume we're in the backend or in async.
if ((substr($scripturi, 0, strlen($mountpoint)) == $mountpoint)) {
    $end = 'backend';
} elseif ((substr($scripturi, 0, 6) == 'async/') || (strpos($scripturi, '/async/') !== false)) {
    $end = 'async';
} else {
    $end = 'frontend';
}
```
Problem is when trying to access `/bolt`uri then $scriptdirname is `#/myboltsite/web`, $scripturi then is `/#/bolt` and the test `if ((substr($scripturi, 0, strlen($mountpoint)) == $mountpoint))` fails.

```
$scriptdirname = '#' . str_replace("\\", "/", dirname($scriptname));
//>> with $scriptname = '/myboltsite/web/index.php'
//>> then $scriptdirname = '#/myboltsite/web'
$scripturi = str_replace($scriptdirname, '', '#' . $_SERVER['REQUEST_URI']);
//>> with $_SERVER['REQUEST_URI'] = '/bolt/'
//>> then $scripturi = '#/bolt/'

if (empty($scripturi) || ($scripturi[0] != '/')) {
    $scripturi = '/' . $scripturi;
}
//>> $scripturi = '/#/bolt/'

// If the request URI starts with '/bolt' or '/async' in the URL, we assume we're in the backend or in async.
//>> $mountpoint = '/bolt/
if ((substr($scripturi, 0, strlen($mountpoint)) == $mountpoint)) { //<= /#/bolt/ != /bolt/, test FAILS
    $end = 'backend';
} elseif ((substr($scripturi, 0, 6) == 'async/') || (strpos($scripturi, '/async/') !== false)) {
    $end = 'async';
} else {
    $end = 'frontend';
}
```

To prevent that I have added a test to check if $scripturi begins with a '#'. If so, remove it.

```
$scriptdirname = '#' . str_replace("\\", "/", dirname($scriptname));
$scripturi = str_replace($scriptdirname, '', '#' . $_SERVER['REQUEST_URI']);
if (!empty($scripturi) && $scripturi[0] === '#') {
    $scripturi = substr($scripturi, 1);
}
// make sure it starts with '/', like our mountpoint.
if (empty($scripturi) || ($scripturi[0] != '/')) {
    $scripturi = '/' . $scripturi;
}
```

As I am not sure this is the right way to solve this, I don't do a PR. In fact I am pretty sure there is another better way to do this.

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by leup** [comment]
I changed my setup to avoid this issue, so I don't know what's the status on this one.

**Comment by GDmac** [comment]
This is not something Bolt should "actively" support.
If you drop out a directory segment out of the path, it gets very difficult to maintain.
More important, it is something that should be handled by symfony request object.

**Comment by CarsonF** [comment]
I'm working on this. Not sure what @leup or @GDmac are trying to do, but this is the result "doing it wrong". Routes should state which "end" they are for, not use "inspection/reflection" to figure it out, which is basically what getWhichEnd is doing.

**Comment by bobdenotter** [comment]
@CarsonF This has been fixed, right?

**Comment by CarsonF** [comment]
I don't think so. But I might be able to swing a fix today

**Comment by GawainLynch** [comment]
Closing as fixed-ed-ed… Please feel free to re-open if I am wrong :grin:

**Comment by leup** [comment]
Never had the chance to test this anymore so I will have to trust you on this. ;)
