### ISSUE TITLE
Add Validation messages for Ajax forms

### ISSUE THREAD

**Issue by toddvalentine** [bolt/bolt#2223]
I set a minwidth validation on my image uploads and can't figure out a way of returning the error message in the json to the field to give the user notification of why the upload failed. Is this possible without hacking the core? If not, could this be added?

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by GDmac** [comment]
Strictly, image and files do not seem to have html5 constraints available, so no.
IMO this has to be implemented as an extension or the dev could attach some JS to the backend.
When we embark on backend-validation we can look into images/files again ... maybe

**Comment by bobdenotter** [comment]
Work on this has been done by @Pinpickle. See #3123.  Feel free to re-open, if you feel this is still an issue, and it should be worked on. :-)
