### ISSUE TITLE
Feature: openstreetmap in bolt

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2233]
It would be great,  geolocation input and the default template use OpenStreetMap, instead of google maps, it has nothing to envy, the service is desentralizado and there are several apis. 
and most importantly, it's free!

**Comment by SahAssar** [comment]
Closing as part of the current cleaning, but if anyone feels like implementing this it could probably either be done as an extension (as an alternative) or (after some discussion) as a replacement for google maps in bolt.
