### ISSUE TITLE
[RFC] Changing BaseExtension initialize method to be an abstract method

### ISSUE THREAD

**Issue by silentworks** [bolt/bolt#2236]
I am working on an extension and noticed my IDE didn't pick up on the fact that the `initialize` method is required for an extension, after a little digging I realised that the `BaseExtension` class has initialize as an empty method rather than a abstract method.

This seems wrong to me, because its not forced that any class extending BaseExtension should have the initialize method although its an actual requirement. Can I get your thoughts on why this is how it currently is and is there any side effect in changing this now?

https://github.com/bolt/bolt/blob/master/src/BaseExtension.php#L308

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by silentworks** [comment]
Yes its still an issue and yes its actionable. I was waiting on 2.0.0 to be released first, will send a PR in coming weeks.

**Comment by GawainLynch** [comment]
@silentworks we're freezing 2.1-dev in the next couple of days if you want to make that cycle.
