### ISSUE TITLE
Tags/slugs do not support CJK characters (was: "tagging does not support non-english words")

### ISSUE THREAD

**Issue by webching** [bolt/bolt#2247]
i tested it by inputting Chinese words into the tags field.

as the data can not be saved into the table 'bolt_taxonomy'.
i think it is caused by String::slug ..

**Comment by GawainLynch** [comment]
Had a bit of a look at this one with the slugify work I was doing.  The hard part is that th need to be able to transliterate the characters into something that can be used as part of a URI slug.

**Comment by rossriley** [comment]
I'm not sure if it's a related cause but we did look at this in #1283

**Comment by hannesl** [comment]
I'm wondering if this is related to #4123

**Comment by SahAssar** [comment]
I've tested this a bit, and the basic issue is that slugify does not know how to transliterate Chinese/Korean/Japanese characters (as @GawainLynch said). Russian works fine, Greek works fine, so most non-latin-based western languages should be fine. If anyone has an idea for how to get it to work with Chinese/Korean/Japanese that'd be great, but it does not seem like it's an easy/small fix. This needs a fix one way or another.

**Comment by rarila** [comment]
``Transliterator::transliterate()``

**Comment by SahAssar** [comment]
Leaving this here to remind myself to fix this... 

https://gist.github.com/CarsonF/a559e6daefc815e99b7b

**Comment by SahAssar** [comment]
I'm going to close this... Sorry, but I just haven't had the time, and this does not exactly seem like an active/requested enhancement. If it comes up in the future I'll reopen it and try to work on it (time forgiving) or if anyone PR's a fix that'd be very welcome. :)

**Comment by jemont** [comment]
i am sorry to bring this up again, but Spanish accent and German umlaut don't work for me. I can't introduce new tags with non latin characters. I can select them thought if its a tag that was create by bolt 2.x before update. 
it accepts the special character and than skips the vocal and accepts one character more, that is overwritten by all following character while writing. 
I am on bolt 3.1.1 but it happens on 3.0.12 as well.

**Comment by GawainLynch** [comment]
@SahAssar I am in and out today, but can you try and ping me if you have a few minutes … I already know what *one* of the problems is, but fixing it in a minor without breaks would be tricky.
