### ISSUE TITLE
Pager giving wrong results when filtering on taxonomy

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#2249]
When content has listing_records set to 10 in contenttypes.yml and then is listed in template by tag {{ setcontent limit 20 }}, the pager will give wrong results. Pages will be counted with settings  in yml file, and displayd by settings in template, so in this case, last pages will be empty.

Question is, if this is bug. It has some logic in it. But propably pager should respect the current setting in template, overriding the listing_records. For example if I would like to display results paged by number parametr given by user, this would be a problem.

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by lexislav** [comment]
I have updated to 2.0.2 right this moment and Yes, that is still an issue. At least the second one mentioned above

{% setcontent records = 'projects' where { categories: '!Opomíjené památky na internetu' } limit 20 %}

shows incorrect number of pages – shows pages number for all projects, the excluded category should  – but it doesn't – affect the number of pages. See in action here: http://www.nadaceof.cz/projekty

**Comment by SahAssar** [comment]
@lexislav Sorry if this seems repetitive, but is this still an issue?

Just checked your site (http://www.nadaceof.cz/projekty) where it seems to be working. Has this been fixed, or are you using a workaround on that page?

**Comment by lexislav** [comment]
No, it is not an issue any more, at least on this site (there is no workaround).
The site is running 2.1.8 right now.
But I have not done any further testing on paging with taxonomy, so far.

**Comment by SahAssar** [comment]
Closing this then, If the issue reappears we can reopen :)

Thanks for the quick reply, @lexislav!
