### ISSUE TITLE
In "File Management / Uploaded files" the "Upload file" procedure is confusing

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2263]
I was just asked how to upload a file as the "Upload file" is greyed out.  It uses the old-fashioned uploader and needs to be updated inline uploader.

![uploader-buttons](https://cloud.githubusercontent.com/assets/1427081/5281170/4a0a6cd4-7ac8-11e4-92ee-7095ee68d3a3.png)

**Comment by SahAssar** [comment]
Personally I'd like for us to prioritize to fix this for 3.1 (or 3.0 if possible), since it deviates from all the other file upload patterns we use, so I'm tagging this for 3.1.

**Comment by GawainLynch** [comment]
So we're on the verge of releasing 3.3.0-stable and this is still a visual, and logical mess. Adding as a 3.4 blocker.

**Comment by GawainLynch** [comment]
Fixed in #6898
