### ISSUE TITLE
Feature request: create/edit user without options like admin and root

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2264]
I want to grant the chief editor permission to create and edit users. Problem is that the chief editor also has the options 'root' and 'admin' to select for their roles. Isn't a simple solution possible to make 'root' and 'admin' invisible for other users than the root and admin accounts? Now it is a potential threat to give the chief editor permission to create and edit a user, because the chief editor can deactivate the root user or give someone else root access.

**Comment by bobdenotter** [comment]
This has been fixed in 2.1.0. :-)
