### ISSUE TITLE
https://extensions.bolt.cm/ is unreachable.

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2283]
It seems the 'install extensions' screen is b0rken in bolt-2.0.0-beta5pl4.

The message on /bolt/extend/ is: 
https://extensions.bolt.cm/ is unreachable.
Unable to install/update extensions!

The extension log screen and all buttons are inactive.

**Comment by bobdenotter** [comment]
More bumps for @GawainLynch @rossriley

**Comment by GawainLynch** [comment]
I saw something in the API today (can't remember exactly) about using downgraded SSL that I don't think the console app uses... Either way. I flagged it to look at when I get home next week.

**Comment by peterboorsma** [comment]
No problem :)

**Comment by GawainLynch** [comment]
OK, so a fix for this has landed in the `canary` branch (#2503) which will become 2.1.  I'll leave open for testing results from other and eventually @peterboorsma

**Comment by bobdenotter** [comment]
Closing this one. Fixed by gawain for 2.1..
