### ISSUE TITLE
Visual Editor not work in lumia

### ISSUE THREAD

**Issue by padicao2010** [bolt/bolt#2305]
I use bolt-2.0.0-beta4. Maybe it is solved in beta5.

In lumia IE 10, Surfy Browser, of firefox in PC with lumia 625 IE 10 agent, WYSIWYG does not work.

It just show ugly HTML source code without breaklines.

It seems that in lumia environment, it shows
```html
    <textarea class="form-control ckeditor" name="body" style="height: 300px">
        ...
    </textarea>
```
no "display:none", and hasn't get following as firefox with PC agent
```html
    <div id="cke_body" class="cke_1 cke cke_reset cke_chrome cke_editor_body cke_ltr cke_browser_gecko" dir="ltr" role="application" aria-labelledby="cke_body_arialbl" lang="en">
        ...
    </div>
```

**Comment by bobdenotter** [comment]
Closing this, but if you feel this is still an issue, feel free to re-open it.
