### ISSUE TITLE
Images general UI questions (previews)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2306]
Select from server
- [ ] pressing escape doesn't cancel selection process

Image
- [ ] choose from stack doesn't show paths (product1.jpg, product1.jpg)  
    (which notes.doc or example/product1.jpg or specs/product1.jpg is the correct one?)
- [ ] choose from stack, possibly include thumb previews? 
- [ ] No unselect "X" on image fields
- [ ] When unselecting an image the preview stays

Can has previews ? (colorbox like functionality?)
- [x] Preview from within an imagelist thumb?  
  (currently the thumb only is a drag handle for the list)
- [ ] Full preview from the image preview box?

And:
- [ ] changing path of an image field to "foo"  
  e.g. clicking save doesn't update the preview box
- [ ] reloading the entry shows 404.  
  e.g. update preview box after ajaxy save

**Comment by bobdenotter** [comment]
This is quite broad i think. How do you want to handle this? I feel like it should be broken down into more manageable issues. Or, alternatively, how do you see this is "fixed" in a proper way?

**Comment by GDmac** [comment]
Made the list actionable :-)

**Comment by SahAssar** [comment]
I'm at least sure that 'Preview from within an imagelist thumb' is fixed, so checking that. Anything else in this list that is fixed as of now?

**Comment by SahAssar** [comment]
Added "When unselecting an image the preview stays" since @suther ran into this on slack...

**Comment by SahAssar** [comment]
After three years... Who are we kidding.
