### ISSUE TITLE
Changing slug in existing record doesn't update "View (saved version) on site" link

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2308]
### Reproducing
1. Open a saved record, unlock and update the slug and do an in-place save.
2. Click caret next to "Preview" button 
3. Select "View (saved version) on site" link

### Expected Result
Open record with new slug

### Actual Result
A 404 error

**Comment by SahAssar** [comment]
How about we use the id instead of the slug for this?

**Comment by SahAssar** [comment]
Alright, so in 2.3/master we do use the id instead of the slug, so this is strictly a 2.2 issue.

**Comment by bobdenotter** [comment]
These are two different issues. 

> Expected Result: Open record with new slug

This works in 3.0

> `The XSS Auditor refused to execute a script ...`

This was fixed a while ago, by sending the `$response->headers->set('X-XSS-Protection', 0);` header along with the preview.
