### ISSUE TITLE
Incorrect use of YAML file structure

### ISSUE THREAD

**Issue by tobias2k** [bolt/bolt#2323]
Various YAML configuration files, most notably `contenttypes.yml`, use key/value objects in the YAML format, but rely on the ordering of entries in various places (e.g. the order of content types in the backend menu, the order of fields in the backend and the default templates, etc.). [The YAML specification](http://www.yaml.org/spec/1.2/spec.html) explicitly states that key/value objects are *unordered* (e.g. in the ["Dump" section](http://www.yaml.org/spec/1.2/spec.html#id2762313)), and provides an example of an ordered object implemented as a list of single-element key/value objects in [Section 2.1](http://www.yaml.org/spec/1.2/spec.html#id2759963).

While our current codebase maintains key order when parsing YAML files, this is merely an implementation detail of the parser we use, a side effect of the way the parser steps through the document and the fact that it uses PHP 'arrays' to represent key/value objects. The mechanism could break at any given moment, under the following circumstances:

- We update the YAML parser to a newer version that happens to use a different parser or a different internal representation for key/value objects (e.g. a proper hash map, tries, btrees, ...); since the YAML specification does not mandate maintaining order, even a minor version upgrade could change this without prior notice.
- We switch to a different YAML implementation, for whatever reasons - security, performance, maintainability, ...
- Someone uses third-party YAML utilities to manage configuration files; since these tools can (and often will) change key order, using standard YAML tools on our configuration files cannot be recommended, and we cannot reasonably claim that our configuration files use proper YAML. (Note that this is not a theoretical situation: EngineYard, for example, provides Ruby hooks for deployment scripting, and using Ruby's built-in YAML implementation is a reasonable approach to managing configuration files during deployment).

The way I see it, we have three options.

1. Ignore the problem. This means that our configuration files aren't 100% YAML compliant (and we should stop advertising them as such, i.e. we cannot reasonably claim that "we use YAML for our configuration files"), and there is a risk that Bolt could break at any time when our YAML implementation changes, though it is quite unlikely that such a change would go completely unnoticed.
2. Change the configuration file format. This is going to be a painful breaking change touching almost everything in Bolt, but it would keep things working the way we want them to. Making this change non-breaking (i.e., still accepting the current file format, but *also* supporting a new one with deterministic ordering) would probably be possible, but more difficult to implement still.
3. Change any code that currently relies on the order of key/value objects, and provide an explicit ordering instead. Contenttypes in the menu, for example, could be ordered alphabetically (which, incidentally, would make a lot of sense IMO); fields however would need an additional ordering property, or they would need to go into an ordered collection after all.

**Comment by bobdenotter** [comment]
Is this still an issue? And if so, is it actionable?

**Comment by GDmac** [comment]
"key/value objects are unordered" - 
i suspect keys added to the arrays will be kept in a line by line way,
so probably not an issue immediately - just to be sure you could ask symfony team.

we could easily add an option to sort by: default, alphabetical or custom (field)
this will not break backward compatibility as it adds functionality instead of change.

```
mainmenu:
    sort: alphabetical
    ...
```

**Comment by tobias2k** [comment]
> "key/value objects are unordered" -
i suspect keys added to the arrays will be kept in a line by line way,
so probably not an issue immediately

The issue is not that Bolt would break when you use it on its own. The issue is that it is no longer safe to use standard YAML tools to process Bolt-YAML (or Symfony-YAML), e.g. as part of a deployment toolchain. Apparently this is acceptable, so I'll close this and speak no more of it.
