### ISSUE TITLE
Extensions not installing

### ISSUE THREAD

**Issue by chilion** [bolt/bolt#2327]
Since updating to RC2 I have the problem that an extension keeps preparing for install, eg:
![image](https://cloud.githubusercontent.com/assets/1157531/5468011/0dd718d2-85c9-11e4-86c8-d95b46cd355a.png)

And this will take until dead departs us, doesn't look good here. Console gives a 500 on the following link: http://sitename.extension/new/bolt/extend/install?package=bobdenotter%2Fsimone&version=dev-master

When I try following this link: 
![image](https://cloud.githubusercontent.com/assets/1157531/5468053/72f29642-85c9-11e4-8244-edfb9a3a4762.png)

![image](https://cloud.githubusercontent.com/assets/1157531/5468059/7e783f3a-85c9-11e4-95b8-9add060a8e5b.png)

**Comment by bobdenotter** [comment]
I think we should "reverse engineer" `escapeshellarg()`. Shouldn't be too hard to do, since we only use it in a very limited setting.

**Comment by rarila** [comment]
I doubt that would be an easy job

**Comment by bobdenotter** [comment]
The source code looks straightforward enough: 

https://github.com/php/php-src/blob/4b943c9c0dd4114adc78416c5241f11ad5c98a80/ext/standard/exec.c#L419
https://github.com/php/php-src/blob/4b943c9c0dd4114adc78416c5241f11ad5c98a80/ext/standard/exec.c#L336

**Comment by rarila** [comment]
Hmmm

**Comment by bobdenotter** [comment]
Also closing this one! Fixed by gawain for 2.1! :100:
