### ISSUE TITLE
Integrity Checker keeps wanting to add custom database

### ISSUE THREAD

**Issue by gpgautier** [bolt/bolt#2335]
function initialize() {
  	  $this->app['integritychecker']->registerExtensionTable(
	      function(Schema $schema) {
          $table = $schema->createTable('waffleorders');
          $table->addColumn("id", "integer", array('autoincrement' => true));
          $table->setPrimaryKey(array("id"));
          $table->addColumn("customer_name", "string", array("length" => 64));
          $table->addIndex(array('customer_name'));
          $table->addColumn("num_waffles_ordered", "integer");
          return $table;
	    });
      }

When running the integrity checker from backend it will correctly notify you of the missing table and lets you add it. But when checking again it displays the same notification:

    Table waffleorders is not present.

I've tested this in a fresh 2.0 install with an empty extension.

Another issue is that when adding a custom field to a contenttype table, the database check wants to add the field twice.

**Comment by GawainLynch** [comment]
Fixed in #2391
