### ISSUE TITLE
Bolt on mobile devices

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2347]
I want to use Bolt on my tablet. For me this is almost impossible. I can only click the main menu items. The submenus become visible, but I can't click the links in it because the main link is loaded.

**Comment by sintemaa** [comment]
I'm having the same problem on my tablet: Asus TF101

I'm running Bolt 2.1.3 pl1

I had a look using the Google developer tools. It looks like the Collapsing touch friendly siderbar menu is only shown on screens of 768px (48em). My 10" Tablert has a resolution of 1200*800, so it gets the desktop menu, with the submenu popping up to the side when you hover over it. Only you cannot hover on a touchscreen, so you must click, which will trigger the event of clciking on the menu item itself.

It would be good if you could detect if the device is a touch device and if so, always serve the touch friendly menu. However after doing a little search I could not find a reliable way to detect touch. 

Alternative options:
1. Change the manu so clicking the menu item itself does not do anything, only opens the sub menu. This way the desktop menu is usable on a touch device.
2. Add a button in the top menu bar to enable the touch friendly menu even on devices with a larger screen (which is saved in the user session or a cookie?)
3. ???
