### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by carmelg** [bolt/bolt#2352]
Hi, I tried to save the content in Arabic but in MySQL are saved as characters ?. I also set local ar_AE in config.yml but the result is the same.

**Comment by rarila** [comment]
@carmelg there's perhaps a solution to be found [here](https://github.com/bolt/bolt/issues/2386#issuecomment-68487148)

**Comment by carmelg** [comment]
It worked !!! Thanks and good BOLT 2015 :-)

**Comment by rarila** [comment]
Did you just create a new db or did you fiddle with the locale?

**Comment by carmelg** [comment]
I recreated the db with the default character and collaction set to utf8
