### ISSUE TITLE
Bolt Snippets: can't login with Github account

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#2355]
On [Bolt Snippets](https://snippets.bolt.cm/page/add). I can't login with the Github link. It redirects to: https://bolt.cm/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

The redirect_uri MUST match the registered callback URL for this application.

**Comment by GawainLynch** [comment]
Fixed :grin:
