### ISSUE TITLE
admin intereface to edit contenttypes

### ISSUE THREAD

**Issue by PeterDeKeer** [bolt/bolt#2356]
Hi,

I wanted to dive into bolt, but the editing of the contenttypes is through yml.
Are you guys planning to let admins create contenttypes in the cms interface?

This is much less error prone.

**Comment by bobdenotter** [comment]
If you're a _developer_ it shouldn't be too much effort to grok yml. I assume you write CSS (or Sass) and HTML by hand too? I think this is similar. 

Closing this, but if you feel this is still an issue, feel free to re-open it.
