### ISSUE TITLE
Bolt Extensions don't work if they have composer.json dependencies 

### ISSUE THREAD

**Issue by jacobtolar** [bolt/bolt#2365]
I built a couple of extensions for Bolt that pull in some dependencies via composer. When I try to use autoloading in my extension:

```php
require 'vendor/autoload.php';
```

it breaks :) Extensions are [required to include 'init.php' inside the autoload section](https://docs.bolt.cm/extensions/config#json-file) - this seems to cause some sort of cyclic dependency when it hits the require statement.

I brought this up in IRC a few days ago and someone suggested a workaround I can use for now, but I thought I'd post the issue here so it could be tracked.

**Comment by bobdenotter** [comment]
Bump @jacobtolar

**Comment by jacobtolar** [comment]
Sorry for the delay. 

Can't remember the IRC name of who suggested this, but the idea was to download the Bolt source, add my dependency to the bolt core composer.json ( https://github.com/bolt/bolt/blob/master/composer.json ) and install using composer. 

What I did instead was download the dependency using Composer and manually 'require' php files I need in extension.php.

I plan to pull this out into its own repo and submit it as an extension but for now, here's what I'm doing:

composer.json:
https://github.com/jacobtolar/mafmc-web/blob/master/bolt/extensions/local/jacobtolar/GoogleCalendar/composer.json

extension.php:
https://github.com/jacobtolar/mafmc-web/blob/master/bolt/extensions/local/jacobtolar/GoogleCalendar/Extension.php#L8-L16

Line 8 crashes Bolt completely - can't load a single page.

**Comment by caseyamcl** [comment]
Here is another **workaround** that allows uses an autoloader instead of `require` statements:

First, require the Symfony Classloader (`~2.6`) in your extension's `composer.json` file, and update dependencies (`composer update`)

Then, your `Extension.php` class can include a `setupAutoloader()` method:

```php
use Symfony\Component\ClassLoader\ClassLoader as SymfonyClassLoader;
use Symfony\Component\ClassLoader\Psr4ClassLoader;

class Extension extends BaseExtension
{
    public function initialize()
    {
        $this->setupAutoloader();
        
        // The rest of your Bolt code here.
    }

    public function getName()
    {
        return "your_ext_name";
    }

    // ---------------------------------------------------------------

    protected function setupAutoloader()
    {
        require_once(__DIR__ . '/vendor/symfony/class-loader/Symfony/Component/ClassLoader/ClassLoader.php');
        require_once(__DIR__ . '/vendor/symfony/class-loader/Symfony/Component/ClassLoader/Psr4ClassLoader.php');

        $defsDir = __DIR__ . '/vendor/composer';

        $psr0Loader = new SymfonyClassLoader();
        $psr4Loader = new Psr4ClassLoader();

        $map = require $defsDir . '/autoload_namespaces.php';
        foreach ($map as $namespace => $paths) {
            foreach ((array) $paths as $path) {
                $psr0Loader->addPrefix($namespace, $path);
            }
        }

        $map = require $defsDir . '/autoload_psr4.php';
        foreach ($map as $namespace => $paths) {
            foreach ((array) $paths as $path) {
                $psr4Loader->addPrefix($namespace, $path);
            }
        }

        $classMap = require $defsDir . '/autoload_classmap.php';
        if ($classMap) {
            $psr0Loader->addPrefixes($classMap);
        }

        $psr0Loader->register();
        $psr4Loader->register();
    }

}
```

**Comment by SahAssar** [comment]
This isn't 2.3 anymore, is it? I'm changing labels, please change back if I'm wrong!

**Comment by GawainLynch** [comment]
I'm going to knock this one on the head… Bolt extensions now (even local) build autoloaders… there is, as pointed put by @caseyamcl, the Symfony option… Composer has libaries for this as well and all are reasonably well documented.
