### ISSUE TITLE
save options, overset text.

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2366]
By clicking the chevron in save button , the text options are overset (text-overflow).
Only the button on the side panel.

:v: 
![screenshot - 291214 - 04 42 21](https://cloud.githubusercontent.com/assets/6233822/5567198/07b0e6b4-8f1e-11e4-9f97-a758c0690f34.png)

**Comment by bobdenotter** [comment]
Duplicate of #2013
