### ISSUE TITLE
calculate height according to aspect ratio if it is not supplied in a template image tag

### ISSUE THREAD

**Issue by bodyflex** [bolt/bolt#2372]
when using template image tags like `thumbnail` or `showimage`, it would be super userful if the height was calculated automatically according to the aspect ratio if only the width is supplied.

right now you need to:
```twig
{% set info = imageinfo(record.thumbnail) %}
{% set ratio = info.height / info.width %}
{{ record.thumbnail|showimage(400, (400 * ratio)|round) }}
```
or else the height will be 100

**Comment by bodyflex** [comment]
why not default it dynamically to `width / aspect ratio` though?

**Comment by bobdenotter** [comment]
@bodyflex It effectively does that now, right?

**Comment by bodyflex** [comment]
oh right, sorry about that. shouldn't try to think after new years eve...
