### ISSUE TITLE
[RFC] More fine-grained control over adding snippets / Javascript / CSS

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2374]
When you currently do this in an extension: 

```
    $this->app['htmlsnippets'] = true;
    $this->addCss('assets/extension.css');
    $this->addJavascript('assets/script.js', true);
```

The `.css` and `.js` are added to the front- and backend both. There's no way to control having it output only in one of them. How to best fix this? 

  1. Replace the whole damn thing, and push forward to implementing RequireJS or something similar. (Note: This will _not_ work for `.css`, only for `.js`.

  2. Fix up our current implementation. 

I'm leaning towards option 2. I'm sure we could make it not break backwards compatibility. Perhaps something like this: 

```
    $this->addJavascript('assets/script.js', array(
        'late' => true, 
        'priority' => 10,
        'frontend' => false,
        'backend' => true
    );
```

**Comment by bobdenotter** [comment]
See also #2109

**Comment by GawainLynch** [comment]
This is now possible in the upcoming 2.3 branch.  An example of asset selection would be:
```php
<?php

namespace Bolt\Extension\Gawain\MyAssets;

use Bolt\Controller\Zone;
use Bolt\BaseExtension;
use Symfony\Component\HttpFoundation\Request;

class Extension extends BaseExtension
{
    public function getName()
    {
        return "MyAssets";
    }

    public function initialize()
    {
        $this->app->before(array($this, 'addAssets'));
    }

    public function addAssets(Request $request)
    {
        if (Zone::isBackend($request)) {
            $request->attributes->set('allow_snippets', true);
        }

        $this->addCss('myasset.css');
        $this->addJavascript('myasset.js', false);
    }
}
```

The `allow_snippets` is set automatically on frontend routes, but you can use the `Zone` class conditionals for `addCss()` etc as needed.
