### ISSUE TITLE
[RFC] Changelog workflow

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2379]
## Problem
Post v2.0.0 release, developers are required to submit `changelog.md` summaries with PRs that have outward changes.  This leads to merge conflicts if PRs are not synchronised in a serial fashion

## Proposed Change
Change workflow to require the updating on `changelog.md` at merge time, by the merging developer, sourced from meta added to the PR by the PRs submitter.

e.g. Include a section in PRs like:
```
Changelog
---------

* My change does something cool
```

**Comment by rarila** [comment]
Just trying some formattings to find something easy to remember and yet machine readable. I came up with this one: Three stars followed by one/multiple lines starting with a star and everything at the end of the message. Would that do? Do we need "Changelog"? Would this be done here in the comment field or in a commit message?

```
***
* Added foo
* Removed bar
```
That would result in:
***
* Added foo
* Removed bar

**Comment by GawainLynch** [comment]
Interestingly enough I am just writing something up for `bolt/docs` now...  I will commit a draft in a minute for comments.

**Comment by GawainLynch** [comment]
Thoughts on https://github.com/GawainLynch/bolt-docs/compare/bolt:master...GawainLynch:internals-prs?expand=1

**Comment by bobdenotter** [comment]
Seems good to me. We should also write a `contributing.md` to go into the repo, so it'll show up at the top of the screen when making a new issue or pr. Like this: https://github.com/symfony/symfony/issues/new

**Comment by GawainLynch** [comment]
OK, will add it to my linked PR in a second

**Comment by GawainLynch** [comment]
Duh!  No I won't, wrong repo...  Nothing to see here!
