### ISSUE TITLE
simpleforms feature

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2380]
Since simpleforms not use ajax, I wish I could change where the notification is received, soil placing the contact form at the footer of the page, and this is a problem because the message is not visible.
It would be great to put something like `{{ simpleforms-notice }}` in the place where I want to receive the response from the server (in the header for example).

Screenshot:

![screenshot - 301214 - 23 59 36](https://cloud.githubusercontent.com/assets/6233822/5585149/5c4db134-9081-11e4-92d6-699832c83621.png)

Sorry if this is not in the right place.

**Comment by bobdenotter** [comment]
I recall seeing some discussion on this, last week. Perhaps @GawainLynch of @jadwigo remember, because I can't seem to find it anymore.

**Comment by GawainLynch** [comment]
AJAX request/response will be coming to Bolt Forms soon(ish).  This is out of scope for Simple Forms either way. 

Please feel free to log it on the [Bolt Forms](https://github.com/GawainLynch/bolt-extension-boltforms) issue tracker though.  I just need to find the hours in my day at the moment :-)
