### ISSUE TITLE
Old year broken, we should replace it with a new year!

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2384]
I've simply replaced ``2014`` with ``2015`` throughout the whole codebase and it seems to fix it. If you like I could make a PR for it.

HAPPY NEW YEAR, BOLTS! :fireworks:

**Comment by GawainLynch** [comment]
:beers:

**Comment by mike-anthony** [comment]
:laughing: :+1: :beers: Happy New Year everyone! :smiley:

**Comment by bobdenotter** [comment]
Happy MMXV, all!

**Comment by bobdenotter** [comment]
SPRING CLEANING!!1!?one!!
