### ISSUE TITLE
Problem with character encoding

### ISSUE THREAD

**Issue by lucasfecko** [bolt/bolt#2386]
Hi, 

I am trying to set up a blog, but can't be able to solve trying to write characters such as č, ď, ť. Characters like š and ž work fine. These characters are from slovak language. The weird thing is, the characters aren't replaced with diamond question mark (broken encoding - �) but a normal question mark (?) when entry or page is saved to database.

I first thought that this would be the issue of CKEditor, but I have also tried to enter the characters in Title field, wich is a normal input, and they were also stored as question marks.

I checked the database encoding, is set to ci_general_utf8, I also checked the HTML encodings, all set to utf8. Then I tried to toy with locales on my server, and set all to sk_SK.utf8, also set locale in config.yml to sk_SK, still with no success.

My server set-up is Nginx with PHP-FPM, PHP version 5.4.

**Comment by rarila** [comment]
I think we have a problem when writing to MySQL here as it seems to be the same problem as described in #2352.

**Comment by lucasfecko** [comment]
Strange, I create an entirely new database, created new user in Bolt, and tried it again and it works. The characters are no more shown as question marks.

**Comment by rarila** [comment]
Do you still have the old database? We could compare both schemes then. Also, with what version of Bolt was the non working db created?

**Comment by lucasfecko** [comment]
The version of Bolt I am using is 2.0.2. I still have the old table, should I create dumps of both tables and post them? Or is there any way to post just database schema? I just checked the bolt_entires tables in both databases and structure and table information seems the same, InnoDB as engine, encoding: utf8.

**Comment by rarila** [comment]
Both structures are exactly the same? Hmm, strange things happen. Were both created with the same Bolt version?

**Comment by lucasfecko** [comment]
Yes they were. One was created yesterday and one today (well, one in 2014 and one in 2015), the only difference was that there were damadged locales when creating the first database. I toyed with LC_ALL and LANG variables before bolt installation and left some unset. I only repaired them after the database was created, since I began to experience problems. I think this was the problem.

**Comment by rarila** [comment]
Sounds reasonable (the thing with the locale, not the year;-)
So do you think we can close this?

**Comment by lucasfecko** [comment]
Yeah, thank you for your assistance @rarila. Have a great new year by the way :).

**Comment by rarila** [comment]
n.p.
Happy new year!
