### ISSUE TITLE
Whoops not naming the faulty line in the actual place

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#2387]
I am fooling around with form-extensions, after I disabled an extension, the Whoops thing said:

" The "boltforms.extension" extension is not enabled in "index.twig" at line 94. "

Line 94 was where I was including _footer.twig, which contained the actual error. Of course the error wasn't hard to find in this ocassion, but just so you know...

**Comment by bobdenotter** [comment]
This isn't really fixable by us. PHP's 'backtrace' get's lost once you start traversing into anonymous functions. Which is what happens, when Twig parses another template from within a template. So, wontfix, i'm afraid.

**Comment by evertalbers** [comment]
Never mind. Just thought I should let you know.
