### ISSUE TITLE
Datetime picker doesn't work in the backend. 

### ISSUE THREAD

**Issue by Slowwie** [bolt/bolt#2392]
I am new in bolt.cm . Its awesome! But the datetimepickers are not working in all browsers and the complete backend. If i click into, the picker is coming but if I select a date then nothing is happening. Default values are deleted and its impossible to bring them back. 
I think this is an very important small bug ;) . 

Great work. I love bolt.cm even after this few days I use it!

Thanks. Michael

**Comment by GawainLynch** [comment]
Could you be more specific about which browsers (and versions) are **not** working for you.

**Comment by Slowwie** [comment]
All browsers doesn't work. Safari, Firefox, Chrome, Opera. All newest versions. I work on a Mac (if its important to know). 

The picker is flashing up. But instead of putting the selected value in the select-field it is deleting it. And in the database is also no effect...

**Comment by rarila** [comment]
@GawainLynch Thanx ;-)
Bug confirmed…

**Comment by rarila** [comment]
Probably fixed by #2394

**Comment by rarila** [comment]
Confirmed…
@Slowwie  Thanks!

**Comment by Slowwie** [comment]
I updated bolt now, and it doesn't work :( . I cleared the cache and all the stuff. Have I something forgotten? In the #2394 was the _geolocation.twig changed. I can't see the connection to the _date,twig and the _datetime.twig problem ...

**Comment by GawainLynch** [comment]
Strange, it worked here for me...  @rarila any further ideas?

**Comment by rarila** [comment]
I was also wondering… but it didn't work before and did work after that change so I didn't care anymore. Perhaps a newly generated bolt.js did the trick… investigating…

**Comment by rarila** [comment]
Works quite nice here (now)…
@bobdenotter: Could you please check on a Mac?!

**Comment by bobdenotter** [comment]
Tested on OSX on latest master with Firefox, Chrome and Safari. All work as expected.

**Comment by rarila** [comment]
@Slowwie Any output in the console?

**Comment by Slowwie** [comment]
Oh there was a problem with the updating (git pull). Now it works also here ;) . Thanks!

**Comment by rarila** [comment]
Uh, ok :-)
