### ISSUE TITLE
libsass generates wrong linefeeds on windows

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2397]
#2371 broke proper generation of linefeeds on windows. (see #2393)
Seems like we have to wait a bit for a [patch](https://github.com/sass/libsass/pull/787) to arrive.

_(Meanwhile @bobdenotter agreed to fix all wrong CRLF linefeeds to LF manually :stuck_out_tongue_winking_eye: )_

**Comment by bobdenotter** [comment]
Has this not been resolved yet?

**Comment by rarila** [comment]
We simply [run](https://github.com/bolt/bolt/blob/master/app/view/Gruntfile.js#L477) ``grunt-eol`` over it. But it seems it is solved upstream now. So it is solved either way, but we probably can remove that eol-target to streamline the process. So we remove the blocking but let it open until it is removed.
