### ISSUE TITLE
Extension's function not being found.

### ISSUE THREAD

**Issue by lswest** [bolt/bolt#2401]
I created a local extension for Bolt 1.6, which I'm in the process of moving to Bolt 2.0.2.  I've followed the information on the Wiki, as well as checking various other extensions that add a twig function.  However, even though my extension is installed (via a local git folder, as described in the wiki).  However, trying to use it in a contenttype (which has allowtwig:true set on the HTML editor) results in the following error:

"The function "icon" does not exist in [...]"

After the word "in" the HTML of the page is simply displayed, as well as the twig function line that reads {{ icon('fa fa-bars') }}.

I've uploaded the extension to a github repository for the time being.  If anyone has any suggestion as to what I'm doing wrong, it would be appreciated.

My assumption is that there's some issue in my Extension.php file which is resulting in the function not being added to the correct namespace, or else the function is being ignored.

https://github.com/lswest/iconfonts-bolt

Thanks in advance.

**Comment by lswest** [comment]
Just a quick update - this is now also happening with the SimpleForms extension.  Seems like the twigAddFunction operation no longer works?

This is, however, an upgrade from Bolt 1.6.  I'll try it in a fresh install of Bolt 2.0.2, and post back.

**Comment by GawainLynch** [comment]
Totally random question, but are you adding `{{ icon() }}` in a record's HTML field, or in a `.twig` file?

**Comment by lswest** [comment]
In the WYSIWYG editor (same way you'd want to usually use the simpleForms extension).  I could try it in the template file, but the role of the extension does require it to be easily user-accessible.  I have also made sure to enable twig in the field of the contenttype (with `allowtwig: true`)

**Comment by rarila** [comment]
I darkly remember that you have to declare the function in your extension as save, too.

**Comment by rarila** [comment]
Something like this:
```
$this->addTwigFunction('icon', 'twigIcon', array('is_safe' => array('html')));
```

**Comment by GawainLynch** [comment]
The problem is where extensions are able to be initialised in the code path.  

Twig in HTML fields has limits, and risks. Most of the extension readme document their Twig function as "by adding to your template" (or similar language).

**Comment by lswest** [comment]
Running the function from a twig file does work.  However, using the 'is_safe' had no impact on the ability to use it in the editor.  I'm aware of the risks, but when I wrote this extension I was of the opinion of it being a better solution than trying to find some way to allow the wysiwyg editor to not ignore/delete <i> elements for things like Font Awesome.  The idea being that non-technical users should be able to use the table on something like Font Awesome to decide what icon they want, and implement/change it, without me having to design an entire system in the content type for this.  Especially because the icons could technically appear anywhere.

Is there any way to get this working?  Or does anyone have an easy suggestion so that the <i> elements aren't removed from the editor upon re-opening of the entry in the backend?

Otherwise I'll head back to the drawing board and design a different system that runs through the template in some way.

Thanks for all the input so far.

**Comment by GawainLynch** [comment]
I have just tired this in current master and it installs and works fine for me.

```bash
$ mkdir -p extensions/local/lswest/
$ cd extensions/local/lswest/
$ git clone https://github.com/lswest/iconfonts-bolt.git iconfonts
```
I have a few suspicions:
1. Your extension wasn't in `extensions/local/lswest/iconfonts`
2. The web server couldn't read `extensions/local/lswest/iconfonts`
3. We fixed something in the 2.1-alpha

Can you confirm that points 1. & 2. don't fix this for you in your stable install, or try all of the above in a master branch test install for us :+1:

**Comment by lswest** [comment]
I've just tried what you suggested.  Placing a copy of the extension in extensions/local didn't change anything for Bolt 2.0.6.  And I have set up a copy of the master branch of bolt, but it seems allowtwig: true isn't registering/working from contenttypes.yml.  As such, I can't test if the function works from within a post.  I'll have a look at the issue in 2.1 again later, and will update this report if I can get it working.

**Comment by GawainLynch** [comment]
Yep, reproduced here.  Exception on 2.0.x and unconverted text on master.

Shall dig deeper!

**Comment by GawainLynch** [comment]
This turns out to be a failure on the part of our documentation.  [Documentation bug raised](https://github.com/bolt/docs/issues/147).

You just need to add this function to `Extension.php` and everything works as expected:
```php
    public function isSafe()
    {
        return true;
    }
```

**Comment by lswest** [comment]
Thanks for all the help, it's working now.

**Comment by GawainLynch** [comment]
No problems. A couple of us were hanging our heads in shame at that one :-)
