### ISSUE TITLE
Error in thumbnail (or something)

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2410]
I noticed that on some of my sites, thumbnails don't always loading correctly. Today I noticed the error below on one of the missing thumbs. Not sure what to make of it.

Warning: session_start() [function.session-start]: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /bla/bla/domains/bla/public_html/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 147

Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /bla/bla/domains/bla/public_html/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:147) in /bla/bla/domains/bla/public_html/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 147

**Comment by rarila** [comment]
Do you have the latest version of bolt-thumbs installed? I don't know if it matches your problem, but creation from non exif jpgs was broken in 2.0.2

**Comment by peterboorsma** [comment]
Ah, could be! I didn't know the thumbnailer was broken. I use the latest official release (2.0.2). I guess it can wait until the next release. This was more a 'look what I found' message.

**Comment by rarila** [comment]
Simply replace that [file](https://github.com/bolt/bolt-thumbs/blob/master/src/ThumbnailCreator.php)

**Comment by peterboorsma** [comment]
Hmm.. The new version doesn't generate the thumb correctly. I'll try to replicate the error later today.

**Comment by bobdenotter** [comment]
Bug confirmed, fix is in the works!
