### ISSUE TITLE
The "used templates" in the debug bar should be trimmed.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2412]
.. They show too much of the path, which isn't really informative: 

![screenshot 2015-01-06 20 50 06](https://cloud.githubusercontent.com/assets/1833361/5635103/2ea03972-95e6-11e4-964a-0fb9a4ab2a27.png)

**Comment by rarila** [comment]
… perhaps sorted alphabetically? (or is that the order they are opened?)

**Comment by bobdenotter** [comment]
Yes, the current order is the order in which they are parsed.

**Comment by bobdenotter** [comment]
See #2416 2416
