### ISSUE TITLE
bolt2 open_basedir error

### ISSUE THREAD

**Issue by bad-kiwi** [bolt/bolt#2413]
I have set up a site using Bolt 2.0.2
Now, my error_log actually gets rapidly filled with these lines:

[xxx] [warn] [client xxx] mod_fcgid: stderr: PHP Warning:  mkdir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/mywebsite.de/:/tmp/) in /var/www/vhosts/mywebsite.de/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 52
[xxx] [warn] [client xxx] mod_fcgid: stderr: PHP Warning:  ini_set(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/mywebsite.de/:/tmp/) in /var/www/vhosts/mywebsite.de/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 55

Ok, it looks like it has something to do with Symfony but this has been installed by Bolt.
Can someone tell me what I can do to fix that? My website is running on a vhost with an up-to-date Apache/Plesk installed.

**Comment by GawainLynch** [comment]
You need to change the `session.save_path` setting in Plesk for that site.

**Comment by bad-kiwi** [comment]
Thanks so far. Where can I find these settings and to what do I have to change them?

**Comment by GawainLynch** [comment]
That I can't remember and I don't have access to a Plesk install at present to dig though, I just remember sorting this once before for someone.

Your web host should be able to help though.  It is a problem they would run into a lot as PHP sessions are pretty commonly used...  I am surprised they haven't set this up as a default for you TBH.

**Comment by bobdenotter** [comment]
Perhaps this will help: http://24hoursit.wordpress.com/2013/02/14/how-to-enable-session-support-for-php-in-plesk-10-and-plesk-11/

**Comment by bad-kiwi** [comment]
Oh thanks, this helped me out. In short:
- create save session directory in domain’s root and give 777 permissions (like: /your-domain-name.com/httpdocs/tmp-sessions/)
- in Plesk open PHP settings and go to session.save_path and change from default to {DOCROOT}/tmp-sessions

**Comment by Largo** [comment]
Easy solution:
Add this to the start of index.php: ini_set("session.save_path","tmp/");
Create the folder tmp beforehand in your main directory.
Maybe use the absolute path to your httpdocs directory and add tmp there.

Suggestion: Can we make this a config item in config.yml?
I'm on a hoster that sets the session.save_path to /tmp, which is not accessible to PHP....
They don't want to change that mistake and there's no way to change it without changing bolt files.
Would be a nice to have.

NativeFileSessionHandler has the path in it's constructor. So it's doable.
 public function __construct($savePath = null)
