### ISSUE TITLE
Maintenance mode in 2.0.2 problem

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#2414]
When starting with new project with 2.0.2  I have ran into issue with maintenance mode:

I have duplicated base-2014 theme and creted /theme/new_theme/my_maintenance.twig (plain html actually), set up config.yml properly, but  maintenance_default.twig is still "active", no matter what.

So, it seems, when /app/theme_defaults/maintenance_default.twig file is present,
config.yml setting to another file in own theme is not working.

When maintenance_default.twig is deleted, my_maintenace.twig in theme folder starts to work. I velieve it has been working correctly in previous versions…

Anyone else has experienced this?

**Comment by bobdenotter** [comment]
In which `config.yml` did you set it? In `app/config/config.yml`, or the one in your theme folder? 

See also: https://twitter.com/BoltCM/status/552551792408813568

You're not the first to bump into this, so I suppose this warrants a "fix" in the docs or something. Hmm.

**Comment by lexislav** [comment]
I have set it in global config, app/config.yml as usually… and must admit I don't use theme's config too often. And of course, the config.yml in theme directory is overriding the global one. Sorry for bothering with this. 
But 'fix' in docs would be helpful. In chapter "Setting up Bolt" could be mentioned the sequence of loading configs and note, that the theme's config can override the global one. In template file structure there is no mention about theme's config.yml as well. But I have to say that docs are getting much better.
Thanks anyway, closing.
