### ISSUE TITLE
translation of label in edit It's not working

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2418]
It's not working the translation of labels, or maybe I have not understood. For example the string "teaser" or "body", I've added to message.es.yml but do not seem to work.
![screenshot - 080115 - 15 37 52](https://cloud.githubusercontent.com/assets/6233822/5668253/202eb162-974d-11e4-864a-02c010bd948c.png)
![screenshot - 080115 - 15 39 24](https://cloud.githubusercontent.com/assets/6233822/5668254/2030cbe6-974d-11e4-8589-9b06b63f2b08.png)

**Comment by bobdenotter** [comment]
You could just add the "label: Resumen" to the contenttype.yml, right?

**Comment by serweb-labs** [comment]
It's true, I guess now works differently, however "teaser" is in the "untranslated keywords" section so I thought it was a mistake.

Do you think that the fields will return to translate or hereafter contenttype.yml recommended?
Thank you for your "bolt" response. ^^

**Comment by bobdenotter** [comment]
My personal opinion is that we should _not_ translate content at all, and this includes labels defined in contenttypes. :-)

**Comment by serweb-labs** [comment]
Good to hear your views. :+1: 
Then keywords should disappear translations file is automatically created.
On the other hand this would prevent making the multilingual administration.

**Comment by rarila** [comment]
@serweb-labs be patient, translation of labels (and all other stuff) is on my list. They will end in contenttypes translations (just like names and group labels are already). It`s just a matter of time.

**Comment by serweb-labs** [comment]
@rarila  Good to know, I have seen that the translations are incomplete for my language (Spanish), I sign as a translator if necessary. Thanks!

**Comment by rarila** [comment]
You're welcome

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
