### ISSUE TITLE
Some issues after updating with 2.0.2

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2421]
After installing Bolt 2.0.2 the buttons on the template editing page disappeared (see screenshot). I can use the buttons because only the top edge is visible. I use Firefox 34. I also can't use the tabs anymore. On the editing page of an entry or page, I can see the tabs. Clicking them doesn't have any effect.

![screenshot](https://cloud.githubusercontent.com/assets/9332608/5676697/af920c7c-97da-11e4-831c-a1fcf34663a9.jpg)

**Comment by bobdenotter** [comment]
Can't reproduce yet. 

You've cut off the most interesting part of the screenshot, so we can't see which browser and platform you're on. Have you tried another browser? cleared all caches? Sure the update went OK? What does the console in the browser say?

**Comment by gwbonline** [comment]
I use Windows 7 with Firefox 34. The update went well and I cleared the cache. With IE everything works fine...

The browser console says a lot, especially in the css section. The JS section says:

TypeError: $(...).magnificPopup is not a function bolt.js:2368


css: (I don't know if this is helping you...)

‘Alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. jquery-ui-1.10.3.custom.min.css:5
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. magnific-popup.css:12
Fout tijdens het parsen van waarde voor ‘cursor’.  Declaratie genegeerd. magnific-popup.css:62
Fout tijdens het parsen van waarde voor ‘cursor’.  Declaratie genegeerd. magnific-popup.css:67
Onbekende eigenschap ‘user-select’.  Declaratie genegeerd. magnific-popup.css:77
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. magnific-popup.css:132
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. magnific-popup.css:140
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. magnific-popup.css:165
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. magnific-popup.css:177
Onbekende eigenschap ‘zoom’.  Declaratie genegeerd. select2.css:9
‘*’ gevonden waar declaratie verwacht.  Naar volgende declaratie gesprongen. select2.css:10
Onbekende eigenschap ‘user-select’.  Declaratie genegeerd. select2.css:49
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:52
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:53
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:55
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:68
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:69
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:71
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:137
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:201
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:202
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:204
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:260
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:261
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:270
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:271
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:282
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. select2.css:283
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:306
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:307
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:309
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:318
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:319
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:321
Onbekende eigenschap ‘user-select’.  Declaratie genegeerd. select2.css:395
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:500
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:501
Onbekende eigenschap ‘user-select’.  Declaratie genegeerd. select2.css:582
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. select2.css:585
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:586
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. select2.css:587
‘-webkit-min-device-pixel-ratio’ gevonden waar naam van mediafunctie verwacht. select2.css:691
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. jquery.fileupload-ui.css:25
‘-webkit-min-device-pixel-ratio’ gevonden waar naam van mediafunctie verwacht. jquery.fileupload-ui.css:104
Onbekende pseudo-klasse of pseudo-element ‘-webkit-inner-spin-button’.  Regelset genegeerd vanwege foute selector. bolt.css:7
Onbekende pseudo-klasse of pseudo-element ‘-webkit-search-cancel-button’.  Regelset genegeerd vanwege foute selector. bolt.css:7
‘auto’ gevonden waar kleur verwacht.  ‘-webkit-focus-ring-color’ gevonden waar kleur verwacht.  ‘-webkit-focus-ring-color’ gevonden waar einde van waarde verwacht.  Fout tijdens het parsen van waarde voor ‘outline’.  Declaratie genegeerd. bolt.css:7
‘\9 ’ gevonden waar einde van waarde verwacht.  Fout tijdens het parsen van waarde voor ‘width’.  Declaratie genegeerd. bolt.css:7
‘\9 ’ gevonden waar einde van waarde verwacht.  Fout tijdens het parsen van waarde voor ‘margin-top’.  Declaratie genegeerd. bolt.css:7
Onbekende pseudo-klasse of pseudo-element ‘-ms-input-placeholder’.  Regelset genegeerd vanwege foute selector. bolt.css:7
Onbekende pseudo-klasse of pseudo-element ‘-webkit-input-placeholder’.  Regelset genegeerd vanwege foute selector. bolt.css:7
‘�’ gevonden waar einde van waarde verwacht.  Fout tijdens het parsen van waarde voor ‘line-height’.  Declaratie genegeerd. bolt.css:7
Onbekende eigenschap ‘user-select’.  Declaratie genegeerd. bolt.css:7
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. bolt.css:7
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. bolt.css:7
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. bolt.css:7
Onbekende eigenschap ‘zoom’.  Declaratie genegeerd. bolt.css:7
Onbekende eigenschap ‘-moz-osx-font-smoothing’.  Declaratie genegeerd. bolt.css:10
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. bolt.css:10
‘top’ gevonden waar kleur verwacht.  Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. bolt.css:10
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. bolt.css:10
Fout tijdens het parsen van waarde voor ‘display’.  Declaratie genegeerd. bolt.css:10
‘grayscale(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. bolt.css:10
Onbekende eigenschap ‘-moz-border-radius’.  Declaratie genegeerd. bolt.css:10
Onbekende pseudo-klasse of pseudo-element ‘-webkit-input-placeholder’.  Regelset genegeerd vanwege foute selector. bolt.css:10
Onbekende pseudo-klasse of pseudo-element ‘-ms-input-placeholder’.  Regelset genegeerd vanwege foute selector. bolt.css:10
Fout tijdens het parsen van waarde voor ‘overflow’.  Declaratie genegeerd. bolt.css:10
‘touch-enabled’ gevonden waar naam van mediafunctie verwacht. progs:1
‘-webkit-touch-enabled’ gevonden waar naam van mediafunctie verwacht. progs:1
‘-o-touch-enabled’ gevonden waar naam van mediafunctie verwacht. progs:1
‘-ms-touch-enabled’ gevonden waar naam van mediafunctie verwacht. progs:1
‘modernizr’ gevonden waar naam van mediafunctie verwacht. progs:1
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. progs:1
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:13
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:14
‘top’ gevonden waar kleur verwacht.  Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. progs:15
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:43
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:44
‘top’ gevonden waar kleur verwacht.  Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. progs:45
Fout tijdens het parsen van waarde voor ‘min-width’.  Declaratie genegeerd. progs:279
Onbekende eigenschap ‘-moz-box-shadow’.  Declaratie genegeerd. editor_gecko.css:5
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. editor_gecko.css:5
‘top’ gevonden waar kleur verwacht.  Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. editor_gecko.css:5
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. editor_gecko.css:5
Onbekende eigenschap ‘-moz-border-radius’.  Declaratie genegeerd. editor_gecko.css:5
‘alpha(’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. editor_gecko.css:5
Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. progs:1
Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:1
‘top’ gevonden waar kleur verwacht.  Fout tijdens het parsen van waarde voor ‘background-image’.  Declaratie genegeerd. progs:1
‘progid’ gevonden waar ‘none’ of URL verwacht.  Fout tijdens het parsen van waarde voor ‘filter’.  Declaratie genegeerd. progs:1
‘:’ gevonden waar einde van waarde verwacht.  Fout tijdens het parsen van waarde voor ‘background’.  Declaratie genegeerd. progs:1
‘*’ gevonden waar declaratie verwacht.  Naar volgende declaratie gesprongen. progs:3
‘*’ gevonden waar declaratie verwacht.  Naar volgende declaratie gesprongen. contents.css:60
Onbekende eigenschap ‘tab-size’.  Declaratie genegeerd. contents.css:100

**Comment by gwbonline** [comment]
An other symptom:

The publish buttons in the top right corner and bottom left corner (editing page) do not work. I can click them, but they do not respond...

**Comment by gwbonline** [comment]
Found the problem! I am using AdBlockPlus. That wasn't a problem before... until update 2.0.2... Adding Bolt to the white list solved everything!

**Comment by rarila** [comment]
@gwbonline Would be interesting what url was blocked and why. As AdBlockPlus is widely used probably others could hit the same problem
