### ISSUE TITLE
ContentType Labelling 

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#2425]
Changing name and singular_name of a Content Group named Entries to something other then entries has no effect in the admin.  

v2.0.2

![screen shot 2015-01-09 at 12 02 01 pm](https://cloud.githubusercontent.com/assets/5342693/5679431/634209b8-97f7-11e4-9cc8-b4954c87e814.png)
![screen shot 2015-01-09 at 12 01 34 pm](https://cloud.githubusercontent.com/assets/5342693/5679432/6342b2be-97f7-11e4-8c30-01a60b9d9bb3.png)

**Comment by rarila** [comment]
Change them in Translations / Contenttypes
