### ISSUE TITLE
Admin tool Upload file triggered when cutting and pasting from word doc into a text field

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#2427]
![screen shot 2015-01-09 at 12 32 56 pm](https://cloud.githubusercontent.com/assets/5342693/5679779/2fb33658-97fc-11e4-9887-b16f0a4f2e7d.png)

**Comment by nealmarques** [comment]
I'm on OSX, pasting from MS Word.  Only happening in Chrome right now.  Can't reproduce in Safari.

**Comment by rarila** [comment]
I guess we have to set [pasteZone](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#pastezone) to ``null``

**Comment by bobdenotter** [comment]
Good catch, @rarila. Fix incoming.

**Comment by bobdenotter** [comment]
@nealmarques Please check if #2436 fixes it for you! :-)

**Comment by nealmarques** [comment]
That update did correct the problem.
