### ISSUE TITLE
[RFE] Sort Number Field Type that can be manipulated in Record Listing View

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#2432]
It would be useful to have an extension that would allow the manipulation of  float/integer field on a given content type via the Record Listing View.

**Comment by bobdenotter** [comment]
Ideally, we should be able to change the sorting-order from the overview screens. Perhaps even with drag and drop. ;-)

**Comment by rossriley** [comment]
Yes, that was the kind of thing I was thinking, make a system field to store sort weight and then use one of the sortable javascript plugins to allow rearranging.... It's the sort of thing that we can refine as an extension and then bring into core when needed.

**Comment by SahAssar** [comment]
Merging into #2958, please feel  free to reopen if I'm wrong
