### ISSUE TITLE
Error: Class 'Bolt\CronEvents' not found

### ISSUE THREAD

**Issue by babaggeii** [bolt/bolt#2434]
I think I've found an error in the docs. See this StackOverflow for details: 

http://stackoverflow.com/questions/27875473/error-class-bolt-cronevents-not-found

Docs page: https://docs.bolt.cm/internals/task-scheduler

**Comment by GawainLynch** [comment]
Updated docs in https://github.com/bolt/bolt-docs/commit/253427c0905d13966c22e0e5c5d24e545feaea34
