### ISSUE TITLE
Message: Template "firstuser/firstuser.twig" is not defined (). and /bolt/bolt/users/edit not found

### ISSUE THREAD

**Issue by hjacquir** [bolt/bolt#2441]
I encountered the error in the title on Apache 2.2.22

**Comment by hjacquir** [comment]
Here is the solution for this problem :
- in /etc/apache2/sites-available/default add a virtualhost like this

    <VirtualHost *:80>
        ServerName bolt.local
        RewriteEngine On
        DocumentRoot /var/www/bolt/
        <Directory /var/www/bolt/>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/bolt-error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/bolt-access.log combined
    </VirtualHost>

And into /etc/hosts create a host like this 
127.0.0.1 bolt.local

Restart apache 2 service and go to bolt.local

**Comment by lardi** [comment]
Can I do this on IIS, because I get same message on my local machine.
Thanks

**Comment by bobdenotter** [comment]
@hjacquir 's solution was very specific for his set-up. Basically, the issue here is that your webserver isn't configured correctly, and we can't tell you how to fix it from the outside. 

I do know that IIS is quite different from apache, so I'm not sure where or how you need to configure this in IIS.

**Comment by hjacquir** [comment]
Actually the solution I propose runs on Apache / 2.2.22 (Ubuntu 13.04 ), but you can always try with this configuration on IIS
