### ISSUE TITLE
Diet for lib.js

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2442]
In order to save some bytes I like to make a few suggestions:

* ~~**ua-parser**
Replace our clientside [ua-parser](https://github.com/bolt/bolt/tree/master/app/view/lib/ua-parser) with servserside [uap-php](https://github.com/ua-parser/uap-php).
_Saves ~10kb_~~

* **bootstrap-file-input**
[bootstrap-file-input](https://github.com/bolt/bolt/tree/master/app/view/lib/bootstrap-file-input) converts file inputs to buttons. But it seems that it's only used in file managment. In edit content we have buttons without it so it seems to be solved without that script.
_Saves ~2kb_

* **backbone**
Without having investigated it deeply I have the feeling we only use that lib as a object container without using any of the features that lib is made for (views, event handling, RESTful interface, …). Correct me if Im wrong there, but things could be rewritten with onboard JS to work like [obj-datetime.js](https://github.com/bolt/bolt/blob/master/app/view/lib/bolt/obj-datetime.js)
_Saves ~20kb_

* **jquery-formatdatetime**
[This one](https://github.com/bolt/bolt/tree/master/app/view/lib/jquery-formatdatetime-1.1.4) can probably replaced with functions from [moment.js](https://github.com/bolt/bolt/tree/master/app/view/lib/moment-2.8.3). Has to be investigated.
_Saves ~3kb_

* ~~**moment**
Using the version of [moment.js](https://github.com/bolt/bolt/tree/master/app/view/lib/moment-2.8.3) without locale data included and loading the locale dynamically gets us another request but the saved bytes probably justify that.
_Saves ~100kb_~~

* **underscore**
[It](https://github.com/bolt/bolt/tree/master/app/view/lib/underscore-1.7.0) seems to be only used in five cases in [upload-files.js](https://github.com/bolt/bolt/blob/master/app/view/lib/bolt/upload-files.js). Perhaps there's another piece of code for our usecase or it can be don with a few lines of JS.
_Saves ~16kb_

* **others**
  - Updating the libs perhaps saves some space?
  - Some libs are quite old. Perhaps another used lib has the functionality already built in now or it was just needed for now unsupported browsers?
  - Do we use/need all features included in our custom jQuery/jQuery-UI?
  - Reinventing the wheel is sometimes better if you only use 2% of the wheel you get

Suggestions, volunteers to assign to a task?!

**Comment by bobdenotter** [comment]
Lib.js has been dieted. :-)
