### ISSUE TITLE
Relations tab hidden when one way relation exists to a contenttype that has no relations defined.

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#2444]
I have no relationships defined for a contenttype A, but I defined a relationship to this contentype  A from another contentype B.  The Relationships tab for contenttype A  is hidden in this case.

**Comment by nealmarques** [comment]
I can get the tab to show up by just defining relations:  and then nothing under it, but that seems wrong.

**Comment by dpfavand** [comment]
See #2399 - is this the same issue?

**Comment by bobdenotter** [comment]
Yes, this seems to be a duplicate! :-)
