### ISSUE TITLE
Template Directory

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2445]
Currently all template paths are relative to the theme directory. I currently have a build system that puts all templates in `dist/templates/*.twig`. I've gotten used to typing 'dist/templates' in everything pertaining to templates, but it's not ideal. I think this will have more troubles if I am say, developing a public theme and this gets dropped into someone else's setup. Furthermore, this renders the template select field unusable as it can't detect any of my templates. I haven't had a need for it yet, but I imagine that when I do this will be really painful.

I am proposing a `template_directory` option in theme `config.yml` that sets the directory (in the theme directory) where the templates are stored. I think that the only internal stuff that would need to change is *some* references to `$this->app['paths']['themepath']` to `$this->app['paths']['templatepath']` where `$this->app['paths']['templatepath'] = $this->app['paths']['themepath'] + template_directory`.

Happy to do this myself, but I'm afraid I'll probably break something without knowing the ins and outs.

**Comment by bobdenotter** [comment]
This is basically what `theme` does already, right? 

```
# The theme to use. Be sure to copy the {theme_path}/base-2014 folder, and change the
# name here accordingly. Don't edit the templates in theme/base-2014, because
# they _will_ get updated in next releases
theme: base-2014
```

**Comment by Pinpickle** [comment]
Well the theme folder is generally also for storing static assets (js, css, images), and you have access to in your templates through `{{ paths.theme }}`. In my case, my templates are in `theme-name/dist/templates` but my js is in `theme-name/dist/js`. I want to keep them in separate directories because its cleaner (and is really the only feasible way to do it with cache-busting and build systems like Gulp). This means if I were to set my theme path to `theme-name/dist/templates`, I can no longer make references to my static files with `{{ paths.theme }}` in my templates. 

Well, I could with a `../` but that's pretty hackish.

**Comment by rarila** [comment]
Am I overseeing something?
```
theme: theme-name/dist
```
```
record_template: templates/entry.twig
listing_template: templates/listing.twig
``` 
```
src="{{ paths.theme }}/js/foo.js"
```

**Comment by Pinpickle** [comment]
Linking to the dist folder, now that is a good idea with the current system.

However, I still can't link to a template by its filename directly: `entry.twig`, which means it could break when dropped into websites with per-contenttype templates already established (not an issue for me at the moment because my themes are made specifically for their own site), but to my knowledge the template select field also doesn't work if the templates are in subdirectories (I've never seen them work with my current setup).

I want to have my cake and eat it to. Be able to have my templates in sub directories but write `template: entry.twig` or `{% include 'template.twig' %}`. If nothing else, its less typing, and if I change my directory structure - a lot of hassle saved.

I wouldn't call this a major issue at all, but it would be a nice addition.

**Comment by bobdenotter** [comment]
> I wouldn't call this a major issue at all, but it would be a nice addition.

If you think we can do this _without_ making it more complicated at all for people who don't need this feature, we should take it under consideration. ;-)

**Comment by Pinpickle** [comment]
> If you think we can do this without making it more complicated at all for people who don't need this feature, we should take it under consideration. ;-)

Definitely. If the template directory, by default, is the theme directory (an empty string), then everything operates as it is now. If someone then sets the template directory (which is relative to the theme directory), all operations pertaining to reading directories (specifying template files, template selectors, includes) will be in that directory.
