### ISSUE TITLE
Record excerpt includes fields that I don't want 

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2447]

**Comment by bobdenotter** [comment]
How would you propose to fix this? 

A workaround might be this: 

```
{{ (record.title ~ record.teaser ~ record.body)|excerpt(200) }}
```

**Comment by gwbonline** [comment]
Yes, that is true. I posted this issue before I found out myself that it works this way... Thanks anyway!

**Comment by bobdenotter** [comment]
No probs! Closing this issue, then. :-)
