### ISSUE TITLE
Filter for templateselect doesn't work

### ISSUE THREAD

**Issue by SlowFox089** [bolt/bolt#2448]
In order to let the filter field take effect for the templateselect in contenttypes.yml, the listTemplates-function in TwigExtensions should use the filter.

In my install I changed the listTemplate-function to:

        $finder = new Finder();
        if ($filter == "") {
           $filter='/^[a-zA-Z0-9]\V+\.twig$/';
        }
        $finder->files()
               ->in($this->app['paths']['themepath'])
               ->depth('== 0')
               ->name($filter)
               ->sortByName();

        $files = array();
        foreach ($finder as $file) {
            $name = $file->getFilename();
            $files[$name] = $name;
        }

        return $files;

**Comment by GawainLynch** [comment]
Whoops... My bad.

**Comment by bobdenotter** [comment]
> Whoops... My bad.

As in, you'll take this on?

**Comment by bobdenotter** [comment]
See #2477

**Comment by SlowFox089** [comment]
Updated my first post, because now I can use the suposed syntax in contenttypes.yml. Somehow I made a mistake the first time I tried. So now it should work with all options like mention in #2477.

**Comment by bobdenotter** [comment]
#2477 also fixes the issue, right? Or are you still having issues?

**Comment by GawainLynch** [comment]
Assuming fixed and closing.  Please re-open if problems are still there for you.
