### ISSUE TITLE
Composer install : command line interface

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2450]
I'm starting a new issue as a previous issue #2309 I opened was targeting multiple problems. 

The post install script does nothing about the app dir. Shouldn't the config, database, cache, resources directories be created and filled with files accordingly ?
When installing the web dir outside the root, there's no command line utility (nut) available.

**Comment by Intendit** [comment]
> The post install script does nothing about the app dir. Shouldn't the config, database, cache, resources directories be created and filled with files accordingly ?

I handle this by running a DB update and then chmodding the files right after the install, like so:

    git clone git://github.com/bolt/bolt.git bolt
    cd bolt
    curl -s http://getcomposer.org/installer | php
    php composer.phar install
    php app/nut database:update
    chmod -R 777 files/ app/database/ app/cache/ app/config/ theme/ extensions/

Not sure if it's a problem as long as one can fix it from the CLI.

**Comment by rossriley** [comment]
This should be fixed in #3419. Closing for now.
