### ISSUE TITLE
[UX] Upload errors aren't shown to user

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2455]
I just had an error uploading a file. A RuntimeException was thrown since files folder wasn't writable. However, this exception left the UI looking like the file was about to upload, instead of showing an error.
![screen shot 2015-01-12 at 2 50 58 pm](https://cloud.githubusercontent.com/assets/932566/5710785/992ab4ec-9a6a-11e4-9ba3-0d37ce051bb3.png)

**Comment by bobdenotter** [comment]
Yes, we should fix this. :-)
