### ISSUE TITLE
Fatal error with latest doctrine/dbal version

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2459]
![capture d ecran 2015-01-13 a 13 36 11](https://cloud.githubusercontent.com/assets/2526939/5720783/439b6bd8-9b29-11e4-8de6-3aef4c9e0022.png)

Version 2.5.1 of doctrine/dbal is throwing a fatal error.

**Comment by bobdenotter** [comment]
Any more info on this? When does this happen? Fresh install of Bolt? Which version? What Database?

**Comment by nlemoine** [comment]
First had the problem with an existing installation. I didn't want to post an unverified issue so I tried on a fresh install: `composer create-project bolt/composer-install <MYPROJECT> --prefer-dist`

Sorry for the lack of details, happens with sqllite. I just checked with mysql and happens to. 
It occurs on load whether a databse already exists or not. 

Try https://github.com/doctrine/dbal/tree/v2.5.1, you should see the error.

**Comment by bobdenotter** [comment]
Ah, didn't notice that 2.5.1 was a new version. I did a `composer install` and got Doctrine DBAL 2.5.1, and now I have the issue too. Will look into it!

**Comment by bobdenotter** [comment]
Found the issue.. Fix incoming! Thanks for noticing!

**Comment by bobdenotter** [comment]
Oh, wait.. I'm dumb. This issue was already fixed: 

https://github.com/bolt/bolt/commit/629ec1f3bf42a47fa488f7dd663c406ab97fa2d6

There'll be a version 2.0.3 very soon, with this fix included.

**Comment by nlemoine** [comment]
Thanks for the quick fix. When do you plan to release 2.0.3 ?

**Comment by bobdenotter** [comment]
Soon. Tomorrow or thursday most likely.

**Comment by nlemoine** [comment]
Great!
