### ISSUE TITLE
pager for taxonomy stays on first page.

### ISSUE THREAD

**Issue by mr-klaatu** [bolt/bolt#2462]
This seems to have popped up again (see #1725 and #1741)

1. http://bolt/categories/accommodation?page_category_accommodation=2 : FAILED - 1st page showing

2. http://bolt/categories/accommodation?page=2 : SUCCESS - paging works as expected.

As the pager only generates the 1st type of link, paging fails for me.

I am using Bolt V2.0.2

**Comment by bobdenotter** [comment]
Confirmed.. 

@rixbeck Could you take a look?

**Comment by rixbeck** [comment]
Acknowledged. On it.
