### ISSUE TITLE
Registering Extensions via Composer

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2464]
The problem is when extensions are added via composer (the same way bolt is installed with composer). The documentation instructs devs to add the `init.php` to their `composer.json`. When bootstrapping the application, Composer autoloads this file (since files are always executed up front) and the `$app` variable isn't defined and a fatal error is thrown.

I suggested creating a register function in `BaseExtension` as a shortcut to the current code in `init.php` which also does a null check.

```php
public static function register($app)
{
    if (!$app) {
        return;
    }
    $app['extensions']->register(new static($app));
}
```
```php
Extension::register($app ?: null);
```

I would argue this doesn't make testing harder as `register()` is just a shortcut.

----

@rossriley murmured something about adding another pass to extensions, not sure what he means, saying here for reference.

**Comment by CarsonF** [comment]
I know @rossriley hates statics. But they do have a place in alternative ways to create a class. I don't think it's right to register the extension upon creation (through constructor), but I do think it should be easy to do since registering the extension is the best use case. The less code the extension dev has to do to bootstrap their code the better.

Also I should note that `new static` isn't static, it's just so you don't have to hardcode the class name.

@rossriley Thoughts?

**Comment by rossriley** [comment]
Retiring this one too, the new loading system for extensions makes this redundant.
