### ISSUE TITLE
Filter related content by id not working

### ISSUE THREAD

**Issue by davidgenetic** [bolt/bolt#2469]
Just updated a site from v1.6 to v2 and had an issue with fetching related content.

It seems the method Content::related has a parameter $filterid which is not used anymore.
This worked in v1.6.

**Comment by bobdenotter** [comment]
I'll see if i can reproduce this! 

Do you have a code snippet of what you're trying to do?

**Comment by davidgenetic** [comment]
You can just take a look at the method and compare it with the one in v1.6.
$filterid is never used. So the method always returns all the related content.
