### ISSUE TITLE
How to make contenttype with just single record?

### ISSUE THREAD

**Issue by bianpratama** [bolt/bolt#2476]
I want to make backend menu for each "custom" page (e.g. about us, contact, et cetera). These content types need specific fields for each separate page.

How can I do this?

**Comment by bianpratama** [comment]
Or, how can I disable the overview page and "add" button for a contenttype. So it can directly be redirected to the record.

**Comment by bobdenotter** [comment]
Three options: 

- Add a "templateselect" field to your general pages contenttype, make a template for 'contact'
- Add a route for 'static page' route to routing.yml, and just create templates. (see the example at the bottom of that file
- Create a 'resources' contenttype, as described here: https://docs.bolt.cm/howto/resource-contenttype
