### ISSUE TITLE
CKEditor removes whitespace in <pre> tags

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2481]
- Set `wysiwyg->codesnippet` to true so you can add code snippets.
- Make a contenttype with an html field.
- Add a new record, and add some code (with indents) to the html.
- Click the source button in the editor after you add the code.
- Watch in horror as your indents mysteriously disappear

This looks to be an issue with Bolt's specific implementation of CKEditor because the [demo page](http://sdk.ckeditor.com/samples/codesnippet.html) for Code Snippet doesn't have this issue.

**Comment by GawainLynch** [comment]
Confirmed here!.

**Comment by bobdenotter** [comment]
This is due to codemirror (the plugin that does the syntax highlighting, when toggling to source code). I don't think we can fix this, without disabling codemirror, if somebody enables `codesnippet`.
