### ISSUE TITLE
How to modify and save contenttype data on preSave?

### ISSUE THREAD

**Issue by yrvn** [bolt/bolt#2484]
Hi, just started trying Bolt and after reading [Adding storage events](https://docs.bolt.cm/extensions/essentials#adding-storage-events) I created an extension for testing and wanted to modify the data of a contenttype on preSave with 
```
$event->getContent()->setValue('title', 'new title'); 
```
but the change isn't saved.  

Any idea? Thanks

**Comment by GawainLynch** [comment]
Here is an example of how I am doing it at the moment:

```php
use Bolt\Events\StorageEvent;
use Bolt\Events\StorageEvents;

class MyClass
{
    public function initialize() {
        $this->app['dispatcher']->addListener(StorageEvents::PRE_SAVE, array($this, 'hookPreSave'));
    }
    public function hookPreSave(StorageEvent $event)
    {
        // Get contenttype, ignore 'foo' and 'bar' types
        $contenttype = $event->getContentType();
        if (empty($contenttype) || !(
            $contenttype == 'foo' ||
            $contenttype == 'bar')) {
                return;
        }

        // Get the content
        $record = $event->getContent();

        // For this example, we'll just set the variables we need here
        $title = 'My Nice Stuff';
        $whiz = 'Swoosh!';
        $bang = 'Where was the KABOOM!?';

        // Updated values
        $values = array(
            'slug'  => String::slug($title, 128),
            'title'  => $title,
            'whiz'  => $whiz,
            'bang'  => $bang
        );

        // Merge over default/existing values
        $values = array_merge($record->values, $values);

        $record->setValues($values);
    }
}
```

**Comment by yrvn** [comment]
Thanks for the answer, but still I can't get this to work. This was what I was doing only that instead of doing the array_merge for $record->values I was just using setValue() for one of them.

Correct me if I'm wrong, I was looking at saveContent() in Storage.php

```
public function saveContent(\Bolt\Content $content, $comment = null)
{
    $contenttype = $content->contenttype;
    $fieldvalues = $content->values;

//...

if (! $this->inDispatcher && $this->app['dispatcher']->hasListeners(StorageEvents::PRE_SAVE)) {
    // Block dispatcher loops
    $this->inDispatcher = true;

    $event = new StorageEvent($content, $create);
    $this->app['dispatcher']->dispatch(StorageEvents::PRE_SAVE, $event);

    // Re-enable the dispather
    $this->inDispatcher = false;
}

//...
```

After dispatching the PRE_SAVE event and changing $content->values the variable $fieldvalues that is used later for saving doesn't reflect the changes. I think that adding a $fieldvalues = $content->values; inside that will fix it (tried and worked for me) but don't know if it's the correct approach.

**Comment by GawainLynch** [comment]
That indicates there is something wrong with the way the object(s) passed to StorageEvent are passed, or passing back changes.

**Comment by GawainLynch** [comment]
Oh wait, that might be the point you're making!  Either way, I shall look soon.

**Comment by GawainLynch** [comment]
Apologies for this taking as long as it did...  Wasn't an straightforward fix!

**Comment by yrvn** [comment]
Completely missed this, didn't get/missed the mail notification. Going to check this tomorrow.

Thank you!

**Comment by GawainLynch** [comment]
No stress, sorry again it took so long :grin:
