### ISSUE TITLE
Bolt is slowly when working on WampServer

### ISSUE THREAD

**Issue by lardi** [bolt/bolt#2496]
Hi,
I use WampServer to host Bolt in my windows PC.
It's slowly when browsing site pages, but it's fast in Admin pages.
Is this WampServer issue?
Thanks

**Comment by mike-anthony** [comment]
I have had several issues with Wamp in the past, and switched over to [XAMPP](https://www.apachefriends.org/index.html) a long time ago.

**Comment by bobdenotter** [comment]
Also, if you're not on 2.0.3, you should update to the latest version. See #2493
