### ISSUE TITLE
allowed file types config.yml update notice

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#2506]
Previous versions of Bolt had a config setting like so in a [string](http://symfony.com/doc/current/components/yaml/yaml_format.html#strings):  
```yaml
# File types that are acceptable for upload in either 'file' fields or through the 'files' screen.
accept_file_types: "gif|jpe?g|png|zip|tgz|txt|md|docx?|pdf|epub|xlsx?|pptx?|mp3|ogg|wav|m4a|mp4|m4v|ogv|wmv|avi|webm|svg"
```  
Bolt 2+ config for allowed filetypes is now a [yaml collection sequence](http://symfony.com/doc/current/components/yaml/yaml_format.html#collections)  
```yaml 
# The following is the default list of file-types that can be uploaded through the 'files' screen.
accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, webp, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]  
```  
This change might cause a slight headache if you update from a 1x install to a 2x install and want to add files to upload  like ```webp``` ````jxr``` or ```svgz``` files
Knowing me I skipped over somewhere where you all mentioned the update but I figured I'd file an issue in case it wasn't mentioned.

**Comment by bobdenotter** [comment]
We did mention this, when the change happened. Still, I can see how this is easy to overlook when you're upgrading and you don't go through the new `config.yml.dist` line by line. I don't know what'd be the best way to do anything about this now, if any. 
Going to leave this one open though, let's see if other people have the same issue.

**Comment by bobdenotter** [comment]
No problems came of this, that i know of, so i'm closing the issue.  Feel free to re-open, if you feel this is still an issue, and it should be worked on. :-)
