### ISSUE TITLE
Refactor out our home-baked reserved SQL keywords.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2507]
See http://www.doctrine-project.org/api/dbal/2.5/class-Doctrine.DBAL.Platforms.Keywords.KeywordList.html, as pointed out by @CarsonF

**Comment by CarsonF** [comment]
Just did a quick search... I don't think these are even being applied.

**Comment by bobdenotter** [comment]
I think only in one place: `src/Database/IntegrityChecker.php` around line 565.
