### ISSUE TITLE
Clear cache does not clear thumbs folder

### ISSUE THREAD

**Issue by magabriel** [bolt/bolt#2511]
Scenario:
- Bolt installed with composer and outside the web root.
- Config option `thumbnails/save_files` set to `true`.

Clearing the cache from admin does not clear the thumbs folder.

I think the culprit is this line in the `Cache::clearCache()` method, that is not taking into account the real location of the thumbs folder under the web root:

        // Clear the thumbs folder..
        $path = dirname(dirname(dirname(__DIR__))) . "/thumbs";
        $this->clearCacheHelper($path, '', $result);

Cheers.

**Comment by GawainLynch** [comment]
Fixed in #2512
