### ISSUE TITLE
Menu backend needs some tweaking

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2513]
Contenttypes with looong names looking ugly in menu. See screenshot.

![screen shot 2015-01-21 at 14 13 11](https://cloud.githubusercontent.com/assets/2750653/5836563/bc0fd85c-a177-11e4-8422-6a27c4dcb480.png)

**Comment by rarila** [comment]
Perhaps we should add css hyphenation, although browser support i. Bad. Have you tried to add a ``&shy;`` in the label definition?

**Comment by cdowdy** [comment]
like @rarila said hyphenation has fairly terrible browser support -> [caniuse.com hyphens](http://caniuse.com/#feat=css-hyphens). I just played around with it and I've tried a few things  

as above here is the current way its done. In the image you can see the text content flows out from the side menu:  
![normal](https://cloud.githubusercontent.com/assets/5969974/5858183/4034f692-a21f-11e4-93dc-e0386c82dec5.PNG)  

here is adding ```text-overflow: ellipsis;``` keeping the normal ```overflow: visible``` on ```a.menu-pop```  
![overflow_ellipsis](https://cloud.githubusercontent.com/assets/5969974/5858222/7d79bd76-a21f-11e4-8779-26a61ad58c42.PNG)  

here is adding ```word-wrap: break-word``` and keeping ```overflow: visible``` on ```a.menu-pop```  
![word-wrap_with_overflow](https://cloud.githubusercontent.com/assets/5969974/5858267/cdd10946-a21f-11e4-8daa-4b259d285e03.PNG)  

and the same word-wrap: break word but removing overflow from ```.menu-pop```  
![word-wrap_no_overflow](https://cloud.githubusercontent.com/assets/5969974/5858281/e0cc2ddc-a21f-11e4-87ea-af3891e3be32.PNG)  

I can try a few more things if you all would like a bit later and I haven't tested any of these really on the mobile side as a caveat

**Comment by cdowdy** [comment]
ok I've done some more... I think you all would like this one.. if it looks good I'll submit a pull:

I have a mixin to add ellipses added too [_secondary.scss](https://github.com/bolt/bolt/blob/master/app/view/sass/nav/_secondary.scss)  

results:  

__Desktop__  
![ellipses_mixin](https://cloud.githubusercontent.com/assets/5969974/5859086/b0925816-a225-11e4-8426-a399889a264a.PNG)  

__mobile__ (nexus 5 chrome emulator)  
![mobile_ellispses_mixin](https://cloud.githubusercontent.com/assets/5969974/5859094/bd49b90a-a225-11e4-9a7d-916feab3894c.PNG)  


This is all dependent on if you are ok with truncating it

**Comment by rarila** [comment]
Good question. I remember making some effort to make multiline menu entries possible. Btw, did you try the softhyphen in the label entry in contenttypes.xx_XX.yml? I'm a bit unoperatable at the moment as I'm moving my office and the IDE somehow doesn't run on tablet :-)

**Comment by bobdenotter** [comment]
Closed by #2528 

Rarila: Using ellipses is much prettier than hyphens, imho.

**Comment by rarila** [comment]
@bobdenotter not when you can only see 20% of text
What of the following (don`t had the time to think about a real world example that makes more sense – but don't forget that there are other languages out there besides english) you would prefer?

```
- Listofflowersthat-
arered
- Listofflowersthat-
aregreen
```
```
- Listofflowers…
- Listofflowers…
```

**Comment by bobdenotter** [comment]
I'm sure most of those can easily be rewritten to be more clear and consise. "Listofflowersthatarered" -> "Red Flowers". 

Let's keep it like this, and if it turns out to be an issue, we'll see then how we fix it.
