### ISSUE TITLE
Spice up our "Markdown" field. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2522]
Currently, our Markdown field is really just a `<textarea>`. We should add something like this: 

http://www.codingdrama.com/bootstrap-markdown/

**Comment by tobias2k** [comment]
Two issues worth thinking about:

1. Two different markdown implementations in different programming
languages means there is a realistic chance that the preview in the
backend (from bootstrap-markdown) won't match the frontend output (from
PHP's markdown implementation). Someone would have to look into the
state of affairs and decide whether the amount by which they diverge is
acceptable.
2. If, at any point, we decide to extend our markdown support with
Bolt-specific things, they will probably not be available in the
preview, unless we somehow manage to implement them twice and hook them
into bootstrap.

As an alternative, we could expose an async route that allows us to send
markdown to the server and get HTML back, and just wire that up with the
textarea and a preview panel next to it. (I've done it before, it's not
super complex).

On Wed, Jan 21, 2015 at 01:20:52PM -0800, Bob den Otter wrote:
> Currently, our Markdown field is really just a `<textarea>`. We should add something like this: 
> 
> http://www.codingdrama.com/bootstrap-markdown/
> 
>  
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2522

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by SahAssar** [comment]
What is the state of [commonmark](http://commonmark.org/) these days? Are the different libraries trying to stay compliant? Otherwise @tobias2k point regarding consistency between preview and final output might become a real issue.

**Comment by bobdenotter** [comment]
SahAssar: I _really_ like commonmark because it's close to spec. It's still very slow compared to our current parser, though. 
The both of you are correct though: If we should add something that provided 'live' previews of markdown, it should be accurate. Either the previews are ajaxy, so they are parsed by the same parser, or we have to be sure the serverside and clientside parser use the same engine.

**Comment by bobdenotter** [comment]
I really like this one: http://getuikit.com/docs/htmleditor.html#tab-mode

@carsonf likes https://stackedit.io/editor better.

**Comment by bobdenotter** [comment]
Fixed by #3225
