### ISSUE TITLE
ckeditor config language is not correct

### ISSUE THREAD

**Issue by webching** [bolt/bolt#2526]
set local:zh_CN in config.yml but ckeditor shows still in 'en'..

**Comment by rarila** [comment]
That's because it's simply not [there](https://github.com/bolt/bolt/tree/master/app/view/lib/ckeditor/lang)

**Comment by webching** [comment]
i added the file app/view/lib/ckeditor/lang/zh.js  as such:
CKEDITOR.lang['zh']={ ........... }

but still not work. 

tested ok if locale set to fr_FR or de_DE.. 

why

**Comment by rarila** [comment]
You have to add it to the [config](https://github.com/bolt/bolt/blob/master/app/view/lib/ckeditor/ckeditor.js). Search for ``CKEDITOR.lang.languages={"de":1,"en":1,"fr":1,"nl":1};``

**Comment by rarila** [comment]
Fixed by #2634
