### ISSUE TITLE
Low level errors look odd. Fix the HTML and/or CSS

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2539]
See screenshot: 
![screen shot 2015-01-24 at 16 29 59](https://cloud.githubusercontent.com/assets/1833361/5887841/85268dc4-a3e6-11e4-99c8-d3569cfc61ef.png)

**Comment by GawainLynch** [comment]
Or as it is in my tree :laughing: 
![bolt error handler](https://cloud.githubusercontent.com/assets/1427081/5887846/3f5ba9b2-a3de-11e4-8920-8ece3d60f7ac.png)
