### ISSUE TITLE
dashboard latest activity overflows

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#2561]
Bolt backend dashboard latest activity overflows from its parent containers:  
see image:
![bolt_activity](https://cloud.githubusercontent.com/assets/5969974/5892941/30b07c22-a4a0-11e4-8897-463eb0483a83.png)  

I've gone in and submitted a pull to fix this to look as follows:  
![bolt-activity-fixed](https://cloud.githubusercontent.com/assets/5969974/5892949/84a16382-a4a0-11e4-83f6-6c30981beef2.PNG)  

pull is here:  https://github.com/bolt/bolt/pull/2560

**Comment by GawainLynch** [comment]
@cdowdy, I am not sure if it is relevant to your Magnific Popup work...  But I know the Australian that we can blame for those errors in master :sheep: 

Background is that we branched `release/2.0` today and master is back on *that* wagon, and one of the first things (3rd really) that went in is the Bolt Log -> Monolog branch... and it needs work...  :pensive:

**Comment by cdowdy** [comment]
ahhhhh ok... I totally wasn't paying attention when I pushed the activity fix to my branch and by the time I realized it amended to the previous commit it was a bit late...  sorry about that !

**Comment by GawainLynch** [comment]
Apology is mine! Your contributions are always welcome :smiley_cat:

**Comment by bobdenotter** [comment]
Fixed by #2560
