### ISSUE TITLE
internal link wrong

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2577]
![screenshot - 260115 - 15 31 23](https://cloud.githubusercontent.com/assets/6233822/5905686/b82a2e70-a570-11e4-810e-18962f6cea57.png)

The internal link points wrong, should be http: //miweb.dev/bolt/file/edit/app/config/contenttypes.yml 
(currently is http://miweb.dev/bolt/file/edit/files/app/config/contenttypes.yml).
To reproduce the error, use a reserved word in contenttypes.yml and click on the link in the error message.

**Comment by bobdenotter** [comment]
Thanks for noticing! Fix is incoming.
