### ISSUE TITLE
Thumbnail preg_match() error

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2594]
![whoops there was an error](https://cloud.githubusercontent.com/assets/2750653/5918116/451c6dfc-a625-11e4-90e6-4d1841b9b610.png)
I just updated a Bolt 1.3.1 to 2.0.5.
No thumbs are being created (backend & frontend) and I get the following error:

preg_match() [<a href='function.preg-match'>function.preg-match</a>]: Compilation failed: unrecognized character after (?&lt; at offset 11

It only happens on one specific server. Does anyone know what happens here and how to fix this?

**Comment by bobdenotter** [comment]
screenshots!

**Comment by peterboorsma** [comment]
Updated with screenshot...

**Comment by bobdenotter** [comment]
Thanks! Now i see what happens. Will fix.

**Comment by rarila** [comment]
What's going on there? A  PCRE version compiled without named groups?

**Comment by peterboorsma** [comment]
El Cheapo Sh*t Hosting. That's what's going on there ;)

**Comment by rarila** [comment]
Would be perhaps worth a test:

```
 if (preg_match('#/thumbs/(\d+)x(\d+)([a-z]?)/?(.+)#', $path, $parsedRequest)) {
    $commands = $this->resizer->provides();
    if (isset($parsedRequest[3]) && array_key_exists($parsedRequest[3], $commands)) {
        $this->action = $commands[$parsedRequest[3]];
    } else {
        $this->action = 'crop';
    }
    $this->width = $parsedRequest[1];
    $this->height = $parsedRequest[2];
    $this->file = $parsedRequest[4];
}
```

Could it be the PHP version is < 5.2.2?

>5.2.2 	Named subpatterns now accept the syntax (?<name>) and (?'name') as well as (?P<name>). Previous versions accepted only (?P<name>).

**Comment by GawainLynch** [comment]
> Could it be the PHP version is < 5.2.2?

We'd throw a LowlevelException if that was the case, no?

**Comment by peterboorsma** [comment]
PHP Version 5.3.28

Command	'./configure' '--host=x86_64-redhat-linux-gnu' '--build=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/usr/com' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--cache-file=../config.cache' '--with-libdir=lib64' '--with-config-file-path=/etc' '--with-config-file-scan-dir=/etc/php.d' '--disable-debug' '--with-pic' '--disable-pcntl' '--disable-rpath' '--without-pear' '--with-bz2' '--with-exec-dir=/usr/bin' '--with-freetype-dir=/usr' '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--enable-gd-native-ttf' '--without-gdbm' '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr' '--with-openssl' '--with-pcre-regex=/usr' '--with-zlib' '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--enable-magic-quotes' '--enable-sockets' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--with-kerberos' '--enable-ucd-snmp-hack' '--enable-shmop' '--enable-calendar' '--without-sqlite' '--with-libxml-dir=/usr' '--enable-xml' '--with-system-tzdata' '--with-apxs2=/usr/sbin/apxs' '--without-mysql' '--without-gd' '--disable-dom' '--disable-dba' '--without-unixODBC' '--disable-pdo' '--disable-xmlreader' '--disable-xmlwriter' '--without-sqlite3' '--disable-phar' '--disable-fileinfo' '--disable-json' '--without-pspell' '--disable-wddx' '--without-curl' '--disable-posix' '--disable-sysvmsg' '--disable-sysvshm' '--disable-sysvsem'

**Comment by rarila** [comment]
ok, does the code above work?

**Comment by peterboorsma** [comment]
Yes, it works. Thank you!

**Comment by rarila** [comment]
I guess the pcre package on your system is just too old. Can you check what version of libpcre3 is installed on your system?

**Comment by peterboorsma** [comment]
How can I check hat?

**Comment by rarila** [comment]
Good question. Don't know Redhat. But I guess you wouldn't be able to update that anyway?!

**Comment by peterboorsma** [comment]
No, it's a client's cheap shared hosting account.

**Comment by rarila** [comment]
Here on debian I just started the package manager and listed packages with "libprce"

**Comment by bobdenotter** [comment]
I'd wager "Cheap-ass hosting" is equivalent to "NO SSH FOR YOU", in this case. ;-)

**Comment by bobdenotter** [comment]
> > Could it be the PHP version is < 5.2.2?
> We'd throw a LowlevelException if that was the case, no?

Yes. ^_^

**Comment by peterboorsma** [comment]
"We don't offer SSH because it is unsafe hosting" Yes

**Comment by rarila** [comment]
@peterboorsma Could you please look at the output of ``phpinfo()``? There you get a PCRE Library Version displayed. Would be interesting to know as named subpatterns are supported since feb. 2003.

**Comment by peterboorsma** [comment]
Did you mean this:

pcre

PCRE (Perl Compatible Regular Expressions) Support	enabled
PCRE Library Version	6.6 06-Feb-2006

Directive	Local Value	Master Value
pcre.backtrack_limit	1000000	1000000
pcre.recursion_limit	100000	100000

**Comment by rarila** [comment]
yes, thanks!

**Comment by rarila** [comment]
Ok, could you please test the following?

```php
 if (preg_match('#/thumbs/(?P<width>\d+)x(?P<height>\d+)(?P<action>[a-z]?)/?(?P<file>.+)#', $path, $parsedRequest)) {
    $commands = $this->resizer->provides();
    if (isset($parsedRequest['action']) && array_key_exists($parsedRequest['action'], $commands)) {
        $this->action = $commands[$parsedRequest['action']];
    } else {
        $this->action = 'crop';
    }
    $this->width = $parsedRequest['width'];
    $this->height = $parsedRequest['height'];
    $this->file = $parsedRequest['file'];
}
```

Would be nice if the old ``?P<`` form of named subpatterns would works, then we could at least stay with the named ones.

**Comment by peterboorsma** [comment]
Seems to work fine.

Replaced code with code above in ThumbnailResponder, emtied cache, checkend backend & frontend.

**Comment by rarila** [comment]
Thanks!
Ok, guess then I replace ``?<`` with ``?P<`` to make ppl with outdated pcre libs and the coder happy :-)
