### ISSUE TITLE
Turn extensions on/off

### ISSUE THREAD

**Issue by miguelavaqrod** [bolt/bolt#2607]
Hi all!

First of all, I've discovered bolt and I am so impressed that I can just give thanks to this great piece of software. I have deep PHP knowledge and I will try to contribute as much as I can to this project :-)

Just a first question... Is there any option to turn on/off extensions? I look for it but no luck...

Thanks in advance.
Miguel

**Comment by GawainLynch** [comment]
Welcome to our community, @miguelavaqrod :smile: 

> Is there any option to turn on/off extensions

Not presently is the short answer.

**Comment by miguelavaqrod** [comment]
Hi,

Nice to meet you! ;-)

Well, in that case, and as I need it for my next project (that I have decided to develop it using bolt) I will implement it, so I will be able to contribute.

See you all!

**Comment by bobdenotter** [comment]
Thinking about this.. perhaps there should be an option added to the `extensions` serction in `config.yml`. perhaps: 

```
extensions:
  site: 'https://extensions.bolt.cm/'
  stability: stable
  enabled: false
```

And disabling them altogether might be as simple as putting a well-placed `if` statement somewhere in `src/Extensions.php`.

**Comment by GawainLynch** [comment]
While that does make it a simple solution, is it something we want to be "all or nothing"?

**Comment by bobdenotter** [comment]
A simple 'all or nothing' switch might be enough for @miguelavaqrod's needs, and it's better than no switch. ^_^

**Comment by GawainLynch** [comment]
OK, incoming on feature/composer-api branch over lunch then.

**Comment by GawainLynch** [comment]
Included in changes wrapped up in #2614 and will appear in 2.1:

You can now globally disable extension loading in config.yml by setting:
```yaml
  extensions:
      enabled: true
```

**Comment by GawainLynch** [comment]
Ooops, corrected the `config.yml` example above.

**Comment by tobias2k** [comment]
I think it's important to distinguish between "extensions that are
currently installed" and "extensions that should be loaded".

Currently, the two are linked hard, such that any extension you install
will also be loaded at all times, but I don't see why we couldn't add a
simple little filter that loads only the specified extensions, even if
other extensions have been installed.

This could either be an optional entry in config.yml, pretty much what
we had in Bolt 1.6 (except that when it's absent, *all* installed
extensions are loaded), or a blacklist in config.yml (listing extensions
*not* to load), or something somewhere else that one could manage
through the extensions backend (and, ideally, nut).

Only problem with this that I can see right now would be that a
"disabled" extension would still be autoloaded when requested
explicitly, so it's possible to call its static methods, for example,
from elsewhere. Oh, and if at some point we get dependencies working,
and we have extensions depending on one another, strange things might
happen if you disable an extension that other depend upon.

On Thu, Jan 29, 2015 at 12:59:31AM -0800, Bob den Otter wrote:
> Thinking about this.. perhaps there should be an option added to the `extensions` serction in `config.yml`. perhaps: 
> 
> ```
> extensions:
>   site: 'https://extensions.bolt.cm/'
>   stability: stable
>   enabled: false
> ```
> 
> And disabling them altogether might be as simple as putting a well-placed `if` statement somewhere in `src/Extensions.php`.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2607#issuecomment-71990554

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by miguelavaqrod** [comment]
Hi!

Wow!! A few days offline (flu, arrggg) and you guys have taken my need into account, and try to achieve a solution.
I can say no more than THANKS for this great support!

What I planned to do is, in the currently installed extensions list,  "inserting" a new button in each extension so you can not only uninstall it (and config, read readme file...) but disable it.

To be honest, sometimes I think.. why disabling an extension.. just delete it. Maybe that's ok for normal use cases.
However, I want to create a complete bolt "package" with all possible extensions i will need in a future and turn them on/off depending of the webpage I am developing.
As all installed extensions are autoloaded, right now creating such package is not optimal in a resources point of view.

However, I am totally agree with @tobias2k thoughts... what if one extension depends on another?
Read all composer files to check for dependencies? Not optimal in my opinion...

So, I think better to just delete whatever extension you do not really need. More compact, less error prone...

Regards,
