### ISSUE TITLE
CKEditor seems to have misplaced some CSS: Ugly Times new roman, instead of the correct font.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2615]
See screenshot: 

![screenshot 2015-01-29 15 36 53](https://cloud.githubusercontent.com/assets/1833361/5959252/fa3df09a-a7cc-11e4-8143-0154e54da76b.png)

**Comment by GawainLynch** [comment]
Academic writers the world over are celebrating this bug! :fireworks:

**Comment by rossriley** [comment]
A style more befitting of lorem ipsum if you ask me.
