### ISSUE TITLE
String.prototype.subst does not correctly handle empty replacement value

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2625]
Currentlly for the Extend page we're using the new internal `String.prototype.subst` JavaScript function which seems to not want to behave, e.g.
```js
html += conf.item.subst({
                    // snip
                    '%THEME%': ext.type == 'bolt-theme' ? conf.theme_button : '',
                    // snip       
                    });
```

Where the string being substituted has an empty replacement, in the above example is not a `bolt-theme` type, the following occurs:
![subst-error](https://cloud.githubusercontent.com/assets/1427081/5973085/1b8093fe-a85c-11e4-810a-f8a2bae791c4.png)

...It is making Clippy :cry: 

The function in question is from `app/view/lib/bolt/start.js`:
```js
String.prototype.subst = function(replacements) {
    return this.replace(/%[A-Z][A-Z0-9_]+%/g, function (placeholder) {
        return replacements[placeholder] ? replacements[placeholder] : placeholder;
    });
};
```

**Comment by rarila** [comment]
I :lips: you to use the ``in`` operator, but you didn`t :ear:
:smile_cat:

**Comment by GawainLynch** [comment]
You kissed me?  Any wonder I missed the point about `in` :grin:
