### ISSUE TITLE
[RFC] Version numbers in view/lib/ on folders

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2628]
After this came up by @cdowdy in #2599 and some refactoring I did in Gruntfile.js came up with the idea of removing the versions from the folders and instead adding a ``Versions.md``. in ``view/lib/`` that lists the version numbers of all libs. That would still make it easy to compare if there are new versions and make it easier – although that was only a search/replace – to update. Just edit the version number one time.

As additional sugar we could add links there to the source of the libs that would even more ease the process. Also we could add some info there how update and if there's something special to care of.

Anyone against that approach?

**Comment by GawainLynch** [comment]
:+1:  from me.

Wondering if we shouldn't do the same with licences of said libraries.

**Comment by bobdenotter** [comment]
Yes, please remove the version numbers from the folders! :100:

**Comment by cdowdy** [comment]
this is also why I [mentioned earlier](https://github.com/bolt/bolt/issues/2585#issuecomment-71571454) using a package manager like [Bower](http://bower.io/) or the others.  

As a dev you'd just have to have bower installed. Seeing as how you already use grunt this shouldn't be a big issue. To update you'd just ```bower update``` then compile your scripts. All license info is still in the folder, version numbers in a json file or in your bower json file for all bower components and not on a folder or file name.   

I've started a branch few days ago [here](https://github.com/cdowdy/bolt/blob/convert-to-bower/app/view/bower.json) with bower if you'd like to possibly see how it may look.

**Comment by rarila** [comment]
@cdowdy I have some other changes in the pipeline and will do them first. Then we could have a look at it.

But we would have to be careful and have to check, if there were no changes made to the code and then the risk is higher, that some changes may break things. And then there's stuff like CKEditor, where we use a customized version.

Do we need this extra file or could we just use [package.json](https://github.com/cdowdy/bolt/blob/convert-to-bower/app/view/package.json) as it is done with moment.js there?

**Comment by cdowdy** [comment]
I did a quick (read extremely dirty ) dif against the files I placed into bower that I linked above. For instance I didn't include jquery hotkeys because that is a customized version. I also tried to include the current version used in Bolt and lock it to that version. Most of these in the bower json pull from their associated github   

Bower uses a bower.json to "hold" the dependencies. We could use the same package.json if you were to install those dependencies through NPM.  Instead of using ```bower install <package-name``` you'd just install like we currently do for a grunt plugin ```npm install <package-name> ```  . I don't know if many of these are available through npm though.     

As for versions you can lock it to a specific version like I did above for jquery -> [here](https://github.com/cdowdy/bolt/blob/convert-to-bower/app/view/bower.json#L14-15) to keep a library at the current version tested and working in Bolt. 

I have a ```.bowerrc``` file in that fork that tells bower to install to ```bower_components```. So it would be two extra files to add if you don't use npm like currently used for moment js

**Comment by cdowdy** [comment]
Here is a bit by the npm team on [managing dependencies with npm](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging). 

They also mention bower. This is mostly food for thought and whichever you choose to use should be what you core devs like and are comfortable with since you'll be the ones using it most.

**Comment by Pinpickle** [comment]
:+1: for using Bower. The only caveat is that there are the rare libraries that don't use Bower/don't play nicely with it (I'm looking at you, CKEditor with your variety of build options).

But dependency managers make life better - Bolt uses one for the backend so surely the client side code should follow suit?

**Comment by rarila** [comment]
@cdowdy Ok, the other stuff is done. Here we go…
Would you like me to add that bower stuff or do you want to add it yourself?

**Comment by cdowdy** [comment]
I'm away from my computer right now so if you have time and want to add it go for it! If not I can definitely get to it tomorrow (Monday).

**Comment by rarila** [comment]
Ok, didn't manage it until now…
So it's still open. Are you able to do the grunt integration? If not, you could do the bower part and I would integrate it then

**Comment by cdowdy** [comment]
alright.. I started updating the files to use bower, doing some diffs to see which files may have customizations and before I go any further I wanted to know a few things.  

Do we want to copy/create a folder in ```lib``` for files that don't have a minified version supplied by bower? For instance __bootbox__ doesn't supply a minified file for it. Should we just create the minifed file inside the bower folder or have a new bootbox directory with the minified file?  

If going that route should there be another grunt task inside ```uglify``` similar too?:  

```javascript  
uglify: {
   bower: {  
    options: {
      preserveComments: 'some'
    },
    files: [{
      expand: true,
      ext: '.min.js',
      src: [
        'bower_components/bootbox.js/bootbox.js',
        'bower_components/jquery.cookie/jquery.cookie.js',
        'bower_components/OTHER-BOWER-LIB',
        'bower_components/OTHER-BOWER-LIB',
      ],
      dest: 'lib'
   }]
  },
}  
```

If you'd like to take a look at it here is the current setup I have:  
__bower.json__
```javascript  
{
  "name": "bolt_bower_dependencies",
  "version": "0.0.1",
  "homepage": "https://github.com/bolt/bolt",
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "jquery": "1.11.2"
  },
  "devDependencies": {
//    hold off on moment .. currently installed with NPM
//    "moment": "~2.9.0",
    "magnific-popup": "~1.0.0",
    "bootbox.js": "https://github.com/makeusabrew/bootbox.git#~4.3.0",
    "jquery.cookie": "https://github.com/carhartl/jquery-cookie.git#~1.4.1",
//    "blueimp-file-upload": "https://github.com/blueimp/jQuery-File-Upload.git#~9.9.2",
    "jquery.formatDateTime": "https://github.com/agschwender/jquery.formatDateTime.git#~1.1.4",
    "jquery.tagcloud.js": "https://github.com/addywaddy/jquery.tagcloud.js.git",
    "underscore": "~1.7.0"
  }
}  
```
__.bowerrc__
```javascript  
{
  "directory": "bower_components"
}  
```

**Comment by rarila** [comment]
The minified files could either go into ``lib/tmp`` that would be cleaned up after the run again or we let uglify do the concat task (like in the prepareBootstrapJs target) if all needed files are there unminified. That would give us the chance to include a sourcemap.
