### ISSUE TITLE
Rouble sign converts into '?' after saving

### ISSUE THREAD

**Issue by grosslarnakh** [bolt/bolt#2648]
Bolt 2.0.5, updated from 1.6

Old entries contains rouble currency sign ("₽"), but after editing and re-saving it converts into "?"

Example:
![rouble-sign](https://cloud.githubusercontent.com/assets/508445/5988723/3a03845e-a97d-11e4-89a1-a3680c1fd7ce.jpg)

**Comment by GawainLynch** [comment]
What is the collation of the table set to?

**Comment by grosslarnakh** [comment]
utf8_unicode_ci

**Comment by GawainLynch** [comment]
Can not reproduce, this is working for me on 2.0.5, 2.0.6 and master.

**Comment by bobdenotter** [comment]
@grosslarnakh MySQL or SQLite?

**Comment by bobdenotter** [comment]
Also, is it only when re-opening existing records? Or does it also happen when you create a new record, insert some Rouble signs, save it, and then re-open it?

**Comment by grosslarnakh** [comment]
It happens also when I create new record.

Server: MySQL
Server Version: 5.5.35-1+wheezy1+mh1-log
Encoding: Unicode (UTF-8)

Table bolt_entries:
Table type: MyISAM
Default Character Set: utf8
Default Collation: utf8_unicode_ci

**Comment by GawainLynch** [comment]
If you look directly at the row in the database, does it should a '?' as well?  I just can't reproduce it here, with much the same set up (CentOS7 MySQL/MariaDB).  I even tested MyISAM & InnoDB tables for the sake of ruling that out too.

The only other thing I can think of is the `default_charset` setting in `php.ini`.

**Comment by dwr** [comment]
Your code breaks utf8 if mysql server default encoding is different, e. g. cp1251, see fix at https://github.com/bolt/bolt/pull/2804

You could read more about this problem here http://stackoverflow.com/questions/1566602/is-set-character-set-utf8-necessary

**Comment by GawainLynch** [comment]
Thank you!

**Comment by grosslarnakh** [comment]
dwr just fixed a bug on my server. 

Thanks to all of you!
