### ISSUE TITLE
Fix default theme

### ISSUE THREAD

**Issue by apatkinson** [bolt/bolt#2649]
The default theme does not work out of the box.

Example: go to `/showcase/home-blurb` and it shall error and complain about `record.twig` not found.

I believe this actually creates a different issue on the correctness of the error reporting. Whereby bolt will complain that it cannot find a twig file, when in actual fact the file in question is fine. It is trying to use a twig include on another file which cannot be found. This makes the error confusing.

**Comment by apatkinson** [comment]
I will create a PR for to fix the default theme out of the box.

**Comment by bobdenotter** [comment]
Fixed by #2650
