### ISSUE TITLE
Theme File Manager Not Respecting HTTPS

### ISSUE THREAD

**Issue by b4ndit** [bolt/bolt#2670]
When signed into the Bolt backend using HTTPS, navigating to bolt/files/theme and selecting a theme in the list will go from HTTPS to HTTP. 

Obviously this isn't ideal for security reasons since people using SSL/TLS would like to keep using it throughout the website. In my specific case, it resulted in a 403 Forbidden error because I restrict the backend to HTTPS-only to keep security as tight as possible.

I am using Bolt 2.0.5 upgraded from Bolt 2.0.2.

cookies_https_only and enforce_ssl are set to true.

Side question about enforce_ssl: how exactly does this setting work? Setting this to true does not seem to redirect me to the HTTPS version of the website, even when accessing the login page for the admin section in /bolt/. Instead, it seems that I cannot login over plain HTTP anymore. I put in the correct credentials repeatedly and it stays on the login page with no error being displayed each time.

Anyway, thanks for developing such a nice CMS. Besides a few quirks here and there, it works beautifully.

**Comment by bobdenotter** [comment]
Part of this confusion is fixed by #2726: Only 'enforce_ssl' is used now. We'll look into the rest of the issue.

**Comment by glasspelican** [comment]
can you update to 2.0.6 and see if the issue still exists, if so then #2703 didnt fully fix the problem

**Comment by b4ndit** [comment]
Updated to 2.0.6 and it now works as expected.
