### ISSUE TITLE
SQLite Check incorrect

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#2682]
As of this commit https://github.com/bolt/bolt/commit/7e16278f5a8e4d75cedc4942d9b18babb7c1eea6 the check for sqlite looks for `pdo_sqlite` rather than the original `sqlite`.

Needs to either check for both or revert since this breaks the default config.yml.dist

**Comment by GawainLynch** [comment]
I may need just coffee, but I am confused as to why this isn't breaking all DB checks.

In config.yml we ask for either `sqlite`, `mysql` or `postgres` for the `database: driver:` key.

In `LowlevelChecks::doDatabaseCheck()`:
```php
        $cfg = $this->config->app['config']->get('general/database');
        $driver = $cfg['driver'];
```

and then:
```php
        if ($driver == 'pdo_sqlite') {
[snip]
        if (!in_array($driver, array('pdo_mysql', 'pdo_pgsql'))) {
```

**Comment by rossriley** [comment]
The other checks won't run at all because the ifs will all evaluate to false, thus letting the config through I think.

**Comment by rossriley** [comment]
Cache invalidation problem... clean cache fixes it.
