### ISSUE TITLE
Backend crashes after e.g. "main configuration -> change something -> save"

### ISSUE THREAD

**Issue by piogasio** [bolt/bolt#2694]
Hi,

I seem to encounter a bug leading to crashing the back end.
When I edit something under e.g. main configuration or content types, the back end crashes.
The changes are being saved, but the site delivers following:

![edit file a config yml a bolt](https://cloud.githubusercontent.com/assets/10832958/6023294/1bf737d2-abc4-11e4-9a3e-b33aaa0d999a.png)

**Comment by piogasio** [comment]
Yes, it exists.

I installed Bolt 2.0.5, 2.0.0 and 1.6.13 new and the same problem occurs. So it seems not to work properly on Strato hosting.

**Comment by dmm1** [comment]
Did you check https://docs.bolt.cm/requirements with your Webspace?

I know Strato and if you have an "old" HostingPackage you run on "outdated" Servers e.g. PHP < 5.3 ....

**Comment by piogasio** [comment]
Yes, PHP 5.6 (can't go below 5.3), Mod_rewrite comes with Bolt in the .htaccess

**Comment by rarila** [comment]
@piogasio Looking at your screenshot I notice two things:

- UTF-8 characters are not displayed properly
- Fontsize in the left menu way too small

Perhaps the answer is sent in non UTF-8 encoding for any reason and that probably makes problems

**Comment by rarila** [comment]
@piogasio how did you install?

**Comment by bobdenotter** [comment]
After some tweaking and fiddling on @piogasio's hosting, i've narrowed it down to this line: 

https://github.com/bolt/bolt/blob/master/src/Application.php#L391

Quick fix, set the following in `config.yml`: 

```
debug: false
```

This will disable the debug toolbar, and will make the issue go away.. Will dig deeper when i have the chance.

**Comment by bobdenotter** [comment]
Let's see if somebody who knows more about the WebProfiler knows where to dig next: https://github.com/symfony/symfony/issues/13595

**Comment by piogasio** [comment]
@rarila I installed Bolt via FTP. The problem is that the content of the file is for some reason put before the doctype of the current html view :/

@bobdenotter Thanks Bob, it helps as a quick fix. For now I don't need the debug bar, so I can live with it. Thank you again for your time!

**Comment by bobdenotter** [comment]
Probably fixed in the meantime. Closing for now. See: symfony/symfony#1359
