### ISSUE TITLE
Vote system

### ISSUE THREAD

**Issue by 2plus** [bolt/bolt#2698]
Is there any extension that would allow a vote on the entries and display depending on the amount?

**Comment by dmm1** [comment]
Imho no, you find all current working extensions here https://extensions.bolt.cm/

**Comment by GawainLynch** [comment]
Yes, what @dmm1 said.

The closest thing that might be of some use would be the [RateIt](https://extensions.bolt.cm/view/5d137130-4ab8-4e75-9d58-43f3f99c5a5a) extension.

**Comment by 2plus** [comment]
@dmm1 @GawainLynch Thanks for your answers.
