### ISSUE TITLE
[RFE] Show path to file in "uploaded files"

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#2714]
It is sometimes handy to let editors link directly to a downloadable file from a HTML field. It would help to show the complete link to a file (in a copy-paste-able way) in the "uploaded files" section, also for communication purposes. It's probably easy to build (I guess).

I'm not sure what would be the best option, probably

```
 /files/2015-01/importantdownload.pdf
```

Maybe there's something to say in favour of

```
//www.mysite.eu/files/2015-01/importantdownload.pdf
```

**Comment by GDmac** [comment]
mentioning #2306

**Comment by SahAssar** [comment]
I was thinking of solving this by doing something like this instead:

![untitled](https://cloud.githubusercontent.com/assets/5096632/12696246/9ebfa682-c765-11e5-9970-cda8294441e8.png)

That would require we include something like [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard), but I think that might be useful in other places anyway.

@rarila Thoughts on including ZeroClipboard with bolt?

**Comment by rarila** [comment]
@SahAssar no, pls no flash. We had [that](https://www.npmjs.com/package/clipboard) already [in](https://github.com/bolt/bolt/commit/e6ef1dfb899be2fc8dccf78016dee1b116c8acb4) a while ago for slugs.

**Comment by SahAssar** [comment]
@rarila Sorry, just so I understand, would you be okay with reintroducing [clipboard](https://www.npmjs.com/package/clipboard) since it doesn't have a flash dependency?

**Comment by rarila** [comment]
@SahAssar At least it looks better than the other.
Are there still people out there in 2016 having Flash installed? ;-)

**Comment by SahAssar** [comment]
@rarila haha, I basically just remembered the name from way back when I last had to use a clipboard polyfill.

**Comment by lenvanessen** [comment]
How about: https://clipboardjs.com/

We use it for marketplace as wel i believe

**Comment by SahAssar** [comment]
This seems like another one of those issues that we will get to sooner or later, but it won't be because of this. Closing due to lack of progress/interest.
