### ISSUE TITLE
Customise which columns are displayed in backend?

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2725]
I struggled to find any docs on this, but I thought it would be a feature that would have already be implemented.

Is it possible to change the columns that are visible when you are viewing a listing for a contenttype in the backend? This is especially necessary when the default sorting is a column which is not visible by default.

**Comment by rarila** [comment]
You can even have complete control about whwt and how it is displayed using [custom listings](https://github.com/bolt/bolt/blob/master/app/view/twig/custom/listing/pages.twig.dist).

**Comment by Pinpickle** [comment]
While custom templates are good for really shaking up how things are displayed, it's a lot of effort to go through just to change what columns are displayed. Surely on the list of possible features to add, could be a `columns` option for overriding the default in contenttypes?
