### ISSUE TITLE
No thumbnail images

### ISSUE THREAD

**Issue by sibputnik** [bolt/bolt#2746]
Hi! I have release 2.0.6 and it not show thumbnails of images. It have take it from thumbs, but folder is not created. I make this folder, but it becomes empty, and thumbnails not shown. 

I have this html (empty installation):
```html
<article>
<h1>Addidisti ad extremum etiam indoctum fuisse.</h1>
<div class="large-5 columns imageholder">
<a href="/files/blur-flowers-home-1093.jpg">ev
<img src="/thumbs/696x400c/blur-flowers-home-1093.jpg"/>
</a>
</div>
```
As u can see, image must be in `<img src="/thumbs/696x400c/blur-flowers-home-1093.jpg"/>`, but folder is empty

**Comment by sibputnik** [comment]
hey.... I can't add html (((

**Comment by sibputnik** [comment]
img src="/thumbs/696x400c/blur-flowers-home-1093.jpg"

**Comment by sibputnik** [comment]
thubnails was in 2.0.5, but none of them in 2.0.6

**Comment by bobdenotter** [comment]
hi @sibputnik you can add HTML in here. Click the "[Markdown supported](https://guides.github.com/features/mastering-markdown/)" link to find out how. Could you fix up the issue, so we can see what's going on better. Also, please post screenshots, and if possible a link where we can see this happening? 

Do you get an error if you right-click an image, and open it in a new tab? If so, please post a screenshot of that too.

**Comment by westerworld** [comment]
I have had simular issues recently.
With help from @bobdenotter I made sure that in my php.ini this extension was included:
extension=php_fileinfo.dll

I also raised my memory limits and filesize upload by adding these lines at the top of my .htaccess:
# Modify PHP settings:
php_value memory_limit 128M
php_value max_execution_time 1800
php_value max_input_time 1800
php_value post_max_size 40M
php_value upload_max_filesize 40M

These may be a bit over the top but for images of modern smartphones the 
default php_value upload_max_filesize limit of 2MB seemes a bit too low :)

Hope this helps.

**Comment by bobdenotter** [comment]
This seems to be resoved, closing. Feel free to re-open, if you feel this is still an issue, and it should be worked on. :-)
