### ISSUE TITLE
Extensions does not work

### ISSUE THREAD

**Issue by djoeybodenstaff** [bolt/bolt#2748]
On several Bolt websites hosted by Dutch hosting provider Antagonist is the extensions section not working. On one instal with an older php version(5.3 I think), I get a infinite loop with ' undefined' variables. The extensions are working here, but when I want to instal another one it's saying.
Fatal error:  Class 'Composer\Plugin\PluginEvents' not found in /home/deb35513/domains/djoeybodenstaff.nl/public_html/vendor/composer/composer/src/Composer/Command/RequireCommand.php on line 133

On another instal the extensions are not working(php 5.5) and when I try to instal something, it's saying:
[ErrorException] 
proc_get_status() has been disabled for security reasons 

Does someone has a solution for this problem?
Thanks in advance!

**Comment by GawainLynch** [comment]
Yes.  These are due to restrictions in-place by your provider.

We have heavily changed the way we use the Composer API for the upcoming 2.1 and this should resolve these issues.

**Comment by djoeybodenstaff** [comment]
Okay, That's fine. When is it going to be released?

**Comment by GawainLynch** [comment]
We hope to get the first beta out this week as we started feature freeze on Monday. So we're aiming for early to mid-March, earlier or later depending on how many bugs turn up in testing.

**Comment by djoeybodenstaff** [comment]
Okay, so until then my extensions are not working?

Met vriendelijke groet,
Djoey Bodenstaff

**Comment by GawainLynch** [comment]
Unfortunately, yes, unless you want to run the master branch.  Which I wouldn't recommend just yet.  We need more testing, and some PRs merged, before we are ready for a beta that I would use.

As I mentioned, some hosting providers are very tight on what they will allow and yours seems to be one of them.  We've done a massive amount of work to try and workaround this in the upcoming v2.1, and if you do have time and willingness, it would be really awesome if (later this week) you could set up a test site on Antagonist with the soon to be released beta and give us feedback.  

We *will* do our best fix this! :+1:

**Comment by bobdenotter** [comment]
> Okay, so until then my extensions are not working?

Whichever comes first: We release Bolt 2.1, or you stop using crappy cheap-ass hosting. ;-)

**Comment by djoeybodenstaff** [comment]
Hahaha, okay your right:) Although most of the time I'm very happy with my hoster(Antagonist) and I don't have stakes in them...

**Comment by GawainLynch** [comment]
Closing as addressed in upcoming 2.1.  Please reopen if issues persist after upgrade to 2.1
