### ISSUE TITLE
bug: bolt.locale not defined

### ISSUE THREAD

**Issue by Umbrielsama** [bolt/bolt#2749]
I'm working with default de_DE setup, but on some (backend) pages I got the JavaScript error 
*Uncaught TypeError: Cannot read property 'long' of undefined*

This is caused by 
/app/twig/_base/_page.twig line 110
```HTML
<script src="{{ paths.app }}view/js/bolt.min.js" data-config="{{ bconfig|json_encode }}" data-jsdata="{{ app.jsdata|json_encode }}"></script>
```
json_encode has also double quoted keys and values, so the result is invalid html, the data-value is invalid.

Please change to single quotes!
```HTML
<script src="{{ paths.app }}view/js/bolt.min.js" data-config='{{ bconfig|json_encode }}' data-jsdata='{{ app.jsdata|json_encode }}'></script>
```

**Comment by rarila** [comment]
Not a Good idea. Think of ``'`` in some of the strings.

Correct would be 
```twig
{{ bconfig|json_encode|escape('html_attr') }}
```
Thought the auto escaper would do the trick

**Comment by Umbrielsama** [comment]
Just updated to version 2.0.6 and cleared cache, now it's correctly parsed.

**Comment by GawainLynch** [comment]
Cool, closing then.  Please re-open if problems arise.

**Comment by rarila** [comment]
:+1: for the auto escaper
