### ISSUE TITLE
Youtube video's are broken in 'preview'.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2752]
They work fine if you save a record, and go to the saved page, but they do not work when clicking 'preview'. Which is weird.

**Comment by Mikescops** [comment]
When you preview the post the src tag of the iframe is not fill in ->

![Preview Post](http://puu.sh/fDka3/6c4a78a6c0.png)

whereas in the published post ->

![Published Post](http://puu.sh/fDkfx/1a70127b76.png)

**Comment by Mikescops** [comment]
The fact is the preview post is not a "real" page. 
Moreover this error seams to be link to that : 
![error](http://puu.sh/fDkxB/bae9339362.png)

**Comment by bobdenotter** [comment]
In `app/src/frontend.php`, in function `preview()`, around line 228, you will see: 

```
        $app['twig']->addGlobal('record', $content);
        $app['twig']->addGlobal($contenttype['singular_slug'], $content);

        return self::render($app, $template, $content->getTitle());
```

Change this to: 

```
        $app['twig']->addGlobal('record', $content);
        $app['twig']->addGlobal($contenttype['singular_slug'], $content);

        header("X-XSS-Protection: 0");

        return self::render($app, $template, $content->getTitle());
```

And it will work. In the meantime, we will consider if this has any unforeseen security implications.
