### ISSUE TITLE
After disabled a user, exception :/

### ISSUE THREAD

**Issue by jirimedved** [bolt/bolt#2763]
Hello,
after disabled a user and reload his page -> exception ...

<pre>
An exception has been thrown during the rendering of a template ("You must be logged in to use this.") in "dashboard/_aside.twig" at line 23.</pre>

**Comment by bobdenotter** [comment]
I'm not exactly following what's happening. Can we get a screenshot? Which version of Bolt? What do you mean by "his page"?

**Comment by GawainLynch** [comment]
It occurs if you disable yourself in the backend.  Just reproduced with master, and I doubt it is any different with stable.

**Comment by jirimedved** [comment]
![screenshot_4oikxi](https://cloud.githubusercontent.com/assets/1313662/6098437/aa2082fc-afde-11e4-8c37-b23f95bff80b.png)

**Comment by jirimedved** [comment]
@GawainLynch Hi, your fix does not solve this exception (screenshot). If the administrator has blocked another registered user and he, for example, reload the page, he gets this exception. Next reload the page it redirects to login. Sorry for my English.

**Comment by GawainLynch** [comment]
Yeah, I did think about this in bed last night...  Does that mean I eat & sleep Bolt?

Let me have another attempt.

**Comment by GawainLynch** [comment]
@jirimedved I have updated #2764 today, which is queued for master.  I am not sure about backporting the changes to 2.0 though as they are a bit invasive… @bobdenotter?

**Comment by bobdenotter** [comment]
Nope. :-)

**Comment by CarsonF** [comment]
I'm still seeing this occasionally. It happens through an async route, through a twig render. Somehow the check that fixes this is getting skipped and the redirect is not happening. I can't consistently reproduce though
