### ISSUE TITLE
Typos in contenttypes.yml.dist

### ISSUE THREAD

**Issue by westerworld** [bolt/bolt#2767]
Hi there,

I am desperately trying to find and invest more time into learing and understanding Bolt.
Reading a lot of the very good documentation and reading the extensive comments inside the example files.

Seems you guys are striving for perfection. That's good.
So, I want to make a small contribution to this quest for perfection.

In the default contenttypes.yml.dist (Bolt206) on line 172 it says:
postfix: "By selecting an Entry, you're creating a di-directional relationshop to that Entry."

I think it must read: "bi-directional relationship" or please educate me on what "di-directional" and a "relationshop" might be... 

Greetings for now,
Harm Wester

**Comment by GawainLynch** [comment]
First thing in the morning this is something of a welcome to start my di-day. You seem like the sort of person that is going to develop a good working relationshop with this community :laughing: 

Fixed in mater and release/2.0 now...  It will make it into 2.0.7 and 2.1.0 :heavy_check_mark:

**Comment by tobias2k** [comment]
Way to make a typo in a commit message for fixing typos...

On Sun, Feb 08, 2015 at 10:35:48PM -0800, Gawain Lynch wrote:
> First thing in the morning this is something of a welcome to start my di-day. You seem like the sort of person that is going to develop a good working relationshop with this community :laughing: 
> 
> Fixed in mater and release/2.0 now...  It will make it into 2.0.7 and 2.1.0 :heavy_check_mark: 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2767#issuecomment-73463582

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GawainLynch** [comment]
> Way to make a typo in a commit message for fixing typos...

Drink some coffee, @tobias2k… Joke went sailing :grin:

**Comment by tobias2k** [comment]
I wasn't talking about the intentional one ;)

"mater"...

On Mon, Feb 09, 2015 at 12:37:42AM -0800, Gawain Lynch wrote:
> > Way to make a typo in a commit message for fixing typos...
> 
> Drink some coffee, @tobias2k… Joke went sailing :grin: 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2767#issuecomment-73473528

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GawainLynch** [comment]
Drink some coffee, @GawainLynch… Obvious went sailing.

**Comment by westerworld** [comment]
Still wondering what a relationshop might have been though...
