### ISSUE TITLE
[RFC] Centralise database table names (2.2)

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2773]
Currently we are doing this everywhere:
```php
$prefix = $app['config']->get('general/database/prefix', 'bolt_');
$tablename = $prefix . 'foo';
```

Proposal:
```php
// System tables
$userTableName = $app['db.tables']->system()->get('users')

// Contenttype tables
$entriesTableName = $app['db.tables']->contenttype()->get('entries')

// Extension defined tables (can, obviously be multiple talbes)
$clippyLogTableName = $app['db.tables']->extension()->get('clippy', 'log')
```

…or similar.

**Comment by rarila** [comment]
:+1:

**Comment by tobias2k** [comment]
I would prefer roughly redesigning the entire storage layer first, then
work towards that design, rather than fixing problems one by one as they
arise.

That said, I'd suggest an API closer to this:

    $entriesTableName = $app['db.schema']->getTable('entries')->getTableName();
    $usersTableName = $app['db.schema']->getSystemTable('users')->getTableName();

...and also stuff like this:

    $tbl = $app['db.schema']->getTable('entries');
    if ($tbl->hasColumn('teaser')) {
        $previewColumnName = $tbl->getColumn('teaser')->getColumnName();
    }
    else {
        $previewColumnName = false;
    }

On Mon, Feb 09, 2015 at 11:42:35PM -0800, Gawain Lynch wrote:
> Currently we are doing this everywhere:
> ```php
> $prefix = $app['config']->get('general/database/prefix', 'bolt_');
> $tablename = $prefix . 'foo';
> ```
> 
> Proposal:
> ```php
> // System tables
> $userTableName = $app['db.tables']->system()->get('users')
> 
> // Contenttype tables
> $entriesTableName = $app['db.tables']->contenttype()->get('entries')
> 
> // Extension defined tables (can, obviously be multiple talbes)
> $clippyLogTableName = $app['db.tables']->extension()->get('clippy', 'log')
> ```
> 
> …or similar.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2773

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GawainLynch** [comment]
> I would prefer roughly redesigning the entire storage layer first, then work towards that design

That is slated for 2.2 anyway.

> That said, I'd suggest an API closer to this:

I was hoping for some brilliance like this from you, awesome :+1:

**Comment by tobias2k** [comment]
On Tue, Feb 10, 2015 at 12:48:07AM -0800, Gawain Lynch wrote:
> > I would prefer roughly redesigning the entire storage layer first,
> > then work towards that design
> 
> That is slated for 2.2 anyway.

I said "redesign", not "rewrite". When writing stuff like this, it's
good to know where we're headed to avoid making things worse. Of course
we're not casually rewriting everything.

**Comment by GawainLynch** [comment]
> I said "redesign", not "rewrite". 

Yes, and @rossriley and I are planning to put our heads together on this soon before writing code.  Does that not count as "design"?

**Comment by tobias2k** [comment]
On Tue, Feb 10, 2015 at 01:01:55AM -0800, Gawain Lynch wrote:
> > I said "redesign", not "rewrite". 
> 
> Yes, and @rossriley and I are planning to put our heads together on this soon before writing code.  Does that not count as "design"?

sure does.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2773#issuecomment-73665364

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by CarsonF** [comment]
DBAL has what @tobias2k is suggesting if we want to use that?

**Comment by GawainLynch** [comment]
It does and we do, it is more being able to just get the damn table names

**Comment by GawainLynch** [comment]
Taken care of by @rossriley in the upcoming 2.3 storage work.
