### ISSUE TITLE
Excessive error messages when template isn't found

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#2774]
![bolt-theme-does-not-exist](https://cloud.githubusercontent.com/assets/5096632/6128752/f5c41b82-b138-11e4-949a-3bd1dd3b8859.png)

The sheer amount of errors when a theme isn't found might be a bit excessive...

To recreate: set theme to something that isn't a theme in config.yml and save.

This is Bolt 2.1.0 - alpha2 running on Apache 2.4.7 with php 5.5.9-1.

**Comment by GawainLynch** [comment]
Driving me nuts too :+1:

**Comment by CarsonF** [comment]
Who could've done this???

**Comment by bobdenotter** [comment]
Perhaps a simple "only output this Flash message if it's different than the last one" would already make a huge difference? :-)

**Comment by CarsonF** [comment]
Oh in the template? That's not a bad idea. But that seems like a bandaid to me

**Comment by GawainLynch** [comment]
That is exactly what I have been trying to get to for the last 2 hours…  Someone keeps debating on IRC though.

**Comment by CarsonF** [comment]
You know this is probably the same async bug as before. The method is called for every async request, but only emptied and displayed on backend requests.

**Comment by GawainLynch** [comment]
The flood, yes, but we shouldn't behave like this regardless.

**Comment by bobdenotter** [comment]
I'd say "both" :-)

**Comment by CarsonF** [comment]
I'd say this is highlighting problems though. Do we want to be doing those checks and displaying errors if we can't do anything about them?

**Comment by GawainLynch** [comment]
> Do we want to be doing those checks and displaying errors if we can't do anything about them?

Yes, or course we want to report the error.  Bolt code might not be able to address something like this, but the end user/administrator/developer most likely can and failing silently is just unfriendly… So is flooding them.

I am still getting multiple messages from synchronous routes though, so not calling this fixed yet!

**Comment by CarsonF** [comment]
I meant do we want to be doing these checks if we aren't going to be displaying the errors that come from them. 

Just saying this highlights stuff we could be "doing wrong" and removing the duplicates in twig hides that

**Comment by GawainLynch** [comment]
Then we should log them.  We shouldn't flood users like this though.

**Comment by CarsonF** [comment]
Would logging them make it clear when it is happening? Like repeatedly when it is unnecessary? 

I agree we shouldn't flood users. This still feels like a bandaid though

**Comment by GawainLynch** [comment]
It is irrelevant. You're approaching the problem like a developer, something we coders are prone to do. An end user would see something like in the screen shot above and recoil in fear… Either thinking something was very wrong that they didn't understand, or that the developers of this "Bolt thing" don't understand them.

See the [second point in the manifesto](https://docs.bolt.cm/manifesto).

**Comment by CarsonF** [comment]
Fair point! Thanks for the perspective :+1:
