### ISSUE TITLE
[RFC/Refactor] Making Fields Dynamically Addable

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2781]
Currently any fields that require JavaScript, naturally, are all initialised when the record editing page is loaded. If people want "repeaters" or "lists" or "arrays" as per #2261, then there needs to be the ability to add these fields on the fly, JavaScript included.

~~This will of course require a lot of refactoring to allow a field to be initialised without interfering with anything that is already functioning on the page. I was wondering if anyone had any opinion on exactly how this could be accomplished? I'm supposing that Backbone could be leveraged somehow, but I have no experience with it. Other options are the more feature rich JS UI libraries like React or Angular but that's a whole lot of bulk to add to Bolt for what is, at the moment, a smaller feature set (though enabling the entire UI through something like that would be very, very cool).~~

I'm proposing a method of doing this now.

Each field type should have its own (backbone?) model behind it, managing all fields of that type - adding events mainly. There will also be a global field manager that manages all fields. This already exists, it's the Editcontent module.

Each field manager will extend off one base field manager that has the following methods:

```js
FieldManager.prototype.add = function(element[, options...]) { }; // Return reference to field object
FieldManager.prototype.remove = function(element/field object) { };
FieldManager.prototype.all = function() { }; // Returns array of field objects
```

Any fields that don't use JS will just be added to the base FieldManager so all references are stored. In the add function is where all of the JS is initialised for a field (again, mainly adding events).

A field object is bound to an element in its constructor, and is added through the field manager:

```js
ImageFieldManager.add(element[, options...]);
```

We bind every kind of field type to a manager

```js
EditContent.fieldManagers = {
    text: FieldManager,
    textarea: FieldManager,
    html: HTMLFieldManager,
    image: ImageFieldManager
    // etc...
};
```

Every initial field will have a `data-fieldtype` attribute set to the field type. We can keep using some kind of `data-config` but standardise it in the same element as the `data-fieldtype`. Then using jQuery...

```js
$('.form-group').each(function() {
    var fieldtype = $(this).data('fieldtype');
    var config = $(this).data('config') || { };
    EditContent.fieldManagers[fieldtype].add(this, config);
});
```

And then if we want to add a new fieldtype in the middle of an editing session, we can add the HTML and just create it.

Ping @rarila, does this look good to you?

**Comment by bobdenotter** [comment]
We've been talking about this for a bit on IRC (which you should join, btw ;-) ) not too long ago.. 

Basically, we do realise we will need _some_ way to handle these things. Like, for example with [requirejs](http://requirejs.org/). However I would like it if we had one solution that would also manage this  for CSS, and not just JS. 

We had this issue with multiple `geolocation` fields in one record, which was fixed like this: https://github.com/bolt/bolt/commit/8f3d9185de54f71d4a4784a815068b13464b2bdb

This is obviously not the optimal way to fix this, so we're still thinking about a solution.

**Comment by Pinpickle** [comment]
I think adding JS and CSS is not so much of a problem - that could be done in a similar way to how extensions are adding custom scripts, couldn't it?

What I'm concerned about is adding a field after the browser has loaded and initialised everything.

I want to join in the IRC chats! GMT+12 in New Zealand, though, isn't very compatible with your timezone in the Netherlands.

**Comment by SahAssar** [comment]
As this is now tracked in #4286 (for repeatable fields) I'm going to close this, hopefully I'm not stepping on any toes here :)
