### ISSUE TITLE
contenttypes.nl_NL.yml lost

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2782]
I'm almost sure it lived [here](https://github.com/bolt/bolt/tree/master/app/resources/translations/nl_NL) a while ago. Who eat it?

**Comment by rarila** [comment]
Hmm
```shell
git log --diff-filter=D --summary | grep delete
```
founds nothing. Could it be, that it was never there? Unbelievable!

**Comment by GawainLynch** [comment]
Also according to this, it never existed either.
```bash
for commit in $(git log | grep commit | cut -d' ' -f2); do
    if [ -f 'app/resources/translations/nl_NL/contenttypes.nl_NL.yml' ]; then
        echo "Appears in $commit";
        exit 1
    fi
done
```

**Comment by rarila** [comment]
@GawainLynch any idea how to get some dutch people in our team? ;-)

**Comment by PixelNL** [comment]
i can make the translations

**Comment by rarila** [comment]
@PixelNL You're welcome :-) :tada:

**Comment by PixelNL** [comment]
# app/resources/translations/nl_NL/contenttypes.nl_NL.yml –

# Warning: Translations are in the process of being moved to a new keyword-based translation
#          at the moment. This is an ongoing process. Translations currently in the
#          repository are automatically mapped to the new scheme. Be aware that there
#          can be a race condition between that process and your PR so that it's
#          eventually necessary to remap your translations. If you're planning on
#          updating your translations, it's best to ask on IRC to time your contribution
#          in order to prevent merge conflicts.

#  no unused messages
#  no untranslated messages
#   1 untranslated keyword based messages
#  no translations
# 102 keyword based translations

#--- 1 untranslated keyword based messages ------------------------------------

"contenttypes.pages.group.content":  "Inhoud"

#--- 102 keyword based translations -------------------------------------------

contenttypes:
    entries:
        description: "Het ** Artikelen ** conntentype kan worden gebruikt voor dingen zoals nieuws of blogposts. Ze hebben een subkop en hebben velden voor afbeeldingen en video.  Wijzig de contenttypes.yml om dit aan te passen. Wijzig het bestand`contenttypes.yml` in de folder `app/config/`, gebruik makende van editor van jouw keuze,  of door naar 'Configuratie' =>  'Contenttypen' te gaan in het menu aan de linkerkant ."
        group:
            content: "Inhoud"
            media: "Media"
        name:
            plural: "Artikellen"
            singular: "Artikel"
        text:
            actions-all: "Acties voor Artikelen "
            actions-one: "Acties voor dit Artikel"
            created: "Dit Artikel is gemaakt op:"
            delete: "Verwijder Artikel"
            duplicate: "Dupliceer Artikel"
            duplicated-finalize: "Inhoud is verveelvoudigd. Click 'Artikel opslaan' om de actie af te maken."
            edit: "Wijzig Artikel"
            error-saving: "Er is een fout opgetreden bij het laden van dit Artikel."
            invalid-field: "Kan variabele of veld: %field%  in Artikel niet lezen: Het is een ongeldig formaat."
            last-modified: "Laatst aangepaste Artikelen"
            new: "Nieuw Artikel"
            no-latest: "Geen recente Artikel"
            no-proper-type: "In het contenttype voor 'Artikel', het veld '%field%' heeft type: %type%', wat niet het juiste veld type is. Wijzig de contenttypes in conttentypes.yml en rectificeer dit. (gebruik geen tabs)."
            no-recent: "Geen recent Artikel."
            none-available: "Geen Artikelen beschikbaar."
            not-existing: "Het Artikel waar je naar zocht bestaat niet. Het is waarschijnlijk verwijderd of heeft nooit bestaan. Er kan ook  een typefout in de URL zitten "
            not-saved-yet: "Dit Artikel is nog niet opgeslagen."
            overview: "Artikelen overzicht"
            publish: "Publiceer Artikel"
            recent: "Recente Artikelen"
            recently-edited: "Recentekijk aangepaste Artikelen"
            reserved-name: "In het contenttype voor  'Artikel', het veld  '%field%' is gedefinieerd, wat een gereserveerde naam is. Wijzig de contenttypes.yml om dit te verbeteren."
            save: "Opslaan Artikel"
            saved-changes: "De aanpassingen in het Artikel zijn opgeslagen."
            saved-new: "Het nieuwe Artikel is opgeslagen."
            saving-impossible: "Kon het Artikel niet opslaan."
            show-more: "Meer Artikelen"
            view: "Bekijk Artikelen"
            wrong-use-field: "In het contenttype voor 'Artikel', het veld  '%field%' heeft 'uses: %uses%', maar het veld '%uses%' bestaat niet.  Wijzig de contenttypes.yml om dit te verbeteren."
    pages:
        description: "Het **Pagina's** conttenttype kan gebruikt worden voor statische pagina's op uw website. Denk aan: Over ons, Contact of disclaimer.  Wijzig de contenttypes.yml om dit aan te passen. Wijzig het bestand`contenttypes.yml` in de folder `app/config/`, gebruik makende van editor van jouw keuze,  of door naar 'Configuratie' =>  'Contenttypen' te gaan in het menu aan de linkerkant."
        description: "The **Pages** contenttype can be used for the more 'static' pages on your site. Things like _'about us'_, _'contact'_ or a _'disclaimer'_. To change the fields that are in this contenttype, edit the file `contenttypes.yml` in the folder `app/config/`, using the editor of your choice, or by going to 'Configuration' » 'Contenttypes' in the menu on the left."
        name:
            plural: "Pagina's"
            singular: "Pagina"
        text:
            actions-all: "Acties voor Pagina's "
            actions-one: "Acties voor dit Pagina"
            created: "Dit Pagina is gemaakt op:"
            delete: "Verwijder Pagina"
            duplicate: "Dupliceer Pagina"
            duplicated-finalize: "Inhoud is verveelvoudigd. Click 'Pagina opslaan' om de actie af te maken."
            edit: "Wijzig Pagina"
            error-saving: "Er is een fout opgetreden bij het laden van dit Pagina."
            invalid-field: "Kan variabele of veld: %field%  in Pagina niet lezen: Het is een ongeldig formaat."
            last-modified: "Laatst aangepaste Pagina's"
            new: "Nieuw Pagina"
            no-latest: "Geen recente Pagina"
            no-proper-type: "In het contenttype voor 'Pagina', het veld '%field%' heeft type: %type%', wat niet het juiste veld type is. Wijzig de contenttypes in conttentypes.yml en rectificeer dit. (gebruik geen tabs)."
            no-recent: "Geen recent Pagina."
            none-available: "Geen Pagina's beschikbaar."
            not-existing: "Het Pagina waar je naar zocht bestaat niet. Het is waarschijnlijk verwijderd of heeft nooit bestaan. Er kan ook  een typefout in de URL zitten "
            not-saved-yet: "Dit Pagina is nog niet opgeslagen."
            overview: "Pagina's overzicht"
            publish: "Publiceer Pagina"
            recent: "Recente Pagina's"
            recently-edited: "Recentekijk aangepaste Pagina's"
            reserved-name: "In het contenttype voor  'Pagina', het veld  '%field%' is gedefinieerd, wat een gereserveerde naam is. Wijzig de contenttypes.yml om dit te verbeteren."
            save: "Opslaan Pagina"
            saved-changes: "De aanpassingen in het Pagina zijn opgeslagen."
            saved-new: "Het nieuwe Pagina is opgeslagen."
            saving-impossible: "Kon het Pagina niet opslaan."
            show-more: "Meer Pagina's"
            view: "Bekijk Pagina's"
            wrong-use-field: "In het contenttype voor 'Pagina', het veld  '%field%' heeft 'uses: %uses%', maar het veld '%uses%' bestaat niet.  Wijzig de contenttypes.yml om dit te verbeteren."
   
    showcases:
        description: "The **Showcases** contenttype is used to show all of the available common field types. In practice, its uses are limited, but be sure to take a look to see which fields are available for use. Wijzig de contenttypes.yml om dit aan te passen. Wijzig het bestand`contenttypes.yml` in de folder `app/config/`, gebruik makende van editor van jouw keuze,  of door naar 'Configuratie' =>  'Contenttypen' te gaan in het menu aan de linkerkant"
        group:
            files: "Bestanden"
            media: "Media"
            other: "Overige"
            text: "Text"
        name:
            plural: "Gallerijen"
            singular: "Gallerij"
        text:
            actions-all: "Acties voor Gallerijen"
            actions-one: "Acties voor deze Gallerij"
            created: "Deze Gallerij was gemaakt"
            delete: "Verwijder Gallerij"
            duplicate: "Dupliceer Gallerij"
            duplicated-finalize: "Inhoud is verveelvoudigd. Click 'Gallerij opslaan' om de actie af te maken."
            edit: "Wijzig Gallerij"
            error-saving: "Er is een fout opgetreden bij het laden van dit Gallerij."
            invalid-field: "Kan variabele of veld: %field%  in Gallerij niet lezen: Het is een ongeldig formaat."
            last-modified: "Laatst aangepaste Gallerijen"
            new: "Nieuwe Gallerij"
            no-latest: "Geen recente Gallerij"
            no-proper-type: "In het contenttype voor 'Gallerij', het veld '%field%' heeft type: %type%', wat niet het juiste veld type is. Wijzig de contenttypes in conttentypes.yml en rectificeer dit. (gebruik geen tabs)."
            no-recent: "Geen recent Gallerij."
            none-available: "Geen Gallerijen beschikbaar."
            not-existing: "DeGallerij waar je naar zocht bestaat niet. Het is waarschijnlijk verwijderd of heeft nooit bestaan. Er kan ook  een typefout in de URL zitten "
            not-saved-yet: "Dit Gallerij is nog niet opgeslagen."
            overzicht: "Gallerijen overzicht"
            publish: "Publiceer Gallerij"
            recent: "Recente Gallerijen"
            recently-edited: "Recentekijk aangepaste Gallerijen"
            reserved-name: "In het contenttype voor  'Gallerij', het veld  '%field%' is gedefinieerd, wat een gereserveerde naam is. Wijzig de contenttypes.yml om dit te verbeteren."
            save: "Opslaan Gallerij"
            saved-changes: "De aanpassingen in het Gallerij zijn opgeslagen."
            saved-new: "De nieuwe Gallerij is opgeslagen."
            saving-impossible: "Kon deGallerij niet opslaan."
            show-more: "Meer Gallerijen"
            view: "Bekijk Gallerijen"
            wrong-use-field: "In het contenttype voor 'Gallerij', het veld  '%field%' heeft 'uses: %uses%', maar het veld '%uses%' bestaat niet.  Wijzig de contenttypes.yml om dit te verbeteren."

**Comment by GawainLynch** [comment]
We still dont' have a `stroopwafel` ContentType… Why!?!?

**Comment by PixelNL** [comment]
note: i haven't been able to implement it myself cause my translation is broken in bolt
it says it could not find locale or something 
after i fix that, i will make a better translation  :)
(i'm already seeing a mistake) xD
