### ISSUE TITLE
Unable to create first user: 'No route found for "POST /bolt/userfirst"'

### ISSUE THREAD

**Issue by jbmoelker** [bolt/bolt#2785]
When trying to create a first user I receive a fatal error:

* Class: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
* Message: No route found for "POST /bolt/userfirst": Method Not Allowed (Allow: GET)
* Code: 0

I think the error is caused by this recent change: https://github.com/bolt/bolt/commit/c0febb5a78c5f17ba89221f04070e9ddce5070f3

Is there an alternative way to creating a first user?

Screenshots of steps:

![screen shot 2015-02-11 at 12 09 16](https://cloud.githubusercontent.com/assets/1516059/6146208/8c68886e-b1ea-11e4-99c3-f0e72d600c0d.png)
![screen shot 2015-02-11 at 12 09 31](https://cloud.githubusercontent.com/assets/1516059/6146209/8c69cbf2-b1ea-11e4-9fce-78b5480ba0b1.png)

**Comment by jbmoelker** [comment]
If am able to create a user if I change `->get` to `->match` on https://github.com/bolt/bolt/blob/c0febb5a78c5f17ba89221f04070e9ddce5070f3/src/Controllers/Backend.php#L99 to:

```php
$ctl->match('/userfirst', array($this, 'userFirst'))
```

However I'm new to Bolt so not real confident to do a PR. Also if I do make the change, the login screen is odd as it shows all notifications, while I am still able to login:

![screen shot 2015-02-11 at 12 41 19](https://cloud.githubusercontent.com/assets/1516059/6146281/67a17210-b1eb-11e4-8d77-a292ee2dcf32.png)

**Comment by GawainLynch** [comment]
The notifications are fixed in #2783 & #2784 (more so the latter)

**Comment by GawainLynch** [comment]
You are 100% correct on the `->get` to `->match` change! 

I am happy to make the change for you, or [if you want to brave it](https://docs.bolt.cm/internals/contributing). Either way, just let me know here :-)

**Comment by GawainLynch** [comment]
Just re-read your point about the PR.  Add to #2784.

**Comment by jbmoelker** [comment]
I see you've already committed a fix. Thanks!!
