### ISSUE TITLE
Bolt matches meta tags within the body for its "after meta" position.

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#2786]
![metainbody](https://cloud.githubusercontent.com/assets/5096632/6148198/ac7971bc-b1ff-11e4-871f-051b70ac79a7.png)

When inserting the snippets for the "after meta" position bolt matches not just meta tags in \<head\>, but in \<body\> too. This means that if one uses meta tags for eg. schema.org/microdata (which is recommended for certain schemas) bolt will insert some meta tags in the wrong position (in my case far down in the \<body\>). In this case the tags inserted are for the canonical tag (from bolt itself) and tags from the OpenGraph extension.

To recreate: put a meta tag in your body.

This is Bolt 2.1.0 - alpha2 running on Apache 2.4.7 with php 5.5.9-1.

**Comment by cdowdy** [comment]
Related:  https://github.com/bolt/bolt/issues/1129

**Comment by SahAssar** [comment]
Closing because duplicate. Reopening #1129 instead.

**Comment by rarila** [comment]
I wonder what's the usecase of ``insertAfterMeta()``. Perhaps someone can enlighten me.

I can think of usecases for head end, body end and probably start of head to initialize something. All other insert functions seem to me like a bit overhead.
