### ISSUE TITLE
Bundle JS locales.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2794]
We have a few JS libraries that come with their own language files, like:

 - CKeditor
 - Moments
 - JQuery UI's datepicker

To reduce the total number of files, and the amount of requests, we should bundle these. For example, all three files for dutch could be combined into one 'nl.js' file.

**Comment by GawainLynch** [comment]
To quote @rarila: :+1:

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
