### ISSUE TITLE
Bootbox.js throwing error instead of dialogues.

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#2798]
In the development version 2.1.0 I noticed that the "readme" button on the extensions screen does not respond to clicks anymore (possible related to the new "versions" button next to it)

I have not really dug any deeper because I jumped ship to 2.0.6 where that button still works.

**Comment by GawainLynch** [comment]
Hmm.. Something in the JS to do with bootbox.

**Comment by GawainLynch** [comment]
Yep, it is Bootbox.js and it is not limited to Extend.  The dashboardCheckboxes() function in init.js has exactly the same error.

@rarila ?

**Comment by rarila** [comment]
Bug found, fix on the way
