### ISSUE TITLE
X-Frame-Options headers

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2814]
For a reason, I had to remove these headers from a Bolt website and noticed that I can't:
https://github.com/bolt/bolt/blob/master/src/Application.php#L448-L449

I found no method to remove headers here neither: http://api.symfony.com/2.6/index.html

I also wonder if a CMS application is meant to send this kind of headers? Wouldn't be better to leave it to the server responsability?

**Comment by bobdenotter** [comment]
We added those to prevent "iframe jacking". Why did you have to remove them?

**Comment by nlemoine** [comment]
I had to display the website on another domain within an iframe.

Wether you decide to leave or remove them, the issue here is that you can't control them (setting "DENY" or allowing a specific domain). 
Moreover, I wonder if the CMS should take care of these kind of headers. Then if you consider it's a CMS responsability, you could extend this to expire, mime type, etc. 
I had a look at some others CMS and found none dealing with this, except Joomla that only send them in the admin routes.

**Comment by bobdenotter** [comment]
Ah, right. Hadn't thought about that. We'll turn this into a setting, most likely.

> except Joomla that only send them in the admin routes.

Hmm, yes. That's something we could also do: Only set it in the backend.
