### ISSUE TITLE
Error: twig.logger when I'm logged in

### ISSUE THREAD

**Issue by HonzaMikula** [bolt/bolt#2816]
After update on latest version, when I'm logged in to admin, it throws me this error. Interesting is that if I turn on debug mode, this error is not happening.

```
[2015-02-14 09:37:57] bolt.CRITICAL: InvalidArgumentException: Identifier "twig.logger" is not defined. 
(uncaught exception) at C:\Moje\WWW\bolt\vendor\pimple\pimple\lib\Pimple.php line 78 {"exception":"
[object] (InvalidArgumentException(code: 0): Identifier \"twig.logger\" is not defined. at 
C:\\Moje\\WWW\\bolt\\vendor\\pimple\\pimple\\lib\\Pimple.php:78)"} []
```
Do anybody know what can be the issue? Thank you very much.

**Comment by HonzaMikula** [comment]
I see that there was bug about it https://github.com/bolt/bolt/issues/2620. But it still happen to me even if I have the latest version.

**Comment by GawainLynch** [comment]
Which version are you on?

**Comment by HonzaMikula** [comment]
I cloned directly from Github, so I have latest version which is in master branch.

**Comment by GawainLynch** [comment]
Weird, that means that `$app['users']->isValidSession()` is returning `true` when you're not logged in.

Shall dig deeper.

**Comment by HonzaMikula** [comment]
Thanks. Just FYI I'm running Bolt on Windows. I'm not sure if it's relevant in this case.

**Comment by GDmac** [comment]
Can't reproduce, can you provide more information, i have tested:
- logged in as admin
- openend frontend (while logged in)
- openend frontend in incognito window (so, guest user)
- both enabled and disabled config.yml debug:true
- click thru to twig from debug bar

Have you done ``composer update`` in the bolt directory?

**Comment by GawainLynch** [comment]
@GDmac did you have `debug: false` set in your `config.yml`?

Either way, I now have it happening here on the frontend, also only when `debug: false` is set.

**Comment by GawainLynch** [comment]
Trace for mine:

```
#0 src/TemplateChooser.php(39): Pimple->offsetGet('twig.logger')
#1 src/Controllers/Frontend.php(98): Bolt\TemplateChooser->homepage()
#2 [internal function]: Bolt\Controllers\Frontend::homepage(Object(Bolt\Application))
#3 vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#4 vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 vendor/silex/silex/src/Silex/Application.php(543): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 vendor/silex/silex/src/Silex/Application.php(520): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 index.php(16): Silex\Application->run()
#8 {main}
```
