### ISSUE TITLE
Dump() causes page encoding fail

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2817]
The old \Dumper::dump() somehow keeps the page (utf-8) encoding correct, whereas the new symfony dump() causes encoding to be lost. (see title/text ON the page)

![dumper-vs-dump](https://cloud.githubusercontent.com/assets/156334/6199664/5ea46ba4-b452-11e4-80ab-e2cc9be762b8.png)

**Comment by GawainLynch** [comment]
A workaround was discussed on IRC, am I correct?

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

**Comment by GDmac** [comment]
Not really a workaround, just a matter of - it happens
