### ISSUE TITLE
uploaded filename pattern - replacement

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2819]
The (new) default filename pattern for uploads ``'[^A-Za-z0-9\.]+'`` 
with the default replacement: ``'-'`` are currently regex-replaced 
in controller/upload L40. 

Suggestion: use cocur/slugify() with nicer replacements

**Comment by rarila** [comment]
:+1:

**Comment by nickwhite75** [comment]
Terminated?

**Comment by bobdenotter** [comment]
> Terminated?

Nope. We just did not get around to implementing this just yet. :-)

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
