### ISSUE TITLE
Add posibility to disable config file generation

### ISSUE THREAD

**Issue by gorkalaucirica** [bolt/bolt#2821]
The auto generation its a nice feature but when using Vagrant, sometimes overrides existing files. This is due to the way Vagrant works, when you change a file, it removes it and copies the new one to the VM. If you refresh the page during the copy the config has gone.

Its not a critical issue but its quite uncomfortable.

**Comment by bobdenotter** [comment]
Thinking about this.. how would we do this? We can't put it in configuration, because this case is only triggered, when there's no config.yml yet.. Doing it in the code won't work, because it will be overwritten on any updates.

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
