### ISSUE TITLE
errors while trying to edit a (theme) files in backend

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2823]
**Note:** put contents error is on on READING a file, because of a update() call to flysystem,
to determine ``writeable = (size-written==size-read)`` \* cough \*

---

Warning: file_put_contents(/theme/temportalist/index.twig): failed to open stream: Permission denied in /vendor/rossriley/flysystem53/src/Adapter/Local.php on line 146
trace via: Backend.php:1526

Warning: htmlspecialchars() expects parameter 1 to be string, object given in /src/Translation/Translator.php on line 28
trace via: Backend.php:1532

Warning: basename() expects parameter 1 to be string, object given in /src/Controllers/Backend.php on line 1609
Trace via: Backend.php:1609

Warning: preg_match() expects parameter 2 to be string, object given in /vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php on line 164
trace via: Backend.php:1617

( ! ) Catchable fatal error: Object of class League\Flysystem\File could not be converted to string in /vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php on line 165
Trace via: Backend.php:1617 (Render.php 53)

**Comment by rarila** [comment]
Five for the price of one! Error weeks, only today. Call 555 Cheap Jack GDmac! ;-)

**Comment by GawainLynch** [comment]
You've missed my rants about Flysystem's "*design*" on IRC, @GDmac :grinning:

**Comment by bobdenotter** [comment]
Git blame points to @CarsonF. Think you could take a look at this, Carson? ^_^

**Comment by CarsonF** [comment]
I'll take a look. Sounds like I derped

**Comment by GDmac** [comment]
(1) Note, this affects any editing of YML files via backend.
I just reported the Theme one, which will give you the most errors :-)

(2) As mentioned, i'ld also love to address the issue of
using file_put_contents() just to determine if a local file is writeable,
That seems ... ehm ... awkward

**Comment by HonzaMikula** [comment]
This is still not working for me. via #2837

**Comment by GawainLynch** [comment]
Ping @CarsonF

**Comment by GDmac** [comment]
Remaining issue on editting /app/config/config.yml 
the namespace is either passed incorrect from /twig/nav/secondary (link namespace app)
or wrongly fecthed in backend::fileEdit (if namespace==app then is set to config)

**Comment by GawainLynch** [comment]
Fixed in #2853
