### ISSUE TITLE
No way to communicate serious issues. (security or otherwise).

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2828]
Currently, the backend shows the "latest news". Some users disable this, because the news is not relevant to them. If, however we have a serious security issue, these users will not be notified. _\*knocks on wood\*_

I propose to _**fix**_ this obvious _**bug**_ by enhancing the way we send out these notifications: 

- There will be a distinction between 'news' and 'alerts'. 
- News items and alerts can have a 'target' version, which is the highest version of Bolt for which these are shown. If your version of Bolt is higher than this value, the news item will not be shown. 
- "Regular" news can be disabled like it is now. "Alerts" can _not_. 

![screenshot 2015-02-15 13 06 09](https://cloud.githubusercontent.com/assets/1833361/6203179/7f8dc736-b513-11e4-9679-779d198390ba.png)

So, for example. Let's say we find a serious issue in Bolt 2.1.2, in a month or two from now. What happens is this: 

- We fix the issue, and release Bolt 2.1.3. 
- We put out an "alert", with a target version of '2.1.2', urging everybody to upgrade. 
- This alert will be shown with a clear **visual** warning, that they will need to upgrade. 
- This warning will be shown on _older_ bolt installs as well, just without the clear distinction between "news" and "alert" 
- The message will go away, as soon as the Bolt install on the site is updated to '2.1.3' (or higher).

**Comment by GawainLynch** [comment]
What if the issue needing upgrade was introduced in 2.1.2, but the user is running 2.1.1?

Other than how we'd handle that, very much like the idea. It could integrate nicely with the updater when that lands.

**Comment by rarila** [comment]
While touching this we should also build in the possibility to localize such messages

**Comment by bobdenotter** [comment]
> What if the issue needing upgrade was introduced in 2.1.2, but the user is running 2.1.1?

There's a slim chance that would happen, but in that case we'll _still_ urge people to update to the latest. Better safe than sorry.

> While touching this we should also build in the possibility to localize such messages

I'm not looking forward to writing the news items in multiple languages. :-)

**Comment by GawainLynch** [comment]
> There's a slim chance that would happen, but in that case we'll still urge people to update to the latest. 

Either way, I am not fazed. Kill this bug with :fire:

**Comment by rarila** [comment]
@bobdenotter nobody is, but we should plan the API to enable it. Does not help to display fat "Urgent, update needed" if the user only understands "/*%$§=& §$$!°".

@GawainLynch If we have a target version we also could have a min and max target version

**Comment by rarila** [comment]
Hmm, Google Translate API: $20 per 1 M characters :-)

**Comment by bobdenotter** [comment]
> Hmm, Google Translate API: $20 per 1 M characters :-)

If they've managed to set up Bolt, I'm sure they understand _some_ english. Otherwise the'll just have to put it through translate themselves. The universal/international red banner should still make it obvious that it's important. ;-)

**Comment by GawainLynch** [comment]
The box title would be translated though.  That would at least give the user context.

**Comment by rarila** [comment]
@bobdenotter But if they just paid for setup?

**Comment by bobdenotter** [comment]
@rarila I'm assuming clients all over the world are the same: It looks broken, you give the guy who did it for you a phonecall. ;-)

**Comment by bobdenotter** [comment]
@GawainLynch The box's title is also part of the content in the feed: http://news.bolt.cm

**Comment by bobdenotter** [comment]
Closed by #2830
