### ISSUE TITLE
[extensions.bolt] Unable to disable extension

### ISSUE THREAD

**Issue by erikaheidi** [bolt/bolt#2836]
Hey all! I was updating an old extension to the new system, while adding it to https://extensions.bolt.cm/ I got a few problems. I didn't realize the form was being submitted (button changed color but was still clickable) so I did it 3 times. Sorry :)

Now I have 3 duplicate extensions: 

* https://extensions.bolt.cm/view/03d7a53d-b540-11e4-a99b-c5c5895e3a0c
* http://extensions.bolt.cm/view/084d8772-b540-11e4-a99b-c5c5895e3a0c
* https://extensions.bolt.cm/view/0cb15c11-b540-11e4-a99b-c5c5895e3a0c

Now, when I access the details and try to disable it, I get the following error:

![screenshot from 2015-02-15 19 33 14](https://cloud.githubusercontent.com/assets/293241/6204391/b7f42b8e-b549-11e4-8b3d-f125137c640c.png)

**Comment by bobdenotter** [comment]
Whoops! Yeah, we should look into that. Thanks for noticing.

For now, I've deleted the duplicates by hand, so only the latest is still present.

**Comment by erikaheidi** [comment]
Thanks @bobdenotter ! :) :+1:

**Comment by rossriley** [comment]
Fixed this now, disabling extensions via the UI will now work.
