### ISSUE TITLE
Can't edit config files through admin

### ISSUE THREAD

**Issue by HonzaMikula** [bolt/bolt#2837]
When I'm trying to edit config file through Bolt admin, I've got error. I'm on windows and have latest version from github.

League\Flysystem\FileNotFoundException thrown with message "File not found at path: config/config.yml"

```Stacktrace:
#9 League\Flysystem\FileNotFoundException in C:\Moje\WWW\bolt\vendor\rossriley\flysystem53\src\Filesystem.php:537
#8 League\Flysystem\Filesystem:assertPresent in C:\Moje\WWW\bolt\vendor\rossriley\flysystem53\src\Filesystem.php:484
#7 League\Flysystem\Filesystem:getMetadata in C:\Moje\WWW\bolt\vendor\rossriley\flysystem53\src\Filesystem.php:502
#6 League\Flysystem\Filesystem:get in C:\Moje\WWW\bolt\src\Controllers\Backend.php:1533
#5 Bolt\Controllers\Backend:fileEdit in <#unknown>:0
#4 call_user_func_array in C:\Moje\WWW\bolt\vendor\symfony\http-kernel\Symfony\Component\HttpKernel\HttpKernel.php:145
#3 Symfony\Component\HttpKernel\HttpKernel:handleRaw in C:\Moje\WWW\bolt\vendor\symfony\http-kernel\Symfony\Component\HttpKernel\HttpKernel.php:66
#2 Symfony\Component\HttpKernel\HttpKernel:handle in C:\Moje\WWW\bolt\vendor\silex\silex\src\Silex\Application.php:543
#1 Silex\Application:handle in C:\Moje\WWW\bolt\vendor\silex\silex\src\Silex\Application.php:520
#0 Silex\Application:run in C:\Moje\WWW\bolt\index.php:16
```

**Comment by bobdenotter** [comment]
We are aware of this. See #2823

**Comment by HonzaMikula** [comment]
I've pulled last commits, but it's still happening. So it's probably something else then #2823. Maybe this will help you.
![bolt-error](https://cloud.githubusercontent.com/assets/1358508/6225193/52010ef2-b687-11e4-875f-ec57f0e5f628.png)

**Comment by GDmac** [comment]
It's either backend.php fileEdit or nav/secondary.twig
namespace should be either set as (app/?)config/config.yml or catched as (app/?)config/config.yml

**Comment by CarsonF** [comment]
See #2853

**Comment by GawainLynch** [comment]
I've just #2853 merged, can those seeing the issue please re-test.

**Comment by HonzaMikula** [comment]
Yeah, it's working now. Good job and thanks!
