### ISSUE TITLE
paths.currenturl is not exactly the current url 

### ISSUE THREAD

**Issue by grosslarnakh** [bolt/bolt#2838]
I am trying to send additional parameter to twig template via url, using for example:
www.site.com/entries/entry-name?parameter (or www.site.com/entries/entry-name#parameter).

In Bolt 1.6, paths.currenturl was exactly "www.site.com/entries/entry-name?parameter", but in Bolt 2.0.5 paths.currenturl became "www.site.com/entries/entry-name".

It seems that $app['paths'] did not contains "?parameter" (or "#parameter"). I think that it can be useful to get somethere current url exactly like it shows in browser.

**Comment by grosslarnakh** [comment]
Maybe it will be better to put parameters part of string in additional field in $app['paths'], so there will be no needs to parse the currenturl.

**Comment by CarsonF** [comment]
You can use `app.request` for the current request parameters. 

For example: `app.request.query.has('parameter')`

**Comment by grosslarnakh** [comment]
Thank you.

**Comment by bobdenotter** [comment]
Closed, because solved :-)

**Comment by grosslarnakh** [comment]
@bobdenotter, maybe it should be written in documentation :-)

**Comment by CarsonF** [comment]
Ah you mean a migration doc. I've never mentioned that

...I'll just leave this here: #2844
