### ISSUE TITLE
Cosmetics - image field

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2856]
Can has image-edit nice [X] to remove the image?
Also "afbeeldings-bestand" sounds like dunglydutch or germydungly like _vorratsdatenspeicherung_

![bolt-image-edit](https://cloud.githubusercontent.com/assets/156334/6249822/1ad55d08-b78a-11e4-859a-5ed52d3628ba.jpg)

**Comment by GDmac** [comment]
Partial (translation) in #2857

**Comment by SahAssar** [comment]
Merged this issue into #2306, added the remaining thing about an unselect X there, so closing :)
