### ISSUE TITLE
Activity log contains strange things (for me...)

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2859]
What does this mean? Every few minutes there is an activity added...

№ 7
Lvl 1 	Storage: requested specific query 'pagina/1', not found. /
in: /httpdocs/src/Storage.php::2048 () 	
79.171.81.123 	2 minuten geleden
№ 6
Lvl 1 	Storage: No valid contenttype '' /
in: /httpdocs/src/Storage.php::1688 () 	
79.171.81.123 	2 minuten geleden
№ 5
Lvl 2 	No route found for "GET /robots.txt" / abort
in: /httpdocs/src/Application.php::567 () 	
79.171.81.123 	2 minuten geleden
№ 4
Lvl 1 	Storage: requested specific query 'pagina/1', not found. /
in: /httpdocs/src/Storage.php::2048 () 	
79.171.81.123 	2 minuten geleden
№ 3
Lvl 1 	Storage: requested specific query 'pagina/1', not found. /
in: /httpdocs/src/Storage.php::2048 () 	
66.249.81.245 	5 minuten geleden
№ 2
Lvl 1 	Storage: requested specific query 'pagina/1', not found. /
in: /httpdocs/src/Storage.php::2048 ()

**Comment by GDmac** [comment]
Every line has specific meaning. ``pagina/1', not found`` could be a (default) record it tries to fetch in a template, like for homepage. The ``robots.txt`` file is probably not present, then the htaccess delegates the request to Bolt, but there is no route to the url there. (lookup robots.txt via google)

**Comment by gwbonline** [comment]
Thanks! I have added a robots.txt and the 'pagina/1' was set in the config file while it was not needed. These two errors do not appear in the activity log anymore. I have one left:

№ 16
Lvl 1 	Storage: No valid contenttype '' /
in: /httpdocs/src/Storage.php::1688 () 

Does this mean I have set some twig code the wrong way?

**Comment by GDmac** [comment]
Try hitting a page and checking the log. Probably somewhere on some twig template is still calling a (setcontent records = ...)

**Comment by gwbonline** [comment]
It only happens on the frontpage. I deleted everything so only the header and the footer where left. I still get the error No valid contenttype " /. So it must be in the footer or header. The footer doesn't contain a setcontent etc. The header does. But after removing all that code, so the header only contains html, the problem is still there. Is there any other way to track down what's causing this?

**Comment by bobdenotter** [comment]
Should be fixed (mostly) by #2928. 

Except: 

> Lvl 2 No route found for "GET /robots.txt" / abort
> in: /httpdocs/src/Application.php::567 ()

You should add a robots.txt ;-)
