### ISSUE TITLE
image ALT attributes

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#2866]
Currently if you use  
```html
{{ record.image|popup(100, 100, "r") }}  
<!-- markup below -->
<a href="/bolt/thumbs/1000x750r/filename.jpg" class="magnific" title="Image: filename.jpg">
  <img src="/bolt/thumbs/100x100r/filename.jpg" width="100" height="100">  
</a>
```
 or 
```html
{{ record.image|showimage(800, 600) }}   

<img src="/bolt/thumbs/800x600c/filename.jpg" width="800" height="600">
```  
There are no alt attributes present. We need these for accessibility purposes and a less significant need of being a valid image tag.  

Most instances a file name can be used without the .jpg/png/gif extentions (if the file name actually describes the image ie. alt="bolt logo") but that isn't very descriptive and in some cases not valid alt attribute text. There is also no place to add a description for the image. Only an option to rename the image.   

I understand this gets into the murky waters of media management and there are no quick fixes ( besides possibly adding a description field to the image in the database).  

more info on alt attributes for anyone interested:  
[web aim atl text](http://webaim.org/techniques/alttext/)
[w3 accessibilty](http://www.w3.org/standards/webdesign/accessibility)

**Comment by GawainLynch** [comment]
Is [this](https://github.com/bolt/bolt/blob/master/app/config/contenttypes.yml.dist#L124) what you're looking for?

i.e.:
```twig
<img itemprop="image"
    src="{{ record.image|thumbnail(x, y, 'f') }}"
    alt="{{ title|e }}" />
```

**Comment by cdowdy** [comment]
@GawainLynch unfortunately not. If you fill bolts db with lorem ipsum records and add  
```yaml  
fields:
   image:
     type: image
     attrib: title  
```  
you'll get this in your contenttype edit page:  
![added_attrib](https://cloud.githubusercontent.com/assets/5969974/6305403/02a603de-b8f9-11e4-9e75-292dce7b0125.PNG)  

and if you use either ```{{ record.image|popup(100, 100, "r") }}``` ```{{ record.image|showimage(800, 600) }}``` you still get the html markup mentioned above.   

if you change the attib to "alt" you get no alt box: 
![no_alt](https://cloud.githubusercontent.com/assets/5969974/6305545/1b7ee5fa-b8fa-11e4-94c3-08d6dbde6ca6.PNG)  

in accessibility terms a title attribute is discouraged (should be used sparingly) and shouldn't be the same thing as the alt text would be. Many browsers don't even expose the title attribute to screen readers (http://www.w3.org/html/wg/wiki/ChangeProposals/notitlev2)   

for template designers building the img tag manually this isn't an issue (as long as they provide alt text) but if you're going by bolts docs and use those tags mentioned above you'll get no alt text.

**Comment by GawainLynch** [comment]
@cdowdy the use of the word "title" is just for editor friendliness — see #827 — as @bobdenotter didn't want to use the word "alt".

In my templates I just use the field for both `alt` and `title`.  I did [note at the time](https://github.com/bolt/bolt/issues/827#issuecomment-32468276) that there might be reasons to expand the `attrib:` key later, and it was (is still?) treated as an array.

BTW, totally agree with what you're trying to achieve.  Just saying that  we have the foundation at the very least, and that can probably be built on if needed :smile:

**Comment by cdowdy** [comment]
> the use of the word "title" is just for editor friendliness   

I understand that but even if that's present you don't get EITHER title nor alt text in these bolt twig tags:  
```twig
{{ record.image|popup(100, 100, "r") }}  
or  
{{ record.image|showimage(800, 600) }}
```  
these tags are built from within bolt. You cant place them inside and image tag like so```<img src="{{ record.image|popup(100, 100, "r") }}" alt="" />```

**Comment by GawainLynch** [comment]
> I understand that but even if that's present you don't get EITHER title nor alt text in these bolt twig tags

Yep, totally get you, and as I said, not trying to argue it down, just point that the foundations are there to be built on.

**Comment by cdowdy** [comment]
ha this is probably my fault @GawainLynch I've got a hundred different things going on right now and If i came across as argumentative or harsh I apologize.  In my haste I thought we were misinterpreting each other..... WHEW ITS FRIDAY THANKFULLY! :beers:

**Comment by GawainLynch** [comment]
@cdowdy no bad intent taken and was worried *I* was coming across the same way! :beers:

**Comment by GDmac** [comment]
@cdowdy we could easily add the alt field to the img tag. (e.g. put the title there)
https://github.com/bolt/bolt/blob/master/src/Twig/Handler/ImageHandler.php#L191
