### ISSUE TITLE
AfterHandler depends on response headers that could not be set

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2871]
### Context / Problem (potentially)
`App::afterHandler` depends on the `Content-Type` header. 
This header is set in the response by the `ResponseListener` at `kernel.response` event at _priority 0_.
Our `afterHandler` also fires at _priority 0_. 
The only reason `ResponseListener` fires first is code execution order. 

### Solution
Change our `afterHandler` to fire at _priority -1_. 
That in itself is an easy fix. However, there could be side effects to that. Other after middlewares could depend on some code that _now_ hasn't fired yet.
So these need to be looked into.

----
This is low priority.

**Comment by GawainLynch** [comment]
Implemented in the upcoming controller refactor branch.
