### ISSUE TITLE
ImageList module unable to show thumbnail

### ISSUE THREAD

**Issue by ustarhk** [bolt/bolt#2884]
The Image list module in Admin panel unable to show thumbnail.
The thumbnails are broken with url contain `<PATH>` and `<FNAME>`.
Issue should be due to `/app/view/js/bolt.js` using `$.replace('{str}','{val}')` which only replace single occurrence.

To fix it, the render function in /app/view/js/bolt.js should change from:
```javascript
            list.append(data.item.
                replace('<ID>', image.get('id')).
                replace('<VAL>', _.escape(image.get('title'))).
                replace('<PATH>', bolt.paths.bolt).
                replace('<FNAME>', image.get('filename'))
            );
```
to:
```javascript
            list.append(data.item.
                replace(/<ID>/g, image.get('filename')).
                replace(/<VAL>/g, _.escape(image.get('title'))).
                replace(/<PATH>/g, bolt.paths.bolt).
                replace(/<FNAME>/g, image.get('filename'))
            );
```

**Comment by rarila** [comment]
Look [here](https://github.com/bolt/bolt/blob/master/app/view/lib/bolt/upload-files.js#L71). This one was fixed about 2 months ago (v2.0.3). Please update to the latest version. Thanks! :smile_cat:
