### ISSUE TITLE
Bad field in contenttypes.yml crashes dbcheck

### ISSUE THREAD

**Issue by kevinkhill** [bolt/bolt#2885]
Issue
-------
I was editing one of my content types and for the teaser field, I accidentally changed __type__ to _inline_ when I meant to set __variant__ to _inline_ and __type__ to _text_.
I was making more changes than just that, but it took me quite a while to figure out that is what caused me to get this pretty nondescript error page. After much hunting, I figured out my problem.
Anyways, I suppose that more descriptive error messages would help sort down that problem quicker if it happens, or maybe some sort of sanity/syntax check that could be ran over the YAML file before saving the changes.

Error
------
![Imgur](http://i.imgur.com/hwsX2yZ.png)

**Comment by GawainLynch** [comment]
Kudos on a really good issue report, @kevinkhill, thank you!

Good news is this came up in #2491 and was fixed a few days ago in #2852 that will be in the upcoming 2.1.

**Comment by kevinkhill** [comment]
Happy to help :)
