### ISSUE TITLE
Including External Package via Composer

### ISSUE THREAD

**Issue by callmenick** [bolt/bolt#2886]
Today, I tried to include an external package from packagist, using composer, in a test environment. After I ran the composer install, something seemed to have happened to my autoloader, and my site crashed giving me a fatal error for classes not found.

I'm wondering if I did something wrong, or if there's a specific way to include external packages? Thanks.

**Comment by GawainLynch** [comment]
Where I usually run into problems doing this is when I do large `git pull` changes or `composer update` changes and the permissions of certain class files end up with permissions that aren't readable be the web server.

**Comment by callmenick** [comment]
@GawainLynch how would you undo that? I felt so noobish today, I ended up replacing the src and vendor directories with originals. Also, using the bolt command line install way, there's no composer.json file by default in the root directory.

**Comment by GawainLynch** [comment]
Ah, I wouldn't stress… I do things all the time that hit 11 on the newbie scale followed by the obligatory self facepalm :smile_cat: 

Anyway there are a couple of things at play here, so let me step though a few things for you…

If you install via *[Option 1](https://docs.bolt.cm/installation#option-1-easy-way-using-command-line)* then yes, you won't have a `composer.json` as the assumption made there is that the person doesn't know how to, or want to, manage the dependencies. So for what you're doing, probably not the best option. As if you added a `composer.json` to this type of install and didn't set up the matching dependencies, but ran `composer update` then Composer would remove most of the libraries in `vendor/` :boom: 

What you probably want it to have a look at our *[Install Bolt with Composer](https://docs.bolt.cm/installation-composer)* page. That will set up Bolt as a dependency of *your* root project, allowing easy addition of things from Packagist.

**Comment by callmenick** [comment]
Haha, the emojis are killing me here. Good stuff. I'm pretty sure that's exactly what happened too. I just looked into installing with composer, and the set up seems to be how I want it now. Going to install a couple packages and play around a bit. I'll close this issue, thanks for the input!
