### ISSUE TITLE
Getting a lot of "Configuration error: users:roles-hierarchy:everyone is not granted to any roles."

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2892]
When editing a page.  See screenshot. 

It points to `src/Permissions.php` line 254. 

![screenshot 2015-02-22 14 25 28](https://cloud.githubusercontent.com/assets/1833361/6318666/acb5091e-ba9e-11e4-9663-cfc35475b837.png)

Pinging @MrAdamCook: Any idea what causes this?

**Comment by CarsonF** [comment]
Did you update your permissions file?

**Comment by GawainLynch** [comment]
What @CarsonF said. Since #2868 we don't send these to La-La Land any longer. Previously they would only be showing in a Codeception run, but I thought for now that annoying us with them would prompt discussions like… um… this one :ballot_box_with_check:

**Comment by GawainLynch** [comment]
Tracking this one though #2893 as it is not  "problem" as such, just a redirection of logging, where #2893 is a problem that needs addressing.

**Comment by CarsonF** [comment]
I'm still getting this error. I think it's still a bug

**Comment by GawainLynch** [comment]
It's actually a "feature" that has been there forever, it is only that we redirected the logging from error_log(). :palm_tree:

**Comment by CarsonF** [comment]
Well who said to move it from error_log, shame on them.
