### ISSUE TITLE
Root not allowed to edit records by other roots..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2894]
See screenshot, when trying to edit a 'page'.

![screenshot 2015-02-22 14 50 19](https://cloud.githubusercontent.com/assets/1833361/6318724/2d5e0f54-baa2-11e4-8249-753457b98e69.png)

Error is triggered here, in Backend.php, line 1809

```PHP
        } elseif (!$request->attributes->get('checkUserRoleHierarchy') && $user = $app['users']->getUser($id)) {
            if (!$app['permissions']->isAllowedToManipulate($user, $app['users']->getCurrentUser())) {
                $app['session']->getFlashBag()->add('error', Trans::__('3. You do not have the right privileges to view that page.'));

                return Lib::redirect('dashboard');
            }
         }
```

I don't think that particular bit of code should be there at all.. Checking whether a user is allowed to edit another user happens elsewehere. Shouldn't be in the 'after' handler at all.

**Comment by bobdenotter** [comment]
pinging @MrAdamCook

**Comment by CarsonF** [comment]
I agree. I'm doing that check in `usersEdit` and `users` which were the only code paths that were using this section. I left it here to not completely rewrite the feature..

**Comment by CarsonF** [comment]
Ok I might remove that check in the after handler based on your agreement. But I think your issue here is your permissions file. I can't replicate it.

**Comment by bobdenotter** [comment]
I've reset the permissions file to the default one, as in the `permissions.yml.dist`. Let's fix the simple ones, and i'll dig deeper.
