### ISSUE TITLE
Excerpt is broken.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2897]
The change in 19e49665c4f2c9be2be956deaee190ddbc994735 has a regression: 

`{{ record.introduction|excerpt() }}` returns `false`, instead of an excerpt of the introduction.

Pinging @rossriley Was that change really necessary?

**Comment by rossriley** [comment]
I can't remember the exact reason for making that change but I'm guessing it's because I thought there was an untestable behaviour, so happy to revert and I'll look at the test again.

Is this the case that the original just returned the object passed in if it didn't implement an excerpt method?

**Comment by bobdenotter** [comment]
Yes, i think so. But, for Twig_Markup it should just pass it through. 

(I've closed #2895 as a duplicate of this)

**Comment by bobdenotter** [comment]
Closed by #2932
