### ISSUE TITLE
Add an option to 'test sending emails'. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2909]
We should make a small tool to send out e-mails, so users can easily test if Bolt is sending out e-mails OK.

See #2864 for reference.

**Comment by GawainLynch** [comment]
See baseline functionality in #2882

**Comment by SahAssar** [comment]
Alrightio, assigning this to @bobdenotter!

**Comment by bobdenotter** [comment]
Moved to https://github.com/bolt/starter-kit/issues/4
