### ISSUE TITLE
Composer Search onlyname flag isn't defined

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2913]
`SearchPackage` doesn't have `onlyname` variable used to determine whether to search by name or full text.

**Comment by GawainLynch** [comment]
Somewhat deliberately left to a later time as I don't think we leverage that in the current UI functionality.

**Comment by CarsonF** [comment]
Ok well we should at least define the variable with a default value then

**Comment by GawainLynch** [comment]
Agreed
