### ISSUE TITLE
[RFC] Is ResourceManager::request array really needed?

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2914]
`ResourceManager::get/setRequest` are only used inside of the class. I don't understand the purpose of this externally from the class, can't the Symfony Request object shouldn't just be used?

**Comment by bobdenotter** [comment]
If it were used from the outside, I suppose we would've noticed the glaring spelling error before: 

    "Request componenet $name is not available"

> can't the Symfony Request object just be used?

It _does_ have some things that are specific to Bolt, like 'canonical', so I don't think we can just replace it easily.

**Comment by CarsonF** [comment]
canonical was, I think, the _only_ usage outside of the request object. That could still be pulled in on `initializeRequest` instead of `initializeApp` which would just pull it from the config then and set the url path.

I'm not saying the functionally it completely useless/unneeded. I just think the current approach could use some refactoring and I don't think exposing the public methods is necessary.

**Comment by rossriley** [comment]
There's a few things that probably aren't strictly necessary any more, but there were instances of request protocol / canonical being used across the codebase and themes / extensions so to stay on the safe side I replicated the previous output completely hence paths() request() and urls().

Once we're sure everything is being used properly then the getRequest and the old syntax of rootpath, extensionspath and equivalent url suffixes can also be killed.

**Comment by GawainLynch** [comment]
@rossriley: are we ready to kill these with :fire: ?

**Comment by SahAssar** [comment]
Any movement on this one? Just asking since it's been a while...

**Comment by rossriley** [comment]
Feel free to close. It's on my radar but realistically it will take another refactor, and that's not going to happen until 4.0 now.

**Comment by SahAssar** [comment]
Alrightio, closing then :)
