### ISSUE TITLE
LowLevelException doesn't call parent constructor

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2915]
Is there a reason for this? Or just an oversight?

**Comment by bobdenotter** [comment]
I'm guessing oversight. :-)

**Comment by GawainLynch** [comment]
It was deliberate. When @rixbeck created that class last year, we knew that @CarsonF would come along, so he and I agreed that it would be fun to annoy him with.

**Comment by CarsonF** [comment]
rixbeck: le trolled

**Comment by SahAssar** [comment]
Is this fixed, or still an issue? Tagging for closing on the 8th if no more info comes in. :)

**Comment by CarsonF** [comment]
Fixed with 42fbce6

**Comment by GawainLynch** [comment]
Yay! I did something good for once!
