### ISSUE TITLE
Filelist upload not working with large files and extension restrictions set

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2917]
I can't seem to find the root of this problem, but its definitely crept up on me. Essentially, large files aren't getting uploaded in certain circumstances (where in others, larger files upload just fine).

How I replicated it:

1. Make sure your PHP max upload limit is sufficiently large (I just have mine set to 1000M)
2. Take a fresh Bolt install (master branch in my case)
3. Change the `filelist` field in the `showcases` contenttype, by adding `extensions: ['mp3', 'ogg']` to restrict the files you can upload
4. Try to upload a ~40mb mp3. Nothing happens

But then if I take away the restrictions, and try to upload a 90mb pdf, all is hunky dory. Then if I reset the extensions to `['pdf']`, it stops working again.

There are no errors on the client or server side, no 500s from `upload?handler=` and no logs that I can see, it just fails silently.

**Comment by lexislav** [comment]
I can confirm this – althought my PHP is conigured for 100M, I am not able to upload bigger files. Safely I can upload files up to 5MB.
For now, I upload files via ftp and then „add them from server“

**Comment by GDmac** [comment]
Next to upload max size, also check post max size.
I verified the above isue. My upload max size was set to 256M, but post max was 32M.
After changing that to 64M i was able to upload a 48mb pdf without problem.
```
// htaccess
php_value upload_max_filesize 16M
php_value post_max_size 16M
```
via: http://stackoverflow.com/a/7754160/25286

**Comment by lexislav** [comment]
Mine setting is:
```upload_max_filesize = 100M
post_max_size = 100M```

Failed even with 36mb file. Could it be related to the jquery file uploader too?

**Comment by GDmac** [comment]
"You should also set [check] post_max_size"

**Comment by Pinpickle** [comment]
Increased memory limit and post size limit and the issue was resolved for me! It's pretty unclear how to do this, but is more of a PHP thing than a Bolt-specific thing. Still, some may want to put it in the docs.

However, there should be some sort of message indicating a failure rather than a silent failure.

**Comment by bobdenotter** [comment]
@Pinpickle Is this solved by your PR for #3123 ?

**Comment by Pinpickle** [comment]
@bobdenotter It seems that when I set an extensions restriction, and lower the memory limit below the size of the file I try to upload, it works just fine.

I'm not really 100% what the original issue was, but the uploader definitely won't let you continue if the files are smaller than either the post max size or the max upload size so people shouldn't run into this anymore.

**Comment by bobdenotter** [comment]
:+1:
