### ISSUE TITLE
[RFC] Backend only set of twig filters/functions

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2920]
Lots of stuff could be done much easier or faster in PHP than in a twig template. Also it would save us from having to much logic inside the templates. Problem is, this functionality often would be of no use for frontend development and would prevent us from being flexible by adding and removing stuff as needed because of BC.

So I would really like it, if we could add a second set of twig filters/functions, that is only loaded and available while being in backend (also not allowed for extensions). :tada:

**Comment by GawainLynch** [comment]
Sounds logical and helpful :+1: 

There is also the added bonus that we could use it as a "proving ground" for things that we're uncertain of before unleashing them on the public API space.

**Comment by rarila** [comment]
I was thinking about while doing the latest patch and suddenly noticed, that this could be the wrong approach or at least the priority could be put on low.

Most of these things I was thinking at while writing this RFC should be moved from the templates into the backend controller and from there precalculated be injected into the template with ``context`` array. But doing so would also need a split of the backend controller into smaller pieces as it is quite big already.

So we have to see if there are enough valid usescases left to justify backend only twig filters/functions.

**Comment by GawainLynch** [comment]
Yeah, while it hasn't ended up there yet, I know that @CarsonF was wanting to split stuff out of that Controller…

**Comment by CarsonF** [comment]
Yeah I think moving more of the logic into the controllers and splitting them up more is the right way to go. 

Splitting up routes into Files, Users, Changelog, and Content controllers seems like a good start.

**Comment by GawainLynch** [comment]
Now exists as `Bolt\Twig\Handler\AdminHandler` and is marked as `@internal`
