### ISSUE TITLE
Editing a user's roles doesn't take into account roles the current user doesn't have permission to change

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2927]
The edit user form takes the roles as an absolute list, instead of accounting for the other roles the user could have that the current user doesn't have permission to change.

Ex: With default setup, UserA has developer role and UserB has admin and developer roles. UserA can remove UserB's developer role, but in doing so it will remove UserB's admin role as well.

**Comment by bobdenotter** [comment]
Hmm, this is a tricky one.. 

I think we should make it so that if UserB has _any_ role that UserA is not allowed to edit, that UserA should not be allowed to edit UserB __at all__. Right?

**Comment by CarsonF** [comment]
It is a tricky one. If we did that though then it kinda makes the users:edit permission pointless.

**Comment by CarsonF** [comment]
If we do allow edit, I think we should show all roles and just disable the ones that the user can't edit. The backend should follow suit.

**Comment by CarsonF** [comment]
Should a role be able to remove the same role from another user?

ex: should a developer be able to remove the developer role from another user, or should it take an admin? I think admin
