### ISSUE TITLE
addSnippet('endofbody' .....) put content in the wrong place

### ISSUE THREAD

**Issue by joanlouis** [bolt/bolt#2946]
$this->addSnippet('endofbody' ...   or
$this->addSnippet(SnippetLocation::END_OF_BODY, .....
put content in the end of document (after `</body></html>`)

**Comment by bobdenotter** [comment]
Is your `</body>` tag on a separate line, or is your HTML minified?

**Comment by joanlouis** [comment]
on separate line

**Comment by joanlouis** [comment]
found the issue : it need a blank new line between a include and </body>

**Comment by bobdenotter** [comment]
Ah, great. Closing this one then. We'll refactor the inlude mechanism soon, though. See #2374
