### ISSUE TITLE
Adding image to wysiwyg html editor from stack fails.

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#2947]
If you enable images in your wysiwyg config and then attempt to insert images from the stack using that functionality it fails. What happens is you click on the image in the popup that appears and instead of that being put into the editor you end up looking at the full size version of the image in the tiny popup window. 

If you choose to navigate to the image via the filesystem view beneath the stack and click on one of the images presented there it works fine. i.e. the image is inserted into the image dialog correctly and appears in the preview. 

This is using a new bolt 2.0.6 install. I have verified the issue exists with a friend also using bolt on a different stack.

**Comment by GDmac** [comment]
I can't reproduce in 2.0.6 not in github:master branch. 
Can you supply a bit more info? Which browser are you using?
Can you verify via browser devtools/firebug that there are no javascript errors?
(e.g. all javascripts loaded)

**Comment by GawainLynch** [comment]
I can reproduce on master with Chrome 40.0.2214.115 (64-bit)

I end up with something like this
```html
<img height="100" src="http://example.com/thumbs/100x100c/2015-02/kittens.jpg" width="100" />
```

**Comment by GawainLynch** [comment]
No console errors from the insert.

**Comment by cooperaj** [comment]
I've figured out how to replicate it. Or rather how you can.

So I have the issue as detailed. But I also have *no* images in the top level folder. I have them all hidden away in subfolders. After uploading a file to the top level folder everything appears to work exactly as intended when clicking on a stack item. Deleting that top image gets me back to my original issue. 

I'm guessing that whatever javascript is needed to insert into ckeditor isn't made available unless a non-stack image is shown.

**Comment by GDmac** [comment]
still can't reproduce. 
Far fetched, i can see a possible ``bind()`` being used instead of ``on()`` (where the latter being the preferred handler method since jQuery 1.7). Sorry hopefully others can reproduce, check this.

**Comment by cooperaj** [comment]
I think i've found the issue. I'm not sure why you can't replicate but the change I made has solved my problem.

In files_ck/_files.twig you have 

    {% import '_macro/_macro.twig' as macro %}

    <table class="dashboardlisting"{{ macro.attr({_bind: ['ckfileselect']}) }}>

Which I'm assuming causes the code to run bindCkFileSelect in bolt.min.js (init.js). This code obviously doesn't get run if no images are shown the table at the bottom of the dialog. Adding that code to the files_ck.twig file in the h1;

    <h1 {{ macro.attr({_bind: ['ckfileselect']}) }}>{{ block('page_title') }}</h1>

Along with the appropriate import statement causes everything to work as I'd expect.

**Comment by rarila** [comment]
@cooperaj I have a look at it …

**Comment by rarila** [comment]
@cooperaj Good catch!

To clear things up (and why GDmac couldn't reproduce it): the error only occured when there where no files in the top level of directory and files on the stack (stack is only displayed on toplevel). The binding was done on file listing and if there was none …
