### ISSUE TITLE
float type buggy for clients with locale fr

### ISSUE THREAD

**Issue by joanlouis** [bolt/bolt#2956]
the fr locale use coma for decimal separation using input type number cause bug because the value have coma and the browser want a dot.
maybe it is safe to not use locale for the form values in the backend?
or not use the buggy input type number for floats (all browsers are buggy)

**Comment by GawainLynch** [comment]
Any ideas @rarila?

**Comment by GDmac** [comment]
It is an issue. How about (like datetime has) have two inputs [ int ],[ fraction ]

> The specification defines the decimal separator as a period regardless of the locale.[2] However, the value the user inputs or the value that is displayed to the user does not need to meet this technical requirement.... 
https://www.aeyoun.com/posts/html5-input-number-localization.html

**Comment by rarila** [comment]
After some testing it looks like that number type is absolutely unpredictable. Looks like we have to homebrew something :-(

@joanlouis Don't use floats ;-))

**Comment by bobdenotter** [comment]
Dutch has the same "problem: as French. Often I just use integers to avoid the problem altogether. Storing the cost or price of something, like € 2.59? Use `amount in cents` = `259`.

**Comment by rarila** [comment]
@joanlouis A fix is half done yet …

**Comment by joanlouis** [comment]
if you need some tests, i can help

**Comment by rarila** [comment]
@joanlouis You can help by heavily testing of this patch. I'm sure I have added some bugs to find ;-)

**Comment by joanlouis** [comment]
tested on safari, firefox and chrome on mac os firefox on linux and safari on iOS i don't find bugs.

**Comment by rarila** [comment]
Great to hear, thanks!
