### ISSUE TITLE
Ordering records using drag'n'drop isn't working.

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2958]
Don't know if this is supposed to be working because it's not really documented, but every record is showing up as "Order 0"

![image](https://cloud.githubusercontent.com/assets/3238878/6407128/255860ba-be9f-11e4-8a9d-5714e6d20925.png)

Shifting them around doesn't do anything except an error throws in the browser console (in 2.0.6):

```
POST http://localhost/sunderland/bolt/content/sortcontent/pages 404 (Not Found)
```

My local master copy throws a different error with an `undefined` thrown in

```
POST http://localhost/bolt/bolt/overview/undefinedcontent/sortcontent/pages 404 (Not Found)
```

I suspect the code for this is in a state of limbo, but I thought I'd post this in case nobody was aware.

**Comment by xiaohutai** [comment]
Hm. I think drag and dropping them isn't implemented yet but somehow this got through. At the moment, you can only manually set a sort value to a record with a `grouping` taxonomy. Like so:

![grouping](https://cloud.githubusercontent.com/assets/4630335/6414745/26f16408-be9a-11e4-9465-cdacd0fd2433.png)

**Comment by bobdenotter** [comment]
I suspect this was snuck in by @rarila a while ago. "sorting pages by drag'n'drop" is a feature that's requested occasionally, and it seems like this is the groindwork for it. Like you noticed, it's just not done yet. 

I've taken the liberty of editing the title to find it easier later on, when we're going to fix this. :-)

**Comment by rarila** [comment]
@bobdenotter Ei incumbit probatio qui dicit, non qui negat.

**Comment by Largo** [comment]
Soo, I needed this feature pronto, so I hacked an extension together which fixes that problem. I'm a beginner in symphony and bolt internals. Just posting this here, in case somebody needs it. 
Obviously not future proof and without out any warranty :)
Not sure why line 52 was necessary, but I ran out of time to investigate.

https://gist.github.com/Largo/d7371d4ba8c8846fdc38

**Comment by SahAssar** [comment]
Also somewhat related is #2989

**Comment by bobdenotter** [comment]
This is how sorting works: https://github.com/bolt/docs/blob/release/2.2/source_docs/howto/sortingorder-in-contenttypes.md

**Comment by SahAssar** [comment]
@bobdenotter Sorry, but this really isn't solved. The taxonomy sortorder, while sufficient for some usecases, really isn't enough.

**Comment by Boorj** [comment]
Probably we could have a special page, dedicated to sorting (and probably some other actions). It could make like easier, not trying to overloat the current listing in overview.

**Comment by GawainLynch** [comment]
This is still in play, but bumping to 3.5 as 3.4 goes into beta next week and there hasn't been time between @SahAssar and myself.

**Comment by SahAssar** [comment]
This is not critical nor has anyone actively working on it right now, if anyone would like to work on it please talk to me, the extension I made should be an okay-ish starting point.

**Comment by zomars** [comment]
@SahAssar can you link the extension you made?

**Comment by SahAssar** [comment]
@zomars Sure, this is it: https://market.bolt.cm/view/sahassar/dragsort

It doesn't work with taxonomies and I haven't tested it on 3.4+, but it's pretty basic (under 10 lines of backend code) so it should work okay-ish.
