### ISSUE TITLE
No route found for "GET /app/LICENSE.txt"

### ISSUE THREAD

**Issue by gander** [bolt/bolt#2968]
Probably missing license file?

**Comment by GawainLynch** [comment]
It's not in `/src/LICENSE.txt`.  How are you triggering this?

**Comment by gander** [comment]
Link found on page "/bolt/about".

**Comment by GDmac** [comment]
Yes, it's (currently) in /src and linked from twig/about
{{ app.translator.trans('about.licence', {'%paths_app%': paths.app}, 'infos')|raw }}

RFC
1. move LICENSE.txt to bolt root dir (next to readme)
2. the link should point to a template that reads the license file and displays
   (this prevents hotlinking to possibly unreachable dirs)

**Comment by GawainLynch** [comment]
The approaches discussed on IRC won't work as we're currently documenting.

@GDmac this is all yours once 2.1 is branched.  

![](http://i.imgur.com/funZXrj.jpg)

**Comment by GDmac** [comment]
alternative temp quick fix: 
- add backend route /about/license (see about method), 
- copy license.txt to app/view/about/license.twig

**Comment by GawainLynch** [comment]
> add backend route /about/license

![](https://github.com/bolt/bolt/issues/2968#issuecomment-76430571)
