### ISSUE TITLE
Database prefill

### ISSUE THREAD

**Issue by gander** [bolt/bolt#2969]
No link to "/bolt/prefill" in dashboard. There is only "/bolt/prefill?force=1".

**Comment by GawainLynch** [comment]
That is correct and intended behaviour. If the database is empty the link is shown on the dashboard. Otherwise it is shown in the "Check database" page content.

**Comment by GawainLynch** [comment]
That is correct and intended behaviour. If the database is empty the link is shown on the dashboard. Otherwise it is shown in the "Check database" page content.

**Comment by gander** [comment]
Ah, I see it now.
