### ISSUE TITLE
Content type Save and return to overview need to clicked two times

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#2981]
Content type Save and return to overview need to clicked pressed two times as the first hit on the button seems to do nothing.
And its too much clicking, isn't?

**Comment by bobdenotter** [comment]
This looks very much like this one: #2735

However, I've not been able to reproduce it yet.

**Comment by lexislav** [comment]
Looks like that one, I did poor research :-(
I can email You access to the site, where it „works“, if You want. Or send You a copy of site.

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
