### ISSUE TITLE
[RFC] Bolt Release Process

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2985]
### Background

Bolt is an evolving project and has come a long way since this commit:

```
commit 656959d875e1ad4e93ee528a33a10f61635ade6d
Author: bobdenotter <bobdenotter@gmail.com>
Date:   Thu Jun 14 09:07:55 2012 -0700

    Initial commit
```

As I write this, we have 139 contributors and [over 9,000](http://vignette4.wikia.nocookie.net/dragonball/images/4/4b/VegetaItsOver9000-02.png) commits… both of those number increasing steadily.

Since branching Bolt v1 and commencing on the path to Bolt v2 we've spent time thinking about how, as a community based project, to best manage our release process. Some of the points that we're trying to consider in this discussion are:
- Keep the project moving… don't stagnate
- Keep our processes in line with our vision of simplicity
- Keep the management of processes from interfering with the fun we have writing the code, documentation, and community interaction
- Learn from the success of other projects, as well as from their mistakes
- Release early, release often!

### New Features

For a new feature there is a three step process:

*Note*: This obviously doesn't include bug fixes

##### Step 1 RFC submission
Create a GitHub issue with the prefix of `[RFC]` in the subject line.

Describe:
- What the feature is
- What the impacts are

##### Step 2 RFC moved to Roadmap

Once approved, a core team member will add the feature and contributor's GitHub handle to the [Roadmap](https://github.com/bolt/bolt/wiki/Bolt-2.x-Roadmap) wiki page

##### Step 3 Feature implemented and merged into version `-next`

Once the feature window is open the contributor can submit a PR for review and merging.

### Schedule & Roadmap

It is proposed that the schedules follow the basic pattern of:
- 14 day feature window (hard limit)
- 14 day bug fix window (soft end-limit)
- 14 day contingency window (only if required)
- Release!

An example would be:

| Window   | Open (09:00 UTC) | Close (midnight UTC) |
|----------|------------------|----------------------|
| Feature  | 09 March 2014    | 22 March 2014        |
| Bug Fix  | 23 March 2014    | 05 April 2014        |
| Release  | 06 April 2014    | n/a                  |

I have drafted a [Roadmap wiki page](https://github.com/bolt/bolt/wiki/Bolt-2.x-Roadmap) that, if we accept this proposal, should be maintained for the 2.x development cycle and added to for each upcoming/new release.

**Comment by bobdenotter** [comment]
Looks good to me! :-)

**Comment by CarsonF** [comment]
Yeah I like it. 

Symfony also has a template for their PRs (I adopted it below)

| Q             | A
| ------------- | ---
| Bug fix?      | [yes\|no]
| New feature?  | [yes\|no]
| BC breaks?    | [yes\|no]
| Deprecations? | [yes\|no]
| Fixed tickets | [comma separated list of tickets fixed by the PR]
| Changelog    | [High level change for changelog]

**Comment by rossriley** [comment]
plus...

| Q             | A
| ------------- | ---
| Added any statics? | [yes\|no]

**Comment by GawainLynch** [comment]
@rossriley I think you meant:

| Q             | A
| ------------- | ---
| Added any statics? | [CarsonF\|no]

**Comment by CarsonF** [comment]
I never thought I would be the statics guy. I'm usually playing the opposite role with a coworker.

**Comment by GawainLynch** [comment]
"It was just one time!"

**Comment by CarsonF** [comment]
Seriously though, I think I've done literally like 2 methods and suggested 1.

**Comment by bobdenotter** [comment]
![448e29cf55d7a9403cca98da77e54654](https://cloud.githubusercontent.com/assets/1833361/6468896/c05c0b70-c1d8-11e4-8608-6d0cfde599ee.jpg)

**Comment by GawainLynch** [comment]
> Seriously though, I think I've done literally like 2 methods and suggested 1.

And you removed all ones in `Bolt\Controllers\Frontend`… versus the guy who did `Bolt\Library`…

**Comment by bobdenotter** [comment]
> versus the guy who did Bolt\Library 

There was literally decade-old code in there. ;-)

**Comment by GawainLynch** [comment]
Oh yes, not pointing fingers at `lib.php` just the Australian character that did `Bolt\Library` :eyes:

**Comment by CarsonF** [comment]
Really the only static I want is #2464

**Comment by GawainLynch** [comment]
> Symfony also has a template for their PRs (I adopted it below)

Probably a separate discussion, at a later time I would guess… Unless anyone has some strong preference for this?  As things stand I would see it not *fit* with these:
* Keep our processes in line with our vision of simplicity
* Keep the management of processes from interfering with the fun we have writing the code, documentation, and community interaction

That being said, this morning's IRC discussion about the 2.1 beta looks like we might be heading for a March 9 release, so if anyone has criticism/feedback on this can you get it in a.s.a.p. as the consensus seems to be in favour of this approach.

**Comment by rossriley** [comment]
Only addition to this, is how we keep an eye on test coverage. It's fine for contributors to submit code without test coverage but in the review somebody, either the contributor or a reviewer, or a friendly helper should do a before/after check on the code coverage.

It's only necessary for the specific module, so if the contribution was for the configuration classes, just run `phpunit tests/Configuration` before and after the PR and make a note in the table. If there's an impact then it gives us an attempt to address it, either as part of the PR or via a separate issue/

**Comment by CarsonF** [comment]
Is there a tool that can do this for us?

**Comment by GawainLynch** [comment]
Yes, almost finished writing it.

**Comment by GawainLynch** [comment]
OK, looks like [we're go!](https://github.com/bolt/docs/pull/166)
