### ISSUE TITLE
Output raw HTML in Markdown

### ISSUE THREAD

**Issue by callmenick** [bolt/bolt#2992]
I am using markdown as my text field, but want the ability to output raw HTML and have it not be stripped. For example, let's say I have a little tutorial going on, and then I want to output some inline SVG and some custom styles in a style tag, it seems that markdown completely ignores the inline svg code, and actually outputs the styles as text on the screen.

Is this something to do with Parsedown itself? Is there any way I can alter this?

In particular, I'm looking at this part of the Parsedown documentation, where they run some tests on "block level html":

http://parsedown.org/tests/block-level_html/

The tests on their site give me the desired results, but the way Bolt outputs it doesn't satisfy those tests.

**Comment by tobias2k** [comment]
On Sun, Mar 01, 2015 at 04:44:32PM -0800, Nick Salloum wrote:
> I am using markdown as my text field, but want the ability to output raw HTML and have it not be stripped. For example, let's say I have a little tutorial going on, and then I want to output some inline SVG and some custom styles in a style tag, it seems that markdown completely ignores the inline svg code, and actually outputs the styles as text on the screen.
> 
> Is this something to do with Parsedown itself? Is there any way I can alter this?

If you don't need any of the usual markdown features, you could just use
a plaintext field (textarea), and in your template, slap the `|raw`
filter on it to keep Twig from HTML-encoding the field.

Note, however, that there are a few considerations that may not be
obvious:

- By allowing editors to enter arbitrary HTML, it becomes easy to break
  the page from within - e.g., it is possible to insert stray `</div>`s
  in your HTML content, causing subsequent content to be rendered
  outside of the intended DOM elements.
- Arbitrary HTML in your content is a security risk, because it opens up
  a window for (persisted) XSS attacks. The most trivial case would be
  if an editor manually injects `<script>` tags, but more sophisticated
  attacks could otherwise trick the system into storing potentially
  malicious HTML without the editors themselves doing it on purpose.
  This is the main reason why markdown output gets stripped and cleaned
  up.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2992

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by callmenick** [comment]
Hm. It is for a personal site, so I'll have no problem with malicious attempts. I do want to keep the markdown though, as I write my articles in markdown anyway. Is that raw tag available in markdown too? Or is there any way to prevent the markdown parser from stripping out the html?

Some HTML actually works, like using a custom class on a link or paragraph element. Some doesn't at all though. Thanks for the input.

**Comment by callmenick** [comment]
@tobias2k Check this out. I realised that Bolt is actually using Maid, which is an HTML cleaner, after it parses the markdown.

```php
switch ($fieldtype) {
    case 'markdown':

        $value = $this->preParse($this->values[$name], $allowtwig);

        // Parse the field as Markdown, return HTML
        $value = \ParsedownExtra::instance()->text($value);

        // Sanitize/clean the HTML.
        $maid = new \Maid\Maid(
            array(
                'output-format' => 'html',
                'allowed-tags' => array('html', 'head', 'body', 'section', 'div', 'p', 'br', 'hr', 's', 'u', 'strong', 'em', 'i', 'b', 'li', 'ul', 'ol', 'menu', 'blockquote', 'pre', 'code', 'tt', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'dd', 'dl', 'dh', 'table', 'tbody', 'thead', 'tfoot', 'th', 'td', 'tr', 'a', 'img'),
                'allowed-attribs' => array('id', 'class', 'name', 'value', 'href', 'src')
            )
        );
        $value = $maid->clean($value);
        $value = new \Twig_Markup($value, 'UTF-8');
        break;
```

Maid accepts some options, including `allowed-tags` and `allowed-attribs`. Naturally, it strips out script tags, style tags, and the works, to prevent against malicious user input. In my case though, I'm the only one doing user input.

If I edit the options myself, these will get overwritten with future updates of Bolt, no?

**Comment by bobdenotter** [comment]
> If I edit the options myself, these will get overwritten with future updates of Bolt, no?

Yes, they will get overwritten. Perhaps we should make these configurable, in the global `config.yml`, then you could add a bunch of tags and attributes, without blatantly allowing `script` and `onhover`. Would that work for your usecase?

**Comment by tobias2k** [comment]
Yes, I know. I am the author of Maid.

Bolt already passes an explicit list of allowed tags and attributes to
Maid, which means that changing the defaults in Maid itself would
achieve exactly nothing.

Changing the list that Bolt passes to Maid would do what you want, but
as @bobdenotter notes, future Bolt updates would override your changes.
If you're fine with manually undoing this after every Bolt update, go
ahead.

The clean solution would be to add a config.yml option to Bolt for the
Maid configuration; this would require changes to Bolt Core, but once
these are in place, you could manage that list as part of your site
configuration.

On Fri, Mar 06, 2015 at 08:43:45PM -0800, Nick Salloum wrote:
> @tobias2k Check this out. I realised that Bolt is actually using Maid, which is an HTML cleaner, after it parses the markdown.
> 
> ```php
> switch ($fieldtype) {
>     case 'markdown':
> 
>         $value = $this->preParse($this->values[$name], $allowtwig);
> 
>         // Parse the field as Markdown, return HTML
>         $value = \ParsedownExtra::instance()->text($value);
> 
>         // Sanitize/clean the HTML.
>         $maid = new \Maid\Maid(
>             array(
>                 'output-format' => 'html',
>                 'allowed-tags' => array('html', 'head', 'body', 'section', 'div', 'p', 'br', 'hr', 's', 'u', 'strong', 'em', 'i', 'b', 'li', 'ul', 'ol', 'menu', 'blockquote', 'pre', 'code', 'tt', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'dd', 'dl', 'dh', 'table', 'tbody', 'thead', 'tfoot', 'th', 'td', 'tr', 'a', 'img'),
>                 'allowed-attribs' => array('id', 'class', 'name', 'value', 'href', 'src')
>             )
>         );
>         $value = $maid->clean($value);
>         $value = new \Twig_Markup($value, 'UTF-8');
>         break;
> ```
> 
> Maid accepts some options, including `allowed-tags` and `allowed-attribs`. Naturally, it strips out script tags, style tags, and the works, to prevent against malicious user input. In my case though, I'm the only one doing user input.
> 
> If I edit the options myself, these will get overwritten with future updates of Bolt, no?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2992#issuecomment-77673426

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by callmenick** [comment]
I think that would be good. I think Bolt has some serious potential to attract a variety of bloggers/writers as well as just being a CMS, and those include technical writers. For example, I run my own blog, callmenick.com, that's a web dev blog in a nutshell. But I'm porting everything over from WordPress to Bolt, because I really like it, and I've been making a conscious effort to use lighter and sleeker platforms like Bolt (which I'm now experimenting with quite a bit, and really enjoying).

I write all my entries in Markdown, and some of them might include a little custom SVG demo, or some custom HTML with inline style attributes, for example. I think that making it configurable via the config.yml file would be awesome. Let me know your thoughts @bobdenotter

**Comment by bobdenotter** [comment]
Agreed. We'll make this configurable in `config.yml`. :-)

**Comment by callmenick** [comment]
:) nice. anything i can do to help the process?

**Comment by bobdenotter** [comment]
I was _just_ finishing up on this. There will be a PR in a few minutes, and it'll be in the very next Bolt update. :-)

**Comment by callmenick** [comment]
Wow, awesome. Fantastic work, and I'm beyond mere appreciation for the communication and eagerness! Keep it all up.
