### ISSUE TITLE
When a content is updated on pre_save, UI is not refreshed wth new values

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#2994]
(tested on bolt 2.1 beta2)

Using defaut "entry" content-type and having a listener which sets entry's teaser to a custom value. 

When clicking "save entry", ajax payload indicates the newest value but form is not updated. A single refresh of page doesn't display the new value, I need to click on entry in the listing to see the new value.

(tested on FF 38 and Chrome 40, release channels on both)

**Comment by GawainLynch** [comment]
Ping @rarila: I have created [a sample extension](https://github.com/GawainLynch/bolt-extension-tester-events.git) that simulates this. The events are firing OK, but the CKEditor fields are not being updated, but fields like title are fine.

Any ideas?

**Comment by GawainLynch** [comment]
OK the meat and potatoes of this one [is here](https://github.com/bolt/bolt/blob/master/app/view/lib/bolt/init.js#L151-L164).

We're assuming an input.

**Comment by rarila** [comment]
@GawainLynch Sure I have

**Comment by GawainLynch** [comment]
Got a fix in bound

**Comment by rarila** [comment]
Ok, then I asign you
