### ISSUE TITLE
HTTP 500 error retrieving tags

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2996]
Loading a page in edit mode with tags enabled (standard `entries` in this case) give the following error:
```
GET http://example.com/async/populartags/tags?limit=40 500 (Internal Server Error)
```

**Comment by GawainLynch** [comment]
```
Doctrine\\DBAL\\Exception\\SyntaxErrorException
An exception occurred while executing 'SELECT slug, COUNT(slug) AS count\n FROM bolt_taxonomy\n WHERE taxonomytype = ?
 GROUP BY slug 
 ORDER BY count DESC
 LIMIT ?' with params ["tags", 40]

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''40'' at line 6"
[snip]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line:90
```

**Comment by GawainLynch** [comment]
Broken by #2584. 

We probably need to look at `Async::tags()` and `Async::populartags()`.

@CarsonF I am going to PR a fix, you might want to have a look at it when you come online to make sure it doesn't break the use-case you were aiming for with that PR.

**Comment by CarsonF** [comment]
Oh did the newline characters break it?

**Comment by GawainLynch** [comment]
Not sure why, but reverting back past it and the error didn't show here.

**Comment by CarsonF** [comment]
That's probably what it is. I'm used to my abstraction layer filtering them out.
