### ISSUE TITLE
Editcontent input id's

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2999]
This is a reminder for two things to do:

- Prefix all id's of input elements so that they can't collide with existing id's used by e.g. css or elsewhere for other uses. Otherwise some fieldname that's accidently is the same as another idea could do some harm.

- Look through our javascript code for jQuery selectors like this ``$('#' + id)``, that would break on non ASCII ids like ``foo:bar``. Best to be replaced by ``document.getElementById()`` which is supposed to be quite faster also.

**Comment by GawainLynch** [comment]
@rarila wasn't this done in your last couple of mega-PRs?

**Comment by rarila** [comment]
No, still todo

**Comment by rarila** [comment]
As field id's and the usage to address field elements from javascript are removed to make repeaters happen I think this issue can be closed.
