### ISSUE TITLE
Possible problem in the near future!

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#3000]
I'm sure a few of you Bolts are old enough to remember the time where we al were afright of the Millenium bug, also know as the [year 2000 problem](http://en.wikipedia.org/wiki/Year_2000_problem).

It is for sure a good idea to start no – only the early bird catches the worm – to start now and prevent us from a hurry just before the next problem arrives. So let us search our codebase for possible incidence **now**, to guard against the upcoming arrise of the Year 3000 problem, also known as #3000! :tada:

**Comment by bobdenotter** [comment]
:tada: :balloon: :birthday: :tada: :balloon: :birthday: :tada: :balloon: :birthday: :tada: :balloon: :birthday: :tada: :balloon: :birthday: :tada: :balloon: :birthday:

**Comment by jkazimir** [comment]
In accordance with the official Bolt rules and regulations, this must be linked with it's associated PR: #1555.

**Comment by GDmac** [comment]
Coming close to 1023 * 3 = 3096  - #2046

**Comment by GawainLynch** [comment]
![3000](https://cloud.githubusercontent.com/assets/1427081/6461200/87929d4c-c195-11e4-81ad-f8db00e815ea.jpg)

**Comment by GDmac** [comment]
Hello IRC

**Comment by ProfoundGames** [comment]
I hope we have fixed this issue within 985 years! :-O

**Comment by Intendit** [comment]
Shouldn't this be tagged with "Milestone: bolt 591.1"? (which is where we will be in 985 years by my calculations).

**Comment by bobdenotter** [comment]
This was fun, but i'm spring cleaning! #buzzkill :neckbeard:
