### ISSUE TITLE
Ability to make slugs not add prefixes for numbers

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3001]
If have a record (say, of contenttype page) with a slug that is generated from a number, it will give you a slug: `page-<x>`. To me this is unexpected behaviour, especially if you are manually entering the slug by clicking on the pencil and editing it.

While I would like the default to be to add no prefix at all, I understand that this feature is here for a reason. Could there be an option for slug fields to not add a prefix?

**Comment by bobdenotter** [comment]
Bolt really likes for slugs to be unique. I'm having a hard time understanding why you'd want this. :-)

**Comment by GawainLynch** [comment]
To add to what @bobdenotter said. This would, in a few ways, be a backwards compatibility break. 

We currently assume that a record is available by it's `contenttype/id` as well as its `contenttype/slug`.  Something that Bolt avoids by doing this (that drove me nuts — pun intended — in other systems was the `/index.php?1234` junk)

The id/slug consistency is also used in our query processing and the like… So, to say the least, this would be a *very* big job to implement :crying_cat_face:

**Comment by Pinpickle** [comment]
Ah fooey. The use case was a house contenttype that had a lot field which I wanted to be its slug - so you'd get:
`/house/<lotno>`

At the very least could we gain the ability to customise what that prefix is? Because `house/house-<x>` looks silly in my opinion. I would be happy with a method to change it to `house/lot-<x>`

**Comment by GawainLynch** [comment]
You should be able to do `contenttype/prefix-N` now. Bolt will, by default, create the initial slug out of what you tell it to in `contenttypes.yml`.  Our default is `uses: title`, but you should be able to "unlock" and "edit" it. 

This did temporarily break at some point during 2.0, so if it's not working for you right now can you update to 2.0.6 (even better if you could quickly check on 2.1-beta2) and open an issue if the problem persists… We'll send the Bolt Medical Team rushing in :ambulance:

**Comment by Pinpickle** [comment]
I know myself (or a client) could manually change it to `lot-<x>` but it's not super intuitive if you don't have any idea of what a slug is, or how urls work, or if you even care what your urls look like. I'll roll with this for now, and can see the feature as being a low-priority but here's how I see it working:

```
type: slug
uses: lot
number_prefix: lot
```

I suppose a hackish way to do this would be to add a select field with a default value, and only one value, and that being the prefix you want, and then use that field as well as the number field to generate the slug. But that's quite a hack.

**Comment by GawainLynch** [comment]
> I know myself (or a client) could manually change it to lot-<x> but it's not super intuitive if you don't have any idea of what a slug is, or how urls work, or if you don't care what your urls look like

This reminded me of a certain part of our [manifesto](https://docs.bolt.cm/manifesto):

> Bolt aims at three groups of users: Editors (content writers and editorial staff), Frontend developers (HTML/CSS specialists and implementers) and Backend developers (coders, devops and sysops). All three are equally important.

Anyway, a few of our field types at the moment support `postfix` and @bobdenotter has the best ideas when it comes to approaching these problems… But I don't see `prefix` or `postfix` as too much to implement for an upcoming release :grinning:

**Comment by Pinpickle** [comment]
@GawainLynch that's exactly the part of the manifesto that I was thinking about and the reason why Bolt is the best CMS.

**Comment by bobdenotter** [comment]
@Pinpickle OK, here's a hackish solution for you, but it might just be enough for what you need: 

```YML
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: dummy_lot

... and at the very bottom of the fields list: 

        dummy_lot:
            label: " "
            type: text
            readonly: true
            class: hidden
            default: "lot-"
```

It will look like this: 

![screenshot 2015-03-03 20 54 35](https://cloud.githubusercontent.com/assets/1833361/6470940/99662172-c1e7-11e4-92fc-0d3355a56ae4.png)

**Comment by Pinpickle** [comment]
@bobdenotter now that's more of a hack that I can get on board with!
It works and is pretty ~~client~~ fool proof

I'll probably do a PR for the proper feature once this 2.1 hullaballoo is over.

**Comment by bobdenotter** [comment]
Ok, closing this issue then.. ^_^
