### ISSUE TITLE
paths.currenturl (and probably other paths) doesn't take into account subdirectories/base

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3008]
Spotted this in the RSS Feed extension which uses `paths.current` and I noticed that the url, which should be `http://localhost/site/contenttype/feed/rss.xml` was just `http://localhost/contenttype/feed/rss.xml` (note the lack of `site` in the second url).

The culprit is the code here in [ResourceManager at 277-285](https://github.com/bolt/bolt/blob/f3f3eae52c9165864844d17c1a20c368044dc760/src/Configuration/ResourceManager.php#L277), not taking into account `$request->getBasePath()` as the paths a few lines above do.

**Comment by CarsonF** [comment]
Grrrrr I should've caught that. Will PR soon.
