### ISSUE TITLE
Using twig {% extends %}

### ISSUE THREAD

**Issue by thi3rry** [bolt/bolt#302]
Why do not use twig extends features instead of include ?

Include implies that some html elements should be open in one template and close in another. But if we forget including the closing template, or if you wont include it, your HTML become invalid.

It should be great to use extends with block to extends each part of a template.
We can do it in custom templates, so why don't use it in based theme ?

Bolt would be "simple". Is that concept so complex for bolt ?

**Comment by psren** [comment]
Is there anything to do here?
It seems that this is not integrated in bold2 or do i miss something?

**Comment by bobdenotter** [comment]
The Bolt backend has been completely rebuilt, using twig template inheritance. What are you looking for? :-)

**Comment by psren** [comment]
Okay, i watched at the default frontend theme, but it's no problem to do this my self :-)
