### ISSUE TITLE
[RFC] Knowledge base pages instead of long error messages

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#3021]
More and more such kind error messages or warnings like #3020 appear. They have to be quite long to be helpful for the less tech-savvy and probably still can't be long enough. And our message catalo get's filled with long error messages.

I have a proposal for this: How about just putting generic message there like

`You have a problem! See here for more information.`

and link that to a knowledge base page like [`https://kb.bolt.cm/allow_url_fopen`](http://www.lovethispic.com/uploaded_images/41500-Playful-Kittens.jpg). There could then be a page with excessive info, links, screenshots, if you like it hot, user comments (like php docu, always helpful …)
That would also free us from some support questions on IRC.

PS: kb might remind you to something you hate. The name is just a example and the information on that pages should be something useful instead … :-)

**Comment by GawainLynch** [comment]
Its a hard one. On the one hand we need to do something! But we run the risk of fragmenting information all over the place. Maybe expanding the way our docs page can be interacted with, or the like?

**Comment by rarila** [comment]
Could also live at the docs section… knowledge base appendix or whatever.

**Comment by bobdenotter** [comment]
Yes, i'd like this. At the docs sounds like a good idea.. For some of these messages, we could add something like "For more info, see [this section] in the online documentation."

**Comment by rossriley** [comment]
This can tie in nicely with the upcoming refactor of exceptions. The plan is to throw much more specific exceptions / codes instead of the generic one we have at the moment in which case we can link to a supplementary page too.

**Comment by SahAssar** [comment]
@PhillippOhlandt You were talking with @bobdenotter about a new search engine for the docs, right?

Any way we could link to just a search query there and have this be a bit easier?

**Comment by PhillippOhlandt** [comment]
@SahAssar yes, algolia.com but there wouldnt be a search query to link to. look at the laravel documentation to see how the search works.

**Comment by SahAssar** [comment]
@PhillippOhlandt I mean that from the error we could link to something like docs.bolt.cm?search=Mailoptions%20not%20set from the error message and have that preform a search in the docs (and perhaps github and the forums?) when following the link.

**Comment by PhillippOhlandt** [comment]
Yes I am for that when you know how to trigger Algolia and search Github and the Forum. But I am not sure about performance. Searching Github and the Forum can take very very long.

**Comment by SahAssar** [comment]
@PhillippOhlandt Personally I'd be okay with a slightly longer response time if it means getting a complete response. Do you know if Algolia has any github API integration?

**Comment by PhillippOhlandt** [comment]
I don't think they have on. Algolia is like a hosted elastic search but not with elastic search as engine.

**Comment by rarila** [comment]
My idea was bit different. Using a search machine and then having to find out which result fits to my problem is just a step more of what I can do myself. My idea was a special page that just handles that one error.

**Comment by SahAssar** [comment]
So is this something that we see as possible in the near future, or should this be put on a backburner to-do list?

**Comment by GawainLynch** [comment]
Needs a volunteer … maybe that should be a tag :stuck_out_tongue_winking_eye:

**Comment by SahAssar** [comment]
Closing for now. This is one of those that would be awesome, but seems like noone has had time to work on it, it isn't a bug, and it has been open for far too long without any progress.
