### ISSUE TITLE
Not currently possible to move files around folders in the File Management UI.

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#3025]
When using the file management UI it is not possible to move files. You can create folders and upload into them but existing files have to stay where they're put. 

It will be important to be able to move files up the structure as well as down so dragging images to a folder cannot really be the only option.

**Comment by rossriley** [comment]
Whilst you wait for this feature to be implemented properly, there's a nice little hack that the 'rename' functionality can contain directory paths, so renaming test.jpg to `../test.jpg` or `../asubdir/test.jpg`

Obvious caveat is that for security reasons this is anchored to the root of your `files` directory and any attempt to move files outside this base won't work.

**Comment by cooperaj** [comment]
As an added issue moves within the UI like this should conceivably alter any references to the file in content so that images don't break. I realise thats a more tricky problem.

**Comment by SahAssar** [comment]
I'm trying to gather all the requests/features for media/file management in #574, so I'm closing this. If anyone has any objections let me know :)
