### ISSUE TITLE
Loading Bolt pages via AJAX results in 404 template not found

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#3026]
Hi, I've done this with older versions of Bolt but with the new release 2.x I seem to be having issues.

What's happening is when I make the GET request via AJAX Bolt returns a 404 with the following message: 

```
{"error":{"type":"Symfony\\Component\\HttpKernel\\Exception\\HttpException","message":"No template for 'homepage' defined. Tried to use 'fusca\/index.twig'.","file":"C:\\Websites\\fusca\\htdocs\\vendor\\silex\\silex\\src\\Silex\\Application.php","line":378}}
```

It does this for all pages (the template name changes depending on the resource being accessed as per my config). The thing is though, when I visit the requested page directly through the browser it loads fine. My JS looks like this:

```
$.ajax({
    type: 'GET',
    url: 'http://fusca.loc',
    dataType: 'html'
}).done(function(data) {
    console.log(data);
});
```

**Comment by bobdenotter** [comment]
Which version _exactly_? ;-)

**Comment by diggersworld** [comment]
Bolt 2.0.6 and jQuery 2.0.3.

**Comment by GawainLynch** [comment]
Fixed in 2.1-beta #2874

**Comment by diggersworld** [comment]
Oh OK. That config file is quite different to the one in 2.0.3.

What is the best way for me to proceed in fixing this issue?

**Comment by bobdenotter** [comment]
Update to 2.1.0 beta 4. It's quite stable. :-)

**Comment by diggersworld** [comment]
OK, cheers guys. Liking the new look by the way. :+1:
