### ISSUE TITLE
grunt: updateLib

### ISSUE THREAD

**Issue by jirimedved** [bolt/bolt#3029]
```
Running "cssmin:installLibCss" (cssmin) task

Running "libcssimg:" (libcssimg) task
Warning: URL not handled: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7' Use --force to continue.

Aborted due to warnings.
```

**Comment by rarila** [comment]
Ok, interesting. here I get:
```
…
Running "cssmin:installLibCss" (cssmin) task

Running "libcssimg:" (libcssimg) task

Running "concat:installLibJs" (concat) task
…
```

Your case should just be handled fine [by](https://github.com/bolt/bolt/blob/master/app/view/Gruntfile.js#L511).

So is this a node issue, a OS issue…? Anyone else having this problem?

**Comment by rarila** [comment]
Ok, found the problem: it's the ’’'’’.
For some reasons your toolchain outputs ``url('data:…')`` instead of  ``url(data:…)``. I guess I probably have to handle both cases …

**Comment by rarila** [comment]
Hmm, meanwhile could you try a ``npm install`` to see if a newer version would help here?
I would say minífying css would involve removing unneccessary quotes …
