### ISSUE TITLE
initProfiler() in Application.php breaks session handling flexibility.

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#3036]
Thanks to Dan1 in IRC who found this problem. 

The problem line is here: https://github.com/bolt/bolt/blob/master/src/Application.php#L221

Accessing session here before the app->run() cycle breaks the ability for users to override the default session handler. This is because the session is a shared object created only once and because this runs before the user has a chance to do any post-init code then overriding is impossible.

The functionality that tests for the logged in user needs to be moved into a normal service provider so the session object isn't consulted until after everything is initialised.

**Comment by CarsonF** [comment]
Why can't one extend Application and override that method.

**Comment by rossriley** [comment]
Yes, you're right i found a separate problem, so this is just a minor bug... it's still nicer to stick to the initialize happening on run so I'd suggest we still wrap the provider setup in a register() method of a provider rather than creating it directly on construct.

That way it matches the style of the rest of the app, and a lot of time we give instructions of how to swap out services we use the following style:

    $app = new Application(....);
    $app->initialize();
    $app['service'] = .......
    $app->run();

**Comment by CarsonF** [comment]
I don't think I'm following. What about "initialize happening on run"? The initProfiler is really just calling a bunch of registers. And that code needs to be ran before initExtensions.
