### ISSUE TITLE
Bolt doesn't work with mb_func_overload set greater than 0

### ISSUE THREAD

**Issue by dwr** [bolt/bolt#3054]
if mb_func_overload is set to 2 ("1" breaks mail which is not seen at the first sight), using utf-8 chars would prevent page from rendering correctly.

e. g. <title>Добро пожаловать!</title> renders to <title>Добро пожалова? etc all tags stuff so page is blank.

Looking into this problem and will make pull request probably.

**Comment by bobdenotter** [comment]
I've never used `mb_func_overload`. If you can fix the issue, a pull request would be most appreciated! :-)

**Comment by bobdenotter** [comment]
This is what i'm seeing now, as i'm googleing what `mb_func_overload` actually does. This thread is the very first result. ;-)

![screenshot 2015-03-12 21 32 33](https://cloud.githubusercontent.com/assets/1833361/6627588/6675ad72-c8ff-11e4-8e0c-42a741743050.png)

**Comment by bobdenotter** [comment]
Looking into this, this seems dangerous: http://php.net/manual/en/mbstring.overload.php. It feels like a hackish solution. 

What exactly went wrong? i'd prefer to actually fix issues in bolt, if you encounter them.

**Comment by dwr** [comment]
Some CMS require it enabled (e. g. we use Bitrix which requires it to be enabled and it's the most popular russian commercial CMS) and it couldn't be overriden via .htaccess mostly. I will make a pull request in the nearest free time I'll have. I think that fix will be short actually :P

**Comment by GawainLynch** [comment]
Any update on this, or should we close this @dwr?

**Comment by dwr** [comment]
I didn't do any job on this atm because I have no time, maybe include that in the installer as the warning?

Russian strings in templates got cut if mb_func_overload > 0.

**Comment by GawainLynch** [comment]
Being busy is something I understand well, @dwr :grin: 

Oh and I am sorry, I clicked the wrong button and didn't mean to close this on you!

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
