### ISSUE TITLE
2.1 rc - add user fails silently

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3056]
**What happened**: Adding a user account (in backend) with some faulty data, 
will simply return to the user list without reporting any error.
**Expected**: return to add user account form with notices.

**Comment by bobdenotter** [comment]
This is what I get after _successfully_ adding a user now. :-/

![screenshot 2015-03-08 09 53 32](https://cloud.githubusercontent.com/assets/1833361/6545172/0742e2f4-c579-11e4-9a62-20d775f3bc27.png)
