### ISSUE TITLE
Bolt 2.1.0 RC2 / PHP5.3 extension installer b0rken

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#3059]
There may be a problem with installing extensions on RC2 running on PHP 3 (my server: 5.3.9).
Hitting the 'Run update check' button returns the message:
Searching for available updates …........................
But nothing happens.
![screen shot 2015-03-08 at 20 36 16](https://cloud.githubusercontent.com/assets/2750653/6547243/054a02de-c5d3-11e4-9d88-22179fbf864a.png)

The 'Search extension' field returns a list of extensions (that's good) but after selecting an extension to install, again nothing happens. 

![screen shot 2015-03-08 at 20 36 33](https://cloud.githubusercontent.com/assets/2750653/6547242/0547aa84-c5d3-11e4-9d2d-11f3d7fd7246.png)

**Comment by GawainLynch** [comment]
OK, two questions to help me go deeper on this one:
1. Do you `debug: false` in `app/config/config.yml`
2. Does anything come up in the Network tab in your browser tools

**Comment by peterboorsma** [comment]
Debug was 'true'. Just tested it again with 'false'. No changes.

See screenshot for network thingie. 
![screen shot 2015-03-08 at 20 52 28](https://cloud.githubusercontent.com/assets/2750653/6547337/201c9548-c5d5-11e4-9e9e-3f1549c09192.png)



Console:
![screen shot 2015-03-08 at 20 53 31](https://cloud.githubusercontent.com/assets/2750653/6547340/38ff5ea6-c5d5-11e4-9f0f-6cc4413434a6.png)

**Comment by GawainLynch** [comment]
@peterboorsma I flushed the cache and it is now working fine… :hamster:
