### ISSUE TITLE
Brown M&Ms and Van Halen both rule!

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3061]
c.f. [Contributing](https://github.com/bolt/bolt/blob/master/contributing.md)

**Comment by GawainLynch** [comment]
I can sense a #1555 coming on!

**Comment by bobdenotter** [comment]
FAIL! you must **NOT** like the brown M&M's. Can't you read. ;-)

**Comment by GawainLynch** [comment]
PASS! I do like… Wait, I hate M&Ms full stop!
