### ISSUE TITLE
New structure for app/

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#3065]
To support ongoing discussion on IRC:

Plan is to clean up the folder structure a bit. I like to have ``app/view/`` the folder visible to the browser and have ``app/src/`` everything in that's just used for the build process of the former folder. @CarsonF likes to have the twig stuff out there. ``translations`` could be moved one up if there are no other resourcs planned. Anything else?

Here a short sugesstion how it could look like (only interesting folder listed here)
```
app/
    view/
        img/
        js/
        fonts/
        css/
    translations/
    twig/
        toolbar/
    src/
        sass/
        grunt/
        lib/
        js/
```

To be checked:
- ``app/src/`` problematic because of leftovers from a former update (src-move)?
- Webserver allow/deny?

**Comment by CarsonF** [comment]
Would templates be better than twig?

**Comment by rarila** [comment]
@CarsonF probably, what do other say?

**Comment by rarila** [comment]
An unnamed person from IRC likes to have ``twig`` renamed to ``view`` and ``view`` named ``assets``

**Comment by CarsonF** [comment]
I like assets. Not sure about view. To me view is so ambiguous I'd rather avoid it all together

**Comment by cooperaj** [comment]
If you're using source maps in your compilation of assets you'll want to ensure the source files are also accessible to the web browser. That said this is moot for me. I use the composer install because I believe  that the best security comes from having nothing available to the server other then assets and index.php.

**Comment by rarila** [comment]
@CarsonF yes, I also like templates more

**Comment by rarila** [comment]
@cooperaj AFAIK we generate sourcemaps with source included. Would that solve your point?

**Comment by cooperaj** [comment]
Yes, though that can make for some pretty large map files. I take this this won't affect the composer installer version?

**Comment by rarila** [comment]
@cooperaj To be honest, I never used that one. As for size, it's two times 113 kb

**Comment by GawainLynch** [comment]
We don't generate the .maps files by default though.

**Comment by rarila** [comment]
@GawainLynch we do

**Comment by cooperaj** [comment]
I'd recommend giving it a shot. If I were to be honest I'd love to see it as the official installation method - it just strikes me as very sane.

**Comment by GawainLynch** [comment]
We compile them, but don't [ship them](https://github.com/bolt/bolt/blob/master/.gitignore#L50)

**Comment by rarila** [comment]
Sorry, that's about 1,5Mb for those maps (I was looking at css maps :-)

**Comment by rarila** [comment]
@GawainLynch Thought that is because they are only needed by devs who would generate them themselves anyway?

**Comment by GawainLynch** [comment]
As to the original RFC question… `s/translations/trans/` just to keep paths shorter, but that's just CDO.

**Comment by GawainLynch** [comment]
> Thought that is because they are only needed by devs who would generate them themselves anyway?

Yes, agreed.

**Comment by rarila** [comment]
@GawainLynch  then we would use ``tmpl`` instead of ``templates`` also? (``i18n``)

**Comment by rarila** [comment]
Thinking about it I would stay with ``translations``. it's already quite a bit shorter than ``resources\translations`` and i doubt it is an performance issue :-)
Either all or none

**Comment by GawainLynch** [comment]
> then we would use ``tmpl`` instead of ``templates``

We're using `template` where?

**Comment by GawainLynch** [comment]
> Thinking about it I would stay with `translations`. it's already quite a bit shorter than `resources\translations` and i doubt it is an performance issue.

Yeah, just a personal preference that I thought I'd throw out there.

**Comment by CarsonF** [comment]
I'd rather not abbreviate them. They are only referenced in a couple places.

**Comment by rarila** [comment]
Time for a intermediate result:

```
app/
    assets/
        img/
        js/
        fonts/
        css/
    translations/
    templates/
        toolbar/
    src/
        sass/
        grunt/
        lib/
        js/
```

**Comment by GawainLynch** [comment]
Ah, to sneak in the `templates`

**Comment by bobdenotter** [comment]
To me this feels like a 3.0 change. I'm not sure we should start shuffling around folders, like we did between 1.6 and 2.0.

**Comment by rarila** [comment]
Uh, where's the agile development :snail:  ;-)

@bobdenotter any objections creating ``app/src/`` and moving the appropriate folders in there now, as I don't think it would have any external effects besides make developing easier?

**Comment by bobdenotter** [comment]
> any objections creating app/src/ and moving the appropriate folders in there now

Sure, go ahead! :-)

**Comment by CarsonF** [comment]
Well same could be said for templates :frowning:

**Comment by xtrasmal** [comment]
yeah rename it to views.. like that's what they are right? 
- Template is the collection of views, images, css etc.
- Twig can be renamed, cause we want to use our own freak-ass templating system. And maybe not.. but should you care what we use?

**Comment by bobdenotter** [comment]
Since #3080 is merged, shall we close this one? I'm pretty sure the issue will pop up again, when we're planning 3.0. :8ball:

**Comment by GawainLynch** [comment]
:fire:

**Comment by rarila** [comment]
@bobdenotter Only a quarter of that issue is implemented and done.
