### ISSUE TITLE
[Regression] Item.link doesn't take into account subdirectory in menus

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3068]
Eagerly installed 2.1 today and I ran into this pretty big one :(

~~See #3008 as it seems to be the exact same issue (but worse as its for a more commonly used path)~~

The title explains it all. Somewhere around [here](https://github.com/bolt/bolt/blob/master/src/TwigExtension.php#L1250) is the culprit code.

Guess it's back to 2.0.6 for now!

\cc @CarsonF

**Comment by CarsonF** [comment]
How have you installed bolt?

**Comment by Pinpickle** [comment]
Through Composer.

I just realised that the culprit links are using menus, not {{ path.root }}

Will do some troubleshooting and then I'll report back

**Comment by CarsonF** [comment]
Cool. The url generator should take into account base paths too.....but maybe I'm wrong?

**Comment by Pinpickle** [comment]
Definitely just menu items using `menu.link`, `paths.root` is working as expected

**Comment by CarsonF** [comment]
tagging in @GawainLynch

**Comment by CarsonF** [comment]
@Pinpickle Is it the homepage?

**Comment by CarsonF** [comment]
Are you using `path` or `link`?

**Comment by GawainLynch** [comment]
I'd tread carefully on that one guys.

**Comment by CarsonF** [comment]
Do you not agree ^ thats the problem?

**Comment by GawainLynch** [comment]
Possibly, but that is regression territory.  Not saying it's correct though.

@Pinpickle do you have a test case we can use?

**Comment by GawainLynch** [comment]
@CarsonF we've gone from 

```php
$item['link'] = Lib::fixPath($this->app['paths']['root'] . $item['path']);
```
to 
```php
$item['link'] = '/' . $path;
```
…and I'll be damned if I can figure out why, but I reworked that to fix a regression so I just want to be able to test @Pinpickle's problem and try and narrow down/test the old problem too.

**Comment by CarsonF** [comment]
I know why. `$this->app['paths']['root']` is the from the url array, not filesystem path array. So that _did_ take into account base path.

**Comment by Pinpickle** [comment]
@CarsonF No, this is on every page

@GawainLynch sure thing.
I had this issue with a site I am working on at the moment, but I just pulled v2.1.0 into my local Bolt copy (which is just a plain install of Bolt). Its symlinked to `localhost/bolt/`

I go to `http://localhost/bolt` and hover over the menu (these are the default menus) item "Second Entry", and I can see where it's pointing to
![image](https://cloud.githubusercontent.com/assets/3238878/6565382/84bcd734-c714-11e4-8d46-972e53cc16b2.png)

Notice how the link in the bottom left is `localhost/entry/1` and not `localhost/bolt/entry/1`

**Comment by GawainLynch** [comment]
@CarsonF :+1: I think you're spot on, good calls!
