### ISSUE TITLE
[Regression] Warning for unsaved content comes up when nothing has been changed

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3077]
In release/2.1

If I go to edit a record, don't change anything, and then try to leave, I get warned that there is unsaved content. If I save the no edits, the message doesn't come up.

Expected behaviour: nothing comes up if I try to leave without changing anything.

It seems like whatever change flag there is in the code, is starting out as true when the page is first loaded.

Or something actually is getting changed on first load, but I get this on config file edits as well.

**Comment by GawainLynch** [comment]
Yep, seen this. I think it is due to the JS creating a hash using the whole form, that includes elements that get updated by Moment.JS… @rarila?

**Comment by rarila** [comment]
After looking at this it seems that the watchChanges stuff has to be rewritten anyway to resolve some problems with it. This particular bug one is - I would guess - something caused by the changes made to how ckeditor fields are handled.

**Comment by bobdenotter** [comment]
Is there a way we can 'backport' this fix to 2.1.x?

**Comment by rarila** [comment]
Yes, just copy the content of both functions back into jquery-watchchanges an replace bolt.ckeditor.update with the old code found there

**Comment by bobdenotter** [comment]
Cool! I will get on that!
