### ISSUE TITLE
"News" for entries which are not viewable are shown on main page

### ISSUE THREAD

**Issue by frantic777** [bolt/bolt#3079]
configuration:
 - in config.yml frontend_permission_checks: true
 - permissions:
   contenttypes:
    hgentries: (new type equal entries without relation to page)
        frontend: [ everyone ]
        view: [ everyone ]
expected:
   - hgentries highlights are not shown in right area of main page for anonymous users
   - hgentries highlights are shown in right area of main page for any logged user
observed:
  - hgentries highlights are shown in right area of main page for anonymous users, links direct to 404
  - hgentries highlights are shown in right area of main page for any logged user

**Comment by bobdenotter** [comment]
By not viewable, do you mean `viewless: true`? 

And how are they shown? Because you're using a `{% setcontent %}` to fetch them?

**Comment by frantic777** [comment]
Nope, they have frontend: [ everyone] permission and not available for those who aren't logged in.

**Comment by bobdenotter** [comment]
Ok, that was half the answers to my questions. ;-)

> And how are they shown? Because you're using a {% setcontent %} to fetch them?

**Comment by frantic777** [comment]
Sorry :-) that's because I don't know. I use standard theme and these links are shown in the right area of main page. You can see that on blog.healthygeneration.ru, look at hgentries.

**Comment by bobdenotter** [comment]
That's not really how that works. the `frontend: [ everyone]` is not meant for that. If you really want you news to be visible only to logged in users (why?!), you should use the Members extension, from extensions.bolt.cm.

**Comment by frantic777** [comment]
Thanks for clarifying that! The idea is to have 2 types of entries: for everybody and for members only.

**Comment by bobdenotter** [comment]
Closing this one, then. You should look into the "members" extension, or the "passwordprotect" extension  on extensions.bolt.cm.
