### ISSUE TITLE
cannot launch dashboard after 2.1 update !

### ISSUE THREAD

**Issue by joanlouis** [bolt/bolt#3084]
after update of 2.1 when i launch the dashboard i have :
Cannot use object of type stdClass as array
/home/web/vanlooveren.fr/web/src/Controllers/Async.php
            }
        } else {
            $app['logger.system']->info('Using cached data', array('event' => 'news'));
        }
 
        // Combine the body. One 'alert' and one 'info' max. Regular info-items can be disabled, but Alerts can't.
        $body = "";
        if (!empty($news['alert'])) {
            $body .= $app['render']->render('components/panel-news.twig', array('news' => $news['alert']));
        }
Silex Application
Charset	UTF-8
Locale	fr
Route Class	Silex\Route
Dispatcher Class	Symfony\Component\EventDispatcher\EventDispatcher
Application Class	Bolt\Application
Silex Application (Request)
URI	http://ww2.vanlooveren.fr/async/dashboardnews
Request URI	/async/dashboardnews
Path Info	/async/dashboardnews
Query String	<none>
HTTP Method	GET
Script Name	/index.php
Base Path	
Base URL	
Scheme	http
Port	80
Host	ww2.vanlooveren.fr
Server/Request Data
REDIRECT_STATUS	200
HTTP_HOST	ww2.vanlooveren.fr
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_CONNECTION	keep-alive
HTTP_COOKIE	bolt_session=er4jspdh14j21mi01jde4pdqu2; bolt_authtoken=d3dfa42ee2f51872b08c6478aedb4b3b
HTTP_USER_AGENT	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12
HTTP_ACCEPT_LANGUAGE	fr-fr
HTTP_REFERER	http://ww2.vanlooveren.fr/bolt/dbupdate_result?messages=%5B%22Created+table+%60bolt_log_system%60.%22%2C%22Created+table+%60bolt_log_change%60.%22%5D
HTTP_ACCEPT_ENCODING	gzip, deflate
PATH	/usr/local/bin:/usr/bin:/bin
SERVER_SIGNATURE	<address>Apache/2.2.22 (Debian) Server at ww2.vanlooveren.fr Port 80</address>
SERVER_SOFTWARE	Apache/2.2.22 (Debian)
SERVER_NAME	ww2.vanlooveren.fr
SERVER_ADDR	62.210.37.43
SERVER_PORT	80
REMOTE_ADDR	78.219.146.142
DOCUMENT_ROOT	/home/web/vanlooveren.fr/web
SERVER_ADMIN	[no address given]
SCRIPT_FILENAME	/home/web/vanlooveren.fr/web/index.php
REMOTE_PORT	51097
REDIRECT_URL	/bolt/
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.1
REQUEST_METHOD	GET
QUERY_STRING	
REQUEST_URI	/bolt/
SCRIPT_NAME	/index.php
PHP_SELF	/index.php
REQUEST_TIME_FLOAT	1426018889.353
REQUEST_TIME	1426018889
GET Data
empty
POST Data
empty
Files
empty
Cookies
bolt_session	er4jspdh14j21mi01jde4pdqu2
bolt_authtoken	d3dfa42ee2f51872b08c6478aedb4b3b
Session
_sf2_attributes	Array ( [retreat] => [user] => Array ( [id] => 1 [username] => joan [password] => **dontchange** [email] => joan@itaca.fr [lastseen] => 2015-03-10 16:56:48 [lastip] => 78.219.146.142 [displayname] => Joan Louis [stack] => ["2015-03\/flat_rosso_scont.jpg","2015-02\/640cb_00.jpg","2015-02\/640cb_toestel.jpg"] [enabled] => 1 [shadowpassword] => [shadowtoken] => [shadowvalidity] => [failedlogins] => 0 [throttleduntil] => [roles] => Array ( [0] => root [1] => everyone ) [sessionkey] => 9f3fa6019eb3cd98c9de0653b55ad0b0 ) )
_sf2_flashes	Array ( )
_sf2_meta	Array ( [u] => 1426018889 [c] => 1426018110 [l] => 0 )
Environment Variables
empty
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
1. Whoops\Handler\CallbackHandler

**Comment by bobdenotter** [comment]
Try emptying the cache. Either by going to `/bolt/clearcache/` or else by manually clearing the folder `/app/cache/` on the server.

**Comment by joanlouis** [comment]
done. other pages of the backend work well

**Comment by joanlouis** [comment]
ok it need to be done two times sorry

**Comment by bobdenotter** [comment]
Allright! Glad it works now! :-)
