### ISSUE TITLE
[RFC] Let's remove the "frontend" permission. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3087]
This one: https://github.com/bolt/bolt/blob/master/app/config/permissions.yml.dist#L149

```
# - frontend: allows front-end access to records (note that this requires the
#             'frontend_permission_checks' global configuration setting, for
#             backwards-compatibility reasons as well as performance)
```

Why? Because:

- It's confusing. See #3079
- It's broken (or at least counter-intuitive).
- Imho it clashes with points 4 and 5 of our manifesto.

**Comment by GawainLynch** [comment]
:+1:

**Comment by tobias2k** [comment]
Kill it with fire. It never made sense, really.

On Wed, Mar 11, 2015 at 12:43:57AM -0700, Bob den Otter wrote:
> Why? Because:
> 
> - It's confusing. See #3079
> - It's broken (or at least counter-intuitive).
> - Imho it clashes with points 4 and 5 of our manifesto.  
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/3087

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GawainLynch** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: `frontend:` :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by rarila** [comment]
:fire_engine: :fire_engine: :fire_engine:

**Comment by rixbeck** [comment]
Saying good bye in tears... its memory will live with us forever... 
![sad](http://i.giphy.com/hryZ5xPHpPAQ.gif)
