### ISSUE TITLE
Can't install extensions after upgrading to 2.1.0

### ISSUE THREAD

**Issue by frantic777** [bolt/bolt#3088]
Log error:
Fatal error:  Call to a member function getPackage() on a non-object in /etc/bolt/src/Composer/Factory.php on line 198" while reading response header from upstream, client: 212.5.125.194, server: blog.healthygeneration.ru, request: "GET /bolt/extend/install?package=dsduit%2Fparallelism-html5up&version=dev-master HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "blog.healthygeneration.ru", referrer: "https://blog.healthygeneration.ru/bolt/extend/"

**Comment by GawainLynch** [comment]
A fix is pending in #3086

**Comment by frantic777** [comment]
Thank you, sorry for dup issue

**Comment by GawainLynch** [comment]
Oh, that is not a problem. Thank you for reporting the issue :+1:
