### ISSUE TITLE
\SplFileInfo requires PHP 5.3.6

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3092]
.. and we support PHP 5.3.3. 

See:  https://www.filepicker.io/api/file/1VxYx8QcRmCy91h5fvFe

What do?

**Comment by cooperaj** [comment]
http://php.net/eol.php

:grin:

**Comment by bobdenotter** [comment]
@cooperaj I'm feeling a bit conflicted now: Part of me wants to slap you for being a smartass, and part of me wants to thank you for that handy link, i can use to rub in other people's faces. ;-)

**Comment by GawainLynch** [comment]
Sure, but: https://access.redhat.com/support/policy/updates/errata

**Comment by cooperaj** [comment]
Intending to support 5.3.3 until 2020? Thats some serious commitment. :stuck_out_tongue:

**Comment by CarsonF** [comment]
I'll fix this. It's not `\SplFileInfo` just `getExtension` method

**Comment by bobdenotter** [comment]
> Intending to support 5.3.3 until 2020?

That'd just be cray-cray. We've been talking about making 2.1 an LTS version, so 2.1.x would run on PHP 5.3.3, and going with PHP 5.3.9 (as req by Symfony 2.7) for 2.2 onwards. Nothing decided, yet.

**Comment by GawainLynch** [comment]
> Intending to support 5.3.3 until 2020? 

Goodness no… Problem being and I am on something of an island here is that RHEL/CentOS 6.x is on **lots** of servers and we immediately cut off a lot of people. 

For those of us with control of the server [Remi Collet](http://blog.famillecollet.com/pages/Config-en) runs "the" repository for supported PHP versions… but for those on shared servers :-1:

**Comment by cooperaj** [comment]
> and going with PHP 5.3.9

Thats still on the old side... and still EOL . It'd be lovely to see a 5.4 if only for traits and short array syntax. I guess that could be a 3.0 thing.

**Comment by CarsonF** [comment]
> Problem being — and I am on something of an island here — is that RHEL/CentOS 6.x is on lots of servers and we immediately cut off a lot of people.

Yeah that's our problem too. 

> Thats still on the old side... and still EOL . It'd be lovely to see a 5.4 if only for traits and short array syntax. I guess that could be a 3.0 thing.

I think the current plan is to follow Symfony, I know they are bumping minimum version required later this year.

**Comment by bobdenotter** [comment]
> I think the current plan is to follow Symfony, I know they are bumping minimum version required later this year.

If it's up to me, that sounds like a good plan.
