### ISSUE TITLE
Using menus is not helped by having a lot of the manipulation code marked private

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#3097]
I'm implementing a TwigExtension to render breadcrumbs based on menu's. In order to get the same functionality as the normal {{ menu() }} call I've had to copy the contents of menu, menuBuilder and menuHelper. Those last two are private. 

All the majority of this code does is turn a menu.yml into a set of proper urls. Would it be too much to ask to have this abstracted out so that a menu can be accessed from within code that contains the proper urls.

**Comment by CarsonF** [comment]
Please! This should definitely be in a separate class.

**Comment by cooperaj** [comment]
Would you be averse to a MenuServiceProvider?

**Comment by CarsonF** [comment]
No, as long as it created a MenuBuilder class.

**Comment by cooperaj** [comment]
No worries. I'll get working on that later.

**Comment by CarsonF** [comment]
Sweet!

**Comment by cooperaj** [comment]
Since I need this now I've implemented it as

https://github.com/cooperaj/bolt-menucompat

But. Now I'm going to get this in as a PR assuming you're happy with it.

**Comment by cooperaj** [comment]
This is part of #3103

**Comment by GawainLynch** [comment]
@cooperaj does #3103 close this?

**Comment by cooperaj** [comment]
Yes I believe so.

**Comment by GawainLynch** [comment]
Legendary, thanks again!
