### ISSUE TITLE
[Small UI Issue] Save and create new record flash is wrong

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3109]
If I go to Save>Save and create new record, I get this message

![image](https://cloud.githubusercontent.com/assets/3238878/6614644/422817a0-c901-11e4-8e1e-4752a0b56965.png)

It says "this page" when "this page" is in fact a new page that has not been saved. I think it should say "page/slug" or if it doesn't have a slug, "page/id".

**Comment by GawainLynch** [comment]
Well, I might debate that. 

Initial point is that the OED defines 'save' (the verb) as "Keep and store up (something, especially money) for future use", and I think that is valid here in both the case of new and existing records.

Second counter point would be that there will always be a slug — if not properly defined/attributed it will default to a random string — so the record ID would never be used (and is not editor friendly regardless). That in mind, the slug can either end up something like `my-new-kitten-page` or `kshaakjh21`. While I tend to stay away from UX, I do happen to see either of those slugs as not addressing UX of all 3 groups, mostly it just appeals to backenders… Ironic misuse noted :wink:

**Comment by SahAssar** [comment]
Just looking through old issues here, would "The changes to the Page have been saved" work? That way we don't need to mix in slugs/whathaveyou.

**Comment by Pinpickle** [comment]
@SahAssar that is probably the best way to go about it, as I wouldn't see this as an issue worth putting a lot of effort into fixing!

@GawainLynch it wasn't "save" that I was opposed to, it was "this page".

**Comment by GawainLynch** [comment]
@Pinpickle: I am somewhat lost on what is wrong… `this` is the determiner/pronoun, `Page` is a *proper noun*, and `save` (which you've ruled out) is a verb. Changing the determiner I have no problem with, but lost on why…

Is this about the presence of the FlashBag itself?

**Comment by SahAssar** [comment]
@GawainLynch It's the fact that when you click "save and create new record" it still says "this Page", but then you are on a new Page to which the message is not referring and which has not been saved. The message is simply wrong in that scenario.
