### ISSUE TITLE
We're still not free of &nbsp;

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3111]
#2745 fixed most of these problems, relating to #2660 but there's still at least one (regularly occuring) case that's hit me up quite a few times.

Between inline tags and text nodes (and just between inline tags, I think), CKEditor will put a `&nbsp;`. To test, just open it up, type (or copy + paste):

> Testing *testing* testing

And look at the source

    <p>Testing&nbsp;<em>testing</em>&nbsp;testing</p>

:cry:

**Comment by GawainLynch** [comment]
Interestingly, I am getting a different — undesirable — result:
```html
<p>Testing<em>testing</em>testing</p>
```

A total **removal** of spaces.

**Comment by Pinpickle** [comment]
@GawainLynch I just started to get that as well! I'm not sure why it flopped between the two, but now I can't get it to do the `&nbsp;` trick on paste.

Definitely still doing it through manual entry, though.
