### ISSUE TITLE
Unexpected behavior deleting related items

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#3113]
If you interlink items with the 'relatations' functionality, Bolt shows a nice list of related items in the editor (see screenshot).
There's an edit button for each relation. The 'delete' option is somewhat vague. It deletes the related item entirely. I expected it (stupid me) to break the relation, not delete the relation.

There should a 'break up relationship' (haha) option too imho.

![screen shot 2015-03-12 at 14 23 34](https://cloud.githubusercontent.com/assets/2750653/6618468/6d2be60e-c8c3-11e4-96fc-9bb939343493.png)

**Comment by bobdenotter** [comment]
Everybody knows Vak Paars is best Vak.
