### ISSUE TITLE
Issue when installing a theme..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3114]
This happens both _before_ and _after_ #3107 was applied to local checkout: 

 - select a theme from the list (like 'clean blog')
 - install any version
 - See error (as in screenshot)
 - refresh page, see installed theme. 

![screen shot 2015-03-12 at 14 45 44](https://cloud.githubusercontent.com/assets/1833361/6619060/e8081448-c8c7-11e4-9383-cad2eb3116cc.png)

**Comment by bobdenotter** [comment]
And sometimes, this one popped up as well:

![screen shot 2015-03-12 at 14 47 05](https://cloud.githubusercontent.com/assets/1833361/6619070/0d661136-c8c8-11e4-9cbe-6306235fc383.png)

**Comment by GawainLynch** [comment]
Error not thrown in a corner case, and `app/view/js/bolt.min.js` needed to be rebuilt.

**Comment by bobdenotter** [comment]
Closink!
