### ISSUE TITLE
[RFC] Ways to define and control resource contenttypes

### ISSUE THREAD

**Issue by Intendit** [bolt/bolt#3120]
The way that I see it the viewless attribute does not really do much in the way of enabling resource contenttypes, it simply restricts frontend views without helping editors on the backend.

To preface the following I will say that the clients (editors) that I work with do not have the experience to edit a yml file such as the config.yml or a theme.yml.

I don't think anyone thinks that the current system for resource contenttypes is good though it might be "good enough" for now.

The way that I see it we have three options (that are obvious to me, please give me better ones):
 1. Add a "limit amount" option to contenttypes and if set to 1 the backend menu link for the contenttype  will lead to editing the only record in question.
  * Pros/cons:
    * Cons:
      * Seems like a waste of a DB table to just use one row (only half sarcastic...)
      * only really solves solves the issue fully for single-record resource-contenttypes such as a global footer/header while doing nothing for multi-record resource-contenttypes
      * does not solve the issue fully since it does not make it readily apparent from the UI that a change affects the whole site nor does it make it more apparent within the UI that the contenttype has more "weight", i.e: it's still listed with the rest of the "normal contenttypes" (Unless it's listed apart from the rest, see below).
    * Pros:
      * Somewhat easy (I think, please correct me if i'm wrong)
      * Solves a majority of small-site use cases
      * Better than the current situation where a resource record used globally might be replaced or edited without that being made clear to the editor.
 2. Same as above but show it under a special section in the menu (something that reminds people that the change is regarding the whole site like "global" or "sitewide", perhaps being merged with the current "settings" as a main menu section but with a sub menu leading to the resource records) if defined as a resource (or other attribute) in the contenttypes.yml
    * Pros/cons: Same as above except
      * Cons:
        * Complicates the backend for what might be an unusual situation (it isn't for me, but perhaps for the rest of users/designers/devs?)
      * Pros:
        * Works for multi-record resource contenttypes (In case I, as an editor, have multiple footers but I will still see them in the backend as being labeled as a resource-contenttype)
        * Makes it clearer than above that the contenttype is a resource and not a "simple record" and that editing it is distinct from editing a single record
 3. Making a gui (or using an existing one) for editing a theme.yml file or some other yml file :
  * Pros/cons:
    * Cons:
      * Almost everything... Including usability, probably because of user error...
    * Pros:
      * I guess in the future i could get/set values via nut, maybe?
      * It would be nice to have a standardized gui for yml files going forward perhaps...

**Comment by bobdenotter** [comment]
On a few of the larger Bolt sites we're working on, the amount of contenttypes starts to grow. A bunch of them generally, either: 

 - Have only 1 or a small handful of records at most
 - Rarely require immediate access from the sidebar in one click (DB-generated stuff, imported content)

I like the idea of having one item in there that groups these together. When hovering over that item, instead of seeing the "5 latest records", you'll see these contenttypes, and can click through, to their overviews. 
Perhaps we should name this one "Other content" and it should be listed at the bottom of the other contenttypes in the sidebar.

**Comment by GawainLynch** [comment]
Forgive me if I am totally missing the point here, but on my sites I add something like this to `app/config/permissions.yml` that limits the menus, the `view: []` part being the clincher.

```yaml
contenttypes:
    resources:
        edit: [ developer ]
        create: [ developer ]
        publish: [ developer ]
        depublish: [ developer ]
        delete: [ developer ]
        view: [ developer ]
```
Logic being if they don't know enough to edit site configuration, they have no place touching any of the (multiple) resource Contenttypes I define.

**Comment by Intendit** [comment]
My goal is to more clearly on the backend indicate what is a resource contenttype, but still allow editing of them. Example:
I have a header and a footer contenttype, both of them only contain one record, and they are used globally. The customer should be able to update the info contained in them, but I want to indicate to them that this is a special contenttype and is treated differently than the rest.

**Comment by bobdenotter** [comment]
Here's an example of a site i'm working on: 

![screen shot 2015-03-13 at 12 58 59](https://cloud.githubusercontent.com/assets/1833361/6637956/cc3c38d4-c980-11e4-944f-e15ac7662c42.png)

I'd love it if `Tekstroutes`, `E-Bike Merken`, `Routebeheerders`, `Routeplaatsen`, `Routethema's`, `Knooppunten` and `Pois` would all be grouped under a single "Other content" option. They all contain one or two records, or are generated from an external source.

**Comment by GawainLynch** [comment]
Lack… of… alphabetical… order… CDO… twitching…

**Comment by GawainLynch** [comment]
A menu "Resources ->" that grouped `viewless: true` Contenttypes, rather similar to the second point and in line with your idea @bobdenotter would be my vote.
```
Resources
    Site Elements
    404
    Easter Eggs
```

**Comment by bobdenotter** [comment]
Yes, that was exactly what i was going for. However, I'd slightly prefer a label like "Other content" over "Resources".

**Comment by bobdenotter** [comment]
> A menu "Resources ->" that grouped viewless: true Contenttypes

Oh, wait. It should be a different setting than `viewless: true`, though. For example, the 404 is viewable on most websites. ;-)
And in my earlier example: "Tekstroutes" is old, imported content. It _will_ be viewable on the new site, but it's unlikely that it'll ever be edited.

**Comment by Intendit** [comment]
Maybe a group option in contenttypes would solve this in the most general and customizable way?

So @bobdenotter would set `group: "Other content"` on his types and somebody else might have `group: Resource` 

That way it allows for categorization much like groups does under fields and follows the same logic.

**Comment by GawainLynch** [comment]
This is how I 404 on PopAnth http://popanth.com/gawain-was-here/

In `app/config.yml`:
```yaml
notfound: resource/not-found
```

In `app/contenttypes.yml`:
```
resources:
    name: Resources
    singular_name: Resource
    fields:
        title:
            type: text
            class: large
            required: true
        slug:
            type: slug
            uses: title
        html:
            type: textarea
            height: 150px
        template:
            type: templateselect
            filter: '*.twig'
    show_on_dashboard: false
    default_status: published
    searchable: false
    viewless: true
```

**Comment by rarila** [comment]
@bobdenotter Ok, it is late, I'm listening to AC/DC (the best Australian export of since @GawainLynch) and I only was flying over that issue… but could it be that you are looking for contenttypes ``show_in_menu: false`` option?

**Comment by bobdenotter** [comment]
@rarila: Hmm, almost, but not quite. If it would mean that `show_in_menu: false` means it will show up in "Other content", that's confusing. Also, sometimes you don't want to show something at all (like a CT with an old import, perhaps).

I'm liking @Intendit's suggestion for `group:` analogous to how we do it in the fields.

**Comment by bobdenotter** [comment]
Well, this is awkward. We already have this functionality baked right in. Add `show_in_menu: false` to your contenttype definition, and it'll be grouped in a 'other contenttypes' sub.
