### ISSUE TITLE
[RFC] Menu editor and/or category editor in core

### ISSUE THREAD

**Issue by miguelavaqrod** [bolt/bolt#3141]
Hi,

Just a topic to discuss about...
First of all, I have to say that I know, and love, bolt's way of doing things... having .yml files is great.

However, regarding menu editing, for me it's a thing that almost all the time is needed so I am asking why did you decide not to incorporate in the main code.
For me, the first thing I always do after installing Bolt is installing MenuEditor extension.

In the other hand, categories I think suffer the same lack (and now we do not have any extension to handle them).

What do you think about?

Thanks in advance.

**Comment by Intendit** [comment]
+1 menus are often touched by people who do not understand YAML.

**Comment by miguelavaqrod** [comment]
I do apologize.. but I need to insist...

Giving my post a turnaround, I think we can live just using the MenuEditor extension (also taking into account that only one user agreed with me).

However, it is getting more and more difficult for me to justify the use of categories by means of a yml file.
Almost every web page I develop, needs to categorize entries using categories, and those categories are totally dynamic (at least at the beginning), so, at the end, I just create a new content type named categories and make use of it with a bit of tweaking... and loosing some bolt features yml categories provide (do are not listed when creating menus, for example).

Again.. what do you think about?

And yes!.. I know it and I will... "you can always create an extension for that", but my questions is.. would it be great to include it in core?

Thanks in advance,

Miguel

**Comment by GawainLynch** [comment]
Interesting I gave my wife, an anthropologist with zero technical training, access to the backend of a site that I was building a couple of days ago… a few minutes later she asks me to refresh the front page.…

I hadn't touched the installed `menu.yml`, but she had built a fresh and correct menu hierarchy for me having never seen a YAML file in her life before.

That aside, one really big problem is that YAML doesn't lend itself to machine manipulation, it is make to be human read/write but machine read.

**Comment by Intendit** [comment]
A lot of this seems to be related to the discussion in #954 that was had a year ago. I think that minimizing how much editors and content authors need to be in YML's is a good idea, but I love YML's for designers and developers.

**Comment by miguelavaqrod** [comment]
Hi!

GawainLynch.. I agree that we can do lot of things and easily just using yml files. No discuss about that.
I just ask what do you think and why not to include those "standard" features.. as any other CMS has.

Let's go to the edge... Imagine somebody make a fork and implement a menu editor and categories/taxonomies editor inside the core... What version will be more downloaded?

Again... please.. consider this just as my own doubt, not as a complain or similar.. I repeat one more time I am enchanted with Bolt. 

Thanks.

**Comment by GawainLynch** [comment]
Oh please do not see my response as attempting to argue your discussion down and say "no". Rather that I am trying to add another point of view to it.

**Comment by miguelavaqrod** [comment]
No! Do not worry.. I know that... ;-)

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
