### ISSUE TITLE
Fatal Errors on Admin Extensions page

### ISSUE THREAD

**Issue by ngroot** [bolt/bolt#3146]
### Description
When going to the Admin Extension page the overview and the installation of a new package crashes with a fatal error.

It looks like the composer.json file in the extensions directory is corrupt somehow. I have a composer.json file with line:

`require: []`

The array notation is breaking the code. When changing it to `{}` everything works.

#### Reproduction
- Have a clean install of bolt with no extensions
- Go to /bolt/extend/
- On the "Your currently Installed Extensions" a PHP Error occurs

- Try installing a new extension
- On the installation a PHP Error occurs.

**Comment by ngroot** [comment]
With some more investigation:

On 2.1.1 when removing the composer.json from the extensions directory the new composer.json generates correct.

**Comment by bobdenotter** [comment]
Thanks! This has been fixed in Bolt 2.1.3!
