### ISSUE TITLE
Method of putting taxonomies in a select field

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3149]
Say you want to select a category to display an overview for on a page. It would be great if somehow, the `values` field for a `select` field when defining the contenttypes would allow to pick from the defined list of contenttypes. I don't know exactly how this would work, but maybe setting `values` to `taxonomy/{taxonomyname}` would be a way to do it?

Of course that wouldn't really work for tags. And in the meantime, we can just enter the taxonomy titles manually.

**Comment by SahAssar** [comment]
I'm going to close this as part of a cleanup.

While I'd like this functionality, in my experience if a client has permissions/knowledge to edit the taxonomy.yml file they also have the same for contenttypes.yml.

If anyone feels this is critical or necessary for their application or site please reopen!
