### ISSUE TITLE
Quirk with Extensions.php

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3158]
See screenshot:

![screen shot 2015-03-17 at 18 55 48](https://cloud.githubusercontent.com/assets/1833361/6693999/6a197fae-ccd7-11e4-8860-4ed213e963e2.png)

**Comment by GawainLynch** [comment]
Bolt version and installed extensions?

**Comment by bobdenotter** [comment]
Master, while working on an extension. Trying to narrow it down. 

Only shows up with `debug_error_level: -1`, and it doesn't seem to have any side-effects at first glance.

**Comment by GawainLynch** [comment]
> …while working on an extension.

Phew, so it's not one of mine! :grinning:

**Comment by GawainLynch** [comment]
> Phew, so it's not one of mine! :grinning:

…no, just cause by me.
