### ISSUE TITLE
Thumbnail change file format

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3166]
It would be pretty swell if we could, say, upload a lossless .png but generate .jpg thumbnails so there's minimum quality loss and the exporting process is easier.

Potentially add a fourth `format` argument to the thumbnail function?

**Comment by SahAssar** [comment]
I'm just spitballing here, but most images where you would want to use a PNG would be the ones where a PNG does best, otherwise you would want a JPEG with the quality turned way up, since PNG and JPEG are good for different kinds of images, right?

**Comment by SahAssar** [comment]
Merging this into the https://discuss.bolt.cm/d/140-new-way-of-thumbnails-generation-continuation-of-3703 thread as it seems like the most appropriate place for it.
