### ISSUE TITLE
v2.1.2 composer-install broken

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#3167]
Update/reinstall of v2.1.2 errors with:
```
Interface 'Symfony\Component\Security\Csrf\CsrfTokenManagerInterface' not found
```

The following command did fix the issue:
```
composer require symfony/security-csrf
```

:beers: to slick0

**Comment by jkazimir** [comment]
:beers: to you, too!

Yea, bolt probably shouldn't be using a component that's not explicitly required by the composer.json. Otherwise, we risk losing it if/when a dependency of bolt's changes it's dependency on it.

**Comment by GawainLynch** [comment]
This is a bug in Symfony 2.6.5 which was released yesterday.  As soon as I noticed it I locked `release/2.1` d27d18dcfc9987837227f7b58f7df6b433b89f1f and `master` 818b25fefc71850af21435a15cc3335fd11bff92 to 2.6.4 (with an IRC ACK from @bobdenotter) 

But yeah, there is a lag with [`packagist.org`](packagist.org) picking up our changes, so if it is still happening this morning we might need to get @bobdenotter to press the manual update button again.

**Comment by jkazimir** [comment]
@GawainLynch While at first glance, it looks like a Symfony bug (a Symfony update causes it), I'm pretty sure it isn't.

What changed in 2.6.5 was in a dependency in one of the sub-tree splits bolt depend on.  Basically, bolt was using something that it didn't directly depend on, according to composer.json.  When that sub-dependency was no more, the Symfony components we used no longer needed the csrf lib, and bolt wasn't asking for it.  Adding symfony/security-csrf or symfony/security to bolts composer.json fixes this without having to lose out on upstream fixes from Symfony.

**Comment by GawainLynch** [comment]
Love your work, @jkazimir

**Comment by jkazimir** [comment]
:beers:

**Comment by GawainLynch** [comment]
Question is, which option?
```bash
$ composer require symfony/security
  - Installing symfony/security (v2.6.5)

$ du -sh vendor/symfony/security/
2.1M	 vendor/symfony/security/
```

```
$ composer require symfony/security-csrf
  - Installing symfony/security-core (v2.6.5)
  - Installing symfony/security-csrf (v2.6.5)

$ du -sh vendor/symfony/security*
776K    vendor/symfony/security-core
80K     vendor/symfony/security-csrf
```

**Comment by bobdenotter** [comment]
Which version was the one that comes "bundled" with our 2.6.4 config?
