### ISSUE TITLE
[2.1.x] Error on extends screen.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3170]
See screenshots: 

![screen shot 2015-03-18 at 10 10 36](https://cloud.githubusercontent.com/assets/1833361/6705654/5e30f46c-cd57-11e4-923f-3a49cf0ba209.png)

Details of the `500`:

![screen shot 2015-03-18 at 10 10 39](https://cloud.githubusercontent.com/assets/1833361/6705655/6946bc4c-cd57-11e4-8ab9-2853591f2472.png)

**Comment by bobdenotter** [comment]
Note: tested on 4 sites. 3 are OK, one has this problem.

**Comment by GawainLynch** [comment]
Something looks fishy with the `vendor/composer/composer` part of the install.

**Comment by bobdenotter** [comment]
If i remove `extensions/composer.json`, all is well.. This is what it looked like:

```
bob@jannie:/2kdata/extra/offertes/extensions$ cat composer.json
{
    "require": [],
    "repositories": {
        "bolt": {
            "type": "composer",
            "url": "https://extensions.bolt.cm/satis/"
        },
        "packagist": false
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "config": {
        "discard-changes": true,
        "preferred-install": "dist"
    },
    "provide": {
        "bolt/bolt": "2.1.3"
    },
    "scripts": {
        "post-package-install": "Bolt\\Composer\\ExtensionInstaller::handle",
        "post-package-update": "Bolt\\Composer\\ExtensionInstaller::handle"
    },
    "extra": {
        "bolt-web-path": ".././"
    },
    "autoload": {
        "psr-4": {
            "Bolt\\Composer\\": ""
        }
    }
}
```

**Comment by rossriley** [comment]
`"require": [],`
is the problem.

**Comment by GawainLynch** [comment]
Yes, but where that is coming from is the question.

@bobdenotter what Bolt version was that on *before* you updated?

**Comment by bobdenotter** [comment]
@GawainLynch it was 2.1.1 before, but it's been updated a zillion times in the last few months.
