### ISSUE TITLE
Cannot write to log from nut command

### ISSUE THREAD

**Issue by magabriel** [bolt/bolt#3172]
Hi, Bolt team!! Latest Bolt 2.1.3 here.

When I try to write to the system log (with the new Monolog implementation) from a nut command, nothing gets writen. Debugging  'Logger\Handler\SystemHandler::write()'  I can see that the following code is eating an exception with message **"Accessed request service outside of request scope. Try moving that call to a before handler or controller."**

```php
        try {
            $this->app['db']->insert(
                $this->tablename,
                array(
                    'level'      => $record['level'],
                    'date'       => $record['datetime']->format('Y-m-d H:i:s'),
                    'message'    => $record['message'],
                    'ownerid'    => isset($user['id']) ? $user['id'] : '',
                    'requesturi' => $this->app['request']->getRequestUri(),
                    'route'      => $this->app['request']->get('_route'),
                    'ip'         => $this->app['request']->getClientIp(),
                    'context'    => isset($record['context']['event']) ? $record['context']['event'] : '',
                    'source'     => $source
                )
            );
        } catch (\Exception $e) {
            // Nothing.
        }
```
Of course I can't move the call to a before handler or controller because is being called from a nut command. 

I assume the problem is the three calls to `$this->app['request']`, that do not make sense from a CLI call.

**Comment by GawainLynch** [comment]
Sorry this took so long to get to @magabriel 

A fix is inbound.
