### ISSUE TITLE
Error when viewing entry

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3176]
Everytime some displays an entry on the web, Bolt wil list an error like this:

624 	Error 	storage 	contentlink 	/bericht/noardske-balk-in-de-balk-in-balk 	Requested specific query 'bericht', not found.

The entry is visible and readable like I want it to be. What does the error say?

Something else: I also get these:

608 	Info 	authentication 	useredit 	/bolt/users/edit/8 	Configuration error: systemlog is not granted to any roles. 	
607 	Info 	authentication 	useredit 	/bolt/users/edit/8 	Configuration error: changelog is not granted to any roles. 	

I have installed 2.1.1 (pl1).

UPDATE:

Ah... in the newest permissions.yml file there are two new lines. I added...

changelog: [ admin, developer, chief-editor ]
systemlog: [ admin, developer ]

...to my own file. I think I will no longer get the authentication error. Do I have to check and edit such files manually everytime there is a new Bolt release?

**Comment by bobdenotter** [comment]
> Do I have to check and edit such files manually everytime there is a new Bolt release?

We strive to keep everything as 'backwards compatible" as possible. That said, it never hurts to take a look, to see what new things have been added :-)
