### ISSUE TITLE
[Bug][RFC] File operations doesn't work under Chrome 41.0.2272.89 (64-bit) 

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#3178]
*File Management - Uploaded files - Create folder* : Uncaught TypeError: Cannot read property 'length' of null bolt.min.js:5 
Backbone.Model.extend.create VM106:1 (anonymous function) bolt.min.js:6 (anonymous function) lib.min.js:3 m.event.dispatchlib.min.js:3 r.handle

*Edit some contenttype's image - Select from server - (click a folder)* : Uncaught TypeError: Cannot read property 'update' of undefined
1:3 Uncaught TypeError: undefined is not a function

---
OS Ubuntu 14.04
Firefox, Chromium Browser doesn't affected

**Comment by rixbeck** [comment]
Oh, forgot... It is on v2.1.3 while 2.0.6 has no this symptom.

**Comment by rarila** [comment]
Not me again! ;-)

**Comment by bobdenotter** [comment]
Can not reproduce yet. Chrome `Version 41.0.2272.101 (64-bit)` on OSX. 

![screen shot 2015-03-20 at 17 38 15](https://cloud.githubusercontent.com/assets/1833361/6756113/fd7dce4c-cf27-11e4-81fe-ba343370596e.png)

**Comment by Intendit** [comment]
Could not reproduce under Chrome 41.0.2272.89 on Windows 10.

**Comment by rixbeck** [comment]
Jumped into 2.1.4pl1 and can't reproduce, so closing. Will open again if appears.
