### ISSUE TITLE
[RFC] Test Weekend Discussion Thread

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3181]
This is an issue to track and coordinate the work we'll coordinate over 21st & 22nd March.  We should kick off sometime after 07:00 UTC on Saturday.

### Goal
We start by defining all of the base UI functionality that **should** work and tackle that.

Then go back over the issue tracker and see what stuff turned up that we can/should write tests to catch in the future.

We aim to:
- Expand the PHPUnit unit tests to bring them closer to complete coverage of the codebase
- Expand the Codeception acceptance tests to cover more of the UI functionality

We have put a lot of effort in during the last couple of releases to get our tests & their infrastructure improved. We now run our Travis Continuous Integration tests on both git & Composer installs, on Sqlite, MySQL & PostgreSQL for each… See Bolt's Travis job [5150](https://travis-ci.org/bolt/bolt/jobs/54924635) and you'll see [that's what dreams are made of](http://www.azlyrics.com/lyrics/vanhalen/dreams.html).

### Can I help?
All interested people are invited to attend. 

If you're a frontend only person, new to PHP, or just new to Bolt code, you will be able to help out **lots** by:
- Pointing out missing activities in the UI that we're not testing
- Searching the issue tracker for problems that we might need to write tests for

In both cases, just add what you find in this discussion thread.

For those who are brave enough to join in on writing the tests…

In an effort to simply reduce the "fun" of merge conflicts, either jump on IRC, or in this thread add the test(s) you want to work on. 

We'll obviously do our best to merge often as we can and we'll deal with conflicts, but the less we have to focus on them, the more time there will be for writing tests.

### Coordinators
- PHPUnit unit tests @rossriley
- Codeception acceptance tests @GawainLynch

**Comment by GawainLynch** [comment]
Admin user:
- Navigate to main configuration
  - can see "Edit file » config.yml"
  - can see "sitename: A sample site"
  - change to "sitename: Wrong Name"
  - Revert button and can not see "sitename: Wrong Name" but can see "sitename: A sample site"
-

**Comment by GawainLynch** [comment]
This weekend's project manager, Furlish van Seal joins us to assist keep a watchful eye on our progress.  Furlish originally joined the Bolt team during the BoltCamp on Vlieland in 2014
![Furlish](https://cloud.githubusercontent.com/assets/1427081/6764070/04889852-cf96-11e4-8254-092e710eb36b.jpg)

**Comment by bobdenotter** [comment]
These three issues could've been caught by tests: 
 
 - #3209 The "current" in menus seems to be broken, causing the current page not to highlight
 - #3201 "Duplicate" pages with differing canonicals
 - #3206 The 'aside' in the `base-2014` theme lists all contenttypes, even if they have `viewless: true`

**Comment by GawainLynch** [comment]
** Manager User **
- Publish records written by 'editor' user

**Comment by GawainLynch** [comment]
**Developer User**
- Navigate to Extras -> View/install extensions

- Navigate to Extras -> Configure extensions

**Comment by GawainLynch** [comment]
**Frontend**
- Navigate to About page
- Check value for menu (see #3209)
