### ISSUE TITLE
Consistent method of telling if a field is empty

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3193]
When writing a template, there are all sorts of checks you can do for a record field to determine if it has a value or not. Sometimes its `{{ if record.value }}` or `{{ if record.value != '' }}`, and most recently I've come to favour `{{ if record.value is not empty }}` and the much uglier PHP "equivalent" `$var = (string) $record['value']; if (!empty($var))`.

The empty method works in most cases but not all (for example, an empty geolocation in a preview shows as not empty), and it the PHP version especially seems quick hackish. For both templates and extensions, being able to determine reliably if there is no data will be very useful.

When the new storage system by @rossriley is in place, this will be very easy to do, so we should probably hold off until then. Heck, it may even be in the works already (in that new system).

**Comment by bobdenotter** [comment]
The difficulty is that they all slightly mean something different, thanks to PHP's 'loose' comparisons. 

This one `{% if foo %}` is nice, but it'll give an error when `strict_variables` is set to `true`, so we try to avoid them. At least, I do, when i think of it. 

There's also a slight difference between `{% if record.value is not empty %}` and {% if record.value is not defined %}`. If we pick one to be consistent, we might introduce edge cases.

**Comment by Pinpickle** [comment]
I'm not talking about picking one of those cases as they all have flaws, I'm talking about introducing a new function/filter/property for fields to determine if they have it.

````twig
{% if record.filled('body') %}
````

````php
if (record.filled('body'))
````

And there would be a generic implementation that would probably be best just to use `empty` but for specialised fields where that doesn't work/isn't reliable, they should have their own function that interprets the contents and determines if its empty or not.

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
