### ISSUE TITLE
All .yml.dist files and theme files should use 'four spaces' as indentation. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3205]
.. to keep them consistent with other files.

**Comment by GawainLynch** [comment]
Space… the final frontier.

**Comment by jkazimir** [comment]
These are the voyages of the star-ship enterprise.

**Comment by rossriley** [comment]
If it's the star-ship enterprise they should be XML?

**Comment by jkazimir** [comment]
I'll work on a SOAP extension. ;)

**Comment by GawainLynch** [comment]
Wash your request out!
