### ISSUE TITLE
Thumbnail generation is buggy

### ISSUE THREAD

**Issue by psren** [bolt/bolt#3208]
I am running bolt with php -S

If i render a thumbnail with e.g. ```{{ image.filename|thumbnail(470, 320, 'b') }}```
the function spits out an image in wrong dimensions. I tried each mode, but always there are some images <= 3px larger than others.
This breaks my layout. Is there a known bug, or do only i have the problem?

**Comment by bobdenotter** [comment]
Are the _original_ images large enough? By default the thumbnailer only scales down, not up. Do you have an example of an image that's the wrong dimensions?

**Comment by psren** [comment]
Okay, the original image was too small.
I misinterpreted the docs.
