### ISSUE TITLE
The "current" in menus seems to be broken, causing the current page not to highlight.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3209]
verified in 2.1.3, probably also in 'master'.

**Comment by Pinpickle** [comment]
I noticed that this was the case when routing was set to use trailing slashes, but not the case when it didn't use trailing slashes. This was around 2.1.0

**Comment by bobdenotter** [comment]
Good catch, @pinpickle! I'll see if that has anything to do with it.
