### ISSUE TITLE
"Shyphenate" naively adds '&shy;' between every two character. It should do this only when needed. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3221]
.. otherwise, this is what you get:

![ebrc9fw](https://cloud.githubusercontent.com/assets/1833361/6768674/66ad40ca-d07a-11e4-9825-34b280f26844.png)

**Comment by GawainLynch** [comment]
…and I am having soooooooooo much fun trying to catch this in tests too, and now you want to take it away from me :stuck_out_tongue_winking_eye:
