### ISSUE TITLE
Thumbs not working

### ISSUE THREAD

**Issue by iulianba** [bolt/bolt#3232]
Hello,

Thumbs not seem to be working. I have created the files directory and uploads into it. Do i need to do something else for thumbs? The path is /thumbs/ if I check the uploaded images, but the path does not exist. Do I have to create it?

Thanks

**Comment by GawainLynch** [comment]
Thumbs are automatically generated when they're needed, and temporarily stored in `app/cache/`.

So if you attach an image to a record, it will generate the thumbnail for that image then (and cache it), or if you reference the image in the frontend template with `thumbnail()` one is also recreated then.

There is a section in the [documentation](https://docs.bolt.cm/templatetags#imageinfo) and in the [cheatsheet](http://cheatsheet.bolt.cm/#bolt-functions-twig) that might explain more on using them in your templates.

**Comment by iulianba** [comment]
I`m only speaking of admin right now. The thumbs are used in content types - but if I right click the image, it says 404 not found.
Generally speaking, now thumb is shown on admin. Even on the uploader.

Also, the image stack is not working. If i try to upload, it won`t do anything. This has something to do with permissions or folders not created, but I have no idea where to start searching from.

**Comment by GawainLynch** [comment]
OK, your web server rewrites are probably not set up correctly.

For Apache make sure mod_rewrite is enabled/installed.

Nginx check that your virtual host config has something like this:
```nginx
    location ~* /thumbs/(.*)$ {
        try_files $uri $uri/ /index.php?$query_string;
    }
```

**Comment by iulianba** [comment]
Apache/2.2.14 (Unix)
mod_rewrite Module Available

**Comment by zomars** [comment]
Im having the same issue, but only when developing in my localhost, the thumb generator gives me a 404 error.

**Comment by 00shoe** [comment]
I was also experiencing this problem where the admin pages weren't showing image thumbs.  I checked a previous htaccess file and copied this line of code to the top of the current htaccess file. Once I did this, thumbs were working again.

AddHandler application/x-httpd-php54 .php

Hopefully my fix isn't breaking anything.  Maybe someone with more experienced with this can confirm it.

**Comment by iulianba** [comment]
I managed to solve this. The "problem" was lighttpd on my server that was serving all "static" files. I've whitelisted the thumbs path and we're good.

**Comment by zomars** [comment]
Care to explain how did you accomplished that?

**Comment by dazeb** [comment]
> ```nginx
>     location ~* /thumbs/(.*)$ {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
> ```

This worked perfectly when using Cloudpanel Nginx vhost file.
