### ISSUE TITLE
We should _not_ translate content.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3234]
Like, ever. See screenshot: 

![screen shot 2015-03-23 at 15 50 39](https://cloud.githubusercontent.com/assets/1833361/6782431/754ba720-d174-11e4-8e6c-fc9cbd6a3a49.png)

I can set the `name` of the `entries` contenttype to whatever I want, but it doesn't change on the site, because it stubbornly keeps using the translation for the word 'entries'. Bolt shouldn't try to do this.

**Comment by rarila** [comment]
The question is why you don't change it where you should: in the translations. :grinning: 
Or delete the translation there if you insist on setting it at the place where you define your data.

**Comment by bobdenotter** [comment]
I politely disagree.. What's the use for a 'name' field, if Bolt is just going to ignore it?

**Comment by rarila** [comment]
I politely disagree. What's the use of a translation if bolt just ignores it.
Simple thing, the name field is something still there from the past something to be deprecated and removed. It makes no sense to have localisation in your data definition. It's simply not the place where it belongs to. It has a reason why we don't (at least try to) hardcode strings in php, why we seperate logic, model and presentation.

**Comment by bobdenotter** [comment]
I think the issue is a bit broader even: The names are also disregarded when the interface is in English. See screenshot:

![screen_shot_2015-03-23_at_18_28_33](https://cloud.githubusercontent.com/assets/1833361/6786159/c3608564-d18a-11e4-9769-1d47b9953173.png)

**Comment by rarila** [comment]
Consistent behavior. There are is also a English translation. How else could it be. There's nowhere defined that contenttypes.yml is English, or Dutch or anything else. How should Bolt know if it should get a translation or the name fits to the choosen locale?

**Comment by GawainLynch** [comment]
Consistent behaviour, IMHO, should be that in the screenshot above that 'My pages name' is what gets translated.

**Comment by bobdenotter** [comment]
But, you agree that if I name my contenttype for pages `name: Mike`, that the sidebar should say "Mike", right? The thing is that it's very confusing.. For example: 

```
pages:
    name: Mike # This will be competely ignored. Shows as 'Pages'

foo:
    name: Bar # Perfectly fine. Will show as 'Bar' everywhere.
```

This is a weird, confusing inconsistency we can never explain to end-users.

**Comment by GawainLynch** [comment]
Either the `name:` and `singular_name:` shouldn't exist, or they should be optional and take precedence over the translation object.

I wan't to be able to have my Portuguese friends use my site and have them see "Mi novas páginas", and in turn I want to see "My new pages".

**Comment by GawainLynch** [comment]
I know my latter point is still "down the track" but if I change the locale then I don't want to have to update my `contenttypes.yml`

**Comment by rarila** [comment]
Deprecate, remove, done.
The real problem is that we deliver a contenttypes.yml.dist with name & co in it and at the same time deliver the correct translations for it. That's the thing that could confuse someone. contenttypes.yml.dist should only have slug and singular_slug set and the source of confusion is gone.

**Comment by rarila** [comment]
@GawainLynch that's the point. The data model has to be decoupled from the presentation. Otherwise Bolt never can go multilanguage.

**Comment by rarila** [comment]
Not to forget that you probably not have to change the locale in config.yml, later the usrr could change his/her language in the user settings or it is simply set by browser preference.

**Comment by GawainLynch** [comment]
@rarila I get where you're going… and agree with decoupling… but we're just not in a position do everything at once rip-and-replace style.

What it does raise though it usability for the endless supply of new users we have trying to grapple with **any** data model we give them.  The current design is relatively easy… I've had Erin go in and edit YAML files in `app/config/` without ever having seen a YAML file or even being told how/where. 

Having a simple "override" *does* make sense to me, as does letting a user who is competently experienced in using and configuring Bolt have the ability to delete those keys and having the translations infrastructure take over. Much like we (currently) document that people should set some directories to `777`… I took one look at that the first time I downloaded Bolt and… well… I've never done it… 

In that same vein, I also implement things like mandatory access control on my servers… Can you imagine telling a basic user that it makes more sense to be running your systems with MAC in place? :grinning: 

> Not to forget that you probably not have to change the locale in config.yml, later the usrr could change his/her language in the user settings or it is simply set by browser preference.

Yeah, I know and I specifically framed my feedback with that on IRC… I am a native English speaker and, like it or not, people default to that when dealing with me… I get my native language where ever I go and it saddens me as I feel the privilege that I get, and prejudice I portray as a result.

**Comment by bobdenotter** [comment]
> change his/her language in the user settings or it is simply set by browser preference.

That is _such_ a huge anti-pattern. Please never do that. Whenever I go to a website, and it tries to "help" me by setting the language to broken dutch, I always want to ragequit. 

I'm going to work tonight on a proposal on how to fix this, regardless if it's a temporary solution until we do this right. In short: 

 - I want to change as little functionality as possibly
 - I _do_ want to allow overrides: If you set the 'name' explicitly, that's what should be used as the basis for the translation. Not the 'slug'.

**Comment by rarila** [comment]
As I said, the usability for new users is absolutely no problem when we remove the names from ct.dist. If you create a new contenttype mike and add name: mike is great there it never will be overwritten by translation as there's none. Also the new user won't change name and wonder that has no effect, when there's no name field from the beginning.
Having contenttypes overwrite translations would render the whole thing useless as they never would be displayed.

**Comment by bobdenotter** [comment]
I'll let the code do the talking! It'll work both ways! :-)

**Comment by bobdenotter** [comment]
Closing this one.
