### ISSUE TITLE
Nut command: extensions:install

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3255]
Most of the time, running `composer install` in the extensions directories works for installing extensions manually, but I am skeptical that it will work all of the time.

A simple nut command to install all extensions as well as installing an individual extension (adding it to the composer.json file if necessary) would be pretty useful. Exactly the same as the workflow on the extension panel on the website.

    php app/nut extensions:install [extensions]

I'm supposing also, that an update command would be useful as well

    php app/nut extensions:update [extensions]

**Comment by Pinpickle** [comment]
Whoops, this command does exist.

Outdated docs: https://docs.bolt.cm/nut

**Comment by Pinpickle** [comment]
Turns out that I was mistaken, the command can install a single extension but not all of them. Re-opening and pinging

I'm proposing that `nut extensions:install` without any extra arguments will install all extensions required by the project, just like a `composer install`.

Pinging um... @rossriley @GawainLynch ?

**Comment by SahAssar** [comment]
Closing this since it would be no different than "php app/nut extensions && cd extensions && composer install", right? If somebody want's to implement it that would be very nice, but it's more of a nice-to-have, right?
