### ISSUE TITLE
can't reinstalled extension

### ISSUE THREAD

**Issue by isularifin** [bolt/bolt#3272]
i have tried reinstalled an extention. But i got error message:

```
Fatal error:  Call to undefined method 
Composer\DependencyResolver\Operation\UpdateOperation::getPackage() in 
/home/sloki/user/xxx/sites/xxx.com/www/extensions/installer.php on line 9

{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Call to undefined method 
Composer\\DependencyResolver\\Operation\\UpdateOperation::getPackage()","file":"\/home\/sloki\/user\/xxx\/sites\/xxx.com\/www\/extensions\/installer.php","line":9}}
```
thanks

**Comment by GawainLynch** [comment]
If I remember correctly, the file `extensions/installer.php` is a left over from version 2.0 that can safely be removed.  Can you delete that, try again and let us know?

**Comment by GawainLynch** [comment]
Oh, and could you also ensure that you are on Bolt 2.1.4-pl1 :-)

**Comment by isularifin** [comment]
Still not working :(

**Comment by isularifin** [comment]
and i got anothe error message:
Warning: copy(/home/sloki/user/k1621177/sites/geraikhazanah.com/www/extensions/ExtensionInstaller.php) [function.copy]: failed to open stream: Permission denied in /home/sloki/user/xxx/sites/xxx/www/src/Composer/PackageManager.php on line 512

**Comment by GawainLynch** [comment]
Ah, that explains something!

Your web server doesn't have write access to `/home/sloki/user/xxx/sites/xxx.com/www/extensions/`

**Comment by isularifin** [comment]
Yes, it's working thanks.

**Comment by isularifin** [comment]
sorry, i have deleted a wrong files :)

**Comment by isularifin** [comment]
big thanks @GawainLynch  :+1:

**Comment by GawainLynch** [comment]
You're very welcome!
