### ISSUE TITLE
Still strange alignment accessible pages in page overview after update 2.1.4

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3281]
With issue https://github.com/bolt/bolt/issues/3228#issuecomment-85361114 I mentioned a strange alignment of accessible pages in the page overview for users with fewer rights. After installing 2.1.4 this issue isn't solved. The strange alignment is still there...

**Comment by GawainLynch** [comment]
Ooopsie… that change went into master, but wasn't cherry-picked into release/2.1

**Comment by GawainLynch** [comment]
Fixed and in there now!  If you want it now, [copy this file](https://raw.githubusercontent.com/bolt/bolt/master/app/view/twig/_base/_listing.twig) into `app/view/twig/_base/` and you'll be good to go until 2.1.5 is released.

**Comment by gwbonline** [comment]
Thanks! Only one more thing...

The 'No.' designation is now a question mark for every entry...
![screenshot](https://cloud.githubusercontent.com/assets/9332608/6892926/c6a67fce-d6c8-11e4-9d3d-e0b463b461c0.jpg)

**Comment by GawainLynch** [comment]
Have you flushed the cache? I have switched my test install to nl_NL and can't reproduce.

**Comment by gwbonline** [comment]
Yes, I did that. The list of users has no question marks. All other lists (content) have a question mark before each entry instead of 'No.'

![screenshot](https://cloud.githubusercontent.com/assets/9332608/6893280/f7542c68-d6cb-11e4-8842-6a1c85c296da.jpg)

**Comment by gwbonline** [comment]
When I view the source code of the older file, I see '№' and copy that. When I view the source of the newer file, I see '?' and thought that it would be simple to replace this with '№'. But when I want to paste the '№', it turns in to a question mark.

**Comment by GawainLynch** [comment]
At a guess, something screwy with translations.  @rarila any ideas?

**Comment by gwbonline** [comment]
Forgot to mention, this happens when I edit the file after downloading them (not online via Bolt)... Because I can't replace the question mark with '№', I see the question mark in Bolt after uploading it.

**Comment by Intendit** [comment]
Are you sure that you are saving them with the correct charset etc? I've seen this issue when editing files with winSCP which defaults to ANSI instead of UTF-8 (I think).

**Comment by bobdenotter** [comment]
The "№" is not run through the translations. I guess this was an error with uploading.

**Comment by GawainLynch** [comment]
Not supposed to be, but it wouldn't be the first time something like that has snuck though and had us doing the "What the?" dance :grinning:

**Comment by bobdenotter** [comment]
I clearly remember declining a Pull Request where somebody made the "№" translatable. ;-)

**Comment by GawainLynch** [comment]
Me too…

**Comment by gwbonline** [comment]
I use Notepad++ and a few years back I set the default charset to UTF-8. For some reason it wasn't set that way anymore. I corrected this and now I can edit _listing.twig manually to replace the question mark with '№'. Uploaded it and now all question marks are replaced in Bolt. Thanks!

**Comment by GawainLynch** [comment]
:+1:
