### ISSUE TITLE
The username should be unique

### ISSUE THREAD

**Issue by TrafeX** [bolt/bolt#3287]
As discussed on IRC; the username should be unique in Bolt.
The current implementation doesn't fully enforce that;

* The userform in the backend does check on the availability: https://github.com/bolt/bolt/blob/master/src/Controllers/Backend.php#L2162
* But the `saveUser` method does a last minute slugify which breaks the availabilty check (https://github.com/bolt/bolt/blob/master/src/Users.php#L125)
    * For example; `user-name` and `user+name` are unique according to the availability check, but slugify changes `user+name` to `user-name` which make it duplicate
* There's no constraint on the user table to make sure username is unique

My proposal would be to:
* Add a unique contraint on the username field in the user table
* Remove the slugify on usernames
* Restrict the validation on the username to only allow 'safe characters' (e.g. `a-z0-9_+-`)
* Keep the availability validation, it now works as expected

:warning: Setting the unique constraint on the username will fail on Bolt instances that already suffered from the 'weak' enforcing on unique usernames.
Maybe there should be some fallback? Or just a big red error that explains this should be resolved manually.

On a side note: It would be nice to increase the length of the `varchar(32)` username field.
In our case we want to use the e-mail address as username. It would be very nice if we only have to worry about getting the email address in the username field and the rest 'just works'! :)

**Comment by bobdenotter** [comment]
I believe this has become a non-issue, after @StevendeVries's hard work on #3348, right? If not, feel free to re-open it.
