### ISSUE TITLE
Timed publish does not work

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#3296]
Setting an entry's status to Timed Publish does not work. I have an etry whose date is set to a few days ago with timed publish and it does not show up on the site. The system log is also filling up with this message repeatedly:

> Timed publication of records for Array failed: An exception occurred while executing 'UPDATE bolt_entries SET status = 'published', datechanged = :now WHERE status = 'timed' and datepublish < :now':

> SQLSTATE[HY000]: General error: mode must be an integer

Using Bolt 2.1.4.

**Comment by GawainLynch** [comment]
This was/should've been fixed in the just released 2.1.5.  Can you update and let us know if that fixes it for you?

**Comment by svivian** [comment]
Ah yes, it's working now thanks. By the way the site still says 2.1.4 (which I just updated to yesterday).
