### ISSUE TITLE
Page links added in editor are incorrect

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#3301]
To reproduce, edit/create any page. In the "content" field (or any CKeditor field), highlight some text and click the Link button. Click "Browse Server", then Pages tab, the click a Page to link to.

The link comes up as `example.com/none/page-slug` but the URL should be `example.com/section/page-slug` due to custom routing. I have this set up:

```
pagebinding:
  path:           /{sections}/{slug}
  defaults:      
    _controller:     Bolt\Controllers\Frontend::record
    contenttypeslug: page
    sections:        none
  requirements:
    sections: [ 'Bolt\Controllers\Routing::getTaxonomyRequirement', ['sections', 'none'] ]
  contenttype:    pages
```

("section" is a custom taxonomy very similar to categories)

---

A second related issue is that the URL `example.com/none/page-slug` actually does show the correct page. And similarly, using any 'section' shows the correct page, causing duplicate content.

**Comment by bobdenotter** [comment]
Hi, 

Looks like this happens because the taxonomies aren't present when fetching the pages to link to.. We'll fix that! 

> A second related issue is that the URL example.com/none/page-slug actually does show the correct page. And similarly, using any 'section' shows the correct page, causing duplicate content.

That's really not an issue, because of the canonical in the source.

**Comment by SahAssar** [comment]
Just checking (since this has been open a while) @svivian, is this still an issue in the latest 2.2 release?

**Comment by svivian** [comment]
Just checked and yes this is still an issue on Bolt 2.2.13. Although the link is coming up as `/page/page-slug` now.
