### ISSUE TITLE
Default timezone to ini setting if not in config

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#3302]

**Comment by Pinpickle** [comment]
100% yes please, I was tripped up by this earlier because I didn't know that Bolt had its own timezone settings.

**Comment by GawainLynch** [comment]
@Pinpickle just move to the UK… it'll al be fine then :stuck_out_tongue:

**Comment by Pinpickle** [comment]
That's a *far* easier solution @GawainLynch! Why didn't I think of it sooner?

**Comment by bobdenotter** [comment]
:+1:
