### ISSUE TITLE
Cannot suppress appearance of related videos after embedded YouTube video ends.

### ISSUE THREAD

**Issue by rbx** [bolt/bolt#3304]
The appearance of related videos after an embedded YouTube video ends can be usually suppressed by adding `rel=0` after the link, like this: `https://www.youtube.com/watch?v=OgusGTmTYac&rel=0`.

However, adding the `rel=0` when inserting the video via Bolt, the parameter is ignored. It looks like Embedly ignores it. I am on an older version of Bolt - 1.6.12.

I tried adding the following to see if it works :
```twig
{# 'wmode=opaque' is part is the final youtube URL after Embedly is done with it #}
{{ record.video.responsive|replace({'wmode=opaque': 'wmode=opaque&rel=0'}) }}
```
and variations thereof with excaping the characters, but it resulted in just printing of this html code in the place where the embedded video should appear:
```html
<div class="responsive-video widescreen"><iframe class="embedly-embed" src="//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2F9Q6fPjw9cTk%3Ffeature%3Doembed&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Q6fPjw9cTk&image=http%3A%2F%2Fi.ytimg.com%2Fvi%2F9Q6fPjw9cTk%2Fhqdefault.jpg&key=3fedecb044d94eccb9eef404bee82126&type=text%2Fhtml&schema=youtube" width="854" height="480" scrolling="no" frameborder="0" allowfullscreen></iframe></div>
```

Looks like I am not escaping something properly or replacing in the wrong place.

**Comment by bobdenotter** [comment]
Hi rbx, 

Try this: 

    {{ record.video.responsive|replace({'wmode=opaque': 'wmode=opaque&rel=0'})|raw }}

**Comment by rbx** [comment]
Hello Bob,
Thanks for the tip, the `raw` filter did the trick!

For anyone else having the same issue:
I had to change the target of the replace filter, because the `wmode=opaque` is part of the second iframe that is created dynamically by Embedly and can't be accessed from the template (it doesn't even show in the source code of the final page, only by inspecting the elements one can view it). 
But modifying the first Embedly URL does the job and Embedly propagates the argument to YouTube (special characters need to be escaped). This worked for me:
```twig
{{ record.video.responsive|replace({'%3Ffeature': '%3Frel%3D0%26feature'})|raw }}
```
Shouldn't be a long term solution however - if the API changes, it might fail.
