### ISSUE TITLE
twig imageinfo function does not take exif orientation into account

### ISSUE THREAD

**Issue by Intendit** [bolt/bolt#3306]
The imageinfo function outputs the following for a image that is landscape "in the file" but is rotated by bolt-thumbs (because of exif rotation) when generating the image:

      "width" => 1536
      "height" => 1024
      "type" => "jpeg"
      "mime" => "image/jpeg"
      "aspectratio" => 1.5
      "landscape" => true
      "portrait" => false
      "square" => false

While I understand that the info output is for the original, not for the expected thumb and that info about thumbs cannot be retrieved in the twig template (thanks @bobdenotter for setting me straight last night :) ) perhaps the imageinfo function could show the exif orientation as well as the original one?

**Comment by bobdenotter** [comment]
Fixed by #3308 :-)
