### ISSUE TITLE
Redirect on 404

### ISSUE THREAD

**Issue by julianxhokaxhiu** [bolt/bolt#3313]
Is it possible to do a Redirect to the homepage on 404 aka `config.yml#notfound` ?

If so how? Thanks in advice.

**Comment by bobdenotter** [comment]
Not really, but you can always redirect in your 404 template, like this: `{{ redirect('/') }}`. 

Hope this helps!

**Comment by julianxhokaxhiu** [comment]
Perfect! Thank you very much :)
