### ISSUE TITLE
[RFC] Password input fields in contenttypes

### ISSUE THREAD

**Issue by miguelavaqrod** [bolt/bolt#3314]
Hi,

It would be nice to have:

myfield:
    type: password

As sometimes, contenttypes store some fields with sensible data I do not need to show to backend users.

Thanks!
miguelav

**Comment by bobdenotter** [comment]
I don't think this is a good idea. The passwords would still be stored in plain text in the DB. 

 - Anybody who has access to that page will _still_ be able to see the 'password', if they have a very minimal amount of knowledge of HTML (either 'right click, inspect element' or 'view source')
- "password masking" is more and more seen as an 'anti pattern', and I try to avoid it if I can: http://passwordmasking.com/

If we added a `type: password` field, we'd only create a false sense of security. If these fields are created by an extension, you should look into hashing them. See here for an example: 

https://github.com/bolt/PasswordProtect/blob/master/Extension.php#L191

**Comment by GawainLynch** [comment]
I'm going to back @bobdenotter up here. I was going to reply with something the same after :coffee: but he beat me to it.

Password handling is something that should be done with audited code, not random templates.  It's just obscurity otherwise and has the potential to give a novice a "feeling" of security where absolutely and utterly none exists.

**Comment by miguelavaqrod** [comment]
Hi!

Thanks in advance...

OK! OK! I see the point... ;-) You are totally right.

Alas, it seems I can not store sensible data in a contenttype field and configure the backend so only, for example, 'normal' users view the contenttype fields without that specific field, and admins see the whole contenttype fields. :-(

**Comment by bobdenotter** [comment]
I'm going to close this for now. I think you should either use the passwords in plain text in the contenttype (knowing that all admins can see them) or use something else. Either encrypt them, before storage.. 

Or, perhaps even use another contenttype, just to store the names + passwords, and create a relationship, and _don't_ give the other editors access to that.
