### ISSUE TITLE
CustomTest extends BoltUnittest but phpunit can't find boltunittest class..

### ISSUE THREAD

**Issue by spicyroland** [bolt/bolt#3315]
Here is the console output.

/usr/bin/php /tmp/ide-phpunit.php --bootstrap /var/www/bolt_cms/tests/phpunit/bootstrap.php --no-configuration phpunit\Controller\BidbucketTest /var/www/bolt_cms/tests/phpunit/Controller/BidbucketTest.php
Testing started at 10:59 PM ...
PHP Fatal error:  Class 'Bolt\Tests\BoltUnitTest' not found in /var/www/bolt_cms/tests/phpunit/Controller/BidbucketTest.php on line 16
PHP Stack trace:
PHP   1. {main}() /tmp/ide-phpunit.php:0
PHP   2. IDE_Base_PHPUnit_TextUI_Command::main() /tmp/ide-phpunit.php:516
PHP   3. PHPUnit_TextUI_Command->run() /tmp/ide-phpunit.php:258
PHP   4. PHPUnit_Runner_BaseTestRunner->getTest() /var/www/bolt_cms/vendor/phpunit/phpunit/src/TextUI/Command.php:127
PHP   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() /var/www/bolt_cms/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:72
PHP   6. PHPUnit_Runner_StandardTestSuiteLoader->load() /var/www/bolt_cms/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:127
PHP   7. PHPUnit_Util_Fileloader::checkAndLoad() /var/www/bolt_cms/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:43
PHP   8. PHPUnit_Util_Fileloader::load() /var/www/bolt_cms/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
PHP   9. include_once() /var/www/bolt_cms/vendor/phpunit/phpunit/src/Util/Fileloader.php:58

Process finished with exit code 255

In phpstorm settings und php > phpunit I have select "use custom autoloader" with default bootstrap file pointing to "/var/www/bolt_cms/tests/phpunit/bootstrap.php"

What am I doing wrong? 
Tried all different kinds of configurations but no luck!
Appreciate your help.

**Comment by rossriley** [comment]
Can you paste the first 16 lines of `Controller\BidbucketTest` up to where the class is defined.

Also worth checking that you have done a composer update.

**Comment by spicyroland** [comment]
Sure. Composer update done just lately.

```
<?php
/**
 * Created by PhpStorm.
 * User: spicyroland@gmail.com
 * Date: 4/3/15
 * Time: 8:16 PM
 */

namespace phpunit\Controller;


use Bolt\Tests\BoltUnitTest;
use Symfony\Component\HttpFoundation\Request;

class BidbucketTest extends BoltUnitTest
{
```

and this is what my phpstorm configuration looks like:

![screenshot - 04052015 - 11 38 55 am](https://cloud.githubusercontent.com/assets/7749379/6996432/641a24a4-db88-11e4-94a4-a50e9762326e.png)

and last but not least this is what my **tests/phpunit/bootstrap.php** contains.
```
global $CLASSLOADER;

// Install base location
if (!defined('TEST_ROOT')) {
    define('TEST_ROOT', realpath(__DIR__ . '/../../'));
}

// PHPUnit's base location
if (!defined('PHPUNIT_ROOT')) {
    define('PHPUNIT_ROOT', TEST_ROOT . '/tests/phpunit/');
}

if (!defined('BOLT_AUTOLOAD')) {
    if (is_dir(TEST_ROOT . '/../../../vendor/')) {
        // Composer install
        define('BOLT_AUTOLOAD', TEST_ROOT . '/../../autoload.php');
    } else {
        // Git/tarball install
        define('BOLT_AUTOLOAD', TEST_ROOT . '/vendor/autoload.php');
    }

    // Load the autoloader
    $CLASSLOADER = require_once BOLT_AUTOLOAD;
}

// Load the upload bootstrap
require_once 'bootstraps/upload-bootstrap.php';

// Make sure we wipe the db file to start with a clean one
if (is_readable(TEST_ROOT . '/bolt.db')) {
    unlink(TEST_ROOT . '/bolt.db');
}
copy(TEST_ROOT . '/tests/phpunit/resources/db/bolt.db', TEST_ROOT . '/bolt.db');

@mkdir(TEST_ROOT . '/app/cache/', 0777, true);
```
Thank you.

**Comment by spicyroland** [comment]
Problem solved!! **require psr-4 Bolt\\Tests** was wrong in composer.json - therefore **tests-directory** didn't get autoloaded.
