### ISSUE TITLE
Bug in 'magic getter' for images..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3318]
As reported by tomntech on IRC: 

If you have a contenttype with an image with title, like this:

```
        image:
            type: image
            attrib: title
```

You would expect to get in in the theme like this: 

```
        {{ dump(record.image.title) }}
```

The correct value is in `values`, though: 

```
        {{ dump(record.values.image) }}
```

This is caused by the code that's "helpful" in returning the filename, when doing `{{ record.image }}`, around line 809 in `src/Content.php`

**Comment by bobdenotter** [comment]
Hmm, I think to _properly_ solve this, we should make `image` into an object with a `__toString()` function.

**Comment by bobdenotter** [comment]
Yeah, this is not fixable without refactoring the image field-type to an object with a `__toString()` method. 

Leaving this with a 'refactor' flag for now, and adding a note in `contenttypes.yml.dist` and docs.

**Comment by GawainLynch** [comment]
As this refers to legacy, it won't be fixed and should not even be relevant in the new storage layer … R.I.P.
