### ISSUE TITLE
PHP OpenSSL extension required (to install extensions)

### ISSUE THREAD

**Issue by hansfn** [bolt/bolt#3325]
Running Bolt 2.1.5 and PHP 5.5.8 and Apache 2.4.7 (on Windows .- local development env.)

Hi, I just tried to install an extension (from bolt/extend/). Clicking "Browse Versions" opened a popup with "Checking available versions.." that never completed. Trying in different browser and searching the issues - no luck. Then I remembered that Bolt comes with Nut (great stuff) and 

```
nut extensions:install name version
```

returned 

> [RuntimeException]
> You must enable the openssl extension in your php.ini to load information from https://extensions.bolt.cm/

Could this error also be returned when running Bolt in the browser?

PS! By the way, should it be possibly to click "Browse Versions" if no extension name is entered?

**Comment by bobdenotter** [comment]
Perhaps this is related to #3322 ?

**Comment by bobdenotter** [comment]
Also, Hi Hans! Good to see you here! :-)

**Comment by hansfn** [comment]
Hi, Bob. I looked at 3322, but found it different enough to post a new issue. 

It's time to move those old PivotX sites over to Bolt. (I would rather give Bolt a spin instead of creating yet another WP site.) Did you see my activity in the ImportWXR repo - one issue and two pull requests?

**Comment by bobdenotter** [comment]
No, i've missed those.. Will take a look now! :-)
