### ISSUE TITLE
[Wish] PDF Thumbs

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3340]
This idea occurred to me when I had to convert a whole bunch of PDFs to JPEGs for a website. Essentially you could get an image thumbnail from a pdf file.

This is probably extension material and is most likely a big can of worms.

**Comment by Intendit** [comment]
Isn't that what blockmurder/pdfpreview does?

**Comment by Pinpickle** [comment]
Well that's what I get for not researching.

It is indeed what that extension does! It looks like it handles it a bit crudely (relying on `convert` executable) but indeed does the job!
