### ISSUE TITLE
Add error states for embed.ly (was: "Video preview and embed not always working")

### ISSUE THREAD

**Issue by doom99** [bolt/bolt#3346]
Enter video url, save entry.  Video metadata is not returned. No preview is available, no video loads when page is displayed. 

per IRC chat: 
	ros******:  it could have been that the embed.ly service was down or something...

Testing again this morning with new entry, videos now embed, above seems reasonable explanation.

Additional issue: Entries created while embed.ly was unavailable, though containing the url, are not updated once the service is reachable again. 

Suggest:   

a) console give pop-up or other message to indicate service unreachable.
b) a mechanism exist that scans video url data to attempt to load any for entries created when embed.ly was not reachable.  Otherwise must re-enter URL's on all those entries (this might be a minor or a major inconvenience depending on site). 

Thanks again for IRC assistance.

**Comment by SahAssar** [comment]
@doom99 Have you experienced this multiple times? While I think we should work on failure states for the JS, this particular error seems uncommon. This seems more like an indication that we should add error states/messages for most external AJAX functionality.

**Comment by SahAssar** [comment]
Alright, I'm changing the title to make this more obviously actionable. Our google maps implementation already has error checking, but embed.ly does not. After talking with @rarila on IRC this seems like a simple fix: simply display an alert when the error occurs. Something along the lines of

    if(err){
        alert('sorry, we had a problem...')
    }

We could probably fix #4179 at the same time.

**Comment by hansfn** [comment]
Yes, logging the error when the call to embed.ly fails would be very nice. Just wasted an hour trying to track it down. In the end I added

    .fail(function(jqXHR, textStatus, errorThrown) { 
        console.log('getJSON request to embedly failed'); 
        console.log("textStatus:" + textStatus + "; responseText:" + jqXHR.responseText)
    });
 
to line 123 of app/src/js/modules/video.js - chaining the $.getJSON call. (Or to be honest - I added the code in the right place of app/view/js/bolt.min.js since I din't have Grunt installed.)

PS! To make it 110% annoying the problem was the NoScript extension blocking embed.ly ... The video embedding of course worked after I told NoScrip to allow embed.ly,

**Comment by hansfn** [comment]
Related to the request for 

> a mechanism that scans video url data to attempt to load any for entries created when embed.ly was not reachable. Otherwise must re-enter URL's on all those entries (this might be a minor or a major inconvenience depending on site). 

This is also needed for all entries imported using the ImportWXR extension which only sets the "url" key for the video field. Doing dummy edits - adding "X" to the video URL and then removing "X" - for all imported entries can be a lot of work. PS! ImportWXR currently doesn't support importing into video fields. See issue https://github.com/bolt/ImportWXR/issues/13 for more info.
