### ISSUE TITLE
[RFC] Live Editor only HTML Fields

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3350]
CKEditor puts in a lot of extra logic when you're editing using their inline mode, and I'm fairly sure it changes how it sanitises its code. For example, if you have some `div` elements making two columns of content, in a normal CKEditor field, it would firstly be very difficult to tell where the two sidebars are and secondly, in my experience, CKEditor unpredictably gets rid of those `div` wrappers (despite my best efforts to change that in config).

When its inline, CKEditor knows that these have meaning, and it doesn't randomly get rid of them and the whole "inline" thing makes it really easy to tell where those different bits of content are. Problem is, when you take those edits back to the regular HTML field inside Bolt, it may then mess with the HTML as I have experienced.

What I'm proposing is a flag for HTML fields to make them "live only", where when you see them in the regular editing page, you have a note saying that this is the case, a button to take you to the live editor and also the ability to edit the raw source of the field (in a CodeMirror block?).

Ping @bobdenotter for philosophy.

**Comment by timcooper** [comment]
Handling layout blocks within a single CKEditor instance sounds like the sort of thing that should be handled by a plugin (http://ckeditor.com/addon/templates or http://ckeditor.com/addon/div) - I would guess/hope they support inline editing properly but can't say I've used them together.

I think this is also in danger of stepping on the toes of (as well as being solved by?) the "block" stuff from the list/repeating fields RFC, which is preferable in my opinion.

**Comment by SahAssar** [comment]
Since the new fieldtype "hidden" shares DB datatype with HTML fields that perhaps could serve as starting point for this?

Something along the lines of this perhaps:

	liveeditoronly:
		type: hidden
		live_edit_as: html
		prefix: "To edit this please use the live editor"

**Comment by SahAssar** [comment]
Closing this as a part of a cleanup (and since there as been no real activity since april 9:th). If the interest for this re-arises feel free to reopen or open a RFC in the forums :)
