### ISSUE TITLE
Changing the Bolt document root with htaccess

### ISSUE THREAD

**Issue by vikashd** [bolt/bolt#3368]
My server has a site with the document root folder set to 'public_html'. I have setup a folder in there called 'www' and a htaccess file which is using a RewriteRule to point at 'www'. The main site works however if I try to access any pages under the main url (e.g. www.my-site.com/admin) I get a fatal  error with Bolt not finding the template file. I'm guessing I need to do something with my .htaccess file. I don't have much experience with this and would appreciate some help fixing this. Thanks!

**Comment by bobdenotter** [comment]
Why don't you just put all the files in 'public_html'? That will work.

**Comment by vikashd** [comment]
I was just wondering if there is a way for me to do it that way as I explained above. For example if I had another version of the site I wanted to switch to I could update the htaccess file to point to another folder under 'public_html'.

**Comment by bobdenotter** [comment]
I don't think that's the best way to do that.. If you want to switch sites like this, set it up like: 

```
- /deploy
  - /version1
  - /version2
```

and then do `ln -s deploy/version2 public_html`.
