### ISSUE TITLE
Canonical tag ignores config.yml setting

### ISSUE THREAD

**Issue by Intendit** [bolt/bolt#3374]
It seems our troubles with canonical did not end with #3201...

Now when a site can be accessed from two domains the canonical is always set to the domain that is accessing the site, not the one set in config.yml.

I'll investigate more and comment when I know whatsup.

**Comment by bobdenotter** [comment]
I can't reproduce this.. I think it works as it should. If you have more info, please let me know. :-)

![screenshot_2015-04-20_20_45_23](https://cloud.githubusercontent.com/assets/1833361/7237815/5b11cc96-e79e-11e4-8dff-355275f7d70f.png)

**Comment by Intendit** [comment]
Can't reproduce on master-branch anymore. Closing issue.
