### ISSUE TITLE
Cannot set "from" email address

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#3376]
I've set up the `mailoptions` on my site, but I didn't see any method to specify the email address and name from which emails are sent.

Currently the emails appear to be sent from "Bolt" with my own email address. In Gmail it's listed as "Bolt via mail133-25.atl131.mandrillapp.com". Potentially this could cause problems with spam filters because the email is not actually sent from that address, and some servers may not even send the email without the correct From address.

After a quick look at the code it seems that "Bolt" is hard-coded, for example in `src/Users.php` on line 616:

    ->setFrom(array($user['email'] => 'Bolt'))

At the very least, by default it could use the `sitename` from config. But preferably have options in the mail section e.g.

    mailoptions:
      fromName: My Site
      fromEmail: mysite@example.com

**Comment by bobdenotter** [comment]
Fixed by @shyim in #3409!
