### ISSUE TITLE
No timezone in config.yml and php.ini leads to RuntimeException

### ISSUE THREAD

**Issue by JeromeBreizhtorm** [bolt/bolt#3377]
After upgrading from 2.1.3 to 2.1.6 i got errors from nut commands : 

> Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /myproject/src/Application.php on line 300

> Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to start the session because headers have already been sent by "/myproject/src/Application.php" at line 300

I fixed it by adding a timezone in my config.yml (i had no timezone set in my php.ini either).

Maybe it should default to UTC when no timezone is set.

see https://github.com/bolt/bolt/commit/a4f3e47590ff6c9b38ddc5029e7cc7002017815c

**Comment by GawainLynch** [comment]
c.f. discussion in #3333

**Comment by CarsonF** [comment]
Whether this is a "bug" is debatable. Not having it set in ini and having strict errors enabled causes this. This is a PHP thing, not a Bolt thing. 

But I understand how it looks to users. I'll do a fix tonight/tomorrow.

**Comment by GawainLynch** [comment]
Yeah, I know where you're coming from… but there was no tag for `cockroach` :stuck_out_tongue: 

UX-wise though, it is a bug.
