### ISSUE TITLE
Empty cache folder

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3378]
When I empty the cache via Bolt, the folder isn't emptied completely. There are still files and folders in the cache folder. Is it save to empty it manually so it contains nothing anymore?

**Comment by GawainLynch** [comment]
Yes, though I would leave the `index.html` file there.

There is probably either file permissions gone wrong, or ir you're viewing though the web UI, the cache directory will immediately get repopulated with generated Twig files to render the backend.  In the latte case, things are operating normally.

**Comment by gwbonline** [comment]
Everytime I install an update of Bolt, I check the mentioned folders (in the manual) for permissions. There are files and folders deleted when I clear the cache with Bolt, but a lot of folders are untouched. That is why I want to remove them manually.
