### ISSUE TITLE
Multilanguage app.config.set() in Twig outputs return value

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#3414]
There seems to be a small issue with your description of setting up multilanguage sites and the boilerplate:
Calling {{ app.config.set('general/locale', locales[language]) }} in Twig produces output of one character ("0" or "1") in HTML, since function set() in Config.php returns false or true.

Current workaround would be to add the replace-filter: {{ app.config.set('general/locale', locales[language])|replace({'0': '', '1': ''}) }} or use variable assignment.

**Comment by GawainLynch** [comment]
Functions have return values so that the caller can take actions based on that value, e.g. an error has occurred.

This is a bit of an overblown example, but you can do something like this:
```twig
{% set retval = app.config.set('general/locale', locales[language]) %}
{% if retval == 0 %}<blink>Setting the locale didn't work!</blink>{% endif %}
```

**Comment by rompcik** [comment]
Thats clear. But in the multilanguage documentation and in the boilerplate template for multilingual sites the return values are unhandled, thus documented code produces unwanted output.
It's not a failure of the function, but a failure of documentation, see https://docs.bolt.cm/howto/building-multilingual-websites and https://docs.bolt.cm/howto/boilerplate-for-multilingual-websites

**Comment by CarsonF** [comment]
[Twig for Template Designers](http://twig.sensiolabs.org/doc/templates.html#synopsis)
> There are two kinds of delimiters: {% ... %} and {{ ... }}. The first one is used to execute statements such as for-loops, the latter prints the result of an expression to the template.

Feel free to submit an issue or PR to [documentation repo](https://github.com/bolt/docs)
