### ISSUE TITLE
Error when I want to configure extensions

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3421]
When I want to configure extensions via the main menu (second option in Extra), I get the following error (screenshot). I use Bolt 2.1.6.

![screenshot](https://cloud.githubusercontent.com/assets/9332608/7248139/d8caca80-e810-11e4-96b9-1911d4d8157b.jpg)

**Comment by GawainLynch** [comment]
You need to have the PHP POSIX module enabled. I think @rossriley has a work around for this in master, but 2.2 isn't out yet.

**Comment by gwbonline** [comment]
Strange, because it was fine before. I thought this error was something else. But I applied the work around and now the error is gone.
