### ISSUE TITLE
[RFC] IIS installation

### ISSUE THREAD

**Issue by hyperTwitch** [bolt/bolt#3422]
Currently there is no easy way to install Bolt on an IIS based setup.

**Comment by bobdenotter** [comment]
Most of us have not much experience with IIS, so we're not in a good position to write docs or provide good configuration settings for it. If you do, you're more than welcome to help us out in this area! :-)

**Comment by bobdenotter** [comment]
Closing, because PR was merged!

**Comment by GawainLynch** [comment]
@hyperTwitch I've submitted #5304 to remove the file from the stable v3 release branch as it no worky-worky in v3 and is creating a support issue we don't have the expertise to handle.

What would be awesome is, if you have the personal bandwidth, move this to a page in [docs](https://github.com/bolt/docs).
