### ISSUE TITLE
Database integrity check broken for MySQL

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3426]
This one keeps showing up: 

![screenshot 2015-04-21 21 29 49](https://cloud.githubusercontent.com/assets/1833361/7260872/a7aa8816-e86d-11e4-8f8d-2e953c92b1e8.png)

Clicking "repair" won't give any errors, but on the next page request, it's back. The logs give this: 

    [2015-04-18 10:08:38] bolt.INFO: Database update required ["ALTER TABLE bolt_users DROP INDEX IDX_5585B54F85E0677, ADD UNIQUE INDEX UNIQ_5585B54F85E0677 (username)"] []

See also: #3398

**Comment by GawainLynch** [comment]
Introduced by #3348

**Comment by GawainLynch** [comment]
Also @timcooper identified the [offending code](http://www.doctrine-project.org/api/dbal/2.5/source-class-Doctrine.DBAL.Platforms.MySqlPlatform.html#550-551) and [reasoning](http://www.doctrine-project.org/jira/browse/DBAL-237) for the change that probably needs upstream action.

**Comment by GawainLynch** [comment]
Ping @StevendeVries any changes here affect you guys! Feedback/advice/beer welcome :grin:

**Comment by timcooper** [comment]
Mm I remember this from the other day, I was going to file an issue upstream but they use JIRA and I didn't have time to faff about making accounts and crap. Worth noting only the MySQL implementation does this, other DBs will be unaffected.

Whilst I agree that this is better dealt with upstream, I have a feeling even if a PR is sent it might not make it into a release by the time you want to release the next Bolt version.

I'm also wondering if they will even agree it's a bug, is there any cause to reasonably expect TableDiff to be immutable?

Either way it might be best to workaround it for now by cloning the object, stick a `/* @todo */` in to review before next release?
