### ISSUE TITLE
XSS Auditor error when saving file with <form action="">

### ISSUE THREAD

**Issue by Aralon** [bolt/bolt#3435]
When editing a twig file in the bolt backend with  `<form action="">` in it, I get the following error:

>The XSS Auditor refused to execute a script in '**path to the file (left this out)**' because its source code was found within the request. The auditor was enabled as the server sent neither an 'X-XSS-Protection' nor 'Content-Security-Policy' header.

The action attribute is what is causing the error, it only happens in files that contain an action attribute. The error only occurs in webkit browsers.

**Comment by GawainLynch** [comment]
@timcooper also [linked this](https://code.google.com/p/chromium/issues/detail?id=418888) in IRC that is possibly relvant

**Comment by timcooper** [comment]
Webkit's XSS Auditor is throwing this false positive and it won't be fixed upstream as there isn't really anything for it to detect the difference between legitimate use and sketchy danger.

We will need to add a header to make security checks on the editor less strict to allow things like this, I don't see it as being an issue as this is already treated as "trusted" input.

Bug on chromium tracker: https://code.google.com/p/chromium/issues/detail?id=418888

Can probably PR this evening if not handled by then.

**Comment by GawainLynch** [comment]
All yours, @timcooper
