### ISSUE TITLE
Error when slug contains words like page or not found

### ISSUE THREAD

**Issue by issux** [bolt/bolt#3438]
I use bolt.cm in my website, and i think i found some bug. I have a contentype called post, and one of them have title "Activar mod_pagespeed en Dreamhost" with slug "/post/activar-mod-pagespeed-en-dreamhost". All correct.

My problem is when i visit the post detail (http://www.domain.com/post/activar-mod-pagespeed-en-dreamhost always) return an error. If i modify slug to "/post/activar-mod-pagspeed-en-dreamhost", post can be viewed without problems. Other post with title "PHP: Warning: ob_start(): function '' not found" and slug "/post/php-warning-warning-ob_start-function-not-found" occurs the same problem. I think use some words like "page" or "not found" in slug is the problem origin.

Thanks.

**Comment by bobdenotter** [comment]
Are you using something as a wrapper to your site? Or perhaps some special rules for the 404 page in your .htaccess? I'm pretty sure that Bolt should not cause this.

**Comment by GDmac** [comment]
Tested, and no problem with ``Activar mod_pagespeed en Dreamhost``
Do you have custom routes (routing.yml) ?
(and then, maybe routing regex that might not anchor or target exact enough) ?

**Comment by issux** [comment]
Hello,

sorry, i did some more test and after saved both posts again, it worked fine.

Thanks.

**Comment by bobdenotter** [comment]
Glad you solved it! closing this issue.
