### ISSUE TITLE
[RFC] Leveraging Content object for other logic

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3440]
Contenttypes come with a lot of nice built in things in the backend - listings, editing, searching, sorting - it's all really someone would need, for say, a list of registrations that is populated by filling out a form on the frontend.

This is so much the case, that this is what I am doing for a current project of mine (yes, I have seen the waffle order extension) and it has made the process really simple. I haven't had to touch any DB code and setting it up as a contenttype has just made the process really easy in a lot of respects.

There are a few areas that aren't ideal, namely the fact that the notion of an owner and publication still exists. The publication status, especially, makes querying using `Storage->getContent` a little less intuitive which can be frustrating to deal with.

I was wondering if there were any plans to open the content object up a bit more, so we can use contenttypes for completely different logic in extensions? I'm guessing that this would be a lot simpler with the introduction of the new storage layer?

I do know about custom content classes, I have used them before but I think I'd have a hard time removing functionality from a class. Especially as so much of its functionality is tied up in the storage layer at the moment.

**Comment by GawainLynch** [comment]
You might want to have a look at the [start of the documentation work](https://github.com/bolt/docs/pull/190) that @rossriley has done for the upcoming changes in 2.3.

**Comment by Pinpickle** [comment]
It would seem that the separation of metadata from entities would solve this issue, which is really promising. I will leave this issue open, though, for reference.

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
