### ISSUE TITLE
Something, somewhere seems to be caching loripsum requests.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3449]
See screenshot: It seems to be a bit beyond coincidence that results are duplicate a bunch of times. 

![screenshot 2015-04-25 14 01 09](https://cloud.githubusercontent.com/assets/1833361/7332809/b48d6740-eb53-11e4-942c-174886563cb2.png)

**Comment by GawainLynch** [comment]
Definitely seeing this!

**Comment by bobdenotter** [comment]
Not just me, then. Good. ^_^

**Comment by bobdenotter** [comment]
Was an issue in loripsum.net itself. Fixed.
