### ISSUE TITLE
Pages showing up in Google index

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#3453]
I notice that pages like this one shows up in Googles index. As I understand it, it shouldn't be possible to reach this url. Is it an error of some kind? I use Bolt 2.1.6

http://www.ekonomism.us/bolt/index.php/entry/basinkomst-kostar-338-miljarder-kronor

**Comment by GawainLynch** [comment]
That is due to http://www.ekonomism.us/robots.txt returning a 404 instead of a robots.txt file.

**Comment by mattiaslundback** [comment]
Ah, so I need to put a robots.txt in the root to avoid the problem?

**Comment by GawainLynch** [comment]
Sure do. For details on the format [see this page](http://www.robotstxt.org/robotstxt.html)

And make sure your web server routes to it properly.  In your Google Webmaster Tools console you can request pages to be deleted from the index as well. That has both a lag-time and a limit on the number of requests you can submit though.

**Comment by mattiaslundback** [comment]
Thanks a lot. Sorry about the question, but I got so puzzled when I saw these entries.

**Comment by GawainLynch** [comment]
No stress… I have had a couple of heart stopping moments in the past over this exact thing. Also going to close this.
