### ISSUE TITLE
Adding twig filters/functions in an extension requires the function to be in the extension

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3456]
See the code [here](https://github.com/bolt/bolt/blob/master/src/BaseExtension.php#L394-L411).

I would like to put my twig functions/filters in another class for separation of concerns and all that, but as there is a `array($this, $callback)`, in the function, the call always comes from the extension object.

### Proposed behaviour

The object that does the calling is the reference (instead of `$this`). I don't know how possible that is in PHP, so if that's too hax, then at the very least, passing an array instead of a string to the function should replace the array that is made inside the twig filter/function functions.

**Comment by GawainLynch** [comment]
Have a look [here](https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/Extension.php#L94) and the [class itself](https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/src/Twig/BoltFormsExtension.php).

**Comment by Pinpickle** [comment]
Ah so it is definitely possible - good to know! I think that the ease of use for allowing arrays to be passed to `addTwigFilter` and `addTwigFunction` would make it a lot more straight forward for the simpler use-cases, though.

That being said, the extension objects do have access to the `$twigExtension` object which is just about as easy to add filters/functions to.

**Comment by bobdenotter** [comment]
Is this still "actionable" after Gawain's pointers? :-)

**Comment by Pinpickle** [comment]
@bobdenotter I believe so!

**Comment by CarsonF** [comment]
I'm going to have to disagree. I would rather use the same interfaces as what the libraries provide (eg: `Twig_Extension`). The Extension class should be the entry point / connection point into Bolt, very similar to symfony's bundles. That requires devs to learn less Bolt specific concepts and more general concepts. For example, if they've written a twig extension before it would be the same thing here.

**Comment by Pinpickle** [comment]
@CarsonF your argument makes much more sense - we don't need "Boltisms" cluttering things up.
