### ISSUE TITLE
[RFC] Change server config to better protect sensitive stuff

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3460]
*I'm going to use the htaccess file as the example here as I don't know other server configs that well. I hardly even know how to Apache anyway*

The only method of protecting sensitive files from being accessed (with default configs) is to 403 any files with the extension: `yml,md,db,twig` - which does work pretty well for protecting information that is sensitive in Bolt. However, I see a few problems with this approach:

- If a particular website wants to distribute other files of these types (which isn't a ridiculous request), it may not be apparent why these permission restrictions are occurring, and enabling them would be a pretty sticky process
- Users are presented with a (probably ugly) 403 error document that isn't served by Bolt
- The fact that a 403 error is returned, and not a 404 error, indicates that this file exists and that is a little bit of information disclosure

What I've done with my server config (and what I propose), is to have select directories and files that are allowed to have their contents served:

- `bolt-public/view` and `app/view` (depends on how Bolt was installed)
- `files`
- `theme/*/assets` - This one is significant as it makes the call that all static assets for a theme should be stored in an assets folder inside that theme. I am suggesting that templates **do not** go in here.
- Select files at root. This is mainly `favicon.ico` but some applications like Google Webmaster Tools have you put a verification file in webroot. Those will have to be handled on a case-by-case basis by the developer.

Then *all* other requests, regardless of whether the file exists or not, get routed to Bolt so it can serve a 404 document.

Currently, Bolt *does* store its templates in `app/view/twig`, so either an extra directory will have to be made to separate server view files from client view files, or special cases will have to be made for every allowed directory (css, js, font, img)

Here's the mod rewrite code I've been using. Let me re-iterate that I am not great at htaccessing. I am very sure that there is a better way of doing this (but still bearing in mind that Bolt in subdirectories has to work and we can't use the `<directory>` directive in a .htaccess file).

````apache
RewriteEngine on

# Catch the base directory of Bolt in variable "base", and the path that Bolt will be parsing in variable "basepath"
RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]
RewriteRule ^(.*)$ - [E=BASEPATH:$1]

RewriteRule cache/ - [F]

# Some servers require the RewriteBase to be set. If so, set to the correct folder.
# RewriteBase /

# Check that there is no internal redirect happening
RewriteCond %{ENV:REDIRECT_STATUS} ^$

# Check that the path is not for an approved directory
RewriteCond %{ENV:BASEPATH} !^theme/([^/]+/assets
RewriteCond %{ENV:BASEPATH} !^files
RewriteCond %{ENV:BASEPATH} !^bolt-public/view
RewriteCond %{ENV:BASEPATH} !^app/view
RewriteCond %{ENV:BASEPATH} !=favicon.ico
RewriteRule ^ %{ENV:BASE}index.php [L]


# We may be in an approved directory, but the file may not exist. So check if the file exists
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{ENV:BASEPATH} !=favicon.ico
RewriteRule ^ %{ENV:BASE}index.php [L]
````

**Comment by GawainLynch** [comment]
**Disclaimer:** I am suck in Dubai airport for 9 hours… and *really* bored. From the Apache perspective this comment adds nothing… but…

Use Nginx, [we do our config better-er](https://docs.bolt.cm/installation#nginx-configuring-virtual-host)… and stuff.

**Comment by Pinpickle** [comment]
@GawainLynch believe me, I would. Unfortunately, that isn't an option for everyone (cheap shared hosting, yay).

Though it looks to me like the Nginx config suffers from similar pitfalls as the Apache one? There are lots of `Deny All`s, which makes me think that a 403 will be sent without Bolt getting to see the request. Correct me if I'm wrong!

**Comment by GawainLynch** [comment]
Well, the funny thing is… I am of the opinion that denies belong low in the stack…

If you're trying to access something you shouldn't in a file system sense, that doesn't belong in the application stack.  Not that the application stack shouldn't also check, but just that it **should** be handled earlier… much earlier. 

I may be on an island here… but we have rum cocktails.

**Comment by Pinpickle** [comment]
I think you're right in that regard, but in this situation there are a lot of caveats (information disclosure and error documents produced not through bolt), which is big enough (in my eyes, at least), to warrant letting the application handle it.

What's your opinion on locking down the places where public files reside so sensitive files that aren't in that list of file extensions can still easily be denied, and non-sensitive files that are in that list can still be served?

**Comment by GawainLynch** [comment]
I don't think that Apache/Nginx bleed path details on error by default… PHP does, badly (embarrassingly so), and we wrap a lot to try and handle that… that is `<insert swear word here>`bad`</insert swear word here>`. We literally try to catch everything we can already (and there is/are still bleeds that we don't want), while making an effort to make this easy on people. 

That said, from an attack vector, if you've gotten far enough that paths are useful… you're an amateur if you to *need* to trigger an application error to *get* them. Skript Kiddiez are annoying and all, but I (personally) worry about pros.

Simply put. We document enough to get people going… under all imaginable circumstances. If we took a "sane approach" to our documentation, most shared hosting providers would fail to run Bolt, as a lot of them insist on FTP over SCP… as SCP is "insecure" (send your **password** over plain text, damn it!)… when you're dealing with brain-dead idiots like that (blog post security), that provide service to **our** users… well… we have to find a happy medium that works (just ask me privately about my initial reaction to the 777 thing… but, nonetheless, it's also valid in this case, for the same reasons).

Again… island… rum… we have some.

**Comment by Pinpickle** [comment]
The rum has made you wise. 

I have always wondered about the 777 thing... *Anyway*

I wasn't concerned so much about the technology bleeding path details, but the error. If you go to `app/config/config.yml` you'll get a different error document and a `403` rather than a `404` and a site-styled error document. You could probably use that technique to discover what extensions a user has installed - just go through the names of the config files under the `app/config/extensions/<file>.yml` until a `403` is returned. Not a major now, but if some extensions are found to have major security vulnerabilities, it could be an issue in the future.

I brought this up because in #3458, @bobdenotter expressed concerns about the user being able to discover information from error codes - I thought that this was relevant.

But I do think that locking files down by directory rather than file types would be a good idea. People store all sorts of weird files in publicly accessible places, and having the default only to allow public access to files in certain places, will help to prevent them from making mistakes in that area. It also allows me to be lazy, which I like doing.

**Comment by bobdenotter** [comment]
> Here's the mod rewrite code I've been using. Let me re-iterate that I am not great at htaccessing.

Neither am I. ^_^ 

If your solution works, i'm not against changing it. However, i think it'll be hard to get the right balance between 'secure' and 'pleasant to use'. For example: 

    RewriteCond %{ENV:BASEPATH} !^theme/([^/]+/assets

This means `theme/foo/assets/app.js` will be accessible, but `theme/foo/scripts/app.js`or `theme/foo/app.js`won't be, right? I can foresee a **lot** of people requiring support on that. Remember: most people don't manuals, changelogs or release notes.

**Comment by SahAssar** [comment]
I'm going to close this one due to inactivity, but I'm hoping that we can get a PR with a better htaccess... sometime... <sup>when someone has the time/willingness...</sup>

;)
