### ISSUE TITLE
Request simpler extension menu

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3461]
I think the extension menu item (under Extra) can be 'much' simpler. I always click the wrong item when I want to configure something or install a new extension. Why not replace Extra with Extensions?

The submenu now contains an item to view/install extensions and a second item for configuring extensions. But I can also choose view/install extensions to configure them. I think it is an improvement when these two items are combined in to one. On the overview page I can view information about different versions, a manual, a button to configure extensions or uninstall them. That is all a user needs. An addition could be a link to the extension page on the extension website.

**Comment by bobdenotter** [comment]
See also #1694 for a discussion on why it is the way it is now.

**Comment by gwbonline** [comment]
The current situation is better than is was before. But I think it can be a bit more simpler, like I described in my initial post. I agree that not every extension should have its own menu item. But renaming Extra with Extensions and discard the submenu items is much more intuitive than having two submenu items of which one has no other function than bringing the user to the configuration page of an extension.

**Comment by bobdenotter** [comment]
@gwbonline I think i agree with you. You can get to all the extension config files easily via the extensions screen itself.

**Comment by gwbonline** [comment]
What do the 'Enhancement' and 'RFC' labels mean? Will this request be implemented in the future?

**Comment by bobdenotter** [comment]
'RFC' means 'Request for comments', opening it up for debate, and 'enhancement' meaning we see it not as a bug, but we do see it as something that could be improved. 

Whether or not it actually gets done, and in what timeframe depends on a lot of factors: 

 - If a developer wants it, he/she can build it, PR it, and it's done
 - If some client needs it, we tend to prioritize it, because it pays the rent
 - If more people complain about it, it also gets prioritized
 - Otherwise, it'll remain in the queue, until one of the above happens. :-)

**Comment by SahAssar** [comment]
@bobdenotter You're on board then with removing the `Configure extensions` menu item then? Just so you're aware, that will collapse the submenu into a main menu item when there are no extensions with backend menu items installed per #3323, but I think that's the better way to do it anyway.

**Comment by GawainLynch** [comment]
@SahAssar removing the submenu and using the buttons on the extension page?

**Comment by SahAssar** [comment]
@GawainLynch Yeah, since it is a much nicer overview and has stuff like the readme's too.

**Comment by GawainLynch** [comment]
OK… Being UI/UX, I am stepping back then :wink:

**Comment by bobdenotter** [comment]
Ok, let's improve the UX on this! I'll suggest some improvements over the weekend!

**Comment by SahAssar** [comment]
Okay, @bobdenotter has okayed the change, so I'm tagging (and hopefully soon bagging) this :)
