### ISSUE TITLE
Getting Broken Image link in all the image fields related to content types in dashboard

### ISSUE THREAD

**Issue by salihkulangara** [bolt/bolt#3464]
I am Getting a broken image link in almost all image preview section in Bolt Dashboard, eg - when we reach Dashboard,  at Recently edited Pages section i  can see a broken image link only for the first time, but if we refresh the page image will back in place. This is happening every where inside dashboard,If I start to add a new page and add image, i will not get a preview, after saving and  refreshing will show up the image. Same thing happening in the front end , when I first visit a page broken image link, refreshing the page fixes the issue.

I am Using PHP 5.5 on latest AMPPS stack on windows, I have tried On Xampp also, but same issue. I have already enabled 'php_fileinfo'.  Using BOLT 2.1.6

**Comment by bobdenotter** [comment]
Try 'right-clicking' and 'open in a new tab' on a broken image, and see if it gives an error when the image is open in it's own tab. Should be somethign like this: `http://test.localhost/thumbs/54x41c/building-frame-garage-1599.jpg` Try changing the image widht and height in the URL, to trigger it to generate new ones, if needed.

Also make sure you have a 'thumbs' folder in the bolt folder, and chmod it to `777`. does it get filled with images if `save_files` is set to `true` in your global `config.yml`?

**Comment by bobdenotter** [comment]
So, did you figure out what was wrong?

**Comment by salihkulangara** [comment]
Actually It was the Issue with AMPPS, I don't know It is an issue or I am missing some configuration, I only see 'php_fileinfo' related config issue in SOF or other forums. I have enabled it, then also issue persists. Later I tried with Latest XAMPP stack, works with no Issue. I don't know what config I am missing In AMPPS's PHP.
