### ISSUE TITLE
"I forgot my password" button not working

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3477]
Sourcemap JavaScript error:
```
Uncaught TypeError: Cannot read property 'top' of undefinedd 
@ secmenu.js:61 j.init 
@ secmenu.js:34 d.run 
@ app.js:57 eb.Callbacks.k 
@ lib.min.js:24 eb.Callbacks.l.fireWith 
@ lib.min.js:24 eb.extend.ready 
@ lib.min.js:24 h 
@ lib.min.js:14
```

Ping @rarila, when you're well enough.

**Comment by rarila** [comment]
If you forget your password you deserve this! :stuck_out_tongue_winking_eye:

**Comment by GawainLynch** [comment]
I didn't, I just need it to pass new tests… that's how I found out. :grinning:

**Comment by rarila** [comment]
Then the test desrves it :stuck_out_tongue_closed_eyes:

**Comment by GawainLynch** [comment]
Just so I know where to find it, I'm going to write my password down here, it is: `K0ala$EatL3av3$`

**Comment by rarila** [comment]
Gone hacking…
