### ISSUE TITLE
Possible Bug - Enforce SSL 

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#3484]
Bolt Version: 2.1.4 p|1
Nginx: 1.8.0   

I've moved my site to https. In the config file I've enabled the corresponding ssl options:   
```yaml  
cookies_https_only: true  
enforce_ssl: true
```  

I also have non-www redirects and non-https redirects  
```  
server {
  listen [::]:80;
  listen 80;

  # listen on both hosts
  server_name site.com www.site.com;

  # and redirect to the https host (declared below)
  # avoiding http://www -> https://www -> https:// chain.
  return 301 https://site.com$request_uri;
}  
server {
  listen [::]:443 ssl spdy;
  listen 443 ssl spdy;

  # listen on the wrong host
  server_name www.site.com;

  include h5bp/directive-only/ssl.conf;

  # and redirect to the non-www host (declared below)
  return 301 https://site.com$request_uri;
}  
server {
  listen [::]:443 ssl spdy default_server;
  listen 443 ssl spdy;
  # The host name to respond to
  server_name site.com;  

 # other ssl settings and server blocks below  
}  
```  

This causes a redirect loop and sends a 302 response - [ ```"GET /bolt/login HTTP/1.1" 302``` ]. Setting enforce_ssl to false doesn't have this issue. So either I'm really dense the past few days or this setting if you set up your site with non www directs and ssl is not needed

**Comment by bobdenotter** [comment]
The `cookies_https_only: true` is no longer used. You don't need to set it. 

Other than that. I know nothing about nginx. Perhaps @GawainLynch can shine his light on this?

**Comment by bobdenotter** [comment]
Bumping @GawainLynch ;-)

**Comment by GawainLynch** [comment]
Bug… confirmed… Sorry, slipped off my radar with travel and stuff.

**Comment by GawainLynch** [comment]
Add to this, I am using a known good Nginx configuration.

**Comment by GawainLynch** [comment]
Derp…  It's an easy one and I can't read.

Quite simply you just need this parameter in your Nginx vhost config:

```
    fastcgi_param              HTTPS on;
```

**Comment by GawainLynch** [comment]
Just a further side note on a gotcha on this one that took me a few minutes to catch.  I was testing on my dev box and that has `HTTPS off` in the fastcgi_param file and that was overriding what I had in the vhost file, which initially lead me to think it was a Bolt bug.  

I didn't notice until I dumped the Request object and looked at the server parameters and saw `HTTPS off`… live and learn :grin:
