### ISSUE TITLE
[RFC] Custom Updates Script

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3486]
Sometimes, when changing the site around, we make changes that the DB integrity checker can't really get around. This could be generating intelligent defaults for new fields, or migrating fields in contenttypes to templatefields because you think that's a better place for them to belong. Stuff like that. This makes it easier to push updates to a website that's already in production, with less maintenance downtime.

The awesome Node.js CMS, [keystone](https://github.com/keystonejs/keystone), has a [good solution](http://keystonejs.com/docs/configuration/#updates) to this issue. Essentially, there is a folder full of update scripts. I'm proposing we'd do the same.

````
|- updates
  |- 0.0.1-add-admins.php
  |- 0.0.2-change-templatefields.php
````

What it does, is look at those scripts in the folder, and runs them in order indicated by the 3 number version string at the beginning (so *not* alphabetically). After that, it saves the name of the update to the database so that it doesn't get run more than once. I think the assumption is that on first install, the website is "up to date" so the update scripts should just be saved without being first run.

The format for the script could be similar to the `init.php` for an extension. You're given an `$app` variable and then you can go nuts (pun intended) with your updates.

**Comment by bobdenotter** [comment]
I've never bumped into this myself, but i can see how this might be useful.

**Comment by Pinpickle** [comment]
I'm starting to think that this should only be available to extensions - as that's where custom PHP code belongs.

**Comment by CarsonF** [comment]
@Pinpickle You're talking specifically about db schema scripts? I should bring up [phinx](https://github.com/robmorgan/phinx)

**Comment by Pinpickle** [comment]
@CarsonF I haven't seen that before, looks like a great tool to learn. I'm mainly talking about DB schema stuff, but it's not impossible that someone would want to update something else (config files, maybe?).

**Comment by SahAssar** [comment]
Moving this one to the forums as activity/interest here has been sparse. See here: https://discuss.bolt.cm/d/141-custom-db-updates-script-continuation-of-3486
