### ISSUE TITLE
[RFC] Proper centralized translation system

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#3490]
Hi, 
Transifex offers free account for Opensource projects and supports YAML file format.

As a french user, I'd help updating french translation using this platform :)

**Comment by CarsonF** [comment]
We are actually just found Transifex at my work too. We want to start using it as well. +1

**Comment by bobdenotter** [comment]
It was mentioned once by @rarila too, I believe.. We should definitely look into this! :-)

**Comment by bobdenotter** [comment]
Found this, some relevant light reading: http://opensource.com/business/15/5/interview-lukasz-jernas

**Comment by rarila** [comment]
@rarila doesn't remember mentioning it :-)
But I see some problems coming like more complexity, the YAML format is the one of Ruby, not of Silex, we not only have open source (= Bolt internal) translations, but also project specific proprietary (contenttypes), we need to register translators, need to integrate it in our workflow (needs a Amazon EC2 instance), get dependent on an external service, …

**Comment by SahAssar** [comment]
Is this some thing we still want/will do? Reading @rarila's last post it does not seem definite that it fits into the workflow all that well, but that was from a year ago so things might have changed.

**Comment by bobdenotter** [comment]
I think it's a valid thing to look into, still. Perhaps not Transifex
exactly, but in the near future, we will need _something_.

**Comment by CarsonF** [comment]
I'd rather hold off on this until we do the entire translation refactor. Which is probably a couple releases out.

**Comment by SahAssar** [comment]
Currently it seems like the idea is to go with translations via Crowdin. Anyway, if this is still wanted please reopen.

**Comment by GawainLynch** [comment]
Crowdin is almost certainly *not* the way to go… and we're still debating it.

@SahAssar could you do some awesome and pick the issue to track that on please (i.e. not sure if this one is/not the one).

**Comment by SahAssar** [comment]
Alright, this one is the tracking one for the system to use for translations. None of the other ones were open at the time I closed this (all other issues were about specific translation issues), so I'm reopening and renaming this.

**Comment by SahAssar** [comment]
Also, every translation issue should have been tagged with the translation label now,

**Comment by SahAssar** [comment]
#5042 is now merged into here, and has some good ideas of how handle this and what the actual issues are

**Comment by CarsonF** [comment]
@horus68 Why do you think Crowdin is better for Bolt? (Not saying it's not, just curious of your thoughts)

**Comment by SahAssar** [comment]
Closing since this has not been updated in a long time and some of this will change soon (with a translations refactor). Feel free to reopen if anyone disagrees.
