### ISSUE TITLE
[RFC] Email set up test button thing UI/UX

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3495]
This is meant as a follow-up to #3494.

Before I get hacking on something, what is the feeling about how we handle this in a UI/UX perspective?

Should we have a "Testing" page, or the like, or should we squeeze in a button somewhere semi-randomly?

**Comment by pygillier** [comment]
IMHO, a dedicated page would be the best : 

* More screen estate to display errors if necessary
* Display functional (sender name & email) and technical (relay name, account used if present) informations to user.

**Comment by GawainLynch** [comment]
Yes, thank you. My thought so far (and I suck at UI/UX) was something on the About page (backend), maybe a "Test my install" button. The route calls are async, so AJAX is OK from the start.

Further question, would this be OK to do in 2.3? There are some big changes queued…

**Comment by bobdenotter** [comment]
A logical place would be on "My profile", i think. 

> Further question, would this be OK to do in 2.3? There are some big changes queued…

Yes, agreed.

**Comment by GawainLynch** [comment]
I did think this at first, but quickly thought it a bad idea. If we're gong to "open" this door, we should probably do it in a way that allows other tests to be added, PHP modules, etc.

**Comment by pygillier** [comment]
Having a dedicated page listing all versions & modules and letting users test their setup (mail, image manipulation, etc) would be the best.

It would be also be helpful in case of incident or problem with core or plugin : the user would be able to copy/paste the informations given here.
