### ISSUE TITLE
Error in 'Extend'. "Malformed JSON response. Ensure no debugging or other code is being added to the response"

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3501]
See screenshot: 

![screenshot 2015-05-09 09 15 31](https://cloud.githubusercontent.com/assets/1833361/7549206/3dec90aa-f62c-11e4-8ead-045d79a501ad.png)

It's probably caused by a theme being flakey (My "Simone" theme), but I think Bolt should not break on this. 

@GawainLynch Is this something you can fix easily, or should I dig in?

**Comment by GawainLynch** [comment]
That *should* only occur if you don't get a JSON response from the controller… the theme itself shouldn't matter. There is something rather wrong to trigger that.

**Comment by bobdenotter** [comment]
It's my test setup, so i can "fix" it by just removing `composer.json` from extensions. Is this something we want to look into, or are we writing it off as a fluke?

**Comment by GawainLynch** [comment]
Nothing is a fluke… if there is something wrong, corner case or otherwise, it's good to track it down. Can you come up with a reproducible test case?

**Comment by bobdenotter** [comment]
Just install "simone", and it breaks for me. Perhaps related, during install i get this: 

![screenshot 2015-05-09 11 48 30](https://cloud.githubusercontent.com/assets/1833361/7549706/7223d2f6-f641-11e4-9f63-7612f9943b78.png)

**Comment by GDmac** [comment]
```php
ob_start();
// do stuff
// ...
$notices = ob_get_contents();
@ob_end_clean();      
```
add  { notices: $notices } to the json :-)

**Comment by GawainLynch** [comment]
I have found the root cause of the original problem… fixing it might be fun, I am trying to untangle what's changed.

**Comment by GawainLynch** [comment]
Oh, and PRed a fix for the second screenshot's problem
