### ISSUE TITLE
Changelog has not been updated

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#3511]
The changelog only goes up to 2.1.1 (for stable releases), whereas the current version is 2.1.8. Is there an updated list of fixes somewhere?

**Comment by bobdenotter** [comment]
Hi,

An up to date changelog for 2.1.x is kept in the `release/2.1` branch: https://github.com/bolt/bolt/blob/release/2.1/changelog.md

**Comment by bobdenotter** [comment]
And i've also updated the changelog in 'master' now: https://github.com/bolt/bolt/blob/master/changelog.md

**Comment by svivian** [comment]
Thanks! By the way, you have two sections for 2.1.8. Also both those and 2.1.7 have the same date.
