### ISSUE TITLE
Seems like StorageEvents::PRE_SAVE has no option to _modify_ content.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3512]
As pointed out by Jowy, on IRC.

See: https://github.com/bolt/bolt/blob/master/src/Storage.php#L362-L373

**Comment by GawainLynch** [comment]
Compltely incorrect. We even test this in the acceptance tests.

**Comment by GawainLynch** [comment]
https://github.com/bolt/bolt/blob/master/tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php#L121

**Comment by bobdenotter** [comment]
Yeah, Ross pointed this out to me as well. This is no issue, closing. 

![do not dumb here](https://cloud.githubusercontent.com/assets/1833361/7588877/fd691724-f8bf-11e4-80dc-3ec57e58fe5b.jpg)
