### ISSUE TITLE
HTML template fields are not visually updated after live edit

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3516]
But it looks like their inner text area is. Tested this in beta 3.

I think this is because the code [here](https://github.com/bolt/bolt/blob/master/app/src/js/modules/liveeditor.js#L197-L199) checks if there is a ckeditor instance with the field name - but ckeditor stores instances by ID. When there are no template fields, this doesn't make a difference, but template fields have different IDs to their name.

**Comment by bobdenotter** [comment]
Pinging @rarila Do you know how to fix this?

**Comment by rarila** [comment]
Probably … if someone can point me to some HTML template fields documentation, so that I can find out what they are for and how they are used :-)

**Comment by GawainLynch** [comment]
https://docs.bolt.cm/building-templates#template-specific-fields

**Comment by Pinpickle** [comment]
@rarila the fix is really simple. The code [here](https://github.com/bolt/bolt/blob/master/app/src/js/modules/liveeditor.js#L197-L199) (I've fixed the link now) simply needs to be changed from 

```
if (_.has(ckeditor.instances, fieldName)) {
    ckeditor.instances[fieldName].setData(fieldValue);
}
```

To

```js
var fieldId = field.attr('id');
if (_.has(ckeditor.instances, fieldId)) {
    ckeditor.instances[fieldId].setData(fieldValue);
}
```

Untested, but should work as long as every field has an ID.

**Comment by rarila** [comment]
@Pinpickle That will work for now but with repeating fields all inputs will lose their ids anyway (I have removed them from ``geolocation`` already)

Otherwise to make ``<textarea name="fieldname[]" …`` work with cke there has to changed quite some code later anyway, if it is possible at all. But I like to avoid numbered ids if possible…

**Comment by Pinpickle** [comment]
@rarila ah I didn't know that was going to be the case. So it would be Bolt's job to keep a `ckeditor.instances` like array that contains references to the ckeditors based on the field names?

On another note, if you're dropping IDs for the fields, how are we going to provide the `for` attribute for the labels to maintain easy accessibility for screen readers and the like?

**Comment by bobdenotter** [comment]
Ok, so should we do the fix as proposed by @Pinpickle for 2.2, and sort it oult for repeating fields later? Or do you have a beter suggestion, @rarila ?

**Comment by rarila** [comment]
@bobdenotter I would say fix it for now and lets see what 2.3 gets us.

**Comment by rarila** [comment]
@Pinpickle Would it be possible to add some of those template fields to showcase as example and for easier testing?

**Comment by rarila** [comment]
@Pinpickle Ah, sorry! Didn't noticed that they are already included in theme base-2014. And finally I even found out how activate them in the backend. You'll never stop learning :-)
