### ISSUE TITLE
Static assets aren't cache busted

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3517]
This becomes quite apparent with big updates like the 2.2 one and some things just don't work/look weird because the JS/CSS files from older version of Bolt are being served.

The tech savvy know just to do a hard refresh but for editors that isn't obvious, and it could be a long time before the browser fixes it without being told to do so.

We can fix this by appending fingerprints to all of the static assets that are hashes of the file. It's a little trickier with Twig (I ended up using a custom asset function), but definitely doable. [Grunt plugins](https://github.com/cbas/grunt-rev) exist for making these fingerprinted files.

**Comment by cdowdy** [comment]
< puts on my asset manager champion hat haha > this is one of the reasons I championed using assetic many months back [assetic cache busting](http://symfony.com/doc/current/reference/configuration/framework.html#ref-framework-assets-version)

**Comment by Pinpickle** [comment]
Symfony already has a solution, no surprises there. I'd be careful with that implementation, though - by default it uses query strings which can stop caching completely in some cases. You could use a different format, and then use some mod_rewrite magic to reroute `app.xxxxxx.js` to `app.js`.

**Comment by CarsonF** [comment]
@cdowdy What do you prefer for versioning?

**Comment by cdowdy** [comment]
Yeah I'm not a fan of query strings. I myself just use grunt and use a date pattern.  

The only issue I see with using a cache busting pattern server side is having to include it in the htaccess or the nginx conf but that's not to much. [Html5 boilerplate](https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess) has these easily available

**Comment by CarsonF** [comment]
Oh I see, vs versioning with filenames. Well requiring users to have certain web server configuration is not a solution IMO.

What was the reason against assetic? I haven't got into it myself, but that's only an issue of time for me. We could do a twig function instead that did some kind of regex logic to check for specific file. Same idea as htaccess rewrite but it doesn't require user config and it can be cached in twig.

**Comment by cdowdy** [comment]
It's not really drop in I don't think... I could be wrong though.  

It's probably the tech debt of incorporating it into bolt and dealing with the bugs that may crop up... 

Plus dealing with assets is hard haha. Like you've noticed. [Silex assetic](https://github.com/mheap/Silex-Assetic) package is ready for a composer include but there's lots of little hooks you have to set up. I haven't looked at incorporating it into bolt in a few months though I got sidetracked

**Comment by CarsonF** [comment]
I'm in favor of assetic with silex's SP, but I don't have time until after 2.3 probably to look at it. 

ping @rarila You have any thoughts since this is closest to your area?

**Comment by cdowdy** [comment]
O and if you're going to do assetic facing the user you have to also think about it's config options. How do you throw an error if the users doesn't have yui (java) installed on their server or some of the other plugins. It adds complexity which regular editors or shared servers might not offer

**Comment by CarsonF** [comment]
See that's where I was wondering if assetic is too complex. We can do the compiling in our repo we just need to dynamically reference the generated file.

**Comment by Pinpickle** [comment]
I think keep it simple. Use a Grunt plugin to rename the static files (and update references inside these files), and create a file manifest in a JSON file or something. A Twig function can read from that file and generate the correct reference for the templates.

[This Bolt extension](https://github.com/Brunty/gulprevbust) serves this exact function (but for the gulp-rev-all function).

**Comment by cdowdy** [comment]
@CarsonF yeah grunt-filerev or grunt templating like 

```javascript 
<%= grunt.template.today('dd-mm-yyyy') %> 
```  
Might be the best /easiest non breaking way to go

**Comment by rarila** [comment]
I'm also for k.i.s.s. principle. Most files will almost never change (images, fonts). And then it comes to the often changing ones (bolt/lib.js/css) having it in the filename will also solve our merging problem.

But I didn't have time to look into it.

**Comment by rarila** [comment]
After 15 minutes thinking …
- Changes should go into 2.3 as we are in beta already.
- Before doing changes in this area my long planned switch to postcss should be done first as this will change the workflow a bit (at least on the css side). Without investigating further there is https://github.com/borodean/postcss-assets#cachebuster
- To think about: stuff will work great with our code, but not with cke. There we probably have to version the folder.

**Comment by CarsonF** [comment]
So postcss doesn't handle JS?

**Comment by cdowdy** [comment]
@CarsonF 

> So postcss doesn't handle JS?

nope... strictly CSS

**Comment by CarsonF** [comment]
Why move to a solution that only solves half the problem?

**Comment by rarila** [comment]
It's called post**CSS** after all ;-)
It adds other cool stuff like autoprefixer and joins matching CSS media queries into a single statement. You could even replace scss if you want.

**Comment by rarila** [comment]
The move is because of above reasons

**Comment by cdowdy** [comment]
@rarila 
> It adds other cool stuff like autoprefixer and joins matching CSS media queries into a single statement..

This [Pleeease.io](http://pleeease.io/) does all that and already fits into your grunt/gulp/brunch/node et all workflow :-)

**Comment by rarila** [comment]
@cdowdy not really, looks like a standalone package, no grunt integration. See here for [postcss](https://github.com/postcss/postcss). It is really great stuff.

**Comment by cdowdy** [comment]
@rarila > not really, looks like a standalone package, no grunt integration. See here for postcss. It is really great stuff.

it's literally PostCSS as a grunt plugin using autoprefixer, px to rem, ie8 opacity filters, media query packing and a bunch of other postcss plugins. 
* [Grunt Pleease](https://github.com/danielhusar/grunt-pleeease)  

including [grunt-postcss](https://github.com/nDmitry/grunt-postcss) into your project would be no different than including grunt-pleeease. you have to include it in your gruntfile then set it up.

**Comment by rarila** [comment]
@cdowdy hmm, so if it's just a post-css with predefined set of plugins I would choose grunt-postcss where you have much more control over what plugins to use and even can add your own.

**Comment by cdowdy** [comment]
Ha OK. I was just saying use that since 

> stuff like autoprefixer and joins matching CSS media queries into a single statement. You could even replace scss if you want.  

This was the reason you wanted to move to postcss. This gave you all those reasons you listed, allows you to still use your own (it's grunt/node after all you just write it in the gruntfile), gives you possible css4 possibilities in your already written scss and keeps you from reworking all your already written scss variables, mixins et all to postcss compat mixins,  CSS vars etc and it keeps you from having your development backend from being a moving target for others who might want to pitch in. But maybe I'm missing something

**Comment by rarila** [comment]
While waiting for 2.3 let's see what we have now:

### Methods

**(A) Add a cachebuster to the querystring.**

``filename.ext?abcd → filename.ext``

:white_check_mark: No filenames have to be to changed.

:red_circle:  Won't work on every occasion (proxies) - but. eg. Sqid changed default behabior to cache query strings in 2008, so probably not that big problem nowadays anymore.

**(B) Serverside rewriting of URLs.**

``filename.abcd.ext → filename.ext``

:white_check_mark:  No filenames have to be changed.

:red_circle: Possible problems as some rewrite rules have to be added to the server configuration and even worse possibly have to be updated.

**(C) Add a cachebuster to the filename**

``filename.abcd.ext → filename.abcd.ext``

:white_check_mark: Always works (caching and busting).

:red_circle: Heavier implementation.

:red_circle: Possible orphan files after two PRs changing the same file.

### Exceptions

Some external assets have to be busted in another way (e.g. CKEditor). There we would have to change the foldername manually. Easiest would be CKEditor version followed by an internal counter signaling changes to the configuration of one version.

Localisation files also needs some special handling.

### Chachebuster

- Version.
- Date.
- Checksum (md5).

I would choose checksum here as version adds some manual handling and date isn't reliable.

---
Comments, ideas and other input welcome! :smile:

**Comment by bobdenotter** [comment]
I'd prefer option 1. Simplest, easy to implement. could be as simple as: `?v={{ app.version|md5 }}`.

**Comment by GawainLynch** [comment]
Or something as simple as [this](https://github.com/GawainLynch/bolt-extension-footprint/blob/master/Extension.php)

**Comment by GDmac** [comment]
+1 for method (A), simple. 
When using @GawainLynch' extension and a config option, option (B) can easily be facilitated.

**Comment by GawainLynch** [comment]
Can now be done with `{{ filename.js|cachehash }}`

Closing as part of a general issue clean up.
