### ISSUE TITLE
Bolt breaks if a datetime field is not filled correctly

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#3522]
If a contenttype uses datetimefields (i.e. even dates) and the fields are empty when an item is published, Bolt breaks.
The only solution I can think of is fill the field directly in the database.
IMHO a total breakdown of Bolt should not happen in such cases.

```
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("datetime1") to generate a URL for route "programmaitembinding".") in "_base/_listing.twig" at line 128.
 if (null !== $template) {
            try {
                $template->$block($context, $blocks);
            } catch (Twig_Error $e) {
                throw $e;
            } catch (Exception $e) {
                throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $template->getTemplateName(), $e);
            }
        } elseif (false !== $parent = $this->getParent($context)) {

```

**Comment by bobdenotter** [comment]
You - being a good developer - have obviously enabled `strict_variables: true` in your config.yml file. This means Bolt will protest about these things, as it should. 

On production sites, just revert it to `strict_variables: false`, and everything should be peachy.

**Comment by peterboorsma** [comment]
strict_variables is set false... As is debug. Bolt 2.1.8

**Comment by bobdenotter** [comment]
Also in `config_local.yml`? If so, then that's a bug?

**Comment by peterboorsma** [comment]
No 'strict_variables' overrides in config_local.yml

**Comment by rarila** [comment]
That shouldn't depend on strict or not. How exactly can I reproduce?

**Comment by xiaohutai** [comment]
Looks like a routing problem to me. The record wants to make a URL for `programmaitembinding`, but the datetime of said record is empty/blank and then explodes.

**Comment by peterboorsma** [comment]
@rarila It's a live website. I can make a temporary login if you want.

**Comment by peterboorsma** [comment]
@xiaohutai Yes it is. One solution can be stop using the datetime in the routing. But I really like it this way.

**Comment by rarila** [comment]
Ok, if it's a routing thing I'm out. Thought the problem was the datetime input.

**Comment by xiaohutai** [comment]
It's not just datetime, you'll get the error for every empty field that is added to the routing. The best way to fix this is to remove it temporarily from the path in `routing.yml`, then fix all the datetimes, In `contenttypes.yml`, you want to have a default value and/or `required: true`. Fixing it via database is also an option. Then when all content is correct, re-add the field to `routing.yml` again.

**Comment by xiaohutai** [comment]
Disregard that, in the `programmaitembinding` route in `routing.yml`: add a `'datetime1': '0000-00-00'` to the `defaults`.

**Comment by peterboorsma** [comment]
Tnx Xiao, that seems to work. 

programmaitembinding:
    path: /{contenttypeslug}/{slug}/{datetime1}
    defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'programmaitem', 'datetime1': '0000-00-00' }
    requirements:
        datetime1: '\d{4}-\d{2}-\d{2}'
    contenttype: programma
