### ISSUE TITLE
Do not display relationships where the record has not published status

### ISSUE THREAD

**Issue by romulo1984** [bolt/bolt#3525]
I know that to set the:
```twig
{% set relatedrecords = record.related() %}
```
will not have the unpublished records, but when I want to do something like:
```twig
{{ record.relation.posts|length }}
```
 it returns me the amount disregarding the status, and also returns records as a draft.

**Comment by rossriley** [comment]
Try: 
`{{ record.related('posts')|length }}`

**Comment by romulo1984** [comment]
Yes, it worked. Thanks.
