### ISSUE TITLE
Feature Request: Pagination page item-optionbox remembering.

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#3530]
OHAI.

-v
As a user of the bolt-backend I want to stay in focus.
-vv
When I am on page "2" of a paginated list of $contenttype and I publish a $contenttype, I want to stay on the same page after the redirect.

I'm at 2.1.8-pl1 on Firefox Dev @ 39.0a2 @ gentoo linux.

**Comment by bobdenotter** [comment]
Confirmed bug.

**Comment by bobdenotter** [comment]
Tentative fix in #3558

**Comment by bobdenotter** [comment]
Fixed, closing.

**Comment by bobdenotter** [comment]
Needs to be fixed for 2.3 as well.

**Comment by GawainLynch** [comment]
@bobdenotter can you confirm that today's current master behaves in a desired fashion. 

I am seeing what I believe to be the desired/requested behaviour, but don't want to assume that I have a clue today :grin:

**Comment by bobdenotter** [comment]
Nope, not resolved on current master. Sry. :-)
