### ISSUE TITLE
Blank frontend/backend after upgrade beta 2.2

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3535]
I installed 2.2 beta (I had 2.1.8) and something went wrong... The frontend and the backend are completely blank. There's also no source code available. I upgraded with ftp and did all the necessary checks. Upgrading never went wrong before. I emptied the cache and chmodded folders again. This didn't help.

**Comment by GawainLynch** [comment]
Curious, but is it on PHP 5.3?

**Comment by gwbonline** [comment]
Yes, 5.3.28

**Comment by GawainLynch** [comment]
@bobdenotter can you try the archive on 5.3, I don't have anything to test on any longer.

My initial suspicion was Guzzle, but both versions are present, valid, and passing unit tests.

**Comment by GawainLynch** [comment]
@gwbonline do you have access to the server error logs for this on install?  I would guess that there is a bigger clue in there if you can see them.

**Comment by gwbonline** [comment]
There are some errors, but they occurred also before the upgrade...

    [Sun May 17 03:28:50 2015] [warn] [client 79.171.81.119] mod_fcgid: stderr: PHP Warning:     is_dir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 51
[Sun May 17 03:28:50 2015] [warn] [client 79.171.81.119] mod_fcgid: stderr: PHP Warning: mkdir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 52
[Sun May 17 03:28:50 2015] [warn] [client 79.171.81.119] mod_fcgid: stderr: PHP Warning: ini_set(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 55

**Comment by GawainLynch** [comment]
Argh… OK, thank you I can see what's happening.  It's a third-party library.

**Comment by GawainLynch** [comment]
@gwbonline I have uploaded a [PHP 5.3 specific tarball](http://bolt.cm/distribution/bolt-2.2.0-beta-php5.3.tar.gz) that will fix this for now.

**Comment by gwbonline** [comment]
Thanks! That worked.

**Comment by andyjessop** [comment]
I don't know if this is still applicable - I had this issue and upgraded to PHP 5.4, which solved the problem.

**Comment by GawainLynch** [comment]
We've added a patch for the zip/tarball version of 2.2-beta to that build so that the unused library is patched.
