### ISSUE TITLE
Why use project root for public folder?

### ISSUE THREAD

**Issue by onlinesid** [bolt/bolt#3536]
I just tried bolt and I'm surprised to notice that bolt uses source root folder for public folder which is a security concern. What is the justification for it?

**Comment by GawainLynch** [comment]
That depends entirely on your install method.

If this is a concern for you, please install Bolt as a Composer project:
```
composer create-project bolt/composer-install <MYPROJECT> --prefer-dist
```

**Comment by onlinesid** [comment]
Thanks @GawainLynch ! :+1:
