### ISSUE TITLE
feature request: HR button in editor

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#3539]
In the future, ever, i'd like to have a `<hr />` button in the CK editor. I just learned that you need a special ckeditor-_plugin_ to get that button in the editor, so added here as a request for my wishlist.

**Comment by GawainLynch** [comment]
This sounds like a job for… Super @Rarila :rocket:

**Comment by bobdenotter** [comment]
Why would you want a button for Human Resources? :8ball:

**Comment by anketwokings** [comment]
Bob, go home, you're drunk. ;D

**Comment by rarila** [comment]
That is probably connected to the question how we will handle configuration of cke in the future discussed elsewhere already. Not an easy task. Adding every possible plugin probably isn't a good idea.

**Comment by GawainLynch** [comment]
This one do, Anke?
![](http://www.creatingchangenaturally.co.uk/wp-content/uploads/2013/05/HR-Dept-logo-HI-RES.jpg)

**Comment by Largo** [comment]
I need this :(

**Comment by peterboorsma** [comment]
Anke requested this in may. We need this. We really do. We're losing clients over it! Ehrm.. that's not true but we want it badly.

**Comment by bobdenotter** [comment]
Pull request is in the queue. #3967

**Comment by GawainLynch** [comment]
:koala: says "merged"
