### ISSUE TITLE
Feature request: alert when opening an item being edited by others

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#3542]
It happens too often: an editor starts editing an item but another editor is in there too. A warning would be in place: Another editor is editing this item.

Saves editors a lot of time and frustration...

**Comment by Largo** [comment]
I like this proposal. 
A way to implement it could be:
- If a field was changed send an ajax request which saves the warning to the database
- If record was saved, => delete the warning
- If a user is editing a record that was saved in the meantime => show an alert/ warning
  Especially if he tries to save it.
- If a user didn't save for an hour => delete the warning.

Please don't do locking like Joomla. Locks there never expire.

**Comment by jadwigo** [comment]
this sounds like a job for an extension

**Comment by SahAssar** [comment]
Since this has been proposed as an extension in #4670, and it does not seen to be regarded as "core functionality" I'm going to close this one, please continue discussion in #4670. 

If you feel this should be within the core functionality or just want to continue on here please reopen! :)
