### ISSUE TITLE
templatefields field not long enough

### ISSUE THREAD

**Issue by onedirective** [bolt/bolt#3545]
templatefields field is limited to 255 characters. So if you have added fields to a page that have data in them longer than 255 characters the data is truncated and it breaks the admin page. It will give an error 'Could not save Page.' under the Save Page button. Reloading any admin page or any page of the public website if you are still logged in returns a server error. 

Sample of the truncated partially saved data in the templatefields field:

{"lessons_intro":"This is a really super amazing long piece of text that is going to break the admin section as soon as I click on save. It will give an error that it can't save the page and then nothing will load in the admin section or on the main site 

Changing templatefields from a varchar(255) to a longtext should fix it.

**Comment by GawainLynch** [comment]
This should have been fixed in #3508. Could you be a champ and let us know if that commit is in your install, i.e. working as expected :grin:

**Comment by onedirective** [comment]
Sorry, I looked through before posting and still missed the previous post about this. My beta version was prior that fix. I'm all good now. Thank you!

**Comment by GawainLynch** [comment]
That's good news, and zero stress here!
