### ISSUE TITLE
Include source map files

### ISSUE THREAD

**Issue by Umbrielsama** [bolt/bolt#3546]
Current .gitignore excludes `*.map` files in line 31 ... which is a bad idea. The Bolt releases only include minified files which have references to the corresponding `*.map` files at the bottom - so I always get a 404 on customer's admin pages.

**Comment by GawainLynch** [comment]
Including them **is** a bad idea, they are massive and slow backend loading for everyone while only providing a benefit to a tiny group of core (?) developers.

The good news is that current master no longer, by default, generates the 404 as the default compile has sourcemaps turned off :grimacing: 

:+1: for @rarila on that one!

**Comment by Umbrielsama** [comment]
Nice one - did not notice that ... thank's to @rarila also from my end as well! :smile:

**Comment by GawainLynch** [comment]
Yeah, it was driving us all nuts… an nobody could blame the :koala: for that one!

**Comment by rarila** [comment]
No problem …
Btw., other than the :koala: I prefer :beer: over :leaves: 
:smile:

**Comment by bobdenotter** [comment]
> so I always get a 404 on customer's admin pages.

I like to call this Schrödinger's 404. It's _only_ there when looking at it, in your inspector. If the inspector is closed, your browser should not try to request the `.map` files.

**Comment by GawainLynch** [comment]
If I wasn't both flying and on an iPad, I'd so meme that one, @bobdenotter

**Comment by GawainLynch** [comment]
![lt16p](https://cloud.githubusercontent.com/assets/1427081/7749811/0e88a5a6-ffc8-11e4-8294-aead823b7d3f.jpg)
