### ISSUE TITLE
Request: entry delete button also on top op entry list

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3548]
When I want to delete a entry, for example the first one in a list of twenty entries, I have to go to the bottom of the entry list to click the delete button. Is it possible that the delete button also appears on top of the list when an entry is selected? That makes deleting entries as easy as deleting an entry that is at the bottom of the list (no scrolling needed).

**Comment by rarila** [comment]
Besides your point, when it's only one item to delete … isn't there a delete entry in the edit popdown menubutton?

**Comment by GawainLynch** [comment]
There is, but the location of that button, top or bottom, has always annoyed me from a UX perspective... We have our other action buttons on the right side bar, why not that one too?

**Comment by gwbonline** [comment]
That one entry was an example. When I select multiple entries on top of the entry list, I still have to scroll down to the bottom to delete them...

**Comment by rarila** [comment]
@GawainLynch When it annoys you, this is probably the best location to put it ;-)

@gwbonline As I said "Besides your point"… just wanted to show a workaround until this is fixed.

**Comment by gwbonline** [comment]
@rarila I appreciate that. Thanks!

**Comment by rarila** [comment]
@SahAssar Not as low hanging as one might think. Relatively easy for a standard listing …but as soon as you look at a grouped list things get ugly UX wise.

But I think I have some ideas … :)

**Comment by SahAssar** [comment]
@rarila: Well, labeling things based on ignorance is sorta my thing ;)
