### ISSUE TITLE
Multiple search contexts

### ISSUE THREAD

**Issue by Eiskis** [bolt/bolt#3552]
I have a site with more than one distinct section, public marketing site and a support-oriented help section. I want to keep these on the same installation so I can use the same content on both, share the theme and editors don't have to switch between different systems.

I want to provide search functionality for help section, which works great by setting the related content types searchable and others not in `contenttypes.yml`. However, I know that I want to expand on this by implementing search on other sections of the site, so basically I want to switch the pool of content types which is searchable.

The simplest way I could think of to achieve this is by simply allowing a way to explicitly filter by content type (and why not taxonomies too) when searching in addition to the search string. I could not find a way to do this currently. It would make sense to be able to send a search request to `?q=foo` for global search but also `?q=foo&qContenttypes=posts,pages` to only search for posts and pages.

Furthermore, I would like to be able to access search results via different templates. I have a site where I load the results via AJAX and show them in a dropdown below the search input, but I would love to have an indexable results page to show all results in (via another template). On this page I would want to show results that I don't show in the dropdown. Naturally, I could hide the excess results and their details in the dropdown with CSS but not searching for and outputting those would seem more intuitive, and result counts, pagination and sorting would probably work much better.

The latter might be a separate issue, and I could probably find a workaround with routing hacks or something. I would also like to access records via different templates, although I can probably cover my use cases with the [bolt/jsonaccess](https://github.com/bolt/jsonaccess) plugin by the looks of it.

Would love to see the roadmap up to date btw, and big thanks to the team for Bolt!

**Comment by GawainLynch** [comment]
> Would love to see the roadmap up to date btw, and big thanks to the team for Bolt!

The current [roadmap](https://github.com/bolt/bolt/wiki/Bolt-2.x-Roadmap) is up to date, we just need to figure out how to merge the old and new ones.

**Comment by JeromeBreizhtorm** [comment]
+1
Also interested in this feature

**Comment by rossriley** [comment]
I may have misunderstood you @Eiskis but there is already the ability to pass contenttype filters into the search via `routing.yml`

Would something like the following answer this use case:

```
search:
  path:               /search
  defaults:           { _controller: 'Bolt\Controllers\Frontend::search', contenttypes: ['pages'] }
  
supportsearch:
  path:               /supportsearch
  defaults:           { _controller: 'Bolt\Controllers\Frontend::search', contenttypes: ['support'] }
```

There you have two separate urls for search each one filtering on different contenttypes.

**Comment by Eiskis** [comment]
Hi, @rossriley 

Thanks for sharing, that's close to what I'm looking for. It's buried pretty deep though, and I guess more or less undocumented? Can I combine this with parameters somehow to create a version where the user would be able to select which content types to include (think of an "advanced search" page with checkboxes).

Having worked on the project I mentioned, I'm seeing myself using the search more and more and I'd really like to change the template I use for showing the results. As an example, I can list 4 different versions:

* Search results on an independent page (with advanced filtering options)
* Search results appearing inline in a dropdown on the homepage (AJAX)
* Quick search results in title bar (AJAX)
* Suggest articles inline when a user is typing a topic for support request (simple inline list of links, AJAX)

So yes the pool of content I'd like to search from might change (all by default, user-selectable in advanced search, only FAQs for the last case), but so might many other things. I realize this latter part might be a different discussion, and I haven't tried hacking around it using routing + custom variables (which is my current plan), but wanted to give you context.

The search is really useful and easy to use for building these things, so I'd like to see some advanced functionality for it as well.

**Comment by SahAssar** [comment]
Closing this one as it should be covered in #3894. Please reopen if needed/wanted. :)

While (as I have understood it) we will not get to all the search features requested above in 3.0, we will be a good bit on the way to a more flexible system. Some of the features/possibilities might be taken care of already. Hopefully if didn't speak any untruths, @rossriley.
