### ISSUE TITLE
[Accessibility/UX] Backend fields don't use for attributes on labels

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3555]
I haven't looked into how far this goes, but many fields in the backend don't have `for` attributes on their label element to specify which element it is related to. Some don't even have labels.

The [text field](https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fields/_text.twig) could easily have its label point towards its corresponding input field. The [file editor](https://github.com/bolt/bolt/blob/master/app/view/twig/editfile/editfile.twig) page doesn't have a label for its input - a hidden one could easily be added with the Bootstrap `.sr-only` class.

This is a pretty big accessibility concern as visually-impaired users with screen readers (and probably other scenarios) use form labels to identify what an input field is for.

This requires all input fields to have IDs, and I now know @rarila is working to remove IDs from input fields. If you're willing to accept a lower ease of access for some users, then this is okay. Personally, I think the backend should cater to all sorts of users. Bolt has definitely worked towards that in other areas, such as with its extensive language support.

The other option is to put input fields _inside_ their corresponding labels. But that makes styling complicated.

Not all labels can be tied to input elements (hidden textareas for example). I don't know what the spec thinks about the `for` attribute pointing towards an element that _isn't_ an input/textarea/select element. Such as a CKEditor instance.

This also comes with the added benefit of being able to click on a label, and automatically gaining focus on the input field.

**Comment by rarila** [comment]
As you already mentioned, no easy stuff.

The [spec](http://www.w3.org/TR/html-markup/label.html#label.attrs.for) says we have to address a "form control" – nothing to trick there. But as the textarea is hidden, also nothing to label here.

As you said, text field is an "easy" one (the label "Text" points to the text input)… As long as you don't have repeated fields. Then to be correct the former label "Text" would point to nowhere and every text input that belongs to that group has to have it's own label named something like "Text 1", "Text 2", … Of course we had to hide these labels and would have to rename the labels on reordering of the list …

Then there are the fields that consists of combined inputs like imagelist or geolocation. For them the "main label" would have to be without reference as before. The geolocation combo has labels for it's fields, imagelist hasn't, so there to be correct there would have added a "hidden" label named "Path to image" or something. Things again get really fun for repeated fields …

So to put things together, that what we name "label" at the moment is more something like a headline for the following inputfield, combo of input fields, repeated input fields or repeated combos of input fields.

Seeing it that way the only correct way to handle the situation is converting the ``label`` to a ``legend`` of the surounding ``fieldset``. The screenreader would then prepend the label name with the legend, e.g. a geolocation named "Location" would then have the latitude field "Location - Latitude" that is much better than a label "Location" pointing to nowhere and a latitude input named "latitude. I don't know if fieldsets could be nested for repeated fields resulting in "Location - Entry 2 - Latitude". That would be really descriptive then.

And now the caveat: I somehow doubt that can be [styled](http://thatemil.com/blog/2015/01/03/reset-your-fieldset/) in any usable way, especially for a responsive design. Exceptions like ``variant: inline`` even make things more complicated.

**Comment by Pinpickle** [comment]
Pwoah, this is a lot more complicated than I first thought.

I think your caveat about using `fieldset` is enough to not consider using it. However, can't fields be smart about their labels and create labels for sub-fields with their "master label" in mind. So a location field can generate `{{ label }} - Latitude` itself. As you said, things get more complex for repeated fields but that complicates a lot of things, so while any refactoring is going on for it, an option could be to allow for intelligent hidden labels?

**Comment by SahAssar** [comment]
@rarila This should be easier (I'm not saying easy, just easier) with buic, right?

Think it's worth doing? pros/cons?

**Comment by rarila** [comment]
@SahAssar buic does not help much there.

I think.I already added some labels here or there.

IMHO accessibility should be a working block in probably v4. But it would be good to have some support by a Bolt user who's a regular screenreader user to get things right. Just adding things because one might think it helps could make things worse. So valueable input on this is welcome!

**Comment by SahAssar** [comment]
Closing, stale for too long with no proper interest in fixing.

**Comment by GawainLynch** [comment]
Also what I will say, the people doing the v4 refactor have quite strong opinions on making things accessible so I would expect that the v4 backend will be a different ballgame in this regard anyway :wink:
