### ISSUE TITLE
BUG: Warning from PackageManager.php

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3575]
Warning: Creating default object from empty value in src/Composer/PackageManager.php on line 556

When using 2.1.8 I get the above warning when checking for extensions. This has been untested in the latest version.

**Comment by GawainLynch** [comment]
That shouldn't be throwing that error there, in the sense that is an error trap… So that's not good on our part… around here we blame the :koala: for those mistakes :grin: 

Having said that, you will hit that error trap if libcurl is not installed/enabled in PHP. Can you confirm/deny that it is working?

**Comment by tomntech** [comment]
I just ran a phpinfo. Looks like CURL is installed and enabled (attached screen capture).
![image](https://cloud.githubusercontent.com/assets/11805211/7808555/f5b67ffe-038b-11e5-8449-f892f1d46e9f.png)

There doesn't seem to be any .htaccess or php.ini settings which are blocking it either. What version are you expecting to be running? I can confirm this with my host if you like, getting a definitive answer.

**Comment by GawainLynch** [comment]
OK, well that's a very recent version of cURL so shouldn't be a problem… Hmm…

**Comment by tomntech** [comment]
Just come across 2 additional messages, also on the extensions view.

cURL library doesn't support TLS. Downgrading to HTTP.
Malformed JSON response. Ensure no debugging or other code is being added to the response

Completely missed these yesterday focusing on the message at the top and wondering where the extensions had disappeared too. Does the aforementioned provide any help/context?

**Comment by GawainLynch** [comment]
Two things:
* What version of PHP are you running?
* Can you try and update to Bolt 2.2 and let me know if you still see this

**Comment by GawainLynch** [comment]
For the benefit of those reading along, the problem is the system SSL/TLS Certificate Authority signing certificates being fatally out of date or not installed.

On Debian/RHEL/CentOS/Fedora it requires the `ca-certificates.noarch` package and this might not be enough for a host that has a custom build of cURL and expects the installed CA to be in a `/usr/local/` or similar location.

**Comment by lionel-bijaoui** [comment]
I just updated to 2.2.4 manually, and I got the same problem "Creating default object from empty value in \src\Composer\PackageManager.php on line 600"
No problem before the update.
I'm using it locally on windows with WampServer 2.5.

**Comment by quincykwende** [comment]
Hello, I am running Bolt v 2.2.4 on Windows and I have similar problem

"System cURL library doesn't support TLS, or the Certificate Authority setup has not been completed (cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html). See http://curl.haxx.se/docs/sslcerts.htmlfor more details. Downgrading to HTTP."

Also, when I try to install an extension it throws same error "Warning: Creating default object from empty value in C:\wamp\www\bolt\src\Composer\PackageManager.php on line 600"

**Comment by dadaxr** [comment]
you need to install localy trusted ssl certificate. The step listing to do that is here : http://www.zen-cart.com/showthread.php?213892-Curl-error-(60)-SSL-Certificate-problem-Unable-to-get-local-issuer-certificate

No more error warning after that :)

**Comment by AvaletDev** [comment]
dadaxr's fix worked for me too:)

**Comment by dizarter** [comment]
Thanks... A detailed explanation for XAMPP at the following link
http://stackoverflow.com/a/18590990/1184296

**Comment by 19th** [comment]
@dadaxr Thanks! Works for me on EasyPHP
