### ISSUE TITLE
Backend font doesn't have cyrillic letters, so it looks ugly

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3586]
![2015-05-28 13-11-34](https://cloud.githubusercontent.com/assets/2145313/7854433/38edc790-053b-11e5-82ff-5bed4493110b.png)
I suggest change Source Sans to any of sans-serif fonts from https://www.google.com/fonts , but with cyrillic support. I suggest Roboto or popular Open Sans. They both have nice unicode support.

**Comment by bobdenotter** [comment]
But, Roboto and Open Sans are _ugly_. Source Sans is _pretty_. :-/

**Comment by rarila** [comment]
Do we probobly use some old version?
["Adds Cyrillic and Greek support."](https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.010R-ro/1.065R-it)
… yeah, the fonts downloaded there are much bigger.

**Comment by bobdenotter** [comment]
Ah, excellent! Then I suggest we add those updated version, so we can support greek and cyrillic! :-)

**Comment by GawainLynch** [comment]
Wasn't there an option use use the Google Font service?

**Comment by bobdenotter** [comment]
Yes, but we do not want that. Bolt should work 'standalone', and not rely on external sources or CDN's. Both for privacy issues, and availability in regions like China. 

See also: http://fontfeed.com/archives/google-webfonts-the-spy-inside/

**Comment by GawainLynch** [comment]
Yes, I know the tin-foil-hat garbage. My question is rooted in "can I still use it?", not if it should be on by default.

**Comment by bobdenotter** [comment]
I'm not much of a conspiracy-in-everything-kinda-guy, but I actually think there are legitimate reasons not to use google stuff, in a product that's meant to be distributed. I mean, we use google fonts in our sites often as well, but i'd like to keep them outside of Bolt itself. So, yeah, we can/could use it, but i'd prefer to just include the fonts with Bolt itself.

**Comment by GawainLynch** [comment]
I am 100% in favour of having local options, but I am also 100% in favour of having CDN style options as well… and I thought we used to do it… just trying to figure out if it's still possible :grin:

**Comment by Boorj** [comment]
Could you just select one not ugly font except Source Sans ?
You can try that here : http://fonts4web.ru/ 
Instructions for non-russian users:
just press red button "КАТЕГОРИИ" and select option "Sans". There will be plenty of cyrillic fonts. 
![2015-05-28 18-17-50](https://cloud.githubusercontent.com/assets/2145313/7859878/4034a052-0566-11e5-9d43-06f18ab701b9.png)
On any font page you can try it by applying that to any webpage
![2015-05-28 18-21-42](https://cloud.githubusercontent.com/assets/2145313/7859923/90810e7e-0566-11e5-9201-5cf6fd89e22a.png)

**Comment by bobdenotter** [comment]
> Could you just select one not ugly font except Source Sans ?

Nope, sorry. We're using Source Sans Pro for all our things. It's part of our visual identity. We will not change this at a whim.

**Comment by bobdenotter** [comment]
I've been looking for the correct files to replace our current ones with, but I can't find a good version that comes with the `.woff` _and_ the `.woff2` files. :-s

**Comment by cdowdy** [comment]
> I've been looking for the correct files to replace our current ones with, but I can't find a good version that comes with the .woff and the .woff2 files. :-s

[Font Squirrel Webfont Genrerator](http://www.fontsquirrel.com/tools/webfont-generator)  

This is also why using a font service like google or any others is nice. They take care of the localization for you

**Comment by bobdenotter** [comment]
@cdowdy: Nope. You should never, ever, ever convert a font between two formats. It fucks up the kerning, hinting and ligatures. 

> This is also why using a font service like google or any others is nice. They take care of the localization for you

Yes, it is nice. As long as your internet connection is fast, and you're not in China or behind a corporate firewall.

**Comment by cdowdy** [comment]
> Nope. You should never, ever, ever convert a font between two formats. It fucks up the kerning, hinting and ligatures. 

I'll have to respectfully disagree. Font squirrel specifically has options to use Open Type Features and preserve those. You aren't going to lose anything. Furthermore Woff is a container that wraps around True Type or Open Type Font. It provides compression and woff2 even more so.  Open Type Is an extension of TTF font. The only time you'll lose kerning is if you the user in Font Squirrel select "remove kerning"  or use a crap conversion tool, or you the user choose a font without ligatures or designed to not need ligatures except for ‘ff’ and ‘ft' like [Source Sans is designed](http://blog.typekit.com/2012/08/02/source-sans-pro/)

**Comment by bobdenotter** [comment]
> I'll have to respectfully disagree. Font squirrel specifically has options to use Open Type Features and preserve those.

Hey @cdowdy, are you 100% sure of that? Last thing I heard was that they _still_ become slightly worse after conversion. Not unlike re-saving a jpg: It might look fine at first glance, but the re-encoding invariably deteriorates some of the details.

**Comment by bobdenotter** [comment]
Oh, ha, Because Font Squirrel is "smart", it recognises the font when i try to convert it, and gives me the cached old one from 2012. :-)

**Comment by cdowdy** [comment]
>Hey @cdowdy, are you 100% sure of that? Last thing I heard was that they still become slightly worse after conversion. Not unlike re-saving a jpg: It might look fine at first glance, but the re-encoding invariably deteriorates some of the details.  

yeah  

![fontsquirrel](https://cloud.githubusercontent.com/assets/5969974/8090161/591e9bea-0f7a-11e5-81be-530fae65b50d.png)  

and even so you aren't going to find a Source Sans font written as Woff, woff is a container format. Source Sans is an Open Type Font. Even Adobe converts it to Woff . If you're worried about font squirrel's quality then use [Adobe's latest release with woff format](https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.010R-ro/1.065R-it). For languages you have to select the appropriate subsetting "setting" or use Adobe's release.  



As for bad tools or bad settings. [OTF to Woff SHOULD be lossless](http://www.w3.org/TR/WOFF/)  
> The result of creating a WOFF file and then decoding this to regenerate an sfnt font MUST result in a final font that is bitwise-identical to the well-formed input font.. If the input font has defects or anomalies that make this impossible, the WOFF-generating tool SHOULD either reject the font or issue an appropriate warning that lossless round-trip conversion will not be possible.

**Comment by SahAssar** [comment]
Fixed by #4169!
