### ISSUE TITLE
Make new field: checkboxes group with select-multiple behaviour.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3589]
For checkboxes it's much easier to select several items for not advnanced users in comparsion with <select multiple="multiple" />. It's not so commonly used, so meeting this type of select may cause frustration, checkboxes are more intuitive.

**Comment by Boorj** [comment]
Can you please add *Multibox* - like several checkboxes that act like ```<select multiple/>```. Sometimes it's much easier if you don't have to hold ctrl to select several items. Sometimes webmaster's clients don't even know where the ctrl button is =) And i always afraid if i click while not holding ctrl.
It also could have option to select how many columns it will have on wide screens. It could be made with col-xs-12 col-md6, for example.

**Comment by bobdenotter** [comment]
In Bolt 2.3, the multi-select will use Select2, making multi-selects much easier. Closing this one for now.
