### ISSUE TITLE
Application breaks when not closing tags on title.

### ISSUE THREAD

**Issue by Pereida** [bolt/bolt#3590]
Hi guys, 

I've been playing with Bolt for a project and I noted that when creating a new Page, Entry or Showcase, the dashboard and the site breaks if the title has an opening hmtl tag such as `<script>` but it is not closed and there is no possibility to delete that Page/Entry/Showcase unless I delete directly from the DB.
![bug-dashboard](https://cloud.githubusercontent.com/assets/6182930/7860764/90e6a340-0554-11e5-9326-fd41cbc17db2.png)

**Comment by bobdenotter** [comment]
That looks derpy. I'm not sure how we can fix this properly, but we'll look into this.

**Comment by rarila** [comment]
@bobdenotter who said titles should never contain html?

**Comment by Pinpickle** [comment]
Possibly escape all output before putting it into the field with the `escape` twig filter?
