### ISSUE TITLE
Upgrading via SFTP is a very very slow process

### ISSUE THREAD

**Issue by tripdragon** [bolt/bolt#3603]
Testing a simple upgrade right now on a shared domain server so no shell access. Using Cyberduck they have a Synchronize feature that is assumed is the option to appease your merge request in the upgrading docs. However finding the timestamps takes a LOOOOOOng time. I could never see doing this for several sites that suddenly need some sort of urgent security fix in the future. Nor testing to see if I broke the site while trying to merge or if the connection goes down for even a moment starting the process all over again.

It would be great if you could separate out the Core files from the user generated files so a simple replace directory could be a faster smarter solution.

Still waiting as I type this to see if my upgrade to 2.2 beta works, so I might have some bug reports for that as well.

Thank you!

**Comment by GawainLynch** [comment]
I'm sorry… I might need coffee, and it is a Sunday morning so forgive me if I am missing something here, but I have no idea at all what you want us to do :question:

If you have SFTP access you probably have rsync access and that would solve part of the problem. But depending on what you're upgrading from/to would also dictate how big the file system delta was…

Which leaves me with "separate out the Core files from the user generated files" part. Everything already is. Depending on how you do your install changes the points where certain directories might be.

**Comment by bobdenotter** [comment]
I'm assuming this is done using the "regular .zip" distrubution, and not with any customized paths. 

@tripdragon: I don't know cyberduck, but you can just merge/overwrite everything from the `.zip` file to the server. All files with user data are not overwritten by that. Yes, it will take a while, but that's just the nature of FTP. We can't fix that. 
If you get SSH access, updating a Bolt site literally takes 15 seconds.

**Comment by GDmac** [comment]
FTP-ing many many lots of small files is always slow as each file is checked individually by cyberduck. On some servers where i have access to a control panel (directadmin) i upload a single zip and extract it on the server from the control panel. Rename the dirs (``src`` to archive or similar) and move stuff around with cyberduck, which is much faster.

**Comment by tripdragon** [comment]
Apologies for the mixed explanation. Ill explain it more in depth with wordpress and normal html as an example.

First though, so after more then an hour of using the Synchronize feature from Cyberduck the update finished. Loading the site it turned out broken its pointless to file the error since the process is unknown to track down to be useable. Again this is just ftp being ftp and the Synchronize mode being slow.

After that experiment I performed another. I dragged a new version of beta 2.2 into a new dir on the ftp. Copied the old database and theme folder into this new build and loaded the site. I then had to replace the config .yml files to get the site back in order and repair the database via the warning in Bolt's admin. The site works now from what I can tell.

Either process above is fiddly and not foolproof.

Now I'm just addressing these views from someone that uses Wordpress and Static site generators like Middleman app for small quick sites. If I had the server type that allowed command line access and tools of that type I would be using a different app most likely built in Rails or a Node/Sinatra variant and submitting capistrana or whatnot. But thats over kill for small sites.

Example for Wordpress. Their upgrade method contacts the server via the admin and background installs any update and its done within minutes. And for static site updates I just drag the build folder over and just deletes and its done.

The only request in this case for Bolt docs would be either segmenting the Apps core from the users themes and database and wherever the config .yml files are. So I can just drag one folder in that instead of checking for timestamps and merging which in practice is a very slow process, i could just directly overwrite the one core folder. Now deleting a folder of files and replacing is still a slow process via ftp but in practice is still much faster.

Again i'm only looking at this from the small user view thats familiar to faster upgrade styles from Wordpress or static, and was looking to hop on a new in-between platform such is Bolt cause Bolt will some day have a fun JSON api which will play really nice with some polymer stuff for small quick apps.

Ill test to see if what GDmac mentioned is a better solution. I could have been mistaken that all I need to replace is src. In that case you should put that in the docs as I would have done just that.

**Comment by bobdenotter** [comment]
Hi @tripdragon,

> The only request in this case for Bolt docs would be either segmenting the Apps core from the users themes and database and wherever the config .yml files are. So I can just drag one folder in that instead of checking for timestamps and merging which in practice is a very slow process, i could just directly overwrite the one core folder.

You _can_ do this. Simply upload _everything_ from the downloaded `.zip` archive to the server. All config is stored for example in `app/config/config.yml`, but this file is _not_ present in the `.zip` file at all. It's only generated on the webserver on installation. As long as you upload and pick "merge" instead of "replace", it should work just fine. No need to manually compare files and folders.

**Comment by aerth** [comment]
I think:
>"Yes, it will take a while, but that's just the nature of FTP. We can't fix that.
>If you get SSH access, updating a Bolt site literally takes 15 seconds." 
Pretty much sums it up :+1:

**Comment by gwbonline** [comment]
I always overwrite files when I do an upgrade. I use Filezilla for that. It doesn't have an option for merging. It does have the option 'Overwrite when source is newer'. Should I use that?

I also have a fast internet connection. But I never have a fifteen second upgrade... Does it make a difference when I use ssh instead of plain ftp access?

**Comment by Umbrielsama** [comment]
What about providing a diff-Update for new releases, including only files that were changed with that release!?

**Comment by aerth** [comment]
With SSH you can use commands such as git, tar, unzip, mv, chmod, etc. To quote https://docs.bolt.cm/updating

```
git pull
composer self-update
composer update
```

or cURL right over your current installation with

```
curl -O http://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
chmod -R 777 files/ app/database/ app/cache/ app/config/ theme/ extensions/
```

Maybe Bolt will push more developers to experience the benefits of shell access. :dancers:

**Comment by Umbrielsama** [comment]
Sure - but it is not always about what you, as a developer prefer, but about the possibilities of the customer's webspace. 80% of mine do not have SSH access for their websites. And you can't always tell them, they bought shit, when it already has been lot of work to convince them not to use Wordpress or TYPO3 for their small website.

- Just my 2 cents.

**Comment by GawainLynch** [comment]
Your point is very relevant, @Umbrielsama, and we work *very* hard to try to provide as much flexibility as we can with Bolt — git installs, archive installs, two types of Composer installs and several other methods that we don't advertise. :wink: 

I've had an updater in the works since before Bolt 2.0 was released, but the problems to solve are not particularly insignificant:
* We're not guaranteed to have write access to all the files we need to touch
* Rollback… "You broke my site you #$%^^@*$!!!!"
* Composer installs, vs archive installs, vs git installs, vs multisite installs, vs hand-crafted installs (yes, they're all out there in large numbers)
* Shared hosting providers do some weird #### with what functionality they'll allow and when, and we have to cope with that — we've run into ones that disable OpenSSL for PHP as "HTTP is safer".
* Core development time is focused at the moment on front line problems that we need to tackle this year before Symfony 3 is released

None of this is a reason that we're not going to do this, but it's a tiny need against a massive request list with limited developer time… PRs welcome :grin:

**Comment by bobdenotter** [comment]
@Umbrielsama I feel your pain! It's not an actual _fix_ for this problem, but what we often do is that we specify server requirements in our project proposals to clients. Things like: 

 - PHP > 5.4.16
 - Apache > 2.4 or recent Nginx
 - Mysql > 5.5
 - Access via SSH

And we note that extra time spent deploying a website on a server that doesn't meet the requirements will be billed to the client. And, my hourly ratre times four is _much_ more money than getting a small VPS, that has better performance as well. 

Finally, we often tell (prospective) clients that we will gladly _advise_ them on how to get proper webspace. If you tackle these things pro-actively, they usually don't see it as being stubborn or "that grumpy developer".

**Comment by tripdragon** [comment]
What GawainLynch just stated helps a lot to know the internal complicated matters. Would have been nice to read that before hand, and the others all speak logical sense on both sides. Some clients are just plain stuck on cheap hosts and you deal with it, wether you can bill more or not or swap them or not.

Anyway I found the many answers here I was looking for so I say thank you to all here instead of just giving me a technical way of saying "shut up".

Thank you!
