### ISSUE TITLE
WYSIWYG editor optimize out empty markups/markups with withspaces

### ISSUE THREAD

**Issue by MateuszKubuszok** [bolt/bolt#3615]
Font Awesome use some tricks like `<tag class="fa-icon fa-place"></tag>`. It uses CSS to add an icon in place of empty tag. However with WYSIWYG editor those icons are trimmed:

    <ul class="fa-ul">
    <li><span class="fa-li fa fa-info"></span> About me</li>
    <li><span class="fa-li fa fa-university"></span> My school</li>
    <li><span class="fa-li fa fa-map-marker"></span> Where I live</li>
    </ul>
            
When code above is pasted into source editing mode and then saved everything works as expected. However if I reload edition window or just turn wysiwyg mode on and off it is turned into something like this:

    <ul class="fa-ul">
        <li>About me</li>
        <li>My school</li>
        <li>Where I live</li>
    </ul>

and then the icons are gone.

So far I was able to overcome this with:

* preview page's source,
* copy and paste original tags into source mode,
* edit and save page in source mode without touching source.

But it is bothersome and its quite easy to forget about copying source first. I've found no setting allowing me to change that behavior and no other issue where it was mentioned.

I use Bolt. 2.1.6, my wysywyg config is:

    wysiwyg:
      images: true
      anchor: true
      tables: true
      fontcolor: true
      align: true        # Add 'align left', 'align right',etc.
      subsuper: true     # Add buttons for subscript and superscript, using <sub> and <sup>
      embed: true        # allows the user to insert embedded video's from Youtube, Vimeo, etc.
      underline: true    # add a button to underline text, using the <u>-tag.
      strike: true       # add a button to add stikethrough, using the <s>-tag.
      blockquote: true
      codesnippet: true
      specialchar: true  # adds a button to insert special chars like '€' or '™'.
      ck:
        allowedContent: true # If set to 'true', any elements and attributes are allowed in Wysiwg Elements
        autoParagraph: true # If set to 'true', any pasted content is wrapped in <p> tags for multiple line-breaks
        disableNativeSpellChecker: false # If set to 'true' it will stop browsers from underlining spelling mistakes
        # viewSourceRoles: [ 'admin', 'developer' ] # the roles which are allowed to use the [Source]-button.

**Comment by bobdenotter** [comment]
It's not a _real_ solution, but have you tried this: `<span class="fa-li fa fa-info">&nbsp;</span>` ?

**Comment by MateuszKubuszok** [comment]
Interestingly when I use the `<span class="fa-li fa fa-info">&nbsp;</span>` approach I can toggle source mode on/off.

However on full page reload issue is back. I can only guess that during save `&nbsp;` is turned into space and during WYSIWYG initial load empty tags/tags with only whitespaces are stripped.

**Comment by rarila** [comment]
@bobdenotter Did I say removing &nbsp; is a bad idea?

**Comment by bobdenotter** [comment]
@MateuszKubuszok And if you add the `allowNbsp` from the default config? https://github.com/bolt/bolt/blob/master/app/config/config.yml.dist#L295

@rarila

**Comment by MateuszKubuszok** [comment]
Changing `allowNbsp ` to `true` doesn't change anything. Is this settings even supported on stable? Cuz when I clicked *Save* while in source mode all `&nbsp;` changed into spaces anyway.

**Comment by bobdenotter** [comment]
@MateuszKubuszok Ah, no, it looks like it isn't. Bolt 2.2 will be released _very_ soon, and that version will have it.

**Comment by MateuszKubuszok** [comment]
@bobdenotter All, right then. I'll give it a shot once it's out. :)

**Comment by bobdenotter** [comment]
2.2 is out, so closing this issue. If this remains a problem for you, feel free to re-open. :-)
