### ISSUE TITLE
getTitle() is a bit broken on 2.2

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3616]
If there's no `title` field, it should still pick up the first text field. See this screenshot, which does have a `titel` field instead. 

![screen shot 2015-06-01 at 17 47 25](https://cloud.githubusercontent.com/assets/1833361/7916800/6581f86e-0886-11e5-99f7-d6fdc044f7a8.png)

**Comment by bobdenotter** [comment]
Nevermind. Not a bug.

**Comment by GawainLynch** [comment]
@bobdenotter… look… over there… :smile_cat:
