### ISSUE TITLE
where is the database?

### ISSUE THREAD

**Issue by ariebl** [bolt/bolt#3617]
I have installed first time the bolt and I don't find where is the database

**Comment by CarsonF** [comment]
By default there is a sqlite database created at `app/database/bolt.db`. 

PS: SQLite is not recommended for production and should be swapped with a MySQL or Postgres instance.

https://docs.bolt.cm/installation#configuring-database

**Comment by ariebl** [comment]
thank you Carson very much for the fast and complete answer
Arie
