### ISSUE TITLE
Broken link on `Contributing to Bolt code or docs page`, Bolt website

### ISSUE THREAD

**Issue by dublutz** [bolt/bolt#3618]
The extensions link on `Contributing to Bolt code or docs page` is leading to 404 page. 
https://docs.bolt.cm/internals/contributing

**Comment by Umbrielsama** [comment]
You also have a wrong link, Bolt Docs issues are here: https://github.com/bolt/docs/issues

**Comment by GawainLynch** [comment]
Fixed by https://github.com/bolt/docs/pull/225
