### ISSUE TITLE
Cannot use imageinfo on an image in an imagelist

### ISSUE THREAD

**Issue by rlowry** [bolt/bolt#3621]
It would be very useful if the imageinfo tag could be used with the images in an imagelist. Is this possible?

At the moment i'm using the thumbnail generator to get the images for my gallery. 

    {% setcontent carousel = 'carousel/home' %}

    {% for image in carousel.images %}
        <li class="galleryImage"><img src="{{ thumbnail(image.filename, width, height) }}"></li>
    {% endfor %}

However I'm currently implementing a PhotoSwipe gallery with which I intend to display the original images. It requires the height and width attributes of each original image before it is initialized.

**Comment by rlowry** [comment]
Please close - I was been an idiot, i just needed to pass imageinfo the filename of the images in the imagelist.

**Comment by bobdenotter** [comment]
rlowry: Closing! Glad you figured it out. :-D

**Comment by GawainLynch** [comment]
@rlowry welcome to the club, usually I am the one around here with the most expertise in doing stupid stuff… stupidly! As @bobdenotter we're glad it's sorted for you :+1:
