### ISSUE TITLE
Extensions HTTPS fallback not working

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3628]
When running bolt on a server without valid CA certs for cURL, the extensions page fails to load extensions. The following error is currently produced:

Testing connection to extension server failed: cURL error 60: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
https://extensions.bolt.cm/ is unreachable.

The check should fallback to http so that hosts without a valid cert can still use extensions.

**Comment by bobdenotter** [comment]
Fixed in the PR's mentioned above.
