### ISSUE TITLE
After update to 2.2.0: Twig_Error_Syntax

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#3636]
After the update from  bolt/bolt (v2.2.0-beta3) to bolt/bolt (v2.2.0) I experience these errors:

cms.dev/bolt:
> Twig_Error_Syntax
> The function "render" does not exist in "dashboard/dashboard.twig" at line 40

cms.dev:
> http://cms.dev/_profiler/wdt/fc477f 500 (Internal Server Error)

http://cms.dev/_profiler/wdt/fc477f
> Twig_Error_Syntax
> The function "render" does not exist in "@BoltProfiler/toolbar/config.html.twig" at line 1

I don't know why. Itried to delete vendor file, cleared cache and updated DB.

dashboard/dashboard.twig
```
{% include 'dashboard/_aside.twig' %}
```

@BoltProfiler/toolbar/config.html.twig
```
{% extends '@WebProfiler/Profiler/layout.html.twig' %}
```

Bolt is installed as composer project.

**Comment by GawainLynch** [comment]
That is due to Silex 1.3 that was released last night… there is a fix already in `release/2.2` that will be tagged as 2.2.1 very shortly. :grin:

**Comment by sbani** [comment]
Thanks mate. 
PS: Crazy fast response

![giphy](https://cloud.githubusercontent.com/assets/3541652/8005297/bffe713c-0b88-11e5-801c-02ab822e349a.gif)

**Comment by GawainLynch** [comment]
Hehe… it was what I woke up to this morning, so was "all over it" :+1:
