### ISSUE TITLE
Error on upgrade

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#3652]
I try to upgrade with:
curl -O http://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
but i receive an
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive

With the version of this morning, it's works !

**Comment by GawainLynch** [comment]
Works here, just this second… are you sure that cURL didn't have an connection problem during the download?

**Comment by mgageo** [comment]
no return code from curl, but it's good now

Thanks for your response

**Comment by GawainLynch** [comment]
No stress :grin:
