### ISSUE TITLE
Is there something like Fancybox for Bolt?

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3654]
I have an imagelist and I want to show these images in a Fancybox way. Didn't Bolt have this functionality? I can't find it anymore...

**Comment by GawainLynch** [comment]
We removed Fancybox due to licencing problems and now include [Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/) as a replacement.

**Comment by bobdenotter** [comment]
@gwbonline it's used in the 'base-2014' theme that comes with bolt. Check the code in there for an example.

**Comment by bobdenotter** [comment]
Closing this one! Let us know if you need further help with this. ^_^

**Comment by gwbonline** [comment]
I understand it is used in the default theme. I was searching for the script setup. Where is this stored? I can't find it in the template itself.
