### ISSUE TITLE
contenttype/slug as path in menu.yml -> menuitem isn't populated with data from record

### ISSUE THREAD

**Issue by hartigdan** [bolt/bolt#3655]
Hey everyone,

i ran into following problem: I use routings for single record overrides (as described in https://docs.bolt.cm/templates-routes)

For example (routing.yml):
```
mypagebinding:
    path: /some/path
    defaults:
        _controller: Bolt\Controllers\Frontend::record
        contenttypeslug: page
        slug: mypage
    recordslug:     page/mypage
```
Now i would expect that if i set the 'path' attribute for some menu item to 'page/mypage', that the link in the resulting record has the value, that i specified in my routing (i.e. '/some/path'). I think this would be more consistent, as all generated links for a content-type behave like this (e.g. in a listing of pages).

**Comment by hartigdan** [comment]
I found out, what's the problem here.

in `src/Helpers/MenuBuilder.php` the Method `populateItemFromRecord(array $item, $path)` is used to fill the menu item with the data from the corresponding record. Unfortunately the method's parameter `$item` isn't defined as reference, so the item isn't filled within the callers scope.

There are two possible solutions:
- either change the param to be a reference,
- or (as the item is being returned by the method), assign the return value to the item variable within the `resolvePathToContent` method

**Comment by hartigdan** [comment]
Well, there's another Bug within `populateItemFromRecord(array $item, $path)`: `$item['label']` and `$item['title']` aren't being filled with the corresponding content's values.

```php
...
if (empty($item['label'])) {
    $item['label'] = !empty($content->values['title']) ?: '';
}

if (empty($item['title'])) {
    $item['title'] = !empty($content->values['subtitle']) ?: '';
}
...
```

should be:

```php
...
if (empty($item['label'])) {
    $item['label'] = !empty($content->values['title']) ? $content->values['title'] : '';
}

if (empty($item['title'])) {
    $item['title'] = !empty($content->values['subtitle']) ? $content->values['subtitle'] : '';
}
...
```

**Comment by sbani** [comment]
```php
$item['label'] = !empty($content->values['title']) ?: '';
```
and 
``` php
$item['label'] = !empty($content->values['title']) ? $content->values['title'] : '';
```
is the same.

**Comment by hartigdan** [comment]
As PHP.net says:

```
The expression (expr1) ? (expr2) : (expr3) evaluates to expr2 if expr1 evaluates to TRUE, and expr3 if expr1 evaluates to FALSE.
Since PHP 5.3, it is possible to leave out the middle part of the ternary operator. Expression expr1 ?: expr3 returns expr1 if expr1 evaluates to TRUE, and expr3 otherwise.
```

In our case, expr1 is `"!empty($content->values['title'])"`, so if `"$content->values['title']"` isn't empty, the whole expression will evaluate to `"TRUE"` and the Menu shows `"1"` instead of the content's title.

**Comment by GawainLynch** [comment]
Yeah, I saw that one the other day and wondered… I think I was to blame as I was giving advice to the contributor building that functionality and missed the final version… then didn't have time to double check/test when I saw it recently… around here, we blame the :koala:  for that.

If you would like your "name on the scoreboard" please feel very free to submit a PR, failing that we'll get to is soon(ish).

**Comment by hartigdan** [comment]
I'm fine with it, if this bug gets assigned to someone who works on Bolt not only since two days. No need for my name to be on the scoreboard ;) Maybe i'll contribute to this very nice project when i'm more familiar with its implementation. Cheers!

**Comment by sbani** [comment]
Thank you @hartigdan and sry again for my wrong answer (which I deleted before).
I fixed the easy stuff.

Perhaps I will add a unit test for this one later

**Comment by GawainLynch** [comment]
> Perhaps I will add a unit test for this one later

Yes please! :grin:

**Comment by bobdenotter** [comment]
@hartigdan Both parts of the problem you described should be fixed now!
