### ISSUE TITLE
Drag'n'drop order problem on overview pages

### ISSUE THREAD

**Issue by dipsy** [bolt/bolt#3658]
Taxonomy as grouping.
When I try reorder in middle - my mouse is freeze, but window scrolling.. see video below
https://www.youtube.com/watch?v=OclsjwMNBFE

**Comment by bobdenotter** [comment]
Hi, 

The browser suggests you can drag'n'drop these to re-order them, but this functionality is not implemented yet. It'll come in a version in the near future.

**Comment by SahAssar** [comment]
Merging into #2958, please feel  free to reopen if I'm wrong
