### ISSUE TITLE
[REGRESSION] Parsing of YAML fails now indents are four spaces rather than two.

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#3667]
To reproduce try to run the following nut command:

`./app/nut config:get extensions/stability`

It will fail where the indentation to the second level is anything other than two spaces.

The culprit is this method in YAMLUpdater.php:

```
private function find($keypart, $indent = 0)
    {
        while ($this->pointer <= $this->lines) {
            $needle = substr('                                      ', 0, 2 * $indent) . $keypart . ':';
            if (isset($this->yaml[$this->pointer]) && strpos($this->yaml[$this->pointer], $needle) === 0) {
                return $this->pointer;
            }
            $this->pointer++;
        }

        // Pointer is past end of file.
        return false;
    }
```
The indent is multiplied by two meaning that it will break on anything other than an indent level of 2.

The YAML spec allows any number of spaces from at least 1 upwards so we need to think of a way to re-engineer this.

This affects all versions *after* 2.1.9.

**Comment by bobdenotter** [comment]
This looks like code I wrote! :-D

**Comment by rarila** [comment]
Not nice anyway

```php
$needle = substr('                                      ', 0, 2 * $indent)…
```
should have been more like
```php
$needle = str_repeat(' ', 2 * $indent)…
```
Must have been late or beer was out ;-)

**Comment by rossriley** [comment]
Beer isn't helping so far...

Have we tried parsing the file via Symfony\Yaml and returning / rewriting the file or was there a reason this method was rejected?

**Comment by GawainLynch** [comment]
I had a small stab at that when I last did a pass on that class… and backed off really quickly. What gets tricky is preserving comments and YAML layout.

**Comment by rossriley** [comment]
Ha. I am now in the same place.

**Comment by bobdenotter** [comment]
Fixed by Ross..
