### ISSUE TITLE
Routing requirements are not regex anymore (BC-break)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3669]
e.g. doesn't support regex anymore
```php
// https://github.com/bolt/bolt/blob/release/2.2/app/config/routing.yml.dist#L69
#     requirements:
#         slug: '[a-z0-9-_]+'
```

**Comment by GDmac** [comment]
i wonder when config has parsed and cached the routing.yml, if that is a suited time to resolve all callbacks and controllers. Currently everything is done at runtime, for every page-hit the whole guacamole is prepared. Is it a viable option to move this to (yaml) compile time, to shave of miliseconds?

**Comment by bobdenotter** [comment]
Take a look at this screenshot: 

![screen_shot_2015-06-12_at_09_39_17](https://cloud.githubusercontent.com/assets/1833361/8125619/6be4b7e6-10e7-11e5-9ce3-bae859d2dfd2.png)

You'll see that the time spent doing 'getContent' calls and rendering Twig templates is orders of magnitude longer than parsing the routes.In fact, i'd go as far as to say that the time for routes is insignificant in this. If we're going to optimize through better caching, it should be done in those two areas.

**Comment by GDmac** [comment]
:+1:

**Comment by sbani** [comment]
![1441](https://cloud.githubusercontent.com/assets/3541652/8126546/9ad364d2-10ef-11e5-9baf-7ee7f479659f.gif)

**Comment by GDmac** [comment]
Here i added some stopwatches to twigExtension (sorry for the deviation from the regex topic)
![bolt-twig-stopwatch](https://cloud.githubusercontent.com/assets/156334/8128577/b042f9d4-1100-11e5-9f31-5385ee78fd62.png)

**Comment by GDmac** [comment]
Currently, what is holding back this bug, is that it cannot easily (without bc break) be determined if a requirement string is a "[regex]" or a "class:method". Any thoughts on an approach to tackle this?

**Comment by GawainLynch** [comment]
The biggest thing is that @CarsonF is away this week.

**Comment by GDmac** [comment]
Research: ConfigurableBase.php Method addRoute()
```php
foreach ($config['requirements'] ?: [] as $variable => $callback) {
  $callback = $this->callbackResolver->resolveCallback($callback);
 $route->assert($variable, call_user_func($callback));
}
```
it assumes every requirement is a callback, but, if resolveCallback is false, it's probably a regex…. 
so, then not overwrite $callback with ReolveCallbak() but ``assert($variable, $regex) // $callback``
(not tested, yet)

**Comment by GDmac** [comment]
Tested the above, and it works.

**Comment by CarsonF** [comment]
A valid callback does not have to be an array. it could be a string too. i.e. `Foo::bar` (called statically)

**Comment by GDmac** [comment]
Have you tested it? Because it works :-) 
Both callback resolvers isvalid() method check for those. (e.g. bolt/callbackresolver tests for double "::" and silex/callbackresolver tests for single ":") In the end resolveCallback() either returns 
(A) a callable array (B) throws invalid service exception or (C) returns the regex string

i would advise against having a need for ":" in a url requirement anyway.

**Comment by CarsonF** [comment]
@GDmac Does that PR work for you?
