### ISSUE TITLE
As a content editor, I would like an easier mechanism of adding records to the menu

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3672]
Customer feedback: Adding items to a menu is a difficult, non intuitive, task. It would be great if a content type could have an optional field whereby you choose if the record will appear in the menu and if so where.

This wouldn't replace the existing mechanism of editing the menu, just provide a more intuitive interface which is accessible at the time you need it.

**Comment by sbani** [comment]
Is this what you're searching for https://extensions.bolt.cm/view/d49af7c7-7b34-4396-b436-2f63f4747a7d ?

**Comment by tomntech** [comment]
Sorry, possibly a little vague in the initial description. The requirement was to be able to add the record to the menu whilst adding/editing the record, from the same interface. 

The extension you noted is already implemented but the bit missing is being able to edit the menu position on the record itself.

**Comment by rossriley** [comment]
I guess this would need to form part of a UI overhaul for Menu handling, there was some talk a while ago about making the menu-editor extension above part of the core, if so then a feature where you could attach a piece of content to a menu, perhaps on the meta-tab would make sense.

**Comment by tomntech** [comment]
Adding it alongside the Published Status section of the meta tab wouldn't be a bad call. Alternatively adding two extra fields to the Title. 

1. A checkbox "Appears in Menu"
2. A drop down that shows menus and allows you to select which menu and where.

**Comment by SahAssar** [comment]
Closing this since it would probably be better as an extension than in bolt core. Menu handling is quite barebones in bolt core, and it's sorta looking like it will stay that way for a while. It could be made into a fieldtype in an extension, which uses the postSave event for adding to the menu. 

@tomntech: If you feel this should be in bolt core and not in an extension please feel free to reopen :)
