### ISSUE TITLE
unit test: cachetest fails (can write mkdir /foo/bar/baz)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3677]
The unittest for cachetest fails on macbook because
https://github.com/bolt/bolt/blob/master/tests/phpunit/unit/Cache/CacheTest.php#L95
can write to /foo/bar/baz 
:-/

I have made a workaround but am unsure if this is a good solution:
```php
    // Windows can achieve both of these tests therefore it is meaningless there

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testNonExistingDirCantBeCreated()
    {
        $dummyfile = $this->workspace.'/foo';
        file_put_contents($dummyfile, "some text");

        if (strtoupper(substr(PHP_OS, 0, 3) == 'WIN')) {
            throw new \InvalidArgumentException('Win can');
        } else {
            $newCache = new Cache($this->workspace."/foo/bar/baz", $this->getApp());
        }

        unlink($dummyfile);
    }
```

**Comment by GawainLynch** [comment]
Um… `testNonExistingDirCantBeCreated` === Test that a **non existing** directory **can't** be created.

Don't ever ever ever ever ever run unit tests as root… ever :grin:

**Comment by GDmac** [comment]
On macbook, in terminal: ``cd /`` and ``mkdir foo`` will make the foo dir in root.
Running phpunit as user WILL make the /foo/bar/baz dir !
(ps. the cache class uses mkdir(path, mode, recursive==true)

**Comment by GawainLynch** [comment]
Then you've potentially added your user account as an "admin" group.
