### ISSUE TITLE
As a web admin, I have been having issues installing extensions.

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3679]
When installing some extensions, most recently https://extensions.bolt.cm/view/cd592dab-788f-11e4-866c-43d66b93a270 and https://extensions.bolt.cm/view/d49af7c7-7b34-4396-b436-2f63f4747a7d, the install doesn't seem to progress to completion. After selecting a version to install the . . . .  progress bar appears and continues to run without completing. Refreshing the page sometimes solves this problem, sometimes you are required to install the extension manually.

Tested on a local web server running under MAMP Pro and on a hosting provider.

**Comment by SahAssar** [comment]
Closing as part of a cleanup, if you are still having the issue in current versions feel free to reopen :)
