### ISSUE TITLE
E-mail Typo in new user message

### ISSUE THREAD

**Issue by JustinDDavis** [bolt/bolt#3687]
There is a typo in "app/view/twig/email/firstuser.twig". The word "received" is misspelled "recived".

**Comment by GawainLynch** [comment]
I'm just glad it was a dropped 'e' and not the 'i' and 'e' the wrong way around… Either way, I am blaming the :koala: 

Thanks for pointing it out, @JustinDDavis

**Comment by JustinDDavis** [comment]
Glad to help! :smile:
