### ISSUE TITLE
"Try Bolt" feature on bolt.cm crashes when logging in to admin area

### ISSUE THREAD

**Issue by use** [bolt/bolt#3690]
The admin login screen works correctly.  I enter the correct username/password, then submit the login form, and see this:

![image](https://cloud.githubusercontent.com/assets/94230/8151588/40dcdec2-12c5-11e5-82e3-6993a8378130.png)

**Comment by GawainLynch** [comment]
Ah, cool, thank you… This is Silex 1.3 breakage… ping @rossriley

**Comment by CarsonF** [comment]
Gawain you already fixed this and backported it. It was the http fragment
SP. The PR with the big flashing lights gif

**Comment by GawainLynch** [comment]
@CarsonF yes, for Bolt itself, but the try.bolt.cm site itself needs to be updated with said fixes.

**Comment by CarsonF** [comment]
Derp. Tired.

**Comment by rossriley** [comment]
Yes, my fault... the YAML updater broke stuff and I haven't got to updating yet.

I'll get on it.

**Comment by rossriley** [comment]
All fixed. 2.2.3 is installed now.
