### ISSUE TITLE
[RFC] Refactor Repository class

### ISSUE THREAD

**Issue by Atriedes** [bolt/bolt#3701]
I see there are some code duplication in Repository class

for example for search query (find)

https://github.com/bolt/bolt/blob/master/src/Storage/Repository.php#L72-L77
https://github.com/bolt/bolt/blob/master/src/Storage/Repository.php#L94-L100
https://github.com/bolt/bolt/blob/master/src/Storage/Repository.php#L114-L120

I think it needs to be extracted to new method maybe 'execute' method. So it can reduce code duplication and implement doctrine query caching more easier

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

Please see @rossriley on IRC for further discussion on this :+1:
