### ISSUE TITLE
Bolt 1.6.12 - Upload never finishes!!!!

### ISSUE THREAD

**Issue by adneto** [bolt/bolt#3711]
Hello from Brazil!
I'm trying to upload images within a website with Bolt 1.6.12 and never ends!
In my localhost it does not happens.
The folder "files" is by permission 777
I have changed the hosting and still the same problem!

Please help me!

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

Bolt 1.x is no longer supported. But I would check the developer tools console as there is probably a JavaScript error occurring :+1:
