### ISSUE TITLE
MassEditor - edit several records' fields simultaneously

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3714]
I want to select several db entries and change several fields at one time.
I see it in 2 ways.
### 1. list of records

![2015-06-19 13-45-51](https://cloud.githubusercontent.com/assets/2145313/8249179/722aa924-1689-11e5-88a6-8fda536c034b.png)
A list of records with checkboxes. When you select some records, you press "edit" and then editor pane or window is open. In the window there' a list of editable fields, each one has a checkbox that points if corresponding field should be overwritten with save, that checkbox could be set manually or on first edit of that field.
![2015-06-19 13-43-17](https://cloud.githubusercontent.com/assets/2145313/8249158/190b2738-1689-11e5-8e0b-69fed675f1fd.png)
### 2. table of records

![2015-06-19 13-52-17](https://cloud.githubusercontent.com/assets/2145313/8249286/68cbc5ce-168a-11e5-9483-c8420fa02615.png)
So it looks like a table in phpmyadmin or excel.
You can select a column, row, or several cells with shift/ctrl, then double click on them or press _edit selected_ and a popup with value input appears. 
### Addendum

 At the top in both options - visibility filter (for example - show only items with price more than $100). I think some jquery libs support table filtering.
And of course buttons : select all, select none, invert selection.

**Comment by GawainLynch** [comment]
Do-able… and looks like a good idea, but better suited for an extension rather than bloating core for that something that only a few people would likely use.

At the very least, an extension would be a good path to core… If it proved popular and commonly used it would, IMHO, be a *candidate* for core under those conditions.

**Comment by Boorj** [comment]
btw, http://nexts.github.io/Clusterize.js/ nice extension for showing huge lists without DOM bloating
![clusterize-js](http://nexts.github.io/Clusterize.js/img/table_example.gif)

**Comment by GawainLynch** [comment]
It is, but DOM was not the part I was thinking. I was more meaning in our general PHP namespace. Not saying this is, or isn't, just that if this is only used by "one person" then it would be feature bloat. However, if it turns out that it's like BoltForms and is heavily used, then it might be a candidate to move to core.

**NOTE:** BoltForms *is* heavily used, and very useful, but even still not a candidate for core :wink:

**Comment by Boorj** [comment]
GawainLynch, that was just like an idea that i want to show, not in the context of previous message. Of course i inderstand that you want to keep Bolt.cms lightweight.

**Comment by rarila** [comment]
I think there has to be done quite some refactoring and cleanups in editcontent before such a thing can (should) happen. The ability to use flexbox would also help.

**Comment by GawainLynch** [comment]
@rarila editContent() doesn't [exists any longer](https://github.com/bolt/bolt/blob/master/src/Storage/RecordModifier.php)… The :koala: ate it :wink:

**Comment by rarila** [comment]
@GawainLynch [*editcontent*](https://github.com/rarila/bolt/tree/master/app/view/twig/editcontent), not *editContent*. You probably have to recalibrate :wrench: your OCD :innocent:

**Comment by Boorj** [comment]
http://**backgridjs**.com/#complete-example
![2015-06-21 18-00-34](https://cloud.githubusercontent.com/assets/2145313/8271544/66ecc850-183f-11e5-8025-4ad117cc34b2.png)
1. it's grid
2. it's editable
3. it has search
4. it has pagination

**Comment by Boorj** [comment]
i think we should create a backend part that allows edit field values by once. For example i double click column header and it opens the edit window, where I input a value. And it's being aapplied to whole column.

So on update command all updated columns are colored yellow, client sends something like
```javascript
        request = {
            action: 'update',
            type : 'several cells', //or 'column' or 'row' or 'one cell',
            parameters : [
                {
                    field: 'name',
                    list_or_record_ids: [12, 13, 154]
                }, 
                {
                    field: 'show_name',
                    list_or_record_ids: [12, 13, 154]
                } 
            ],
            value : 'Lee' //as the most common name
        };
```
Backend responses ok or error (with reasons) and it indicates. On success cells are colored back to white color.

When you edit only one cell in grid - simpler data is sent (like `action, type, record id, field name, value`)

How should it be defined, if a field in contenttype could be edited in mass-editor?
1. allowed in contenttype field description (if not - disallowed)
2. restricted in content type description (all others - allowed)
3. by default - all numbers and texts could be edited, if not restricted (like in p2)

**Comment by Boorj** [comment]
Also it could be done another way, with `xeditable.js` and `list.js`.
I found a snippet, changed it little bit, it goes like this:
![2015-06-21 18-22-13](https://cloud.githubusercontent.com/assets/2145313/8271616/82659e88-1842-11e5-8718-c9b9695bcd32.png)
So here i can use and input : selectboxes, calendars, sliders. 
It could be done for one cell or one column, or for cells of one column in selected rows...
(it takes less javascript and seems smooth).

How do you like this idea?

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

**Comment by Boorj** [comment]
@bobdenotter  Can we reopen this issue?  And move to v4 discussion?
Imagine, when you need to change 100 records - it's a hell to do that.

Try to select several rows here: https://editor.datatables.net/examples/simple/multiRow.html and press `Edit`. It could save tons of time!

Anyway, that wouldn't be a thing with `vue.js`. And can become a killer feature and one of the most notable updates for Bolt V4.

**Comment by jadwigo** [comment]
If you are mass editing records you already noted that Bolt is not the best way to do it at the moment.

A table editor is also not a good solution even if there are javascript components with examples that show a table editor. The integration with Bolt of one of those components is not simple, just to name a few of the problems with that: What should happen in the interface if the record has 200 text fields, or 5 image fields, or a repeater field, or a combination of those. Or you have 100 records with a youtube video, will your browser handle that or will it just crash. A horizontal scrollbar and putting all fields next to each other works with a few fields, but not with more than 15. If you only want to make a few fields available, which ones, and how do you choose?

We don't have the resources to build this, because we basically would have to recreate Excel inside of Bolt. This means that we will not re-open this issue.

But there is a workaround for many of those problems: use Excel.
You can export the records to a CSV file with PHPMyAdmin and similar tools. That CSV file can then be edited in a spreadsheet program. After that you can import the updated CSV file back into Bolt.

**Comment by Boorj** [comment]
@jadwigo i dramatically disagree. The case is not so difficult as it could seem.

I will answer step-by-step.

## 💭   Generally
I suggest to
- make a page for each contenttype with table, presenting all records (maybe filtered)
- row will present rows, columns - all or _selected_ fields in `contenttypes.yml`
- each value will have it's own editor, based on types
- table should support pagination OR lazy load OR mega-scroll (emulating of all rows presence, see `Clusterize` above)

This table could use one of existing libraries, or framework table component with editors.
In my example i will use screenshots of 
- [datatables.net](https://editor.datatables.net/examples/index) - awesome popular library with all functionality included
- [x-editable](https://vitalets.github.io/x-editable/) - lightweight system of micro-editors

## 👍 Benefits
See far below, in the end 

## :suspect:   Are we recreating excel inside Bolt?
No, definitely no. We are creating [simple page]((https://editor.datatables.net/examples/advanced/upload-many.html)) with a simple table and few buttons. 

![image](https://user-images.githubusercontent.com/2145313/44798767-9245c180-abdc-11e8-85f5-b7838f4c3ed8.png)

That doesn't seem 👶 to look as complex as excel.


## ✏️  How will we edit values?

As far as i can imagine we have 3 options of mini-editors:

- ### 🔪   inline editor
  As seen in excel. Click on value → **input [with confirmation]** replaces value representation
  ![2018-08-29_21-56-41](https://user-images.githubusercontent.com/2145313/44797687-ffa42300-abd9-11e8-8614-df6009acefff.gif)

- ### 🔫 :  popover
  Click on value → **mini-bubble** appears above the value.
  ![2018-08-29_21-55-07](https://user-images.githubusercontent.com/2145313/44797739-1fd3e200-abda-11e8-8ceb-1e44686e0e07.gif)
  ![2018-08-29_22-02-07](https://user-images.githubusercontent.com/2145313/44797791-4003a100-abda-11e8-89bb-bb3071ce4117.gif)

- ### 💣  modal window
  Click on value → **popup** appears on screen
  ![image](https://user-images.githubusercontent.com/2145313/44797828-5578cb00-abda-11e8-9e20-9b0c3027a240.png)

#### Editor box can contain ...
any input. Checkbox, text, textarea, datepicker. Any.

So you can edit one row or several - doesn't matter:
![2018-08-29_23-43-19](https://user-images.githubusercontent.com/2145313/44802274-7bf03380-abe5-11e8-92e0-35dedfb1137f.gif)



## 👯 What will happen, if we are editing many records at the same time, and they have different values in one field?
Simple, For example, _datatables_ editor has ability to solve that (see previous gif). 
![image](https://user-images.githubusercontent.com/2145313/44798024-b30d1780-abda-11e8-84d5-f519c9abcb7e.png)


## 📢 How will we define which field is editable in massedit (multieditor, if you wish)
>If you only want to make a few fields available, which ones, and how do you choose?

In `contenttypes.yml` . We can define the same way as the access is granted in `.htaccess` for apache server. `allow all, then deny specified` or `deny all, then allow specified`. So we can define multiedit option at contenttype level, or at field level. Take a look:

```yml
# 1. defining at field level for several distinct fields
posts:
  fields:
    title:
      type: text
      multiedit: auto # means it will use default editor for type "text" 
      # or 
      # ... custom editor, maybe text input with mask or something
      multiedit: {editor: custom_editor }
      # or 
      # ... value will be read-only in table
      multiedit: {preview_only: true}
```

```yml
# 2. defining at contenttype level (for all fields of contenttype)
posts:
  # note that it's not in 'fields: ...' branch
  multiedit: true # or true or any not null value
  # or
  multiedit: [text, number, checkbox] # this will filter fields by type
  # or
  multiedit: 
    include: [text, number, checkbox] # this will filter fields by type
    variant:  inline # / popover / modal

  fields:
    title:
      multiedit: false # this will exclude this field from table
```


##  📚 What should happen in the interface if the record has 200 text fields? 
It's a very specific situation. If webmaster decided, that editing 200 text fields is more convenient in masseditor (not in contentedit), okay.
- no problem to show table with 200 columns, table will have horizontal scroll.
  ![2018-08-29_23-55-17](https://user-images.githubusercontent.com/2145313/44802861-008f8180-abe7-11e8-8272-693563719e5f.gif)

- you can use popup window (see the 3rd option above)

## 🖼 or 5 image fields 
No problem. 😎 I imagine the table with 5 cells with 30×20px previews in 5 columns. When you press on image - editor appears. Popover with upload button, or our "select image on server" input.
Or popup. Datatables have such thing:
![image](https://user-images.githubusercontent.com/2145313/44799617-97a40b80-abde-11e8-8664-6ed3c580f136.png)

## ➿  and repeaters? what about them?
Easy. As i told above we can use any html markup as editor. For example, _datatables_ library supports custom forms:
![image](https://user-images.githubusercontent.com/2145313/44799745-e05bc480-abde-11e8-9211-bf26917f2aa1.png)
In such examples it's close to using `contentedit` page as editor, but if you will need to edit 200 records, you will realize hoge time economy.

##  💥  what if we have more than 50 records? for example, 10000 rows? Or 1 million 🤑    ?
Many libraries are using ajax for getting chunks of table rows. So we have 3 solutions
We can use:
- ajax **lazyload** - i suppose it's applicable for < 100 records. Because in expands the page height
- ajax **pagination** 
- ajax **mega-scroll** - technique, which emulates scrollbar of container with many rows (1 million, for example)
  - See Clusterize example above. 
  - Datatables has plugin ["scroller"](https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html) 
  ![2018-08-29_23-10-42](https://user-images.githubusercontent.com/2145313/44800512-c622e600-abe0-11e8-8ac0-c18ff731604c.gif)


## ☘️  We have phpmyadmin, excel. Why do we need mass-editor?
> use Excel. You can export the records to a CSV file with PHPMyAdmin and similar tools. That CSV file can then be edited in a spreadsheet program. After that you can import the updated CSV file back into Bolt.

That sounds like a counter-argument, based on "it's very hard to implement", not on "it won't be useful".
So.. If we assume that **it's not impossible**, we will realize, how convenient it is. 
Imagine, if there were a feature in Bolt that allowed you perform all those required operations easily, wouldn't it be cool?

## 👍👍👍 Benefits
Case: _you need to change price for 50 products from $20 to $22.5_
Choose one of solutions:
- 📆 open 50 pages -> scroll×50 -> edit×50 -> save (+wait until it's saved) ×50
- 📅 ask webmaster to export (optionally) -> then edit in spreadsheet editor -> then import 
- 🗓  ask webmaster to make an extension or whatever
- 🕐  or *make this in 30 seconds*   with mass editor

I suppose it will be VERY convenient. Basing on my experience of using bolt for different sites for different clients. This issue was created 3 years ago, and i still assume that it's a killer feature, often demanded.

**Comment by jadwigo** [comment]
You are correct that is it possible, and that there is a demand for it.

My point is that we do not have enough programmers to build it.

The good thing is that people who need it can use excel or phpmyadmin to do what they need to do.

**Comment by Boorj** [comment]
I can build it. Realization is not so hard as it seems. I started making that, done in 75%, but had no time to finish that.
Probably i'll need some logical help to find the best optimal solution for backend questions. And solve some dilemma on frontend: for example, if user selects 1st row, then goes to 5000 row on 50 page, and presses shift-select. Will it select 5000 rows (from 1st to 5000). And some other dilemmas.
For frontend things there is plenty of ready solutions.

**Comment by JarJak** [comment]
Looks like perfect candidate for an extension.

**Comment by bobdenotter** [comment]
Re-opening, although I agree with @JarJak: IMHO this is a candidate for an extension :-)

**Comment by Boorj** [comment]
If an extension can inject it's menu items into standard (beside overview, create new), i'm ok with that ;)
