### ISSUE TITLE
Limit visibility of content only to their respective owners

### ISSUE THREAD

**Issue by pr3drag** [bolt/bolt#3719]
I'm currently using Bolt as a backend for a mobile app, in which every user has its own credentials and is allowed to create its own content. 

Unfortunately, every user who has "view" permission for a given content type can see all the entries of that content type, so he can also see what other users are posting. I would like the ability to limit the list of entries, so that every user can see only the entries that he created. It's an "owner" permission, but applied to the overview list page, rather than on the single entry detail page.

Example for content type "post":
User 1 creates post A, B
User 2 creates post C, D

If user 1 and 2 are granted permission "view" on content type post, in the backend post list they both can see: A, B, C, D

I would like something like an editable "overview" permission, to make sure that user 1 sees only: A,B
and user 2 sees only: C,D.

**Comment by pr3drag** [comment]
I wanted like to add something to the original issue: I've been playing around bolt for a while, but I'm a newbie both in php and twig. 

Looking at the code, I had the feeling that what I asked in the issue above could be reached by tweaking the template. Is there anyone who has done this before and willing to share some suggestion? Thanks

**Comment by jadwigo** [comment]
@pr3drag you are asking for stuff that's a bit outside of the scope for bolt, the basic premise is that people in the back-end create content for a website, and have to collaborate to do that.

This transplates to the point that if you have content that should be hidden from other people in the bolt back-end you should not put it there in the first place.

Hiding information from co-workers (people with access to the back-end) is something that bolt is not designed for. This is something more suited for an inter-office document workflow tool where secret information is a requirement (think privacy for medical records) - which is something completely different from a website. 

It may be possible that you can tweak some templates, but I'm afraid that you're looking for the proverbial hammer in the analogy "when all you've got is a hammer everything looks like a nail"

**Comment by pr3drag** [comment]
Hi, thanks for the reply. I appreciate that. 

What I asked is something that is very common in backends. I think that bolt is a great product and well suited not only for creating websites, but also for creating mobile apps backends, as it has all the features that are needed plus an extreme ease of use. 

In my specific case, I don't believe that we can consider hiding some data as a "bad" feature only because it's against co-operation, as it's something that might be very useful to have in many situations. 

As an example: I'm using bolt as a backend for a mobile application that works as an aggregator of restaurants. Each restaurant can publish his menu and dishes, and there could be 20 or 30 users working on the backend. The restaurant owner sometimes is someone who has no specific IT knowledge, and it might be confusing for him to see dozens of records created by other restaurants. To keep all clean and simple, I would prefer to show him only the records that he creates.

**Comment by jadwigo** [comment]
That use case makes sense and is very cool.

In this case I would not want the restaurant owners in the bolt cms back-end, but I would build an extension where restaurant owners can edit one specific record.

The records could then be edited by admins in the back-end, but the non technical restaurant owners can only edit the one record that is linked to their account in the front-end.

I would handle authentication with something like https://github.com/gawainlynch/bolt-extension-clientlogin or a similar extension. And there obviously needs to be a process of approving users so not everyone can just pick a restaurant to edit.

**Comment by jadwigo** [comment]
To elaborate a bit.. the restaurant owners would never log in to bolt, they would authenticate into some kind of "members only" area where they can edit their "User Generated Content". 

The bolt back-end is where the owner of the site manages the "official" content of the site, so only "employees" get access there

**Comment by rarila** [comment]
I'm also for restricting the visibility for the same reason. I had a similar case a while ago. But in my case the editors were unlike the restaurants more of internal nature. Why do we have a backend when we need another login? Also the external login is quite strange if you consider one contenttype that all can edit an one that ia restricted. I won't tell them for A login here and have that interface and for B login there with anorher interface. Also it doubles the coding work. Afaik there is already a role attribute for that, it just doesn't work as expected.

**Comment by jadwigo** [comment]
@rarila that's where the hammer/nail analogy comes in - at the moment bolt is not the best tool for keeping secrets in the back-end. Maybe another tool is better.

**Comment by rarila** [comment]
@jadwigo Sure, but I'm not a user talking with users here. We are devs that have the power to change things and add things that makes sense.

**Comment by SahAssar** [comment]
This ties in very closely to #4439, and the solution for both this and #4439 will probably be the same (unless I'm reading things wrongly). I think we should combine these into a spec/RFC as soon as 3.0 is released.

**Comment by SahAssar** [comment]
I'm closing this one and moving it into #4439 (since it's the same issue with different symptoms), but I'm also going to add that to the blocking release list since we need a decision on this sooner rather than later to make it predictable for future versions.
