### ISSUE TITLE
Cannot use admin on new install to 2.1.3 

### ISSUE THREAD

**Issue by decebal** [bolt/bolt#3727]
Bolt - Fatal error.
Class: Twig_Error_Syntax
Message: The function "render" does not exist in "dashboard/dashboard.twig" at line 40
Code: 0

**Comment by GawainLynch** [comment]
You are using a Composer install have have updated Silex to 1.3 which is incompatible. You can either lock `silex/silex` to `<1.3` in your composer.json or update to Bolt 2.2.3 as the 2.2.x series works around the problem :grin:

**Comment by GawainLynch** [comment]
Closing to keep the issues under control, feel free to reopen if you're still having issues.
