### ISSUE TITLE
Some of the templates no longer work (if ever)

### ISSUE THREAD

**Issue by awrog** [bolt/bolt#3731]
The following templates do not work (fully) on try.bolt.cm
Suggestion remove them (for now)

I only checked the front-end:
* Bolt 2014 Theme -> OK
* Twenty by HTML5 UP -> OK
* Helios theme -> **not OK**, only frontpage
* Simone theme -> OK
* Miniport theme -> OK
* Clean Blog -> OK, has some styling issues in the menu
* Straight Line -> **not OK**, only frontpage
* Bootstrap Basic Theme -> OK
* Big Picture theme -> **not OK**, only partial frontpage, no menu, no nothing
* Simple Theme -> OK
* Parallelism theme -> seems OK, (purpose of lay-out puzzles me)
* HTML5Up Striped -> **not OK**, pages generate errors
* Aldehyde Theme -> OK
* Read Only theme -> OK, menu has issues
* cleanwhite theme -> **not OK**, not functional at all
* Easy Start theme -> OK
* ModdernFolio -> OK
* Bangalore -> seems OK, has styling issues
* Appalachia -> OK

**Comment by bobdenotter** [comment]
Thanks! We're going to look into this! :-)

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

**Comment by SahAssar** [comment]
For future reference, I've started a forum thread about this: https://discuss.bolt.cm/d/25-theme-compatability-with-2-2-2-3-continuation-of-3731
