### ISSUE TITLE
How to show content in previous location?

### ISSUE THREAD

**Issue by emanuelbg** [bolt/bolt#3736]
I have the bolt installed in a folder on the server **"test / blog"**, and can usually show the records on the home page within that directory. But I need to show the records in a file that is in the previous directory, **"test"**. How can I do this? must install the twig in the "test" directory also? Or is there any calls?

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.

See this page on [Apache .htaccess](https://docs.bolt.cm/howto/making-sure-htaccess-works) configuration.
