### ISSUE TITLE
Feature request: show extension screenshots  'a step earlier'

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#3744]
A couple of designers that I am trying to 'convert' to Bolt felt that 'there are no plugins' available - turned out that they did not grasp that the stuff at http://extensions.bolt.cm/ is quite extensive already because there's not much to see, only to read.

I see that you can add screenshots and other visuals to extensions, e.g. like in the beautiful http://extensions.bolt.cm/view/ed895319-603e-11e4-866c-43d66b93a270 and would recommend to show thumbs of the screenshots a step earlier, in the overview at http://extensions.bolt.cm/

This way, visually orientated folks will and/or people with a WP background will see more easily what an extension or theme can look like / do.
The same thing goes for the part of the Bolt backend where you browse and add extensions.

This may cause a challenge for extensions that are useful don't have a visual component, like the redirector - maybe something default should be shown for these.

**Comment by SahAssar** [comment]
This is already fixed for the extensions site, but I'm not sure how much I'd want to do on the backend extensions screen... In 2.3 it seems slightly more end-user friendly to me (more spacing, icons), but the question seems to be how much do we want people to browse extensions from the bolt backend? In my mind it's much better to have the browsing at extensions.bolt.cm, and install/config in the backend. Does that make sense? :)

**Comment by evertalbers** [comment]
I can see that it would change the UX too much. I don't know what the UI is going to look like in 2.3, maybe the line with the link to the extensions site can appear with a subtle fade-in just after page load, so you can't miss it? 
(best solution that I could think of, the first one that came to mind was make that line big or bold, but that would make it distract too much from the surrounding buttons).

Additionally, the link to the extensions site could shown be a bit more prominent on https://bolt.cm, e.g. somewhere on https://bolt.cm/download maybe?

**Comment by SahAssar** [comment]
I'm very late to reply (again), but would it be better to show it like was tried here: https://github.com/bacbos/bolt-menu-editor/issues/31#issuecomment-234263985, basically show a bit of the description and the icon? I was planning to do that for the omnisearch anyway, so the FE work should be basically the same.

A more prominent link in the backend and on bolt.cm would be good too IMO.

**Comment by evertalbers** [comment]
That example sure looks good to me.

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
