### ISSUE TITLE
bolt_session cookie lifetime

### ISSUE THREAD

**Issue by ntomka** [bolt/bolt#3754]
'bolt_session' cookie lifetime is not set here: https://github.com/bolt/bolt/blob/master/src/Application.php#L78, so it uses defaults.

[Documentation](http://silex.sensiolabs.org/doc/providers/session.html) says we can set it with the `cookie_lifetime` option. Should we use `cookies_lifetime` key from config.yml or not?

**Comment by GawainLynch** [comment]
The cookies lifetime that refers to is the authentication cookie… the one linked is (obviously) the session cookie.

@CarsonF and I are working on a branch for master/2.3 that will set paths and lifetimes for sessions… and clear then when not needed, and not set them in the first place if they aren't.

It is not possible with 2.2 as the session cookies are set by the session handler itself any time is is used, e.g. FlashBags.

**Comment by ntomka** [comment]
Is there a public repository for that 2.3 branch so I can look into it?

**Comment by CarsonF** [comment]
https://github.com/CarsonF/bolt/commits/feature/csrf-sessions

**Comment by GawainLynch** [comment]
Wow… @CarsonF you beat me for once!

**Comment by CarsonF** [comment]
hehe hard to beat Mr.:rocket:

**Comment by ntomka** [comment]
:) Thank you! :beers:

**Comment by GawainLynch** [comment]
Closing as this was merged a while ago
