### ISSUE TITLE
make a Yeoman scaffolding generator

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3755]
It would be nice to have a generator-bolt for Yo. 
http://yeoman.io/generators/

**Comment by GawainLynch** [comment]
That link fails badly on Chrome and Firefox:
```
XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://yeoman.io' is therefore not allowed access. 
The response had HTTP status code 500.
```

What would this give us? Apart from massive security problems?

**Comment by sbani** [comment]
There is a composer project : bolt/composer-install
What do you want the generator to do?

**Comment by Pinpickle** [comment]
Sorry for the self-promotion, but I've written a Yeoman generator for Bolt: [Tight](https://github.com/pinpickle/generator-tight)

Early days for it, so contributions are welcome!

**Comment by sbani** [comment]
Ok I know what it's doing but why not using `composer create-project bolt/composer-install`?

**Comment by Pinpickle** [comment]
@sbani for people used Yeoman, it could make more sense to use it rather than learning how to use another generator tool.

Personally, I made mine to add a little more out-of-the-box functionality to my Bolt sites, as I was noticing that I did a lot of the same stuff when building a new website.

There's nothing wrong with the composer creation. I'd go for that to set up Bolt as bare as it can be and not try to duplicate functionality on a Yeoman generator.

**Comment by GawainLynch** [comment]
> Sorry for the self-promotion

Promote away :grin: 

Personally — for now — I feel this is better left  in third-party-land with @Pinpickle's generator. Adding another supported install target/option is just starting to look like spreading ourselves too thin… as it currently stands. 

That said, maybe we could add a "*Third Party Installs*" section to the readme/docs and point to these things as they come up and indicate that we don't (directly) support them?

**Comment by Pinpickle** [comment]
> That said, maybe we could add a "Third Party Installs" section to the readme/docs and point to these things as they come up and indicate that we don't (directly) support them?

I support this notion.

**Comment by Boorj** [comment]
I'm using slightly different default directory structure for my purposes.  Its
##### My set-up
1. /web/ folder for public access
2. /src/views for *.twigs (actually hamls in my case)
3. /src/coffee and /src/less for preprocessor sources (*.coffee and *.less, obviously)
4. moved configs to /src/config
5. i use custom index.php (actually symfony style app.php and app_dev.php that require index.php)
6. moved all bolt stuff to app folder. 

I think 1-4 items are very convenient to all webdesigners who prefer not to use themes and store all changable project files in one special folder. In this way you don't have to struggle with server settings, prohibiting access to *.twigs in web directory,  all assets are also stored in /src.
It works perfectly, but when i need to put it to another - i have a problem to move everything manually and rename all things  to avoid loosing all my customizations . It goes to a problem if i start with bolt's own install package, because i have to do same job time by time.

So **my big wish** is to make automation for all that processes. That's why i'm interested in what @Pinpickle made and probably i could make my own version of it. Thanks, Christian.

**Comment by Pinpickle** [comment]
@Boorj your implementation sounds really clean. Would there be any way that you could share how you put it together?

**Comment by Boorj** [comment]
Of course. It's suitable for those who makes their own pages, not based on templates. So i have own routing, i deleted all template references (like record.twig and listing.twig) from ```config.yml```.
## Folder structure
![2015-07-23_19-13-51](https://cloud.githubusercontent.com/assets/2145313/8851087/f0cf415e-316e-11e5-932a-b2e139380b42.png)

## File contents

#### Full ```AppInit.php```
```php
<?php
namespace Mapple\Bolt;

use Bolt;
use Mapple\Bolt\CustomTranslationsProvider;
use SilexMtHaml\MtHamlServiceProvider;

Class AppInit {

	public function __construct ($path) {
        $this->path = $path;
	}

    public function run() {
        $vendor_dir = "vendor";
        $app_dir    = "app";
        $src_dir    = "src";
        $web_dir    = "web";
        $upload_dir = "up";
        $site_dir   = "{$src_dir}/Site";
        $res_dir    = "{$site_dir}/Resources";

        $configuration = new Bolt\Configuration\Composer($this->path);
        $configuration->setPath("vendor_dir",             $vendor_dir);
        $configuration->setPath("cache",                  "{$app_dir}/vars/cache");
        $configuration->setPath("logs",                   "{$app_dir}/vars/logs"); //planned to use it
        $configuration->setPath("database",               "{$app_dir}/database");
        $configuration->setPath("extensionspath",         "{$app_dir}/extensions");

        $configuration->setPath("themebase",              "{$res_dir}");
        $configuration->setPath("config",                 "{$res_dir}/config");
        $configuration->setPath("extensionsconfig",       "{$res_dir}/config/extensions");
        $configuration->setPath("translations",           "{$res_dir}/translations");

        $configuration->setPath("web",                    "{$web_dir}");
        $configuration->setPath("files",                  "{$web_dir}/{$upload_dir}");
        $configuration->setPath("thumbs",                 "/{$upload_dir}/thumbs");


        $configuration->getVerifier()->disableApacheChecks();
        $configuration->verify();

        $app = new Bolt\Application(array("resources"=>$configuration));
        $app->initialize();

        $app->mount($configuration->getPath('thumbs'), new \Bolt\Thumbs\ThumbnailProvider());
        $app->register(new MtHamlServiceProvider());
        $app->register(new CustomTranslationsProvider());

        $app->run();
    }
}
```

#### Routing

![2015-07-23_19-17-26](https://cloud.githubusercontent.com/assets/2145313/8851138/618e5646-316f-11e5-97d2-fa2e9e073c69.png)

It's just a current project, so soon i'll connect database to controller actions, so they will grab data from db.

Here are some listings for copypasting:
###### Important content from  ```/src/Site/Controller/Front.php```
```php
class Front
{
    /**
     * Returns some common variables that are used on various pages.
     * @param Request $request
     * @return array [its_local, _route, referer]
     */
    function get_initial_tempate_arguments(Request $request)
    {
        $args = [
            'its_local' => (PHP_OS != 'linux'),
            'referer'   => $request->server->get('HTTP_REFERER'),
            '_route'    => $request->get('_route'),
        ];
        return $args;
    }


    function home_action(Request $request, Application $app) {
        $args = $this->get_initial_tempate_arguments($request);
        return $this->render_page($app, $args);
    }

    //... other actions
    
    function render_page(Application $app,  $args=[]) {
        $template = $this->page_prefix. $args['_route'] .'.haml';
        return $this->render($app, $template, $template, $args );
    }

    function simple_render(Application $app,  $template, $args=[]) {
        return $this->render($app, $template, $template, $args );
    }

    function render_text(Application $app,  $text) {
        return $text;
    }

    //... and 2 functions copied from Bolt's standard installation    
    // Probably i'll alter change that to use functions from original classes, not copies.
    private function render(Application $app, $template, $title, $template_arguments=[])    {/*...*/}
    private function setTemplateError(Application $app, $error)    {/*...*/}
  
}

```

###### Some contents from ``` /src/Site/Resources/config/routing.yml ```
```yml
solutions:
  path:      /solutions
  defaults:  { _controller: 'Mapple\Site\Controller\Front::solutions_action'}

solution:
  path:      /solutions/{slug}
  defaults:  { _controller: 'Mapple\Site\Controller\Front::solution_action'}

# some lines for Google Webmaster approvement
google_webmaster_approvement: 
  path:      /54ed2f488b62.html
  defaults:  { _controller: 'Mapple\Site\Controller\Front::render_text', text : 'da2111d7809f'}
```


###### Interesting lines from ```config.yml```
```yml
# to use ../Resources/views as the folder to search templates in
theme: views 

 # to save logs to /app/vars/bolt-debug.log
debuglog:
  filename: '../bolt-debug.log' 
```
---
So that's it, if you need something, maybe archive with those directories - feel free to write. 
This config lets me start new project very quickly.

**Comment by Boorj** [comment]
Actually i was also aiming to separate config.yml into 2 parts: one thing that is used from project to project (like debug settings, mail options, log folder etc). And another part is like ```payoff```, ```sitename``` and other private data for each exact project. Because it's too weird to see, for example, *security settings* and *branding name* in one config file.

Another plan was to use different configs for production and development versions. So that caused my using ```app.php``` and ```app_dev.php``` in web folder. I wanted to config my server next (obvious way) - app.php for production, and app_dev.php for development, and then they call different config.ymls or use #3005 to make some config.yml variables, so they change the way ```Config.php``` loads per each environment mode.
