### ISSUE TITLE
What happened to my dashboard

### ISSUE THREAD

**Issue by isularifin** [bolt/bolt#3756]
![slug](https://cloud.githubusercontent.com/assets/8610007/8469887/f0be07f6-20b4-11e5-8f0e-c575bab814c4.png)

I have upgraded my bolt engine to 2.2.3. There's something with my dashboard. When i made an entry or page, the slug was not to be entry/title-entry. And i couldn't edit it. Please help me

**Comment by rarila** [comment]
One part of the problem could be a not updated bolt.min.css or an old version of it in the browser cache.

**Comment by isularifin** [comment]
wow. You are right. Thanks alot

**Comment by rarila** [comment]
@isularifin hehe, no problem. As I did that slug control I know how it should look. :-)
But I just learned that two buttons aren't allowed in bootstrap input groups, so the next refactoring is on the way…
