### ISSUE TITLE
BUG: "Copy to theme folder" fails on local extensions

### ISSUE THREAD

**Issue by ffxsam** [bolt/bolt#3758]
I have a theme in `extensions/local`, and it shows up fine in the extensions page. When I click "copy to theme folder," though, it fails:

```
Invalid theme source directory: /home/samh/bolt/extensions/vendor/myself/testtheme
%ERROR_LOCATION%
```

**Comment by GawainLynch** [comment]
The local extension functionality doesnt support themes, as themes can just be placed directly in the `themes/` directory and enabled in your `app/config/config.yml` file.

**Comment by GawainLynch** [comment]
That said, we should be hiding that button in that case.

**Comment by ffxsam** [comment]
Ahh, thanks. Sorry, still learning Bolt!

**Comment by GawainLynch** [comment]
Please don't feel the need to apologise… It's definitely a UX blunder on our part :grin:
