### ISSUE TITLE
Improve documentation on creating custom themes

### ISSUE THREAD

**Issue by ffxsam** [bolt/bolt#3759]
https://docs.bolt.cm/extensions/config

It's entitled "Creating a Bolt Extension or Theme," yet following the instructions does not yield a theme at all. It seems the correct way to make a theme is to make a copy of the "base-2014" theme, and edit that.

I'd suggest that clarification is needed. The documentation is unclear.

**Comment by GawainLynch** [comment]
That documentation is for creating extensions a themes to be published in the market place.

For templating see [Building Templates](https://docs.bolt.cm/building-templates).

**Comment by ffxsam** [comment]
Thanks for pointing me in the right direction!
