### ISSUE TITLE
Markdown fields do not translate definition lists correctly

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#3762]
Definition lists are not translated correctly under 2.2. This had been fixed in #3194

**Comment by cooperaj** [comment]
The markdown is:

    The definition title item (dt)
    :    The definition data item (dd)

2.2. translates this into the html

    <dl>The definition title item (dt)
    <dd>The definition data item (dd)</dd>

Note the lack of *dt* item.

**Comment by cooperaj** [comment]
Scratch this. I'd migrated to a new config file and brought across the allowed tags forgetting to check the existence of *dt*

**Comment by GawainLynch** [comment]
Phew… You had me scrambling then!
