### ISSUE TITLE
Markdown editor does not convert definition lists or tables when previewing

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#3763]
When previewing a markdown field neither definition lists nor tables are correctly shown. This is confusing for the end user.

https://www.dropbox.com/s/1p98y07x8cxbxoc/Screenshot%202015-07-03%2012.20.04.png?dl=1

**Comment by cooperaj** [comment]
After some research it appears that the marked library, and it's slot in replacement commonmark do not support definition lists.

http://talk.commonmark.org/t/description-list/289/12

This is a shame but I figure it means that unless you can find a parsedown-extra compatible JS library for markdown parsing you won't be able to fix this.

It also appears that tables are indeed supported. It's just that markdownextra takes a slightly more lax syntax then parsed/commonmark and so works when they don't. Leading and trailing pipes must be included on all rows.

**Comment by bobdenotter** [comment]
As you've mentioned: our Markdown Editor uses the javascript based 'marked.js' to parse javascript, while it's done by Parsedown on the PHP end of things. 

As far as I know, Parsedown _strives_ to be [commonmark compliant](https://github.com/erusev/parsedown/issues/213), but I think marked.js is aiming to be a 'basic markdown' implementation. 

> This is a shame but I figure it means that unless you can find a parsedown-extra compatible JS library for markdown parsing you won't be able to fix this.

The only real solution for this is to forego javascript parsing altogether, and do all previews with an ajaxy roundtrip to the server. That's the only guaranteed way the preview will be the same as the actual result. The question then becomes: How big of an issue is this, and do the benefits (consistency, "pureness") outweigh the downsides (slowness, more work)?

That said: Both of them have had recent updates, so marked.js might be closer to the spec as well, now.

**Comment by SahAssar** [comment]
Just adding here: the commonmark spec does not **currently** include neither tables nor definition lists: http://spec.commonmark.org/0.22/

**Comment by SahAssar** [comment]
Since marked.js tries to follow commonmark(ish) by default and since neither definition lists or tables are part of the spec I'm going to close this one.

Please feel free to reopen if you have a better idea for this :)
