### ISSUE TITLE
Override CMS (admin Panel) templates?

### ISSUE THREAD

**Issue by poznet** [bolt/bolt#3768]
Is  there any easy way to override CMS (admin Panel) templates ? 
For example by copying them to  app / ....  ?

**Comment by jadwigo** [comment]
You can overwrite the templates directly - but we don't support it.

If you overwrite them your changes will be reverted when you update bolt.

The idea behind it is that the back-end of bolt is the "core" user interface where we try to have a common interface with all other bolt sites. Extension can expand this a little bit.. but most of it is locked down.

**Comment by evertalbers** [comment]
An easy way to change stuff shown the dashboard, is to install the GoogleAnalytics extension, and then replace the content shown in there - things will remain intact when Bolt is updated.

This may or may not do it for you, depending on what you want to achieve. Hope it helped.

**Comment by poznet** [comment]
jadwigo -  true is  - if i want to use idea that you described  ("locked" back-end )  i would  use wordpress or joomla .

I need some configurable , simply, easy to use , nice looking CMS ,based on  good quality  code (SF2).   Bolt  have very good configurable  frontend (twig + yml) , but  i need in some  cases extend functionality in backend  ( for exapmle change listing  in specyfic contenttype etc ).  Most of it (what i need) can be changed in twig - that's why i'm asking  about  overwriting  templates in CMS.

Of course i can  fork all and create new contorllers / views  but  it's not right way :/

**Comment by GawainLynch** [comment]
You can `$app['twig']->prependPath();` Twig paths and supply your own Twig files, and they obviously won't get broken on upgrade. However we provide zero backwards compatibility guarantees on backend as so much needs to change, sometimes just for bug fixes.

**Comment by jadwigo** [comment]
You can also change the listing for content types somewhat by changing the yaml - https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes

**Comment by rarila** [comment]
@poznet I guess you are looking for [that](https://github.com/bolt/bolt/blob/master/app/view/twig/custom/listing/pages.twig.dist). Not a 100% solution as it has to be moved to another location but it should do for now.
