### ISSUE TITLE
Twig template not defined when using AJAX

### ISSUE THREAD

**Issue by riks24** [bolt/bolt#3769]
I have a form which sends an AJAX request, the request in then parsed in a custom controller. 

When trying to render the template I get the following error:
<pre>
Class: Twig_Error_Loader
Message: Template "twig/template/email.twig" is not defined ().
Code: 0
</pre>

This only occurs when I do the request with AJAX, a normal page request works fine, the template will also render if I put it in the default directory 'app/theme_defaults'. 

I've narrowed it down and the problem seems to be that it hasn't added my theme's path to Twig.

Dump from AJAX:
<pre>
dump($app['twig']);

1 => Twig_Loader_Filesystem {#617
        #paths: array:3 [
          "__main__" => array:2 [
            0 => "/var/www/websitename/app/view/twig"
            1 => "/var/www/websitename/app/theme_defaults"
</pre>

Dump from normal request:
<pre>
dump($app['twig']);

1 => Twig_Loader_Filesystem {#616
        #paths: array:3 [
          "__main__" => array:2 [
            0 => "/var/www/websitename/theme/websitename"
            1 => "/var/www/websitename/app/theme_defaults"
</pre>

I'm using Bolt 2.0.6 with PHP 5.5.9 on Ubuntu 14.04.

Any help or clarification would be awesome.

Thanks,

Ricky

**Comment by GawainLynch** [comment]
I am so glad you included you Bolt version in this as I was all "Ugh, this is back!" :grin: 

OK, this was raised in #3026 and fixed in #2874 which was in 2.1.0. If you're able to upgrade to the latest (currently 2.2.4) and let us know if the problem goes away, that would be awesome!

**Comment by riks24** [comment]
Upgraded to 2.2.4 and it's working now! Thanks for getting back to me so quickly :)

**Comment by GawainLynch** [comment]
Excellent, great news :grin:
