### ISSUE TITLE
[RFC] classes for Field types - validation, settings, content and storage

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3770]
From my comment on #2967 

As commented on IRC, i have some question regarding the direction that fieldtypes are going. 

A basic fieldtype (like input type=text) only needs very basic methods to be able to validate, prepare for storage and display it's data in a form field. It returns the data for storage. More complex fieldtypes could implement their own storage and return simple (text) data for indexing/search functionality. Like one file field (settings) that stores locally, another that communicates with dropbox. A geo field could for instance return simple long-lat-info as json or text, or could also store these coordinates itself to add store locator functionality.

The base field is unaware of the content-object that it is called from. For example, for datecreated of a content entity, it can instantiate a date type of field, get the form twig, but the field is not bound directly to any content type storage. When the form data returns, it is validated by the field, and simply returned. As datecreated is stored as a property of the content object itself. Decoupling fields from storage. A field validates data that has been offered, returns data (or an abstract) for storage and can handle data itself if needed.

The field can subscribe to events if needed or implement various methods, like for example postSave, to get notified when the contenttype as a whole was validated and the storage was permanent. Various other methods/events probably need to be implemented, like deleteValue(), deleteField(), createField() etc.

The base field probably has no need to implement/extend ArrayAccess or IteratorAggregate as those are interface contracts that have no use for simple fieldtypes like input-text, input-date. The base field is a simple interface for a content class to have/get/set field data. More complex data models can be handled from (or handed over from) within the getter/setter or within event methods.

```php
namespace Bolt\Field;

class BaseField
{
	// setValue($data) {}
	// getValue() {}
	// validate($data) {}
	// save($data) {}

	// setName($name) {}
	// getName() {}
	// displayField($data) {}

	// setSettings($settings) {}
	// getSettings() {}

	// ## Dispatched methods ...

	// createField($event) {}
	// deleteField($event) {}

	// preSave($data) {}
	// postSave($data) {}
}
```

**Comment by SahAssar** [comment]
Closing as most of this should be implemented/possible in 3.0/master.

(Also a certain someone told me to ;) )

**Comment by GawainLynch** [comment]
> Also a certain someone told me to 

It was the :koala: sitting in the :palm_tree: eating :leaves:, right? :wink:

**Comment by GDmac** [comment]
Should have paid attention in computer science classes to set a field ('X') value to ('1'),
MetaData, Builders, Entities, its Managers and its Fieldmappings...
```php
    public function set($entity, $value, $rawData = null)
    {
        $key = $this->mapping['fieldname'];
        $metadata = $this->buildMetadata($entity, $rawData);
        $builder = $this->em->getEntityBuilder('Bolt\Storage\Entity\TemplateFields');
        $builder->setClassMetadata($metadata);
        $templatefieldsEntity = $builder->createFromDatabaseValues($value);
        $ct = new ContentType('templatefields', ['fields' => $metadata->getFieldMappings()]);
        $templatefieldsEntity->setContenttype($ct);
        $entity->$key = $templatefieldsEntity;
    }
```
