### ISSUE TITLE
[RFC] Canonical URL Generation

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#3775]
Hey,

at the moment canonical URLs are generated with http:// as default.
See: https://github.com/bolt/bolt/blob/master/src/Configuration/ResourceManager.php#L329-L335

My problem:
I have https URLs only and have to add the `canonical` option to the [config.yml](https://github.com/bolt/bolt/blob/master/app/config/config.yml.dist#L63).
Starting without the option causes http URLs.
But I checked the `enforce_ssl` option which is for backend only.

My solutions:
1) User has to use the `canonical` option
2) We add a `enforce_ssl_frontend` or `enforce_ssl: ['backend', 'frontend']`
I prefer the second one just because I think using the "automatic" URL generation for canonicals is better than the hardcoded. And it's a kind of double check for internal URLs.

I updated the test #3774 to check the schema. So every change should already be tested there.

**Comment by StevendeVries** [comment]
Just to add an opinion. Solution 2 has my vote :+1: 
Add a check to prevent BC breaks.

**Comment by bobdenotter** [comment]
I'd propose a different solution: 

 - Let's leave the `canonical: ` setting as is
 - Change the behaviour of the automatic canonical generator: If the page is requested over HTTPS, make sure the generated canonical starts with `http://` too.

**Comment by sbani** [comment]
That's the current situation @bobdenotter . Canonical is always `http://` except you set `canonical:`setting.
Why do you want the automatic generator to start with `http://` and not `https://`? Google, for example, prefers https URLs asaik.

**Comment by SahAssar** [comment]
I'm going to close this as the current default behavior works perfectly fine if your server config forces https, but can also allow for http (if I understood the previous exchange correctly). Using a `canonical` with https seems to solve the issue for users that have/use https but also want their site to be accessible from http.

If you have objections please feel free to reopen the issue. I'll probably be the first one admitting to misunderstanding the issue :)
