### ISSUE TITLE
[RFC] File Archiver

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3778]
The primary objective would be providing versioning/archiving capability for physical files. 

We're planning implementing as an extension, but file events (pre-/post-upload; pre-/post-delete) were added to (a subclass of) Handler.php. The extension listens for these file events to mirror the file in question and capture relevant metadata about the event.

**Comment by bobdenotter** [comment]
Shouldn't this perhaps be part of a larger effort, to build actual file storage / management functionality?

**Comment by mhodges-cainc** [comment]
https://github.com/bolt/bolt/issues/574

**Comment by SahAssar** [comment]
Okay, I'm changing #574 to a General discussion for media management and consolidating #3784 and  #3778  there. If anyone has any objections let me know :)
