### ISSUE TITLE
[RFC] - Revert Capability

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3780]
The primary objective of this would be to provide the ability to revert content to any previous version via the front end. 

Team currently plans on building it out as an extension.

**Comment by GawainLynch** [comment]
Part of the core of this is in place now with the change log stuff, but it is something that I personally have on my wish-list.

It really comes down to handling the diffs that are written to the database.

**Comment by bobdenotter** [comment]
I've been thinking about this before, and it'd be great to have. The obvious "downside" would be the increase in Database size, but that should be manageable. 

Thinking about this.. We could even look at multi-language setups as if it were records with different versions. In fact, something like this could even be used to keep a 'current' version of a page online, while an editor is working on a new version that isn't published yet.

**Comment by GawainLynch** [comment]
Closing as this will likely land in an extension from CA at some point, and we can then look at implementation into v3/4 at that point.
