### ISSUE TITLE
[RFC] - More Granular Logging

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3781]
The primary objective would be to allow better control over name-spacing logic in regards to logging, etc. Providing lower levels of granularity for logging output (i.e. if we didn't want to set the entire code base to DEBUG, but just a portion). 

Our current implementation involves extending files for most of the logic, but configuration may live in application.php.

**Comment by GawainLynch** [comment]
Closing as this will likely land in an extension from CA at some point, and we can then look at implementation into v3/4 at that point.
