### ISSUE TITLE
[RFC] - Parent/Child Embedded Content Type

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3782]
The primary objective of this would be to allow for custom content types to be child element in another content type (in element vs. via relationships).

Team currently plans to build it into an extension - creating new field type called ‘nested content’.

**Comment by GawainLynch** [comment]
This is already WiP with the hope that we can get this into 2.3 as in core there are some rather fundamental changes required.

Ping @CarsonF

**Comment by helman** [comment]
Don't forget to add ordering :+1:

**Comment by SahAssar** [comment]
I'm guessing this is satisfiable by the repeatable fields spec that's in master?

**Comment by SahAssar** [comment]
Closing this as it should be satisfiable by the repeatable fields in 3.0 (was 2.3). If not, please feel free to reopen :)
