### ISSUE TITLE
[RFC] - Sidebar Customization

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3783]
The primary objective of this would allow ‘custom’ categories on the left sidebar which group content inside each (vs. forcing that specific content type as the only option). Need to ensure roles are also respected for the display of these ‘custom categories’. 

Team currently plans on building it out as an extension.

**Comment by SahAssar** [comment]
This was my proposal to solve #3120 (intendit is my work user) but that was more about resource contenttypes. Same solution, different (as I understand it) problem.

The thing I like about grouping of contenttypes is that it doesn't require that much code on the backend and follows the same logic as grouping/tabs in contenttypes.

**Comment by bobdenotter** [comment]
We currently have `show_in_menu: false` only. It groups these inside a group "Other content". I I read you correctly, that's basically what you want, only with the addition of having more of these groups, and the ability to name them, right?

**Comment by bobdenotter** [comment]
> Team currently plans on building it out as an extension.

If this is done in a non-obtrusive way, I wouldn't mind having this in core at all.

**Comment by SahAssar** [comment]
@bobdenotter: that was exactly what I was intending, and how I understood @mhodges-cainc.

Building this as an extension wouldn't really work well since it changes the admin-area/backend which is not extension-proof when it comes to updates.

**Comment by rossriley** [comment]
To make this really easy, why don't we just allow show_in_menu to accept both `false` and a textual value, then we only need to add an elseif and add the contenttype to an array named after the value:

eg:

**Comment by SahAssar** [comment]
That PR should solve it exactly like @rossriley suggested, as for the roles/permissions that @mhodges-cainc mentioned those can be handled just like any other contenttype.

**Comment by slahav** [comment]
Hi Guys,
maybe to clarify our use case a bit...
as far as i understand the out of the box menu implementation as it stand today is giving a somewhat limited control over what it displays, the menu can display:
 - Bolt System objects (config, dashboard, etc`)
 - Content types 
On top of those you have some additional control using permissions and menu configuration.
What we want is to be able to customize the menu with non-authorable objects that will introduce our own sense of order into the menus.

For example:
To support multi-solution authoring environment we want to be able to group our content types by product affiliation, like:
 - Math
 - Foundational Reading
 - Close Reading
The way I imagined that will be done is using a new property (just another meta-data) on the content types that will be processed while displaying the menu to determine how to group them under a parent menu entry.

So as a more concrete example, if the content type foo would have a new property in contenttype.yml that will say:
menu: /math/algebra/2nd Grade
This content type will appear under the following menu in bolt:
Math
  |----> Algebra
                |-------> 2nd Grade
                                       |--------> my content type
                   
Sivan

**Comment by SahAssar** [comment]
@slahav: Ah, that's a bit more complex.

In my current PR you can just do one level, formatted like in your example that would look like:

Math
|----> Addition
|----> Subtraction
|----> Multiplication
|----> Division
Reading
|----> Reading comprehension
|----> Foundational Reading
etc.

It's still a little step up from having no option at all though :smile:

**Comment by slahav** [comment]
@SahAssar agreed :) Baby steps.. :)
