### ISSUE TITLE
[RFC] - Additional Files/Folders Permissions Granularity

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3784]
The primary objective of this would be to have more granularity in file/folder operations permissions, to better control conditional rendering of elements in the twig's in these areas.

For example:
files:delete: [ admin ]   # allowed to delete files
files:rename: [ admin ]   # allowed to rename files
files:dup: [  ]           # allowed to duplicate files

**Comment by bobdenotter** [comment]
I think this one and #3778 should be done as part of a "media management" effort. I might be overcomplicating things, but to me it seems it'd be hard to enforce something like this in Bolt, while the files themselves are simply files on a server.

**Comment by SahAssar** [comment]
Okay, I'm changing #574 to a General discussion for media management and consolidating #3784 and  #3778  there. If anyone has any objections let me know :)
