### ISSUE TITLE
Record editing lookups failing

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3787]
Fresh master install with a pre-filled database:
![relationships](https://cloud.githubusercontent.com/assets/1427081/8634635/b2a9ad18-27f7-11e5-8588-dea7d94a0ba5.png)
![selectentries](https://cloud.githubusercontent.com/assets/1427081/8634636/b2c0e42e-27f7-11e5-96b7-1f0699bd01d3.png)

**Comment by bobdenotter** [comment]
Yup, looks broken. ^_^

**Comment by bobdenotter** [comment]
The correct results are in the rendered HTML.. I think it's the select/autocomplete that's having issues. 


![screenshot 2015-07-12 10 56 15](https://cloud.githubusercontent.com/assets/1833361/8637174/d4753fe2-2884-11e5-8713-0d7b7146523e.png)

**Comment by GawainLynch** [comment]
Yeah, that'd make sense as the dropdown is sized to a larger content set

**Comment by bobdenotter** [comment]
No idea why it's not working yet, but i'm going to dig in.

**Comment by GawainLynch** [comment]
Fixed during the closing scene of *Refactor Wars Episode VI: Return of the Koala* #4189
