### ISSUE TITLE
Fatal Error LowLevelException not found

### ISSUE THREAD

**Issue by MelvinDRM** [bolt/bolt#3788]
Good day people,

I'm trying to get Bot running, but I'm getting the following error as soon as I try to enter in my server:

Fatal error: Class 'Bolt\Exception\LowlevelException' not found in C:\xampp\htdocs\levnet\app\bootstrap.php on line 45

I have no idea how to fix this. Any thoughts?

Thanks in advance,

MR

**Comment by GawainLynch** [comment]
My immediate guess is that you've installed by cloning the git repository and not done a `composer install`.

See the [install documentation](https://docs.bolt.cm/installation#option-3-developer-way-using-git-and-composer).

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
