### ISSUE TITLE
Using Services as Controllers means before handler is not run

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#3791]
This was noted on 2.2 branch, not had time to trace on master because the routing refactor has changed the way it works.

If you define your controller in `routing.yml` as a service eg: 

```
path: '/my-page'
    defaults:
        _controller: 'controller.frontend:my-page'
```

Then whilst the controller resolves correctly to `$app['controller.frontend']` the code in `src/Controllers/Routing.php` that adds the default before handler does not get added because it only does a class_exists check.

**Comment by CarsonF** [comment]
Using controllers as services was only added in 2.3, right?

**Comment by GawainLynch** [comment]
@CarsonF further ideas here?

**Comment by rossriley** [comment]
Looking at the new stuff in master, I'm pretty sure it's not going to be an issue, the new `resolveBefore` method seems to resolve correctly.

So probably best we ignore this for 2.2 branch since it's functionality that not many are using, and it was easy enough to work around.
