### ISSUE TITLE
I'm willing to rewrite French translation from scratch

### ISSUE THREAD

**Issue by fabschurt** [bolt/bolt#3796]
Hi folks,

I'm building a Bolt website for a client, and I'm not entirely satisfied with the default core French translation. I can tell that a fair amount of work has been put into it, but there are some problems:

* Various misspellings.
* Various language errors and sometimes weird (kind of _old fashioned_) grammatical and syntactical structures.
* Missing translations.
* The translation files' format seems a bit dated, and does not reflect the new format used in the reference `en_GB` translation files (which use YAML hash nesting instead of full-inline string keys).

So for now I've duplicated `vendor/bolt/bolt/app/resources/translations/en_GB/messages.en_GB.yml` to `app/resources/translations/fr_FR/messages.fr_FR.yml` and I'm in the process of fully translating it, starting from scratch.

It's gonna be some bit of work and I think other French Bolt users could benefit from it, so I was wondering if you'd be considering a pull request for this brand new translation or if it's of no interest to you. It doesn't change things so much for me as I'm doing this translation for my client no matter what, but if I know that I'll ultimately push it upstream, I'd put extra care and spell checking into it.

For the record, I have really fair language skills in both English and French, and my relatives regularly call me a _grammar nazi_, so I guess I have the right profile for the job.

**Comment by rarila** [comment]
Your input is really welcome and we happily merge it!

Looking at the French files it looks like the French translation was orphaned and just a leftover from an old Bolt version.

_(I hope I or someone else finds some time to push the conversion to keybased translations forward in the future)_

**Comment by fabschurt** [comment]
Excellent, I'll gladly submit a PR for this work then :+1:

When this is done, I'm willing to offer my help about transitioning to key-based translations.

Just a quick question: can we consider the translation files in the core `app/resources/translations/en_GB/` directory to be up-to-date and can they be used as a reference for other translations? As I mentioned earlier, I copied the `en_GB` files to start from scratch, but maybe it's not the best way to go?

**Comment by rarila** [comment]
Ok, the most up-to-date translation is for sure ``en_GB`` but I doubt that it is 100% complete as devs (I won't exclude me) probably are often lazy and just add some ``__('Whatever text')`` without doing a correct keyed translation. But missing translations can easily regenerated using "Translations/…" in the backend.

I really appreciate any help in convertion to keybased translations. I started that a while ago but since then I had a lot of other areas with much higher priority to work on. But be assured, this a much harder work as one might expect. It takes quite some time to find reasonable keys (as with coding, naming is always the hardest part), you have to decide if a translation should be handled as generic or should be duplicated, … the rest is heavy search-replace.

**Comment by GawainLynch** [comment]
:+1:

**Comment by GawainLynch** [comment]
Just don't ask me for help with French… I am a native English speaker and often fail at that :grin:

**Comment by rarila** [comment]
@GawainLynch en_KOALA

**Comment by fabschurt** [comment]
> Ok, the most up-to-date translation is for sure en_GB but I doubt that it is 100% complete as devs (I won't exclude me) probably are often lazy and just add some __('Whatever text') without doing a correct keyed translation.

Yeah, it's the kind of things that can be easily overlooked, as it's part of the rather boring things in coding :sweat_smile: But okay, it's a good thing to know that `en_GB` files are regularly updated anyway.

> missing translations can easily regenerated using "Translations/…" in the backend.

Oh yeah, that's right. That'll come in handy.

> But be assured, this a much harder work as one might expect.

Oh don't worry, I do expect this to be a genuine pain in the ass! But I think it's worth it.

> Just don't ask me for help with French

No worries :sweat_smile: But it's true that discussion/validation of the new translation by a couple of other French-speaking contributors will be preferable, if possible at all.

**Comment by zo0o0ot** [comment]
I've been watching the repo, looking for an excuse to help, and I am an English speaker with a bachelor's degree in French, so I can help with sanity checks and translation discussions as you work towards the final translation text.  Let me know where you want the help, and I'll do what I can.

**Comment by GawainLynch** [comment]
@zo0o0ot, welcome to our community… pull up a chair, grab a :beer: and feel very welcome!

I am sure that both you and @fabschurt can find a workable way to collaborate on this, also we have the #boltcms IRC channel on Freenode that all the core devs hang out on. We try to make it an inviting place to be, so please both feel free to join us there to discuss further.

**Comment by rarila** [comment]
@fabschurt I'm doing a big refacturing in the editcontent area. While doing so I thought it would perhaps a good idea to convert to keybased translations in that area. Do you think it would be problematic for you? Then I could wait. But i don't think it would be a big deal as your translations wouldn't get lost, you would just have to copy them from "Unused translations" to "Missing keybased translations" after a rebase?!

**Comment by fabschurt** [comment]
@zo0o0ot Thanks mate, that's duly noted. I think maybe the best approach is for me to go on with the rewrite from scratch, asking you for advice if I get stuck on something, and when it's all done, we will discuss about the final draft as much as necessary, if that's fine by you? It'll be interesting to get the impressions of a native English speaker about the translations :+1:

@rarila I don't see how this could be a problem at all, as this situation will last until the `en_GB` base translation files are fully transitioned to key-based format anyway. So please help yourself :beer:

**Comment by zo0o0ot** [comment]
@fabschurt That works for me.  Let me know when you need my involvement.

**Comment by Maelphi** [comment]
Hello,
I'm a newbie with Bolt CMS but can help to translate or check french messages if needed.
I can also propose to translate some documentation pages like install, update and others.
Please let me know what is the best...

Mael

**Comment by pygillier** [comment]
@fabschurt any news on this ? I already started some translations on my own instances and would gladly share what I've already done (lexicon included)

**Comment by GawainLynch** [comment]
Merged in @pygillier changes in #4002 closing this

**Comment by fabschurt** [comment]
Wow, really sorry about that, I've been busy with a _huge_ pack of other things and I haven't had the time to work on this properly. Glad @pygillier could take over!
