### ISSUE TITLE
Error on checkTablesIntegrity

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3801]
After pulling in master, dashboard hangs on a whoops.
**Identifier "showcases" is not defined.**
seems to try to access a undefined content table on pimple
…/­src/­Storage/­Database/­Schema/­Manager.php313

```
20. InvalidArgumentException
…/­vendor/­pimple/­pimple/­lib/­Pimple.php78
19. Pimple offsetGet
…/­src/­Storage/­Database/­Schema/­Manager.php313
18. Bolt\Storage\Database\Schema\Manager cleanupTableDiff
…/­src/­Storage/­Database/­Schema/­Manager.php206
17. Bolt\Storage\Database\Schema\Manager addResponseDiff
…/­src/­Storage/­Database/­Schema/­Manager.php181
16. Bolt\Storage\Database\Schema\Manager checkTableIntegrity
…/­src/­Storage/­Database/­Schema/­Manager.php150
15. Bolt\Storage\Database\Schema\Manager checkTablesIntegrity
…/­src/­Storage/­Database/­Schema/­Manager.php234
14. Bolt\Storage\Database\Schema\Manager needsUpdate
…/­src/­Config.php785
13. Bolt\Config checkConfig
…/­src/­Controller/­Backend/­BackendBase.php63
12. Bolt\Controller\Backend\BackendBase before
<#unknown>0
```

**Comment by GDmac** [comment]
Quick workaround i used.
- app['schema.tables'] seems to be a new pimple of basetables, and contenttables don't seem to get added anywhere (src/Provider/DatabaseSchemaProvider.php)
- i surrounded in src/Storage/Database/Schema/Manager.php the blind $alias call with a conditional with a isset() check - seems to work, dunno if the content tables are supposed to be on app['schema.tables'] though...

```php
        if (isset($this->app['schema.tables'][$alias])){
            if ($ignored = $this->app['schema.tables'][$alias]->ignoredChanges()) {
                $this->removeIgnoredChanges($this->app['schema.tables'][$alias], $diff, $ignored);
            }            
        }
```

**Comment by GDmac** [comment]
After looking at this a bit more, it depends on if the storage/database/schema/table/contenttype ever will get a 'general' ignoredChanges() method implementation.

My suggestion is to implement above isset fix, but also future proof it, and create the method on the contenttype table class (return false). It should have a note that "ignoredchanges is currently not used for contenttypes in the checktablesintegrity"

**Comment by GawainLynch** [comment]
`Bolt\Storage\Database\Schema\Table\ContentType` extends `BaseTable` which has the `ignoredChanges()` function returning a false unless overridden, e.g. `LogChange`

**Comment by GawainLynch** [comment]
The problem with how it is now, and simply checking `isset()` is that it is guaranteed that we will need to ignore ContentType table columns in this context… The new storage layer has shown up these bugs in DBAL that we now have to work around and the refactoring that I did of the database schema classes now makes the tables extensible. So someone just needs to have a ContentType with a JSON array column and they're going to be bitten… The :koala: must have been eating some dodgy :leaves: that  day.

**Comment by GDmac** [comment]
yes, i thought about basetable. having a ignoredchanges() method on contenttype makes sure you have to look at it if the ignoredchanges is ever altered on basetable (which would require a parent::ignoredchanges() anyway)

**Comment by GawainLynch** [comment]
If `BaseTable` was modified to return a non-false, that would be a bug… it is a parent class and does not itself define a schema table.
