### ISSUE TITLE
Cannot use link logic with a custom routed record in menus

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3807]
The `menu.yml` structure allows us to refer to content types by a `path` attribute, which in turn will have its link resolved based on the content type. We can use the syntax `content-type/slug` or `content-type/id` as the docs suggest.

However, if this is not sitting on the default routing setup, where entering `content-type/slug` as an address doesn't resolve to a page, this functionality doesn't work. This is because the menu builder first checks if the path is a valid route _before_ seeing if there is a record associated with it. But if you enter the custom route, the check won't run because it doesn't match the regular expression check of the `contenttype/record` syntax.

Most of the time, this isn't a problem - enter the custom route and then it will just link to that custom route. This becomes a problem when you have custom routing logic in your record by extending the content class and overriding the `link` function - it is no longer called.

The culprit code is [here in MenuBuilder.php](https://github.com/bolt/bolt/blob/master/src/Helpers/MenuBuilder.php#L138-L160)

``` php
try {
    // See if we have a 'content/id' or 'content/slug' path
    if (preg_match('#^([a-z0-9_-]+)/([a-z0-9_-]+)$#i', $path)) {
        // Determine if the provided path first matches any routes
        // that we have, this will catch any valid configured
        // contenttype slug and record combination, or throw a
        // ResourceNotFoundException exception otherwise
        $this->app['url_matcher']->match('/' . $path);
        // If we found a valid routing match then we're still here,
        // attempt to retrieve the actual record and use its values.
        $item = $this->populateItemFromRecord($item, $path);
    }
} catch (ResourceNotFoundException $e) {
    $this->app['logger.system']->error(
        Trans::__(
            'Invalid menu path (%PATH%) set in menu.yml. Does not match any configured contenttypes or routes.',
            ['%PATH%' => $item['path']]
        ),
        ['event' => 'config']
    );
}
```

The call to `url_matcher` will throw an exception, so the record won't be fetched. Only the matching should be wrapped in a try/catch, and this, combined with the `populateFromRecord` should determine if the match was a failure or not.

**Edit:** I'm now of the mind that the URL matcher call shouldn't be there at all. It doesn't matter if its a valid route or not, does it?

**Comment by GDmac** [comment]
i agree, it seems the preg_match doesn't allow custom routes only foo/bar,
not even the suggested /entries from the docs
docs: https://docs.bolt.cm/menus
regextester: https://regex101.com/r/qR5cD9/1

Suggestion: just [matcher] the supplied path and 
add a test if populateItemFromRecord returns anything meaningfull

**Comment by Pinpickle** [comment]
@GDMac I think the `preg_match` format is okay, as it's for finding the route to a specific record (`/entries` won't resolve to a record, but a listing). I also think it would be counter-intuitive to enter the route for a record, have that record resolved, and then get the link from that record.

I think the matcher in that snippet of code should just go - as this is for finding the route to a record, it doesn't matter if the text entered is a valid route or not. 

- If it's not a valid route, and not a valid record path, it just falls back to the text that was entered for the `path` attribute
- If it is a valid route, and not a valid path, then the route *is* the text that was entered for the `path` attribute so same as above
- If it is a valid route, and also a valid path, then the route is determined from the record which may or may not be different to the path
- If it is not a valid route but is a valid path, then the route should be determined from the record which may or may not be different to the path. **This is what the current implementation disallows** - as the matcher will just stop the code right in its tracks

In all of these cases, the expected behaviour is the same regardless of whether the route is valid or not. It doesn't really make sense to check it.

**Comment by GawainLynch** [comment]
> I'm now of the mind that the URL matcher call shouldn't be there at all. It doesn't matter if its a valid route or not, does it?

Yes it does… it is to prevent database calls where there are potentially not required to build menus, c.f. [`populateItemFromRecord()`](https://github.com/bolt/bolt/blob/master/src/Helpers/MenuBuilder.php#L173-L190)

**Comment by Pinpickle** [comment]
> Yes it does… it is to prevent database calls where there are potentially not required to build menus, c.f. `populateItemFromRecord()`

@GawainLynch An invalid route doesn't necessarily mean that there are no valid database entries for that path. I'll explain my use case.

I have disabled the default content routes, so `{contenttype}/{slug}` does not resolve to anything. There are four records of these, each with a custom route to point towards that record. I have a content type with an overridden `link` function which will either generate a link to itself (the relevant route on the website), or to an external website if a field is filled in the record.

So, I want to enter `contenttype/slug1` ... `contenttype/slug4` for these four records as paths for the menu, and let the link logic generate the appropriate URL. However, as none of these references are valid routes, the menu builder will not check these records for the link they generate. I think linking to records is one of the most powerful features of the menu system of Bolt, and at the moment, this isn't doing it any justice.

**Comment by GawainLynch** [comment]
I am sort of lost in all of this… If there are no routes to the, um, routes… How are you routing to them?

**Comment by Pinpickle** [comment]
> I am sort of lost in all of this… If there are no routes to the, um, routes… How are you routing to them?

There are routes to these records, but they are hard-coded routes (as opposed to a catch all for a contenttype). For example:

```yml
parkterraces:
    path: /park-terraces
    defaults:
        _controller: 'Bolt\Controllers\Frontend::record'
        contenttypeslug: hometype
        slug: park-terraces
```

But whether there are routes defined or not is besides the point. Using the `path` attribute for a menu item, I am trying to link to a *record* and **not** a route. The record determines what the best way to link to it using its internal `link` function which could be anywhere on the web but most importantly its dynamic and allows developers to easily add code for dynamic menus.

So if I write:

```yml
label: Freestanding Homes
path: hometype/freestanding-homes
```

For a menu item, that path should resolve to the record from `hometypes` with slug `freestanding-homes` and then find its link. I've made a bit of a hack-fix by overriding the menu service provider with my own menu builder class that is literally exactly the same except I've removed the URL matcher call in the code I originally quoted and it is working really well.

The eventual call to the storage handler from `poulateItemFromRecord` will determine if the content type is valid or not, and will prevent unnecessary calls to the database.

**Comment by Pinpickle** [comment]
I've found some potential problems with this method with the use of the `|current` filter. It's simple enough to check if the current record's `contenttypeslug . '/' . slug` matches the current `path` of a menu item but I can see false positives coming from this...

How's about a *specific* `contentpath` attribute for menus so people know if they're linking to a route or to a record? It may also, as well as this, be an advantage to specify a `route` attribute for menus to link to a route's name (such as `parkterraces`).

**Comment by GDmac** [comment]
To recap, 
A) the docs say you can have a ``path: /entries`` that should link to the entries overview page.
https://github.com/bolt/docs/blame/master/source/menus.md#L39
B) However the regex that is used in the menubuilder will ONLY match ``typeslug/entryslug`` type of text,
it will never match anything else with less or more segments.

- this either needs fixing in the docs (remove example) or fixed in the menubuilder.
my current workaround is to only use (hard) links, which also saves on lots of DB calls for larger menus.

**Comment by SahAssar** [comment]
This one I'm gonna close just based on age and that we have traveled to this part of the code 10 times and back, so without repro in 3.4...
