### ISSUE TITLE
[Regression] Changing names of fields does not trigger DB update

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3808]
When I change the name of a field in `contenttypes.yml`, I am not prompted for a DB update. I have tried clearing the cache and deleting the DB, recreating it with the old schema and changing the field name again doesn't work either.

So then when I try to save, I get an error as the column doesn't exist.

Tested in 2.2.4

**Comment by GDmac** [comment]
Had the same **when adding a select field** 
When i added a select (2.2.4) it doesn't warn on the dashboard that the database needs updating. 
The select shows up in the dashboard / editcontent, but frontend print(record) doesn't include the field.
**command line: app/nut database:update does update the database**

**Comment by GawainLynch** [comment]
Found the issue. It was introduced in #3445 as it doesn't account for changes correctly.
