### ISSUE TITLE
Cache Config Yaml results

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3809]
instead of parsing all config, permission, routing, contenttype Yaml files for every hit, this proposal suggests to use a caching mechanism to store the parsed array data in cache.
pseudo code:
```php
// src/Config.php
protected function parseConfigYaml($filename, $path = null)
{
        // check cache first
        $cached = from_cache($filename);
        if ($cached->mtime() >= filemtime($filename)) {
            return unserialize($cached->data);
        }

        // Initialise parser
        if ($this->yamlParser === false) {
            $this->yamlParser = new Parser();
        }
        // ....
}
```

**Comment by GDmac** [comment]
use the source luke:  initialize() ... if (!$this->loadCache()) { ... }

**Comment by bobdenotter** [comment]
Haha! ;-)

**Comment by GDmac** [comment]
Yeah, after that translator.cache (100ms saved),
i thought to shave of a few moar yaml miliseconds *cough*
