### ISSUE TITLE
2.2.x adding a select field to contenttype not always triggers database update notice

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#3810]
When i added a select (2.2.4) it doesn't warn on the dashboard that the database needs updating. 
The select shows up in the dashboard / editcontent, but frontend print(record) doesn't include the field.
app/nut database:update does update the database

**Comment by Intendit** [comment]
It's not only select fields, I've had this happen with text and image fields too, so I'd guess it's for every field. Same as #3808 and perhaps related to #3801?

**Comment by GawainLynch** [comment]
#3801 is only relevant to master as none of that exists in 2.2.

**Comment by GDmac** [comment]
indeed duplicate, added the above info in there
