### ISSUE TITLE
Update JS Markdown Options to match Parsedown

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#3818]
Parsedown does not use GFM line breaks, and strikethrough doesn't work.
This code will update the editor to better reflect what is rendered.
```js
UIkit.on('beforeready.uk.dom', function(){
    $.extend(UIkit.components.htmleditor.prototype.defaults, {
        markedOptions: {
            breaks: false
        },
        // Removed strike
        toolbar: [ 'bold', 'italic', 'link', 'image', 'blockquote', 'listUl', 'listOl' ]
    });
});
```

I'm not sure where to put it though. @rarila help
I was testing it in `editcontent/_includes_data.twig`, right after the script includes

**Comment by rarila** [comment]
Probably ``/app/src/js/modules/fields/markdown``

**Comment by CarsonF** [comment]
I think it needs to run before an editor field is initialized though, since we are just changing defaults. Would that be ok?
