### ISSUE TITLE
Backend listing checks for any checkbox for "Delete Selected"

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3822]
I was working on an extension to add a checkbox into the backend listing, but I found that when I was checking them, the "Delete Selected" button would pop up. This is because [the code for it](https://github.com/bolt/bolt/blob/master/app/src/js/init.js#L209-L221) only checks for a checkbox, not a checkbox with a particular class.

```js
$('.dashboardlisting input:checkbox').click(function () {
```

Should be something like

```js
$('.dashboardlisting .record-select-checkbox').click(function () {
```

**Comment by rarila** [comment]
@Pinpickle Made it backwards compatiple. Hope it works for you.
