### ISSUE TITLE
Field type time

### ISSUE THREAD

**Issue by errogaht** [bolt/bolt#3823]
Im think this is good idea to create new field type "Time"

**Comment by rarila** [comment]
Probably a good idea.

**Comment by geoff-winner** [comment]
https://github.com/bolt/bolt/pull/4186

Made a PR for this Feature

**Comment by SahAssar** [comment]
Sorry, but this feels like an extension feature for now... It'd be pretty easy to make as an extension too. Closing this issue as part of a cleanup, if you feel this really should be part of bolt core please feel free to reopen! :)
