### ISSUE TITLE
Content behind changelog link is outdated

### ISSUE THREAD

**Issue by karfau** [bolt/bolt#3828]
The [Download](https://bolt.cm/pages/download) page links to release 2.2.4 and has a link to the [CHANGELOG.md file at master](https://github.com/bolt/bolt/blob/master/changelog.md). This changelog is outdated, it stops at 2.2.1.

I found a changelog containing the information about 2.2.4 in the [release/2.2](https://github.com/bolt/bolt/blob/release/2.2/changelog.md) branch.

**Comment by GawainLynch** [comment]
@bobdenotter has resynced the master changelog :+1:
