### ISSUE TITLE
Register/Login Module

### ISSUE THREAD

**Issue by MelvinDRM** [bolt/bolt#3832]
Hello community,

I'm thinking on adding a Register/Login functionality to my site. I have no clue about how to do it (I'm new to this). Has anyone attempted this? What are your thoughts? I would like people to register as guests.

Going a little bit forward: Is the SessionServiceProvider good enough to pass some variables like the user ID or ID type so I can make queries throughout the site?

Thanks in advance,

MR

**Comment by Intendit** [comment]
bolt/members does this if I'm not mistaken.

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
