### ISSUE TITLE
Database update broken on master.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3838]
When clicking "Update database", Bolt breaks on Master with the following error: 

![screen shot 2015-07-20 at 14 14 59](https://cloud.githubusercontent.com/assets/1833361/8775757/7dbb55b6-2eeb-11e5-8ad6-41355622e1db.png)

Using PHP 5.5.10, with MySQL on Osx.

**Comment by GawainLynch** [comment]
Platform junk with MySQL: https://bugs.mysql.com/bug.php?id=19498
