### ISSUE TITLE
Cannot modify contenttype once generated

### ISSUE THREAD

**Issue by eimajenthat** [bolt/bolt#3846]
In my contenttypes.yml, I can define new contenttypes with as many fields as a I want, all day long, but if I modify the fields of an existing contenttype, by adding a field, removing a field, or modifying a field, the application is rendered inoperable (I get a Whoops! error page, which I will attach when I figure out a good way to do it) until I restore my contenttypes.yml to its previous state.

I thought perhaps I needed to manually run the database update script, but it gets the same error:
```
php app/nut database:update



  [InvalidArgumentException]
  Identifier "stories" is not defined.



database:update

```

I don't know Bolt that well yet. Perhaps there is a different procedure to modify contenttype schemas?  Or perhaps it's simply not allowed?

The error I receive is similar to https://github.com/bolt/bolt/issues/3801 but the steps to get there appear to be different, hence the new bug.

Any help would be much appreciated.

**Comment by eimajenthat** [comment]
Here's the Whoops error: http://jsfiddle.net/eimajenthat/x28c31o1/

**Comment by eimajenthat** [comment]
I'm on dev-master.

**Comment by GawainLynch** [comment]
Ah, master is currently highly unsuitable for production use, we are in the middle of some large refactoring work… the storage layer being one part under heavy construction.

If you `git checkout release/2.2` that is the current stable branch, and `git checkout v2.2.4` for the current stable tag :+1:

**Comment by eimajenthat** [comment]
Thanks for the heads up.  My use case is a hobby project, so it seemed a good place to try out the development branch.  I'm going to stick with v2.2.4 for now though, since it is working for me.  Other than this issue, my experience on master was pretty solid.  I'm really liking the flexible architecture of Bolt.  Seems like it could be a great fit for all sorts of projects.

**Comment by GawainLynch** [comment]
Cool… We're making things even more modular in master right now, but it changes on a daily basis… We keep tests passing, but we know there are corner cases. I've never been so nervous about people using master :grin:
