### ISSUE TITLE
Send storage event in publishTimedRecords 

### ISSUE THREAD

**Issue by pbnPierre** [bolt/bolt#3862]
Shouldn't bolt send a Storage event in publishTimedRecords and depublishExpiredRecords ? https://github.com/bolt/bolt/blob/master/src/Storage.php#L1077

For example if we want to make live indexing in elasticsearch, it's not possible when items are timed published.

**Comment by GawainLynch** [comment]
From memory this will trigger an event in `master` (what will become Bolt v2.3.0) when we're finished implementing the new storage layer. On that note, please be aware that `master` is under *very heavy*, and invasive, development right now and absolutely **not** suitable for production. The controller, storage, configuration and session layers are being refactored/rewritten.

For `release/2.2` (our current LTS branch) it sounds like a reasonable addition, as it's low impact.

**Comment by pbnPierre** [comment]
Great, an idea of the delay to implement this ?
Do you want me to do it ?

**Comment by GawainLynch** [comment]
I am in the middle of writing the code at this moment.

**Comment by pbnPierre** [comment]
![image](https://cloud.githubusercontent.com/assets/5654638/8903328/6b9a43d0-3457-11e5-92f0-38e90a5fc130.png)
<3

**Comment by GawainLynch** [comment]
Oh and just by the way on this, the code I am adding will be going into the current stable (long term support) branch, `release/2.2`. 

The work in master is going to take a little longer due to some stuff that has to land (shortly).

**Comment by GawainLynch** [comment]
@bobdenotter just merged that PR and it should land in Bolt v2.2.6.

**Comment by pbnPierre** [comment]
I finally have used the feature. I'm sorry for the delay.
There is a bug, the event doesn't get the content because the var $recordIds is not read properly.

It has this structure : 
```
array (size=1)
  0 => 
    array (size=1)
      'id' => string '17' (length=2)
```
So the method to get the content must be change in the loop by :
```
$content = $this->getContent("$contenttypeSlug/".$recordId['id'], array('hydrate' => false, 'returnsingle' => true));
```

**Comment by GawainLynch** [comment]
By all means, feel free to PR something :+1:

**Comment by pbnPierre** [comment]
Phew it was harsh sorry. It's done.
