### ISSUE TITLE
Login page problem in v2.2.5

### ISSUE THREAD

**Issue by gitllermopalafox** [bolt/bolt#3869]
Hi,

In my local, after upgrade to 2.2.5 the login page looks bad:

![login](https://cloud.githubusercontent.com/assets/4684919/8890018/a59e10fa-32b5-11e5-8fe9-5064822f676c.PNG)

I use this method to update:

```
curl -O http://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
chmod -R 777 files/ app/database/ app/cache/ app/config/ theme/ extensions/
```

**Comment by GawainLynch** [comment]
Can you give us a screenshot and some more details please.

**Comment by gitllermopalafox** [comment]
Sorry, I update my issue.

**Comment by bobdenotter** [comment]
Dumb question: Have you tried a hard refresh and/or clearing your browsercache?

**Comment by gitllermopalafox** [comment]
Yes, I cleared my browser cache.

I have just to delete the bolt cache manually and it works. I'm going to trying to replicate my steps in a backup of my local project.

**Comment by gitllermopalafox** [comment]
I have been upgrading several times, in differents bolt instalations and I can't to replicate the error, all is working fine, so sincerely I don't know what happend, I'm sorry.

You can close this issue.

**Comment by GawainLynch** [comment]
Yeah, this one is strange as for a while now we've automatically flushed Bolt's cache when it detects a version change. One of the times it does not work as we'd like is when people move the Bolt installation. 

In your case I am unsure, but we're glad it's all working for you now :grin:
