### ISSUE TITLE
addMenuOption documentation issues

### ISSUE THREAD

**Issue by Johardmeier** [bolt/bolt#3871]
In the SampleExtension the initialization function looks like this:
`$path = $this->app['config']->get('general/branding/path') . '/sampleextension';`
`$this->app->match($path, array($this, 'myfunction'));`
`// Add a menu option, only for users with level DEVELOPER`
`$this->addMenuOption("Sample Extension", $path, "icon-exchange", \Bolt\Users::DEVELOPER);`

But the addMenuOption function only adds the full URL if there is no backslash. So the correct line would be
`$this->addMenuOption("Sample Extension", 'sampleextension', "icon-exchange", \Bolt\Users::DEVELOPER);`

And if instead of 'sampleextension' we'd want something like 'myextensions/sampleextension it would break again...

Either the addMenuOption function needs some adjustments or the SampleExtension needs to be revised.

**Comment by GawainLynch** [comment]
Ah, that is probably just a matter of clarity in the documentation, as `addMenuOption()` is to add backend menu items, not frontend… hence the use of `$app['config']->get('general/branding/path')`.

**Comment by Johardmeier** [comment]
Wes I can see that. It is probably best if the SamlpleExtension in the snippets would be adjusted.
There are only two small concerns with that: 
- Older solutions that base upon the SampleExtension are probably broken
- It is not possible to use an extended path like ../backend/myExtensions/sampleextension.
Should I try to add this to the diocumentation?

**Comment by GawainLynch** [comment]
OK, took me a while to [find this](https://snippets.bolt.cm/s/1r1u1)… First point is that extension is for Bolt 1.x. For our current documentation on extensions see our [documentation site](https://docs.bolt.cm/extensions/config).

**Comment by GawainLynch** [comment]
Closing as part of a general issue clean up.
