### ISSUE TITLE
src/Storage.php checks for return_single, not returnsingle

### ISSUE THREAD

**Issue by padawan** [bolt/bolt#3877]
In all occurrences of $storage->getContent, the parameter key 'returnsingle' is used: https://github.com/bolt/bolt/search?utf8=✓&q=returnsingle

However, in src/Storage.php, what's checked is 'return_single': https://github.com/bolt/bolt/search?utf8=✓&q=return_single&type=Code

**Comment by GawainLynch** [comment]
You are correct insomuch that when calling `getContent()` you should use `returnsingle`.

However, the `return_single` is used as a decoded internal parameter, and assigned as `$decoded['return_single'] = $metaParameters['returnsingle'];` in the internal function `parseTextQuery()` as you can [see here](https://github.com/bolt/bolt/blob/release/2.2/src/Storage.php#L1252).

**Comment by padawan** [comment]
Sorry about that confusion.

**Comment by GawainLynch** [comment]
No stress… That class is nothing short of confusing :grin: 

It is also worth noting that class is deprecated in master currently and we're replacing the storage layer completely (while maintaining backward compatibility).

**Comment by padawan** [comment]
Yes, I've seen that (searching for "Bolt 2.3" in the docs ;-). I'm writing an importer plugin for Movable Type, I was searching for the best way to fetch the ID of an existing record using an array of key/value (e.g. `WHERE field1 = '…' AND field2 = '…'`) to merge with existing records but didn't succeed with `getContent()`, so I resorted to a direct SQL query.

**Comment by GawainLynch** [comment]
Yeah, I think the original thoughts around `Storage::getContent()` were more about having it talked to by the Twig `setcontent()` function. 

You might have, as you hint toward, have found [these pages](https://docs.bolt.cm/storage/introduction), if not @rossriley has put some good work into outlining the process of using the new storage layer. Also there is the internal brief that he wrote up in #3720 (might not be so useful to you).

Also a good place to see how we're doing things internally is the [`Bolt\Storage\Repository` classes](https://github.com/bolt/bolt/tree/master/src/Storage/Repository).
