### ISSUE TITLE
Unnecessary data in image/file lists

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3878]
I was looking through my DB when I noticed an image list field

```json
[{"filename":"image.jpg","title":"An Image","id":0,"order":1,"progress":0,"element":null}]
```

The `id`, `order`, `progress` and `element` fields aren't useful pieces of data afaik (well I know progress and element aren't but I don't know about id and order). I'm pretty sure the array just isn't getting sanitised before being put into [its textarea and then saved to the DB here](https://github.com/bolt/bolt/blob/master/app/src/js/upload-files.js#L156-L159).

```js
serialize: function () {
    var ser = JSON.stringify(this.list);
    $('#' + this.id).val(ser);
}
```

Running 2.2.4 (but present on master I think)

**Comment by GawainLynch** [comment]
ID and order are used when you set order on the images, something I do 100% of the time with imagelists myself.

**Comment by Pinpickle** [comment]
But when it's saved to the db, isn't that dependent on the order of the
objects in the encoded array and not the contents of the objects?

**Comment by GawainLynch** [comment]
Real world test… Imagelist field with 3 of Bolt's stock images:
* apple-desk-iphone-2750.jpg
* blur-flowers-home-1093.jpg
* carrot-cooking-eat-1398.jpg

Saved JSON when initially added in alphabetical order:
```json
[
    {
        "filename":"apple-desk-iphone-2750.jpg",
        "title":"apple-desk-iphone-2750.jpg",
        "id":0,
        "order":1,
        "progress":0,
        "element":null
    },
    {
        "filename":"blur-flowers-home-1093.jpg",
        "title":"blur-flowers-home-1093.jpg",
        "id":1,
        "order":1,
        "progress":0,
        "element":null
    },
    {
        "filename":"carrot-cooking-eat-1398.jpg",
        "title":"carrot-cooking-eat-1398.jpg",
        "id":2,
        "order":1,
        "progress":0,
        "element":null
    }
]
```

JSON after moving `carrot-cooking-eat-1398.jpg` to the second position:
```json
[
    {
        "filename":"apple-desk-iphone-2750.jpg",
        "title":"apple-desk-iphone-2750.jpg",
        "id":0,
        "order":0,
        "progress":0,
        "element":null
    },
    {
        "filename":"carrot-cooking-eat-1398.jpg",
        "title":"carrot-cooking-eat-1398.jpg",
        "id":2,
        "order":1,
        "progress":0,
        "element":null
    },
    {
        "filename":"blur-flowers-home-1093.jpg",
        "title":"blur-flowers-home-1093.jpg",
        "id":1,
        "order":2,
        "progress":0,
        "element":null
    }
]
```

So this becomes a question for the :de: contingent… @rarila when you're done with that yummy :beer:, what is your call on what the JS needs, as from a PHP/database perspective we just save and return what we're given.

**Comment by GawainLynch** [comment]
Made the mistake of leaving my database client open… so I removed the `id`, `order`, `progress` and `element` parameters… reload worked fine… reorder and reload… working results that mirror the JSON order!

@rarila I think it's time to bring out the Bolt :gun: on those :grin:

**Comment by GawainLynch** [comment]
DOA: https://github.com/bolt/bolt/commit/8e9a97b54063be15410913656520a37145d73ecb
