### ISSUE TITLE
Weird memory leak / loop in "new content" 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3883]
Encountered this on one site, so i'm not sure if it's a but in Bolt, or something quirky with the site just yet. Thought i'd log it just in case. 

Most pages on that site hover around 25mb memory usage: 

![screen shot 2015-07-28 at 17 33 20](https://cloud.githubusercontent.com/assets/1833361/8935841/176bc984-354f-11e5-953f-13f63e0a30b3.png)

But, when clicking "new entry", it breaks: 

![screen shot 2015-07-28 at 17 33 37](https://cloud.githubusercontent.com/assets/1833361/8935845/1ae68068-354f-11e5-88d1-3e9a3f0c4d7c.png)

**Comment by GawainLynch** [comment]
@bobdenotter does Blackfire show anything?
