### ISSUE TITLE
[RFC] .editorconfig

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#3890]
A good and easy way to ensure some setting for the dev's Editor/IDE

Info: http://editorconfig.org/
Plugins: http://editorconfig.org/#download

Please discuss about the settings and the need in general.

My suggestion:
```
+; top-most EditorConfig file
+root = true
+
+; Unix-style newlines
+[*]
+end_of_line = LF
+insert_final_newline = true
+trim_trailing_whitespace = true
+charset = utf-8
+
+[*.php]
+indent_style = space
+indent_size = 4
+
+[*.yml]
+indent_style = space
+indent_size = 4
+
+[*.js, *.json]
+indent_style = space
+indent_size = 4
```

**Comment by rarila** [comment]
Probably:
```
+[*.twig]
+indent_style = space
+indent_size = 4
```

**Comment by GawainLynch** [comment]
This has come up before, and I am not sure about it:
* No plugin for Eclipse… Someone buy me a new laptop with enough memory to run PHPStorm and we'll talk  :wink:
* I feel **really** uncomfortable with things like indent, and to a far lesser extent whitespace, being managed automatically… People don't have a habit of checking their `git diff` before committing
* Another requirement for developers to contribute
* Historically problems occur from IDE configuration, or generation tools like Grunt and Co.
* @rarila should use a real operating system :stuck_out_tongue:

**Comment by sbani** [comment]
If you feel uncomfortable with **very basic** settings, it's probably not good idea to add this file, just because there are many checks afterwards.

But I still think there are very basic settings (like `end_of_line = LF`) that can be added.

> Another requirement for developers to contribute

No! Devs don't need to install it. It's just a good thing for devs who have the plugin, many projects with different setting, and don't want to create settings manually. It's just working out of the box.

**Comment by rossriley** [comment]
Doesn't the .gitattributes file take care of line endings?

**Comment by GawainLynch** [comment]
> Doesn't the .gitattributes file take care of line endings?

Yes

**Comment by rarila** [comment]
No, it doesn't. It does that only for checkout (if at all) and that doesn't help when you push a file with CRLF. Otherwise PRs like this would't be neccessary.

**Comment by sbani** [comment]
So, what do you say? +1 or -1?
Seems to be a "+/- 0" and therefore I would stop here.

**Comment by bobdenotter** [comment]
I'm not much of a fan of this. I feel it just re-iterates all that's done already in our .gitattributes and PSR-1/PSR-2. For a specific set of IDE's.

**Comment by GawainLynch** [comment]
I'm with @bobdenotter on this one too.

**Comment by sbani** [comment]
Okay. Feels good to close it :+1:
