### ISSUE TITLE
Hundreds of "Notice: Array to string conversion in /..../src/Storage.php on line 1071"

### ISSUE THREAD

**Issue by iMaxxx** [bolt/bolt#3893]
Just updated to 2.2.7 and now I have these message everywhere in back and front end:
"Notice: Array to string conversion in /..../src/Storage.php on line 1071"

**Comment by GawainLynch** [comment]
Thanks for finding, and my humble apologies…

It is a simple online fix: #3896

**Comment by iMaxxx** [comment]
Thanks!
