### ISSUE TITLE
Load more posts on scroll

### ISSUE THREAD

**Issue by antonioperic** [bolt/bolt#3895]
Hi,
what is the best way to implement load more on scroll. Basically I have blog with posts and showing 4 posts, on scroll I need to load 4 more etc. Is there any ajax action already ready for this or I should do some customization

**Comment by rossriley** [comment]
I don't think there's an easy way built in, but it would be straightforward to do by implementing your own controller method.

The normal way to attack this is to put a next page placeholder at the bottom of your first results and then when that comes into the viewport, fire off an ajax request that renders a single page of results (along with the next page placeholder), then repeat ad infinitum until you run out of pages.

Bolt already supports paging queries via the `allowpaging` directive. So all you'd probably need to do is hijack the contentlisting route and map it to your own controller method:

    contentlisting:
        path: '/{contenttypeslug}'
        defaults:
            _controller: 'My\Custom\Controller::listing'
        requirements:
            contenttypeslug: 'Bolt\Controllers\Routing::getPluralContentTypeRequirement'

You can then us `$request->isXmlHttpRequest()` to do your own behaviour if it's an ajax request.

**Comment by antonioperic** [comment]
@rossriley I will try it, thnx

**Comment by hansgrinwis** [comment]
You might want to check out
https://github.com/paullla/bolt-extension-infinite-scroll

**Comment by antonioperic** [comment]
@hansgrinwis thnx, I know about @paullla extension as we work together on project ;)
