### ISSUE TITLE
Timed entries unpublished after update to 2.2.7

### ISSUE THREAD

**Issue by iMaxxx** [bolt/bolt#3899]
After updating to 2.2.7 all my timed entries were unpublish, but published (timed) before updating.

**Comment by iMaxxx** [comment]
- now I opened an entry
- changed status to timed again
- saved it
- reopen it and ist unpublished again
(publish date was from june and unpublish date coming in december)

**Comment by iMaxxx** [comment]
It's also not possible to publish these entries in any way. You can set it to published, but after reload its unpublished again. In system log all you see is 'Granting "publish" for titelbilder to root user'

**Comment by GawainLynch** [comment]
I'll have a look at this later today for you… Unless someone beats me to it :grin:

**Comment by GawainLynch** [comment]
OK… This lead to an interesting discussion in IRC while I scratched my head trying to figure this out.

Another small typo. Easy fix in #3907 for you.

**Comment by iMaxxx** [comment]
That's it, thanks!
