### ISSUE TITLE
Yearly archive

### ISSUE THREAD

**Issue by MiguelMoC** [bolt/bolt#3904]
Is there a way to have a yearly archive for post or other contenttypes in the sidebar, using a datetime field as reference and not the year created? Like for events.

**Comment by bobdenotter** [comment]
Hi, you can use this extension for yearly archives: http://extensions.bolt.cm/view/30b130a7-0ebb-11e5-9120-621e70d6e3eb

**Comment by MiguelMoC** [comment]
Thats great men! Thanks!
