### ISSUE TITLE
Always return array when using setcontent with where (was "Bolt too smart about returning a single query result")

### ISSUE THREAD

**Issue by martijneken** [bolt/bolt#3914]
I'm querying relationships, and using a sort and limit, as follows:

   {% set ids = person.relation.projects|join(" || ") %}
   {% setcontent relatedproj = "projects" where { id: ids } orderby '-year_started' limit 5 %}

This query follows the guidelines given here (end of the page): https://docs.bolt.cm/relationships

The problem is that Bolt interprets an id-based query with 1 id as something that should return a single result, and not an array. So normally I get an array, but when I have exactly 1 relationship, I don't get an array. This breaks result iteration using a for loop.

Here's my terrible workaround, but I'm hoping there's a better way:

   {# Bolt is too smart about array vs. single element... we always want an array! #}
   {% if relatedproj|length == 1 %}{% set relatedproj = [relatedproj] %}{% endif %}

Is there a better way to query relationships? Should Bolt be less aggressive about returning single results? Should Bolt support something analogous to 'returnsingle', but for multiple results?

For reference, the single-vs-multiple functionality is described here:
https://docs.bolt.cm/content-fetching#one-record-or-multiple-records

**Comment by SahAssar** [comment]
As far as I can see you are not using pagination, which is the primary purpose for using that way of retrieving related records. Have you tried just using something like this to get your relations?:

    {% set relatedproj = person.related('projects') %}

**Comment by martijneken** [comment]
Thanks for the suggestion. I am using this method because it allows to control of the query, specifically so I can use orderby and limit.

**Comment by SahAssar** [comment]
I'm just going to edit your title a bit to make it more clear what this is regarding :)

**Comment by SahAssar** [comment]
@rossriley Any way that we could "fix" this in 3.0? I get that is breaking some themes/sites, so doing it in either 3.0 or 4.0 seems best, right?

**Comment by SahAssar** [comment]
@rossriley Is this something that needs/wants to be fixed or is the reccommended fix to just `{% set relatedproj = relatedproj|length < 2 ? : [relatedproj] : relatedproj%}` or something like that?

**Comment by SahAssar** [comment]
Actually, Because of the great discussion in #5067 (which I didn't remember when posting the previous comment) I think that this will be covered there.
