### ISSUE TITLE
thumbs not working on php built-in server

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#3920]
This is Bolt 2.2.8 when the built-in php server is used, the thumbnail images are not generated (return 'error 404'), anyone can reproduce this error ?.
![captura de pantalla_2015-08-04_07-13-17](https://cloud.githubusercontent.com/assets/6233822/9058660/36687d58-3a79-11e5-829b-6f0778a649a7.png)

The embedded server is started in the root folder of the site as well:

```php -S localhost:8000```

p/d: I do not use grunt-php  #3629

**Comment by GawainLynch** [comment]
Have a look at [this page](https://docs.bolt.cm/howto/using-php-built-in-web-server)

**Comment by serweb-labs** [comment]
Great. Now it works. local.php content can not be incorporated directly index.php?
my sincere thanks :+1:

**Comment by serweb-labs** [comment]
by the way, although it is a test server, add also missing that protects ".db" files and ".twig"

**Comment by GawainLynch** [comment]
> local.php content can not be incorporated directly `index.php`?

Not really. The built-in PHP web server is for development work only, and having every request do a bunch of checks has a performance impact. Also, this is only a problem on Composer based installs, as git and archive based installs are fine without needing the `local.php` changes.

**Comment by serweb-labs** [comment]
You're right, let me clarify that my mistake was not to include the router on the call to server, I regret the inconvenience but surely someone will serve you in the future.

```php -S localhost: 8000 index.php```
 instead of
```php -S localhost: 8000```

Certainly I think there is a small error in the documentation of the link you provided me, in the "Git & Zip Installs" section where it says local.php should say index.php (unless I have misunderstood).

**Comment by GawainLynch** [comment]
You are absolutely correct, thank you! :+1: 

Fixed now :grin:
