### ISSUE TITLE
Internal Server Error after unspecific time

### ISSUE THREAD

**Issue by iMaxxx** [bolt/bolt#3921]
On one of my bolt pages I get an Internal Server Error after an unspecific time. I can restore a working backup and after a while (with no changes using back end) I get the error 500. All I have is the server error log:
```
05.08.2015 09:12:04 example.de [client 91.00.00.0] Premature end of script headers: index.php, referer: http://example.de/verwaltung
...
05.08.2015 09:56:45 example.de [client 91.00.00.0] Premature end of script headers: index.php, referer: http://example.de/verwaltung
...
05.08.2015 10:45:35 example.de [client 91.00.00.0] Premature end of script headers: index.php, referer: http://example.de/verwaltung

**Comment by GawainLynch** [comment]
This is almost always an Apache/OS configuration issue… File and directory permissions are the first place to check followed by resource limits.

**Comment by iMaxxx** [comment]
Thanks for quick reply, I will check this...

**Comment by iMaxxx** [comment]
Are the permissions already a possible reason after running 
```chmod -R 777 files/ app/database/ app/cache/ app/config/ theme/ extensions/

**Comment by GawainLynch** [comment]
Highly unlikely, I'd look at `index.php` and ensure that is 644 … 

It is a hard error to track down as it means nothing specific, just that something is wrong on your system.

**Comment by iMaxxx** [comment]
It is 644. 
Yes I know, but I don't get any further more specific error message.

**Comment by iMaxxx** [comment]
I found out, that it is enough to delete bolt.db and bold.db-journaled and restore my working bolt.db. Could cause the .db file size the problem?

**Comment by GawainLynch** [comment]
I would imagine it would have to get very large… If you are seeing the `-journal` file then that is a very good indicator of the problem… that should be removed by Sqlite at the end of the transaction. So either you're somehow hitting a resource limit, your file system is dying/partially corrupted, or the storage hardware controller is throwing faults.

**Comment by iMaxxx** [comment]
But I'm also not able to import it in to MySql server:
```
INSERT INTO `bolt_log_system` VALUES(18150,200,'2015-06-01 19:25:36','Checking permission query ''contenttype:news'' for user ''User2'' with contenttype '''' and contentid ''''','','/verwaltung/','dashboard','2003:74:e3b:f600:b9bc:fd06:ff83:66fb','authentication','');
MySQL meldet: Dokumentation

#1062 - Duplicate entry '18150' for key 'PRIMARY'

**Comment by GawainLynch** [comment]
The first column is a unique key, and as such can't have duplicates. Hence the error.

**Comment by iMaxxx** [comment]
Yes, but why do I have this error. 'bolt_log_system' is a system table.

**Comment by iMaxxx** [comment]
I justed opened the sql dump. Is it possible that you cannot clear the system log via bolt back end? I cleared it manually via back end and after a reload all entries were back. And in my dump are also all entries.

**Comment by iMaxxx** [comment]
This was my config.yml
```
debug: false
developer_notices: false
debug_show_loggedoff: false
debug_permission_audit_mode: true
```
permission audit was writing all in my system log but debug mode is disabled.
