### ISSUE TITLE
Symfony 2.5 : An error occurred while loading the web debug toolbar (404: Not Found)

### ISSUE THREAD

**Issue by videni** [bolt/bolt#3922]
this still happens for every page I request, even though I dig in , but still don't find the answer, I almost look through all questions related to this in stackoverflow.com, none of them can solve the problem, any ideas please?

**Comment by GawainLynch** [comment]
What version of Bolt?

**Comment by videni** [comment]
sorry, what is the Bolt?

**Comment by GawainLynch** [comment]
Um… :grin: 

Bolt is the software product this issue tracker is for.

**Comment by bobdenotter** [comment]
The Bolt is the Best™! :8ball:

**Comment by videni** [comment]
sorry , a big mistake, I thought this is symfony repo for I saw a same question here, forget to check the repo name.

**Comment by GawainLynch** [comment]
No stress mate… Happy to see you visit :+1:

**Comment by videni** [comment]
thanks, I see , Bolt is a relative to symfony.
