### ISSUE TITLE
For some obscure reason, Pages get filled with dummy content in ALLCAPS titles. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3927]
It boggles the mind. :8ball: 

see screenshot:

![screenshot_2015-08-05_21_25_26](https://cloud.githubusercontent.com/assets/1833361/9095657/b6268054-3bb8-11e5-819e-cca13e966c11.png)

**Comment by bobdenotter** [comment]
This is really weird.. It seems to be happening when saving a "Page", and only with a page. Not with other contenttypes.. 

See: 

![screenshot_2015-08-05_21_54_44](https://cloud.githubusercontent.com/assets/1833361/9096377/0a404180-3bbd-11e5-98f7-a347bdef4e51.png)

**Comment by bobdenotter** [comment]
Hmm, it's actually firing PRE_SAVE events from the acceptence tests, in normal use: 

From `tests/codeception/_data/extensions/local/bolt/tester-events/src/StorageEventTests.php:`

```

            if ($event->isCreate()) {
                // Make the new title uppercase
                $record->setValue('title', strtoupper($values['title']));

                // Add a unique paragraph to the end of the teaser
                $record->setValue('teaser', $values['teaser'] . '<p>Snuck in to teaser during PRE_SAVE on create: ' . date('Y-m-d H:i:s') . '</p>');
            } else {
                // Uppercase the first character of each word
                $record->setValue('title', ucwords(strtolower($values['title'])));

                // Add a unique paragraph to the end of the teaser
                $record->setValue('teaser', $values['teaser'] . '<p>Added to teaser during PRE_SAVE on save: ' . date('Y-m-d H:i:s') . '</p>');
            }
```

**Comment by GawainLynch** [comment]
We can't fire those unless you run the tests… it can get left behind on a fatal.

**Comment by bobdenotter** [comment]
Do you mean those events **couldn't** or **shouldn't** fire in normal use? Because they really do. :-)

**Comment by GawainLynch** [comment]
They can fire on normal use… if the extension wasn't clean up after a run. But no, they absolutely can't fire from `tests/codeception/_data/extensions/local/bolt/tester-events/`

**Comment by bobdenotter** [comment]
>  if the extension wasn't clean up after a run.

Ugh, that was it.. The extension was still active. :-/ 

Problem solved.
