### ISSUE TITLE
Is the new session code supposed to set 6 cookies? 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3929]
See screenshot:

![screenshot 2015-08-05 22 01 05](https://cloud.githubusercontent.com/assets/1833361/9096473/96bc90be-3bbd-11e5-8ad0-7e96ba419cf7.png)

**Comment by CarsonF** [comment]
Is that after clearing cookies?

Could be a different with `.` prefix in domain name. Maybe `.` was set before and it isn't now

**Comment by CarsonF** [comment]
I think 3 of those are valid. The ones without `_baa..` are from before merge.

**Comment by bobdenotter** [comment]
@CarsonF You're partially right. After clearing the cookies and logging on again, only 4 of them get set.. 
Note that the last two only get set on `/bolt/prefill`, not on other pages. 

![screenshot 2015-08-05 22 20 59](https://cloud.githubusercontent.com/assets/1833361/9096894/73631bbc-3bc0-11e5-810c-78e1f697e1f6.png)

**Comment by rarila** [comment]
Don't tell the Cookie Monster!
:cookie::cookie::cookie::cookie::cookie::cookie:

**Comment by CarsonF** [comment]
Yeah so the first 3 are valid. It's just the last one with the different domain

**Comment by CarsonF** [comment]
What is `$app['sessions.default_options']['cookie_domain']` set to?

**Comment by bobdenotter** [comment]
Is that correct? 

```
dump($app['sessions.default_options']);
```

=> `null`

**Comment by CarsonF** [comment]
Is that after `$app->initialize();`?

**Comment by bobdenotter** [comment]
I inserted that right before the `return $this->render('prefill/prefill.twig', $context);` statement in `src/Controller/Backend/General.php`, so I would assume it is. :-)

**Comment by CarsonF** [comment]
Ugh stupid wrong key name.

`$app['session.default_options']['cookie_domain']`

**Comment by bobdenotter** [comment]
Sure? `dump($app['session.default_options'])` is still `null`. :-)

**Comment by GawainLynch** [comment]
![cookies](https://cloud.githubusercontent.com/assets/1427081/10122299/2c261752-650c-11e5-9a18-6558819aa67f.png)

**Comment by CarsonF** [comment]
@GawainLynch Are you saying the CSRF cookies are a problem?

**Comment by GawainLynch** [comment]
Just that is looks odd the way it's setting them, and the volume(s) involved.

**Comment by CarsonF** [comment]
Like the 3 for `/bolt` path?

**Comment by GawainLynch** [comment]
Yeah, all with subtle path/domain differences

**Comment by CarsonF** [comment]
Ok so trailing slash presents an interesting problem. We redirect requests with trailing slashes at `kernel.request priority 32`, but `SessionListener` starts session at priority `128`. So we need to do something about that. Not sure the best option yet.

The leading period on domain is the other thing. It's confusing, because I'm not sure if it happens automatically. We could try to enforce it though

**Comment by GawainLynch** [comment]
> The leading period on domain is the other thing. It's confusing, because I'm not sure if it happens automatically. We could try to enforce it though

I'm just hesitant to start forcing things down Symfony's virtual throat…

**Comment by CarsonF** [comment]
Trailing slash problem: #4157

> I'm just hesitant to start forcing things down Symfony's virtual throat…

No it's not their throat, it's cores. It would be for the `setcookie` call.

**Comment by GawainLynch** [comment]
Oh right! That I am in favour of

**Comment by CarsonF** [comment]
#4158 for leading period on domains

**Comment by wysow** [comment]
What the status of this, just tried and got this:
![capture d ecran de 2015-11-06 15 23 47](https://cloud.githubusercontent.com/assets/632747/10999101/79d640b4-849a-11e5-9650-deef76a85dbb.png)

As I'm new to Bolt I can't say if ti's normal behavior or not, what do you think?

**Comment by GawainLynch** [comment]
It's relying on some upcoming work by @CarsonF… /me nags @CarsonF again :stuck_out_tongue_winking_eye:

**Comment by wysow** [comment]
My bad didn't take a look at `assignee` field... :no_mouth:

**Comment by GawainLynch** [comment]
Zero stress mate… it just gives me another chance to nag @CarsonF again… and again :smiley:

**Comment by CarsonF** [comment]
But then I ask @GawainLynch if is the top priority and he says no, so here we are. 

@wysow that looks right.

**Comment by GawainLynch** [comment]
@CarsonF the screenshot by @wysow is correct, the one that @bobdenotter posted does legitimately highlight somewhere this isn't working properly though.

But more so, we have some issues with the session stuff that are blockers… creeping up the priority chain.

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by GawainLynch** [comment]
Yes… We need a "Waiting on Carson" tag I think…
