### ISSUE TITLE
Attach assets from extensions. New way.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3932]
I suppose this way of assets attaching has lots of limitations:
```php
$request->attributes->set('allow_snippets', true);
$this->addCss('assets/extension.css');
$this->addJavascript('assets/extension-plugin.js', true);
$this->addJavascript('assets/extension-logic.js', true);
```
1. Some plugins should be called *before* body (in head section), some plugins should be called in the end of body, some plugins should be called after jquery loads. And also i'm not sure that everybody wants their plugins to be included in big bolt.js file. So i suppose it's very nice to have some sockets, where assets could be put. like 'head', 'end', 'bolt.js' (names are optional ;)

2. So my suggestion is to make an array (or even separate yaml file) with extension's assets config, which is called by app method that gathers all extensions data and executes all tasks.
```php
// Somewhere deep in the extension...
        static $assets = [
            ['css', 'css_include.css', 'head'],
            // not sure if any css could be loaded anywhere else except head
            ['css_include.css'],
            // or
            'css_include.css',
            
            ['js',  'html5shiv.js', 'head'],
            // all parameters put in a row
            ['js',  'separate_plugin.js', 'end', 'defer'],
            // or this way
            [ 'separate_plugin.js', [
                'asset_type' => 'js',   // or autodetected from file extension
                'socket'     => 'end',  // or 'tail' ? or 'butt'? let there be some humor ;)
                'which_end'  => 'back', // 'all' / 'back' / 'front'. All by default.
                'defer'      => true,   // optional parameter
            ]] ,
            [ 'separate_plugin.js', [
                // it takes grunt work and i can't see any advantages of mixing all extensions' plugins but..
                'socket'     => 'put_it_to_bolt.js_please',
            ]],
        ];
// And later somewhere it will place all required files in html markup and probably mix neccessary ones to bolt.js.
```

Also there could be a socket for js templates, it's optional but it's being used often and often each day. 

Also we can surround all scripts by container ```<div id="_bottom_scripts" />``` . It will be lovely in firebug =)

**Comment by GawainLynch** [comment]
You're using those functions incorrectly… This will insert the JavaScript in the `<head>`

```php
$this->addJavascript('assets/extension-plugin.js', ['late' => false]);
```

This will insert it at the end of the HTML:
```php
$this->addJavascript('assets/extension-plugin.js', ['late' => true]);
```

Alternatively you can inject in many varied places:
```php
use Bolt\Asset\Target;

$html = '<script src="https://yoursite.com/assets/extension-plugin.js"></script>';
$this->app['asset.queue.snippet']->add(Target::BEFORE_JS, $html);
```

**Comment by Boorj** [comment]
@GawainLynch but it's an answer only to the first part of issue.
* If you store all asset includes in an array, you won't have a problem (or with *less probability* have) with changing the methods in your API. So it adds an independency
* Also my way allows to store all includes in ```assets.yml``` and extension author doesn't have to know what method does he need to attach assets in current version of bolt. 
* it has easier syntax
* it's easier to make tutorial for yaml options than for several functions with their arguments))

**Comment by GawainLynch** [comment]
Then it belongs in an extension itself :grin:

**Comment by Boorj** [comment]
Anyway it's easy to implement and it makes extensions development little bit easier.

**Comment by Boorj** [comment]
Extension's config is stored in yaml (and _local.yml) and assets should also be loaded from yml. It will ease porting extensions to new versions of bolt. Also it's much more easy to use yaml instead of functions => thus it will make extension making easier => people will love bolt more.

**Comment by GawainLynch** [comment]
It is extension logic that belongs in the extension.

**Comment by Boorj** [comment]
Anyway  somewhere in the core you process all those assetsm that  fieldtypes do attach. And then collect all required files to proper injections. Why can't you just collect all extensions' yaml resources and parse them. It's just a more convenient way to set asset attaching. Is it?

**Comment by GawainLynch** [comment]
We do, we allow you to queue assets:
```php
 $this->app['asset.queue.file']->add('javascript', 'boorj.js', ['priority' => 10, 'attrib' => 'defer']);
 $this->app['asset.queue.file']->add('stylesheet', 'boorj.css', ['priority' => 42]);
```
That will give you both, with some degree of ordering based on who else pick the needed priority.

Past that you start to run into what we want to do for v3 and have proper asset management… But both your solution and the v3 proposals **really** hurt performance.

**Comment by Boorj** [comment]
Yes probably yes. 
Actually, i just assume that it will increase simplicity of extension development and not sure that + 2-3 yaml parses will kill the perfomance.
I'll be waiting for v3 =)

**Comment by GawainLynch** [comment]
Closing as this is essentially being tracked by the asset work for v3 in #1913 and #2109
