### ISSUE TITLE
Allow extensions perform fieldtype pre-save and post-read actions

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3933]
If you create an extension with new fieldtype, it needs an ability to perform conversions to/from database storage types.
For example, you create fieldtype, that uses array. Its values are stored as text. So you need to perform  clean (striptags, for example) and pack (json_encode / serialize / implode) on save. On read it needs unpack (unserialize / json_decode / explode) and, probably, some formatting.

**Comment by GawainLynch** [comment]
The already can.

**Comment by Boorj** [comment]
#### No it can't. 
Only several events are triggered, and it goes not the proper way.
I can only add this code to Extension::initialize:
```php
$this->app['dispatcher']->addListener(StorageEvents::PRE_HYDRATE, $pre_hydrate_listener);
```
But it listens to ALL db requests, even with those DB requests that i'm not interested in = those contenttypes that don't use my fieldtype. Probably i can make a handler like that: 
```php
        $pre_hydrate_listener = function (HydrationEvent $a)
        {
            $entity = $a->getSubject();
            $arguments = $a->getArguments(); //['data' => $data, 'repository' => $this]
            $data = $arguments['data'];
            /* @var \Bolt\Storage\Repository $repository */
            $repository = $arguments['repository'];

           // ...  HERE I KNOW IF IT'S NEEDED CONTENTTYPE AND TRANSFORM FIELDS
        }
```
but it's not the proper way to do that.

So algorythm that uses events is ugly in this task.
On [this line in Content.php](https://github.com/bolt/bolt/blob/master/src/Content.php#L148) there's a loop that handles each standart type transform. 
For example, for geolocation it's 
```php
    if (!empty($this->values[$field]['latitude']) && !empty($this->values[$field]['longitude']))
        $newvalue[$field] = json_encode($this->values[$field]);
    else
        $newvalue[$field] = '';
```

##### So my goal is 
to allow **fieldtypes set by extension** to add their own transform functions to this list.  
![6](https://cloud.githubusercontent.com/assets/2145313/9107858/5d1d3824-3c4c-11e5-86a1-5f3d5df3b216.jpg)

**Comment by Pinpickle** [comment]
I believe this functionality is landing in 2.3 with the massive storage refactor.

**Comment by GawainLynch** [comment]
> I believe this functionality is landing in 2.3 with the massive storage refactor.

It is, and the `Repository`s and table definitions are already extensible.

**Comment by rossriley** [comment]
Sorry, i thought I already replied to this, but i was on an Island yesterday with dodgy wifi.

So the hydrate events aren't really the place to do this since as you've found they aren't field specific. 

The way the new field types are designed is that each new field type (or if you want to replace an existing field type too) can implement handlers for the key events.

So we have so far: `load()`, `query()`, `persist()`, `hydrate()` and any field type can implement these handlers and transform the specific data received. So as a simple example, lets say I wanted to rewrite all values `foo` to `bar` whenever a field is hydrated

    public function hydrate($data, $entity, EntityManager $em = null)
    {
        $field = $this->mapping['fieldname'];
        $value = $data[$field];
        if ($value == 'foo') {
            $entity->$field = 'bar';
        } else {
            $entity->$field = $value;
        }
    }

So the hydrate handler passes in both the raw data and the entity that we are going to hydrate, and as you can see we either hydrate our entity with the raw value, unless it's `foo` then we set it to `bar`

Similar transformations can happen at the other events too, so we could do the revere on persist, and swap out all our `bar` values back to `foo`

**Comment by Boorj** [comment]
And.. at the moment events are emmited only for users table. Contenttypes are with an old verson, not with Repository.php.

#### request for comment:
By the way, i think there should be another transformer that is called after js code sends serialized data from backend. So extension developer doesn't have to go to the core to tweak the way server receives the data.

**Comment by maiorano84** [comment]
I too am curious about this one. As it stands, I'm creating a field type that needs to store x and y coordinates as an array. I can modify the information via the PRE_SAVE event, but this only fires for new records (at least for version 2.2.4, I don't know if this was addressed in later releases).

If the FieldInterface - or even the Base Field - had methods to override values for encoding/decoding purposes, that would be ideal.

**Comment by GawainLynch** [comment]
@maiorano84 sorry I some how missed your comment. Yes, 2.2.x and current master are significantly different in the storage layer.

@Boorj it's a work in progress cutting this over, but [this branch](https://github.com/bolt/bolt/commits/refactor/record-edit-and-save) is dong the work for backend editing to be handled by the new layer.
