### ISSUE TITLE
Error generated with attempting to use Liquibase with BOLT

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3936]
To manage database changes, we're using Liquibase, which injects 2 tables into the bolt database: DATABASECHANGELOG & DATABASECHANGELOGLOCK.

The latter includes a bit field. When I try to bring up bolt after these tables have been create, I get the error:

Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

To fix the issue, I had to add the following line to Database/initListener.php (at line 32):
$db->getDatabasePlatform()->registerDoctrineTypeMapping('bit', 'integer');

2 questions:
Why would Bolt care about non-Bolt tables?
Can you incorporate this fix into the Bolt source?

**Comment by GawainLynch** [comment]
> Why would Bolt care about non-Bolt tables

@bobdenotter can you remember the history on this one?

**Comment by bobdenotter** [comment]
> Why would Bolt care about non-Bolt tables?

I believe this is a bug, plain and simple. We've noticed it before, but we never got round to fixing, yet.

**Comment by bobdenotter** [comment]
@mhodges-cainc Your fix might fix it in your case, but I think this is a good time to look into why it crawls and compares _all_ tables, and not just the Bolt ones.

**Comment by GawainLynch** [comment]
Related to #2769

**Comment by GawainLynch** [comment]
Fixed in #3949
