### ISSUE TITLE
Height option for multiple select field

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3943]
Could you add height option for ```<select multiple/>``` ? If you have 50 entities in one small box - it's hard to use.
Also, btw, setting **rows** in textarea is a nice option (for a case if i don't want to use height in px).

**Comment by SahAssar** [comment]
If we go with #4865 and therefore go with select2 for those select fields this should be fixed, right?

**Comment by Boorj** [comment]
i think yes, select2 still can't guess needed height

**Comment by rarila** [comment]
AFAIK you only can set this with css. – Did you notice that you can enter characters to filter the list?

**Comment by Boorj** [comment]
> AFAIK you only can set this with css.
Yupp, aaand.. what's so bad in `style='min-height: 200px'` or `max-height` or `height` ?

> Did you notice
and again - yupp. But sometimes if you do have only 10 options it's faster to do one click, not typing or scrolling + click.

But you can close it, i suppose.

**Comment by rarila** [comment]
Wouldn't it be better to get that done upstream?

**Comment by Boorj** [comment]
i can do that, but want to know community opinion.

**Comment by SahAssar** [comment]
Fixed in #5441, see 
![image](https://cloud.githubusercontent.com/assets/5096632/17154805/d49cc164-5382-11e6-95df-a10502507067.png)
