### ISSUE TITLE
Autosize for textarea fields

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3944]
I think it could be very nice as option - textarea autosize. It expands if your text is big enough reach the bottom of a textarea. So there's no more problem with small textareas or big but empty ones.

here's the code in _coffee_ & _javascript_

``` coffee
    AutoGrowTextArea = (e) ->
        textField = e.target
        if textField.clientHeight < textField.scrollHeight
            textField.style.height = textField.scrollHeight + 'px'
            if textField.clientHeight < textField.scrollHeight
                textField.style.height = textField.scrollHeight * 2 - (textField.clientHeight) + 'px'
        return

    # if using underscore.js  or  jquery.throttle-debounce.js 
    $('textarea').keyup _.throttle(AutoGrowTextArea, 900)
    # else
    $('textarea').keyup AutoGrowTextArea
```

and js one:

``` js
    AutoGrowTextArea = function(e) {
      var textField = e.target;
      if (textField.clientHeight < textField.scrollHeight) {
        textField.style.height = textField.scrollHeight + 'px';
        if (textField.clientHeight < textField.scrollHeight) {
          textField.style.height = textField.scrollHeight * 2 - textField.clientHeight + 'px';
        }
      }
    };
    $('textarea').keyup(AutoGrowTextArea); //no throttling, but should
```

_tip_ :  need to trigger that AutoGrowTextArea function on start - for a case if a content is loaded and it's bigger than viewport of textarea.

**Comment by SahAssar** [comment]
I'd be all for this with some sort of sensible max, like 100vh.

**Comment by Boorj** [comment]
80vh will be enough, but i think you meant that.

**Comment by rossriley** [comment]
I'm assuming we're talking about vertical hectares here.

**Comment by bobdenotter** [comment]
Handy, for when you're going to write the next War and Peace.

**Comment by Boorj** [comment]
handy for 90% of my clients who post some news by copypasting from ms word)
@rossriley - viewport height percents, if you were serious :)
Happy birthday)) :birthday: :gift:

**Comment by SahAssar** [comment]
Closing this as it isn't a bug and has been open without activity for over a year. Feel free to reopen when there is a PR/solution and it needs tracking! :)
