### ISSUE TITLE
Translations not loading at all throughout the back end. Think I've found the cause.

### ISSUE THREAD

**Issue by philbates35** [bolt/bolt#3950]
I have installed the SimpleForms extension, which means I need to set up `mailoptions` in config.yaml. There's a helpful flash message that tells me this at the top of every screen in the backend.

Today I ran `vendor/bin/nut cache:clear` and no matter what I did after doing so, no translations were loading throughout the back end, and instead just showing `label.key.name.example` instead. After some debugging, I'm pretty sure I've found the reason:

Summary:
* The flash message about setting 'mailoptions' tries to load a translation.
* However, all resources have not yet been added.
* As part of the label retrieval process, it gets what it thinks are all the available resources (which is completely empty) and caches it.
* Subsequent requests for translation files (after the resources have been added, and the translations are theoretically available) see that there is a cached translation file (which upon manual inspection contains no translations) and tries to load it from the cache.
* As the cache is empty, it can't find a match and therefore just displays the translation key.

Temporary Fix to prove cause:
* Comment out the translation [request](https://github.com/bolt/bolt/blob/v2.2.8/src/Application.php#L434)
* Clear the cache using `vendor/bin/nut cache:clear`
* Reload the backend and all translation load successfully.

Quick explanation of the backtrace:
* The [flash message](https://github.com/bolt/bolt/blob/v2.2.8/src/Application.php#L433) in question is set in `Bolt\Application::initMailCheck()`.
* Setting the flash message results in a call to `Bolt\Translation\Translator::__($error)` [here](https://github.com/bolt/bolt/blob/v2.2.8/src/Application.php#L434).
* However - the crucial point is that the translation resources aren't loaded until `Bolt\Provider\TranslationServiceProvider::boot()` is called. In terms of the application, `Bolt\Application::initMailCheck()` is called before the [translation resources have been added](https://github.com/bolt/bolt/blob/v2.2.8/src/Provider/TranslationServiceProvider.php#L36).

**Comment by GawainLynch** [comment]
See #3948… do you have MenuEditor installed, and any other extensions?

**Comment by philbates35** [comment]
Ah dammit I searched and couldn't find a similar issue! Sorry about that.

However in my case I am not using MenuEditor. The only extension I am using is bolt/simpleforms, as I mentioned in the OP. I am using bolt/bolt 2.2.8.

I'm pretty sure that the issue is in the bolt core rather than the extension though, for the following reason:

* `Bolt\Application::initMailCheck()` is always called by `Bolt\Application::initialize()`.
* `Bolt\Application::initMailCheck()` calls `Bolt\Translation\Translator::__($error)` if there's no `general/mailoptions` config set and `Bolt\Extentions::hasMailSenders()` is true [here](https://github.com/bolt/bolt/blob/v2.2.8/src/Application.php#L432)
* Bolt's request cycle means this all happen before it calls the `boot` method on any Service Providers. It is the `boot` method on the TranslationServiceProvider that adds the resources.

So the resulting early call to `Bolt\Translation\Translator::__($error)` is all deteermined by Bolt. Granted, the extension is indirectly responsible for the early call to `Bolt\Translation\Translator::__($error)`, but only by being installed (it's presence is enough to make it happen, it's not directly making the early call itself) - this results in `Bolt\Extentions::hasMailSenders()` to return true, which means the flash message should be displayed, resulting in the early call to the translator.

**Comment by GawainLynch** [comment]
Yeah, that's actually a good call @philbates35 and I have sent #3953 in to handle it properly. 

Basically that function call doesn't belong outside of the request cycle.

**Comment by GawainLynch** [comment]
Fixed in #3953
