### ISSUE TITLE
Allow themes to override config parameters

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#3951]
While porting a theme, I had to change the value of `listing_records` to match my theme layout. I tried to change it using the config.yml in theme, but it seems it isn't supported. 

So, themes should be able to override, at least, this parameter. To keep it organized and safe, I would place theses overrides in a specific section in the config file, like, `override`.

**Comment by bobdenotter** [comment]
Are you sure it doesn't work? It really should work, I think.. see: https://github.com/bolt/bolt/blob/master/theme/base-2014/config.yml#L23

Two things to check: 

 - Have you spelled `listing_template` correctly? (so, not `listing_records`)
 - Have you tried clearing the cache in Bolt?

**Comment by pygillier** [comment]
Bob, 

I would like to change the number of records displayed in listings, not the template itself :smile:

**Comment by bobdenotter** [comment]
Oh, right.. Might be good to add those to the values to override in the theme's `config.yml`. I'm not a fan of an extra section for overrides in the config, but would like to keep them on the same level in the config file..

Is this something you'd like to have a go at so you can make a PR, or should I handle it?

**Comment by pygillier** [comment]
I'll try a PR

**Comment by pygillier** [comment]
Got the line where the value is retrieved : https://github.com/bolt/bolt/blob/master/src/Controller/Frontend.php#L250

So, the question is : which one takes precedence over the others ? 

1. Theme > Content-Type > General ? 
2. Content-Type > Theme > General ? 

I would say number 1

**Comment by bobdenotter** [comment]
Theme has the highest precedence. If that isn't set, it uses the value from contenttype.. If that also isn't set, then it should use the global value.
