### ISSUE TITLE
Cannot set session ID after the session has started.

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3954]
Presume this is something to do with extensions handling session data, as there are a few extensions on this site.

Checking out 2.2 and everything works, checkout master:

```
Bolt - Fatal error.
Class: LogicException
Message: Cannot set session ID after the session has started.
Code: 0
Bolt\Session\SessionStorage->setId()
[root]/vendor/symfony/http-foundation/Session/Session.php, line 199

Symfony\Component\HttpFoundation\Session\Session->setId()
[root]/src/Session/SessionListener.php, line 61

array:1 [▼
  0 => "oz3h8sD9GS7lWmwJu8nsTrrnZ4viKAIJ"
]
Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
[root]/vendor/symfony/event-dispatcher/EventDispatcher.php, line 53

Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
[root]/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php, line 124

Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
[root]/vendor/symfony/http-kernel/HttpKernel.php, line 128

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]/vendor/symfony/http-kernel/HttpKernel.php, line 68

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]/vendor/silex/silex/src/Silex/Application.php, line 581

Silex\Application->handle()
[root]/vendor/silex/silex/src/Silex/Application.php, line 558

Silex\Application->run()
[root]/index.php, line 48

[]
```

**Comment by CarsonF** [comment]
I first guess is the session is getting started before the session listener has a chance to set the session ID from the cookie.

@GawainLynch Can you log a stacktrace on SessionStorage::start see what's causing it to start?

I think we could update the listener to check if the session is started with a different ID than the one in the cookie and close it, and start it again with the correct ID. It's not addressing the root problem, but if it's needed to maintain BC then I'm ok with it.

**Comment by decebal** [comment]
Same problem here, I got the problem after trying to install an extension, but quited admin while it was doing something I didn't like.

**Comment by GawainLynch** [comment]
@decebal are you running master?

**Comment by decebal** [comment]
yes,v 2.2.8

**Comment by GawainLynch** [comment]
OK… 2.2.x isn't master, that is a released version. That will be a separate issue. This is specific to master as we've implemented a custom session handing.

If you could file a separate issue with as much information as you have, that would be awesome :+1:

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by CarsonF** [comment]
@GawainLynch Close? Can we force sessions to wait until request cycle since this is 3.x now?

**Comment by GawainLynch** [comment]
Yeah, it is much harder to do now in extension land… and given that this was during in the time that `master` was headed for a `v2.3` is no longer relevant in BC terms.
