### ISSUE TITLE
Mixed content error on video preview

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#3955]
Having my site behind HTTPS (frontend & backend), when I want to insert a video in an entry, Firefox (IE/Edge/Chrome should do the same, not tested yet) prevents preview to be displayed and console shows a "mixed active content" error.

It's due to HTTP/HTTPS mixing : embedly is called over http only.

Got it !

It's in https://github.com/bolt/bolt/blob/master/app/src/js/modules/video.js#L87
embed.ly API is called specifically on http, It should be called without scheme

(as is it javascript, no PR for me this time :smile: )

**Comment by bobdenotter** [comment]
PR's are in the queue. Thanks, @pygillier!
