### ISSUE TITLE
Editing write protected files in Bolt backend deletes contents/corrupts file.

### ISSUE THREAD

**Issue by hansgrinwis** [bolt/bolt#3962]
Note upfront: I know I should write-enable these files!

Bug summary: 
Editing write protected files in Bolt backend deletes contents/corrupts file.

Specifics: 
Example: URL http://<<server-address>>/Bolt/bolt/file/edit/theme/<<theme-name>>/_aside.twig
Bolt version: 2.2.5
Installation method: Option 2: The traditional way, using (S)FTP
Browser: IE 11.0.9600.17905 (update version 11.0.21)
Tested in other browsers: Chrome 44.0.2403.155 m (64-bit), Firefox 40.0

Steps to reproduce:
Open a (theme) file that is write protected in the Bolt backend editor (Bestandsbeheer/Bekijk-bewerk templates). An note appears that Bolt cannot save the file. (Het bestand '<<theme-name>>//_aside.twig' is niet schrijfbaar. Gebruik je eigen editor om wijzigingen in dit bestand aan te brengen.) 

Expected result:
Bolt would not touch (i.e. modify) the file.

Actual result:
All of a sudden the filesize is 0 bytes. Browser refresh results in "Whoops! There was an error."

![bolt1](https://cloud.githubusercontent.com/assets/13786613/9259440/80830d7e-4201-11e5-8644-2bf4d85e13ee.png)
![bolt2](https://cloud.githubusercontent.com/assets/13786613/9259444/83f319cc-4201-11e5-9399-8c6f89b79703.png)
![bolt3](https://cloud.githubusercontent.com/assets/13786613/9259448/862cbe64-4201-11e5-8258-1f99db047133.png)
![bolt4](https://cloud.githubusercontent.com/assets/13786613/9259452/87ad7eae-4201-11e5-8e6c-64f0ab7e9993.png)

**Comment by bobdenotter** [comment]
I'm going to try and reproduce this. This is weird though, because if Bolt is not allowed to _write_ the file, Bolt shouldn't even be _able_ to clear or corrupt it. 

 - What version of PHP is the server running? 
 - Apache? Nginx? 
 - Linnux? Windows?

**Comment by hansgrinwis** [comment]
The server is a Synology NAS (DS213+):
Linux 2.6.32.12 #5592 SMP Wed Jul 29 14:39:24 CST 2015 ppc
Apache 2.2.29 (Unix)
PHP 5.5.26

**Comment by GawainLynch** [comment]
I think this is due to Synology bugs… those things have caused people grief before. If the web server can't write to a file, it can't write to a file.

**Comment by hansgrinwis** [comment]
@GawainLynch I think you have a fair chance at being right. 

I installed XAMPP on a Windows 7 virtual machine and whatever security setting I tried on the file at hand, as soon as Bolt said it could not write to the file, the file would remain untouched. I have no easy access to (and experience with) other setups, so cannot test that. 

I can live (and eventually, agree) with the fact that it is not a Bolt issue. On the other hand, I am unsure as how to report this to Synology. I guess they need very detailed info on how Bolt accesses the file. This is info I do not have.

@bobdenotter Still want to try and reproduce?

**Comment by GawainLynch** [comment]
If I remember correctly, Synology runs its own custom build of Apache + PHP… So if that is the case, probably just reporting that a PHP application failing to write to a file that it doesn't have access to it causing it to be truncated to zero length.

From our end, short of getting a Synology ourselves (and having the time to invest) I don't know there is too much we can do.

**Comment by GDmac** [comment]
if i recall, for translation and config edit, if the files are not writable, then the save button is disabled / greyed out. (However, OTOH, that would not make these kind of issue show up / be found)

**Comment by hansgrinwis** [comment]
@GDmac It happens before that! As soon as the content of the file is displayed, including a messsage that Bolt cannot write to the file, it is corrupted.

Thanks to all for thinking with me. For now I'll go with @GawainLynch and consider it a Synology bug!
