### ISSUE TITLE
Not possible to give "view" permission to "owner" role

### ISSUE THREAD

**Issue by iMaxxx** [bolt/bolt#3971]
In addition to issue #3909 it is also not possible to give someone view permissions with owner role. 
I have users they should only view their own entries.

**Comment by bobdenotter** [comment]
Hi, 

I'm not sure this one makes sense to me. I'm trying to think of a scenario, where it is not confusing that somebody is not able to edit their own entries. 

Why not make them owned by an admin or someone else, and then only give 'view' permission to these users?

**Comment by iMaxxx** [comment]
they should be be able to edit them, but also should only see own entries and no entries from other users.
permissions.yml snippet 
```
    unternehmen:
        edit: [ admin,chief-editor,owner ]
        create: [ admin,chief-editor]
        publish: [ chief-editor,admin ]
        depublish: [ chief-editor,admin ]
        delete: [ admin ]
        view: [ admin,chief-editor,owner ]
        change-ownership: [ admin ]

**Comment by GawainLynch** [comment]
This wouldn't be possible without a massive degradation in performance, as the "owner" role is specific to a record, from my comment on https://github.com/bolt/bolt/issues/3909#issuecomment-126710816
```
    /**
     * A special role that is used to tag the owner of a resource; it is only
     * valid for permission checks that are specific to one particular content
     * item.
     */
    const ROLE_OWNER = 'owner';
```
Just for listing routes (and associated menu items), as they are for ContentTypes, to change the route record lookup queries we'd need to know if you're just wanting owned records, or owned plus permission by that contenttype, and would have to repeat queries several times.

Unless someone else has a better idea?

**Comment by SahAssar** [comment]
Closing this as there seems to be no good solution as @GawainLynch indicated.

Please feel free to reopen if anyone comes up with an idea or feels this is crucial :)
