### ISSUE TITLE
[RFC] How to handle releases / tags on the extension website. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3980]
As yo know, @Mikescops is working on a new site for extensions.bolt.cm. 

He's working on a new functionality that allows you to see release notes on the front end. For example: 

![screen shot 2015-08-17 at 15 14 46](https://cloud.githubusercontent.com/assets/1833361/9305591/d107ca2a-44f2-11e5-9ec9-9215c90f0d97.png)

Thing is: The script Corentin's using only retrieves **releases**, and not **tags**. This might cause a small discrepancy: https://github.com/bacbos/bolt-menu-editor/releases

![screen shot 2015-08-17 at 15 17 40](https://cloud.githubusercontent.com/assets/1833361/9305629/209cb12c-44f3-11e5-8004-04ff2e924813.png)

Because the latest version is not 2.1.4, but 2.1.5, it might be slightly confusing.. What should we do about this? Options:

 - Fix the script, so it also gets tagged versions, and not just releases. Even though they won't have descriptions.
 - Educate people to only use "releases" instead of "tags" 
 - Force this behaviour change by only listing "releases", instead of both releases and tags. 

.. or something else?

**Comment by GawainLynch** [comment]
I for one don't, and would prefer to not, use GitHub releases on mine. I do everything on the command line.

**Comment by bobdenotter** [comment]
Closing this one! :gun:
