### ISSUE TITLE
[RFC] How to handle extensions with a lot of releases.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3981]
For extensions that have a bunch of releases, the list gets quite long.. 

![screen shot 2015-08-17 at 16 00 36](https://cloud.githubusercontent.com/assets/1833361/9306659/f4a65576-44f9-11e5-8b61-d7865fe24be6.png)

How should we handle this? If it were up to me, I'd like to show just one button for the latest release, and a link to show "all other" releases. My gut feeling tells me, 99% of the time people should want to install the latest stable version of an extension.

**Comment by GawainLynch** [comment]
> I'd like to show just one button for the latest release, and a link to show "all other" releases.

:+1: 

Would it be easy/possible to make it part of the modal?

**Comment by bobdenotter** [comment]
> Would it be easy/possible to make it part of the modal? 

Yes. :-)

**Comment by GawainLynch** [comment]
:+1: :+1:

**Comment by GawainLynch** [comment]
I know I am self-banned from UI commentary… But would "last two" or "last three" be better?

**Comment by bobdenotter** [comment]
It feels unnatural to do that, to me. I'd like to keep the decision for the user as straightforward as possible: 

- Do I want the latest version? 
  - Yes -> click "Install Latest" 
  - No -> click "Show versions"
    - Choose from all versions -> click "install"

If we do the "latest two or three, they will have one more choice to make: 

- Do I want the latest or another recent version? 
  - Yes
    - Choose from recent versions -> click "install"
  - No -> click "Show versions"
    - Choose from all versions -> click "install"

While this is only one extra choice, it's still a choice we shouldn't have to present to the 99% of users who  should "just get the latest version"

**Comment by GawainLynch** [comment]
Yeah, see… This is why I self-ban myself! I like your version much better :grin:

**Comment by jadwigo** [comment]
the only case where this is more complicated is if there are lots of dependencies - like the clientlogin with the different hybridauth and openauth things... where some versions are excluding some options from working

in that case a link to an explanation page would be helpful -> the explanation page being the extension page on ext.bolt.cm or the changelog or readme for the extension?

**Comment by GawainLynch** [comment]
Yeah, ClientLogin & Members were on my mind with my original comment… My reservation is that there might be **lots** of releases after compatibility changes. Some way of flagging would be good.

**Comment by GawainLynch** [comment]
**RFE:** It would be good, nay *awesome*, if an extension has `suggests` and/or `requires` that those are listed on the modal too.

Use case, Mary heard that BoltForms is awesome, but is not great at handling YAML files… But luckily BoltForms suggests *Bolt Forms Editor*… 'cause @rossriley is awesome! :+1:

**Comment by jadwigo** [comment]
suggestions and requirement and versions and [ insert checkboxes, shaved yaks and pretty coloured bikesheds here ] would create a very complicated :christmas_tree: christmas tree :christmas_tree:  interface which would make the really smooth installation procedure less smooth :crying_cat_face: 

.. but on the extensions site it would be very cool to do exactly that because there is more room for a story there

**Comment by GawainLynch** [comment]
> would create a very complicated christmas tree

I don't know that I agree. It'd be two simple sub headings, with bullet lists underneath. That other blogging platform does this very well.

**Comment by GawainLynch** [comment]
There is simple and then there is too simple… I have had people hit me up countless times on IRC stressed that upon installing, for example, BoltBB, they had Members, ClientLogin and GeoIP in their list now and had no visibility or warning of why.

**Comment by rarila** [comment]
Just make it simple (sorry, no spare time at the moment) and dump the list completely:

```
   Version:  [ 2.1.5 |^]   [ Install ]
```
(Explanation: text | select | button)

Simple. You see only one - the latest - version on first sight and have only one button, but still access to all versions.

You couls also add a " - Latest" to the latest version string.
```
   Version:  [ 2.1.5 – Latest |^]   [ Install ]
```

**Comment by jadwigo** [comment]
@rarila :+1:

**Comment by GawainLynch** [comment]
I see your picture and raise you :stuck_out_tongue_winking_eye: 

![too long](https://cloud.githubusercontent.com/assets/1427081/9497012/ffc2c83c-4c0a-11e5-8384-5a0c9a1e5782.png)
