### ISSUE TITLE
Live Editor doesn't load when the final <script> tag in the <head> tag is commented out

### ISSUE THREAD

**Issue by philbates35** [bolt/bolt#3982]
(Bolt 2.2.8)

This isn't really Bolt's fault, but given that I've spent a whole evening working out why the live editor wont work for my theme, I figured it was worth mentioning in the hope that this could at the very least be highlighted somewhere in the documents to save someone else some time later on.

### The problem
The live editor would just work in my theme (worked fine in the Base-2014 theme). I got this error in the console:

    Uncaught TypeError: Cannot set property 'editorConfig' of undefined

### The explanation
The final `<script>` tag in the `<head>` element happened to be commented out in the form of a conditional IE 9 statement in the `_header.twig` template using HTML comments. When Bolt did it's regex search to find the last `<script>` tag to place `ckeditor.js` after, it discovered the final commented out `<script>` tag and inserted a new `<script>` tag for `ckeditor.js` __inside__ the HTML comment.

I stopped debugging at that point (once I worked this was the issue), but strangely when I look in the Chrome inspector, the entire `<head>` element actually ends up being empty. Maybe this is something that could be investigated further.

### Work around
Ensure that the final script in the `<head>` tag is not commented out / a conditional IE script.

### Reproduceable Steps
Add the following to your `_header.twig` template and attempt to live edit a page::
    
    <head>
        
    </head>

Hopefully the three hours I spent debugging this helps someone else out. Let me know if you want any more information from me.

**Comment by SahAssar** [comment]
Wasn't this fixed when the regex was changed in #4367?

**Comment by bobdenotter** [comment]
The issue mentions Bolt 2.2.8, so there's a good change it's been fixed in the meantime.

**Comment by SahAssar** [comment]
Yep, seems to have been fixed in #4367, I'm closing. Please feel free to reopen if it's still an issue! :)
