### ISSUE TITLE
Fix hardcoded file upload paths (files/)

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3983]
I've found that somewhere in code default *user upload folder name* (`files/`) is hardcoded, like
```js
//...
filename = filename.replace(/files\//ig, '');
//...
```
(taken from https://github.com/bolt/bolt/blob/master/app/src/js/modules/stack.js#L74)

I'm using custom name for that folder (`up`) and, for example, in imagelist fieldset it doesn't allow to preview, because path is hardcoded to *files/* .
![2015-08-18 13-14-13](https://cloud.githubusercontent.com/assets/2145313/9324323/ea97b8de-45aa-11e5-8594-05a8bbfc8c9c.png)

**Comment by bobdenotter** [comment]
I don't think the files path is configurable. How did you set that custom name?

**Comment by Boorj** [comment]
```php
$configuration->setPath("files", "my folder");
```
is it restricted or not allowed?

**Comment by bobdenotter** [comment]
Hmm, I never used that.. Guess we should fix this.

**Comment by GawainLynch** [comment]
Yeah, it fails on JavaScript as @rarila is still in the process of heavily refactoring said script and creating data objects for all this.

**Comment by Boorj** [comment]
https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fielddata/_imagelist.twig#L13
here's that line
But there's a problem. If i set 
```twig
<a class="thumbnail-link" href="%PATH%../{{ paths.files }}/%FNAME%">
```
instead of `href="%PATH%../files/%FNAME%"` it still gives me "files" string, since my setup was made for frontend, and paths.files is set up for backend to "files".

**Comment by GawainLynch** [comment]
There is a very simple fix… Use standard paths… :+1:

**Comment by bobdenotter** [comment]
That's what you get when you use alpha level software..  ¯\\\_(ツ)_/¯

**Comment by Boorj** [comment]
:koala: will eat your bread.

**Comment by GawainLynch** [comment]
:grin:

**Comment by rarila** [comment]
@Boorj Ok, …

- the line ``filename = filename.replace(/files\//ig, '');`` does not do any harm in that case, as the comment above indicates.

- How are things to work at all, if the upload path for frontend and backend is different?!

For the rest… gotta check

**Comment by rarila** [comment]
From available documentation I wasn't able to create a working alternative namespaced upload. So no testing… *Emergency – paging Dr. @rossriley – Emergency*

**Comment by rarila** [comment]
:bell: Ping @rossriley here again …

**Comment by SahAssar** [comment]
@rarila Did you mean to close this one or was it just accidental?

**Comment by rarila** [comment]
@SahAssar Oh, good catch, you are right. Sorry!

Now I know why this vanished from my assign list:)

**Comment by rossriley** [comment]
Ok, apologies for the delay in getting to this. Should now be covered in #4591

One caveat, the url update won't be automatic from setting the files path, it will also require setting the URL as well, since there's two many variables in terms of public root being different to file root. 

    $configuration->setPath("files", "my folder");
    $configuration->setUrl("files", "/my folder/");

If you want to keep uploaded files out of the web root then you're on your own :-)

**Comment by Boorj** [comment]
i tried to use ready implemented routine for uploading to outside dir - i failed, because it's impossible for now without changing a core. So only custom upload handlers.
