### ISSUE TITLE
Add multiple selection for file selector in imagelist fieldtype

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3984]
It would be nice if file selector could have checkboxes to select several items at once
![2015-08-18 13-17-57](https://cloud.githubusercontent.com/assets/2145313/9324379/708a05e6-45ab-11e5-87ac-58f3870f3417.png)
Probably it could be used somewhere else.

**Comment by GawainLynch** [comment]
Yeah, this has, *silently*, been on my wish list for a while too :+1:

**Comment by Boorj** [comment]
### 1
And if you can, can you please add sorting by natural order , so it goes like 
`xxx-1 xxx-2 xxx-3 ... xxx-11 xxx-12`  and not 
`xxx-1 xxx-11 xxx-12 ... xxx-19 xxx-2 xxx-20`

### 2
would be lovely to have a selector for "choose sorting"

### 3 
would be great to have ability to switch view to thumbnails

**Comment by bobdenotter** [comment]
As you know we're working hard on Bolt, but we can't do it all by ourselves.. If you want to see all these feature requests you're making to come to fruition, please help fixing them, instead of only opening new issues.

**Comment by Boorj** [comment]
I supposed rarila is working on backend widgets

**Comment by EJanuszewski** [comment]
I've made a start on this now, will most likely need some reviews since I've not contributed to bolt yet and style/where things go might be incorrect.

**Comment by EJanuszewski** [comment]
Ok I think this is now done, I've tested it quite thoroughly I think, I think I need to make a PR next but if I'm wrong can someone please point me in the right direction.

**Comment by SahAssar** [comment]
Should have been fixed in #4894 and #4879, Closing. Reopen if it isn't fixed :)
