### ISSUE TITLE
Dropdown at users&permissions stretches div and scrollbar appears

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3985]
![2015-08-18 14-40-31](https://cloud.githubusercontent.com/assets/2145313/9325846/511d5882-45b7-11e5-959b-aa82d79209b6.png)
Should it be fixed?

**Comment by SahAssar** [comment]
I can't reproduce this in Chrome, FF or IE.

Which browser are you using?

**Comment by SahAssar** [comment]
Couldn't reproduce so I'm closing. If you see this on current versions please reopen ;)

**Comment by Boorj** [comment]
checked again in FF 40.0.2 and Iron v39.0.2100.0 (chromium based)
appears again.

![2015-10-05 00-59-33](https://cloud.githubusercontent.com/assets/2145313/10269536/c798b82a-6afc-11e5-814e-155fe9345a69.png)

this weird property causes that.

**Comment by SahAssar** [comment]
Confirmed in all sizes in master, and on 767px width and down on 2.2.

**Comment by Boorj** [comment]
confirmed anywhere, FF 40.0.2 and chromium on v39

**Comment by Boorj** [comment]
confirmed for any resolution

**Comment by bobdenotter** [comment]
Fixed by me, in aee9e5307990e6e4950f01c64b2264828798613d
