### ISSUE TITLE
Content Type translations aren't using all generic ones

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#3986]
While translation to fr_FR, I discovered that some translations hints in `contenttypes_<lang>.yml` aren't reusing the ones defined in `messages_<lang>.yml`

Steps to reproduce : 

1. Set Bolt to use a new langage (fr_FR as example)
2. Create a new `messages` translation using backend.
3. Edit keys `contenttypes.generic.actions-all` and `contenttypes.pages.text.recent-changes-one` 
4. Create a new ContentType translation using backend

`contenttypes.generic.actions-all` hint is still in english and `contenttypes.pages.text.recent-changes-one` is translated.

**Comment by Boorj** [comment]
Had close problem, haven't solve. 
When you add custom locale , it's messages are overwritten by fallback messages (if they exist)
![2015-08-18 15-16-39](https://cloud.githubusercontent.com/assets/2145313/9326511/0bd890b6-45bc-11e5-9cd9-1b9645da5caf.png)
seems that it was just an order problem. Each time i have to delete auto generated messages when i add new contenttype.

**Comment by SahAssar** [comment]
This is the same problem as #4161 (or at least will be solved by the same solution IIRC), so closing.
