### ISSUE TITLE
Handle incorrect repository URLs when submitting extensions

### ISSUE THREAD

**Issue by paullla** [bolt/bolt#3987]
Error while trying to upload new extension to http://extensions.bolt.cm/:

FatalErrorException in PackageManager.php line 64:
Error: Call to a member function getRootIdentifier() on null

**Comment by GawainLynch** [comment]
Tried this a couple of times and it's working here. Any chance there was a typo in the URL you provided for the repo?

**Comment by paullla** [comment]
Yes, I entered wrong URL, thank you. Maybe you could show custom error message on invalid URL instead of FatalErrorException.

**Comment by Mikescops** [comment]
We'll keep that in mind, i'm working on the new extension website.

**Comment by GawainLynch** [comment]
@Mikescops this sounds like a reasonable one to add to the work you're doing at the moment.

**Comment by Mikescops** [comment]
Solved by Rossriley. see bolt/bolt-extensions#9

**Comment by GawainLynch** [comment]
@Mikescops where is the commit?

**Comment by rossriley** [comment]
Note this is on the new branch, so not live yet.

https://github.com/bolt/bolt-extensions/commit/9674e55861ba1fc78459f69a534bf3dad31fc249

**Comment by GawainLynch** [comment]
Cut over last week :+1:
