### ISSUE TITLE
{{ debugbar(false) }} isn't working

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3988]
[According to the docs](https://docs.bolt.cm/internals/bolt-internals#debug-bar) we can disable the debug bar (while still debugging) in any template that we want:

> Note that the debug bar is appended to all your frontend templates by default. If you don’t want the bar in a custom template, just use this, anywhere in the template:
>
> ````twig
> {{ debugbar(false) }}
> ````

In Bolt 2.2.8, I tried adding this in my template, first in a block in an extension of another template, and then at the root of my base template, but in both of them, the debug bar stuck around. I tried clearing the cache, too, but it didn't work either.

**Comment by GawainLynch** [comment]
That went the way of the dodo a couple of years ago when Symfony changed stuff… There is a PR in to update the docs https://github.com/bolt/docs/pull/234, just waiting on merge and we'll push it to the docs.bolt.cm
