### ISSUE TITLE
Geolocation snaps pin to matched address, unable to set specific coordinates

### ISSUE THREAD

**Issue by jlainvolve** [bolt/bolt#3991]
It no longer appears possible to drag the Geolocation map marker to a location without having it automatically "snap" to the center of the closest Matched Address. It is no longer possible to manually set the coordinates to a non-addressed location (as it was in earlier versions).

Behavior noted in 2.2.5 and 2.2.8.

**Comment by rossriley** [comment]
For reference the change is in `js/modules/fields/geolocation.js` the previous implementation did this in the callback for a marker move:

    function (results, status) {
        field.formatted.val(results[0].formatted_address);
    }

Now the behaviour is subtly different.
    
    function (results, status) {
        var location = results[0].geometry.location;
        field.marker.setPosition(location);
    }

Version 1 uses the geolocation to update the formatted address but doesn't override the latlng, the newer version passes the whole geocoded location including new latlng to the field.

**Comment by rarila** [comment]
Probably both versions seems to be usefull. Would have the behavior selectable via a checkbox be useful?

**Comment by bobdenotter** [comment]
> Probably both versions seems to be usefull. Would have the behavior selectable via a checkbox be useful?

I'm a big proponent on picking _one_ and sticking with it. Less options is better.

**Comment by rarila** [comment]
@bobdenotter Patch is done…
