### ISSUE TITLE
Allow disabling of debug bar while in debug mode

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3994]
There's an element in my UI that is obscured by the Bolt debug bar button, but I want to be in debug mode to be able to view dumps and have PHP error reporting. I'm proposing a simple option, `debug_bar` in config that allows to explicitly disable the debug bar even when `debug` is `true`.

Requested because #3988 happened.

**Comment by GawainLynch** [comment]
#3988 "happened"? That was due to Symfony 2.1 being released in September 2012.

You know you can either collapse the bar, or open a window in incognito mode and not get the tool bar?

**Comment by Pinpickle** [comment]
> September 2012

Yikes! That *was* a long time ago. I was just referring to the issue to say
at one point we could disable the debug bar - and on a per-template basis
did make a lot of sense.

Didn't think about the incognito thing. It's not just the bar that gets in
the way, but the button when it's collapsed as well. I guess this is a rare
enough use-case to warrant needing to do this in an extension? At least for
the time being... Isn't too hard to fix so you may see a PR soon.

**Comment by GawainLynch** [comment]
Going to close this for the sake of clean up and getting the issue tracker back under some semblance of control… :laughing: 

But we'll happily review a PR if/when you have time.
