### ISSUE TITLE
allowedContent and viewSourceRoles

### ISSUE THREAD

**Issue by mafin** [bolt/bolt#3998]
Changing of setting items viewSourceRoles and allowedContent does not take effect.
The source button is allowed for all roles despite of viewSourceRoles setting.
Change allowedContent to 'p strong', but wysiwyg still allows all other tags.

**Comment by GDmac** [comment]
It was introduced in commit, [Killing darlings, less is more! (35fa258)](https://github.com/bolt/bolt/commit/35fa25853efe8d3dbc8c64780a5ebb3d2fc8b438#diff-c282328d4235194c5d5aa4f1e092beb8) by @bobdenotter
But currently does not handle the user group.
