### ISSUE TITLE
Content Fields - Preserve Diacritical Marks

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#4003]
Goof Afternoon,

We have some fields in our CMS that may use diacritical marks (ŭ, ô, ē, etc).

Do we know of any issues that Bolt may have in preserving these values?

Thanks,
Matt

**Comment by GawainLynch** [comment]
@mhodges-cainc can you give us some more information… We shouldn't be touching that in content fields.

**Comment by GawainLynch** [comment]
> Goof Afternoon,

I know those days! Thankfully it's Friday :grin: 

We don't touch those, I just was able to save a record with this:
![text](https://cloud.githubusercontent.com/assets/1427081/9412667/f1321014-4824-11e5-8798-ada80472ae55.png)

Only thing I can think of is the database's collation/character set.

**Comment by mhodges-cainc** [comment]
Perfect - thanks!

**Comment by GawainLynch** [comment]
Presuming this was resolved your end. Please feel free to re-open if there are further issues.
