### ISSUE TITLE
Changelog 'next' & 'previous' buttons don't work as expected in Bolt 2.2.x 

### ISSUE THREAD

**Issue by slahav** [bolt/bolt#4009]
when trying to navigate between changelog entries, the behavior they got was unexpected.
Essentially, when they try to use the next & previous buttons to navigate, Bolt redirect them to the page with all the changelog entries rather than showing the next or previous change.
After talking to @GawainLynch, my understanding is that this has been solved in 2.3 but not back ported to 2.2.x

**Comment by GawainLynch** [comment]
Hmm… Just found out why I didn't backport this… I more-or-less rewrote the classes in a refactor branch, that's now in master.

I'll have a dig and see if I can't work something out though.

**Comment by GawainLynch** [comment]
Pfft… Ignore that, it was a very simple Twig change. Fixed in #4026 :grin:

**Comment by GawainLynch** [comment]
@slahav this should be appearing in v2.2.9, which @bobdenotter is planning to release over the weekend.

**Comment by slahav** [comment]
Thank you @GawainLynch :smile: i'll plan to upgrade next week.

**Comment by GawainLynch** [comment]
@slahav: @bobdenotter has tagged and released 2.2.9. 

Also worth noting is that for unit tests the [`getApp()`](https://github.com/bolt/bolt/blob/master/tests/phpunit/unit/BoltUnitTest.php#L40) function now accepts a boolean (`true` by default) that when passed a `false` will skip the call to `boot()` so you can better manipulate SPs and the like if need-be and call `boot()` in the test function yourself.
