### ISSUE TITLE
Fatal Error after quiting in process of installing an extension

### ISSUE THREAD

**Issue by decebal** [bolt/bolt#4020]
I get a fatal error. I am currently using master.

```
Bolt - Fatal error.
Class: LogicException
Message: Cannot set session ID after the session has started.
Code: 0
Bolt\Session\SessionStorage->setId()
[root]/vendor/symfony/http-foundation/Session/Session.php, line 199

Symfony\Component\HttpFoundation\Session\Session->setId()
[root]/src/Session/SessionListener.php, line 61
array:1 [▼
  0 => "6EmSTDUoBZhYPpAj5XX7boLbvabu7jZv"
]
Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
[root]/vendor/symfony/event-dispatcher/EventDispatcher.php, line 53

Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
[root]/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php, line 124

Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
[root]/vendor/symfony/http-kernel/HttpKernel.php, line 128

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]/vendor/symfony/http-kernel/HttpKernel.php, line 68

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]/vendor/silex/silex/src/Silex/Application.php, line 581

Silex\Application->handle()
[root]/vendor/silex/silex/src/Silex/Application.php, line 558

Silex\Application->run()
[root]/index.php, line 48

[]
```

The error occured in the scenario of me pulling down an extension and quiting in the process.

**Comment by GawainLynch** [comment]
Ah, so you are running master then? I thought in #3954 you said you were on 2.2.8?

**Comment by bobdenotter** [comment]
@decebal Are you _sure_ you are on `2.2.8`, and not on `master`? I'm confused.

**Comment by bobdenotter** [comment]
Yeah, what @GawainLynch said.

**Comment by decebal** [comment]
just merged master, thinking that might solve the problem :dash:

**Comment by decebal** [comment]
in the system log database table i have the following row:

{"file":"\/var\/www\/bolt-latest\/src\/Session\/SessionStorage.php","line":143,"class":"","function":"","message":"Cannot set session ID after the session has started."}

**Comment by GawainLynch** [comment]
OK… but please know that `master` is under heavy development at the moment and isn't suitable for production.

**Comment by GawainLynch** [comment]
Ah, also, what extension did you install?

**Comment by decebal** [comment]
That's the thing, I haven't installed any, I just tryied to install and failed, simpleforms

**Comment by GawainLynch** [comment]
Weird I just checked SimpleForms and it doesn't use sessions in the `initialize()` method.

No other local extensions?

**Comment by decebal** [comment]
it seems like it is starting the session too many times, the session id is regenerated, I just commented own the line 143 that was trowing an error

**Comment by GawainLynch** [comment]
Quite possible… Line 143 in which file?

**Comment by decebal** [comment]
sorry: {"file":"\/var\/www\/bolt-latest\/src\/Session\/SessionStorage.php","line":143,"class":"","function":"","message":"Cannot set session ID after the session has started."}

**Comment by GawainLynch** [comment]
Any ideas @CarsonF ?

**Comment by CarsonF** [comment]
He's on master so its the same error as #3954

**Comment by GawainLynch** [comment]
Yes, that much we're clear on… But why this would trigger without any extensions installed is the bigger question.

**Comment by CarsonF** [comment]
I have some ideas I'll try to implement tonight to help us with this transition and BC

**Comment by SahAssar** [comment]
Closing as this is same issue as #3954.
