### ISSUE TITLE
twig popup() while $filename is an array

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#4022]
twig imagehandler popup expects a string,
however docs suggest to serve it an image field (array) ``{{ image|popup(200,200,'c') }}``

The imagehandler does pass the filename (array) to its thumbnail method
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L183

The thumbnail method extracts the name if it is an array
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L298

And then back in popup method, it tries to use filename (still array) for title
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L187

**Comment by GDmac** [comment]
Suggested solutions:
```php
            if (empty($title)) {
              // try to get title from filename array
              if (is_array($filename) && isset($filename['title']) {
                $titel = $filename['title']
              } else {
              // fallback to filename from array
                if (is_array($filename) && isset($filename['filename']) {
                  $titel = $filename['filename']
                } else {
                  // fallback to filename as provided (string)
                  $title = sprintf('%s: %s', Trans::__('Image'), $filename);
                }
            }

```

**Comment by GDmac** [comment]
Related: #2866

**Comment by bobdenotter** [comment]
At first glance this seems like an OK solution.. Want to PR it, for virtual Karma? ;-)

**Comment by GDmac** [comment]
Yes, making a PR (soonish)

**Comment by GDmac** [comment]
note to self (bopp :-)
https://github.com/marionnewlevant/twig-img-macro

**Comment by bobdenotter** [comment]
Those Twig macros should be really simple to include in a Bolt project, if you need them :-)

**Comment by bobdenotter** [comment]
What are the steps to reproduce this issue? If i do this: 

```
            <p>record.image:</p>
            {{ dump(record.image) }}
            {{ record.image|popup(300, 260) }}

            <p>record.values.image:</p>
            {{ dump(record.values.image) }}
            {{ record.values.image|popup(300, 260) }}
```

I get this, which seems OK to me:  

![screen shot 2015-09-09 at 15 49 46](https://cloud.githubusercontent.com/assets/1833361/9763543/70d48894-570a-11e5-9923-c7fc9d3f7a1d.png)

**Comment by cdowdy** [comment]
@bobdenotter I too did what you did   

```twig
 <p>record.image:</p>  
{{ dump(record.image) }}  
{{ record.image|popup(300, 260) }}  

<p>record.values.image:</p>  
{{ dump(record.values.image) }}  
{{ record.values.image|popup(300, 260) }}  
```  

On Bolt 2.2.10 ( and any version below ) this is what you get with placeholder content.  

![bolt-dummy-content-2 2 10](https://cloud.githubusercontent.com/assets/5969974/9766511/478bef4a-56e7-11e5-8813-d50763070537.PNG)  

if you add in the field attributes for an alt attribute it doesn't print it to the screen.  

```yaml  
pages:
    name: Pages
    singular_name: Page
    fields:
        image:
            type: image
            attrib: alt  
```  

which will give you  
![with-alt-attrib](https://cloud.githubusercontent.com/assets/5969974/9766611/cea73eda-56e7-11e5-8a87-df53381c8cd6.PNG)    

So no Alt attributes are printed to the screen and I just noticed that the Title attribute on the anchor tag for   
```twig  
{{ record.values.image|popup(300, 260) }}  
```  
seems to be broken because it prints out ```Image: Array``` instead of the File name Or title.  

Disregard all this if I'm off base.. If I am this still is an issue which I filed a while ago mentioned above.

**Comment by bobdenotter** [comment]
@cdowdy Good point! I'm not sure if that's what @GDmac meant, but i will fix what you've discovered.

**Comment by GDmac** [comment]
yup, that's the issue. I thought we could maybe add alt attribute, next to already existing title, as well

**Comment by bobdenotter** [comment]
@GDmac: You can! :-)

```
image:
    type: image
    attrib: [ alt, title ]
```

**Comment by GDmac** [comment]
I meant add ``alt`` attribute to the popup() and showimage() methods,
they have no attributes at all besides ``src= width= height=``
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L191
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L244
