### ISSUE TITLE
Error while loading web debug toolbar

### ISSUE THREAD

**Issue by ronraney** [bolt/bolt#4023]
I am brand new to Bolt CMS. I am getting a 404 error when loading the web debug toolbar. I would appreciate any help, or the most likely cause for this. I think that I have the .htaccess file configured correctly but not sure. I was able to load the page a couple of days ago with no problems. I think I may just re-install since I haven't gotten very far with this CMS.

**Comment by bobdenotter** [comment]
Hi, @ronraney,

Which version of bolt are you using? And does the rest of the backed work as expected?

**Comment by GawainLynch** [comment]
Second time today for this one, I think I am off to buy a lottery ticket :grin: 

In your vhost definition you need the `AllowOverride` parameter set, a lose example is:
```apache
<Directory /path/to/bolt>
    AllowOverride All
</Directory>
```

**Comment by ronraney** [comment]
-BOLT 2.2.8
-The backend seems to work okay
-I'm not sure where the vhost definition is

Thanks for your help!

**Comment by GawainLynch** [comment]
"vhost" is your Apache host configuration for that host, e.g. `mysubdomain.domain.com` would be a vhost.

Basically somewhere in your Apache config you'll have a `<Directory /path/to/bolt>` section and the `AllowOverride All` parameter needs to be inside that.

**Comment by bobdenotter** [comment]
@ronraney Be sure to read this section of the docs: https://docs.bolt.cm/howto/making-sure-htaccess-works
