### ISSUE TITLE
[2.2.9] extension version listing in the wrong order?

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4032]
It seems like the listing of extensions are in the wrong order in certain cases, see the image below:
![versionlisting](https://cloud.githubusercontent.com/assets/5096632/9562205/d282be24-4e65-11e5-9060-d200e3276b2d.png)

Shouldn't v1.1.1 be on top instead of v1.0.2?

Only tested on 2.2.9 so far.

**Comment by GawainLynch** [comment]
It's the tag… They've used a capital 'V' for 1.1.1

**Comment by SahAssar** [comment]
Ah, sorry, didn't even see that! Closing issue.

**Comment by GawainLynch** [comment]
Well… It might be something we can address with a case-insensitive sort.

**Comment by rarila** [comment]
Perhaps some ``s/^v//i`` would be a good idea to unify things a bit
