### ISSUE TITLE
Slug generator adds extra tail after record saving

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4034]
![2015-08-31 00-43-24](https://cloud.githubusercontent.com/assets/2145313/9568862/35ba0682-4f79-11e5-8258-bafeaaab51b3.png)
i just created a record, then i save it and slug is damn long.

And the second wish : do something with long slugs, controll buttons go under the right panel.

**Comment by GawainLynch** [comment]
@CarsonF: I've been meaning to hit you up about this one. For some reason some async requests are testing in `Zone` as `backend` and applying the snippets.

**Comment by CarsonF** [comment]
@gawainlynch: Fixed?
