### ISSUE TITLE
Slug field in backend doesn't wrap text inside

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4035]
![2015-08-31 12-14-50](https://cloud.githubusercontent.com/assets/2145313/9573089/c9c6f71c-4fd9-11e5-80ab-50d0334a7bee.png)
Probably it should be moved to textarea with rows='1' and javascript snippet will track the length of slug. 
Or maybe it could be done with hidden field and div: move text from input to div, since it's not used as input and all editings are being made with a popup.

**Comment by bobdenotter** [comment]
It's width isn't confined to the "9 column" div properly. See screenhot:

![screenshot 2015-09-09 19 59 32](https://cloud.githubusercontent.com/assets/1833361/9770006/d9effbba-572d-11e5-88a5-8d25ed10aebd.png)

@rarila Could you look into this?

**Comment by rarila** [comment]
This one has to be redesigned anyway as it's the last one that isn't valid Bootstrap (two buttons not allowed)
