### ISSUE TITLE
Relationship select field support for thousands of records

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4042]
Hello,

I saw that the searchable list for the relationship select stores all selectable entries in the HTML.
That can be a problem when you have thousands of entries. For example:

You have 50.000 book entries and want assign them to a landing page or something else. 

That select field can't handle 50.000 entries (I imagine).
It would be good if the select field only shows a few but the search function will search the database so you can select an entry that is not in the preloaded list. 

Phillipp

**Comment by Pinpickle** [comment]
:+1: 

Even with 100 records, you're still pushing a lot of unneeded bytes down the wire.

It would be great if a similar implementation was introduced for select fields with `values: contentype/field`.

**Comment by GawainLynch** [comment]
@rossriley did your recent changes cover this?

**Comment by SahAssar** [comment]
This seems like another one of those issues that we will get to sooner or later, but it won't be because of this. Closing due to lack of progress/interest.
