### ISSUE TITLE
Local Extension: Assets not copied to public dir

### ISSUE THREAD

**Issue by fadoe** [bolt/bolt#4047]
I wrote a local extension with assets. I have the issue, that the assets from extensions installed by bolt are copied to public/extensions/vendor, but the assets from local extensions does not.

Is there a way to copy the assets from local extensions into public dir?

I use Bolt 2.2.10.

**Comment by GawainLynch** [comment]
Not with local extensions… That is not their purpose, they are a way to avoid having to publish to the market place or set up repositories in `extensions/composer.json` file.

**Comment by escorter** [comment]
I don't get the point in your argument. I have the same issue, I want to have an extension which is not published but want to have the assets copied by bolt. So what's the reason why this is not possible for local extensions?

**Comment by GawainLynch** [comment]
@escorter local is local, that is entirely up to the management of the person who set up the local install.

**Comment by escorter** [comment]
Ok I see. Did I got it right that in this case all the assets are copied to public/extensions/local/... and the extension it self is at extensions/local/...?

**Comment by GawainLynch** [comment]
If your extension has assets you need to move to a public directory, you can place them as and where you like, the local extension just adds/refers to them relative to the base URL.

**Comment by fadoe** [comment]
@GawainLynch I think this are good points for the documentation. Can you update them?
