### ISSUE TITLE
Translation in extensions

### ISSUE THREAD

**Issue by fadoe** [bolt/bolt#4048]
When I write extensions, how can I add extension specific  translations? Where do I store them? How can I load them? Is this in bolt already included or must I add this in my extension?

**Comment by SahAssar** [comment]
The best/easiest way is probably to use the way that is currently used for bacboslab/menueditor and bobdenotter/seo (and hopefully soon bolt/googleanalytics), which all share the same basic code for translations.

Please feel free to reopen if I didn't answer your question well enough! :)
