### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#4050]
I know we have an IRC channel available but, and I'm not the only one, some of us can't access irc all day long. Plus, IRC can be quite frightening for newcomers.

Having a slack would be great as there are mobile apps and a better UI (as said by a friend "Slack is IRC who took a shower, dressed correctly and who can meet your parents")

**Comment by GawainLynch** [comment]
You mean like this one: https://boltcms.slack.com/messages/general/

**Comment by pygillier** [comment]
Ahem...

**Comment by GawainLynch** [comment]
Hehe… I am not sure if @bobdenotter has to add you to the "team" or whatever, but he's back on Monday and can wave wand, or something :+1:

**Comment by CarsonF** [comment]
@bobdenotter I still want this too :) Did we not like the pipes-something connection?
