### ISSUE TITLE
Setcontent with related records

### ISSUE THREAD

**Issue by XusBadia** [bolt/bolt#4054]
I'm stuck building a site and wanted to know if what I'm trying is even possible before I keep trying. Can I setcontent for specific records using relatedrecords? Like `{% setcontent records = 'contenttype' where { related.record = "{{ thisrecord.name }}" %}`.

Thanks!

**Comment by GawainLynch** [comment]
Not presently as I understand it.

Just one thing, your example syntax is incorrect and you may get caught with it, the use of `{` and `}` can get confusing…

So in the example if you're trying to use a value from an array:
```twig
{% setcontent records = 'my-contenttype/my-slug' where { foo = myarray.somevalue } %}
```
or if `foo` matches a string:
```twig
{% setcontent records = 'my-contenttype/my-slug' where { foo = 'bar' } %}
```

**Comment by XusBadia** [comment]
Thanks for the clarification!

**Comment by XusBadia** [comment]
Thanks for the clarification, but trying to get the value from an array using your example, I get this:
Twig_Error_Syntax: A hash key must be followed by a colon (:). Unexpected token "operator" of value "=" ("punctuation" expected with value ":")

**Comment by GawainLynch** [comment]
Ugh… I'm an idiot :grin: 

```twig
{% setcontent records = 'my-contenttype/my-slug' where { foo: myarray.somevalue } %}
```

**Comment by XusBadia** [comment]
haha Thanks! I realized my mistake immediately after pressing the "Comment" button.

Thanks for your time! :)
