### ISSUE TITLE
How do I manually sort content types?

### ISSUE THREAD

**Issue by stefantalen** [bolt/bolt#4056]
I've created a content type and would like to manually set the order in which they are being displayed. Right now they are being displayed in order of creation.

When looking in the backend I see a "Order: " option within the "Meta" column but it doesn't seem to work (Found this issue: #3821, maybe this bug still exists?)

I've been through the documentation but the only thing I found for sorting content types was this:
```
float: A field to store (floating point) numbers. Internally stored so that they can be sorted numerically. Note: the maximum precision is 9 digits before the decimal mark, and 9 digits after.
```

But I don't think that'll work with the "Order" arrows on the content type backend page :confused:

**Comment by bobdenotter** [comment]
You can use the sorting order in the backend, but only by inputting a value manually. 

![screen shot 2015-09-08 at 12 37 31](https://cloud.githubusercontent.com/assets/1833361/9732741/7c204150-5626-11e5-8949-d0e88b80d183.png)

(the visual drag-n-drop feedback is confusing.. We'll remove that!)
