### ISSUE TITLE
Add possibility to sort by date in file manager

### ISSUE THREAD

**Issue by cathelijne** [bolt/bolt#4057]
Pretty self-explanatory.

Background: when uploading duplicate file(names) with the uploader, it gets automatically renamed with a (timestamp-ish?) number in front of the original filename. Editors often can't find their files after that, claiming they aren't there etc. The possibility to sort by date would simply put the latest uploads on top; making them easier to find (and a handy feature no matter what if you ask me).

**Comment by SahAssar** [comment]
Sorry, this seems like it will be a part of #574 or because someone actually PR's it... So I'm closing, since I don't think this being open in any way helps it getting fixed. PR'ing this would be very appreciated!
