### ISSUE TITLE
Relations in the order they were added

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4060]
Hello,

first I'll explain what I did:

We need a little better relation handling for one contenttype. So i created a custom content field that retrieves all related entries from one type and pass it to a vuejs component that displays it as a list. There I can add new ones, based on a DB fulltext search, I can delete them or reorder them. The vuejs component renders a hidden select field with the entry informations. 

The old relation select field was removed by jquery so it will just send the data from my new select field to the server.

I noticed that they were saved or outputted in DESC id order. That removed the reorder function at all. Is there a setting to turn that off so I retrieve the entries in the order they were saved to the db?

Here is the generated select field:

```
<select name="relation[books][]" multiple="" style="display:none;">
  <option selected="" value="5">TEXT</option>
  <option selected="" value="2">TEXT</option>
  <option selected="" value="1">TEXT</option>
  <option selected="" value="3">TEXT</option>
</select>
```

When I reload the page I get them in the following order: `5,3,2,1`

**Comment by SahAssar** [comment]
Hey PhillippOhlandt, please have a look at the sortable-relations extension as this requires an extra column in the relations table.

**Comment by PhillippOhlandt** [comment]
Hey SahAssar. I tried it but it seems like it won't work. I'll post an issue on its github page.
