### ISSUE TITLE
JS Error on save: Cannot read property 'attr' of undefined

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4062]
Hello,

what I did: I reordered the option elements in the select element for a relation to bring them in a specific order. (I use a bolt extension to save them in this order). 

Then when I click on save, he sends everything to the server and so on. But I get the following error in the JS console and the spinner on the save button don't stop:

```
Uncaught TypeError: Cannot read property 'attr' of undefined
```

The error occured on `bolt.min.js` in line `4` (minimized so pretty useless info)

All the data were saved in the right way to the database but I don't know what's the reason for that JS error.

**Comment by PhillippOhlandt** [comment]
I formatted the JS code to see where the error happens. It's this:

```
function e(a) {
		var c, d, e, f, g = "",
			h = "";
		"datedepublish" === a.data.attr("id") && "1900-01-01 00:00:00" === a.data.val() && a.data.val(""), d = a.data.val().match(/^(\d{4}-\d{2}-\d{2})(?: (\d{2}:\d{2}:\d{2}))?$/), d && (g = d[1], h = d[2] || ""), e = "" === g || "0000-00-00" === g ? "" : b.datepicker.parseDate("yy-mm-dd", g), a.date.datepicker("setDate", e), a.time.exists && "0000-00-00" !== g && ("" === h ? h = "" !== g ? "00:00" : "" : i ? h = a.data.val().slice(11, 16) : (c = parseInt(h.slice(0, 2)), f = 12 > c ? " AM" : " PM", h = (c % 12 || 12) + h.slice(2, 5) + f), a.time.val(h)), a.data.trigger("change")
	}
```

That can be this from the source:
https://github.com/bolt/bolt/blob/master/app/src/js/modules/datetime.js#L172 

But why throws that an error when I switch two option fields within a select field and click save. Everything is okay without switching the option fields before I save the entry.

**Comment by GawainLynch** [comment]
If you need to debug JavaScript, you're best off [generating map files](https://github.com/bolt/bolt/tree/master/app/src) as they will save you a lot of energy :grin: 

Also please note that if you're running off master, we're in the middle of a very big refactor of that part.

**Comment by PhillippOhlandt** [comment]
Currently I am using Bolt 2.2.8.
I'll try to generate the map files.

**Comment by GawainLynch** [comment]
> Currently I am using Bolt 2.2.8.
 :+1: 

> I'll try to generate the map files.

Yeah, they're awesome. Our docs are not 100% up to date yet as @rarila is doing a lot of work on that part of the code, but he should be back from holidays tomorrow.

**Comment by PhillippOhlandt** [comment]
Ok now chrome devtools told me that the error is on the line I mentioned above. But a hidden input field with the id `datedepublish` exists, even after I switched the option fields with JS.

**Comment by PhillippOhlandt** [comment]
I pushed the field parameter from the display function to the console. When I save it will run 2 times. 
But when I reorder my list, it will run 3 times and the last throws the error. I am not a big Javascript fan and you know your JS better than me. I recorded it for you, maybe you have an idea whats the problem. Otherwise I have to debug a little bit more.

http://recordit.co/GLF95FETsU

**Comment by PhillippOhlandt** [comment]
Looks like my Array.prototype function to move an item in an array to a new position is the problem.

```
Array.prototype.move = function (old_index, new_index) {
                    if (new_index >= this.length) {
                        var k_whatever = new_index - this.length;
                        while ((k_whatever--) + 1) {
                            this.push(undefined);
                        }
                    }
                    this.splice(new_index, 0, this.splice(old_index, 1)[0]);
                    return this;
                };
```

**Comment by PhillippOhlandt** [comment]
Ok, solved it by exporting that Array.prototype into a simple JS function. Everything is fine now. Sorry for the trouble =)

**Comment by GawainLynch** [comment]
:+1: 

Source maps are awesome, hey :grin:

**Comment by PhillippOhlandt** [comment]
Yes they are!
