### ISSUE TITLE
php memory issue when installing bolt via composer

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#4064]
Hi,

I have been trying to install bolt via composer to get more control over my projects but fail because 128mb for a bolt project does not seem enough i get a

`Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)`

error when creating a project. I don't think raising the php memory in the php.ini will solve anything, 128M should be enough ( is it not? ) So what can I do to fix this problem, instead of contacting my provider to increase the limit.

**Comment by CarsonF** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by GawainLynch** [comment]
As @CarsonF points out, this is very much to do with what Composer requires and not Bolt itself.

To get around this on heavily constrained machines, I will set up project on a workstation and then `rsync -a bolt-install/ user@host:/dst/bolt-install/` .

**Comment by melcarthus** [comment]
I'll talk to my system admin to fix the issue, the server should not be "heavily constrained" but it seems to work fine for now if I install it localy and push it to my host, thanks for the great suggestion @GawainLynch and thanks for the link to the php memory commands @CarsonF !

**Comment by GawainLynch** [comment]
Yeah, it's just worth noting to the sysadmin that it is only the CLI that needs the extra memory, PHP running in the web server should be fine at 128MiB.

Closing this one off, but ping us if you have further issues.

**Comment by sbani** [comment]
```bash
php -d memory_limit=-1 composer.phar update
```

You can manually set memory_limit for this console command.
