### ISSUE TITLE
Extensions installer: Clicking "versions" once, triggers the request twice, making it take twice as long.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4067]
See screenshot: 

![screen_shot_2015-09-08_at_18_03_08](https://cloud.githubusercontent.com/assets/1833361/9740265/232b69fc-5654-11e5-878e-d4c83357d9f7.png)

**Comment by GawainLynch** [comment]
Stable and master?

**Comment by bobdenotter** [comment]
Yes, both `release/2.2` as well as `master`. Screenshot:

![screen_shot_2015-09-08_at_18_10_32](https://cloud.githubusercontent.com/assets/1833361/9740433/01dd1aec-5655-11e5-805c-8c263014b70e.png)
