### ISSUE TITLE
Allow overriding of bolt backend JS files

### ISSUE THREAD

**Issue by MichaelMackus** [bolt/bolt#4069]
Using a composer installed project, there's no way to override the bolt backend JS files using the local "app/src" directory. This is because bolt hardcodes the asset dir in the ScriptHandler to the bolt vendor dir. 

See: https://github.com/MichaelMackus/bolt-vagrant for an example of what I have (relevant code in composer.json and app/src)

**Comment by GawainLynch** [comment]
I am afraid this is by design. We don't support modification of backend code and it will break for you.

**Comment by MichaelMackus** [comment]
:(

Better ckeditor configuration would help this issue, but it would definitely be nice to be able to override some stuff on a per-site basis.
