### ISSUE TITLE
Previous and next functions not fetching relations

### ISSUE THREAD

**Issue by Twiebie** [bolt/bolt#4075]
For example in a blog situation where the route looks like this
`'/{contenttypeslug}/{categories}/{slug}'`

The next and previous functions don't fetch all relations to fill the required parameters.

`An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("categories") to generate a URL for route "blog".")`

**Comment by bobdenotter** [comment]
The problem here is that `/{categories}` relies on 'hydration' for the situations in which Bolt needs to make a link. 

Looks like I introduced this bug in 56000eda49b3cdbc5fd59f44e0258d03b5485f69.  I'll fix it.
