### ISSUE TITLE
Is it possible to extend default user fields

### ISSUE THREAD

**Issue by paullla** [bolt/bolt#4085]
How can I add more fields to user?

**Comment by GawainLynch** [comment]
You can't currently.

What I do for these types of things is have a "People" ContentType as that can very easily be used with `getContent()` for things like staff pages, etc.

**Comment by paullla** [comment]
Can I than make relation from ContentType to User?

**Comment by GawainLynch** [comment]
Not in terms of a content relation, no. The user table isn't considered a content table.

I guess the best question is, "what do you need to achieve?"

Also please feel free to jump on #boltcms on Freenode as there are a few of us around today, and it's a friendly bunch.

**Comment by GDmac** [comment]
as Gawain says, "what do you need to achieve?",
For quick thingies and where you administrate the site,
an entry does have a possibility to set meta "owner" as a way to relate to "users".

The "users" are generally more of an administration access thing for a site.
Maybe have a look at bolt/members extension? That uses it's own DB-table,
and developing a fieldtype to "select/relate" a member is not impossible.

**Comment by paullla** [comment]
I made new ContentType for my users as @GawainLynch suggested. Thanx.

**Comment by SahAssar** [comment]
Closing since as this is mostly the same goal as #927 (custom fields in users) and @paullla seems to have achieved her goal in the short term. Feel free to reopen if there is more to add :)
