### ISSUE TITLE
In [2.3] snippetcallbacks in extensions no longer work.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4086]
In Bolt extensions you can add snippets, like this: 

```
$this->addSnippet(SnippetLocation::END_OF_HEAD, 'headsnippet');
```
In case of the [Sitemap](https://github.com/bolt/Sitemap) extension, it would use `'headsnippet'` as a callback, to insert a piece of generated HTML into the `<head>` section. 

On current master, it no longer recognizes it as a callback, and simply outputs the string `'headsnippet'`. Is this a regression in 2.3?

**Comment by GawainLynch** [comment]
Yes, probably the detection of the [callable or string](https://github.com/bolt/bolt/blob/master/src/Asset/Snippet/Queue.php#L174)

**Comment by bobdenotter** [comment]
Ok, marked it as such. ^_^

**Comment by GawainLynch** [comment]
BTW, in case it isn't obvious and you're working on the other thing, this will work:

```php
$this->addSnippet(SnippetLocation::END_OF_HEAD, [$this, 'headsnippet'])
```

**Comment by bobdenotter** [comment]
Yes, but the other thing _used_ to work too. I think this won't be too hard to fix, for BC sake. On it!

**Comment by GawainLynch** [comment]
Oh yes, regressions must be fixed… It was more that if you wanted a workaround in the meantime so you didn't get distracted on… oh wait :wink:
