### ISSUE TITLE
Got  'The CSRF token is invalid. Please try to resubmit the form' 

### ISSUE THREAD

**Issue by edge2012** [bolt/bolt#4089]
When the first time to access my site to create the root user after setted bolt.
Using Nginx and Php 5.6.12

**Comment by edge2012** [comment]
fixed with command   ./nut  user:add <username> <displayname> <email> <password> <role>

**Comment by SahAssar** [comment]
@edge2012 I'm going to try to recreate the issue (as I've seen it before too), could you post your full versions and what repos you used for nginx and php?

**Comment by edge2012** [comment]
im using nginx/1.8.0 and PHP 5.6.12 (cli)

**Comment by GawainLynch** [comment]
@edge2012 was this on `master`, or `release/2.2` (stable branch)?

**Comment by SahAssar** [comment]
I can sometimes reproduce this on master, but not on 2.2.
