### ISSUE TITLE
2016 theme ? 

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#4091]
Currently Bolt ships with a "base-2014" theme. It would be quite cool to get a new theme for 2016.

Maybe a contest or something like would help.

**Comment by GawainLynch** [comment]
Your wish is @SahAssar's command in #4083 :grin:

**Comment by SahAssar** [comment]
Hey @pygillier, if you have any suggestions or criticism regarding the proposed theme I'd be happy to discuss and/or change it (if there is consensus). It mostly grew out of a frustration with bolt's current base-2014 and my personal preferences regarding flexbox.

I'd love to hear your feedback/thoughts!

**Comment by pygillier** [comment]
Strange, PR weren't refreshed... So I didn't saw this bloody good one \o/

**Comment by pygillier** [comment]
@SahAssar I'll fork your theme and add several a11y enhancements if you don't mind :)

**Comment by SahAssar** [comment]
Sounds like a great idea. I was mainly thinking of size, speed and adding a splash of visual modernity when I made it.

**Comment by SahAssar** [comment]
Wooo, It's in!
