### ISSUE TITLE
Modernizr step in grunt process broken.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4094]
Modernizr has updated to 3.0 (from 2.8.x), and broke the build process. This link gives a 404 now: 

http://modernizr.com/downloads/modernizr-latest.js

```
[bob:~/Sites/bolt-origin/app/src]$ grunt modernizr:prepare                                                              (master)
Running "modernizr:prepare" (modernizr) task

Enabled Extras
>> touch
>> shiv
>> cssclasses

Enabled Extensibility Options
>> teststyles
>> prefixes

Downloading source files
404 modernizr-latest.js

Downloading community files
200 cookies.js
200 contenteditable.js

>> Generating a custom Modernizr build
>> Skipping uglify

>> Wrote file to tmp/modernizr-custom.js
>> The following tests could not be downloaded
>>
>>     404 http://modernizr.com/downloads/modernizr-latest.js
>>
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157

Done, without errors.
```

@rarila How can we best fix this?

**Comment by rarila** [comment]
Simply try again. That's just a server problem. (Did work for the :koala: )

**Comment by bobdenotter** [comment]
Still wonky for me. Will try again tomorrow!! :-)

**Comment by rarila** [comment]
Take some :leaves: ;-)

**Comment by bobdenotter** [comment]
Just to be sure, we're doing the same here. I did this, on master

```
cd app/src/
rm -rf bower_components/ node_modules/
bower install
npm install
grunt modernizr:prepare
```

And then i get the error as described above. Happens on two machines, from two different IP's.. If i open `http://modernizr.com/downloads/modernizr-latest.js` in a browser, i get a `404` as well.

**Comment by rarila** [comment]
Take some tea [meanwhile](https://github.com/Modernizr/grunt-modernizr/issues/118) :-(
