### ISSUE TITLE
[Feature] Thumbnails/Uploads/FileManager with remote filesystems

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4095]
Using S3 or other remote filesystems is a "talked about feature" but is really only half implemented. For example, thumbnails do not work at all for remote filesystems. 

We have also have a fragmented code base, some parts using `Flysystem` and other parts using `ResourceManager::getPath(s)`. I would like to unify these.
## 
#### Here's what's needed for this:
- [X] [`Filesystem`](https://github.com/bolt/filesystem) Create interface to sit on top of Flysystem's.  
  This gives us more flexibility while still allowing flysystem adapters to be used.
- [X] `Filesystem` Create image info abstraction with filesystem interface.  
  This will be used instead of native functions for local files.  
  Here: [Image\Info](https://github.com/bolt/filesystem/tree/master/src/Image/Info.php) [Image\Type](https://github.com/bolt/filesystem/tree/master/src/Image/Type.php)
- [x] [`Thumbs`](https://github.com/bolt/bolt-thumbs/compare/2.x...master) Refactor Thumbnail code to use our filesystem interface instead of Symfony's (which requires local files). 
- [x] `Core` Integrate new thumbnail code (service provider/twig functions)
  - [X] Create service provider to connect config to thumbs service provider
  - [x] `ImageHandler` Update to use filesystem interface
- [ ] `Core` Ensure upload code works. I think this is already setup to use flysystem interface. So aside from #3831, this may be done.
- [ ] `Core` Update filesystem plugins
  - [ ] `Authorized` - Halp :dizzy_face:
  - [x] `Browse` - Integrate into filesystem with objects pls
  - [ ] `PublicUrl` - Integrate into filesystem
  - [x] `Search` - Integrate into filesystem
  - [x] `ThumbnailUrl` - Keeping in core, but it is deprecated now.
- [ ] `writeable/readable` checks and `file permissions` need to be removed and accounted for differently as they are not apart of the flysystem interface.

Branch for core changes [here](https://github.com/CarsonF/bolt/tree/filesystem-refactor). Comparison [here](https://github.com/bolt/bolt/compare/master...CarsonF:filesystem-refactor).
## 

I've put in a lot of work for the image and thumbnail code. I hope to knock out the rest of this fairly quickly.

Questions, suggestions, complaints are always welcome. I'll forward them on to :koala:

**Comment by GawainLynch** [comment]
@CarsonF no pressure, but I have added this to the release tracker so that this is blocking release of 2.3… Pressure it on :stuck_out_tongue_winking_eye:

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by GawainLynch** [comment]
@CarsonF My turn to be the pain in the arse… can we call the 3.0 stuff done and move the remainder to 3.1?

**Comment by CarsonF** [comment]
Most is done, I just need to verify it.

**Comment by SahAssar** [comment]
Removed blocker per dev-meeting

**Comment by CarsonF** [comment]
This is implemented in 3.3

**Comment by romulo1984** [comment]
Hi, @CarsonF 

Can you give some example usage for a filesystem using Amazon S3, for example? At least one way, since I am discouraged from creating an extension that still does this in version 3.2.x.

I saw your comment on [this link](https://discuss.bolt.cm/d/496-how-do-use-s3-file-system-with-bolt-3-1) stating that I would write something demonstrating how to use, but A starting point would be a great help.

Something that was still trying in version 3.2.x is something like the code below:

```php
<?php

namespace Bolt\Extension\YourName\YourExtension;

use Bolt\Extension\SimpleExtension;
use Silex\Application;
use Aws\S3\S3Client;
use Bolt\Filesystem\Filesystem;
use League\Flysystem\AwsS3v3\AwsS3Adapter as Adapter;

class YourExtensionExtension extends SimpleExtension
{
  public function boot(Application $app)
  {
    parent::boot($app);

    $client = new S3Client([
      'credentials' => [
        'key'    => '[key]',
        'secret' => '[secret]'
      ],
      'region' => '[region]',
      'version' => 'latest'
    ]);

    $adapter = new Adapter($client, '[bucket]');
    $filesystem = new Filesystem($adapter);
    // Then with Bolt App
    $app['filesystem']->mountFilesystem('files', $filesystem);
  }
}
```

**Comment by CarsonF** [comment]
@romulo1984 Are you looking for an example for 3.2 or for 3.3?

**Comment by romulo1984** [comment]
@CarsonF 3.3.

**Comment by romulo1984** [comment]
News, @CarsonF?

**Comment by CarsonF** [comment]
It's just not the easiest answer and everyone is waiting on me for some code. @GawainLynch and I have a doc page in progress that will describe the solution fully.

**Comment by romulo1984** [comment]
Documentation of this will be perfect. Thanks.

**Comment by GawainLynch** [comment]
> Documentation of this will be perfect. Thanks.

Yep, it is coming along nicely … I am doing a little bit of it each day, and trying to find time to review with Carson across time zones :smile: 

Please do note, we're documenting the Bolt part with appropriate links to Amazon's documentation for their part … mainly, it is the implementor's job to make sure the Amazon side itself it correctly configured.

**Comment by romulo1984** [comment]
@GawainLynch @CarsonF Any news? Could you please cheer me up with some drafts.

**Comment by GawainLynch** [comment]
[If you insist](https://github.com/bolt/docs/pull/740) :wink:

**Comment by romulo1984** [comment]
@GawainLynch Very good. Thanks, this will help a lot.

**Comment by GawainLynch** [comment]
We're going to merge the SPs into one, I just need time … but if you know what you're doing, that's all enough information to get you started.

**Comment by romulo1984** [comment]
It's more than enough.
The expectation now is the launch of 3.3.
