### ISSUE TITLE
Allow themes to use bolt's jquery library

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#4098]
Currently, jQuery can be included in two ways : 

* In config.yml : add_jquery key
* In extensions : Extension::add_jquery() method.

Themes can't "force" usage of jQuery and should be able to by setting key in their config.yml.

Like in #3951

**Comment by bobdenotter** [comment]
Sounds sensible! I'd be in favor of this.

**Comment by bobdenotter** [comment]
Fixed!
