### ISSUE TITLE
Display a views count

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4102]
Sorry if this is just a stupid question, but it seem like Bolt lacks one of basic features for a CMS - a possibility to display how many times a current record was viewed. Can I achieve a possibility to display an amount of views via extension?

**Comment by SahAssar** [comment]
It can be done via an extension, but saying that it's a "basic feature" seems a bit... off. View counters have generally gone the way of the dodo since 10 years. They are also highly inaccurate in most cases because of bots, browser prefetching and other factors.

**Comment by dennschu** [comment]
@C4Grey consider the use of piwik or google analytics if the feature is still that important for you. As positive side effect you off-load some processing from your server. For frontend count displaying you have to use their respective apis
