### ISSUE TITLE
Access config values in extension Nut Command

### ISSUE THREAD

**Issue by gerob** [bolt/bolt#4103]
I'm having issues with accessing config values when using a Nut command. I've tried passing the application into a constructor, extending `Bolt\Nut\BaseCommand` and just calling `$app`.

Could someone tell me what I'm missing here?

I'm trying to do something like this.

`$db_info = $app['config']->get('general/database/host');`

Thanks!

**Comment by bobdenotter** [comment]
We figured it out on IRC: `$this->addConsoleCommand(new DbImportCommand($this->app));`

**Comment by gerob** [comment]
Thanks Bob! I meant to come back and update this with that info. :)
