### ISSUE TITLE
Resource contenttypes should be invisible in link-tool

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#4120]
I noticed that the link-tool popup gives the opportunity to link to viewless contenttypes, which would result in an error in the frontend. If possible, it would be better not to show these.

In this example the quotes and the libraryitems:
![files_ _bolt_-_2015-09-21_09 47 13](https://cloud.githubusercontent.com/assets/3974120/10000757/71340c5e-609e-11e5-8c0c-0785603c6079.png)

**Comment by royallthefourth** [comment]
Where do you access this popup? I'd like to try fixing this one.

**Comment by rossriley** [comment]
The url is `/async/filebrowser/`

You get to it by hitting the 'browse server' button on the ckeditor link modal.

**Comment by royallthefourth** [comment]
Sent pull request #4320 with a fix
