### ISSUE TITLE
[RFC/Poll] Twig namespace for admin templates

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4131]
We need move our backend templates to a separate twig namespace. Suggestions?

- `@bolt`
- `@backend`
- `@BoltBackend`
- `@admin`
- `@BoltAdmin`

It's used like this:
```twig
{% extends '@namespace/foo/bar.twig' %}
```

**Comment by GawainLynch** [comment]
I like this:
```twig
{% extends '@at/imperial/walker.twig' %}
```

**Comment by bobdenotter** [comment]
My vote goes to `@bolt`. :+1:

**Comment by rarila** [comment]
``@bolt`` :+1:

**Comment by CarsonF** [comment]
`@bolt` it is

**Comment by rarila** [comment]
Now that was a fast one :racehorse:

**Comment by GawainLynch** [comment]
Glad you got to put your voice in @rarila :wink:

**Comment by rarila** [comment]
@GawainLynch Now I wait for you to add ``imperial/walker.twig`` (optionally ``johnny/walker.twig``)

**Comment by rossriley** [comment]
damn did i miss the vote?

what about `@beer`

**Comment by rarila** [comment]
@rossriley I hope it is not too late …
