### ISSUE TITLE
Timed Publication timezone issue

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4139]
Hello,

Server and bolt.cm have the same timezone and output the same time to me. 

When I set the publication date to (now + 1 minute) and the status to "Timed publish" it doesn't work. 

I have to subtract 2 hours to make it work.

I am in the timezone `Europe/Berlin`. 

Any other places where I have to check the timezone?

**Comment by GawainLynch** [comment]
PHP and time zones… :frowning: 

If the time zone isn't set in `php.ini` then PHP gets upset, so we have an override in `app/config/config.yml` that you can set… 

Best approach is to make sure that `php.ini` has `date.timezone = "Europe/Berlin"` and that `app/config/config.yml` has `timezone: Europe/Berlin` set and you should be good.

**Comment by PhillippOhlandt** [comment]
php.ini = check
config.yml = check

Everything looks fine. When I dump the current time in my Extension I get the correct time and the system time is the same.

**Comment by GawainLynch** [comment]
OK, tested here on 2.2.11 and seeing similar problems (WEST)

**Comment by PhillippOhlandt** [comment]
I am on 2.2.9 btw

**Comment by GawainLynch** [comment]
@PhillippOhlandt are you using an Sqlite database?

**Comment by PhillippOhlandt** [comment]
Yep

**Comment by GawainLynch** [comment]
Yeah, Sqlite sees CURRENT_TIMESTAMP as always UTC… Looking deeper

**Comment by PhillippOhlandt** [comment]
Damn, go home sqlite, you are drunk!

Ok then it should work when we switch to mysql in production. Good.

**Comment by GawainLynch** [comment]
Haha! Yeah, pretty much. I am looking at the Doctrine docs now to see what we can do for Sqlite

**Comment by bobdenotter** [comment]
Fixed by #4146.

**Comment by PhillippOhlandt** [comment]
+1
