### ISSUE TITLE
Idea: Backend content hooks

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4147]
Hello,

it would be nice if an Extension can hook into several views and put own content in it. 

For example: You build a poll extension and want to show statistics in the dashboard above the "recently updated" feed. 

Or you want to add another button to the sidebar in the create or update form of an entity.

**Comment by GawainLynch** [comment]
@bobdenotter is working on a "widgets" feature at the moment, not sure if it will make 2.3 though as we're already in freeze.

**Comment by PhillippOhlandt** [comment]
Ah nice. I am excited.

**Comment by SahAssar** [comment]
Closing cause implemented in #4258, and dropping in 2.3 :)

**Comment by GawainLynch** [comment]
> and dropping in 2.3 :)

I so read that as "being removed in 2.3" as was like :confused:
