### ISSUE TITLE
Idea: Own pages in the backend

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4148]
Hey,

it would be nice if an Extension can add a new page to the backend (also linked in sidebar) that contains custom content.

That would make this very flexible CMS alot more flexible.

**Comment by SahAssar** [comment]
That is already possible, see the menueditor or boltformseditor plugins.

**Comment by PhillippOhlandt** [comment]
Ah ok, thanks. Will look at them.
