### ISSUE TITLE
Idea: DB table definition in contenttypes config

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4149]
Hey,

it would be nice if the user can tell the system which DB table it should use for a contenttype. 

Example: 

```
pages:
    name: Pages
    singular_name: Page
    table: site_pages
```

Then the system would look (er create first) in the table `site_pages` or `bolt_site_pages` (when slug defined).

Usecase would be:

You have a few sites that share some data (e.g. books) but also have per-site specific entities or relation between entities. 

For example: You have two systems on the same database with books and pages. You want to have the same books in both systems but each system has its own pool of pages. 

Then you can define the `pages` contenttype in each system but with different DB table names so they are stored in its own table. The `books` contenttype would use the same DB table in both systems.

**Comment by bobdenotter** [comment]
This is already present. I think it's called `table_name: `.

(Not sure, because I'm in a train so I can't look it up properly)

**Comment by GawainLynch** [comment]
Also already possible with the `tablename` key

**Comment by GawainLynch** [comment]
No underscore…

**Comment by PhillippOhlandt** [comment]
Oh ok, isn't it in the docu or did I miss it?

**Comment by PhillippOhlandt** [comment]
Nope it is not in the docu (so you cannot blame me for this issue here :P)

**Comment by GawainLynch** [comment]
No blame at all mate… we haven't documented it yet as it was a work around for a bug introduced in v1.2 and there is BC problems if we fixed said bug.

Also, we hang out on Freenode in #boltcms too, that's always a good place to asynchronously chat with us if you're so inclined.

**Comment by PhillippOhlandt** [comment]
I will join on monday =)
