### ISSUE TITLE
Templatefields do not show in editcontent on viewless records

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4150]
When using a templateselect on a contenttype that is viewless the templatefields do not show in the backend. 

While I understand that this might be an unusual way of using them, in some of my themes they are used to define "partials", that are never meant to be viewed by themselves, and therefore are viewless, but they also have their own template and template specific fields.

An example of this would be a one-page theme where it is listing "sections" on the homepage that each has it's own templatefields and template by using an index.twig akin to this:

	{% extends '_base.twig' %}
	{% block body %}
		{% for record in records %}
				{% include record.templateselect ignore missing %}
		{% endfor %}
	{% endblock %}

Tested on 2.2.3, 2.2.10 and Master.

**Comment by Pinpickle** [comment]
Just ran into this myself. Another usecase is the commonly cited `resources` content type. Templatefields allow potentially many different kinds of resources.

Culprit code for 2.2.x is in [Content.php](https://github.com/bolt/bolt/blob/703f259373c3b39385f42ac00e334affb96dfb62/src/Content.php#L590)

```php
if ((!$this->contenttype['viewless']) // Just remove this condition and we're sweet
    && (!empty($this['templatefields']))
    && ($templateFieldsConfig = $this->app['config']->get('theme/templatefields'))) {
        $template = $this->app['templatechooser']->record($this);
        if (array_key_exists($template, $templateFieldsConfig)) {
            return true;
        }
}
```

**Comment by SahAssar** [comment]
In my testing this is not an issue in master anymore, but when looking at the code it should be because of https://github.com/bolt/bolt/blob/master/src/Storage/Entity/ContentValuesTrait.php#L591

I can't really wrap my head around this, does anyone know why? I know there was quite a bit of discussion about the implementation of templatefields pretty early on 3.0dev.

**Comment by SahAssar** [comment]
Posting a chatsnippet here for future reference.

```
15:38	gawainlynch	Just read that… rossriley would be the person to answer that
15:39	SahAssar	Ah, right :)
15:40	gawainlynch	Oh wait, I thought that was frontend
15:40	gawainlynch	No… Template fields are in proper classes now
15:41	SahAssar	So hasTemplateFields is not used to check if the template tab should be shown in editcontent?
15:42	gawainlynch	I strongly doubt it
```
