### ISSUE TITLE
Why do I get an error when uploading bolt from local to online server

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#4152]
I get an error when I upload my local project to an online server.
Local is ``apache`` / ``php`` , online is ``apache`` / ``php``.
Local I used sqlite / online I use ``mysql`` driver.

``
Bolt - Kritieke fout.
Class Twig_Error_Runtime
Bericht: An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT bolt_widgets.* FROM bolt_widgets WHERE (`bolt_widgets`.`status` = 'published') ORDER BY `desc` LIMIT 9999': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'de
``

**Comment by bobdenotter** [comment]
Probably because the database isn't initialised online. 

- Clear the entire app/cache/ folder
- Reload `/bolt`

and it should work.

**Comment by melcarthus** [comment]
O boy, I just looked at my zip and the full contents of the cache dir was transfered...I normally leave it empty. Thx for the quick response, I overlooked the cache dir this time...

**Comment by GawainLynch** [comment]
Hehe… Zero stress, we know this one from the amount of times we do it ourselves. :grin:

**Comment by melcarthus** [comment]
The issue still remains guys.. I figured out the culprit, my ``contenttype``

``
widgets:
    name: Widgets
    singular_name: Widget
    fields:
        <<: *field_defaults
        route:
            type: text
            label: "Route via Google Maps"
        <<: *template_defaults
        <<: *field_adress
    vieuwless: true
    searchable: false
``

If I remove this then bolt wil load without errors.

**Comment by melcarthus** [comment]
To be more precise,

I have to remove ``oderby 'desc';

```twig
	        {% setcontent records = "widget" orderby 'desc' %}
```

**Comment by GawainLynch** [comment]
Hmm… OK, I'll reopen.

**Comment by jadwigo** [comment]
``` orderby 'desc' ``` 
does that mean you want ordering in descending order, or do you want to order the column named 'desc' 

otherwise you should ```orderby -title``` (order by the column 'title' in descending order)

**Comment by melcarthus** [comment]
I added the "widgets" in the wrong order into bolt, so I wanted to flip them, order desc helped on my local dev machine but it broke online, order by title also worked btw.

**Comment by jadwigo** [comment]
you can also order by other fields, eg. 'id', see https://docs.bolt.cm/content-fetching#ordering-results
