### ISSUE TITLE
Cannot install third party composer packages as dependencies for extension

### ISSUE THREAD

**Issue by dennschu** [bolt/bolt#4154]
1. **Bug summary**:
	Third party composer packages cannot be installed through composer *(inside extensions directory)* when they are registered as a *single* extension dependency.

2. **Specifics**: I created a private non-local extension (delivered through private satis registry that is added to extensions composer.json) which reads the projects git repository and provides the actual (HEAD) version hash through a twig function. Bolt has the version `2.2.10` and composer `1.0-dev (afd98b74f13b9def1b2447f16fd0bfd4d96dff94)`. Bolt and composer work as expected except in case of third party extension dependencies.

3. **Steps to reproduce**:
	4. Add dependency e.g. `cypresslab/gitelephant` to extensions composer.json file *(`[project_root]/extensions/vendor/org/extension_name/composer.json]`)*
	5. update private registry
	6. install the extension through `composer install` 

4. **Expected result**: 
	- extension should be installed with all required dependencies
	- version conflicts should be resolved (don't try to install e.g. symfony command twice)

5. **Actual result**:
	- extension got installed but third party dependencies like `cypresslab/gitelephant` are skipped toggling `"packagist": false` to `true` inside `[project_root]/extensions/composer.json` does not solve the issue

### composer config files that are used

**`[project_root]/extensions/vendor/organisation/composer.json`**

		{
		  "name": "organisation/bolt-nut-backup-command",
		  "description": "",
		  "type": "bolt-extension",
		  "require": {
		    "bolt/bolt": ">=2.0.0,<3.0.0"
		  },
		  "license": "MIT",
		  "authors": [],
		  "autoload": {
		    "files": [
		      "init.php"
		    ],
		    "psr-4": {
		      "Bolt\\Extension\\Organisation\\GitVersion\\": [ "", "src" ]
		    }
		  }
		}

**`[project_root]/extensions/composer.json`**

		{
		  "repositories": {
		    "packagist": false,
		    "organisation": {
		      "type": "composer",
		      "url": "http://packages.organisation.de/private/"
		    },
		    "bolt": {
		      "type": "composer",
		      "url": "https://extensions.bolt.cm/satis/"
		    }
		  },
		  "minimum-stability": "stable",
		  "prefer-stable": true,
		  "config": {
		    "discard-changes": true,
		    "preferred-install": "dist"
		  },
		  "provide": {
		    "bolt/bolt": "2.2.10"
		  },
		  "extra": {
		    "bolt-web-path": ".././"
		  },
		  "autoload": {
		    "psr-4": {}
		  },
		  "scripts": {
		    "post-package-install": "Bolt\\Composer\\ExtensionInstaller::handle",
		    "post-package-update": "Bolt\\Composer\\ExtensionInstaller::handle"
		  },
		  "require": {
		    "organisation/bolt-starter-theme": "~0.1",
		    "organisation/bolt-git-version": "~0.1.0"
		  }
		}

**`[project_root]/composer.json`**

		{
		  "name": "organisation/bolt-composer-install",
		  "description": "",
		  "license": "MIT",
		  "repositories": [
		    {
		      "type": "composer",
		      "url": "http://packages.organisation.de/private/"
		    }
		  ],
		  "require": {
		    "bolt/bolt": "~2.2.8",
		    "composer/composer": "1.0.*@dev",
		    "ircmaxell/random-lib": "dev-master",
		    "league/fractal": "^0.12.0",
		    "neomerx/json-api": "~0.5.0",
		    "deployer/deployer": "^3.0",
		    "maknz/slack": "^1.7"
		  },
		  "config": {
		    "vendor-dir": "vendor",
		    "bin-dir": "bin"
		  },
		  "authors": [],
		  "autoload": {
		    "psr-4": {}
		  },
		  "minimum-stability": "beta",
		  "prefer-stable": true,
		  "scripts": {
		    "post-create-project-cmd": [
		      "Bolt\\Composer\\ScriptHandler::bootstrap",
		      "Organisation\\Bolt\\Installer\\InstallerScriptHandler::postInstallCmd"
		    ],
		    "post-install-cmd": [
		      "Organisation\\Bolt\\Installer\\InstallerScriptHandler::postInstallCmd"
		    ],
		    "post-update-cmd": [
		      "Organisation\\Bolt\\Installer\\InstallerScriptHandler::postInstallCmd"
		    ]
		  },
		  "extra": {
		    "branch-alias": {
		      "dev-master": "2.3-dev"
		    },
		    "bolt-web-dir": "./",
		    "bolt-app-dir": "./app"
		  }
		}

**Comment by GawainLynch** [comment]
This works for me, I was literally just setting up a test instance yesterday and I have been using this workflow since the Composer functionality was added in 2.0-dev.

Are you sure that your Satis JSON is built correctly, and that it knows the repos of any dependencies?

**Comment by dennschu** [comment]
@GawainLynch You are right i had to add `cypresslab/gitelephant` package to our satis registry because the extensions composer.json does not use packagist. But then it starts to fail on sub dependencies. Ok i added these. Installation went fine but now it fails because monolog class gets redeclared... 

I got the feeling working against your extension system and composer – am I right?

**Comment by GawainLynch** [comment]
Yeah, Composer is a pain in the butt with is stuff... When yu define a "composer" repo weird things happen with dependencies. One thing that partially works is to add this unwanted libraries I the "provides" section... But I am still working not the Composer logics on this.

**Comment by dennschu** [comment]
@GawainLynch But how can we solve this. I think it is a common requirement the define third party dependencies of an extension in its `composer.json` without resolving sub-dependencies manually because that is or better has to be composers job. I understand that the usage of composer as framework for managing bolt extensions enforces some limitations... maybe we can merge the projects autoload file with extensions autoload file at the time of installing extension dependencies in order to prevent that already declared dependencies are required a second time - what do you think?

**Comment by GawainLynch** [comment]
I am actually working on this in a local branch… but it gets sticky quite fast, and we're in freeze right now for the upcoming 2.3 but a number of us want/need a better solution during the later 2.x series… and the mumblings with respect to 3.x are some big changes too.

**Comment by dennschu** [comment]
Thats sounds very good because the actual implementation is show stopper for extension development. Would you mind sharing your progress on the topic maybe i can shim in and support you. *Background:* We are in progress of building a plattform that consists of multiple bolt systems that share the same codebase and use extensions for e.g. [json-api](http://jsonapi.org/) endpoint that uses [neomerx/json-api](https://github.com/neomerx/json-api) package and are only different by content and some frontend-styling/branding. An extension composer system that can seamless manage third party packages like the main/project composer system would be a big improvement. What do you think?

**Comment by GawainLynch** [comment]
> Would you mind sharing your progress on the topic maybe i can shim in and support you

I would happily, but it's saved to an external hard drive that's at home in Lisbon, and I am currently in The Hague for the week. The other side of it was the Satis part which is hiding on bolt.cm… but that's in bits. 

Feel free to kick something off and we can collaborate further. I also just want to (re)mention that the current development cycle is in feature freeze, so changes would be targeted at 2.4. :grin:

**Comment by SahAssar** [comment]
@dennschu I'm currently running a similar system (many boltsites sharing the same codebase), but doing it in a way which is based on https://docs.bolt.cm/howto/muti-site-setup

Anyway, I'll be watching with interest what comes of this :)

**Comment by SahAssar** [comment]
This seems like a duplicate of #2365 to me, so I'm going to close this one, please feel free to reopen if I am wrong. While that conversation has gone a bit 'stale' it would be great to keep this one in one place since whatever you come up with will probably be helpful to other people :smile:
