### ISSUE TITLE
CSRF cookie for paths with trailing slash

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4157]
![](https://cloud.githubusercontent.com/assets/1427081/10122299/2c261752-650c-11e5-9a18-6558819aa67f.png)

We shouldn't set a cookie for a path with a trailing slash if we are just redirecting to a non-trailing slash route.

Not sure the best option to forward yet.

**Comment by GawainLynch** [comment]
Related to #3929

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by GawainLynch** [comment]
Yes… We need a "Waiting on Carson" tag I think…
