### ISSUE TITLE
Force leading period on domain for session cookies

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4158]
`.foo.com` instead of `foo.com`

**Comment by GDmac** [comment]
> The leading dot means that the cookie is valid for subdomains as well; nevertheless recent HTTP specifications (RFC 6265) changed this rule so modern browsers should not care about the leading dot. The dot may be needed by old browser implementing the deprecated RFC 2109.


http://stackoverflow.com/a/20884869/25286

**Comment by GDmac** [comment]
So, yes, pick on one notation, but unsure if it should be including a leading dot.

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by GawainLynch** [comment]
@CarsonF is working on the outstanding sessions stuff presently.

**Comment by CarsonF** [comment]
By setting the domain the leading period is implied by browsers. There's no need to force it.
