### ISSUE TITLE
Suggested Nginx config returns 403 for all URLs on OSX

### ISSUE THREAD

**Issue by codesman** [bolt/bolt#4171]
Tested on Bolt 2.2.11, Chrome 45.0.2454.101, OSX 10.10.3, Nginx 1.8.0, PHP 5.6.13_3, Xdebug v2.3.3, MariaDB 10.10

## Description:

When implementing the suggested Nginx server config outlined in https://docs.bolt.cm/installation, all pages return 403.

## To Recreate

Use the Nginx config as suggested at https://docs.bolt.cm/installation.  Run the app.  Any/all urls return 403.

## The Issue:

The directive that is supposed to deny invisible files is missing a slash, so essentially is denying everything.  Makes sense!  Is this just an OSX issue?  Does this config work properly on other OS?

## The Fix?:

Change this:
``` php
# Block hidden files
    location ~ \. {
        deny all;
    }
```
To this:
``` php
# Block hidden files
    location ~ /\. {
        deny all;
    }
```

**Comment by GawainLynch** [comment]
Yeah, I am guessing it is some sort of oddity with OSX… I run a lot of sites on Nginx as to a lot of the core team.

**Comment by SahAssar** [comment]
@GawainLynch Does the OS X version work on both platforms? if so that's probably the one we should include in the docs, and if not we should probably have a note/footnote that describes the fix, no?

**Comment by GawainLynch** [comment]
@SahAssar the problem I have here is that `location ~ /\. {` bind the rule to the root directory, so if you had `/foo/.htpasswd` file, that would not be denied.

**Comment by codesman** [comment]
@GawainLynch in my experience on OSX(and CentOS and Ubuntu), the `location ~ /\.` rule does not bind to the root directory.  I just tested by putting a .foo file in my stylesheets directory.  When I hit /theme/default/css/.foo, I get 403.  I mention CentOS and Ubuntu because I have had apps running with that config on those OS' for long times.  Is binding to root a Windows thing?

This is touched on a bit here: http://stackoverflow.com/questions/2999353/how-do-you-hide-git-project-directories

Which brings up another point.  Returning 403 is considered a security faux pas.  We shouldn't divulge what exists and what does not in production.  Although that is perhaps out of our scope as we are talking about a baseline local dev config, correct?

I have altered my config to:
```php
# Block hidden files
    location ~ /\. {
        access_log off;
        log_not_found off;
        deny all;
        return 404;
    }
```
Which works for me on OSX 10.10, Centos 6.6/7 and (IIRC)Ubuntu 12/14.

Perhaps a comment in the config would be helpful, such as:
```php
# Block hidden files
# If everything is coming up 403 for you, try changing this to `location ~ /\.`
    location ~ \. {
        deny all;
    }
```

**Comment by GawainLynch** [comment]
I tested it here and yes, this works fine:

```php
    # Block hidden files
    location ~ /\. {
        access_log off;
        log_not_found off;
        deny all;
        return 403;
    }
```
I'll update the docs.

> Returning 403 is considered a security faux pas

I have to disagree. This will return 403 based on pattern, regardless of if the target exists or not.
