### ISSUE TITLE
permission 'view', would not work in frontend?

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#4174]
Hello!.
I changed the configuration of permissions.yml, assume that anonymous users can not view the 'pages'.
![captura de pantalla_2015-10-01_00-08-23](https://cloud.githubusercontent.com/assets/6233822/10212120/41d963de-67d1-11e5-9cee-ba4501db44ee.png)
![captura de pantalla_2015-10-01_00-15-14](https://cloud.githubusercontent.com/assets/6233822/10212157/8d0ffd04-67d1-11e5-9887-45f5cd7f099f.png)

However, this is not so.
I think in the frontend driver permission 'view' is not checked.

![captura de pantalla_2015-10-01_00-07-40](https://cloud.githubusercontent.com/assets/6233822/10212121/41dc05bc-67d1-11e5-841b-9021eca98696.png)

**Comment by GawainLynch** [comment]
Hola @serweb-labs!

Permissions in Bolt are only valid for the backend

**Comment by serweb-labs** [comment]
Hola Gawain!
Sorry to hear that, with two lines of code could be solved if there is consensus.
```yml
# This is an example of how to define Contenttype specific permissions
#
#contenttypes:
#    # Keys in this dictionary map to keys in the contenttypes.yml specification.
#  showcase:
#        # Rules defined here *override* rules defined in contenttype-default,
#        # but *add* to rules in contenttype-all. This means that permissions
#        # granted through contenttype-all cannot be revoked here, merely
#        # amended.
#
#        # Only the Admin and Chief Editor are allowed to edit records
#        edit: [ admin, chief-editor ]
#        create: [ admin, chief-editor ]
#        publish: [ admin, chief-editor ]
#        depublish: [ admin, chief-editor ]
#        delete: [ admin, chief-editor ]
#        # Roles that can see the area in the admin section
#        view: [ developer, admin, chief-editor ]
#        # Do not expose this content type on the front-end unless user is
#        logged into the backend
```

"Do not expose this content type on the front-end unless user is  logged into the backend".
I can not understand if that comment is correct.
Surely it is my problem with the language.

**Comment by GawainLynch** [comment]
Bolt used to have this feature, but it did not work properly and the decision was made to remove it during 2.0-dev.

There is `bolt/members` extension that provide the ability to do this in the frontend using OAuth2, but it is still being worked on as I do not have enough time in my day :grin:

**Comment by bobdenotter** [comment]
For a _really_ low level solution, you could always use [PasswordProtect](http://extensions.bolt.cm/view/2e8d4d94-bb78-43a6-aa32-78bbbc63480c).

**Comment by serweb-labs** [comment]
I understand, thank you for your cooperation.
That believe this comment Should be removed?
or simply close the issue ?.  :v:

**Comment by SahAssar** [comment]
@serweb-labs closing the issue, feel free to reopen if you have more questions regarding this :)
