### ISSUE TITLE
Local configuration files

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4176]
Hey,

for our project, I push all config files into git to deploy them easily. After deployment I have to disable debug mode and other things by hand. 

It would be nice if the user can create files called like `config.yml.local` or `config.local.yml` to override the default values in `config.yml`. Then the user can use different settings on his dev machine than his production machine.

**Comment by rossriley** [comment]
Hey.
This is already available, check the docs here for how to use: https://docs.bolt.cm/installation#different-configs-environment

**Comment by PhillippOhlandt** [comment]
Oh nice. Never scrolled down that much, lol xD Sorry =)
