### ISSUE TITLE
How to get Doctrine Manager?

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4177]
Hey,

because 2.3 isn't out yet, I have to write some Doctrine Models to interact with the database to import and update some data.

I found this but I need the Doctrine Manager to store the model in the database:
http://symfony.com/doc/current/book/doctrine.html#persisting-objects-to-the-database

Is it possible to resolve the Doctrine Manager from the app instance?

**Comment by Raistlfiren** [comment]
@PhillippOhlandt In an extension you can access doctrine by doing 

```php
$this->app['db'];
```

You could also always just create a separate script that connects to the database through PDO to import data in to keep everything simpler.

**Comment by PhillippOhlandt** [comment]
When I try `$this->app['db']->persist();` I get `Call to undefined method Doctrine\DBAL\Connection::persist()`

**Comment by Raistlfiren** [comment]
Sorry, I think what you are actually looking for is this reference: https://docs.bolt.cm/storage/repositories

Except you would use save instead of persist.

**Comment by Raistlfiren** [comment]
Mind you that is for Bolt 2.3+

**Comment by Raistlfiren** [comment]
Otherwise, you can just use $this->app['db']->executeQuery('SELECT * FROM bolt_users');

**Comment by PhillippOhlandt** [comment]
I want use the Repositories but 2.3 isn't out yet. And I don't want to use raw queries. There must be a way to get the Doctrine Manager ...

**Comment by rossriley** [comment]
@PhillippOhlandt you need to note that Bolt only uses DBAL and not the full ORM so you don't have access to the Doctrine Manager by default. If you want to use it, you'll need to require `doctrine/orm` in your project base, and make a provider that registers it with Silex.

It can be a bit hard though to get Bolt and ORM to play nicely together, which is one of the things we are trying to address in the next version...

**Comment by PhillippOhlandt** [comment]
Damn, ok. When will 2.3 be released or can I use the master branch for now to use the repositories?

**Comment by SahAssar** [comment]
@PhillippOhlandt the current stated release date is 12 October 2015, but that might be pushed. 2.3 contains quite a bit of changes, so the bugfix phase might need to be extended.

**Comment by PhillippOhlandt** [comment]
Ok our release date for the product is 14 October 2015. I'll try to use the master branch until the release of 2.3.

**Comment by SahAssar** [comment]
@PhillippOhlandt Actually, looking at the calendar it will almost surely be pushed, I thought it was more than a month to 12th of October.

**Comment by SahAssar** [comment]
Going to close this one, as the fix is already in the next version and cannot be backported

**Comment by GawainLynch** [comment]
Yeah, the editing branch and the repeating fields are not in yet as the FSM is punishing @rossriley and myself for sins in previous lives…

I am running master on a couple of sites and the frontend stuff is mostly OK, but there are lots of known issues still with backend that will be addressed when the edit branch lands… YMMV.
