### ISSUE TITLE
Preview YouTube video on Bolt edit content with HTTPS

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#4179]
If you run your site behind HTTPS you cannot preview YouTube videos from the edit content templates as the embed link is hardcoded to use `http://` in the `bolt.min.js` file. This is for version 2.1.8 of Bolt.

The error message in Chrome network looks like this:

```Mixed Content: The page at 'https://mysite.co.uk/bolt/editcontent/events/11#media' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.embed.ly/1/oembed?format=json&key=51fa004148ad4d05b115940be9dd3c7e&url=https://www.youtube.com/watch?v=EhAFyaObY6U'. This request has been blocked; the content must be served over HTTPS.```

My apologies if this has already been fixed.

**Comment by bobdenotter** [comment]
This was fixed in #3961. If you upgrade to the latest 2.2.x, the problem should go away. :-)
