### ISSUE TITLE
Soliciting advice for project implementation

### ISSUE THREAD

**Issue by codesman** [bolt/bolt#4181]
Hello all,

I've inherited a legacy app/site/backend that has it's pieces in several parts.  WordPress for the frontend, an aging proprietary south-central-asian business logic backend and several mini-apps for various things.  It's a mess. Old, unmaintainable code.  Bus factor 1.

I would like to use Bolt to consolidate it all. And do it with style...

The structure that I would like to achieve is not what Bolt's default config is set up to do, so I'm asking for guidance on the best way to extend Bolt for my use case.

My long term goal:

An app that spreads functionality across 4 sub domains but runs off one codebase and is administrated by all users from a single domain.  app.domain.com, mail.domain.com, api.domain.com and www.example.com are the domains I'm working with.  TLS all the things.

1. app.domain.com
  a. **Frontend** - Not much here.  Requests to app.domain.com/ should return a login form, unless logged in and then return the Backend.
  b. **Backend** - Should only respond at app.domain.com/ if logged in.
    1. Need to remove bolt slug base from backend.

2. mail.domain.com
  a. **Frontend** - Responds to unauthenticated public requests to mail.domain.com at these 2 URLs:
    1. mail.domain.com/subscribe
    2. mail.domain.com/unsubscribe

  b. **Backend** - Handled by app.domain.com

3. api.domain.com
  a. **Frontend** - Responds to authenticated and unauthenticated public requests to api.domain.com
    1. Multiple endpoints.

  b. **Backend** - Handled by app.domain.com

4. www.domain.com
  a. **Frontend** - Responds to unauthenticated public requests to www.domain.com, the main website.
    1. This will be very tricky as it requires supporting legacy URLs that must maintain a nested page structure as well as an .html extension on any Page.

    a. Need to remove "page" slug and have pages available at root level on www.domain.com.

  b. **Backend** - Handled by app.domain.com and will attempt to replicate what is going on in our current, heavily modified WordPress site.

My goal is to implement these incrementally.  I would like to have 1 and 2 in production asap, but 3 and 4 are on a much grander timetable, like 3++ months.

Comment and suggestion are solicited! How would you do this?

Thanks,
Tom

**Comment by bobdenotter** [comment]
Hi, 

What you're doing here will require a bit more custom work than a "plain" bolt site, but I don't see any immediate obstacles. 

Some comments / pointers: 

> Need to remove bolt slug base from backend.

you cannot _remove_ this, but you can configure it to be something else than `bolt`, using the 'branding' settings in `config.yml`.

For the API parts, i'd look into the `JSON API` extension: http://extensions.bolt.cm/view/5f66c2bf-0eb1-11e5-9120-621e70d6e3eb

For setting up what's basically four instances of Bolt, and I'm guessing you'd like to share code between them. Roughly speaking there are two options for this: 

 - Look into [Advanced Installation Options](https://docs.bolt.cm/installation-advanced), and use this to set up four instances from the same codebase, modifying the bootstrap to suit your needs. 

 - Use distinct `config_local.yml` files which aren't in your versioning control system, to tweak and tune the differences between the instances. You'll likely wind up with some unused code on each of the subdomains, but it'll still be one codebase. see here for more info: [Performance and finetuning for Bolt websites](https://docs.bolt.cm/howto/performance-tips).

**Comment by codesman** [comment]
@bobdenotter thank you very much.  That's exactly the input I was looking for.

Could you explain why I would need 4 instances.  I couldn't run it all from one instance?

**Comment by CarsonF** [comment]
@codesman Yeah you can run them from one instance. It's going to take some coding though. How familiar are you with `Silex`?

**Comment by codesman** [comment]
@CarsonF Thanks, good to know.  Yes, I'm aware it will take some coding!  I'm cozying up to Silex.  Initially I was planning to build the app(s) with Silex but I don't need or want to write my own user management/cms functionality so I went looking for something I could "bolt" on to handle that.

**Comment by CarsonF** [comment]
Perfect. Then I'd recommend starting with the composer install.

Do `app, mail, api` need a backend? Or can they just redirect to the main sites backend (if appropriate)?

**Comment by codesman** [comment]
Excellent. I installed with the composer installer using the public directory option.  Then I extended Bolt\Composer\ScriptHandler with my own installAssets method and added that as a composer script on "post-update-cmd" and "post-install-cmd."

I also extended the ScriptHandler to bootstrap all the npm/bower/grunt stuff before I move the assets.
 
One thing that is not working is the tests.  I'm pretty sure that's because of directory structure. The Bolt tests directory is at /vendor/bolt/bolt/tests, but I think it needs to be at /tests.  When I go to /vendor/bolt/bolt and run `phpunit` it fails because `'Bolt\Tests\Cache\FooObject' not found`

However, if I move `tests/` and `phpunit.xml.dist` to the root directory, it fails with the same error.  I don't have much experience with tests, so I'm not quite sure how to fix this.

If I'm going to add tests for my app, I need to define my own tests and then figure out how to add the Bolt tests to mine.  Is that correct?  Any tips on how to set this up?

>Do app, mail, api need a backend?

`app.domain.com` IS the backend for the whole thing. There is no frontend on app.domain.com other than a login form if the requester isn't logged in. There is no logging in from anywhere other than `app.domain.com`.

I suppose another way of thinking of it is that I'm really just using subdomains for namespacing instead of subdirectories. `www, api` and `mail` are frontend only and this app could just as easily be served from a single domain as:

`www.domain.com/`
`www.domain.com/app/`
`www.domain.com/api/`
`www.domain.com/mail/`

However, our marketing email requires a separate subdomain with different MX, so that's why I need to respond at mail.domain.com.  If I didn't need to do that, I could just use www.domain.com/mail/.  That would save us a bit of cash on TLS certs!

Also, the www.domain.com site is already in production, so starting with app.domain.com will allow me to build the functionality incrementally and then replace www.domain.com when it is ready versus needing to integrate them from the get-go.

**Comment by bobdenotter** [comment]
Hi, 

We'd like to keep the issues list on Github focused on actionable items for Bolt. If you have a question about working with Bolt, would like feedback on an idea, or have a general issue with Bolt that's not "a bug", you're welcome to post about it on our discussion forum. We'll gladly help you out there! 

https://discuss.bolt.cm
