### ISSUE TITLE
ckeditor on chrome in android is not working

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4196]
If you use the backend on an android device the ckeditor component does not work. If you use the same on firefox (or iOS) it works.

According to the documentation the compatibility flags are changed in ckeditor 4.5 and the ckeditor should work. http://docs.ckeditor.com/#!/guide/dev_browsers - http://docs.ckeditor.com/#!/guide/dev_unsupported_environments

I'm happy to help test a fix, but I'm lost in trying to locate why it's not working.

**Comment by rarila** [comment]
Just a a reminder to myself and as a start for everyone else who wants to have a look a this problem: [Chrome remote debugging](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging)

(Thanks at @CarsonF for the link)

**Comment by jadwigo** [comment]
cool tip, testing this actually made me check the issue again.

On a tablet with android 4.1.1, chrome 46, and 1024x600 pixels screen ckeditor works

On a phone with android 5.1.1, chrome 46 and 640x360 pixels (reported pixels, the screen is actually 1280x720 pixels) ckeditor does not work. On other phones the same happens. Also landscape or portrait mode both don' t show the ckeditor.

When I go to the ckeditor site the same phone can use the demo editor.

So the ckeditor works on android with chrome, but the reported screen resolution might be the reason.

**Comment by rarila** [comment]
Interessting …

**Comment by jadwigo** [comment]
or maybe something in a mediaquery breakpoint somewhere?

**Comment by rarila** [comment]
Now you gave me an idea … looking for it …

**Comment by rarila** [comment]
Ok, #4416 didn't do it then … :worried: 

As for being connected to width: No problems on Chrome/Windows with a window width of 320px.

**Comment by jadwigo** [comment]
In chrome - if you turn on developer tools (f12) you can switch to mobile view and then emulate different devices - chrome then spoofs the user agent and screen sizes

![screenshot-selection_094](https://cloud.githubusercontent.com/assets/1488214/11062931/60df9c92-87b3-11e5-874b-6eb62fce89db.png)

A quick check:
- Google nexus 7 shows the ckeditor
- Google nexus 5 does not
- iphone 5 shows the ckeditor

**Comment by jadwigo** [comment]
Iphone emulation in chrome shows the ckeditor
![screenshot-selection_095](https://cloud.githubusercontent.com/assets/1488214/11062963/92337c28-87b3-11e5-9b96-24ea9a8c49f7.png)

**Comment by jadwigo** [comment]
Safari on osX with an iphone also does something similar: https://developer.apple.com/safari/tools/

**Comment by rarila** [comment]
Ok, now it gets funny. ``Google nexus 5`` works for my using the emulator

**Comment by jadwigo** [comment]
ah.. well, let met check.. the site in the screenshots is running on bolt 2.2.1

Aaaand ...testing it in another site running bolt 2.2.13 it works!

**Comment by rarila** [comment]
hehe, user error :-))

Anyway, glad it works now. One blocking issue less
