### ISSUE TITLE
[Tracker] Bolt 3.0 Release Blocking Issues

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4202]
Alright, this is my suggestion for what should be considered blocking for the 3.0 (previously 2.3) release. Everything has been labelled as such, so if you remove from here please also remove the label on the issue.

Criticism/additions/subtractions and ¯\\\_(ツ)_/¯ welcome!

Open
-------
##### Trackers
- #4503 [Tracker] Documentation updates
- #5098 [Tracker] Popular Extensions with Bolt v3 versions

##### Others

- #5184 [BUG] Check updates shows wrong new version for bolt/members

Closed
---------

- ~~#2409 Errors in search results front end~~ **[Fixed in #4522]**
- ~~#3210 Weird issue with sorting with grouping~~ **[Fixed in #4073]**
- ~~#3244 Error when saving content due to insufficient permissions~~ **[Fixed in #4233]**
- ~~#3346 Add error states for embed.ly (was: "Video preview and embed not always working")~~ **[Fixed in #4446]**
- ~~#3530 Feature Request: Pagination page item-optionbox remembering.~~ **[Fixed in #4221]**
- ~~#3787 Record editing lookups failing~~ **[Fixed in #4189]**
- ~~#3803 Error in taxonomy listing~~ **[Fixed in #4208]**
- ~~#3831 Potential BC/Functionality Break in Uploads~~ **[Fixed in #4835]**
- ~~#3868 Status transition changes removing taxonomy~~ **[Fixed in #4227]**
- ~~#3929 Is the new session code supposed to set 6 cookies?~~ **[Fixed in #4941]**
- ~~#3954 Cannot set session ID after the session has started.~~
- ~~#3983 Fix hardcoded file upload paths (files/)~~ **[Fixed in #4591]**
- ~~#3985 Dropdown at users&permissions stretches div and scrollbar appears~~ **[Fixed in aee9e5307990e6e4950f01c64b2264828798613d]**
- ~~#4043 [master] Datatype mismatch upgrading 2.2 database in PostgreSQL~~ **[Fixed in #4400]**
- ~~#4044 No related entries on preview~~ **[Fixed in #4341]**
- ~~#4046 [master] Fatal error when tables don't exist~~ **[Fixed in #4205]**
- ~~#4108 Filter db tables (was Port #3949 to 2.3)~~ **[Fixed in #4489]**
- ~~#4120 Resource contenttypes should be invisible in link-tool~~ **[Fixed in #4320]**
- ~~#4157 CSRF cookie for paths with trailing slash~~ **[Fixed in #4941]**
- ~~#4158 Force leading period on domain for session cookies~~ **[Fixed in #4941]**
- ~~#4196 ckeditor on chrome in android is not working~~ **[Fixed in #3963]**
- ~~#4206 Snippet queue doesn't seem to get processed in frontend~~ **[Fixed in #4207]**
- ~~#4209 Multiple relation fields don't clear when single relation used~~ **[Fixed in #4449]**
- ~~#4210 Taxonomy order not saved in record editor~~  **[Fixed in #4418]**
- ~~#4211 Unwanted dump() data in base-2016~~ **[Fixed in #4213]**
- ~~#4212 Database check incorrectly reporting required schema modifications~~ **[Fixed in #4215]**
- ~~#4217 Slug locked by default on new record (on master)~~ **[Fixed in #4218]**
- ~~#4220 Unable to delete records~~ **[Fixed in #4941]**
- ~~#4223 Clearing a templatefields selection doesn't clear the warning~~ **[Fixed in unknown PR]**
- ~~#4224 Template tabs not working correctly in editor~~ **[Fixed in #4333]**
- ~~#4225 Unable to add files to the Stack~~ **[Fixed in https://github.com/bolt/docs/commit/913f5f18bfad5e54cb9e8d4eecb597b932263ddd#diff-f54dbf5b5212b8f0ddac37ed4c5453d9]**
- ~~#4226 Can't change ownership for a record from root account~~ **[Fixed in #4230]**
- ~~#4237 Unable to disable users~~ **[Fixed in #4392]**
- ~~#4238 Errors in loading extension's info from git breaks JSON request by showing PHP error~~ **[Fixed in #4254]**
- ~~#4241 Upload permissions not working for non-root users~~ **[Fixed in #4267]**
- ~~#4243 Publish & Depublish buttons not hooked up yet~~ **[Fixed in #4280]**
- ~~#4253 Changing record status multiple times in overview clears taxonomies~~ **[Fixed in #4418]**
- ~~#4259 Relation contenttype with no title column [Fixed in #4352]~~
- ~~#4260 Link for "View (saved version) on site" re-opens the record editor~~ **[Fixed in #4448]**
- ~~#4281 Extension's query dialogue break when no stable versions are available~~ **[Fixed in #4490]**
- ~~#4286 [Tracker] Improving JS to support repeating fields~~ **[Continued in #4422]**
- ~~#4291 Uploading files too large gives incorrect error~~
- ~~#4332 $this->addJavascript and addCss doesn't add more than one js file.~~ **[Fixed in #4334]**
- ~~#4338 "Relationships" shows only 'from' relations, not the 'to' ones.~~ **[Fixed in #4449]**
- ~~#4339 Editing an existing record shows 'New ..' instead of 'Edit .. » ..'.~~ **[Fixed in  #4352]**
- ~~#4344 Adding relations on record creation causes a fatal error~~ **[Fixed in #4449]**
- ~~#4360 Adding a select in templatefields throws DB error~~ **[Fixed in unknown PR]**
- ~~#4373 Users added with app/nut have their password written to DB in plaintext~~ **[Fixed in #4390]**
- ~~#4442 Random password corruption~~ **[Fixed in #4445]**
- ~~#4450 Fatal errors in widgets, because Twig. ("Defining the initRuntime() method…")~~ **[Fixed in #4451 & #4468]**
- ~~#4453 Duplicate queries in `master`~~
- ~~#4457 New record creation prompt to unlock slug~~ **[Fixed in #4461]**
- ~~#4469 Select from server & Upload image buttons not working~~ **[Fixed in #4476 & #4480]**
- ~~#4477 Creating a record for a slugless contenttype entity gives an error~~ **[Fixed in #4579]**
- ~~#4516 "Searchweight" seems to have stopped working in 2.3~~ **[Fixed in #4519]**
- ~~#4518 unexpected behaviour of content type listing in frontpage controller~~ **[Fixed in #4617]**
- ~~#4532 "Default" values in contenttypes.yml aren't used.~~ **[Fixed in 4534]**
- ~~#4533 Leaving fields "empty" tends to throw errors~~ **[Fixed in #4851]**
- ~~#4550 Move preview link to Twig~~ **[Fixed in #4696 ]**
- ~~#4559 Side menu overlaps full screen markdown editor~~ **[Fixed in #4566]**
- ~~#4563 Empty array field types getting saved with attribute keys~~ **[Fixed in #4588]**
- ~~#4564 Using `{{ widgets() }}` without specifying a template throws an error.~~
- ~~#4567 MySQL can't create table with hyphen in ContentType name~~ **[Fixed in #4578]**
- ~~#4570 Relation select can get too wide.~~ **[Fixed in #4584]**
- ~~#4581 Missing variable error in repeating fields data~~ **[Fixed in #4630]**
- ~~#4590 Hardcoded cache path causes fatal error~~  **[Closed since seemingly fixed]**
- ~~#4620 Seeing `page.login.title` and other placeholders..~~ **[Fixed in #4855]**
- ~~#4623 Notices in frontend, on listing screen~~ **[Fixed in #4725]**
- ~~#4624 Notices in backend, when logging in~~ **[Fixed in #4753]**
- ~~#4652 Improve deprecation handling for controllers.~~
- ~~#4657 Editing Content is not Updating the modified timestamp~~ **[Fixed in #4741]**
- ~~#4667 RecursiveDirectoryIterator fatals when scanning /tmp/~~  **[Fixed in #4941]**
- ~~#4673 custom contenttype slugs is broken for listings~~ **[Ficed in #4841]**
- ~~#4703 Repeater field problems~~  **[Reported fixed in [dev meeting](https://github.com/bolt/bolt/wiki/Dev-meeting-2016-03-01)]**
- ~~#4706 Date in repeater throws an error~~ **[Fixed in #4739]**
- ~~#4710  post and prefix dont work in repeater fieldsr~~ **[Fixed in #4740]**
- ~~#4754 ContentType names with Capital Letters break~~ **[Fixed in #4841]**
- ~~#4755 Incorrect relationship keys give unclear error~~ **[PR #4852]**
- ~~#4763 unable to save records with an empty select field~~
- ~~#4789 Not root-account can't upload images~~ **[Fixed in #4842]**
- ~~#4797 "White screens of death" in PHP7.~~ **[Fixed upstream in 1.18.0]**
- ~~#4801 Whoops! v2 breaks AJAX error reporting/handling~~
- ~~#4802 Incorrect directory separator in extension assets path~~ **[Fixed in #4806]**
- ~~#4804 Admin menu permissions not working for user IDs > 1~~ **[Fixed by feeding the :koala: ]**
- ~~#4830 Relationships do not show correctly in selectbox~~ **[Fixed in #4843]**
- ~~#4858 The `{{ fields() }}` tag doesn't parse Twig in fields.~~ **[PR #4880]**
- ~~#4896 record.related() returns unpublished items in twig~~ **Fixed in #4897**
- ~~#4907 Twig variable missing in editor for text fields~~ **[Fixed in #4914]**
- ~~#4948 CacheHash fails for viewfiles because of path resolving~~ **[Fixed in #4959]**
- ~~#4953 Repeater field won't show unless there's also an 'html' field~~ **[Fixed in #4956]**
- ~~#4960 Bolt shouldn't break when it can't create `/thumbs`~~ **[Fixed in #4962]**
- ~~#4965 Users don't get logged off, when their account is revoked~~ **[Fixed in #5002]**
- ~~#4972 v2 extensions showing up on v3 extend page~~ **[Fixed in #4989]**
- ~~#4975 We need "Move up" and "move down" buttons for repeaters.~~ **[Fixed in #5005]**
- ~~#4980 Inconsistent results for 'homepage: page/1' and 'homepage: pages' settings.~~ **[Fixed in #4983]**
- ~~#5000 Select All in overview buggy~~ **[Fixed in #5000]**
- ~~#5007 newly created record doesn't get a publish date~~ **[Fixed in #5011]**
- ~~#5009 Can't delete a record from dashboard listing~~ **[Fixed in #5131]**
- ~~#5017 Your configuration does not allow connection to http://extensions.bolt.cm~~ **[Fixed in #5024]**
- ~~#5023 Extension assets not resolving paths correctly on Bolt Composer installs~~ **[Fixed in #5069]**
- ~~#5063 Dashboard settings menu broken links~~ **[Fixed in #5136]**
- ~~#5065 Schema manager isCheckRequired always returns true~~ **[Fixed in #5066]**
- ~~#5072 [BUG] Uniqueness of field names in repeater field~~ **[Fixed in #5099]**
- ~~#5094 "Pimple warning" when paging content.~~ **[Fixed in #5125]**
- ~~#5101 Base-2016 theme empty after install~~ **[Fixed in https://github.com/bolt/docs/pull/349]**
- ~~#5114 Default cookie domain value in header can't contain port number~~ **[Fixed in #5115]**
- ~~#5119 Records can't select templates~~ **[Fixed in #5127]**
- ~~#5117 Database entities won't hydrate if columns use captials~~ **[Fixed in #5117]**
- ~~#5142 Imagelist in templatefields is quirky: Doesn't "stick", Stack not working.~~ **[Fixed in #5188]**
- ~~#5143 Templatefields (and repeaters) should NOT allow templateselect.~~ **[NOTABUG]**
- ~~#5146 Preview page with not publish status catch Fatal error~~ **[Fixed in #5151]**
- ~~#5165 Not null constraint failed~~ **[Fixed in #5207]**
- ~~#5190 Newly created users are always enabled~~ **[Fixed in #5190]**
- ~~#5191 Omnisearch gives template error~~ **[Fixed in #5192]**
- ~#5199 [Upgrade] Fatal error in dashboard from getLatest()~~ **[Fixed in #5253]**
- ~~#5214 performance with multiple repeater fields~~ **[Fixed in #5216]**
- ~~#5218 Bad default values for list types~~ **[Fixed in #5221]**
- ~~#5240 Assets and paths in extensions~~ **[Fixed in #5244]**
- ~~#5250 can't delete a record from dashboard~~ **[Fixed in #5255]**
- ~~#5288 Repeater fields throwing fatals~~ **[Fixed in #5291]**

### Trackers
- ~~#4422 [Tracker] Repeating Fields Push to the Finish~~
  - ~~Replaces #4286 [Tracker] Improving JS to support repeating fields~~
  - ~~PR: #4479 WIP More fixes for repeating fields~~
 - ~~#4444 [Tracker] Missing functionality for widgets.~~
 - ~~#4556 [PSA] Upcoming v3 extension breakage~~

Moved to 3.1
----------------
- #3318 Bug in 'magic getter' for images
- #3424 Twig_Loader_String is deprecated
- #4439 Contenttype owner does not have Edit option under Actions in Overview Screen
- #4770 Numeric slugs
- #4095 Thumbnails/Uploads/FileManager with remote filesystems
- #5242 More v2 extensions showing up on v3 extend page
- #5161 Create Project from single composer.json throws errors

**Comment by wysow** [comment]
We should mark #4373 as done now... ;)

**Comment by SahAssar** [comment]
For the meeting tomorrow:

This seems to what we perhaps should think of fixing before release (besides what little is left in the tracker):

- #5084 [bug] notices in frontend on first pageview after cache clear
- #5085 [BUG][UX] back-end publish process quirks
- #5014 [BUG] unable to create first user on ip-based server

Also, if more time is magically found under the couch cushions (otherwise for 3.1?):

- #4895 [BUG] image field upload silently fails for cms users if a server error occurs
- #5025 [Bug] Error on save contentype. The “timepublish” input is not correct on Server with timezone UTC

And fix documentation for:

- #5029 [bug] v3 content type fields with float are not using html5 elements
- #5072 [BUG] Uniqueness of field names in repeater field
