### ISSUE TITLE
Taxonomy order not saved in record editor

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4210]

**Comment by rarila** [comment]
World record in label usage, gold medal! :full_moon:

**Comment by SahAssar** [comment]
I just thought there wasn't quite enough labels on this one.

**Comment by SahAssar** [comment]
Fixed the label issue that slick0 reported over IRC. #1555 added.

**Comment by GawainLynch** [comment]
Wow… a **major** regression bug and you all want to joke about issue tags… Stuff this, I'm off to go and use a real CMS like CMS Made Simple, or WordPress! :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
Is this a regression, really? I think taxonomies are unordered by design. At least, having categories `books` and `movies` is equivalent to `movies` and `books`.

**Comment by GawainLynch** [comment]
@bobdenotter my immediately previous comment was 100% satire.

What is not being saved is the "order" value in the record editor.
![taxonomy](https://cloud.githubusercontent.com/assets/1427081/10614969/0670f148-7755-11e5-9917-390fdc1e9be7.png)
