### ISSUE TITLE
PHP timeout before installation

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4219]
Hey,

I tried to install v2.2.11 but PHP times out before I see the install mask. 

https://infinit.io/_/3eDJTyW

What does the thing do in the background? Will it start from zero when I reload the page because I tried it 10 times? Why does it time out?

**Comment by GawainLynch** [comment]
That's a problem coming from you Vagrant instance's file system, not Bolt. Basically the dump you list is just Composer setting up the autoloader for extensions and the underlying file system isn't responding.

**Comment by PhillippOhlandt** [comment]
Ok, what can I do to solve this?

**Comment by GawainLynch** [comment]
No idea, I don't use Vagrant. :grin:

**Comment by PhillippOhlandt** [comment]
Damn. Tried to generate that fist on the Macbook itself and switched then to Vagrant but then it tries to regenerate it.

**Comment by PhillippOhlandt** [comment]
Ah, worked after a few times.
