### ISSUE TITLE
Unable to delete records

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4220]
From either the overview page or the record editor… I think the :koala: messed with the route logic.

**Comment by GawainLynch** [comment]
@CarsonF it might not have been the :koala: this time :stuck_out_tongue_winking_eye: 

```
× The security token was incorrect. Please try again.
× Content 'Id Sextilius factum negabat' could not be deleted.
```

**Comment by rarila** [comment]
No, that's not a bug, that's an advanced data protection mechanism!

**Comment by GawainLynch** [comment]
Jokes aside, what is happening is that the page is rendered with `$this->app['form.csrf_provider']->getToken('bolt_csrf_token')->getValue()` returns something like `60bbWAqXnpNPPQZWw9l7WRlW5vZ0U77Dio0HagM6DtM` but when `$this->app['form.csrf_provider']->getToken('bolt_csrf_token')->getValue()` is re-called in the controller we're getting `1aMRdsVkk_asJQSsOW2md1Yfy5gioftPfo8e5oToO1Q` from the same damn session key/value/cookie.

@CarsonF Also, I have tried adding a dump in the Csrf class and it is **not** recreating the token, but fetching it from the session storage… and page refreshes (for that session) produce the same tokens for each instance so it's not the fact that they're not being persisted in the session… :nut_and_bolt: is it :car: me

**Comment by CarsonF** [comment]
Ok so this is because the the `backend edit content` route is different than the `async content action` route. The CSRF token storage is now the _csrf session_ whose cookie is stored on the current path/route. So the token storage is different for each route thus the failure.

**Comment by GawainLynch** [comment]
Ouchy… Any brilliant ideas for this then?

**Comment by rarila** [comment]
Get your kicks on Route 66 … :notes:
