### ISSUE TITLE
Relationship auto complete enhancement

### ISSUE THREAD

**Issue by simnom** [bolt/bolt#4229]
Just a quick thought to improve the performance of the relationships autocomplete.  Could we set a minimum number of characters to initiate the search, by adding `minimumInputLength: 3` to the invoking code with `_relationships.twig`.

I have a site with a large amount of articles and it's really slow to do the initial lookup on a single character, setting a minimum length makes this much more bearable.

I wonder if long term it might be better looking these up via ajax rather than loading into the main add/edit screen.

**Comment by GawainLynch** [comment]
> I wonder if long term it might be better looking these up via ajax rather than loading into the main add/edit screen.

Yes, the problem is BC… We have plans to re-do this in v3.

**Comment by simnom** [comment]
Awesome, I'll shut up then :-)

**Comment by SahAssar** [comment]
Info for anyone that comes along: The version roadmap has changed, and since this issue mentions v3.0 (which is now 4.0) I'm posting this here https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/7

**Comment by SahAssar** [comment]
Closing as a duplicate of #4042 of since they are two sides of the same coin :)
