### ISSUE TITLE
Upload permissions not working for non-root users

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4241]
In this case, an upload with a standard `chief-editor` role
![access control derpy](https://cloud.githubusercontent.com/assets/1427081/10343554/1ab2693c-6d16-11e5-9cd9-5c84f96d9363.png)

As reported by @boorj

**Comment by GawainLynch** [comment]
""not enough rights to SEE the folder"
![](http://i.imgur.com/AhroQmM.png)

**Comment by GawainLynch** [comment]
@rarila something weird is going on here… the "Upload Image" button is getting bad data
```html
<input    accept=".gif,.jpg,.jpeg,.png"
    data-upload="{ Removed for GitHub }"
    data-url="http://bolt.gringalet.org/bolt/extend?handler="
    id="fileupload-image"
    name="files[]"
    type="file">
```

Notice that the `data-url` is being set to `extend/` which is wrong… it should be `upload/` and [in Twig](https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fields/_image.twig#L34) it's being told the right thing but by the time it renders…

**Comment by Boorj** [comment]
Zomby issue :dead:  came back #4789, it doesn't work again i suppose..
