### ISSUE TITLE
Use of *_INSERT events

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4246]
Hey,

currently you can get the information if a record was created or updates from the `isCreated()` method on the event class.

There are already this `PRE_INSERT` and `POST_INSERT` events defined but they are [not triggered yet.](https://github.com/bolt/bolt/blob/master/src/Events/StorageEvents.php#L19)

I think it does make sense to trigger either the `*_SAVE` or `*_INSERT` events in the repository. 
But that means the `isCreated()` function is a little bit useless on the event. I can create a PR tomorrow to trigger the `*_INSERT` events.

The question is, do we need the `isCreated()` function or should I delete it? Maybe we can keep it and remove it in the 2.3 release?

**Comment by GawainLynch** [comment]
OK… Those events were introduced in #3578 so still need to be "wired up" and I'll defer to @rossriley on the plan there… but yeah, thank you for pointing that out at the very least :grin: 

As for `isCreated()` we can only deprecate it… It would break backward compatibility. I have a couple of sites that run it, and it would break a lot of stuff if we ripped it out.

That said, yeah… the new storage layer and the events that @rossriley has added are definitely the way to go moving forward.

**Comment by PhillippOhlandt** [comment]
Ok then I don't touch that. But I'll create a PR in the next days to add some new events to Bolt.

**Comment by GawainLynch** [comment]
Oh… you mean like in this discussion that is still ongoing… #1914

**Comment by PhillippOhlandt** [comment]
Uh that's an old discussion I didn't know about. But the changes mentioned there wasn't made yet. 

The first two events I would add were `USER_LOGIN` and `USER_LOGOUT`.

**Comment by GawainLynch** [comment]
> Uh that's an old discussion I didn't know about. But the changes mentioned there wasn't made yet.

Yeah, it was one of the closing things we did for the end of BoltCamp last year.

> The first two events I would add were USER_LOGIN and USER_LOGOUT.

Sounds good… what data are you thinking of including in the event?

**Comment by PhillippOhlandt** [comment]
Just the user data. Maybe useful for logging. 
Or like the content events with `PRE_` and `POST_` prefixes so an extension can stop the login process or something else.

**Comment by GawainLynch** [comment]
PRE and POST might be a bit tricky on that one… and as things stand I am not too keen on extensions changing login behaviour as it opens the door to security holes… but let's see what you come up with and we can discuss further.

A good approach might be to get a branch working and then link the compare in here so we can review prior to PR… Not a requirement, just potentially useful.

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by GawainLynch** [comment]
Moving this to the new [forums](https://discuss.bolt.cm/d/9-dispatchers-listeners)
