### ISSUE TITLE
Bolt sites should have a Site Properties section

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#4251]
sitename and payoff could be added to a new Properties section. 

For all my customer sites I create a Resources content type which has a name and text area associated with it, this allows site owners to specify fields such as email address, phone number, address, twitter url etc. It would be great if we could have a properties section, which you can dynamically add fields to, that allows a site owner to specify properties. As a designer I can then use the names the site owner has given to those records to build my template.

This should be something *prettier* than a plain text field, the resources content type solution mentioned above works quite well already.

**Comment by SahAssar** [comment]
To me it seems like this is more of a resource contenttype/record situation. I don't know about other bolt users, but I try to keep the clients out of the YML files. Still, we need better handling of resource contenttypes.

**Comment by dennschu** [comment]
@tomntech I think you can resolve your usecase with the following strategy:

backend:
- create a ressource contenttype like before
- create a custom javascript gui field that acts like a repeater which stores its data as json (so you require only one db table cell)
- create and assign a custom contenttype class (gets registered with class attribute in contenttype.yml) that has a method for retrieving and dehydrating the json (maybe as array)

frontend:
- use custom json method of custom contenttype class and iterate over the data

**Comment by SahAssar** [comment]
Since this is such a broad discussion with non-specific solutions I've moved it to the new [forums](https://discuss.bolt.cm/d/11-handling-of-resource-contenttypes-sitewide-properties-continuation-of-4251) :)
