### ISSUE TITLE
Changing record status multiple times in overview clears taxonomies

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4253]
@rossriley yet to debug this, but I have a feeling this is the proxies getting us in the same way that #4209 is problematic.

![bug](https://cloud.githubusercontent.com/assets/1427081/10411488/bc0eee54-6f5f-11e5-99d5-16f73bac1871.png)

**Comment by SahAssar** [comment]
Fixed in #4418 (I think?)!

**Comment by GawainLynch** [comment]
Fixed in #4418… I know… I tested it earlier today :+1:
