### ISSUE TITLE
Link for "View (saved version) on site" re-opens the record editor

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4260]
Rendered HTML for the link:
```html
<a href="" target="_blank">
    <i class="fa fa-external-link-square"></i> View (saved version) on site
</a>
```

**Comment by rarila** [comment]
It uses ``href="{{ context.content.link }}"`` in both cases. But ``link`` isn't defined (anymore?). So how would a correct link look like?

**Comment by GawainLynch** [comment]
Ah… so this is actually my derp then! I'll reassign.

**Comment by rarila** [comment]
@rarila is :eyes: the :koala: sitting on a :deciduous_tree: eating some :leaves:

**Comment by GawainLynch** [comment]
The `link()` function from the legacy provider isn't able to access the hydrated Entity object. @rossriley has some fixes incoming.

**Comment by SahAssar** [comment]
Was just trying to test #2308 and ran into this :smile:
