### ISSUE TITLE
Bolt 2.2.13 breaks on PHP 5.3.27

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#4261]
'Something' goes wrong with installation extensions...

![screen shot 2015-10-12 at 14 08 35](https://cloud.githubusercontent.com/assets/2750653/10427534/c0ede06a-70ea-11e5-9061-73f54c398ac8.png)

**Comment by GawainLynch** [comment]
Oops… that is SimpleForms itself… I blame that damn :koala: again!

**Comment by peterboorsma** [comment]
OK. Close this issue. I'll post it at Jadwigo's thingie.

**Comment by jadwigo** [comment]
https://github.com/jadwigo/SimpleForms/issues/42
