### ISSUE TITLE
ext-gd missing when installing/updating with composer

### ISSUE THREAD

**Issue by madc** [bolt/bolt#4264]
I'm on Arch Linux having gd (`php-gd`) installed, but when trying to install/update bolt via composer, it throws the following error:

````
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bolt/thumbs 2.0.9 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - bolt/thumbs 2.0.8 requires ext-gd * -> the requested PHP extension gd is missing from your system.
[...]
    - bolt/thumbs 2.0.9 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for bolt/thumbs ~2.0 -> satisfiable by bolt/thumbs[2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].
````

Using the `--ignore-platform-reqs` allows to to perform this actions as a workaround.

**Comment by GawainLynch** [comment]
That is not a Bolt issue. That is quite literally that the GD extension is not enabled.

**Comment by GawainLynch** [comment]
Damn button presses! :grin: 

You can use this to screen it
```
$ php --info | grep -i gd
```

**Comment by madc** [comment]
Are you sure? Image processing is working perfectly (also with bolt itself) and this is the output of your command:

````
GD Support => enabled
GD headers Version => 2.1.1
GD library Version => 2.1.1
gd.jpeg_ignore_warning => 0 => 0
````
I've been trying to research this issue for quite some time now, but couldn't get get somewhere. Its really no critical issue and i'm happy to provide additional information.
This is the installed version: [php-gd 5.6.14-1](https://www.archlinux.org/packages/extra/i686/php-gd/)

Btw, impressively quick response.

**Comment by aerth** [comment]
I can't replicate this issue on arch linux. Just did a successful bolt install:

```php
composer create-project bolt/composer-install bolt --prefer-dist
```
I'm wondering if you did a composer.json install using this (which I can't get to work at the moment)

```php
composer require 'bolt/bolt ~2.2'
```

**Comment by madc** [comment]
Bolt was installed, checking out this very repo. Then later I pulled and wanted to update the vendors, which results in the dependency error posted above.

Your first install method does exactly the same, the second one has a problem with `composer/composer` as dependency.

**Comment by madc** [comment]
After thinking about, its more likely, that is is a composer issue (see [composer #4353](https://github.com/composer/composer/issues/4353)). I'll move the discussion there. Thanks for all the support.

**Comment by GawainLynch** [comment]
@madc agreed with `php-gd`… something funky going on there.

The second issue with the dependency issue is being tracked in #4265 if you want to stay abreast.

**Comment by madc** [comment]
Will be following, thanks.

Btw, my composer version:
`composer --version`: `Composer version 1.0-dev (9f6fdfd703f433bd0777fd89fb4684908a6c4f06) 2015-09-07 16:55:30`

**Comment by madc** [comment]
I updated composer and the issue seems to be solved.

**Comment by OmarFaruque** [comment]
i also have same problem when i try to install magento from git using composer. 

 Problem 1
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.
  Problem 3
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 4
    - The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.
  Problem 5
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 6
    - The requested PHP extension ext-zip * is missing from your system. Install or enable PHP's zip extension.
  Problem 7
    - Installation request for braintree/braintree_php 2.39.0 -> satisfiable by braintree/braintree_php[2.39.0].
    - braintree/braintree_php 2.39.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 8
    - Installation request for pelago/emogrifier v0.1.1 -> satisfiable by pelago/emogrifier[v0.1.1].
    - pelago/emogrifier v0.1.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.

**Comment by bobdenotter** [comment]
@OmarFaruque Two things: 

1) Your issues come from your PHP installation missing those extensions. Install or enable them. 
2) This is the *Bolt* issue tracker, so we can't help you with *Magento* stuff.

**Comment by OmarFaruque** [comment]
Thanks

**Comment by simplyniceweb** [comment]
as for me i commented it out and works like a charm.

from:
;extension=php_gd2.dll
to:
extension=php_gd2.dll
