### ISSUE TITLE
Getting contenttype from PRE_/POST_DELETE

### ISSUE THREAD

**Issue by madc** [bolt/bolt#4269]
I'm using the current master (don't worry, only to develop an extension) and from what I understand, it uses a re-factored method for the event handling. Its possible to get all the content of the deleted entity with `$event->getSubject();` but there seems to be no way of getting its contenttype. Also in [src/Storage/Repository.php](src/Storage/Repository.php#L302-L316) it looks like the contenttype is simply not given to event.

**Comment by PhillippOhlandt** [comment]
Look here for another discussion: https://github.com/bolt/bolt/issues/4248

**Comment by madc** [comment]
I saw this issue, but as far as I can tell, they are talking about the event handling, before it got re-factored.

**Comment by PhillippOhlandt** [comment]
Ah ok.

**Comment by GawainLynch** [comment]
Finalising events/event handling is still on our TODO for this development cycle and, yeah master… It's coming :grin:

**Comment by madc** [comment]
I figured. I guess, its the same for PRE/POST_HYDRATE events. Is there an issues that tracks that? I'd like to follow it, as it is another thing, i can't wait to have.

**Comment by SahAssar** [comment]
Please take note that there is also a discussion about the events open in the forums: https://discuss.bolt.cm/d/9-dispatchers-listeners-continuation-of-1914-4246

**Comment by madc** [comment]
Right, i'll move my question over there..

**Comment by SahAssar** [comment]
Just checking here.... Is this still an issue or are we just bouncing milestones? 😆

**Comment by PhillippOhlandt** [comment]
I think it is fixed, otherwise I would have seen it while updating my Pusher Realtime extension.

**Comment by SahAssar** [comment]
Well, then I'm closing, feel free to reopen if I'm wrong!
