### ISSUE TITLE
Context-sensitive excerpts and search term highlight for search results

### ISSUE THREAD

**Issue by Eiskis** [bolt/bolt#4274]
One of the most requested features from my end-users and content editors is context-sensitive preview of page content in search results, with the actual hits highlighted.

I believe in its simplest form, this could be implemented as another `excerpt` function that would build an array or concatenated string of the hits for the search term (passed as input). You'd use this on whatever content you'd display of your records on the search result page.

The actual highlighting is trivial to do with JS, but it can only use the content it has been passed or is already in the DOM. Right now that's what I'm doing, but the end result is slighly confusing since the search term might be included on the page a hundred times at the end without being visible in the excerpt I'm showing to the user now.

Now of course the search functionality uses tags and other pieces of content as well for the hits, so in practice you might have to take more things into account. We could also think of an entirely different way to implement this, for example the search result nodes including some kind of context information in addition to the relevance ranking we have now.

I might look into building an extension myself if I have the time but would love to hear some thoughts, I doubt I'm the first one working on this.

**Comment by sbonardt** [comment]
For the highlighting part.... I ran into this one as well. Look at below code. If you put the search variable containing your entered term(s) in brackets you can use it in a twig replace

'<p>{{ record.excerpt(250)|replace({(search): "<strong>" ~ search|escape ~ "</strong>" })|raw }}</p>'

ps: with thanks to @bobdenotter

**Comment by SahAssar** [comment]
Moved to the forums since this in it's current form isn't very actionable or even sure if it should be in core or in an extension. See here: https://discuss.bolt.cm/d/139-context-sensitive-excerpts-and-search-term-highlight-continuation-of-4274

**Comment by SahAssar** [comment]
Fix for this on the way in #4825 courtesy of @bobdenotter!
