### ISSUE TITLE
Git minimum version

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#4275]
I try to upgrade the simpleforms extension from 1.5 to 2.0.
I have an error:
Bolt\Composer\Action\UpdatePackage::execute recieved an error from Composer: Failed to execute git status --porcelain --untracked-files=no error: bad index file sha1 signature fatal: index file corrupt in /home/nicalala/public_html/vendor/composer/composer/src/Composer/Downloader/GitDownloader.php::109

On my shared server, the git version depends of Cpanel (git version 2.2.0).
What is the the minimum required version of git ?

**Comment by GawainLynch** [comment]
I know git 1.7.8 works fine, but it doesn't necessarily relate the the version of git. This is however still a git problem and not a Bolt one :grin: 

Have you had a chance to speak with you host directly about this? I can totally understand that it is frustrating you, it is just that shared hosting can often be "interesting" in the support you get… You have friends here, I'm just not sure what we can do to help.

**Comment by SahAssar** [comment]
Going to close this one as this is a git/composer issue, not a problem with bolt. Sorry @mgageo but I don't think there is much we can do to help with this one (if I understood gawainlynch right). :(

Hope your hosting provider can help you get it sorted :)

**Comment by mgageo** [comment]
After the commands:
rm -f .git/index
git status
git fsck --full
I can upgrade the extension

**Comment by GawainLynch** [comment]
Great news, really helpful to know :+1:
