### ISSUE TITLE
Question about extending bolt 

### ISSUE THREAD

**Issue by poznet** [bolt/bolt#4278]
I'm aware how to make  extension for  frontend etc. 

Is there any option to make  extension do backend (cms)  that will add new funcionality in admin panel? 

If there is solution for this please give me example  of  extension of this kind

**Comment by GawainLynch** [comment]
It depends on what you want to do…

If you want to add routes, that have menus… have a look at the MenuEditor extension for an example.

Adding widget panels should be making a return to the 2.x codebase in 2.3.

**Comment by SahAssar** [comment]
Well menueditor and formeditor both add backend routes with backend menu items. If you are looking to do more than that you will probably have to wait for 2.3 when we will hopefully have a more complete implementation of backend widgets. Closing this issue, and if you have more questions please feel free to open a thread in our new forums: https://discuss.bolt.cm
