### ISSUE TITLE
Removing relationships does not work

### ISSUE THREAD

**Issue by tricksel** [bolt/bolt#4284]
It looks as if #1089 has risen again. I'm using version 2.2.13 with MySQL, and these contenttypes are related:
```
works_paper:
    name: Werken op papier
    slug: works-on-paper
    singular_name: Werk op papier
    singular_slug: work-on-paper
    fields:
        title:
            type: text
            required: true
            label: Titel
            error: "Het titel-veld is een verplicht veld."
        slug:
            type: slug
            uses: [ title ]
        image:
            type: image
            extensions: [ gif, jpg, png ]
        description:
            type: textarea
            label: Omschrijving
        date:
            type: date
            label: datum
            default: "today"
        dimensions_w:
            type: float
            label: Breedte
        dimensions_h:
            type: float
            label: Hoogte
    relations:
        categories-paper:
        multiple: false
        label: Selecteer een categorie
        order: title
    show_on_dashboard: true
    default_status: publish
    record_template: works_paper_record.twig
    listing_template: works_paper_listing.twig
    listing_sort: -date
    sort: -date

categories_paper:
    name: Categoriën papier
    slug: categories-paper
    singular_name: Categorie papier
    singular_slug: category-paper
    fields:
        title:
            type: text
            required: true
            label: Titel
            error: "Het titel-veld is een verplicht veld."
    show_on_dashboard: false
    default_status: publish
    listing_template: categories_listing.twig
    listing_sort: title
    sort: title
```
From the works-on-paper content type I select one of the previously made categories-paper to be related, and save. After that, 2 situations create a problem:
1. When changing that category (related contenttype) to another, the works_paper is related to both of them. Wanted result is that the works_paper is related to the second category only.
2. When selecting "none" for a related category, the relation is not removed. When refreshing, this is also represented in the editing section of the content type.

**Comment by SahAssar** [comment]
Hmm, while I could recreate this when I exactly copy-pasted your contenttypes, I couldn't when I properly indented the relation. This is yours:
```
    relations:
        categories-paper:
        multiple: false
        label: Selecteer een categorie
        order: title
```
This is what I changed it to:
```
    relations:
        categories-paper:
            multiple: false
            label: Selecteer een categorie
            order: title
```
It still looks like a bug of sorts, but not the same as #1089. Could you confirm that it works when properly configured on your setup?

**Comment by tricksel** [comment]
Yes, that's it! Stupid me. Thanks for working it out.
The "other" problem is weird though. You want me to try/test something?

**Comment by SahAssar** [comment]
I can't recreate that issue either on 2.2.13. I'm on sqlite though, so that *might* be it. Can you recreate that problem on a fresh 2.2.13 install with the same contenttypes?

**Comment by tricksel** [comment]
I've just tested, it seems the problem is somewhere related to using MySQL. When fixing the contenttypes, all is well; when using my initial contenttypes, the problem arises again, on a free 2.2.13.

**Comment by SahAssar** [comment]
@tricksel We don't have validation on the YAML yet, so I'm not sure if this is even "fixable". When the config is incorrect it can produce some pretty wonky results in other places too, so unless the issue appears with a correct config I'm going to count this as solved. If you disagree or want further discussion, please feel free to reopen :)

**Comment by tricksel** [comment]
While YAML validation would be nice (some day...), I fully agree.

**Comment by antonio-polastri** [comment]
I have similar problem on my contenttype file

# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes

# Pages can be used for the more 'static' pages on your site. Things like
# 'about us', 'contact' or a 'disclaimer'. This content-type has a 'templateselect'
# field, which allows you to override the record_template setting for an
# individual page.
# The taxonomy for this contenttype is defined as 'chapters', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ chapters ]
    recordsperpage: 100


# Entries can be used for things like 'news' or 'blogpostings'. They have a 'teaser',
# which can be used for a short blurb on listing-pages, allowing visitors to
# click-through to the rest of the entry. It also has fields for an image and an
# optional video.
# A relation is defined to the pages contenttype. This way you can refer to a page
# from your news-item.
# This contenttype defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'sort' is set to '-datepublish', which means that newer entries will be
# shown above older entries.

#entries:
#    name: Entries
#    singular_name: Entry
#    fields:
#        title:
#            type: text
#            class: large
#            group: content
#        slug:
#            type: slug
#            uses: title
#        teaser:
#            type: html
#            height: 150px
#        body:
#            type: html
#            height: 300px
#        image:
#            type: image
#            group: media
#        video:
#            type: video
#    relations:
#        pages:
#          multiple: false
#          order: title
#          label: Select a page
#    taxonomy: [ categories, tags ]
#    record_template: entry.twig
#    listing_template: listing.twig
#    listing_records: 10
#    default_status: publish
#    sort: -datepublish
#    recordsperpage: 10


tvcontents:
    name: Tv Contents
    singular_name: tvcontent
    fields:
        title:
            type: text
            class: large
            required: true
            group: content
        images:
            type: imagelist
            extensions: [ gif, jpg, png ]
            group: content
        video:
            type: filelist
            extensions: [ mov, mp4, MOV ]
            group: content
            
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    viewless : true       
          
shopindex:
    name: Shop index items
    singular_name: Shop index item
    fields:
        hidden-title:
            type: text
            class: large
            required: true
            error: "The Title field is required, and must contain at least 2 characters"
            group: content
        images:
            type: imagelist
            extensions: [ gif, jpg, png ]
            group: content
        gender:
            type: select
            values: [ mens, womens ]  
            group: content
            
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    viewless : true          
    
collections:
    name: Collections
    singular_name: collection
    fields:
        title:
            type: text
            class: large
            group: content
        subtitle:
            type: text
            class: large
            group: content 
        cover-image:
            type: image
            group: content
        credits:
            type: html
            height: 300px
            group: content   
            
#   record_template: entry.twig
#    listing_template: listing.twig
#    listing_records: 10
    default_status: publish
    sort: -datepublish
#    recordsperpage: 10

slide:
    name: Collection Images 
    singular_name: Collection Image
    fields:
        complete name:
            type: text
            class: large
            group: content
#        products:
#            type: select
#            multiple: true
#            order: title
#            values: products/complete_name     
        images:
            type: image
#        collection:
#            type: select
#            multiple: false
#            order: title
#            values: collections/title   
           
    relations:
        
          
        collection:
            type: select
            multiple: false
            label: Select one collection
            order: id
            
        products:
            type: select
            multiple: true
            label: Select links
            order: id
     
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    viewless : true




products:
    name: Shop Links
    singular_name: Shop Links
    fields:
        complete name:
            type: text
            class: large
            group: content
        shop-link:
            type: text
            class: large
            group: content
             
 #       images:
 #           type: imagelist
           
           
#    relations:
#        slide:
#          multiple: true
#          order: title
#          label: Select image
          
     
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    viewless : true

slide:
    name: Images Collection
    singular_name: Image Collection
    fields:
        complete name:
            type: text
            class: large
            group: content
#        products:
#            type: select
#            multiple: true
#            order: title
#            values: products/complete_name     
        images:
            type: image
            
        
            
    relations:
        products:
          multiple: true
          order: title
          label: Select image
           
     
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    viewless : true



events:
    name: Events
    singular_name: event
    fields:
        title:
            type: text
            class: large
            group: content
        link_text:
            type: text
            class: large
            group: content 
        link_url:
            type: text
            class: large
            group: content 
        cover-image:
            type: image
            group: content
        details:
            type: html
            height: 300px
            group: content
#        images:
#            type: imagelist     
     
    default_status: publish
    sort: -datepublish


With a doble relations don't clean the multiple.
Could you help me?

**Comment by bobdenotter** [comment]
@antonio-polastri Which version of Bolt are you using? 

Also, if you use three backticks, the code formatting doesn't break: 
https://guides.github.com/features/mastering-markdown/

**Comment by antonio-polastri** [comment]
Hi, thanks for reply.
the version in 2.2.18
I don't think is a formatted problem, because if i change 

`relations:
        collection:
            type: select
            multiple: false
            label: Select one collection
            order: id
            
        products:
            type: select
            multiple: true
            label: Select links
            order: id`

multiple with false in products relations it works well.
Thanks

**Comment by SahAssar** [comment]
@antonio-polastri Any way you could check on 2.2.22 (the current 2.2.X version)?
