### ISSUE TITLE
[Tracker] Improving JS to support repeating fields

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4286]
Pinging @rarila and @SahAssar especially, but any help will be appreciated.

## Overview

Our frontend handlers for fields are very much anchored around initialising on page load and then retiring for a beer.  In trying to get repeating fields working I've run into the problem of needing to initialise fields subject to a context and additionally we need to start considering how we allow custom / extension fields to hook into the `Bolt.fields` object too.

## Todos 

So to get this working we need to adjust each initialiser to take a context and then we need to ensure that they can be called ad-hoc depending on events. Ideally we'd like to support all fields as member of a repeating field set. For reference, in the recent PR for repeating fields I've added a context to `Bolt.fields.init()` and ideally calling `bolt.fields.init(element);` where element is any jQuery element should re-initialise for that node only.

Easy (I think these should all work, or with minor modifications)
- [x]  Geolocation
- [x]  Select
- [ ]  Templateselect
- [x]  Text

Harder Ones
- [x]  Image
- [x]  Imagelist
- [x]  File
- [x]  Filelist
- [x]  Markdown
- [x]  Video

Not Sure
- [x] HTML

Other
- [x] Allow other fields handlers to be registered on `Bolt.fields`

~~I must admit, I've combed through the code and can't quite work out how the ckeditor ones are initialised at the moment, they seem to need a class of `ckeditor` on the textarea.~~

**Comment by SahAssar** [comment]
Closed cause #4422
