### ISSUE TITLE
Twig complains about templates not being defined

### ISSUE THREAD

**Issue by hannesl** [bolt/bolt#4290]
This is a tricky one that is hard to reproduce. I don't know when or why the problem occurs, but it happens from time to time, seemingly by random.

The problem is that sometimes the site ends up in a state where the Frontend templates are not found by Twig:

    Symfony\Component\HttpKernel\Exception\HttpException: Rendering homepage failed: Template "index.twig" is not defined.

Clearing the cache fixes it, always.

I've nailed it down somewhat:

* It only happens if you put your templates in a subdirectory of your theme.
* The reason the templates aren't found is because the `theme` configuration isn't available. `$app['config']->get('theme')` returns nothing. This means there is no `template_directory` variable available. Twig is instead handed the root theme path, which doesn't contain any templates in this case. (See `Bolt\Configuration\ResourceManager::postInitialize()`.)
* The cached configuration in `config_cache.php` does not contain the theme configuration, so the problem persists until the cache is cleared.

I've installed Bolt as a Composer project if that makes a difference.

**Comment by GawainLynch** [comment]
For the record, I have hit this one as well… although for whatever reason I haven't hit it for quite a while (potentially as I am hard wired to `master`) and was never able to find a good way to reproduce it either.

**Comment by hannesl** [comment]
Good to hear I'm not alone, or crazy. I'm on 2.2.13, forgot to mention that.

I wrote this extension to work around the problem:
https://gist.github.com/hannesl/cdad9610a47091b0c8a6

**Comment by SahAssar** [comment]
@hannesl I'm just going through old issues, have you run into this lately? If so, have you found any pattern to when it arises or any way to reliably reproduce?

Förutom det så är det trevligt att se lite svenskar här då och då ;)

**Comment by hannesl** [comment]
@SahAssar Sorry for the delay – I'm on a good old Swedish pappaledighet so I'm less active online at the moment. I haven't found any way to reproduce it reliably. I can't really say if it's still an issue for me since I've solved it with the workaround I linked to above. I do log it when it happens, but there is nothing in the recent log.

**Comment by SahAssar** [comment]
Alright, then I'm closing this for now... If anyone runs into again it feel free to reopen, and if that person also finds a way to reliably reproduce it would be even better :)
