### ISSUE TITLE
Don't append meta tags to ajax calls

### ISSUE THREAD

**Issue by madc** [bolt/bolt#4295]
When calling a page via ajax, the following lines are append:

````
<meta name="generator" content="Bolt">
<link rel="canonical" href="<url>">
````

**Comment by GawainLynch** [comment]
Is that on `master` or `release/2.2`?

**Comment by madc** [comment]
It is v2.2.8

**Comment by GawainLynch** [comment]
Awesome, thanks… we were having the problem in `master` for a while and I fixed it a few weeks back but that just scared me into thinking it went all zombie on me :grin:

**Comment by madc** [comment]
Let me know, if i can provide additional information.

**Comment by GawainLynch** [comment]
Will do… It should be an easy fix and if nobody gets in before me, I should be able to get to it in a few hours.

**Comment by bobdenotter** [comment]
> It is v2.2.8

I think this'll be gone if you update to 2.2.13.

**Comment by GawainLynch** [comment]
>> It should be an easy fix and if nobody gets in before me, I should be able to get to it in a few hours.

> I think this'll be gone if you update to 2.2.13.

See, @bobdenotter beat me by two weeks, without even lifting a finger :wink:

**Comment by madc** [comment]
Give me a minute, i'll check and close the issue.

**Comment by madc** [comment]
Are you sure it's in 2.2.13? I downloaded the latest zip, uploaded the `app`. `src` and `vendor` folders and still getting the two elements appended.

**Comment by GawainLynch** [comment]
Zero stress… I'll look into it soon. I know where/why it happens, so as my original statement it should be straightforward :grin:

**Comment by madc** [comment]
Awesome!

**Comment by GawainLynch** [comment]
#4297 should be an easy port for you.

**Comment by madc** [comment]
True. Thanks!

**Comment by gwbonline** [comment]
This issue is still present in Bolt 3.3.3. I have just implemented Fancybox and want to use a AJAX call to display some info. I have three close buttons that are generated because the mentioned lines

`<meta name="generator" content="Bolt">
<link rel="canonical" href="<url>">`

are inserted.

**Comment by bobdenotter** [comment]
How are you implementing Fancybox? For Ajaxy calls, it really shouldn't do this.

**Comment by gwbonline** [comment]
I use Fancybox3 to open a modal window to display some content from a different template file. That file has no head elements, just the content. When opening it, Fancybox shows four close buttons. One for closing the modal window. And three extra with links like site map, canonical and the Bolt meta tag.

**Comment by bobdenotter** [comment]
Code, mate. I want to see code and/or a working example. ;-)

**Comment by gwbonline** [comment]
A working example is at: beta.degeintrappers.nl/vereniging/foto-s

Click on the link half way the page (‘Dansgala Lingewaard’). This will open the modal window.

**Comment by bobdenotter** [comment]
Hmm, right.. The request _is_ done as xhr in the browser, which is correct: 

![screen shot 2017-09-12 at 15 27 17](https://user-images.githubusercontent.com/1833361/30328220-fdd1daa6-97ce-11e7-90f6-5262199dccfb.png)

But it does append the meta tags regardless: 

![screen shot 2017-09-12 at 15 27 27](https://user-images.githubusercontent.com/1833361/30328237-0a834a6e-97cf-11e7-9ce0-eff02a9a496e.png)

@GawainLynch This is something we should be catching, right?

**Comment by GawainLynch** [comment]
Yeah, we were … it was a :koala: … fix in the queue.
