### ISSUE TITLE
Bug sorting images in gallery

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#4306]
Ordering images in a gallerylist has an annoying bug. When picking up an image, the editor page is scrolling all the way down so you can't see what you are doing.

(Bolt 2.2.13 /  Chrome & Safari OSX)

**Comment by rarila** [comment]
Sounds like #3473 … ok, we have Marty McFly Day, but …

**Comment by bobdenotter** [comment]
It looks the same.. Wonder if that fix made it back into 2.2.x, though.. hmm.

**Comment by bobdenotter** [comment]
Fixed in this commit: e548a32747f8ceba15148d8169ac201951da77b1. There will be a 2.2.14 soon, with this fix.
