### ISSUE TITLE
Admin Theme?

### ISSUE THREAD

**Issue by ellioseven** [bolt/bolt#4308]
Just wondering if there was any possible way to add in a custom admin theme without modifying core?  

Even just replacing the CSS and JS files would be very helpful.

**Comment by GawainLynch** [comment]
Short answer is "no". :grin:

The longer answer is that it is something that we've deliberately stopped until now. However there is recent [discussion on the forum](https://discuss.bolt.cm/d/22-new-backend-style-in-bolt-3/3) to move in that direction for version 3.

**Comment by reybenher** [comment]
Curious to know whether we can look forward to this in v3 ^^

**Comment by SahAssar** [comment]
@reybenher: It's on the wishlist, but in what way, shape and form will be up to whoever ends up implementing this and what is "reasonable"... Keep an eye on the forum thread, pretty sure it will be discussed there as 3.0 draws nearer :)

**Comment by reybenher** [comment]
@SahAssar great to know! looking forward to 3.0! The whole question being Wordpress is being used quite extensively at work only because of it's 'flash' admin back-end (easy for clients to edit and make changes). If we could polish the admin theme for Bolt I see no worry in it taking over the market haha.

**Comment by GawainLynch** [comment]
I am not a UI/UX person, but the utter "overflow" of the WP backend is another story... We specifically cater to broad use. Or am I missing a point here?

**Comment by bobdenotter** [comment]
Hi @reybenher 

>  If we could polish the admin theme for Bolt

This is an ongoing process! Bolt 3.0 will see bigger changes, but for the upcoming 2.3 we've done some finetuning. See this screenshot for an example: 

![screenshot 2015-11-12 08 30 34](https://cloud.githubusercontent.com/assets/1833361/11112888/d8244a0e-8917-11e5-97eb-e9ac5049da49.png)

**Comment by reybenher** [comment]
Not trying to pick a fight here :) Kudos to the UI team, waiting for 3.0 to come out.

**Comment by GawainLynch** [comment]
I doubt any of us took it as picking a fight mate, all good and don't worry :grin:  

We're **really** looking forward to the 3.0 release too… there will be :beers:
