### ISSUE TITLE
Adding assets through an Extension when are rendered are previously sorted

### ISSUE THREAD

**Issue by dactivo** [bolt/bolt#4319]
After adding the extension Editable, I realize that ckeditor.js is added after startup.js, the author has added the javascript with ckeditor.js first.
Searching the code I find in "src/Extensions.php" the following line (l.834) (look at the last line):
```php
    public function processAssets($html)
    {
        foreach ($this->getAssets() as $type => $files) {

            // Use http://en.wikipedia.org/wiki/Schwartzian_transform for stable sort
            // We use create_function(), because it's faster than closure
            // decorate
            array_walk($files, create_function('&$v, $k', '$v = array($v[\'priority\'], $k, $v);'));
            // sort
            sort($files);
```
This provokes that ckeditor for any reason is put at the end, so startup.js does not know CKEDITOR variable

**Comment by SahAssar** [comment]
@dactivo Isn't this an issue with the extension, and not with bolt itself? In bolt you can set the priority of assets to ensure a proper loading order, so I don't think this belongs as an issue here. If I am wrong please tell me so and feel free to reopen! :)

**Comment by dactivo** [comment]
I know that AddAsset (the method used to add assets)  implements a priority:
```addAsset($type, $filename, $late = false, $priority = 0)````

Finally I have found the real reason, It is not working because the method the AddJavascript and AddCss in Extensions.php, has an inline condition that deletes the priority accidentally and transforms all priorities in a boolean, you can see it in the last line:
```
public function addJavascript($filename, $options = array())
    {
        // Handle pre-2.2 function parameters, namely $late and $priority
        if (!is_array($options)) {
            $args = func_get_args();

            $options = array(
                'late'     => isset($args[1]) ? isset($args[1]) : false,
                'priority' => isset($args[2]) ?isset($args[2]): 0,
```

So the sort function was OK but not here.

To demonstrate it further more if you dump the $files variable in the loop (see code in the first comment  of the issue),  you get this:
```
array:2 [▼
  "ebb081dd3fe3d1e6b08d5f11c5e01ac3" => array:4 [▼
    "filename" => "/extensions/vendor/bolt/editable/assets//ckeditor/ckeditor.js"
    "late" => true
    "priority" => true
    "attrib" => false
  ]
  "dcb1cb7e3145c3508a7ee333d2803159" => array:4 [▼
    "filename" => "/extensions/vendor/bolt/editable/assets//ckeditor/startup.js"
    "late" => true
    "priority" => true
    "attrib" => false
  ]
]
```

**Comment by GawainLynch** [comment]
Ah yes… I thought I introduced (and later fixed) that in master! Very good find, thank you!

Do you want to PR the fix @dactivo and get the credit for hard work?

**Comment by dactivo** [comment]
@GawainLynch My first PR here #4343, hope it's OK with contributing guide, :-D, thx

**Comment by GawainLynch** [comment]
Yeah, great stuff. Thank you very much!
