### ISSUE TITLE
addMenuOption produces wrong URL in userdir

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#4322]
addMenuOption produces wrong URLs if bolt was installed in userdir or subdir. Given /bolt/labels for example with bolt running in http://server/~user the following link is generated: http://server/bolt/labels, instead of http://server/~user/bolt/labels

**Comment by bobdenotter** [comment]
I'm afraid that's really hard to fix. `~userdir` is especially weird in that it sometimes is treated as a subdirectory, and sometimes it's not. 

If you add this in `extensions/vendor/bolt/labels/Extension.php`, around link 37: 

```
        dump($this->app['resources']);
```

I'm interested to see what it says on your setup. Please open the 'urls' part, and post a screenshot _with_ the browser's address bar. :-)

I'm getting the following, and the 'bolt' url is correct in my case:

![screen shot 2015-10-26 at 18 33 32](https://cloud.githubusercontent.com/assets/1833361/10762871/1755f22e-7cc8-11e5-90ca-4a264e24b9cd.png)

**Comment by SahAssar** [comment]
@rompcik Any progress on getting that dump? :)

**Comment by rompcik** [comment]
Sorry for the delay. I'm currently absent on business and do not have any access to my local development area. But I'll return overnext week. All I can say from distance: OS: Windows 7, Apache 2.4.17, PHP 5.5.30. Will test on Linux (Debian) when returned. Thx.

**Comment by SahAssar** [comment]
@rompcik No problem, was just checking up on some issues :)

**Comment by SahAssar** [comment]
I'm tagging this for closing on the 11:th unless good reason otherwise. Looking forward to getting some details on this issue though, but if you find the cause/issue after the close please feel free to reopen! :smile:

**Comment by rompcik** [comment]
URLs seem to be fine with bolt 2.13 now:

    #urls: array:13 [▼
        "root" => "/~irata/hotel/"
        "app" => "/~irata/hotel/app/"
        "extensions" => "/~irata/hotel/extensions/"
        "files" => "/~irata/hotel/files/"
        "async" => "/~irata/hotel/async/"
        "upload" => "/~irata/hotel/upload/"
        "bolt" => "/~irata/hotel/bolt/"
        "theme" => "/~irata/hotel/theme/hotel/"
        "current" => "/~irata/hotel/bolt"
        "canonicalurl" => "http://localhost/~irata/hotel/bolt"
        "currenturl" => "http://localhost/~irata/hotel/bolt"
        "hosturl" => "http://localhost"
        "rooturl" => "http://localhost/~irata/hotel/"
    ]

Can be closed. Again, sorry for the delay. Currently I'm totally out of time.

**Comment by SahAssar** [comment]
Thanks for the clarification @rompcik!
