### ISSUE TITLE
Bug on new install: Editor submits an entry

### ISSUE THREAD

**Issue by eduardr** [bolt/bolt#4323]
Hi, a bug report:

With Bolt 2.2.13, a completely new install.
When an 'editor' level user submits an entry, he gets an error page instead.
If that same user gets 'chief-editor' level permissions, there is no error page and the page gets saved all right.

So editors cannot save entries in this version. But chief-editors can. there's a permissions problem.

Error Message:

 Exception
 Invalid content status transition: -> publish 
 at articles/src/Permissions.php, lines 725-734:

                   return 'depublish';
                    }
                    break;
                case 'timed':
                case 'published':
                    return 'publish';
                default:
                    throw new \Exception("Invalid content status transition: $fromStatus -> $toStatus");
            }
        }

**Comment by SahAssar** [comment]
Hey eduardr! For the master branch this was fixed in #4233 but we still haven't handled it in 2.2. This was brought up during 2.2-dev in #3244 but wasn't fixed until 2.3-dev, so a fix for 2.2 would be good.

**Comment by GawainLynch** [comment]
I shall have a look this afternoon @SahAssar and @eduardr :grin:

**Comment by bobdenotter** [comment]
Fixed by #4326
