### ISSUE TITLE
Question about video embeds

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#4328]
You can show videocontent nicely in templates with {{ record.video.responsive }}. I often use {{ record.video.thumbnail }} to avoid slow loading pages. I'd like to replace the thumbnail with the embedded video on click somehow.
Is there a simple way to load the video after clicking on the thumbnail?

**Comment by bobdenotter** [comment]
This is something that should _really_ go on the forum. ;-) 

http://discuss.bolt.cm 

We're trying to keep the issue tracker strictly related to actual, actionable issues these days.

**Comment by peterboorsma** [comment]
Sowwy

**Comment by GawainLynch** [comment]
I know, right, @peterboorsma …
