### ISSUE TITLE
$this->addJavascript and addCss doesn't add more than one js file.

### ISSUE THREAD

**Issue by madc** [bolt/bolt#4332]
Version: current master.

I have two local  extensions installed. Both of them want to include js files into the backend like this:

```
    public function initialize()
    {
        if ($this->app['config']->getWhichEnd() == 'backend') {
            $this->addCss('assets/css/file1.css');
            
            $this->addJavascript('assets/js/file1.js', true);
            $this->addJavascript('assets/js/file2.js', true);
        }
    }
```

and

```
    public function initialize()
    {
        if ($this->app['config']->getWhichEnd() == 'backend') {
            $this->addCss('assets/css/file2.css');
            
            $this->addJavascript('assets/js/file3.js', true);
        }
    }
```

Only `file1.css` and `file2.js` get included into the backend. If i comment out `file1.js`, `file2.js` and `file1.css`, than `file3.js` and `file2.css` show up in backend.

Pretty wired! Any ideas?

**Comment by GawainLynch** [comment]
This on master or stable?

**Comment by madc** [comment]
I just edited my comment, its on master.

**Comment by GawainLynch** [comment]
I might have busted something recently… I'll look into it in the morning… basically in master (2.3) everything is moved into asset queues in `src/Asset/` and I have probably made a really derpy mistake :grin:

**Comment by madc** [comment]
I thought I went nuts! Sometimes, the js would work, sometimes it wouldn't... :D

**Comment by GawainLynch** [comment]
> I thought I went nuts!

I am not a psychologist and therefore not qualified to judge that on your behalf… :grin:

**Comment by GawainLynch** [comment]
Found the problem… not quite sure how you're hitting it… but the :koala: has come out of his :palm_tree: and broken things when I was working on the recent widget branch… I should have a fix soon.

**Comment by GawainLynch** [comment]
@madc there is a fix in #4334

Also there is few changes coming in 2.3 for `addCss()` and `addJavaScript()` that if you're using master, might be worth looking into… details in #4334 :+1:

**Comment by madc** [comment]
Looks good!! Btw, I just use the master to keep you guys busy with PRs and develop a couple of extensions... :fist:

**Comment by GawainLynch** [comment]
Yeah, it's good to have someone capable like you testing master… It is very much appreciated! :+1:
