### ISSUE TITLE
How to add an extension to Twig in Bolt.cm?

### ISSUE THREAD

**Issue by dactivo** [bolt/bolt#4335]
I would like to add an extension to Twig in Bolt.cm. 

I have found a way but I change Bolt code itself and my target is not to do that.

In concrete, I change the line 52 of TwigServiceProvider.php.

```
  $app['twig'] = $app->share(
            $app->extend(
                'twig',
                function (\Twig_Environment $twig, $app) {
                    $twig->addExtension(new TwigExtension($app, $app['twig.handlers'], false));

                    $twig->addExtension(new MYEXTENSION);

                    return $twig;
                }
            )
        );
```

How could I do this from my own Bolt.cm extension? Or from index.php, better the first option, but overall, from a file that is not overwritten when Bolt.cm updates.

**Comment by bobdenotter** [comment]
Hi, 

The documentation describes how to do this: https://docs.bolt.cm/extensions/config

If you set up the "extension skeleton", it'll have an example on how to add twig extensions. 

For questions like these, please use our forum at discuss.bolt.cm from now on. We'd like to keep the issue tracker for actual, actionable issues with the code itself. ;-)

**Comment by GawainLynch** [comment]
@dactivo for reference, see [this example](https://github.com/GawainLynch/bolt-extension-twig-extensions/blob/master/Extension.php#L26-L35)

**Comment by dactivo** [comment]
Thx a lot.
With your help, finally, I have opted for adding function to Twig from Bolt Extension:

```
$function = new \Twig_SimpleFunction('THENAME',function(){....});
$this->app['twig']->addFunction($function);
```
