### ISSUE TITLE
The "View saved version" has wrong link.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4342]
This one: 

![screenshot 2015-10-26 20 56 56](https://cloud.githubusercontent.com/assets/1833361/10740751/3261040e-7c24-11e5-89d3-41908ecf6357.png)

It links to _editing_ the record, instead of te record on the front end.

**Comment by GawainLynch** [comment]
You mean like #4260

**Comment by bobdenotter** [comment]
No, this is COMPLETELY different. 

*ahem*

Yes..
