### ISSUE TITLE
Checkbox back-end unexpected update behavior

### ISSUE THREAD

**Issue by LXLH** [bolt/bolt#4356]
I found some unexpected behavior with checkboxes in the back-end for content types.
When i edit a checkbox types in my back end, if i don't return to records list, the value of the checkbox isn't update, in other words, if i keep changing the checkbox value and saving whit the default option "save" this field its not updated in the database, until i go back the records list or select the "Save & return to overview" option, this field is updated.

I don't know if this behavior is what an user expect, if he is editing multiple times a record, whit out going back to the list of records.

Thanks for all your hard work !

**Comment by SahAssar** [comment]
@LXLH What version are you on?

**Comment by LXLH** [comment]
I'm in the  2.2.13 version

**Comment by MarienTimOnline** [comment]
I might have a related problem, or a different effect of the same thing.

I try to implement a postsave function (hook) and the behavior of a checkbox is not as expected. The value sent is 1 once checked, but becomes 0 when unchecked (still perfect), but stays 0 no matter what you check or uncheck after that... When refreshing the page it starts reacting again, but same thing as above.

My functionality (code):

    function postSaveCallback(\Bolt\Events\StorageEvent $event)	{
        $content 			= $event->getContent();
        $values 			= $content->getValues();

        file_put_contents('test.txt', date('Y-m-d H:i:s').': '.$values['notify_customer']."\n", FILE_APPEND);
    }

The results (when checking, unchecking, checking, unchecking):

2015-11-10 11:10:04: 1
2015-11-10 11:10:06: 0
2015-11-10 11:10:08: 0
2015-11-10 11:10:09: 0

**Comment by SahAssar** [comment]
Actually it seems like an unchecked checkbox is not included in the JSON sent to the server at all, not sure if that is part of the issue though... Anyway, bug confirmed.

**Comment by rarila** [comment]
@SahAssar that's how it is defined in the spec for checkboxes - so nothing wrong here

**Comment by SahAssar** [comment]
@rarila: Ah, had no idea, thanks for setting me straight ;)

**Comment by rarila** [comment]
To say it with specs words, only a checkbox with on-state is successful and only successful controls are submitted. Almost as in real life ;-)

**Comment by rarila** [comment]
But we could change it to use a hidden input instead of a checkbox as we render the checkbox ourselfs anyway and trigger it with a button. If that helps … the storage gurus could tell …

**Comment by rossriley** [comment]
Normal way to do it is to render both a hidden input with a value of 0 and then the checkbox normally after it. That way the checkbox value will override the hidden input if set, but if not it will fallback to the hidden field.

**Comment by rarila** [comment]
@rossriley Won't that break with ``name="field[]"`` ?

**Comment by MarienTimOnline** [comment]
An 'unchecked' checkbox value not being sent is fine.
But it's not getting sent when you check it again either (the ajax save way)... that's the problem ofc :).

**Comment by SahAssar** [comment]
@MarienTimOnline Ah, seems we got a bit sidetracked ;)

Anyone got an idea as to the actual source of the problem?

**Comment by rarila** [comment]
@MarienTimOnline yeah, good point :-)
