### ISSUE TITLE
Adding a select in templatefields throws DB error

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4360]
Adding a select field in a templatefield on master throws the following error when trying to edit a record that has the template selected:

    Unknown column type "select" requested. Any Doctrine type that you use has
    to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a
    list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap().
    If this error occurs during database introspection then you might have
    forgot to register all database types for a Doctrine Type. Use
    AbstractPlatform#registerDoctrineTypeMapping() or have your custom types
    implement Type#getMappedDatabaseTypes(). If the type name is empty you
    might have a problem with the cache or forgot some mapping information.

If trying to switch to the template you get the error on save instead (in ajax):

    {
        "error": {
            "type": "Doctrine\\DBAL\\DBALException",
            "message": "Unknown column type \"select\" requested. Any Doctrine
            type that you use has to be registered with
            \\Doctrine\\DBAL\\Types\\Type::addType(). You can get a list of all
            the known types with \\Doctrine\\DBAL\\Types\\Type::getTypesMap().
            If this error occurs during database introspection then you might
            have forgot to register all database types for a Doctrine Type. Use
            AbstractPlatform#registerDoctrineTypeMapping() or have your custom
            types implement Type#getMappedDatabaseTypes(). If the type name is
            empty you might have a problem with the cache or forgot some mapping
            information.",
            "file": "\/var\/www\/private\/boltMaster\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php",
            "line": 228
        }
    }

Tested on up-to-date master with SQLite.

**Comment by dadaxr** [comment]
Annoying bug because related to #4358 which is also ... you know ... annoying ^^ 
Some feedback on this @rossriley  ?

**Comment by rossriley** [comment]
Got a fix coming in for this hopefully today/tomorrow

**Comment by dadaxr** [comment]
:+1:

**Comment by SahAssar** [comment]
Has been fixed, not sure in which PR though.
