### ISSUE TITLE
Minor UI Bug on Slug Field for Firefox

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4365]
Dropdown for slug field is too short on latest Firefox.

![](http://i.imgur.com/BZloK81.png)

**Comment by GawainLynch** [comment]
@GawainLynch added the "It's Rarila's Fault" label just now

**Comment by rarila** [comment]
@rarila blames unfeasible bootstrap

**Comment by madc** [comment]
The padding on `#editcontent fieldset[data-bolt-field="slug"] .input-group-btn button` overwrites the padding-top/bottom values with 0.

**Comment by bobdenotter** [comment]
@madc Yes, that's where the problem is! :-)

@rarila Bootstrap is to blame for a lot of things, i'm not sure this is one of them. :-p 

Fix incoming.

**Comment by rarila** [comment]
Problem is - I do a educated guess here, I haven't tried it – the patch doesn't get it as the top/bottom values were set for a reason. Try it with a multiline slug!

@bobdenotter bootstrap works if you use it 100% the way it is supposed to. Problem is, it is very limited in what it is able to do and as soon as you have to leave the path 1% you are in trouble.

**Comment by bobdenotter** [comment]
@rarila riiiiiight. But the used css wasn't really correct, right? It was like this: 

```
                height: 100%;
                padding-top: 0;
                padding-bottom: 0;
                padding: 0 $padding-base-vertical;
```

And to me, declaring padding like that is asking for trouble.. Let's see if i can fix it properly. :-)

**Comment by rarila** [comment]
Have fun :smile:

It took me a few hours to get it working (on Chrome) as expected … who would think that this time Firefox spoils the party…

**Comment by bobdenotter** [comment]
Added one more small thing: 

  - Doubleclick on slug to unlock. Don't ask confirmation.

I'm happy with it now! ^_^
