### ISSUE TITLE
Users added with app/nut have their password written to DB in plaintext

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4373]
In master if you add a user with app/nut their password is written to the DB in plaintext instead of being properly hashed/encrypted.

**Comment by bobdenotter** [comment]
We should obviously change our code so that _all_ passwords get saved to the database in plain text. This will make password retrieval so much easier!

**Comment by GawainLynch** [comment]
I so should have gotten @SahAssar to send me a dump of his database when he mentioned this on IRC :stuck_out_tongue_winking_eye:

**Comment by SahAssar** [comment]
@GawainLynch I would have just written a GUI in Visual Basic to backtrace your IP and double-encrypt the database using rot26!

**Comment by GawainLynch** [comment]
I actually know of someone who (because you can) wrote a traceroute clone in VB.
