### ISSUE TITLE
5.3.x is not supported right now, while docs say it is

### ISSUE THREAD

**Issue by tricksel** [bolt/bolt#4383]
In vendor/react/promise/src/functions.php shorthand array creation is used on multiple occasions (eg. line 68:)
```
return resolve([]);
```
This is supported since PHP 5.4.0.
Also, line 144 gives a syntax error on PHP 5.3.29.

**Comment by GawainLynch** [comment]
What version of Bolt, and install method are you using?

If you're installing via git/Compser, that should pull in Guzzle 3, if you're installing via archive we include a patched version of React.

However master has dropped support for PHP 5.3.

**Comment by tricksel** [comment]
Ah, that must be it. It's a git pull of the master. It still does some checking of php version though, which -I believe- validates from 5.3.3 and up.

**Comment by GawainLynch** [comment]
Just an update, Bolt 2.2 is a long term support branch to cope with people requiring PHP 5.3. Release [announcement is here](https://bolt.cm/newsitem/bolt-2-2-0-released).

Also please note, if you are on master… it is in heavy development right now :grin:

**Comment by tricksel** [comment]
Hehe, thanks for the heads up! I'll check later on whether I'm right of saying it's the master. I'm in doubt it might be some 2.2-ish version...

**Comment by GawainLynch** [comment]
OK. This will get you going:
```
git checkout release/2.2`
composer update
```

The version check in master is in `index.php`
```php
if (version_compare(PHP_VERSION, '5.4.16', '<')) {
    require dirname(__FILE__) . '/app/legacy.php';
    return false;
}
```

**Comment by tricksel** [comment]
Thanks! 👍🏻

**Comment by bobdenotter** [comment]
Closing this one, as it seems to be resolved :-)
