### ISSUE TITLE
Css not added in extension

### ISSUE THREAD

**Issue by kur1977** [bolt/bolt#4397]
I try to add css file in the extension.
into the function initialize() I added `$this->addCss('assets/select2.sortable.css', 1);`

dump($this->getAssets())  dumps an object - there is an added css in it.
But in html code - there is no this css file!
What I doing wrong?

**Comment by GawainLynch** [comment]
Are you on 2.2.x or master?

**Comment by kur1977** [comment]
bolt-2.2.13

**Comment by GawainLynch** [comment]
OK, what you probably have it a wrong file name or path. When the CSS/JS files are injected the function looks for `'assets/select2.sortable.css'` first in the extension's directory, then in the theme directory and if it doesn't find it drops it from the array… This has bitten me a few times :grin:

**Comment by kur1977** [comment]
the assets/select2.sortable.css is present in the extension directory

**Comment by kur1977** [comment]
I don't understand, how it will insert css or javascript in html, if in \app\view\twig\_base\_page.twig
there is no any code about it.

**Comment by GawainLynch** [comment]
> I don't understand, how it will insert css or javascript in html

The insertion part is done [here](https://github.com/bolt/bolt/blob/release/2.2/src/Extensions.php#L738-L809).

The matching I was referring to [is here](https://github.com/bolt/bolt/blob/release/2.2/src/BaseExtension.php#L496-L560)

**Comment by kur1977** [comment]
function processSnippetQueue  is not called at all.
I try to add css in the admin section, it it matters

**Comment by kur1977** [comment]
And processSnippetQueue - is not that function. I not adding a snippet.

**Comment by kur1977** [comment]
I added '{% for link in app.extensions.assets.css -%}
		<link rel="stylesheet" href="{{ link.filename }}" >
	{% endfor %}' into \app\view\twig_base_page.twig ant it works for me. But there is nothing about that in the documentation.

**Comment by bobdenotter** [comment]
You should not need to modify _any_ backend templates. Changes you make there will get overwritten during an upgrade. 

It really, really should work out of the box. See here for a simple example how i've done it: https://github.com/bobdenotter/gridviewfield/blob/master/Extension.php#L38

If it doesn't work for you, can you post the extension code?

**Comment by kur1977** [comment]
Thank You wery wery much!!! I'll look in it.

**Comment by kur1977** [comment]
I trying to get the Sortable Select
by Ross Riley extension to work. I installed the stable version. Looks like it's not compatible with current bolt release. Will try to modify it with help of you https://github.com/bobdenotter/gridviewfield/blob/master/Extension.php

Thank you again )))

**Comment by kur1977** [comment]
I investigate that the key is to use $this->app['htmlsnippets'] = true; in __construct
and there is not enough to write $this->addCss('assets/select2.sortable.css'); in initialize()

All $this->addCss and $this->addJavascript  must be in function.
Ant this function must be passed to the $this->app->before(array($this, 'addAssets'));

Nothing about that in the documentation https://docs.bolt.cm/extensions/essentials#add-css-or-javascript-file

**Comment by bobdenotter** [comment]
Yes, you should add `$this->app['htmlsnippets'] = true`, to get the html snippets to be processed. It's in the documentation here: https://docs.bolt.cm/internals/bolt-internals#app8216htmlsnippets8217

**Comment by kur1977** [comment]
Thanks. Closing this issue
