### ISSUE TITLE
question about order filter

### ISSUE THREAD

**Issue by kur1977** [bolt/bolt#4398]
I have entries with *date_start* field.

How can I get the entries in **setcontent** tag that are the nearest by NOW?

**Comment by bobdenotter** [comment]
This is really a question that should be posted on the forum: http://discuss.bolt.cm
If you post it there we can help you out with code snippets and stuff. 

We're trying to keep the github issues strictly for bugs and actionable issues with the code.

**Comment by kur1977** [comment]
Oh. sorry. Will pot it there.

**Comment by bobdenotter** [comment]
No worries, see you there. ;-)
