### ISSUE TITLE
base-2016 improvements

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4424]
(this is partially to remind myself and partially to have a place for others to comment..)

Pointers:

* use theme.yml instead of config.yml
* smaller headings
* more images
* areas for widgets
* add more than one template specific fields template to the theme for testing/showing off.

From me personally:

* Update grid css

**Comment by rarila** [comment]
Excuse my ignorance, I still don't not know about templatefields and how they are used… would it be possible to add another set like ``extrafields.twig`` in a reasonable way so that we have a testbed for switching those in the backend?

**Comment by SahAssar** [comment]
rarila: absolutely, added to the list.

**Comment by bobdenotter** [comment]
Let's leave this one open for now.. We'll need a place to document the ongoing fine-tuning of the theme, and this is as good a place as any. :-)

**Comment by SahAssar** [comment]
Alright, so AFAIK remaining the points are:

 - [ ] Do checks for widgets and adapt certain parts of the theme to it (now they just kinda plop into the spots if they exist)
 - [ ] Get feedback from @bobdenotter on general structure and styling details and adjust accordingly
 - [ ] Do ‎WCAG checks to make sure that the theme follows all best practices for accessibility (add ARIA attributes?)

**Comment by SahAssar** [comment]
Closing since this is outdated/irrelevant because of [the dev meeting 2016-02-02.](https://github.com/bolt/bolt/wiki/dev-meeting-2016-02-02)
