### ISSUE TITLE
Is it possible to set taxonomies required field?

### ISSUE THREAD

**Issue by mamedov** [bolt/bolt#4430]
Hello,

For example, if I have taxonomies for my content type Article, I need to validate that there always at least one taxonomy selected.

Is it possible?

**Comment by Boorj** [comment]
i would even suggest to make a field "taxonomy/tag" or something that could be reordered and moved to another tab (not taxonomy)

**Comment by bobdenotter** [comment]
Hi @mamedov 

No, this is currently not possible. For questions like this, please use our forum ar discuss.bolt.cm, as we're trying to keep the Issue Tracker for actual bugs and actionable issues.

**Comment by mamedov** [comment]
ok, thanks!
