### ISSUE TITLE
Web Profiler Bundle template location

### ISSUE THREAD

**Issue by emarref** [bolt/bolt#4431]
When Symfony is installed along side Bolt, the location of the web profiler bundle changes. [Symfony uses Composer's `replace` functionality](https://github.com/symfony/symfony/blob/2.8/composer.json#L77), which moves the web profiler bundle to `vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle`.

During the Bolt application's initialisation phase, Bolt attempts to load the web profiler bundle's templates into the twig engine, but in doing so, assumes they are always in the same place; `vendor/symfony/web-profiler-bundle/Symfony/Bundle/WebProfilerBundle/Resources/views`.

This causes Bolt to crash with a `Twig_Error_Loader` exception and the message:

> The "/var/www//vendor/symfony/web-profiler-bundle/Symfony/Bundle/WebProfilerBundle/Resources/views" directory does not exist.

**Comment by emarref** [comment]
Fix proposed in #4432.

**Comment by SahAssar** [comment]
Fixed in #4432!
