### ISSUE TITLE
DumpAutoload shuts the system

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4433]
`Bolt\Composer\Action\DumpAutoload::execute`  tries to reach  `<root>/app/extensions/vendor/composer`  directory (and some subdirs) and crashes the system if it's not existing. I can see that there's a critical level warning, but on remote server, when debug is off - it takes time to realize, what's the problem.

**Comment by bobdenotter** [comment]
We've fixed a lot of things related to this in the last few weeks. I'm going to assume this has been fixed in the meantime. 

Feel free to re-open this issue, if the problem persists after updating Bolt.
