### ISSUE TITLE
Bottleneck in `StorageEventListener`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4456]
I've noticed that on current master, the `StorageEventListener` takes a disproportionate amount of time. What happens in there, and can we fix it? See screenshot: 

![screenshot 2015-11-15 14 52 41](https://cloud.githubusercontent.com/assets/1833361/11169030/cd499a1a-8ba8-11e5-91d6-fd8e118e747c.png)

**Comment by GawainLynch** [comment]
I am guessing the short answer is stuff that came out of `Bolt\Storage`.

In `StorageEventListener::onKernelRequest()` comment out and re-test on:
* `$this->schemaCheck($event);`
* `$this->em->publishTimedRecords($contenttype);`
* `$this->em->depublishExpiredRecords($contenttype);`

**Comment by bobdenotter** [comment]
Thanks for the pointer. It's in here: 

> $this->schemaCheck($event);

It seems that after the refactor the Database checks are run every time, and no longer "occasionally", like they did in 2.2
