### ISSUE TITLE
Change lock symbol on slugs to better reflect editability 

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4470]

**Comment by rarila** [comment]
If I don't miss something, that is not a bug, but a user (UIX) error ;-)
"Lock" means that it doesn't reflect changes in the title field (or whatever it is defined in ``uses``).

Probably that should be renamed to
```
     Copy
"[X] Connect to <Title+Subtitle>
     Edit
```
with ``fa-link`` and ``fa-unlink`` as icon.

Alternatives: 
- "Linked to …"
- "Generated by …"
- "Build with by …"

Native speakers can certainly come up with better alternatives.

**Comment by GawainLynch** [comment]
Yeah, and I don't think it's the first time I have made this mistake myself… But yeah, I think "linked" works better. The lock says to me that I can't edit it.

**Comment by bobdenotter** [comment]
I think the "lock" should be interpreted as "doesn't reflect changes automatically". Unlocked means it does. 
I think i'm the one who made this originally, but i'm sure it's a fairly common pattern. it's just "locked" against unintentional changes. 

Personally, i'd think "link" might be more confusing to average users. It's _always_ linked to the same field, it's just not always _updated_ from that field.

**Comment by GawainLynch** [comment]
Sure… but the current behaviour doesn't stop you changing it when locked… I keep confusing that.

**Comment by rarila** [comment]
> it's just "locked" against unintentional changes.

can't test right no, but isn't it just so that you **can** change it if it is locked?

**Comment by bobdenotter** [comment]
How can you change it?

**Comment by GawainLynch** [comment]
Click the pencil button, fill in new data, click save.

**Comment by Boorj** [comment]
i think you have enough data even to print with small grey font : "this field is linked to *title*" and if it's unlinked = it could be "is unlinked from title". It even increase understanding for casual users (for ex. - my customers), who doesn't understand the logic of linking slug to a field.

**Comment by jadwigo** [comment]
I would offer the alternative: 
automaticcally synchronized with title
edit manually (as action on a button)
locked (meaning slug has been automatically or manually set, but the linked field has changed since then)

**Comment by rarila** [comment]
@jadwigo Hmm, automatically synced as default wouldn't work.

Technically the slug is just a string in the db. The state (syncing or not) is not saved in any way, it is just something that persists in that record editing session. So what we have now is just some comfort setting, it could also be a button "generate" on the input that generates it from the linked fields by command.
