### ISSUE TITLE
Subfolders in "upload" field (in contenttypes.yml)

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4471]
Suggestion: make available to set complex folders for upload fieldtype. Like "articles/avatars" which leads to /web/files/articles/avatars.
At the moment this code (`createDir`) will crush:
https://github.com/bolt/bolt/blob/master/src/Storage/ContentRequest/Edit.php#L191

**Comment by Boorj** [comment]
createDir just throws an uncatched exception if can't reach folder. In my case there was no `files` folder, so it just died with an error.

**Comment by SahAssar** [comment]
Personally this feels like a (small, but still) part of #574, which was "moved" to the forums (though there hasn't been much activity there).

We need better media/file management in general, but doing it piecemeal is probably not a good idea. We need an overarching plan for this and making the current implementation more complicated until we have one will probably just going to complicate BC matters when we actually try to implement a proper solution.

Anyway, that is my two cents.

**Comment by Boorj** [comment]
My version was just to wrap createDir into static Lib function, that supports recursive subdirs. And this solution can wait until team will make a bigger solution. Also this piece of code seems harmless to me and it doesn't have to be supported elsewhere, so it's local.

**Comment by SahAssar** [comment]
Just tested on a 3.1.X install, and this is now working, so I'm closing :)
