### ISSUE TITLE
Allow default option for type: select

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4481]
Documented way to set default option in *select* field for new record is `default : foo`.
Not sure this code is using `default`
https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fields/_select.twig#L43
```twig
{% for id, value in values %}
    {% set is_array = (value is iterable and (value | length) > 1) %}
    {% set options = options|merge([{
        value:     id,
        text:      is_array ? value[0:]|join(' / ') : value,
        selected:  id in selection or (not onlyids and (is_array ? value[0] : value) in selection),
    }]) %}
{% endfor %}
```

**Comment by SahAssar** [comment]
Where in the docs does it say that `default` works with select fields? I can't find it. I agree that it should work, but I'm trying to figure out if this is a bug or an enhancement.

**Comment by Boorj** [comment]
It's said nowhere, i suppose. i haven't found. But i thought `default` is a common way to set default. If it's not, it should be done.

**Comment by SahAssar** [comment]
Yep, agreed. I changed the title a bit to make it more obvious what it's about.

**Comment by Boorj** [comment]
:leaves: for :koala:

**Comment by bobdenotter** [comment]
This is part of the larger issue, here: #4532

**Comment by Boorj** [comment]
I don't know, what am i doing wrong, but this https://github.com/rossriley/bolt/commit/66c18428982ca2e0b388493cc76d7167c7e62e11#diff-b60d5990f13034e72f21ef00bce39668R119
doesn't work for me.

How do i suppose to set default value for a select field?
