### ISSUE TITLE
Form data persistence in browser localstorage

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4482]
It could be a very nice ehchancement: save all filled fields in browser's local storage.
Sometimes i press "save" or "create new record" or something - and it drops down with an error or other problem and data is lost.
For example, github saves the data and restores your comment if you refresh your page with comment (checked now, working).
It could also be useful for some non-bolt problems - like browser crash.

**Comment by SahAssar** [comment]
This feels like one of those that will either get done during a major refresh of the backend (where it would be on the wishlist anyway) or by a very dedicated dev who needs it. Either way, it probably shouldn't be on the priority list right now, so I'm going to close this.
