### ISSUE TITLE
Database update seems to get stuck for extensions

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4483]
When (for example) the SEO extension is installed, and you've added the field to the contenttype: 

```
        seo:
            type: seo
            group: SEO Options
```

It seems to get stuck when doing the update: 

![screen shot 2015-11-17 at 13 55 59](https://cloud.githubusercontent.com/assets/1833361/11211904/f9184926-8d32-11e5-9530-cb8b4df82532.png)

![screen shot 2015-11-17 at 13 52 26](https://cloud.githubusercontent.com/assets/1833361/11211906/fb4477f6-8d32-11e5-97ac-cbaff0475dde.png)

**Comment by bobdenotter** [comment]
If i change the field definition in https://github.com/bobdenotter/seo/blob/master/Seo.php#L25

from: 

```
    public function getStorageOptions()
    {
        return array('default' => '');
    }
```

to:

```
    public function getStorageOptions()
    {
        return array('default' => null);
    }
```

So, is this a quirk in our DB-checks? Or should extension developers just use `null` ?

**Comment by GawainLynch** [comment]
What platform and field type?

**Comment by GawainLynch** [comment]
Also if you turn on debug logging, it will output the SQL it wants to use… generally speaking the problem is… well… DBAL :grimacing:

**Comment by GawainLynch** [comment]
Seems to be a bug (?) with MySQL… I have tried with all three platforms and only hit it with MySQL
