### ISSUE TITLE
Remove bug-link to Stackoverflow

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#4486]
I saw someone else's error on Slack (below)
<img width="512" alt="screen_shot_2015-11-17_at_14 33 57_1024" src="https://cloud.githubusercontent.com/assets/3974120/11215020/7438de8e-8d44-11e5-8270-43e68aace8d1.png">
and noticed the link to Stackoverflow . 
Wasn't Stackoverflow going to be ditched for feedback? - then this link should be changed as well.

**Comment by bobdenotter** [comment]
Old cook! ;-)

https://github.com/bolt/bolt/blob/master/src/Exception/LowlevelException.php#L40-L44
