### ISSUE TITLE
File upload chmod on non-cgi shared hosts (2.2.13)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#4511]
When uploading files via the Bolt dashboard on a shared host (apache module), the files are owned by www-user. It is then very difficult to access, modify or chmod the files via FTP.

**Comment by GDmac** [comment]
The same goes for app/cache (cannot even delete cache files via plesk/directadmin)

**Comment by GawainLynch** [comment]
Um... That's kind of how an operating system works.

You can set the directories to 777, but the process owner on file creation will own them, and unless the sticky bit is set the group will be the owners primary group. Not a Bolt issue.

**Comment by bobdenotter** [comment]
@gdmac You can USD my chmodinator extension for that.
