### ISSUE TITLE
Strange working addJavascript

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4512]
Is it a bug? 
In extension i use addAssets function.

This combination 
![2015-11-22 18-33-31](https://cloud.githubusercontent.com/assets/2145313/11323794/dd040900-9147-11e5-957d-277c68572b86.png)
gives me
![2015-11-22 18-34-58](https://cloud.githubusercontent.com/assets/2145313/11323800/f02d275a-9147-11e5-9f2f-ecda495b0872.png) (in html sourcecode)

![2015-11-22 18-33-42](https://cloud.githubusercontent.com/assets/2145313/11323801/f8529e4c-9147-11e5-9d8e-6bb83eaadb68.png)
↓↓↓
![2015-11-22 18-34-33](https://cloud.githubusercontent.com/assets/2145313/11323802/fb87c448-9147-11e5-978f-e7009ba0e7c1.png)

![2015-11-22 18-34-03](https://cloud.githubusercontent.com/assets/2145313/11323804/0253c83a-9148-11e5-91cd-e4fa6d243a0c.png)
this one, again, gives me
![2015-11-22 18-34-33](https://cloud.githubusercontent.com/assets/2145313/11323806/095c99e0-9148-11e5-94c7-4057f3987f08.png)

Is it ok that addJavascript adds only one last existing file?
bolt - v2.3.

**Comment by GawainLynch** [comment]
Works for me:
![gridview](https://cloud.githubusercontent.com/assets/1427081/11326527/ea4a3c38-91bf-11e5-98d2-e580c4dea4bf.png)

**Comment by Boorj** [comment]
will try to reproduce that.

**Comment by SahAssar** [comment]
Yeah, also working here... @Boorj this is on an up to date master, correct?

**Comment by Boorj** [comment]
yes.

**Comment by Boorj** [comment]
tested again on the project. again - it shows only the last javascript.

here's the whole code snippet
```php
    public function __construct(Application $app)
    {
        parent::__construct($app);
        $this->app['config']->getFields()->addField(new GridField());
        $app['storage.typemap'] = array_merge( $app['storage.typemap'], ['grid' =>'Bolt\Extension\BobdenOtter\GridField\GridField'] );

        if ($this->app['config']->getWhichEnd()=='backend') {
            $this->app['htmlsnippets'] = true;
            $this->app['twig.loader.filesystem']->prependPath(__DIR__."/twig");
        }

    }

    public function initialize() {
        $this->app->before(array($this, 'addAssets'));
    }

    public function getName()
    {
        return "Gridfield";
    }

    public function addAssets(Request $request)
    {
        if ($this->app['config']->getWhichEnd()=='backend') {
            $request->attributes->set('allow_snippets', true);

            $this->addCss('assets/handsontable.full.min.css');

            $this->addJavascript('assets/start.js');
            $this->addJavascript('assets/handsontable.full.min.js');
//            $html = '<script src="/extensions/local/BobdenOtter/GridField/assets/handsontable.full.min.js"></script>';
//            $this->app['asset.queue.snippet']->add(Target::AFTER_BODY_JS, $html);
//            $html = '<script src="/extensions/local/BobdenOtter/GridField/assets/start.js"></script>';
//            $this->app['asset.queue.snippet']->add(Target::AFTER_BODY_JS, $html);
        }

        $this->app['twig.loader.filesystem']->prependPath(__DIR__."/twig");

    }
```

**Comment by Boorj** [comment]
My solution was to use that commented code. Adding with `$this->app['asset.queue.snippet']->add(...)` renders both lines.

**Comment by SahAssar** [comment]
Huh, trying with that exact code, and it still works for me. Anyone got a plausible suspect for this?

**Comment by Boorj** [comment]
checked - my & my composer missed that commit https://github.com/bolt/bolt/commit/62f9b1030ef31afc630d13c43ff5ea3991a00377 so `$cacheHash = $this->app['asset.file.hash']($fileName);` gave null.

**Comment by Boorj** [comment]
each time key was `""` so `Queue->javascript` was like:  
```php
array(''=>new JavaScript(…));
```

**Comment by SahAssar** [comment]
Alright, closing since fixed :)

**Comment by CarsonF** [comment]
Derp
