### ISSUE TITLE
Reduce SQLite base size after logs clear

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4513]
Would be lovely to automatically execute `VACUUM;` sqlite command (after clearing logs - especially).
It could reduce database size at more than 100 times.
[→ Vacuum docs](https://sqlite.org/lang_vacuum.html)

**Comment by CarsonF** [comment]
I was going to say an event listener for nut, but this can also be called from UI. Maybe we need some events around this functionality?

**Comment by GawainLynch** [comment]
We support SQLite, MySQL and PostgreSQL... 

Personally speaking, I don't think it is Bolt's job to do extended database management. For newbies it might be nice, but for others they would potentially be unhappy.

**Comment by Boorj** [comment]
You would be lovely to make an item "optimize database" in menu. As i can see - bolt is also meant to be for newbies and people who doesn't want to hire code guys.

**Comment by GawainLynch** [comment]
Maybe if someone wanted to make an extension that uses [Adminer](https://www.adminer.org/) or the like, but I just really don't see it as the job of Bolt core… IMO.

Don't get me wrong, these things are nice to have, but if we spread ourselves too thin, we take an awesome product with a reasonable set of features and make it a crap product with lots of features (many that are hardly ever used).

**Comment by Boorj** [comment]
i agree it's good to leave it as dry as possible, but this feature is really nice for those people who bought 100mb shared hosting, and it' getting filled with logs) but it's only my humble opinion, i don't insist.

**Comment by GawainLynch** [comment]
You could write the extension for us all :wink:

**Comment by Boorj** [comment]
but newbies won't have it, since the're newbies

**Comment by GawainLynch** [comment]
If they can't install an extension, they shouldn't be doing database maintenance… sorry.

**Comment by CarsonF** [comment]
To be clear, all I was arguing for was making it extendable in core. That way we don't have to maintain every little thing in core.

@Boorj you could disable logging completely as well.

**Comment by GawainLynch** [comment]
> I was arguing for was making it extendable in core

Not against that specifically… what are we missing to enable that now?

**Comment by Boorj** [comment]
I can do `vacuum` by myself, i thought it's would be just friendly and full of care for dear newbies and amateur users. You can close that if you want)

**Comment by KerimG** [comment]
I actually agree with @Boorj . Most newbies will not even realize what's eating up their storage space and will end up claiming that SQLite, or even worse Bolt itself, is bloated or whatever.

**Comment by SahAssar** [comment]
So what we are looking for is to have the events to enable extension hooks for better DB management, right? Just trying to nail down what we could do about this.

**Comment by GawainLynch** [comment]
@SahAssar I think there are differing ideas here.

Certainly an extension that listens for an event would be the best way to go… and Doctrine already provides an [event manager](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html). Of course there is a long running discussion in the [forums](https://discuss.bolt.cm/d/9-dispatchers-listeners-continuation-of-1914-4246) on what additional events to dispatch in core that is welcome to be added to post the release of the current master branch.

IMO, there is too much in the way of things that can go wrong while trying to cover 3 or more platforms in a core product feature… I am not saying I couldn't have my mind changed on that point, but it would want to be a very very good set of reasons. :grin:

**Comment by SahAssar** [comment]
@GawainLynch Sure, @Boorj and @KerimG (and probably many others) want it in core, but the most agreeable solution seems to be the extension route. Moving this to the [forum](https://discuss.bolt.cm/d/9-dispatchers-listeners-continuation-of-1914-4246) thread, if actually having it in core turns out to be a good idea feel free to reopen :)

**Comment by GawainLynch** [comment]
Just for a small experiment on this, I created a `app/database/bolt.db` SQLite file with 10,000 content records, 50,000 taxonomies and associated log entries and that was a 30 MiB file… which is still smaller than my PostgreSQL testing database with 5 records in it.

If you are hitting the point where SQLite databases are getting large enough to worry, you have bigger problems than will be solved by Bolt doing a vacuum.

**Comment by rarila** [comment]
> people who bought 100mb shared hosting, and it's getting filled with logs) 

@Boorj  although I somehow like the idea to have something like that out if the box, those people probably still have a problem:

>This means that when VACUUMing a database, as much as twice the size of the original database file is required in free disk space.

**Comment by Boorj** [comment]
Maybe we can just wrap that to some conditions (if it's sqlite, if system has an access) and launch vacuum when cache is cleared?
