### ISSUE TITLE
Using 'allowtwig: true' in a textarea field - {% include 'template.twig' %} not working

### ISSUE THREAD

**Issue by errogaht** [bolt/bolt#4514]
Just want to include sub template in content body field

**Comment by bobdenotter** [comment]
Yeah, no. Don't do that. :-)

We've made two separate "sandboxes" in twig, to allow parsing twig inside content (like in body fields). However, this second one uses a subset of the entire scope, for security reasons. As such it has no `app`, and you can't do `include` or `extends`, for example.

**Comment by SahAssar** [comment]
@errogaht I assume you know this, but for anyone else coming across this, I'd say that this seems like a usecase for a `templateselect` field.
