### ISSUE TITLE
unexpected behaviour of content type listing in frontpage controller

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4518]
The homepage / frontpage controller is doing something I don't expect.

When I set the homepage to a content type to create a simple blog and the homepage template to a standard `listing.twig` the `listing_records` value in the main `config.yml` and the per content type setting is ignored.

So in a site with the following config variables the frontpage will show _all_ entries and no pager, where I was expecting only 3 records and a pager.

homepage: entries
homepage_template: listing.twig
listing_records: 3

**Comment by GawainLynch** [comment]
What version(s) is this happening on?

**Comment by jadwigo** [comment]
the current git master as of this morning

**Comment by GawainLynch** [comment]
Fixed in #4617
