### ISSUE TITLE
Ability to set default map position for geolocation

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4526]
It would be lovely to have the ability to set default **zoom**, **latitude** and **longitude** for geolocation field type.
Now it's hardcoded to.. (is it Bopp's house? i think i can see him there)
https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fields/_geolocation.twig#L58-L59
Some of my clients live not in Europe and sometimes there's no address yet (real estate agency), so it takes too long to scroll. 
I know there are other way to do that, but for routine work it will save time. I suppose there are some people who will agree.

**Comment by SahAssar** [comment]
Closing this as it isn't a bug and has been open without activity for over a year. Feel free to reopen when there is a PR/solution and it needs tracking! :)
