### ISSUE TITLE
Geolocation field search input problem

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4527]
When i'm trying to find something with search input - i need to type something in and press enter. When i do that, Bolt just saves my record.
I told about that issue (with saving by enter problem), now it happens again)
WAIDW?

**Comment by SahAssar** [comment]
Hm, It works without enter for me, this on current master, right? Any errors in the console?

**Comment by rarila** [comment]
@Boorj I slowly get the feeling that there's something wrong wuth your installation

**Comment by Boorj** [comment]
Inspected more deep, problem was that `mts1.googleapis.com` was silently blocked, while `maps.googleapis.com` was allowed in blocker and seemed to be ok. So map worked, but binding to key didn't shot. Close this, please, i suppose that's not a common case.
