### ISSUE TITLE
New "mini footer" overlaps the popovers in the sidebar. Doesn't look very nice. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4528]
See: 

![screen shot 2015-11-25 at 09 17 59](https://cloud.githubusercontent.com/assets/1833361/11391788/7a2cf62e-9355-11e5-906c-25134bc667b3.png)

**Comment by GawainLynch** [comment]
Sorry mate… totally my fault :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
Heh, why would that be? I'm pretty sure I did this myself. :-)

**Comment by GawainLynch** [comment]
Hehe… no the emoticon should give it away… 

But I did pull in Symfony 2.8 so there is an obtuse reason that I might have had something to do with it.

**Comment by bobdenotter** [comment]
And another one: 

![screen shot 2015-11-25 at 09 30 16](https://cloud.githubusercontent.com/assets/1833361/11392015/29f2e2ac-9357-11e5-9267-b6772957be34.png)
