### ISSUE TITLE
Leaving fields "empty" tends to throw errors

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4533]
For example, when adding a "new page" on an out-of-the-box setup, and leaving the "title" empty: 

![screen shot 2015-11-25 at 17 30 23](https://cloud.githubusercontent.com/assets/1833361/11402908/61e14a26-939a-11e5-9176-a1c4dcae9645.png)

Altenatively, leaving the "template" select field empty: 

![screen shot 2015-11-25 at 17 30 43](https://cloud.githubusercontent.com/assets/1833361/11402903/5c4431aa-939a-11e5-8e6d-3dc7e4424616.png)

**Comment by GawainLynch** [comment]
The second one is potentially OK to allow nulls on.

The first one is a bit harder to solve properly, but I have ideas… just helping @CarsonF to get the FS stuff in first.

**Comment by rossriley** [comment]
For reference, the current behaviour on 2.2 is that the page saves ok with the empty title, but the slug is auto-generated to a few random characters.

I guess we want to continue this approach?

**Comment by GawainLynch** [comment]
@rossriley that is more-or-less what I had in mind in persist... The hard part is what is passed into the entity.

**Comment by SahAssar** [comment]
Can't recreate this, has this been fixed?
