### ISSUE TITLE
Show exceptions' messages for async operations to user

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4535]
It could be kind of enchancement. 
Would be lovely to know, what is the reason, why ajax operation fails. And show that in backend as toast or message. All post operations can show a message, or at least, whoops.
And async operations are keeping silence. For example, if upload operation could not save file, because bolt has no access to a folder - i would be happy to know the reason. Otherwise user needs to track with firebug. 
In my case of *"no access"* it fails here:
https://github.com/bolt/bolt/blob/master/src/Controller/Backend/Upload.php#L97
and that could be only tracked with dev tool.

![2015-11-26 13-50-59](https://cloud.githubusercontent.com/assets/2145313/11418170/a74778f8-9447-11e5-97e2-4ef26d790b41.png)

Would be lovely to wrap all file (and maybe other async) operations with some try/catches and show the result to user as message.

**Comment by GawainLynch** [comment]
AJAX should return better information, but that response didn't come from an AJAX call

**Comment by Boorj** [comment]
That was a result of image upload. I can see controller\backend\upload part, but anyway - i dind't have any page reload. So.. anyway, my point was - to let user know what is going wrong and catch an error that could occure.

**Comment by GawainLynch** [comment]
Better exception handling is coming, but it is a lot of work. The AJAX part @rarila has been working on but... Time.

**Comment by Boorj** [comment]
## This error strikes back

* remote linux
* folder `files/events` is made manualy
* `files/` has permissions
So the error is uncaught and gives this async error:

##### problem:
![2016-02-02 14-43-50](https://cloud.githubusercontent.com/assets/2145313/12744163/e3e03d36-c9bc-11e5-8129-ba3a673fba27.png)

#### Suggestion
Can we please start catching errors and show notifications?

**Comment by SahAssar** [comment]
Hmm, this one should have been fixed at the same time as #4801, no? Closing, feel free to reopen if it still appears!

**Comment by Boorj** [comment]
The idea was to show error notifications with explanations to let user know what is going wrong with his setup
