### ISSUE TITLE
New debugbar version: please bring back used templates

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4536]
Hi, I use 2.3.0 alpha 6, and noticed the new debugbar. Nice nice, but i prefer to see the templates on hover. 
Now I have to click through; thus losing the view of the site so i cannot easily see what goes with what in the templates vs the site. 

Makes it too obscure. :(  Possible to hack it back in this version?
Thx!

Anke

**Comment by GawainLynch** [comment]
I am not sure that we can.

The old version went away in May with the release of Symfony 2.7 and we don't, and we can't use the old data collection class, I am unsure about extending the new one… but we don't have enough penguins to write the amount of code we need at the moment :grin: 

For reference, the black debug bar landed very recently when we moved to Symfony 2.8-beta.

**Comment by anketwokings** [comment]
Ohnoes! Bring more Penguins! :)

**Comment by GawainLynch** [comment]
Oh just a thought… but middle clicking that part of bar, you can open the list of templates in the profile page. Not perfect compared to what you had, but a lot of really useful information on that page.

**Comment by anketwokings** [comment]
Yes, I know. :) I do use that now, but i kinda liked the earlier version. 
I guess i'll have to learn to let go. *sobs*

**Comment by SahAssar** [comment]
Closing because of penguin insufficiency. If a new shipment of penguins arrive please reopen :)

**Comment by rarila** [comment]
:penguin:
