### ISSUE TITLE
New installation with problems

### ISSUE THREAD

**Issue by pabbec** [bolt/bolt#4543]
Hi,
I was installed Boid to try it in my system, but, before initial setup, create the first user and login, Bolt says:

 Whoops \ Exception \ ErrorException (E_ERROR)

Maximum function nesting level of '100' reached, aborting!
C:\data\infosoft\desarrollo\test\apps\cms.bolt\vendor\twig\twig\lib\Twig\Node.php

Any idea?

**Comment by GawainLynch** [comment]
Yes, this is a must argued about xdebug thing.

`xdebug.max_nesting_level = 1000` in your php.ini will fix it.

**Comment by pabbec** [comment]
Thanks! It's work!
