### ISSUE TITLE
index on 'slug' in bolt_taxonomy

### ISSUE THREAD

**Issue by jan-t3000** [bolt/bolt#4545]
hey, i'd suggest adding
`$taxonomyTable->addIndex(array('slug'));`
to `getBoltTablesSchema()` in \Database\IntegrityChecker.php
as it might speed up certain queries. (bolt 2.2)

ty

**Comment by SahAssar** [comment]
Any downsides to doing this? Is it applicable to both 2.2 and (default) 3.0?

**Comment by rossriley** [comment]
nope, good idea for both.

**Comment by SahAssar** [comment]
@rossriley Assigning you for response, fix or both :)

**Comment by SahAssar** [comment]
Fixed in 55e8a97
