### ISSUE TITLE
Move preview link to Twig

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4550]
Move preview link to twig/php instead of JS. It is not dynamic and therefore no reason to be in JS. 

Unless I'm missing something with new content?

This will generate the "preview" route and fix a bug for me.

**Comment by bobdenotter** [comment]
I made it in JS originally, because as far as I can tell, you can't have two distinct 'submit' actions in a single form. If you can fix this, be my guest! :-)

**Comment by CarsonF** [comment]
@bobdenotter Cool, thanks for verifying I'm not missing anything

**Comment by rarila** [comment]
@bobdenotter I think @CarsonF meant the generation of the link, not the usage.

**Comment by bobdenotter** [comment]
Ah. :-)

**Comment by CarsonF** [comment]
@rarila Well I looked and it seems like the whole thing can just be moved to the backend (twig)

**Comment by bobdenotter** [comment]
Looking forward to being proven wrong on this one. ;-)
