### ISSUE TITLE
[Feature] Create users via invitation

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4555]
It would be nice to be able to create new users via an invitation vs having to input all their info yourself (including a password). The invitation could be typing their email and having bolt email them a link, and/or just an a authorized link generated and displayed on backend that can be copy/pasted to them.

**Comment by GawainLynch** [comment]
Want me to pick this up again, @CarsonF ?

**Comment by CarsonF** [comment]
Please

**Comment by GawainLynch** [comment]
OK, moved your branch to `feature/users-invitation` on my fork

**Comment by SahAssar** [comment]
Closing, the branch hasn't been active since Jan 30, and while I'd love the functionality I don't think keeping this open is helping.

**Comment by GawainLynch** [comment]
> Closing, the branch hasn't been active since Jan 30

Only as it hasn't been pushed … and a 3 person effort is now down to 1.

**Comment by bobdenotter** [comment]
Can I help out?

**Comment by GawainLynch** [comment]
Potentially … and that would be genuinely appreciated! The feature is all but ready to go, and as much as I was sceptical about it at first, it is a great feature and @mangroud put in a **lot** of work on this.

That said, mostly it is architectural changes that are needed (e.g. Forms), but the Twig is 100% in your area of awesome :+1:

**Comment by bobdenotter** [comment]
Sure thing. Show me the status tomorrow, and I'll join in.

**Comment by zomars** [comment]
Is this a no-no? Or a no-no right now?

**Comment by GawainLynch** [comment]
This is a "Gawain still has the branch, but is focusing on v4" as the whole auth system changes with SF4
