### ISSUE TITLE
Feature Request:  batch imagelist "select from server"

### ISSUE THREAD

**Issue by aerth** [bolt/bolt#4557]
When using the **imagelist** field, and the images are *already* on the server, there should be the option to add entire folders from /files, instead of only one image at a time.

**Comment by SahAssar** [comment]
Adding to this, it should be possible to add multiple files from one folder... Perhaps with checkboxes next to the list?

**Comment by aerth** [comment]
Yes. A "check all" box would help, too.

**Comment by rarila** [comment]
I already wanted to add this while fixing all the bugs in #4509, but as I considered this as not a bug and as we are in feature freeze …

**Comment by Boorj** [comment]
Can you please make an exception for this case :pray: ? Several of my clients have to use one-by-one selection, while sometimes mass-upload is broken, and in other cases..

**Comment by SahAssar** [comment]
@Boorj I'd rather we get 3.0 out the door and try to get this done for a 3.X rather than try to cram the whole wishlist into 3.0. [But that's just, like, my opinion.](http://31.media.tumblr.com/55d170c898b240783dc332124bbd197d/tumblr_inline_n4foafra0C1sew80h.jpg)

**Comment by aerth** [comment]
I'm going to close this because it is a feature request, but it will reopen one day.
