### ISSUE TITLE
RFC Allow dynamic base-url in menu.yml links

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#4572]
I'm using ``link: /about-page`` etc. in menu.yml 
I do this to avoid extra needed DB calls and url-matching to resolve ``path: page/1`` type of links.

**The issue:**
When developing, i'm not always adding the site to my hosts, e.g. ``example.dev``
and sometimes dev away on ``local.dev/website/www``.
Whereas a ``path: page/1`` would resolve to the correct url, 
a ``link: /about-page`` will not. 

**Work-around:**
I added the following functionality to helpers/menubuilder to search-replace
the root keyword with the root-url from app. In menu.yml use ``link: {root}/about-page``
and menuhelper resolves the correct root url.

```php
   // private function menuHelper($item)
   // ...
        if (strpos($item['link'], '{root}/') === 0) {
            $item['link'] = str_replace('{root}/', $this->app['resources']->getUrl('root'), $item['link']);
        }
        return $item;
```

**Comment by rossriley** [comment]
I think this is very similar in idea to #3005 which was a good idea, would be nice to standardise across all yml config files.

**Comment by GDmac** [comment]
It looks similar Ross, but 3005 uses variables that you can be set by the user/dev. 
This RFC is about replacing of dynamic ``webroot``

Which in combo with 3005 could maybe be done as
``$app['webroot'] = $this->app['resources']->getUrl('root')``
Depending on, where that app[webroot] would be defined (bootstrap?),
and if the resources class is available that soon.

**Comment by SahAssar** [comment]
Moved this to the forums for further discussion: https://discuss.bolt.cm/d/138-dynamic-variables-in-config-files-continuation-of-4572-and-3005
