### ISSUE TITLE
Unable to update single column of content item in user extension

### ISSUE THREAD

**Issue by jcaarls** [bolt/bolt#4592]
Hi Bolt team,

I'm new to Bolt and trying to create my first Extension in Bolt 2.2.14. 

In my extension I'm trying to update a single value of a content item. The content type is called 'Testcases' the column I'm trying to update is 'result'. In order to do this:

I'm doing the call:

$this->app['storage']->updateSingleValue($contenttype,$id,$field,$value);

with

$contenttype = 'Testcases'
$id = 1
$field = 'result'
$value = 'this is a test'

But this call fails. When debugging it:

updateSingleValue is validating the column name on line 567 of storage.php. According to the comment the parameter name for content type is of type string:

     * @param string $contenttype Content Type to be edited.
     * @param int    $id          Id of content to be updated.
     * @param string $field       Field name of content to be changed.
     * @param mixed  $value       New value to be defined on field.
     *
     * @return bool Returns true when update is done or false if not.
     */
    public function updateSingleValue($contenttype, $id, $field, $value)
    {
        $id = intval($id);

        if (!$this->isValidColumn($field, $contenttype)) {

But when I'm checking the function isValidColumn, the second argument is of type array.

    /**
     * Check if a given name is a valid column, and if it can be used in queries.
     *
     * @param string  $name
     * @param array   $contenttype
     * @param boolean $allowVariants
     *
     * @return boolean
     */
    private function isValidColumn($name, $contenttype, $allowVariants = false)

The comment in the source code is not updated I guess?
Any hints on how to do it properly are also welcome!

**Comment by GawainLynch** [comment]
> Hi Bolt team,

Hi Bolt user :wave: 

> In my extension I'm trying to update a single value of a content item.

OK, so you're close. The functions you're probably wanting are:
* `Storage::getContent()` — Fetches the content records from the database as `Content` objects
* `Content::setValue()` & `Content::setValues()` — Change value(s) of `Content` objects.
* `Storage::saveContent()` — Saves the world

An pseudo example would be:
```php
$record = $this->app['storage']->getContent('…');
$record->setValue('result', 'we have a winner!');
$this->app['storage']->saveContent($record);
```

**Comment by jcaarls** [comment]
Tried out some query examples from: https://docs.bolt.cm/content-fetching 
Fetching and updating content in my Extension works fine now. Thanks for your help!
