### ISSUE TITLE
v3.0 Extensions

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4596]
# v3.0 Extensions
##### Author: Gawain Lynch

This RFC lays out our proposed changes to Bolt’s extension implementation. It is very important to note from the very beginning, this implementation breaks backward compatibility (detailed later), but also aims to make transitioning Bolt v1 & v2 extensions easy and straightforward in most cases.
## Structure

There is currently no clear guide as to how to organise an extension’s files system layout. While this specifically doesn’t present a problem, we feel that this is a good point in time to offer some easy to follow guidelines to our extension developers that make life a bit easier and allow us a “known base” to expand upon.

We feel that levering a combination of PSR-4 and [Silex standards](https://github.com/silexphp/Silex-Skeleton) is the best approach.

```
foo-bar-extension/
├─ config
│  └─ config.yml.dist
│  └─ contenttype.yml.dist (future)
├─ src
│  └─ FooBarExtension.php
├─ templates
│  └─ foo.twig
├─ translations
│  └─ en_GB.yml
│  └─ en_US.yml
│  └─ en.yml
│  └─ es_AR.yml
│  └─ es_CA.yml
│  └─ es.yml
│  └─ pt_BR.yml
│  └─ pt_PT.yml
│  └─ pt.yml
├─ tests
├─ web
│  └─ dropbear.jpg
│  └─ koala.js
│  └─ style.css
└─ composer.json
```

| File/Directory      | Description                              |
| ------------------- | ---------------------------------------- |
| `config/`           | Configuration base files |
| `src/`              | Extension’s PHP code |
| `templates/`        | Twig templates. These should be kept separate from public assets |
| `tests/`            | Unit/acceptance test files |
| `translations/`     | Translation files |
| `web/`              | Public/web files: css, JavaScript, images, etc. |
| `composer.json`     | This is for all extension metadata: autoloading, author(s), keywords, etc. |

#### Current

In Bolt v2 registration is done with `init.php` file:

```php
if (isset($app)) {
    $app['extensions']->register(new Bolt\Extension\Bolt\BoltForms\Extension($app));
}
```
The only thing that changes in this file is the extension class name. This is the entry point for every extension, and as such there is no other customization extensions can do before this point. `init.php` comes with problems though. An `isset()` check is needed in case composer loads the file first, and we have to load it (possibly a second time) with the `$app` variable. 

This is painful for both extension developers and core developers. Extension developers have to have this file with code they may not understand and knowledge/assumptions of how core works, and it is a common tripping point when people are attempting to write a new extension.

#### Proposed

The class name is the only thing core really needs to hook into, load, and manage the extension. Achieving this has been possibly the largest, and most contentious, part of the design discussions so far.

An initial thought in the design working group’s discussion was to utilise [PHP-Parser](https://github.com/nikic/PHP-Parser) and detect class files in the `src/` directory and “magically” inject the load-chain. However, we soon realised that having core do this would be an excessive amount of work, code, and risk (including parsing PHP files, namespaces, class names, test for interface implementations, etc.). This would be very non-performant, and thus caching and cache invalidation would need to be coded / resolved.

We've come to the conclusion that it is way easier for extension developers to give us their extension’s class name. Looking at the industry, this is how others do it too. JetBrains IDEA Plugins do this with all their class names: [Symfony Plugin’s plugin.xml](https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/META-INF/plugin.xml).  PHPUnit’s [Test Listeners](https://phpunit.de/manual/current/en/appendixes.configuration.html#appendixes.configuration.test-listeners) are configured this way as well.

Don’t worry, we definitely do **not** want XML files, and we also don’t want a not-invented-here solution. Our proposal is to place the class name in the `extra` section of the extension’s `composer.json`. Several other meta information is already defined here, and is standard for meta information for PHP packages. With some good documentation, we feel this will be simpler for extension developers, and will help us (core) be more flexible in the long run.

An example `composer.json` file would then look like:
```json
{
	"name" : "carsonfull/koala",
	"description" : "Drop bear detection extension for Bolt… Texas style!",
	"type" : "bolt-extension",
	"require" : {
		"bolt/bolt" : "^3.0"
	},
	"autoload" : {
		"psr-4" : {
			"Bolt\\Extension\\CarsonFull\\Koala\\": "src"
		}
	},
	"extra" : {
		"bolt-class": "Bolt\\Extension\\CarsonFull\\Koala\\DropBearExtension",
		"bolt-assets" : "web/",
		"bolt-icon" : "assets/icon-koala.png"
	}
}
```
### Interface

All Bolt extensions are required to implement the `Bolt\Extension\ExtensionInterface` contract. This will mostly be handled in the abstract classes that extension developers can extend.

Presently this involves the following functionality:
* `getServiceProvider()` — Returns the Silex service provider interface
* `setContainer()` — Sets the Pimple application container
* `getName()` — Returns the extension name
* `getVendor()` — Returns the extension vendor name
* `getNamespace()` — Returns the extension namespace
* `getPath()` — Returns the extensions directory path

### Abstract Extension Class

The root of the extension implementation is the abstract `Bolt\Extension\AbstractExtension` class. This class implements the `Bolt\Extension\ExtensionInterface` contract. 

**Warning:** Extending directly off this class is generally not suited to a beginner PHP programmer. See below.

This is a bare-bones implementation, useful for robust extensions and/or where an extension developer wants full and absolute control over the extension’s implementation. Especially where those tiny last bits of performance might matter… or they possess an extreme level of OCD.

At this point they would have their own service provider class(es) that would be hooked into `ExtensionInterface::getServiceProvider`.

### Abstract Simple Extension Class

Most extension developers will extend the `Bolt\Extension\SimpleExtension` class. This is most analogous to the current `Bolt\BaseExtension` class, and provides helper functionality that allows fast and easy development of Bolt extensions.

This class combines our ExtensionInterface, Silex’s ServiceProviderInterface, and Symfony’s EventSubscriberInterface. This also developers to spin up simple extensions fast. However, once the extension grows and the class is a few hundred lines long the developer should migrate to the AbstractExtension class.

Previously, there was a single `initialize` method. This method was able to (and used as) a “do everything” container, and created/enforce a lot of bad habits. As a result some things work more as a result of luck and faulty functionality in core.

Some of the largest problems this created was causing functionality that depended on the request cycle (e.g. sessions) to be triggered on every single request, and trying to access data that doesn't exist yet (practically speaking).

Our proposed solution to this is to implement `register` and `boot` methods, and define helper functions for extension writers to use that make appropriate, and apparently transparent, use of `register` and `boot` eventing.

### Helper Traits

Extension helpers are provided by a collection of traits. The goal of these traits is to observe Single Responsibility Principles as much as possible, and providing flexible “helper” functions to extension developers. 

#### `Bolt\Extension\AssetTrait`

Asset injection for CSS, JavaScript, snippets and widgets.
```php
protected function registerAssets()
{
    return [
        new Stylesheet(‘style.css’),
    ];
}
```
#### `Bolt\Extension\ConfigTrait`

Special class, not so much a helper class in the same way the others are, that handled the initial installation, and ongoing loading of, extension YAML configuration files.

```php
protected function getDefaultConfig
{
    return [];
}
```
#### `Bolt\Extension\ControllerMountTrait`

Register and mount route controllers that hook into v3 controller mount functionality.

Old, deprecated way:
```php
$this->app->get(‘/foo’, [$this, ‘fooAction’]);
```

The new way is with dedicated controller classes that are registered here:
```php
protected function registerFrontendControllers()
{
    return [
        new Controller\FooController(),
    ];
}

protected function registerBackendControllers()
{
    return [
        new Controller\AdminFooController(),
    ];
}
```
#### `Bolt\Extension\MenuTrait`

Addition of extension menu items.

While this trait if extremely simple, it implements new `Bolt\Menu\MenuEntry` functionality that is used in `Bolt\Menu\AdminMenuBuilder` to build the `$app['menu.admin']` object and removing more business logic from our backend Twig templates.

```php
protected function registerMenuEntries()
{
    return [
        new MenuEntry(‘’),
    ];
}
```

#### `Bolt\Extension\NutTrait`

Before we had Clippy, we went nuts over Nut…

Old, deprecated way:
```php
$this->addConsoleCommand(new FooCommand());
```

The new way is:
```php
protected function registerNutCommands(Container $container)
{
    return [
        new Command\FooCommand($container),
    ];
}
```
`$container` is provided here for convenience to pass to your console commands.

#### `Bolt\Extension\TwigTrait`

Register function and filters that extend Bolt’s Twig implementation.

Old, deprecated way:
```php
$this->addTwigFunction(‘foo’, ‘fooMethod’);
$this->addTwigFilter(‘foo’, ‘fooMethod’);
```

New way:
```php
protected function registerTwigFunctions()
{
    return [
        'foo' => 'fooFunction',
        'bar' => ['barFunction', ['is_safe' => 'html']]
    ];
}

// Same for registerTwigFilters
```
See PHP docs in trait for more info.
## Integration with core
`Bolt\Extensions` will be replaced with `Bolt\Extension\Manager`. The implementation is still being worked out.

Local extensions will be autoloaded provided that the composer autoloader is re-dumped, and autoloader generation will be moved to a nut command for local extensions

Thought being that core doesn't have to maintain checks (and associated caching). So local extensions will be added to composer.json upon auto loader dump (or whatever command) and then core includes the composer autoloader.php and we are done.

The current autodetect and dump is a hack that is fragile… but it will break when we re-do the exception handling.

## Backward Compatibility Breaks
* Base class to extend changes
* No more `initialize()` function
* Global twig variable for extension is no longer added

**Comment by GawainLynch** [comment]
@SahAssar flagging this to be closed after the dev meeting on 22 December.

**Comment by Boorj** [comment]
maybe it's clearer to use `extension.yml` instead of one more `config.yml`?

**Comment by SahAssar** [comment]
I'd be more for it to be the same filename as what the file will be named by bolt in the /app/config/extensions folder (but with `.dist` added), since then we might preempt more confusion...

**Comment by GawainLynch** [comment]
> I'd be more for it to be the same filename as what the file will be named by bolt 

TBH, that is just asking for a living hell. If we *know* then are called `config.yml` or `extension.yml` then we only have a single file to try and match.

Personally, I think how `config.yml.dist` is now is intuitive enough for an extension developer, as it is only relevant to the extension developer **and** Bolt core… 

For everyone else, it is in `app/config/extensions/` and named based on the extension's Composer name pattern (`package-name.author-name.yml`).

**Comment by GawainLynch** [comment]
Landing in a PR near you… soon!
