### ISSUE TITLE
Bolt takes a long time to process

### ISSUE THREAD

**Issue by pabbec** [bolt/bolt#4597]
I was installed Bolt in a local machine to test the CMS. Each request take 10 to 30 seconds to proccess and to generate a response (in admin or public).

In the debug bar, I see in the timeline (image attached) that the componente Symfony\Component\HttpKernel\EventListener\EsiListener take 23244ms to run.

I'm using Bolt with WAMP with PHP 5.5.12 on Windows 7. 

![bolt-timeline](https://cloud.githubusercontent.com/assets/426825/11822772/06582c00-a34f-11e5-80df-6491541f386d.png)

**Comment by bobdenotter** [comment]
Hi, 

Which version of Bolt is this? 

Is your local setup's reverse DNS configured correctly? I'm guessing what you're seeing is the time-out for when your Bolt setup can't reach bolt.cm to fetch the latest news.

**Comment by aerth** [comment]
Try disabling news in [config.yml](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L439) by uncommenting lines 437, 438, 439.  *That should do it*

**Comment by pabbec** [comment]
Hi, I'm using de latest version of Bolt 2.2.14

**Comment by pabbec** [comment]
Hi aerth. I disabled it, but the problem persists :(

**Comment by aerth** [comment]
Have you tried clearing the cache? You may just clean out the ```/app/cache/``` directory

**Comment by pabbec** [comment]
Hi aerth. Yes, if it's the first thing I did.

**Comment by pabbec** [comment]
I enabled logs, clean and disabled cache.

I attach the log file here:

[bolt-debug.log.txt](https://github.com/bolt/bolt/files/65513/bolt-debug.log.txt)

In this case, Bolt takes 102 seconds to bulid de dashboard :/

**Comment by SahAssar** [comment]
Actually, it could still be the news request since it still tries to fetch the news to check for alerts. See here: https://github.com/bolt/bolt/blob/release/2.2/src/Controllers/Async.php#L190

@pabbec: Could you see if you can cURL http://news.bolt.cm/ from the server?

**Comment by SahAssar** [comment]
Tagging this for closing on the 8th if no more info comes in. Please feel free to reopen after that if you have the info we need to recreate!

**Comment by SahAssar** [comment]
Closing per my comment on the 5th. Please feel free to reopen if this is still an issue and you have the info we need to recreate!

**Comment by pabbec** [comment]
Hi @SahAssar . I apologize for the delay, for personal reasons, I was disconnected these days.

I was installed Bolt on another PC (where I work normally) and going great.

I have also installed Bolt on the production server, and it runs smoothly.

But just I try my notebook (where this problem appeared) and yes, I can connect with cURL to http://news.bolt.cm smoothly and fast.

It is a very rare case, but is likely to be a timely issue in shaping my old notebook.

It is the first project that will use Bolt for production, and I hope eventually learn enough to bring things to the project.

Thank you so much for everything!

Pablo
