### ISSUE TITLE
[RFC] Make Javascript mandatory for the backend

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#4615]
At the moment we display a warning

> JavaScript is currently disabled in your browser. Most functionality in Bolt will work without it, but for greater ease of use we recommend you enable JavaScript in your browser.

in the sidepanel of dashboard and omnisearch. I haven't testet it but I guess it will range more between some things will probably work and you're in danger of corrupting things. Too much things depend on Javascript to not only work more comfortable but to work at all. Even if 50% of all pages would work, the warning would have to be displayed on every page or at least on every page where switching it off can make problems, not just on two pages.

So my suggestion is to make Javascript mandatory for the backend. Lets display the warning at the login screen and make the login Javascript based.

**Comment by GawainLynch** [comment]
This has my support. :+1: 

I use script blockers to stop obnoxious ad risky stuff, be re-enable it for my bank, GMail, etc, where I know functionality is needed. 

…and let's face it, if you're using the Bolt back end, you have a login and have been given that either because you created the site yourself, or someone you know and have some degree of trust in did.

**Comment by rossriley** [comment]
:+1:  Here.

Adding that the new repeating field blocks are dependent on JS too so that's another set of functionality that won't work without it enabled.

**Comment by rarila** [comment]
Tested it yesterday there's almost nothing you can do without. You can't even log off. No dropdowns, no tabs, only toplevel navigation, …

**Comment by GawainLynch** [comment]
Yeah, if JavaScript is disabled, we should have a JavaScript dialogue that pops up to say:
```
If you had JavaScript enabled, you would see this warning about 
having JavaScript disabled!
```

**Comment by rarila** [comment]
@GawainLynch … yeah, and we let a JavaScript animation trickle green :leaves: from the screen …

**Comment by bobdenotter** [comment]
If we lived in an ideal world, and we had the resources, I'd very much like it, if we could make the Javascript for the backend completely "progressive enhancement".

That said, seeing how js is basically required to make it work, we might as well make it mandatory.

> Lets display the warning at the login screen 

Agreed.

> and make the login Javascript based.

Nooope. No reason to make it _less_ accessible, just to prove a point.

**Comment by GawainLynch** [comment]
>> and make the login Javascript based.

> Nooope. No reason to make it less accessible, just to prove a point.

Totally agree!

**Comment by rarila** [comment]
But isn't there a possible security risk if you can login but can't logout?

Say you wanna login on a computer you don't own, see the warning… ah, I just wanna look up something let's see if it works… boom, you have a real problem.

**Comment by GawainLynch** [comment]
That one should have a backup plan (on our part), but yes, that is a valid point too.

**Comment by rarila** [comment]
Backup plan: always take a :bomb: with you for the case you can't logout ;-)

**Comment by delfiramirez** [comment]
If no progressive enhancement, better no Javascript-ish based back-end, gentlemen.

**Comment by rarila** [comment]
@delfiramirez We are past this point already since a long time. Progressive enhancement would mean having second parallel server side handling path for all things that are dynamic now. Doing so and having to design, coordinate and test those two interfaces would not just double the development time, it would increase exponentially. It would be for sure take much less resources to create a second non js backend.

But as @bobdenotter said, we are short of resources. So I prefer having a comfortable and modern interface and have v3.0 soon than having an ideal interface in 3 years. I'm all for Javascript free frontend code, but I see the backend as an application where I like to make other requirements. Other changes to the interface like RTL would for sure bring benefit to pretty much more users than a js free interface.

Also don't forget the motivation behind developing Bolt:
- Having fun coding and being with nice people
- Making Bolt into an tool that fits personal and business needs

As my customers for sure neither know what Javacript is nor care or even know how to switch it off…
I guess the same is true for the other devs. So as long there's no dev with a need for a js free interface and quite amount of spare time… :smile_cat:

**Comment by delfiramirez** [comment]
@rarila May it be possible to change  the custom v3 back end interface via extensions ?. 

Users -- developers -- can install the extension  if their clients need it.  An install in the same way a personal branding theme, or a front end widget is done right now.

"...than having an ideal interface in 3 years," um that looks like low blow.

Anyway, that was a simple suggestion. Nice festives

**Comment by GawainLynch** [comment]
> May it be possible to change the custom v3 back end interface via extensions ?.

Somewhat on the radar for v4 (was going to be v3, but 2.3 became v3).

We still have to hash out the details of how that will work, so nothing to "share" yet, but I would imagine either @bobdenotter or @rarila will RFC a proposal some time in 2016… Watch this space :grin: 

> "...than having an ideal interface in 3 years," um that looks like low blow.

Honestly, I think that got lost in translation… @rarila isn't one for low blows, only sharing :beers: :grin:

**Comment by SahAssar** [comment]
Are we agreed that making JS mandatory for the backend has sorta already happened and formalizing this with a "harder" noscript message would be logical at this point?

I agree that making the login JS based just to block non-js clients might be a bit to far, but showing a very clear noscript message on the login screen and all backend pages should suffice. Something along the lines of "You do not currently have JavaScript activated in your browser. Bolt requires JavaScript to function properly and continuing without it might corrupt or erase data."

**Comment by delfiramirez** [comment]
Yes, we agree -- and realize -- JS is mandatory, in fact ;) .
a <noscript> might be nice. Common ECMAScript-enabled browsers, re ok with it.

**Comment by bobdenotter** [comment]
Yes, :+1: 

I would still urge that we find another way to "enforce" this, than by adding weird javascript hacks to the login page, though. :-)

**Comment by SahAssar** [comment]
#4737 should be a sufficient "fix" for this, please reopen if anyone feels there is more to do on this :)
