### ISSUE TITLE
When using output caching, the assets queue is processed every time.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4618]
If `cache: request: true` is set, Bolt caches the rendered output. This works (mostly) as expected, expect for the fact that the assets queue is applied to the cached results again, and the outcome of that is saved to the cache again. 

The result might look like this: 

![screen shot 2015-12-22 at 13 49 48](https://cloud.githubusercontent.com/assets/1833361/11955550/27d30f80-a8b3-11e5-9b89-cf3d5cfe5a0f.png)

Every subsequent request adds a set of `meta generator` and `canonical` tags.

**Comment by GawainLynch** [comment]
Are those AJAX requests?

**Comment by SahAssar** [comment]
Yeah, I've run into this, but I couldn't figure out what made it appear, since when I have `request: true` sometimes it happens and sometimes it doesn't....

**Comment by bobdenotter** [comment]
Nope, just regular http. Check for yourself by refreshing view-source:http://www.writersunlimited.nl/nieuwsbericht/jung-chang-opent-festival-op-donderdag-14-januari

**Comment by bobdenotter** [comment]
> since when I have request: true sometimes it happens 

When not logged in, or incognito.. 

> and sometimes it doesn't....

.. when logged in. ;-)

**Comment by SahAssar** [comment]
Ah, makes sense :)

**Comment by GawainLynch** [comment]
Yeah, pretty straightforward to fix… in Bolt\Render it need to flag/check if it's a rendered request and skip the queues in that case.

**Comment by bobdenotter** [comment]
@GawainLynch I was implementing just that. ;-)

**Comment by GawainLynch** [comment]
You, sir, are a legend! Thank you! :+1:

**Comment by GawainLynch** [comment]
Fixed in #4619

**Comment by bintoro** [comment]
I'm seeing the compounding generator and canonical tags again in the current version of Bolt.

**Comment by SahAssar** [comment]
@bintoro You mean in 3.1.0?

**Comment by bintoro** [comment]
@SahAssar I got started with 3.0.6/3.0.7 and then upgraded to 3.1.0. I remember noticing the compounding already on 3.0.7 but didn't think much of it at the time. It was only now that I realized it happens all the time with caching enabled, and this is on 3.1.0.

**Comment by GawainLynch** [comment]
The request caching layer has been replaced in what will be v3.2 (`release/3.2`) and given available resources I honestly can't see it getting fixed in the old layer.

If you're really serious about request caching though, I'd strongly recommend looking at Varnish.

**Comment by bintoro** [comment]
Right, this is certainly not a priority for me.
