### ISSUE TITLE
Seeing `page.login.title` and other placeholders..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4620]
This still happens occasionally: 

![screen shot 2015-12-22 at 16 00 48](https://cloud.githubusercontent.com/assets/1833361/11957995/6051b566-a8c5-11e5-88ff-0812ae568fe9.png)

It's "fixed" when you clear the cache, but it's still confusing (and slightly offputting) for newcomers. I thought we fixed this, somewhere in the 2.x cycle, right?

**Comment by SahAssar** [comment]
@bobdenotter same "symptoms" as #3948, but I'm guessing it isn't the same issue unless you have some quirky extensions installed.

**Comment by SahAssar** [comment]
Can't recreate this, has this been fixed?

**Comment by GawainLynch** [comment]
I saw it again the other day… it was permissions on the cache.

**Comment by GawainLynch** [comment]
OK… so this is going to invoke a "How many times have I tried to tell you!!!" response from @CarsonF :grin: 

Quite simply, it is from invoking `$app['translator']` too early… that builds, and caches, an empty catalogue… and as it is now in cache, the translation keys are no longer in the catalogue.

Most (all?) of the culprits seem to be the FlashBag (handled by the FlashLogger in v3), so it might be worth shifting those translations to a lazy loading object that is called on the request cycle event.

**Comment by bobdenotter** [comment]
Fixed in #4855

**Comment by CarsonF** [comment]
How many times have I told you! :P
