### ISSUE TITLE
Bunch of notices when clearing the cache.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4622]
See screenshot: 

![screen shot 2015-12-22 at 17 08 48](https://cloud.githubusercontent.com/assets/1833361/11959640/be21f5b2-a8ce-11e5-9011-2d8ddaee11cb.png)

**Comment by GawainLynch** [comment]
Oh wait… I might have fired the assignment too quickly… can you composer update and see if you still get that please.

**Comment by bobdenotter** [comment]
Right! Issue solved, closing.. 

![https://s-media-cache-ak0.pinimg.com/originals/e3/8e/b6/e38eb6f2fb021eb9bd2dec3ea158b121.gif](https://s-media-cache-ak0.pinimg.com/originals/e3/8e/b6/e38eb6f2fb021eb9bd2dec3ea158b121.gif)

**Comment by GawainLynch** [comment]
Yeah… I was too quick… @CarsonF made my day with that PR in the bolt/filesystem repo too! :+1:

**Comment by CarsonF** [comment]
![](https://lh3.ggpht.com/K5g3GuzDZFSNqQnZ_tLo9tMPc3fDuWHfY_eiYIIHLYeIGF1etT8741wigPlAFwtVSm8=w300)
