### ISSUE TITLE
Notices in backend, when logging in: 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4624]
![screen shot 2015-12-22 at 17 24 09](https://cloud.githubusercontent.com/assets/1833361/11960090/263e2e0c-a8d1-11e5-8410-d7d0f5686aef.png)

I get these right after logging on. `composer update`'d and I have `debug_error_level: -1` in `config.yml`.

**Comment by GawainLynch** [comment]
Fixed in #4753
