### ISSUE TITLE
[RFC] Refactoring current Pager implementation

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#4627]
Bolt 3.0 is going over a great rejuvenation and had been reorganized beside some important viewpoint. I thought let's touch those parts too - if you all think so - that should have a more elegant face lifting. One of those our current paging (Pager) solution.

We should have ``Bolt\Provider\PagerServiceProvider`` and ``Bolt\PagerManager`` or ``Bolt\Pager\PagerManager``

### class PagerManager ...

- is going to be a centralized service that would be instantiated lazily by ``PagerServiceProvider``.
- Furthermore each currently applied ``Pager::`` based, global smelling static call would be served by the manager to fit TDD principle.
- The service will be accessible via ``$app['pager']`` then.

#### Role of the manager

- manages Pager elements which are atomic objects of a paging reference and roughly corresponding current ``Bolt\Pager`` objects
- responsible for decoding/encoding pager objects from/to query parameters
- centralizing all pager related operations like ``$page = ($request->query) ? $request->query->get($param, $request->query->get('page', 1)) : 1;`` occurred redundantly some places in code ATM
- a pager element would be reached like ``$app['pager']['search']``
- ``(string) $app['pager']`` for encoding HTML query rather than ``Pager::makeLink()``
- no more ``Bolt\Legacy\Storage::GetContent()`` (and others) need to receive ``&$pager`` as argument, which is not so clear enough

At first sight... Thoughts?

**Comment by rarila** [comment]
:+1:

**Comment by GawainLynch** [comment]
> Bolt\Provider\PagerServiceProvider

:+1: 

> Bolt\PagerManager or Bolt\Pager\PagerManager

I am in two minds on namespace location… need more :coffee: first… and I am sure others will chime in.

> (string) $app['pager'] for encoding HTML query rather than Pager::makeLink()

Yes please… I already know the `__toString()` :cop: will give us a hard time, but solutions damnit!

> Furthermore each currently applied Pager:: based, global smelling static call would be served by the manager to fit TDD principle.

And pretty please can we also enhance tests on these at the same time… I know a start has been made, but it is a part of the code that is really under tested.

> no more Bolt\Legacy\Storage::GetContent() (and others) need to receive &$pager as argument, which is not so clear enough

:100: :100: :100:

**Comment by SahAssar** [comment]
Fixed by #4648
