### ISSUE TITLE
Replace our request caching with Symfony's HttpCache

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4629]
Here are the problems I see with our current _request caching_ implementation:
1. Only _duration_ is supported for cache expiration. vs. HTTP protocol which supports timestamp and lifetime expiration and invalidation via ETags and last modified time.
2. Don't reinvent the wheel. Part of being *simple* for users/developers is less custom code.
3. It only works with routes that go through the [`Frontend`](https://github.com/bolt/bolt/blob/release/3.0/src/Controller/Frontend.php#L75-L81) controller as fetching the cached response is done there.
4. Separation of concerns. `Frontend` and `Render` should not need to know about caching as that is not their responsibility.

Symfony's [HttpCache](http://silex.sensiolabs.org/doc/providers/http_cache.html) is the answer. Heck we already load the [Silex integration](https://github.com/bolt/bolt/blob/release/3.0/src/Application.php#L160-L162) of it.

Setting the response cache headers also allows a _Gateway Cache_, such as _Varnish_, to be used. This is faster than _Symfony's HttpCache_, which is a _Reverse Proxy_.

As with lots of code changes for 3.0, the push is towards Bolt as a framework / platform. Leveraging this is another step in that direction. Not to mention less code, cleaner code, and moar better.

**Comment by GawainLynch** [comment]
Overall I am in favour… but we have a few things to clear out first.

**Comment by rixbeck** [comment]
Fine...

**Comment by bobdenotter** [comment]
I'd be in favor of this. :+1:

**Comment by bobdenotter** [comment]
Closed by #5615
