### ISSUE TITLE
Bad pagination performance

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4632]
I've just finished migration of a huge amount of data into a Bolt-based site and now I have a problem with a very slow performance of pagination on large lists. So I watched into profiler and this query
````sql
SELECT bolt_news.* FROM bolt_news WHERE (`bolt_news`.`status` = 'published') ORDER BY `datepublish` DESC LIMIT 35 OFFSET 25270 
````
takes near 12 seconds to fetch a data. I've tried [an alternative approach](http://devoluk.com/mysql-limit-offset-performance.html):
````sql
SELECT * 
FROM bolt_news 
JOIN (SELECT id 
      FROM bolt_news 
      WHERE status = 'published'
      ORDER BY datepublish DESC
      LIMIT 25270, 35) AS t ON t.id = bolt_news.id;
````
and it is very fast in comparison to previous query(~0.016 sec), even without a multi-column index(btw, how to create it using Bolt configuration file?). Where should I look to make a quick fix and replace the default query?

**Comment by bobdenotter** [comment]
Hi C4Grey, 

That's quite a slowdown there, yes. Which version of Bolt are you using? MySQL, I assume? 

> even without a multi-column index(btw, how to create it using Bolt configuration file?). 

You can use `index: true` in the contenttypes.yml, but only for single columns. 

> Where should I look to make a quick fix and replace the default query?

Right here: https://github.com/bolt/bolt/blob/release/2.2/src/Storage.php#L1775

Please be aware that if you change core files, it'll break (or be reverted) on updates of Bolt.

**Comment by C4Grey** [comment]
Thank you for the answer.

> Which version of Bolt are you using? MySQL, I assume?

Yes, I am using MySQL 5.5.46 and Bolt 2.2.14.

> You can use index: true in the contenttypes.yml, but only for single columns.

In my experience, multi-column index can show a nice boost on a large data set, it will be good to have an opportunity to use it.

> Right here: https://github.com/bolt/bolt/blob/release/2.2/src/Storage.php#L1775
> 
> Please be aware that if you change core files, it'll break (or be reverted) on updates of Bolt.

And thanks again :)

**Comment by GawainLynch** [comment]
For reference, this should be possible via extension, etc, in Bolt v3 (Q1 2016) on a per-table basis… as the tables are all DI objects now.

**Comment by rarila** [comment]
It would be interesting how PostgreSQL performs in this case.

**Comment by C4Grey** [comment]
@GawainLynch Every time I learn something new about Bolt 3, it makes me to wait for a release even more :)
@rarila According to [this article](http://explainextended.com/2011/02/11/late-row-lookups-innodb/), using PostgreSQL you will not encounter such a problem:

>PostgreSQL won't pull the fields from the table until it really needs them. If a query involving an ORDER BY along with LIMIT and OFFSET is optimized to use the index for the ORDER BY part, the table lookups won't happen for the records skipped.

**Comment by GawainLynch** [comment]
> Every time I find out something new about Bolt 3, it makes me to wait for a release even more :)

Yeah, there is so much awesome coming in v3, we're all pretty excited. :grin: 

Although, v2.2.x is a **very stable ** release branch that we're also very proud of.

**Comment by rarila** [comment]
@C4Grey So preconceptions sometimes turn out to be right :tada: 
I wonder if MySQL will ever get it right.

**Comment by SahAssar** [comment]
If I'm reading this thread correctly (and I'd like to think I am) this is not something we want to change in 2.2 (because it is a performance issue in one specific database) and in 3.0 it will be possible to fix this in extensions, right?

**Comment by GawainLynch** [comment]
@SahAssar Yeah, 2.2 is definitely in maintenance mode functionality-wise.

…and yes, doable with an extension in 3.x.

**Comment by SahAssar** [comment]
Alright, closing this then. Feel free to reopen if more discussion is needed.
