### ISSUE TITLE
show_in_menu option is not working with custom names

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4633]
Hi!
When I am trying to group a few content types in the backend menu, like [described in documentation](https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes):

>show_in_menu (optional): When set to false the contenttype will show in a submenu instead of as a top level menu. Can also be set to a word or sentence to group contenttypes under different menus.

like this:
````yaml
show_in_menu: Broadcast
````
grouping simply not working, menu entries just stays in place.

P.S. I am using Bolt 2.2.14

**Comment by bobdenotter** [comment]
have you tried putting _more than one_ contenttypes into `show_in_menu: Broadcast` ?

**Comment by C4Grey** [comment]
@bobdenotter of course...this is a meaning of this option, isn't it?

**Comment by bobdenotter** [comment]
Just checking.. :-)

I'll see if i can replicate it.

**Comment by bobdenotter** [comment]
Confirmed.. Something's not quite right there.. Expect a fix soon!

**Comment by bobdenotter** [comment]
@C4Grey Turns out we had this in 'master' (for Bolt 3.0), but not yet in 2.2.x, even though it snuck into the documentation. 

I could do a simple backport, so it'll be in Bolt 2.2.15.
