### ISSUE TITLE
Exception if extension config is empty

### ISSUE THREAD

**Issue by fadoe** [bolt/bolt#4636]
I installed a bolt extension with empty config file (like clientprofiles). When I want to open this file in the backend, I get a exception "The file 'extensions/clientprofiles.bolt.yml' doesn't exist, or is not readable.". The problems are here:

* https://github.com/bolt/bolt/blob/master/src/Controller/Backend/FileManager.php#L81
* https://github.com/bolt/bolt/blob/release/2.2/src/Controllers/Backend.php#L1849

The checks should be:
```
if (!$file->exists() || false === $file->read()) {
```
$file->read() returns false if file can't be read. At the moment $file->read() returns a empty string and this is checked as false.

**Comment by GawainLynch** [comment]
Good find… :+1: 

You're very welcome to PR the fix if you would like, or I'll grab it soon for you if need be.

**Comment by fadoe** [comment]
You have pull requests. ;-)

**Comment by GawainLynch** [comment]
Legendary! Thank you :smile:
