### ISSUE TITLE
Extending user contenttype

### ISSUE THREAD

**Issue by ScreamZ** [bolt/bolt#4643]
Hi,

I was looking for a way to extends the user profile, to add some kind of field like a bio, image, I've been searching on Google and even in issues topics on github but I didn't found anything. I know i can use the mail address and gravatar but what about a bio field ?

I would like to know if there is a way I can do that ?

Thanks for the support

**Comment by SahAssar** [comment]
Hey @ScreamZ,

It's currently not possible, but see #927 and #4085 for discussion. There should also be a thread in discuss.bolt.cm with some tips on workarounds...

Closing since #927 is kept open as the place to discuss this.
