### ISSUE TITLE
Delete button and extension page

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#4646]
I have been away for some time and couldn't follow Bolts development. But I'm back and I'm curious about two things. Can someone catch me up? I can remember that I asked for a delete button on top of the entry list. Wasn't that implemented earlier? I just installed 2.2.15 and now the delete button is gone. I also started an issue about making a simpler extension menu/page. Is this still something that is discussed?

**Comment by SahAssar** [comment]
Hey @gwbonline!

The delete button is in master/3.0, see #4242. The extension menu fix is also in master/3.0, see #4232. 

Hopefully that answers your questions!
