### ISSUE TITLE
Improve deprecation handling for controllers.

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4652]
This is just a minor issue I've found while trying to update 2.x sites to 3.0

If you are providing a custom Frontend controller with a setup something like this:

```
<?php
namespace MyApp\Controller;

use Bolt\Controllers\Frontend as BoltFrontend;

class Frontend extends BoltFrontend
{
...
```
For reference note the namespace this points to the deprecated `Controllers\Frontend` rather than the new `Controller\Frontend`

Firing up a request on this will give this uncaught exception:

    Fatal error: Uncaught exception 'LogicException' with message 'The "mount" method takes either a "ControllerCollection" or a "ControllerProviderInterface" instance.'

So, two possible suggestions, can we adjust the deprecated controller to implement those interfaces, or if not and the deprecations are non-compatible then can we detect and throw a better error message informing them to rename `Controllers\Frontend` to `Controller\Frontend`

**Comment by GawainLynch** [comment]
Damn :koala: strikes again!

My vote is that we should gracefully handle extension of the deprecated controller in v3.

**Comment by rossriley** [comment]
Another one spotted.

Fatal error: Class 'Bolt\Controllers\Async' not found

It would be nice if this one could be handled too.

**Comment by GawainLynch** [comment]
Closing as per dev meeting

**Comment by SahAssar** [comment]
For any future issuenauts the dev meeting reefers to https://github.com/bolt/bolt/wiki/Dev-meeting-2016-03-01
