### ISSUE TITLE
Installing new extensions will no longer create the asset directory

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4655]
This line here seems to be the culprit:

https://github.com/bolt/bolt/blob/master/src/Composer/EventListener/PackageEventListener.php#L34

Passing through `realpath` returns false if the directory doesn't exist and it therefore won't get created.

**Comment by GawainLynch** [comment]
Does this [iteration](https://github.com/GawainLynch/bolt/blob/feature/v3-extensions/src/Composer/EventListener/PackageEventListener.php) solve it ?

**Comment by rossriley** [comment]
I'm guessing not since the implementation is similar eg here: https://github.com/GawainLynch/bolt/blob/feature/v3-extensions/src/Composer/EventListener/PackageEventListener.php#L46

We'd either need a mkdir that tries to create the directory before passing to realpath, or as we did before, pass the theoretical directory to the mirror method and it will try to create / copy or fail if it is unable to.

**Comment by GawainLynch** [comment]
Ugh… I really need to not try and answer these things when walking out the door… That was 10 parts stupid on my behalf :grin: 

Does this work for you @rossriley  https://github.com/bolt/bolt/commit/24a24defb2309826d439ecf9ce1e22be05798aed ?

**Comment by rossriley** [comment]
:+1:

**Comment by GawainLynch** [comment]
I'm pretty sure @CarsonF asked me to remove that `realpath()` call when the PR was in review… I must have been sober or something.

**Comment by rossriley** [comment]
Have these :beers:

**Comment by SahAssar** [comment]
Fixed in #4695, no? Riiiight about here: https://github.com/GawainLynch/bolt/commit/82c28532ad8ce10c1f93df90d19a2deef90b5a90

**Comment by GawainLynch** [comment]
:+1:
