### ISSUE TITLE
Async File Listing Bug

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4659]
Again on master only.

An async browse files request on the default directory, eg: `/async/browse` seems to do a recursive listing of all files rather than just a listing of the files within the base folder.

Once you navigate to a folder then behaviour seems to return to normal, eg when the url shows: `/async/browse/files/2016-01` then the listing appears to behave correctly again, showing only files in that level folder.

**Comment by GawainLynch** [comment]
Probably the identical derp that I fixed in #4656 today
