### ISSUE TITLE
extensions.bolt.cm & ipv6

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#4661]
OHAI.

http://0.0.0.0:8080/bolt/extend gives me a curl error  because I'm on an ipv6 enabled connection and it tries to resolve extensions.bolt.cm via ipv6. This is the german version of curl crying the resolv.conf song of it's people:

```
Das Prüfen der Verbindung zum Erweiterungsserver ist fehlgeschlagen: cURL error 6: Could not resolve host: extensions.bolt.cm
http://extensions.bolt.cm/ is unreachable.
```

Options to fix:

* give the extensions.bolt.cm fleet ipv6 connectivity
* persuading guzzle / the extensions code to not try ipv6 in the first place by using curl params like `curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );`

Another one would be to disable ipv6 on the machine that's running bolt. You can easily do this with bash e.g.: `echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6`. The problem is if you're running bolt from within a container (like me), /proc is being mounted from the host read-only. So within the container instance, you don't have a chance to. Other options like socat'ing ipv6 to ipv4 are even hackier.

**Comment by SahAssar** [comment]
Adding this to the todo list... I'd prefer if *.bolt.cm had ipv6 connectivity.

**Comment by SahAssar** [comment]
@GawainLynch Is there anything standing in the way of this besides just adding the AAAA record?

**Comment by GawainLynch** [comment]
Don't quote me, but I seem to think I added IPv6 to the new extensions site so when we go live it might be a non-issue.

**Comment by doertedev** [comment]
@SahAssar adding the AAAA record is enough when the box actually has an IPv6 address.
@GawainLynch then please leave  the issue open, would you? :)

**Comment by SahAssar** [comment]
@doertedev Of course!

**Comment by SahAssar** [comment]
@GawainLynch Just a gentle reminder that since we have gone live with the new site we might be able to solve this one :)

**Comment by SahAssar** [comment]
@GawainLynch Assigning this to you!

**Comment by GawainLynch** [comment]
Done! (including docs, extensions & main site)
