### ISSUE TITLE
Improve Deprecation for Bolt\Controllers\Routing

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4663]
Pinging @CarsonF 

Most of the deprecation is handled nicely here, the one exception that I've found is that previously the constructor allowed no args to instantiate, eg: `new Bolt\Controllers\Routing();`

Doing this now results in the error: 

```
Catchable fatal error: Argument 1 passed to Bolt\Controller\Requirement::__construct() must be an instance of Bolt\Config, none given
```

This comes from the deprecated class now extending the new `Bolt\Controller\Requirement` and inheriting its constructor.

Would we be ok to implement a constructor in the deprecated class to work around this?

**Comment by CarsonF** [comment]
Sure..we would just need to figure out how to set the config
