### ISSUE TITLE
Graceful Deprecation for Custom Controllers

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4665]
I'm turning into the grinch of deprecations at the moment, this one is more an RFC.

We've made this change to the signature for controllers

Was: `public function record(Silex\Application $app, $contenttypeslug, $slug = '')`
Now: `public function record(Request $request, $contenttypeslug, $slug = '')`

Now this is absolutely the correct approach, but we've again made all custom controllers breaking between 2.x and 3.0 without a deprecation version. As it happens (and I assume this was also done to maintain BC) the frontend controller does have access to $this->app.

So as a deprecation step what's everyone's thoughts on making the signature:
`public function record($request, $contenttypeslug, $slug = '')`
and then sniffing:

```
if ($request instanceof Silex\Application) {
    $request = $request['request'];
}
```
or something similar, perhaps also logging a deprecation warning inside the block. Note that this would need to be the case for all methods on the controller so maybe it could be wrapped into a single handler method.

Again, I think what we have is correct, passing the app around to controller actions is obviously wrong, but since we can make it smoother that may save a fair amount of work needing immediate migration for those of us that have a lot of custom controllers.

**Comment by GawainLynch** [comment]
Couldn't we handle that in the parameter detection? (it would mean overriding it I think)

**Comment by CarsonF** [comment]
I don't think this matters at all as silex/symfony already uses reflection to determine what parameters to pass in.

**Comment by GawainLynch** [comment]
Well, that's what I thought too… but why is this getting hit?

**Comment by CarsonF** [comment]
@rossriley if you are talking about the `Frontend` class, that signature has stayed the same.

**Comment by rossriley** [comment]
Yes, but the problem is also related to #4652 if you try and extend the old Frontend controller then you get `Fatal error: Uncaught exception 'LogicException' with message 'The "mount" method takes either a "ControllerCollection" or a "ControllerProviderInterface" instance.'` 

So moving to extend the new one solves that problem but obviously introduces the one above. So we can solve this either by making #4652 backwards compatible or by addressing this one instead, whatever is easier.

**Comment by rossriley** [comment]
Ok, I've been playing around for a while with this and I don't think it's going to be possible to get it to work.

There's two ways I've tried, firstly leaving a custom controller extending the deprecated controller and secondly by updating it to use the new one.

There's a few steps to attempt option 1. 

Firstly the controller cannot be mounted, it was relatively easy to fix this by setting deprecated frontend to extend configurable base and implementing the necessary methods. 

However, you soon run into problems because the `->frontend()` method calls `$app['controller.frontend']` which is of course your overriden controller and then all of the methods aren't compatible with the new `Controller\Frontend` 

I tried sniffing the instance of `$app['controller.frontend']` to decide which behaviour to exhibit but that also has a new set of problems because if you try to proxy to the new controller from the old one it has not been connected properly so `$this->app` isn't available which in turn means the `before()` method can't work.

So, all being considered, I'm thinking that we probably should tackle this with a clean break and document how to upgrade your controllers, rather than deprecating, I think the process to upgrade controllers to work with Bolt 3.0 can be:

1: Update the class to extend `Bolt\Controller\Frontend`
2: Replace each method signature `Silex\Application $app` with `Symfony\Component\HttpFoundation\Request $request`
3: Add `$app = $this->app` as the first line in the method (or rewrite all the instances within the method if easier)
4: If you call the parent method, then replace `$app` with `$request` as the first parameter.

If we do this then we get the added benefit of being able to kill the old controller classes and just alias it to be compatible with old `routing.yml` setups.

thoughts?

**Comment by GawainLynch** [comment]
Well… and I am channelling @CarsonF's frustration at me now… the reason the plural namespace stayed originally was that branch was going to be a 2.x branch and I wouldn't let Capt. Carson break shiiii… stuff.

I honestly am in favour of ditching it, lots of stuff is going to break BC, and trying to give BC on as much as we are now seems to be counter intuitive for a major release.

Also, thank you @rossriley for putting in the effort here… really appreciated on my part :smile:
