### ISSUE TITLE
RecursiveDirectoryIterator fatals when scanning /tmp/

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4667]
Basically the site crashes (running a recent snapshot of master) on the front end with an access denied error reading `/tmp/.foobar` (which it shouldn't have access to). Not sure about reproducing this one, will attempt to recreate it but it's hit us twice today.

My initial gut feel was sessions, as the sites are all using `/tmp` for the `session.save_path`, but this wasn't an authenticated user.

@CarsonF any thoughts as to what might be the cause?

**Comment by CarsonF** [comment]
Yes that is basically an unavoidable breaking change with sessions. We are trying to write now with user land code instead of native C code.
