### ISSUE TITLE
[RFC] - Content Locking Feature

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#4670]
We're currently in the midst of building an extension to allow authors to lock an entry (upon the initial 'auto save' execution integrated into our solution') This is to prevent concurrent access to a single entry that we've seen result in data corruption when done in combination with our nested content extension. 

There may be some work that needs to be done to make this entirely generic, but would the community see any benefit in an extension that does this? Is it a moot point for those implementations not using nested content?

Working on tech debt roadmap for 2016, and debating whether or not to add this to the queue!

**Comment by GawainLynch** [comment]
This is probably excellent for targeting v2.2 as an extension, and depending on what lands wrt nested content in the 3.x series might be worth assessing for core later on.

**Comment by SahAssar** [comment]
This has been brought up a couple of times (#3542 is along the same lines), and would definitely be a plus to have. Personally I'd love for it to be available as an extension :)

**Comment by SahAssar** [comment]
This feels like it would be better served as an extension than as a core feature. If anyone feels it should be in core please feel free to comment/reopen! 

Closing as part of the cleanup.

**Comment by GawainLynch** [comment]
For the record… I am :+1: on this as a core feature

… but I would still like to see it land as an extension or feature branch first.
