### ISSUE TITLE
Sessions not working in 3.0-alpha2

### ISSUE THREAD

**Issue by shamotj** [bolt/bolt#4694]
I installed  version 3.0-alpha2 on local server. I couldn't pass form creating first user, always get "CSRF token is invalid.". I checked session cookies and there were none. Then I tried latest stable release 2.2.16 on the same machine with the same virtual host config etc. and it works. I can see session cookies and everything works. Seems like 3.0-alpha2 won't save any session.

I'm using NGINX and PHP 5.6.

**Comment by GawainLynch** [comment]
The problem is your PHP configuration. First thing to check would be what your `session.save_path` is in your `php.ini` file and ensure the target is writeable by the PHP-FPM user/group.

We now don't use the built-in native PHP session handler, to properly enable the use of Redis, or Memcache(d) and the like. As a result, some of the flexibility of the native C has to be worked around.

**Comment by shamotj** [comment]
My <code>session.save_path</code> is set to Debians default <code>"/var/lib/php5/sessions"</code> and it is writable and  working. I have other projects on that server and sessions are  working just fine.

I think problem is somewhere else. I will check if session options are set correctly in SessionProvider.

**Comment by GawainLynch** [comment]
Cool :+1: 

A number of us are running up-to-date master on Nginx and PHP 5.5 though 7 without issues. That said, we have seen this pop up for people, what I described has always been a factor.

Also please note that other things working is largely irrelevant, as we are not using the native session handler any longer.

**Comment by shamotj** [comment]
OK I found the problem. It was wrong <code>cookies_domain</code> setting. I had it empty so application tried to construct it from server host. However our local dev server is running on port 88 and not 80 so the domain was wrong. I set correct domain in config.yml and it is working now. 

So I'm closing this issue and consider it resolved. Thanks for help.

**Comment by GawainLynch** [comment]
Ah cool, and thank you for having a thorough look. I totally didn't think of this one as a cause too :grin:
