### ISSUE TITLE
Allow minifying JS and CSS on the fly. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#47]
Using either: 

 - Munee: https://github.com/meenie/munee
 - Minify: http://code.google.com/p/minify/

**Comment by bobdenotter** [comment]
Because we shouldn't be reinventing the wheel: Should we do even do this? Isn't Grunt/Gulp better suited for this?

**Comment by GDmac** [comment]
The question is, should Bolt core make that decision or offer that feature, or put it in an extension?

For the distribution is with the compiled-css and javascript files. When you work on core css, you should be able to use any tool you want, the compiled files go into the distribution. Again, if you want to offer on-the-fly compilation, i'ld ask if this is a core bolt feature or an extension.

**Comment by bobdenotter** [comment]
Spring cleaning! This should be an extension, or it should be handled in your Grunt/Gulp workflow.
