### ISSUE TITLE
Repeater field problems

### ISSUE THREAD

**Issue by d-m-** [bolt/bolt#4703]
Hi again!

There is still some problematic behavior of repeater fields:

* Sometime it appears that the repeater field overwrites the id of the parent object. Apparently, this occurs using `app.storage.getRepository('somecontenttype').findBy()` but not  `app.storage.getRepository('somecontenttype').findOneBy()` (?)
The `somecontenttype` object then has the id of the last fetched row from bolt_field_values.
 I think that in the first case the generated SQL does not contain the GROUP_CONCATs, maybe this is related... 
* Right now, having multiple repeater fields results in completely redundant joins (in part due to my fix #4693), making queries extremely slow. I guess it would be best to fetch all field_values only once.
* Repeater fields with underscores in their name do not work

I'd be happy to work on these issues, but maybe you have some clues where to look for problems, as I do not fully understand the storage/ORM layer.

Cheers!

**Comment by d-m-** [comment]
A small update concerning point 2:

Fetching records with multiple repeater fields is working fast and memory efficient using {% setcontent %} (with access to the repeater fields introduced in #4726). In the backend, the problem remains. I guess this is related to the use of the old content objects?

Real world example, record with 4 repeater fields:

template: ~ 10MB, 150ms
backend: ~ 1GB, 14s

**Comment by SahAssar** [comment]
Closed since reported fixed in dev meeting :)

**Comment by SahAssar** [comment]
More info will be available here in an hour or so: https://github.com/bolt/bolt/wiki/Dev-meeting-2016-03-01
