### ISSUE TITLE
addJavascript inserts javascript where ever the last insertion was

### ISSUE THREAD

**Issue by jeffpfoster** [bolt/bolt#4705]
-Version of bolt: 2.2.16
-All browsers reproduce the error
-Install via curl command (fresh install just to test the issue)
-Steps to reproduce:
  --Fresh install
  --Install CodeHighlightBolt 
  --Modify template for entries to include highlight() around entry body ouput
  --Create entry that should have code highlighted in it
  --Open browser debug console and see error (hljs not defined)
  --Inspect code:  addJavascript is including the file after the snippet which is called later

Installed extension and get an error in the console.  Looking at the code initializing the call it appears the snippet is getting added before the javascript file.  Changing the afterjs to afterhtml or afterbody doesn't change the output.  The snippet always displays before the highlight.pack.min.js as seen below the initialize function.  I'm not sure if the bug is the addSnippet not respecting the placement argument or if the initialize function uses the first write as the insertion point for later writes. 

    /**
     * Initialize Code Highlight. Called during bootstrap phase.
     */
    function initialize()
    {

        // Add javascript file
        $this->addJavascript("assets/highlightjs/highlight.pack.min.js");

        // Add CSS file
        $theme = $this->config['theme'];
        $this->addCSS("assets/highlightjs/styles/" . $theme . ".css");

        $snippet = "<script>hljs.initHighlightingOnLoad();</script>";

        // Add string snippet to endofbody
        $this->addSnippet('afterjs', $snippet);

        // Initialize the Twig function
        $this->addTwigFunction('highlight', 'twigHighlight');

    }

Resulting html:

```
<script src="/test/theme/base-2014/javascripts/app.js" async="" defer=""></script>
<script>hljs.initHighlightingOnLoad();</script>
<script src="/test/extensions/vendor/royallthefourth/codehighlightbolt/assets/highlightjs/highlight.pack.min.js"></script>
```

**Comment by jeffpfoster** [comment]
Changing the ordering of the addJavascript call or the parameters doesn't change the output:

        // Add javascript file
        $this->addJavascript(
                'assets/highlightjs/highlight.pack.min.js',
                        array('late' => false, 'priority' => 10)
        );

**Comment by jeffpfoster** [comment]
Digging into it further.  I discovered that installing the GoogleAnalytics extension cause the output of the addJavascript to write under the google analytics insertion point.  So it appears the bug is that addJavascript adds were ever the last insertion was and the documented methods for changing that don't appear to work.

**Comment by bobdenotter** [comment]
Closing this. Many things have changed in Botl 3.0, and as far as i can tell, it works correctly now. 

Feel free to re-open, if this remains an issue.
