### ISSUE TITLE
Date in repeater throws an error

### ISSUE THREAD

**Issue by parijke** [bolt/bolt#4706]
I have made a repeater with a date and added this to the entries content type . After filling in two dates and trying to save the item, an error is thrown:

Doctrine \ DBAL \ Types \ ConversionException
HELP
Could not convert database value "" to Doctrine Type date. Expected format: Y-m-d

I entered the info as 2011-01-01 and so on

**Comment by GawainLynch** [comment]
Fixed in #4739
