### ISSUE TITLE
isallowed template function behaviour

### ISSUE THREAD

**Issue by guidsen** [bolt/bolt#4707]
At the moment when you use `isallowed("contenttype:asdasd:view")` where `asdasd` is a contenttype that doesn't exists, the function still returns `true`. I'm not sure if this is intended behaviour, but it would be easier to just return `false`, because it doesn't make sense to return `true` if the contenttype doesn't even exists. Therefore we always need to have another statement to check if the contenttype exists.

**Comment by bobdenotter** [comment]
Thinking about this again: You're not using this in the frontend of a website, are you? ;-)

**Comment by guidsen** [comment]
Yes I am. I'm using it to have conditional menu items based on the
permission.

Op zo 17 jan. 2016 om 14:05 schreef Bob den Otter <notifications@github.com>

**Comment by bobdenotter** [comment]
Strictly speaking, you really shouldn't be using "backend permissions" to do stuff in the frontend. You'll need to have users log into your backend, to see certain things on the site, which isn't good practice. 

It will work though, but it's hackish.

**Comment by guidsen** [comment]
Well it's more about the logic behind it, not specifically about the use-case.. It just the fact of returning true when the resource doesn't exist. It's pretty common to have your front end dynamically to the kind of user. Why would you want people to login in the dashboard to view specific pages? Many times you have some kind of content that is only available for specific roles.

**Comment by bobdenotter** [comment]
> Well it's more about the logic behind it, not specifically about the use-case.. It just the fact of returning true when the resource doesn't exist.

Yes, I agree on that part. That's why it's now fixed in #4713. :-)
