### ISSUE TITLE
[RFC] We need a `{{ outputfields() }}` for outputting all fields.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4714]
Currently, our `record.twig` has a bunch of boilerplate to basically output each field sequentially. When we have 'repeating fields' in, this will only increase. 

At the same time, I've often seen people use the default `record.twig`, and the code in there is fugly.If we have a Twig tag to do this, we could clean up this mess in the `record.twig` templates, and open it up for use to more people. 

(I'm not too happy with the name `outputfields()` though. Any suggestions?)

**Comment by GawainLynch** [comment]
What about just `{{ fields() }}`

**Comment by bobdenotter** [comment]
An analogy for this is Symfony Form's `{{ form_widget(form) }}` tag, which outputs all form fields. You can output each field by hand if you want, or take the easy route and print them all.

**Comment by bobdenotter** [comment]
@GawainLynch Yeah, `{{ fields() }}` would be fine with me.

**Comment by SahAssar** [comment]
Wouldn't it be better to separate it to a macro instead?

**Comment by bobdenotter** [comment]
I thought about that, but I don't think so.. 

 - I want to be able to allow the user to override the used template for the fields: `{{ fields(template='_myfields.twig') }}`
- Or to specify fields to exclude: `{{ fields(exclude='description, image') }}`
- Or to specify what to dump: `{{ fields(use=record) }}`

Doing this as a twig function with named parameters will be much cleaner than a gigantic macro, I think.

**Comment by SahAssar** [comment]
Added in #4722
