### ISSUE TITLE
"Preview" crashes on `thumbnail` or `popup` …

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4715]
… when trying to preview a record that has an image-field with no image specified. See screenshot:

![screenshot 2016-01-17 17 48 41](https://cloud.githubusercontent.com/assets/1833361/12378579/9fb28398-bd42-11e5-9993-cc0291e3cfd9.png)

**Comment by GawainLynch** [comment]
This will be [this](https://github.com/bolt/bolt/blob/master/src/Twig/Handler/ImageHandler.php#L226-L228) not catching an empty string.

**Comment by bobdenotter** [comment]
I found that one, but there's more weird stuff going on.

**Comment by GawainLynch** [comment]
Such as?

**Comment by bobdenotter** [comment]
Like `popup` outputting a broken link. It just needs an additional check in `function popup()`.

**Comment by GawainLynch** [comment]
Ah sweet… You had me worried for a second :grin:

**Comment by SahAssar** [comment]
Fixed in #4716
