### ISSUE TITLE
We need a `{% switch %}` statement in Twig.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4717]
Like this: https://craftcms.com/docs/templating/switch

@see: https://gist.github.com/maxgalbu/9409182

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by GawainLynch** [comment]
Isn't this in Twig extensions?

**Comment by bobdenotter** [comment]
Don't think so? It's not present in Bolt, at least.

![screenshot 2016-01-17 18 42 25](https://cloud.githubusercontent.com/assets/1833361/12378800/18ccf676-bd4a-11e5-88f3-e16681bffd87.png)

**Comment by GawainLynch** [comment]
Ah, no I meant the Composer package [twig/extensions](https://packagist.org/packages/twig/extensions)

**Comment by bobdenotter** [comment]
Looking through the docs: Don't think so.. At least, i don't see it here: http://twig.sensiolabs.org/doc/extensions/index.html

**Comment by GawainLynch** [comment]
Damn… that would've made it *really* easy to do then.

**Comment by SahAssar** [comment]
Fixed in #4718
