### ISSUE TITLE
[RFC] Request: Upload image function into CKEditor

### ISSUE THREAD

**Issue by chloroformiate** [bolt/bolt#4730]
Request: It will be nice to add upload image in CKEditor like this plugins http://ckeditor.com/addon/uploadimage

Also in my dream this will be awsome to have possibility in contentypes.yml to specify folder upload for CKEditor like:

body:
     type: html
     upload: path/myfolder

**Comment by gandalf3** [comment]
It'd be nice if this was possible for the markdown editor as well.

Having to upload images that belong in text through the stack or FTP can often be tedious..

**Comment by bobdenotter** [comment]
If either of you has the time/skill to work on this: Please do, PR's are welcome.

**Comment by gandalf3** [comment]
Good to know :)

I have some time and a definite interest in having this functionality. As for adequate skill . . . well that remains to be seen :P

**Comment by gandalf3** [comment]
I've been slowly poking my way through the code, and it looks to me like it should be as simple as pointing ckeditor at [some php script](http://docs.ckeditor.com/#!/guide/dev_file_browser_api-section-example-4) (or similar) which validates the incoming file, then (strangely enough) returns a `<script>` which runs a CKeditor callback; passing the URL of the newly uploaded file.

Not being familiar with symphony/silex, I'm not sure where this upload handler would best be implemented. If I understand correctly, the requirement of a `<script>` being returned seems to rule out using `src/Controller/Backend/Upload.php`, at least in its current form.

Is there any documentation explaining the structure of bolt's internals? Or at least some suggestions of where/how to integrate a ckeditor-specific upload handler?

**Comment by SahAssar** [comment]
Gonna close this, it'd be nice to have, but keeping this open isn't helping. PR's to implement this are very welcome though!
