### ISSUE TITLE
Named arguments in Twig macros

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4738]
Since version 1.12 Twig has support for [named arguments](http://twig.sensiolabs.org/doc/templates.html#named-arguments), but when I tried to use it in my template like this:
````twig
{{ news.column(title='Analytics', count=1, category='analytics') }}
````
I've got an error:
>Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",") in "index.twig" at line 52.

I've looked into dependencies and found that Bolt uses Twig ~1.16, so this feature should be available.

**Comment by SahAssar** [comment]
I thought that named arguments was only implemented for functions, not for macros? See twigphp/Twig/issues/929

**Comment by C4Grey** [comment]
@SahAssar Understood now, thanks.

**Comment by SahAssar** [comment]
Btw @C4Grey you can replicate this by passing an array, as ninsuo showed in that thread:
```
{# main.twig #}
{% import 'macros.twig' as test %}
{{ 
  test.myMacro({
    'hello': 'world',
  })
}}

{# macros.twig #}
{% macro myMacro(options) %}
  {% 
    set defaults = {
      'hello': 'bob',
      'foo': 'bar',
    } 
  %}
  {% set options = defaults|merge(options) %}
  {{ options.hello }} {{ options.foo }}
{% endmacro %}
```
