### ISSUE TITLE
Relation format (in v3) doesn't work

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4744]
this line 
https://github.com/bolt/bolt/blob/master/app/view/twig/editcontent/fields/_relationship.twig#L4
```twig
{% set format = context.content.relation.format|default("{{ title|escape }} (№ {{ id }})") %}
```

should be done as here:
https://github.com/bolt/bolt/blob/release/2.2/app/view/twig/editcontent/_relationships.twig#L17
```twig
{% set format = relation.format|default("{{ item.title|escape }} <span>(№ {{ item.id }})</span>") %}
```
Or i don't know the plan of copying the while `/fields/_relationship.twig` to `/_relationships.twig' as done in v2.2.

Also in v3 it gives only `id` and `title` variables into format template, so v2.2 relationship selectbox is more perfect
```twig
<option value="{{ item.id }}"{% if item.selected or selectedbyrelation %} selected{% endif %}>
    {{ format|twig({'item': item}) }}
</option>
```

**Comment by bobdenotter** [comment]
This is fixed in #4843.
