### ISSUE TITLE
Select from server - not working

### ISSUE THREAD

**Issue by anteatersa** [bolt/bolt#4745]
Just installed the latest stable version (2.2.16) and cannot select any files using the "Select from server" function in image, imagelist or file fields.

The modal window pops up but when you click it closes and nothing happens. Looking at the source for a single link I can see that one of the function arguments is blank e.g.:

    <a href="#" data-action="Bolt.stack.selectFromPulldown('', 'bell-bills-cash-register-2738.jpg');" class="file">

**Comment by SahAssar** [comment]
@anteatersa Could you check the JS console in your browser if there is an error defined? Also, could you perhaps post the contenttype that you are editing when this happens (since it uses the field key to populate that field)?

**Comment by anteatersa** [comment]
Hi, I did have a look at js console but no errors. 

I am testing on the default Showcase contenttype (but have tested on page and blog too) and looking at the first image field in the media tab. But I see the same behaviour in all select from server popups.

The field has the id of: field-image

This is the html for the "Select from server" button on the first image field:

    <button type="button" class="btn btn-tertiary" data-target="#selectModal-image" href="/async/browse/files?key=image" data-toggle="modal">
            <i class="fa fa-download"></i>
            Select from server
        </button>

Where is the JS to set the first argument for the selectFromPulldown after the /async/browse/files?key=image page has loaded?

**Comment by SahAssar** [comment]
@anteatersa It's set in twig here: https://github.com/bolt/bolt/blob/release/2.2/app/view/twig/files_async/files_async.twig#L57

It's weird because I just tried this on a 2.2.16 install and it works for me. Could you try in a different browser and in incognito/private mode so that we can know that this is not a browser/extension issue?

**Comment by anteatersa** [comment]
Just tested in incognito mode, same problem. 

Also deleted the sqlite database and tried from a new page but same problem. Everything else works perfectly "Upload image" or "Select from stack"

**Comment by anteatersa** [comment]
I installed bolt onto a new server and it all works fine so there is another issue maybe with the PHP version?. The server with the problem is running 5.3.3-7

**Comment by anteatersa** [comment]
Please close this bug. Problem was caused by the url rewrites on my server not passing the GET variable 'key=image' properly to bolt.

**Comment by SahAssar** [comment]
@anteatersa Great :)
