### ISSUE TITLE
Upload attempts to only upload over non SSL when on an HTTPS site

### ISSUE THREAD

**Issue by jeffpfoster** [bolt/bolt#4747]
Strict Transport Security violation: Setting your site to only allow https traffic the backend doesn't follow how the site was loaded.  For example: visit https://example.com/bolt/ and try to upload to the stack from the dashboard page.  You will get an error of mixed content as the upload attempts to load http://example.com/upload. 

Version: 2.2.16
Tested on Chrome

**Comment by jeffpfoster** [comment]
Additional note:
The file management upload section will still upload the picture but it generates a thumbnail but when trying to view the image, it displays the 404 image.

**Comment by SahAssar** [comment]
Hey @jeffpfoster 

What server are you using? If you are using nginx it my be that you have set "fastcgi_param HTTPS" to off in your config, many example configs come with it set to off.

**Comment by jeffpfoster** [comment]
Looks like it was the nginx setting.  I figure it must be a setting somewhere cause I inspected the code for that button and it didn't look like it was stuck to either protocol.  I tried the force ssl on the config.yml but no luck.  Thanks for realizing the issue.
