### ISSUE TITLE
Add `postlabel` hint to field in contenttypes

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4751]
Often i need something that has to be written below label but above field. Sometimes my clients don't see important note if it's below text input. So can we add "postlabel" option for the field?
### Demo
*postfix:*
![2016-01-26 13-08-14](https://cloud.githubusercontent.com/assets/2145313/12574484/5b674fa0-c42e-11e5-8ca5-224584b6bf19.png)

*postlabel*:
![2016-01-26 13-11-57](https://cloud.githubusercontent.com/assets/2145313/12574467/4cd55dce-c42e-11e5-94ba-87bfb9bc61d7.png)

p.s.
Label is escaped, and also putting gint to label is not proper way (hint and label have different senses). Some magic with empty label and filled prefix is non-elegant solution.

**Comment by GawainLynch** [comment]
Next, the `postman` option… which means we should then have the `postwoman` option, which would also require the `postother` option :stuck_out_tongue_winking_eye:

**Comment by Boorj** [comment]
`postchild` is nice :baby:

**Comment by Boorj** [comment]
Actually, call as you wish. But in most cases i thought hundred times that suffix (or postfix) position between label and input is much better.
And also now postfix is **too far** from field and an eye can't understand, what is the parent :man: of hint - field above or field below (read: *reduce the space between postfix and input*)

**Comment by bobdenotter** [comment]
@Boorj Please, please take the time to learn how to do PR's.. A lot of your suggestions (like this one) could've been in the source code for months now, if you made the PR's. Just shooting in a whole bunch of suggestions, while you know we're already short on time, isn't nearly as effective.

**Comment by SahAssar** [comment]
So we currently have `label`, `postfix`, `prefix`, right? I'm not against adding another per se, but perhaps we should consider what fields would be reasonable to add once and for all (if that is at all possible..).

**Comment by SahAssar** [comment]
I don't really see the value of this, we already have three (five with `description` and `placeholder`) places to put informational text about fields... It shouldn't be hard to implement if anyone really needs it, so let's see if that happens. Closing, feel free to reference from a PR if/when it lands :)

**Comment by Boorj** [comment]
IMHO the postfix is the best way to explain something to non-dev users.
