### ISSUE TITLE
Add GD check in install

### ISSUE THREAD

**Issue by geggleto** [bolt/bolt#4757]
First time user of Bolt.

I ran into a problem where my server did not have php-gd installed.
It would have been nice if the installation procedure had of pointed that out, instead of me noticing it post install.

Seems like it could be a small little change that would help out new users.

Cheers!

**Comment by bobdenotter** [comment]
:+1:

**Comment by SahAssar** [comment]
This is sorta related to #4712 so I'm just gonna leave this here :smile:

**Comment by geggleto** [comment]
I am all for contributing ;) if you guys want to help me out with some basic stuff around your code base :)

**Comment by GawainLynch** [comment]
@geggleto help is always welcome

**Comment by CarsonF** [comment]
[bolt/thumbs](https://github.com/bolt/bolt-thumbs/blob/master/composer.json#L19) requires it

**Comment by geggleto** [comment]
In my particular case, I could not run a composer install because my VPS does not have enough ram ;)

**Comment by bobdenotter** [comment]
Fixed by #4881.
