### ISSUE TITLE
"Unlisted" status for content

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4760]
GMO is having a problem where they want to have a _live_ link (for testing with other systems / external reviewing), but we don't want it to be _published_.

The solution I had is an _**unlisted**_ status, where routing directly to the link is allowed, but it is not shown on listing pages, related articles, or taxonomy pages.

Thoughts?

**Comment by SahAssar** [comment]
Sorta related to #4077 :)

**Comment by PhillippOhlandt** [comment]
Seems much easier to do than a shareable link with a token or other stuff. I like the idea.

**Comment by GawainLynch** [comment]
Ha… You're going to love me for this one… not!

But why not an extension with a controller that returns a 404 for content looks ups that don't have `x` value in `y` field?

**Comment by CarsonF** [comment]
In what field? And the other idea is the link doesn't change once the item is _published_.

**Comment by GawainLynch** [comment]
> In what field?

Pick one, assign via config… options exist.

> And the other idea is the link doesn't change once the item is published.

That makes sense :+1:

**Comment by CarsonF** [comment]
Less "magic" the better. That kinda feels like magic.

**Comment by bobdenotter** [comment]
We've solved this in the past with an extension: Have the extension listen to `/preview/entry/1234?key=666DECAFBAD`, and the controller just renders and shows the page, even if it's not published. 

If the record in question _is_ published in the meantime, the controller in the extension could just `301` to the `$record->link()`.

**Comment by CarsonF** [comment]
Problem is the link is put into a mailing service. So that key would go out to everyone. Mind as well publish it at that point. That's a good thought though!

**Comment by SahAssar** [comment]
@CarsonF Is there some version/milestone that you think is realistic to get this done? Not to pressure, but I'm trying to get an estimate on what we can assign and what milestone we can sorta assign it to when it comes to the current issues. That is if it's still something that is wanted in bolt core.

**Comment by CarsonF** [comment]
Bigger fish to fry right now. Still I think it's a useful feature.

**Comment by SahAssar** [comment]
Right, while I agree that this might be a usable feature, it does not seem to be either critical or have anyone working on it. I'm going to close this , and if there is interest and work on it please reopen! :)
