### ISSUE TITLE
Bug in mailservice provider

### ISSUE THREAD

**Issue by geggleto** [bolt/bolt#4764]
This should go along with code styling... but

https://gist.github.com/geggleto/04f187024efe25ca315d

This is why you do not do assignments in if statements :)

https://github.com/bolt/bolt/blob/master/src/Provider/MailerServiceProvider.php#L29

**Comment by GawainLynch** [comment]
> This is why you do not do assignments in if statements :)

Highly dependent IMHO :grin: 

Fixed in #4765

**Comment by geggleto** [comment]
Bhahaha ;) its so easy to forget to wrap in () @GawainLynch :P better to be safe than sorry. Be a good coder and wrap your if assignments ;) tgif.
