### ISSUE TITLE
The "permalink preview" is not accurate.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4767]
The "permalink preview" when editing a record is _always_ just `/{contenttypeslug}/{slug}`, regardless of what's configured in `routing.yml`. 

It should use the correct route, to display an accurate 'permalink'. 

![screenshot_2016-01-28_21_00_13](https://cloud.githubusercontent.com/assets/1833361/12657180/4f4c88a4-c602-11e5-968f-a4f66dafa63f.png)

**Comment by bobdenotter** [comment]
See #4766 for a hackish, temporary fix.

**Comment by evertalbers** [comment]
Is it possible to make the total '/contenttype/slug' url copy-able?

**Comment by SahAssar** [comment]
Perhaps something we should tackle at the same time/way as #2714...

**Comment by GawainLynch** [comment]
Moving to 3.5, same deal :wink:

**Comment by SahAssar** [comment]
This one I actually wanna keep open... Feel free to disagree :)
