### ISSUE TITLE
Paging throws an warning

### ISSUE THREAD

**Issue by parijke** [bolt/bolt#4772]
When using base-2016, having multiple showcases. Going to the next page 
`showcases?&page_showcases=2`

gives this message
( ! ) Warning: Missing argument 1 for Bolt\Application::{closure}() in /home/paul/www/bolt3/vendor/pimple/pimple/lib/Pimple.php on line 122

**Comment by SahAssar** [comment]
Hmm, I can't recreate this, did you set this up in any special way?

**Comment by SahAssar** [comment]
Sorry, Closing this since it's been a week an no additional info on recreating this... If you are still experiencing the issue and have more info please reopen! :)
