### ISSUE TITLE
Nut commands don't work with custom directories ([RFC] ?)

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4780]
### Problem
Sometimes people want to change the structure of their projects. Bolt has nice possibility to customize folders (cache, thumbnails, database, config). Some issues are with `files/` directory (since it's coupled with filesystem in some code parts), but in general: if set folders in index with '$configuration->setPath' it works ok.
But when launching Nut commands it still uses default directories from `\Bolt\Configuration\ResourceManager::__construct`.

### Solution
We discussed that once, and that was sort of a problem of an egg and a hen, but.. Probably we could make a `CustomProjectPaths.php` that is included both in `index.php` and in nut's `bootstrap.php` and performs merging of default paths list and user custom paths. 

### Profit
* System will have much better flexibility.
* Once refactored the system to this solution, we'll get rid of many possible hardcode parts.

##### Comment
Actually, having custom paths sometimes is a hell now, you don't know where the problem will appear from next time. For me (imho) it's convenient to have all project source files in one folder: business logic, configurations, translations, assets. And bolt's files - in another folder (database, cache, log, nut, extensions). That's why i really want to vanish all problems with custom paths.

**Comment by Boorj** [comment]
###### feel free to close it if
solution duplicates #4406 , but @CarsonF told in #4590 to report all weird behaviour.
Seems that i'm that test guy who has both composer install and custom directory structure, and pays his time for discovering of all imperfections in code.

**Comment by CarsonF** [comment]
@Boorj How are you doing a custom directory configuration without using your own `bootstrap.php / index.php` file?

**Comment by Boorj** [comment]
i'm doing it with `index.php` injections. I have a class that provides some custom logic and path settings.

**Comment by GawainLynch** [comment]
Nut just gets it's paths from the same place as the rest of the application, if your path overrides aren't done properly then that will cause you issues.

**Comment by Boorj** [comment]
it takes me to create `cache`, `theme`, `theme_default` and other directories to make nut work (Actually i didn't make it work).. Is it ok?  Theme directory is set inside `config.yml`, maybe we can put directory structure there too? And feed `index.php` and `nut.php` (bootstrap) with this config? IT could solve hen/egg question.

**Comment by Boorj** [comment]
So now i have whole collection of issues that claim to have one file with custom paths configuration , that could be used in:
* `index.php` on application run  (#3594)
* `script handler` on composer update/install (#4406)
* `bootstrap.php` for nut commands (this issue)
It will allow users to set their own structure without having problems.

**Comment by SahAssar** [comment]
I'm probably just way off on this, but have you looked at how the multisite config does it? There the bootstrap.php with the custom directories config is "fed" to both nut and index.php.

**Comment by Boorj** [comment]
@SahAssar , thanks. Are you talking about [this](https://docs.bolt.cm/howto/muti-site-setup) or  [this](https://gist.github.com/GawainLynch/33e992a567ef84cfee3c) ? Yes, i think that could solve the problem, but.. it's kinda "illegal".. It's being overwritten each time i update bolt. Actually, i'm using composer install, so i have to copy manually changed .php-files from `vendor/bolt/bolt/app/` to my `root/app/nut`

So problems with this solution are:
1. [`ScriptHandler`](https://github.com/bolt/bolt/blob/master/src/Composer/ScriptHandler.php) also has to support this file, since it creates some extra directories and perform other operations with that.
2. Changes in bolt repo need to be supported manually
3. Weakest problem: PHP is very handsome solution, but probably it could be solved in more elegant way. Maybe YAML or something.. But it's optional.

**Comment by SahAssar** [comment]
@Boorj Those two are the same, it just started out as a gist and then got included in the docs.

I don't have a way forward for your other issues though... My bolt install is in a completely separate folder (and not a composer install) so I haven't had those issues.

**Comment by GawainLynch** [comment]
Fixed in #5069
