### ISSUE TITLE
'CSRF token is invalid' creating first user

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#4781]
In a fresh install of cloned master can't create first user with that message above.

Cache and cookies has been cleared.

**Comment by rixbeck** [comment]
I was trying to disable CSRF protection temporarily in `createFormBuilder()` options. Then Login form has blocked me, with unable to login. I was trying to understand what happens here, but we are not close friends with forms... :-(

**Comment by GawainLynch** [comment]
You can get this to happen, and the behaviour is correct in this case, if there was a previous install at that host name/path combination and a session cookie is still set.

**Comment by rixbeck** [comment]
All cookies - included session cookies - has been cleared, no cookies set in request header.

**Comment by bobdenotter** [comment]
This should be fixed, now that the new CSRF branch has landed. 

Feel free to re-open this issue, if the problem persists after updating Bolt.

**Comment by rixbeck** [comment]
Related to #5114
