### ISSUE TITLE
Not root-account can't upload images

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4789]
looks the same as #4241 

When this user is uploading:
![2016-02-02 15-19-19](https://cloud.githubusercontent.com/assets/2145313/12744771/42855d64-c9c0-11e5-8608-85ceb391cf35.png)
it gives
![2016-02-02 15-18-39](https://cloud.githubusercontent.com/assets/2145313/12744776/491c4d40-c9c0-11e5-93c5-30c7dda09d98.png)

when this user does the same:
![2016-02-02 15-19-25](https://cloud.githubusercontent.com/assets/2145313/12744784/530dfad8-c9c0-11e5-9072-c668c8988f63.png)
it gives 302 and returns html back.
![2016-02-02 15-17-51](https://cloud.githubusercontent.com/assets/2145313/12744798/6756fb84-c9c0-11e5-97f5-13faf5ba81b4.png)

**version: v3 master**

**Comment by Boorj** [comment]
developer's permission gives the same.

**Comment by Boorj** [comment]
@GawainLynch can i help to fix this someway? That really causes the problem for all projects on v3, because i have to set root roles to all users...

**Comment by GawainLynch** [comment]
Sure. If you have the time, and can narrow down where the permission check is failing, we can go over potential fixes.

**Comment by archayl** [comment]
It appears that `public function isAllowed($what, $user, $content = null, $contentId = null)` in `src/AccessControl/Permissions.php` having the `$what = upload`. It can't find it in the `config.yml` because it is written in there as `files:uploads`. As for `root` user, it skips the process thus no error.

**Comment by GawainLynch** [comment]
Thank you so much, @archayl … That's a really helpful pointer for a very busy team!

:+1:

**Comment by GawainLynch** [comment]
@Boorj & @archayl I can not reproduce this locally… do either of you have old or custom `app/config/permissions.yml` files?

**Comment by archayl** [comment]
Nope, straight github clone. I'll try reproduce again.

**Comment by archayl** [comment]
Yep, same thing. Replicated on vagrant and DO droplet.

1. Fork bolt/bolt
2. Git clone
3. Checkout master
4. composer install
5. Install using web browser
6. Login as admin
7. Create user 'dummy' with chief-editor role
8.Logout and login as 'dummy'.
9. Click +New Page
10. Click Upload Image.
11. ![permission-error](https://cloud.githubusercontent.com/assets/247152/13032488/9f1870de-d32f-11e5-8193-331a103ab0cb.jpg)

**Comment by GawainLynch** [comment]
Thanks, @archayl … I will keep digging then! :grin:

**Comment by GawainLynch** [comment]
Found… and fix in the queue!

**Comment by archayl** [comment]
@GawainLynch :+1:
