### ISSUE TITLE
Menu function performs unnecessary hydration

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4790]
I've noticed that with time every page on my site become extremly slow, so I spent some time with a profiler and found next:
![image](https://cloud.githubusercontent.com/assets/2578826/12746918/d3bfbdcc-c9a9-11e5-9b37-584a1f4d687d.png)
All my content types somehow are fetching on every page, it is always a few items, but it takes a huge amount of time, especially for the "programs" content type. So I've looked into template parts that used on every page...and found that when I removed the "menu" function call, my pages began to render in 200-300 ms! Indeed, all those huge blocks on the timeline specifies IDs of programs presented as links in a main menu. [This line of code](https://github.com/bolt/bolt/blob/aa99c8e914bdfc9f09e6f41eb049b9d473c4b843/src/Storage.php#L2566) takes all that time.
P.S. I also think that #4672 is related to this issue.

**Comment by C4Grey** [comment]
I've dug into the menu builder and found [this](https://github.com/bolt/bolt/blob/aa99c8e914bdfc9f09e6f41eb049b9d473c4b843/src/Helpers/MenuBuilder.php#L151). I think, it should be an option is settings allowing to disable this. Also, [here](https://github.com/bolt/bolt/blob/aa99c8e914bdfc9f09e6f41eb049b9d473c4b843/src/Helpers/MenuBuilder.php#L177) definitely should be something like
````php
$content = $this->app['storage']->getContent($path, array('hydrate' => false));
````

**Comment by GawainLynch** [comment]
Yeah, I want to rewrite this class for Bolt 3.1… it needs an overhaul.

**Comment by GDmac** [comment]
When (and if) event dispatching gets implemented at the content level (entry save,delete,update,etc) then menu could listen for the event and update its menu when necessary and CACHE it. 

Because of the huge overhead for every menu instance (header/footer) 
i only use hard ``link: /about-page`` instead of dynamic ``path: page/1``

**Comment by GawainLynch** [comment]
> When (and if) event dispatching gets implemented at the content level (entry save,delete,update,etc) 

It's been in for 6 months or more.
