### ISSUE TITLE
Revised process for new base-2016 theme.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4792]
When I was working on the `{{ fields() }}` code to include in the base templates, I came to the realisation that I think we skipped a few steps in the thought-process to come to a new default theme. So, I think we need to take a step back in regards to the new base-2016 theme. In my opinion, we need to think it through a little better beforehand. The current version looks nice, but I have this nagging feeling in the back of my head that we've skipped a few steps in the process, and that if we don't fix those, it will not benefit users in the long run. 

Some thoughts/ideas. All open for discussion:

 - The default theme serves as a first introduction to Theming with Bolt for most people.

 - Even though we don't really intend it that way, a lot of people will use this to get a first site up and running.

 - The theme should be easy to tinker with, and not restrict this more than absolutely necessary.

 - It should be based on a framework. (both to facilitate the tinkering, as well as to not have to write documentation for it ourselves)

 - It absolutely needs to nice and appealling, but it shouldn't be too distinctive. I'd rather have it be "basic and extensible", than "pretty and locked down".

 - On the one hand, it should show a bunch of possible features, but at the same time it shouldn't be too overwhelming. 

 - In the code, we should strive to use _simple_ twig, that's easy to get into. Even if this goes slightly against best practices. 

 - As you might know, my personal preference would be to use Foundation for this: Aimed at frontend code, for frontend-developers. But, that's just me, and I could live with another choice, as long as it's well documented, open source and easy to use. (so, imho the viable candidates are Foundation, Bootstrap, Materializecss or even Skeleton or ResponsiveBP)

When it comes to the actual implementation, some points: 

 - I think we should actually draw up some wireframes to discuss what's going on with the theme. If we do this before we start actually coding the things, it will help _us_ formulate more clearly what we want to achieve with the default theme. Afterwards, it could also be good to have as actual documentation of how the theme is structured to newcomers to Bolt. 

 - We should set up a "three step" Sass -> CSS workflow. We should have a gulp script that builds two CSS'es: `foundation.css` and `theme.css`. The `foundation.css` contains whatever we used from the framework, but yields an otherwise very bare-bones layout. The `theme.css` should have all the overrides, and specific theming to make it look nice. 

 - People can then choose what they want to muck about with:
   - Modify stuff directly in the `theme.css`, for CSS beginners, or people who "don't get sass".
   - Build their own CSS on top of `foundation.css`, theming the *structure* of the default theme
   - Make changes in the foundation output, and/or replacing the thing entirely, if they want to do so. 

 - I'd like to have some sort of 'pluggable' features for it too. "Need a caroussel? set this-and-that, and you're good to go!" I'm not yet sure how that would work in practice, though.

**Comment by SahAssar** [comment]
Agreed on most of it, but some things like
> I'd like to have some sort of 'pluggable' features for it too. "Need a caroussel? set this-and-that, and you're good to go!" I'm not yet sure how that would work in practice, though.

might be better to have as simple extensions that we have tested with the theme. Simpler is better in the default I think.

**Comment by bobdenotter** [comment]
> might be better to have as simple extensions that we have tested with the theme. Simpler is better in the default I think.

Or macro's?

**Comment by SahAssar** [comment]
closed since the new base-2016 is now merged
