### ISSUE TITLE
"White screens of death" in PHP7.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4797]
Bolt on `master` on specifically PHP 7 will sometimes give a white screen of death. No errors on screen or in the logs, regardless of `display_errors` and `error_reporting` settings.

(One of) the culprit(s) is Monolog. There's a newer `dev-master` version that fixes this. However, this is PHP 7 **only**, which is a major issue. 

We can probably "fix" this by requiring `"monolog/monolog": "~1.17|dev-master",`, so on a `composer update`, you'll get the version for your installed PHP. This is a major concern for releasing a packaged version, though. :-/

~~For the time being, it seems `"monolog/monolog": "1.x-dev",` will do the trick as well: It's not the latest and greatest, but at least it works on both PHP 5.5 and 7.~~ Scratch that. No it doesn't. Problem still very much a problem.

**Comment by bobdenotter** [comment]
See #4798 for preliminary fix.

**Comment by GawainLynch** [comment]
Can you please check Monolog 1.18.0 as that probably closes this

**Comment by bobdenotter** [comment]
I will

**Comment by bobdenotter** [comment]
Did some monkey-testing, and I can't reproduce anymore after updating to monolog 1.18. Closing for now!
