### ISSUE TITLE
Show random content in a loop

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#48]
It would be handy if there was some kind of "random" sort option in a loop: get random items of a contenttype and exclude the active one.

**Comment by Maelstrome26** [comment]
For people finding this out, the functionality has changed to:

`orderby 'RAND()'`

Example:

`{% setcontent testimonials = 'testimonials' where { status: 'published' } orderby 'RAND()' %}`

**Comment by SahAssar** [comment]
Nudge nudge: https://docs.bolt.cm/3.0/templates/templatetags#setcontent
