### ISSUE TITLE
500 error and Bolt - Fatal Error at install

### ISSUE THREAD

**Issue by Puddingboy** [bolt/bolt#4800]
at install I get the following:
PHP Fatal error:  Call to undefined function Bolt\\mb_internal_encoding() in /var/www/http_development.xpertdata/app/bootstrap.php on line 20

after removing lines, I get the following error.

Fatal error
/var/www/http_development.xpertdata/app/cache isn't writable while it is set t 777 so it should be writable

Where do I start fixing this?

*Edit: All mentioned files have been set to 777.

**Comment by GawainLynch** [comment]
You need to install/activate the `mbstring` PHP extension. It should be included in a base PHP install, but not acttivated in your environment.
