### ISSUE TITLE
Whoops! v2 breaks AJAX error reporting/handling

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4801]
With `debug_enable_whoops: true`

![screenshot from 2016-02-04 07-52-10](https://cloud.githubusercontent.com/assets/1427081/12808038/535690fe-cb14-11e5-9d39-afb81957117b.png)

**Comment by CarsonF** [comment]
See if https://github.com/CarsonF/bolt/tree/bugfix/whoops fixes it for you. I just tried (very quicky) to reproduce it and couldn't. Other than that content-type header change. Probably totally off :)

**Comment by GawainLynch** [comment]
…and now, I can't reproduce it either… :frowning:

**Comment by GawainLynch** [comment]
Closing as I just can't get it to happen any longer
