### ISSUE TITLE
Incorrect directory separator in extension assets path

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4802]
There's problem with directory separators.
![2016-02-04 13-44-45](https://cloud.githubusercontent.com/assets/2145313/12808968/5144110c-cb45-11e5-9d2f-90dcdbe8e840.png)

![2016-02-04 13-41-01](https://cloud.githubusercontent.com/assets/2145313/12808927/dd85217a-cb44-11e5-8c65-0f44969ce664.png)

getAssetPath function returns path, taken from extension's json, and it has backslashes in its path string. So it returns:
![2016-02-04 13-24-39](https://cloud.githubusercontent.com/assets/2145313/12808640/93e582aa-cb42-11e5-87d0-4827fecc67d1.png)
(example of how it **is now** and how it **has to be**).

So [here in AssetTrait](https://github.com/bolt/bolt/blob/master/src/Extension/AssetTrait.php#L255) we can use
```php
return str_replace('\\', '/', $this->getRelativeUrl()) . $fileName;
//instead of 
return $this->getRelativeUrl() . $fileName;
```
which fixes the problem. But also it could be fixed in other places, depending on what is the purpose of 'path' usage.
Probably
- [here in Extension\Manager](https://github.com/bolt/bolt/blob/master/src/Extension/Manager.php#L216) 
- or [here in PackageDescriptor](https://github.com/bolt/bolt/blob/master/src/Composer/EventListener/PackageDescriptor.php#L128)
- or somewhere [here in Asset Injector](https://github.com/bolt/bolt/blob/master/src/Asset/Injector.php#L220)
- or even directly [in Asset/File/JavaScript.php](https://github.com/bolt/bolt/blob/master/src/Asset/File/JavaScript.php#L21)

I could make a PR (because it fixes my problem), but don't know where to put a fix properly.

**Comment by GawainLynch** [comment]
Ping @CarsonF 

This is a WiP with the new file system layer… the `str_replace` is absolutely the wrong approach.

**Comment by Boorj** [comment]
what happens when we load assets:
![2016-02-04 14-01-32](https://cloud.githubusercontent.com/assets/2145313/12809245/b952ffc2-cb47-11e5-8b0c-54809a30e1e5.png)


![2016-02-04 14-01-05](https://cloud.githubusercontent.com/assets/2145313/12809267/e99da9ca-cb47-11e5-92ae-23acd5e8e279.png)

![2016-02-04 14-00-44](https://cloud.githubusercontent.com/assets/2145313/12809281/002d8e9e-cb48-11e5-99e6-c2f65daa1962.png)


![2016-02-04 14-00-27](https://cloud.githubusercontent.com/assets/2145313/12809293/14ec0036-cb48-11e5-95b4-533fdb24aef9.png)



#### relativeurl story

where do we get RelativeUrl? 

...meanwhile in addManagedExtensions kingdom:

![2016-02-04 13-56-59](https://cloud.githubusercontent.com/assets/2145313/12809340/6feb985c-cb48-11e5-8fc9-f917cfa7e900.png)


So we  are taking path from `vendors/autoload.json`

![2016-02-04 13-55-35](https://cloud.githubusercontent.com/assets/2145313/12809349/81709e74-cb48-11e5-90ae-0ca3020c65fe.png)
![2016-02-04 13-56-15](https://cloud.githubusercontent.com/assets/2145313/12809358/8d045eb0-cb48-11e5-882a-c87490d9b725.png)


when we got  descriptors we add them

![2016-02-04 13-57-08](https://cloud.githubusercontent.com/assets/2145313/12809373/a816b07c-cb48-11e5-87e5-f030de00fb90.png)

When we are adding extension it sets relative url

![2016-02-04 13-58-31](https://cloud.githubusercontent.com/assets/2145313/12809405/efb5d0fc-cb48-11e5-99c7-81e5339ac9aa.png)


![2016-02-04 13-58-16](https://cloud.githubusercontent.com/assets/2145313/12809388/cc01521c-cb48-11e5-9f87-4397e498c875.png)

#### conclusion
Asset url is taken from composer file without any changes. Somewhere in process it could be normalized to normal separators.

**Comment by rixbeck** [comment]
As I remember we were introduced the _academic_ ``Pathogen`` lib to avoid like this. As I see since there are some new ``sprintf()`` and ``::getRelativePath()`` that doesn't use atomized paths. Don't we want to return to use all the paths in atomized way again?

**Comment by GawainLynch** [comment]
@rixbeck the new filesystem layer does away with the need for Pathogen and handles the transformation internally with Flysystem.

We just need to move that into the asset layer as it was introduced **after** the asset loader and we haven't had the time/resources to get to it… and we're not in a stable release cycle with this branch yet.

*"Welcome to Development Branch, patches and patience welcome"* :grin:

**Comment by rixbeck** [comment]
Ah... I didn't know. There's no impatience but I was long time away to follow the trends and was wondering how that problem appearing again. I thought ``Pathogen`` just became a victim of oblivion... - that wouldn't be a miracle honestly - :-)

**Comment by GawainLynch** [comment]
Oh, zero stress. I wasn't saying you were being impatient by the way. Just that there is a lot of "Please do this now!" going around and if we could do it all now, then v3 would be out already :grin: 

…and yeah, saying goodbye to Pathogen won't make me cry.

**Comment by rixbeck** [comment]
Got it, @GawainLynch! Totally agree!
Just for fun... how can be something pathogen thing in our code anyway? eh? :smile:

**Comment by Boorj** [comment]
That wasn't about "please do this now" that was "i can make a patch, where should i put that" :panda_face:

**Comment by GawainLynch** [comment]
Well it kind of is… Hence why I pinged @CarsonF at the beginning, he's got lead on the filesystem work and I want to seek his input first… but the sun is yet to rise in Dallas so he'll be in bed.

**Comment by Boorj** [comment]
thanks @CarsonF ) and don't be upset, @GawainLynch . One day it will be properly fixed.

**Comment by GawainLynch** [comment]
Actually, I am not upset… what the :koala: missed in the stress was URL !== file path. However the place you suggested was incorrect and @CarsonF had the clear mind.

All in all, a win all around… Thank you both!
