### ISSUE TITLE
Pages loading slow. unknown cause(to me)

### ISSUE THREAD

**Issue by Puddingboy** [bolt/bolt#4803]
I am experiencing slow page load times sometimes 5-10 seconds before I get a visable page. I highly doubt that the server would be having capicity issues. I suppose my server is incorrectly configured. Where do I start fixing this?

**Comment by CarsonF** [comment]
We're going to need more info than that. What webserver are you using (njinx, apache, php's builtin webserver)? Which version of php? what database and is it local or remote? how much data is in it? Which version of bolt? etc.

**Comment by Puddingboy** [comment]
PHP 5.3.3 as far as I can remember, apache, local db, only filled with content from the entry filling option. Right now, the issue seems to have itself fixed after asking our IT guy. I'm getting around 400ms in the debugging bar, which is acceptable. I am not sure how fast it is supposed to run. Sorry for not offering this info from the start. I didn't know what info was needed. Would you say 400ms is still slow for pageload compared to how fast it is supposed to be?

**Comment by bobdenotter** [comment]
400ms is pretty much OK. Since you're using a slightly ancient version of PHP, I'm guessing it's not a _very_ powerful server, so I'd say it's acceptable.

**Comment by SahAssar** [comment]
Closing since it seems fixed (though the only real fix is to not use php that is old enough to have grandkids)...
