### ISSUE TITLE
bolt multilanguage

### ISSUE THREAD

**Issue by Puddingboy** [bolt/bolt#4807]
Would it be possible to create an ID for each content automatically so that I can tie every translation to the same id? This way I can make sure that a language change will redirect users to the right page. While multilanguage is still a work in progress, I'd still like to create something that works for me. Do you have any suggestion other than available on this page https://docs.bolt.cm/howto/building-multilingual-websites

**Comment by bobdenotter** [comment]
Please post support questions on the forum: discuss.bolt.cm. :-)

We'd like to keep the issue tracker for actionable issues and bugs with Bolt itself.
