### ISSUE TITLE
Unable to save a record - null templatefields

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4817]
Master branch, having such a problem, while saving a new record:
![2016-02-08 13-51-15](https://cloud.githubusercontent.com/assets/2145313/12880462/2a9ca018-ce6b-11e5-8042-7d7ec3e6abbf.png)

haven't found any solution in history, so created this issue.

**Comment by Boorj** [comment]
maybe you need any parameters that contenttype or system has?

**Comment by bobdenotter** [comment]
We've fixed a bunch of stuff related to templatefields in the meantime, so i'm going to assume this is fixed. 

Feel free to re-open this issue, if the problem persists after updating Bolt.

**Comment by Boorj** [comment]
![templatefield_error](https://cloud.githubusercontent.com/assets/2145313/13702412/a415b98c-e7b8-11e5-84f8-b13b10dfee11.gif)

Version alpha 8. Updated today.

What am i doing wrong?

**Comment by Boorj** [comment]
Here's a static showup
![2016-03-11 18-41-56](https://cloud.githubusercontent.com/assets/2145313/13702451/f27c834e-e7b8-11e5-879d-cadfa0ffaf4e.png)

**Comment by SahAssar** [comment]
@Boorj did you do a database update before trying? Is this on an existing site, or one you set up today?

**Comment by Boorj** [comment]
it's on existing site and database doesn't look like it needs to be updated (no notifications).

**Comment by SahAssar** [comment]
Can you try manually updating the database? As in going to the database update page?

**Comment by Boorj** [comment]
that was my first idea, Svante, but... 
![2016-03-11 19-38-23](https://cloud.githubusercontent.com/assets/2145313/13703513/ddfcc7d2-e7c0-11e5-9c74-878186fe5db9.png)

**Comment by SahAssar** [comment]
Does it happen when you create a new record, or just on existing ones?

**Comment by Boorj** [comment]
On creation

**Comment by SahAssar** [comment]
Cause this is fixed here: https://github.com/bolt/bolt/blob/master/src/Storage/Database/Schema/Table/ContentType.php#L60 but I suppose it could have something to do with the templatefields column changing to being a 'json_array' type in doctrine and that change being ignored because of https://github.com/bolt/bolt/blob/master/src/Storage/Database/Schema/Comparison/MySql.php#L24

**Comment by Boorj** [comment]
I deleted templatefields column and recreated. Now it works (SQLiteDatabaseBrowser corrupts the database, file becomes not-readable by bolt - some doubleprecision issues...)
But still: there should be some checks anyway, probably later it will be crashing again.
