### ISSUE TITLE
Notices. Notices everywhere.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4820]
![ytjr6](https://cloud.githubusercontent.com/assets/1833361/12888173/033e1994-ce79-11e5-89c0-b5b45905c47d.jpg)

![screen shot 2016-02-08 at 15 28 10](https://cloud.githubusercontent.com/assets/1833361/12888099/a705a9a8-ce78-11e5-998e-20bfb7dd940a.png)

This seems to have been introduced in #4811. @rossriley Is this easily fixable?

I have `debug_error_level: -1`, and I see notices *everywhere*.

**Comment by rossriley** [comment]
Yes, sorry... line 280 will just need to do a check that the key exists, so change:

`if ($this->app['storage.field_manager']->hasCustomHandler($this->contenttype['fields'][$key]['type'])) {`

to 

`if (
    isset($this->contenttype['fields'][$key]['type']) &&
   $this->app['storage.field_manager']->hasCustomHandler($this->contenttype['fields'][$key]['type'])
    ) {`

**Comment by GawainLynch** [comment]
Fixed in #4821
