### ISSUE TITLE
Impossible to set a page size for a taxonomy listing

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4822]
Although we can specify a count of entries per page via the "listing_records" parameter, it is impossible to set a different amount of entries in a taxonomy listing template(or, what is necessary sometimes, to set a page size per one taxonomy entry). I don't see a way to make it simply via extension, since a few core features should be re-written...Correct me, if I wrong, please.

**Comment by SahAssar** [comment]
@C4Grey Fix incoming in #4823 :)
