### ISSUE TITLE
Relationships do not show correctly in selectbox

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4830]
The first and last name of my person do not show up when selecting them in the bolt backend.
(More info with Bob, This is a bolt 3 issue.)

![screen shot 2016-02-12 at 11 08 29](https://cloud.githubusercontent.com/assets/5583671/13004001/0b0766e6-d179-11e5-89c0-a8eefda942c1.png)
![screen shot 2016-02-12 at 11 08 48](https://cloud.githubusercontent.com/assets/5583671/13004002/0b1bd388-d179-11e5-92b7-932fe1ea5742.png)

**Comment by anketwokings** [comment]
damnnnn.. koala's are fast this time of year..

**Comment by GawainLynch** [comment]
:koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: 

It's a whole pack of them!

**Comment by bobdenotter** [comment]
Found out that the Array that gets passed into `context` only has 'id' and 'title', because of this: https://github.com/bolt/bolt/blob/master/src/Storage/Repository/ContentRepository.php#L54

Will fix.

**Comment by GawainLynch** [comment]
Fixed in #4843
