### ISSUE TITLE
Animated GIFs support

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#4836]
Hi guys, 
I need support for animated gifs and if I upload an animated gif, it just show the first static frame Any clue please?

        image:
            type: image

thanks in advance

**Comment by SahAssar** [comment]
Hey @tourdefran,

You can of course show the gif, you just can't resize it currently. To show the image just do `<img src="/files/{{record.image}}">`. Support for resizing gifs is hopefully coming *sometime*, but AFAIK it's not exactly a priority.

**Comment by tourdefran** [comment]
Hi @SahAssar 
I see, well, this workaround is perfect right now, thanks for the support!! :)

**Comment by bobdenotter** [comment]
We can't easily add this, because we use GD under the hood, and its support for animated gifs is, well, fragile at best. (or so I've heard)
