### ISSUE TITLE
Error in parsePath throws an error for custom upload folder

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4848]
When the system performs this check
```php
        // Test write access for uploadable fields.
        $contentType['fields'] = $this->setCanUpload($contentType['fields']);
```
here: https://github.com/bolt/bolt/blob/master/src/Storage/ContentRequest/Edit.php#L112
it takes upload paths, set for fields in `contenttypes.yml`. 
So, for example, i have a folder called `'downloads'`, which exists : `/files/downloads`.
So when the algorhythm flows further, it goes to [`setCanUpload`](https://github.com/bolt/bolt/blob/master/src/Storage/ContentRequest/Edit.php#L212) and later to [`checkUploadDirectory`](here: https://github.com/bolt/bolt/blob/master/src/Storage/ContentRequest/Edit.php#L218). The last one performs a check with `\Bolt\Filesystem\Manager::parsePath` function. Which throws an error in this check:
```php
        if (!preg_match('#^.+\:\/\/.*#', $path)) {
            throw new InvalidArgumentException('No mount point detected in path: ' . $path);
        }
```
since it doesn't have any `://` instance, and only `'download'` in my example.

'events' is the name of directory in this example:
![2016-02-15 15-13-57](https://cloud.githubusercontent.com/assets/2145313/13045240/660cec5c-d3fc-11e5-9af6-c965fa0a0c74.png)

I suppose it should be prefixed to files://downloads or something like that.

**Comment by GawainLynch** [comment]
Fixed in #4848 … which is just heading over to Travis' place for an argument now about CI :wink:
