### ISSUE TITLE
Issue with HTTPS and backend (fileupload)

### ISSUE THREAD

**Issue by nthommen** [bolt/bolt#4853]
Hi
Whenever I configure my server (nginx) for HTTPS only I get a problem in the backend since it looks like for a file (image) upload it sends it to a http url which is not allowed by google chrome (not secure). I was not able to find a way to configure it that it sends the file to https://xxxx.com/upload?handler= instead of http. How can I fix it? thanks in advance
<img width="844" alt="bildschirmfoto 2016-02-16 um 03 32 06" src="https://cloud.githubusercontent.com/assets/5330826/13065609/655c83c8-d45e-11e5-95dd-7d8edd6c5697.png">

**Comment by aerth** [comment]
Check out [the config file](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L397)

**Comment by SahAssar** [comment]
Hey @nthommen,

Please try the solution in #4747 and see if that fixes it :)

**Comment by nthommen** [comment]
@aerth I did try that out without any success but #4747 fixed it
@SahAssar thanks so much - that fixed it, fastcgi params was off in nginx
