### ISSUE TITLE
[RFC] Promote "resource contenttype" to first class citizen..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4859]
.. as in, provide a 'blocks' contenttype in `contenttypes.yml.dist`. 

The reason i'm bringing this up _now_, is that I've noticed a LOT of people ask for something like this, and when they are pointed to the relevant Howto docs page, they say "Yes, that's exactly what I need!".

So, for the good of the 'user experience', we should add this now, for 3.0.

**Comment by GawainLynch** [comment]
Nike!

**Comment by PhillippOhlandt** [comment]
Sure, do it! :)

**Comment by dystalsolutions** [comment]
Yes! I agree for the good of the user!

**Comment by sbonardt** [comment]
Yes, useful for almost any website and definitely 'first class citizen' worthy.
:+1:

**Comment by PhillippOhlandt** [comment]
As long as my Required record extension is mentioned somewhere in a comment :) (its useful for everyone :runner: )

**Comment by GawainLynch** [comment]
> As long as my Required Records extension is mentioned somewhere in a comment :) (its useful for everyone
:octopus:

**Comment by bobdenotter** [comment]
Fixed in #4867
