### ISSUE TITLE
Default listing template shows wrong url

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#4860]
I use the default listing template to output the headings of a specific category. The main title is the name of the category. But the url's of the entries are something else than supposed. For example:

- I have an entry with the url /poem/poem1
- Instead of that, Bolt puts out /blog/poem1

When creating the content, I only selected 'poem' as the category to save in. I do have a category 'blog' (but didn't select that when saving the entry). Bolt puts out the wrong url on the listing page. When I click on a title, Bolt redirects me to the content, but the url is wrong and I don't want that. What am I doing wrong?

**Comment by SahAssar** [comment]
@gwbonline: links for records are generated using the contenttype slug, not the taxonomy slug. So, your contenttype has the slug "blog". I'm pretty sure you could change it to use the taxonomies slug by editing routing.yml, but I'm not exactly sure how to use the taxonomy slug like that...

**Comment by gwbonline** [comment]
Ok, thanks! I will try some things to make it work like I want.

**Comment by SahAssar** [comment]
Closing since it seems fixed, please open a thread on the forums if you have more questions :)
