### ISSUE TITLE
[RFC] Adding sortable multiselect and relations to core in v3.1

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4865]
At Intendit we have been making heavy use of @rossriley's awesome sortable relations extension and have found it very, very useful, however since #4340 the old way of doing sortable relations is no longer possible since the extension cannot get the original order of the relations in the save event.

I propose that we make it part of bolt proper. Both extensions are quite light and I think this would be a useable feature for many users of bolt.

**Comment by GawainLynch** [comment]
Sounds like a job for… Ninja Ross! ;-)

:+1:

**Comment by PhillippOhlandt** [comment]
:+1: just do it! :P

**Comment by GawainLynch** [comment]
@PhillippOhlandt, just so we're on the same page, it's **late** freeze right now for 3.0… but for 3.1 absolutely.

**Comment by PhillippOhlandt** [comment]
Sure, I meant 3.1:) I was just too excited xD

**Comment by bobdenotter** [comment]
Fixed in #5441

**Comment by SahAssar** [comment]
Just to be clear then, we are not going to implement sortable relations then? I'm totally okay with that and was going to suggest it anyways, but that's the idea, right?

**Comment by bobdenotter** [comment]
I closed this during cleanup, but I might've been a bit too hastily. I assumed this was fixed by #5441, but it was only mentioned in there. 

I know @rossriley was planning to overhaul relations some day, so this will probably get included with that then, right?

**Comment by SahAssar** [comment]
Well, sortable relations really seems more like a hack the more I've tried it out, and goes against the idea of relations (being bidirectional), so IMO it's better to leave relations without sortability, and focus on them being more like other fields, so this being closed makes sense.
