### ISSUE TITLE
SLUGS with underscore and special characters: ( _, á, é, Á, É)

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#4866]
Hi guys, 
I have this problem, I'm migrating an old site to Bolt. So I need to keep some urls with special characters in the slug, underscore and spanish tildes: _, á, é, í, ó, ñ
Any clue please?
Thanks in advance!
Fran

**Comment by SahAssar** [comment]
Hey,

This can be done with an extension overriding the default slug generator, have a look at https://github.com/SahAssar/internationalslugs, which should be enough for your use case.

**Comment by tourdefran** [comment]
Great!!
Thanks Svante, you saved me!
