### ISSUE TITLE
[BUG] Template specific fields not saving

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#4877]
Using 2.2.17 and SQL db. 2 templates setup, one with a template specific field named sidebar.

- Edit a content type whose template is currently set to one with no template specific field.
- Change to the template with an extra field.
- Save the changes.
- Refresh the page.
- Enter a value into the additional field.
- Save the changes.
- Navigate away from the editor.
- Navigate back to the editor and witness the value has not persisted. No commits made to the db either.

**Comment by SahAssar** [comment]
Sorry for the late reply! What server/db are you on? (Sorry, but "SQL db" does not say me much since all our supported platforms do SQL).

**Comment by tomntech** [comment]
MySQL 5.5.42.
Running PHP 5.6.

**Comment by bobdenotter** [comment]
I've tried it on PHP 5.6.10, and Bolt 2.2.18. I've not been able to verify this, so I guess this is fixed in the meantime. 

Feel free to re-open this issue, if the problem persists after updating Bolt.
