### ISSUE TITLE
[RFC] File uploading to subfolder based upon content-type post

### ISSUE THREAD

**Issue by smokeysmokeyd** [bolt/bolt#4884]
Hi all,

I have a content type that will have many many images associated with each post. I'd like it the most if, for each post made with a content type, the images were added to a subfolder that was assigned to each post.

Right now one can specify the upload folder for an entire content-type but not one specific to each post, like so:

```
imagefield:
   - type: imagelist
   - label: "Upload a photo"
   - upload: photos
```

How would we go about implementing upload into a post subfolder? Perhaps with a new `filesubfolder`  field? But I'm not sure where to begin to implement this myself so I come to you all for advice.

For example, for a new post "boulder" with a content-type having `upload: photos` specifier like above, I'm looking for the photos to be stored in `files/photos/boulder`

Thanks a bunch. Do let me know if I'm unclear!
Smokey

 - Relevant Bolt Version: [ 2.2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.4 | 5.5  ]
 - Used webserver: [ Apache ] version [ 2 ]

**Comment by bobdenotter** [comment]
Why would you want this? Seems like a huge overkill to me.. 

Anyhow, if you're dead set on creating folders for every single post, just upload the files manually to the server, and then insert them by "pick from server" in Bolt.

**Comment by smokeysmokeyd** [comment]
Personally I'm a fan of neatly organizing things, and considering I have 20 different posts with each having 40+ images, it seems a total hairball to have them all 800+ photos lumped in the same folder; also to avoid duplicate filenames.

What you say makes sense though, and is an easy way to go about it.

**Comment by rossriley** [comment]
Here's how:
https://gist.github.com/rossriley/31037198c925ec137014

**Comment by smokeysmokeyd** [comment]
Thanks so much! Where would I inject that code?

**Comment by rossriley** [comment]
If you want to modify Bolt at runtime like this, you're best off following the guidance on this page:
https://docs.bolt.cm/installation-advanced

Once you have your own bootstrap file, then you just add the code like the above snippet, before the call to `$app->run()`

And yes it will create the directory automatically as long as the web server has permissions on the parent folder.

**Comment by smokeysmokeyd** [comment]
Thanks so much @rossriley! Can't believe I hadn't stumbled upon that page in the docs yet. Cheers

**Comment by EJanuszewski** [comment]
@smokeysmokeyd With uploading them in file manager and selecting being inconvenient, this should help https://github.com/bolt/bolt/pull/4879

**Comment by bobdenotter** [comment]
Since there's a workaround, it's not likely we'll have time to implement this soon. Closing this, if you don't mind.
