### ISSUE TITLE
[BUG/WIP] Controller actions in the async FilesystemManager controller are still using the old API

### ISSUE THREAD

**Issue by robbert-vdh** [bolt/bolt#4886]
The FilesystemManager controller is still using the old API and relies on filesystem manager returning booleans instead of throwing exceptions. This causes some file operations to throw errors even though they still succeed. I've already fixed this for `/async/file/delete` in #4882 but I just noticed this is happening in more places. I'm working on a patch (and some much needed tests) right now.

**Comment by GawainLynch** [comment]
Thanks mate. The help is very welcome... Especially on tests.
