### ISSUE TITLE
[RFC] Should we display '404 pages' instead of error pages, for logged in users?

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4888]
Currently, when a visitor is _not_ logged in, they get nice 404 pages, like this: 

![screenshot 2016-02-22 22 52 10](https://cloud.githubusercontent.com/assets/1833361/13234047/052d43c6-d9b7-11e5-9301-b599abb38f31.png)

However, if a user is logged in, they see this, for the exact same URL: 

![screenshot 2016-02-22 22 48 21](https://cloud.githubusercontent.com/assets/1833361/13234061/15bc9692-d9b7-11e5-86e5-44e6e00fd87f.png)

~~Silex~~ Whoops! does this, because it _assumes_ the 404 is an error. Strictly speaking that's correct, but it also confuses a lot of people. 

Should we fix it so that 404's in the frontend _always_ show the proper 404 page, regardless of logged-in state?

**Comment by SahAssar** [comment]
I'd like to propose that we default to `debug: false` instead... having the default be `true` makes no sense to me.

**Comment by bobdenotter** [comment]
sahassar: the 'debug bar' is pretty invaluable, I think.. 

However, you do raise a good point: If you disable _whoops_ with `debug_enable_whoops: true`, it already works as proposed.. So, in this case it's the Whoops library that 'catches' the 404, while (imho) it shouldn't. :thought_balloon:

**Comment by SahAssar** [comment]
bobdenotter: the debug bar is invaluable. If you are looking for the info that it gives you, which I would expect that the people that are confused by that "404" would not be, which is my point. Which one of our three target groups will look at the debug bar but will not get the 404?

**Comment by GawainLynch** [comment]
`/me` avoids rant about Whoops! library

**Comment by bobdenotter** [comment]
I'd like to make it so that if you're logged in, you'd see this: 

![screenshot 2016-02-22 23 05 05](https://cloud.githubusercontent.com/assets/1833361/13234402/bda6c82c-d9b8-11e5-8ed4-e9c6f89b2d45.png)

So, you would see the proper '404' page, but _with_ the debug toolbar, that's pointing out that you have a '404' response.

**Comment by SahAssar** [comment]
@bobdenotter: Right and that seems better than what we currently have, but still what's the reason for `debug` being on by default?

**Comment by GawainLynch** [comment]
OK… Whoops! rant it is :stuck_out_tongue_winking_eye: 

Quite simply #4889 has a big vote from me, and if I wasn't feeling so damn happy this morning, I'd just BPFL merge it. The Symfony routing page is far more useful to all three groups, and if Whoops! went away tomorrow I wouldn't be sad.

**Comment by bobdenotter** [comment]
You know I really like Whoops generally, but in this case you're right. ;-)

@SahAssar I can see where you're coming from, but I think disabling debug by default would be one step too far.

**Comment by GawainLynch** [comment]
Fixed in #4889
