### ISSUE TITLE
[BUG] imageinfo() fails on non existent path

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#4892]
```twig
{{ imageinfo('path/to/non/existant/file') }}
```

fails with on master

> An exception has been thrown during the rendering of a template ("File not found at path: …")

Emergency, paging dr. @CarsonF  :ambulance:

**Comment by rarila** [comment]
@GawainLynch I guess we are missing a test for this case, too?

**Comment by GawainLynch** [comment]
Maybe, I think it is intended behaviour though… but @CarsonF had lead on FS work and I want to give him time to chime in.

**Comment by rarila** [comment]
I don't think I like to see exceptions for normal operations in twig land. At least as long as we don't have ``{{ try }} … {{ catch }}``. It should return something like ``null`` in this case

**Comment by CarsonF** [comment]
@rarila I can't reproduce this

**Comment by rarila** [comment]
Big sorry, the error was in front of the keyboard.

For the record, don't do something like this:

```twig
{% set info = imageinfo(path) %}
{% set width = info.dimensions.width %}
```
better do it that way:
```twig
{% set info = imageinfo(path) %}
{% if info.exists %}
    {% set width = info.dimensions.width %}
{% endif %}
```

**Comment by CarsonF** [comment]
You shouldn't need the if exists check. `width` should just return `0`.

**Comment by rarila** [comment]
Yeah, but in a real case there is of course some more other stuff in there what you perhaps don't wanna do if the image doesn't exists, e.g. display it.

And as we just found out, accessing ``info.type`` throws the exception.
