### ISSUE TITLE
Image field upload silently fails for cms users if a server error occurs

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4895]
In the bolt back-end, if the image uploader fails because of a server error the uploader resets and the image is not uploaded.

**How to reproduce**: 
- Start by creating or editing a record for a contenttype with an normal image field: http://example.com/bolt/editcontent/{contenttype}/{contentid}
- Upload an image. 
  ![image](https://cloud.githubusercontent.com/assets/1488214/13286300/cc2c8b72-db00-11e5-8d7c-15b2ef39c714.png)

**Result in normal working case**:
- The image is uploaded to the server
- the image is saved on the server
- the image is added to the image field 
- and the thumbnail for the imagefield is changed

**What happens in the error case**:

For example the upload is too large and nginx returns a header "413 (Request Entity Too Large)"
- The user does not see that there was an error and the upload silently fails, the thumbnail and the image stay as they were

**Expected result**:
- If there is an error on the serverside the upload field should show an error message with something along the lines of:

> The upload has failed, please try again with another image. If the problem keeps occuring the following message might help to solve this problem: 'HTTP Server Status: 413 (Request Entity Too Large)'
## Details
- Relevant Bolt Version: 3.0 alpha5 / master
- Install type: Composer install
- PHP version: 5.6
- Used webserver: Nginx
- For UX/UI issues: Chrome 48.0 Ubuntu

**Comment by GawainLynch** [comment]
Um, that is web server configuration, and the FPM doesn't even know about it.

**Comment by jadwigo** [comment]
Yes.. that's why the ajax handler in the user interface should show a message.. the ajax request knows about http return codes

**Comment by GawainLynch** [comment]
Oh right… Good point.

**Comment by jadwigo** [comment]
By the way - https://github.com/bolt/try-bolt/issues/2 is related

**Comment by Maelstromeous** [comment]
This also happens for image uploads where the server directory could not be made.

**Comment by GawainLynch** [comment]
Bumping up to 3.4 as a lot of this will be caught up in the UI-Beam project

**Comment by GawainLynch** [comment]
Bumping to 3.5.

**Comment by Maelstromeous** [comment]
As far as I know this still occurs. Any fixes in the pipeline?

**Comment by GawainLynch** [comment]
Yes, but not targetting v3 … I rewrite the file upload handling last week for v4, and the front end components are being prototyped in Vue, so a whole different ball game :wink:
