### ISSUE TITLE
[BUG] record.related() returns unpublished items in twig

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4896]
If you have two content types and one is related to the other

The twig function {{ record.related() }} will show all published and unpublished related items where it should only show the published items

Details
-------

 - Relevant Bolt Version: 3.0 alpha5 / master
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Nginx
 - For UX/UI issues: n/a

**Comment by bobdenotter** [comment]
I'm on it! PR in 2 minutes!

**Comment by GawainLynch** [comment]
Fixed in #4897
