### ISSUE TITLE
The browser should not pre-fill the password in "new user" screen. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4898]
See screenshot: 

![screen shot 2016-02-24 at 15 05 01](https://cloud.githubusercontent.com/assets/1833361/13287632/4e925752-db08-11e5-8cca-2ff9d392e6d3.png)

I'm pretty sure I fixed this a while ago, but Chrome seems to have the opinion that it shouldn't listen to `autocomplete="off"`.

Relevant Bubbles: 

![giphy](https://cloud.githubusercontent.com/assets/1833361/13287683/98ea3446-db08-11e5-84fe-38981972231f.gif)

**Comment by geggleto** [comment]
I believe the only current fix to this, is to set a javascript callback to erase the password field after the page is fully loaded.

The autocomplete="off" is unreliable.

**Comment by bobdenotter** [comment]
@geggleto Seems to be the case, yes.. I'd really like a non-javascript solution for this, but Chrome seems  hellbent on being "helpful". :boom:

**Comment by SvanteRichter** [comment]
Seems like basically every browser except android and opera ignore it for
either password fields, or for all login form fields...

**Comment by geggleto** [comment]
@bobdenotter if you find a solution, let me know because I want to find one too for work, haha.

**Comment by jadwigo** [comment]
as soon as its vaguely related to <input type="password" name="password"> the autocomplete will probably be overridden by the reasoning "this is a user password field, lets autocomplete anyway"

the solution is probably not to use password inputs and/or a name containing password (in any language)

**Comment by bobdenotter** [comment]
Looking through the git logs, i've fixed this twice before, but the Chrome developers insist this is feature, and keep "fixing" the workarounds. 

https://bugs.chromium.org/p/chromium/issues/detail?id=468153

**Comment by geggleto** [comment]
Would dynamic field names solve it?

**Comment by GawainLynch** [comment]
Please don't move away from password input types… 3.1 should hopefully bring us toward bringing in Symfony Forms, and validators, for our backend fields… and if you spend some time to have written your own validator, you get why I'm asking :wink:

**Comment by bobdenotter** [comment]
@GawainLynch This will most likely be an issue in Symfony Forms as well. Also, the problem occurs with both `text` and `password` fields. 

Seems like the Chrome devs know better than us, and are committed to this "feature" of disabling the disabling of prefill. 

None of the workarounds in here work anymore: http://stackoverflow.com/questions/12374442/chrome-browser-ignoring-autocomplete-off

geggleto: Dynamic field names _might_ solve it, but that would mean a lot of hackish crap to fix an issue that shouldn't even be there in the first place.

**Comment by jadwigo** [comment]
another solution was to add autocomplete="address-level4" or another rarely used attribute to another unimportant textfield and it might work ... and the workarounds keep on getting more obscure

**Comment by bobdenotter** [comment]
@jadwigo: Tried it, doesn't work anymore.

**Comment by jadwigo** [comment]
Would this solution help?

https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c150 

> All, after reviewing https://html.spec.whatwg.org/multipage/forms.html#autofill , I was able to fix my issue by adding 'autocomplete="new-password"' to each password field I don't wish the browser to autofill.

**Comment by bobdenotter** [comment]
@jadwigo: Thanks mate, `autocomplete="new-password"` works!

**Comment by jadwigo** [comment]
Whooohoo .. and that is a very unambigous solution, if the chrome devs also try to "help" there they may be publicly shamed

**Comment by geggleto** [comment]
oh sweet. thank you @jadwigo

**Comment by GawainLynch** [comment]
@bobdenotter I wasn't saying it isn't an issue with Symfony Forms, I was saying don't **move away** from password field types as it will make life much harder for them backend team.

**Comment by bobdenotter** [comment]
@GawainLynch: Noted! Wasn't even an option in my mind, considering we should be working towards the 3.0.0 release. ;-)

**Comment by bobdenotter** [comment]
Fixed in #4900
