### ISSUE TITLE
[RFC] Simplified setcontent queries for taxonomies

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#4903]
Currently when you do a setcontent for a taxonomy you use the where clause like

    {% setcontent myevents = 'events' where { categories: 'music' } %}

I'd like it to be able to do something like 

    {% setcontent myevents = 'events/categories/music' %}

And also something that pulls from all contenttypes like:

    {% setcontent myevents = 'categories/music' %}

The last example currently works for URLs, but not for setcontent.

Thoughts?

**Comment by geggleto** [comment]
:+1: :)

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by bobdenotter** [comment]
Personally, i think this would be 'fragile', and bug prone. 

For example: `{% setcontent myevents = 'categories/music' %}`.. How would the storage engine know you'd want a taxonomy, and not slug 'music' from contenttype 'categories'..

**Comment by geggleto** [comment]
forgive my noobishness, but how does it work for URLs ? would it not be the same?

**Comment by SahAssar** [comment]
@bobdenotter Either we'd disallow calling a contenttype the same as a taxonomy (which seems reasonable to me, but I get if there disagreements) or one could modify it to be `{% setcontent myevents = 'taxonomy/categories/music' %}`. In that case we'd just need to disallow a contenttype to be called "taxonomy", and we already have this issue (paritally) since the URL's are handled the same way.

**Comment by GawainLynch** [comment]
This is something that we should **not** do in stable, and v3 is in the lead up to release… and @rossriley's changes to how storage works would probably make this easier to implement.

That said, I am not sure we want more BC breaks in the 3.x life cycle (as noted in @bobdenotter's comment)

**Comment by rossriley** [comment]
Yes, once we can switch over to the new system for querying content, the parser for these queries is a lot more (Details outlined in #3891) extendible.

The goal with having the parser as a service mounted on `$app` is that even if we don't decide to do something like this in core, it would be very easy to implement via an extension in a few lines of code.

**Comment by SahAssar** [comment]
I'm not saying to do this in 2.2.X or even necessarily in 3.X, but to me it feels like bolt would feel more predictable/easier if it was implemented. Making setcontent queries and URL's act more like each other seems logical to me, since they already act the same for basically every other purpose. Also, just like in  the routing we already have we could just have the contenttype take precedence if there are taxonomies and contentypes with the same slug.

Anyway, I'm not going to rant. :)

**Comment by SahAssar** [comment]
@rossriley Sorry, didn't see your reply before I posted mine.

I'll just make an extension when we switched to the new system for querying content, thanks! :)

**Comment by SahAssar** [comment]
Closing since this has moved to both extensionland and futureland.
