### ISSUE TITLE
[question] Adding content from the backend with 3 fields each time, special form or contenttype

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#4905]
Hi guys, 
I need to solve this problem, I've read all the documentation and I can't figure it out. I need some help please! 

**The thing is:**
I need to add some kind of filelist, to load 3 fields per iteration. I mean, the user needs to add 3 elements each time. So in the front end I can show this elements:
![schelp](https://cloud.githubusercontent.com/assets/2666701/13308343/49b6f578-db51-11e5-92aa-0de28d5568d5.png)
Any clue please?! I need to deliver this an I'm stucked, any help will be very appreciated, thanks in advance!
Fran

**Comment by bobdenotter** [comment]
Hi, 

Please post questions on the forum at discuss.bolt.cm. We'd like to keep the tracker to actionable issues, and support questions are better suited on the Forum. I'm going to close this one now, but you can still reply below it. :-)

Anyhow, I'm not sure what you mean. Some pointers: 

 - You can limit the output to three max, if you need: `limit 3` in the setcontent tag.
 - If you want to group them in threes with `<div>` or something, use `|batch`: http://twig.sensiolabs.org/doc/filters/batch.html
 - Are you looking for a resources contenttype? https://docs.bolt.cm/howto/resource-contenttype

**Comment by tourdefran** [comment]
Hi Bob, 
Thanks for your answer. I will keep in mind the discuss forum. 
What I need to do is a form in the backend that allows me to introduce a Soundcloud Mixtape ( 3 fields, embed, txt and link). The thing is that I need to add several mixtapes, at least 50, so in the backend I can't have 150 fields, I need to make it more clean. For example, some "add new mixtape" button that adds 3 fields, and so one

**Comment by bobdenotter** [comment]
Ok, you'll need this: 

 - Resource contenttype for all the mixtapes:  https://docs.bolt.cm/howto/resource-contenttype
 - add 3 select fields to pick a mixtape on the page itself: https://docs.bolt.cm/howto/select-field-type#populating-list-contenttype
