### ISSUE TITLE
[BUG] Twig batch not passing the fill argument

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#4906]
Hi, I'm having this issue with Twig, the thing is that the fill argument is not working, 
cheers!
Fran

```
{% setcontent records = "artists" %}

<div class="artist-list" >

	{% for row in records|batch(3, 'No content') %}
	    <div clas="row">
	        {% for record in row %}
	            <div class="small-4 columns">
	                content here
	            </div>
	        {% endfor %}
	    </div>
	{% endfor %}

</div>

```

Rendered:
```
<div class="artist-list">

		    <div clas="row">
                     <div class="small-4 columns">
	                content here
	            </div>
	        	            <div class="small-4 columns">
	                content here
	            </div>
	        	            <div class="small-4 columns">
	                content here
	            </div>
	        	    </div>
	
</div>
```

Expected:
```
<div class="artist-list">

		    <div clas="row">
	        	            <div class="small-4 columns">
	                content here
	            </div>
	        	            <div class="small-4 columns">
	                content here
	            </div>
	        	            <div class="small-4 columns">
	                No content
	            </div>
	        	    </div>
	
</div>
```

[Twig documentation](http://twig.sensiolabs.org/doc/filters/batch.html)

Details
-------

 - Relevant Bolt Version: [ 2.2.1.7 ]
 - Install type: [  Zip/tarball install ]
 - PHP version: [ 5.3.24 ]

**Comment by tourdefran** [comment]
After a {{ dump(record) }} I'm more confused:

![batchtwig](https://cloud.githubusercontent.com/assets/2666701/13310365/48f05d9c-db64-11e5-97d6-875696ae055b.png)

**Comment by bobdenotter** [comment]
I don't see what's wrong with this.. Seems to me to be doing what you want: 2 records, and the rest filled out with "No content". 

Please post questions on the forum at discuss.bolt.cm. We'd like to keep the tracker to actionable issues, and support questions are better suited on the Forum. I'm going to close this one now.
