### ISSUE TITLE
Symfony's Webdeveloper Toolbar should _not_ set flashes..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4912]
Currently, on most pages, most flashes are set twice. This is because the "regular" page sets it, and then the initialisation of the toolbar sets it again. 

A simple solution is this, is to add something like this to `Flashlogger.php`, in `function add()`:

```
        // Don't show the check if we're in the Webdeveloper toolbar.
        $app = ResourceManager::getApp();
        if ($app['request']->get('_route') === '_wdt') {
            return;
        }
```

But, I'm certain Gawain, Ross or Carson will know of a better place to put that. :-)

**Comment by CarsonF** [comment]
Yes I'll fixed that in my session/csrf branch landing in a day or two
