### ISSUE TITLE
[RFC] Configuration notices should be more prominent

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4916]
Everyone likes their dose of new, granted. But human eyes will not scan past the first or second box on average:
![image](https://cloud.githubusercontent.com/assets/1427081/13329243/155dbd00-dbf3-11e5-8860-9615288a0b1b.png)

**Comment by bobdenotter** [comment]
Are you saying it needs more `<blink>`?

**Comment by GawainLynch** [comment]
```html
<blink><marquee><koala><strong>Nah, just bumped up the visual list</strong></koala></marquee></blink>
```
