### ISSUE TITLE
"White screens of death" in 404 handler.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4921]
Details
-------

 - Relevant Bolt Version: [ master ]
 - PHP version: [ 5.5 | 5.6 | 7.0 ]

Reproduction
------------

 - Edit 'config.yml', set `strict_variables: true`.
 - Edit 'record.twig', and add to the body somewhere `Doesn't exist: {{ foo }}`
 - In the browser, trigger a 404 by going to `/ggggg` or whatever. 
 - Boom. Nothing! 

![screenshot 2016-02-27 09 53 33](https://cloud.githubusercontent.com/assets/1833361/13372081/055def60-dd38-11e5-9521-9f5a8e35455d.png)

**Comment by rossriley** [comment]
The same can happen on 2.2 as well if the error is in the 404 page, for example include a non existent twig template in 404.twig then a white screen of death results.

**Comment by bobdenotter** [comment]
Hmm. Is if fixable, though? It had me stumped this morning, and took a while to pinpoint why this happens.

**Comment by jadwigo** [comment]
Does this happen when the 404 handler in config.yml is set to `page/not-found` or to a template.

If the `page/not-found` does not exist you will get a double error which might trigger a WSOD is debug output is disabled

> Bolt - Fatal error.
Class: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
Message: The page could not be found, and there is no 'notfound' set in 'config.yml'. Sorry about that.
Code: 0

**Comment by bobdenotter** [comment]
Either. 

It happens if there's an `Exception` thrown inside the 404 handler. So, in normal use, this doesn't show up. Only if you've triggered an error, inside the 'not found' template or handler.

**Comment by jadwigo** [comment]
Looing a bit further.

If the 404 page or template does _not_ exist it seems to render in the bolt default `error.twig`.

If you create an `error.twig` in your theme that will be used.

So it only happens if there is an error in a twig template that is used to display the error page.

**Comment by GawainLynch** [comment]
> So it only happens if there is an error in a twig template that is used to display the error page.

Which is kinda logical if you ask me :wink: 

So a non-issue?

**Comment by jadwigo** [comment]
nope - WSOD is never a non issue, because they are hard to debug and users of bolt will make lots of support request about it

**Comment by GawainLynch** [comment]
Yeah… but if the error is caused by the error template, it will fail in the `__toString()` call and that can **not** be caught due to PHP being PHP.

**Comment by jadwigo** [comment]
so lets make sure we never get to that point - can we disable twig strict mode for the rendering of error templates?

**Comment by GawainLynch** [comment]
…and if there is other errors that prevent a render?

**Comment by jadwigo** [comment]
that should not be relevant to this issue - there will either be another wsod situation we need to fix or an error which should be found by the lowlevelchecks

**Comment by bobdenotter** [comment]
The issue here is not that Twig is "strict" or not.. It's PHP being derpy. I agree with Gawain that forcing non-strict twig rendering will not solve this issue.

**Comment by bobdenotter** [comment]
This has been an issue since, basically forever, and there's no clear fix for it. 

I've removed the "blocking release" tag, but leaving it open.

**Comment by SahAssar** [comment]
@GawainLynch Did any of you exception handling touch this?

**Comment by GawainLynch** [comment]
It does, but doesn't yet catch this one … PR inc!

**Comment by GawainLynch** [comment]
#5667 now behaves like this for this circumstance:
![image](https://cloud.githubusercontent.com/assets/1427081/17556867/4c156e92-5f15-11e6-9c8d-0cf22dc08034.png)

**Comment by bobdenotter** [comment]
closed by #5667
