### ISSUE TITLE
[BUG] Clicking into filelist/imagelist title doesn't focus first time

### ISSUE THREAD

**Issue by EJanuszewski** [bolt/bolt#4923]
When clicking the input field in a filelist and imagelist, it doesn't focus into the textbox, you have to click again which is really annoying, it seems to work if its the first click into the list, but not when clicking between each one

Details
-------
 - Relevant Bolt Version: 2.2.18
 - Install type: Git
 - PHP version: 5.5.9
 - Used webserver: Apache version
 - For UX/UI issues: Chrome 48.0.2

I shall investigate this and try put a fix in if we agree this is a bug

**Comment by bobdenotter** [comment]
I'm seeing the same thing: http://recordit.co/zzJ3liOAuy

I guess there's a rogue `blur();` somewhere, that makes it lose focus, when toggling between the different inputs.

**Comment by bobdenotter** [comment]
Note:I'm seeing this _only_ on 2.x.. It works correctly in 3.0.

**Comment by EJanuszewski** [comment]
Good to know its fine in 3.0, I might compare them since I imagine the core is similar in that area

**Comment by EJanuszewski** [comment]
Looking at it in 3.0 it seems the file stuff is handled in /app/src/js/widgets/fields/fieldFilelist.js and there doesn't appear to be anything similar so I can't copy/backport it with the same code.

**Comment by rarila** [comment]
@EJanuszewski half of JS stuff has been completely rewritten for 3.0 (and the other half would have been if I had more spare time)

**Comment by EJanuszewski** [comment]
@rarila yeah I noticed, took me a good 5 minutes to find it in 3.0, you've done a good job :)

**Comment by rarila** [comment]
Thanks! :metal:
