### ISSUE TITLE
[RFC] Stop using scrutinizer.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4931]
As of lately, Scrutinizer seems to be very flaky. Even more so than usual. 

![screen shot 2016-02-29 at 17 03 58](https://cloud.githubusercontent.com/assets/1833361/13400088/77e0f846-df06-11e5-8549-225cfd12b5ee.png)

(No scrutinizer, pr #4913 was not the first inspection you did on master..)

Right now there are 4 PR's in the queue showing up as failures, because Scrutinizer has gone of his rockers.

**Comment by GawainLynch** [comment]
I'm just going to BPFL this one… disabled!

**Comment by GawainLynch** [comment]
Side note: Travis and Screwtinizer and configured to run against my fork on all pushes I do, so I will know when things start working again.
