### ISSUE TITLE
[RFC] Link to bolt/about from a page in backend, not just from debugbar

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4936]
When debug is off, for instance, in production, it is not easy to see the Bolt versionnumber.
This makes it a bit unclear whether my update went well. The page bolt/about is great for that, but only links from the debugbar (correct me if i'm wrong).
Shouldn't there be a link to bolt/about on the configpage or some other basic page?

Thank you!
A

Relevant Bolt Version: 2.2

**Comment by anketwokings** [comment]
Hold on.. Seemed to be a glitch in the matrix that caused the bottom bar not to show. Not sure what happened there, trying to reproduce.

**Comment by bobdenotter** [comment]
Writing this off as a one-time fluke! 

Feel free to re-open this issue, if the problem persists.
