### ISSUE TITLE
When updating Bolt, you're not always getting the 'new' CSS and JS files. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4944]
.. Which causes some people to think they've broken it, until they do a "hard refresh". This shouldn't be necessary.

**Comment by GawainLynch** [comment]
In master, the backend assets should all be getting file mtime hashes from `{{ cachehash() }}` in the query… unless @CarsonF broke it on me

**Comment by bobdenotter** [comment]
"should" as in "on our list to be implemented soon"? I didn't see them, and I was annoyed at my css / js not updating for an update to `alpha 7`. :-)

**Comment by GawainLynch** [comment]
Should as in it was part of the asset handling refactor 6 or 9 months ago…

**Comment by GawainLynch** [comment]
But just grepping it looks like it has been removed from the Twig templates :frowning:

**Comment by bobdenotter** [comment]
Hmm.. I don't recall seeing this.. :-/

**Comment by GawainLynch** [comment]
It was introduced in #3715

**Comment by bobdenotter** [comment]
I see the code for it now. How _predictable_ is the outcome for `{{ cachehash() }}`? 

What I liked about this implementation, is that it uses the version number _and_ the filemtime of the `Version.php`, making it pretty hard to build a table with outcomes for different versions of Bolt. At first glance it seems like yours does this too.. Just touching the file makes the hash change.

**Comment by bobdenotter** [comment]
Right. I'll fix this up and restore the 'cachehash' ones in the template.

**Comment by bobdenotter** [comment]
Going back through the code, It seems like is _was_ intrododuced then, but I don't think it was ever applied to the files served in the backend. I'll make a new PR to do this now.

**Comment by GawainLynch** [comment]
It definitely was applied… and definitely has been removed/refactored at some point… might have been a later PR as there was a lot of churn around then.

**Comment by bobdenotter** [comment]
I clicked through the history of `_page.twig`, but i couldn't find it. :-)

**Comment by GawainLynch** [comment]
Strange… I spend ages "hashing" it out on IRC with you and @rarila too:

```
Jun 18 08:52:18 <rossriley>	it's catching up with the issue queue
Jun 18 08:52:54 <gawainlynch>	Bopp: So I am about to PR that snippet branch (today), only outstanding question is if we add any sort of Twig function… rarila is against generating full HTML (for valid reasons) but do we want a function/filter to allow passing in a file name and adding a unique hash query?
Jun 18 08:53:38 <Bopp>	gawainlynch: yes, i think so.. 
Jun 18 08:53:45 <gawainlynch>	rossriley: Yeah, fortunately a lot of the issue queue is questions and feature requests
Jun 18 08:53:52 <gawainlynch>	Bopp: Filter or function then?
Jun 18 08:54:26 <Bopp>	perhaps even make the filename optional.. if empty, it does a generic magic hast.. 
Jun 18 08:54:59 <Bopp>	i'm leaning towards function.. bla.js?v={{ magic('app/view/js/bla.js') }} 
Jun 18 08:56:11 <gawainlynch>	Bopp: It would probably make more sense to do: <blah src="{{ magic('app/view/js/bar.js') }}"/>
Jun 18 08:57:07 <rarila>	gawainlynch: yep, then we could switch to that cache thing
Jun 18 08:57:23 <gawainlynch>	Just not seeing where an optional file name makes a lot of sense as you'd only get an MD5 of the salt and that in itself is a risk
Jun 18 08:57:32 <gawainlynch>	(slight)
Jun 18 08:57:39 <gawainlynch>	rarila: Cool
Jun 18 08:58:01 <gawainlynch>	{{ filehash() }}  ?
Jun 18 08:58:39 <rarila>	{{ koala() }}
Jun 18 08:58:41 <Bopp>	gawainlynch: yeah, true
Jun 18 08:58:59 <rarila>	{{ hashme() }}
Jun 18 08:59:11 <gawainlynch>	{{ hasbrown() }}
Jun 18 08:59:21 <gawainlynch>	*hashbrown()
Jun 18 08:59:34 <sbani>	{{ hashhashhash() }}
Jun 18 09:03:14 <Bopp>	{{ leeloo_multihash() }} 
Jun 18 09:03:43 <gawainlynch>	Bopp: Gold!

```

**Comment by bobdenotter** [comment]
Now that i see that, I do remember that conversation. :-)

**Comment by GawainLynch** [comment]
I laughed so hard (again) when I re-read the `{{ leeloo_multihash() }}` bit :laughing:

**Comment by rarila** [comment]
21 lines of IRC conversation and not one mention of ``#beer`` …  :disappointed_relieved:

**Comment by GawainLynch** [comment]
Haha… actually I think there was, but I removed it as it wasn't relevant to the issue

**Comment by rarila** [comment]
If it had been ``#beer?a64e4f8b`` … the only way to always get fresh :beer:

**Comment by bobdenotter** [comment]
Closing this one. We have `{{ cachehash }}`, that solves this problem.
