### ISSUE TITLE
Bolt shouldn't break when it can't create `/thumbs`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4960]
See screenshot:

![screenshot 2016-03-06 13 37 07](https://cloud.githubusercontent.com/assets/1833361/13554177/7ebc1de0-e3a1-11e5-9eff-95da8586e3b9.png)

Details
-------

 - Relevant Bolt Version: [ alpha 7 | master ]

Reproduction
------------

 - Install bolt.
 - make sure the webserver is not allowed to create `/thumbs`
 - Open in browser, you'll see the error before the "first user" screen
 - Create folder manually, all's fine.

**Comment by CarsonF** [comment]
@bobdenotter Can you post the stacktrace?
