### ISSUE TITLE
Don't show "You've been logged out", before the first user exists.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4961]
See screenshot: 

![screenshot_2016-03-06_13_46_25](https://cloud.githubusercontent.com/assets/1833361/13554202/fc0f3048-e3a1-11e5-91b8-558a7f76f2ea.png)

**Comment by GawainLynch** [comment]
Forgive me if I am totally wrong, but doesn't this only happen after you delete/truncate the user table, ergo logging you out?

**Comment by bobdenotter** [comment]
Nope, happens everytime you get redirected to `bolt/userfirst` from the front page.. See screenshot: 

http://g.recordit.co/RwDuB6BRiW.gif

**Comment by GawainLynch** [comment]
Thanks!
