### ISSUE TITLE
[BUG] thumbnail() ignores default cropping setting

### ISSUE THREAD

**Issue by rgls** [bolt/bolt#4964]
On a freshly installed bolt 2.2.18 I changed thumbnails/cropping in config.yml from crop to resize.
The thumbnails were still cropped. Clearing the cache didn't change anything. Only changing entry.twig from "thumbnail(record.image, 400, 260)" to "thumbnail(record.image, 400, 260,'r')" resulted in the images being resized instead of cropped.

**Comment by SahAssar** [comment]
Yeah, this looks to be a bit buggy... I'll try to get a fix in today.
