### ISSUE TITLE
Users don't get logged off, when their account is revoked..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4965]
When a user get disabled or their accounts gets removed, their current sessions should be killed. This isn't happening right now. 

I made a short screencast: http://recordit.co/jTqRKVbWV9

Details
-------

 - Relevant Bolt Version: [ master ]

Reproduction
------------

 - Add a user
 - Log on as that user in a new incognito window.
 - Disable or delete that user. 
 - Toggle back to incognito window, break stuff.

**Comment by GawainLynch** [comment]
This isn't a regression... It only works in v2 due to every request querying the database.

So we need to decide if we re-add the queries, or stick with a session time out (currently 10 minutes, but I always figured we'd end up making it configurable at some point).

**Comment by bobdenotter** [comment]
I'm not sure.. I can see a need for being able to revoke somebody's access right now. 

Is there a way we could "flush" it, and force a re-check for all users?

**Comment by GawainLynch** [comment]
Chicken vs egg… we can store session IDs in the database, but b) kinda defeats the porpoise :dolphin:  of a)

**Comment by bobdenotter** [comment]
Fixed by #5002
