### ISSUE TITLE
[RFC] Rename moment

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#4969]
At the moment (LOL) we use the [Moment.js](http://momentjs.com/) library for displaying relative times and dates (= from now) in a human readable form (eg. ``5 days ago``, ``a few seconds ago``, …). So we have several places in our code that contains that name ``moment`` (``moment()``, ``buic-moment``, ``BuicMoment``, ``moment.scss``, …).

We had something similar a while ago where we had a function called ``fancybox()`` named after the library used. Then we replaced it magnific popup and we had to deprecate a function name.

To prepare for a possible future library change and to give the whole thing a more namingful and descriptive name I suggest renaming it now.

- ``RelativeTime``
- ``RelTime``
- ``FromNow``
- ``TimeAgo``
- …?

I guess native speakers have some better ideas. Suggestions welcome!

**Comment by rarila** [comment]
Reference to the function used: [fromNow()](http://momentjs.com/docs/#/displaying/fromnow/)

We don't use "Time from X" ([from()](http://momentjs.com/docs/#/displaying/from/)) and the "time to" variants at the moment and I don't if there ever will be a usecase for them. But we should probably keep in mind when sreaching for a name that we sometime might want to extend the widget for that functionality.

**Comment by bobdenotter** [comment]
I think i'd like `fuzzyDate`.

**Comment by SahAssar** [comment]
`humanTime`? The real purpose is for it to display time in a human readable way, not for it to be fuzzy.

**Comment by rarila** [comment]
@SahAssar  Not quite. If it would display ``Thursday, the fourths of may of the year twentytwotwentytwo at 12'o clock``… It's the difference between two points of time. (one is "now" in our case)

**Comment by SahAssar** [comment]
@rarila *human readable* ;) That does not mean spelled out in words, it simply means the easiest readable way to convey a time/date.

**Comment by GawainLynch** [comment]
> I think i'd like fuzzyDate.

But there is nothing fuzzy about it.

This sounds like half the conversations that @CarsonF and I have about naming PHP classes/functions/parameters only to realise after an hour long discussion that the first name we chose was the best one :laughing: 

Our approach is usually, "What does 'it' do in a practical sense", and in this sense it is taking a time/data value and formatting it… as @SahAssar says, in a "human readable" format.  So for me that is the base logic for choosing a name.

**Comment by rarila** [comment]
@GawainLynch it's fuzzy in the sense that it doesn't display an exact value, eg. 545 days is displayed as "a half year ago" and that's about 50% difference.

I think "human readable" is only one (minor) part of what it does. It misses the main part that it displays the span of time that is between a point of time (in the past) and now. That way something like "timeago" is probably closer to what it does.

**Comment by CarsonF** [comment]
[moment](https://github.com/moment/moment) has **24,993 stars** on GitHub. I think it's safe to say it isn't going away.

**Comment by rossriley** [comment]
If you want some other library comparisons, Rails uses `time_ago_in_words` and Django uses `naturaltime`

**Comment by rarila** [comment]
@CarsonF Didn't say that Moment.js is going away. But there's a small chance that Moment.js moves :truck: to the Dodos :bird: and the lovely animals  :pig: :rabbit: :dog:.

One thing is, that I think from seeing a "moment" widget/class/… you have a hard time guessing what it does.

And there's jQuery/Globalize now and I'm sure we use it sooner or later (our datepicker will use it with jQuery-UI 0.13). So with quite some overlapping functionality and as we use only small parts of Moment.js. So to shave off some bytes … Globalize seems to miss ``fromNow()`` but I guess it can be done with a few lines using ``relativeTimeFormatter()`` or someone else will do. There's also talk about a collaboration of both and even a ``moment-cldr`` exists, but that one seems to be stalled. We'll see what time brings.

But I'm sure that we will use Globalize / PHP Intl in the mid/long term as it gives us (besides a huge a mount of languages) an identical handling of things like date formatters on client and server side.

@rossriley Great idea to have a look beyond one's own nose! Anyone else knows usage of this in other languages?

So for me ``TimeAgo`` starts to get *my* favourite, It is descriptive and Rails' "in_words" can be seen as an implicit option that is set as default. If we would need we could always add an "inWords: false" option and are prepared without any big changes.

**Comment by SahAssar** [comment]
I'd be okay with basically any of the suggestions here (of course preferring something that actually conveys it's use-case), but having more discussion just seems like bikeshedding. So, unless we have some actual differences here I'll leave it up to the implementer of the change and close this. :)
