### ISSUE TITLE
[RFC] Removing Backbone.js

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#4970]
We still include ``Backbone.js`` in ``bolt.js`` although we don't use it anymore internally. As extensions have to be refactored for 3.0 anyway I guess we should take the chance and get rid of that 22kb.

Comments?!

EDIT:
Same for ``Underscore.js`` which was mostly there because of ``Backbone.js``. We still have one ``_each()`` and one ``_.has()`` in there, but I'm sure they can be pretty easily replaced.

**Comment by SahAssar** [comment]
:fire:

**Comment by GawainLynch** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by rarila** [comment]
:fire_engine:
