### ISSUE TITLE
We need "Move up" and "move down" buttons for repeaters. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4975]
From tonight's IRC meeting: 

 - *rossriley*: it would be nice if a UI person could get move up/down implemented for repeaters
though not a blocker if noone has time
 - *Bopp*: rossriley: will re-ordering them in the HTML do? Or does it need changes under water?
 - *rossriley*: reorder in html and then call the reindex js function

**Comment by rossriley** [comment]
For reference the js that controls it is in `app/src/js/widgets/fields/fieldRepeater.js` and after moving the html it just needs a call to `self._renumber();`

**Comment by EJanuszewski** [comment]
I could potentially look into this, i'll look in a couple of days when i'm back home

**Comment by bobdenotter** [comment]
@EJanuszewski I initially 'self assigned' this, because _someone_ has to do it, but if you have time, you are more than welcome to tackle this one! :+1:

**Comment by bobdenotter** [comment]
Fixed by #5005
