### ISSUE TITLE
We need an `instanceof` test in Twig. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4978]
I'd really like it if I could do things like this: 

```
{% if record is instanceof('Content') %} 
```

See: https://gist.github.com/adrienbrault/7045544

**Comment by PhillippOhlandt** [comment]
So that wouldn't check for contenttypes, only for a content object in general? Are there any cases where a `record` variable isn't a content object?

**Comment by GawainLynch** [comment]
This alone makes me want to say "no" :stuck_out_tongue_winking_eye: 
```php
        return 'yolo';
```

I'm not seeing the benefit of this though, why would we want this?

**Comment by PhillippOhlandt** [comment]
I would prefer a check if the given record is a type of a contenttype. I know its already possible but a cleaner way is always good, isn't it?

**Comment by bobdenotter** [comment]
My usecase is the following: 

In config.yml, you can define `homepage:`, but it can either be something like `homepage: page/lorem-ipsum` or `homepage: entries`. 

For the new base theme, I'd like an elegant way of checking, in order to handle both cases. What I suggested here was wrong though. Closing.
