### ISSUE TITLE
[RFC] Why is there no support for Symfony (Components) >= 2.7 ?

### ISSUE THREAD

**Issue by lastzero** [bolt/bolt#4979]
**As a developer, I would like to use Bolt CMS together with other tools or libraries that require a more recent version of Symfony Components. Being limited to < 2.7 (see `composer.json`) is a blocker.**

If you tell us why you need Symfony Components < 2.7, I might be able to send a few pull requests to fix the issues.

**Comment by GawainLynch** [comment]
The 2.x series supports PHP 5.3.3+

Bolt 3 uses Symfony 2.8 and requires PHP 5.5.9+

**Comment by bobdenotter** [comment]
Bolt 2.2 is locked to Symfony 2.6.

Bolt 3 is however coming out very soon. It uses symfony 2.8 currently, and 3.0 soon-ish. Check out the `master` branch of this repository. Any help with stabilizing and bug-hunting for the big 3.0 release would be appreciated, too!

**Comment by lastzero** [comment]
Thanks for the quick feedback - PHP 5.3 is the problem then, not Symfony Components. I understand.

If we're going to work with 3.0, I will surely help as much as possible :)

**Comment by GawainLynch** [comment]
Yeah, we should be going into beta very shortly for v3 and help is always appreciated :smiley:
