### ISSUE TITLE
Select All in overview buggy

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5000]
When using the "select all" in an overview like so:
![image](https://cloud.githubusercontent.com/assets/1427081/13699741/a87d73b6-e77c-11e5-8ce4-17fc5020e05d.png)

The result is that only the first item is selected:
![image](https://cloud.githubusercontent.com/assets/1427081/13699713/732e9064-e77c-11e5-8ed5-eee62bb50120.png)

Clearing and reselecting individually is also borked
![image](https://cloud.githubusercontent.com/assets/1427081/13699723/848820dc-e77c-11e5-92be-412b37246537.png)

**Comment by rarila** [comment]
Introduced by #4901

**Comment by GawainLynch** [comment]
Nice catch

**Comment by rarila** [comment]
The reviewer should have noticed…  :stuck_out_tongue_winking_eye:

**Comment by jadwigo** [comment]
there were a lot of buggy animals involved ... *ducks*

**Comment by bobdenotter** [comment]
Fixed by #5022
