### ISSUE TITLE
[RFC] 

### ISSUE THREAD

**Issue by pabbec** [bolt/bolt#5006]
Hi,

I'm developing my first Bolt extension to subscribe users to a mailing list based on Bolt default extension. The extension is very simple:

A form on the public site with a single field: email, and the send button.

Jquery intercepts the form submit event, and send the email field value through POST method to the controller.

The controller only must register the email address in a table and return an simple JSON response.

My problem is that when Jquery makes the call to the controller (/newsletters/ajax/subscribe/) via POST, I get an HTTP 301 redirect to the same controller, but through GET.

This generates an error because this URI, is associated to post method in the controller: This is the code to set routes in the controller:

```
$this->app
->post('/newsletters/ajax/suscribe/', array($this, 'ajaxSuscribe'))
->bind('newsletters-suscribe'); // route name, must be unique(!)
```
Any idea why this happens?

 - Relevant Bolt Version: [ 2.2.16 ]
 - Install type: Zip/tarball install
 - PHP version: 5.5.12
 - Used webserver: Apache. Version 2.4.9 on Win64

Request header (POST):

```
POST /newsletters/ajax/suscribe/ HTTP/1.1
Host: v2.geiser.ls
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: http://v2.geiser.ls/novedades
Content-Length: 29
Cookie: bolt_session=ersu2i3gqfr4bh6fln6c9u95u0; bolt_authtoken=1087dc062cd0514c431d68b14ab327a1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Response header

```
HTTP/1.1 301 Moved Permanently
Date: Fri, 11 Mar 2016 17:32:50 GMT
Server: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12
X-Powered-By: PHP/5.5.12
Cache-Control: no-cache
Location: /newsletters/ajax/suscribe
X-Debug-Token: dc2f6a
Content-Length: 348
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

```

Next. Request Header (GET)

`
GET /newsletters/ajax/suscribe HTTP/1.1
Host: v2.geiser.ls
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://v2.geiser.ls/novedades
X-Requested-With: XMLHttpRequest
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: bolt_session=ersu2i3gqfr4bh6fln6c9u95u0; bolt_authtoken=1087dc062cd0514c431d68b14ab327a1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
`

Response:
`
HTTP/1.1 405 Method Not Allowed
Date: Fri, 11 Mar 2016 17:32:50 GMT
Server: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12
X-Powered-By: PHP/5.5.12
Cache-Control: no-cache
X-Debug-Token: ff92fa
Content-Length: 406
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
`
JSON

`{"error":{"type":"Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException","message":"No route found for \"GET \/newsletters\/ajax\/suscribe\": Method Not Allowed (Allow: POST)","file":"C:\\data\\infosoft\\desarrollo\\clientes\\matusik\\proyectos\\geiserdiscos.com.ar\\dev\\v.02\\vendor\\symfony\\http-kernel\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php","line":148}}`

**Comment by geggleto** [comment]
Well it looks like your request does not match the route because it is a "GET" request instead of a "POST" request.

Where is this request being generated?

If it's on a form, add `method="POST"` to the form element.

**Comment by rossriley** [comment]
Trailing slash by the look of it.
Use `/newsletters/ajax/suscribe` rather than `/newsletters/ajax/suscribe/`

It's a quirk of Silex routing whereby for some BC reason they support trailing slash but only as an alias to a route without it.

**Comment by geggleto** [comment]
@rossriley The error clearly shows the problem. `Method Not Allowed (Allow: POST)`. The routing is fine, it's handling a GET request instead of a POST.

**Comment by pabbec** [comment]
Thanks @rossriley, it's work now! I'm curious: what do you call BC?

@geggleto thanks for you response. The request is generated in a form, controlled by jQuery that makes an POST request. The problem is that this post REQUEST was turned in a GET request.

I changed /newsletters/ajax/suscribe/ for /newsletters/ajax/suscribe and work fine.

**Comment by geggleto** [comment]
Cool :) That's a pretty weird transformation.

**Comment by rossriley** [comment]
@pabbec sorry for the jargon... BC = backwards compatibility.

From memory Silex in the early versions used to support trailing slashes and then the added the ability to nest routes via mount and changed the way they work... But they kept support for trailing slashes but only by 301 redirecting to the non-slash route.

**Comment by pabbec** [comment]
thanks @rossriley!

@geggleto yes, It is very weird. I have gone mad :(
