### ISSUE TITLE
[BUG] newly created record doesn't get a publish date

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5007]
Create a record. It gets `'publish'` status, but to publish date. Is it ok?
![2016-03-12 00-27-40](https://cloud.githubusercontent.com/assets/2145313/13711715/3f8924d6-e7ea-11e5-894f-c341fb73ba85.png)

It causes sorting problems and.. seems like it's logically incorrect.

**Comment by bobdenotter** [comment]
It should get a `datepublish` date, absolutely. Not a `datedepublish`, though. :-)

**Comment by GawainLynch** [comment]
Fixed in #5011

**Comment by Boorj** [comment]
Bopp indeed, my mistake )) was angry ande defocused that night)

**Comment by GawainLynch** [comment]
I know that feeling mate, I know that feeling :grin:
