### ISSUE TITLE
[BUG] Extra </tbody> in listing

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5008]
Looks like in listings (all listings) there's something redundant:
![2016-03-12 11-04-15](https://cloud.githubusercontent.com/assets/2145313/13720990/948005a6-e842-11e5-8857-411ef44e1192.png)

Probably the problem is here
![2016-03-12 11-06-10](https://cloud.githubusercontent.com/assets/2145313/13720993/a0bb12b6-e842-11e5-86cd-0c4316d35473.png)

Does it need investigation?

**Comment by rarila** [comment]
Duplicate of #5000

**Comment by SahAssar** [comment]
If this is a duplicate it should be closed, so I'm closing it.

**Comment by bobdenotter** [comment]
Fixed by #5022
