### ISSUE TITLE
[RFC] Notify user that entity is saved in clearer way

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5010]
The most popular demand from my clients is that they sometimes couldn't catch the moment when the record is saved. Probably we can make a notification more.. obvious?
Maybe some growl-style floating notification? Probably that could be related to error messages, which also could be shown with the same js library.

**Comment by SahAssar** [comment]
Just mentioning it here, but adding flash messages to JS actions was kinda-sorta-a-bit touched on in today's dev meeting in the context of errors. It'd probably have the same kind of solution as this ("soft" notifications show based on JS/ajax actions).

**Comment by Boorj** [comment]
If you want a 3rd party lib - i'm happy with http://notifyjs.com/
![2016-08-24_20-56-16](https://cloud.githubusercontent.com/assets/2145313/17933165/3baf7cc2-6a3d-11e6-9be6-802f87d3f776.png)

**Comment by Boorj** [comment]
It's still very hard to understand that something is saved. It can even be a little animation on button.
Or even - **if there's something unsaved - save button is green, otherwise - it's gray.**

**Comment by bobdenotter** [comment]
This was fixed in 3.2.

**Comment by Boorj** [comment]
@bobdenotter 
Some of my clients have problem: they press save in the bottom part (ajax), getting error and not see that, because that's in top part. 
So my request is : can we improve indication of that in clearer way?

**Comment by Boorj** [comment]
Also i think that "saved at 12.12.2012" is not the best way to indicate that something is saved. Sadly, but many bolt users have some problems with vision, so.. it's still too small. Any color indication could help.
