### ISSUE TITLE
[BUG] New Page in dashboard produces error 

### ISSUE THREAD

**Issue by jrapdx** [bolt/bolt#5012]
When trying to use the New Page feature, I get an error about a second after the New Page form appears.  

Details
-------
 - Relevant Bolt Version: 2.2.17
 - Install type: FreeBSD pkg
 - PHP version:  5.6.19
 - Used webserver: Nginx 1.7.12
 - For UX/UI issues: Firefox Nightly 48.0a

Reproduction
------------

Just installed Bolt on FreeBSD 10.3 and nginx.  When trying to use the New Page feature, I get an error a second after the New Page form appears.  Error is independent of database in use, Postgresql or sqlite.  However, data does not save to pgsql as there .  It will save to sqlite, but the saved page then shows error info written into the "slug" parameter.

Error message: Fatal error:  Call to undefined function Symfony\Component\HttpFoundation\filter_var() in /usr/local/opt/www/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/ParameterBag.php on line 297
 
The slug param = br-b-fatal-error-b-call-to-undefined-function-symfony-component-httpfoundation-filter-var-in-b-usr-local-opt-www-vendor-symfony-http-foundation-symfony-component-httpfoundation-parameterbag-php-b-on-line-b-297-b-br-call-to-undefined-function-symfony-component-httpfoundation-filter-var-error-type-whoops-exception-errorexception-message-call-to-undefined-function-symfony-component-httpfoundation-filter-var-file-usr-local-opt-www-vendor-symfony-http-foundation-symfony-component-httpfoundation-parameterbag-php-line-297	  

These messages appear re: use of the form to enter a new page.  It's the same in qupzilla (webkit) as firefox.  Not sure if this will reproduce on another system, I don't have the setup to test it.  

Error occurs with both Postgresql or sqlite.  

Data does not save to pgsql as there is a database error:
An exception occurred while executing 'INSERT INTO bolt_pages (datechanged, title, slug, image, teaser, body, template, status, templatefields, ownerid, datepublish, datedepublish, datecreated) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2016-03-13 02:01:32", "My new page", "br-b-fatal-error-b-call-to-undefined-function-symfony-component-httpfoundation-filter-var-in-b-usr-local-opt-www-vendor-symfony-http-foundation-symfony-component-httpfoundation-parameterbag-php-b-on-line-b-297-b-br-call-to-undefined-function-symfony-component-httpfoundation-filter-var-error-type-whoops-exception-errorexception-message-call-to-undefined-function-symfony-component-httpfoundation-filter-var-file-usr-local-opt-www-vendor-symfony-http-foundation-symfony-component-httpfoundation-parameterbag-php-line-297", "", "\<p>Teaser<\/p>", "\<p>Body text<\/p>", "", "draft", "[]", "1", "2016-03-13 02:00:41", null, "2016-03-13 02:01:32"]: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(128) 

It does save to sqlite, but the saved page then shows error info written into the "slug" parameter per above.  Obviously no new page is added when pgsql is used.  With sqlite the page is added, but the weird "slug" interferes with navigation.

Screenshot:
![bolt-error](https://cloud.githubusercontent.com/assets/17805424/13726476/cb09e96c-e87d-11e5-89c1-16ae3a2007f2.jpg)

**Comment by GawainLynch** [comment]
This is your PHP set up.

You need to install the PHP Filter modules (probably a package called `php-filter` or similar on FreeBSD`).

The database error is directly related as `ParameterBag::filter()` function is getting called and throwing that exception.
