### ISSUE TITLE
'Malformed JSON response' while checking Extensions

### ISSUE THREAD

**Issue by awrog** [bolt/bolt#5015]
I cannot check nor install extensions.
Currently using Bol 2.2.19
Since several updates ago (sorry I cannot be more specific) I receive the following error:
Extras -> View / install Estensions
![extend bolt bolt_2016-03-13_15-03-57](https://cloud.githubusercontent.com/assets/12153667/13729093/efa5e17c-e92c-11e5-92be-7ea8f4952463.png)

After clicking the button [Run all Updates] the following erros are shown

Warning:  is_dir(): open_basedir restriction in effect. File(/etc/pki/tls/certs) is not within the allowed path(s): (/usr/share/php:/home/regenboogkerkhilversum.nl/:/usr/share/pear:/usr/sbin:/usr/bin:/bin:/tmp:/etc/phpmyadmin:/usr/lib/php4:/usr/lib/php5:/opt/ioncube/lib) in /home/regenboogkerkhilversum.nl/public_html/muziek/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914

Warning:  is_dir(): open_basedir restriction in effect. File(/etc/ssl/certs) is not within the allowed path(s): (/usr/share/php:/home/regenboogkerkhilversum.nl/:/usr/share/pear:/usr/sbin:/usr/bin:/bin:/tmp:/etc/phpmyadmin:/usr/lib/php4:/usr/lib/php5:/opt/ioncube/lib) in /home/regenboogkerkhilversum.nl/public_html/muziek/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914

Warning:  is_dir(): open_basedir restriction in effect. File(/etc/ssl) is not within the allowed path(s): (/usr/share/php:/home/regenboogkerkhilversum.nl/:/usr/share/pear:/usr/sbin:/usr/bin:/bin:/tmp:/etc/phpmyadmin:/usr/lib/php4:/usr/lib/php5:/opt/ioncube/lib) in /home/regenboogkerkhilversum.nl/public_html/muziek/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914

Warning:  is_dir(): open_basedir restriction in effect. File(/usr/local/share/certs) is not within the allowed path(s): (/usr/share/php:/home/regenboogkerkhilversum.nl/:/usr/share/pear:/usr/sbin:/usr/bin:/bin:/tmp:/etc/phpmyadmin:/usr/lib/php4:/usr/lib/php5:/opt/ioncube/lib) in /home/regenboogkerkhilversum.nl/public_html/muziek/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914

Warning:  is_dir(): open_basedir restriction in effect. File(/usr/ssl/certs) is not within the allowed path(s): (/usr/share/php:/home/regenboogkerkhilversum.nl/:/usr/share/pear:/usr/sbin:/usr/bin:/bin:/tmp:/etc/phpmyadmin:/usr/lib/php4:/usr/lib/php5:/opt/ioncube/lib) in /home/regenboogkerkhilversum.nl/public_html/muziek/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914

**Comment by bobdenotter** [comment]
Hi awrog, 

In config.yml, locate the following line: 

```
debug_error_level: 8181 # equivalent to E_ALL &~ E_NOTICE &~ E_DEPRECATED &~ E_USER_DEPRECATED &~ E_WARNING
```

Make sure it's set to `8181`, and not to `6135`.

**Comment by awrog** [comment]
That's fast!
That solved it, great!

**Comment by SahAssar** [comment]
Closing since fixed!
