### ISSUE TITLE
[RFC] Vulnerability in the thumbnail generation system

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#5016]
Bolt-based site can be forced to create a huge amount of previews using a thumbnail generation address, for example:
````
http://example.com/thumbs/200x150c/news/02/03/2016/17852851.jpg
````
Using a simple cycled cURL request replacing a width or height of a desired thumbnail attacker can significantly decrease performance of a site and also force it to over-use a hard drive requesting large-scaled images. Possible solution: add some fast hash as a query parameter to request, for example md5(image.width + image.height + image.url + secret).

**Comment by bobdenotter** [comment]
Hi C4Grey, 

This is a duplicate of #3703. If this is something you'd like to help on fixing, please join us in the other thread. :-)
