### ISSUE TITLE
[Bug] Error on save contentype. The “timepublish” input is not correct on Server with timezone UTC

### ISSUE THREAD

**Issue by libastian** [bolt/bolt#5025]
## Details
- Relevant Bolt Version: [ 2.2.19 ]
- Install type: [ Github checkout |  Composer install ]
- PHP version: [  5.5  ]
- Used webserver: [ Apache2  ]
  - For UX/UI issues: [ Chrome, Versión 45.0.2454.101 (64-bit) ]
## Reproduction

1.- Set the “timezone:UTC” in my config.yml.
2.- Edit a content type from a computer set in another timezone (e.g.: “CET”).
3.- When saving my content type, Bolt saves in DB the data of the "timepublish" input, without converting to the one indicated in the configuration file ("UTC" format).

I think this is a bug, right?

Note: The "datechanged” is saved correctly in the BD every time you update.

**Comment by GawainLynch** [comment]
This should be fixed in 3.2 & further so in 3.3 (due for release a.s.a.p) … in the not-so-unusual event that I am wrong, please feel free to reopen with additional data and we'll do our best to get it covered off quickly.
