### ISSUE TITLE
 [Language] parsing error on messages.yml 

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5027]
This 2 lines from file messages.en_GB.yml are creating an issue with translations downloaded from crowdin. They are causing parse errors
`Unable to parse the YAML translations`

Original 

```
"The database needs to be updated/repaired. Go to 'Configuration' > '<a href=\"%link%\">Check Database</a>' to do this now.": "The database needs to be updated/repaired. Go to 'Configuration' > '<a href=\"%link%\">Check Database</a>' to do this now."
"The field %field% has been changed to \"%newValue%\"": "The field %field% has been changed to \"%newValue%\""
```

When downloaded as translation those lines are changed by Crowdin to (note the escaped signs and an |- on the first string):

```
"The database needs to be updated/repaired. Go to 'Configuration' > '<a href=\\"%link%\\">Check Database</a>' to do this now.": |-
  The database needs to be updated/repaired. Go to 'Configuration' > '<a href="%link%">Check Database</a>' to do this now.
"The field %field% has been changed to \\"%newValue%\\"": 'The field %field% has been changed to "%newValue%"'
```

I have to remove both lines so translation files can work on sites.

Note: Crowdin can manage single and double quotes but this lines are not working. Maybe because there are many quotes in each string or is there an error i'm not seeing now?
How can we solve this? Can we get cleaner string (reduce escaped or all single quotes) before asking Crowdin platform for support?
- Relevant Bolt Version: [master ]
- Install type: [ Zip/tarball install ]
- PHP version: [ 5.4 ]
- Used webserver: [ XAMPP ]

**Comment by bobdenotter** [comment]
The `|- ` is valid YML. It's a multiline string: http://www.yaml.org/spec/1.2/spec.html

Could you do some experiment to see if the problem is in the 'key' or 'value' part.. I.e. would this work: 

    "foo": "this 'is' bar"

but this perhaps breaks: 

    "this 'is' foo": "bar" 

If the keys can't have the extra quotes, we can work around that, I bet. :-)

**Comment by rarila** [comment]
@bobdenotter Using keybased keys isntead ;-)

``"`` should be replaced with typographic correct ones like ``„`` and ``“`` anyway

**Comment by bobdenotter** [comment]
> " should be replaced with typographic correct ones like „ and “ anyway

Yes, but obvs only in the 'value' part. 

(and yes, keybased would be better, but takes time to convert.. However, if there's a finite number of breakages, we can fix them quicker)

**Comment by horus68** [comment]
testing a dummy file foo.yml

Uploaded contents
```
"foo": "this 'is' bar"
"this 'is' foo": "bar" 
"this 'is' foo": "this 'is' foo"
```

get downloaded as
```
---
foo: "this 'is' bar"
this 'is' foo: bar
this 'is' foo2: "this 'is' foo2"
```

**Comment by bobdenotter** [comment]
Ok, seems like the assumption is correct: We shouldn't use `'` in "keys" :-)

**Comment by horus68** [comment]
Note that this is working fine:
```
"Content '%title%' could not be deleted.": "Content '%title%' could not be deleted."
"Content '%title%' has been changed to '%newStatus%'": "Content '%title%' has been changed to '%newStatus%'"
```

**Comment by horus68** [comment]
Can you paste me a correct version with the „ and “ ?

**Comment by bobdenotter** [comment]
Forget the typographicallt correct „ and “ for now. We should perhaps add them some day, but for now we should fix this issue. 

Ok, if those two work, the problem perhaps lies in the `\` backslashes?

**Comment by rarila** [comment]
Those are language dependant. The ones I have posted are the German variants.

**Comment by rarila** [comment]
@bobdenotter why not fix it now in a correct way instead of workarounds. I guess there are not to many of them and replacing them is just a matter of search and replace.

**Comment by rarila** [comment]
@horus68 btw, I guess all translations need some regenerating as for sure many changes aren't reflected

**Comment by bobdenotter** [comment]
Rarila: Yes, replacing the breaking ones shouldn't be too hard, but first we'd need to pinpoint _what_ is breaking ;-)

**Comment by rarila** [comment]
@bobdenotter thought it were the ``\`` inside keys. Also a matter of search and replace as we don't need a string in the key that is identical to the english one.

So as their parser tells us the problematic lines I would just run it, search/replace the offending keys until we are green

**Comment by bobdenotter** [comment]
> thought it were the \ inside keys

As they say: "To assume is to make an ASS out of U and ME". I'd like to know for sure. ;-)

> So as their parser tells us the problematic lines I would just run it, search/replace the offending keys until we are green

That sounds terribly pragmatic of you. :+1:

**Comment by horus68** [comment]
new foo file, removing `\` inside keys works fine
`"The field %field% has been changed to %newValue%": "The field %field% has been changed to %newValue%"`

downloaded as
```
---
"The field %field% has been changed to %newValue%": 'The field %field% has been changed to %newValue%'

```

**Comment by rarila** [comment]
So removing ``\`` from keys and setting correct typographic quotation marks in the data part should fix the issue?!

**Comment by horus68** [comment]
3 other lines with issues
I found them on the section "93 untranslated messages" after I make them translatable by duplicating key part to value part instead of # sign


`"Detected Bolt version change to <b>%VERSION%</b>, and the cache has been cleared. Please <a href=\"%URI%\">check the database</a>, if you haven't done so already.": "Detected Bolt version change to <b>%VERSION%</b>, and the cache has been cleared. Please <a href=\"%URI%\">check the database</a>, if you haven't done so already."`

`"Menu item property \"add\" is deprecated. Use \"#\" under \"param\" instead.": "Menu item property \"add\" is deprecated. Use \"#\" under \"param\" instead."`

`"Unfortunately, no content could be found. Try another page, or go to the <a href=\\"%paths_root%\\">homepage</a>.": 'Unfortunately, no content could be found. Try another page, or go to the <a href="%paths_root%">homepage</a>.'`

**Comment by rarila** [comment]
I see ``\"`` in there

**Comment by rarila** [comment]
And you see another problem of our translations here (I wanted to tackle in the next version).No HTML should be allowed in translations. It simply doesn't belong there and makes many things difficult.

**Comment by SahAssar** [comment]
Okay, so turning back the clock (which is needed when visiting "old issues island") @rarila how feasible is it to fix this in a proper way like you mentioned in [your comment](https://github.com/bolt/bolt/issues/5027#issuecomment-196480519) ?

**Comment by rarila** [comment]
First, using typographically correct characters would help a lot.

Then the translation system has to be extended to allow a parameter for the replacement placeholder. The call from the example abovce would change from

```php
$msg = Trans::__(
   "… Go to 'Configuration' > '<a href=\"%LINK%\">Check Database</a>' to do this now.",
   ['%link%' => $this->urlGenerator->generate('dbcheck')]
   );
```
to something like
```php
$msg = Trans::__(
   "… Go to 'Configuration' > '%LINK{Check Database}%' to do this now.",
   ['%LINK{' => '<a href="' . $this->urlGenerator->generate('dbcheck') . '">%LINK%</a>']
   );
```

. So we first would escape the complete string and then add the html part programmatically.

Next thing we need is a way to mark some text in a logical way to remove the clutter in the way things are done. E.g.

```
'The field %field% has been changed to "%newValue%"'
```
could be end up in 
```
'The field %*field*% has been changed to %<newValue>%'
```
and finally translated to something like
```html
The field <em>field</em> has been changed to <mark class="value">newValue</mark>'
```
which can be styled and even typographically correct apostrophes could be added (even with css via :before and :after).
