### ISSUE TITLE
Wampserver fails to install master - Configuration autodetection failed

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5028]
- Bolt Version: [ master ]
 - Install type: [ zip from Github master ]
Wampserver version 2.5
(fresh install but running ok)
- Apache 2.4.9 (Win32)
 - PHP version: [ 5.5.12]

installing under localhost gives this error on first screen

```
Fatal error: Uncaught exception 'Bolt\Exception\LowlevelException' with message 'Configuration autodetection failed because The file vendor/autoload.php doesn't exist. Make sure you've installed the required components with Composer.' in F:\wamp\www\rcboltmaster\app\bootstrap.php on line 54
( ! ) Bolt\Exception\LowlevelException: Configuration autodetection failed because The file vendor/autoload.php doesn't exist. Make sure you've installed the required components with Composer. in F:\wamp\www\rcboltmaster\app\bootstrap.php on line 54
```
![2016-03-15 18_27_02-mozilla firefox](https://cloud.githubusercontent.com/assets/3055443/13789427/d3fe3dce-eadb-11e5-9007-1b706addec80.png)

**Comment by GawainLynch** [comment]
You need to run `composer install` in the web root.

**Comment by horus68** [comment]
How? I'm on windows

**Comment by rarila** [comment]
[hmm](https://getcomposer.org/doc/00-intro.md#installation-windows)

**Comment by GawainLynch** [comment]
This has been required for all Bolt versions, [see the v2 docs](https://docs.bolt.cm/installation#option-3-developer-way-using-git-and-composer).

If you clone the Bolt git repository, it does not, should not and will not, include the libraries that Bolt needs to run.

If you need an off-the-shelf way of running Bolt, the archive and Composer install methods are the way to do this… git clones are for people who are developing :smile:
