### ISSUE TITLE
[RFC] Typografically correct language files

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5040]
- Relevant Bolt Version: [ master ]

Proposal to mass edit en_GB language files to:
- Use typografically correct apostrophes on en_GB
- Use typografically correct quotation marks on en_GB contenttypes

There is a PR for this (mixed with some other changes) by @rarila user:
https://github.com/bolt/bolt/pull/5031

**Comment by GawainLynch** [comment]
Translation update in progress, but not scheduled to land until 3.4.
