### ISSUE TITLE
[RFC] Switch to non nested output for keybased translations

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5041]
Actual language files have different output for strings. Using just one output format would make languages easier to work with.
A non nested format should be used so it will also make it easier to mass edit.
Translations already done will not be lost on the string format changes.

 - Relevant Bolt Version: [ master ]

Note: There is a PR (with other changes) that changes the language files output:
Regenerated translation files by @rarila 
 · Pull Request #5031 · bolt/bolt - https://github.com/bolt/bolt/pull/5031

**Comment by GawainLynch** [comment]
100% in support of this! There is contention over the typography changes suggested in #5040 that need to be settled, but if we can just get the typography parts delayed to a latter post-RFC PR we can get that in a.s.a.p.

**Comment by SahAssar** [comment]
Fixed in #5031 IIRC, so closing
