### ISSUE TITLE
[RFC] Translate with an online translation platform

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5042]
On translations for bolt core files I found that some needs to be done to make them better for the translators. This is my proposal for a change and it can be done with no mess and in any time frame.
 
### The actual scenario
- Translations are done by individual users on their own system/computers. 
- Almost all are very incomplete and also many files are missing.
- Some translations are contributed back to Github and probably others are not, it depended on translators using Github to PR those translations
- Translating directly on Github its difficult for translators, with no validation tools, no memory translation, and so on
- Translators don't want to be coders and shouldn't be required to know how to use Github and other sync/editing tools as they will do less translations!

**This is my say as a translator involved in many software translations**

### What "**we the translators**" usually need:
- An online platform to manage languages and translations
- A repository for unfinished translations so they could pick up old languages if in need
- Online tools with translation memory to avoid repetitive tasks
- Online tools translation assistance to act as suggestions
- Be able to download translations anytime we need and ready to be used in their own systems
- A place to share collaboration with other translators and proofreaders

### What any software needs from translations
 (and plain users expect to get)
- They work with the software
- They are updated / validated by teams

### Additionally software managers do need:
- Get users collaboration on translations
- Changes done to master language are reflected on translations
- Updated/download files using API/automated systems

## My Proposal: use an specialized online platform for translations
Do people agree on that or not?
This can be done in the next minute or in some time in the future. I can take the work required to the make the online platform ready for translators and send translations done back to Bolt Github.

Note: I'm not talking here on solutions but want to hear on the need of working like that.
I will leave online solutions for later. For the record there are free online platforms that can be used for it and some of them do not involve any change on the code.

# Please post your questions and considerations but also reply to these questions :
(so its easier to understand options from all)

1. How translators should work?
2. What is the time-frame for your proposal?

**Comment by GawainLynch** [comment]
Side note: Added this to the agenda for [Tuesday's dev meeting](https://github.com/bolt/bolt/wiki/Dev-meeting-2016-03-22)

**Comment by horus68** [comment]
This is a comment to be edited with a summary on the comments done here 
(so I don't edit my main proposal)

**Comment by horus68** [comment]
Actual workflow is explained here:
Adding a translation · bolt/bolt Wiki - https://github.com/bolt/bolt/wiki/Adding-a-translation

**Comment by GawainLynch** [comment]
> Actual workflow is explained here:

That is literally from Bolt 1 :smile: 

So yeah, this area really needs a lot of work.

**Comment by SahAssar** [comment]
Merging into #3490, sorry @horus68
