### ISSUE TITLE
[RFC] Missing language strings

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5043]
[BUG]  - Relevant Bolt Version: [ master ]

There is a PR that includes "missing language strings"
Those missing language strings should be added to the master language in its own PR
https://github.com/bolt/bolt/pull/5031

**Comment by GawainLynch** [comment]
@rarila Aren't these auto-added to the translation files?

**Comment by bobdenotter** [comment]
Missing strings are (currently) added as you go into the backend screen to edit the language file in there. 

If/when we move to a new process we should probably make sure we can keep this. Either as a fallback, or as an easy way to add missing strings.

**Comment by GawainLynch** [comment]
Oh right… I see the differentiation now.

**Comment by SahAssar** [comment]
Is this still relevant? If it is, do I understand things correctly that "all" one needs to to do to generate the missing stings is to visit every possible page once and the PR the changes in that translation file?

**Comment by GawainLynch** [comment]
It is. @rarila was going to hack up a nut command to parse the strings and sync each language. I have something hacky too, so as @bobdenotter says, we just need to do as normal and try to not make things harder as we move :smile:
