### ISSUE TITLE
[RFC] Language tag for Github

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5044]
Relevant Bolt Version: [ all ]
Any Issue or PR posted in Bolt Github that involves en_GB language changes (new, remove or edit strings) should be tagged as "language" so its easy to be filtered by translators

**Comment by GawainLynch** [comment]
Added a "Translation" label… @SahAssar this is probably most relevant for your OCD.

**Comment by bobdenotter** [comment]
I see we have a "translation" label. :+1:

**Comment by bobdenotter** [comment]
(and, Gawain beat me to it. :beers:)

**Comment by horus68** [comment]
Language is different from translation!
Language: en_GB only (could involves code)
Translation: all languages (only involve translators)

**Comment by GawainLynch** [comment]
> Language is different from translation!

In this case no, it is not.

The noun, verb, and pronoun that is "translation" we use to describe a category. That noun describes classes, processes and behaviours around what you describe as a "language".
