### ISSUE TITLE
Whoops: Maximum function nesting level of '100' reached, aborting! when accessing a content-type with no items yet

### ISSUE THREAD

**Issue by sintemaa** [bolt/bolt#5049]
When accessing a content type in the backend for which no items exist yet, I get a Whoops error: Maximum function nesting level of '100' reached, aborting! Adding an item solves the problem so it seems to be related to no items yet

E.g. localhost/mysite/bolt/overview/news gives this error

> D:\html\mysite\vendor\twig\twig\lib\Twig\Node.php
```
     *
     * @param string $name
     *
     * @return mixed
     */
    public function getAttribute($name)
    {
        if (!array_key_exists($name, $this->attributes)) {
            throw new LogicException(sprintf('Attribute "%s" does not exist for Node "%s".', $name, get_class($this)));
        }
```

I had a little look around but this code goes over my head.

Bolt version: 2.2.19-pl1

**Comment by GawainLynch** [comment]
Xdebug issue triggered by Twig.

Setting `xdebug.max_nesting_level=1024` in your php.ini will resolve it for you.

**Comment by sintemaa** [comment]
Wow you're fast. That indeed solved it

**Comment by GawainLynch** [comment]
Hehe… Not fast enough, that took 68 seconds :grin:
