### ISSUE TITLE
[BUG] Can't login or save a record, if having obsolete NOTNULL columns

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5062]
_Started in #4817, but i can see it deserves a separate issue._

Some day i created a new bolt project, when there was `shadowtoken` and `shadowpassword` and they had `NOTNULL` constraint. And when i updated and tried to login, it tries to save my user's record (update the number of attempts to `users` table) and sqlite constraints don't let me do that.
And login fails.
Also had the similar problem - when couldn't save a record with notnull templatefields.

### The problem
I think it's bad, if such an exception that could be cought is given back as uncaught problem. That's not a single case, i suppose. So...

### Suggestion
Maybe we could catch the exception with notnull constraints? And suggest to update database. And if the problem goes with `users` table, and since you can't login -  automatically update (i know it's probably bad) without a need to login? Or at least assume that a database with not proper constraints is obsolete and needs to be updated.
Any other solutions are welcome.

**Comment by GawainLynch** [comment]
Was the database created on v2 or an early master?

**Comment by Boorj** [comment]
I think on 2.3 early master, if it matters.

**Comment by bobdenotter** [comment]
Please verify if this is still the case if setting up a new database. A lot has changed, since those early 2.3 days.

**Comment by Boorj** [comment]
The question is next: if you create a technical column nowdays with constraints, and if it will be removed in future - will we got the same problem?

**Comment by bobdenotter** [comment]
If we do, we'll deal with it then.

**Comment by Boorj** [comment]
Why wasn't it done before with 2.3? Yeah, i know, that is alfa..
But.. probably we can include a check for any improper constraints into the db_check ?

**Comment by SahAssar** [comment]
Sorry, but we don't really test or ensure that alpha to alpha upgrading works, since alpha probably shouldn't be used in production or a persistent way unless one is willing to deal with these issues.

Closing, feel free to reopen if you experience it when upgrading from 2.2 to a released 3.0.
