### ISSUE TITLE
[BUG] Dashboard settings menu broken links

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#5063]
Bolt master, github checkout.
i have bolt installed in a subdir, and some of the links under settings > config seem broken.
I have my dashboard under: ``local.dev/subdir/bolt``.

The Settings > Config > Main configuration, correctly links to: ``local.dev/subdir/bolt/file/edit/config/config.yml``
But others, like users, link to the TLD somehow
``local.dev/bolt/users``

I think it can be traced to ``src/menu/AdminMenuBuilder`` which in some 
cases uses ``$path = $this->rootEntry->getUri() . '/users'`` and in other cases
uses ``$app['url_generator']->...``

**Comment by GDmac** [comment]
This also affects the extensions screen ``/bolt/extend`` 
as it tries to load ``/bolt/extend/installed``

**Comment by bobdenotter** [comment]
Fixed in #5136
