### ISSUE TITLE
Schema manager isCheckRequired always returns true

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#5065]
While looking at optimising speed i noticed that storage event listener takes some time.
Inside StorageEventListener::schemaCheck() a dump($expired) always outputs ``true``.
Even immediately after a dbcheck in the backend.

Maybe i'm missing something but schemaCheck seems to be also called
for every frontend page as well (overhead)

Bolt master 3.x

**Comment by GawainLynch** [comment]
Yeah… just checked, something has changed recently and the time stamp file isn't getting saved

**Comment by GawainLynch** [comment]
Do you have any extensions installed BTW, and have you run and dbcheck/update?

**Comment by GDmac** [comment]
Nope, no extension
(ps. clicking extensions on dashboard pops up "unexpected token"
because of the issue #5063 )

**Comment by GDmac** [comment]
Note / addendum
Seems timer::setCheckRequired() which hard sets expired to ture,
is called from src/Config.php line 94 because if (!$this->loadCache()) ...

**Comment by GDmac** [comment]
And indeed, Config.php::loadCache() 
the extensions.yml is not found, resulting in NOT $this->cachetimestamp > max($timestamps)
and returning false for loadcache()
Setting extensions.yml to 0 fixes the call
https://github.com/bolt/bolt/blob/master/src/Config.php#L1144

**Comment by GawainLynch** [comment]
Fixed in #5066
