### ISSUE TITLE
Ctrl-S / ⌘-S doesn't work when CKeditor field has focus. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5074]
On "edit page" screens, you can use Ctrl-S / ⌘-S to save the page, _unless_ a CKeditor wysiwyg field has focus, because it intercepts the keypresses. 

There is a workaround for this, as pointed out by @kehugter in #717: 

> Oh, right. Is that intended? IMO the most useful time to hit CTRL-S is while CKeditor is focused.
> [Bypassing CKeditor key bindings](http://stackoverflow.com/questions/3245797/how-to-use-custom-keyboard-shortcuts-within-ckeditor-with-jquery) looks non-trivial but not impossible.

**Comment by rossriley** [comment]
Last I tried it also doesn't work on Markdown and Textarea fields too.

**Comment by bobdenotter** [comment]
I was pretty sure it _used_ to work in `<textarea>` fields, but it currently doesn't. In Markdown fields it also doesn't work.

**Comment by SahAssar** [comment]
This seems like one of those UI/UX issues that we will get to sooner or later, but it won't be because of this.
