### ISSUE TITLE
[RFC] improvements for basetheme - add a showcase.twig to base-2016

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#5077]
The `{{ fields() }}` tag has a very unclear usecase and it actually clouds the example function of base-2016

Therefore I propose that a `showcase.twig` template is created that shows the usage of every field that is in the showcase in a straighforward way - so not with loops and variables like in https://github.com/bolt/bolt/blob/release/2.2/theme/base-2014/record.twig
```
            {% for key,value in record.values if key not in ['id', 'slug', 'datecreated', 'datechanged', 'datepublish', 'datedepublish', 'username', 'status', 'title', 'subtitle', 'ownerid', 'templatefields'] %}
                {% if record.fieldtype(key) == "image" and value != "" %}

                    {% if record.image!="" %}
                        <div class="large-4 imageholder">
                            <a href="{{ image(value) }}">
                                <img src="{{ thumbnail(value, 640, 480) }}">
                            </a>
                        </div>
                    {% endif %}
                {% else %} ....
```

But directly like:
```
                    {% if showcase.image!="" %}
                        <div class="large-4 imageholder">
                            <a href="{{ image(showcase.image) }}">
                                <img src="{{ thumbnail(showcase.image, 640, 480) }}">
                            </a>
                        </div>
                    {% endif %}
                    {% if showcase.multiselect!="" %}
                       {{ dump(showcase.multiselect) }}
                    {% endif %}
                    {% if showcase.geolocation.latitude is not empty %}
	                    <div class="imageholder-wide">
	                        <img src="http://maps.googleapis.com/maps/api/staticmap?center={{ showcase.geolocation.latitude }},{{ showcase.geolocation.longitude }}&amp;zoom=14&amp;size=617x300&amp;sensor=false&amp;markers={{ showcase.geolocation.latitude }},{{ showcase.geolocation.longitude }}">
	                    </div>
	                    <p>{{ showcase.geolocation.formatted_address }}</p>
	                {% endif %}
```

The `showcase.twig` does not need to be linked in the showcase content type in contenttype.yml.dist / contenttype.yml - but it should have some comments on how to do that in the head of the file.

Details
-------
 - Relevant Bolt Version: 3.0 / master

**Comment by SahAssar** [comment]
This would allow newcommers to have a reference to show them how to use different fields, and we could also show how to use bolt functions like `localdate`, so I'm all for this :+1:

**Comment by bobdenotter** [comment]
Nope. This is what `fields()` is for. Making a separate template for that will just be duplicating effort.

**Comment by jadwigo** [comment]
Then why does `{{ fields() }}` have options at all?

**Comment by bobdenotter** [comment]
Why not? Those options are for doing some of the stuff you describe above.

There's documentation now, by the way: https://docs.bolt.cm/master/fields-tag

**Comment by SahAssar** [comment]
Reopening since the fields template isn't/won't be accessible from a "normal" (one-click/automated) install.

**Comment by SahAssar** [comment]
As part of #5145 it will include the _sub_fields template in the theme folder, and if so we could include a comment to that effect before the `{{fields()}}` call. That would alleviate some of the concerns raised here.
