### ISSUE TITLE
[BUG][UX] back-end publish process quirks

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#5085]
The process of publishing from the content listing has some weird quirks.

The first two steps are normal
![image](https://cloud.githubusercontent.com/assets/1488214/14045886/fecf3dea-f29d-11e5-9ca8-92e4b0155eaa.png)

![image](https://cloud.githubusercontent.com/assets/1488214/14045892/037e1000-f29e-11e5-8827-8b5d3a587182.png)

But the third step tells me "there is no undo" which is just FUD for this action.
![image](https://cloud.githubusercontent.com/assets/1488214/14045914/1ada3d14-f29e-11e5-9284-4205827da277.png)

The real quirk comes after I confirm - only the published records are displayed and I have to refresh the page to get the other records back. The _pager_ is hidden too.

![image](https://cloud.githubusercontent.com/assets/1488214/14045967/6293fbf4-f29e-11e5-9ac6-a33e5203458e.png)

Details
-------

 - Relevant Bolt Version: 3.0 / master
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Apache
 - For UX/UI issues: Chrome Version 49.0.2623.87 (64-bit) Linux

**Comment by anketwokings** [comment]
Are you sure you want to publish? THERE IS NO UNDO! :')

**Comment by SahAssar** [comment]
Seems like the "only the published records are displayed" after publish is fixed, but the FUD remains...
