### ISSUE TITLE
BUG: Server error 500

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5088]
Getting a server error 500 after clean install of Bolt 3.0 beta 1. Didn't have any problems with the alfa 8 version. Using PHP 5.6 and Apache 2.2. Also tried NGINX with the same result. No other clues to what it could be about.

I expect to find the "create new user" page when visiting the web address in the browser.

Details
-------

 - Relevant Bolt Version: 3.0 beta 1
 - Install type: Zip/tarball install (clean install)
 - PHP version:  5.6
 - Used webserver: Apache 2.2

**Comment by GawainLynch** [comment]
Have you checked the file permissions?

**Comment by bobdenotter** [comment]
Check the error log in either nginx or apache. It'll probably say what the error is.

**Comment by mattiaslundback** [comment]
I have found the problem now. There is a new path for bootstrap.php now. There was no index.php in the download map so I used the old one. But that didn't work.

But I guess there should be an index.php in the download folder.

**Comment by bobdenotter** [comment]
@mattiaslundback Have you read the documentation? https://docs.bolt.cm/master/installation/install-command-line

The default process changed a bit.

**Comment by mattiaslundback** [comment]
A small, but important, detail that I missed: "To do this, configure your webserver to use the public/ folder as the webroot. For more information about this, see the pages on configuring Apache or Nginx."

Thanks a lot. Probably not a bug then. I will se how it all works out. But I might need some more information on the latter part. Using a graphical user interface (Synology) for the webserver. Maybe I can get back to you in the forum later if it doesn't work?

**Comment by bobdenotter** [comment]
Sure thing! Beta is all about getting feedback! Closing this issue for now. :-)
