### ISSUE TITLE
[RFC] Widgets with context

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5091]
Right now, widgets don't have access to any context. That makes them only 90% awesome because on locations like the `editcontent_*` ones, having the context would give you much more possibilities.

I already talked with @bobdenotter about that and he said we can make that optional. That means when the user wants access to the context, defer loading and caching will be turned off so there are no unexpected results.

I don't know how difficult it is to implement that, but I would love to see it added before we release 3.0.0 stable because that makes them 100% complete.

Details
-------

 - Relevant Bolt Version: 3.0 | master
 - Install type: yolo
 - PHP version: yolo
 - Used webserver: yolo

**Comment by GawainLynch** [comment]
> Right now, widgets don't have access to any context. 

This is very deliberate and one of the original design decisions.

**Comment by GawainLynch** [comment]
> I don't know how difficult it is to implement that, but I would love to see it added before we release 3.0.0 stable because that makes them 100% complete.

No, sorry. They will not be changed for 3.0.0… 3.1.0 would be the earliest.

**Comment by bobdenotter** [comment]
One thing we _could_ do, is make the context _optional_, but that would mean that for that specific widget, we need to disable `caching` and `deferred`.

Phillipp: For your usecase, right now.. Can you not get the info you need from `\Request`?

**Comment by PhillippOhlandt** [comment]
@gawainlynch then I have to wait for 3.1 until I can use the widgets and all the extensions won't work with 3.0. 

@bobdenotter then I have to fetch all that data again. Not a fan of recoding the backend just to show a button.

**Comment by GawainLynch** [comment]
> then I have to wait for 3.1 until I can use the widgets and all the extensions won't work with 3.0.

Ç'est la vie. :smile:

**Comment by PhillippOhlandt** [comment]
But really, widget don't make sense without context for me. It's like having the Post Save Event without the record.

I can't think of a single use-case where someone want to include some things on the editcontent page without relating to the actual record that will be created/edited.

**Comment by SahAssar** [comment]
Will be fixed in https://github.com/bolt/base-widget/pull/7, no?

**Comment by bobdenotter** [comment]
@SahAssar Well, yes and no.. There's a workaround for it, but it would be good to check if this is the best way to do it. Regardless of the outcome of that, it'll need to be documented.

**Comment by bobdenotter** [comment]
Documented in https://github.com/bolt/docs/pull/462
