### ISSUE TITLE
[BUG] Admin sidebar URL malformed for some links

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5095]
Sidebar URL malformed for some links.
Lets say a site created under Wamp server, plain install, no dummy contents
```
Local folder: F:\wamp\www\rcbolt3
Admin URL: http://localhost/rcbolt3/public/bolt
```

Some links on the sidebar  do not include full URL (they are in red on the image included)
![2016-03-29 11_45_01-inicio](https://cloud.githubusercontent.com/assets/3055443/14105843/f5456334-f5a5-11e5-8360-3130f1e230e1.png)

This ones works fine
```
Pages - http://localhost/rcbolt3/public/bolt/overview/pages
Blocks - http://localhost/rcbolt3/public/bolt/overview/blocks
File Management - http://localhost/rcbolt3/public/bolt/files
Translations - http://localhost/rcbolt3/public/bolt/tr
```
This don't
```
Configuration - http://localhost/bolt/users
Extensions - http://localhost/bolt/extend
```
Note: the "Configuration" menu works for some submenus only)

If I edit the URL directly it works fine as in
```
Configuration - http://localhost/rcbolt3/public/bolt/users
Extensions - http://localhost/rcbolt3/public/bolt/extend
```

Details
-------

 - Relevant Bolt Version: [ 3.0.0 Beta 1 ]
 - Install type: [ Zip install | bolt-3.0.0-beta1.zip ]
 - PHP version: [ 5.5.12 ]
 - Used webserver: [ Wamp Apache 2.4.9 ]
- Plain install, no default data

**Comment by PhillippOhlandt** [comment]
duplicate to #5063
