### ISSUE TITLE
Some minor nitpicks in base-2016

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5097]
Some collected nitpicks for the base-2016 theme. 

 - Vertical rhythm is a bit sloppy, here: 

![screenshot 2016-03-29 21 50 23](https://cloud.githubusercontent.com/assets/1833361/14121550/53acc186-f5f8-11e5-82f1-dcdb3862e5ee.png)

 - Images could do with better margin in single pages: 

![screenshot 2016-03-29 21 51 11](https://cloud.githubusercontent.com/assets/1833361/14121593/763f5114-f5f8-11e5-8785-c4f50215d403.png)

 - Links are not recognisable: (please make them underlined, with a color)

![screenshot 2016-03-29 21 52 07](https://cloud.githubusercontent.com/assets/1833361/14121625/895f5302-f5f8-11e5-9a34-b829df78899b.png)

 - The pagination is _very_ bland. It might be a little more exiting. Perhaps with a sublte background, or an outline?

![screenshot 2016-03-29 21 54 19](https://cloud.githubusercontent.com/assets/1833361/14121697/ce987516-f5f8-11e5-95e4-92178e31733b.png)

 - In general, I think it's a bit _too_ white. Having one 'Spot color', and using that for links and the pager would be nice. Perhaps even make it configurable? 

- Entries in listing views could get some love: vertical rhythm, and the images should get a lightbox/popup/modal. Maybe use http://foundation.zurb.com/sites/docs/media-object.html ?

![screenshot 2016-03-29 21 57 17](https://cloud.githubusercontent.com/assets/1833361/14121842/5ce85ee4-f5f9-11e5-85bb-18f9b0dbe606.png)

 - Videos break the column (needs [flexvideo](http://foundation.zurb.com/sites/docs/flex-video.html) )

![screenshot 2016-03-29 22 09 12](https://cloud.githubusercontent.com/assets/1833361/14122254/3d2b3f52-f5fb-11e5-9e37-25069cec5ee5.png)

 - The 'boxed' layout mode has gone missing ;-)

(Some of these can be fixed in `bolt-foundation` as well, by the way. I'll work on either having changes to the theme flow back to that one, or i'll PR my relevant changes into `bolt/bolt`)

**Comment by bobdenotter** [comment]
@SahAssar: FYI, this fixes the quirk with the video: https://github.com/bobdenotter/bolt-foundation-theme/commit/b1e85461e5d69fe2baac653e4de4800d0ae34c03

**Comment by SahAssar** [comment]
@bobdenotter I got all of the points fixed except the color one here: https://github.com/SahAssar/bolt/commit/31ecc51f514571c6aa43a36887fb8b74d00c3816 so I'll PR tomorrow.

**Comment by bobdenotter** [comment]
Cool! Looking forward to it.. :-)

**Comment by psychonaut** [comment]
Hi, I've got some issues with theme (fonts), should I add them there or should I create new ticket?

**Comment by SahAssar** [comment]
@psychonaut Whichever way you prefer is fine :smiley:

**Comment by psychonaut** [comment]
Ok, so for example header fonts don't have polish characters.
![carrie fisher ksiezniczka po przejsciach zuzanka blogitko](https://cloud.githubusercontent.com/assets/807289/14452642/48def952-0090-11e6-99e6-f92c698e77f3.png)

**Comment by kempust** [comment]
There are some issues with the topmenu

- The black top menu for mobile devices flashes visible when displaying on desktop, fix is at bottom of this page - http://foundation.zurb.com/sites/docs/responsive-navigation.html
- The top menu stays horizontal when viewing on a mobile chopping of all bar the first couple of items, fix is to add **vertical medium-horizontal** to <ul> at bottom of _sub_menu.twig.  When the top menu is vertical, sub menus don't display properly, I am still looking into this.

`
<ul class="dropdown menu vertical medium-horizontal {{ class|default('') }}" data-dropdown-menu>
`

**Comment by SahAssar** [comment]
@psychonaut Thanks, I'll switch it out for one that has the full latin-extended charset. Do you have any suggestions for a font that would fit the purpose and is on Google Fonts?

@kempust Thanks, do you want to PR those fixes? If not I can do it.

**Comment by kempust** [comment]
@SahAssar I am not a git person, can you do it, thanks.

**Comment by psychonaut** [comment]
https://www.google.com/fonts

**Comment by bobdenotter** [comment]
> these look fine (and similar to current one):

Are you certain they also work with polish diacritics and perhaps even cyrillic? :-)

**Comment by psychonaut** [comment]
i've checked russian and from that list:
Noto Sans
Merriweather

**Comment by cdowdy** [comment]
if you are dead set on using Montserrat as a font and you need these extra language support I would suggest that 

* use this font https://www.fontsquirrel.com/fonts/montserrat - it has a tooooooooooooon of langauge support 

then use this https://github.com/bramstein/fontfaceobserver to load the fonts

**Comment by SahAssar** [comment]
@cdowdy Well, in the old base-2016 I wanted to include the fonts in the package (I don't like that it sends data to Google), but got some pushback due to the size it added. So google fonts it is, but I settled on Noto Sans now, which looks pretty good too.

**Comment by kempust** [comment]
@SahAssar I have found a fix for the missing submenu for a top menu on a small device.  In _sub_menu.twig, the submenu &lt;ul> should be

`<ul class="menu submenu vertical" data-submenu>`

and the top menu should be 

`<ul class="menu vertical medium-horizontal  {{ class|default('') }}" data-responsive-menu="accordion medium-dropdown">`

There are still missing submenu triangles for small devices but this appears fixed in foundation 6.2.1 (but this has issues of its own as there is missing css for the hamburger)
