### ISSUE TITLE
[Tracker] Popular Extensions with Bolt v3 versions

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5098]
This is the tracker list for the most popular set of Bolt v2 extensions according to download stats.

There are more than the agreed 20 as some are discontinued and the vast majority are either by core developers, or long standing community members and therefore should be low-hanging-pineapples.

 | Name | Composer name | Comment
------------ | ------------- | ------------- | -------------
:x: | MenuEditor | bacboslab/menueditor | 
:red_circle: | SimpleForms | bolt/simpleforms | Discontinued
:heavy_check_mark: | Bolt Forms | bolt/boltforms | Updated, but untagged
:heavy_check_mark: | Sitemap | bolt/sitemap | 
:heavy_check_mark: | Bolt SEO extension | bobdenotter/seo | 
:heavy_check_mark: | Disqus | bolt/disqus | 
:red_circle: | Client Login | bolt/clientlogin | Discontinued/abandoned (merged into bolt/members)
:x: | BoltBB | bolt/boltbb | In progress, but might not make release day
:heavy_check_mark: | RSS Feed | bolt/rssfeed | 
:x: | GoogleAnalytics | bolt/googleanalytics | 
:heavy_check_mark: | Members | bolt/members | Updated, but untagged
:heavy_check_mark: | Bolt Labels | bolt/labels | 
:x: | TaxonomyList | jadwigo/taxonomylist | 
:x: | JSON API | bolt/jsonapi | 
:x: | Bolt Forms Editor | rossriley/formeditor | 
:x: | Socialite | bolt/socialite | 
:heavy_check_mark: | Clippy | gawain/clippy | It looks like you're trying to update an extension, would you like some help with that?
:x: | Editable | bolt/editable | 
:red_circle: | Bolt Redirector | foundrycode/boltredirector | Discontinued/abandoned
:heavy_check_mark: | Zocial Icons | bolt/zocial-icons | 
:x: | ImageUpload | blockmurder/imageupload | 
:x: | MetaTags | xiaohutai/bolt-metatags | 
:x: | ImportWXR | bolt/importwxr | 
:x: | Bootstrap Carousel | bolt/bootstrap-carousel | 
:x: | Google Maps | sahassar/gmaps | 
:heavy_check_mark:  | FacebookComments | bolt/facebookcomments | 
:heavy_check_mark: | Cord | gawain/cord | 
:heavy_check_mark: | PasswordProtect | bolt/passwordprotect | 
:heavy_check_mark: | Bolt Colourpicker | bolt/colourpicker | 
:x: | Gallery | blockmurder/gallery | 
:x: | JSON Access | bolt/jsonaccess | 
:x: | Twitter Feed | bolt/twitterfeed | 
:x: | FacebookLike | bolt/facebooklike | 
:x: | Simple Contact Form | salidasoftware/boltcontact | 
:x: | ArrayFieldType | ws/array-field-type-extension | Is this needed/relevant with the new storage system?

### Others 
 | Name | Composer name | Comment
------------ | ------------- | ------------- | -------------
:heavy_check_mark: | Edit Button | bobdenotter/editbutton | 
:heavy_check_mark: | Bolt Tweet Embed | bobdenotter/bolt-tweet-embed |
:heavy_check_mark: | GeoIP | bolt/geoip |

**Comment by bobdenotter** [comment]
| Name | Composer name | Comment
------------ | ------------- | ------------- | -------------
:heavy_check_mark: | Edit Button | bobdenotter/editbutton |

**Comment by bobdenotter** [comment]
Disqus has been updated too.

**Comment by rossriley** [comment]
There's also a new version of bolt/colourpicker

**Comment by bobdenotter** [comment]
I've added 'Sitemap' and 'RSS Feed' to the list of converted ones. ( @GawainLynch Or didn't you add them on purpose, because they aren't tagged yet? 

I just pushed the changes for an updated FacebookComments.

**Comment by GawainLynch** [comment]
It was down to rank… everything on this list fell *way* below the threshold

**Comment by bobdenotter** [comment]
@GawainLynch Euhm, they are numbers 5 and 9 respectively on the list.. I just edited the checkmarks, because I noticed you converted them.

**Comment by GawainLynch** [comment]
OK… so guess what… I can't read :laughing:

**Comment by Raistlfiren** [comment]
Can we update this list? I think the following extensions can be checked off - 

- BOLT SEO Extension
- BOLTBB
- BOLT Google Analytics
- BOLT Labels

Thanks!

**Comment by GawainLynch** [comment]
SEO & Labels updated.

BoltBB and Google Analytics  are not v3 compatible yet, the former still being a little while away.
