### ISSUE TITLE
Assets queue doesn't filter duplicates anymore.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5104]
Previously, the assets queue filtered out duplicates. In Bolt 3 It no longer does so. 

To reproduce: 

 - Install 'TweetEmbed' (will be in extensions store in an hour or so)
 - Add three `{{ tweet(..) }}` tags to the page, 
 - Inspect source: 

![screen shot 2016-03-30 at 15 27 37](https://cloud.githubusercontent.com/assets/1833361/14143574/51a85834-f68c-11e5-8470-77a5becef080.png)

**Comment by GawainLynch** [comment]
Recounting here…

So a couple of issues identified with this approach/requirement:
* If you're laying out repeating HTML elements
* Snippets are made to (also) have callbacks, and those callbacks can potentially change state… that's something that should be left to a programmer, not us, to decide

@bobdenotter:
> I think this is something that we’d better leave as-is right now, and (for now) instruct people on adding callbacks once, if they are to be added once only.
