### ISSUE TITLE
[BUG] Database check / update

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#5110]
I try to migrate do version 3.0.
After update of the database, I have the message
Modifications made to the database:
    Table bolt_users is not the correct schema: missing index on username, removed index idx_5585b54f85e0677
Your database is now up to date.

And when I check again, I have the same message

Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Zip/tarball install
 - PHP version: 5.6.8
 - MySQL version :  5.6.24 MySQL Community Server (GPL)
 - Used webserver: Apache/2.4.12

**Comment by bobdenotter** [comment]
Hi, 

What version were you migrating _from_ ?

For a quick fix, you might want to go into your preferred DB-tool, and remove the index manually from `bolt_users`.

**Comment by mgageo** [comment]
The actual version is 2.2.16
It's good after removing the index.
