### ISSUE TITLE
[BUG] URLs in admin menu

### ISSUE THREAD

**Issue by christophermh44** [bolt/bolt#5111]
I installed Bolt 3 beta 1 into a subdirectory of my server (http://mysite.com/sandbox/bolt/…). Some URLs in the back office main menu don't add the subdirectory to the path:

- /bolt/users
- /bolt/dbcheck
- /bolt/clearcache
- /bolt/changelog
- /bolt/systemlog
- /bolt/extend

So when I click on one of those links, I'm 404'd.

Details
-------

 - Relevant Bolt Version: 3.0 - beta 1
 - Install type: Tar install
 - PHP version: 7.0
 - Used webserver: Apache 2.4
 - For UX/UI issues: Chrome 49

**Comment by PhillippOhlandt** [comment]
duplicate to #5063 :D

**Comment by bobdenotter** [comment]
Sorry, but this is a duplicate for #5063.

**Comment by bobdenotter** [comment]
Haha, * shakes fist at @PhillippOhlandt *

**Comment by PhillippOhlandt** [comment]
@bobdenotter deal with it, old man! XD
