### ISSUE TITLE
[BUG] Template "partials/_master.twig" is not defined

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#5112]
I try to migrate to version 3.0 from version 2.2.16
The display of the page http://bolt3.nicalala.com/page/las-isletas-1 is good.
But for http://bolt3.nicalala.com/ I have a fatal error 

Twig_Error_Loader
Template "partials/_master.twig" is not defined in "index.twig" at line 1. 

Details

    Relevant Bolt Version: 3.0
    Install type: Zip/tarball install
    PHP version: 5.5.33
    MySQL version : 5.6.29-76.2
    Used webserver: Apache

**Comment by GawainLynch** [comment]
It should happen automatically… but have you flushed the cache?

**Comment by mgageo** [comment]
I don't flush the cache. After the flushing, it's good for http://bolt3.nicalala.com/
but not for http://bolt3.nicalala.com/chapters/rever
Template "_header_subpages.twig" is not defined in "listing.twig" at line 1.

**Comment by bobdenotter** [comment]
The file `_header_subpages.twig` is not in the default theme. Which theme are you using? Does the theme have this file?

**Comment by mgageo** [comment]
I use a custom theme, the same as in nicalala.com (bolt version 2.2.16)
In this theme, I don't use listing.twig. In version 2.2.16 I have an error http://nicalala.com/chapters/rever

Sorry for the false issue
