### ISSUE TITLE
[BUG] Default cookie domain value in header can't contain port number

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#5114]
In case of server addressed via any port number like http://bolt.me:8080 and no explicit _cookies_domain_ value set to _.bolt.me_ then right session storage can't be reached by the app.
This will be producing CSRF errors at first user creation like mentioned in #5014.

Details
-------

 - Bolt Version: [ master ]

Screenshot:
![Response header](https://cloud.githubusercontent.com/assets/761149/14246730/5b8a4dc2-fa69-11e5-900c-52a56aac5dab.jpg)

**Comment by bobdenotter** [comment]
Fixed by #5115
