### ISSUE TITLE
Database entities won't hydrate if columns use captials

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5117]
If a table name has columns like `customerID` they will create and save OK, but the `FieldTypeBase::hydrate` chokes as the `$data` array is all keyed with lower case column names

**Comment by jadwigo** [comment]
ouch, optional capitalization in MySQL strikes again

**Comment by rossriley** [comment]
@GawainLynch any idea how these are getting through, according to this line: https://github.com/bolt/bolt/blob/master/src/Config.php#L604

All the field names should be lower-cased, and hyphens replaced with underscores, as far as I can see the metadata driver uses these parsed values to pass to the hydrate method.

Is there any other places they can slip through without being parsed here?

**Comment by GawainLynch** [comment]
@rossriley Yeah it was a custom extension table. The table creates fine with column names CamelCased, the pdo calls work fine, but the hydration is skipped for those columns.
