### ISSUE TITLE
Templates output `{{ dump() }}` when not logged in, and more.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5124]
- The `{{ dump() }}` tag shows output when not logged on:

![screen shot 2016-04-05 at 14 37 03](https://cloud.githubusercontent.com/assets/1833361/14281965/5efe1fbe-fb3c-11e5-8c02-9488bb97c6d7.png)

- The `debug_show_loggedoff` setting is not used.

- We should probably apply the same rules to `firebug` and `backtrace`, as we do to `dump`

@see #5123 for how I fixed it for Bolt 2.2.

Details
-------

 - Relevant Bolt Version: [ master ]

**Comment by GawainLynch** [comment]
Fixed in #5138
