### ISSUE TITLE
multi language support for content?

### ISSUE THREAD

**Issue by DerManoMann** [bolt/bolt#513]
I haven't really seen anything about it, so here is my questions: Is there any support for having the same content in multiple languages?

If not, is there any way of simulating that? The minimum viable feature would be to have a unique key that consists of a content-id and a locale.

I am considering bolt as a backend for managing content in an application that needs to be multilingual. So I would need something that can manage the same content in multiple languages.

ta, mano

**Comment by bobdenotter** [comment]
Closing. Use only #234 for discussion on this. 

See also this informational page on the docs: https://docs.bolt.cm/howto/building-multilingual-websites
