### ISSUE TITLE
[BUG] Preview page with not publish status catch Fatal error

### ISSUE THREAD

**Issue by joshuan** [bolt/bolt#5146]
When i want preview page and status now not publish (Timed publish, Not published, Draft) - Controller generate error: 
```
PHP Fatal error: Bolt core
Error: Call to a member function setFromPost() on a non-object
File: /src/Controller/Frontend.php
Line: 203
````

Details
-------
 - Relevant Bolt Version: master
 - Install type: Github checkout
 - PHP version: 5.5

**Comment by bobdenotter** [comment]
Fixed by #5151
