### ISSUE TITLE
[RFC] Renaming/reshuffling/rethinking some configs

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#5164]
I'm proposing that we rename/reshuffle a few configs to make them more predictable/usable (preferrably for deprecation in 3.1 and removal in 4.0):
### config.yml
1. Consolidate the cookie settings under one array like we do with mailoptions/wysiwyg/branding and most other things.
2. Same as above but for debug settings (and perhaps combine with `debuglog`)
3. Same as above but for frontend settings (`listing_template`, `search_results_template`, `taxonomy_sort` and so on).
4. ~~Remove the grunt/livereload settings from config.yml. They are only for developing the backend (if they even still work), and having them in config.yml confuses people (**this should be done for 3.0** PR: #5166 ).~~
5. Put backend news and stack enable/disable under the branding setting array (where we also already have `news_source` and `news_variable`). Also not including them in the default config.
6. Rename the wysiwyg key to something more logical like `html_field_settings`. Or rename the field to `wysiwyg`, either works, but when looking at the configs one should get that they are connected.
7. Rename recordsperpage and listing_records to make it more clear what is frontend and what is backend.
### contenttypes.yml
1. Rename the `show_in_menu` option under a contenttype to `group` to match the the way we do with fields and also remove the option to set it to `false`. Instead of false one could just do `show_in_menu: "Other content"` and get the same effect (or add the false option to `group`).
2. ~~Not including documentation on YAML repeating nodes in contenttypes.yml, since most people who are new to bolt probably wont be using them until they are more comfortable (and therefore more versed in the docs).~~ See #5168 and #5176
3. deprecate all no-underscore keys like `recordsperpage` and replace them with underscored ones. It might be confusing to have `recordsperpage` and `show_on_dashboard` right next to each other.
4. Have a better example of the settings available for the html area in the `showcases` contenttype.
### taxonomy.yml
1. ~~Rename `chapters` to `groupings` or vice versa. The other taxonomy type examples are named after their `behaves_like` value, that makes this inconsistent.~~ Fixed in #5169
2. Provide some more helpful comments in taxonomy.yml and menu.yml. The other yml files have pretty good comments, but these two are pretty barren.

**Comment by bobdenotter** [comment]
Thums up, I say: :+1:

**Comment by SahAssar** [comment]
I've PR'ed the ones that only change examples or comments (except better comments in menu.yml and taxonomy.yml, those require some thought),

**Comment by GawainLynch** [comment]
* config.yml :+1: 
* taxonomy.yml  :+1: 
* contenttypes.yml 
  * 1 — You mean deprecate?
  * 3 & 4 :+1: 

How long would it take to get this sorted?

My concern is that it is getting late for changes that require code.

**Comment by SahAssar** [comment]
@GawainLynch Well, My plan was to change it in 3.1 and keep the old ways deprecated but working and then remove the old ways in 4.0, but if everyone is okay with getting these in for 3.0 that would be very nice. It shouldn't take long to do, AFAIK it's mostly changing the defaults, a couple of config.get() and the corresponding tests and docs.

**Comment by GawainLynch** [comment]
@SahAssar the config branch is nearing completion (over a year later), and will be in full-swing again after 3.3.0 is released in a few days, so we should touch base on this very soon as a lot has changed over that year, and even in the last few weeks to do with this!

**Comment by SahAssar** [comment]
@GawainLynch Sounds good, sorry for the late reply. If you have time tomorrow we can go over it :)

**Comment by GawainLynch** [comment]
WFM :+1:

**Comment by SahAssar** [comment]
Since I'm selfish I'm giving this issue one more shot:

Any +1 or -1 votes for the structure proposed in https://docs.google.com/spreadsheets/d/1hAITaszfxn5rOFifhYdUDM1ySo2Xiiu7ZI7IhNePh1M/edit?usp=sharing ?

**Comment by GawainLynch** [comment]
I'd hold off … Config will have to massively change anyway with Flex

**Comment by SahAssar** [comment]
Alright, then I'm closing this for now. Perhaps it will be helpful down the line.
