### ISSUE TITLE
[BUG] Not null constraint failed

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5165]
Trying to move my old Bolt 2.2 database to Bolt 3.0 beta 2. It works, but once I try to add a new entry it breaks with the following error:

"An exception occurred while executing 'INSERT INTO bolt_entries (slug, datecreated, datechanged, datepublish, datedepublish, username, ownerid, status, templatefields, title, teaser, image, video) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test-1", "2016-04-12 20:22:40", "2016-04-12 20:22:40", "2016-04-12 20:22:30", null, "", "1", "published", null, "test", "<p>test<\/p>\r\n", "[]", "[]"]:\n
\n
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: bolt_entries.templatefields"

It is possible to make a new page, block or something else. But not new entries. It is still possible to edit old entries.

In the old database the Schema is "CLOB NOT NULL DEFAULT". In the new database it is "CLOB DEFAULT NULL". Somehow I think this is a clue to the problem.

Details
-------

 - Relevant Bolt Version: [3.0 beta 2]
 - Install type: [ Zip/tarball install]
 - PHP version: [ 5.59 ]
 - Used webserver: [ Apache ]
 - For UX/UI issues: [ browser name and version ]

**Comment by SahAssar** [comment]
Hey @mattiaslundback,

Was this a straight 2.2 -> 3.0 beta 2 upgrade or did you previously try out an alpha or beta with the same DB?

If manually going to the check database page do you get any indications that something needs updating?

Thanks!

**Comment by mattiaslundback** [comment]
I went through beta 1 first. But I have also trioed to migrate directly from 2.2 to 3.0 beta 2 with the same result. Have som complemantary information I got when inspecting the database also. 

In the old database the Schema is "CLOB NOT NULL DEFAULT". In the new database it is "CLOB DEFAULT NULL". Somehow I think this is a clue to the problem.

**Comment by mattiaslundback** [comment]
And, no. There are no indications that the database need updating when I check manually.

**Comment by SahAssar** [comment]
Hmm, this looks like #4817 has risen from the dead. We should probably have an extra look at this, but I'm still hoping that we just missed something simple :) I'll add it to blocking if we haven't figured it out tomorrow.

**Comment by mattiaslundback** [comment]
Have solved the problem by deleting the constraint manually in the database. Now it works flawlessly. But I fear everyone who upgrades could have the same problem. The database I used have been around since the first versions of Bolt, so I'm not sure for how long this "NOT NULL" constraint has been in the database. Could have been inherited from long ago.

**Comment by SahAssar** [comment]
IIRC the "NOT NULL" constraint was in 2.2, but it should have been changed when you moved to 3.0betaX... Since it wasn't it might be something to look into.

**Comment by GawainLynch** [comment]
OK… finally got around to confirming and tracking this down.

It seems that DBAL doesn't update the constraint on `json_array` fields :-/
