### ISSUE TITLE
COMPOSER_HOME environment variable must be set for composer to run correctly

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#5172]
I installed Bolt 3 and it did work for a day. Now I get an error when I visit my website or want to log in to the cms. See below. It's a different error that I posted earlier on the forum (but I haven't done anything). The cms is installed with a different webroot ( www instead of public) and for that bolt.yml was edited to make it work. 

Details
-------

 - Relevant Bolt Version: [ 3.0 beta 2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [  5.5.9-1Ubuntu4.14 ]
 - Used webserver: [ Apache 2.0 ]

Error
--------------

PHP Fatal error: Vendor library

Error: Uncaught exception 'RuntimeException' with message 'The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly' in /vendor/composer/composer/src/Composer/Factory.php:604

Stack trace:

#0 /vendor/composer/composer/src/Composer/Factory.php(64): Composer\Factory::getUserDir()

#1 /vendor/composer/composer/src/Composer/Factory.php(155): Composer\Factory::getHomeDir()

#2 /vendor/composer/composer/src/Composer/Factory.php(282): Composer\Factory::createConfig(Object(Composer\IO\BufferIO), '/var/www/domain...')

#3 /vendor/composer/composer/src/Composer/Factory.php(532): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), 'composer.json', false)

#4 /vendor/bolt/bolt/src/Composer/Action/BaseAction.php(74): Composer\Factory::create(Object(Composer\IO\BufferIO), 'composer.json', false)

#5 /var/www/do

File: /vendor/composer/composer/src/Composer/Factory.php
Line: 604

**Comment by dadaxr** [comment]
Got the same error, and fixed it with updating my composer version.

Try to do a 
`composer self-update`
and then a 
`composer clear-cache`

It seems it's originally a composer bug :) ( https://github.com/composer/composer/issues/4789 )

**Comment by gwbonline** [comment]
I don't know how to do this commands.

**Comment by dadaxr** [comment]
you can do them in shell prompt. 

If you don't have installed composer globally you should specify the installation path. 
Have a look at [the composer installation doc](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx)

**Comment by GawainLynch** [comment]
@dadaxr problem here is that @gwbonline is using an archive install

**Comment by gwbonline** [comment]
Can I solve this myself or is it better to wait for a newer (beta) release?

I always use the archive install because I've always done that.

**Comment by gwbonline** [comment]
Is this (probably) solved by https://github.com/bolt/bolt/pull/5150?

**Comment by GawainLynch** [comment]
Probably not… #5150 was just for setting up the testing environment.

It makes no sense that you're getting this error either, as those libraries should on be loaded on the Extend page in the admin UI.

**Comment by gwbonline** [comment]
There was nothing wrong... for a couple of days. Suddenly there was an comparable error on the frontpage of the site and shortly after that also the Bolt login page was replaced by the error I posted here. After I used my backup database and config files I did nothing else to mess things up. It worked a few days. Currently I'm back at the old install that works fine.

**Comment by cathelijne** [comment]
On my composer install, I have set composer to 1.0alpha11 in composer.json, and then this error disappears (after cleaning cache etc.). Just FYI, this is by no means a solution nor explanation for the fact that this happens in file installs. Just thought the knowledge might come in handy.

**Comment by fadoe** [comment]
I have the same bug. Using bolt in a existing project. Bolt 2.2 works well, now I want update to 3.0 and get this error. I updated composer.phar and clear the cache.

**Comment by GawainLynch** [comment]
OK… This took a bit of tracking down… I had to read Composer code :laughing: 

It is very simply that the system variable `HOME` is not set for the web server user, and Composer is not being invoked properly as a result.

This is not something we have control over, but might be able to cope with… have to try and see if/where it makes sense to do this.

**Comment by GawainLynch** [comment]
Something that just occurred to me… were either of these failures (@gwbonline & @fadoe) on shared hosts where `safe_mode_allowed_env_vars` is set?

That would prevent Bolt from setting the environment variable needed for Composer.

**Comment by gwbonline** [comment]
I don't have this option since it is no longer supported in the version of php my hoster has (5.5.9).

**Comment by gwbonline** [comment]
Sorry... Wrong button...

**Comment by kupalizer** [comment]
Had this problem on a shared host and my solution was to add following i my .htaccess 

`SetEnv COMPOSER_HOME /home/youraccount/vendor/composer/composer/bin/composer´
/vendor is shere you places your bolt 3 app root folder

**Comment by GawainLynch** [comment]
That should be 
```
SetEnv COMPOSER_HOME  /home/user/app/cache/composer/
```

As COMPOSER_HOME is a writable location to put caches and repo data.

**Comment by gwbonline** [comment]
With this line of code everything should work without errors like above?
