### ISSUE TITLE
[BUG] Unclear message in dashboard on failed login

### ISSUE THREAD

**Issue by Sjord** [bolt/bolt#5173]
When somebody tries to log in into the backend with a valid username and an invalid password, the message "*unknown* logged in" is shown in the dashboard. This message is incorrect: it lets the user think that somebody logged in and the username of this person is unknown.

![latestsystemactivity](https://cloud.githubusercontent.com/assets/113030/14494276/43195e9a-018a-11e6-8c72-42408fe0e0c6.png)

The system log shows the correct message "Failed login attempt for 'Sjord'."

Details
-------

 - Relevant Bolt Version: v2.2.19-pl1-28-g954b34a
 - Install type: Github checkout
 - PHP version: 7.0
 - Used webserver: Apache
 - For UX/UI issues: Firefox 45.0.1

Reproduction
------------

* On the backend login page (/bolt/login), submit a valid username and invalid password.
* Log in to the backend using the correct username and password.
* The  "Latest system activity" panel shows "*unknown* logged in" as second item.
* I would expect it to be "Failed login attempt for 'username'."

**Comment by bobdenotter** [comment]
Also present in Bolt 3.0. Good find!

**Comment by bobdenotter** [comment]
Fixed in #5177
