### ISSUE TITLE
[RFC] Proposed Git Branching Process

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5181]
In order to get things moving with a greater degree to continuity, this RFC proposes moving to three "active" branches:

  * Stable
  * Next
  * Development (`master`)

**NOTE:** During early 2.x development cycle we experimented with a `canary` branch. While similar, this proposed approach will use merging as opposed to rebasing.

###### Stable

The stable branch is just that, the supported production-ready release branch. No new features should ever be added to this branch, ergo it should be hotfix only.

Currently this role is being filled by `release/2.2` and once 3.0.0 is tagged, `release/3.0` would become the stable branch.

###### Next

The next branch is the feature set that will become the next stable branch.

It would be made the repository's default on each version iteration at the point that the development branch is ready to be made a beta.

###### Development

This is `master` and would remain open for features.

###### Features

Features should target either "next" until feature freeze, then only master until a new "next" branch is created.

###### Hot Fixes

Hot fixes should target the lowest currently supported version branch they affect, and should then cascade via branch-merge to new version branches.

#### Branch Merges

At regular intervals, or as needed, stable branches can be merged to "next" and "next" down to master.

Comments welcome on whether we use fast-forward merges or not.

**Comment by bobdenotter** [comment]
My initial concerns are: 

 - I remember the 'canary' thing being a huge hassle to maintain. If we're going to use _three_ active branches, how are we going to prevent the same from happening? 
 - The 'graphs' tab looks really sad at the moment. For the casual visitor, it might seem the project isn't _nearly_ as active as it actually is: 
![screen shot 2016-04-14 at 08 43 07](https://cloud.githubusercontent.com/assets/1833361/14519095/f7d40d2a-021c-11e6-95c0-3862e1260794.png)

it should look like: 
![screen shot 2016-04-14 at 08 43 16](https://cloud.githubusercontent.com/assets/1833361/14519107/fda97f3c-021c-11e6-8e9d-15a6a4bdf177.png)

How will this change in the process affect that?

**Comment by GawainLynch** [comment]
#### Canary

The problem/hassle here was rebasing, we're proposing merges this time.

As for the three branches. Well, the point being that this will allow us to iterate our releases faster. 
  * Stable should be quiet, and hotfix only. 
  * Next would mostly be in bug-fix mode
  * Development (master) 

The challenge becomes occasional PRs that are targeted at the wrong branch, but that can resolved by not merging that PR via the GitHub interface.

#### Commit Graphs

Well, talk to GitHub. Seriously. Why they have no selector there is just a mystery. :frowning: 

That aside, this proposal is aimed at speeding up our iteration time on branches, the reason the current graph looks so quiet is that we've been in a year long bug-fix mode for that branch. 

If we adopt the RFC's approach, the second graph would become active as we'd branch `release/3.0` now (it's reached beta) and will still get bug-fix attention for a while until 3.1 is released.

**Comment by bobdenotter** [comment]
If you think it'll be manageable, I'm all for it. :+1:

**Comment by rossriley** [comment]
I'm generally 👍 for the approach, with the same reservations that came out of trialing the canary branch. I personally prefer the approach but we did make it more difficult for less experienced contributors to navigate the process.

But, I'd say let's give it a go and review after a decent trial period.

**Comment by GawainLynch** [comment]
OK… branch created. Let's see how this goes.

**Comment by PhillippOhlandt** [comment]
:boom:
