### ISSUE TITLE
[BUG] Check updates shows wrong new version for bolt/members

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5184]
I have the bot/members extension installed on a Bolt 3 Beta 2 version. That means I have `dev-master` of bolt/members installed.

When I run the update check via the backend, it shows me Bolt Members v2.1.2 as version to install. The v2.1.2 seems to be the latest tagged version of bolt/members but requires `"bolt/bolt" : ">=2.1.0,<3.0.0"` so it shouldn't be shown for the update.

![](https://infinit.io/_/32wphy2.jpg)

And here is the response from the AJAX call for the check update request:

![](https://infinit.io/_/bssps2j.jpg)

Details
-------

 - Relevant Bolt Version: [ 3.0 Beta 2 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used webserver: [ php dev-server ]

**Comment by SahAssar** [comment]
Did we implement this?
```
<rossriley> on that note I was going to suggest that we hack the provides version to 2.9.9
<rossriley> while we are in alpha stage
```
From https://github.com/bolt/bolt/wiki/Dev-meeting-2016-01-05

**Comment by PhillippOhlandt** [comment]
Yeah I can remember that. We should fix that ASAP :P

**Comment by GawainLynch** [comment]
@SahAssar we never ended up going with that. It is only the queries from updates and the version button that are problematic... We have the technology!

...and yes, deffo a bug.

**Comment by SahAssar** [comment]
Imma guess this has been fixed in the meantime an just not closed (And I think I heard talk about it being fixed in one of the chats)... I'd assume there would be more activity on this otherwise ;)

Anyway, closing, please reopen/comment if it's still around!
