### ISSUE TITLE
[BUG?] Composer Post-Update Path Selection Order

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#5185]
When running the post-update composer hook which then forwards to `ScripHandler::installAssets` then then web-dir specified in composer.json is always ignored. It should take precedence over the Bolt default.

[Here](https://github.com/bolt/bolt/blob/release/3.0/src/Composer/ScriptHandler.php#L132) it seems to be done correctly, whereby the composer specified one is set as default. But in [this block](https://github.com/bolt/bolt/blob/release/3.0/src/Composer/ScriptHandler.php#L234) the composer option is only read in a catch statement that is never executed.

I'm thinking that that block should be the other way round whereby the composer.json is read for a value after which if there isn't one then it can fall back to the Bolt default. 

Thoughts @CarsonF 

Details
-------

 - Relevant Bolt Version: [ 3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]

**Comment by CarsonF** [comment]
It's intended functionality. It's not the default path though. It's the path from the application. The application is configured based on the `.bolt.yml/.bolt.php` file in the project root. This is much more robust than a hardcoded value in the `composer.json` file.

**Comment by SahAssar** [comment]
Closing because above. Feel free to reopen and all that. :)
