### ISSUE TITLE
Restyaboard integration

### ISSUE THREAD

**Issue by reidharry** [bolt/bolt#5194]
I'm looking to integrate Bolt with [Restyaboard](https://github.com/RestyaPlatform/board)

Can I get the integration document, if any?

**Comment by PhillippOhlandt** [comment]
Hey, are you looking for the extensions documentation?
https://docs.bolt.cm/release-2-2/extensions/introduction

**Comment by reidharry** [comment]
Thanks a lot.

**Comment by PhillippOhlandt** [comment]
Seems like it's what you searched for. I'll close here. If you still have any questions, feel free to reopen or post in the forum (discuss.bolt.cm) or ask us directly in our slack channel (slack.bolt.cm). :)

**Comment by SahAssar** [comment]
@PhillippOhlandt Don't forget the IRC channel!

**Comment by PhillippOhlandt** [comment]
That's oldschool stuff for old men :P

**Comment by GawainLynch** [comment]
We have just as many women in our IRC channel thank you very much!

**Comment by PhillippOhlandt** [comment]
The "old men" was dedicated to you :P

**Comment by GawainLynch** [comment]
> The "old men" was dedicated to you :P

I'll let is slide… but I think I am going to surprise you (in a good way) when you come to NL in May.

**Comment by PhillippOhlandt** [comment]
Now I am scared, really really scared :P

**Comment by rarila** [comment]
The truth lies probably somewhere between :older_man: and :skull: …
