### ISSUE TITLE
[BUG] $repo->findAll() returns id-less records. (v3.0.0)

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5198]
Please, fill free to close that if it's fixed already...
When i get content with $repo->findAll(), it returns an array of records with `id: null`.
![](https://i.imgur.com/Ydtw52F.png)

Don't have a chance to check that on the latest version..

**Comment by GawainLynch** [comment]
I think this has long been fixed. Querying just now on a pre-filled database give me:
![image](https://cloud.githubusercontent.com/assets/1427081/14579893/2c26e08a-03bb-11e6-8eb2-aaf93ff34c04.png)
