### ISSUE TITLE
[BUG] missing .htaccess on c9.io

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5206]
Details
-------

 - Relevant Bolt Version: [ 3.0 beta 2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

When I install Bolt on c9.io I get an error of the following type:

Stack trace:
#0 /home/ubuntu/workspace/vendor/bolt/bolt/src/Configuration/LowlevelChecks.php(85): Bolt\Configuration\LowlevelChecks->checkApache()
#1 /home/ubuntu/workspace/vendor/bolt/bolt/src/Configuration/ResourceManager.php(440): Bolt\Configuration\LowlevelChecks->doChecks()
#2 /home/ubuntu/workspace/vendor/bolt/bolt/app/bootstrap.php(116): Bolt\Configuration\ResourceManager->verify()
#3 [internal function]: Bolt\{closure}()
#4 /home/ubuntu/workspace/vendor/bo in /home/ubuntu/workspace/vendor/bolt/bolt/src/Configuration/LowlevelChecks.php on line 159
[16-Apr-2016 11:30:47 UTC] PHP Fatal error:  Uncaught exception 'Bolt\Exception\LowlevelException' with message 'The file /home/ubuntu/workspace/.htaccess doesn't exist. Make sure it's present and readable to the user that the webserver is using. If you are not running Apache, or your Apache setup performs the correct rewrites without requiring a .htaccess file (in other words, if you know what you are doing), you can disable this check by calling $config->getVerifier()->disableApacheChecks(); in bootstrap.php' in /home/ubuntu/workspace/vendor/bolt/bolt/src/Configuration/LowlevelChecks.php:159

It only happens on c9.io as far as I know. I have set the doc_root to "/public". If I do as I'm told in the text above the error disappears. Might not be a bug, but rather an area of possible improvement of the code. But I thought it might be of interest since it might appear on other cloud-services.

If you wan't to close it that's ok, I have managed to solve it myself.

**Comment by bobdenotter** [comment]
Does this mean that the `.tgz` file doesn't contain the `.htaccess` file? Because it really should be in there.

**Comment by mattiaslundback** [comment]
No, it does contain the .htaccess file (in the public library). But somehow the docroot becomes www.???.com/public although I set it to /public in php.ini. Think this is what triggers the error, somehow it checks for the .htaccess in www.???.com/

This might be something that only happens on virtual servers, like c9.io. It is related to the other problem in issue #5210. 

These are my settings in php.ini

; The root of the PHP pages, used only if nonempty.
; if PHP was not compiled with FORCE_REDIRECT, you SHOULD set doc_root
; if you are running php as a CGI under any web server (other than IIS)
; see documentation for security issues.  The alternate is to use the
; cgi.force_redirect configuration below
; http://www.php.net/manual/en/ini.core.php#ini.doc-root
doc_root = "/public"

; The directory under which PHP opens the script using /~username used only
; if nonempty.
; http://www.php.net/manual/en/ini.core.php#ini.user-dir
user_dir = "/public"

**Comment by bobdenotter** [comment]
I'm not sure I follow. Why configure this stuff in `php.ini`, and not in the webserver config where it belongs? 

Have you read this? https://docs.bolt.cm/master/howto/troubleshooting-outside-webroot

**Comment by mattiaslundback** [comment]
I was trying to do the first alternative on the list: "Configure Apache or Nginx to use public as web root". But nothing happens as far as I can tell.

Then, of course, I could move on to the other alternatives. But it's a virtual server and I can't get access anything above the root folder. Though, I can create folders below this level. Still, that would not make a request for www.???.com land in www.???.com/public

So, the remaning alternative would perhaps be to put a .htaccess in the root folder to rewrite all requests to /public. Which would mean I then have the about the same type of configuration as in Bolt 2.x.

This problem is only on my virtual server. On my ordinary server, which is not virtual, everything works well. Using this server for testing and development only. But I have got it to work now, with some caveats, such as the problem in #5210.

**Comment by bobdenotter** [comment]
> If you wan't to close it that's ok, I have managed to solve it myself.

I am still very confused.. If you "fixed" this, what is the issue? Was it a bug, or not knowing how to configure it? Would other people benefit from a description of what you did, besides "nvm, i fixed it"?

**Comment by mattiaslundback** [comment]
Can't reproduce this error now. Have tried to to reinstall twice and it works alright. So it was probably some fileerrors when uploading/installing.

What I did the first time was to disable low-level checks of .htaccess (rows 153-169 in bolt/bolt/src/configuration/LowlevelChecks.php), which solved the problem temporarily. But then I got into more problems and had to reinstall. 

But since then I have tried reinstalling on c9.io (a virtual server) a couple of times and there is another thing one has to do to make it work. The setting for cookies must all be "false".

cookies_use_remoteaddr: false
cookies_use_browseragent: false
cookies_use_httphost: false

Since it works this far, I can manage with having a subdirectory. I just enter www.???.com/public instead. It is only a virtual testserver, so it doesn't really matter that much that I have difficulties moving the webroot.

**Comment by SahAssar** [comment]
@mattiaslundback does it work with
```
cookies_use_remoteaddr: false
cookies_use_browseragent: true
cookies_use_httphost: true
```
?

That is the setting that was most restrictive but still working with cloudflare as reported in #2922.

Not being able to change the web root is going to be an issue for anyone using the bolt 3 packages... Would packaging a version which does not use a separate web root help this out? If so we might be able to have such a package separate from the normal ones.

I'm closing since it is "fixed", but please feel free to reopen/comment!

**Comment by mattiaslundback** [comment]
I agree, it is not a bug as I first thought. And yes, people who run a virtual server in production might very well have use for a verson that makes it possible to run with the webroot at the root. I actually have no idea how common it is to not being able to change the root at all. Hopefully not that many users, at least not in production. For me it works anyway since it is only my testserver where I try out my extensions.
