### ISSUE TITLE
[BUG] Probably wrong directory in extend.twig

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5210]
When installing Bolt 3.0 beta 2 on a Cloud Server, specifically c9.io, the Javascript functions in the backend does not always seem to be pointing at the correct controller address. The result is that the installation and updating of extensions always fails. All others paths seem to be correctly configured and the installation works properly except for this problem.

The error-message is unspecific, but by looking at the Javascript Console in Chrome it seems as if the script tries to access www.???.com/bolt/extend although the actual webroot is in www.???.com/public/. The address should thus be www.???.com/public/bolt/extend.

Row 200 in vendor/bolt/bolt/app/view/twig/extend/extend.twig is probably the culprit in this case. 
The row 
 {{ data('extend.baseurl',   '/' ~ app['controller.backend.extend.mount_prefix']|trim('/') ~ '/') }}
does seem to exclude the library "public" in my case. When I change this row (adding "public") Bolt works normally again.

The paths are othervise set up as follows:
```
array:40 [▼
  "root" => "/public/"
  "rootpath" => "/home/ubuntu/workspace"
  "apppath" => "/home/ubuntu/workspace/vendor/bolt/bolt/app"
  "extensionsconfig" => "/home/ubuntu/workspace/app/config/extensions"
  "extensionsconfigpath" => "/home/ubuntu/workspace/app/config/extensions"
  "extensionspath" => "/home/ubuntu/workspace/extensions"
  "filespath" => "/home/ubuntu/workspace/public/files"
  "web" => "/home/ubuntu/workspace/public"
  "webpath" => "/home/ubuntu/workspace/public"
  "cache" => "/home/ubuntu/workspace/app/cache"
  "cachepath" => "/home/ubuntu/workspace/app/cache"
  "config" => "/home/ubuntu/workspace/app/config"
  "configpath" => "/home/ubuntu/workspace/app/config"
  "src" => "/home/ubuntu/workspace/vendor/bolt/bolt/src"
  "srcpath" => "/home/ubuntu/workspace/vendor/bolt/bolt/src"
  "database" => "/home/ubuntu/workspace/app/database"
  "databasepath" => "/home/ubuntu/workspace/app/database"
  "themebase" => "/home/ubuntu/workspace/public/theme"
  "themebasepath" => "/home/ubuntu/workspace/public/theme"
  "view" => "/bolt-public/view/"
  "viewpath" => "/home/ubuntu/workspace/public/bolt-public/view"
  "composer" => "/home/ubuntu/workspace/vendor/bolt/bolt"
  "composerpath" => "/home/ubuntu/workspace/vendor/bolt/bolt"
  "app" => "/public/bolt-public/"
  "files" => "/public/files/"
  "themepath" => "/home/ubuntu/workspace/public/theme/base-2016"
  "templatespath" => "/home/ubuntu/workspace/public/theme/base-2016"
  "extensions" => "/public/extensions/"
  "async" => "/public/async/"
  "upload" => "/public/upload/"
  "bolt" => "/public/bolt/"
  "theme" => "/public/theme/base-2016/"
  "current" => "/public/"
  "currenturl" => "https://bolt3-???.c9users.io/public/"
  "hosturl" => "https://bolt3-???.c9users.io"
  "rooturl" => "http://bolt3-???.c9users.io/public/"
  "canonicalurl" => "http://bolt3-???.c9users.io/public/"
  "canonical" => "http://bolt3-???.c9users.io"
  "protocol" => "https"
  "hostname" => "bolt3-???.c9users.io"
]
```
The question marks are not question marks really, but the specific name of the library which I do not wish to make public unnecessarily.

I cannot verify that this happens on all servers where the installation has an additional level relative to the baselevel. I also do not rule out that this is a configuration error, of course, but the only thing I have changed on the webserver is moving the webroot from / to /public by changing php.ini. And since everything else works it is rather strange that this path is the only one that is not correctly configured.

Details
-------

 - Relevant Bolt Version: [ 3.0 beta 2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache ]

**Comment by bobdenotter** [comment]
I can't confirm this yet.. It seems to work for me, even in more levels. See: 

![screenshot_2016-04-18_19_55_00](https://cloud.githubusercontent.com/assets/1833361/14614070/bec05fc6-059f-11e6-9357-7b112431715d.png)

**Comment by mattiaslundback** [comment]
The link in the menu is ok for me to, but not when I try to update the extensions. Then it fails. Took a while until i understood what was going on. Run update check or check version would give an error if the problem is the same. 

But it might also be specific to the cloudserver I'm running (which is c9.io) since it creates a virtual working directory. A way to test is to install on c9.io, but I can understand if you think that would be overkill. It is probably a quite isolated problem anyway if it is only virtual servers that are affected.

**Comment by SahAssar** [comment]
IIRC we had a few of these path issues early in 3.0 and in 3.0-dev.... I'm closing because we seem to have fixed most of them. If this still happens for you in a current 3.X.X please comment or reopen and I/we will further look into it!
