### ISSUE TITLE
[BUG] Twig templates not showing up for templateselect

### ISSUE THREAD

**Issue by Eiskis** [bolt/bolt#5212]
I've been using the latest version of Bolt, starting off with a clean install, and I'm having issues getting my twig templates to show up for templateselect. I can't get all my twig templates in there from my theme, not by messing with the `filter` value in `contenttypes.yml` and not by explicitly defining them in `theme.yml`. Attached is my directory structure and theme config.

<img width="772" alt="screen shot 2016-04-17 at 18 45 41" src="https://cloud.githubusercontent.com/assets/1101002/14588562/ebf60384-04cc-11e6-9de2-58863bb3a885.png">

What ends up in the templateselect dropdown in the admin panel is the one and only twig file on the second level of nesting in my theme folder, and if I add twig files there I will see them on the dropdown. This is pretty weird however and I can't really find the root cause of my templateselect config not taking effect. I'm trying my best to keep my theme well organized and reusable and being confined to just one level of nesting is quite limiting, if this is indeed the intended behavior.

<img width="716" alt="screen shot 2016-04-17 at 18 46 38" src="https://cloud.githubusercontent.com/assets/1101002/14588561/ebf34e00-04cc-11e6-8302-6c8a9219b82d.png">

If I dump my theme config in the frontend, I can see that the `templateselect` values are what I set them to be in the config, so that can't be the issue.

I feel like I'm missing something obvious with my file paths or something, but I can't really find anything wrong and I'm working on a fresh install. I think there might be something wrong with how Bolt looks for the twig files in the theme folder recursively.

**Comment by bobdenotter** [comment]
Which version of Bolt is this? ("latest" stable or "latest" beta?)

The names you've used, do those files actually exist?

**Comment by Eiskis** [comment]
Like you see in the first pic, the files exist (right?). Even if they didn't though, I should be able to get whatever does exist to show up in the template selector with setting the filter in the contenttype config to something, right?

I cloned the branch `release/3.0`yesterday, I'm on `199c9d8`.

**Comment by bobdenotter** [comment]
> Like you see in the first pic, the files exist (right?). 

In the screenshot the `twig/main/` folder is closed, so no, i cannot see that. :-)

> I cloned the branch release/3.0yesterday, I'm on 199c9d8.

We fixed something similar recently.. See #5127
Maybe there's another quirk with deeper nested folders.

Are you sure you're on a recent checkout? The description in your theme.yml seems older: https://github.com/bolt/bolt/blob/release/3.0/theme/base-2016/theme.yml

**Comment by Eiskis** [comment]
I'm sure, I copied some of the configs over from another site I had. I believe the actual configs should be correct.

**Comment by bobdenotter** [comment]
Could you try it with the default base-2016, as is in the repo.. It should work there.

**Comment by Eiskis** [comment]
The existing templates in `base-2016` are shown, as is my `setup.twig`. Those templates are on the main level. If I move `extrafields.twig` to `foo/bar/extrafields.twig` it won't show up anymore, even if it's defined correctly in `theme.yml`. So, I get the same behavior in both themes.

**Comment by bobdenotter** [comment]
Bug found.. It's not in the `named templateselect`, but in Bolt not looking in enough folders. Fix incoming in a PR.
