### ISSUE TITLE
Bad default values for list types

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5218]
Not sure if this should read "Help, @rossriley!" or "Help, @rarila!"

On new showcases (that have virtually nothing in them) these warnings are getting triggered on save: 
![image](https://cloud.githubusercontent.com/assets/1427081/14627489/444af368-05f5-11e6-8c3c-ca8b51c5f5fa.png)

Looking at the database entries most other JSON fields end up defaulting to an empty array `[]` but imagelist and filelist are being getting double quotes `" "` (space added for effect)
![image](https://cloud.githubusercontent.com/assets/1427081/14628168/d5c5e108-05fb-11e6-9f07-851874f488d9.png)

**Comment by GawainLynch** [comment]
Possibly related to what @bobdenotter is seeing in https://github.com/bolt/bolt/pull/5207#issuecomment-211507161

**Comment by rarila** [comment]
Either way, IMHO the backend should be able to handle even wrong values from client side without throwing errors like this.

**Comment by GawainLynch** [comment]
> Either way, IMHO the backend should be able to handle even wrong values from client side without throwing errors like this.

Agreed… but it would be good to know where it is coming from in the first place.

**Comment by rarila** [comment]
Yep

**Comment by GawainLynch** [comment]
So… any ideas? :wink:

**Comment by rarila** [comment]
Yes… starts with getting up and switching on the computer… ;-)

**Comment by GawainLynch** [comment]
Keeping this open as it doesn't solve the storage problem, just the cause in this case.

**Comment by GawainLynch** [comment]
@rossriley assigning you as… well… storage.

**Comment by GawainLynch** [comment]
Closing as I am pretty sure we fixed this :smile_cat:
