### ISSUE TITLE
[BUG] backend search function starts new searches on every key press -> dead server

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5226]
The small search box in the header of bolt's backend executes a search request on every keypress. On systems with more than a couple of pages, a search request may take some seconds. Now when a user starts to type in a longer search text with eg 10 characters, this will execute 10 different search requests. The javascript cancels all requests befor sending a new one, but the PHP scripts will of course continue to run, leading to 10 concurrent search requests on your database.
This will kill many servers or at least slow down the websites for minutes.

The solution i implemented in a similar case was to block all further search requests until the currently running one really finished. In addition, not every key press should start a search but only a pause of maybe 800ms after the last keypress.

Details
-------

 - Relevant Bolt Version: 2.2.19-pl1
 - Install type: Composer install
 - PHP version: 5.4
 - Used webserver: Apache 2.4
 - For UX/UI issues: Chrome 49 on OSX

Reproduction
------------

- Open the CMS and login
- Open a network proxy or the developer tools > tab network
- type away into the search field

Actual Result:
a list of search requests will popup, all canceled but the last one. And the server will slow down. A list of running PHP threads will show all search requests as still being processed and your Mysql db will show all queries still running.

Expected:
Only one process is running. No further request will be made until this one is finished.

**Comment by SahAssar** [comment]
The ideal scenario would be to actually abort the request with something like http://php.net/manual/en/function.connection-aborted.php I'd guess, but then we'd have to start flushing data to the client before the query starts and it does not seem like silex has a good way to do equivalent functionality (from some light googling), so +1 for this.

**Comment by ToBe998** [comment]
Are there any plans yet on if and when this might get done?
It's a bit of a show stopper atm for the search as it wont ever return any results on a site with more than a couple of items.

**Comment by GawainLynch** [comment]
The core team is on two weeks down time after the 3.0.0 release this Tuesday… But PRs are most welcome if you have the bandwidth to get started on it @ToBe998

**Comment by bobdenotter** [comment]
@ToBe998 I didn't perceive this as very urgent. At least for me, it works. It's currently listed as `enhancement`, if it's classified as `bug`, it'll get more eyes, quicker.

**Comment by ToBe998** [comment]
If it's a bug probably depends on the size of the site and servers used, for me it's a bug ;)

Didn't want to push you guys here, just find out if something is planned soon.
I can try to put it into our sprint and do a PR if it's not in your short time road map. Should i mark this issue if i can get time to work on it?

**Comment by bobdenotter** [comment]
@ToBe998 It might also be related to the size of the dataset and/or number of contenttypes.. Is it a lot of data?

**Comment by bobdenotter** [comment]
> Should i mark this issue if i can get time to work on it?

Yes, just a comment saying "We'll try to work on this" will suffice! And would be awesome. :-)

**Comment by ToBe998** [comment]
I have around 10K objects spread over 8 contenttypes, mostly in 2 of them.

**Comment by GawainLynch** [comment]
/me hands @ToBe998 a nice Belgium :beer: and assigns #5226 to him

:wink:

**Comment by rossgardt** [comment]
Since I found some misuse of the `delay` parameter, I was able to make a quick-fix for the problem. Please see the PR above.

Best,
Benedikt

**Comment by ToBe998** [comment]
We (meaning mostly @rossgardt) also found out that this parameter is not present in the version of the script using in Bolt 2.2. So it's currently not possible to also put this fix into Bolt 2.2 without upgrading the lib there and refactoring all GUI elements using it. :(
