### ISSUE TITLE
[BUG] Assets and paths in extensions..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5240]
It seems the assets in extensions don't get the correct paths. (or i'm doing something stupid, of course)

Or, perhaps this is a side-effect of my working on an extension in `extensions/local/bobdenotter/seo` ?

Details
-------

 - Relevant Bolt Version: [ master ]
 - Install type: [ Github checkout ]

Reproduction
------------

In your (local) extension, add an asset: 

```
    protected function registerAssets()
    {
        $asset = new Stylesheet();
        $asset->setFileName('seo.css')
            ->setZone(Zone::BACKEND)
        ;

        return [
            $asset,
        ];
    }
```

In composer.json the 'web' is set: 

```
    "extra": {
        "bolt-assets": "web",
        "bolt-class": "Bolt\\Extension\\BobdenOtter\\Seo\\SeoExtension"
    }
```

I've made sure `web/seo.css` exists.

In the rendered HTML, this is the output: 

```
    <link rel="stylesheet" href="seo.css?" media="screen">
```

Which doesn't work. :-)

**Comment by GawainLynch** [comment]
You are correct… I have been wanting to open this one for a couple of days :wink:

**Comment by bobdenotter** [comment]
Just glad it's not me. :-)

**Comment by GawainLynch** [comment]
Assigning this to you, @CarsonF, mainly for direction as we have differing ideas on approach… I'll happily cut the code though if we can agree on said approach.

**Comment by PhillippOhlandt** [comment]
Lol, you (@GawainLynch) told me, that is normal behaviour on local extensions and I just have to put the file in my public folder at the right path (which indeed works). 
I was about to add a note in the docs for that.

**Comment by GawainLynch** [comment]
![image](https://cloud.githubusercontent.com/assets/1427081/14761461/cb35ba28-0962-11e6-92d3-65a27feb2703.png)
