### ISSUE TITLE
More v2 extensions showing up on v3 extend page

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5242]
Case in point, this one is not going to be updated to Bolt v3 and therefore shouldn't be shown

![image](https://cloud.githubusercontent.com/assets/1427081/14762894/3b90883e-0986-11e6-8225-237f10e44e82.png)

**Comment by SahAssar** [comment]
Removed blocker per dev-meeting

**Comment by GawainLynch** [comment]
Moving to 3.1 so "not lost"

**Comment by SahAssar** [comment]
@GawainLynch I might very well be misremembering here, but didn't you get this one in one of your extension PR's?

**Comment by GawainLynch** [comment]
No, two problems "looked" linked but were not.

**Comment by SahAssar** [comment]
@GawainLynch Since 2.2 isn't supported anymore can't we just filter out any 2.2 only extensions and just not show them? Perhaps we could show a nut command to manually install them on the market.bolt.cm page, but showing them as "first-class" extensions shouldn't be needed anymore, right?

**Comment by GawainLynch** [comment]
I'm not totally sure what to do yet, and the problem is about to hit again when 4.0 extensions start to appear, so hiding 2.2 isn't enough IMHO.

**Comment by GawainLynch** [comment]
Fixed long ago, mainly on the market place site and from memory a small query tweak in 3.2
