### ISSUE TITLE
[BUG] Field prefix and suffix 

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5245]
When adding a prefix to a field, the text is much closer to the field above than to the field it belongs to.

![](https://infinit.io/_/3iS7CkU.png)

On the screensot above, the text belongs to the Email_address field.

And I guess there were suffix'es in Bolt 2.2. But adding a suffix to a field does nothing in Bolt 3. Was it removed or am I completely wrong about the suffix option?

Details
-------

 - Relevant Bolt Version: 3 beta 3
 - Install type: composer
 - PHP version: 7.0.4
 - Used webserver: php-dev
 - For UX/UI issues: chrome, almost newest

**Comment by SahAssar** [comment]
> And I guess there were suffix'es in Bolt 2.2. But adding a suffix to a field does nothing in Bolt 3. Was it removed or am I completely wrong about the suffix option?

I think that is called postfix, not suffix.

**Comment by SahAssar** [comment]
Yep, called postfix. So that part of the issue is cleared up.

The other part is from the margin being on the `fieldset` instead of the `data-bolt-fieldset` div.

**Comment by rarila** [comment]
Update: gotta wait until node-sass is fully compatible with Node.js 6. That'll be node-sass 3.7.0 and hopefully out soon.

**Comment by bobdenotter** [comment]
> Update: gotta wait until node-sass is fully compatible with Node.js 6. That'll be node-sass 3.7.0 and hopefully out soon.

Am i getting it correctly that you're saying we can't fix this CSS issue until some future Node update?

**Comment by rarila** [comment]
No, I just said **I** can't fix it as libsass support for Node 6 on Win is missing and I have installed that as i need it for other projects cause of its great support for ES6. But from reading the issues next version should be out very soon.

**Comment by rarila** [comment]
node-sass 3.7.0 with Node.js support is out now. Unfortunately I'm away for a few days so I can't fix it right now. So, if someone wants to take over, feel free to do so. Otherwise I'll fix it when I'm back. (I'll be back;)
