### ISSUE TITLE
[RFC] Redirect to overview after deleting a record.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5247]
Maybe it's better to redirect from deleted record, or at least show notification **"You have deleted the record"**

**Comment by SahAssar** [comment]
For now, the confirm dialog seems enough, If anyone wants to PR a flash message for it I'm pretty sure it'd be welcome :)

**Comment by Boorj** [comment]
This one goes to some growls/notifications (again). Flash messages are for important, notifications - for not important.
