### ISSUE TITLE
[BUG] can't delete a record from dashboard 

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5250]
### v3.0.0.beta3

trying to delete a record from dashboard
![2016-04-28 02-37-21](https://cloud.githubusercontent.com/assets/2145313/14867392/12a8ce1a-0cea-11e6-9cb2-ecd53e825f31.png)

getting error:
![2016-04-28 02-35-56](https://cloud.githubusercontent.com/assets/2145313/14867332/d8032ddc-0ce9-11e6-8ec1-07d019c1d074.png)

and screenshot evidence where lib.js sends the request
![2016-04-28 02-36-40](https://cloud.githubusercontent.com/assets/2145313/14867374/f5ec81ea-0ce9-11e6-8462-6acc6bb567c0.png)

**Comment by bobdenotter** [comment]
It works correctly from a "contenttype overview" page, but not from dashboard.

**Comment by bobdenotter** [comment]
@rarila Is this something you can look into?

**Comment by GawainLynch** [comment]
@bobdenotter this is failing due to CSRF weirdness, and is probably the same issue as #5246 and @sbonardt is having a similar problem too.
