### ISSUE TITLE
[BUG] Can't update db - getting exception.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5251]
#### v3.00b3

I was adding some fields for SEO and meta generation to my table.
![2016-04-28 02-45-48](https://cloud.githubusercontent.com/assets/2145313/14867635/3862ea36-0ceb-11e6-8c86-90965faaa23a.png)

when i'm trying to perform db_check, it gives an exception:
![2016-04-28 02-43-59](https://cloud.githubusercontent.com/assets/2145313/14867648/49bd9722-0ceb-11e6-92fe-d9d9e9f6a40a.png)

text: 

>    An error occured while updating `bolt_articles`. The error is An exception occurred while executing 'ALTER TABLE bolt_articles ADD COLUMN share_image CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

What am I doing wrong? **Cannot add a NOT NULL column with default value NULL** — why is it so?

**Comment by GawainLynch** [comment]
Was the database crated with an earlier beta/alpha?

**Comment by Boorj** [comment]
hm.. probably yes.. but `share_image` is a new field, @GawainLynch . What should i do with db? (it's sqlite)
I also had some similar problems with NOT NULL fields, should they be caught somewhere?

**Comment by GawainLynch** [comment]
> hm.. probably yes.. but share_image is a new field

OK… but… to understand the problem, and fix it (either in code or documentation) we need to be able reproduce it… :chicken: versus :egg: 

> I also had some similar problems with NOT NULL fields, should they be caught somewhere?

Depends (but almost certainly not). Catching those errors hides them and makes correcting legitimate mistakes very difficult.

**Comment by Boorj** [comment]
Are they cought on stable versions? Is it a problem only in beta?
Anyway, thanks, @GawainLynch

**Comment by GawainLynch** [comment]
Well, the problem likely occurs due to changes that were made during development, then changed again. If we know how to reproduce it then we can work with it better :wink: 

But silencing other exceptions would hide things that we **must know** about when they happen.

**Comment by logansam** [comment]
I'm getting the same issue with imagelist. Did not use any beta version, started with 3.0.1

**Comment by SahAssar** [comment]
Also getting the same with a fresh 3.0.1 when adding a geolocation field on SQLite. Error is: `An exception occurred while executing 'ALTER TABLE bolt_pages ADD COLUMN geolocation CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL`

**Comment by GawainLynch** [comment]
Ugh… I can see where this is happening… DBAL versus Sqlite versus JSON arrays.
