### ISSUE TITLE
[BUG] tags input field not editable anymore in admin (bolt 2.2)

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#5252]
On live site editor has reported he is not able tag field anymore.
I can confirm it on configuration in details bellow. Have no idea what could possibly changed - no changes or updates were done on server for a long time. They have edited same content aprox. 6-8 weeks ago with no troubles.

However: Tags input field on taxonomy tab is present, but is not editable. Value is not visible.

`<input type="text" name="taxonomy[tags]" id="taxonomy-tags" value="zavisly" style="width: 100%;" tabindex="-1" class="select2-offscreen">`

When the class `select2-offscreen` is removed from this input field, I can see two inptut fields and the second is editable and allows me to edit the tags. Is there any fix for this?

[edit]: In console, i can see this error: `lib.min.js:149 Uncaught TypeError: Cannot read property 'id' of undefined`

Thnx for any idea to fix this

Details
-------

 - Relevant Bolt Version: [ 2.2 ]
 - Install type: [  Zip/tarball install  ]
 - PHP version: [ 5.3.10-1ubuntu3.18 ]
 - Used webserver: [ Apache ]
 - For UX/UI issues: [ safari 9.1 ]

**Comment by bobdenotter** [comment]
@lexislav which Bolt 2.2.x exactly? There's a lot of difference between 2.2.1 and 2.2.20. :-)

**Comment by lexislav** [comment]
Originally 2.2.18. Recently updated to 2.2.20 on localhost - problem is still there :-( (on localhost and production server)
Unfortunatelly I have not been editing content and tags in bolt for while, so no idea when it started, sorry.

But yes, I follow that The Bolt is making progress :-)

**Comment by lexislav** [comment]
one more observation: it is related to editing existing record with tags. Tags input field works for new records, however, the bolt is not able to recover already used tags and is still searching.

**Comment by SahAssar** [comment]
I can't verify this bug... I've tried to get it to happen in 2.2.20, but it works for me on both new and existing records. Please update to the latest version of 2.2.X and make sure you have hard reloaded the backend to get the appropriate js/css files and if it persists reopen the issue...

Thanks!
