### ISSUE TITLE
[BUG] User gets logged out from admin panel very often without apparent reason

### ISSUE THREAD

**Issue by DragonbornSR** [bolt/bolt#5256]
Details
-------

 - Relevant Bolt Version: [ 3.0 master beta 3 ]
 - Install type: [ Github checkout & Composer install ]
 - PHP version: [  5.6  ]
 - Used webserver: [ Apache version 2.4 ] Using HTTPS!!!
 - For UX/UI issues: [ Chrome ]

Reproduction
------------

 1. User gets logged out from admin panel very often without apparent reason. No log in system log to see why. It also happens in the middle of editing templates, configs and pages. Then Logout screen will not be displayed before next refresh, but saving (whatever you are editing) fails before that.
 2. /bolt/*
 3. occurs randomly when browsing in the backend panel.
 4. I expect it to log all cases when user gets logged out (forced or not)
 5. User logout gets not logged and user will end up with login screen

**Comment by GawainLynch** [comment]
We're seeing a couple of these random things come up with the current `release/3.0` branch lately… and there can also be a couple of valid reasons, 

1. [if this is set to `true`](https://github.com/bolt/bolt/blob/release/3.0/app/config/config.yml.dist#L342) and there is proxing in between the users and the site.
2. If the `app/cache/.sessions/` directory gets deleted

Can you confirm for me that neither of those are happening, and I might do up a branch to test (if you're up to it?) that might give more information.

**Comment by DragonbornSR** [comment]
Directory has not been deleted for days. variable was true, I set it to false to see if anything changes for now. It might be because the file read/write permissions are 755

**Comment by DragonbornSR** [comment]
Update... Changing cookies_use_remoteaddr: false did help to solve this problem, for now.

**Comment by DragonbornSR** [comment]
CHMOD does not affect the result.

**Comment by GawainLynch** [comment]
No, it shouldn't… the `user` is required (generally speaking) to be the web server's user ID, and group is useful so that the CLI user(s) can be a member of that group and perform `app/nut` or other file system actions.

Let us know tomorrow some time if that setting is still working though. Much appreciated for your testing :smile_cat:

**Comment by DragonbornSR** [comment]
After working for an hour, I got about 20 forced logouts again. Seems like this was not the case. Case open again...

**Comment by bobdenotter** [comment]
This should be fixed now, right?

**Comment by GawainLynch** [comment]
FWIW I think this was fixed in #5278

**Comment by DragonbornSR** [comment]
I am testing now. Will give results today.

**Comment by DragonbornSR** [comment]
after 20 minutes of testing, no random logging out bugs happened.
Edited templates, changed content, also I let it stay idle for 5 min. All good! Thanks!

**Comment by bobdenotter** [comment]
Awesome. Closing this issue then. Feel free to re-open if it pops up.
