### ISSUE TITLE
[BUG]: Twig parsing fails when field type is "markdown"

### ISSUE THREAD

**Issue by sebastiaanfranken** [bolt/bolt#5271]
The parsing of twig fails when the field type is set to "markdown". I have a `body` field in my `contenttypes.yml` with the following:

````yml
body:
            type: markdown
            height: 300px
            allowtwig: true
````

If I use a twig statement (I used ` {{ boltforms('contact') }} `) however, it doesn't work. I get to see the following: [screenshot](http://sebastiaanfranken.nl/screenshots/bolt-markdown.png).

The HTML is getting cleanly dumped. The HTML tags have been sanitized it seems.

__Details:__
- Bolt version: 2.2.20 and, according to @GawainLynch  3.x as well
- Install type: Zip install
- PHP Version: 5.6.20
- Used webserver: Apache 2.4.18 (Fedora)

__Reproduction__:
1. Install Bolt per usual
2. Create a field (let's call it `body`) in your `contenttypes.yml` file where the type is `markdown` and add `allowtwig:true`
3. Create a new piece of content to the `body` and add twig in there.
4. Publish page
5. Check page
6. See raw HTML (sanitized) on your page, like my screenshot above.

**Comment by bobdenotter** [comment]
Fixed in #5310

**Comment by bobdenotter** [comment]
Oh, wait, that's a different issue. Mea Culpa!

**Comment by bobdenotter** [comment]
This happens because the field is parsed _first_, and _then_ the html cleanup is applied. Fix incoming.
