### ISSUE TITLE
SQL exception on Blocks ContentType

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#5274]
Tried adding an imagelist to default block content type and got the following error:

An error occured while updating `bolt_blocks`. The error is An exception occurred while executing 'ALTER TABLE bolt_blocks ADD COLUMN imagelist CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

Bolt Version 3.0 beta 3
tarball install
PHP 5.6.10
Apache
Chrome latest
SQLLite

Reproduction
------------

Add:

        imagelist:
            type: imagelist
            extensions: [ gif, jpg, png ]

to blocks contetype

In bolt admin, update database.

![screen shot 2016-05-02 at 16 44 29](https://cloud.githubusercontent.com/assets/5342693/14958985/3159c8ca-1085-11e6-8fdd-43e4bf69ae0d.png)

**Comment by GawainLynch** [comment]
Brand new database, or was it upgraded from v2 or an older `master`?

**Comment by nealmarques** [comment]
I assume it was a brand new database, I just took the 3.0 tarball, pointed map to it.

**Comment by ChrisTitos** [comment]
I have the same error when I add an imagelist field to a content type (for example to "Entry").

I got the error on the last beta of 3.0. After upgrading to the release I still got the error, even after completely removing the database.

**Comment by ChrisTitos** [comment]
Never mind, I did a clean install again and now it's working fine

**Comment by GawainLynch** [comment]
I am going to assume that this was covered off in the last minute schema fixes immediately prior to release.

@nealmarques please please please reopen if it still strikes on 3.0.0 stable.
