### ISSUE TITLE
[BUG][Discussion] Composer Install with V3.0

### ISSUE THREAD

**Issue by Raistlfiren** [bolt/bolt#5277]
When running `composer create-project bolt/composer-install:^3.0 <MYPROJECT> --prefer-dist` I run into the issue - 
```

[InvalidArgumentException]
Could not find package bolt/composer-install with version ^3.0

```

Details
-------

 - Relevant Bolt Version: [ 3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.5 ]

Reproduction
------------

Run: `composer create-project bolt/composer-install:^3.0 <MYPROJECT> --prefer-dist`

Solving the Issue
------------
Run: `composer create-project bolt/composer-install:^3.0 <MYPROJECT> --prefer-dist --stability=dev`

Question
------------
Should this be posted in v3.0 documentation?

**Comment by PhillippOhlandt** [comment]
Stable will be out soon, so for me, it doesn't make much sense to add it just for the few days left.

**Comment by GawainLynch** [comment]
It was a very deliberate omission on my part to prevent people creating sites and unknowingly tracking non-release HEAD.

It is a sucky combination of chicken, eggs and :koala: :wink:

**Comment by Twiebie** [comment]
I still ran in to this issue today with the stable being out.

**Comment by GawainLynch** [comment]
Ugh… so the :koala: was eating too many :leaves: last night and forgot to tag the installer :frowning: 

Give it another try, as it is now showing up on Packagist correctly…
