### ISSUE TITLE
[BUG] - Taxonomy lost after saving

### ISSUE THREAD

**Issue by Dsduit** [bolt/bolt#5283]
Details
-------

 - Relevant Bolt Version: [ 2.2.* ]
 - Install type: [ Github checkout ]
 - PHP version: [ unknown ]
 - Used webserver: [ Apache ]
 - For UX/UI issues: [ Chrome / Safari ]

Reproduction
------------

Link for video with screencast: https://www.dropbox.com/s/ah3acd2ygrtplm0/Taxonomy_4_mei%202016%2009.01.04.mov?dl=0 

1. **Bug summary**

After saving the existing taxonomy is lost from the content-type.
When a taxonomy is declared, the user changes something in (for example) a text-field, saves, then the taxonomy is lost.

 2. **Specifics**: 

- Happens on bunkerdag.nl (also on testserver bunkerdag.twokings.eu).
- Happens in Bolt 2.2.20 but was also observed in 2.2.18.
- Method of installing Bolt? Unknown.
- Tested in Safari (9.*), Chrome (50.0.2661.94)
- See video for example.

 3. **Steps to reproduce**: 

Add a taxonomy. SAVE.
Change a text-field or something else . SAVE
Reload page with taxonomy.

 4. **Expected result**: 

I expected to see the taxonomy as saved

 5. **Actual result**: 

Result was an undefined taxonomy

**Comment by bobdenotter** [comment]
Fixed by #5337
