### ISSUE TITLE
RFC - Suggestion for better handling of Taxonomies

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#5284]
(With the risk of being told "always been like this and we're not gonna change it".. )

Step 1 - When I add a taxonomy, i usually use an 'internal name' and a descriptive text to show in bolt and the front-end.  
![screen shot 2016-05-04 at 11 44 21](https://cloud.githubusercontent.com/assets/5583671/15010743/ff3a609c-11ed-11e6-95d2-9286aa668aa3.png)

Step 2 - In the frontend I want to be able to use the 'internal' name. But there is no way this can be done without exploding. 

![screen shot 2016-05-04 at 11 44 48](https://cloud.githubusercontent.com/assets/5583671/15010742/fadc689c-11ed-11e6-8ff5-a55a9ed7c93b.png)

Iterating over a taxonomy gives me a 'link' instead of the value I specified in the taxonomy.yml. Which has always seemed highly illogical to me, and not consistent to the way Bolt works. ( I want a value, not a predefined idea of what I might do with it)

Asked around, seems I am not the only one.
Is there a reason behind this, except 'always been like this' ? And is there a possibility to change this in the future (was hoping v3 would have picked this up)?
## Details
- Relevant Bolt Version: [ all ]

**Comment by GawainLynch** [comment]
I'm going though issues at the moment, and I have to agree with @anketwokings on this one too, FWIW, it has annoyed me on more than one occasion.

@rossriley I have a sneaking suspicion you might have plans for this one, is that correct?

**Comment by anketwokings** [comment]
Haha, oh wow, that's an old one. :)

**Comment by SahAssar** [comment]
Still relevant, still a good idea :)

**Comment by rossriley** [comment]
On my radar

**Comment by bobdenotter** [comment]
Added a `'keep` label. :-)

**Comment by rossriley** [comment]
OK, so as of 3.6 when you can opt to move to the new storage system this has effectively been dealt with since iterating over a taxonomy now gives you a Taxonomy object so you will be able to do the following for the `stages` taxonomy

```
{% for stage in record.stages %}
    <option value="{{ stage.slug }}">{{ stage.name }}</option>
{% endfor %}
```

It won't be ported back to legacy storage which will continue to work as is.
