### ISSUE TITLE
[BUG] Bolt 2.2.20 not php7 ready?

### ISSUE THREAD

**Issue by parijke** [bolt/bolt#5286]
I've upgraded using composer to 2.2.20. Also I updated my system, which is now running php7.0. Since this I get the following message:

Fatal error: Cannot use Bolt\Helpers\String as String because 'String' is a special class name in /home/paul/www/bolt/extensions/vendor/bolt/clientlogin/src/UserInterface.php on line 6

Bolt3 is running smoothly on php7.0 sofar

**Comment by GawainLynch** [comment]
2.x has been fully compatible with PHP 7 since 7.0-rc4.

You have upgraded from an old Bolt version as we had a `Bolt\Helper\String` class that was removed in 2.1 or 2.2 over a year ago… simply removing that file will be enough. :+1:

**Comment by SahAssar** [comment]
Small caveat: The version of whoops included with bolt 2.x is not fully PHP 7 compatible, but that only shows if there was a major error anyway and you have `debug_enable_whoops` turned on.

**Comment by parijke** [comment]
That did the job Gawain thx
