### ISSUE TITLE
[BUG] Twig ArrayHelper::orderHelper() addressing

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#5289]
Describes #5257, #5272 
## Reproducing

I have a contenttype `calculators` and it is fetching by a template as below
![selection_134](https://cloud.githubusercontent.com/assets/761149/15109859/d1c7aaf4-15dd-11e6-8665-53e09e3915d3.jpg)

In the highlighted row shows it is need to be ordered so the execution will flow into `ArrayHelper::orderHelper()` 

![selection_137](https://cloud.githubusercontent.com/assets/761149/15109965/6fbcc1ea-15de-11e6-83fc-97aacb2e0262.jpg)

After hooking there can see resulting `null` values got because of array addressing at line 99,100 while we got `\Bolt\Content` that should be acceptable as parameter of the method. This will be producing a wrong sort order of records.

![selection_139](https://cloud.githubusercontent.com/assets/761149/15110024/d02c785e-15de-11e6-8a48-4fa3af8a930f.jpg)

**Comment by SahAssar** [comment]
Per the comments in #5272, having a working test case would probably help, could you possibly provide that in that PR? Thanks!

**Comment by SahAssar** [comment]
Closing per #5272 and #5257. Please reopen if a working testcase is there and then we can work on fixing it :)
