### ISSUE TITLE
[BUG] Symlink to app/nut won't be created

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5306]
I just deployed our current Bolt 3 project to a test server. I have a normal composer installation so I did a `composer install` after deployment. 

For some reason the `app/nut` symlink to `../vendor/bin/nut` wasn't created.
I know it worked on Bolt 3 Beta 1 because that's the version I started with on my local machine and the symlink was created there.

Details
-------

 - Relevant Bolt Version: 3.0.0
 - Install type: composer
 - PHP version: 7.0.4
 - Used webserver: nginx

**Comment by GawainLynch** [comment]
Did you use the `composer create-project` method, or a from-scratch `composer.json` approach?

**Comment by GawainLynch** [comment]
...and 7.0.4 is so last month :wink:

**Comment by PhillippOhlandt** [comment]
@GawainLynch I used the `composer create-project` method. And I see just now that the `nut` symlink is already there in the `bolt/composer-install` repo :D 
https://github.com/bolt/composer-install/blob/master/app/nut 

Weird that the file wasn't deployed then, it's also in our git repo. (We use deploybot.com)

**Comment by SahAssar** [comment]
Since this has been inactive for so long and since the symlink is actually in the repo I'm gonna close this, please feel free to reopen if this is actually an issue with bolt or bolt/composer-install!
