### ISSUE TITLE
BUG Repeater-fields

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#5311]
The problem description is simple: when copypasting the example code, and adding some repeater items to an page, Bolt says: "Could not Save Page" when hitting the save button.

PHP5.6, MySQL

It's possible that I'm using the wrong or incomplete documentation, [I only had this](https://github.com/bolt/bolt/blob/release/3.0/app/config/contenttypes.yml.dist#L165)
via Ross' comment on https://discuss.bolt.cm/d/291-repeater-fields-documentation-are-missing

**Comment by GawainLynch** [comment]
Check the result on the request in the "Network" tab in the browser developer tools, that might give more information to help

**Comment by evertalbers** [comment]
![schermafbeelding 2016-05-12 om 17 08 45](https://cloud.githubusercontent.com/assets/3974120/15219495/4f6c56ac-1864-11e6-8338-875ca7e69aa6.PNG)

The "Could not save.." notification appears at the same moment as the last error 500-line, so I guess that's the troublemaker and clicked it so you see that one in the right column.

Browser related? Latest FF. I'll try Chrome now.

**Comment by GawainLynch** [comment]
Chrome will give you something like this:
![image](https://cloud.githubusercontent.com/assets/1427081/15219747/31069dca-1865-11e6-8afb-92a38fa755c5.png)

On the "Preview" subtab will be either JSON or HTML returned that often tells you what you need to know.

**Comment by evertalbers** [comment]
![schermafbeelding 2016-05-12 om 17 20 14](https://cloud.githubusercontent.com/assets/3974120/15219941/e3ef5166-1865-11e6-90b6-071aa8bef69b.PNG)
Chrome errors as well.
Hope this is what you want - can't get the same layout as your example.

**Comment by GawainLynch** [comment]
Nah, that doesn't tell me anything useful…

You should just be able to click on `1?returnto=ajax` and get a new frame open to the right as in my screenshot.

**Comment by evertalbers** [comment]
Not sure if it's what you want but I see this under XHR:

`{"error":{"type":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","message":"An exception occurred while executing 'INSERT INTO bolt_field_value (contenttype, content_id, name, grouping, fieldname, fieldtype, value_string, value_text, value_integer, value_float, value_decimal, value_date, value_datetime, value_json_array) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"homepages\", \"1\", \"repeater\", 0, \"repeattitle\", \"text\", null, \"asdasd\", null, null, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value_json_array' cannot be null","file":"\/domains\/blix-bv.com\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","line":112}}`

**Comment by SahAssar** [comment]
This is should have been fixed in #5291, right? Is the DB from before the Bolt 3.0 release?

**Comment by rossriley** [comment]
Yes, that's right, that was the issue fixed in #5291

**Comment by GawainLynch** [comment]
I agree with @rossriley & @SahAssar that this issue was fixed in #5291 

… that said, are we seeing a repeat of the disaster that was #1555 by any chance? :wink:

**Comment by evertalbers** [comment]
You are right, I did not realise that the Release Candidate was not 3.0.0 -  Humble apologies for not noticing that.

Just updated as described in https://docs.bolt.cm/3.0/upgrading/updating, incl. the composer install - interesting experience for a designer. 

Anyway, everything seems to be working fine now. Repeater contenttypes galore!
