### ISSUE TITLE
[BUG] Repeater fields as 'templatefields' in theme.yml

### ISSUE THREAD

**Issue by jan-t3000** [bolt/bolt#5320]
When putting repeater field as templatefield in a theme.yml they do show up in the backend properly, but saving the the contenttype fails. "Could not save %contenttype%".

**Comment by ryanturner10** [comment]
+1

**Comment by willstorm** [comment]
+1

**Comment by willstorm** [comment]
How this type of field behaves with live editing?

**Comment by SahAssar** [comment]
Please do not respond with "+1" as that only clutters the threads, github has a reaction feature for that now. I've deleted the comments that were just "+1"s (two, from @ryanturner10 and @willstorm).

Also, with regards to how it behaves in live editing that is a different question. IIRC it does not work in live edit, but this type of question is better asked on the slack/IRC channels or on the forum.
