### ISSUE TITLE
[BUG] Some HTML Entities in CKEditor are always unescaped

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#5323]
Adding some HTML entities in CKEditor (even if they are encoded in the source editor), will result in them being converted to their character counterpart and thus breaking the HTML output.
## Details
- Relevant Bolt Version: 2.2 (haven't tested in others)
- Install type: Composer install
- PHP version: 5.6
- Used webserver: PHP web dev server
- For UX/UI issues: Google Chrome 50.0.2661.94 (64-bit)
## Reproduction

Edit the source of an HTML field, add `&lsquo;` for example.

![image](https://cloud.githubusercontent.com/assets/3238878/15275782/adbcbe80-1acc-11e6-877f-d865a3b77681.png)

Navigate back to the editor tab.

![image](https://cloud.githubusercontent.com/assets/3238878/15275786/b6ecbb04-1acc-11e6-843f-91e3f191a901.png)

Navigate back to the source tab, notice how the `&lsquo;` has been resolved to its corresponding character.

![image](https://cloud.githubusercontent.com/assets/3238878/15275788/c229f374-1acc-11e6-95d4-71be49ac0b03.png)

What is expected is that this encoding is respected, and the `&lsquo;` stays as such.

**Comment by SahAssar** [comment]
If I understand correctly this is purely upstream in CKEditor and we would need an issue or bug report opened there to actually get it fixed. Do you feel like opening that issue @Pinpickle?

**Comment by GawainLynch** [comment]
Closing as both and old, and upstream, issue. If we cn do more, please feel free to re-open with more data that we can work with and we'll do what we can :+1:
