### ISSUE TITLE
[BUG] "Delete %contenttype%" Button (/editcontent/... Sidebar)

### ISSUE THREAD

**Issue by jan-t3000** [bolt/bolt#5324]
I've come across this issue... 

[http://i.imgur.com/vq5b6P1.jpg](http://i.imgur.com/vq5b6P1.jpg)
Doesn't work.

[http://i.imgur.com/oqy6I94.jpg](http://i.imgur.com/oqy6I94.jpg)
In this 'Overview' submenu...
[http://i.imgur.com/1ziju8F.jpg](http://i.imgur.com/1ziju8F.jpg)
...it works.

**Comment by GawainLynch** [comment]
ping @bobdenotter or @rarila

**Comment by bobdenotter** [comment]
I can't reproduce.. It seems to work for me: 

![screenshot 2016-05-22 15 14 25](https://cloud.githubusercontent.com/assets/1833361/15454146/f01c2b40-202f-11e6-81a7-b4894fea0e28.png)

Any details on what exactly is not working about it?

**Comment by bobdenotter** [comment]
NVM, found it! Fix incoming.
