### ISSUE TITLE
[RFC] making html snippets insert points widgets

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#5325]
I'd like to propose that we make the html snippets insert points (like END_OF_HEAD) something more like widget functions. That way we would avoid parsing the HTML with regex (which is a bad idea and can be slow, see #5294), and we would have less "magic" happening in the `after` stage.

**Comment by GawainLynch** [comment]
htmlsnippets were removed from Bolt about half way thought 3.0-dev

…or am I missing something?

**Comment by SahAssar** [comment]
@GawainLynch Ah, sorry I used htmlsnippets as a general name for assets/code inserted in certain predefined points, like canonical, favicon and also extension scripts/styles.

**Comment by GawainLynch** [comment]
Ah! :laughing: 

I don't think this is possible. In the case of what Bolt itself injects, we do that on any render (depending on route), ergo we don't expect template developers to care/implement.

In the case of something like extensions, how would an extension reliably load assets without the template designer coping?

**Comment by SahAssar** [comment]
Well, most other cms'es that I've seen have something akin to this (not that that is a reason to do it, but rather an argument that doing it is not unusual)... To me it seems more logical, especially since the <head> and <body> tags are optional in html5, so getting the right position with regex seems impossible,

**Comment by GawainLynch** [comment]
Regex & HTML … well … ZA̡͊͠͝LGΌ ISͮ̂҉̯͈͕̹̘̱ TO͇̹̺ͅƝ̴ȳ̳ TH̘Ë͖́̉ ͠P̯͍̭O̚​N̐Y̡ H̸̡̪̯ͨ͊̽̅̾̎Ȩ̬̩̾͛ͪ̈́̀́͘ ̶̧̨̱̹̭̯ͧ̾ͬC̷̙̲̝͖ͭ̏ͥͮ͟Oͮ͏̮̪̝͍M̲̖͊̒ͪͩͬ̚̚͜Ȇ̴̟̟͙̞ͩ͌͝S̨̥̫͎̭ͯ̿̔̀ͅ

Nonetheless, due to BC we just can't do this during v3 and c.f. #2109 & #2153

**Comment by SahAssar** [comment]
Yep, not meant for 3.0, if it is agreed on it will be a 4.0 change.

Anyway, the less magic and regex-html we can do I think it's a good thing.

**Comment by GawainLynch** [comment]
Agreed… biggest problem is that it is a *huge* job and the amount of people capable versus willing… That said, I can do what I can to help… but it won't be easy :wink:

**Comment by SahAssar** [comment]
Closing... If this turns out to be needed/wanted a PR will turn up (taking a cavalier tone on it since it was opened by myself.)
