### ISSUE TITLE
[BUG] Repeater fields type 'Select' doesn't store value

### ISSUE THREAD

**Issue by jan-t3000** [bolt/bolt#5326]
When putting a 'Select' type as repeater field, the value (as set in contenttype.yml - values: [ "None", "Example1", "Example2" ]) won't get stored. (value_string in bolt_field_value remains NULL, value_text becomes "%someid%" instead of the desired value configured as selectable via contenttype.yml) 

{{ dump(repeater.get('select-field')) }} then just outputs "%someid%" (expected, i.e. "Example1"...)

---
Workaround (until fixed):
see - values: [ "None", "Example1", "Example2" ]
as values: [ 0, 1, 2 ]
and put corresponding {% if repeater.get('select-field') == 2 %}Example2{% endif %}
in twig...

perhaps less tedious {% switch %} {% case %} ...

**Comment by SahAssar** [comment]
This is how all select fields work in bolt though? It stores the key, not the value. You can define the keys by using something like this though:

```
values: { "None": "None", "Example1": "Example1", "Example2": "Example2" }
```

We've been thinking of implementing a getter for the value, but... limited time, you know.

**Comment by jan-t3000** [comment]
I see! I'll change the yml then, fair enough :)
Thanks!

**Comment by tourdefran** [comment]
Hello guys, 
I'm in the same situation here 
Is there available a new approach to this case study?
Thanks in advance

EDIT:
My workaround, just in case, for any random reader...
```
{% for item in record.items %}
    {% for field in item %}
        {% if field.fieldtype == 'select' %}
            {% setcontent productname = "productos" where { 'id': field.value } returnsingle %}
                <p>Nombre: {{ productname.nombre }}</p> 
        {% endif %}
    {% endfor %}
{% endfor %} 
```
