### ISSUE TITLE
[BUG] Thumbnail must return a string value

### ISSUE THREAD

**Issue by gander** [bolt/bolt#5329]
Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Zip install
 - PHP version: 5.5
 - Used webserver: Apache

Reproduction
------------

1) Installed locally, inside the container Docker
2) Gave permission `chmod -R 777 .`
3) Created a root user
4) Logged
5) Displayed a page "Files"
6) Thumbnails do not show up
7) I went to the picture http://bolt.dev/thumbs/1000x1000r/agriculture-cereals-field-621.jpg
8) Displayed a following error:

> Catchable fatal error: Method Bolt\Thumbs\Thumbnail::__toString() must return a string value in /www/bolt.dev/vendor/symfony/http-foundation/Response.php on line 400

**Comment by bobdenotter** [comment]
Could that be related to this? #3629

**Comment by nightmarepl** [comment]
Same bug here. Both extensions enabled. I use Docker too.

Install type: composer
PHP: 7.0.6
Webserver: Nginx

**Comment by bobdenotter** [comment]
I haven't been able to reproduce this yet, but could either of you take a look to see if this fixes it? 

https://github.com/bolt/bolt/pull/5382/files

**Comment by nightmarepl** [comment]
No, it does not. I found that the $thumbnail variable passed to Bolt\Thumbs\Thumbnail's constructor is false.

**Comment by bobdenotter** [comment]
Any idea what causes that? Since i can't reproduce it yet, any information might help.

**Comment by nightmarepl** [comment]
For some reason, the imagecreatefromstring placed in Bolt\Thumbs\ImageResource::createFromString returns false. That's why resize returns false instead of throwing exception. I have no idea, why the function is not working.

**Comment by adamlc** [comment]
I'm also having this problem when running inside a docker container. Did you ever figure out what it was @nightmarepl ?

**Comment by mikemcgowan** [comment]
It's probably because **gd** hasn't been compiled with jpeg support ...

![no-jpeg-support](https://cloud.githubusercontent.com/assets/2492670/26064873/21cb5584-398a-11e7-8561-384a404889df.png)

As per [this link](https://github.com/docker-library/docs/tree/master/php#php-core-extensions), you probably want to compile **gd** with something like this:

```
FROM php:7.0-fpm
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libmcrypt-dev \
		libpng12-dev \
	&& docker-php-ext-install -j$(nproc) iconv mcrypt \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) gd
```

**Comment by romulo1984** [comment]
This worked best for me, on an Alpine-based image.

https://github.com/docker-library/php/issues/225

**Comment by JarJak** [comment]
https://github.com/bolt/thumbs/pull/48 this will provide you a better exception message.

**Comment by Ichag** [comment]
I use the following Dockerfile as basis for my projects. JPEG support only gets enabled when I separate `gd` installation from all other extensions O_o . After using this template all thumbnails are getting generated as expected!

```
FROM php:7.1-fpm-stretch

MAINTAINER Max Hellwig "mail@maxhellwig.de"

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV BASE_DIR="/var/www/html"

RUN apt-get update && apt-get install -y  libpq-dev git libzip-dev  wget libxrender1 libfontconfig1 libicu-dev
RUN docker-php-ext-configure intl --with-icu-dir=/usr && \
        docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql && \
        docker-php-ext-install pdo_pgsql pgsql && \
        docker-php-ext-install exif && \
        docker-php-ext-install zip && \
        docker-php-ext-install intl && \
        docker-php-ext-install opcache && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libmcrypt-dev \
		libpng-dev \
	&& docker-php-ext-install -j$(nproc) iconv mcrypt \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) gd

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

COPY docker/php/custom.ini /usr/local/etc/php/conf.d/custom.ini

COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

```
