### ISSUE TITLE
[BUG] Sidebar overlaps CKeditor in fullscreen mode

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#5331]
Details
-------

 - Relevant Bolt Version: [ 3.0 ]
 - For UX/UI issues: [ Chrome Canary 50.0.2640.0  ]

Reproduction
------------

When using the CKeditor in fullscreen mode, the sidebar overlaps it, my guess is that it could be a z-index issue, here's a screenshot:

![ckeditor](https://cloud.githubusercontent.com/assets/3504472/15298435/7e5cdab8-1b5c-11e6-8ff5-36e69bbb29bc.png)

PS. I do not like brown M&M's.

**Comment by brysont** [comment]
Same issue in v3.0.1 with lastest Chrome, 50.0.2661.102 m.
