### ISSUE TITLE
[RFC] - Add a Bolt-2-latest downloadlink for ease of maintainability

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#5334]
Since we still support the 2.x version in the docs, it would be easy to have a 
`https://bolt.cm/distribution/bolt-2-latest.tar.gz` link as well, that always contains the last version of the 2.x branch. 

(Added this issue by request of Bob.)

**Comment by bobdenotter** [comment]
Done! 

 - https://bolt.cm/download
 - https://docs.bolt.cm/2.2/getting-started/installation
