### ISSUE TITLE
[BUG] Page Link ⇒ Browse Server broken in 3.0.0

### ISSUE THREAD

**Issue by xstable** [bolt/bolt#5340]
Details
-------
 - Relevant Bolt Version: 3.0.0
 - Install type: Zip/tarball install
 - PHP version: 7.0 
 - Used webserver: Apache 
 - For UX/UI issues: Google Chrome on Linux

Reproduction
------------

1. Open an anchor-Link in WYSIWYG-editor
1. Tab=Linkinfo ⇒ Press "Browse Server" Button
1. Popup-Opens ⇒ choose Tab "Pages"
1. Choose a link

What happend: The link will be open inside of the popup, instead to putt the link-url to the textfield, as expected.

See Images:

![bug_bolt](https://cloud.githubusercontent.com/assets/1778068/15402375/2a3d0986-1df4-11e6-9675-134db0c7389d.jpg)

And this in English by brysont:
![bolt_bug2](https://cloud.githubusercontent.com/assets/1778068/15402401/4686ba10-1df4-11e6-80dd-22c030ac4d26.png)

![bolt_3](https://cloud.githubusercontent.com/assets/1778068/15402413/59ec3102-1df4-11e6-926e-d818475f4b07.png)

**Comment by brysont** [comment]
Last 2 screenshots are mine, which are from Bolt v3.0.1 on PHP 7, DO VPS, so it is a v3.x issue. Applies regardless of which contenttype is being selected from the server.

**Comment by bobdenotter** [comment]
Found it! Fix incoming!
