### ISSUE TITLE
[Bug] Using Html 'base' tag breaks pagination links

### ISSUE THREAD

**Issue by dadaxr** [bolt/bolt#5346]
The way Paging works is not compatible with the use of html 'base' tag.

they are many use case where we must define the html base tag  within the html head tag.: 
example : 
`<base href="{{ paths.rooturl }}">`

The problem is : 
given a content type "entries", 

```
entries:
    name: Entries
    singular_name: Entry
    fields:
    ...
    listing_records: 10
```

we can list 10 of them with this url http://site.com/entries, which match the default route 

```
contentlisting:
    path: '/{contenttypeslug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::listing'
    requirements:
        contenttypeslug: 'Bolt\Controllers\Routing::getPluralContentTypeRequirement'
```

We just have to use the {{ pager() }} twig function in our template to generate the pagination.

By default the html generated by the app/theme_defaults/sub_pager.twig template is something like that : 

```
<div class="pagination pagination-centered ">
  <ul class="pagination">
    <li class="active"><a href="?&page_entries=1">1</a></li>
    <li><a href="?&page_entries=2" rel="noindex, follow">2</a></li>
    <li><a href="?&page_entries=2" rel="noindex, follow">›</a></li>
  </ul>
</div>
```

you can notice that the generated link href attributes does not contain the full url ( it's a relative link ).
So how works a relative link  ?
if the url is : 
http://site.com/entries , the relatives links should target to : http://site.com/entries?page_entries=XXX
EXCEPT if we have defined an html base tag, in that case, the relative link use the base tag url ... as base.

So it's quite usual to define the html base tag to the root url, as i write abose : 
`<base href="{{ paths.rooturl }}">` 
==> which generate 
`<base href="http://site.com">` 

SO in that case the pagination links target to http://site.com/?page_entries=XXX and ... that's not the good url. ( it does not contains the content type part (entries), so the link do not paginate anything... and redirect to the root, in that case. )

We can fix that behavior in the Bolt\Pager class, within the makeLink() method.
I think that method should retrieve the current "script" url and use it as prefix before adding the pagination parameters.

Just to be quick, this is the actual Pager::makeLink() implementation: 

```
/**
     * Used for calling from template to build up right paginated URL link.
     *
     * @return string
     */
    public function makelink()
    {
        /*
         * If link set directly that forces using it rather than build
         */
        if ($this->link) {
            return $this->link;
        }

        $pageid = static::makeParameterId($this->for);
        $parameters = $this->app['request']->query->all();
        if (array_key_exists($pageid, $parameters)) {
            unset($parameters[$pageid]);
        } else {
            unset($parameters['page']);
        }

        $parameters[$pageid] = '';
        $link = '?' . http_build_query($parameters);

        return $link;
    }
```

I think we can just add something like that : 

```
...
        $parameters[$pageid] = '';
        $link = $this->app['paths']['current'] . '?' . http_build_query($parameters);

        return $link;
}
```

where $this->app['paths']['current'] contain the '/entries' part.
That way pagination links are no longer fully relative, but relative to the root ( so that  links are not relying on the base tag and still works. )

Any thoughts on that ? 

Details
-------
 - Relevant Bolt Version: [ >= 2.2 & 3.0 ]

**Comment by bobdenotter** [comment]
Maybe i've not had enough coffee yet, but i'm not sure this is a problem we can solve, right? What you're seeing is a result of using the `<base href>` tag in your HTML, and it affects all relative links on the page. Because the PHP code isn't aware of a `<base href>` tag being present (might be added in the template itself, in an include, or through an extension), I don't think we'll be able to properly account for this.

**Comment by dadaxr** [comment]
I think we can fix. It's not necessary to know if there is a base tag in the template or not.
We just have to modify the "makelink" function to include the last part of the url in the generated link.

for instance for the the page http://site.com/entries
today the "makelink" method just generate "?page_entries=X" , we should generate "entries?page_entries=X" ( no starting "/" ). That way, we keep a relative link which include the "context" to paginate.

Come on, one more cup of coffe and you'll get my point :)

**Comment by SahAssar** [comment]
@dadaxr Just a question, what is your reason to use the base tag? I've never seen it used in modern web-dev, so I thought I'd ask.

**Comment by dadaxr** [comment]
One of my usage is, when i push a site in preproduction.
for example : 
- my local url is : http://local.mysite.com ( which point directly to the web root folder of the bolt project via the virtual host )

but then before going totally live, I push my website in a preproduction env which is accessible from outside. For convenience I have only one url for every project ( not only bolt's ones ) so it ends up with : 
http://mypreprodurl.com/mysite/ 
Why not using subdomain ? because i use a free domain provider like no-ip.org and "subdomain" is a paying option. So i'm using the base html tag to say  : this is the new root budy !

**Comment by SahAssar** [comment]
@dadaxr: It seems to me like it would just be easier to pay for one domain and then use subdomains under that... But, if you want to keep the way you do things now just add `{{app.paths.currenturl}}` in `_sub_pager.twig`, which you can bundle with your theme.

**Comment by dadaxr** [comment]
Yeah of course I can do that.. but ... what's the problem about fixing the way I suggested ?
It impacts the twig function directly, not the pager service ... so i cant see any use case where ouputing the link prepended with the $this->app['paths']['current'] is broking the existing.

**Comment by SahAssar** [comment]
@dadaxr: yep you're right, sounds good to me... Wanna PR the change?

**Comment by dadaxr** [comment]
Yep, will do that this evening :)

**Comment by dadaxr** [comment]
@SahAssar I think we can close no ?
