### ISSUE TITLE
BUG default image not showing if a image field is empty

### ISSUE THREAD

**Issue by kupalizer** [bolt/bolt#5347]
Bolt Version 3.0.1, Fresh install with composer

Expect to get the image url specified in the config.yml when a image field is empty on a record

Can be reproduced if you do `<img src="{{ thumbnail('record.imagefield', 300, 300) }} ">` 
Output from the thumbnail function will be empty string, expect to be view/img/default_notfound.png when the field is empty

**Comment by SahAssar** [comment]
Just to be sure... You do mean `<img src="{{ thumbnail(record.imagefield, 300, 300) }} ">`, not `<img src="{{ thumbnail('record.imagefield', 300, 300) }} ">` right? (see the single-quotes around `record.imagefield`)

**Comment by kupalizer** [comment]
Yes, sorry, thats right SahAssasr

**Comment by kupalizer** [comment]
Another problem related to this issue is that when I change the settings in config.yml
  notfound_image: view/img/my_picture.png
  error_image: view/img/my_picture.png

Bolt 3 will not find these images (placed in same folder as the distributed images) I had these settings in Bolt 2 but can not manage to make it work in Bolt 3

**Comment by frozenshadow** [comment]
Same problem here. Changing error and notfound image produces the following exception:

```
( ! ) Fatal error: Uncaught Error: Call to a member function getImageInfo() on null in /bolt/vendor/bolt/filesystem/src/Handler/Image.php on line 24
( ! ) Error: Call to a member function getImageInfo() on null in /bolt/vendor/bolt/filesystem/src/Handler/Image.php on line 24
Call Stack
#	Time	Memory	Function	Location
1	0.0001	361352	{main}( )	.../index.php:0
2	0.1474	2068512	Silex\Application->run( )	.../index.php:14
3	0.1476	2075424	Silex\Application->handle( )	.../Application.php:563
4	0.2494	4687912	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../Application.php:586
5	0.2494	4688328	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../HttpKernel.php:64
6	0.3416	5705840	call_user_func_array:{/bolt/vendor/symfony/http-kernel/HttpKernel.php:144} ( )	.../HttpKernel.php:144
7	0.3416	5706312	Bolt\Thumbs\Controller->thumbnail( )	.../HttpKernel.php:144
8	0.3427	5718688	Bolt\Thumbs\Responder->respond( )	.../Controller.php:75
9	0.3429	5718688	Bolt\Thumbs\Responder->getThumbnail( )	.../Responder.php:70
10	0.3442	5718728	Bolt\Thumbs\Creator->create( )	.../Responder.php:95
11	0.3442	5718728	Bolt\Thumbs\Creator->verifyInfo( )	.../Creator.php:38
12	0.3442	5718728	Bolt\Filesystem\Handler\Image->getInfo( )	.../Creator.php:60
```

**Comment by GawainLynch** [comment]
Thank you @frozenshadow … that is really helpful!

**Comment by SahAssar** [comment]
I've experienced this when bolt generates a "folder url" like "/thumbs/100x100r/", and not having a proper fallback for that in the server config.  Not sure if we should change the url generated or the recommend server config, but that has been my experience.

When using a server config that hits the backend even for those urls it'll give the right backup image in my experience.

**Comment by SahAssar** [comment]
IMO this is a server config issue. We should hit the server for every directory request and every non-existent file request. Self-assigning as a docs issue.

**Comment by CarsonF** [comment]
There is actually a bug [here](https://github.com/bolt/bolt/blob/release/3.3/src/Provider/ThumbnailsServiceProvider.php#L75) and [here](https://github.com/bolt/bolt/blob/release/3.3/src/Provider/ThumbnailsServiceProvider.php#L84).

The fallback objects aren't getting the filesystem object assigned to them. This only happens though when the image can't be found. 

Letting the `FileNotFoundException` bubble up would be better, but open to other suggestions about how to more gracefully handle this case.

**Comment by SahAssar** [comment]
Ah, In that case I'll leave it in your hands @CarsonF :)

**Comment by bobdenotter** [comment]
Is this still relevant? Works for me.
