### ISSUE TITLE
Fatal error: "There is no suitable CSPRNG installed on your system" 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5361]
On every page in the backend. On Bolt 3, PHP 5.6.21.

Full error stacktrace: 

```
Bolt - Kritieke fout.
Class Twig_Error_Runtime
Bericht: An exception has been thrown during the rendering of a template ("There is no suitable CSPRNG installed on your system") in "@bolt/dashboard/_recently_edited.twig" at line 12.
Code 0
Twig_Template->displayWithErrorHandling()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 355

Twig_Template->display()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 366

Twig_Template->render()
[root]//vendor/twig/twig/lib/Twig/Extension/Core.php, regel 1463

__TwigTemplate_ac94884343e370602042fa16cee0584ae83ce3de1e02fc940c05947d2b8ed665->block_page_main()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 167

Twig_Template->displayBlock()
[root]//app/cache/92/9228d8c2494874a24d0592bafb11897b571b8e7d06919d154b8700963672d9bf.php, regel 156
array:3 [▼
  0 => & "page_main"
  1 => & array:24 [▶]
  2 => & array:7 [▶]
]
__TwigTemplate_00dee96435a0ae98c1fbba0af1b3fc118aa7af52fb5aecb89194e133438a757b->block_page_plain()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 167

Twig_Template->displayBlock()
[root]//app/cache/b1/b15bd4fe13473afa8b7300264ea188441a61f40468d6a04311ca71f823519f64.php, regel 202
array:3 [▼
  0 => & "page_plain"
  1 => & array:24 [▶]
  2 => & array:7 [▶]
]
__TwigTemplate_bbefc424eccc15898826cea21e3b508cafa581417085b66d5fac1c1b2d261a37->doDisplay()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 381

Twig_Template->displayWithErrorHandling()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 355

Twig_Template->display()
[root]//app/cache/92/9228d8c2494874a24d0592bafb11897b571b8e7d06919d154b8700963672d9bf.php, regel 37
array:2 [▼
  0 => & array:16 [▶]
  1 => & array:6 [▶]
]
__TwigTemplate_00dee96435a0ae98c1fbba0af1b3fc118aa7af52fb5aecb89194e133438a757b->doDisplay()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 381

Twig_Template->displayWithErrorHandling()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 355

Twig_Template->display()
[root]//app/cache/59/59d87893c8f842c22755f0a05cb125b8afd6692f26bd3c1c4523797f9ee3104d.php, regel 30
array:2 [▼
  0 => & array:13 [▶]
  1 => & array:4 [▶]
]
__TwigTemplate_ac94884343e370602042fa16cee0584ae83ce3de1e02fc940c05947d2b8ed665->doDisplay()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 381

Twig_Template->displayWithErrorHandling()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 355

Twig_Template->display()
[root]//vendor/twig/twig/lib/Twig/Template.php, regel 366

Twig_Template->render()
[root]//vendor/bolt/bolt/src/Response/BoltResponse.php, regel 198

Bolt\Response\BoltResponse->compile()
[root]//vendor/bolt/bolt/src/Response/BoltResponse.php, regel 174

Bolt\Response\BoltResponse->getContent()
[root]//vendor/symfony/http-kernel/HttpCache/Esi.php, regel 131

Symfony\Component\HttpKernel\HttpCache\Esi->addSurrogateControl()
[root]//vendor/symfony/http-kernel/EventListener/SurrogateListener.php, regel 49

Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
[root]//vendor/symfony/event-dispatcher/EventDispatcher.php, regel 46

Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
[root]//vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php, regel 140

Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
[root]//vendor/symfony/http-kernel/HttpKernel.php, regel 179

Symfony\Component\HttpKernel\HttpKernel->filterResponse()
[root]//vendor/symfony/http-kernel/HttpKernel.php, regel 161

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]//vendor/symfony/http-kernel/HttpKernel.php, regel 62

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, regel 586

Silex\Application->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, regel 563

Silex\Application->run()
[root]//public_html/index.php, regel 14
[]
```

**Comment by bobdenotter** [comment]
Workaround is here: https://github.com/paragonie/random_compat/releases/tag/v1.3.0

**Comment by GawainLynch** [comment]
Am I understanding that this only occurs when you do not have a working OpenSSL installed?

**Comment by bobdenotter** [comment]
@GawainLynch Nope: https://github.com/paragonie/random_compat/issues/99#issuecomment-198380215

> Please check the version 1.3.0 release notes. We removed OpenSSL in 1.3.0 due to a preponderance of concerns over its reliability as a secure provider of random data.

**Comment by bobdenotter** [comment]
In my case, requiring `"paragonie/random_compat": "1.2.2"` made the problem go away.

**Comment by GawainLynch** [comment]
Right… I take it this is on OS X then?

**Comment by bobdenotter** [comment]
Nope, on the recently updated shared hosting server. :-)

**Comment by bobdenotter** [comment]
Seems that `"paragonie/random_compat": "^1.4"` does the trick too.

**Comment by paragonie-scott** [comment]
This isn't a complete fix. See: https://github.com/ramsey/uuid/issues/80

Relying on OpenSSL's broken RNG in a non-fork-safe environment (anything Apache or FPM-- which by my estimates is what most people use) will lead to security problems; i.e. worst case scenario: repeated nonces.

**Comment by bobdenotter** [comment]
Hey @paragonie-scott,

We _are_ aware of the best practices, and we agree that your approach makes sense. 

However, we think it's bad practice to _break_ working implementations in "userland" without warning people in advance. And that is exactly what happened when the latest version got pulled in, and wound up in our distro's. 

So yes, technically speaking you are correct, but it also means sudden breakage on a non-major version, which is just not acceptably to users, who look to us to not break shit in a 0.0.1 update. 

That's why we're sticking to the 1.x branch for now. Which, imho, works just fine. 

Also, just a sidenote: I think that if you're making a library that's basically a polyfill for future versions, it's a bit odd to scrap features from it. Isn't the entire purpose of it to be a bridging library, until everybody is on PHP 7?

**Comment by paragonie-scott** [comment]
> I think that if you're making a library that's basically a polyfill for future versions, it's a bit odd to scrap features from it. Isn't the entire purpose of it to be a bridging library, until everybody is on PHP 7?

Version 2 is actually a truer polyfill than version 1, since PHP 7 doesn't ever depend on OpenSSL. It was added as a "worst-case attempt" at not failing closed. Since v1.0.0 was tagged, a lot of concerns were raised about OpenSSL's RNG. Version 1 is friendlier towards broken systems, at the cost of security, which is bad for a *security* feature.

> However, we think it's bad practice to break working implementations in "userland" without warning people in advance.

The 1.3.0 decision was [discussed here](https://github.com/paragonie/random_compat/issues/96#issuecomment-197554247), and was reverted in 1.4.0 because it turns out, everyone was wrong, that *is* a breaking change.

> So yes, technically speaking you are correct, but it also means sudden breakage on a non-major version, which is just not acceptable for us to do to our users, who look to us to not break shit in a 0.0.1 update. 

That's fine, and also the *entire* reason why Paragon is still maintaining v1.x. I just wanted to make sure the risks were communicated. :)

**Comment by paragonie-scott** [comment]
Sidenote: Specifying `^1.4` in your main repository is fine, but for any components I highly recommend `^1|^2` instead, in case someone explicitly uses version 2 in their project.

**Comment by temple** [comment]
So, 
¿Why don't you set your _php_ `open_basedir` parameter and allow _php_ accessing `/dev/urandom`?

**Comment by GawainLynch** [comment]
> ¿Why don't you set your php open_basedir parameter and allow php accessing /dev/urandom?

For people that have access to that, it is possible, but people will use shared hosting … and too often the people running those hosts get their security "knowledge" from blog posts by randoms on the Internet … things like "We block SSH key exchange, as it is a security risk, use FTP instead" is all to common a response from these types of providers.

**Comment by ali32b** [comment]
Just change your php version to 7. I did and my website is working now.
