### ISSUE TITLE
[BUG] Undefined index: slug

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#5364]
Hi,

the error:
> "PHP message: PHP Notice:  Undefined index: slug in /var/www/vhosts/bolt/vendor/bolt/bolt/src/Legacy/Storage.php on line 414" while reading response header from upstream, client: 192.168.33.1, server: cms.dev, request: "POST /foo HTTP/1.1", 

Code: [View with Github](https://github.com/bolt/bolt/blob/release/3.0/src/Legacy/Storage.php#L413)
```php
$fieldvalues['slug']
```

Details
-------

 - Relevant Bolt Version: 3.0.2

Reproduction
------------

1. Create contenttype
2. Save data with `bolt/boltforms` to the contenttype
3. See undefined index

Hope you can reproduce it. I don't know if a slug is needed here or if we can skip slug creation.

**Comment by SahAssar** [comment]
I'm not really sure if this is a boltforms issue or a bolt issue... @GawainLynch?

**Comment by GawainLynch** [comment]
It was BoltForms and this warning won't appear in BoltForms 3.1 when released soon as it uses the new storage layer.

**Comment by sbani** [comment]
thanks @SahAssar and @GawainLynch
