### ISSUE TITLE
[RFC] Add an ability to delete a record to mobile version of backend

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5371]
For me it's still not obvious - how to delete a record from narrow screen device. 
![2016-05-26 13-07-02](https://cloud.githubusercontent.com/assets/2145313/15566466/ff786048-2342-11e6-99cd-5a2408688338.png)
Also no buttons inside a record.
Am i missing something? Or it's a strategy?

**Comment by SahAssar** [comment]
Seems to me like it's good to declutter the interface on mobile... One can still delete record by going into the record and clicking the button there.

**Comment by Boorj** [comment]
I doubt that, i haven't found any way to delete a record from mobile screen.

![2016-06-02 08-26-42](https://cloud.githubusercontent.com/assets/2145313/15732070/cbc5f676-289b-11e6-9cd6-43e132977e14.png)

Try yourself, goto devtools/firbug and switch mobile mode on.

**Comment by SahAssar** [comment]
I still have the delete button (see the image below)... Is there anything non-standard about the contenttype or your backend?

![image](https://cloud.githubusercontent.com/assets/5096632/15758724/36af4454-290c-11e6-9548-213d33af9a83.png)
