### ISSUE TITLE
[RFC] [Twig] Official way to check for extension existence 

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5372]
In Bolt 2 we were able to do the following check in the theme to add features only if an extension is installed:

```
{% if UserProfiles is defined %}
    ...
{% endif %}
```

That doesn't work anymore in Bolt 3 and we have to do the following little "hack":

```
{% app.extensions.get('ohlandt/user-profiles') %}
    ...
{% endif %}
```

That doesn't feel right and isn't very clean.

I would suggest something like a `hasExtension('ohlandt/user-profiles')` twig function which returns `true` or `false`. 

In that context, it would be also nice to have an `extension('ohlandt/user-profiles')` twig function to get the actual extension object.
## Details
- Relevant Bolt Version: 3.x

**Comment by GawainLynch** [comment]
The way it was able to be done in v2 was itself a massive hack :laughing: 

But yeah, I think that should be easy to implement as you suggest.

**Comment by PhillippOhlandt** [comment]
I changed the code above to use the exact package name.

**Comment by GawainLynch** [comment]
You would need to use the name that is returned by `getName()` as not all extensions use Composer names

**Comment by bobdenotter** [comment]
See also: https://github.com/bolt/docs/pull/606

Pinging @CarsonF You said this would be trivial to make, right?

**Comment by CarsonF** [comment]
Are we wanting to call a function that may not be defined?

Or check if a extension exists? Those are similar but two different things. I could implement both.

For the extension exists check we need a test name. 
```twig
{% if "my/extension" is ... %}
``` 
And we can't use `defined` as it's already taken

**Comment by CarsonF** [comment]
Well we want it to be unique. I've had coffee now, and my brain is working better. How about `extension`?

```twig
{% if "my/extension" is extension %}
```

I guess the only thing about that is what extension, bolt or twig?

Maybe:
```twig
{% if "my/extension" is bolt_extension %}
```

**Comment by bobdenotter** [comment]
> I guess the only thing about that is what extension, bolt or twig?

I'm assuming here, but I think the bulk of the front end developers won't care.. They just want this to to work: 

```
{% if "bolt/facebookcomments" is extension %}
  {{ facebookcomments() }}
{% endif %}
```

Would your solution work like that, BTW? i'd think we'd bump into the exact same issue as earlier: The above example would break, if the extension isn't present.

**Comment by CarsonF** [comment]
Yes it would, which is why I was asking if we even needed the test

**Comment by bobdenotter** [comment]
In that case, no. We can do without the test.

**Comment by bobdenotter** [comment]
@CarsonF `*bump*` ;-)

Any progress on this?

**Comment by SahAssar** [comment]
Fixed in https://github.com/bolt/docs/pull/606, closing
