### ISSUE TITLE
[BUG] substr() expects parameter 1 to be string, array given in

### ISSUE THREAD

**Issue by alex996** [bolt/bolt#5378]
Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Zip install
 - PHP version: 5.5
 - Used webserver: Apache
 - For UX/UI issues: Chrome

The error occurs in the sitemap.xml file (using Sitemap extension):

`
<image:image>
    <image:loc>
        http://myurl.com
        <br/>
        <b>Warning</b>
        **: substr() expects parameter 1 to be string, array given in**
        <b>
            /my_ftp_path/vendor/bolt/bolt/src/Helpers/Image/**Thumbnail.php**
        </b>
        on line
        <b>**215**</b>
        <br/>
        /thumbs/1000x750c/2016-05/sample_img_1.jpg
    </image:loc>
......
`

Somehow, instead of a string, the sitemap template receives an array. Line 215 is in Thumbnail.php, in setScale($scale) function -- $scale becomes an array, rathar than str. The thumbnail image itself (at myurl.com/thumbs/1000x750c/2016-05/sample_img_1.jpg) displays perfectly well, and the page reports no errors. I tried default server images instead, same issue. Any suggestions?

**Comment by bobdenotter** [comment]
Confirmed! Looking into it.

**Comment by bobdenotter** [comment]
Fixed by #5382.
