### ISSUE TITLE
[BUG] Custom table schema won't be called when new twig globals are registered

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5380]
When you install my `ohlandt/user-profiles` extension and `bodenotter/seo`, then you don't get a database update notification for adding the new user table fields. The reason is that my User Schema class is never be called when the Seo extension is installed.

When you look at the `SeoExtension` class at line `83`, you will see the following function:

```
public function registerServices(Application $app)
{
    $seo = new SEO($this->getContainer(), $this->getConfig(), $this->version);
    $app['twig']->addGlobal('seo', $seo);
    $app['twig']->addGlobal('seoconfig', $this->getConfig());
}
```

When you remove the two `addGlobal()` function calls, my User Schema class will be called and everything works. @bobdenotter confirmed that this must be a Bolt issue.

Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: composer
 - PHP version: 7
 - Used webserver: php-dev

**Comment by GawainLynch** [comment]
This is an extension bug.

The `registerServices` function is for *registering* services, not using them as using them invokes them before the request cycle.

If you need to make a function/property call to service you can use `$app->extend()` to push that to when the container is finally built.

i.e. it should be more like:

```php
public function registerServices(Application $app)
{
    $app['twig'] = $app->extend(
        'twig',
        function ($twig) ($app) {
                $seo = new SEO($this->getContainer(), $this->getConfig(), $this->version);
                $twig->addGlobal('seo', $seo);
                $twig->addGlobal('seoconfig', $this->getConfig());

                return $twig;
        }
    );
}
```

**Comment by bobdenotter** [comment]
I know nothing! 🙄
