### ISSUE TITLE
[RFC] Image Alignment Options In CKEditor

### ISSUE THREAD

**Issue by brysont** [bolt/bolt#5383]
The current options are _none_, _left_, and _right_. Begs the question, why not _center_ as well?

Publishers use a wide variety of images and other multimedia in content and this extra point of control is crucial to properly displaying an entry and providing a solid user experience. Publishers also often have writers who do not understand even the basics of HTML and CSS, so relying on writers to correctly add a centering class to the image isn't reliable.

It's a hard limit on what can be done with Bolt, saying what can't be done instead of what can be done.

In the mindset of covering the most common uses, one (not me) could argue that even something as fickle as parallax should be included in the editor (whether I think that's right or wrong) so omitting only one of the 4 basic image alignment properties seems rather like an "oops" than strategy.

As I've been told on similar issues, I can make a CKEditor plugin for it, which of course is true. And to that I say, hacking core to achieve a basic precept of a content concept already built into core is a practice that will push away publishers in favor of developers, and publishers outnumber developers...

As seen on the Bolt.cm homepage - http://prntscr.com/b9kcrx - editors (aka publishers) are a priority. So why not take a small step to include the largest group of potential users available?

_*\* I apologize now if this sounds preachy. I am a publisher and have already received resistance on ideas about what publishers need from Bolt. So I'm attempting to make a plea for some rational thought on the matter. Whether this feature is the right one for it or not, I don't know._
## Details
- Relevant Bolt Version: [ 3.0.3 - ALL ]
- Install type: [ Composer install ]
- PHP version: [ 7.0 ]
- For UX/UI issues: [ ALL ]

**Comment by SahAssar** [comment]
While I agree on on the functionality here I think that if we want to make the editor properly usable for a editor/publisher we have a long way to go. Bolt (currently, and hopefully in the future) works best with structured content that fits into one of the contenttypes that has been set by the front/backend dev. Making the WYSIWYG editor fully featured just shows that we need to improve, it's not a solution.

**Comment by brysont** [comment]
Sorry, totally confused by your comment. You agree but think nothing should be done (not a solution because it's such a long way to go)? I must be reading that wrong...

I am talking about the `entries` contenttype. I've renamed mine to posts for continuity with what my writers are familiar with, but it's just the default contenttype setup in Bolt.

The way images are worked into content on Bolt is very static. I can only really control an image if it's added as a field in the contenttype. If it's included within an HTML or markdown field, it can only be controlled (beyond just size, link) by having non-technical people do technical things. This works great sometimes, but in a daily news website that is very much dynamic, the images used are often inside the HTML field and cannot be manipulated in the template (where I could solve the problem) beyond just styling all images at once.

In my particular case, it's easier to show you... https://insidethestar.com/kyle-wilber-front-runner-olb/

That's a great example of the kind of content we push out 3-5 times a day all year. The images are inside the context of the content and don't work as an image field in the contenttype. This is common publishing functionality that Bolt does not accommodate.

Furthermore, I've looked deeply into adding plugins for CKEditor and while that does work, I have to alter Bolt's core manually to do it (maybe I'm missing it, but can't find anything suggesting an extension can replace or alter the CKE plugins included in core). That means overwrites with every Bolt update.

Extra steps were taken within Bolt to add oEmbed functionality and this issue I bring up is the same thing, just for images. If I want to add a custom lightbox ext to the site, I have to alter Bolt's core (by adding a plugin and modifying the CKE config.js to load it). Page-level scripting can modify the DOM but this is a process that quickly slows a page down.

**Comment by SahAssar** [comment]
@brysont haha, sorry, I should have read through that before posting. +1 for this.

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
