### ISSUE TITLE
new features: foundation for rest

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#5384]
For a while Bolt is my favorite content manager , though at times I have been forced to hack it to suit my needs.
In my work I am struggling to convince my bosses retire the old drupal 7 in favor of Bolt, but because of its shortcomings still I have not been able to convince .

Two things you should consider : 
 - Supporting authentication without cookies and possibly Stateless
 (Json Web Tokens for example)
 - Check permissions on the front.
 This would allow developers to create an extension REST API. and make bolt is presentente in mobile applications.

I think it is not feasible to get these features directly from extensions.
I hope you consider my request , and I'll be happy to contribute ideas, code , and everything in my power .

**Comment by PhillippOhlandt** [comment]
Hey,

what are your problems with creating a REST api extension that checks authentication in the frontend?
The auth system in Bolt is very flexible and you can add as many custom permissions and roles as you want.

**Comment by PhillippOhlandt** [comment]
You can also use `bolt/members` and build on top of that. Then you have your app users separated from the backend users which is always a good idea.

**Comment by serweb-labs** [comment]
Thank you for responding.  I hope to explain well . 
 - Mainly is a limitation of the rest architecture, one should be able to get a token and send that token on each request in a custom header , ie , the server does not save the user's status . Then get the cookies and send them in the head is not very acceptable .

 -  I have also understood that it is not possible to limit the content posted by the permit system . That is, the permit system does not check the frontend

Right now I 'm for publishing a Rest Api Bolt extension , with all the limitations . :+1:

**Comment by PhillippOhlandt** [comment]
There is already a JSON API extension. It would be nice if you can contribute to it:
https://extensions.bolt.cm/view/5f66c2bf-0eb1-11e5-9120-621e70d6e3eb 

It's not for Bolt 3 yet but I was told that @xiaohutai will update it soon. You can also talk to him about new features like Token Auth and other stuff.

**Comment by serweb-labs** [comment]
Thank you for your view.
I have managed to overcome some limitations , and implement JWT, I am sending my extension at this time. closed for now.
