### ISSUE TITLE
[RFC] Include CKEditor's Accessibility Checker plug-in

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5388]
The CKEditor Accessibility Checker, formerly a proprietary plugin, has been released under the GPL.

 - https://cksource.com/accessibility-checker/
 - https://cksource.com/blog/Accessibility-Checker-Goes-OS

We should include this in Bolt, as it will help editors use sane markup, instead of "one line of bold text as headings".

**Comment by rarila** [comment]
Don’t think so:

>* GPL license only (you can use Accessibility Checker in your software only when it is also on a GPL license)

**Comment by GawainLynch** [comment]
Yup… GPL is viral. No can do.

**Comment by bobdenotter** [comment]
I'm not sure this is a problem. I've asked them, let's hope we can use it, because it'd be really neat.

**Comment by bobdenotter** [comment]
Meh! https://twitter.com/ckeditor/status/737225224274481152

**Comment by rarila** [comment]
:red_circle: I’m sorry Dave, I’m afraid I can't do that

**Comment by bobdenotter** [comment]
Stupid CKEditor people. 👎
