### ISSUE TITLE
[BUG] viewless setting in contenttype also affects backend omnisearch

### ISSUE THREAD

**Issue by annejan** [bolt/bolt#5392]
According to related issue #2149 setting `viewless: true` should cause:
- the contenttype is not associated with any template
- the contenttype does not produce any frontend routes
- there is no 'Preview' button in the backend for this contenttype
- the contenttype does not appear in any search results or listings on the frontend

Unfortunately in practice this also means that the content of that type is hidden from the (backend) omnisearch.
## Details
- Relevant Bolt Version: 2.2
- Install type: Composer install
- PHP version: 5.6
- Used webserver: Apache
## Reproduction

Setting `viewless: true` on a contenttype hides it from backend omnisearch.
This is unwanted behaviour in my opinion.

I have currently patched this on my instance with the following crude patch.

```
--- vendor/bolt/bolt/src/Storage.php    2016-05-31 17:35:44.000000000 +0200
+++ vendor/bolt/bolt/src/Storage.php    2016-06-01 11:21:28.000000000 +0200
@@ -783,9 +783,7 @@
             $contenttypes = array_filter(
                 $contenttypes,
                 function ($ct) use ($appCt) {
-                    if ((isset($appCt[$ct]['searchable']) && $appCt[$ct]['searchable'] === false) ||
-                        (isset($appCt[$ct]['viewless']) && $appCt[$ct]['viewless'] === true)
-                    ) {
+                    if (isset($appCt[$ct]['searchable']) && $appCt[$ct]['searchable'] === false) {
                         return false;
                     }

```

**Comment by SahAssar** [comment]
@annejan You want to PR that patch? :smile:

**Comment by SahAssar** [comment]
Closing this, see #5531 for more info.
