### ISSUE TITLE
[BUG] php app/nut doesn't work on Windows

### ISSUE THREAD

**Issue by ThomasBerends** [bolt/bolt#5394]
On Windows running the php app/nut command, as described in the documentation, does not work. It returns '../vendor/bin/nut'.

As discussed on IRC. The issue lies when symlinks on Windows get moved. On my computer, they seem to lose their destination, or the php command line tool doesn't seem to understand it.

**For users having this issue:**
You can use the following command instead. Just replace `php app/nut` with `php vendor/bolt/bolt/app/nut` .
Also, if you encounter this issue, please let us know by commenting on this issue.

Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Zip/tarball install
 - PHP version: 5.6
 - Used webserver: PHP internal webserver

Reproduction
------------

1. Install Bolt with a tarball install
2. Run 'php app/nut cache:clear'

**Comment by GawainLynch** [comment]
Note for readers: This is **not** a Bolt specific issue.

Nut is just a symlink, so if anything during install/upload resolves that symlink as a real file, internal paths will be wrong and you just need to re-symlink to `vendor/bolt/bolt/app/nut`

**Comment by SahAssar** [comment]
@GawainLynch Well, if it isn't a Bolt specific issue, can we do anything about it? Is this just windows being windows or can we open an issue somewhere?

**Comment by GawainLynch** [comment]
Yeah, the action item here is a docs update, either on Windows quirks generally, or the install page as a warning

**Comment by bobdenotter** [comment]
We fixed this recently, right? In the `.zip` file we include the symlink differently, so this oughta be fixed. Feel free to reopen if still an issue.

**Comment by humaxi** [comment]
Uhmm, is this windows being windows? no? It's Nut being nuts. If it doesn't work don't use it in your demn cms..
