### ISSUE TITLE
[RFC] Make bolt's public folder installable in the site root

### ISSUE THREAD

**Issue by sebastiaanfranken** [bolt/bolt#5396]
I was wondering if it's possible/plausible to have the default files and folders in the public/ folder in the site root folder, like so:
```
- app
- ...
- extensions
- README.md
- vendor
- bolt-public
- files
- index.php
- theme 
- thumbs
```

The reason I'm asking is because the webhosting company I'm using (TransIP) doesn't support placing core files outside the 'public' folder, you only have read/write permissions in /public and /private (you get a few folders, with a public and private folder, your site goes in public), and also they won't change this setting because it's their security policy.

However: TransIP works for me, I'm not going to switch hosting companies nor am I going to switch away from Bolt to something else, since Bolt does exactly what I need and want it to do and also works like a charm. I really want tot upgrade to 3.x, but with it's rather rigid requirements it's simply not possible.

I've snooped around the code a little bit, and I think the biggest issue is paths. For example in `public/index.php` the following code is used:

```php
 <?php
  
   /*
    * `dirname(__FILE__)` is intentional to support PHP 5.2 until legacy.php ca    n be shown.
    */
   /** @var Silex\Application|false $app */
   $app = require dirname(__FILE__) . '/../vendor/bolt/bolt/app/web.php';
```

Thus making a 'publicless-folder' install impossible. Maybe something like the following: (messy, fast written code, excuse my code):

```php
<?php

/*
 * `dirname(__FILE__)` is intentional to support PHP 5.2 until legacy.php can be shown
 */
 
$rootFolder = (end(explode('/', $_SERVER['DOCUMENT_ROOT'])) == 'public') ? '/../' : '/';

/**
 * @var Silex\Application|false $app
 */
$app = require dirname(__FILE__) . $rootFolder . '/vendor/bolt/bolt/app/web.php';
```

Sorry for the lengthy post. Any comments would be greatly appreciated. Again, I'd hate to have to go looking for a new CMS.

**Comment by GawainLynch** [comment]
Already is: https://docs.bolt.cm/3.0/installation/install-git-clone

**Comment by sebastiaanfranken** [comment]
Sorry, I should have been a little more expressive. This isn't really a solution, since your site becomes browsable on it's URL (let's say example.nl) and on example.nl/public as well, which isn't great for users (or SEO). Or am I missing something obvious?

**Comment by GawainLynch** [comment]
The git install method doesn't have a `public` directory, so this isn't a problem for SEO. 

However, you are however not making things easy for yourself in the security realm. Also see: https://docs.bolt.cm/3.0/howto/troubleshooting-outside-webroot

**Comment by sebastiaanfranken** [comment]
Ah, I didn't know the git clone provided you with a slightly different version (which seems to do what I want / need it to do).

And I know about the security implications, it's just that you **cannot** install Bolt the default way with TransIP, since your user can't write to anything but the "public" folder, so the core files for Bolt **cannot** be uploaded, no matter how hard you try. Ergo my question / RFC.

Anyway, my issue has been resolved, though I still think you should give this RFC some thought for later versions.

**Comment by bobdenotter** [comment]
@sebastiaanfranken I've added an extra bit to the docs: https://github.com/bolt/docs/issues/420
