### ISSUE TITLE
Mounting Bolt with stackphp: links not working

### ISSUE THREAD

**Issue by fadoe** [bolt/bolt#5397]
I installed Bolt 3.0 with composer and make it run. Now I installed stackphp and stack\url-map how described at https://docs.bolt.cm/3.0/installation/advanced#mounting-bolt-on-an-existing-application. I can sho the start page, but the links are not created with the new base path (in documentation /blog). Must I configure something or is it a issue? I have a project where I will mount Bolt with stackphp. The other application running with Silex too is working and creates routes correct.

**Comment by fadoe** [comment]
Any updates for this? Is there a problem in bolt or is there anything missing in my config? I need this information for a project.

**Comment by fadoe** [comment]
There are also wrong links in Backend for and under Settings/Configuration and Settings/Extends. The other links are correct.

**Comment by GawainLynch** [comment]
Unsure on this one. Might be worth trying Slack as a few people there might have tried something similar.

**Comment by fadoe** [comment]
I found the problem in the backend: All brocken links are generated via:
`$path = $this->rootEntry->getUri() . '/dbcheck';`
The correct way should be:
`$path = $app['url_generator']->generate('dbcheck');`

**Comment by GawainLynch** [comment]
Oh wow … that's awesome, thank you!

**Comment by GawainLynch** [comment]
PR #5577 submitted … thank you again :smile:

**Comment by fadoe** [comment]
Your'e welcome.

The frontend problem is a little bit harder: When I am right the URL are created at MenuBuilder on line 163:
`$item['link'] = $this->app['resources']->getUrl('root') . $path;`
How we can use the url_generator on this place?

**Comment by SahAssar** [comment]
@fadoe It should use the link property from the records if they are correctly entered: https://github.com/bolt/bolt/blob/858d652e49c3b61fef7e0f66f47750a4fe97d766/src/Menu/MenuBuilder.php#L193-L219

**Comment by fadoe** [comment]
Hej @SahAssar. On this place $content has already the incorrect link. This link is generated before this method is called.

**Comment by GawainLynch** [comment]
Yeah, front-end has a legacy cut-over problem … it could be hard(er) to solve.

We do some magic currently to build that link that needs to :fire: … and it is caught in between the two storage layers

**Comment by fadoe** [comment]
I will look at this later. When I solve this problem I will tell you. 

This must be fixed when i use bolt for this project ... tz tz tz.

**Comment by fadoe** [comment]
@GawainLynch Okay, I think I fixed the frontend:

`$appBolt['resources']->setUrl('root', '/my-bolt-project/');`

**Comment by GawainLynch** [comment]
> Okay, I think I fixed the frontend:

How/where are you applying this?

**Comment by fadoe** [comment]
I wrote this in my index.php. It's not the best way but it works at the moment.

**Comment by GawainLynch** [comment]
Reopening until we have a handle / decision on front-end impact.

**Comment by fadoe** [comment]
Can you describe this problem? Eventually I can help to fix it.

**Comment by CarsonF** [comment]
@fadoe Can you verify that you don't need the `setUrl` hack with v3.3 beta?

**Comment by GawainLynch** [comment]
Closing due to lack of verification & tests case. Please feel very welcome to reopen with said requirements
