### ISSUE TITLE
[BUG] Html snippets are not loaded because of an unexpected cache-control setting

### ISSUE THREAD

**Issue by flrvt** [bolt/bolt#5398]
As discussed in Slack, I spent the past few days debugging a problem with my bolt install where the assets of all extensions would not load. The htmlsnippets were just not included in the html. 

Assets are not loaded because of this line in Application.php which was last edited for release 2.2.20 (see PR  https://github.com/bolt/bolt/pull/5121 by @SahAssar)

```
if (isset($this['htmlsnippets']) && ($this['htmlsnippets'] === true) && ($response->headers->get('Cache-Control') === "no-cache")) {
```

I deployed the site locally, I deployed it to another server, and the behaviour is not present. I only see this behaviour on one of our servers. I have confirmed the server is the only variable, and changing the line of code below to what it was in 2.2.19-pl1 actually 'fixes' it.

I will describe the specifics of this server below.

Details
-------

 - Relevant Bolt Version: 2.2.21
 - Install type: Composer install
 - PHP version: 7.0.6
 - Used webserver: Apache version 2.4.6 (CentOS)

Environment information
----------------------
Please rename these txt files to html to view the detailed phpinfo() output in your browser
[phpinfo_not_working.txt](https://github.com/bolt/bolt/files/294360/phpinfo_not_working.txt)
[phpinfo_working.txt](https://github.com/bolt/bolt/files/294361/phpinfo_working.txt)

Reproduction
------------

 1. Do a clean install of bolt 2.2.21 on a similar environment
 2. Install any extension that uses html snippets to load assets
 3. Watch as the html snippets are not loaded into the html.

I tested this with the bolt/labels extension.

**Comment by SahAssar** [comment]
@flrvt Did you ever find out what was the issue with the server? Cause I've tried to reproduce and can't get it to fail...

**Comment by SahAssar** [comment]
@flrvt Closing cause it seems like it's a server issue (and no reply to above), but if you find out what it was please reopen/comment.
