### ISSUE TITLE
Using 'sortorder' with 'limit' gives weird results. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5418]
For example: 

```
  {% setcontent dashboard = 'blocks' where { groups: 'dashboard' } limit 10 %}
  {% for item in dashboard %} {{ item.sortorder }} {% endfor %}
```

Result: 

```
5 10 15 20 25 30 35 40
```

And this: 

```
{% setcontent dashboard = 'blocks' where { groups: 'dashboard' } limit 4 %}
{% for item in dashboard %} {{ item.sortorder }} {% endfor %}

15 20 25 30
```

It seems it's sliced wrongly somewhere, before the results are sorted.

**Comment by bobdenotter** [comment]
I _think_ this might have been an issue in Bolt 2 as well. Content is retrieved, then sliced for `limit`, and only _then_ hydrated for the taxonomies (and thus the `sortorder`).

**Comment by SahAssar** [comment]
@bobdenotter Still a bug? Closing for now (let's call it "due to inactivity"), but if it still is I'm assuming you'll reopen ;)
