### ISSUE TITLE
[BUG][NOT SURE]Bolt V3 Storage -> addHandler NOT calling addOperation

### ISSUE THREAD

**Issue by Raistlfiren** [bolt/bolt#5419]
When adding handlers to the new Bolt Storage level, it isn't calling addOperation() as well. I am not sure if this is intended or not.

Details
-------

 - Relevant Bolt Version: 3.0 | master
 - Install type: [ Github checkout | Zip/tarball install | Composer install ]
 - PHP version: [ 5.4 | 5.5 | 5.6 | 7.0 ]
 - Used webserver: [ PHP ]

Reproduction
------------
In a service provider I add a new handler:  

`$app['query.parser']->addHandler('pager', new PagingHandler());`
The new handler is not recognized when being calling `$query->getContent('pages/pager');`.

In order to get it working, it must be added to the operations list as so - 
`$app['query.parser']->addOperation('pager');`

Then it is recognized as an operation and executes it correctly. 

Proposed Solution
------------
```php
    /**
     * Adds a handler for the named operation.
     *
     * @param string   $operation
     * @param callable $callback
     */
    public function addHandler($operation, callable $callback)
    {
        $this->handlers[$operation] = $callback;
        $this->addOperation($operation);
    }
```

P.S.
-------
Should addOperation() throw an Exception instead of silently not adding the operation to the list? It would be easier to debug if it did IMHO.

**Comment by SahAssar** [comment]
Fixed in #5423, no?
