### ISSUE TITLE
Bug // content of repeater fields lost

### ISSUE THREAD

**Issue by steiha** [bolt/bolt#5426]
Content of repeater fields lost when adding field to content type definition.
Or just not populated to admin edit form.

Details
-------

 - Relevant Bolt Version: 3.0.5
 - Install type: Composer install
 - PHP version: 5.5
 - Used webserver: Apache
 - Storage: MySQL

Reproduction
------------
- have a content type with repeater section (eg. title (text) and body(html))
- have a template to render repeater content in front end
- enter some data

- have a look in the front end, everything fine so far

- add a new field to the content type, does not have to be inside the repeater section

- have a look in the front end, everything fine so far
- have a look in the database, yes the repeater field contents are still there
- but if you look in the admin you see that the repeater field contents are missing in the edit view (existing content not populated in the edit form)

- so next time you store the record the existing repeater field contents will be lost

**Comment by steiha** [comment]
I looked into this again.
Seems to be a problem only when using underscores in the field name.

`app/config/contenttypes.yml`
nok
>         service_list:
            type: repeater
            limit: 3
            fields:
                service_title:
                    type: text
                content:
                    type: html

ok

>         services:
            type: repeater
            limit: 3
            fields:
                service_title:
                    type: text
                content:
                    type: html

**Comment by rossriley** [comment]
Fixed by #5436
