### ISSUE TITLE
[BUG] repeater field // HTML editor // does not store

### ISSUE THREAD

**Issue by steiha** [bolt/bolt#5428]
Details
-------

 - Relevant Bolt Version: [ 2.2 | 3.0 | master ]
 - Install type: Composer install
 - PHP version: 5.5
 - Used webserver: Apache
 - For UX/UI issues: Chrome/ Safari (OS X 10.11.5)

Reproduction
------------

- vanilla install via composer

`composer create-project bolt/composer-install:^3.0 bolt --prefer-dist`

- add a new content type

>         example:
            name: Examples
            singular_name: Example
            fields:
                list:
                    type: repeater
                    limit: 10
                    fields:
                        list_title:
                            type: text
                        list_content:
                            type: html

- create a new example
- add some content
- save record
- leave edit view, click somewhere else
- open this record again
- html editor shows up twice
- try to change the contents (e.g. add a running number 1..9)
- save
- the text type fields are stored as expected
- the html type fields only the last one is stored

Guess this is tightly related to #5427

**Comment by rossriley** [comment]
Fixed also by #5436
