### ISSUE TITLE
[BUG] Using Taxonomy type of Tag with 'allow spaces' option cause JS error (bolt 3.0)

### ISSUE THREAD

**Issue by denis-gorin** [bolt/bolt#5430]
Editing record, Clicking on a link in TagCloud there is a JS error:

`Uncaught Error: Syntax error, unrecognized expression: option[value=A Few Words Tag]`

workaround:

find in /public/bolt-public/view/js/bolt.js: 

`d.find("button").on("click",function(){var b=a(this).text(),d=c.find("option[value="+b+"]");`

and replace:

`d.find("button").on("click",function(){var b=a(this).text(),d=c.find("option[value='"+b+"']");`

**Comment by bobdenotter** [comment]
Confirmed, and your fix looks good. I'll commit the fix. 

Thank you! 👍
