### ISSUE TITLE
[BUG] [L10N] contenttypes.generic.none-available wrongly translated in vendor/bolt/bolt/app/resources/translations/fr/messages.fr.yml

### ISSUE THREAD

**Issue by padawan** [bolt/bolt#5432]
Details
-------

 - Relevant Bolt Version: [ 3.0.x ] (tested on 3.0.4)
 - Install type: Zip/tarball install

The following code (used in both in vendor/bolt/bolt/app/view/twig/_sub/_record_list.twig and vendor/bolt/bolt/app/view/twig/recordbrowser/_content.twig):

`                {{ __('contenttypes.generic.none-available', {'%contenttypes%': contenttype.slug}) }}
`
is wrongly translated in vendor/bolt/bolt/app/resources/translations/fr/messages.fr.yml by this:

`contenttypes.generic.none-available: "Aucun(e) %contenttype% disponible"
`

Note the plural `%contenttypes%` used in the code and the singular `%contenttype%` in the L10N file for FR (other languages do not have this bug).

Reproduction
------------

Display any content type that is empty, on a Bolt install localized in French. The following will be displayed:

> Aucun(e) %contenttype% disponible

Fix
---

Change line 143 of vendor/bolt/bolt/app/resources/translations/fr/messages.fr.yml to:

`contenttypes.generic.none-available: "Aucun(e) %contenttypes% disponible"
`

**Comment by GawainLynch** [comment]
Fixed in #5433
