### ISSUE TITLE
BUG Select all button visible when taxanomy multiple set to false for category behaviour

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#5437]
When editing Taxanomy where behaviour is set as category with multiple set to false, the select all/ select none buttons are visible.

Details
-------

 - Bolt Version 3.0.4
 - tarball install
 - PHP version: [5.5.29 ]
 - Used webserver: [ Nut server run]
 - For UX/UI issues: [ Chrome Version 50.0.2661.102 (64-bit) ]

![screen shot 2016-06-10 at 12 45 03](https://cloud.githubusercontent.com/assets/5342693/15963352/371d6fb2-2f09-11e6-9dd6-94ee2a1b0a5d.png)

**Comment by bobdenotter** [comment]
@rarila if you're going to look into this, can you also make sure the `[x]` and `[v]` buttons are on the same line? ;-)

**Comment by rarila** [comment]
yes and no (with having both you have multiline on the left anyway so less space is wasted)
