### ISSUE TITLE
installing from composer, change the "themes" folder not working

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#5439]
When installing Bolt, from composer, the default template can not load the assets.  {{ paths.theme }} still return "theme".
## Details
- Relevant Bolt Version: 3.0 .5
- Install type: Composer install
- PHP version: 5.6
- Used webserver: php built-in server version
## Reproduction

 1 - Install Bolt `composer create-project bolt/composer-install:^3.0 <MYPROJECT> --prefer-dist`
 2 - when asked what name you want to put templates folder put "views"
 3 - get to homepage

**Comment by GawainLynch** [comment]
Closing based on 9 months without verification … and so much has changed in that time.

Please feel most welcome to re-open with more information & a test-case
