### ISSUE TITLE
Comments System (again, sorry)

### ISSUE THREAD

**Issue by mr-klaatu** [bolt/bolt#5440]
RFC:  I know it has been talked about many times before but the only thing I feel is missing with the latest version of Bolt is a solid Commenting System.

There was some rapid prototyping of a system using the BoltForms extension in issue #3472 but I tried it on Bolt 3 and could not get it to work.

Is anyone out there working on a Commenting Extension ? 

Does anyone have a working system they would care to share ?

I wish I could go it alone and write one, alas my skills are not up to the job.

**# Details**

Relevant Bolt Version: 3.0.5
Install type: Composer install
PHP version: 5.6
Used webserver: apache 2.4.18

**Comment by SahAssar** [comment]
Well, if you don't want to use disqus or facebook comments there are many systems like [isso](https://posativ.org/isso/) that can supplant bolt to give it a commenting system... Are those alternatives not enough?

**Comment by mr-klaatu** [comment]
I was looking for a self hosted (local) system that does not rely on a third party solution. I had not seen issue, and it looks good, but it will cause problem with many shared hosting packages and is not accessible as a inbuilt solution or proper native extension. That's my thoughts anyway :-)

**Comment by PhillippOhlandt** [comment]
I think an extension would do the trick. It's definitely possible as extension and IMO better as built into core.

**Comment by bobdenotter** [comment]
I'm against doing this in core. Having a good third-party extension to store them in the Bolt DB would be fine with me. 

In fact, shouldn't be too hard to build it on top of BoltForms, now that I think of it. 

Cleaning spam won't be fun, though. (Which is the main reason why i'm all for using an external tool.)

**Comment by SahAssar** [comment]
Since boltforms now can override certain fields/options from the twig function this is now very doable with just boltforms. Even if it wasn't I think that integrating a comment system in bolt core is a bad idea and it seems like other contributors agree, so I'm closing this one. Perhaps a forum discussion on how to build it with boltforms would be more appropriate?

**Comment by bobdenotter** [comment]
@PhillippOhlandt Would this be a good topic to cover in a Boltacade.my tutorial?

**Comment by PhillippOhlandt** [comment]
@bobdenotter sure. or somewhere earlier because boltacademy will need some more weeks before its online. too much other stuff going on recently.

**Comment by bobdenotter** [comment]
I'mma put this on my personal list of stuff to work on. :-)

**Comment by PhillippOhlandt** [comment]
Whatever you want :)
