### ISSUE TITLE
[BUG] Namespace not set in Filesystem Plugins

### ISSUE THREAD

**Issue by nikgo** [bolt/bolt#5449]
Namespace not set in Filesystem Plugins. This causes e.g. permissions in FileManager not work for different namespaces.

Details
-------

 - Relevant Bolt Version:  3.0.5 | master 
 - Install type:  Github checkout 
 - PHP version: 5.5 
 - Used webserver: Apache version 2.4.7 

Reproduction
------------

Use bolt master or release/3.0 branch:

 1. Go to Bolt File Manager `/bolt/files`
 2. Append a filesystem mount point to `/bolt/files` e.g `/bolt/files/cache` or `/bolt/files/app`
 3. You can view files from not allowed mount points via FileManager.

Only allowed prefixes (files,theme,config) in `\Bolt\Filesystem\FilePermissions` should authorized. 

Technical
-----------
This is caused because namespace not set in constructor of Filesystem Plugins which inherits from `\Bolt\Filesystem\Plugin\AdapterPlugin`. Default namespace is "files". So other namespaces are still authorized.

Solution
----------
PR is in work.

**Comment by GawainLynch** [comment]
Nice find… Awaiting the PR :+1:
