### ISSUE TITLE
[BUG] Bootstrap modal z-index not high enough on smaller screens

### ISSUE THREAD

**Issue by AlphaRecon19** [bolt/bolt#5454]
When a modal is shown in the backend on a smaller screen size (between a tablet and laptop) the side navigation overlaps with the modal content. Quick fix would be to increase the z-index for the modal but is this the correct way to do this?

```
.modal {
    ...
    z-index: 100002;
    ...
}
```

Reproduction
------------

 1. Login to the Bolt backend and navigate to extend
 2. Open up developer tools and set the screen width to 768px
 3. Click on the 'Browse Versions' button
 4. Wait for the modal to appear

<img width="810" alt="" src="https://cloud.githubusercontent.com/assets/3878240/16077880/56a1e9a6-32f3-11e6-9638-1f2a59ebc9a2.png">

**Comment by bobdenotter** [comment]
Yes, it's the "correct" way.. Over the past year we've had to 'bump' a few other z-indices as well. I'll get on it.

**Comment by AlphaRecon19** [comment]
![](https://media.giphy.com/media/11ISwbgCxEzMyY/giphy.gif)

**Comment by GawainLynch** [comment]
Haha… You fit in perfectly around here @AlphaRecon19 :+1:
