### ISSUE TITLE
Links are not supported

### ISSUE THREAD

**Issue by dfridrich** [bolt/bolt#5460]
I deploy Bolt app via Capistrano and I share menu.yml among releases. I want to edit menu.yml in Bolt admin, but menu.yml is not file but link to file. If I try to edit I get `Links are not supported, encountered link at /var/www/slahosting.com/www/releases/20160617132704/app/config/menu.yml` error.

It would be great if Bolt would support editing files which are linked.

**Comment by GawainLynch** [comment]
This is not actually possible. Bolt uses a visualised file system layer, so that we can have files on the likes of S3 or other CDN type services and symlinks are not valid on most FS types.

**Comment by SahAssar** [comment]
Since this is not actually possible I'm gonna close this... Feel free to reopen if I'm wrong!

**Comment by CarsonF** [comment]
I want to revisit this. https://github.com/thephpleague/flysystem/issues/599 describes something that we could implement ourselves with our adapter. It just needs to be transparent to the `Filesystem` which has no concept of symlinks. At the very least non-mutating functionality could be implemented.

**Comment by bobdenotter** [comment]
Should we put this on the list for 3.4? I think it'd be really nice to have.

**Comment by GawainLynch** [comment]
3.4 is going into beta next week, so the door is close for this there. Bumping to 3.5 if we make it, else closing in September :timer_clock:

**Comment by bobdenotter** [comment]
If it's up to me, this would get priority for 3.4

**Comment by GawainLynch** [comment]
Agreed, but Carson is on leave at the moment, and after looking at this over the last couple of weeks it will break lots of things badly if we're not careful … 

Not to mention it is a lot of work.

**Comment by GawainLynch** [comment]
Oh, and to add context. I looked at how a couple of other projects approached this for "inspiration", and the term (might be an Aussie thing) that comes racing to mind is _"Wouldn't touch that with a 10 foot pole"_

**Comment by SahAssar** [comment]
Partially solved in #6744, Closing for now... If anyone has active work please revert :)
