### ISSUE TITLE
[RFC] DateTime support in content

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5465]
Just ran into an issue when importing data, and I was setting the following

```
'datecreated' => $date->format('Y-m-d H-i-s'),
'datepublish' => $published ? $date->format('Y-m-d H-i-s') : null,
```

The dates were being created as `NOW` instead of the imported dates, it took me some time to reaslise
that I was using `-` instead of `:` in the time section.

Interally threre is a [regex](https://github.com/bolt/bolt/blob/release/3.0/src/Storage/Entity/ContentValuesTrait.php#L276) which caused this failure.

I don't know much about this (just starting with bolt), but would it not be possible to have some mapping of the fields, like in f.e. Doctrine ORM, to a date type where you could accept either a string or a \DateTime? and if there was a value and it wasn't a valid date string, throw an exception?

**Comment by GawainLynch** [comment]
Could you add some awesome to this and replace the boilerplate text with some details of the RFC? :smile:

**Comment by dantleech** [comment]
I accidentally submitted the form before filling the issue in, updated it afterwards :)

**Comment by GawainLynch** [comment]
@dantleech that listed regex & code path are in legacy, and the entity object take/use DataTime for said fields.

Does this address the request?

**Comment by dantleech** [comment]
Yeah sure, wasn't sure there was a divide when I wrote this ticket, closing.

**Comment by GawainLynch** [comment]
Zero stress, thanks :+1:
