### ISSUE TITLE
[BUG] Duplicate Set does not duplicate HTML field contents unless record is saved first.

### ISSUE THREAD

**Issue by saltpeanuts** [bolt/bolt#5476]
## Details
- Relevant Bolt Version: 3.07
- Install type: Zip 
- PHP version: 5.5.12
- Used webserver: Apache 2.4.9
- For UX/UI issues: Firefox 47 / Chrome 51
## Reproduction
- Have a repeater with a text and a html field
- Add content to both fields
- Hit the Duplicate Set button

**Expected result**
The set and its contents should be duplicated

**Actual result** 
The set is duplicated, the text field content is duplicated, the HTML field content is missing.

If the record is saved before hitting Duplicate Set it works as expected.

**Comment by bobdenotter** [comment]
This has been fixed, somewhere in the mean time.
