### ISSUE TITLE
[RFC] Update deprecation notices to point to new class or method...

### ISSUE THREAD

**Issue by Raistlfiren** [bolt/bolt#5477]
On several of the classes like [Config](https://github.com/bolt/bolt/blob/release/3.0/src/Config.php), [Library](https://github.com/bolt/bolt/blob/release/3.0/src/Library.php), [addJQuery](https://github.com/bolt/bolt/blob/186defe6e36d8072edb84bfc24ee8054353b0106/src/Extension/AssetTrait.php), and etc... they have @deprecated doc blocks, but they don't say what to use instead. It would be nice if either these doc blocks were updated to include the new class or method to use, or going forward the deprecation notices include that updated information. Symfony uses the doc block @link to point to a new class. An example - 

``` php
/*
* @deprecated Since 3.1, to be removed in 4.0. Cache the choice list in the {@link ChoiceLoaderInterface} instead.
*/
```

Thoughts?

Thanks for your time.
## Details
- Relevant Bolt Version: [ 3.0.\* ]

**Comment by GawainLynch** [comment]
I totally agree. PRs are most welcome :smile:

**Comment by SahAssar** [comment]
Is there someone working on this?

**Comment by Raistlfiren** [comment]
@SahAssar I am not. I do not know the code base well enough, otherwise I would. Can you handle it @SahAssar? :)

**Comment by SahAssar** [comment]
@Raistlfiren Don't think that I know it well enough either... 

We have a nice (probably non-exhaustive) list of what has been deprecated here: https://github.com/bolt/bolt/wiki/Deprecations-Tracker, but not something that actually maps them to a recommended alternative...

**Comment by GawainLynch** [comment]
Yeah, I'll take the blame there … the deprecation tracker should be pretty close on *what* went, but not to where.

This is not a bad job for someone who is curious, and happy to answer queries from said person.

**Comment by SahAssar** [comment]
No volunteers have stepped up and core seems to have enough on their plate. We will have to make due with what we got, and hopefully make better use of the community via the forum and other communication channels. Closing for now, feel free to reopen if someone has the time to work on it :)
