### ISSUE TITLE
[BUG] sub-folder rename with Umlaut-names does not work

### ISSUE THREAD

**Issue by rwchhs** [bolt/bolt#5478]
Details
-------

 - Relevant Bolt Version: 3.0.4 - 3.0.8
 - Install type: Zip/tarball install
 - PHP version: 7.0.6 FPM/FastCGI
 - Used webserver: Apache 2.4.7
 - For UX/UI issues: Chromium 50.0.2661.102; Firefox 47.0

Reproduction
------------

 1. **Bug summary**: It is not possible to rename sub-folders whose names contain Umlaute (German diacritical characters - ä ö ü ß)
 2. **Specifics**: In the admin backend, folders whose names contain one or multiple Umlauts cannot be renamed (either from or to the Umlaut-version), but they can be created. This only applies if attempted in a sub-folder of the files/ directory. I.e. it *does* work as expected directly below files/, but not on a deeper level.
 3. **Steps to reproduce**:
* create a folder of any name below files/ via the admin backend's file manager
* in this sub-folder, create another folder called "testü"
* attempt to rename this folder; this does not work
* instead of steps 2 & 3, you can also create a folder called "test" and attempt to rename it to "testü"; this does not work either
 4. **Expected result**: Folders should be able to be renamed to/from a name containing Umlauts *not* only if they're directly below files/
 5. **Actual result**: A javascript alert() message pops up with the following localized message:
"Ordner konnte nicht umbenannt werden: events\/test\u00fc" [Folder could not be renamed: events\/test\u00fc]. Additionally, a console.log() message gets written after the first message is closed,
with the text "Something went wrong renaming this folder!"
In this case, event/ is a folder directly below files/, and the folder testü/ was attempted to be renamed to test/

![bolt rename bug](https://cloud.githubusercontent.com/assets/15850815/16317156/221eff78-398a-11e6-95cb-08d4a43e283a.png)
(the long execution time visible in the debug bar is only due to a large number of directories and files)

**Comment by GawainLynch** [comment]
Any ideas @rarila or @CarsonF ?

**Comment by CarsonF** [comment]
Maybe a filesystem limitation? Maybe try in straight php code not admin UI?

**Comment by rwchhs** [comment]
>filesystem limitation

just ext4, nothing fancy.
```shell
root@server# df -T
Filesystem        Type     1K-blocks     Used Available Use% Mounted on
/dev/ploop15096p1 ext4     209333532 14040848 186766776   7% /
```

>straight php code

```php
mkdir("ütest");
rename("ütest", "uetest");
```
This works as intended. Anything in particular you want me to try?
