### ISSUE TITLE
[Config] Validation / Normalization

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5480]
Currently there is no (or at least weak) configuration validation.

For example, if I accidentally place the boolean `show_in_menu` under `fields` I get the following:

![bolt_error_schema](https://cloud.githubusercontent.com/assets/530801/16346510/9ec0e6d0-3a3f-11e6-855c-b743b9501bba.png)

And if I make a typo then it goes unnoticed. I would expect an exception like:

```
Configuration key "singular_names" at path "events" is not known. Valid keys: "singular_name", "name", "fields", "taxonomy", "relations" (and so on)
```

You could use the Symfony Config component for this, but you would then probably want to cache the processed configuration as serialized PHP (which would be a performance boost over YAML).

Otherwise just doing some assertions when building the config would be cool.

**Comment by GawainLynch** [comment]
A complete rewrite of Config is on the cards, and Symfony Config is a strong candidate, but BC is part of the issue there.

The config class is overloaded and fragile,so an in-place fix would only give with one hand,bwhile taking with the other.

**Comment by SahAssar** [comment]
This is in the books and in the works with @GawainLynch and @CarsonF working on it (IIRC), but since this issue isn't really about any of the specifics of that work or tracking it I think it'd be better to close it as to not overwhelm our already overwhelmed issue tracker. If anyone disagrees please feel free to reopen :)

**Comment by GawainLynch** [comment]
Yes, it is in-flow and well in play [here](https://github.com/bolt/bolt/compare/release/3.4...GawainLynch:feature/configuration-loader)
