### ISSUE TITLE
[RFC] Testing

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5487]
In this RFC I want to propose a clear distinction between Unit and Functional tests and advocate the use of Prophecy.
## Unit and Functional testing
- [Unit tests](https://en.wikipedia.org/wiki/Unit_testing): Tests where only the test unit is instantiated - all dependencies are mocked. In general they always extend `PHPUnit_Framework_TestCase` directly.
- Functional/integration tests: Tests which are executed "from the container/application", **no mocks** are used (definition of functional testing is subjective).

Currently (afaict) bolt uses a Hybrid approach, it has the `BoltTestCase` which creates some mocks AND boots the container/application.

I propose that there be a clear separation such that the tests directory looks like:

```
tests/
    /unit
    /functional
    /...
```

(we do this in the CMF, [here for example](https://github.com/symfony-cmf/routing-auto-bundle/tree/master/Tests))
## Prophecy

[Propehcy](https://github.com/phpspec/prophecy) is a (now native) alternative to PHPUnit's mocking system. The following is an example of a unit test:

``` php
class ResourceEnhancerTest extends \PHPUnit_Framework_TestCAse
{
    public function setUp()
    {
        $this->registry = $this->prophesize(RegistryInterface::class);
        $this->urlGenerator = $this->prophesize(UrlGeneratorInterface::class);
        $this->requestConfigurationFactory = $this->prophesize(RequestConfigurationFactory::class);
        $this->requestStack = $this->prophesize(RequestStack::class);
        $this->enhancer = new ResourceEnhancer(
            $this->registry->reveal(),
            $this->requestStack->reveal(),
            $this->requestConfigurationFactory->reveal(),
            $this->urlGenerator->reveal()
        );

        $this->cmfResource = $this->prophesize(CmfResource::class);
        $this->metadata = $this->prophesize(Metadata::class);
    }

    /**
     * It should return true if the payload is supported by Sylius.
     */
    public function testSupportedBySylius()
    {
        $this->cmfResource->getPayloadType()->willReturn('stdClass');
        $this->registry->getByClass('stdClass')->willReturn($this->metadata->reveal());
        $this->assertTrue(
            $this->enhancer->supports($this->cmfResource->reveal())
        );
    }
}
```

With prophecy you describe (or "prophesize") the behavior of objects.

I personally find it far easier to work with than the old PHPUnit mock framework.

**Comment by GawainLynch** [comment]
Thanks! Added to the [agenda for tonight's meeting](https://github.com/bolt/bolt/wiki/Dev-meeting-2016-06-28).

**Comment by GawainLynch** [comment]
> I propose that there be a clear separation such that the tests directory looks like

We've settled on a similar approach, just that unit/functional/acceptance tests are spilt out by provider, i.e. currently `tests/phpunit/unit/` with the intention that when we revamp the tests that we'd end up with:
 * `tests/phpunit/unit/`
 * `tests/phpunit/functional/`

**Comment by SahAssar** [comment]
Is this still going?

**Comment by dantleech** [comment]
Not at the moment

On 26 January 2017 23:10:40 GMT+00:00, <notifications@github.com> wrote:
>Is this still going?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bolt/bolt/issues/5487#issuecomment-275543306

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SahAssar** [comment]
Alright, then I'm closing for now :)
