### ISSUE TITLE
[BUG] demo site provisioning fails on https://try.bolt.cm/

### ISSUE THREAD

**Issue by benhtn** [bolt/bolt#5488]
There are no items in the Theme select#demo_theme. 
After submitting the form, it appears to get to completion with a message of "Your Bolt Site is Ready!"
However accessing the URL provided gives the following error:

> Bolt - Fatal error.
> Class: Twig_Error_Loader
> Message: Template "index.twig" is not defined.
> Code: 0
> Twig_Loader_Chain->getCacheKey()
> [root]//vendor/twig/twig/lib/Twig/Environment.php, line 312
> 
> Twig_Environment->getTemplateClass()
> [root]//vendor/twig/twig/lib/Twig/Environment.php, line 378
> 
> Twig_Environment->loadTemplate()
> [root]//vendor/bolt/bolt/src/Render.php, line 57
> 
> Bolt\Render->render()
> [root]//vendor/bolt/bolt/src/Controller/Base.php, line 76
> 
> Bolt\Controller\Base->render()
> [root]//vendor/bolt/bolt/src/Controller/Frontend.php, line 115
> 
> Symfony\Component\HttpKernel\HttpKernel->handleRaw()
> [root]//vendor/symfony/http-kernel/HttpKernel.php, line 62
> 
> Symfony\Component\HttpKernel\HttpKernel->handle()
> [root]//vendor/silex/silex/src/Silex/Application.php, line 586
> 
> Silex\Application->handle()
> [root]//vendor/silex/silex/src/Silex/Application.php, line 563
> 
> Silex\Application->run()
> [root]//public/index.php, line 6

**Comment by SahAssar** [comment]
Fixed by @rossriley a few days ago!

**Comment by chrissound** [comment]
I'm running into the same issue. Any ideas?

This is how I'm installing bolt: 
```
cd ${pwd}
if [ ! -f bolt-latest.zip ]; then
    curl -O https://bolt.cm/distribution/bolt-latest.zip
fi

if [ ! -d public ]; then
    mkdir public
fi

unzip bolt-latest.zip -d public
mv public/bolt-3.0.12/* public/
rm -rf public/bolt-3.0.12/

cd ${pwd}

chown 82:82 -R ${pwd}/public
cd ${pwd}/public
for dir in app/cache/ app/database/ public/thumbs/ ; do
    find $dir -type d -print0 | xargs -0 chmod u+rwx,g+rwxs,o+rx-w
    find $dir -type f -print0 | xargs -0 chmod u+rw-x,g+rw-x,o+r-wx > /dev/null 2>&1
done
chmod 777 -R ${pwd}/public
```

**Comment by SahAssar** [comment]
Hey @chrissound, this issue was specifically on try.bolt.cm, so I don't think it's the same issue that you're having. Could you verify that you actually have all the necessary files in the theme folder?
