### ISSUE TITLE
[BUG] Clear Cache deletes images saved in thumbs directory

### ISSUE THREAD

**Issue by zel777** [bolt/bolt#5491]
When I clear my cache in the admin panel, all of my images that were saved to the thumbs directory get deleted. I may be mistaken, but shouldn't these images STAY in the thumbs directory when my cache is cleared? The thumbs are vital for proper display of the website... Can someone please explain why the "save_files" option is even in place if the thumbs get deleted?...

**Comment by GawainLynch** [comment]
That directory is considered a "cache", and `save_files` means to save to cache instead of regenerating on each request.

**Comment by zel777** [comment]
Is there a way to permanently save thumbnails in a permanent directory then? Until the image or post is deleted? I don't think that display images should be saved in a "cache". This is the first CMS I've ever seen that wipes out an image directory when the cache is cleared... Don't get me wrong, I love the software, but this feature is very confusing to me.

**Comment by SahAssar** [comment]
@zel777 Well, why do you want them to be permanent? They are recreated when requested if they don't exist, so I don't really see the use cause for keeping them. Clearing the cache in this way is useful for times when an image with the same name is changed/deleted. Also, if you want you can just `rm rf` the cache directory and clear it that way if you want to keep the thumbs.

**Comment by zel777** [comment]
@SahAssar I'm thinking that I may have something configured wrong, because my thumbnails do not get re-created. When I clear my cache, all of the thumbs are wiped out and do not come back. This could be something to do with updating to v3.  I'll post my configuration and the display template as soon as I get a free moment and maybe someone can explain what I've done wrong.

**Comment by bobdenotter** [comment]
@zel777 Make sure the `thumbs/` folder exists, and is writable. Also, check that you have `save_files: true` in `config.yml`.

**Comment by jemont** [comment]
i got a problems with thumbs. in firefox the thumbs are getting created but don't show up on the page. only on reload the thumbs are shown. chrome creates and shows the thumbs on first request. 
anyways on thumbs that open images with the magnific popup even in chrome the thumbs don't get created and i need to do one reload for the thumbs to show up and another reload for the images actually to be opened in the popup, otherwise the image in the popup don't get loaded and i get "the image could not be loaded".
this happens on osx browsers and bolt 3.1.1

**Comment by SahAssar** [comment]
@jemont If you have an issue please open a new issue, this one is about a different topic and has been closed. Also your issue sounds like a webserver problem to me, but open a new issue and we'll have a look at it.
