### ISSUE TITLE
Retreiving content with a belonging to a given taxon

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5494]
I would like to retireve all content with a certain taxon value from a controller.

Something like:

```php
    public function index(Request $request)
    {
        $records =  $this->query->getContent('regions', [
            'region_group' => 'Fobar',
        ]);
```

Which doesn't work, as I get the following error:

```
The given alias 'regions' is not unique in FROM and JOIN clause table. The currently registered aliases are: regions.
```

(i get the same error if I remove the taxonomy criteria).

What is the best way to retrieve content based on its taxonomy value?

**Comment by SahAssar** [comment]
If using legacy storage it would probably be this: https://github.com/bolt/bolt/blob/502ddba3e8cc4c5077f1788e1fbad0531197017d/src/Legacy/Storage.php#L1043-L1132

But that error does not look like that is the issue to me (based on nothing but gut feeling)... @rossriley, want to pitch in?

**Comment by rossriley** [comment]
Yes, I have a feeling the error is unrelated, I've got a test in core that ensures the following query works:

`$results = $app['query']->getContent('entries', ['categories' => 'movies']);`

I've also just ran a couple of tests locally and it seems to do the job too. The error looks to be coming from a doubling up of field names in the query, I'm thinking maybe it could be an issue when a taxonomy slug has the same value as the table name or something like that. 

If you could post up the `contenttypes.yml` configuration for your 'regions' contenttype and the `taxonomy.yml` configuration for region groups too, then I can get debugging.

**Comment by bobdenotter** [comment]
Closing, because this is a question. Feel free to re-open if this remains an issue.
