### ISSUE TITLE
[Test] Acceptance tests fail under 2.2.2

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5495]
Since the tagging of Codeception 2.2.2 [this button press is failing](https://github.com/bolt/bolt/blob/v3.0.8/tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php#L388)

See failures such as https://travis-ci.org/bolt/bolt/jobs/141101499

Reverting to 2.2.1 works around the issue.

**Comment by SahAssar** [comment]
Merging in 3...

**Comment by SahAssar** [comment]
2...

**Comment by SahAssar** [comment]
1....

**Comment by GawainLynch** [comment]
That was a long 1 to 0 interval
