### ISSUE TITLE
[extension] Allow prefer-source option

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5499]
Frequently when I install an extension of my own I need to make changes to it within my project. It therefore needs to be a source checkout, not the dist checkout.

With composer `dev` dependencies are git clones, and there is also a `--prefer-source` option which will force depdencies to be git cloned rather than downloaded.

With bolt it seems that extensions are always downloaded and never cloned - would it be possible to support cloning? (maybe a `--prefer-source` option?)

**Comment by GawainLynch** [comment]
Personally, I am totally in favour of this. :+1: 

There is an [`Options`](https://github.com/bolt/bolt/blob/release/3.0/src/Composer/Action/Options.php) class that is intended as a "starting point" if interested :wink:

**Comment by GawainLynch** [comment]
Done in #5571
