### ISSUE TITLE
[Storage] Custom repository for Content

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5506]
Currently it is not possible to use a custom repository for a contenttype AND have the legacy functionality of the content records.

For example, if I use a custom repository for `pages` then `record.link` does not work.

This is due to the in-between state of the storage layer (see comment [here](https://github.com/bolt/bolt/blob/release/3.0/src/Storage/EntityManager.php#L282)).

I realize this is a temporary state, but just thought I would bring it up as it is somewhat of an obstacle when it comes to keeping code organized.

@rossriley what is the plan here? does it depend on other refactorings? (e.g. routing) or could it be fixed in a minor release?

**Comment by GawainLynch** [comment]
Closed via #5523
