### ISSUE TITLE
[BUG] Cant install dev extension

### ISSUE THREAD

**Issue by versh23** [bolt/bolt#5507]
Details
-------
 - Bolt Version:  3.0.8
 - Install type: Composer install
 - PHP version:  7.0
 - Used webserver:  Nginx version 1.10
 - OS: Windows 10

I cant install dev versions extensions, such as BoltMember. 
But stable version is OK - BoltForms for example

Giving error
```
Could not find package bolt/members at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
File: D:\Projects\www\bolt\vendor\bolt\bolt\src\Composer\Action\BaseAction.php::198
```

**Comment by GawainLynch** [comment]
This is Composer's stability setting, [change this](https://github.com/bolt/bolt/blob/release/3.0/app/config/config.yml.dist#L392) to `    stability: dev`
