### ISSUE TITLE
[BUG] showImage get original width and height not working

### ISSUE THREAD

**Issue by gander** [bolt/bolt#5508]
ShowImage (`\Bolt\Twig\Handler\ImageHandler::showImage`) docs:

>      * Set width or height parameter to '0' for proportional scaling.
>      * Set them both to '0' to get original width and height.

When i use
```
{{ showimage(content.image, 0, 0) }}
```
result is
```html
<img src="..." width="0" height="0" alt="">
```

Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Composer install
 - PHP version: 7.0
 - Used webserver: Apache

**Comment by SahAssar** [comment]
Sorry, this seems to be a discrepancy between the docs and trying to get the implementation to follow the config... I tried to get all image related functions to follow the defaults (set in config.yml) if no arguments where specified. So image and showimage would follow the image size set in the config, and thumbnail would follow the thumbnail setting in the config. 

Along this line, 0 is a valid "size" to request an image, and if one want's an auto size no arguments except the file should be given (or have them set to null), see: https://github.com/bolt/bolt/blob/release/3.0/src/Twig/Handler/ImageHandler.php#L158 whereby it will then use the defaults from the config or extrapolate from the arguments given.

I'm not sure there is a function to get a raw image anymore, but it should probably be similar to how we handle files.

IMO this is pretty logical. If you want an image to be processed you use the image functions, and if you don't you don't. We need way better docs on it, but the core idea makes sense to me.
