### ISSUE TITLE
GMaps API Key mandatory since 22th June

### ISSUE THREAD

**Issue by creativo** [bolt/bolt#5509]
Geolocation field stopped working 22th June. Google API is now mandatory in Gmap apps. [More info here](http://googlegeodevelopers.blogspot.com.es/2016/06/building-for-scale-updates-to-google.html).

Proposal
------------

- Add a new **google_api** parameter in `Config.dist.yml`
- Insert the **key** parameter in `app/theme_defaults/_sub_fields.twig` http://maps.googleapis.com script calling

Details
---------

Relevant Bolt Version: 3.0
Install type: Composer install
PHP version: 7.0
Used webserver: Apache

**Comment by PhillippOhlandt** [comment]
As far as I know, there is already support for the API key. It was PR'ed a few days ago.

**Comment by PhillippOhlandt** [comment]
#5492

**Comment by GawainLynch** [comment]
… and #5505

These will land in the next stable releases of 2.2.x and 3.0.x, hopefully in the next few days!

Thanks for the detailed head-ups up though :+1:
