### ISSUE TITLE
[BUG] "Invalid Version String" on Ext Update Check

### ISSUE THREAD

**Issue by brysont** [bolt/bolt#5511]
Just updated from Bolt v3.0.3 to v3.0.8 (via composer, no errors). Went to extend menu to check for extension updates and got this error: http://prntscr.com/bp4ca6

Dismissing the modal leaves the page checking for updates with no further action (tested for 14 minutes). Have replicated the issue 3 times so far with the same result. Refresh the page, all is back to normal. Not finding any other issues related to this. Checked for ext updates before the core upgrade with no issues.

Thanks!

Details
-------

 - Relevant Bolt Version: [ 3.0.8 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used webserver: [ Apache 2 ]
 - For UX/UI issues: [ Win10 Chrome 51 ]

**Comment by GawainLynch** [comment]
The root cause of this *should* have been fixed, can you check `extensions/composer.json` and make sure not of the requires contain empty constraints, e.g.:
```json
    "bolt/boltforms": ""
```

**Comment by brysont** [comment]
Yeah, none are empty: http://prntscr.com/bp4gb4

**Comment by jnvsor** [comment]
I think it's trying to take it's version from the package manager. For example, I'm seeing this with regards to php dependancy:

>     Invalid version string "7.0.7-3"
> File: /vendor/composer/semver/src/VersionParser.php::172

Of course, if it used [version_compare](http://php.net/manual/en/function.version-compare.php) behaviour this wouldn't be a problem (And I can in fact run composer update manually and it works)

**Comment by GawainLynch** [comment]
> I think it's trying to take it's version from the package manager. 

Our Composer instance iterates over a mix of objects and arrays, depending on the action. 

> Of course, if it used version_compare behaviour this wouldn't be a problem 

It is a vendor class, and we have to deal with that. Also, version_compare is not much good here as the check is to find the best version for a given constraint, something that isn't native to PHP.

**Comment by psychonaut** [comment]
Hi, I don't it's fixed, still got error:

Invalid version string "7.0.8-3"
File: /vendor/composer/semver/src/VersionParser.php::172

bolt 3.0.9 pl 1 updated via composer from bolt 3.0.3.

**Comment by GawainLynch** [comment]
OK, can you tell me *how* you are reproducing that?

The error previously occurred due to an object being passed instead of a string (among other Composer WTFs), and I am confident (based on the fact that your error also shows a string) that the object problem is gone.

Also, according to Composer, that is not a legitimate version string, so the package you're using would help me track this down too.

**Comment by jnvsor** [comment]
I'm guessing it's his system version for PHP - I have the same result when updating extensions through the admin interface though it works with plain composer

**Comment by GawainLynch** [comment]
Nope, we use the Composer APi ourselves, the PHAR also implements the APi, but we cut out a lot of functionality that is relevant to a console application. But the API shifts all the time, so it is a bit of a catch-up game on our part

**Comment by psychonaut** [comment]
Sure,

**Comment by jnvsor** [comment]
Installing boltforms through admin:

> PHP Error
> `Invalid version string "7.0.7-3"`

> File: /vendor/composer/semver/src/VersionParser.php::172

Adding boltforms to `extensions/composer.json` and running `composer update`:

```
$ ../vendor/composer/composer/bin/composer update --no-dev
Loading composer repositories with package information
Updating dependencies
  - Installing bolt/boltforms (v3.0.2)
    Loading from cache

> Bolt\Composer\EventListener\PackageEventListener::handle
Writing lock file
Generating autoload files
> Bolt\Composer\EventListener\PackageEventListener::dump
```

The composer.json:

```
{
    "autoload": {
        "psr-4": {
            "Bolt\\Composer\\EventListener\\": "../vendor/bolt/bolt/src/Composer/EventListener"
        }
    },
    "config": {
        "discard-changes": true,
        "preferred-install": "dist"
    },
    "description": "Bolt extension installation interface",
    "extra": {
        "bolt-web-path": "../public",
        "bolt-root-path": "..",
        "merge-plugin": {
            "include": [
                "local/*/*/composer.json"
            ]
        }
    },
    "license": "MIT",
    "minimum-stability": "stable",
    "name": "bolt/extensions",
    "prefer-stable": true,
    "provide": {
        "bolt/bolt": "3.0.8"
    },
    "repositories": {
        "packagist": false,
        "bolt": {
            "type": "composer",
            "url": "https://extensions.bolt.cm/satis/"
        }
    },
    "require": {
        "wikimedia/composer-merge-plugin": "^1.3",
        "bolt/boltforms": "*"
    },
    "scripts": {
        "post-autoload-dump": "Bolt\\Composer\\EventListener\\PackageEventListener::dump",
        "post-package-install": "Bolt\\Composer\\EventListener\\PackageEventListener::handle",
        "post-package-update": "Bolt\\Composer\\EventListener\\PackageEventListener::handle"
    }
}
```

Well something's not quite right is it? :)

**Comment by GawainLynch** [comment]
Thank you both, very helpful… I should have enough time to t fix this in the next day or two!

**Comment by brysont** [comment]
FWIW I'm running Debian as well (Deb-8).

**Comment by GawainLynch** [comment]
@jnvsor that `composer.json` file you posted lists your Bolt version as 3.0.8 — was that just an old copy you were working with?

**Comment by evertalbers** [comment]
Same thing here, Bolt 3.0.9.
Screenshot: https://i.imgur.com/hJOOFZs.png

**Comment by jnvsor** [comment]
@GawainLynch Yeah. I also noticed from @psychonaut 's php version I hadn't done a system update in a while too :)

**Comment by GawainLynch** [comment]
OK… #5524 shall resolve the problem for Debian users.

…side note, this is the first time I've had to compile a custom PHP build to fix a Bolt bug :beer: time now I think :wink:

**Comment by jnvsor** [comment]
Hmm, I'd still suggest changing all non numericals into `.` and splitting by it. There are some weird package versions out there *cough* `+ubuntu0` *cough*

**Comment by GawainLynch** [comment]
Wait, Ubuntu use a `+` on their PHP `PHP_EXTRA_VERSION`? 

Side point this is how Composer handles it … and the minute we start allowing exceptions, we're just creating a slippery slide into extra work IMHO.

What I did contemplate, and might use if the answer to my question above is "yes", was to use:

```php
$phpVersion = sprintf(
    '%s.%s.%s', 
    PHP_MAJOR_VERSION, 
    PHP_MINOR_VERSION, 
    PHP_RELEASE_VERSION
);
```

But if if a broken version string is coming from a package itself… that is the package maintainers problem, not Bolt's.

**Comment by jnvsor** [comment]
I'm not sure what exactly the unbutu version string is, but they do tend to use `+` a lot in version numbers. Composer uses [version_compare](http://php.net/manual/en/function.version-compare.php) in `Composer\Package\Version\VersionSelector::findBestCandidate` which:

> The function first replaces _, - and + with a dot . in the version strings and also inserts dots . before and after any non number so that for example '4.3.2RC1' becomes '4.3.2.RC.1'.

**Comment by GawainLynch** [comment]
Just ran up an Ubuntu machine, and their `PHP_EXTRA_VERSION` is identical in structure to Debian's.

> Composer uses version_compare in 

Not the problem. :wink:
