### ISSUE TITLE
Feature request: Unable to select and copy permalink

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#5512]
It's quite hard and annoying to select and copy the permalink in the content editor. IMHO this is a much used thing.

Maybe add a 'copy permalink' option in the permalink field?

Bolt 3.0.8

**Comment by peterboorsma** [comment]
I still think it's a bug ;)

**Comment by GawainLynch** [comment]
> I still think it's a bug

I get the frustration, but it wasn't "designed" to accommodate that… but it can be redesigned :wink: 

That said, calling it a design flaw… sure, I'll run with that.

**Comment by SahAssar** [comment]
For this to really work we need #4767 to be fixed first.

**Comment by SahAssar** [comment]
This seems like one of those UI/UX issues that we will get to sooner or later, but it won't be because of this.
