### ISSUE TITLE
[RFC] File manager: Moving files between folders

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#5530]
If someone wishes to move files between folders within the file manager, they're currently unable to do so unless they directly access the file system.

It would be nice to add an option to the file and allow selection of a new file destination. Could be done via the modal system which allows you to select files, instead it selects folders.
## Details
- Relevant Bolt Version: 3.0.9

**Comment by SahAssar** [comment]
Related: #574

**Comment by rossriley** [comment]
It's obviously not the most user friendly way, but you can move files by renaming them which is in the drop down list of operations on the 'Uploaded Files' page.

Eg, if you navigate to `newsimages` and you want to move to `otherimages` you can load up the images inside the `newsimages` folder, pick a file, choose Options > Rename image1.jpg and in the dialog that comes up enter: `../otherimages/image1.jpg`

**Comment by SahAssar** [comment]
Closing, a more full featured file manager is one of those "sorta planned" features, and this would certainly be a part of it. See #574
