### ISSUE TITLE
RepeatingFieldCollection - mapping vs. field config in legacy storage

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#5533]
The RepeatingFieldCollection constructor should be passed a mapping but [here](https://github.com/bolt/bolt/blob/502ddba3e8cc4c5077f1788e1fbad0531197017d/src/Legacy/Storage.php#L2729) it is passed a field config instead which leads to it throwing a FieldConfigurationException [here](https://github.com/bolt/bolt/blob/faefe71ac4d3fc7d562efac62575db7f1866516e/src/Storage/Field/Collection/RepeatingFieldCollection.php#L208) when one uses `addFromArray` or similar methods.

I'm not sure how to get the mapping there (in legacy storage) so, I'm opening this issue instead of PR'ing a fix :)

**Comment by SvanteRichter** [comment]
@rossriley do you know if we ever fixed this? I can't seem to find any commits/PR's relating to it.

**Comment by bobdenotter** [comment]
I'm not @rossriley, but I don't think so. 😇

Let's re-open and add a `keep` label

**Comment by sablonier** [comment]
The fix with reference to this issue in https://github.com/BoltTranslate/Translate/blob/master/src/Storage/Legacy.php loose LazyFieldCollection references with 3.6.x. Maybe someone who understands RepeatingFieldCollection vs. FieldCollection vs. LazyFieldCollection etc. can have a look, remove or alter the fix and close this issue- or close it here and move it to Bolt/Translate?
