### ISSUE TITLE
[RFC] Improve error handling of accessing non-existing contenttypes in dashboard

### ISSUE THREAD

**Issue by ThomasBerends** [bolt/bolt#5537]
Currently if you visit, for example `/bolt/editcontent/thisdoesntexist`, you get the error:
`Attempted to load mapping data for unmapped class thisdoesntexist`

This error doesn't say that the contenttype doesn't exist, and me (and at least one other user) have run into this problem and had trouble figuring out what resulted into this error.

I propose a better handling of this situation so users get a clear 404 error and see a clear error.
For example: `Contenttype thisdoesntexist doesn't exist.`.

Details
-------

 - Relevant Bolt Version: 3.0 | master
 - Install type: All
 - PHP version: All

Reproduction
------------

If you have a running Bolt installation, simply go to `/bolt/editcontent/thisdoesntexist` to reproduce the error. Any string (except an existing contenttype) instead of 'thisdoesntexist' will result in the unclear error.

**Comment by GawainLynch** [comment]
@rossriley I am wondering if we shouldn't have an extension that extends `Bolt\Exception\StorageException` for this specifically to make catching easier in these instances… thoughts?
