### ISSUE TITLE
[BUG] Bolt 3.0.9 logging into user produces event error

### ISSUE THREAD

**Issue by Jovinsson** [bolt/bolt#5539]
Details
-------

 - Relevant Bolt Version: 3.0.9
 - Install type: Zip/tarball install
 - PHP version: 5.5.35
 - Used webserver: Apache (XAMPP 5.5.35)

Reproduction
------------

 **Bug Summary** 
When logging into Bolt.cm the page will attempt to process login and then present the error at the bottom of this post. If you navigate to the backend again (for my install its /admin instead of /bolt) and try log in a 2nd time, it will work. This is the case every time for all users. 1st time fail, second time succeeed.

 **Specifics** 
URL impacted: http://mybolt.local/tenser3/admin/login
All users as stated above

 **Steps to Reproduce** 

1. Access the backend via http://mybolt.local/tenser3/admin without being logged in
2. Log in with any user
3. The error below is presented
4. Access the backend again via http://mybolt.local/tenser3/admin
5. Log in with the same user
6. Successfully logged in

**Expected Result** 
Should be able to successfully log in after 1st attempt

**Actual Result** 
Every user takes exactly 2 attempts to log in successfully

**My Install Modifications** 
1. I have changed my back-end access from /bolt to /admin
2. I have moved my /public files into the root directory and modified my `.bolt.yml` to show the following as I cannot change the Document Root.
```
paths:
    cache: app/cache
    config: app/config
    database: app/database
    web: .
    themebase: theme
    files: files
    view: bolt-public/view
```

Error Message
------------
```
Bolt - Fatal error.
Class: RuntimeException
Message: Attempted to change event user name.
Code: 0
Bolt\Events\AccessControlEvent->setUserName()
C:\xampp\htdocs\tenser3\vendor\bolt\bolt\src\AccessControl\AccessChecker.php, line 261

Bolt\AccessControl\AccessChecker->checkSessionKeys()
C:\xampp\htdocs\tenser3\vendor\bolt\bolt\src\AccessControl\AccessChecker.php, line 194

Bolt\AccessControl\AccessChecker->checkSessionStored()
C:\xampp\htdocs\tenser3\vendor\bolt\bolt\src\AccessControl\AccessChecker.php, line 130

Bolt\AccessControl\AccessChecker->isValidSession()
C:\xampp\htdocs\tenser3\vendor\bolt\bolt\src\EventListener\RedirectListener.php, line 76

Bolt\EventListener\RedirectListener->handleNoBackendAccess()
C:\xampp\htdocs\tenser3\vendor\bolt\bolt\src\EventListener\RedirectListener.php, line 63

Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
C:\xampp\htdocs\tenser3\vendor\symfony\event-dispatcher\EventDispatcher.php, line 46

Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
C:\xampp\htdocs\tenser3\vendor\symfony\http-kernel\HttpKernel.php, line 184

Symfony\Component\HttpKernel\HttpKernel->filterResponse()
C:\xampp\htdocs\tenser3\vendor\symfony\http-kernel\HttpKernel.php, line 166

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
C:\xampp\htdocs\tenser3\vendor\symfony\http-kernel\HttpKernel.php, line 64

Symfony\Component\HttpKernel\HttpKernel->handle()
C:\xampp\htdocs\tenser3\vendor\silex\silex\src\Silex\Application.php, line 586

Silex\Application->handle()
C:\xampp\htdocs\tenser3\vendor\silex\silex\src\Silex\Application.php, line 563

Silex\Application->run()
C:\xampp\htdocs\tenser3\index.php, line 14
```

**Comment by GawainLynch** [comment]
Firstly… Thank you for a detailed report! :+1: 

OK, I am guessing this is a path issue on Windows. The exception you are getting should only happen (under "normal" circumstances) if someone was trying to change audit data compared to what is stored in session … 

So that exception is getting thrown (on the first attempt) as the [session is not returning the authentication object](https://github.com/bolt/bolt/blob/release/3.0/src/AccessControl/AccessChecker.php#L259-L260) and passing a null to the event for the user name and failing the security check as a result.

If you're game with editing files, I would have a look at [this change](https://github.com/bolt/bolt/pull/5527/files) and if you could manually apply it (I don't have any Windows machines).

**Comment by Jovinsson** [comment]
Thank you very much @GawainLynch! Sorry for not stating what OS it is running on, but you picked it perfectly.

Adding that modification to the ResourceManager.php file fixed it. Kudos to you!

**Comment by GawainLynch** [comment]
Mate, not a problem… your reporting made it easy. Thank you too!
