### ISSUE TITLE
[docs] Custom Field Types setZone for getAssets

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5540]
Following the documentation [here](https://docs.bolt.cm/3.0/extensions/advanced/customfields) instructions are given for registering custom assets.

However, this will not work unless the assets are assigned to a zone:

```php
		$asset = new JavaScript('web/jquery.uix.multiselect.min.js');
		$asset->setZone(Zone::BACKEND);
        return [
			$asset
        ];
```

**Comment by GawainLynch** [comment]
FYI, the docs repo is [here](https://github.com/bolt/docs)

**Comment by dantleech** [comment]
ok, didn't realise. moved to https://github.com/bolt/docs/issues/448
