### ISSUE TITLE
[BUG?] Custom field type similiar selectmultiple clear all issue

### ISSUE THREAD

**Issue by denis-gorin** [bolt/bolt#5556]
I've  created custom field whith functionality of selectmultiple (binding entries from bolt/members extension with some content type). 

Everything is okay, but when I try to clear all once selected and saved members and save the entry the previous value of my custom field is recovered. 
There is going ok when I change option multiple to false - the field value reset.

All roads led me to this code:

* file: vendor/bolt/bolt/src/Storage/ContentRequest/Save.php
* function: setSuccessfulControlValues
* line:  ~ 315

```
if ($values['type'] === 'select' && isset($values['multiple']) && $values['multiple'] === true) {
    $formValues[$key] = [];
} elseif ($values['type'] === 'checkbox') {
     $formValues[$key] = 0;
}
```

As we see the reset of selectmultiple field is bound for type select, not for any multiple.

I've tried to remove this restriction :

```
if (isset($values['multiple']) && $values['multiple'] === true) {
```

And have got what I want.

Details
-------

 - Relevant Bolt Version: 3.0.11 
 - Install type: Composer install
 - PHP version: 7.0
 - Used webserver: Nginx 1.11.1

**Comment by GawainLynch** [comment]
I may be in need of :coffee:, are you talking about the screen for editing Members in the admin section?

**Comment by denis-gorin** [comment]
Yes in admin section but not editing members. Sorry I forgot mention, I've created extension for custom field type. It is working similiar native select field, but get entries from bolt/members extension

http://screencast.com/t/w9f704Xlifn

**Comment by GawainLynch** [comment]
Looks cool, btw! Just a heads up … we're getting pretty close to a beta sage on dev-master of Members, but no promises that stuff won't break in the mean time :wink: 

I'll have to see if I can dig in at some point … I don't suppose you could send me the class for the custom field?

**Comment by denis-gorin** [comment]
Ok, I will put extension in public a little bit later, although it is ugly for now, and, I'm afraid, will not be universal (it is designed to address my specific tasks)

**Comment by GawainLynch** [comment]
Oh that is fine, you can even just email the class to me if you like

**Comment by denis-gorin** [comment]
Ok!

**Comment by SahAssar** [comment]
Hmm, if the field isn't `multiple` then it shouldn't be set to an empty array, it should be set to `null`, right?

Or am I also making pre-coffee assumptions?

**Comment by GawainLynch** [comment]
Yeah, that is what I came to as well. What I want to check is that we don't have a data loss bug as a result. It may well be a non-issue, but want to look when I get a chance.

**Comment by SahAssar** [comment]
Hey @denis-gorin,

Another potential pre-coffee comment: Reading through your issue again it sounds to me like you are talking about the select field and "selectmultiple" as two different fieldtypes, when they really are the same just with or without `multiple: true` in the field config.

The reason the default is just set on multiple is that that's the only situation where we need to selectfield to be iterable but empty. For normal select fields null is fine, and is what is posted from an empty selectfield.

Is your modified select fieldtype set to `multiple: true`?

**Comment by denis-gorin** [comment]
> Is your modified select fieldtype set to multiple: true?

Yes

**Comment by SahAssar** [comment]
If it is the removing `isset($values['multiple']) && $values['multiple'] === true` should make no difference whatsoever...

**Comment by denis-gorin** [comment]
aaaa... sorry my bad english. I think I've confused you...
I mean, I remove this piece of code `$values['type'] === 'select'`

BEFORE


```
if ($values['type'] === 'select' && isset($values['multiple']) && $values['multiple'] === true) {
    $formValues[$key] = [];
} elseif ($values['type'] === 'checkbox') {
     $formValues[$key] = 0;
}
```

AFTER


```
if (isset($values['multiple']) && $values['multiple'] === true) {
    $formValues[$key] = [];
} elseif ($values['type'] === 'checkbox') {
     $formValues[$key] = 0;
}
```

I think attribute multiple itself implies select fieldtype

**Comment by SahAssar** [comment]
Ah, now I got what you mean!

That sort of logic should be handled by your extension... We don't know what attributes another extension or a future bolt release might add, so it'd probably be bad to assume the fieldtype from the attributes alone... You can see how custom hydrate/persist works by taking a look at https://github.com/rossriley/bolt-url-field/blob/master/src/Field/URLFieldType.php for example.

I'm going to close this, but if you have issues with the hydrate/persist please let us know!

**Comment by denis-gorin** [comment]
> ...bad to assume the fieldtype from the attributes alone...
You are right about that.

I will look to hydrate/persist example again, But it seems no chance for my case... In hydrate data always has cleared options from select (when clear all).

**Comment by SahAssar** [comment]
Persist is probably where you want to be looking... You should have direct access to the posted value and can therefore fix it there.

**Comment by denis-gorin** [comment]
> You should have direct access to the posted value

You are right! Thanks!

```
$globals = Request::createFromGlobals();
$postedValue = $globals->request->get($key);
```
