### ISSUE TITLE
[BUG] Database check/update - incorrect error messages

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#5558]
There are unnecessary/incorrect error messages when upgrading the database.

Details
-------

 - Relevant Bolt Version: 3.0.10
 - Install type: Composer
 - PHP version: 5.5.37
 - Used webserver: Apache

Reproduction
------------

1. Add a new field to a content type. The "check database" red box should appear.
2. Click "check database" to go to the page.
3. Bug 1: (minor) when you're on the check database page, the error message still says "Go to 'Configuration' > 'Check Database' to do this now."
4. Click the upgrade button to actually do the upgrade.
5. Bug 2: Once the upgrade is complete, the error message is still there until you reload the page:

![bolt-error](https://cloud.githubusercontent.com/assets/207887/16986497/b7059242-4e7e-11e6-985c-3a721c9517d8.jpg)

**Comment by GawainLynch** [comment]
There are some cases that DBAL can't handle.

Can you press the "Show proposed alterations" and let us know what changes it wants to make and we'll try to talk you though the change.

**Comment by GawainLynch** [comment]
Also "bug 1" isn't so much a bug as the session isn't coupled to the route, so the flashbag will show regardless

**Comment by svivian** [comment]
> Can you press the "Show proposed alterations" and let us know what changes it wants to make and we'll try to talk you though the change.

The screenshot above shows what alterations were made. I added a 'city' column. After running the upgrade, the error still shows on that page view, even though it was completed successfully. Reloading the page (or clicking check again or going to any other page) the error disappears.

I'm guessing the check for whether the db needs upgrading is done *before* the actual upgrade is completed.

> Also "bug 1" isn't so much a bug as the session isn't coupled to the route, so the flashbag will show regardless

Sure, just a minor UX point.

**Comment by GawainLynch** [comment]
> The screenshot above shows what alterations were made. 

Have I got a present for you :+1: 

3.x has a "Show proposed alterations" that will add additional output, e.g.

![image](https://cloud.githubusercontent.com/assets/1427081/16991445/e771d81a-4e9b-11e6-9a63-119b28ce97f8.png)

The notice in your original screenshot is just a simple "human friendly" string that doesn't give much information :smile:

**Comment by svivian** [comment]
I'm not sure you're understanding the problem. **The database update already completed successfully.** The problem is the error message shows *after* the database is updated.

**Comment by GawainLynch** [comment]
OK… I might not be understanding myself … I blame the :koala: 

So after you have successfully updated the database, and then refreshed a second time, the flash goes away? 

i.e. the problem you're highlighting is the fact that it is *still* there after pressing the button to do the update the first time

If that is the case, to explain, there are a couple of things that can cause DBAL to get its shoe laces in a twist and I thought you'd hit one of those.

**Comment by svivian** [comment]
> So after you have successfully updated the database, and then refreshed a second time, the flash goes away?

Yes.

>  there are a couple of things that can cause DBAL to get its shoe laces in a twist and I thought you'd hit one of those.

OK well it's really just adding a single field like I said. But I added a test field (literally `test` with `type: text`) and here are the "proposed alterations":

```
bolt_properties
ALTER TABLE bolt_properties CHANGE county test VARCHAR(256) DEFAULT ''

TableDiff {#1486 ▼
  +name: "bolt_properties"
  +newName: false
  +addedColumns: []
  +changedColumns: []
  +removedColumns: []
  +renamedColumns: array:1 [▶]
  +addedIndexes: []
  +changedIndexes: []
  +removedIndexes: []
  +renamedIndexes: []
  +addedForeignKeys: []
  +changedForeignKeys: []
  +removedForeignKeys: []
  +fromTable: Table {#1941 ▶}
}
```

**Comment by svivian** [comment]
Also another related point - when I remove fields from my contenttype, they are not removed from the database (no "database update required" message appears). Is there a way to remove them via Bolt, or do I need to do this manually in the DB?

Would be nice if there was a separate button on the Check Database page, allowing to remove those fields.

**Comment by GawainLynch** [comment]
> Also another related point - when I remove fields from my contenttype, they are not removed from the database (no "database update required" message appears). 

That is a very deliberate design decision to prevent accidental data loss on ContentType records. 

> Is there a way to remove them via Bolt, or do I need to do this manually in the DB?

Well, you could easily do it in an extension … but it would be a significantly less amount of work to just fire up a database admin client and drop the column.

You're welcome to RFC something if you feel it is worth it. Generally the thinking has been that the data cost is small (if not tiny) and those that need to regain that space know how.
