### ISSUE TITLE
UI missing ability to remove not-yet-installed or disabled extension

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5576]
![image](https://cloud.githubusercontent.com/assets/1427081/17093418/7cb83ad0-5249-11e6-95e2-2abbb7e2d582.png)

At this point a user either has to enable or install a potentially broken extension to uninstall it, or edit `extensions/composer.json`

**Comment by bobdenotter** [comment]
I think this is no longer an issue in 3.2, right?

**Comment by GawainLynch** [comment]
I believe it is.

**Comment by bobdenotter** [comment]
Just double-checked.. It still is valid.. self-assigning.

**Comment by GawainLynch** [comment]
^w^w^w^w^w^w^w^w^w^w^w^w^w^w
