### ISSUE TITLE
Migration of extension to Bolt3 crashes if getname() is used

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5579]
If you migrate any extension from Bolt 2 to Bolt 3, you will most probably have a **getName()** method in your old extension, that is returning a string. In Bolt 3 however, this method is already defined in the base classe AbstractExtension. And it is defined as *final*.

Since you are now extending a method defined as **final**, your Bolt will crash. The problem with it is, Bolt's Error handling will brak to. You will have **no error**, and **no log entry** leading to a long hunt for invisible bugs.

**Suggestion**
1) I heard the error handling is rewritten. Please take this case into account and allways return something ro at least use the basic error reporting and logging. There is nothing worse than having to develop blind.

2) If there is no good reason for declaring the method **final** please consider keeping it consitant with the old method definiton or maybe even rename it. This creates problems with migration of extensions.

3) Update the migration guide to include this detail please.

Details
-------

 - Relevant Bolt Version: 3.0.11
 - Install type: Composer install
 - PHP version:5.5
 - Used webserver: Apache

Reproduction
------------

Just create a getName() method in one of your extensions (local works too) and return some string there.

**Comment by GawainLynch** [comment]
This is not a bug, but programmer error… albeit it easy one to make. :wink: 

You are correct, the failing is in the documentation here, and I thought we had but obviously hadn't covered this one.

**Comment by GawainLynch** [comment]
Ah, [found it](https://docs.bolt.cm/3.0/upgrading/moving-22-30-advanced#independent-or-local-extensions)

**Comment by ToBe998** [comment]
Yep, like I said, the main problem is not that it's final but that it's difficult to find out what's wrong there. ;)

**Comment by SahAssar** [comment]
I'm sorry if this sounds off, but when migrating a 2.2 to a 3.0 wouldn't one be expected to read the migration guide that is provided? It's not ideal at all that it throws a WSOD (which as I understand it does?), but this is still loading an incompatible extension on an incompatible bolt version, right?

If one has local extensions they are expected to know what/how to debug and to check the docs for relevant info, right?

@GawainLynch Does your exceptionhandling work help with this in the near/far future?

**Comment by ToBe998** [comment]
@SahAssar you are right, it's now mostly a documentation problem. (A less critical behaviour would be nice, but we can absolutly live with this). The documentation now contains specific instructions about exactly this issue, so for me this bug can be closed.

**Comment by GawainLynch** [comment]
FWIW… This commit d62cbe42a2b4e3a304a822d899b4c6def6620f73 will stop the white screens in this case, at the very least giving you information you can work with in fixing/solving this issue in the future.

**Comment by GawainLynch** [comment]
In #5667

**Comment by bobdenotter** [comment]
Fixed in #5667.
