### ISSUE TITLE
[BUG] Unknown argument "skip_uses" for function fields()

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#5586]
When I use the `skip_uses` example from the bottom of [this page](https://docs.bolt.cm/3.0/templates/fields-tag), I get an error:

> Unknown argument "skip_uses" for function "fields(record, common, extended, repeaters, templatefields, template, exclude)" in "record.twig" at line 10.

To be clear I'm using this in `record.twig`:

    {{ fields(skip_uses = false) }}

Details
-------

 - Relevant Bolt Version: 3.0.11
 - Install type: composer
 - PHP version: 5.5
 - Used webserver: Apache

**Comment by SahAssar** [comment]
As far as I can see it was never implemented... Checking the file history with `git log -S'skip_uses' -- src/Twig/Handler/RecordHandler.php` and `git log -S'skip_uses' -- /app/theme_defaults/_sub_fields.twig` show nothing, and the check isn't there in https://github.com/bolt/bolt/blob/release/3.0/app/theme_defaults/_sub_fields.twig#L20-L22...

Should be easy enough to implement though.
