### ISSUE TITLE
[BUG] Blank alert box when deleting folders

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#5590]
1. Go to the file manager.
2. Delete any folder (by clicking the "Options" dropdown then "Delete foldername").
3. An alert pops up saying "Do you really want to delete foldername?". Click OK.

Expected: the folder to be deleted.

Actual: a second, blank alert box appears. It doesn't appear to do anything as clicking either button continues to delete the file.
## Details
- Bolt 3.0.11
- PHP 5.5
- Apache server
- Chrome browser, Mac

**Comment by GawainLynch** [comment]
This has long since been fixed in stable. Closing.
