### ISSUE TITLE
[BUG] Display issues with File Manager

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#5592]
1. Go to the file manager.
2. Upload a small image, such as a 16x16 icon.
3. Click the filename to preview the image.

**Problem 1:** the image thumbnail shown in the file list is blurry and has the wrong aspect ratio. The problem is that the image is linked as `/thumbs/54x40c/icons/pdf-button.png` which resizes/crops images to 54x40, but not if they are smaller than that. But the `<img>` tag has the size explicitly set to `width="54" height="40"`

![bolt-bug-icon](https://cloud.githubusercontent.com/assets/207887/17147474/d6157824-535a-11e6-997c-5a42d94d3f75.jpg)

To solve this, you could 'expand' the image canvas to 54x40, by which I mean make it a 54x40 image with the icon regular size sat in the middle. Or, change the img tag to use `style="max-width:54px; max-height:40px`

**Problem 2:** when you click the filename to see the full-screen 'preview', the filename is squashed into a narrow column:

![bolt-bug-preview](https://cloud.githubusercontent.com/assets/207887/17147475/d61cb346-535a-11e6-9b2e-17336d873fbe.jpg)

Probably want to set a minimum width on the 'figure'. I'd suggest adding a `min-width` to `.mfp-figure`, around 250px should be enough. A minimum height may be worthwhile too to make it look better.

Details
-------

- Bolt 3.0.11
- PHP 5.5
- Apache server
- Chrome browser, Mac (issues also occur in Firefox)

**Comment by SahAssar** [comment]
problem 1 is one that we should fix anyway in showimage and one I didn't get to during my last run through those parts, basically if `allow_upscale` is false we should max out at the images natural dimensions (and also a check for resize to make sure that we preserve aspect ration if it is resized, not cropped/bordered).

problem 2 should just be the min-width/min-height like you said.

You wanna PR those fixes or you want me to do it? :)

**Comment by GawainLynch** [comment]
@SahAssar do you want to take lead on getting this one over?

**Comment by SahAssar** [comment]
(just tagging, mostly for myself) This is sorta, kinda related to #4474, The fix should aim to fix both.

**Comment by GawainLynch** [comment]
Fixed in #5848 … the :koala: forgot to close :wink:
