### ISSUE TITLE
[BUG] Unable to rename files

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#5594]
Me again, starting to wonder if you've tested your own app at all ;)

Actually this one could be an issue on my side but I can't see what would be causing it. After my earlier bug report I have everything set up with correct permissions, but I am not able to rename files through Bolt.

I've uploaded a file through the file manager in Bolt, so the folder definitely has the correct permissions. I can even delete the file. But when I try to rename it I just get an alert:

> "Unable to rename file: pdf-button.png"

I've tried increasing the permissions - the file uploaded through Bolt was originally 644 with the same `_www` user (which should work of course), but changing that manually to 666 still doesn't work. Same with the folder (it's 777).

Details
-------

- Bolt 3.0.11
- PHP 5.5
- Apache server
- Chrome browser, Mac

**Comment by GawainLynch** [comment]
Related to #5478 and #5582?

**Comment by svivian** [comment]
I don't think so. I don't have any special/accented characters in the filename or server path (unless in that other bug, a hyphen is counting as a special character?)

**Comment by GawainLynch** [comment]
Oh, the characters were a red herring … it was actually a path issue that looks very similar to what you reported.

**Comment by bobdenotter** [comment]
I'm not able to reproduce this. For me it works as expected. 

Is this still an issue?

**Comment by svivian** [comment]
Not using Bolt for my project any more so technically, no.
