### ISSUE TITLE
[RFC] SQLite, "analyze;" and DB performance

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#5603]
Many "expensive" db queries can gain a massive speedup in SQLite if [analyze;](https://www.sqlite.org/lang_analyze.html) has been run on the database since the SQLite queryplanner becomes much more efficient with the additional info it has to work with (if I have understood things correctly). Analyze needs to be rerun if the db changes significantly or if the schema is updated though, so it's not fire and forget by itself.

Currently it has to be done manually with `sqlite3 app/database/bolt.db "analyze;"`, which one can put in a cron or whatever to ensure continuous good performance.

I'm wondering if it would be possible to run this on every schema update that that an SQLite-based bolt install does and add it to one of our default app/nut cron jobs.

---

Example query for 250ish relations on the frontend (legacy storage) (with all the `or` clauses for the id's removed except one for readability):

```
SELECT bolt_kommentarer.* FROM bolt_kommentarer WHERE (( "bolt_kommentarer"."id" = '269209' ) AND "bolt_kommentarer"."status" = 'published') ORDER BY datepublish DESC LIMIT 9999
```

Before analyze: 7622.69 ms

After analyze: 6.51 ms

---

Example query for the 5 latest modified to show in the sidebar of a contenttype overview on the backend (new storage):

```
SELECT bolt_kommentarer.* FROM bolt_kommentarer WHERE ("bolt_kommentarer"."status" = 'published') ORDER BY "datechanged" DESC LIMIT 5 
```

Before analyze: 2265.70 ms

After analyze: 0.21 ms

---

Those examples are pretty extreme (that contenttype has a lot of records), but even on more "normal" queries it can make a difference. Queries that are already in the sub-ms range stay mostly the same though in my testing.

If we don't add it so it's automatically run in bolt it'd be nice to have as a section in https://docs.bolt.cm/3.0/howto/performance-tips anyway.

**Comment by GawainLynch** [comment]
Docs: :+1: 
Calling out to a binary we can't guarantee is there, or allowed by the system: :-1:

**Comment by SahAssar** [comment]
@GawainLynch Sorry, I wasn't clear, analyze can be run as a simple sql query. I just used the example with sqlite3 as that is how I've run it on my db's.

It can be run from php by just running the query "analyze;".

**Comment by GawainLynch** [comment]
Derp… Sounds like a potential addition to the "check database" page

**Comment by SahAssar** [comment]
Oh, and I just retested on a more "normal" site (50ish pages, 100ish newsitems, a few more small contenttypes), the backend query time went from ~10ms to ~4ms, so most sites should see an improvement.

**Comment by bobdenotter** [comment]
👍

**Comment by SahAssar** [comment]
Fixed by adding docs.
