### ISSUE TITLE
[RFC] Slugify file names instead of sanitizing during upload

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5606]
**Problem**: many clients use local file names during upload. So server is now full of similar names like `-1.jpg` and other like this.

Maybe we can slugify image name, when using standard uploader? Now sanitizing is used.. so `название картинки.jpg` is  uploaded as `nazvanie-kartinki.jpg` and not `-.jpg`. Or we can `sanitize(slugify($image_name))`..
What do you think?

**Comment by zkchen310** [comment]
:shipit:

**Comment by SahAssar** [comment]
Sounds good to me, @Boorj can you PR that? The second option of `sanitize(slugify($image_name))` looks best to me.

**Comment by Boorj** [comment]
Not sure i can do it soon :sob: . But if i'm the only one for that - assign me to the task.

**Comment by Boorj** [comment]
..still busy, but remember :blush:

**Comment by GawainLynch** [comment]
Closing based on six months of nobody stepping up to do this, and limited resources.

Volunteers to make it happen most welcome, and support/help available to said person(s)
