### ISSUE TITLE
[BUG] (or rfc?) Underscopes in slug name

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5607]
When user edits slug manually and puts underscopes instead of dashes (hyphens), system _allows_ him to do that. So slug is stored like `'this_is_slug'` in database. 

But when i use `$app['slugify']->slugify($potential_slug)` in code to detect if there's a content for this slug (got `$potential_slug` by routing system), `slugify` changes underscopes to dashes. So in uri it's `http://foo.com/bar/this_is_slug`. After slugifying  system couldn't find `'this-is-slug'`, because in db it has underscores (`'this_is_slug'`).
Am i doing something wrong?

I made a simple workaround, but not sure it's a proper system workflow..
```php
$slug = str_replace('_', 'o0o0o0o0o0o', $slug);
$slug = $app['slugify']->slugify($slug);
$slug = str_replace('o0o0o0o0o0o', '_', $slug);
```

p.s. feel free to rename this issue.. or close if i'm doing something wrong.

**Comment by Boorj** [comment]
seems it's related to #5601 , @GawainLynch suggested allowing `_` in that topic..

**Comment by rossriley** [comment]
I'm going to close this one in favour of #5601 which I've already assigned to myself and we'll get a solution in place.
