### ISSUE TITLE
[BUG] Unnecessary db queries on extension route load

### ISSUE THREAD

**Issue by maximivanov** [bolt/bolt#5624]
Local extension with a route which does nothing more than `return new Response('Drop bear sighted!', Response::HTTP_OK);` results in a few unnecessary SQL queries.
I want to have a performant Bolt setup, and these extra queries seem like a problem.

Details
-------

 - Relevant Bolt Version: [ 3.0.11 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used webserver: [ Nginx 1.4.6 ]

Reproduction
------------

Fresh bolt install. I have 2 content types enabled: "blocks" and "banners".
New local extension created via github's bolt/bolt-extension-starter:^3.0.
Extension code:

```
class EavExtension extends SimpleExtension
{
    protected function registerFrontendRoutes(ControllerCollection $collection)
    {
        $collection->get('/custom', [$this, 'callbackCustom']);
    }

    public function callbackCustom(Application $app, Request $request)
    {
        return new Response('Drop bear sighted!', Response::HTTP_OK);
    }
}
```

Open page http://boltdomain/custom as anonymous user. It renders 'Drop bear sighted!' as expected, but in query log I can see these 5 queries while I expect to see none (or probably just the first one?):

```
SELECT name FROM sqlite_master WHERE type = 'table' AND name != 'sqlite_sequence' AND name != 'geometry_columns' AND name != 'spatial_ref_sys' UNION ALL SELECT name FROM sqlite_temp_master WHERE type = 'table' ORDER BY name

SELECT id FROM bolt_blocks WHERE (status = :oldstatus) AND (datepublish < :currenttime)

SELECT id FROM bolt_blocks WHERE (status = :oldstatus) AND (datedepublish <= :currenttime) AND (datedepublish > :zeroday) AND (datechanged < datedepublish)

SELECT id FROM bolt_banners WHERE (status = :oldstatus) AND (datepublish < :currenttime)

SELECT id FROM bolt_banners WHERE (status = :oldstatus) AND (datedepublish <= :currenttime) AND (datedepublish > :zeroday) AND (datechanged < datedepublish)
```

**Comment by GawainLynch** [comment]
This has been changed in the upcoming 3.1 release… and heavily redone in the 3.2 branch.

See #5599

**Comment by PhillippOhlandt** [comment]
That are the queries to check if a timed publish/depublish needs to change the status of a record. @GawainLynch already built something to do those queries only all X minutes.

**Comment by PhillippOhlandt** [comment]
Damn, @GawainLynch was faster :D
