### ISSUE TITLE
[BUG] Garbage collection of session files doesn't work

### ISSUE THREAD

**Issue by dariusz-rzeznik** [bolt/bolt#5625]
Hi.

After commit https://github.com/bolt/bolt/commit/2d2634a5fe111613aa60eaed56bb7ab61b9b5a3e
Change cache://session to cache://.sessions functionality of cleaning session files has stopped working.

In bolt\filesystem\src\Iterator\PathFilterIterator.php
In accept method we have problem in:

       foreach ($this->noMatchRegexps as $regex) {
            if (preg_match($regex, $filename)) { //here is the problem with dot files - .session/

In my opinion we have to register new mount point in Bolt\Configuration\ResourceManager eg. $this->setPath('session', 'app/sessions');

and that mount point should be used to store session files, it can not be dot directory.

Details
-------

 - Relevant Bolt Version: 3.0 | master 
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Apache 2.4
 - For UX/UI issues: not relevant

**Comment by GawainLynch** [comment]
- `ResourceManager` is in the process of being removed, so the mount point would be in `bolt/filesystem`
- Sessions is a volatile directory, so `app/` is out, and given the incredibly broad distribution of environment types we have to support, cache is the only area that we *know* we can write to 
- The dot directory was used to prevent a flush logging out every single user
- The cache layout changes in #5615

In other news, thanks for finding this one … we've known it was there for a bit, just unsure what :+1:

**Comment by bobdenotter** [comment]
Fixed by #5615
