### ISSUE TITLE
Bolt session listener breaking functional tests

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5650]
I am testing a Bolt application using BrowserKit - which means that all the requests are in the same process.

The problem was that the cookies were not being persisted, after much digging the culprit was:

```php
        # SessionListener
        if ($this->options->getBoolean('restrict_realm')) {
            $name .= md5($request->getHttpHost() . $request->getBaseUrl());
            $this->session->setName($name);
        }
```

https://github.com/bolt/bolt/blob/release/3.0/src/Session/SessionListener.php#L52

This caused the session name to be appended to for each request, meaning that the session was named differently each time.

**Comment by dantleech** [comment]
Worked around with overriding the session options in the Application:

```
$options = $this['session.options'];
$options['restrict_realm'] = false;
$this['session.options'] = $options;
```

**Comment by dantleech** [comment]
But this means the session ID changes on each request made in the same process... 

e.g.

```
1. bolt_session_123nfdkjadsfjsdf
2. bolt_session_123nfdkjadsfjsdf23nfdkjadsfjsdf
3. bolt_session_123nfdkjadsfjsdf23nfdkjadsfjsdf23nfdkjadsfjsdf
...
```

Normally the listener only gets called once per process invocation, but when called multiple times it appends the hash to the existing session ID.

**Comment by GawainLynch** [comment]
OK, *that* is a bug … it should only get called once and set `bolt_session_abc123` which on everything I have control over **is** running correctly.

I'll try and reproduce (if someone doesn't get there first) … but is there anything "interesting" about your setup?

**Comment by dantleech** [comment]
No, I don't think so, other than the fact that I am making multiple requests in the same process:

```
    public function testLogin()
    {
        $this->getSession()->visit('/connexion');
        $this->getPage()->fillField('_username', 'adherent@example.com');
        $this->getPage()->fillField('_password', 'foobar');
        $this->getPage()->pressButton('connect_button');
        $this->assertStatusCode(200);

        // user is logged in
        $this->assertSession()->pageTextContains('adherent@example.com');
    }
```

Feel free to assign to me if you don't have a burning desire to do this :)

**Comment by GawainLynch** [comment]
> Feel free to assign to me if you don't have a burning desire to do this 

Go for it

ping @CarsonF

**Comment by CarsonF** [comment]
Doh! Nice find @dantleech, PR away 👍

**Comment by CarsonF** [comment]
Probably just checking if the name already ends with the "realm" then don't append it again

**Comment by CarsonF** [comment]
@dantleech Hope you don't mind, I was in there anyways :)

**Comment by dantleech** [comment]
Absolutely not! Thanks :)
