### ISSUE TITLE
[Bug] Memcache Session Management broken

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5658]
The session management in Bolt 3+ currently has a design flaw that breaks sessions in a couple of situations.

Bolt has it's own session management that reads and writes directly to session storage and is not using the PHP native session storage like other applications (including silex and sf2 apps do). This leads to trouble when paired with the ability of Bolts SessionServiceProvider to parse and import PHPs session options.
If you do this, Bolt essentially uses the same session storage as PHP and conflicts with it. See this scenario:
- PHP Session reads it's data , currently containing "START". This allways happens at "session_start", probably during application boot.
- Bolt reads it's session data, still containing "START".
- Bolt writes "CHANGED" to it's session (while not using PHPs session but writing to storage directly)
- PHP Writes "START" to it's session at Script end automatically (It didnt get the change by bolt before)
-> Session get's overwritten!

This happens for all session handlers, that create the same storage when used by Bolt *and* by PHP. The filesystem handler is safe as it uses different paths and filenames. I don't know about Redis, *but memcache will use same host and storage key* when used by Bolt and by the PHP session handler.

**Suggested Solution**

- **Bad but working** Disable the "import from ini" feature and provide an option to configure the memcache connection paths for Bolt inside it's own config. Then you could remove the settings from PHPs session handler and the two would no longer conflict. This solution would however still try to reinvent then wheel, provide it's own cookie mechanics and it has not lazy writes or script end handlers.

- **Good Solution** Use the session manager as it is supposed to be used and common to almost all Silex/Sf2 Apps. You create your own handlers, but access to session data still happens through PHPs native session functions. Then the custom handler is registered via `session_set_save_handler `. This has no drawbacks on security (validation still happens, just on session data and not on the mechanism to load them. There is no loss of features as the official mechanism is fully compatible with your solution and is actually the one preferred by SF2. The Handlers provided by SF2 and used by Bolt directly are actually intended to be sued like this.

**Reproduction**
You can reproduce this by configuring the same session storage for PHP and for Bolt. This is easiest with a memcache handler (They will use the same connection and storage keys automaticlly, hence the bug). But you can probably also use the filesystem handler if you set the path and filename mechanisms so Bolt will use the same files as PHP would.

In my case, you can see a Session Error message on Login. You have to logout before that though, as the conflicting sessions from Bolt and PHP sometimes make it look like you are logged in.

You can also see that your memcache server gets strange requests not routed through Bolts session management.

**Counter Test**
If you hard code the connection string to memcache inside the SessionServiceProvider and then remove the session settings from PHP, the conflicts vanish and sessions work fine again.

**Comment by GawainLynch** [comment]
ping @CarsonF

**Comment by ToBe998** [comment]
Its not a Memcache problem but affects all session handlers. It's just less common for them to generate conflicting storage targets. So, you really should solve is in general and not just for memcache.

**Comment by GawainLynch** [comment]
Yes, but session handling for normal, and Redis works … so calling all broken is a dramatic stretch :wink:

**Comment by ToBe998** [comment]
No, it sadly does not work. It is actually just luck that those do not generate conflicting session targets. They still have two session handlers running in parallel.

**Comment by CarsonF** [comment]
Why are you using native session functions? It was never intended to work side by side with native code.

**Comment by ToBe998** [comment]
No, i am not using any native code. It's pure Bolt. But PHP of course still has it's own session handler, if you use it or not.

Bolt is adding it's own session handling mechanism instead of utilizing the PHP method for custom session handlers. At the same time the native session handling is not stopped, leading to conflicts.

**In completely other news**
I also noticed that the Memcache class seems to be broken. Yea, i know that's unlikely, but that's how debugging turned out. I managed to hack your Session handler to use Memcached instead and everything seems to work now...
(cant be configured because of a bug where Bolt uses "memcache**d**" as the pimple service identifier but then still refers to it via "memcache". And configuration is still not possible directly)

**Comment by ToBe998** [comment]
Didnt test this, but if we add the following block to your `SessionServiceProvider->registerMemcacheHandler`, it should make memcachd work again, right?

```
$app['session.handler_factory.backing_memcached'] = $app->protect(
            function ($connections) {
                $memcached = new \Memcached();

                foreach ($connections as $conn) {
                    $memcached->addServer(
                        $conn['host'] ?: 'localhost',
                        $conn['port'] ?: 11211
                    );
                }

                return $memcached;
            }
        );
```

**Comment by CarsonF** [comment]
> Didnt test this, but if we add the following block to your SessionServiceProvider->registerMemcacheHandler, it should make memcachd work again, right?

Yes you are right about memcached missing it's factory, that's a major derp. I'm about to PR that now. Although I can't test either since I don't have the extension installed.

> No, i am not using any native code. It's pure Bolt. But PHP of course still has it's own session handler, if you use it or not.
> 
> Bolt is adding it's own session handling mechanism instead of utilizing the PHP method for custom session handlers. At the same time the native session handling is not stopped, leading to conflicts.

Sorry, you confused me by using "native". I'm still confused by "native session handling is not stopped". Are you registering Silex's SessionServiceProvider or something?

**Comment by ToBe998** [comment]
Cool, thanks for the memcached fix.

Regarding the session stuffz... I could not find the command `session_set_save_handler ` in any part of Bolts session management. So i assume that Bolt reads/writes it's session stuff completely on its own and into a storage that is parsed from PHPs session settings (the `session.options.import_from_ini` parameter). This is working fine on its own.

Now there is of course the normal session stuff that PHP is doing. Bolt might not use it (neither do i here), but it's still in effect as its a core function of PHP. This native session is using the same session settings which Bolt parsed and is reading/writing its own completely separate data into its storage.

In case of the filesystem hander, this is ok. PHP writes into /tmp (or whatever fits your distribution) and Bolt writes into app/cache/.sessions. probably even different file names. So, no conflicts.
In case of memcache, this is a problem since both use the same connection strings and the same memcache storage keys (we use the same config settings). This way PHP overwrites Bolt as it's registering a Destruct handler by default and writes into the same data.

PS: Im reachable via Slack if my explanation is still to bad. ;)

**Comment by CarsonF** [comment]
Yes that makes sense. Let's move this to slack anyways for speed :)

**Comment by ToBe998** [comment]
Sadly got some more updates on the issue. The new memcache/memcached factories work in theory, but there still are some showstoppers:

the PHP Extensions Memcache and Memcached use different notations for their server path#s.
- Memcache: `tcp://1.2.3.4:11211?query=options,tcp://1.2.3.4:11211?query=options`
- Memcachd: `1.2.3.4:11211,1.2.3.4:11211`

Now Bolt uses the URI parser from Symfony `GuzzleHttp\Psr7\Uri` for both kinds of connection strings. This parser however can not correctly parse a URI that does not start with a scheme section. So this failes with memcached strings.

So i think we should either make a different `safe_path`parser for each type session handler or just stop parsing the ini files alltogether since they dont work anyways.

**Comment by ToBe998** [comment]
As all of the other session handlers already have their own Bolt classes and only memcache and memcached do not have those. Would it be an option for me to just create those myself?

I could solve the "different save_path" syntax there myself and just replace the current `registerMemcacheHandler` inside the `SessionServiceProvider` with something that is more similar to the `registerFilesystemHandler` function.

Meanind, the Handler class will take care of parsing the save_path and then do what it should do. So just a small extender of the current Memcache/Memcachd classes used.

**Comment by GawainLynch** [comment]
> Would it be an option for me to just create those myself?

Potentially… thoughts @CarsonF ?

**Comment by ToBe998** [comment]
How about something like this?
https://github.com/bolt/bolt/compare/master...ToBe998:master

**Comment by GawainLynch** [comment]
The idea looks good… less in the SP the better.

**Comment by CarsonF** [comment]
Nope that's way more work than necessary. Just need to default the scheme in parseConnections

**Comment by ToBe998** [comment]
Ok, as dicussed on Slack. I think keeping the connection parsing inside separated handlers would be a cleaner idea, but i can live with whatever works. In summary, i'll try setting memcached inside the config_local.yml

This is what i tried (untedted yet, I'll update as soon as i had time):
````
session:
  connections:
    - host: 1.2.3.4
      port: 11211
    - host: 2.3.4.5
      port: 11211
```

**Comment by CarsonF** [comment]
You'll want to be sure to specify the handler. Also, port is optional and defaulted to 11211 (for memecache)

```yaml
session:
  save_handler: memcached
  connections:
    - 1.2.3.4
    - 2.3.4.5
```

**Comment by ToBe998** [comment]
Looking good. Thorough test tomorrow.

**Comment by ToBe998** [comment]
There still are some rare session invalidation errors, but they dont seem to be related to this atm. So, many thanks!
