### ISSUE TITLE
[BUG] Repeater not persisted for contenttype with some specific key

### ISSUE THREAD

**Issue by WedgeSama** [bolt/bolt#5671]
In order to work properly, the `repeater` field has to be add to a `contentype` with a alphanum key.

For exemple, if the key of a content type is `mypage`, `repeater` values will be peristed in the database and it works as expected. But if you use `my_page`, all `repeater` of this contenttype will not by persisted.

Details
-------
- Tested on Bolt versions 3.0.11 and 3.0.12.

Reproduction
--------------
- Use one of your working configuration
- Rename one of your contenttype key's with an _underscore_, _dot_ or whatever not matching `/^[a-Z][a-Z0-9]*$/` (like `my_page`)
- Update your database
- Try to add a new entry with `repeater` (same for existing one)
- Take a look at `bolt_field_value` table or reload your editing page

Solution
--------
Do not name you contenttype key's with some weird characters ^^

I can add a note to the documentation if you think its relevent.

**Comment by GawainLynch** [comment]
> Do not name you contenttype key's with some weird characters ^^

:laughing: 

Seriously though, I am 99.9% sure this is the same bug as #5601

**Comment by WedgeSama** [comment]
I dont think this is the same as #5601 (but the cause is maybe related). #5601 is about underscore in slug when using `relations`. Some errors are display to said somethink is not correct. Try the #5601 without the relation and you'll see its work like a charm.

My case is about `repeater` field. There is no error message (like #5601), just a success one for creation/edit success. It perfectly works, except the "fact" `repeater` values are not persisted in database.

**Comment by GawainLynch** [comment]
Yes, understood… I still think it is the same bug from Slugify being to aggressive on character transforms during the configuration stage that lead the storage layer to be looking for `foo-bar` and other areas using `foo_bar`

**Comment by WedgeSama** [comment]
Yes, my bad. After some more test, its seems to be the same problem. Just now, we know this bug impact also `repeater` fields.

My offer about adding a note to the documentation is still open, if you think its relevent.

**Comment by bobdenotter** [comment]
Fixed in 3.2: See #5853
