### ISSUE TITLE
[BUG] Adding a tag with a slash crashes the content in backend and frontend

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5673]
It is currently possible to add a taxonomy of type tag that includes the `/` character to a contenttype in the editor. If the contentobject is then safed, bolt will crash whenever this contentobject would be displayed.
This includes the contentobject's view on the frontend, aggregations and the backend edit view.

The crash can only be resolved by deleting the value containing that evil character from the bolt_taxonomy table manually.

**Suggested Solution**
Add a Whitelist for characters allowed in freetext taxonomies like taks.

Details
-------

 - Relevant Bolt Version: [ 3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.5 ]
 - Used web server: [ Apache ] version [ 2.4 ] Mysql
 - For UX/UI issues: [ Chrome ]

Reproduction
------------
- Open the edit view of any contenttype with a taxonomy field of type tag
- enter a value with a`/`character
- Press safe
- Reload page and/or open it on the frontend

**Comment by SahAssar** [comment]
Righto, bug confirmed, a fix is incoming.
