### ISSUE TITLE
[BUG] Buttons in custom field trigger save and return

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#5674]
When you create a custom field with a button, clicking that button triggers the save event and returns to the record over view page. 

Details
-------

 - Relevant Bolt Version: [ 3.0.12  ]
 - Install type: [  Composer install ]
 - PHP version: [ 7.0.9  ]
 - Used web server: [  Nginx 1.11.3  ]

Reproduction
------------

 1. **Bug summary**:  
when you create a custom field that has a button and the button is clicked it triggers the save and return to over view method

 2. **Steps to reproduce**:
    * add a filelist field type to a contenttype
    * add some videos to a record in the filelist type  
    * open up the filelist template and add a button underneath the file list
 4. **Expected result**:  
    * the button in this instance should capture a screenshot from the video in the video tag 
    * here is a plain html page and what is expected.  
    * ![canvas-capture-example](https://cloud.githubusercontent.com/assets/5969974/17600258/af894d98-5fd0-11e6-8bf5-3ddc99becf81.gif)

 5. **Actual result**: 
    * a button clicked does the ole "lets take you oonnnnnnnnna riiiiiiiide myyyyy friend to the over view"  
    * result in bolt dot gif  
    * ![bolt-canvas-capture-result](https://cloud.githubusercontent.com/assets/5969974/17600336/004ba456-5fd1-11e6-91ab-fb8333bbdbd8.gif)  

I also mentioned the button clicks over at the docs repo but figured since this isn't a docs thing to put it here too: https://github.com/bolt/docs/issues/468

**Comment by SahAssar** [comment]
Sorry, but is this a button like `<button>Capture</button` or have you actually given it the type like `<button type="button">Capture</button`? Cause any button that does not have a specified type is treated like `<button type="submit">` if it is inside a form. The fact that clicking the button does not perform an ajaxy save for for you seems to support that you are only missing a `type` attribute.

**Comment by cdowdy** [comment]
Well would you look at that I did not specify a type atrrib haha. When I get back to my comp I'll see if adding a type fixes it haha thanks @SahAssar

**Comment by cdowdy** [comment]
well.. I'm gonna put away my dev hat for the time being haha. it was as @SahAssar mentioned the type attrib which I left off. Thanks!

**Comment by SahAssar** [comment]
Haha, no stress, I only guessed it since I've made the same mistake myself many times :)
