### ISSUE TITLE
Select2 (omnisearch, tags, multiselects) broken in IE10 and 11

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#5676]
The omnisearch is currently broken in IE10 and IE11, probably because of upstream issues in select2.

I didn't get too far in my testing yet, but reverting select2 to 4.0.0 fixes the issue, while 4.0.1, 4.0.2 and 4.0.3 all seem broken in IE.

Edge seems to still work though.

**Comment by SahAssar** [comment]
The tag fields and searching in categoryfields with multiple: true are also broken... so basically anything that does anything even mildly complex with select2.

**Comment by bobdenotter** [comment]
Should we perhaps revert to Select2 4.0.0 for 3.1 and 3.0.x for now?

**Comment by SahAssar** [comment]
@bobdenotter we talked about that in IRC, but that might introduce other issues since a large number of issues were fixed between 4.0.0 and 4.0.3... In my testing it didn't, but we'd need a more serious cross-browser test to know for sure.

**Comment by SahAssar** [comment]
In my shallow testing everything seems to work when using 4.0.0 in IE 10 and 11. If we (ping @rarila) are okay with that solution as long as it does not break anything in other browsers I can test the rest and if it works perhaps we'll want to revert to 4.0.0 for now.

IE11 is about 4.2% usage, so it's not a disaster, but still something worth fixing.

**Comment by SahAssar** [comment]
Oh, and thanks to @Largo for finding this (he found it in bacbos/bolt-menu-editor#33)

**Comment by rarila** [comment]
We only have to follow upstream so that we can bump again when it's fixed or when IE explodes and vanishes forever under heavy lighning. — whatever happens earlier.

**Comment by bobdenotter** [comment]
Any progress on this?

**Comment by SahAssar** [comment]
@bobdenotter Well, no... Either we revert and might face bugs because of that (since it's used in quite a few places that use it differently), or we keep the current version and it's broken on IE10/11.

I'm not sure which one is more preferable, so I haven't made a PR to revert or closed this...

**Comment by GawainLynch** [comment]
OK… "*hard*" question … what do we support, browser-wise? … EoS

**Comment by SahAssar** [comment]
I think that when I asked that question a year or so ago the answer was IE10+... I think we can drop IE10 (0.3% global usage), but IE11 (4.3% global usage) might be harder to drop.

**Comment by GawainLynch** [comment]
Yeah, figured. Thanks @SahAssar

**Comment by rossriley** [comment]
I know there may well be other preeures, but I'd still be in favour of retaining IE10 support if we can. Whilst headline usage is below 1% it's not unusual to have much bigger usage in corporate networks, and that's often a target for our end-users.

**Comment by SahAssar** [comment]
Adding to that, if we are going to support IE11 it's not a huge step to support IE10, so let's drop them both when the time is right.

**Comment by GawainLynch** [comment]
@SahAssar I am closing the door on `release/3.2` today for non-critical bug fixes. So bumping this one to 3.3 which give you about another 6-8 weeks :wink:

**Comment by GawainLynch** [comment]
@SahAssar where are we at with this?

**Comment by SahAssar** [comment]
I had hoped for this to be solved upstream, but I can't even find my issue anymore, and no new version has been tagged. I say we revert to 4.0.0, I couldn't find any glaring issues in that in my quick testing.

**Comment by bobdenotter** [comment]
Sounds good to me. 👍
