### ISSUE TITLE
Uploading a files in `themes/` seems to be broken.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5678]
Uploading a file here: 

![screen shot 2016-08-12 at 16 55 31](https://cloud.githubusercontent.com/assets/1833361/17626483/b52c71e8-60ad-11e6-9ae9-42525a83b29d.png)

Gives this error: 

![screen shot 2016-08-12 at 16 55 24](https://cloud.githubusercontent.com/assets/1833361/17626495/c15b405c-60ad-11e6-9182-8b0aadde6225.png)

**Comment by bobdenotter** [comment]
And while i'm digging around that part of the codebase, I might as well fix this visual niggle too: 

![screen shot 2016-08-12 at 17 19 41](https://cloud.githubusercontent.com/assets/1833361/17627341/378efebe-60b1-11e6-95a8-a2f7859a0259.png)

**Comment by GawainLynch** [comment]
:lollipop: for some sorting on that mess :laughing:
