### ISSUE TITLE
[bug] Certain backend jQuery uses broken on 3.1.0-beta2

### ISSUE THREAD

**Issue by rogeriomarques** [bolt/bolt#5685]
Using the stock imagelist field on 3.1.0-beta2, the backend UI for this kind of field may to be broken. Clicking "Select from server"does nothing, not even a popup. 

JS console output:

`lib.js?30f21afc74:24 Uncaught The editor instance "html" is already attached to the provided element.`

**Comment by GawainLynch** [comment]
Confirmed here.

Rolled back the jQuery constraint to `~2.4` ran `grunt updateLib` and the problem disappeared.

**Comment by GawainLynch** [comment]
Seems to also affect all jQuery handled buttons, and things like Select2 …

![image](https://cloud.githubusercontent.com/assets/1427081/17676125/4ac9f406-632d-11e6-8fe9-b69583591c5d.png)

Renaming this for incoming serch-i-ness :laughing:

**Comment by rogeriomarques** [comment]
This issue touches the db too.

Using a 3.0 generated db with records containing properly formed imagelist fields, editing any field of this record on 3.1.0-beta2 (say, the title) and saving the record messes up the original db imagelist field.

**Comment by rogeriomarques** [comment]
On further investigation...

After reading #5671, I noted that all my contenttypes had underscores in their names.

Renamed them all, sans underscores, just plain ascii, and suddenly everything works as expected.

**Comment by bobdenotter** [comment]
@GawainLynch Check, i'll roll back. Jquery to the latest 2.2.x version.

@rogeriomarques Seems like your issue is related to #5601 as well, rather than this one. It's on our list of things to tackle!

**Comment by SahAssar** [comment]
Fixed in #5687
