### ISSUE TITLE
New exception handling templates need UI love

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5690]
![image](https://cloud.githubusercontent.com/assets/1427081/17736355/a902718c-6487-11e6-87a1-cd1f5c77c320.png)

**Comment by bobdenotter** [comment]
Work in progress: 

![screen shot 2016-09-08 at 18 07 27](https://cloud.githubusercontent.com/assets/1833361/18356932/26b29788-75ef-11e6-9a61-35eca1a2f2bf.png)

**Comment by GawainLynch** [comment]
McAwesome :+1:

**Comment by GawainLynch** [comment]
I am not seeing wrapping on the message, and the profiler is now failing to load on this route (not sure if related).

![image](https://cloud.githubusercontent.com/assets/1427081/18408516/2d30ac50-7732-11e6-9a09-dd6177111c34.png)

**Comment by bobdenotter** [comment]
Fixed in #5828
