### ISSUE TITLE
[BUG] nut copied instead symlinked

### ISSUE THREAD

**Issue by gander** [bolt/bolt#5694]
`vendor/bolt/bolt/app/nut` is copied into `vendor/bin` and `app` instead symlinked, so trying to run `nut` results by exception:
`Fatal error: require(): Failed opening required '/www/bolt.dev/app/bootstrap.php' (include_path='.:/usr/local/lib/php') in /www/bolt.dev/app/nut on line 14`

`app/bootstrap.php` exists only in `vendor/bolt/bolt/app`.

Details
-------

 - Relevant Bolt Version: 3.0.12
 - Install type: Zip install
 - PHP version: 5.6
 - Used web server: Apache

**Comment by bobdenotter** [comment]
Which OS / Filesystem is this on?

**Comment by GawainLynch** [comment]
@bobdenotter it is the zip file …` tar.gz` is fine

**Comment by bobdenotter** [comment]
Maybe it's because `.zip` doesn't really support symlinks?

**Comment by GawainLynch** [comment]
This works for me https://github.com/bolt/bolt-distribution/commit/35bd3305e704730bfcfcee516c50fe57465df4d8

**Comment by bobdenotter** [comment]
That looks sensible. 👍

**Comment by gander** [comment]
OS: Ubuntu 16.04

**Comment by bobdenotter** [comment]
We'll release Bolt 3.1.0 tonight, which comes with a fix for this. Closing. :-)
