### ISSUE TITLE
Login seems to be case-sensitive

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5695]
Details
-------

 - Relevant Bolt Version: [ 3.0.12 ]

Reproduction
------------

 - Use an admin user to create a new user 'test', with a straightforward password.
 - Open an incognito window, go to the log in page
 - Try loggin on with user 'Test' (note the capital 'T') and the chosen password.
 - See the `Your account is disabled. Sorry about that.` notice. 

See screenshot: 

![screen_shot_2016-08-19_at_14_20_10](https://cloud.githubusercontent.com/assets/1833361/17809810/5a9baf34-6619-11e6-9cc4-0916298d4b81.png)

**Comment by GawainLynch** [comment]
IMHO it should be.

**Comment by bobdenotter** [comment]
No, it very much shouldn't be case-sensitive. It'll cause _so_ much headaches for people on mobile platforms. In the 'Username' input browsers tend to be 'helpful', and won't allow you to type 'mike' instead of 'Mike'. If only 'mike' would be accepted, logging in becomes very, very cumbersome.

Also, It's been case insensitive on purpose for years, so i think this should be treated as a regression.

**Comment by bobdenotter** [comment]
Another thing that's inconsistent right now, it that if you create a user 'Mike' right now, it'll be stored in the db as 'mike', meaning you _have_ to log in with 'mike', and you can't log in with 'Mike'.

**Comment by GawainLynch** [comment]
> Also, It's been case insensitive on purpose for years, so I think this should be treated as a regression.

Given it has behaved this way for the last year, I would call it **not** a regression, rather a break between major versions :smile: 


> Another thing that's inconsistent right now, it that if you create a user 'Mike' right now, it'll be stored in the db as 'mike', meaning you have to log in with 'mike', and you can't log in with 'Mike'.

Well, the database value should be consistent with a standard, i.e. if you compare lower, store lower.

**Comment by bobdenotter** [comment]
> Well, the database value should be consistent with a standard, i.e. if you compare lower, store lower.

Agreed, and that is exactly what I want to achieve, because that's not the case right now.

**Comment by bobdenotter** [comment]
Oh, and finally: The message 'Your account is disabled. Sorry about that.' is wrong, because that's not the case. It happens when you use the wrong case. :-)

**Comment by ToBe998** [comment]
You should always only get a very generic login failed message. The same for every possible cause. If you give more info on the real cause, like "your password was wrong" or "your username was not found", you would introduce a security leak.

Good authentication pages never give any more details other than "Username or password was wrong". The only possible exception could be if username and password was both valid but the account was locked on purpose, but even that is debatable. ;)

**Comment by bobdenotter** [comment]
> The only possible exception could be if username and password was both valid but the account was locked on purpose. 

That is exactly what we have. ;-)

**Comment by ToBe998** [comment]
oh, i thought the current mechanic, currently being case sensitive, resolves the described issue as a username not found. Just ignore me if not.

**Comment by GawainLynch** [comment]
> Oh, and finally: The message 'Your account is disabled. Sorry about that.' is wrong, because that's not the case. It happens when you use the wrong case.

That is the one that we've always defaulted to as the "catch all" … if we check for case or not it is irrelevant. If they system doesn't find the user name (due to case, or otherwise) it should act as if it was there, otherwise we have a serious information leak.

**Comment by bobdenotter** [comment]
> That is the one that we've always defaulted to as the "catch all" …

I think that the "Username or password not correct. Please check your input." would be more appropriate there.. I've made a tiny PR for this, open to criticism: #5697
