### ISSUE TITLE
Exception being thrown on new installation Template "index.twig" is not defined.

### ISSUE THREAD

**Issue by chrissound** [bolt/bolt#5699]
I'm using the following bash script to deploy:
```bash
pwd=`pwd`

cd ${pwd}
if [ ! -f bolt-latest.zip ]; then
    curl -O https://bolt.cm/distribution/bolt-latest.zip
fi

if [ ! -d data ]; then
    mkdir data
fi

unzip bolt-latest.zip -d data
mv data/bolt-3.0.12/* data/
rm -rf data/bolt-3.0.12/

cd ${pwd}

cd ${pwd}/data
chmod 777 -R ${pwd}/data
```

![2016-08-21-18 49 04](https://cloud.githubusercontent.com/assets/1499652/17838887/00fb6678-67d0-11e6-94e4-82ebe0e0f4ac.png)

**Comment by GawainLynch** [comment]
You're not copying over the dot files, only deleting them.

**Comment by chrissound** [comment]
Thank you! That has solved it!

**Comment by GawainLynch** [comment]
Sounds very much like the kinda thing I do all the time, so the answer was close at hand :wink:
