### ISSUE TITLE
[BUG] Contenttype translation updates automatically any time

### ISSUE THREAD

**Issue by sibputnik** [bolt/bolt#5703]
Bolt uses auto-created translation for contenttypes in backend any time. When I go to "translation-contenttypes" I have newly created app/resources/translations/ru/contenttypes.ru.yml any time.
What I done:
- Set ru_Ru or Ru localce.
- Add new contenttypes.
- Update database

And now I can refresh contenttypes translatin page and have new generates translation each time. I can change contenttypes.ru.yml by external editor or in Bolt backend, but it not give any changes - contenttype options in backend is still without translation.

Each time I open contenttypes.ru.yml, I see new creation time in first line (e.g. # app/resources/translations/en_GB/contenttypes.ru.yml – generated on **2016-08-24 15:44:53** Europe/Moscow)

I can change contenttypes.entries.text.\* or  contenttypes.showcases values and it saves. But if I change translation for my contenttype, it not saves,

I set locale to en_Gb and have same problem.
My contenttypes works correctly in backend and frontend (templates).
## Details
- Relevant Bolt Version: 3.0.12
- Install type: Zip/tarball install
- PHP version: 5.6-x64
- Used web server: Apache 2.4-x64

**Comment by sibputnik** [comment]
hey! Can anybody fix this?

**Comment by sibputnik** [comment]
heeeeeeeeeeeey!!!

**Comment by GawainLynch** [comment]
Those translations are currently distributed by Bolt, as that part of the translations is not quote finished.

**Comment by sibputnik** [comment]
Can I disable translation auto-generation? I need my translation for contenttypes

**Comment by bobdenotter** [comment]
Hi,

No, you cannot do that currently.. If you really wish to prevent Bolt from updating the files, you should edit them in an external editor.

**Comment by rarila** [comment]
@sibputnik I don’t know what’s goes wrong on your side but it absolutely should work.

The date you see in the editor is always a new date as it is the date the file is generated and not the date the file is written. When opening the translation page the file is read, data extracted, **missing** translations get added, translations get sorted by category. So no user edited translations are overwritten. Could it be that your translations won’t be actually saved at all?

(Btw, removing access rights to that file sends us to the debbugger with an ``ContextErrorException``, but that’s another problem then:-)

**Comment by sibputnik** [comment]
bobdenotter, I edit translation in external editor, but it recreates each time

**Comment by rarila** [comment]
@sibputnik You mean ``contenttypes.ru.yml`` gets overwritten automatically by just being in backend?

**Comment by sibputnik** [comment]
In russian not all can be auto-translated by flat logic, so after auto-translation I need correct it by hands.

**Comment by rarila** [comment]
@sibputnik Could it be that you didn’t remove the comment sign ``#`` from the edited translation?

**Comment by GawainLynch** [comment]
Just a note, Russian is one of the great examples of why we need to look very seriously at how we're (not properly) using Symfony's translation component … Apparently, Russian isn't very forgiving as a language in this way :smile:

**Comment by sibputnik** [comment]
@rarila where I need to remove # ?

**Comment by GawainLynch** [comment]
Automatic translation of ContentTypes was removed in #6802 and it is now possible to specify site specific translation files. This will land in a stable release in the coming days when 3.3.0 is tagged.
