### ISSUE TITLE
[BUG] Clicking the Preview button leads to duplicated entries (sometimes)

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5706]
Sometimes the Preview button acts a bit weird. Right now, when I was writing a new newsitem for bolt.cm, the Preview button (sometimes) opened the newsitem listing in the backend with the successfully saved message. Clicking the Preview button again led me to the preview page.

After I finished the newsitem, the record was there multiple times with different states of the text. 

I can't say how to reproduce this because it seems to appear randomly. 
As a side note, I didn't save the newsitem on my own while writing it. 

I guess it's something with the button listeners on the editcontent page where the save function is triggered instead of the preview function.
## Details
- Relevant Bolt Version: 3.0.11
- Install type: composer
- PHP version: 7.0 (i guess)
- Used web server: nginx
- For UX/UI issues: chrome 52.something

**Comment by SahAssar** [comment]
Can't reproduce in 3.2.7, if it's still there please reopen the issue! :)
