### ISSUE TITLE
[BUG] Incorrect ownerid when no user is authenticated

### ISSUE THREAD

**Issue by dhargitai** [bolt/bolt#5707]
I tried to log some information of a POST request through the `logger.system` in one of my controllers.
When there is no user information in the session, the `ownerid` parameter is set to `''` (empty string) in src/Logger/Handler/SystemHandler.php:99
This is causing an exception when the PDOStatement tried to execute the insert query, because the table definition says that `ownerid` can be a valid integer or NULL.

The exception is: `SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'ownerid' at row 1` and it is thrown in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91

Details
-------

 - Relevant Bolt Version: 2.2 (2.2.23)
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Nginx version 1.8.0

Reproduction
------------

Create a new HTTP endpoint in an extension, and try to log anything into the system log without authenticating the actual user. The `ownerid` parameter will be '' and nothing will be logged.

**Comment by GawainLynch** [comment]
What database engine are you running?

**Comment by dhargitai** [comment]
I'm using MySQL 5.7.13

Fix for the issue: https://github.com/dhargitai/bolt/pull/1

**Comment by GawainLynch** [comment]
> Fix for the issue: dhargitai#1

Cool, just commented there too … you can PR it against here and we can review/merge/party :smile:

**Comment by dhargitai** [comment]
Thanks for pointing it out :)
https://github.com/bolt/bolt/pull/5708

**Comment by SahAssar** [comment]
Fixed in #5708, right? Closing, please feel free to reopen if I'm wrong!
