### ISSUE TITLE
[BUG] Modifying ContentType to have Repeater Field produces error on existing records

### ISSUE THREAD

**Issue by Jovinsson** [bolt/bolt#5709]
I found an issue whereby if you modify and existing ContentType to have a repeater field it will then cause the following errors to appear at the top of the dashboard when you open an existing record. Note: this does not happen for new records, OR, records that have been saved again after the modification:

`Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\bolt\vendor\bolt\bolt\src\Storage\Mapping\MetadataDriver.php on line 232`

`Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\bolt\vendor\bolt\bolt\src\Storage\Mapping\MetadataDriver.php on line 232`
## Details
- Relevant Bolt Version: 3.0.12
- Install type: Zip install
- PHP version: 5.5
- Used web server: xampp stack using Apache
- For UX/UI issues: Chrome v44
## Reproduction

​
1. **Bug summary**: 
   - Modifying an existing contenttype to have a repeater field causes existing records to produce an error when modifying the record
2. **Specifics**:
   - This occurs when you open an existing record in a contenttype that has been modified to have a repeater field (when it previously did not), OR, modified to have an additional repeater field
   - Does not occur once you have saved the existing record after modifying the contenttype
   - Does not occur for new records after modifying the contenttype
3. **Steps to reproduce**:
   - Create a new contenttype
   - Populate a record into the contenttype
   - Modify the contenttype to have a new repeaterfield
   - Open the existing record, the error appears at the time
4. **Expected result**: 
   - Would open without error allowing modification of the record
5. **Actual result**: 
   - Opened successfully, however with error dumped at top of the screen
   - Could still modify and save the record successfully
6. **Workaround**:
   - Save the existing record (with or without the new information)

![repeater error](https://cloud.githubusercontent.com/assets/5206571/17997946/54dc5cde-6ba4-11e6-80fa-9d880ce8c203.png)

**Comment by SahAssar** [comment]
Hmm, I'm not seeing this anymore, seems to have been fixed in the meantime, I'm closing, but if it reappears please reopen!
