### ISSUE TITLE
[UI] File types arrow's position is messed up

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#5715]
On 3.1
![screen shot 2016-08-29 at 4 24 01 pm](https://cloud.githubusercontent.com/assets/932566/18068038/1bdfb4ae-6e05-11e6-9de4-0793498087d2.png)

**Comment by GawainLynch** [comment]
@bobdenotter this looks like the job for super :hamster:

**Comment by bobdenotter** [comment]
removing "low hanging" label, because i spent to much f'ing time on this already. :-/
