### ISSUE TITLE
"ScriptHandler::installAssets" takes a _long_ time on sites with a large `public/files/` folder

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5719]
Bumped into this the other day: A site with a large `public/files/` folder (several dozen `.jpgs` of 4 - 6 mb each) takes a long time for the `ScriptHandler::installAssets` part of the install / update procedure. 

Eventually it craps out on a random line in our EXIF library, seemingly indicating that the folder is crawled, while there's no apparent need for it. 

Needs verification, though. 
## Details
- Relevant Bolt Version: [ 3.1 ]
- Install type: [ Composer install ]

**Comment by CarsonF** [comment]
I can look into this

**Comment by GawainLynch** [comment]
Assigning to you then, @CarsonF if you can before "you know what" :wink:

**Comment by nbehier** [comment]
@CarsonF @GawainLynch What are you planning ? You're teasing us ! Not cool ;)

**Comment by GawainLynch** [comment]
Well, I am pretty sure I know why… so if @CarsonF doesn't have time this week, I'll get it next week when I am off the island. :smile:

**Comment by CarsonF** [comment]
@nbehier I'm getting married this weekend 💪  👫   🎉 

I'll probably just point @GawainLynch to the problem if I find it so he can fix it lol

**Comment by GawainLynch** [comment]
The problem is :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: 

In other news, we now have drop bear emoji on Slack :laughing:

**Comment by nbehier** [comment]
@CarsonF I don't want to say it too soon… but hope you'll have one of your best weekend ;-)

**Comment by GawainLynch** [comment]
Nudge @CarsonF

**Comment by GawainLynch** [comment]
Given he six months since this was seen, I'm retiring this… I ma pretty sure this was due to massive `app/cache/profiler/` directories from long running `debug: true` settings … we both know where the "Reopen" button is if I am wrong … not an unusual occurrence :smile
