### ISSUE TITLE
"Index.twig is not defined" or ".htaccess doesn't exist" when `.bolt.yml` is missing..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5720]
This issue popped up a few times last week, mostly for people using the `.zip` file, and uploading files manually. 

When the `.bolt.yml` file is left out, you get this error, that's unrelated at first. This happens often, because the file is 'hidden'. 

We should eitheradd a gracefull fallback, or better error reporting for this, I think. 
## Details
- Relevant Bolt Version: [ 3.1 ]
- Install type: [ Zip/tarball install ]

**Comment by PhillippOhlandt** [comment]
I think it's good to output something like "Could not find index.twig. Check your paths and make sure .bolt.yml exists."

**Comment by bobdenotter** [comment]
This is the same issue as #5729

**Comment by GawainLynch** [comment]
As discussed on Slack, sending to the land of closed issues :wave:
