### ISSUE TITLE
[BUG] Time publish events have been removed

### ISSUE THREAD

**Issue by pbnPierre** [bolt/bolt#5721]
I am working on bolt upgrade from 2,2 to 3,1 and i have this fatal error
Undefined class constant 'TIMED_PUBLISH'
Theses storage events have been removed ( probably in https://github.com/bolt/bolt/pull/2664 )
## Details
- Relevant Bolt Version: 3.1
- Install type: Composer install 
- PHP version: 5.6
- Used web server: Apache

**Comment by pbnPierre** [comment]
They are still sended by 
` 
    private function timedHandleRecords($contenttypeSlug, $type)
    {
       ...
        try {
            foreach ($recordIds as $recordId) {
                $content = $this->getContent($contenttypeSlug . '/' . $recordId['id'], ['hydrate' => false, 'returnsingle' => true]);

                $event = new StorageEvent($content, ['contenttype' => $contenttypeSlug, 'create' => false]);
                $this->app['dispatcher']->dispatch("timed.$type", $event);
            }
        } catch (\Exception $e) {
            $this->app['logger.system']->critical("Dispatch handling failed for $contenttypeSlug.", ['event' => 'exception', 'exception' => $e]);
        }
    }`

As a hotfix I will not use class constant

**Comment by SahAssar** [comment]
Closing since this seems to have been a 2.2 way of doing things erroring on 3.X, which is to be expected. If that is not the case please reopen!
