### ISSUE TITLE
[BUG] [3.2 Branch] Disabling Apache Checks Ignored

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#5724]
This is one that's crept in with the new config validation classes.

If you want to disable Apache checks we allowed this call before:
`$configuration->getVerifier()->disableApacheChecks();`

Reproduction
------------
​
Make any custom configuration, eg using `.bolt.php`, add the call `$configuration->getVerifier()->disableApacheChecks();`

Delete `public/.htaccess` and run Bolt as normal.

Following exception is thrown:
![screen shot 2016-08-31 at 21 14 32](https://cloud.githubusercontent.com/assets/5082/18144719/f481aa7c-6fbf-11e6-89e8-c1c3d3270576.png)

**Comment by SahAssar** [comment]
Fixed in #5728
