### ISSUE TITLE
[BUG] having datefield as required in contenttypes produces 'Field "": ...' error message

### ISSUE THREAD

**Issue by mikenosko** [bolt/bolt#5730]
I've added a `required: true` to my date field and as there is a js to duplicate the input to allow for date picker it seems to loose the name of it and the error message at the top after submitting  displays as:

<img width="361" alt="screen shot 2016-09-05 at 15 10 27" src="https://cloud.githubusercontent.com/assets/49306/18250356/077b5ca4-737b-11e6-97e8-16c7be27a89b.png">
## Details
- Relevant Bolt Version: [ custom 2.2 | 3.0 | 3.1 ]
- Install type: Composer install
- PHP version: 7.0
- Used web server: Apache
## Reproduction

​

```
event:
    ...
    fields:
        ...
        date:
            type: date
            required: true
    ....
```

**Comment by SahAssar** [comment]
Can't repro in 3.2.7, assuming fixed, Please reopen if you are still seeing it!
