### ISSUE TITLE
[BUG] $resources->verify() doesn't show error warning

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5732]
I'm deploying new project, i haven't granted chmod to config folder.
Bolt doesn't show an error and crashes on `$resources->verify()` [this line](https://github.com/bolt/bolt/blob/release/3.1/app/bootstrap.php#L117) in `app\bootstrap.php`.
I thought it has to show some error.
Had to wrap it to try/catch to catch the error. Bug verification needed. If i'm doing something wrong - tell me please, and close this issue.
_(using v 3.1)_

**Comment by GawainLynch** [comment]
If you are getting that far, the exception object you're catching will contain the data you need to know.

**Comment by Boorj** [comment]
yes, of course, the problem was in not changed chmod for config folder. But shouldn't it be shown as message to user?

**Comment by SahAssar** [comment]
Closing since we state what the FS write requirements for the folders are in the docs and IIRC we show better error messages now (but that might just be me misremembering). 

Anyway, feel free to reopen for further discussion :)
