### ISSUE TITLE
Media / image / asset / file management

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#574]
OHAI.

Just gave it a thought: 

While  `image` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' defines my MySQL Contenttype "image" field, I think with an upgrade to TEXT we could do awesome shit here:

The modern web whants us to provide Title and Alt stuff to every media we set into a web page. With maybe a JSON declaration we could pump in informations to every image the web whants us to provide anyway, and not only the image path. Within the frontend we could simply display smaller thumbnails with an extra input field. This will be the easier part.

Edit: Imagine: Fancy post-modern media markup like google / http://schema.org/ ....

Whats your thoughts on this topic?

**Comment by bobdenotter** [comment]
Pinging @silentworks 

As pointed out by Andrew, this one in [Roadiz](http://roadiz.io) looks nice: 

 - http://static.roadiz.io/files/e9eb6b90/home_carrousel08.jpg
 - http://static.roadiz.io/files/f13230e6/home_carrousel03.jpg

**Comment by SahAssar** [comment]
Okay, I'm changing this to a General discussion for media management and consolidating #3784 and  #3778  here. If anyone has any objections let me know :)

**Comment by SahAssar** [comment]
"Moved" #2232 and #3025 here.

**Comment by SahAssar** [comment]
Moving this to the new [forums](https://discuss.bolt.cm/d/10-media-image-asset-file-management-continuation-of-574).

**Comment by SahAssar** [comment]
Per the dev meeting on 2016-01-05 (see github wiki for transcript) I will be moving some stuff back to github, among them this RFC. While the forums should still be used for "unbaked" RFC's, for ones that are actionable github is better suited.

**Comment by SahAssar** [comment]
Closing for now. When there is time for someone who needs it I'm guessing it will get done, but having this issue open isn't helping anyone. If anyone is willing to work on it please contact a core dev and we can coordinate someone to help out with it.
