### ISSUE TITLE
[BUG] With IP address paths, Chrome is causing Bolt to go into a login loop

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#5746]
It appears there is some sort of incompatibility between Bolt and Chrome in certain scenarios. On both my local development machines, as well on a server at work, I'm unable to log into Bolt via Chrome.

However, using Firefox and IE are fine. They log in and operate normally.

Details
-------

 - Relevant Bolt Version: 3.0+
 - Install type: Composer install (without create-project)
 - PHP version: 5.6
 - Used web server: apache

Reproduction
------------
1: Create new instance of Bolt.
2: To to /bolt
3: Fill in "userfirst" form
4: Stuck in a loop

1: Complete first user in Firefox.
2: Attempt to log in with Chrome
3: Unable to login, redirected back to login page.

**Comment by bobdenotter** [comment]
Never seen this. Could you try using an incognito window, To rule out extensions like adblocker?

**Comment by Maelstromeous** [comment]
Tried it in incognito mode, cleared cache, cleared cookies, restarted the browser, nothing worked :-/

I wonder if it's something to do with CSRF tokens, I was told they're far more strict in webkit.

**Comment by Maelstromeous** [comment]
One way to repro this is to install Vagrant and use the scotchbox.io vagrantfile. That way you exactly have my setup.

Although at this point I won't rule out environment configs. I'm about to deploy my project on a proper web server, I'll feed back if it works on there.

**Comment by Maelstromeous** [comment]
It does seem to be fine on the live server.

**Comment by bobdenotter** [comment]
@Maelstromeous So, should we consider this a fluke and close it, until somebody else bumps into it again?

**Comment by Maelstromeous** [comment]
Not entirely sure to be frank, it's happened on multiple environments
across multiple machines, and I've only encountered such issues with Bolt.
When logging in does built do any external calls outside of the application?

**Comment by bobdenotter** [comment]
That shouldn't be the case.  

I'm not sure what to do about this, then.. I don't doubt you had an issue with this, but without a way to reproduce, it's not very "actionable" so far.

**Comment by Maelstromeous** [comment]
Yeah I understand, I wouldn't blame you if you flagged it as unreproducible.

I can't think of ways to diagnose it I'm afraid, it only happens in Chrome,
and only in certain circumstances. It's not a VM thing, as it's doing the
same on my work's staging server, which is a full blown linux box. It's
very hard to track down.

For now the workaround is simply to use Firefox, but still, it's something
about webkit (as it does it in Safari also) that's causing the issue.

-
Kind Regards,

Matt Cavanagh

**Comment by SahAssar** [comment]
Perhaps I'm stating the obvious, but if you check/dump app['request'] for the login post, do you see any differences between FF and chrome? What are the cookie settings in your config.yml?

**Comment by Maelstromeous** [comment]
Will check tomorrow at work so I can get you the environments I was getting the issue in.

**Comment by Maelstromeous** [comment]
Upon investigation in tandem with @SahAssar, we've come to the conclusion that Chrome's policy on cookie storage for IP based paths is causing this issue. 

Basically, Bolt is rightfully assigning a session and a cookie to the user, however on Chrome's end, that cookie is being discarded, therefore causing Bolt to redirect the user to the login page, and cause a loop.

Tested this by using both a virtual host (e.g. `dev.somesite`) and just a standard `192.168.60.10/public/somesite/bolt` path.

The `dev.somesite` virtual host worked fine, no issues when logging in with Chrome or any other browser. However, with the IP based one, non-webkit browsers such as Firefox logged in successfully, but Chrome does not

I suggest we make a note of this in the documentation somewhere so that others who encounter this won't scratch their heads like I was.

**Comment by Maelstromeous** [comment]
Looking into this further, if Chrome was to blame, it would mean that any sessions wouldn't work on any sites. I've only encountered this issue with Bolt, any other website I have with an IP range works fine with sessions.

**Comment by GawainLynch** [comment]
Probably should have flagged this earlier … but everyone got in and it was closed…

I am really not sure this is something we *should* change… our session & authentication cookies are tied to a domain name … and in some of our larger use cases we have single IP servers with literally hundreds of Bolt sites on them.

Here's the crunch…

Some browser to accept and store IP based cookies — to my knowledge not all — but browsers like Chrome will refuse to return it to you. If they did … oh my … it would prove a massive security hole, roughly the size of Australia :smile: 

i.e. If you set a `bolt_authtoken_abc123` cookie for `.example.com` (note the leading dot), that will be send by your web browser for visits to `example.com`, `bolt.example.com`, or `nuts.bolt.example.com`. 

…but an IP range like  `.n.n`, or just `n.n.n.n`… The first would match that whole CDIR, whereas the second would give you access to every Bolt site on that IP address.

So if your clients want any forensic security investigation done, I'll email you my hourly rate :wink:

**Comment by Maelstromeous** [comment]
Fair explanation! We certainly wouldn't want gaping holes in security ;-)
