### ISSUE TITLE
[RFC] Improving the installation procedure for Frontend Developers.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5752]
Currently, our install procedure has a few points that need significant improvements in order to be "workable" for Frontend developers. 

There are too many steps where specific backend-knowledge is required in order to get stuff working. These will lead people to get confused, and bail. Below I've noted some "painpoints" i've seen people struggle with. You might agree or not, but these are real findings that FE devs have and told me about. 
- People install Bolt using an SQLite database, instead of MySQL, because they don't see the big blue box warning them that they're going to do so. 
- The packaged version comes with a "broken" .gitignore. Half the stuff they need in their own repo's will never get in there. 
- They misplace the `.bolt.yml` file.
- "Why do I need to go to the install page first, before I can edit the config?" / "Where are the `config.yml.dist` files?"
- "What's the use of putting all files outside of the webroot? All it does it complicate stuff."
- The docs say "Generally most servers should be fine with the default permissions", causing people to skip them. They think "My server is definitely 'most servers', so this does not apply to me.". Even if the process breaks down in the next step, they will not realise it's because they've skipped this step. 

Note: These are _not_ my opinions per se. These are things I've found other people struggling with.

Some of these will require better docs, some will require fixes in the packaging procedure, and some will require core changes in Bolt. 
Most of these things we can answer by saying "They should read better" or "They should learn to devops", but the truth is that they will not. 
Or at least, they will not do so because we tell them to. It's up to us to improve these things, or these people _will_ choose to drop Bolt, and use something else instead. In my opinion it's absolutely crucial that we improve these things, if we wish to grow the adoption of Bolt. 

Things that need improvement:  
- The `.gitignore` that comes with the `.tgz` and `.zip` files is not right for them. We need to ship with file that suits their workflow better. 
- We need a complete "How to set up bolt for development and shove it into git and deploy later" guide. All of these things are documented in various places, but the overview is missing.
- We need to "unhide" `.bolt.yml` (This is in progress! Yay!)
- We need to prevent "White screens of death" (Also in progress, yay!)
- We should ship with the `.yml.dist` files in the `app/config/` folder.
- We should (somehow) make it possible to start editing the `config.yml` file _before_ we've first shown the "Set up the first user" screen.

**Comment by GawainLynch** [comment]
> We should ship with the .yml.dist files in the app/config/ folder

No, just no. We're about to completely gut them down to minimal anyway.

> We should (somehow) make it possible to start editing the config.yml file before we've first shown the "Set up the first user" screen.

Any `nut` command should do. We load and boot the application, sadly, in the console application. That presently should trigger loading of the config.

**Comment by bobdenotter** [comment]
> Any nut command should do. 

I like that idea. We could perhaps even make a `nut setup` command that does this and other things, and include it as the third step in the simple install procedure: 

```
curl -O https://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
php app/nut setup
```

**Comment by GawainLynch** [comment]
Oh, I mean that running any nut command *currently* has that effect … not sure if I can still read at this time of night.

One point that just popped back in my mind about the `.dist` thing, is that we want to try to funnel people to easy to find & navigate documentation sources that are "rich". They're really an application resource that we want to keep the ability to tweak as needed in its at-hand form.

> … as the third step in the simple install procedure:

Yeah bout what about my ongoing nag:

```
$ php -r "copy('https://bolt.cm/installer', 'bolt-setup.php');"
$ php bolt-setup.php

  Downloading Bolt 3.2.2 ........ [OK]
  Unpacking download ............ [OK]
  Running configuration tasks ... [OK]

Installation complete! May the Koala be with you!
```

**Comment by bobdenotter** [comment]
> php -r "copy('https://bolt.cm/installer', 'bolt-setup.php');"

Sounds good at first glance, but the composer people used to do something similar until recently, an have moved away from it. Don't know why though. 

> Running configuration tasks ... [OK]

Yes, but this could easily be a `nut setup` as well, right? :-)

**Comment by SahAssar** [comment]
> People install Bolt using an SQLite database, instead of MySQL, because they don't see the big blue box warning them that they're going to do so.

Question: Is it bad because they expected to use MySQL? Cause for a lot of frontenders I've talked to this has been a big plus for bolt.

**Comment by bobdenotter** [comment]
> Question: Is it bad because they expected to use MySQL? Cause for a lot of frontenders I've talked to this has been a big plus for bolt.

It's "unexpected", and therefore "bad". I wish I was making this up. :-/

**Comment by SahAssar** [comment]
Well, that feels like one of those marketing questions where we should headline it with "Database built in!" or whatever and have a tab that says "configure custom database" that writes the credentials input to the config.yml.

I seriously don't think most people want to use MySQL, but they get used to it being required by any CMS they try. But I might be wrong.

**Comment by bobdenotter** [comment]
@SahAssar I don't know what's "correct", but the problem lies in not providing the choice, as you say.. Thing is, you can't make any choices _before_ going to the 'first user' screen, currently. I'm leaning towards fixing that by incorporating a 'app/nut setup' step.

**Comment by GawainLynch** [comment]
>> php -r "copy('https://bolt.cm/installer', 'bolt-setup.php');"

> Sounds good at first glance, but the composer people used to do something similar until recently, an have moved away from it. Don't know why though. 

No, that's what they moved **to**. 

The change they made was to not pipe the output of cURL directly into `php-cli` as it is a security nightmare.

>> Running configuration tasks ... [OK]

> Yes, but this could easily be a `nut setup` as well, right? :-)

So nut will magically be there? 

No the point is these people are having trouble installing… because they don't know fundamentals that anyone should be across to work in a technical environment, but I digress.

So what I am proposing in that is a simple way to get executing code that can download and install for them, as they otherwise can't manage it themselves.

**Comment by Wartybliggens** [comment]
One thing I would like to add: 
After a fresh install, there is often a Twig error screen the first time you go to the admin section. A refresh fixes it, but that's not a good thing for a newbie to see.

**Comment by bobdenotter** [comment]
@Wartybliggens Is that the case? I'm not familiar with that. Can you post a screenshot, and details of how you got that?

**Comment by Wartybliggens** [comment]
@bobdenotter - I guess I take that back. I tried a fresh install locally with MAMP and the twig error didn't happen. Perhaps what I was seeing had to do with the whole Docker container setup I've been doing, which built off the composer.json etc.

**Comment by GawainLynch** [comment]
Covered with https://github.com/bolt/installer
