### ISSUE TITLE
[BUG] HTML deleted in textarea fields

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#5753]
If yo use 'textarea' fields to store embedcodes and such (like I do often), Bolt 3.1.1 is now deleting that code from the field.

Reproduction:
Paste an embedcode (soundcloud, youtube, whatever) in a textarea field
Save the item
Refresh the item page
Aaaand... It's gone... :)

This used to work fine before updating to 3.1.1.

**Comment by GawainLynch** [comment]
Confirmed … we were having the same issue on bolt.cm when we updated that to 3.3.1 and definitely is unique to 3.1.x

**Comment by rossriley** [comment]
Is this related to #5611 I'd guess the embed tags would need to be added to the allowed list now for that content not to be cleaned.

**Comment by GawainLynch** [comment]
Yeah, that is what @bobdenotter was hinting at too … :watch:

**Comment by bobdenotter** [comment]
@peterboorsma Content gets passed through a filter now, for added security. Make sure the `iframe`, `width` and `height` are allowed.. 

in config.yml: 

```
    allowed_tags: [ iframe, ... ]
    allowed_attributes: [ width, height, ... ]
```

**Comment by peterboorsma** [comment]
Ah ok. :/ I add them to the htmlcleaner in config.yml

The fun thing is, it cleans up embedcodes now because it still deletes stuff like:
scrolling="no" frameborder="no"
(Because I didn't add scrolling, frameborder to the list).

Tnx!

**Comment by bobdenotter** [comment]
Thanks, I'm making a PR, and i'll include `frameborder` and `allowfullscreen`. What does `scrolling` do?

**Comment by peterboorsma** [comment]
'scrolling' is an oldskool tag, not useful anymore but still quite common in embed codes (like SOundcloud). (Now 'overflow'  in css)
