### ISSUE TITLE
[BUG] Filebrowser breaks when folder has files with certain filenames

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#5759]
With thanks to **suther** for reporting this on Slack.

Related thread on forums (no solution): https://discuss.bolt.cm/d/427-error-when-opened-theme-folder

Details
-------

 - Tested on Bolt Versions: 3.0.10 and 3.1.1
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

 * When logged in the back-end, navigate to **File Management** -> **View/edit Templates** (i.e. `/bolt/files/themes/`)
 * Create a file with one of the breaking options below:
   * a file without an extension (e.g. `LICENSE`)
   * a file with a name and the extension `.save` (e.g. `foo.save`)
   * a file like `config.yml` with something appended (e.g. `config.yml.foo` or `config.ymlx`, etc.)
   * and more?

The following exception will be thrown:
```
An exception has been thrown during the rendering of a template ("Requested url themes is not available") in "@bolt/files/_files.twig" at line 53.
```
This refers to https://github.com/bolt/bolt/blob/fde4e50fbbca13d90fea34f502477b4e26796593/app/view/twig/files/_files.twig#L53

It might be the magic stuff that's related to:
https://github.com/bolt/bolt/blob/release/3.1/src/Filesystem/Plugin/AdapterPlugin.php#L46

**Comment by CarsonF** [comment]
The problem is ResourceManager doesn't have a `themes` url.

Even though it was referenced (indirectly) like this:
```php
$fs->url('themes://foo.jpg')
```

The `url` method calls `$app['resources']->getUrl('themes')`, but nothing was there.
