### ISSUE TITLE
RFC - Suggestion - No feedback when saving goes wrong in fullscreen editor mode

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#5767]
**Situation:**
When editing an page, and something might go wrong when saving, i get a visual clue.
I can check under the 'Save' button. When it says "last saved 1 hour ago", but I saved 3 minutes ago, I have a clue that something might have gone wrong, and I have to quickly copy-paste my stuff and log in again. 

Don't ask me why, but there is one site where sometimes sessions expire or so. And the only feedback is looking at the 'last saved' time.

**Problem:**
However; When editing in full-screenmode (putting the ck-editor in fullscreen mode), and hitting command-s (on my mac) , gives me no feedback if the saving went wrong. 
(insert image of me typing happily and hitting the command-s now and again)

**suggestion**
I don't know if that's even possible, but a pop-up / bar when full screen editing goes wrong might literally save a lot of work.

Disclaimer: When something like this is implemented after Bolt 2.2.18. mea culpa, I'll update and not complain anymore. :)
## Details
- Relevant Bolt Version: [ 2.2.18 ]

**Comment by GawainLynch** [comment]
I was so tempted to update the title to 

> No feedback when :koala: detects save

**Comment by bobdenotter** [comment]
This should be sorted by now, right? If not, feel free to reopen.
