### ISSUE TITLE
[BUG] Bolt 3.2 - depublish date kill entry

### ISSUE THREAD

**Issue by denis-gorin** [bolt/bolt#5776]
[BUG]

Set future depublish date cause entry data loss

[shot1](http://screencast.com/t/ZzixOWP6)
[shot2](http://screencast.com/t/7MqBnRc9Y)

Details
-------

 - Relevant Bolt Version: [ 3.2.0 alpha 1 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache | Nginx ] version [  Apache/2.2.22 | nginx/1.11.1 ]

**Comment by GawainLynch** [comment]
Thanks! 

This is the same (root) problem as #5733 as we're tracking that there. Please subscribe to that issue for updates :+1:
