### ISSUE TITLE
[3.2] Strict variable error editing content

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5778]
![image](https://cloud.githubusercontent.com/assets/1427081/18579982/383415a8-7bf9-11e6-994b-10dae2538190.png)

What probably needs to be understood is the "why" for this coming up

**Comment by GawainLynch** [comment]
Per discussion in Slack … passing back over to you @bobdenotter

**Comment by bobdenotter** [comment]
Coincidentally, this was fixed in #5772.
