### ISSUE TITLE
[BUG] - Records indexes

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#5779]
Records indexes take id as key.

Details
-------

 - Relevant Bolt Version: [ 3.0 | master ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.4 | 5.5 | 5.6 | 7.0 ]
 - Used web server: [ Apache ] version [ 2.4 ]

Reproduction
------------
​
 1. **Bug summary**: 
    Records indexes are using ids as keys.
 2. **Specifics**:

![capture d ecran 2016-09-16 a 15 44 55](https://cloud.githubusercontent.com/assets/2526939/18587929/9aa2d1a4-7c24-11e6-8c36-7dcd80538397.png)
 3. **Steps to reproduce**:
Dump any records on any listing page.
 4. **Expected result**: 
Zero indexed numerical arrays.

Useful in views. In my case, I want to be able to access next/previous records in a loop, It can't be done with IDs (k+1 isn't necessarily the next item).

Plus it makes sense to have an numerical 0 indexed array as a result. ID can be easily accessed throw `record.id`

What do you think?

**Comment by bobdenotter** [comment]
It took me a long time to get it the way it is right now. ;-)

Imho the preferred behaviour is the way it is right now. If you want to have it 0-indexed, this might work: `{% set content = []|array_merge(content) %}`.

**Comment by nlemoine** [comment]
> Imho the preferred behaviour is the way it is right now.

I guess we'll have to disagree on that point ;) Just by curiosity, what was the purpose behind this? As mentionned above, IDs are already part of record objects and it feels more natural to me to get 0-indexed array when retrieving a collection of records. 

> If you want to have it 0-indexed, this might work: {% set content = []|array_merge(content) %}. 

That's what I did but that's a bit a shame to add this extra code to achieve this.

**Comment by bobdenotter** [comment]
I like this syntax: `{% for id, record in records %} {{ id }} … `

It's just syntactic sugar, but it looks neat.
