### ISSUE TITLE
ckeditor image alt atribute

### ISSUE THREAD

**Issue by jemont** [bolt/bolt#5781]
​​the alt attribute in the image tag of ckeditor is not retained.
it worked on 3.0.12. but on 3.1.0 and above it gets stripped. downgrading to 3.0.12 is working again.
no error message.
i have tried with allowedContent but it doesn't fixed it

**Comment by GawainLynch** [comment]
@bobdenotter assigning to you, as I presume this is more tweaks needed for the sanitisation.

**Comment by bobdenotter** [comment]
@jemont Make sure you have `alt` listed in `allowed_attributes` in your config.yml file : https://github.com/bolt/bolt/blob/release/3.1/app/config/config.yml.dist#L212

We'll fix this in core for the next release.
