### ISSUE TITLE
[BUG] can't login to backoffice on new domain (only the first domain works)

### ISSUE THREAD

**Issue by tbondois** [bolt/bolt#5784]
Hi,

I first install bolt on my server with a temporary subdomain on mine. Everything was working.
Then I linked another  domain on my server, updated the nginx site configuration.
So everything in frontoffice works fine, but i can login in backoffice only with my first url (/bolt)
When I try to log in since the second domain, /bolt/login redirect me in loop to /bolt/login . Without error message. And BTW the password in good.
Is that a know bug ? Maybe I have to update an URL parameter in sqlite / yml ?

Details
-------

 - Relevant Bolt Version: 3.0
 - PHP version: 5.5.38
 - Used web server:  Nginx
 - For UX/UI issues: Firefox last

**Comment by GawainLynch** [comment]
This sounds like the Nginx configuration for the new vhost, especially if you have set `brainding:` in `app/config/config.yml`

If you are using Sqlite for your database, flush the cache as the config is stored in full path form, so moving servers might be a problem.

Also check that the web server can write to the cache directory and all files/folders in there.

**Comment by tbondois** [comment]
Thanks for your help @GawainLynch !

Unfortunately : 

- for the nginx configuration, the only parameter which include the domain name in my case (I used the sample config for nginx givent on the official website of bolt, if my memory is good)
is 
`
server {
    ...
    server_name sub.domain1.com www.domain2.com domain2.com
`
Maybe i have to add something ?

- I already flushed the cache via the backoffice, it didn't change.
- I didn't uncomment the `branding:` in app/config/config.yml
- `app/cache` is also re-filled after I cleaned the cache.

**Comment by bobdenotter** [comment]
Is the "new domain" using an IP address only, or is it a regular domain name?

**Comment by tbondois** [comment]
it's a regular domain name
But I just update Bolt from 3.0 to 3.1.12, and it fix my problem. So I close the ticket.
