### ISSUE TITLE
[RFC] clearer warning when Bolt cannot save

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#5788]
Ohai!
When saving goes wrong, there's a small little warning that appears, that can easily be overlooked. 
It would make sense to give this a more warning - like appearance. 
I think this can be done easily by adding a class 'alert alert-danger'.

top: alert now.
bottom: prererred alert.

![screen shot 2016-09-19 at 14 26 45](https://cloud.githubusercontent.com/assets/5583671/18631987/5e2a74fe-7e75-11e6-9304-5cd54bbb1829.png)

Details
-------

 - Relevant Bolt Version: [ 3.1 ]

**Comment by GawainLynch** [comment]
:+1: from me … I've missed it myself in the past.
