### ISSUE TITLE
[BUG] - cannot use anymore TextType to save php serialized data in DB

### ISSUE THREAD

**Issue by dadaxr** [bolt/bolt#5789]
I was previously using a TextType field to save in database a serialized array of php basic objects.

I know there is a best alternative to do that, ie, using [doctrine object type](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#object)
but in my case I'm using the bolt/members extension and there is a feature to store some meta values to accounts. Those meta values are quite generic and store in database using a TextType.

After investigate the code, it seems it's not really a  bolt/members regression but a bolt/bolt I guess, because since that commit : https://github.com/bolt/bolt/commit/71c6c171435a28e49ffa36ea94e676c7a4283c4d

The sanitizer is called on all (string) FieldTypeBase persist() method : 

```
if ($this instanceof SanitiserAwareInterface && is_string($value)) {
            $isWysiwyg = $this instanceof WysiwygAwareInterface;
            $value = $this->getSanitiser()->sanitise($value, $isWysiwyg);
}
```

Whereas before that commit, it was called on the HtmlType fields ...

The problem is : a serialized string like 

`a:1:{i:0;O:51:"Bolt\Extension\DHuteau\MembersAddon\Form\Entity\Car":3:{s:8:"*model";s:9:"911 turbo";s:8:"*brand";s:7:"Porsche";s:13:"*identifier";s:10:"1234-vf-44";}}`

is trimmed to something like 

`a:1:{i:0;O:51:"Bolt\Extension\DHuteau\MembersAddon\Form\Entity\Car"`

And of course ... it fails silently when i try to "unserialize()" because it just returns "false".

Details
-------

 - Relevant Bolt Version: [ 3.2 | master ]
but i think since : https://github.com/bolt/bolt/commit/71c6c171435a28e49ffa36ea94e676c7a4283c4d

**Comment by GawainLynch** [comment]
@bobdenotter I am wondering if we need to rethink what is targeted for sanitisation … just because it is in a text field, doesn't mean it is for render … as above.

**Comment by bobdenotter** [comment]
Hmm, if it's a `type: text` it might as well be a Title or somesuch, and we absolutely want to sanitise that. Two possible solutions that come to mind: 

 - Before sanitising, make a guess if the data is JSON or serialized (as opposed to 'text with HTML') and don't sanitise if it is. 
 - Add an optional `sanitise: false` option to the field configuration.

**Comment by dadaxr** [comment]
Was thinking about the 2nd option ( ie : sanitise: false ) but the first one is more clever & flexible ( at least in the case of bolt/member ) but it need an a non native function because there is no easy way to know if a string has been previously serialized.

maybe a start : https://gist.github.com/cs278/217091

**Comment by GawainLynch** [comment]
Yes, but that only catches the use case of JSON (or PHP) serialisation.

IMHO, it should be off by default and enabled with `sanitise: true`

**Comment by bobdenotter** [comment]
>  but the first one is more clever & flexible

It _would_ be, if we could make it work perfectly. In practice, I suspect it'll only lead to confusion in edge cases. Also, having that would defeat the purpose. We have the sanitation as an extra layer to prevent XSS, basically. Having a mechanism for this, would allow a potential cracker to do this: 

    a:1:{i:0;s:7:"Porsche";s:13:"*identifier";}}<script>XSS_here_yolo()</script>

Automatic checking is out of the question, now that I think about it. 

> IMHO, it should be off by default and enabled with sanitise: true

That would mean that the "secure" option would have to be enabled, having it "unsecure" as a default. 
I'd much rather have the "secure" option be the default, and only have people disable it, if they know what they're doing.

**Comment by bobdenotter** [comment]
Oh, and this is slightly off topic, but this: 

   O:51:"Bolt\Extension\DHuteau\MembersAddon\Form\Entity\Car"

is the main reason we moved away from serialisation in Bolt itself, as it's a security risk. A _potential_ cracker can insert their own object with a `__wakeup` method, and the code will get executed on deserialisation. See: https://securitycafe.ro/2015/01/05/understanding-php-object-injection/

**Comment by GawainLynch** [comment]
Fair enough … but we should "plaster" something in all relevant places to alert people to almost certain data loss … especially when they're just innocently upgrading their Bolt install.

**Comment by dadaxr** [comment]
Yep but in case of bolt/members, the final user does not have access to the Meta TextType field configuration... it's like a single field configuration to rule all user inputs.

So I guess we 'll have to set "sanitize: false" for bolt/members ... what do you think ?

**Comment by bobdenotter** [comment]
Thinking out loud... What are the most likely situations where people have fields with info like this? 

  - In fields added by extensions (where we can add the `sanitize: false` option)
  - In fields used by an Event, in an extension. (in which case the handler should be able to skip sanitizing)

Am I forgetting common use-cases here?

**Comment by GawainLynch** [comment]
> is the main reason we moved away from serialisation in Bolt itself, as it's a security risk.

Yeah, but this is about people saving whatever they want in fields that are designed to cope with them … if the fields aren't rendered for display, there is a slightly different set of rules.

BTW, the above example from @dadaxr is an entity, which could be JSON encoded and rebuilt anyway :stuck_out_tongue_winking_eye:

**Comment by GawainLynch** [comment]
> What are the most likely situations where people have fields with info like this?

* Some sort of meta data store in a ContentType …

**Comment by rarila** [comment]
Perhaps we're missing some data field type then?!

**Comment by GawainLynch** [comment]
> Perhaps we're missing some data field type then?!

No, just missing common sense.

**Comment by bobdenotter** [comment]
A 'data' type would be complicated, because then we'd need to specify how to display it in the backend (as 'hidden', 'text' or 'textarea'). So far a `sanitise: false` makes most sense to me.

**Comment by GawainLynch** [comment]
Well, for all intensive purposes the text type is a data type given a number of factors and approaches such as serialisation.

I am still furiously waving the flag on this one … these should *not* be sanitised by default. We are going to have pissed off users in the long run, and mysterious support questions that are very hard to track down and answer … 

… we're literally shooting ourselves in the foot here! :-1:

**Comment by bobdenotter** [comment]
@GawainLynch So, what do you suggest? Revert to sanitising only on `html` and `markdown` for now?

**Comment by GawainLynch** [comment]
I've been thinking it over for the last couple of hours. So let's step back.

**Problem:**

  1. Certain field types *should* be sanitised, e.g.
    * HTML
    * Markdown
  2. Certain fields are potential risks if un/sanitised, e.g.
    * Text
    * Textarea

No. 2 is only a problem if the field is used in the render context, and those fields can contain data not intended for such purpose … also text is the default type, and the fallback. it is a data loss problem to sanitise when we do.

**RFC:**

Sanitise fields in category 1. as we do now, but delay category 2. until render and cache the results.

**Comment by rarila** [comment]
@bobdenotter Thought of the data field type of a field that is not even editable in the backend and just used by extensions. You won't (normally) add JSON or serialized php code by hand, won’t you?

**Comment by bobdenotter** [comment]
@rarila So, literally what `type: hidden` is already?

**Comment by rarila** [comment]
@bobdenotter How can I know when this field type is hidden?! ;-)

So to simply solve that problem above that type should have been used?!

**Comment by SahAssar** [comment]
The master branch of translate uses `type: hidden` for this exact purpose, since our old way of loading values broke.

Also... "intensive purposes" _twitches_

**Comment by rarila** [comment]
But still ``type: hidden`` sends its data to the browser and then back although it's not touched there in any way.

**Comment by SahAssar** [comment]
@rarila Right, I'm not saying it's good, I'm just saying that at least for me it was a solution. Ideally we'd have a proper way to deal with this.

**Comment by rarila** [comment]
@SahAssar So I’m not completly wrong with suggesting a data field type. So, is there any real usecase to have that ``hidden`` type? The only one I can think of extensions fiddling with their values using javascript on the backend. Is this possible or even used already anywhere?

**Comment by SahAssar** [comment]
@rarila basically a data field type would be the same as the `hidden` type except that no hidden input is printed to the editcontent screen, right? That sounds like a good solution to me. If we could decide db column type it'd be even better, since MySQL can't add indexes on TEXT columns.

**Comment by rarila** [comment]
@SahAssar Yep. Sounds more naturally for me than type hidden. There's also other column formats that are interesting, e.g. Postgres has ``json`` and ``jsonb``. So you get type checking, faster access and extra functions to use on that data for free.

```
    fields:
        mydata:
            type: data
            format: json
```

**Comment by bobdenotter** [comment]
@rarila @SahAssar I think you two have a point, however this should be an `[RFC]`. The _bug_ that was causing this has been fixed for now, what you're suggesting is a major new feature. ;-)

**Comment by GawainLynch** [comment]
Necro so it (hopefully) makes it into the RFC … but if we're going this way, we probably want a `BLOB` (`BYTEA` on PostgreSQL).

**Comment by rarila** [comment]
@bobdenotter Sure! We're just do some brainstorming to see if we* should do a RFC :smiley_cat: 

_*) This translates to: I hope someone – by reading this – gets the idea he urgently needs this and starts a RFC as I (at the moment) don’t need this necessarily but I might in the future ;-)_

**Comment by GawainLynch** [comment]
@rarila done … #5808

**Comment by rarila** [comment]
@GawainLynch I love it when a plan comes together…  :relieved:

_.oO(I heard this somewhere else before…)_
