### ISSUE TITLE
[RFC] When a record is saved, show a tick icon to indicate saving has been successful

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#5803]
For a better user experience, when the record has been successfully saved, it should show a tick icon and after a few seconds revert back to the flag.

While there is checking the timestamp as a way of making sure it's saved, often people continue to look at the button they've pressed, so it just adds that little extra bit of UI sugar.

Example:

![saved](https://cloud.githubusercontent.com/assets/1776058/18715013/93dc0036-800f-11e6-86f2-3af50a95908d.png)

And after 2/3 seconds or so, revert back to current format

![tosaved](https://cloud.githubusercontent.com/assets/1776058/18715028/a4881ce4-800f-11e6-88ed-b5f0502db428.png)

Applied `.fa-fw` class in both examples to the icon so that the icon change doesn't "bump" the buttons around.

Details
-------

 - Relevant Bolt Version: 3.0+
 - For UX/UI issues: Chrome 33+

**Comment by bobdenotter** [comment]
I like this idea. 👍

**Comment by Maelstromeous** [comment]
Might add it myself if I can figure out how :P

**Comment by bobdenotter** [comment]
Already done, I'll add it to PR #5801 :-)

Screencast: http://recordit.co/YBxyHjHC2J

**Comment by Maelstromeous** [comment]
Ahh sweet, nice one! 👍
