### ISSUE TITLE
[RFC] Admin filter by the values of a field from the contenttype

### ISSUE THREAD

**Issue by duskohu** [bolt/bolt#5807]
Hi.

Is it possible to add additional filters to the contenttype overview page? By default it seems that it's only possible to filter by taxonomy term or do a search. Is it possible to filter by the values of a field from the contenttype?

It would also be useful if you were able to filter for records that are not .

Thanks!

 - Relevant Bolt Version: [ 3.1.2 ]
 - Install type: [ Composer install ]
 - PHP version: [5.6]
 - Used web server: [ Apache]

**Comment by SahAssar** [comment]
This isn't something we have currently, but we have #2046 open to remind us to get it done at some point...

I'm closing this as a duplicate since 2046 has some good discussions and ideas on how to get this done, please feel free to chime in there!
