### ISSUE TITLE
[RFC] Generic data field type

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5808]
This is a follow up to the discussion in #5789

TL;DR in various cases, uses need to store data that isn't used for view rendering. This might be binary data, serialized PHP objects, JSON, XML, l33t JavaScript, or :koala:s, such as a `BLOB` (`BYTEA` on PostgreSQL).

This field should **never** be subject to sanitisation and filtering, _caveat emptor_.

**Comment by rarila** [comment]
A useful data type for sure is ``JSON`` which is supported in PostgreSQL (``json`` and ``jsonb``) and MySQL ≥ 5.7. Thwere’s also an extension for SQLite. Extensions could benefit from from it by enforcing correct JSON on database level, faster processing and JSON-specific functions and operators.

Another thing to mention is, that in contrast to the now used hidden field type the data of this type would’t be sent to the browser and back while editing a record.

**Comment by SahAssar** [comment]
Closing this as there has been no movement on it since it was opened, if anyone feels like I'm wrong about that please reopen! :)
