### ISSUE TITLE
[RFC] Remove as much version-unconstrained JS as possible from backend

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5812]
JavaScript and the NPM ecosystem bring us weekly breakage and pain. Let's get rid of as much of it as we can.

I've just spent 2.5 days trying to get a select2 to work, with zero success. We can not expect people to use this when the core team themselves can't.

**Comment by rarila** [comment]
You forgot to restrict the supported browsers to Lynx!

**Comment by GawainLynch** [comment]
@rarila See #1555

Part of what I was pointing too is that we just have so many 3rd party components that we're using that are systemically, functionally, and fundamentally broken … On average I can install and compile our assets 5 out of ~365.25 days per year … and that is not because we're doing something wrong.

If "I/me/you" want to work on/contribute to Bolt's JS, one shouldn't have to go though what I have seen become weeks of time just to get npm to run.

**Comment by rarila** [comment]
Most problems in that area comes bumping to newest versions without checking consequences and without need. It’s just the same as with the php side. If you for example suddenly require Symfony 3.1 you wouldn't wonder why quite some stuff stops working. And then, whatever you had in node_modules and what once was running, will do so in the future. So a simple ``mv node_modules node_modules.backup`` before a ``npm install`` will keep you in a working state in case of problems.

And what’s the alternative? Do all that stuff manually? Then you are ~360.25 days per year busy to put handcrafted stuff together and have 5 days left for other work.

But if you prefer to write all documentation manually, check JS and php code for errors, lint them, minify them, have all CSS in one big file and add all browser prefixes … 

So mate, come down and get some :leaves: and some  :beers: It’s :sun_with_face: weather outside …

**Comment by GawainLynch** [comment]
> It’s just the same as with the php side. If you for example suddenly require Symfony 3.1

Yeah, and on the PHP side we're very quick at catching and blocking that. But why do I get 5 magic unknown dates in the year I can even install these components.

Thing is … I have spent days trying to track down a problem, that I can't get very far with because I can't installed the needed libraries to recompile the JavaSchit (sic) to start looking at code I can read and work with, and object variable dumps that mean something,

**Comment by rarila** [comment]
Blocking by going back to a working set of packages. So if it was working before and doesn’t after an update to package.json it’s as simple as reverting to the state before.

As long as there’s no open issue "npm install broken" or at least a plea for help on IRC no one can fix it or we have to get a clairvoyant into the team.

**Comment by bobdenotter** [comment]
> So if it was working before and doesn’t after an update to package.json it’s as simple as reverting to the state before.

That's not always the case.. In some cases it breaks all by itself, because other parts have bumped versions, and they became incompatible. 

Also, we don't commit `node_modules` to git for a very good reason: It's considered volatile, and it should be easy to rebuild it, when missing.

**Comment by GawainLynch** [comment]
Exactly… and in terms of delivery, it is close to our biggest single point of failure.

**Comment by SahAssar** [comment]
This doesn't seem to have to be open anymore: any details/progress is better tracked in #6229 or another issue that deals with this on an implementation level rather than a RFC, so I'm closing.
