### ISSUE TITLE
SVG file causes error when fetching directory

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#5819]
I'm currently building a new theme. Any directory in my theme that contains a .svg file (even empty) causes an error when fetching the directory

Details
-------

 - Relevant Bolt Version: 3.1.1
 - Install type: Composer install 
 - PHP version: 5.5.9
 - Used web server: Apache
 - For UX/UI issues: All

Reproduction
------------

 1. **Bug summary**: 
    Whenever a file containing extension  ".svg" appears in a theme directory, an error occurs when fetching the directory. Error disappears when you change file extension.
 2. **Specifics**:
    URL : https://server.url.com/bolt/files/themes/theme-name/directory_with_svg
 3. **Steps to reproduce**:
   create or upload a svg file in this directory, then visit the directory with /bolt/files/directory_adress

The error legend : An exception has been thrown during the rendering of a template ("Requested url themes is not available") in "@bolt/files/_files.twig" at line 53.

**Comment by PhillippOhlandt** [comment]
I think this was already fixed. Ping @SahAssar

**Comment by GawainLynch** [comment]
Yes, it was fixed in #5760 … too fast for me @PhillippOhlandt :smile:

**Comment by trigau** [comment]
Thanks, I didn't notice this existing bug when searching with tag "svg"

**Comment by GawainLynch** [comment]
Hey, zero stress … it is easy enough to miss some times. Even I took a moment to find it :grin:
