### ISSUE TITLE
No title in content listing

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#5820]
Hello, here is a kind or re-opening of #933 : I then found a trick, but in the new release of my website I would like to have a cleaner installation.

Let me explain the problem. I have 3 contentypes : City, Teacher and Seminars.
A seminar contains 2 date fields (start-date end end-date) and 2 relations (to city and teacher).

So Seminar contenttype contains no text field. When listing Seminars in back-end, I have a list of items with the same title : "_No title_", and no way to filter it by teacher or city.

A possible trick is to use a select field type, but this field won't appear in the listing either. Moreover, you lose the relation which can be useful (for listing next seminars under a teacher's page for example).

So my suggestion is to provide a way to use more fields in back-end content listing for title/excerpt : dates, selects or even relations.

**Comment by SahAssar** [comment]
This is the same that is discussed in #3849, right? Dates (and that should work for select fields too) can already be used like this `title_format: [ start-date, end-date ]` and if you need relations there you can use a custom content class. Closing as a dup of #3849, feel free to reopen or discuss further in there :)

**Comment by trigau** [comment]
Thanks for your help. title_format works fine but doesn't seem sufficient.

I would enjoy to write a custom content class, but [the link](https://github.com/bolt/bolt/issues/3849#issuecomment-123549647) in #3849 is broken and a search on Bolt website doesn't provide answers. So I can't figure how to start.

Moreover, would this new content class allow to search in events by teacher or city name ?
