### ISSUE TITLE
[RFC] File upload and replacing underscores by hyphen

### ISSUE THREAD

**Issue by xstable** [bolt/bolt#5824]
Currently if you have a file named : taxi_picture.jpg, and you do an fileupload via Bolt, the file is renamed to taxi-picture.jpg.

This behavior can be really confusing, if the Filename will be renamed without any note.

**For example:**
1) The developer upload the image-file which is used in Layout via FTP as taxi_picture.jpg.
2) Another user download the image from bolt-filemanager, change something and upload it again... (btw. you can't replace, so the user delete the old image before uploading the changed one). Now it's taxi-picture.jpg (with hyphen instead underscore).

If the developer now try to sync the Live-Page with his development-version, they differ for this file.

**Details**
-------
 - Bolt Version: 3.1.1]
 - PHP version: 7.0
 - Used web server: Apache

**Comment by GawainLynch** [comment]
These [config settings](https://github.com/bolt/bolt/blob/release/3.1/app/config/config.yml.dist#L214-L221) should be what you need

**Comment by xstable** [comment]
Wow. Incredible fast answer  :+1: 
I would wish/recommend to not overwrite underscores by default, but only if a user set this up in the config-file.

**Comment by GawainLynch** [comment]
You're welcome. :smile: 

We keep it simple and standardised by default, and it's configurable … and better docs are being worked on.
