### ISSUE TITLE
Backend search doesn't search in "select" fields

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#5829]
Following #5820, I tried to answer my needs by using select field instead of relation, thus loosing the relationship.

To sum up, I have 3 contenttypes: city, teacher, seminar
A seminar references two dates, e teacher and a city. My need:
1. The backend seminar listing shall display the dates (ideally, in a locale format)
2. This list can be filtered by teacher's name or city name.

Relationship doesn't seem to fulfill that need (1. seems complicated, no doc on how to create custom content classes, and 2. seems impossible, relation is stored by ID)

Select fields could be useful, even if I loose the useful relationship. But (here we are) there's seems to be a bug : I can't filter by teacher's or city name event if they're stored in the record (using keys: name for example)
## Details
- Relevant Bolt Version: 3.1
## Reproduction

​
1. **Bug summary**: 
   - Seminar contenttype containing select field populated from "teachers" contenttype and stored with specific keys (keys: name)
   - **Steps to reproduce**:
   - create a new entry for this contenttype, select the teacher, register it, and then filter seminar list by the selected name 
2. **Expected result**: 
   - filtered list should display the seminar
3. **Actual result**: 
   - "no seminar available"

**Comment by GawainLynch** [comment]
OK  … so … bug and it will get "de-bugged" … amybe even fixed!

…but can I just note a very big "thank you" … your issue reports are consistently useful and helpful!

Everyone is different, will do things in different ways — and that is a good thing — but when you have things made more useful it just feels good! :+1:

**Comment by trigau** [comment]
You're welcome.

To be honest, explaining with so much details is also a way for me to invite suggestions : if anyone thinks to a better way to fullfill my needs, he's welcome to suggest.

**Comment by trigau** [comment]
Hello,

Is this enhancement scheduled in 3.3 ? This would be very useful...

**Comment by GawainLynch** [comment]
I don't know it is "scheduled" as such … but once release day calms down we'll take a look at issues and triage next steps and if it can fall under "bug fix" :wink: then 3.3 is on the cards depending on who has time to implement.
