### ISSUE TITLE
[RFC] Formatting select fields

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#5830]
Select field type allows values coming from another contenttype (using values: mycontenttype/fieldname). Moreover, it allows to display multiple values (values: people/name,surname), which is very useful.

However, I would suggest to improve such a display. Actually, when you use name and surname, the results is : Doe / John. This is quite not sexy.

So I would suggest to allow user to format output (as you do for "title_format" for example).

Or at least, provide a sexier default display (using comma instead of slash for example).

**Comment by SahAssar** [comment]
`title_format` and `format` (in relations) are hopefully going to undergo a revision soon (It's been on my to-do for half a year) to unify them, this would be a good addition to that.

**Comment by GawainLynch** [comment]
@SahAssar have I got the branch for you … well several :wink:

**Comment by SahAssar** [comment]
Closing this as there has been no movement on it since it was opened, if anyone feels like taking it on please reopen and ask a core member for help if you want/need it!
