### ISSUE TITLE
[BUG] nut database:prefill doesn't create the content

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5832]
The `nut database:prefill` command seems to have stopped working. I tried it on a fresh Bolt installation. The Backend UI version works like expected.

I don't get any errors, but there will be also no content created.

I tried it with and without setting the ContenTtype as argument:

```
phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/test-nut$ app/nut database:prefill
Continue with this action?
phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/test-nut$ app/nut database:prefill pages
Continue with this action?
phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/test-nut$ app/nut database:prefill entries
Continue with this action?
phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/test-nut$
```
## Details
- Relevant Bolt Version: 3.1.4
- Install type: composer
- PHP version: 7.0
- Used web server: php-dev, but doesnt matter

**Comment by SahAssar** [comment]
Hmm, working here:

```
php app/nut database:prefill pages
Continue with this action? y
Database pre-filled
```

Did you confirm the "action"? Closing for now, but if still an issue please reopen (or just slap me next time we see each other 😉  )!

**Comment by PhillippOhlandt** [comment]
Ok, I just saw that you actually have to enter `y` for it to work. I might be stupid or it isn't obvious that input is required.

On a fresh 3.2.1 install, I get an error:

```
phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/boltnuttest2$ app/nut database:prefill pages
Continue with this action? y


  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array


database:prefill [-n|--no-interaction] [--] [<contenttypes>]...

phillipp at Phillipps-MacBook-Pro in ~/Private/Code/Tests/boltnuttest2$
```

**Comment by PhillippOhlandt** [comment]
Ok, stupid me again. I installed a fresh version, ran the `database:update` nut command, bit I **didn't** create the first user. After I created the user, everything works fine.
