### ISSUE TITLE
[BUG]  Cannot edit local translations in editor

### ISSUE THREAD

**Issue by duskohu** [bolt/bolt#5833]
Hi, I have structure where I have local translations yml files.
- app
  - resources
    - translations
- ...
- vendor
  - ...

When I change something in app/translations yml files in IDE editor, translation is changed. But, when I edit translations in admin, it offers content from vendor yml files.
## Details
- Relevant Bolt Version: [ 3.2.0 | beta 1 ]
- Install type: [ Composer install ]
- PHP version: [ 5.6 ]
- Used web server: [ Apache ]

**Comment by bobdenotter** [comment]
Are you editing the files because you want to improve Bolt's files, or for your own project? 

In case of the latter, you shouldn't use those files, because they will change when updating Bolt. Perhaps https://extensions.bolt.cm/view/bolt/labels would work for you?

**Comment by duskohu** [comment]
Hi @bobdenotter,

its nice extension, but why should I use it, when Bolt has similar tool out of the box - Translations?

I need to translate strings (messages) through ```app/resources/translations/en_GB/messages.en_GB.yml``` file. When I edit some string used in theme, f.i. ```general.phrase.missing-about-page: "Alas, no about!"``` to ```"EDIT: Alas, no about!"```, its translated after **clear cache** and **page refresh**.

But issue is, when I want to edit ```messages.en_GB.yml``` through **Bolt Admin > Translations**. It seems it loads different ```messages.en_GB.yml```, the one from vendor. It results into useless Translations tool in Admin and force me to edit translations through source code only.

**Comment by GawainLynch** [comment]
@duskohu I'll let the multi-linguists chime in further, but the translation in `app/resources/translations/` are for Bolt itself. We're still transitioning the translations layer to properly enable this.

Currently in 3.1+ you can build an extension which loads _user_ translation catalogues, or as @bobdenotter suggested, we have a few options available to get things working *now* … and we have a lot of sites running multiple languages … also see the Translate extension, as that is another one (co-maintained by one of the Bolt core development team), that I believe makes a lot of this easier.

**Comment by SahAssar** [comment]
Well, translate is more meant for content, not keywords or phrases (like for example 'Menu' or 'Contact us'), so I think labels is the one to use here :)

**Comment by SahAssar** [comment]
Closing because a lack of response. Please reopen if still an issue :)
