### ISSUE TITLE
Fatal error because cache file doesn't exist. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5842]
- Relevant Bolt Version: [ 3.2 | master ]

I get this error, when going to login:

![screen shot 2016-09-30 at 14 52 35](https://cloud.githubusercontent.com/assets/1833361/18992298/cdd23a16-871d-11e6-98cd-c5b07d8d0ca4.png)

Full text of trace: 

----------

Bolt
Uncaught Fatal Error:

Details

UnexpectedValueException in FileCache.php line 271

RecursiveDirectoryIterator::__construct(/Users/bobdenotter/Sites/bolt-origin/app/cache/development/data): failed to open dir: No such file or directory

Stack trace

 \RecursiveDirectoryIterator:: __construct()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php # 271
 Doctrine\Common\Cache\FileCache:: getIterator()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php # 175
 Doctrine\Common\Cache\FileCache:: doFlush()
[root]/src/Cache.php # 68
 Bolt\Cache:: doFlush()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php # 156
 Doctrine\Common\Cache\CacheProvider:: flushAll()
[root]/src/Storage/Database/Connection.php # 76
 Bolt\Storage\Database\Connection:: executeUpdate()
[root]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php # 208
 Doctrine\DBAL\Query\QueryBuilder:: execute()
[root]/src/Storage/QuerySet.php # 46
 Bolt\Storage\QuerySet:: execute()
[root]/src/Storage/Repository.php # 414
 Bolt\Storage\Repository:: update()
[root]/src/Storage/Repository/UsersRepository.php # 226
 Bolt\Storage\Repository\UsersRepository:: update()
[root]/src/Storage/Repository.php # 357
 Bolt\Storage\Repository:: save()
[root]/src/Storage/Repository/UsersRepository.php # 214
 Bolt\Storage\Repository\UsersRepository:: save()
[root]/src/AccessControl/Login.php # 264
 Bolt\AccessControl\Login:: updateUserLogin()
[root]/src/AccessControl/Login.php # 212
 Bolt\AccessControl\Login:: loginFinish()
[root]/src/AccessControl/Login.php # 134
 Bolt\AccessControl\Login:: loginCheckPassword()
[root]/src/AccessControl/Login.php # 72
 Bolt\AccessControl\Login:: login()
[root]/src/Controller/Backend/Authentication.php # 152
 Bolt\Controller\Backend\Authentication:: handlePostLogin()
[root]/src/Controller/Backend/Authentication.php # 81
 Bolt\Controller\Backend\Authentication:: postLogin()
#
 call_user_func_array()
[root]/vendor/symfony/http-kernel/HttpKernel.php # 144
 Symfony\Component\HttpKernel\HttpKernel:: handleRaw()
[root]/vendor/symfony/http-kernel/HttpKernel.php # 64
 Symfony\Component\HttpKernel\HttpKernel:: handle()
[root]/vendor/silex/silex/src/Silex/Application.php # 586
 Silex\Application:: handle()
[root]/vendor/silex/silex/src/Silex/Application.php # 563
 Silex\Application:: run()
[root]/src/Application.php # 88
 Bolt\Application:: run()
[root]/index.php # 14

**Comment by GawainLynch** [comment]
Do you have extensions installed, if so which ones?

That is happening as the database provider is being invoked prior to boot.

**Comment by bobdenotter** [comment]
Yes, prolly.. Let me see if that remedies it.

**Comment by GawainLynch** [comment]
BTW … I left a few of those "holes" there deliberately for the dev cycle … those exceptions *should* occur under normal circumstances, but it is the best way to flush out incorrect use of service and the request cycle :smile:

**Comment by bobdenotter** [comment]
Removed all extensions from this setup, but the problem persists.

**Comment by bobdenotter** [comment]
Fixed by #5879
