### ISSUE TITLE
[BUG] Two possible bugs imagelist

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#5851]
I use a image list on our site. When adding images, I encounter two possible issues. As long as the entry isn't saved, I can't click added images because it asks if I want to leave the page. This happens when the image isn't present on the server. When it is, I can click images to view them if I want and then save the entry.

Second issue has to do with draging images. Sometimes I want to change the order of added images. I can drag images, but a dragged image keeps being selected even when I drag an other image. So when dragging the second image, I also drag the image I dragged before. Why isn't the first image deselected when I drag the second image? This is more intuitive than clicking the second image first and then click again to drag it.
## Details
- Bolt 3.1.4

**Comment by bobdenotter** [comment]
This one has been open for a long time. I think it's fixed in the meantime. If not, feel free to re-open.
