### ISSUE TITLE
[BUG] Memcache Session Handler wrong default weight

### ISSUE THREAD

**Issue by kouz75** [bolt/bolt#5855]
Hi,

In SessionServiceProvider method registerMemcacheHandler
some default values are set for the connection to memcache.
When the weight is empty default value is set to 0.

When the weight is 0, $memcache->addServer will return false and  users won't be able to login.

Details
-------
 - Relevant Bolt Version: [ 3.1.2  ]
 - PHP version: [ 5.6  ]

Reproduction
------------

In phph.ini, enable memcache for session
[Session]
session.save_handler = memcache
session.save_path=tcp://myserver:11212

**Comment by bobdenotter** [comment]
@kouz75 Seems plausible. Do you want to make a PR to fix this bug as well?
