### ISSUE TITLE
[BUG] Memcache Session close but never open

### ISSUE THREAD

**Issue by kouz75** [bolt/bolt#5857]
Hi,

When users try to login on the backoffice, they are redirect to /admin/login with the message  general.phrase.error-session-data-login

In the method handlePostLogin, we try to get the token from Memcache. 
SessionHandler return false because the connection to memcache was closed.

The connection to Memcache  is close by the SessionStorage when it's save  the session and never open it again. Informations retrieve from  session after this aren't correcte.

In fact the session is open but the code of the handler juste return true

`   public function open($savePath, $sessionName)
    {
        return true;
    }
`
A quick fix : Do we really need to close Memcache(d) connection ?

Details
-------

 - Relevant Bolt Version: [  3.1.2 ]
 - Install type:  Composer install multi site
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache ]

Reproduction
------------
Configure Memcache in php.ini
​try to login.

**Comment by GawainLynch** [comment]
Ping @CarsonF

**Comment by CarsonF** [comment]
I do see the close connection call. Does the Memecache class not reopen the connection when it needs it? I'll dig into it.

**Comment by CarsonF** [comment]
You could also try using `memcached`
