### ISSUE TITLE
[BUG] Since Twig 1.26, only the last extension using TwigTrait will get registered by Twig

### ISSUE THREAD

**Issue by Dragory** [bolt/bolt#5868]
[Since Twig deprecated the usage of getName() in Twig extensions](https://github.com/twigphp/Twig/commit/f58cce77d773a805e5e4d0ddf5b5e5b17b097d93), multiple Bolt extensions using `TwigTrait` keep overriding the previously loaded extension, resulting in only the last one having its functions, filters, etc. registered. This is because Twig now treats every instance of `Bolt\Twig\DynamicExtension` as the same extension.

Details
-------

 - Relevant Bolt Version: 3.1/all
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Nginx 1.11.3

**Comment by GawainLynch** [comment]
Correct … we found this yesterday and will probably lock to 1.25.x for the time being.

Thank you for the details added to the report … always very useful.
