### ISSUE TITLE
[3.3] Unable to delete records on the dashboard

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5885]
![image](https://cloud.githubusercontent.com/assets/1427081/19219290/a10fb096-8e0f-11e6-86a3-e6764c95b56d.png)

@CarsonF any chance this is related to the recent JS changes?

**Comment by CarsonF** [comment]
Possibly.... I or someone would need to dig in more though

**Comment by bobdenotter** [comment]
I can reproduce this on 3.3 also. If i switch to 3.2, the problem goes away.

**Comment by CarsonF** [comment]
What do I need to do to reproduce it?

**Comment by bobdenotter** [comment]
@CarsonF I just do this: 

http://recordit.co/q8E8Pc1ycp

**Comment by GawainLynch** [comment]
Fixed in #6289
