### ISSUE TITLE
Exception rendering exception template

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#5891]
![](http://www.breaknenter.org/wp-content/uploads/2011/09/inception_movie_poster_small.png)

`exception` and `request` aren't always defined when rendering exception templates.
It can be triggered with a configuration error, such as, a templatefield without any fields defined.
Maybe an exception could be created for this case, @GawainLynch? It seems weird to me to render an exception view without an exception.

We probably should not use `app` either. Maybe `request` can be passed in from controller.

**Comment by bobdenotter** [comment]
> We probably should not use app either. Maybe request can be passed in from controller.

I would think that if `{{ app.request }}` doesn't exist yet, that we also can't use `$this->app['requests]` in the controller, right before it's rendered, right?

**Comment by CarsonF** [comment]
> I would think that if {{ app.request }} doesn't exist yet, that we also can't use $this->app['requests] in the controller, right before it's rendered, right?

I'm more ok with that. I think using `app` in Twig is less acceptable than in PHP.

I'm not sure when/how that method is being called though. Typically in a controller you just "ask" (pass in) request object, and it's given to you. But if we have to do `$app['request']` here, I'd be ok with that for now - It still abstracts it from Twig.

**Comment by GawainLynch** [comment]
Yeah, this is kinda what I wanted to clean up too… I initially just extended exiting templates, 'cause "get it done".

Not convinced it is blocker, but more than happy to see it resolved before stable release … and 3.3/3.4 should put some nails in some coffins, but we have to get there (safely and stably) first.

**Comment by CarsonF** [comment]
Right I was more so wondering if `{{ app.request }}` could even be called without giving an exception in all cases. Default filter and is defined checks can get this out the door, that's what is blocking in my mind.

**Comment by GawainLynch** [comment]
> It can be triggered with a configuration error, such as, a templatefield without any fields defined.
Maybe an exception could be created for this case, @GawainLynch?

That was the plan, yes.

> We probably should not use app either. Maybe request can be passed in from controller.

:+1:

**Comment by GawainLynch** [comment]
> Default filter and is defined checks can get this out the door, that's what is blocking in my mind.

:+1:

**Comment by bobdenotter** [comment]
I've updated the PR, so it doesn't use `{{ app }}` anymore.

**Comment by CarsonF** [comment]
If @GawainLynch merged it, I guess it's good.
