### ISSUE TITLE
redirect in extension

### ISSUE THREAD

**Issue by georgi-kovachev** [bolt/bolt#5910]
I am trying to redirect to the homepage (or any other pages) in extension.

```
public function deleteNotification(Request $request, $errors = null) {
        //email field is passed from frontend page as post param
        $email = $request->get('email');

        $tablename = $this->app['config']->get('general/database/prefix') . 'notifications';
if ($email) {
            $query = "DELETE FROM $tablename WHERE email = ?";
            $stmt = $this->app['db']->prepare($query);
            $stmt->bindValue(1, $email);
            $res = $stmt->execute();

            return new Response();// how can i redirect here?

        }
}
```

**Comment by GawainLynch** [comment]
Assuming that is a controller route, you can return a `Symfony\Component\HttpFoundation\RedirectResponse`:

```
return new RedirectResponse($app['url_generator']->generate('homepage'));
```

Side note, we try to keep the issue tracker to issues/bugs only. Best places to discuss these sort of things are in either the [Slack](https://slack.bolt.cm/) or IRC channels, or on the [discussion forum](https://discuss.bolt.cm/) … as there are way more people watching and participating, willing to share information and advice :smile:
