### ISSUE TITLE
Translation files not being added to translation catalogue

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#5931]
Bolt 3.1.5

Xdebugging why bolt-menu-editor plugin was not finding translation strings.... 

The translations were not being added to the en_gb catalogue in the cache, following this back to the following function:

The translation files were found correctly, but this function drops them due to the string comparison. 

ContentListingFormatter.php

```
private function residesInDirectory(array $entry)
    {
        if ($this->directory === '') {
            return true;
        }

        return strpos($entry['path'], $this->directory . '/') === 0;
    }
```

The `strpos()` is comparing:

`$entry['path']` = `vendor/bacboslab/menueditor/translations/en.yml`

with

`$this->directory` = `vendor\bacboslab\menueditor/translations`

(I still hate brown m&ms)

**Comment by CarsonF** [comment]
Ok so `Bolt\Filesystem`/`Flysystem`'s path normalization does not convert `\` to `/`. However, the `Local` adapter does. So [`$contents` returned from `Adapter\Local::listContents`](https://github.com/bolt/filesystem/blob/master/src/Filesystem.php#L731) have the correct paths, but [`$directory` given to ContentListingFormatter](https://github.com/bolt/filesystem/blob/master/src/Filesystem.php#L736) does not.

The path with `\` in it comes from [PackageEventListener.php#L83](https://github.com/bolt/bolt/blob/master/src/Composer/EventListener/PackageEventListener.php#L83). 

So the question is do we normalize the path there or in Filesystem? I think Filesystem is the better spot, but I'm wondering if there is a reason @frankdejonge didn't code it this way. We haven't ran into problems with this yet, but most of us don't have Windows machines.

**Comment by graham73may** [comment]
Heh, sorry to be a Windows fiend. The short of it is the new Macbook was too far away and I ended up with an XPS 13. Pleasantly surprised how much I like it!

**Comment by graham73may** [comment]
Just a note for myself for any upgrades and maybe for any other people having the same issue on Windows:

```
    private function residesInDirectory(array $entry)
    {

        if ($this->directory === '') {
            return true;
        }

        // TODO: Temporary fix for Windows file string
        $this->directory = str_replace('\\', '/', $this->directory);

        return strpos($entry['path'], $this->directory . '/') === 0;
    }
```

**Comment by bobdenotter** [comment]
So, can anyone confirm this is fixed in Flysystem 1.0.32 and up?

**Comment by graham73may** [comment]
Tested 1.0.32 - Problem still exists

**Comment by bobdenotter** [comment]
.. and 1.0.33? :-)

**Comment by frankdejonge** [comment]
1.0.33 fixed a path traversing issue, might be good to notify your windows users if there's a direct exposure of user input to flysystem.

**Comment by bobdenotter** [comment]
@frankdejonge Thanks, good to know! We'll get an update out soon, with a notification for the users on Windows! 👍
