### ISSUE TITLE
[BUG]  Unsupported password hash when trying to create the first user, bolt 3.1.5 (and also 3.2

### ISSUE THREAD

**Issue by phpetra** [bolt/bolt#5947]
I created a new bolt project with create-project, changed the db name (MySQL) to an already existing one, to use the DB from an earlier version 2 install. And everything was fine.
Destroyed the db to start afresh but then I got the error while attempting to create the first user:

> "Unsupported Password Hash Supplied"

When I look in the database, the user is created but the password is stored in PLAINTEXT. @bobdenotter can verify to that since he saw.

See the image for a full stack trace.

Update to 3.2@beta with composer, threw away config.yml and composer and app.caches but the problem persisted.
Tried to reproduce the error in a clean checkout in another directory and I could not, everything is hunky dory there.
I have no idea what's going on and am posting this on Bobs request. Not sure if it really is an error, or just me, as per ususal [;-)]

<img width="544" alt="screen shot 2016-10-24 at 13 24 35" src="https://cloud.githubusercontent.com/assets/2119144/19645104/6b6b5e46-99f3-11e6-9fb6-28b7da1ddf5c.png">
https://guides.github.com/features/mastering-markdown
<img width="931" alt="screen shot 2016-10-24 at 13 48 57" src="https://cloud.githubusercontent.com/assets/2119144/19645111/718b935e-99f3-11e6-95d9-38f900bc6467.png">

Details
-------

 - Relevant Bolt Version: [ 3.1.5 | 3.2.0-beta7 | master ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.5.9 ]
 - Used web server: [ Nginx ]

**Comment by GawainLynch** [comment]
In what context do you mean "destroyed", tables, rows, complete DB object?

**Comment by GawainLynch** [comment]
That data shown in the stack is 100% correct behaviour at that point … the verification compares the plain text password to the stored hashed & salted one.

**Comment by GawainLynch** [comment]
Damn you GitHub and you're suckful POST on enter at random times!!!!

**Comment by phpetra** [comment]
Hi @GawainLynch,

Destroyed as in Drop Database... to start completely fresh.
What I then did was: delete cookie in browser and navigate to `bolt/userfirst`. The stack trace you see is what I get immediately after the POST (that is creating the firstuser)... 
I had thought it would create the user in the DB **with** a hashed password... ;-)

**Comment by GawainLynch** [comment]
> I had thought it would create the user in the DB with a hashed password... ;-)

Yes, but I can not find a way to reproduce it … so there is a race somewhere that you've found … and OMG … O.C.D.! :laughing:

**Comment by phpetra** [comment]
I did mention this before right? That I'm good at breaking stuff? :-P
Bob has seen it live in action today... pitty you weren't there to witness it too. 
I can still reproduce it this evening, inside this one codebase but not inside a fresh install... Swapping or deleting config.yml didn't even help.... 

I'll be testing a fresh git checkout of this same repo as soon as...
Just forget about it till next week, I'l try and not destroy it so you can see for yourself ;-)

**Comment by GawainLynch** [comment]
Yeah, no doubting you for second, just needing a reproducible test case, as something is obliviously wrong

**Comment by bobdenotter** [comment]
Fixed by #5958
