### ISSUE TITLE
Link to License.md is broken in "About" on 3.2

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5948]
See screenshot: 

![screen_shot_2016-10-24_at_14_08_10](https://cloud.githubusercontent.com/assets/1833361/19645155/acb38964-99f3-11e6-8b29-8e525996085a.png)

Should we fix the link? Or just link to a license online?

**Comment by GawainLynch** [comment]
I am tending towards a link to the docs site

**Comment by bobdenotter** [comment]
Works for me!

**Comment by bobdenotter** [comment]
fixed in #5949
