### ISSUE TITLE
[BUG] Error not catched when saving content

### ISSUE THREAD

**Issue by nbehier** [bolt/bolt#5951]
When I save a content, if there is an error 500, no error message is displayed and save button keep on busy state.
## Details
- Relevant Bolt Version: [ 3.2.0 beta 5 ]
- Install type: [ Zip/tarball install ]
- PHP version: [ 5.6 ]
- Used web server: [ Apache ]
- For UX/UI issues: [ Chrome v53 windows ]
## Reproduction
1. open a Content (Page for example)
2. try to save it
3. if the result of ajax call is something in 500 http code, you should keep a "saving..." button and nothing append (see the attachment)
   ​
   ![161025_bolt-saving-issue](https://cloud.githubusercontent.com/assets/1059917/19684094/b30088a4-9ab5-11e6-985d-b66829c185ab.JPG)

**Comment by GawainLynch** [comment]
Out of curiosity, when you click the line under "Name", what is the response (it is probably coming though as HTML) that gets shown in the preview pane?

**Comment by nbehier** [comment]
@GawainLynch You could see the cause of 500 error on https://github.com/bolt/bolt/issues/5952 but it seems to me it's better to have two issue for that, one for the UI part and one for the core .

**Comment by Maelstromeous** [comment]
Also seen this happen, ideally should show some kind of error to the user upon a 500 code.

**Comment by SahAssar** [comment]
Hmm, shouldn't this have been fixed in #5801? Closing for now as this has been inactive for a while, but if it's still an issue please reopen!
