### ISSUE TITLE
[BUG] Quick install, command line, fails: Command init is not defined

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#5953]
Doing the quick install via the command line results in an error at the third step:

Steps: (using current version)
```
curl -O https://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
php app/nut init
```

Result: 
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "init" is not defined.
```

Tested on two different servers. Same result when running 'php app/nut init. 

Expected:
```
Welcome to Bolt! - version 3.2.0.
```

**Comment by GawainLynch** [comment]
Latest is 3.1.x currently

**Comment by GawainLynch** [comment]
Damn train WIFI … what I was trying to add was that @bobdenotter might have gotten a little ahead on the instructions on the release note on RC

**Comment by sbonardt** [comment]
Jep. That was it. I see the changes have already been made in the docs and version dropdown.
```
php app/nut setup:sync
```
works
