### ISSUE TITLE
[BUG][3.x] Dangling Content for Custom fields can cause exceptions

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#5957]
This, to be fair, is a little obscure, but logging here for visibility etc.

As is Bolt's philosophy we don't do any cleaning up and deletion of content should the structure change, but a combination of using repeaters along with custom field types can cause the backend to choke, if at any time you remove the custom field from your installation.

**To reproduce:** Install an extension that provides a custom field, put the custom field config inside a repeater block and add some content. Then uninstall the extension, remove the custom field item from the contenttypes.yml repeater definition. Load up the content item that you saved it to and you will see a crash with a ContextException.

Solution will be to make some modifications to the hydration that completely discards rows with unrecognised field types.

**Comment by Eiskis** [comment]
Came across this the first time when I started using repeater fields. I think the main culprit might be `type: select` but I can't confirm. I had issues when changing the content type definition, I think Bolt didn't pick it up and make schema updates to the DB which caused exceptions and other problems with my templates. I also have issues removing existing entries.
