### ISSUE TITLE
Local Extension Replacement Plan

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#5964]
# Modifying PHP code

Let's add a Service Provider skeleton class as (one of) the entry point for users.

```
/my/bolt/
├ app
├ extensions
├ public
├ src
│ └ Provider
│    └ CustomizationServiceProvider.php
├ .bolt.yml
└ composer.json
```

We would also autoload `src`. I think a namespace would be good, I chose `My\Bolt`.

Next we need a way to hook this into the bootstrap process. This should be with `.bolt.(yml|php)` as it is the common entry point for all for all processes (web/cli).

``` yaml
# .bolt.yml
paths:
  web: public
services:
  - My\Bolt\CustomizationServiceProvider
```

``` php
<?php

return [
    'services' => [
        My\Bolt\CustomizationServiceProvider::class
    ],
];
```

This class could have (commented out?) code for some basic examples. 
## But what about my SimpleExtension?

Long term I want use straight Pimple DI syntax for almost all customization. But SimpleExtension, or AbstractExtension with the helper traits, look very different than this. That's for a few reasons. 

First, I feared Pimple v1 syntax was too complicated for users to learn and is very verbose.

Second, we've been transitioning from the Service Locator pattern to the actual DI pattern. Most users/devs did't/don't understand the difference. (`config` and `resources` are the last two services that are invoked during registration phase and I have a PR 90% done to fix that). The difference between calling services directly and extending them lazily is subtle, so in an effort to make the difference more noticeable I created the helper traits. These methods invert the invocation process, as in, we call them and they return arrays vs calling services directly.

Third, I knew the transition from Pimple v1 to v3 was coming up and wanted to ease that transition for extension devs. By not using Pimple's syntax they don't need to change their code.

The reality is we can't and shouldn't provide these abstractions for each service. It's more for us to maintain and a second "syntax" users/devs have to figure out. But maybe now isn't the best time for that. Maybe we wait for 4.0 to transition users to straight DI. 

To that end we could stub into the skeleton an Extension that would be registered directly. Something like this: `src/CustomizationExtension.php`. The `CustomizationSP` could have this block (commented out?):

``` php
public function register(Silex\Application $app)
{
    // Register my CustomizationExtension.
    $app['extensions'] = $app->share($app->extend('extensions', function(Bolt\Extension\Manager $manager, $app) {
        $fs = $app['filesystem'];

        $manager->add(new My\Bolt\CustomizationExtension(), $fs->getDir('root://'), $fs->getDir('web://'));

        return $manager;
    }));
}
```
# Assets

Since you are in control of the project your custom assets are going on there's no reason not to put them in the _web_ folder yourself. Doing so means they don't have to be synced from extension folder when changes are made. We don't currently have a _web_ asset package, but it should be created. The _theme_ folder could also be used.

Assuming this structure:

```
└ public
  ├ js
  │ └ foo.js
  └ theme
    └ my-theme
      └ js
        └ bar.js
```

Unless there's some special logic, frontend assets should always be included from Twig templates.

``` twig
<script src="{{ asset('js/foo.js', 'web') }}"></script>
<script src="{{ asset('js/bar.js', 'theme') }}"></script>
```

Backend customization can be done with the extension:

``` php
protected function registerAssets()
{
    return [
        (new JavaScript('js/foo.js', 'web'))
            ->setZone(Zone::BACKEND)
            ->setLocation(Target::END_OF_HEAD),
        (new JavaScript('js/bar.js', 'theme'))
            ->setZone(Zone::BACKEND)
            ->setLocation(Target::END_OF_HEAD),
    ];
}
```

**Comment by bobdenotter** [comment]
Looks good. Few remarks: 

 - Shouldn't we go with `bolt.yml` to start with, since we're heading in that direction for 4.0 anyways, right? 
 - Maybe I missed it, but where would the files for the new "local extension" be placed?
 - How complicated would it be for someone to transform one of these to a proper extension after you're done developing it? That's what I often do: Develop a local extension, and if it's generic / useful enough, fix it up so it can go on the extensions website.

**Comment by PhillippOhlandt** [comment]
I like most of it and I thought about the SP too, my only concern was that it could still be a bit complicated for some users.

I am, like bob, not sure about the extension structure. IMO it should support the same structure as normal extensions, so you can easily just push them to GitHub and add to the marketplace.

For the DI vs. Helper Functions:
Would work for me, but we need transition time for extension developers to change their extensions. Not sure if deprecating Helper Functions in 3.3 and removal in 4.0 is enough or if we should aim for 4.0 (deprecation) and 5.0 (removal). 

There is one thing I disagree with:
> Unless there's some special logic, frontend assets should always be included from Twig templates.

That works for extensions only you use, but not for extensions on the marketplace. We can't assume that people who use Bolt and an Extension have the knowledge to insert assets in the head or end of body. (Sad but true). It would also break some existing extensions.

just my two cents :runner:

**Comment by bobdenotter** [comment]
I didn't catch this at first, either: 

> Unless there's some special logic, frontend assets should always be included from Twig templates.

I hope this doesn't mean `registerAssets()` will go the way of the dodo. A lot of extensions insert _part_ of a page, or a widget. The extension should still have a way to inject CSS in the head or JS in the footer of a page. SEO, Sitemap, Disqus, Facebookcomments, to name a few of the more used ones.

**Comment by CarsonF** [comment]
> Shouldn't we go with bolt.yml to start with, since we're heading in that direction for 4.0 anyways, right?

No, it's the same file as we currently have. We are just adding functionality to it. That will be a breaking change for 4.0, we are still in 3.3.

-----

> For the DI vs. Helper Functions:
> Would work for me, but we need transition time for extension developers to change their extensions. Not sure if deprecating Helper Functions in 3.3 and removal in 4.0 is enough or if we should aim for 4.0 (deprecation) and 5.0 (removal). I am also not in favor of another extension break in 4.0. While it's totally valid in terms of semantic versioning, it's not cool from an user/extension-developer view.

Sorry for the confusion. The initial idea was deprecation in 4.0 and removal in 5.0, but we can hold off on setting that in stone until we get there. And no, `registerAssets` is not going away.

-----

I think there's some confusion here. This plan is not for extensions that would eventually end up in the marketplace. Developing an extension and modifying your bolt install should be two different things. There's abstractions we put in place to allow extension's extra code / resources / assets to be pulled into the main system. These aren't needed for modifying your own install.

What I've gathered over the past few days is people are using/creating local extensions that they never intend to publish. Local extensions were intentionally designed to make developing an extension easier, I know. But my impression right now is that is rarely the use case. Therefore, I think we should put together a separate RFC for developing extensions. If I could repeat once more developing extensions !== modifying your own bolt install.

I know this leads to questions about where stuff goes for your own install. These are valid and need to be addressed. Where do twig templates go? We don't really have a spot right now, besides theme folders. I don't think that's the best place and disagree with twig templates in the web root. 
Where do translations go? We don't have a spot right now. Where do my own config files go? We don't have a spot right now, but that may be addressed soon with config refactor. Where do assets go? Well that's the easiest one, they just go anywhere you want in the web root.

----

I can see that having an extension class, `CustomizationExtension`, may be confusing for users, since it doesn't follow the same extension structure. It's only used for helper methods.

Let me think about this.

----

Question: Are we trying to emulate Symfony's Bundles? If so, we maybe we can change the structure to be more modular. I can see the benefit in that. I think @bobdenotter would like that as he writes his extensions in his sites and then splits them out. But there is also mental & technical overhead in that. I remember being confused when I started to write a Full Stack Symfony app. Do I put everything in AppBundle or try to split out my logic into separate bundles? With separate bundles the structure is `{subject}/{type}`. Each one has it's own templates folder, translations folder, etc. Generally we have the opposite in core, `{type}/{subject}`. We have one `Provider` folder that all of our Service Providers go in.

I think this last question is most important and has a big effect on our direction. Curious to have everyone's thoughts on this before we move forward with this RFC.

**Comment by rossriley** [comment]
Generally, I'm more of a fan of the Symfony Bundles approach and I think incidentally it's closest conceptually to what we already do with extensions.

Long term once we've got our config loader sorted it would be nice if extensions could ship a `Resources/config/config.yml` file or a `Resources/config/contenttypes.yml` file as well as a `Resources/views` etc that all get processed and added to the mix (translations too hopefully).

That also solves the issue of portability, since deciding to publish a locally developed extension is as simple as taking `src/Extensions/MyCoolLocalExtension` adding a `composer.json` and creating a new repo to push to the marketplace.

The only thing we should bear in mind is the concept of providing a semi-sandboxed API for extension developers. Whilst I'm the first to get rid of Extension classes and use my own providers that extend the Pimple services, I'm not sold on the idea that is the best approach for general release. Firstly because there's almost too much freedom for people to do the wrong thing — for instance, running queries directly on `$app['db']`, loading paths onto `$app['twig']` without concern for namespace clashes, understanding the difference between frontend / backend controllers.

Secondly it at least gives us a shot at a surface area for Backwards Compatibility, we really need in the future to keep extensions compatible between major versions because it took far too big an effort to update all the extensions over the last major version. If we don't have the extension `registerXXXX` methods then we're effectively making the entire service stack of Bolt the surface area that we need to consider before breaking BC.

I'm not suggesting that we disable access to the `$app` object, just that we strongly encourage developers to use the official API wherever possible and couple that with a guarantee that we'll work hard to retain BC if that is used.

**Comment by PhillippOhlandt** [comment]
With the explanation of Carson's last reply, this is more a discussion about an inbuilt custom bootstrap, right? I am not really sure if we should have extension support here because there will be a separate approach to develop extensions.

**Comment by CarsonF** [comment]
> With the explanation of Carson's last reply, this is more a discussion about an inbuilt custom bootstrap, right? I am not really sure if we should have extension support here because there will be a separate approach to develop extensions.

Well my comment started that way, but then took a turn. Ross makes a very valid point that Extensions allow us to sandbox what we approve of public API. We definitely aren't ready to publicly support our entire codebase.

I think I'm agreeing with Ross that we should push more towards extensions. That really means structure doesn't change, we just don't _magically_ autoload and register it for you.

So we have the previous structure:
```
/my/bolt/
├ app
└ extensions
  ├ local
  |  └ my
  |    └ customization
  └ vendor
```

### Autoloading:

Users need to add this folder to the `autoloader` themselves.
```json
"autoload": {
    "psr-4": {
        "Bolt\\Extension\\My\\Customization\\": "extensions/local/my/customization"
    }
}
```

### Registration:
Registration is trickier. The simplest way to code it is how I did it in the OP. Instead of specifying that in PHP we could move it to the `.bolt` file.
```
extensions:
  - class: Bolt\Extension\My\Customization\Extension
    baseDir: extensions/local/my/customization
    webDir: public/extensions/my/customization
```
I really don't want to guess the extension's base dir and web dir. But the hard part is `my/customization`. If that was given I could easily base it on our extension dir and web dir, aside from the `local` directory being there. Could the `local` dir be removed?

Registration I'm more flexible on. The part that _really_ needed to go was autoloading and creating the extension list ourselves. So as long as users register the folder in the `composer.json` `autoload` section and provide us with some sort of list to load we'll be good.
