### ISSUE TITLE
[BUG] ContentRepeater order gets mixed up when using postgres

### ISSUE THREAD

**Issue by 5in4** [bolt/bolt#5968]
I am using a contentrepeater in a contenttype. If more than 10 elements are created, the 11th is displayed after the first. This only happens when using postgres.
## Details
- Relevant Bolt Version: 3.2.0 RC1
- Install type: Zip/tarball install
- PHP version: 7.0.10
- Used web server: Apache/2.2.31
- postgres: postgres (PostgreSQL) 9.5.4
## Reproduction
1. clean install from zip
2. use this contenttypes file [contenttypes.txt](https://github.com/bolt/bolt/files/557939/contenttypes.txt)
3. setup with postgres
4. insert a contenttype "case" with 11 repeater elements
5. navigate somewhere else and reopen the case. The order is mangled (same happens in frontend).

The data is saved correctly in the db, but something goes wrong when trying to display the fields.

**Comment by bobdenotter** [comment]
I'm guessing the ordering is alphabetical, without having tried it myself..

```
0
1
10
2
3
4
5
6
7
8
9
```

**Comment by GawainLynch** [comment]
Fixed in #5976
