### ISSUE TITLE
[BUG] "contentsCss" pref for CKEditor not honored

### ISSUE THREAD

**Issue by bintoro** [bolt/bolt#5974]
Specifying `wysiwyg/ck/contentsCss` in `config.yml` has no effect unless I comment out the relevant lines introduced in 6034fedd477926481bd43aeb92a5698b0cbacdd9. After that it works like a charm.

I haven't delved very deeply into Bolt's source, but it seems that `getDefaults()` sets the exact same `contentsCss` paths as `setCKPath()`, so perhaps the latter need not touch them at all.

Observed on v3.0 and v3.2.0-rc1.

**Comment by tompato** [comment]
This still appears to be an issue. Regardless of your setting in 'general/wysiwyg/ck/contentsCss' the defaults are always used as @bintoro mentions above.

I think it's just a legacy thing as there are defaults for CK Editor to fallback to using defined in the very same file ('vendor/bolt/bolt/src/Config.php') so if the user didn't define anything it shouldn't break.

**Comment by CarsonF** [comment]
This is fixed in 3.3
