### ISSUE TITLE
Documentation text correction for resource-contenttype

### ISSUE THREAD

**Issue by gautamz07** [bolt/bolt#5975]
Was just going through the douementation here:

https://docs.bolt.cm/3.1/howto/resource-contenttype#template

There are the following explanation:

> > This is particularly useful for things like 404 pages where you want to have a database stored record for the content of the 404 page, but a themed template to display it.
]

is't it suppose to be 

> where you `do not` want to have a

**Comment by PhillippOhlandt** [comment]
No, the docs are correct. You can edit the 404 text via the Bolt backend because it's in the database then.

**Comment by gautamz07** [comment]
oops sorry ! :P
