### ISSUE TITLE
[RFC] No way to re-trigger copying web assets for extensions..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5979]
If I install an extension in Bolt, like `SEO`, it comes with a `web/` folder. On installation, the contents of this `web/`folder get copied to `public/extensions/vendor/bolt/seo/`, so these assets become available in a web browser. 

In the case that I accidentally clear this `public/extensions/` folder, I can't "rebuild" those files, without removing and re-installing the `SEO` extension. 

I'd like it if there was an option to re-trigger this copy action. Preferably both as a `app/nut` command, as well as through the "Update all things" button on the Extend page in the backend. 

Details
-------

 - Relevant Bolt Version: [ 3.2 | master ]
 - Install type: [ Zip/tarball install | Composer install ]

**Comment by GawainLynch** [comment]
For those reading along, the title is slightly misleading.

From the CLI this can be achieved using Composer:
```
cd extensions/
composer run-script post-package-update
```

We do need a more convenient way via both Nut and the admin UI to handle this, without a doubt.

**Comment by bobdenotter** [comment]
> From the CLI this can be achieved using Composer:

Additional note: in recent composers this doesn't work as expected: 

```
$ composer run-script post-package-update

  [InvalidArgumentException]
  Script "post-package-update" cannot be run with this command
```

**Comment by GawainLynch** [comment]
Ping @rossriley & @CarsonF 

This is intended as an initial RFC on approach: https://github.com/bolt/bolt/compare/release/3.3...GawainLynch:feature/extension-events

**Comment by CarsonF** [comment]
It's actually `composer run post-install-cmd`

**Comment by GawainLynch** [comment]
> This is intended as an initial RFC on approach: release/3.3...bolt:feature/extension-events

I have deleted said extension. If someone wants to waste their time on this, they are more than welcome, but my code is gone.

**Comment by GawainLynch** [comment]
This is hard, and despite repeated questions to the team on approach nothing has come up.

Filing in the circular filing cabinet.
