### ISSUE TITLE
[RFC] Aggregated content types without fields

### ISSUE THREAD

**Issue by michelangeloRome** [bolt/bolt#5990]
Hi all,
I'm new on Bolt, I'm enthusiast of this fantastic cms.
I would propose to permit a pure aggregated content type. 

This is my situation: I have a content type with too many fields and I wont a db table with too many rows. So I have decided to split this content type into 2 small content types (_B_ and _C_). So what i want is to have a "container" content type _A_ that is composed of my 2 obtained content types with fields (_B_ and _C_). Content type _A_ does not need fields, only relations, but if I try to run bolt in this situation I receive this error: 

_In contenttype A, no 'fields' are set. Please edit contenttypes.yml, and correct this._

Is possible to obtain more flexibility on this argument?

**Comment by PhillippOhlandt** [comment]
Hey,

you probably just have to give them a title and a slug. Perhaps only a slug. So in your situation, `A` (your aggregate) would just have a title and slug and would have relations to `B` and `C`. B and C also need a slug.

**Comment by PhillippOhlandt** [comment]
Just checked. Only a slug field is required. But a title field makes sense too, because otherwise every record would look the same in the backend.

**Comment by michelangeloRome** [comment]
Ok, catched, this appears to be se reasonable.
Thank you for your reply :)

**Comment by PhillippOhlandt** [comment]
Great. I will close this for now. You can always re-open it again. If you need more help, feel free to join us on Slack (http://slack.bolt.cm/) or IRC (https://bolt.cm/irc). We are always there :)
