### ISSUE TITLE
Changing themes isn't invalidating cached Twig

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5998]
### Reproduction

* Base install
* Add some content
* Change to a theme like [Solid State](https://github.com/nestordedios/bolt-theme-solid-state.git)

![image](https://cloud.githubusercontent.com/assets/1427081/20043417/40a95484-a48d-11e6-979d-3322cd3f586f.png)

### Workaround

* Flush cache

Reported in Slack by @eduardomart

**Comment by GawainLynch** [comment]
This seems to be caused by a change in Twig 1.24+ … reverting to 1.23.0 doesn't cause it to occur.

**Comment by GawainLynch** [comment]
Also present in Bolt 3.1.6

**Comment by GawainLynch** [comment]
…and found it. It has been with us since 3.0.0.

Twig creates a hash based on the full path of the file, but in 3.x we virtualise the file system and rather than the hash being created on `/path/public/theme/{name}/index.twig` it is created on `theme://index.twig` … so Twig assumes it is the same file and uses the cached version.

Removing as a blocker … getting some sleep …and I will have a chat with @CarsonF about bright ideas to resolve this.

**Comment by bobdenotter** [comment]
Yeah, this doesn't qualify as a blocker to me. Glad you caught it, though.. I recall bumping into this behaviour before, but never enough to realise what was going on, other that "huh, something strange" that passes. :-)

**Comment by rixbeck** [comment]
Also experienced first a week ago here but felt like Bob... :)
