### ISSUE TITLE
We need a new `base-2018` theme.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6002]
Because 2018 is coming, whether we want it to or not.

**Comment by GawainLynch** [comment]
Can we haz `<blink>` tags this time? :wink:

**Comment by bobdenotter** [comment]
No can haz `<blink>`! 

![mcctph_e](https://cloud.githubusercontent.com/assets/1833361/20064389/d3c95ed0-a50a-11e6-8065-224852ed8d65.jpg)

**Comment by rossriley** [comment]
Capturing the Zeitgeist, it should be entirely in AMP.

**Comment by PhillippOhlandt** [comment]
🔥 AMP 🔥 

![](http://www.godandscience.org/images/devil.jpg)

**Comment by zomars** [comment]
Can I play too?

**Comment by SahAssar** [comment]
Actually, let's just `{{ dump(record) }}` and say that dump-based navigation is the next big thing.

**Comment by PhillippOhlandt** [comment]
@SahAssar THANKS. You are the only one who actually wants to innovate! Let's move forward!

**Comment by bobdenotter** [comment]
@zomars Sure, mate! Are you going to build it in Facebook™ Pages™?

**Comment by zomars** [comment]
I was thinking a more a brutalist website apporach @bobdenotter

**Comment by SahAssar** [comment]
Alright, so we're building a brutalist, AMP-only, dump-based Facebook™ Page™ wrapped entirely in a `<blink>` tag!

**Comment by PhillippOhlandt** [comment]
@SahAssar Do you want to setup the tracker?

**Comment by SahAssar** [comment]
@PhillippOhlandt No, I'm busy doing all the thought leading on this one.

**Comment by GawainLynch** [comment]
OK, so I derailed this … might be good if I bring it back on track.

What do we **seriously* want to do with this one?

**Comment by SahAssar** [comment]
IMO we can't get much more basic design-wise without it being way to generic, and it's supposed to be pretty basic, so making it much more complex isn't an option either. CSS/SASS-wise we could make it more basic, but then we'd suffer in flexibility (and move us further away from the default foundation setup that many people are used to).

@bobdenotter What did you have in mind?

**Comment by PhillippOhlandt** [comment]
IMO, we should make a really nice looking, design'ish theme. The current one works, but I wouldn't run a blog or a website on it because it has just too little design'ish parts.

**Comment by SahAssar** [comment]
@PhillippOhlandt It's readable and pretty simple. There are a number of blogs and sites that use it, and I think that they like that it isn't over-designed. Also, any too designed parts of it might make it less useable for a different audience (it should work equally well for a blog about a humanitarian crisis as for a page about tech gadgets for example, without tilting to either side).

IIRC one of the requirements is basically that it should "lack" it's own personality, so that the author can fill it with his/her (but still look good when filled).

**Comment by PhillippOhlandt** [comment]
The problem is, we have not enough good looking and functional themes in our ecosystem. I talked to a few people which decided against Bolt because there wasn't a theme that fits their needs.

So my quick idea was that we could deliver a more designed theme, but you are probably right.

**Comment by SahAssar** [comment]
@PhillippOhlandt I think you are right, I just think that might be better for a non-default theme... Perhaps we should try to have some more "official" themes made by core/core members that showcase that sort of thing.

**Comment by GawainLynch** [comment]
> Perhaps we should try to have some more "official" themes made by core/core members

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: for the reasons that @PhillippOhlandt outlines

**Comment by bobdenotter** [comment]
I was thinking we _should_ make a nice, good looking out-of-the-box theme. `base-2016` is a great skeleton, but like Phillipp says, we need something that's a bit more "showy". 

I'd like for Bolt 3.3 to ship with _both_ the `base-2016` as well as the `base-2017` themes. One being a nice skeleton, and the other a ready-to-go nice looking website theme.

**Comment by GawainLynch** [comment]
> I'd like for Bolt 3.3 to ship with both the base-2016 as well as the base-2017 themes

Yes please … just from a BC perspective. 

The only negative is the size of the install archive … our libraries could use a bit of trimming for v4 too

**Comment by bobdenotter** [comment]
Of all the things people have decided to complain to us about, I've never heard "Bolt is too large", so  imho that is not a very large concern.

**Comment by zomars** [comment]
I've have very good experiences with the latest inuitCSS as a starting point for many of the themes I've developed, they provide just enough functionality for a clean start. And they have a very nice approach for clean and reusable code. I could submit some components I've made if that would help.

**Comment by roggan87** [comment]
Maybe an odd question, but why name it with the year in? Wouldn't it be enough to name the theme "base" and maybe another more stylish named something else? (The fact that WP names their themes based on current year doesn't count as an argument to why we should do the same ;)

**Comment by SahAssar** [comment]
@roggan87 Hmm, when I got here that was the practice and I never really reflected on why. I guess we could use "codenames" for it, but just calling it "base" makes it odd when updating (overwritten files and so on).

Using either major version numbers like "bolttheme4" or codenames would be nice IMO.

**Comment by GawainLynch** [comment]
This is one that I would like to stick with myself.

Three reasons:
1) Simple and obviously simple … very Bolt :wink: 
2) Social contract for the UI team to get a new one out each year
3) Deployment scripts … _lots and lots and lots_ of deployment scripts regex-ing that pattern

**Comment by bobdenotter** [comment]
> The fact that WP names their themes based on current year doesn't count as an argument to why we should do the same

Correct, but it _also_ shouldn't be a reason to _not_ do it. 

One reason not to name it "bolttheme 4" is that the versioning differs from Bolt itself. There's already a bit of confusion sometimes with support, when (mostly novice users) mix up "PHP 3.2.5 and Bolt 5.6". If we'd add "Theme 4" to that, i foresee more confusion. 

Let's just stick with "base 2017". :-)

**Comment by roggan87** [comment]
>> The fact that WP names their themes based on current year doesn't count as an argument to why we should do the same

>Correct, but it also shouldn't be a reason to not do it.

No of course. Thanks for your response, it feels more clear now, and it seems like a majority still think the themes should be year based, so i guess that's the way ahead.

**Comment by GawainLynch** [comment]
@bobdenotter can we call this implemented now with the skeleton theme added to `bolt/themes`?

**Comment by bobdenotter** [comment]
Nope, I'd like to have an _actual_ base-2017 theme. The skeleton theme is nice and basic, but it doesn't take the place of a visually good looking theme out-of-the-box.

**Comment by GawainLynch** [comment]
Cool … Wasn't sure on context, as re-reading the comments there was talk of a "skeleton" theme.

Just thinking about it, we might want to re-target branding, and call it `base-2018` … Just a suggestion though.

**Comment by SahAssar** [comment]
`Retargeting confirmed`

**Comment by GawainLynch** [comment]
![stay on target](https://user-images.githubusercontent.com/1427081/28735856-89b0e05a-73e7-11e7-8f21-a89e422c6c46.jpg)

**Comment by zomars** [comment]
![roger taht](https://media.giphy.com/media/KTCZtCQgTKmru/giphy.gif)

**Comment by GawainLynch** [comment]
![i have you now](https://user-images.githubusercontent.com/1427081/28736817-f285bcf0-73eb-11e7-947d-af69646f0b16.jpg)

**Comment by GawainLynch** [comment]
Given this issue looks like it will see in the 25th anniversary of the `<blink>` tag, I'm just going to leave this here:
```css
blink, .blink {
  -webkit-animation: blink 1s step-end infinite;
  -moz-animation: blink 1s step-end infinite;
  -o-animation: blink 1s step-end infinite;
  animation: blink 1s step-end infinite;
}

@-webkit-keyframes blink {
  67% { opacity: 0 }
}

@-moz-keyframes blink {
  67% { opacity: 0 }
}

@-o-keyframes blink {
  67% { opacity: 0 }
}

@keyframes blink {
  67% { opacity: 0 }
}
```
… and note it should be a requirement for our next theme :stuck_out_tongue_winking_eye:

**Comment by lenvanessen** [comment]
Why only our theme? I think every theme! We can use DOM-crawler to check if it's actually in there, otherwise throw a ThemesShouldHaveBlinkException

Anyhows, I think this should be moved to the 3.5 milestone? Or is someone secretly doing this?

**Comment by GawainLynch** [comment]
Yeah, there are higher priorities for 3.4 … and that is too far overdue for me to agree to this as a blocker.

Wondering if the title should be changed to _"We need a new `base-2019` theme."_ given that this won't happen before 2018 anyway. :wink:

**Comment by bobdenotter** [comment]
Yes, let's push this to 3.5

**Comment by bobdenotter** [comment]
Closing this one.. Going to open a new one for the process. With less gifs, grumpy cats and absolutely no `<blink>`.

**Comment by GawainLynch** [comment]
Copy/paste FTW :wink:

**Comment by bobdenotter** [comment]
See #7005 for the new issue.
