### ISSUE TITLE
[BUG] save record when repeater field group have been deleted

### ISSUE THREAD

**Issue by andreasrrr** [bolt/bolt#6006]
When I save a record in bolt admin where a repeater field group set has been deleted the save button will be greyed out and locked with the preloader symbol. Record is saved but as user I expect the button to be green again in UI when the save is completed

Details
-------

 - Relevant Bolt Version:  3.2 stable 
 - Install type:  Composer install/upgradet from previous version 
 - PHP version: [5.6.10 ]
 - Used web server: Apache
 - For UX/UI issues: Chrome 54.0.2840.7 also other browser

**Comment by SahAssar** [comment]
Could you perhaps check if you have any errors in the browser console?

**Comment by andreasrrr** [comment]
CONSOLE
POST http://domain.localhost/bolt/editcontent/boatmodels/1587?returnto=ajax 500 (Internal Server Error)
Uncaught SyntaxError: Unexpected token < in JSON at position 0(…)

PHP_ERROR_LOG
PHP Fatal error:  Call to a member function getFieldtype() on boolean in /vendor/bolt/bolt/src/Storage/Field/Collection/FieldCollection.php on line 115

**Comment by SahAssar** [comment]
Could you also post your ContentType config, then I can try to reproduce it here.

**Comment by andreasrrr** [comment]
Hi

Its a pretty complex content type with many relations, here is the definition of the repeater field in the content type
 pricenew:
            label: Priser ny båt
            type: repeater
            group: prices
            fields:
                price:
                    type: integer
                    info: "Pris i SEK"   
                yearprice:
                    info: "Vilket år kommer priset från?"
                    type: text
                pricetype:
                     type: select
                     values: pricetypes/id,title
                     postfix: "Välj typ av pris"
                     autocomplete: true
                     sort: ordering

**Comment by rossriley** [comment]
I think this may be the same one I came across in #5957

**Comment by SahAssar** [comment]
Just saw this after testing #6086 which is the same issue (it seems), so closing this one. I don't think its #5957 cause @andreasrrr's repeaters doesn't seem to use custom fields (unless of course it did before, which is half the point I guess).
