### ISSUE TITLE
[BUG] Contenttype slug still inconsistent in backend - failing routes

### ISSUE THREAD

**Issue by phpetra** [bolt/bolt#6007]
Setting the slug on a contenttype leads to inconsistent naming in the backend, and failing routes for editing and saving relations.

Create a contenttype with the following settings and generate a few records.
```
videos:
    name: Videos
    singular_name: Video
    slug: films
    singular_slug: film
    tablename: videos
    fields:
        title:
            label: "Title"
            type: text
            required: true
            group: content
	relations:
        pages:
            multiple: false
            label: "Choose a page"
            order: -title
            format: "{{ item.title|escape }} (№ {{ item.id }})"
            postfix: "Choose a thing"
```
			
In the backend, when you hover over a singular item in the left menu everything is fine and you get to the correct uri: /bolt/editcontent/videos/1 
There is some inconsistency in the naming: see the screenshot: "View Films" vs "New video" but the link is working.

<img width="326" alt="screen shot 2016-11-07 at 22 18 21" src="https://cloud.githubusercontent.com/assets/2119144/20078044/3dd3389e-a53f-11e6-8718-1c2766324372.png">

Hoewever: if you first go to the /bolt/overview/videos overview and hover (and click) a singular item it attempts to load ```/bolt/editcontent/films/1``` (using the slug) and that page can not be found.
The "Edit" action also has that link.
<img width="424" alt="screen shot 2016-11-07 at 22 19 52" src="https://cloud.githubusercontent.com/assets/2119144/20078095/775c6306-a53f-11e6-9802-0fe6f8e57796.png">

You get redirected to the dashboard with the following error: 
```
"The Films you were looking for does not exist. It was probably deleted, or it never existed."
```
<img width="713" alt="screen shot 2016-11-07 at 22 19 33" src="https://cloud.githubusercontent.com/assets/2119144/20078103/7e9fcb6c-a53f-11e6-8746-123852077141.png">

Something similar happens when trying to save a relation:

Go to the relationships tab and try to select a related page and save:
A POST is done to: ```/bolt/editcontent/videos/21?returnto=ajax```
but that results in a 500 error:

```
Uncaught Exception: InvalidRepositoryException

InvalidRepositoryException in EntityManager.php line 259:
Attempted to load repository for invalid class or alias: films. Check that the class, alias or contenttype definition is correct.

        }

        try {
            $classMetadata = $this->getMapper()->loadMetadataForClass($className);
        } catch (StorageException $e) {
            throw new InvalidRepositoryException("Attempted to load repository for invalid class or alias: $className. Check that the class, alias or contenttype definition is correct.");
        }

        if (array_key_exists($className, $this->repositories)) {
            $repoClass = $this->repositories[$className];
            if (is_callable($repoClass)) {

Google this Exception
Stack trace
# 1 	Bolt\Storage\EntityManager::getRepository("films")
[root]/vendor/bolt/bolt/src/Storage/ContentRequest/Save.php # line 90
# 2 	Bolt\Storage\ContentRequest\Save::action([array], [array], "21", [false], "ajax", "/bolt/overview/videos")
[root]/vendor/bolt/bolt/src/Controller/Backend/Records.php # line 71
# 3 	Bolt\Controller\Backend\Records::edit(Request, "videos", "21")
# 4 	call_user_func_array([array], [array])
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 144
# 5 	Symfony\Component\HttpKernel\HttpKernel::handleRaw(Request, 1)
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 64
# 6 	Symfony\Component\HttpKernel\HttpKernel::handle(Request, 1, [true])
[root]/vendor/silex/silex/src/Silex/Application.php # line 586
# 7 	Silex\Application::handle(Request, 1, [true])
[root]/vendor/symfony/http-kernel/HttpCache/HttpCache.php # line 491
# 8 	Symfony\Component\HttpKernel\HttpCache\HttpCache::forward(Request, [true])
[root]/vendor/symfony/http-kernel/HttpCache/HttpCache.php # line 258
# 9 	Symfony\Component\HttpKernel\HttpCache\HttpCache::pass(Request, [true])
[root]/vendor/symfony/http-kernel/HttpCache/HttpCache.php # line 275
# 10 	Symfony\Component\HttpKernel\HttpCache\HttpCache::invalidate(Request, [true])
[root]/vendor/symfony/http-kernel/HttpCache/HttpCache.php # line 206
# 11 	Symfony\Component\HttpKernel\HttpCache\HttpCache::handle(Request)
[root]/vendor/silex/silex/src/Silex/HttpCache.php # line 35
# 12 	Silex\HttpCache::run([NULL])
[root]/vendor/bolt/bolt/src/Application.php # line 91
# 13 	Bolt\Application::run()
[root]/public/index.php # line 18
```

In all cases removing the 
```slug: films``` from the contenttype resolves the problem in the backend but of course aslo destroys the nice frontend routes.

Details
-------

 - Relevant Bolt Version: [ 3.2.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.5  ]
 - Used web server: [ Nginx ]

**Comment by ToBe998** [comment]
I recently stumbled upon something related. It seems that you are currently *strongly encouraged* to use the "slug" as the key in your contenttypes.yml.

**Comment by phpetra** [comment]
Yes, I'd see that as a workaround for now, but it's functionality that was lost. I discovered this problem by copying a working contenttype.yml from a  2.x bolt project to the 3.1/3.2 version.
