### ISSUE TITLE
[BUG] 404 page after updating Bolt

### ISSUE THREAD

**Issue by AlphaRecon19** [bolt/bolt#6011]
I'm having an issue after upgrading one of my Bolt sites to 3.2.0. This issue has already been reported over on the forum [here](https://discuss.Bolt.cm/d/502-3-1-6-and-homepage) but I'll go into a little more detail here with a test case. After upgrading Bolt to 3.2.0 (or 3.1.6) and navigating to the homepage you might see the 404 page. A quick fix for this would be to set the homepage as the 404 page but this is a hack to get the site working again. Reverting back to 3.1.5 also fixes this issue.

Trying to replicate the issue with fresh copy of Bolt (I used a clone from Github to make switching versions easier) I noticed that I was missing the `homepage` key in the `config.yml` for the site that was breaking. Removing this key also broke the fresh copy of Bolt (when I'm checked out at 3.1.6).

Looking at the changes between 3.1.5 and 3.1.6, I found that reverting [this](https://github.com/bolt/bolt/commit/38ace924a78ebd436a04422e23d1783bcba75ff3) commit fixed this issue and looking at what has changed this would make sense. If this is intended behaviour then it would be good to get something about this on the docs as this was working before the update.

As for a fix I'm still working on that but it could be a quick fix.

Details
------------
 - Relevant Bolt Version: [ 3.1.6 | 3.2 ]
 - Install type: [ GitHub checkout | Composer install ]
 - PHP version: 7.0
 - Used web server: Nginx

Reproduction
------------
1. Setup a new install of Bolt 3.1.5
2. Create first user and add some sample content
3. Click the 'view site' button and you should see the homepage
4. Edit the `config.yml` and remove the `homepage` key
5. Click the 'view site' button again and should still get the normal homepage
6. Update the site to either 3.1.6 or 3.2.0
7. Check the homepage and it should be showing the 404 page
8. Restoring the `homepage` key or reverting the commit fixes the homepage

**Comment by web316** [comment]
I also had this issue when updating to 3.1.6. No page would display if it was set as homepage in the config, but would work fine if navigated to directly by its slug or if set as not found.

**Comment by jkazimir** [comment]
I also noticed this on one of my sites, and took a quick look at it.  It seems to only happen when the homepage is set to a contentType that doesn't exist.

It seems related to a change in https://github.com/bolt/bolt/pull/5985/files where the logic surrounding the 404 exception changed ever so slightly. :koala:

As a better temporary work around than setting your 404 page, simply changing `page/1` to another dummy content object with a type that exists should work.  As an example, if you have a `items` type with a singular_slug of `item`, something like `item/not-a-real-item` should work.
