### ISSUE TITLE
[BUG] New thumbnail alias' don't work within repeaterfields

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6014]
Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

1. Create a repeatfield set with an image field
2. Create an thumbnail alias
3. Attempt to load the image with `{{ set.image|thumbnail('alias') }}`
4. Observe images not being generated and DOM showing broken image links

**Comment by bobdenotter** [comment]
I have an inkling this is fixed by either #6027 or #6031. Could you verify?

**Comment by SahAssar** [comment]
Closing due to lack of response (to verify fix/still issue) and it seems like it is fixed by the issues @bobdenotter referenced (or it might be #5846, which is a known issue tracked there).

**Comment by Maelstromeous** [comment]
My apologies, yes this does appear to be fixed in later versions.
