### ISSUE TITLE
[BUG] New thumbnail generator cannot be used with image properties directly, requires string to be passed directly

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6015]
Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

You have to pass the `file` property of an image directly (presumably related to #6014 with repeatsets) to the thumbnail generator, or an exception will throw:

`"Parameter "file" for route "thumb_alias" must match ".+" ("Array" given) to generate a corresponding URL."`

E.g.

```
{{ client.get('image').file|thumbnail('client') }} - Works
{{ client.get('image')|thumbnail('client') }} - Does NOT work
```

**Comment by bobdenotter** [comment]
I have an inkling this is fixed by either #6027 or #6031. Could you verify?
