### ISSUE TITLE
[BUG] Save & create new record doesn't show any kind of saving animation

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6017]
Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome 54

Reproduction
------------

1. Create a new record
2. Press "Save and create new record"
3. Observe that the button where animations normally would appear do not

**Comment by GawainLynch** [comment]
Just making sure there isn't a lurking :koala: … but did you update that site from an older version, and dump your browser cache to make sure nothing is stale in the JS?

**Comment by Maelstromeous** [comment]
Updated from 3.1 this morning, will trash cache and try again...

**Comment by Maelstromeous** [comment]
Confirmed, trashing the cache and doing it again still presents the issue.
