### ISSUE TITLE
[BUG] Filename for image uploads are clipping into progress bar

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6019]
Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - For UX/UI issues: Chrome 54

Reproduction
------------

1. Add an image to a record
2. Observe the progress bar and the filepath clipping

![clipping](https://cloud.githubusercontent.com/assets/1776058/20147659/f3ab1c38-a6a0-11e6-9952-4e49308a192d.png)

**Comment by lenvanessen** [comment]
This seems to be fixed in 3.3/3.4

**Comment by GawainLynch** [comment]
Yep, long since fixed. Please feel free to reopen @Maelstromeous as per normal :wink:
