### ISSUE TITLE
[BUG] ErrorHandler do not catch notices when is debug disable

### ISSUE THREAD

**Issue by duskohu** [bolt/bolt#6020]
Hi, when I have disable debug, ErrorHandler do not catch notices. I don't know if is right functionality but when I enable Monolog\Handler\NativeMailerHandler this handler do not sent mail when is notice.

```php
$app['monolog'] = $app->share(
  $app->extend(
    'monolog',
    function ($monolog, $app) {
      if (!$app['debug']) {

        $nativeMailerHandler = new \Monolog\Handler\NativeMailerHandler(
          'some-email@some-domain.com',
          '[My App] Error report',
          'some-email@some-domain.com',
          \Monolog\Logger::NOTICE
        );

        $monolog->pushHandler($nativeMailerHandler);
      }

      return $monolog;
    }
  )
);
```

Config:
```php
debug: false
developer_notices: true
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: -1
debug_error_use_profiler: true
```
Details
-------

 - Relevant Bolt Version: [ 3.2.1 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6.8 ]
 - Used web server: [ Apache ]

**Comment by GawainLynch** [comment]
That is by design. In PHP errors & notices are not intended to make noise during normal operation.

**Comment by Mariyo** [comment]
@GawainLynch you are right, but I would allow option to enable also this "noise", if its wanted.

**Comment by GawainLynch** [comment]
Yes, there is `debug: true`
