### ISSUE TITLE
Consistent way to select records based on empty field

### ISSUE THREAD

**Issue by ea2973929** [bolt/bolt#6022]
Environment
---------------
 - Relevant Bolt Version: [ 3.2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache ]

Background
-------------
Essentially I wanted to select all records where a certain field was not set (empty). 

Doing the opposite is documented (https://docs.bolt.cm/3.2/templating/content-fetching): 
`{# get all products where price is not empty #}`
`{% setcontent myproducts = 'products' where { price: '!' } %}`

By trial I conclude that this works for fields that get encoded as an empty string:
`{% setcontent myproducts = 'products' where { price: '' } %}`
(this is quite intuitive although I would suggest it gets documented somewhere)

In my case the field was multi value so the above did not work. Instead this works:
`{% setcontent ungrouped = 'members' where { groups: '[]' } %}`
(because empty multi select fields are stored as '[]' in the database).

Feature Request
------------------
My feature request would be that 
`{% setcontent ungrouped = 'members' where { groups: '' } %}`
would work for selecting records based on empty fields regardless of the field type.

This has many advantages:

1. You only need to document one thing
2. You can change the field type and the code still works
3. If you change the internal representation of empty values, the users code still works
4. Probably saves time for users trying to figure out why their where-clause doesn't give them the records they want.

**Comment by Maelstromeous** [comment]
Would this work for `null`s? E.g. if you're selecting by a date field, but it has no entry, it would be `null` as far as I know.

If it doesn't work, then perhaps using `where { groups: isEmpty }` or something along those lines may be a solution.

**Comment by ea2973929** [comment]
This was discussed in slack the other day. As far as I understand, isEmpty would be interpreted as an undefined variable. That's why other selectors for where {} is always special notation within strings (like '!' and '>'). But '' to always mean "empty" whatever the field type is would work for me. If it's a date and the empty representation is null that should work as well.

**Comment by Maelstromeous** [comment]
I see, yeah in that case it would be the most logical character abbreviation to represent empty then.

**Comment by SahAssar** [comment]
I think `{% setcontent myproducts = 'products' where { price: '!!' } %}` should work, lemme know if it doesn't. Closing for now due to inactivity.
