### ISSUE TITLE
BUG publishing for bolt don't work with animal/translate extension

### ISSUE THREAD

**Issue by bravoury** [bolt/bolt#6035]
Details
-------

 - Relevant Bolt Version: 3.2.1
 - PHP version: 5.6.24
 - Used web server: XAMPP for Windows 5.6.24
 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
 1. **Bug summary**: 
i install bolt 3.2.1.
first i create a new page and save it
but when i make it for publishing and try to save it , then apache shout down.
Finally i find that the extension animal/translate is making that bug!!!!

**Comment by GawainLynch** [comment]
Works fine here. 

Could you provide some detail please as to the problem you're seeing.

**Comment by SahAssar** [comment]
Sounds odd that it would shut down the apache process...

Also, if this is a bug in translate please open it in that repo, not this one.

**Comment by SahAssar** [comment]
Closing this, it's an extension issue. I'll get more time to work on translate soon hopefully, but this does not belong here either way. I think there is an issue open in the translate repo, and if there isn't feel free to :)
