### ISSUE TITLE
[BUG] Markdown footnotes are parsed wrong in the markdown field preview

### ISSUE THREAD

**Issue by KKozlowski** [bolt/bolt#6039]
Details
-------

 - Relevant Bolt Version: 3.0.12
 - Install type: try.bolt.com

Reproduction
------------
 1. **Bug summary**: Standard syntax for footnotes in Markdown Extra (`[^id]` in text as a link, and `[^id]: Footnote content` somewhere below as an actual footnote) is parsed properly on the website after applying changes, but it's parsed differently in the markdown field preview in editor. In markdown field preview, footnotes are parsed as simple links (the `^` mark inside square braces seems to not have any meaning in the preview).
 2. **Specifics**: It happens on every try.bolt.com website I create, with Bolt version 3.0.12
 3. **Steps to reproduce**:
    * Get yourself a content type that has a field of `type: markdown` parsed to the website (it can be, for example, the `body` field in the standard `entries` contenttype).
    * Go to the editor of this content type and look at the markdown field.
    * Write this text into the markdown field:
```
Example text[^id]

[^id]: Footnote content
```
 4. **Expected result**: `[^id]: Footnote content` should be parsed as a footnote and displayed. `[^id]` should be parsed as a link to this footnote, with displated text "[1]". In both preview and on the parsed website.
 5. **Actual result**: The code is parsed expectedly on the website, but in the field preview, the `[^id]` code is parsed as `<a href="/Footnote content">^id</a>`, while `[^id]: Footnote content` is not displayed at all.

**Comment by GawainLynch** [comment]
Thanks @KKozlowski

@rossriley has updated the try.bolt.cm images to Bolt 3.2.2 and your given example now produces this:

--- 

![image](https://cloud.githubusercontent.com/assets/1427081/20244001/08abf1da-a970-11e6-9d90-9af3a1f1bb0a.png)

**Comment by KKozlowski** [comment]
The bug wasn't fixed. Markdown is still parsed wrong in the editor:
![Markdown editor](http://i.imgur.com/rF7iHbs.png)

How it is parsed on the website, and how it should be parsed in the editor also:
![Markdown parsed](http://i.imgur.com/Wn1xZK4.png)

**Comment by bobdenotter** [comment]
As explained on slack, this is a "wontfix". 

If possible, i'd like to fix it, but it's not feasible. 

 - Serverside, we use Parsedown and and Parsedown-extras to parse Markdown.
 - The Markdown editor is a third-party component, which uses the basic [Marked](https://github.com/chjj/marked) javascript parser. 

Their "dialect" differ slightly, so on edge-cases or stuff in "markdown extras" the "preview" might be less than accurate.
