### ISSUE TITLE
[BUG] POST_INSERT and PRE_INSERT events do not trigger

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6042]
It appears that the `POST_INSERT` and `PRE_INSERT` events don't trigger.

The only way I was able to do what I wanted to do was by using `POST_SAVE`.

Ideally this should be removed from the documentation and it updated to state "use the `isCreated()` function to determine if it was an insert".

Details
-------

 - Relevant Bolt Version: 3,2.2
 - Install type: Composer install

Reproduction
------------

1. Create an extension to subscribe to the `StorageEvents::POST_INSERT` event.
2. Observe nothing's happening.
3. Create an extension to subscribe to the `StoragEvents::POST_SAVE` event.
4. Observe your code triggers.

**Comment by psren** [comment]
Mhh, i stumbled over your issue and for me it seems to work.

```php
    public static function getSubscribedEvents()
    {
        return [
            StorageEvents::POST_INSERT => 'afterInsert',
            StorageEvents::POST_SAVE => 'afterUpdate',
            StorageEvents::POST_DELETE => 'afterDelete'
        ];
    }

    public function afterInsert(StorageEvent $event)
    {
        /** @var Entity */
        $entity = $event->getSubject();

        $this->adapter->add($entity);
    }
```

This is the part of my eventsubscriber and it get's fired on creation of a new entry

**Comment by Maelstromeous** [comment]
Then in this case this means the documention is incorrect and isn't describing the events properly. @GawainLynch @rossriley could you chaps offer your input on this?

**Comment by SahAssar** [comment]
I'm guessing the difference here is that psren used `getSubscribedEvents` and @Maelstromeous used `subscribe`, right?

**Comment by GawainLynch** [comment]
Closing based on lack of verification. Please feel very welcome to open with additional data, but I personally can verify.
