### ISSUE TITLE
[BUG] Filepath shows up double slashes for file browser

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6048]
File structure:

```
- files
  |- who-we-are
    |- clients
```

Results in below showing at the top of the file picker modal:

![filepath](https://cloud.githubusercontent.com/assets/1776058/20313352/946a80b2-ab4e-11e6-89d0-620ce1c8a79b.png)

Details
-------

 - Relevant Bolt Version: 3.2.1+
 - Install type: Composer
 - For UX/UI issues: Chrome 54

Reproduction
------------

1. Create the filepath as above
2. In an image upload, navigate to that path
3. Observe the path shown

**Comment by SahAssar** [comment]
Can I just get a confirmation that this still happens in 3.2.3 and which OS/php version you are using? just tested on php7 on centos7 and can't confirm.

**Comment by CarsonF** [comment]
this was changed in 3.3. If it's fixed there I would say it's not worth fixing for 3.2

**Comment by SahAssar** [comment]
Closing, cause I agree with carson. Please reopen if it happens in 3.3 or later :)
