### ISSUE TITLE
[BUG / RFC] When using the upload: {PATH} on an image ContentType, and that path doesn't exist, file browser breaks

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6049]
If you've got a ContentType field of `image` and use the `upload: SOMEPATH` property, e.g. `upload: somefolder/somesubfolder` the file picker will break if that folder doesn't exist.

Shows simply the refresh logo. You're unable to navigate higher up in the file structure.

Solution is to make the folder manually and the bug goes away.

This issue could be also classed as an RFC, which would suggest to provide the user some feedback such as "The folder doesn't exist". 

Example config:

```
page:
    image:
        type: image
        upload: somefolder/somesubfolder
```

Details
-------

 - Relevant Bolt Version: 3.2.1+
 - Install type: Composer Install
 - PHP version 5.6
 - For UX/UI issues: Chrome 54

Reproduction
------------

1. Create a ContentType with a field of image
2. Change the image field to have the property e.g. `type: somefolder/subfolder` of a path that is incorrect (doesn't exist)
3. Attempt to `Select from server`.
4. Observe file browser taking a long time to load and eventually failing.

**Comment by GawainLynch** [comment]
This is now working in testing of 3.2.14 (and 3.3.0-beta13), so closing this. Usual story if problems still persist, @Maelstromeous :+1:

**Comment by Maelstromeous** [comment]
Awesome, cheers @GawainLynch 👍

**Comment by Maelstromeous** [comment]
@GawainLynch you got a PR reference or this?
