### ISSUE TITLE
[BUG] Upon creating a record, switching tabs cancels the creation and doesn't allow resave

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6060]
1. Open network tab in browser dev tools
2. Create a new record and add details
3. Switch record tabs during save (to Meta for example)
4. Observe request being cancelled and user not being notified or buttons re-enabled.

Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - PHP version: 5.6
 - For UX/UI issues: Chrome 54

**Comment by Maelstromeous** [comment]
Doesn't seem to be affecting editions, only creations.

**Comment by SahAssar** [comment]
Verified in 3.2.7. Still an issue.

**Comment by GawainLynch** [comment]
Fixed in #6766 that will land in 3.4

**Comment by Maelstromeous** [comment]
:+1:
