### ISSUE TITLE
[BUG] Field 'image' doesn't have a default value

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#6065]
On a new Bolt installation, I removed the image field from the page contenttype. But now when I try to add a page I get this error:

> Uncaught Exception: DriverException

> DriverException in AbstractMySQLDriver.php line 115: 
> An exception occurred while executing 'INSERT INTO bolt_pages (slug, datecreated, datechanged, datepublish, datedepublish, username, ownerid, status, templatefields, title, body, template) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["welcome", "2016-11-21 16:37:25", "2016-11-21 16:37:25", "2016-11-21 16:36:44", null, "", "1", "draft", "[]", "Welcome", "...the content...", ""]:

> **SQLSTATE[HY000]: General error: 1364 Field 'image' doesn't have a default value**

I'd already gone to the database check page and it said there were no changes necessary (IIRC Bolt doesn't remove fields from the DB when they've been removed from the contenttype). But the query is not setting a value for the image field.

Depending on the type of field, setting a default would be the correct solution (if that's not already being done?). But text/longtext fields cannot have defaults, so you'll have to make sure all fields get a value set if they have been removed.

Details
-------

 - Relevant Bolt Version: 3.2.2
 - Install type: Composer install
 - PHP version: 5.5.38
 - MySQL version: 5.6.13
 - Used web server: Apache

**Comment by svivian** [comment]
Has this been fixed now? Just upgraded to v3.2.9 and it proposed to update the text fields to allow NULL.

**Comment by GawainLynch** [comment]
Yes, fixed in #6199 … update your database and all is good.
