### ISSUE TITLE
[BUG] HTML showing in Latest system activity widget

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#6069]
![image](https://cloud.githubusercontent.com/assets/6642498/20516233/7498a8f6-b08d-11e6-8fbd-9b5436113559.png)

<tt> tags showing in activity widget (and maybe other HTML, not seen anything else yet). 

Details
-------
 - Relevant Bolt Version: 3.2.2
 - Install type: Composer install
 - PHP version: 7.0.9 
 - Used web server: Apache

Reproduction
------------
Login and look at the dashboard widget

**Comment by bobdenotter** [comment]
Fixed in #6080
