### ISSUE TITLE
[RFC] More advanced getContent queries

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#6073]
As discussed in the dev meeting yesterday we need to finalize the syntax spec for doing more complex searches, primarily at this stage on relations to content and also on repeater fields but this will also apply to any of the new fields we have planned like named blocks etc.

There's so far been two proposals for syntax, but this is an ideal time to propose any more or tweaks to these as set out.

## Option One

As we do in the contenttype part of the query use a slash as a separator eg:

`$records = $app['query']->getContent('pages', ['relations' => 'entries/1' ])`

The equivalent in Twig when it moves to the new engine:

`{% setcontent records = 'pages' where {'relations': 'entries/1'}`

## Option Two

Allow arrays to be passed as arguments instead of using a string eg:

`$records = $app['query']->getContent('pages', ['relations': ['entries' => '1']])`

The equivalent in Twig when it moves to the new engine:

`{% setcontent records = 'pages' where {'relations': {'entries':'1'}}`

## Option Three

Is to implement both syntaxes and allow users to choose their preferred method.

## Edge Cases and Considerations

Initial comments were that option one seems most intuitive to users of the current syntax. One concern of using it is that without a workaround we may lose the ability to include the `/` character in a search and although that is currently the case with the supported operators, they are a little less common than the `/` character (eg: `'!1'`, `'%searchterm%'` etc). This could perhaps be mitigated a little by doing the transform at a field level, so searches on a text field would receive a single string whereas the field types that want to implement nested search can do the splitting.

Option two is basically what option one will be compiled to, so there are no clashes, although it might give the impression of two parallel syntaxes since we would be supporting strings on some types of query and arrays on others.

**Comment by graham73may** [comment]
From my experience with this recently, I would prefer option two. Of course I would be happy with option three, but that's because it allows me to use option two. 

I do have some questions (or maybe just things to take into consideration)... Would passing arrays allow for multiple values, e.g.:

```
$records = $app['query']->getContent('pages', ['relations': ['entries' => ['1', '2']]]);
```

How would you go about looking up a specific contenttype and id? For example, find me any page, news or event which has a relation to event/1?

```
$records = $app['query']->getContent(('pages', 'news', 'events'), ['relations': ['entries' => 'event/1']])
```

The use case in my head is for featured content, related content, or something such as finding all contenttypes where author = 'people/John Smith'

**Comment by graham73may** [comment]
Another complicated query I've come across before is where you have multiple where conditions with different AND / OR requirements. 

For example, find me all content by `John Smith`, that is in category `abc` or is tagged as `123`

```
$records = $app['query']->getContent('pages', [
    operator: 'AND' 
    [
          operator: 'OR'
         [ 
             'tags': [ '123' ],
             'category': [ 'abc' ]
         ]
    ], [
        'author' : 'John Smith'
    ]
]]);
````

Obviously the above syntax I've just made up, but I couldn't think of a better way to express what I meant.

**Comment by rossriley** [comment]
OK, I'll take these one at a time...

```
$records = $app['query']->getContent('pages', ['relations': ['entries' => ['1', '2']]]);
```

It could theoretically work like that, but that would involve introducing an array parser across all values and would probably make things a bit more complex than immediate timescales allow, you can easily do it but it would involve using the existing syntax which is:

```
$records = $app['query']->getContent('pages', ['relations': ['entries' => '[1,2]']]);
```

It's a subtle difference, but the search values against the field key are passed as a string rather than an array. It's one of the confusions I was alluding to in that if we do searching by array as well as by string for standard values then it could get subtly confusing for users.

Specific contenttype / id would be exactly how you described:

```
$records = $app['query']->getContent(('pages', 'news', 'events'), ['relations': ['entries' => 'event/1']])
```

In the second comment, now we've refined the parser I'm pretty sure we can already do that query with something like:

```
$records = $app['query']->getContent('pages', ['tags ||| categories' => '123 ||| abc', 'author' => 'John Smith']]);
```

That should compile in pseudo sql to: `WHERE (tags='123' OR categories='abc') AND author='John Smith'`

**Comment by graham73may** [comment]
@Ross, I find having an "array" inside a string confusing in itself, but I agree it probably would confuse the situation further to support both `['entries' => [1,2]]` and `['entries' => '[1,2]']` at this point.

`contenttype/id` 👍

Hm ok, I think my understanding of the ORs and ANDs in the where array were wrong in that case. I didn't realise that the where array is structured so:

```
[
    [ "a" OR "b" ]
    AND "c"
    AND [ "d" OR "e" ]
]
```

I think it may be a case that the Twig docs go into a fair amount of detail (https://docs.bolt.cm/3.1/templating/content-fetching#) but the Storage Layer docs (https://docs.bolt.cm/3.1/extensions/storage/queries#fetching-content) are quite small by comparison. No mention of the `||` and `|||` syntax, and no mention of how the where array treats AND and OR groups. 

Happy to have a go and PR to the storage docs when I get some free time, but that's likely to be in about February at this rate!

**Comment by ross** [comment]
@graham73may I believe you have the wrong Ross, I assume you want @rossriley

**Comment by graham73may** [comment]
Oops really sorry @ross, rossriley is @ross in the Bolt slack channel. My mistake!

**Comment by graham73may** [comment]
Just to add to this - Having access to use the sortorder on each contenttype would be great in a multicontenttype query. - being able to sort ASC/DESC by the sortorder field.

The result would be something like a list of events (event start date), publications (publication date), news (publish date) sorted by their sortorder field as defined in contenttypes.yml.

Ross, your notes from Slack on how to currently achieve this for reference:
```
$records = $app['query']->getContent('(entries,pages)',
    [
        'order' => '-datepublish',
        'getquery' => function($query) {
            $ct = $query->getContentType();
            $qb = $query->getQueryBuilder();
            $qb->addSelect("MATCH($ct.title) AGAINST('longus') as relevance")
                ->andWhere("MATCH($ct.title) AGAINST('longus' IN BOOLEAN MODE)")
                ->having("relevance > 0");
        }
    ]
);
```
> I forgot I added in that callback that allows you to modify the query before fetch

> that's assuming a search param of `longus` but you can swap that out for the search param

> then you can change order to `datepublish` or `title` and see the ordering change accordingly

**Comment by SahAssar** [comment]
@rossriley @graham73may Any progress/decisions on this? Just tagging for closing otherwise :)

**Comment by graham73may** [comment]
All I have to offer is requests and opinions 😀

**Comment by SahAssar** [comment]
Well, gonna close this for now then, seems like the discussion won't be had here ;)
