### ISSUE TITLE
[BUG] HttpCache output showing upon exception

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6075]
Looks like someone forgot to remove an header debug output ;-)

![uncaught exception connectionexception](https://cloud.githubusercontent.com/assets/1776058/20561212/51ce6afc-b175-11e6-9756-92660cbfa9d7.png)

Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome 54

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
1. Create a exception (e.g. database connection)
2. Observe cache message at the top

**Comment by GawainLynch** [comment]
No, it is Symfony doing it. Not Bolt.

**Comment by Maelstromeous** [comment]
Oh I see. Naughty Symfony!
