### ISSUE TITLE
[RFC] Undescriptive exception when generating thumbnails by dimension when "only_alias" is set to true

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6081]
Currently we have a scenario where if thumbnails are accessed via dimensions when only_alias is set to true, we throw an exception.

However the exception isn't very descriptive: `HttpException in Application.php line 400: unknown`

In development mode, even with `debug_show_loggedoff: true` it doesn't provide much detail to the user.

Ideally, when `debug: true` and logged out, exception should read along the lines of:

> You have tried to access a thumbnail using dimensions when you have `only_aliases: true` in your config. Please change your code to use aliases or turn this setting to false.

Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer

**Comment by GawainLynch** [comment]
> Ideally, when `debug: true` and **logged out**, exception should read along the lines of:

That would be a leak, and bad security practice.

> However the exception isn't very descriptive: HttpException in Application.php line 400: unknown

Does this happen when logged in and debugging is on? If so, your point is valid … that is not helpful to anyone :smile:

**Comment by Maelstromeous** [comment]
> That would be a leak, and bad security practice.

But one shouldn't be running debug in a non-development environment? In prod this should **always** be false, which in this case would mean that no error is displayed. I would say it's safe to display a more meaningful message in debug / development mode to remind a developer that he's using aliases but actually requesting dimensions.

> Does this happen when logged in and debugging is on? If so, your point is valid … that is not helpful to anyone 😄

It performs fine when logged in, only when logged out that errors occur. It's like (in at least 3.2.1) only_alises is being totally ignored when logged in, with or without debug.

**Comment by GawainLynch** [comment]
I might be mis-remembering, but wasn't 3.2.2 released to address problems with using aliases in 3.2.1?

**Comment by Maelstromeous** [comment]
I believe 3.2.2 fixed breaking the backend with using aliases, only @rossriley truly knows however.

**Comment by GawainLynch** [comment]
> But one shouldn't be running debug in a non-development environment? In prod this should always be false, 

Should be the case, but people leave it on all the time

**Comment by Maelstromeous** [comment]
You would agree with me though, displaying the error "unknown" helps no-one? :P

**Comment by GawainLynch** [comment]
> You would agree with me though, displaying the error "unknown" helps no-one? :P

Yes, it needs to be better. But if you're not logged in **and** have debug turned on, it should not leak information. The purpose of having aliases in the first place is to lazily do security, it belongs in web server config … but don't get me started on this one, I'll rant for hours about how wrong this whole approach is :laughing:

**Comment by Maelstromeous** [comment]
In that case, would being logged in and debug on, AND using dimensions in that case should trigger an exception to remind the developer that they're using dimensions when they should be using aliases?

That should satisfy the security concern and do the job of reminding the developer that they're using it incorrectly.

**Comment by Maelstromeous** [comment]
As it seems right now, being logged in overrides thumbnails in a way where you're seeing something totally different when logged out.

**Comment by GawainLynch** [comment]
Actually, yeah you have a point … I think this the "can of worms" I warned @rossriley about :laughing:

**Comment by Maelstromeous** [comment]
![Worms](https://thesquarerootofapplepie.files.wordpress.com/2011/11/can-of-worms.jpg)

**Comment by rossriley** [comment]
Well those will go well on my toast.

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
