### ISSUE TITLE
[BUG] When deleting image repeatsets, deleting all sets results in 500 OR saves but doesn't apply

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6086]
Currently if you delete all sets from a repeatset for a record, the record cannot be saved and returns a 500 error.

However, if you delete all but 1 of the sets, and clear the image link, it allows a save and performs successfully.

The Delete Set button is greyed out, but the elments are still removed upon clicking. Maybe this is the cause of the bug?

Theres is also a scenario where it allows a save, but doesn't apply it. So upon refresh the data is there like it's never been edited or applied.

Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer

**Comment by Maelstromeous** [comment]
@rossriley Did this get fixed in 3.2.3 at all?

**Comment by SahAssar** [comment]
Just tried on 3.2.6, while it doesn't 500, it doesn't delete the repeaters either. It does however save the other fields.

Assinging to @rossriley

**Comment by peterboorsma** [comment]
This bug is still there in 3.2.8 am I right?

**Comment by rossriley** [comment]
Hopefully this should be sorted both in 3.3 and in the latest 3.2.10 release today.
