### ISSUE TITLE
"current" filter needs a little enhancing

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#610]
At the moment, the `current` Twig filter returns positive if the record's link has an **exact match**. I really think that it should be a little more flexible.

This came up because of a site that I'm busy building. It's menu usn't very normal; where it utilised panes and columns. As such, I had to create some macros to emulate the behavior I wanted, without looping through records. Though, that's not the issue.

### Listings vs Records

Bolt cannot have a listing and a record with the same slug. It has plurals and singulars. So, in my site, I have `beneficiaries` for the listing and `beneficiary` for the record/item.

Now, the menu works like this:

- Beneficiaries
  - Beneficiary

And I need to be able to mark `Beneficiaries` as `current` when `Beneficiary` is `current`. As such, we would need to enhance the filter to add a regular expression so that it can test this.

The desired HTML output is this:

```
<li><a class="current" href="/beneficaries">Beneficiaries<div>
	<ul class="borderRight">
		<li><a class="current" href="/beneficiary/strathyre-girls-home">Strathyre Girls Home</a></li>
...
```
That way, we can easily see where we are in a complex menu.

In a nutshell, if we're visiting a record, then it's listing menu item must also be marked.

### My specific situation

As I mentioned up top, my menu is not normal - it doesn't confirm to a standard array, as certain things a grouped differently.

What I'm doing at the moment is using a macro to create links and check if they are `current`:

```
{% macro anchor(link, title) %}{% spaceless %}
	{% set data = { 'link': link } %}
	<a{% if data|current %} class="current"{% endif %} href="{{ link }}">{{ title }}</a>
{% endspaceless %}{% endmacro %}
```

I then call it like so: `{{ links.anchor('/my-link', 'My Page') }}`.

I can't figure out a decent way to, in the case of `Beneficiaries`, match the content type as well. I guess I'll land up writing an Extension for it, but I think it should be built into the core. Perhaps another filter, like `currentStartsWith`?

**Comment by SahAssar** [comment]
Closing as this is currently implemented in the extension designspike/menuchain.

Feel free to reopen if this is something you feel should be in bolt core.
