### ISSUE TITLE
[BUG] Search not working properly using case-sensitive DBMS

### ISSUE THREAD

**Issue by artggd** [bolt/bolt#6109]
I am using PostgreSQL - searching content doesn't work properly due to Postgres' _LIKE_ operator being case-sensitive unlike most database systems. This is also true for SQLite.

As per [this comment](https://github.com/doctrine/doctrine2/pull/654#issuecomment-17112097), Doctrine chose to let the platform decide how to manage their case sensitivity, this is why I'm opening this ticket on bolt and not on doctrine's repository.

I suggest to change the query and lower the searched fields and the input string with the _LOWER()_ function. That would cover any database system.

Details
-------

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer install
 - PHP version: 7.0
 - DBMS: PostgreSQL

PR is coming

**Comment by bobdenotter** [comment]
> PR is coming

Excellent! 👍

**Comment by bobdenotter** [comment]
Fixed in #6110
