### ISSUE TITLE
[RFC] On cache clear page, offer options for clearing various caches, rather than all

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6119]
During active development of a website, it is useful to clear caches such as Template, Database and Thumbnails.

However, currently with Bolt, ALL caches are cleared, when this isn't what the developer wants.

## Example scenario

Developer has updated a template for a production website. Currently there's no facility via the UI to allow him to clear the template cache. They're forced to clear ALL caches, including thumbnail caches, which can cause the server to start generating lots of thumbnails at expense of CPU power.

## Resolution

Developer should be able to pick and choose what caches are to be cleared. E.g. if they wanted to wipe all thumbnails, they can do that. If they want to wipe *just* the template cache, they can do that also.

**Comment by GawainLynch** [comment]
It is already well underway … @CarsonF and I have been hashing over things for a while, but other things in our way, so will probably be circa 3.5. 

FWIW the initial parts landed in 3.2.0.

**Comment by Maelstromeous** [comment]
Ahh smashing, good to know! 👍

**Comment by GawainLynch** [comment]
This is being moved to v4 as it requires a significant amount of work, that while not hard to do, is dependent on BC breaks that we can't introduce in v3
