### ISSUE TITLE
[RFC] On taxomony listings, allow the ability to get the name of the current taxonomy

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6137]
Currently, you're not able to easily pull out the name of the taxonomy you're currently using.

For example, if you're viewing a tag called `money` (with the url `/tag/money`), and you wanted to dynamically set that to say a title on the template you're viewing, you have to do the below:

`{% set tag = paths.current|split('/')[2] %}`

I think it would be better to give some kind of context to the user. For example, you could have a twig var populated under `{{ context.title }}` or something to easily pull out the taxonomy you're viewing.

Details
-------

 - Relevant Bolt Version: 3.2.3

**Comment by bobdenotter** [comment]
I got you, fam: 

```
    {{ dump(taxonomytype) }}
    {{ dump(slug) }}
```

**Comment by Maelstromeous** [comment]
👍
