### ISSUE TITLE
[BUG] Nut command config:set damages config.yml

### ISSUE THREAD

**Issue by colorando-de** [bolt/bolt#6138]
Nut command config:set damages config.yml because of a wrong regex in the file /vendor/bolt/bolt/src/Configuration/YamlUpdater.php

Details
-------

 - Relevant Bolt Version: [ 3.4 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ] version [ 2.4.18 ]

Reproduction
------------
​
 1. **Abstracted bug description**: 
    * The call to `nut config:set key/subkey newval` should change the value of `subkey` to `newval` in the file config.yml
    * If `subkey` appears again later in the config.yml, maybe as subkey of another key, even if this key is commented out, the last occurence of subkey is changed, not that belonging to `key`
 2. **Steps to reproduce**:
    * Install Bolt
    * Uncomment the key `mailoptions` on line 334 till line 344
    * Call `nut config:set mailoptions/host mymailhost.com`
 3. **Expected result**: 
    * On line 337 in file config.yml the value of host should have changed from `localhost` to `mymailhost.com`
 4. **Actual result**: 
    * On line 442 in file config.yml the commented out property of `httpProxy/host` changed to `mymailhost.com`
 5. **How to fix**:
    * A quick-and-dirty change would be to change the pattern replacement on [Line 81 in file YamlUpdater.php](https://github.com/bolt/bolt/blob/release/3.4/src/Configuration/YamlUpdater.php#L81) from `':.*'` to `':.*?'`.
    * I guess my regex is not the best we could do. We should take in account more cases, e.g. that an subkey could not exist under the main key but the subkey would appear later under another key in the file. Maybe this could only be solved by a real yaml parser.

**Comment by bobdenotter** [comment]
Thanks for the bug report. The thing i've written a while ago is rudimentary at best. The problem here is that there's no _proper_ way to read a yaml file, make modifications and write it back out. 

If we do that with the yaml parser, we'd lose all comments, which would be a bad thing. We might one day have this, but your change sounds like an improvement at first glance. Want to PR that, for sweet worthless Github Karma? :-)

**Comment by colorando-de** [comment]
Ok, I'll create a PR. I will think about it, maybe I find a regex that's closer to the desired result.
