### ISSUE TITLE
[BUG] Composer Error Message - Broken Link

### ISSUE THREAD

**Issue by bjshirey** [bolt/bolt#6140]
​​The Composer error screen contains a broken link that goes to https://getcomposer.org/doc/articles/troubleshooting

Details
-------

 - Relevant Bolt Version: [ 3.2.2 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache  ] version [ 2 ]
 - For UX/UI issues: [ Chrome - Linux, Firefox - Linux, presumably all Browser/OS combos ]

Reproduction
------------

1. Develop a local extension.
2. Add a Packagist package (like "weew/url-matcher": "1.*"). Since Packagist repository doesn't appear to be supported by Bolt, this will end up generating a composer error (next steps).
3. Log in to the admin dashboard (/bolt).
4. Go to the Extend screen.
5. Click "Run All Updates >> Install all Packages"
6. The Composer Error pop-up appears, link is in the "Read this link for further common problems" at the bottom.

**Comment by bobdenotter** [comment]
Hi, 

Unfortunately you can't add composer packages in bolt extensions, as you've experienced. I've been looking for the error message you mention, but I can't find it anywhere in our code. 

The link should be: https://getcomposer.org/doc/articles/troubleshooting.md (note the `.md`), and it seems to be generated in `vendor/composer/composer/src/Composer/DependencyResolver/SolverProblemsException.php` 

No idea what causes the '.md' to fall off on your end, though.. 🤔

**Comment by GawainLynch** [comment]
Closing for spring clean … Local extensions have been removed in the upcoming 3.3 and replace with non-Composer specific functionality.

Please feel very welcome to re-open if I am missing something here, bt trying to get some SnR on issues :smile:
