### ISSUE TITLE
[RFC] Allowed tags and attributes on wysiwyg

### ISSUE THREAD

**Issue by eamador** [bolt/bolt#6141]
I am working in a module which opens content in a modal box. The idea is to add a button so that the user can comfortably close the modal. For this i am trying to add a <button> with some data-* attributes, the problem is that the **src/Storage/Field/Sanitiser/Sanitiser.php** does not cater for any of these and so when the <button> and any data-* attributes get removed before the field content is saved.  

I guess that this is not the only situation where editors/developers will need to add **button tags** and/or some **data-X attributes** in a **wysiwyg field** (especially the data-* attributes).

 The activation to allow the "button" tag / "data-X" attributes would be a setting in the wysiwyg part in the config.yml file.

Do you think this feature could be useful for more people? If so i will proceed to implement the changes needed for this and create the pull-request.

Best regards.

**Comment by bobdenotter** [comment]
Hi, 

I'm not sure i follow completely.. Are you talking about the filtering we do in content when saving? If so, adding the attributes here might suffice: https://github.com/bolt/bolt/blob/release/3.2/app/config/config.yml.dist#L218-L220

**Comment by eamador** [comment]
Hi, that looks what i need, thank you!

**Comment by bobdenotter** [comment]
Cool. Closing this issue, then. :-)
