### ISSUE TITLE
[RFC] Rename 'extend' to Extensions

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#6143]
Hi!
The things you put in Bolt are called _extensions_, the website where you find the things is called _https://extensions.bolt.cm/_ ... 

So please call the menu item "**Extensions**" 
(It is now 'extend', maybe logical for native speakers, but not clear at all)

Extra request:
Could we move the name extensions up one level?
so rename Extra's -> Extensions?

![screen shot 2016-12-08 at 11 49 03](https://cloud.githubusercontent.com/assets/5583671/21007247/67e587da-bd3c-11e6-9d91-b26b8e883b4b.png)

I am not sure what is all under 'extras', but if it is only extension stuff, why hide it under a shady / unclear name? (Extra? Extra what? Extra sauce? Fries? Mmmmm Fries...)

Details
-------

 - Relevant Bolt Version: [ 3.2 ]

**Comment by bobdenotter** [comment]
I recommend we rename it to "Apply yourself now". 😈

**Comment by sbonardt** [comment]
Yes, please. And remove "Extend". We wouldn't name a modules page "Modulate" or a  plugins page "Plug in" right....

If the "extra's" menu item only contains extensions or extensions submenu items, name it "Extensions" 

"Extra's" wants to cover a lot, but there are only extensions in it.

Can it link directly to the "Extensions" page?  And all extensions that have menu thingies under the hover.

**Comment by rossriley** [comment]
By way of context, when we first had the new extensions system there was already a url for /extensions which was an information page, hence we needed to pick a different URL.

Obviously the old one has gone now so it would be perfectly reasonable to rename in the next version.

**Comment by anketwokings** [comment]
Great, tx!
(By he way, a url should never be the reason to use a certain word as a label for the end-users)

**Comment by SahAssar** [comment]
Tagging some issues for future bolt archaeologists: #1694 #3461

Also closing since fixed in #6156
