### ISSUE TITLE
 [BUG] ImportWXR (Bob den Otter - bolt/importwxr) not working on 3.2.2

### ISSUE THREAD

**Issue by bcmans** [bolt/bolt#6146]
No available versions of ImportWXR (Bob den Otter - bolt/importwxr) to install in 3.2.2.

Details
-------

 - Relevant Bolt Version: [ 3.2  ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6  ]
 - Used web server: [ Apache ]

Reproduction------------

No available versions of ImportWXR (Bob den Otter - bolt/importwxr) to install in 3.2.2.

![2016-12-08_11-18-14](https://cloud.githubusercontent.com/assets/14008560/21024097/1c5b826e-bd38-11e6-8ac0-f54c1c1e0ef0.png)

**Comment by GawainLynch** [comment]
Hi @bcmans 

The author of [that extension](https://github.com/bolt/ImportWXR) hasn't had he free time to update it yet for Bolt 3, so it won't appear as an available option to install.
