### ISSUE TITLE
[Bug] Cache clear crashes on empty cache folders

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#6149]
If you have a complete and working Bolt instance and then clean the cache folder manually, the subsequent `app/nut cache:clear` command fails.

A common scenario is a bolt website that get's deployed via tools like Capistrano or similar including an empty cache folder.

Details
-------
 - Relevant Bolt Version: 3.2.3
 - Install type: Composer install
 - PHP version: 5.5
 - Used web server: Apache
 - For UX/UI issues: n/a

Reproduction
------------
You can easily reproduce the issue like this in a complete and running Bolt instance:

1) Manually clear the cache folders. `rm -rf app/cache` and then `mkdir app/cache`. Make sure to use correct permissions for your system.

2) Call the cache:clear command. `vendor/bin/nut cache:clear`

3) You will see the following error:
```
[UnexpectedValueException]                                                                                                                 
RecursiveDirectoryIterator::__construct(/xxx/app/cache/development/data): failed to open dir: No such file or directory

cache:clear
```

**Comment by GawainLynch** [comment]
Do you have extensions running? @bobdenotter and I saw this recently and it was from memory a race to do with custom fields.

**Comment by ToBe998** [comment]
There are plenty of extensions, both local and vendor. Some provide fields. Anything special to look out for?

**Comment by ToBe998** [comment]
This big is really getting urgent. Is there anything i can do to speed it up?

**Comment by GawainLynch** [comment]
Remove extensions and see if you can find out which one isn't behaving correctly.

**Comment by SahAssar** [comment]
@ToBe998 Did you find out which extension it was or was it bolt itself?

**Comment by GawainLynch** [comment]
@ToBe998 This whole section got rewritten in the time between this issue and now. I'm going to close, but **please** feel very welcome to re-open if I am wrong … triaging
