### ISSUE TITLE
after update to 3.2 routing.yml _requires_ homepage route to be defined

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#6165]
after update to 3.2 routing.yml _requires_ homepage defined. And some url generator instances stopped working. like [_page-no_nav.twig](https://github.com/bolt/bolt/blob/release/3.2/app/view/twig/_base/_page-no_nav.twig#L21)
```twig
<div class="view-site">
            <a href="{{ path('homepage') }}" target="_blank"><i class="fa fa-fw fa-external-link-square"></i> {{ __('general.phrase.view-site') }}</a>
        </div>
```

And previously it was not demanding for that. So when i clone config from previous version, it refuses to load `.../userfirst` path. 

Maybe we can make a hardcoded fallback for`homepage` route, if `routing.yml` hasn't it defined? To avoid obliging users to keep something in their routing.ymls, except their own custom routes. For example, my custom page route was called `home` until now, not `homepage`.

**Comment by SahAssar** [comment]
IMO this is something for the larger backend twig refactor (check that we allow more "flexible" routing), but if you want to override the '/' route with something else you can do that by putting it above the homepage route.

I'm going to close this as the backend is still coupled pretty closely with the frontend, and this is just a small piece of a problem we are looking to solve in a future major version.

**Comment by CarsonF** [comment]
Also it is clearly stated in [`routing.yml`](https://github.com/bolt/bolt/blob/release/3.2/app/config/routing.yml.dist#L12-L13) those routes are required.

Note that this route can have its path changed, it's just it's name needs to stay the same.

@Boorj You can also have another `home` route that's the same as `homepage` if you would like.

**Comment by Boorj** [comment]
Actually, i tried to solve that, by putting `homepage: {path: /}` in the end of file.
But that is not working on remote server, bringing the same error.
Yes, it's stated in `routing.yml`, but.. isn't it okay to make defaults for required paths?

**Comment by Boorj** [comment]
actually, i'm experiencing the same problem, and i don't know why:

![image](https://cloud.githubusercontent.com/assets/2145313/21161418/16d8bf46-c1bb-11e6-809c-aa7c0e4724e3.png)

and still:

![image](https://cloud.githubusercontent.com/assets/2145313/21161432/28256ab0-c1bb-11e6-84a3-090b425b2b41.png)


Cache is cleared, problem appears **on backend**.

**Comment by Boorj** [comment]
i think the problem is here:
` 'filePath' => 'app://view/twig/_nav/_primary.twig',  `
gives: 
> Warning: file(): Unable to find the wrapper "app" - did you forget to enable it when you configured PHP?

What am i missing?

**Comment by CarsonF** [comment]
@Boorj Set `debug_error_use_symfony: true` in `config.yml` and then what happens?

**Comment by Boorj** [comment]
@CarsonF 
![image](https://cloud.githubusercontent.com/assets/2145313/21164155/eeb61766-c1c9-11e6-994c-b5252d0a684a.png)

**Comment by CarsonF** [comment]
Oh. You need to define a `_controller` in the homepage route or it isn't valid.

**Comment by Boorj** [comment]
okay, thanks, that worked!
But @CarsonF, i assume that it's a problem, because all my sites could be broken after update, because previously they were working without that route, and now they seems to be not.

**Comment by CarsonF** [comment]
Sorry, but its not. The fact that it was working before unintended.
