### ISSUE TITLE
[RFC] Extensible menu in the backoffice

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#6168]
Currently it is possible to use a `MenuTrait` in your extension which allows you to add menu items as children of `Extends`.

It is *not* currently possible to add menu items anywhere else without overriding the templates (i.e. `_nav/secondary.twig`).

I would suggest using a library such as [Knp menu](https://github.com/KnpLabs/KnpMenu) which would allow menus to be arbitrarily extended.

Using that library would mean something like:

```php
class MenuListener
{
    public function extend(Menu $menu)
    {
          $menu->addChild('Foobar', ['route' => 'my_foobars', 'icon' => 'fa-foobar']);
          $menu->getChild('config')->addChild('barbar' .... );
    }
}
```

**Comment by bobdenotter** [comment]
This is by design. See here for more info: #478

**Comment by dantleech** [comment]
Well, I don't see the issue here. Using a "real" menu tree and rendering system would be an improvement in it's own right IMO. f.e. at the moment you are mapping configuration values to an array and redering them with a macro in the twig template:

https://github.com/bolt/bolt/blob/release/3.2/app/view/twig/_nav/_secondary-configuration.twig

If it would improve things generally and it is extensible as side-effect, it's all good no?

**Comment by bobdenotter** [comment]
Is this something you would like to work on?

**Comment by GawainLynch** [comment]
That Twig file isn't used.

Admin menu generation is in [PHP since 3.0.0](https://github.com/bolt/bolt/blob/release/3.2/src/Menu/AdminMenuBuilder.php)

**Comment by GawainLynch** [comment]
> That Twig file isn't used.

I take it back, it is, but mostly "cut-out" of the picture. 

The foundation is in place basically, but there is a heavily/continually blocked request to open this up …
