### ISSUE TITLE
[BUG] Uploading images fail in editcontent if not using canonical domain

### ISSUE THREAD

**Issue by SofaCitizen** [bolt/bolt#6177]
When uploading one or more images to an image or imagelist field within the editcontent section of the dashboard (e.g. /bolt/editcontent/galleries/6) the images will fail to upload if the canonical setting of the config is set to a different domain.

Details
-------

 - Relevant Bolt Version: 3.2.3
 - Install type: Zip/tarball install
 - PHP version: 5.6.22
 - Used web server: Apache
 - For UX/UI issues: Chrome 54.0.2840.98 (64-bit) & Firefox 50.0.2

Reproduction
-------------

 1. Open config.yml
 2. Uncomment "canonical" setting and set a valid domain for the site - e.g. "domain.co.uk"
 3. Create a content type with a field that uses either image or imagelist
 4. Navigate to the admin panel on a different domain - e.g. "**www**.domain.co.uk"
 5. Click to Edit/Add some content
 6. Attempt to "Upload Image"

Expected Result
---------------

 1. Filename(s) to appear between button and field
 2. Progress bar for each image fills up
 3. Image thumbnail(s) appear in the field/preview area
 4. Images appear in dated folder within files folder

Actual Result
-------------

 1. Filename(s) appear between button and field but the progress bar will never move and eventually disappear.
 2. field/preview area does not get updated
 3. Images are not anywhere within the files folder.
 4. No error messages of any kind are displayed within the screen or system log

Steps to fix
-----------

 1. Flip the canonical value to the domain you are using: e.g. "www.domain.co.uk"
 2. Reload the editcontent page
 3. Attempt to "Upload Image"
 4. Image(s) now upload as expected. 

Conclusion
----------

I appreciate that this is a weird edge-case but I wasted several hours trying to track down why images would not upload despite working fine in the demo environment on the same server. Perhaps a "fix" for this bug could just be a suitable additional line in the comments for this setting, like with the cookies_domain option?

**Comment by bobdenotter** [comment]
Hmm. I wonder why the upload won't work.. How about we add a test to this: https://github.com/bolt/starter-kit ? 

That seems like a good place to tackle this by providing feedback to the users caught by the edge-case.

**Comment by SofaCitizen** [comment]
Sounds good. That won't install as an extension (either normally or local) tho so I assume I have to build a fresh install?

**Comment by GawainLynch** [comment]
No, it is a separate Composer packager that can be installed in the root package as of Bolt 3.3 (released soon). By default it will be included in the archive/zip version of the installer.

**Comment by bobdenotter** [comment]
Moved to Starterkit: https://github.com/bolt/starter-kit/issues/3
