### ISSUE TITLE
[RFC] Extension Idea: Thumbnail cache warmer

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6193]
So a small concern of mine with Bolt, is with the thumbnail rendering upon runtime. Currently, we have to have a user (be it a editor or just Joe Bloggs) visit a page with the image on in order to trigger the thumbnail rendering.

This results in the particular user having to wait for the thumbnail to be rendered, saved, then served to them. While user 2 doesn't have to wait for the rendering, I think it's bit of a odd/bad UX in having to wait, especially if there's a ton of images on a page.

This is especially a concern on websites with either user generated content, or content updated very regularly.

Therefore, what I propose is a thumbnail warmer. Upon saving a record, we can use the `POST_SAVE` event in order to check and if necessary, generate thumbnails using specific thumbnail aliases / sizes.

We would have to propose a change to the config for the image ContentType. Below is an example:

```
Page:
    image:
        type: image
        cache:
            alias: ['thumbnail_alias1', 'thumbnail_alias2']
            sizes: [ [300, 200], [500, 350] ]
```

The above config means that we can state the thumbnail aliases to use (if applicable) and also pass in specific dimension sizes of that image.

When doing this upon save, it then means we can trigger the event with `POST_SAVE` and then render all these thumbnails in the background.

This will result in the images being fully rendered and ready to serve to users, without delay. All while maintaining a simple config.

The actual implementation of this could simply be a CURL request to the thumbnail generator, based off the settings determined above.

Details
-------

 - Relevant Bolt Version: 3.2^

**Comment by Maelstromeous** [comment]
This might be of interest to you @rossriley

**Comment by GawainLynch** [comment]
Personally, I am :-1: this in core. Extension or script should be the option IMHO.

**Comment by Maelstromeous** [comment]
Would you care to share why? :P

**Comment by Maelstromeous** [comment]
Of course it would be an optional thing, only triggered when the developer requests it, so it doesn't do extraneous requests / rendering when it's not wanted.

**Comment by bobdenotter** [comment]
IMHO this can be useful in some cases, but for the majority of users this will be irrelevant. Because of that I agree that it should definitely be an extension.

**Comment by Maelstromeous** [comment]
I do agree leaning towards an extension yes, as I know Bolt's philosophy is to keep things lean and mean. Was mainly wondering on people's opinions on the matter though :)

**Comment by bobdenotter** [comment]
In that case: I'm sure it'll be very usefull for a bunch of people who need this. 👍

**Comment by GawainLynch** [comment]
> Would you care to share why?

Caching is hard… it is a lot of work/code to support something of limited use to 99% of sites. :smile:

**Comment by bobdenotter** [comment]
Closing this here.. Trying to tidy up a bit. :-)
