### ISSUE TITLE
Saving entity relation by repository

### ISSUE THREAD

**Issue by michelangeloRome** [bolt/bolt#6194]
I'm extending bolt and I would save 2 content type and their relations.
I'm using this code to save content and all works well 

```
public function saveAvailability($app, $data)
    {
        // Getting a repository via alias.
        $repo = $app['storage']->getRepository(self::TABLE_AVAILABILITY);

        // save and return id
        return $this->saveGenericEntity($repo, $data);
    }

private function saveGenericEntity($repo, $data) {

        $entCreated = $repo->getEntityBuilder()->create($data);

        if ($repo->insert($entCreated)) {
            return $entCreated->getId();
        } else {
            return -1;
        }
    }
```

If I try to save accordingly a relation with this code I get an error

```
public function saveRelations($app, $fromContent, $fromContentId, $toContent, $toContentId)
    {
        $data = array('from_contenttype' => $fromContent, 'from_id' => $fromContentId, 'to_contenttype' => $toContent, 'to_id' => $toContentId);

        // Getting a repository via alias.
        $repo = $app['storage']->getRepository('relations');

        // save and return id
        return $this->saveGenericEntity($repo, $data);
    }
```

I obtain this error:

_Attempted to load repository for invalid class or alias: relations. Check that the class, alias or contenttype definition is correct._

There is an other approach to save relations? I can't find anything in the docs

Thank you

**Comment by rossriley** [comment]
I think there isn't a short alias setup for relations, if you change your getRepository call to:

```
    // Getting a repository via alias.
    $repo = $app['storage']->getRepository('Bolt\Storage\Entity\Relations');
```

Then everything else should work ok.

**Comment by michelangeloRome** [comment]
Right, forgive me for the stupid question: I thought relations weren't threated as entities.

Thank you

**Comment by bobdenotter** [comment]
This has been resolved, right? If not, feel free to reopen.
