### ISSUE TITLE
[3.2] wrong canonical url with a sub-folder url

### ISSUE THREAD

**Issue by hiousi** [bolt/bolt#6200]
coming from 3.1 (https://github.com/bolt/bolt/issues/5924) canonical url is still wrong on 3.2 when bolt is accessed from a sub folder like `http://exemple.com/myfolder`

now canonical is for home

`/myfolderhttp://example.com/myfolder`

or on some pages

`/myfolder/myfolderhttp://example.com/myfolder/showcase/blub`

is it related to https://github.com/bolt/bolt/issues/6071?

**Comment by bobdenotter** [comment]
Hi @hiousi, Which Bolt 3.2 exactly? That fix landed only in 3.2.4.

**Comment by hiousi** [comment]
@bobdenotter  3.2.4

**Comment by bobdenotter** [comment]
Confirmed: 

![screen shot 2016-12-28 at 20 48 07](https://cloud.githubusercontent.com/assets/1833361/21530152/f7ab4410-cd3e-11e6-94e2-bafcb13486b8.png)

**Comment by CarsonF** [comment]
@hiousi do you mean in the HTML response or are you trying to access it in Twig/PHP?

**Comment by bobdenotter** [comment]
@CarsonF See my screenshot, right above your comment.
