### ISSUE TITLE
[BUG] Session Error Flashbag when using more than one file link, returns the same link again.

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6203]
Scenario:

You have an extension that spits out errors with the following code:

```
$app['session']->getFlashBag()->set(
    'error', 
    'There was an error in generating the thumbnails. Please check your contenttypes.yml, your theme.yml file and ensure the original file exists.'
);
```

The result of the above code is:

There was an error in generating the thumbnails. Please check your `contenttypes.yml`, your `contenttypes.yml` file and ensure the original file exists.

Both instances link to `contenttypes.yml`, when one should link to `theme.yml`.

Details
-------

 - Relevant Bolt Version: 3.2^
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome v55

Reproduction
------------

Build an extension and use the code supplied.

**Comment by bobdenotter** [comment]
The error is located here: https://github.com/bolt/bolt/blob/release/3.2/src/Twig/Handler/AdminHandler.php#L198-L202

The detection is correct, the replacement is too broad. Wanna take a crack at fixing it?
