### ISSUE TITLE
[RFC] - Separate save and add new / save and return buttons

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#6218]
I would like to know if there are other people like me that want to have the two save options bolt has grouped under one button to be split into two separate buttons. If I wanted to save a current record and create a new one it would save me (and other users/customers) 1 click. They would not have to click the arrow button to get to the 'save and create new record' option. So in my opinion it would be more user friendly.

![image](https://cloud.githubusercontent.com/assets/7837653/21591725/f9d0a296-d106-11e6-95d5-716fbd985235.png)

**Comment by bobdenotter** [comment]
Hi, 

At the same time, it would be two extra buttons, cluttering up the screen for everybody that doesn't need them. Because, _if_ we would split it up, it'd make no sense to split it up into two buttons, instead of three: 

![screen shot 2017-01-02 at 17 11 05](https://cloud.githubusercontent.com/assets/1833361/21592530/791b8c62-d10e-11e6-9d91-83959dbe8f2c.png)

I'm not a huge fan of this. My primary concern is that we should try to keep the amount of clutter down.

**Comment by melcarthus** [comment]
Yes, that is a con alright. I understand that once you go down that road you could end up with allot of clutter...

**Comment by mborn319** [comment]
How about saving the last selected as the default? So, any time a user hits the arrow and picks an option, it stores their button action preference in a cookie or localStorage? Obviously, it would make sense to also change the button text to reflect this so users know what to expect when they hit "Save & create new record", for example.

**Comment by SahAssar** [comment]
@mborn319: Well, then anyone providing support for bolt would have an unknown variable to consider... For example I'm guessing both our support dept and our users would not like it if a button changed action without changing appearance or position. (Just my 2 cents in this discussion)

**Comment by Eiskis** [comment]
What about having the extra options in an (persistent) expandable container instead of a dropdown?

**Comment by SahAssar** [comment]
@Eiskis You mean that we basically store if the container was expanded or not and keep that state on later screens?

**Comment by bobdenotter** [comment]
We should not do this in the 3.x branch. For 4.0 we'll do an overhaul of the interface. If you think this is something we should pursue (and ideally something you'd want to help out with), please add it to #6229
