### ISSUE TITLE
[BUG] [Cosmetic] Hovering the Bolt-symbol on the frontend when logged in.

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#6222]
​​I noticed that on a site on which I defined a global magenta `a:hover` background color, the Bolt symbol in the lower right corner takes that color on hover (see attachment). I suggest defining a `none` colour here. 
(And sorry, I have not looked up these lines in the source).

![schermafbeelding 2017-01-03 om 10 54 34](https://cloud.githubusercontent.com/assets/3974120/21604472/9f1eb57a-d1a3-11e6-808a-5304d6605e52.png)

**Comment by bobdenotter** [comment]
Fixed in #6268
