### ISSUE TITLE
[BUG][3.2] "paths" array no longer includes the base url

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#6224]
@CarsonF One for you to check I think.

Looking at this change: https://github.com/bolt/bolt/commit/865954f5f6d724b1107e2bcb6ba706d49f5eb793#diff-4e5c371ae52e9efef268f345acce54b2 now whenever an asset calls `getUrl` the second parameter is always false and so the asset url never has the urlPrefix added to it.

I've just tested on a flat install inside a subfolder and can confirm that calling `paths.theme` returns `/theme/xxxxxxx` rather than the expected `/prefix/theme/xxxxx`

**Comment by CarsonF** [comment]
We don't want the base path applied from ResourceManger for symfony assets as it's applied in the RequestStackContext. 
If you are calling the method outside of the request cycle it won't be included though as there's no request to get the base path from.

**Comment by rossriley** [comment]
Ok, looking into this further I think I've found the problem.

https://github.com/bolt/bolt/commit/865954f5f6d724b1107e2bcb6ba706d49f5eb793#diff-b5ba60dbf22fab2f495585f3cd13532fL358

I've highlighted the start point of the removed lines. What that block did before was if onRequest we detected that we were running in a non-root folder then we pull the prefix from the request and then re-set all of the urls. Because they were removed in this commit then the root url stays as `/` and then later on when the theme url is set, based on the root url it also gets set as `/theme` rather than `/prefix/theme`.

So at the point the Twig globals are set we do have the correct data in, the problem is that `paths.theme` returns `/theme` but the live lookup `app.resources.url('theme')` returns `/prefix/theme`

So the question is, that commit seems to target the double-applying but when we remove it then it never gets single applied either.

**Comment by CarsonF** [comment]
Right the prefix is not set on each url, instead it is prepended when you call `getUrl`

**Comment by CarsonF** [comment]
Ah ok. PathsProxy needs to be back ported to 3.2.

**Comment by rossriley** [comment]
I'll close this one now since the fix is in 3.2 branch and will thus be in the next release.
