### ISSUE TITLE
[RFC] Add web updater

### ISSUE THREAD

**Issue by bjorn3** [bolt/bolt#6239]
Updating currently requires me to download the zip and the use ftp to upload it. This isn't very handy.

I propose adding a button to the web interface to update bolt with one click.

**Comment by bobdenotter** [comment]
This will take a _lot_ of work to do, to do properly. 

Instead, you should really look into using the command line. Updating Bolt to the latest version is then only a matter of typing `composer update` and you're done. Literally takes 1 minute.

**Comment by bjorn3** [comment]
Commandline is not an option because i dont have ssh access.

**Comment by SahAssar** [comment]
Also, to update it via the web interface requires the webserver to have write access to all bolt files, which isn't exactly ideal.

**Comment by bobdenotter** [comment]
@bjorn3 Then you should _get_ command line access. In 2016 there's really no excuse not to have it. A Digital Ocean droplet costs € 5,- per month, and there's even a ton of shared hosting accounts that cost € 30,- or € 40,- a year that allow SSH.

**Comment by SahAssar** [comment]
Closing since this isn't something that we probably can implement in a proper, secure way. If there in the future is a proposal on how to achieve it please reopen or open a [RFC] issue :)

**Comment by bjorn3** [comment]
Maybe add a button to run `php composer.phar update` and clear cache.

**Comment by SahAssar** [comment]
@bjorn3 that'd still require the php user to have write access to the whole bolt install, which is something that we strictly do not reccommend.

**Comment by bjorn3** [comment]
Crazy option: let composer update into another folder and remove write permission. Then let the user rename the folder to vendor. This still requires ftp, but it is faster because you dont have to upload all files with ftp.

**Comment by bobdenotter** [comment]
bjorn3: Those are still hackish workarounds with a high chance of failing, while the alternative (running `composer update` on the CLI) is pretty solid. This will take a lot of work and time to develop and test thoroughly, that we'd better spend on working on features that benefit a large amount of users.

**Comment by bjorn3** [comment]
I understand.
