### ISSUE TITLE
[3.3 beta] URLs ending in `/` no longer work.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6261]
Previously, you could go to the backend using either `/bolt` or `/bolt/`. The first one is obviously correct, but the second one worked as well. 

It no longer seems to do that, though: 

![screen shot 2017-01-15 at 13 05 11](https://cloud.githubusercontent.com/assets/1833361/21962332/90283684-db23-11e6-87bf-54c976c35860.png)

Details
-------

 - Relevant Bolt Version: [ 3.3 ]

**Comment by GawainLynch** [comment]
Ah, that's what is causing that!

**Comment by GawainLynch** [comment]
Fixed in #6288
