### ISSUE TITLE
[3.3 beta] Thumbnails don't work when running in a subfolder.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6263]
Say I have a working Bolt set up at `/bolt-origin`. Bolt is accessible through `/bolt-origin/bolt`, and works OK. 

The frontpage and subpages work as well, but the thumbnails don't. Accessing one directly gives: 
![screen shot 2017-01-15 at 14 07 37](https://cloud.githubusercontent.com/assets/1833361/21962675/ff7f2bb6-db2b-11e6-9843-2e74edd6b0ba.png)

Full trace: 

```
# 1	Silex\Application::abort(403) 
[root]/vendor/bolt/thumbs/src/Controller.php # line 78
# 2	Bolt\Thumbs\Controller::thumbnail(Application, Request, "food-fruit-orange-1286.jpg", "crop", 1600,  1200) 
# 3	call_user_func_array([array], [array]) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 144
# 4	Symfony\Component\HttpKernel\HttpKernel::handleRaw(Request, 1) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 64
# 5	Symfony\Component\HttpKernel\HttpKernel::handle(Request, 1, [true]) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 586
# 6	Silex\Application::handle(Request) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 563
# 7	Silex\Application::run(Request) 
[root]/src/Application.php # line 79
# 8	Bolt\Application::run() 
[root]/index.php # line 12
```

**Comment by CarsonF** [comment]
I can't reproduce this

**Comment by leggewie** [comment]
I tried to reproduce this but being a bolt newbie I'm not sure I did it right.  My bolt 3.2.5 installation is at http://localhost/bolt  I tried to access http://localhost/bolt/thumbs/1000x1000r/agriculture-cereals-field-621.jpg and FWIW it seems to work just fine.

**Comment by bobdenotter** [comment]
@leggewie That's good to know. It's probably something to do with my setup. 

@carson I just triggered this again, but it went away after logging off and on, and I can't reproduce it consistently. Weird. Let's just see if others bump into this, before we spend too much time on it.

**Comment by GawainLynch** [comment]
@bobdenotter without busting out too much effort, are you still able to reproduce this?

**Comment by bobdenotter** [comment]
Nope, can't reproduce anymore. Closing.
