### ISSUE TITLE
[BUG] Problems running Gulp in base-2016

### ISSUE THREAD

**Issue by lenardchristopher** [bolt/bolt#6265]
Details
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 | master ]
 - Install type: [ GitHub checkout | Zip/tarball install | Composer install ]
 - PHP version: [ 5.5 | 5.6 | 7.0 ]
 - Used web server: [ Apache | Nginx ] version [ version ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
 1. **Bug summary**: 
    Running gulp against the default Gulpfile.js results in an error
 2. **Specifics**:
    From command line, if you run gulp against the Gulpfile an error about missing "util/util" is thrown.
 3. **Steps to reproduce**:
    From the [bolt root]/public/theme/base-2016/source directory, run gulp in command line.
 4. **Expected result**: 
    Successful running gulp.
 5. **Actual result**: 
   an error about missing "util/util" is thrown.

I added Foundation's "util/util" back in and no error is thrown. This should work out of the box.

**Comment by bobdenotter** [comment]
I'm having trouble reproducing this. How did you get this. What I tried: 

```
rm -rf bower_components node_modules
bower install; npm install
gulp
```

result: 

```
$ gulp build                                                                         
[16:05:00] Using gulpfile ~/Sites/bolt-origin/theme/base-2016/source/gulpfile.js
[16:05:00] Starting 'javascript'...
[16:05:00] Starting 'foundation-sass'...
[16:05:00] Starting 'theme-sass'...
[16:05:01] Finished 'theme-sass' after 1.08 s
[16:05:01] Finished 'foundation-sass' after 1.38 s
[16:05:04] Finished 'javascript' after 4.62 s
[16:05:04] Starting 'build'...
[16:05:04] Finished 'build' after 71 μs
$
```

**Comment by lenardchristopher** [comment]
It is bolt 3.2.3, but I can see it in the latest github code too.

In the theme/base-2016/source/scss directory is a file named _settings.scss. The first line of code is

`@import 'util/util';`

Do you how a 'util' directory in theme/base-2016/source/scss directory? I don't see it and I get an error running gulp unless it is?

**Comment by bobdenotter** [comment]
In `gulpfile.js`, line 77: 

    includePaths: PATHS.sass

this adds `./bower_components/foundation-sites/scss` to the path: 

![screen shot 2017-01-17 at 16 58 22](https://cloud.githubusercontent.com/assets/1833361/22028060/34c31eda-dcd6-11e6-9132-aff90b320330.png)

Are you _sure_ you've run npm install, and have Foundation 6.3 now?

**Comment by lenardchristopher** [comment]
Oh I see, yeah I didn't run npm install before running Gulp. I definitely didn't have all that populated before running gulp. I was assuming it was supposed to run gulp "out-of-the-box". Thanks for your help!

**Comment by bobdenotter** [comment]
Cool, glad it's working. Closing the issue. 

For others stumbling on this, it's documented here: https://github.com/bolt/bolt/tree/release/3.3/theme/base-2016#working-with-the-scss-files
