### ISSUE TITLE
[BUG] record.link in template with related content not working after upgrade

### ISSUE THREAD

**Issue by andreasrrr** [bolt/bolt#6277]
If I upgrade my installation from 3.2.2 to 3.2.3(and above, tried all version) an exception occur with the {{ record.link}} function in my template. The exception only occur when I use {{ record.link}} on content that I fetched from record.related('contenttype').

Error message:

> An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("slug") to generate a URL for route "contentlink".").

Might be related ?
#6067 

Details
-------

 - Relevant Bolt Version: [ 3.2.3 and above]
 - Install type: [ Composer install/ update ]
 - PHP version: [  5.6  ]
 - Used web server: [ Apache ]

**Comment by bobdenotter** [comment]
Does the content you're fetching via the 'related' have a `slug` field? Can you also verify that all records in that database table have their slugs filled?

**Comment by andreasrrr** [comment]
Might be related ?
#6067

**Comment by bobdenotter** [comment]
That one should be included in one of the latest 3.2.x releases. 

> Does the content you're fetching via the 'related' have a slug field? Can you also verify that all records in that database table have their slugs filled?

**Comment by andreasrrr** [comment]
My thought was that #6067 may broke this for me in 3.2.3 and above. Is it required to have the slug set/saved in db table after this fix? (The content have been imported directly to db table from start)

**Comment by GawainLynch** [comment]
>  Is it required to have the slug set/saved in db table after this fix?

If they are empty, yes.

**Comment by andreasrrr** [comment]
Thanks. Guess I have to set the slug on all records in order to be able to upgrade. Is there a way to batch fix/update all slugs in a table in Bolt? (i have about 5000 records)

**Comment by GawainLynch** [comment]
I have a hack … are all your ContentTypes using a "title" field?

**Comment by andreasrrr** [comment]
Nice, yes

**Comment by GawainLynch** [comment]
OK, give me a few minutes … I'll pop it up GH

**Comment by GawainLynch** [comment]
Right!

You can temporairly modify your `extensions/composer.json` file to add an extra repository, and require `"bolt/slug-fixer": "^1.0"` … e.g.:
```json
    "repositories": {
        "packagist": false,
        "bolt": {
            "type": "composer",
            "url": "https://market.bolt.cm/satis/"
        },
        "fixer": {
            "type": "git",
            "url": "https://github.com/GawainLynch/bolt-extension-slug-fixer.git"
        }
    },
    "require": {
        "bolt/slug-fixer": "^1.0"
    },
```

Then run (first):
```
./app/nut slug-fix --dry-run
```

And that should give you a very long list of records that it **wants** to update.

Once you're happy that it is OK, remove the `--dry-run` and run it again, that will save the updated records to the database.

**Please make sure you back up your database first** … this one is best effort, I have used it and had no problems, but it comes with no warranty :smile:

**Comment by GawainLynch** [comment]
Derp … forgot to add that once you've updated `composer.json`, you will need to run `composer update` in the `extensions/` directory, or the use the web UI.

**Comment by GawainLynch** [comment]
Closing this @andreasrrr but feel free to reopen if needed :smile:

**Comment by mizterp** [comment]
I don't get any exception, but I am not seeing any value for {{ record.link }} in my templates (i.e. it seems that record.link does not exist), even after doing update from Bolt 3.25 to 3.2.6 and all my contenttypes have values in the "title" and "slug" fields.

**Comment by GawainLynch** [comment]
@mizterp do you have records in the database that have empty (NULL) slug values?

**Comment by mizterp** [comment]
@GawainLynch Nope, all records have slug values. I do however have empty tables for a few default contenttypes (pages, entries, showcases), but all my other contenttypes have slug values

**Comment by GawainLynch** [comment]
I'd guess you have a very different problem (guessing) to the one here.
