### ISSUE TITLE
[BUG] Overriding extension templates inside a theme breaks when template_directory is configured

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#6294]
A Bolt extension can add a template path to Bolt's twig for it's own template files. If you then use the same template/folder names inside your theme, you can override the extensions template (provided it's not added with the `prepend` option.
This breaks, if a theme does use a sub folder for it's twig templates via the configuration option `template_directory` inside it's `theme.yml`. 

**Hint**: you can workaround this problem by including the same template directory as configured in your theme.yml in your extensions template paths. This implies that whatever magic makes Bolt prefix the template_directory for a theme's templates does not apply them anywhere else.

**Use Case**: Let's assume you have an extension that can render a HTML block for an image. The extension has it's own template in a folder `<extension>/templates/myimage.twig` and adds the folder via
```
protected function registerTwigPaths(){
    return ['templates'];
}
```
Your theme also has a file `myimage.twig`. Now the template engine will use your theme's template and not the one from the extension as it has higher priority.

If you now store the file in a subfolder `templates` in your theme and configure the option `template_directory: templates` nin your theme.yml, this override process fails.

**Expected behaviour**: The template override mechanism of twig works, no matter where your template base folder is, as long as files and folders are exactly the same (which is the normal behaviour of twig).

Details
-------

 - Relevant Bolt Version: 3.2
 - Install type: Composer install
 - PHP version: 5.5
 - Used web server: Apache

Reproduction
------------
See *Use Case* above. you need an extension, that provides a template and does not specify the `prepend` option.
Create a theme that uses this extensions template and does *not* have a subfolder for it's templates.

Test: Website shows extensions template **OK**

Now copy the extensions template to your theme's base folder. Modify it's contents.

Test: Website shows themes template **OK**

Now move the theme's templates into a subfolder and configure this subfolder in your theme.yml.

Test: Website shows extensions template **Fail**

**Comment by GawainLynch** [comment]
This is standard Twig behaviour if I am understanding correctly.

Twig uses a group of base paths to find the relative path to a template, and theme will (and should be default) always have priority.

This is very specifically why if you need to guarantee the extension templates are loaded, then you should use Twig namespaces.

**Comment by GawainLynch** [comment]
Example:

```php
    protected function registerTwigPaths()
    {
        return [
            'templates'       => ['position' => 'append', 'namespace' => 'MyExtTwigNs'],
        ];
    }
```

```twig
   {{ include('@MyExtTwigNs/my_template_name.twig') }}
```

**Comment by ToBe998** [comment]
Maybe there is some misunderstanding. Yes, twig allows overriding templates with same name.
Problem is, this breaks if a theme uses it's own subfolder which *should* and *is* transparent to twig.

**Comment by CarsonF** [comment]
Does this happen with 3.3? I think it might be fixed there already

**Comment by ToBe998** [comment]
Only tested 3.2 so far. Bit busy atm but will try asap.

**Comment by ToBe998** [comment]
In the middle of a relaunch atm. So, it'l take a bit more time but it's not forgotten ;)

**Comment by GawainLynch** [comment]
Also pinging @ToBe998 for updates :smile: (zero stress, just doing a big triage, so useful info is useful)

**Comment by ToBe998** [comment]
Trying to test in Bolt 3.3-beta2 but need a bit more time until #6413 is resolved.

**Comment by GawainLynch** [comment]
Sweet mate, just didn't want it caught in a spring clean up if it is being worked on. :+1:

**Comment by bobdenotter** [comment]
@ToBe998 Any updates on this? :-)

**Comment by bobdenotter** [comment]
*bump* The "Due for closing unless update" label has been on this issue for two months now.

**Comment by ToBe998** [comment]
Still not getting Bolt 3.3 to run because of deprecated twig functions in bolt's templates (reused inside my widgets template). Namely the `request` function. Bolt crashes as i can not suppress twig exceptions inside a widgets template.

I can gladly take over the PR for that template if you tell me what the new method of getting request parameter is. Couldnt find any replacement for it.

**Comment by CarsonF** [comment]
```twig
{{ global.request.get('foo') }}
```

**Comment by ToBe998** [comment]
PR is committed. Still can't get 3.3 to work as it's now moaning about `$app["resources"]->getUrl("rootUrl")` being deprecated. Tried to find a replacement, but no luck so far.

(`$this->container['url_generator']->generate("contentlink", ['contenttypeslug' => $record->contenttype['slug'], 'slug' => $record->get("slug")], UrlGeneratorInterface::ABSOLUTE_PATH); // $this->container['resources']->getUrl('rooturl').ltrim($record->link(),'/');` failed to generate an absolute url)

**Comment by CarsonF** [comment]
> PR is committed. Still can't get 3.3 to work as it's now moaning about $app["resources"]->getUrl("rootUrl") being deprecated. Tried to find a replacement, but no luck so far.

If you are trying to create a route, use the _url generator_. 

If you are trying to reference an _asset_ (js/css/etc. file), then use Symfony Assets instead.
```php
// For assets (files to be loaded in browser)
$app['asset.packages']->getUrl('img/foo.jpg', 'packageName')
// Valid package names: bolt, files, theme, themes, extensions
```
```twig
{{ asset('img/foo.jpg', 'bolt')
```

**Comment by ToBe998** [comment]
Hurray! I finally got it all working.

The *bad news* is: manually adding the theme folder (that was the workaround for Bolt 3.2) crashes as the system cant find the template.

The *good news* is: We dont care, because that was a dirty hack anyways and the system works fine with the correct paths now, without the theme folder.

In short: many thanks. Please close.
