### ISSUE TITLE
[BUG] bolt market confirmation mail is in HTML

### ISSUE THREAD

**Issue by leggewie** [bolt/bolt#6301]
The confirmation mail for bolt market is in HTML.  That in itself is not so great already.  But there is no formatting used so it's absolutely pointless.  It's get only worse when the given link is then unclickable which would not be the case if the mail was sent in txt format.

**Comment by GawainLynch** [comment]
FWIW, the mails get sent in multi-part MIME, so this _should_ be up to your mail client.

**Comment by leggewie** [comment]
True, but that makes the wasted bandwidth only worse (in some parts of the world this matters, think about being on roaming).

I suggest to send the mails in txt-format only and if that's not an option to at least make the link clickable.

**Comment by SahAssar** [comment]
Most email clients auto-link http adresses in emails these days, right? And the HTML part for a confirmation email for me is 394 bytes, which is small enough that even the email headers for me (1.13kb) was three times the size.

I'm guessing a PR to add the <a> tag to link it in the HTML part would be welcome, but changing the email to make it smaller just seems like bikeshedding to me.

**Comment by leggewie** [comment]
On 27.01.2017 06:10, wrote:
>
> Most email clients auto-link http adresses in emails these days, right?
>

I guess so.  If the mail is sent as txt-only!  That's the point, sending
html as well makes the mail bigger and prevents this.

Sending in HTML and txt at the same time currently bloats the mail
(granted, it's small bloat), adds no functionality at all but takes some
away.  That's not bikeshedding.  Please reopen.

Why close first and ask a question?  I understood triage as asking a
question and deciding what to do based on the answer.  BTW, the answer
to the question had been given in the initial report " It's get only
worse when the given link is then unclickable which would not be the
case if the mail was sent in txt format."  FWIW, I'm using Thunderbird
for mail, certainly not the most uncommon mail client.

> I'm guessing a PR to add the tag to link it in the HTML part would be
> welcome

Can you please point me to the code for this?  I would not assume that
the code for the mails in "bolt market" are hosted in this project, or
are they?  I'm willing to have a look if I knew where.

Thanks.

**Comment by GawainLynch** [comment]
OK, the emails come from Members.

The multi-part MIME was initially implemented, as when I surveyed all actual users a while ago, the response was 100% in favour of HTML **only**, I added the multi-part as I am not a fan of HTML emails myself. Further, these templates are 100% overridable by the implementer as I mentioned in one of your other reports.

On several dozen sites running this now, they all use quite elaborate HTML emails as a **requirement**, so removing the functionality is jut not an option for something I already have used during my work in Haiti, so I know what low bandwidth is like, on a **$5** handset no less. Interesting corollary, rural health workers there use mobile HTML apps, mostly on Digicel networks, and they are sending data, and lots of it, that make this email conversation look quite blown out of proportion.

That aside, if you're willing to work on this, and come up wiht a solution that meets both needs (the market place email will stay HTML by default), the repositiroies are here:
  * https://github.com/bolt/site-market-bolt-cm
  * https://github.com/bolt/marketplace-theme
  * https://github.com/bolt/marketplace-core

**Comment by bobdenotter** [comment]
> Sending in HTML and txt at the same time currently bloats the mail
(granted, it's small bloat)

I strongly disagree with that. It's commonly accepted as Best Practice. The added overhead (a few kilobytes at the worst, I bet) does not ratify the tonne of extra work that's needed for this, as well as the reduced usability for over 99% of the users.

**Comment by leggewie** [comment]
On 29.01.2017 17:42, Bob den Otter wrote:
>
>     Sending in HTML and txt at the same time currently bloats the mail
>     (granted, it's small bloat)
>
> I strongly disagree with that. It's commonly accepted as Best Practice.
>

I'm not arguing that HTML *has* to be dropped.  I'm saying either 1)
drop it or 2) if you use it, then use it and include a proper href. 
Currently, the link is not clickable.

On 29.01.2017 13:54, Gawain Lynch wrote:
> That aside, if you're willing to work on this, and come up wiht a
> solution that meets both needs (the market place email will stay HTML
> by default), the repositiroies are here:
>
>   * https://github.com/bolt/site-market-bolt-cm
>   * https://github.com/bolt/marketplace-theme
>   * https://github.com/bolt/marketplace-core
>

Thanks, that's what I needed.  I think I should be able to do 2) above
pretty easily once I know where.

**Comment by GawainLynch** [comment]
> I'm not arguing that HTML *has* to be dropped.  I'm saying either 1) drop it or 2) if you use it, then use it and include a proper href.

Ah! On board now, early morning emails and all :laughing: 

Yes, that shouldn't be hard to fix, and it potentially a derp in the default template.

**Comment by leggewie** [comment]
OK, so I cloned all three repos in a server in the connected part of the world and grepped for Thank and confirm and did various other things to find where the relevant code is.  Unsuccessfully.

I need a clearer picture of where to tweak this.

**Comment by GawainLynch** [comment]
Understand.

OK, the overrides are defined here in the site's [`app/config/extensions/members.bolt.yml`](https://github.com/bolt/site-market-bolt-cm/blob/master/app/config/extensions/members.bolt.yml#L10-L18)

The default template is in [Members itself](https://github.com/bolt/Members/blob/master/templates/profile/registration/body.twig).

So there are two options on approach:
 * Wrap the `{{ link }}` in the default templates (I'll update the dependency in the lock file for you, much faster from here)
 * Copy the `templates/profile/registration/body.twig` file from Members into the theme directory (rename if you think that makes sense, example below names it `_verification_body.twig`) and update the `app/config/extensions/members.bolt.yml` file to something like

```yaml
forms:
    templates:
        profile:
            parent: partials/_profile.twig
            register: partials/_profile_register.twig
        authentication:
            parent: partials/_authentication.twig
            login: partials/_auth_login.twig
            recovery: partials/_auth_recovery.twig
        verification:
            body: partials/_verification_body.twig
```

**Comment by leggewie** [comment]
OK, so it looks like there's two files that need to be changed, after all.

./Members/templates/profile/registration/body.twig
./Members/templates/authentication/recovery/body.twig

What I don't understand yet, is how the txt part of the mail is generated.  Is the HTML from body.twig simply stripped and that used for the txt part?  If so, having "Please follow this `<a href="http://somedomain.com">link</a>`" would not work, I suppose.

**Comment by leggewie** [comment]
You mentioned in bolt/Members#69 that you did some work to make fixing this issue easier.  As far as I understand the issue itself (the actual implementation of how mails get sent from extensions.bolt.cm) still has to be updated or am I wrong?

**Comment by GawainLynch** [comment]
Moving issue to https://github.com/bolt/Members/issues/86
