### ISSUE TITLE
[RFC] warn in the dashboard when bolt is accessed via IP instead of hostname

### ISSUE THREAD

**Issue by leggewie** [bolt/bolt#6315]
After reading through #5746 and as a challenge to myself, I'd like to see if I can come up with the code to put a warning in the dashboard when bolt is accessed via IP number instead of Hostname.  Seeing that the warning for unconfigured mailoptions comes from ./vendor/bolt/bolt/src/EventListener/GeneralListener.php that's where I shall look first.

I'd appreciate some mentoring.

**Comment by GawainLynch** [comment]
"Challenge accepted" :+1: 

@leggewie All those are moving to [this package](https://github.com/bolt/configuration-notices) in 3.3, so should be a tonne easier to find your way around.

@bobdenotter has lead on that package, so he'll be the next to chime in :smile:

**Comment by bobdenotter** [comment]
Hi @leggewie, yes it'd be a good fit in that package, which will come bundled with the Bolt 3.3 distribution version. The code for that extension is pretty straightforward, but setting it up right now might be quirky. 

You can also grab a `bolt-3.3.x-dev` build from this folder, and hack away in that: https://bolt.cm/distribution. 

Let me know if you're stuck, we'll gladly help.

**Comment by leggewie** [comment]
Can I safely install the extension (which AFAIU it is meant for the upcoming 3.3 release pocket) in a 3.2.5 installation?  More warnings shouldn't hurt, I guess, or is this extension incompatible?

**Comment by GawainLynch** [comment]
It is totally safe, but in 3.2 there is no registration of the service. Given your low bandwidth, it would be safe enough (under this circumstance) to just add these https://github.com/bolt/bolt/blob/release/3.3/src/Application.php#L243-L246 to your installed `vendor/bolt/bolt/src/Application.php` file in the same place … You'll get double notices as you mentioned, but task at hand and all :smile:

**Comment by GawainLynch** [comment]
Fixed in https://github.com/bolt/configuration-notices/pull/14
