### ISSUE TITLE
[Bug] bolt expects to be served from the webroot

### ISSUE THREAD

**Issue by leggewie** [bolt/bolt#6320]
I've learned in bolt/Members#71 that bolt has some known issues when not being served from the webroot.  I'm not sure what they are but it would be good to document here in the tracker what they are and that subdirectory installations are as of now discouraged.

**Comment by Maelstromeous** [comment]
I would have to second this, we should be able to install Bolt on a subroot, e.g. `/blog`. Makes little sense why we have to use root.

**Comment by rossriley** [comment]
Bolt should definitely work from a subfolder, there is a test in the test-suite to ensure that paths are resolved correctly taking into account the sub-folder.

If you do spot any individual problems where this doesn't happen then feel free to open a bug issue and we can fix and get our test coverage of it improved.

**Comment by leggewie** [comment]
On 31.01.2017 04:29, Ross Riley wrote:
> If you do spot any individual problems where this doesn't happen then
> feel free to open a bug issue and we can fix and get our test coverage
> of it improved.

Well, I had done that with this ticket, hadn't I?

Why close the ticket when the issue at hand hasn't been deal with at
all?  I don't get how you guys manage bugs.

**Comment by SahAssar** [comment]
@leggewie: Well, issues are usually for specific bugs. In this case "has some known issues" does not mean a specific bug, so therefore wasn't actionable and was therefore closed. While we don't encourage subfolder installs, they are supported, (as discussed in https://github.com/bolt/bolt/wiki/Dev-meeting-2017-01-10) so if you find any specific bugs and open an issue about it we will try to fix it.

Keep in mind though that not all extensions will support it, and it is the agency of every extension developer to support or not support them if they so prefer.

**Comment by rossriley** [comment]
sorry @leggewie what I meant was that we do actively fix bugs that are found for subfolder installs, eg #6071 was recently fixed and #6263 is currently being fixed for 3.3.

As far as I know there are no problems with running Bolt in a sub-folder other than those we have issues for, so if you find a specific problem then please open an issue with some details of exactly what isn't working correctly and we'll get it fixed.

**Comment by leggewie** [comment]
Well, I referenced bolt/Members#71 which has both a blow-by-blow account of how things went wrong for me with a subdirectory install (granted with an extension) and where I'm being told that "sub-directory installs are not officially supported, and have known issues in Bolt at present" quote @GawainLynch.  That's an actionable bug.  Close the ticket when subdirectory installs are officially supported.  But it seems like there is some disagreement over whether or not they are.
