### ISSUE TITLE
Noscript showing as text instead of html

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#6337]
![screen shot 2017-02-01 at 11 59 03 am](https://cloud.githubusercontent.com/assets/932566/22519451/e79784a6-e875-11e6-906f-d35c593a1196.png)

In Chrome 55

**Comment by bobdenotter** [comment]
I can't reproduce this. See my screenshot: 

![screen shot 2017-02-01 at 21 16 16](https://cloud.githubusercontent.com/assets/1833361/22524470/adb66556-e8c3-11e6-8d49-92190dcc0348.png)

Did you just disable Javascript in the inspector console?

**Comment by bobdenotter** [comment]
Slightly related: How did you get to the second "Template" tab, if you have no Javascript?

**Comment by CarsonF** [comment]
> Did you just disable Javascript in the inspector console?

Yeah I did.

Maybe it was fixed in Chrome 56?

**Comment by CarsonF** [comment]
> Slightly related: How did you get to the second "Template" tab, if you have no Javascript?

I loaded the page with the anchor `#template`

**Comment by bobdenotter** [comment]
Closing this, feel free to re-open if it pops up again.
