### ISSUE TITLE
[Config] Remove hash_strength

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#6346]
`hash_strength` doesn't do anything anymore.

**Comment by bobdenotter** [comment]
Nice! I think that's actually a leftover from the olden PHPass days.

**Comment by GawainLynch** [comment]
> Nice! I think that's actually a leftover from the olden PHPass days.

Yes, it is, and yes it is unused.

**Comment by rossriley** [comment]
Just out of interest, why did we decide to drop this as an option, looks like the default is 8 and whilst by no means a low work factor, is probably quite a bit less than most people are using unless hardware is a problem.

I was tending to default to 12 on average VPS machines and a decent AWS/Google Cloud instance is fine with even higher values.

**Comment by GawainLynch** [comment]
@rossriley I might have total :koala: brain, and am missing where you're going … if so send :leaves: 

But that parameter was for PHPass, that we stopped using in favour of the polyfilled PHP 5.5+ functionality from `passwordlib/passwordlib` … that being chosen as it allows us to check a v1 or v2 password at fist login after upgrade (per user), and then re-save an updated hash.

**Comment by bobdenotter** [comment]
While we don't use this now, we _will_ again when we move to using `password_hash()` everywhere.  So, we shouldn't remove this.
