### ISSUE TITLE
Mcrypt deprecated in  PHP 7.1

### ISSUE THREAD

**Issue by halojoy** [bolt/bolt#6348]
At the install of Bolt 3.2.6 using PHP 7.1.1
I get the following errormessage:

Deprecated: Function mcrypt_module_open() is deprecated in C:\Apache24\htdocs\bolt\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 75

Deprecated: Function mcrypt_enc_get_block_size() is deprecated in C:\Apache24\htdocs\bolt\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 76

Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in C:\Apache24\htdocs\bolt\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 77

Deprecated: Function mcrypt_module_close() is deprecated in C:\Apache24\htdocs\bolt\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 86

So, I stop the installation and I am unhappy.

**Comment by GawainLynch** [comment]
Already deprecated as an include, and removed in 3.3
