### ISSUE TITLE
[BUG] Cant save custom translation

### ISSUE THREAD

**Issue by versh23** [bolt/bolt#6349]
Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 7.1
 - Used web server: Nginx 1.10.1

Reproduction
------------

- install boltcms by composer
- add new contenttype
- go to bolt/tr/contenttypes 
- change some translation string
- save

there are no folder with translation strings in 
![image](https://cloud.githubusercontent.com/assets/1758392/22595849/374d9966-ea3a-11e6-8425-0b1f049aad5c.png)

so, i cant save translation

**Comment by versh23** [comment]
After investigation, I discovered that bolt save a file 
D:/web/orion-14/vendor/bolt/bolt/app/resources/translations/ru_RU/contenttypes.ru_RU.yml

why vendor? not local app/

**Comment by bobdenotter** [comment]
Because those files are not meant for "custom translations".. If you use that functionality to add missing strings, you're more than welcome to make a PR for it, so others will benefit from it too.

**Comment by versh23** [comment]
@bobdenotter ok. what functionality i must use for adding missing strings ? for exmaple - translate new contenttype in nav bar

![image](https://cloud.githubusercontent.com/assets/1758392/22599617/986d4cf6-ea48-11e6-8519-23d6310500aa.png)

**Comment by bobdenotter** [comment]
You can use it like this:

```
albums:
  slug: albums
  name: "My albums"
  singular_slug: album
  singular_name: "My album"
```

Just use the name to label it what you want.

**Comment by versh23** [comment]
oh.. sorry, it`s work!

**Comment by bobdenotter** [comment]
No worries, glad it works! 👍
