### ISSUE TITLE
[RFC] Can't login into Bolt on IDN domain

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#6359]
Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx version 1.10.0 on Ubuntu 16.04.1 LTS
 - Used web server config: provided by documentation on [bolt.cm](https://docs.bolt.cm/3.2/installation/webserver/nginx)

Reproduction
------------

1. Go to IDN-enabled website on http://www.xn--k1agdan.xn--p1ai/bolt/login
2. Enter test login / password: test / test_password
3. 302 Find and same login page again

P.S.
It works fine in case of login via ip address using Firefox or IE(Chrome is not working due to cookie policies).

**Comment by C4Grey** [comment]
I've moved further in my investigation and tried to convince Bolt to be a little bit less suspicious:
cookies_use_remoteaddr: false
cookies_use_browseragent: false
cookies_use_httphost: false
Then I've wiped cache folder, re-created it with all required permissions...and it worked. And here comes the strange part: I've removed those configs, deleted the cache folder again...and it still works. May the problem be related to PHP sessions mechanism?

**Comment by C4Grey** [comment]
It seems like I hane an idea why such a thing happened: our domain was not resolving correctly on the root CNAME and worked only with www-prefix. Modern browsers consider themselves smarter than users and redirects from root adress to www sub-domain automatically(i.e. caches successful redirect in case of DNS error on a root)...and it seems like cookie was attributed by the root domain.
Don't know for sure, if there was really any Bolt-related issues, or it was totaly our provider's fault. Well, I've migrated to another NS-server, and now I have a good news: Bolt is working well with IDN domains :)

**Comment by GawainLynch** [comment]
Sweet … Got to love those days when providers make you work your butt off … and it's their fault.

I'll close this, but feel free to reopen should it be needed. :+1:
