### ISSUE TITLE
[BUG] Broken manifesto link  in contribution doc

### ISSUE THREAD

**Issue by zquintana** [bolt/bolt#6366]
Hey guys, this one is simple. I was reading through your contribution doc (because I want to contribute), and I tried clicking through to your manifesto under https://github.com/bolt/bolt/blob/release/3.2/.github/CONTRIBUTING.md#2-id-like-to-requestpropose-a-feature, and was greeted with a 404. Maybe put that in the repo for easy linking?

**Comment by SahAssar** [comment]
Closing, fixed in #6367 😄
