### ISSUE TITLE
Sessions partially broken when serving from IP address

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6377]
~Can't quite narrow it down, but sessions seem to not be created under the build-in web server the second you update to FS2.1~

**Comment by GawainLynch** [comment]
Well, this much took all day:
```
Twig_Error_Runtime in Template.php line 447:
An exception has been thrown during the rendering of a template ("There is no default asset package, configure one first.") in "@bolt/_base/_page.twig" at line 78.
```

**Comment by GawainLynch** [comment]
Oh dear … Looks like it is Chrome Version 56.0.2924.87

**Comment by bobdenotter** [comment]
Added a "configuration notice" check for this: https://github.com/bolt/configuration-notices/pull/14

**Comment by CarsonF** [comment]
Are you trying to use different hostnames or different base paths?

We restrict sessions to specific hostnames and base paths with the `restrict_realm` option [here](https://github.com/bolt/bolt/blob/release/3.3/src/Provider/SessionServiceProvider.php#L120).

**Comment by GawainLynch** [comment]
I first hit it with a `composer create-project bolt/composer-install --no-interaction` and then `./app/nut server:run` … moved the `0.0.0.0` to `localhost`, then to a couple of single word host names (that only exists in my `/etc/hosts`)

I know I am a newbie and all … but I have read the standards a few times, and set up a web server once for my cousin using Microsoft Front page so I'm an expert you know :stuck_out_tongue_winking_eye:

**Comment by GawainLynch** [comment]
Fixed in one of the recent sets of heavy changes
