### ISSUE TITLE
Repeater with required fields and empty first

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#6378]
If you have a repeater with a required field and your list is empty, Bolt says missing required field. But I don't want to specify that first item. An empty list should be fine, or at least configurable.

**Comment by GawainLynch** [comment]
Does #6459 close this?

**Comment by rossriley** [comment]
I think so, also added to docs here: https://github.com/bolt/docs/pull/685

**Comment by GawainLynch** [comment]
WFM
