### ISSUE TITLE
Make pager template more semantic

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6383]
c.f. https://github.com/bolt/bolt/pull/6381#issuecomment-280251768

**Comment by GawainLynch** [comment]
Ping @bobdenotter & @CarsonF 

Not sure who's court this should land in, but we'll get it sorted :smile:

**Comment by bobdenotter** [comment]
What I meant by that comment, is that the HTML for the pagination thingy is not very _semantic_. We can improve the HTML, so that it's more meaningful. Making it both easier to style, as well as more useable in the frontend.

**Comment by GawainLynch** [comment]
:timer_clock:

**Comment by GawainLynch** [comment]
Bumping to 3.5, you have higher priorities on 3.4.
