### ISSUE TITLE
[BUG] showImage() does not implement proportional scaling

### ISSUE THREAD

**Issue by Cal7** [bolt/bolt#6387]
The source of the helper function showImage() ([here](https://github.com/bolt/bolt/blob/release/3.2/src/Twig/Handler/ImageHandler.php)) states to "Set width or height parameter to '0' for proportional scaling". However, this does not happen - instead the image is simply given a width/height of 0.

Details
-------

 - Relevant Bolt Version: 3.2.7
 - Install type: Composer
 - PHP version: 7.0
 - Used web server: Apache 2.4

Reproduction
------------

In a twig file, write `{{ dump(showimage(record.image, 500, 0)) }}` (obviously ensuring that `record` is set and contains an image). Then the output will be `<img src="/thumbs/500x0c/alarm-clock-gold-hands-of-a-clock-1778.jpg" width="500" height="0" alt="">` - note the height attribute of 0 (the src attribute will obviously differ).

**Comment by SahAssar** [comment]
IIRC this was because when I looked over the image functions last time there was a discussion about 0 should not be interperted as "not defined". So `{{ dump(showimage(record.image, 500, null)) }}` is the correct way IIRC.

**Comment by SahAssar** [comment]
Fixed in bolt/docs/pull/660, please reopen if there are more uncertainties! :)
