### ISSUE TITLE
[BUG] paths.current is the same as paths.currenturl

### ISSUE THREAD

**Issue by lo-cwb** [bolt/bolt#6404]
Hi,

I've found a little issue in the twig paths variable with bolt 3.2.7, paths.current return the same as paths.currenturl but depending on the doc the result must be:

paths.currenturl -> http://example.com/­entry/lorum-ipsum
paths.current -> /entry/lorum-ipsum

Here is my test code: 

`
{{ dump(paths.current) }}
`
`
{{ dump(paths.currenturl) }}
`
`
{{ dump(path('faq')) }}
`

and here, the result:

`
"http://localhost:8000/page/faq"
`
`
"http://localhost:8000/page/faq"
`
`
"/page/faq"
`

Please, let me know for a solution ;)

**Comment by GawainLynch** [comment]
That is a v1 legacy. Not longer supported from v2 onwards.

**Comment by lo-cwb** [comment]
What about update the doc https://docs.bolt.cm/3.2/cheatsheet ?

**Comment by GawainLynch** [comment]
Sorry mate, I am grumpy at you for something that has zero to do with you, and I offer my humble apologies.

This is a failing of our team, and it is a lot of documentation to cover off, and we haven't always done the best (on limited resources).

Please believe me when I say that one of our awesome core team will take over and pick this up… :+1:

**Comment by shyim** [comment]
The right value is also available in paths, but its not accessible in twig. I had this problem yesterday also.... I added the variable with a custom extension globaly...

**Comment by GawainLynch** [comment]
> The right value is also available in paths, 

Paths only work in a limited set of circumstances. Please see path_resolver and `{{ asset() }}` docs … app.paths is v1 … is dead … is not supported… is not portable … and will give problems

**Comment by lo-cwb** [comment]
@GawainLynch no problem, apologies accepted.

The crappy solution I use for the moment is to work with `paths.hosturl ~ path('faq')` and `paths.currenturl` to determine the current page.

**Comment by SahAssar** [comment]
@lo-cwb: I think the better way to do that might be to use the `|current` filter/function, see here: https://docs.bolt.cm/3.2/templating/templatetags#current

**Comment by lo-cwb** [comment]
@SahAssar Your solution works in a record frontend controller not in a template frontend controller as in my case, sorry I forgot to mention it.

**Comment by SahAssar** [comment]
@lo-cwb Ah, in that case it'd be better to compare `app.request.get('_route')` and `app.request.get('_route_params')` (if there are route params) IMO.

**Comment by lo-cwb** [comment]
@SahAssar Better an cleaner solution, Thanks!
