### ISSUE TITLE
[bug] recurrence of #5084 (images not loading after cache clear)

### ISSUE THREAD

**Issue by thely** [bolt/bolt#6407]
About a year later on Bolt 3.2.3, I'm having the exact same problem as [this bug from last April](https://github.com/bolt/bolt/issues/5084). It's not happening on my localhost, just on my live site. It's not happening for images that are pulled directly from my theme's images folder, but it is happening on any image that I uploaded through the admin view. 

In the first view of a page after a cache clear, uploaded image(s) don't load. Subsequent views of that page display the image(s) fine, but you have to reload every page that contains uploaded images to make the 500 Internal Server Error go away. I don't have a ton of Symfony debugging experience, but if you lead me through some troubleshooting, I would love to help shoot these troubles. Sqlite for DB at the moment, 3.2.3 updated through the admin view.

(Sorry if double-posting bugs is bad form - the old one seemed like it had been solved.)

**Comment by GawainLynch** [comment]
> Sorry if double-posting bugs is bad form - the old one seemed like it had been solved

Nah, a bug is a bug… and if it reappears that's good enough reason for me.

While we wait for the European crew to wake up … Can you update me on a few things:
* PHP version
* Web server version 
* Is [`save_files`](https://github.com/bolt/bolt/blob/release/3.2/app/config/config.yml.dist#L208) set to true or false
* Are you getting anything useful 404s or 500s in the Network tab of your browser tools?

**Comment by GawainLynch** [comment]
> I would love to help shoot these troubles.

Oh, and you really know how to put a smile on the face of someone doing bug triage with comments like that :+1:

**Comment by thely** [comment]
What I'm assuming are typical DreamHost settings: PHP 5.6 Fast CGI (though 7.0 is available to me if you want to try it), probably Apache 2.2.22. `save_files` is set to true. Only non-default thing I have server-side is that gzip is enabled.

As for anything useful in dev tools - just getting 500s in the first post-cache page loads, the response HTML has the "Whoops, something went wrong" message. I checked the thumbnail URL between first load and second load - it's the same URL, so nothing's wrong there.

**Comment by GawainLynch** [comment]
Apache 2.2 & PHP 5.6 should be fine … both supported.

OK, the 500s are where we need to look, you can get more data than just "Whoops …" if you enable debuging in `app/config/config.yml` (don't forget tot turn it off when done).

I am guestimating that there is a filesystem problem, somewhere around the `save_files` part, but enabling debug, repeating the error state and then looking at the "Response" sub-tab on the line that has a 500 is going to give us the next step…

**Comment by thely** [comment]
Weird - with debugging enabled, the behavior is the same, but all the failed requests show up as 200 OK under the Network tab with no response body. Disabling debugging makes them show up as 500 Internal Server Error again. The Symfony profiler doesn't show any 500s, at least none that I could see, which might make sense if it's somehow suppressing the errors? Is there anything I should hunt for?

**Comment by GawainLynch** [comment]
Hmm … thinking about it, I am not sure that `save_files` gets used when debugging is on … I was going off _Gawain's Status Quo Test Steps_ … which usually lead me to find something I've completely overlooked.

I'm going back to a file system error though in my head … Assuming you're using a normal install, and your document root is `public/` can you try to set `public/thumbs/` to 777 and see what you get (debug off)

**Comment by thely** [comment]
Aah! Before we do that, I tried just accessing the image directly, got the following PHP error:

```
Fatal error: Class 'finfo' not found in /home/rebbro21/dev.becky-brown.org/vendor/league/flysystem/src/Adapter/Local.php on line 305
```

Plus something with more Bolt-specific error formatting:

```
ClassNotFoundException in Local.php line 305:
Attempted to load class "finfo" from the global namespace.
Did you forget a "use" statement?
	1.	in Local.php line 305
```

**Comment by GawainLynch** [comment]
Derp … that will be it … missing PHP extension(s) … [c.f.](https://docs.bolt.cm/3.2/getting-started/requirements#)

**Comment by thely** [comment]
Uff, so I guess this means a cool trip to PHP.ini to see what else is missing apart from `fileinfo`? Haven't had any other weird behavior pop up yet, but it's probably best to nip this sort of thing before it confuses me again.

**Comment by GawainLynch** [comment]
Yeah … In Bolt 3.3 we're adding an optional package, that will be installed by default on archive installs, that will give admin notices on a few more of these issues.

**Comment by thely** [comment]
Significantly less painful than I thought it might be - enabled `fileinfo`, problem solved. And we didn't even have to wait for Europe. 👍

**Comment by GawainLynch** [comment]
> And we didn't even have to wait for Europe. :+1:

Hehe … Lucky I am on a trip to Australia then … Compatible time zones FTW.
