### ISSUE TITLE
[BUG] User created slugs are not slugified or verified

### ISSUE THREAD

**Issue by sablonier** [bolt/bolt#6408]
- Relevant Bolt Version: [ 3.2.6 ]
 - Install type: [ GitHub checkout ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache 2 ]

1. **Summary**:When authors do a mistake in the slug/permalink field in the backend, i.e. leaving a trailing slash accidentally, or typing something like '/I/do/not/get/the/routing/system' as a slug, the record could be saved but then the backend has gone, because of the invalid slug.
 2. **Specifics**:
    * Throws an twig error for the backend, i.e. for http://www.example.org/bolt, after a record got an invalid slug saved
 3. **Steps to reproduce**:
    * Edit a slug or permalink with an invalid slug
 4. **Expected result**: 
    * Trying to save an invalid slug should throw an error message to the authors before the record is saved
 5. **Actual result**: 
    * After saving a record with an invalid slug a twig exception is thrown and the backend has gone, 

Here is an example of an error with an invalid trailing slash saved:

Uncaught Exception: Twig_Error_Runtime

Twig_Error_Runtime in Template.php line 447:
An exception has been thrown during the rendering of a template ("Parameter "slug" for route "contentlink" must match "[^/]++" ("est-enim-effectrix-multarum-et-magnarum-voluptatum/" given) to generate a corresponding URL.") in "@bolt/editcontent/_buttons.twig" at line 60.

**Comment by SahAssar** [comment]
Verified in bolt 3.2.7, I'm guessing that we need to run user-created slugs through the slugifyer too.

**Comment by GawainLynch** [comment]
Fixed in #6411 and will be released with v3.3.0
