### ISSUE TITLE
[3.3 BC] Extensions break on missing `load()`.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6420]
After updating from 3.2.7 to 3.3 beta, my Gridview extension broke with this exception:

![screen shot 2017-02-25 at 17 24 44](https://cloud.githubusercontent.com/assets/1833361/23332770/78baedee-fb7f-11e6-99e4-f8a65e80fd9a.png)

Can easily be "fixed" by adding this to the class that implements `FieldInterface`:

```
    public function load()
    {
        return;
    }
```

However, this is a BC break, that should be fixed. :-)

**Comment by bobdenotter** [comment]
Same for missing `persist()`, by the way. 

![screen shot 2017-03-04 at 13 31 38](https://cloud.githubusercontent.com/assets/1833361/23578787/ebd59fb8-00de-11e7-8c7c-fac7a7e93808.png)

**Comment by bobdenotter** [comment]
@rossriley In the case of `persist`, adding a `public function persist() { }` also makes the error go away, but it also means that the data input doesn't actually get saved in the DB. :-)

**Comment by GawainLynch** [comment]
Fixed in #6458
