### ISSUE TITLE
Suggestion: Next / Previous links in Backend

### ISSUE THREAD

**Issue by tilllt** [bolt/bolt#6425]
It would be great to have a "Next Record" and "Previous Record" (or, more precise: "Save and Edit Next / Previous")  link in the Backend. For example, when modifying the Contenttype of already existing data, i.e. adding a field which has to be set for each record, the current way to always go through the menu of that CT is very time consuming. Totally great would also be having the "Next Record" and "Previous Record" links additionally as Keyboard shortcut, for quick editing.

**Comment by bobdenotter** [comment]
Hmm, maybe.. Let's think on how to do that. 🤔

**Comment by SahAssar** [comment]
This seems like another one of those issues that we will get to sooner or later, but it won't be because of this. Closing due to lack of progress/interest.
