### ISSUE TITLE
[RFC] Allow root user with empty password

### ISSUE THREAD

**Issue by robations** [bolt/bolt#6426]
Allow an insecure password with an extra database configuration property such as `allow_insecure_password: true`. For most people, having a private development machine with a root user with an empty password is a convenience and not a large risk.

Details
-------

 - Relevant Bolt Version: 3.3
 - Install type: n/a
 - PHP version: n/a
 - Used web server: n/a
 - For UX/UI issues: n/a

On a private development machine having a user root with an empty password saves time managing and entering passwords. If you are a consenting adult and wish to allow this with Bolt it would be useful to allow this by setting an additional configuration key such as `allow_insecure_password: [boolean]`. This would require just a small change in the database validation logic.

**Comment by bobdenotter** [comment]
Hi @robations, 

I'm sorry, but we will not allow this. We've discussed this at length, and decided that it would be encouraging bad practice. 

You should really set a (any, really) password on your local root user, or just use SQLite if you want to get a quick start.

See also #262, #863

**Comment by robations** [comment]
Ah sorry, I did a quick search for a previous discussion but didn't see anything.

I don't agree, but will have to respect your previous decision :) I'm just glad your CMS doesn't open all the PHP code to public access/fuzzing attacks, unlike some others.

**Comment by bobdenotter** [comment]
Thanks! We try to make sane decisions for things like this. Sometimes this means we cannot please everybody at once, and i'm glad you can see that. 👍
