### ISSUE TITLE
Generated cookies_domain config is cached

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#6431]
Currently if one does not set the cookies_domain option in the config it will be autogenerated from globals [here](https://github.com/bolt/bolt/blob/master/src/Config.php#L345-L368), but it is then cached with the rest of the config too, which can lead to issues on multi-domain sites.

Assigning to @CarsonF per discussion on slack :)

**Comment by shyim** [comment]
I had the problem before 2 weeks also. The answer from irc was its a feature and it doesent make sense when its empty.. :/
