### ISSUE TITLE
[BUG] Locale ru_RU ignored

### ISSUE THREAD

**Issue by sibputnik** [bolt/bolt#6451]
Hi.

I works in ru_RU locale and it brilliant in developers computer. But when I copy and run Bolt in web-hosting, it works in en_EN locale. I change locale settings to en_EN and to ru_RU, but actualy I see English backend. I set "locale: nl_NL" and language has changed. But I can't turn it to ru_RU

What I done:
1) dev comp: clear cache, zip all files.
2) copy zip to hosting and unzip it.
3) have error from my local extension and clear all cache by hands
4) enter to backend, but have no ability to work in ru_RU locale

You can try it here:
xn--h1adhkt.xn----7sbabe8anmu4afdkn.xn--p1ai/bolt
user: root
pwd: rootroot

Details
-------
 - Relevant Bolt Version: 3.2]
 - Install type: Zip/tarball install 
 - PHP version: 5.6
 - Used web server: Apache

**Comment by sibputnik** [comment]
I set as shown bellow and it help me. But if I set translation cache to true, or locale to ru_RU, I have English dashboard again.

locale: ru
caching:
    translations: false

**Comment by SahAssar** [comment]
@sibputnik I think this is the same basic problem as #5727, in that the translation cache is pretty persistent. Try deleting the `trans` folder in the `app/cache` folder, if that fixes it for you it's the same issue as above (and will hopefully be fixed at the same time).

**Comment by GawainLynch** [comment]
Closing this as mentioned by @SahAssar this is being tracked in #5727 and will land in 4.0-dev in the coming months.
