### ISSUE TITLE
[Question] MailOptions with Windows Authentication

### ISSUE THREAD

**Issue by Jovinsson** [bolt/bolt#6452]
Hi All,

Bolt Version: 3.2
OS: Windows Server 2012 R2
Web: XAMPP v3.2.2

Hoping someone can assist with how I would get the mailoptions setup in the main configuration file as my server uses Windows Authentication based on a whitelist allowing the server to simply send.

For example, a previous project was able to send emails using PHPMailer() with the following setup:
```
$mail = new PHPMailer;
$mail->isSMTP();
$mail->Host = 'smtp.mycompany.net';
$mail->SMTPSecure = 'TLS';
$mail->Port = 25;
$mail->setFrom('sendemailshere@mycompany.net', 'Admin');
$mail->addReplyTo('sendemailshere@mycompany.net', 'Admin');
```

Note how no username or password are provided.

Any clues?

**Comment by GawainLynch** [comment]
My guess is something very simple being over looked at your end. The options are [passed as-is to the Swiftmailer service](https://github.com/bolt/bolt/blob/release/3.2/src/Provider/MailerServiceProvider.php#L25-L28)

FWIW the [Swiftmailer documentation](http://swiftmailer.org/docs/introduction.html) is probably eht  next place to look.

Also, port 25 for TLS is very much non-standard, are you sure you don't want 587?

**Comment by Jovinsson** [comment]
Appears that SwiftMailer doesn't support NTLM authentication properly. 

I made a modification to the ResetPasswordNotification source file which sends the mail content and address through to a sister application via cURL. I couldn't get it to be able to make use of PHPMailer in the middle of the function. 

Bit clunky, but works!

**Comment by Jovinsson** [comment]
Happy to share the code if anyone would like!
