### ISSUE TITLE
gulp-minify-css needs replacement in base-2016 theme

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#6461]
The current base theme (base-2016) needs some love: Gulp Minify is deprecated and should be replaced with https://www.npmjs.com/package/gulp-clean-css

> npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css

(Bolt 3.2.8)

**Comment by bobdenotter** [comment]
If you can, any help with this would be appreciated.

**Comment by peterboorsma** [comment]
Let me see if I can figure it out :)
