### ISSUE TITLE
[BUG] Repeater data is not retrieved on frontend

### ISSUE THREAD

**Issue by diskoflorian** [bolt/bolt#6465]
- Bolt Version: 3.2.7
 - Install type: Composer install
 - PHP version: 7.0 (fpm)
 - Used web server: Nginx

Hi,

I have some trouble with repeaters. 
In fact, I added a field on page content type (pages_fr, because I have a multilingual website), here is my configuration :
![screen shot 2017-03-08 at 16 56 11](https://cloud.githubusercontent.com/assets/20900621/23711678/d12d22a4-0420-11e7-806e-a74d5c552863.png)

In the back office, everything is ok, the repeater appears and the data is well persisted:
<img width="726" alt="screen shot 2017-03-08 at 16 58 42" src="https://cloud.githubusercontent.com/assets/20900621/23711556/86efdc68-0420-11e7-9331-fd3ae8d036f5.png">

However, in frontend, when I try to access to the data, it is empty :(
<img width="456" alt="screen shot 2017-03-08 at 16 59 12" src="https://cloud.githubusercontent.com/assets/20900621/23711598/9892333a-0420-11e7-9bc8-6eb936425ec8.png">

Do you have any idea about this issue ?

Thank you for your help !

**Comment by bobdenotter** [comment]
This seems correct. You'll need to iterate over `slider` to get the items one by one. See the docs about this subject: https://docs.bolt.cm/3.2/fields/repeater#example-usage-in-templates

(I'm closing this as it is a question, feel free to re-open if you're certain it is a bug instead)

**Comment by diskoflorian** [comment]
Hi @bobdenotter,

Thank you for the link of the documentation x)

I followed this part but it doesn't work :
![screen shot 2017-03-08 at 17 08 30](https://cloud.githubusercontent.com/assets/20900621/23712074/079f351a-0422-11e7-8797-40c6056ad16f.png)

The result is :
<img width="1229" alt="screen shot 2017-03-08 at 17 09 58" src="https://cloud.githubusercontent.com/assets/20900621/23712095/191a3416-0422-11e7-8088-3ec33012a050.png">

{{ dump(slide) }} => RepeatingFieldCollection with empty elements
{{ slide.get('slide_title') }} => blank / nothing / empty :(

**Comment by bobdenotter** [comment]
Can you try to explicitly set the slug? 

```
pages_fr: 
  slug: pages_fr
  singular_slug: page_fr
```
Might be the same issue as #6438

**Comment by diskoflorian** [comment]
You save my day ! Thank you very much 👍

**Comment by bobdenotter** [comment]
You're welcome! :-)
