### ISSUE TITLE
Discrepancy in `{{ record.foo }}` vs `{{ record.get('foo') }}`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6472]
There's a discrepancy in how these are handled.. The latter isn't output as `\Twig_Markup`.

Example: 

```
    <h1>{{ record.title }}</h1>

    <hr>
    <p>record.teaser:</p>

    {{ record.teaser }}

    <hr>

    <p>record.get('teaser'):</p>

    {{ record.get('teaser') }}

    <hr>
```

Result: 

![screen shot 2017-03-10 at 17 24 01](https://cloud.githubusercontent.com/assets/1833361/23803295/63a1449e-05b6-11e7-9336-94e7e0e66e99.png)

Details
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 ]

**Comment by werner-rammer** [comment]
I experienced a (probably) similar problem: I upgraded from 3.0 to 3.2.9 and found that the HTML tags were visible in the output (the same as the ```reord.get('teaser')``` example above).
I used this in ```entry.twig``` (which worked fine in 3.0):
```
{{ fields(exclude = ['image']) }}
```
After some experimenting I modified this to:
```
    {{ record.teaser }}
    {{ record.body }}
```
i.e., include the fields explicitly. This resolved the problem (see ```record.teaser``` above).

**Comment by CarsonF** [comment]
Pretty sure this is only for repeaters, as they don't render twig/markdown or mark content as safe yet.

**Comment by bobdenotter** [comment]
@CarsonF Look at the code example above. It's not just repeaters.

**Comment by bobdenotter** [comment]
The discrepancy is still there, but the risk of introducing new bugs when changing this was too high, so instead we did what we did in #6474.
