### ISSUE TITLE
RFC - vertically resizable text boxes for config

### ISSUE THREAD

**Issue by ChangePlaces** [bolt/bolt#6476]
Being forced to work in a (vertically) small text box on the web editor for the content types yaml is hard going. I'd like to recommend that it's made vertically resizable to mimic the behaviour of a text frame. This is really easy to fix: just add a `resize:vertical` to the outer div that contains the code. This is CSS3.

**Comment by bobdenotter** [comment]
Unfortunately, the code editing component we use ([codemirror](http://codemirror.net/)) doesn't easily allow this. It resizes to fit the viewport by default, and I think that's the best we can do, within reason. 

Feel free to reopen, if you think it can be fixed.

**Comment by ChangePlaces** [comment]
add some jquery/js that, after codemirror has done its magic, adds the resize:vertical style by adding a class.
