### ISSUE TITLE
[BUG] Install a new Extension is doesn't working

### ISSUE THREAD

**Issue by readingsnail** [bolt/bolt#6477]
- Relevant Bolt Version: 3.2.8
 - Install type: GitHub checkout
 - PHP version: 7.0
 - Used web server: Nginx 1.10.3

Reproduction
------------

i wanna install some extension or theme, so try this in my bolt

[https://i.imgur.com/05d9F6W.png](https://i.imgur.com/05d9F6W.png)

it's conclude this [https://i.imgur.com/AqGkgAU.png](https://i.imgur.com/AqGkgAU.png)

so i don't know what's going to happen. no error message, sorry.

and all permission is 777 (not making to public directory, so weird) and composer is full update status.

**Comment by bobdenotter** [comment]
That extension unfortunately isn't available for Bolt 3. Other, current extensions will be installable, i bet. 

If you're still stuck, feel free to join us in our slack channel for support. :-)
