### ISSUE TITLE
[Bug] Failed to parse SVG image with text/html mime type

### ISSUE THREAD

**Issue by tilllt** [bolt/bolt#6487]
After updating Bolt to 3.2.9, the "Select from Server" function in the backend does not work anymore, the dialog shows a spinning dotted disk and then fails with a reload symbol. This is likely to be a config specific error and not a general Bolt 3.2.9 error since other people (running 3.2.9) dont experience this behaviour. The same error occurs on the local staging server running php 5.6 / nginx and the "production" server running apache. i doublechecked file permissions and file / dir ownerships on both machines. As in the other referenced issue, "Upload File" and "Select from Stack" still works fine.

Details
-------

- Bolt 3.2.9
- Composer Install
 - PHP version: [  5.6 & 7.0 ]
 - Used web server: [ Apache & Nginx ] nginx 1.11
- All Browsers

Browser Console error:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)
`

Bolt system log
```
47	Critical	exception	asyncbrowse	An exception has been thrown during the rendering of a template ("Failed to get image data from file") in "@bolt/async/browse.twig" at line 123. 
URI: /async/browse/files?multiselect=true
Source: /xyz.de/vendor/twig/twig/lib/Twig/Template.php :: 447 
```
Nginx Error Log:
```
*13 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 192.168.1.200, server: xyz.de, request: "GET /async/browse/files?multiselect=true HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: xyz.de", referrer: "https://xyz.de/bolt/editcontent/projects/1"
```
probably unrelated since the same error happens with nginx and apache: http://serverfault.com/questions/587386/an-upstream-response-is-buffered-to-a-temporary-file

maybe related but unlike in this issue, a different php version didnt solve the issue (tried on Apache with php 5.6 & php 7 - and on nginx with php 5.6)
https://github.com/bolt/bolt/issues/4745

Still could be a rewrite issue, but the servers are using unmodified versions of the Nginx config example and the .htaccess file from the bolt distribution - so no idea how to fix this.

**Comment by GawainLynch** [comment]
Working fine here … my guess is something screwy with your Bolt admin assets. 

Try:
* Clear cache: `php ./app/nut cache:clear`
* Resync Bolt's assets: `php ./app/nut setup:sync` 
* Clear browser cache

**Comment by tilllt** [comment]
Did all that, no luck. Will try a full reinstall next...

**Comment by CarsonF** [comment]
> Failed to get image data from file 

There's an image in your `files` folder that Bolt is throwing an exception when trying to read the data from it.

Maybe you can isolate it?

**Comment by tilllt** [comment]
Yes! That was the Problem... 

Something must have changed in the way that Bolt reads (or does not read) .svg files. The "problematic" file was an SVG which was always there in the /files folder and never caused problems, but now after the 3.2.9 update it does. BTW: the SVG file is readable and not broken, its just that Bolt has a problem with it!

**Comment by GawainLynch** [comment]
Guessing at #6374

**Comment by CarsonF** [comment]
would you mind posting that svg file so we can see what's causing the error?

**Comment by tilllt** [comment]
i.e. this image makes bolt hang
[bg02.svg.zip](https://github.com/bolt/bolt/files/849875/bg02.svg.zip)

**Comment by CarsonF** [comment]
So the detected MIME type of that file is `text/html` instead of the expected `image/svg+xml`.

Forcing past that check while debugging seems to load the image info fine. So maybe we should check for that MIME type as well....I just don't think that's a good indication to go off of. Maybe check the file extension if `text/html`?

@GawainLynch thoughts?

@tilllt Bare with us as this is new code :)

**Comment by tilllt** [comment]
If you Google the mime-type error, there are quite some people complaining to Adobe because of Illustrator exporting the wrong mime type. So I guess if will be fixed at some point. On the other hand I would bet that adobe illustrator is one of the main programs used to create svg's.

**Comment by GawainLynch** [comment]
@CarsonF what @tilllt said about Adobe holds in my ~~research~~ Googling, so if we're going to support SVGs, then it seems reasonable to accept the format … "it's just a text file."

Security Vector Gold is inconsequential, we're not able to mitigate XSS attacks emanating from them, so how said file was originally saved isn't going to change that … you serve the file … you serve the problem :laughing:

**Comment by tilllt** [comment]
I saw that there are lengthy discussions about the svg mime type going on since the svg specs also allow for embedded Javascript. People say that having image/svg+xml is misleading because it can be much more than just an image...

**Comment by CarsonF** [comment]
should we even bother checking for the mime type then and just check the file extension?

**Comment by GawainLynch** [comment]
I know I am going to regret saying this, but probably just the extension.

**Comment by cdowdy** [comment]
@CarsonF  & @GawainLynch shoo me away if I'm wrong haha: but I think this is a problem somewhere else... I tried the svg linked above and it's being served with the right content type: 

![svg_mime](https://cloud.githubusercontent.com/assets/5969974/24109869/55f7b60c-0d68-11e7-932f-85c34390bef0.png)


It seems like it's stopping when trying to get the width and height from and image. particulalry 
https://github.com/bolt/bolt/blob/release/3.2/app/view/twig/async/browse.twig#L122-L124

and:

https://github.com/bolt/bolt/blob/release/3.2/app/view/twig/files/_files.twig#L67-L69

**Comment by CarsonF** [comment]
@cdowdy Chrome may be fixing for you.

Here's the code that's determining the MIME type:
```php
$finfo = new Finfo(FILEINFO_MIME_TYPE);

$mimeType = $finfo->buffer($content) ?: null; // returns "text/html"
```

**Comment by cdowdy** [comment]
@CarsonF I just tried with curl.. still the right mime type 
![curl-content-type](https://cloud.githubusercontent.com/assets/5969974/24111003/74356580-0d6b-11e7-9c9d-ce4fe10acefe.png)

**Comment by CarsonF** [comment]
@cdowdy Can you try with the code I posted?

**Comment by cdowdy** [comment]
@CarsonF yeah give me a bit :)

**Comment by GawainLynch** [comment]
I downloaded the file, and served it from my local git worktree, as I was running xdebug over the request as well … Everything this side came back `text/html`.

I'm guessing that the MIME guesser is using native tools on some machines, and polyfills on others.

**Comment by cdowdy** [comment]
@CarsonF ok yeah that returns `text/plain` and if we use (since it's already included) `$flysystem->getMimetypes('bg02.svg');` we'll get `text/html` 


buuuuut if you use just regular old flysystem like I did before ... some crappy code haha:  

```php  
$fileList = $filesystem->listContents( null, true );
$files         = [];
$expected = [ 'image/svg+xml' ]; 

foreach ( $fileList as $object ) {

if ( $object['type'] == 'file' && in_array( strtolower( $filesystem->getMimetype( $object['path'] ) ), $expected )
			) {

  $files[] = [  mimeType'    => $filesystem->getMimetype( $object['path'] ), 
    ];
}
```  

You'll get the right svg

![svg_right_mime](https://cloud.githubusercontent.com/assets/5969974/24112357/a5954902-0d6f-11e7-9514-eafc1f9d5e77.png)

**Comment by cdowdy** [comment]
I just got it to work with flysystem and the svg from this post: 

flysystem needs the ``<?xml version="1.0" encoding="utf-8"?>`` block in the head.. 

finfo still doesn't work and since we you all are using bolt's version of flysystem this wont work you'll get null or text/plain using finfo

**Comment by cdowdy** [comment]
ok this:

```php  
$finfo = new \Finfo(FILEINFO_MIME_TYPE);  

$mimeType = $finfo->buffer($boltFilesPath . '/test-mime.svg') ?: null; // returns "text/html"
```  

returns ``text/plain``  

```svg  
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 15.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="400px" height="400px" viewBox="0 0 400 400" enable-background="new 0 0 400 400" xml:space="preserve">
<rect fill="#DD0000" width="400" height="400"/>
</svg>  
```

using that svg (and the others in this post)  flysystem gives the right mime 

![flysystem_mime](https://cloud.githubusercontent.com/assets/5969974/24113311/c737e7c4-0d72-11e7-9ee6-d56c70675741.png)

**Comment by CarsonF** [comment]
@cdowdy didn't know GitHub supported collapsible blocks, thanks for that ;)

> finfo still doesn't work and since we you all are using bolt's version of flysystem this wont work you'll get null or text/plain using finfo

Flysystem uses `Finfo`.

> flysystem needs the <?xml version="1.0" encoding="utf-8"?> block in the head..

Yes, that fixes the detection for the "bad" svg image.

Maybe we could do something like this:
```php
$type = Flysystem\Util::guessMimeType($file, $data);
if ($type === 'text/html' && strpos($data, '<svg') === 0) {
    $data = '<?xml version="1.0" encoding="utf-8"?>' . $data;
    $type = Flysystem\Util::guessMimeType($file, $data);
}
```

**Comment by GawainLynch** [comment]
I think that's best effort, IMHO :+1:
