### ISSUE TITLE
[RFC] setting config value from env

### ISSUE THREAD

**Issue by santi6291** [bolt/bolt#6497]
Getting certain configuration from environmental variables, a great example is Docker and MySql. the hostname is dynamic and you need to fetch the `getenv('MYSQL_PORT_3306_TCP_ADDR')` to use MySql.

**Comment by rossriley** [comment]
We've already got this feature merged in via #6208 

It's not in a released version of Bolt yet, but will be soon.

**Comment by santi6291** [comment]
That's awesome thanks!
