### ISSUE TITLE
[BUG] Clicking View Readme for an extension results in an error

### ISSUE THREAD

**Issue by use** [bolt/bolt#6507]
Details
-------

 - Relevant Bolt Version: 3.2.9
 - Install type: Composer install
 - PHP version: 7.0.2
 - Used web server: Apache (Windows 10)
 - For UX/UI issues: Chrome 56

Reproduction
------------
​
 1. **Bug summary**: 
    * Clicking View Readme for an extension results in an error
 2. **Specifics**:
    * Screenshot:
![image](https://cloud.githubusercontent.com/assets/94230/24266710/0e6da3a0-0fc5-11e7-898e-dd3ee09526b3.png)
 3. **Steps to reproduce**:
    * Install an extension
    * Click "View Readme"
 4. **Expected result**: 
    * The readme should be displayed
 5. **Actual result**: 
    * An error message is displayed:
    * Unexpected token < in JSON at position 0

**Comment by CarsonF** [comment]
What extension?

**Comment by use** [comment]
Hi @CarsonF, seems like any extension. I tested this with boltforms since I figured that was a save one to test, and I see the same problem.

Here is the network log in Chrome:

![image](https://cloud.githubusercontent.com/assets/94230/24266868/8d9e8c98-0fc5-11e7-963e-8ae3dd6b48e6.png)

Maybe a problem related to Windows path separators? Since the the local platform is Windows and %5C is a backslash.

And when I change the URL from:

http://local.bolt/async/readme/vendor%5Cbolt%5Cboltforms/README.md

to:

http://local.bolt/async/readme/vendor/bolt/boltforms/README.md

and paste the fixed one into my browser, it resolves correctly and displays the readme.

**Comment by CarsonF** [comment]
Yeah the windows path separators are exactly it. The UrlGenerator encodes them.

This has already been rewritten for v3.3 (which is in beta) and won't have this problem anymore.

**Comment by use** [comment]
Ok, I will go ahead and close this then. Thanks for the heads up.

**Comment by CarsonF** [comment]
Cool, thanks for the heads up though 👍
