### ISSUE TITLE
[BUG] Image `alt` and `title` without `file` breaks admin page

### ISSUE THREAD

**Issue by Sendoushi** [bolt/bolt#6511]
Details
-------

 - Relevant Bolt Version: 3.2
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
 1. **Bug summary**: 
    * Backend `contenttype` page breaks when setting `attr` in image without `file` set
 2. **Specifics**:
    * Mention the URL where this bug occurs, if applicable
    * What version of Bolt are you using (down to the very last digit!)
    * What method did you use to install Bolt
    * What browser and version you are using
    * Please mention if you've checked it in other browsers as well 
    * Please include *full error messages* and *screenshots* if possible
 3. **Steps to reproduce**:
    * Simply set an image on a `contenttype` with `alt` and `title`
    * Set in the backend a new item with the `alt` and `title` for that said `contenttype`
    * Save and refresh
 4. **Expected result**: 
    * It should show the `contenttype` page or at least not save those `alt` and `title`
 5. **Actual result**: 
    * `Key "file" for array with keys "title, alt" does not exist in "@bolt/editcontent/fields/_image.twig" at line 49`

**Comment by GawainLynch** [comment]
Very specifically, are you using Bolt =< 3.2.9 or `release/3.2- HEAD`?

**Comment by Sendoushi** [comment]
`"bolt/bolt": "^3.2"`

**Comment by GawainLynch** [comment]
That is the Composer constraint, as in the "Specifics" section above: "_What version of Bolt are you using (down to the very last digit!)_" is important to know, as small changes often happen in patch versions and HEADs too, so it helps to know where to start to look.

You can get the require information from Composer by changing to the root directory of the site, and executing:
`composer show bolt/bolt`

**Comment by GawainLynch** [comment]
Never mind, I managed to reproduce it, but took a while :smile: 

Fix coming in #6512

**Comment by Sendoushi** [comment]
Sorry. Do you still want me to provide the specific version?

**Comment by GawainLynch** [comment]
> Sorry. Do you still want me to provide the specific version?

Nah, all good mate … pre-coffee curiosity got the better of me and I went digging (and found/fixed the problem).

So as soon as #6512 is merged, this issue will be magically gone :sparkles: :smile:
