### ISSUE TITLE
Button to toggle between `config` and `config_local` in 3.3 is missing. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6513]
See screenshot: 

![screen_shot_2017-03-25_at_13_08_21](https://cloud.githubusercontent.com/assets/1833361/24322056/8df74606-115c-11e7-970e-2df678b82849.png)

**Comment by GawainLynch** [comment]
I get something completely different:

![screenshot from 2017-03-25 13-13-11](https://cloud.githubusercontent.com/assets/1427081/24322065/d345f5ea-115c-11e7-9a08-b4341c1fc4b5.png)

![screenshot from 2017-03-25 13-13-54](https://cloud.githubusercontent.com/assets/1427081/24322070/eddf16de-115c-11e7-8446-38ded219bb89.png)

**Comment by bobdenotter** [comment]
The difference is the install method: You get the top one using the beta distro .tgz, and the bottom one using a git clone. :-)

**Comment by bobdenotter** [comment]
Closed by #6516
