### ISSUE TITLE
Ajaxy uploads are done to the "canonical", instead of the current location.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6514]
To reproduce: Set canonical to `canonical: example.org`. 

Screencast: http://recordit.co/RMlgfWp1NK

Details
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 | master ]

**Comment by CarsonF** [comment]
Well of course that would fail. I don't really think this is a bug, but I'm fine with the change.

**Comment by bobdenotter** [comment]
@CarsonF Thing is, it's really confusing. We have clients where we set the canonical to `www.domainname.com`, and the client logs in to `domainname.com`, and they suddenly can't upload anything anymore, without feedback why. I'd consider this a bug.

**Comment by SahAssar** [comment]
Either we should redirect/warn users that are not on the canonical or we should allow all functionality on non-canonical domains IMO.
