### ISSUE TITLE
Suggestion: Improve documentation to mention --enable-exif PHP requirement?

### ISSUE THREAD

**Issue by kyeno** [bolt/bolt#6544]
Hello,
I've been playing around Bolt for a few days now and I noticed I'm not getting thumbnails whatsoever. Went through different topics here, on stackoverflow, etc and finally noticed that my Bolt returns:

``UndefinedFunctionException in Native.php line 182:
Attempted to call function "exif_read_data" from namespace "PHPExif\Adapter".``

I also had to open the thumb url "by hand" to get there since I couldn't see any dev logging enabled (but that could also be my mistake, I think. I'm a symfony dev for years now, but just figuring out Bolt as I find it potentially nice for very simple sites and I totally *hate* Wordpresses ;))

Running Gentoo Linux with nginx-1.10.3 and php-5.6.30 fpm, the latter compiled from source with:
``'./configure' '--prefix=/usr/local/php-5.6.30' '--sysconfdir=/etc/php-5.6' '--with-config-file-path=/etc/php-5.6' '--disable-ipv6' '--enable-mod-charset' '--enable-mbregex' '--enable-mbstring' '--with-pcre-regex' '--with-curl' '--with-gd' '--with-jpeg-dir=/usr/include/' '--with-png-dir=/usr/include/' '--with-zlib' '--with-freetype-dir=/usr/include/' '--enable-gd-native-ttf' '--enable-intl' '--with-openssl' '--enable-bcmath' '--with-bz2' '--enable-calendar' '--enable-ftp' '--with-mhash' '--with-gettext' '--with-mcrypt' '--with-mysql' '--with-mysql-sock' '--with-mysqli' '--enable-embedded-mysqli' '--enable-pcntl' '--enable-opcache' '--with-pdo-mysql' '--enable-sockets' '--with-xsl' '--enable-zip' '--enable-fpm' '--with-fpm-user=nobody' '--with-fpm-group=nobody' '--with-xmlrpc' '--with-pear'``

I have figured that I'm missing ``--enable-exif`` to make it run smooth now.

My suggestion then is that Bolt should at least state it's basic PHP requirements somewhere in the docs.

As a related feature request I could propose a small roadmap; from the easiest step to the hardest:
- at least some sanity checks for uncommon and non-critical things (like EXIF) with ``if(function_exists(...)) {...`` before running it
- a bit more driveability for the thumbnail generator engine in the ``config.yml`` allowing to disable EXIF extensions
- an interchangeable thumbnailing engine allowing gd(+exif), ImageMagick (via native Imagick class), ImageMagick via executables (convert, identify)

Keep up the good work!

**Comment by bobdenotter** [comment]
Hi, 

> My suggestion then is that Bolt should at least state it's basic PHP requirements somewhere in the docs.

The requirements can be found on the "Requirements" page in the docs: https://docs.bolt.cm/3.2/getting-started/requirements
Did you have trouble finding it? If so, how can we improve that?

> at least some sanity checks for uncommon and non-critical things (like EXIF) with if(function_exists(...)) {... before running it

Bolt 3.3 comes with a 'configuration helper' that tells the user about common pitfalls like this, and a ton others.

**Comment by kyeno** [comment]
Hey, thanks for the fast answer. That's indeed interesting, I really seemed to miss it!

My suggestion would be a big, bolded link stating "Make sure your PHP environment requirements are met" from the https://docs.bolt.cm/3.2/installation/installation page or something.

Running Bolt 3.2.10 loaded from composer.

Still my feature request about more drivability to the thumbnailing engine stays. In a perfect world, I'd prefer even not to compile-in the gd extensions (and many others) to my PHP. Keeping the parser small theoretically helps on busy, bleeding-edge-optimized machines. Both security and speed wise. ;)

**Comment by bobdenotter** [comment]
> Still my feature request about more drivability to the thumbnailing engine stays. In a perfect world, I'd prefer even not to compile-in the gd extensions (and many others) to my PHP.

This sounds like a very specific usecase. Realistically, i don't see any of the core members having time for that in the near future. That said, if you're willing to build that feature and PR it, we'll gladly help you get started. :-)

**Comment by kyeno** [comment]
Thanks again for your reply - and I might actually do that in a free while; likely past-easter time. Been a looong while since I contributed to classy OpenSource. :) Will keep in touch!

**Comment by bobdenotter** [comment]
@kyeno Cool. Free free to ping us here, or drop in on our Slack channel. 

For now I'm going to close this issue to keep the list tidy. You can re-open if needed. :-)
