### ISSUE TITLE
[BUG] html is not parsed by fields function

### ISSUE THREAD

**Issue by braedsjaa** [bolt/bolt#6563]
**Bolt version 3.2.10**

_Bug summary:_
`{{ fields() }}` function parses html fields as text so we see all the tags on the finished page. 

_Specifics:_
As far as I know this is only used on the fallback record.twig which may not come up very often on a finished site. I have updated Bolt 2 or 3 times since I started a project and I don't know when this bug appeared. I think it was OK at 3.2.5

_Steps to reproduce:_
Clean install Bolt 3.2.10
Add dummy lipsum text.
Look at "recent entries" 
For an "entry" such as   http://example.dev/entry/2  teaser and body text are shown including the html tags and without formatting.

_Expected result:_
```
<div data-bolt-field="body"><p>Lorem ipsum dolor sit amet</p>
```

_Actual result:_
```
<div data-bolt-field="body">&lt;p&gt;Lorem ipsum dolor sit amet&lt;/p&gt;
```

**Comment by bobdenotter** [comment]
This was introduced (on purpose) in #6463 as a stopgap measure, and fixed in properly in #6474. Soon, 3.3 will be out, with this fix included. 

As a temporary measure you can add the `|raw` yourself, if you're confident no editors will mess things up on the content side. :-)
