### ISSUE TITLE
[RFC] Asset() replacing Paths variable makes templating more obscure

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#6566]
Disclaimer to start with: This is an issue just to start a discussion to include a front-enders view on this.

### Background: 
If I'm correct, the `{{PATHS}}` variable will be deprecated and (partly) replaced by the Asset() function.

This will cause 
`<img src="{{ paths.theme }}images/logo.png" alt="Client logo" />`
To look like this:
`<img src="{{ asset('images/logo_footer.png', 'theme') }}" alt="Client logo" />`

### Why?
There are a number of reasons why, as a frontender  / templater think this is not desirable.

**1. It obsures your templating code with magical backender bits.**
The `{{paths.theme}}` was used to shorten the longer absolute path, and was a readable tag. You could output the paths variable by dumping it and choosing what path you needed. 
Replacing it with a function that needs extra knowledge and is not readable by default, throws a threshold for templaters.
_To speak for myself, this would end-up being a 'magical' tag, where I have no idea what is does, will be copied and pasted from my gist, and being an annoyance, before returning to absolute paths again._

**2. The über-readable Twig is used for a reason**  
The reason why it's a bliss for frontenders and templaters to work in Bolt templates, is because backend is separated from frontend by the lovely Twig language. My Templates are not messy php functions, but readable snippets like {{  record.title }}. There's no learning curve for that. Inserting functions in the templates is a diversion from this philosophy, and in my opinion, is unlike Bolt.

**3. A technical issue with the paths variable should be handled in the backend, and not trickle through to the templating.**
Knowing the Bolt team, I am sure there is a very valid reason for this change from a technical point of view. Mostly, changes in Symfony versions, new possibilities etc. However. These technical changes should be handeled in the (invisible) backend part, and not end up on the screens of templaters. 

### Solutions?
For me, keeping the `{{PATHS}}` variable alive for getting the paths would be a great option, as is, or as an alias. 

An alternative solution @bobdenotter came up with, was making the theme default, so 
`<img src="{{ asset('images/logo_footer.png', 'theme') }}" alt="Client logo" />` would be simplified to:
`<img src="{{ asset('images/logo_footer.png') }}" alt="Client logo" />`
Although, as a templater I am still drawing blanks why I should use a function for something as simple as getting a static image from a static folder.

Please discuss! Thanks!

_(Won't somebody think of the frontenders!)_

**Comment by Mikescops** [comment]
I had the same thought when i discovered that the {{ PATHS }} will be deprecated.
Twig is used for his simple templating integration for _frontenders_, and i'm skeptic about using this asset path method.

**Comment by GawainLynch** [comment]
Firstly, paths was an ugly hack that held Bolt back in so many way, has caused us no amount of pain to get rid of on the path of getting us to any/all of Twig 2/Silex 2/Symfony 3 components.

We've deliberately avoided a default on `{{ asset() }}` as it is unclear to end users where they are getting those files from. In a single project that might make sense, but Bolt being a CMS as a lot of locations you might/need to use.

Things are changing in Twig, Silex & Symfony and we have to adapt to that, part of that is better documentation, part of that is accepting that tools change over time.

> For me, keeping the {{PATHS}} variable alive for getting the paths would be a great option, as is, or as an alias.

Already long removed from `master`.

**Comment by bobdenotter** [comment]
> Things are changing in Twig, Silex & Symfony and we have to adapt to that, part of that is better documentation, part of that is accepting that tools change over time.

All true, but there's also the part where "we" (as the developers) are in a place where we can make the life of implementors easier, by providing sensible templating options. 

I expect we'll hear this opinion voiced more often by frontend devs / implementors.

**Comment by evertalbers** [comment]
When I came across {{ asset }} my thought was "Ugh, that looks powerful indeed - but I'm afraid that I will only use the 'theme' option unless I use somebody else's code or plugin".

**Comment by anketwokings** [comment]
My first reaction would be that you did not understand any of my reasons, but state your own reasons for the change. I am respectful of that, and competely understand that there are technical reasons beyond my grasp for this change. 
However, this does not change the fact that this change imho is not user friendly, and in my opinion, unlike the bolt philosophy to keep the front-end clean and readable.

I was simply voicing my concern for keeping the templates as readable as can be, when I encounter something that might be improved

> Already long removed from master.

So, If I understand correctly: Stop whining, it's been done. I am sorry to get such a reply, but will consider this discussion as closed.

**Comment by bobdenotter** [comment]
The `{{ asset() }}` is undoubtedly good to have, especially for extension development. For the average implementor it's an increase in complexity.

**Comment by jadwigo** [comment]
How about a twig tag that is something like `{{ current_theme_path }}` wich is pointing to the publicly available path of the theme so theme developers can use that to point to a logo, stylesheet or script that is *in* their theme. 

Why should creating a twig variable to make  `<img src="{{ current_theme_path }}/images/logo_footer.png">` work be harder than creating documentation that explains why a theme developer should use `<img src="{{ asset('images/logo_footer.png', 'theme') }}">`

**Comment by GawainLynch** [comment]
> Quote @bobdenotter 
> but there's also the part where "we" (as the developers) are in a place where we can make the life of implementors easier, by providing sensible templating options.

We do, we provide the Twig, Silex & Symfony standard, well documented options.

> Quote @evertalbers 
> I'm afraid that I will only use the 'theme' option unless I use somebody else's code or plugin".

Yes, and here is part of the problem … support gets hard and documentation confusing when you're trying to load something "else" … and that happens all too often.

**Comment by bobdenotter** [comment]
> We do, we provide the Twig, Silex & Symfony standard, well documented options. 

But that's the problem. That's like pointing to a book about economics, if somebody has trouble making ends meet. 

For the people that have problems with this change, the documentation at the silex and symfony sites are useless. Those docs don't tell you how to link to a page in Bolt, or how to include a javascript file from the theme folder.

**Comment by GawainLynch** [comment]
>> Already long removed from master.

> Those docs don't tell you how to link to a page in Bolt, or how to include a javascript file from the theme folder.

I meant **our** docs, which you and I wrote most of on the subject of pathing recently.

**Comment by bobdenotter** [comment]
> I meant our docs, which you and I wrote most of on the subject of pathing recently.

Yes, and they will make it easier. It will allow people to find how to do it, but I am still not convinced that we shouldn't somehow do something about the increased complexity for the implementors.

**Comment by GawainLynch** [comment]
> How about a twig tag that is something like {{ current_theme_path }} 

Because `{{ asset() }}`:
 * Already exists
 * Can handle dynamic paths, change base-paths, etc
 * Handles cache stamping on the asset
 * … more

**Comment by GawainLynch** [comment]
> How about a twig tag that is something like {{ current_theme_path }}

Won't work in Twig 2

**Comment by GawainLynch** [comment]
> I am still not convinced that we shouldn't somehow do something about the increased complexity for the implementors

Agreed, such as:
 * Still better docs
 * Tutorials
 * Videos
 * i.e. better help, tools, and education for users

**Comment by anketwokings** [comment]
Imho, If you need a tutorial to wrote out an image path, there must be better solutions, and the solution will not be a better tutorial. :)

**Comment by jadwigo** [comment]
I don't buy that `{{ current_theme_path }}` won't work in twig2, you're telling me that Bolt will not be able to set variables that should be available in twig before it starts rendering twig. How is `{{ record.title }}` possible then?

But in that case we can also make it `{{ current_theme_path() }}` which still needs a lot less documentation than `{{ asset('some/asset.css', 'theme') }}`

**Comment by bobdenotter** [comment]
> I don't buy that {{ current_theme_path }} won't work in twig2, 

It is.

In Twig 2 global variables are removed the way we use them, making it unfeasible to just set stuff globally during different phases of the request cycle.

**Comment by GawainLynch** [comment]
Template … context …

**Comment by GawainLynch** [comment]
> But in that case we can also make it {{ current_theme_path() }} which still needs a lot less 

No it needs more, and you have build and support it … how's your PR record going there, mate?

**Comment by GawainLynch** [comment]
> It is.

Twig 2/ Silex 2 … whatever … it won't work

**Comment by GawainLynch** [comment]
Seriously, then if `{{ asset() }}` is too much, then [`{% setcontent %}`](https://docs.bolt.cm/templating/content-fetching) should leave you crying in the corner.

**Comment by bobdenotter** [comment]
> > It is.
> Twig 2/ Silex 2 … whatever … it won't work

I know. That's what i was saying.

**Comment by anketwokings** [comment]
> Seriously, then if {{ asset() }} is too much, then {% setcontent %} should leave you crying in the corner.

The difference between those tags is, that `{%setcontent}` might have a lot of options, it is designed to do exactly what it needs to do, and is simplified and readable as can be in that situation. 
I fail to see the similarity with using `asset()` to get a mere static path for an image. 

I certainly don't want to argue about all the other uses of `asset()`, that will no doubt be an improvement to the Bolt core. I am simply asking if there might be a workaround for that simple sotuation, such as the `{{paths}}` variable has been doing up until now.

**Comment by CarsonF** [comment]
To reiterate what @GawainLynch has said, there are many reasons why we needed to get rid of `paths` and there are many reasons why `assets` is better. 

Reasons why `paths` is going away:
- `paths` referenced absolute _filesystem_ paths as well as _url_ paths. It was very confusing to keep track of. i.e. `paths.files` vs `paths.filespath` vs `paths.filesurl`
- urls in `paths` needs to be updated with the request base path. Inherently this isn't a problem, but the way it was coded (forced by BC) was terrible.
- Twig 2 says "why are you changing globals?" and we agree.

Reasons why `assets` is better:
- It's a function instead of string concatenation. With `{{ paths.theme }}images/logo.png` we have no idea what you want to do with the themes path. With `{{ assets('images/logo.png, 'theme') }}` we know you want a url for that specific file. This opens up a world of possibilities.
- The biggest possibility (and currently implemented) is versioning (for cache invalidation). Instead of something like this:
```twig
{# must manually change every time file changes #}
{{ paths.theme }}images/logo.png?v=3

{# defeats the purpose of caching #}
{{ paths.theme }}images/logo.png?v={{ date() }}

{# This could get the files changed time or the hash of the file.
   It is the best way to version but it is very verbose #}
{{ paths.theme }}images/logo.png?v={{ getversion('images/logo.png') }}

{# Now this looks a lot better #}
{{ asset('images/logo.png', 'theme') }}
```
- CDN base paths can be assigned to a package and picked based on file path.
- Request base path is determined right when it's needed, instead of as "early as possible because we don't know when this global will be used".

-----

> 1. It obsures your templating code with magical backender bits.
> The {{paths.theme}} was used to shorten the longer absolute path, and was a readable tag. You could output the paths variable by dumping it and choosing what path you needed.
> Replacing it with a function that needs extra knowledge and is not readable by default, throws a threshold for templaters.
> To speak for myself, this would end-up being a 'magical' tag, where I have no idea what is does, will be copied and pasted from my gist, and being an annoyance, before returning to absolute paths again.

By that token, all twig functions and filters are magical and shouldn't be used. This includes `dump()` and `menu()`. It's also invalid to think everything can just be dumped. Dumping shows the current state, not the possibilities with all the functions of the object. 

> 2. The über-readable Twig is used for a reason
> The reason why it's a bliss for frontenders and templaters to work in Bolt templates, is because backend is separated from frontend by the lovely Twig language. My Templates are not messy php functions, but readable snippets like {{ record.title }}. There's no learning curve for that. Inserting functions in the templates is a diversion from this philosophy, and in my opinion, is unlike Bolt.

I'm just having a hard time believing the function is less readable. It's just a change from how it was previously.

> 3. A technical issue with the paths variable should be handled in the backend, and not trickle through to the templating.
> Knowing the Bolt team, I am sure there is a very valid reason for this change from a technical point of view. Mostly, changes in Symfony versions, new possibilities etc. However. These technical changes should be handeled in the (invisible) backend part, and not end up on the screens of templaters.

I agree. But this isn't just about paths, it's about versioning too.

**Comment by SahAssar** [comment]
Very late to this party, but perhaps we could have a `{{ files('images/logo.png') }}` and a `{{ theme('images/logo.png') }}` that just sets the second parameter and then forwards to the normal asset if that helps?

I prefer asset by far, but I have also seen that (some of) our designers see everything that is in any method/function as magic that they don't want to learn (and the more params to add, the harder to convince). I'm not saying that is the case here, but asset provides many benefits, but if it is seen as cumbersome perhaps we can make it easier to understand without actually changing the functionality or implementation via stuff like the above?

**Comment by CarsonF** [comment]
I don't think that's a good idea. Package names can be any string. The are defined at runtime. It wouldn't make sense to have functions for some of them. Then you have two different ways of doing something which adds to the confusion.

I don't think `files` and `theme` are good function names either, they aren't descriptive of what they are used for at all.

**Comment by SahAssar** [comment]
>I don't think that's a good idea. Package names can be any string. The are defined at runtime. It wouldn't make sense to have functions for some of them. Then you have two different ways of doing something which adds to the confusion.

Right, I get that, but if we are thinking from the "normal bolt-install, frontend-dev" sorta way, those two packages will be 99.9% of what is used. Anyway, if it feels helpful to any frontenders to have that kind of function it might warrant further discussion, otherwise not.

**Comment by GawainLynch** [comment]
Then we'll end up with wrapper, over wrapper, over wrapper.
  * https://symfony.com/blog/new-in-symfony-3-3-asset-preloading-with-http-2-push
  * http://symfony.com/blog/new-in-symfony-3-3-weblink-component

The asset function is the way forward, it is woven into the product demands we're going to need to adapt to.

The web evolves … fast … as does the tools you need to work on and with it, and Bolt tries its best to flatten out some of those curves.

But, like it or not, HTTP/2 Server Push is here. It will get fast, broad, adoption, and will be demanded by front-enders & back-ender's alike … not to mention your buzzword -savvy clientele …

> Build me seven blue HTTP/2 Server Push solutions, but 2 of them need to be red. Oh, and don't forget the kittens

**Comment by MichaelMackus** [comment]
+1 on setting the second argument in the ```{{ asset() }}``` function to "theme" by default. I fail to see how this wouldn't solve all these issues. I mean, if that really is the "default" way the `asset` function is used, why not set "theme" as the default?

**Comment by GawainLynch** [comment]
> +1 on setting the second argument in the ```{{ asset() }}``` function to "theme" by default. 

I've been pondering this a lot (the PR's point as a whole, and the default package for `asset`), and it has been a looooooooooooooooong conversation that I have had with @CarsonF, since the initial branch work. 

Our concerns are about the known unknowns, e.g. 
 * FrontEnderA does all the layout and CSS/JS work, so they will probably assume the default to be theme directory, as that is where their focus is 
 * FrontEnderB is the graphic designer who's mental focus is on adding site-specific image assets from the public `files/` directory, are they then likely to assume that "Of course, `files/` is my default" or is it an obvious distinction?

Problem coming to a decision is, we live with it … potentially for _many_ years. So if we made the wrong assumption, and we continually confuse people as a result, we're stuck with it … and the unhappy users such a mistake would bring.

**Comment by evertalbers** [comment]
Michael's suggestion looks good to me. I am working as both FrontEnderA and FrontEnderB, and I would always assume that the theme directory is default, because that's where you 'are' when you are building templates.

Just my 2 cents, but I consulted Donald Rumsfeld on this and he seems to agree.

**Comment by GawainLynch** [comment]
> Just my 2 cents

Yeah, but this is the "decision to be made" where it matters :+1:

**Comment by zomars** [comment]
As a frontender I don't see an issue to the new `asset` function (As a frontendy I've had to learn way more complicated stuff than that 😅 ), I've already replaced it in all my themes quick and easy and I loved the added benefits (caching, etc.) so far. For me the `{{ paths.theme }}` concatenation felt a little bit hacky and fragile TBH.

**Comment by ToBe998** [comment]
While i dont have any problems with the new assets stuff, why not do a quick extension that add a global path object with properties that simply wrap the appropriate assets methods?
This way it would be unrelated to Bolt. Bolt could do what it wants and users could still use old stuff no matter how much the Bolt devs dislike it ;)

Such a compatibility extension would also make migrating old themes easier.

**Comment by GawainLynch** [comment]
OK, so after a long talk with @bobdenotter about this yesterday, I'd like to throw some empiricism at this:

Let me start with the OP apples vs oranges comparison, with lines taken from `base-2016`.

Bolt v1 default: 58 characters
```twig
<script src="{{ paths.theme }}js/jquery.min.js"></script>
```
v3 default: 65 characters
```
<script src="{{ asset('js/jquery.min.js', 'theme') }}"></script>
```

"Ah ha! You evil backenders who spend all of your free time trying to make things better for frontenders (who don't even contribute to core work :wink:) are making us use an extra **seven characters**!!!111!!1!!"

OK then, well let us look at what it would be if you were to actually compare tapples with apples, not oranges, using v1 paths **and** apply the same logic to cache-bust assets:

```twig
<script src="{{ paths.theme }}js/jquery.min.js{{ paths.theme ~ 'js/jquery.min.js'|filetime }}"></script>
```
**105 characters** … 

Yes, you're welcome. We just saved you 40 characters worth of typing per asset you want to add to your theme :smile: … we even [documented the approach](https://docs.bolt.cm/3.2/templating/linking-in-templates#using-asset-to-link-to-assets-or-files), but I seem to be drawing a blank on finding the documentation for the v1 hack.

Oh, and speaking of documentation … Using `{{ asset() }}` and related friends, any developer familiar with Symfony, Silex, or Twig based CMS … like … oh, I don't know, [Drupal 8+](https://www.drupal.org/docs/8/theming/twig/functions-in-twig-templates) would be able to step between products with little to no friction … 

… or we could behave like a certain other platform and turn everything into jargon for the ~cult~cliqué :wink: 

"OK, but the rest of paths…"

Bolt v1 default: 96 characters
```twig
<form method="get" action="{{ paths.root }}search" id="searchform-inline" enctype="text/plain">
```
Bolt v3 default: 94 characters
```twig
<form method="get" action="{{ path('search') }}" id="searchform-inline" enctype="text/plain">
```
I don't need to expand here … v1 is improved upon in character count alone before we even start comparing apple with apples.

**Comment by anketwokings** [comment]
Ending this conversation with a conclusion that seems to draw the center of the discussion as if the problem were a mere count of characters was not very necessary. But the stance of the core team is clear and for all who were doubting, the free time that the developers invenst in Bolt is very, very much appreciated. This does however not mean that other opinions should not be heard or evaluated in the process.

Leaving it at this, keep up the hard work!

**Comment by GawainLynch** [comment]
> This does however not mean that other opinions should not be heard or evaluated in the process.

They are heard, and this was open for 3 months of discussion and evaluation. Suggesting otherwise would not be very fair.

We (as I guess I'm in the back-ender group here) talk with front-enders every day, and there are wildly differing opinions on everything, but out of all the people I have spoken with only the couple of objectors here are against the "new" way of doing things.

But yeah, to go back to a point about solution that was raised here earlier in the thread — and is one of @bobdenotter's common responses to people asking for features that don't have a lot of foothold — an extension can be written by someone that wants to maintain it to provide some of what you want in v3 … I'm even willing to be a technical sounding board for the person writing it.

But take it from me, having watched some of the pain that some extension developers have gone though to keep hacks running over time, it's pain and suffering and a lot of continuous work that will break sites and make customers unhappy.

**Comment by anketwokings** [comment]
> They are heard, and this was open for 3 months of discussion and evaluation. Suggesting otherwise would not be very fair.

Sorry, sorry, my words might not have been clear. I actually meant that (trying to rephrase correctly) while I know that you guys spend way more time, also your private time on the project, and I know that, but that it might not always be a valid argument to bring into an discussion to prove your point. 
Not trying to imply _at all_ that this subject or my opinion on the variable was ignored, because I think this was a very helpful discussion, and I am glad it stayed open for as long as it did.

**Comment by GawainLynch** [comment]
Ah sweet. My heart sank when I read your previous response, thanks for clarifying :+1: 

In the spirit of attempting to clarify responses … I introduced the time spent as validation because it is really central to those of us coding. 

By that I just mean that historically Bolt's API just grew and grew out of control to a point where small changes would break so many things in "WTF" ways and trying to keep things working, and development under control often looked to outsiders like "we" were not listening or caring, but in our "tight knit cabal" we were desperately trying to give people what they wanted with a vision of both now, and the future.

To be honest, I can see the apparent disconnect here, I just can't (currently) see how to "fix it". There is an amazing amount going on behind the scenes to make things better, easier, more stable, and more awesome. Please believe me that individuals and groups like yourself are constantly in our minds, for all the reasons you'd want to be there. :smile_cat:

**Comment by bobdenotter** [comment]
Just for reference.. Symfony 3.4 will add a default option: http://symfony.com/blog/new-in-symfony-3-4-default-request-context-for-assets

(which will be Bolt 4 before we can use it, BTW)

**Comment by CarsonF** [comment]
@bobdenotter That's something different - not related.

**Comment by GawainLynch** [comment]
![facepalm](https://user-images.githubusercontent.com/1427081/31043361-6f1d4e0e-a5ba-11e7-8e8f-736a31b1dd70.gif)

**Comment by bobdenotter** [comment]
Ah, I see now. Maybe I should read stuff better, first. ;-)

**Comment by GawainLynch** [comment]
Nah, I need excuses to find more GIFs like that … I mean, Sir Patrick is awesome and all, but how *cute* is that :rofl:
