### ISSUE TITLE
[RFC] Remove `.bolt.yml` by default.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6582]
As pointed out by @CarsonF and discussed during tonight's dev-meeting. The settings in`.bolt.yml` default to the same settings as in the code right now: 

https://github.com/bolt/bolt/blob/release/3.3/src/Configuration/PathResolver.php#L30-L40

```
    public static function defaultPaths()
    {
        return [
            'site'              => '.',
            'app'               => '%site%/app',
            'cache'             => '%app%/cache',
            'config'            => '%app%/config',
            'database'          => '%app%/database',
            'extensions'        => '%site%/extensions',
            'extensions_config' => '%config%/extensions',
            'web'               => '%site%/public',
            'files'             => '%web%/files',
            'themes'            => '%web%/theme',
            'bolt_assets'       => '%web%/bolt-public/view',
        ];
    }
```

Meaning that we can remove the `.bolt.yml` from the composer install and "normal" distribution, as well as make it optional. 

The alternative is that we keep it, but have the contents commented out and/or just link to the page in the docs that describes the functionality in the file. 

I - personally - would like to go along with Carson's suggestion and remove the file by default and make it optional. 

Preliminary checklist: 

 - [x] update [composer-install](https://github.com/bolt/composer-install/blob/release/3.3/.bolt.yml) - https://github.com/bolt/composer-install/pull/20
 - [x] Make sure Bolt still works, without the file. 
 - [x] update [packaging script](https://github.com/bolt/bolt-distribution)
- [x] Remove file check 
- [x] Update ScriptHandler to remove file if default values
- [x] Update ScriptHandler's prompt for paths
 - [x] Write docs.

**Comment by GawainLynch** [comment]
:file_cabinet:  :gun: 

:+1:

**Comment by bobdenotter** [comment]
About the "Make sure Bolt still works, without the file"-bullet.. This is what I currently get on Bolt 3.3 beta 5 (from the non-flat .tgz distro), after removing `.bolt.yml`: 
![screen shot 2017-04-19 at 09 05 17](https://cloud.githubusercontent.com/assets/1833361/25167537/1b5302ce-24e0-11e7-9982-1b2104d18e63.png)

Note: said install was working fine before the removal.

**Comment by CarsonF** [comment]
Can you post the .bolt.yml fine here?

**Comment by bobdenotter** [comment]
@CarsonF Sorry, forgot to update here.. This issue was a derp on my side, and as far as i can tell it works as expected.

**Comment by GawainLynch** [comment]
Done & dusted
