### ISSUE TITLE
[BUG] Named repeaters cannot be rearranged

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6598]
When editing a previously saved named repeater, if I rearrange any of them and save the changes are not saved at all.

Details
-------

 - Relevant Bolt Version: [ 3.4 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ] version [ 2.4 ]

**Comment by eduardomart** [comment]
Looks like @rossriley fixed it with #6606

**Comment by bobdenotter** [comment]
Excellent. Closing this one, then! Fixed by #6606
