### ISSUE TITLE
[BUG] Page Slug Allows Submission of Illegal Characters

### ISSUE THREAD

**Issue by Matthewbeck75** [bolt/bolt#6602]
While editing a record, you may add a / to the slug field. Saving the record will cause the Bolt back end to become inaccessible, triggering an uncaught exception.

Details
-------

 - Relevant Bolt Version: [ 3.2.10 ]
 - Install type: [ Zip/tarball install]
 - PHP version: [  7.0 ]
 - Used web server: [  Nginx 1.1.0 / ubuntu 16.04 ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
 1. **Bug summary**: 
    * Record edit page allows characters such as / to be saved to the slug field
 2. **Specifics**:
    * Front end stays available, url/bolt does not.
    * Link to exception and trace route: https://pastelink.net/61jy
 3. **Steps to reproduce**:
    * Add a / to the permalink value of a record and save. Full value I used: page/about-us/our-services
 4. **Expected result**: 
    * The page would display with a slug that shows it is a sub page of /about-us/
 5. **Actual result**: 
    * The uncaught exception linked above. Unable to access the Bolt back end, even when modifying menu.yml 
    * Was unable to find a fix besides editing the database directly to remove the / from the slug

**Comment by CarsonF** [comment]
The exception was in `@bolt/_base/_listing.twig`. It was trying to generate a url with the `slug` which had `/`s in it which failed the route requirement.

But we should definitely assert that slugs don't have `/` in them before this point.

**Comment by SahAssar** [comment]
While `/` should not be allowed in default routes it should still be possible to allow it via extending the slugifyer and changing the routing, right? We've done that with one client that "had" to have that sort of routing and have it be configurable by the client and his/her SEO expert.

**Comment by GawainLynch** [comment]
Closing this as the slug field in 3.3.0+ (RC due on Tuesday) now passes the field data though slugify on save.

Please feel free to re-open if I am missing something extra on top of this.
