### ISSUE TITLE
Viewless ContenTypes create frontend routes conflict

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6612]
Ok, this is an odd case.

1. I'm using the `pagebinding` example from the `routing.yml` file.
2. I have a viewless CT which slug is `services`.
3. I also have a page record which slug is also `services`.
4. In my `routing.yml` file, `contentlisting` is above `pagebinding`.

My first reaction would be to move the `pagebinding` above the other one but it would cause conflict with my other non-viewless CTs.

Still I find odd that a viewless CT is trying to generate a front-end listing route regardless. For me it would be logical to completely ignore the route and fall back to the next one, but I don't know if this is the intended behavior. I've searched in the other issues and didn't find something like this.

Details
-------

 - Relevant Bolt Version: [ 3.2.11 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.1 ]
 - Used web server: [ Apache ] version [ 2.4 ]

**Comment by GawainLynch** [comment]
This is correct behaviour. The routes are built long before configuration is loaded.

**Comment by zomars** [comment]
Thanks for the clarification! What would be a suggested workaround? My initial though was to add a single override on top for that single page, but IDK if there another one.

**Comment by SahAssar** [comment]
The correct workaround is what you suggested, routing should be thought as isolated and not able to react to configuration or other stuff loaded later. Closing for now, feel free to reopen if I'm wrong :)
