### ISSUE TITLE
[BUG] Hidden fields take up space

### ISSUE THREAD

**Issue by larsvansche** [bolt/bolt#6620]
I've noticed that the fields with hidden: true take up space. They have a height of 1px, a margin-top of 24px and a margin-bottom of 12px: 
![image](https://cloud.githubusercontent.com/assets/16673968/25738732/0f773500-317f-11e7-95c0-715253e224a4.png)

The unwanted height creates meaningless spacing between fields in the record editor: 
![image](https://cloud.githubusercontent.com/assets/16673968/25738779/447de474-317f-11e7-8384-f82825001496.png)

Specifics: 
This occurs when editing a record of a contenttype that contains fields of type: hidden
I'm using Bolt 3.2.11
I installed bolt by simply moving the files to my localhost webroot. 
I am using Chrome 58.0.3029.96 (64-bit)
I have not checked this in other browsers
There are no error messages. 

Expected result: 
I was expecting to not see any hidden fields at all, or notice they're taking up space. 

Actual result: 
Instead, They take up a height. No fields are visible, they're just taking up a height because of their margin. 

Proposed solution: 
Perhaps adding the following line of CSS will prevent it (I have not tested this): 
`div[data-bolt-fieldset='hidden'] { display: none }`

Details
-------

 - Relevant Bolt Version: 3.2.11 
 - Install type: Zip install 
 - PHP version: 7.0.3
 - Used web server: Apache version 2.4.18 (Win32)
 - For UX/UI issues: Google Chrome 58.0.3029.96 (64-bit)

**Comment by bobdenotter** [comment]
Thanks. Fix is in the PR queue. 👍
