### ISSUE TITLE
[BUG] Validation field names for text areas

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#6629]
It seems that the system name for the field is used instead of the field label for text area fields:

![123123123](https://cloud.githubusercontent.com/assets/530801/25772156/87c391d8-325c-11e7-8dee-3019c74d63b8.png)

The field labels are as follows:

![1234123121](https://cloud.githubusercontent.com/assets/530801/25772157/8ca0cec8-325c-11e7-9cce-cf51bc2ab912.png)

Details
-------

 - Relevant Bolt Version: v3.2.9
 - PHP version: 7.0
 - For UX/UI issues: Firefox

**Comment by bobdenotter** [comment]
Ah, I see! Fix incoming! Thanks! 👍

**Comment by dantleech** [comment]
Thanks @bobdenotter !
