### ISSUE TITLE
Replace baked-in embed.ly with something else

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6635]
Recently, embed.ly changed their business model, so we can't use it in Bolt anymore. At least, not in the way we used to. We need to replace it asap. 

More information: [embedly faq](http://docs.embed.ly/docs/new-pricing-faq) / [blogpost with marketing bingo](https://blog.embed.ly/the-best-is-yet-to-come-f5aac2bd6b13)

Current options on the table are: 

 - 1. Fork over $99 per month to keep the service running as is. We're going to do this for May, to give us some time to implement another option.

 - 2. Switch over to (third party / hosted) noembed.com, urlembed.com or iframely.com. We can do this rather quickly, and include it in a 3.2.x release rather painlessly. 

 - 3. Provide configuration options in Bolt, so people can use either the "default" provider that is to be determined, or their own third-party or self-hosted option

 - 4. Integrate `embed/embed` with Bolt, so we can use an "internal" provider. 

 - 5. Self-host a noembed installation on embed.bolt.cm. This would seem "professional", and we're less dependant on third parties, but it will require extra maintenance from us on another module. Additionally, there might be privacy concerns, because people might question why embedded URL's are sent to a bolt.cm subdomain. 

Currently i'm leaning towards option 1 (for the short term), and get a 3.2.x out of the door with option 2 and 3. 
If we then also provide either option 4 or 5 later on, it can still work as a configurable option in Bolt: Use what we provide out-of-the-box, or select your own self-hosted or third-party solution.

**Comment by SahAssar** [comment]
For me the best sounds like 1 for the next month, 4 for medium-term solution and then in 4.0 spin the field out as a extension.

**Comment by GawainLynch** [comment]
> - 1. Fork over $99 per month to keep the service running as is. We're going to do this for May, to give us some time to implement another option.

:-1: this will only be the beginning.

> - 2. Switch over to (third party / hosted) noembed.com, urlembed.com or iframely.com. We can do this rather quickly, and include it in a 3.2.x release rather painlessly. 

:+1:/:-1: short term, I can deal with that for 3.2, but this is short-short-short term thinking and approach only.

> - 3. Provide configuration options in Bolt, so people can use either the "default" provider that is to be determined, or their own third-party or self-hosted option

:-1: Lots of work, then docs

> - 4. Integrate `embed/embed` with Bolt, so we can use an "internal" provider. 

:+1: :wink: 

>  - 5. Self-host a noembed installation on embed.bolt.cm. This would seem "professional", and we're less dependant on third parties, but it will require extra maintenance from us on another module. Additionally, there might be privacy concerns, because people might question why embedded URL's are sent to a bolt.cm subdomain. 

:-1: we have too much on our plate, and there is no _real_ gain for us here

**Comment by bobdenotter** [comment]
So, we ended up with `I` and `IV`. :-)
