### ISSUE TITLE
[BUG] Not found message no longer correctly displayed

### ISSUE THREAD

**Issue by sebtombs** [bolt/bolt#6637]
Behaviour has changed regarding the parsing of fields(record), used in the base notfound.twig.

The html content used to be rendered verbatim but now all special characters are expanded.

e.g.
`<p>Oops! Something seems to have gone wrong - that page doesn&#039;t exist!</p> `
is now
`&lt;p&gt;Oops! Something seems to have gone wrong - that page doesn&#039;t exist!&lt;/p&gt;`

I'm sorry but I can't say at which version this change occurred.

Is the issue actually that we should no longer be using fields(record) in this context? I've checked the repo for bolt-base-2017 and it currently still does so. However, _aside.twig uses block.content and changing notfound to use record.content seems to fix the issue. I may be missing something in the intent however - relatively new to Bolt and twig.

Details
-------

 - Relevant Bolt Version: 3.2.12
 - Install type: Zip/tarball install followed by Composer update
 - PHP version: 5.6
 - Used web server: Apache

**Comment by sebtombs** [comment]
I'll try that again!
`<p>Oops! Something seems to have gone wrong - that page doesn&#039;t exist!</p>`
is now
`&lt;p&gt;Oops! Something seems to have gone wrong - that page doesn&#039;t exist!&lt;/p&gt;`

**Comment by bobdenotter** [comment]
@sebtombs It's a known issue, related to this: #6463

It is fixed _properly_ in bolt 3.3.. If you use `fields()` in your Bolt 3.2 install, you might have to re-add that `|raw` in your `_sub_fields.twig` template: https://github.com/bolt/bolt/pull/6463/files#diff-561ace6f484a81a322350fc21793097eL41

**Comment by sebtombs** [comment]
Thanks Bob, and apologies for not spotting #6563 describes my issue.
