### ISSUE TITLE
Default value for template specific fields doesn't work

### ISSUE THREAD

**Issue by larsvansche** [bolt/bolt#6642]
When I add a default value in theme.yml to a template (for a template specific field) it doesn't fill in that default value in the field. Instead, it is empty (or unchecked). 

I have tried this with a checkbox field and a text field. The text field turns out empty, the checkbox field is unchecked. 

Details
-------

 - Relevant Bolt Version: 3.2
 - Install type: Zip/tarball install
 - PHP version: 7.0
 - Used web server: Apache version 2.4.18 (Win32)

Reproduction
------------

The problem occurs when adding a contenttype with a templateselect field, of which the template contains template specific default values, defined in theme.yml. 

How to reproduce: 
1. Create a contenttype with a templateselect field
2. Add a template that the recently created templateselect field can select 
3. Add a template specific field in theme.yml to the recently created template
4. Give the recently created template specific field a default value in theme.yml
5. Add and save a new record to the contenttype created in step 1 and select the template created in step 2 with the templateselect field created in step 1
6. Check the templatespecific field created in step 3: you'll notice that the default value is not set

**Comment by GawainLynch** [comment]
Have you tried flushing the cache after changes to `theme.yml`?

From memory it is one of the ones that we can't yet monitor for changes, and reload configuration files as a result.

**Comment by larsvansche** [comment]
Now that I think of it, perhaps I should also mention a possible solution to the problem. 

It is possible that this option simply hasn't  been built before. I conclude this from checking the database: for newly created records the "templatefields" cell is empty, which is only logical. 

A possible solution could be to add a function that runs on presave for the contenttype (any contenttype with a templateselect field), checking if there will be any template specific fields and if so, check if there is a default value set for them. If a default value is set, add it to the templatefields cell in a json. 

I'm not sure if this is possible, since I don't know when the templatespecific fields are invoked.
