### ISSUE TITLE
Some extensions don't show up.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6646]
On Bolt 3.3, when searching for `seo` you get no results: 

![screen shot 2017-05-10 at 16 12 02](https://cloud.githubusercontent.com/assets/1833361/25903034/939db942-359b-11e7-9824-7bc3d51387d2.png)

Searching for `bobdenotter` does work, and it _also_ shows the "Bolt SEO" extension, that ought to show up in the other search too. 

![screen shot 2017-05-10 at 16 11 42](https://cloud.githubusercontent.com/assets/1833361/25903069/b02ef6d4-359b-11e7-833e-a3c02ad6da0f.png)

This is the URL that's requested, for `seo`: https://market.bolt.cm/list.json?callback=jQuery224030190277536586985_1494425514824&name=seo&bolt=3.3.0&_=1494425514827

This is the response, which is valid JSON according to JSONlint.com: 

```
/**/jQuery224030190277536586985_1494425514824({"packages":{"2":{"id":"3cda7d7e-09e9-11e5-9120-621e70d6e3eb","account_id":null,"source":"https:\/\/github.com\/bobdenotter\/seo","title":"Bolt SEO extension","name":"bobdenotter\/seo","keywords":[],"type":"bolt-extension","description":"The Bolt SEO extension is an extension to help you improve the search engine indexing of your Bolt website. It does this by:\r\n\r\n - Allowing you to specify the SEO title and meta-description for your pages.\r\n - Adding meta tags to your HTML to facilitate indexing of your pages using meta tags and OG tags.\r\n - Override the canonical, if you really want to.\r\n - Set the -tag.","documentation":null,"approved":null,"created":{"date":"2015-06-03 14:08:17.000000","timezone_type":3,"timezone":"UTC"},"authors":["Bob den Otter"],"license":["MIT"],"screenshots":null,"icon":null,"support":{"issues":"https:\/\/github.com\/bobdenotter\/seo\/issues","source":"https:\/\/github.com\/bobdenotter\/seo\/tree\/v0.14.2"},"suggested":[]},"3":{"id":"c23555b5-b373-4025-8380-1ff3f296302a","account_id":null,"source":"https:\/\/github.com\/chronometreur\/bolt-geotags","title":"Geotags","name":"chronolabs\/geotags","keywords":["Analytics","SEO","Tools","Geotags"],"type":"bolt-extension","description":"Extension to add geotags to your site.","documentation":null,"approved":null,"created":{"date":"2016-11-07 01:38:55.000000","timezone_type":3,"timezone":"UTC"},"authors":["Victor Rodriguez"],"license":["MIT"],"screenshots":null,"icon":null,"support":{"issues":"https:\/\/github.com\/chronometreur\/bolt-geotags\/issues","source":"https:\/\/github.com\/chronometreur\/bolt-geotags\/tree\/v1.0.1"},"suggested":[]},"4":{"id":"e89b81c7-bbd3-4221-82b9-070ba6680c45","account_id":null,"source":"https:\/\/github.com\/bolt\/Sitemap","title":"Sitemap","name":"bolt\/sitemap","keywords":["sitemap","SEO"],"type":"bolt-extension","description":"Create XML sitemaps for your Bolt website","documentation":null,"approved":null,"created":{"date":"2014-08-14 08:35:23.000000","timezone_type":3,"timezone":"UTC"},"authors":["Bob den Otter","Patrick van Kouteren","Gawain Lynch"],"license":["MIT"],"screenshots":null,"icon":"icon-sitemap.png","support":{"issues":"https:\/\/github.com\/bolt\/Sitemap\/issues","source":"https:\/\/github.com\/bolt\/Sitemap\/tree\/2.1.1"},"suggested":[]},"5":{"id":"ea9c07c8-ff94-44dd-bedc-a53d8ebf15fb","account_id":null,"source":"https:\/\/github.com\/bolt\/bolt-extension-robots","title":"Robots.txt","name":"bolt\/robots","keywords":["Google","SEO","robots.txt"],"type":"bolt-extension","description":"A simple extension to return a generated `robots.txt` file.","documentation":null,"approved":null,"created":{"date":"2016-07-10 13:27:07.000000","timezone_type":3,"timezone":"UTC"},"authors":["Gawain Lynch"],"license":["GPL-3.0+"],"screenshots":null,"icon":"icon-robots.txt.png","support":{"issues":"https:\/\/github.com\/bolt\/bolt-extension-robots\/issues","source":"https:\/\/github.com\/bolt\/bolt-extension-robots\/tree\/master"},"suggested":[]}}});
```

**Comment by GawainLynch** [comment]
Don't we have a minimum character limit to avoid flooding the server?

Also, that query result broken out contains:
```json
{
  "packages": {
    "2": {
      "id": "3cda7d7e-09e9-11e5-9120-621e70d6e3eb",
      "account_id": null,
      "source": "https://github.com/bobdenotter/seo",
      "title": "Bolt SEO extension",
      "name": "bobdenotter/seo",
…
```

**Comment by bobdenotter** [comment]
Minimum character limit is 3, i believe. :-)

> Also, that query result broken out contains:

I don't see what's wrong, immediately.

**Comment by bobdenotter** [comment]
Oh, I think I get you now.. Yes, the SEO extension is in the return set, but nothing is shown in the Bolt backend. No errors or anything in the console, either. So, i'm guessing they get swallowed somewhere.

**Comment by bobdenotter** [comment]
Ok, found where the issue is.. Compare these two: 

Searching for "bobdenotte" :

https://market.bolt.cm/list.json?callback=jQuery22406375723846019816_1494498082249&name=bobdenotte&bolt=3.3.0&_=1494498082252

Result: 

![screen shot 2017-05-11 at 12 24 25](https://cloud.githubusercontent.com/assets/1833361/25944770/cf231986-3644-11e7-9961-f83847906c73.png)

Searching for "seo" :

https://market.bolt.cm/list.json?callback=jQuery22406375723846019816_1494498082249&name=seo&bolt=3.3.0&_=1494498082254

![screen shot 2017-05-11 at 12 25 10](https://cloud.githubusercontent.com/assets/1833361/25944839/06014996-3645-11e7-9721-cb291ae6030a.png)

first one returns an `array`, with a "length", while the second one is an `object`, so our JS doesn't try to iterate over it: 
 
```
                    .success(function (data) {
                        if (data.packages.length) {
```

**Comment by GawainLynch** [comment]
OK, that is the change in the market place then … I can fix, @PhillippOhlandt just pointed to another bug on the site, so I'll move onto it soon

**Comment by bobdenotter** [comment]
For reference: 

![screen_shot_2017-05-11_at_12_30_15](https://cloud.githubusercontent.com/assets/1833361/25945759/6928a3ae-3648-11e7-8bc2-690b69d75d7d.png)

![screen_shot_2017-05-11_at_12_30_21](https://cloud.githubusercontent.com/assets/1833361/25945803/8a9f5ba4-3648-11e7-8138-5991cba834ef.png)

**Comment by GawainLynch** [comment]
Dank je wel :smile:

**Comment by GawainLynch** [comment]
Fixed the site response … So it turns out I learned today that `json_encode()` will treat an array as associative if the array keys don't start from 0 and continue in consistent increments of 1 … even if the keys remain numerical :disappointed:
