### ISSUE TITLE
[BUG] news widget sql error

### ISSUE THREAD

**Issue by JelleDijkhuizen** [bolt/bolt#6661]
Details
-------

 - Relevant Bolt Version: [ 3.2.1 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.5 | 5.6 | 7.0 ]
 - Used web server: [ Apache with Nginx proxy ] version [ centos 7 default repo latest ]
 - For UX/UI issues: [ Chrome but probaly all ]

Reproduction
------------

 1. **Bug summary**: 
The news widget does not load the news.
After digging in the code i found my server request to the news site is:
https://news.bolt.cm/?v=3.2.13&p=7.1.5&db=mysql&name=web.dijkhuizen.family
I past that url in chrome and got a internal server error:
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''��݊9!�,ޝ���\'' at line 1

PDOException

code: 42000

 Array
(
    [function] => query
    [class] => PDO
    [type] => ->
)
 
      solution might be.
When i change the request url to https://news.bolt.cm/?v=3.2.13&p=7.1.5&db=mysql&name=web.dijkhuizen.famil
every thing works fine.

**Comment by bobdenotter** [comment]
Thanks for writing this up! It has been fixed in the backend of the news feed. 👍

**Comment by JelleDijkhuizen** [comment]
no problem at all if i find anything else i will let you know
