### ISSUE TITLE
[BUG] "slug" used instead of name in content type edit buttons

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#6671]
Buttons on the edit content page use the "slug", for example

```yaml
my_content_type:
    name: "My Content Type"
    # ...
```

The save button renders as (in French) `Enregistrer le/la my-content-type` instead of the expected `Enregistrer le/la My Content Type`.

Offending code in `/view/twig/editcontent/_aside-save.twig`:

```twig
    <button type="button" class="btn btn-primary" id="sidebarsavecontinuebutton">
        <i class="fa fa-flag"></i> {{ __('contenttypes.generic.save', {'%contenttype%': context.contenttype.slug}) }}
    </button>
```

Offending

Details
-------

 - Relevant Bolt Version: `3.2-dev`

**Comment by bobdenotter** [comment]
Thanks for reporting! Fix in the PR queue. 👍

**Comment by dantleech** [comment]
Cheers Bob!

On 17 May 2017 08:52:56 BST, Bob den Otter <notifications@github.com> wrote:
>Thanks for reporting! Fix in the PR queue. 👍 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bolt/bolt/issues/6671#issuecomment-302014237

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
