### ISSUE TITLE
How to download file while use the file type 

### ISSUE THREAD

**Issue by boosen** [bolt/bolt#6684]
e.g. when I upload a pdf file on admin form page, then I use {{ record.attachment }}  in twig file.
It just open the pdf in browser  rather than download the file.

So the question is how can I download the file directly ?

Docs page: https://docs.bolt.cm/3.2/fields/file

Thanks

**Comment by GawainLynch** [comment]
This is your web server configuration.

Assuming you're using Apache, edit the `files/.htaccess` file, and at the top add:
```apache
<FilesMatch "\.(?i:pdf)$">
    ForceType application/octet-stream
    Header set Content-Disposition attachment
</FilesMatch>
```
See the [Apache docs](https://httpd.apache.org/docs/2.4/mod/mod_headers.html#header) for more details.

If you're using Nginx, the [docs are here](http://nginx.org/en/docs/http/ngx_http_headers_module.html) on setting headers.

**Comment by xiaohutai** [comment]
For newer browsers, you can also use the `download` attribute [1]. This doesn't work on older versions of Internet Explorers though [2]

[1] https://www.w3schools.com/tags/att_a_download.asp
[2] http://www.caniuse.com/#search=download

**Comment by boosen** [comment]
Thanks， I created a extension and use **readfile** solved the problem.
