### ISSUE TITLE
[BUG] Relationships order field is backwards

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#6687]
On my `pages` contenttype I added a relation to my `services` contenttype:

    pages:
        #...
        relations:
            services:
                multiple: true
                label: Services
                order: id

(Services is just a standard contenttype very similar to Pages).

But when I go to edit a page, click Relationships tab, then click in the "Services" field, the services in the dropdown are ordered in descending order. Similarly if I set `order: -id` in the relation they are ordered ascending.

Bolt 3.2.13, PHP 5.5.38, Apache 2.4

**Comment by bobdenotter** [comment]
Thanks, @svivian. A fix for this is in the PR queue: #6695
