### ISSUE TITLE
[BUG] permissions.yml link to docs incorrect

### ISSUE THREAD

**Issue by DavidOliver** [bolt/bolt#6688]
`permissions.yml` currently links to documentation at https://docs.bolt.cm/content/permissions, which 404s. The correct link seems to be https://docs.bolt.cm/configuration/permissions.

I was going to submit a pull request but I'm not sure which branch to submit to. 3.x?

**Comment by GawainLynch** [comment]
Thanks, you can send that change as a "bugfix" :wink:  to `release/3.2` :+1:
