### ISSUE TITLE
[BUG] Canonical URL in <head> missing?

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#6700]
I remember in the past (Bolt 2) that if you didn't set a `canonical`, you still get a canonical url in your `<head>`.

Details
-------

 - Relevant Bolt Version: [ `3.2.*` ] I am on `3.2.14` specifically
 - Install type: [ Zip/tarball install | Composer install ]
 - PHP version: [ `5.6` ]
 - Used web server: [ Apache ] version [ `2.2.22` ]

Reproduction
------------

 1. Install Bolt
 2. Add some dummy content
 3. View the website and inspect the source: canonical is missing (I'm looking for a `<link rel="canonical" href="...">`)

If I set the `canonical` setting to:
- `://`
- `http://`
- `https://`
- `bolt.xiao.twokings.eu` (my dev environment)
- `true` becomes `1` (so: "http://1/)

then it shows up in the source (basically any non-empty string works).

Both missing/empty values and `false` will actually hide the `<link>` element.

---
I can't really pinpoint since which version this occurs. I'm pretty sure Bolt 2 always added a canonical (tested on a 2.2.21 website). I'm not sure whether this is intended behavior or not (for Bolt 3).

**Comment by GawainLynch** [comment]
Yeah, seems to happen in 3.2, but is definitely fixed in 3.3 … that whole layer was rewritten for 3.3.

**Comment by bobdenotter** [comment]
One more reason to get 3.3 out of the door, stat! ;-)

**Comment by GawainLynch** [comment]
Catching this one in the July Spring Clean … 3.3.0 is only _days_ away :tada: :champagne:
