### ISSUE TITLE
[BUG] Incompatible with MySQL 8

### ISSUE THREAD

**Issue by luispabon** [bolt/bolt#6706]
I'm getting the following issue while installing bolt from scratch on MySQL 8:

```
An error occured while updating `bolt_field_value`. 
The error is An exception occurred while executing 
'CREATE TABLE bolt_field_value (id INT AUTO_INCREMENT NOT NULL, 
contenttype VARCHAR(64) DEFAULT '' NOT NULL, 
content_id INT NOT NULL, 
name VARCHAR(64) DEFAULT '' NOT NULL, 
grouping INT DEFAULT 0 NOT NULL, 
fieldname VARCHAR(255) NOT NULL, 
fieldtype VARCHAR(255) NOT NULL, 
value_string VARCHAR(255) DEFAULT NULL, 
value_text LONGTEXT DEFAULT NULL, 
value_integer INT DEFAULT NULL, 
value_float DOUBLE PRECISION DEFAULT NULL, 
value_decimal NUMERIC(18, 9) DEFAULT NULL, 
value_date DATE DEFAULT NULL, 
value_datetime DATETIME DEFAULT NULL, 
value_json_array LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', 
value_boolean TINYINT(1) DEFAULT '0' NOT NULL, 
INDEX IDX_8B31D78784A0A3ED745E1826 (content_id, contenttype), 
PRIMARY KEY(id)) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB': 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your 
SQL syntax; check the manual that corresponds to your MySQL server version for the 
right syntax to use near 
'grouping INT DEFAULT 0 NOT NULL, fieldname VARCHAR(255) NOT NULL, fieldtype VARC' at line 1
```

Details
-------

 - Relevant Bolt Version: 3.2.14
 - Install type: Composer install
 - PHP version: 7.1.5
 - MySQL version: 8.0
 - Used web server: nginx 1.13

You can generate the environment above at http://phpdocker.io.

Reproduction
------------
1) make a new bolt installation
2) switch database config to MySQL, add credentials
3) ensure you're using MySQL 8
4) load up bolt

**Comment by GawainLynch** [comment]
I doubt there is anything we can do; 
  - MySQL 8 is a BC breaking release; 
  - Doctrine DBAL will need to cope with that, and the 2.5 branch is in maintenance mode with 2.6 long overdue and their `master` has not landed a platform class for MySQL 8 yet.

My recommendation would be, if you can first, produce a test case, then report the bug on [Doctrine DBAL's](https://github.com/doctrine/dbal) issue tracker

**Comment by GawainLynch** [comment]
Closing this, as mentioned this is upstream with Doctrine.
