### ISSUE TITLE
[RFC] Add width to fields

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#6708]
Hi,

I've worked with Wordpress/ACF for a long time, and one of the things I loved was the ability in ACF to specify the width of a field. It's a small feature, but it really helps cleaning up the admin when you have a lot of fields to work with.

I have to examples, one ACF and one Bolt
![image](https://cloud.githubusercontent.com/assets/23024452/26459994/4af2a32c-4146-11e7-918d-397115512b54.png)

Bolt:
![image](https://cloud.githubusercontent.com/assets/23024452/26460001/4e839244-4146-11e7-95ee-c02bb8cce97f.png)

See the difference, the bolt fields take up a lot more space since there is no easy way to specify the width. 

Somethimes you might even want 4 text-fields next to each other, and sometimes only 2 or 1.

Would be great if the YAML allowed a **width** to be specified as a percentage of the outer container.

**Comment by GawainLynch** [comment]
You can add the `class:` keyword to field options and load additional CSS, e.g.:

```yaml
content_type_name:
    fields:
        my_text_field:
            type: text
            class: is-out
```

**Comment by lenvanessen** [comment]
Hi Gawain,

Tried that, but the class is on the input field itself, and it needs to be on the outer div for this to work. If i style the class on in de input making it 50% width, there would still be a col-xs-12 wrapper around it preventing it from getting next to each other.

![image](https://cloud.githubusercontent.com/assets/23024452/26460576/15d9af8a-4148-11e7-8cf4-4f747a364fe3.png)

**Comment by GawainLynch** [comment]
Ah right, I'll leave it to the UI/UX part of the team then … I am so not a CSS person :rofl:

**Comment by zomars** [comment]
+1 For UI customizations

**Comment by bobdenotter** [comment]
At the moment you can add: `variant: inline` and `class: narrow` to modify the way they look. You can put the input next to the label and/or make them less wide: 

![screen shot 2017-05-27 at 11 23 33](https://cloud.githubusercontent.com/assets/1833361/26520252/06dca6bc-42cf-11e7-88fc-edc2c81ab20c.png)

For now, i'd like to close this one. If there's more requests, we'll see what we can do for the Bolt 4.0 backend, which is tracked here: #6229

**Comment by lenvanessen** [comment]
All right, would still be cool though if you could actually get them next to each other, this way they are narrower but that just leaves some unused space:)
