### ISSUE TITLE
[RFC] "Selected items counter" shows wrong number

### ISSUE THREAD

**Issue by filisko** [bolt/bolt#6716]
You can press "Select all" as much times as you want and the *selected items counter* gets increased.

Is just a visual bug (or its what it seems like).

I need to learn a little bit more about the Bolt script files structure to have a look at it.

![Image 1](https://i.snag.gy/FyofX6.jpg)
![Image 2](https://i.snag.gy/rP2KwU.jpg)

Details
-------

 - Relevant Bolt Version: [ `3.2` ]
 - Install type: [ `Composer install` ]
 - PHP version: [ `7.0` ]
 - Used web server: [ `Apache` ] 
 - For UX/UI issues: [ `Mozilla Firefox 53.0.3` and `Chromium 58.0.3029` ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

1. Go to any Content Type overview from your admin panel.
2. Click on the *arrow down* button before the ID column. List of options will appear.
3. Click on "Select all", the *selected items counter* will show how many selected elements are there.
4. Repeat the process of step 2 and 3.
5. The selected itmes counter will show up duplicated number of selected items.

**Comment by bobdenotter** [comment]
Thanks, @filisko. A fix is in the PR queue. See: #6717

**Comment by filisko** [comment]
Thanks to you @bobdenotter !
