### ISSUE TITLE
Suggestion: Browse content-types by year/date

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#673]
I think it would be nice to be able to browse content-types (on their overview listing templates, of course) by their years/dates of publish.

For example, I'd like to be able to 'filter' my blog posts by year, using the following route:

```
/blog?year=2012
```

Alternatively, everything posted on a particular date:

```
/blog?date=2012-12-03
```

These formats could also work (like Wordpress):

```
/blog/2012
/blog/2012/12
/blog/2012/12/03 (this is not very common, but could work)
```

**Comment by randy-girard** [comment]
Is there any update on this? I am moving my blog from wordpress, and its using this format. I want to keep the same routes if possible. Best I can get is `http://domain/2015-12-11/article`. I want to replace the `-` with `/`.

Thanks

**Comment by GawainLynch** [comment]
You could implement a custom controller to handle it, but it isn't something that makes sense as a default. 

Symfony/Silex define the parts in between the `/` as route parameters, so you could match a route on `$year, $month, $day, $slug` and do a lookup based on that.

**Comment by randy-girard** [comment]
Thanks for the feedback. I guess I don't know enough about Symfony to implement that at this point. What I have so far is this:
```
pagebinding:
  path:           /{datecreated}/{slug}
  defaults:       { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'entry' }
  requirements:
    datecreated:    '\d{4}-\d{2}-\d{2}'
  contenttype:    entries
```

I was hoping I could do something like `{datecreated|localdate('Y/m/d')} but it just prints all that out. Is there no way to run a filter/formatter on a variable in the route?

**Comment by GawainLynch** [comment]
OK… so you are on track more or less, but the Bolt controllers won't do it for you. You would need to add one in an extension… the [extended extension starter](https://github.com/bolt/bolt-extension-starter-extended/) has some examples.

The key is the path, above you're using YAML (and that is also one way to go) so if you were pointing at a custom controller you'd end up with *something* like:

```yaml
custom_route:
  path:           /{year}/{month/{day}/{slug}
  defaults:       { _controller: 'Bolt\Extension\Author\MyFooBar::myStaticFunction' }
```

The controller's PHP route function would looks something like:

```php
public static function myStaticFunction($request, $year, $month, $day, $slug)
{
    // Do stuff here
}
```

(all typed out pseudo-code off the top of my head, no promises that I didn't derp)

It is all very do-able… but you're starting to hit a learning curve here… and it is fun… seriously! Just don't be put off by it at first… once it clicks you'll be pumping thing stuff out in no time! :grin:

**Comment by randy-girard** [comment]
Thanks! I'll take a stab at it as I have time.
