### ISSUE TITLE
Automatical logout every 10 minute's.

### ISSUE THREAD

**Issue by dionys1705** [bolt/bolt#6734]
Hello, 

Bolt keeps logging me out after 10 minutes. Even if I am on the root account. 
And even if I am active at that moment.
It may be very easy but I can not find any settings to prevent this. 

Does anyone here have an suggestion on how I can stop this auto logout? 

There is no error message it does just redirect me to the login screen.

- Bolt 3.2.13

Kind regarts, 

dionys1705

**Comment by GawainLynch** [comment]
That is how long it is between checks that the cookies data and the cached data, if that check is failing something like a proxy may be using round-robin and changing the requesting IP, try [setting this](https://github.com/bolt/bolt/blob/v3.2.14/app/config/config.yml.dist#L362) to `false`, and if that still persists the one two lines below as well.

**Comment by bobdenotter** [comment]
There's a faq on discuss.bolt.cm that explains in detail how to fix this.

**Comment by dionys1705** [comment]
Hi, 

Thanks for the reactions. but this did not work for me.
![image](https://cloud.githubusercontent.com/assets/28395146/26673640/e8a411f6-46bd-11e7-8690-837867ff3fd1.png)
But I have set them to false. and it still logs me out. 
And yes I have done this:
- Cleared bolt cache.
- Cleared browser cache. 
- Tripple checked if the changes have been applied.

**Comment by GawainLynch** [comment]
Ah, also clear your existing `bolt_session_*` cookie(s) in your browser.

**Comment by dionys1705** [comment]
ah oke. thank you for now it does work. havent been logged out for 20 mins now.

**Comment by GawainLynch** [comment]
Cool, looks to be it.

If you have questions like this, try one of our [community channels](https://bolt.cm/community) such as Slack or IRC … Those mediums have a lot more "Bolties" hanging around to help, and we try to keep the issue tracker to things like bugs. Zero stress though. :smile:
