### ISSUE TITLE
[BUG] Update default_status in contenttypes.yml

### ISSUE THREAD

**Issue by fredpo** [bolt/bolt#6736]
The default_status in the distribution version of contenttypes.yml has an example of:

```
showcases:
    default_status: publish
```
The **publish** status no longer works, there appears to have been a code change and this was not updated. All ported yml files are not backward compatible with this change.

The following works, as documented.
`    default_status: published`

Bolt Version: 3.2.9

**Comment by GawainLynch** [comment]
Works for me on both a 3.2.9 & 3.2.14 install out of the box, plus it is covered in unit and acceptance tests.

My guess is you have the indentation slightly wrong in your `contenttypes.yml`. Ensure the `default_status:` key lines up with the same column and `name:`, e.g.

```
entries:
    name: Entries
    …
    default_status: publish
```

**Comment by fredpo** [comment]
The point here is that it's not the same as the documentation, which states: 
[https://github.com/bolt/docs/blob/release/3.2/docs/howto/resource-contenttype.md](url)


> Default Publishing Status
> 
> We use the default_status: published parameter to automatically set new resource records to published for ease of use.


It worked after changing it to **published** so there's a gremlin there somewhere. Everything lines up as it should. It creates confusion when your example uses **publish** instead of the documented term,  **published**.

**Comment by GawainLynch** [comment]
Ah, I see where you're going now :+1: 

I've just done a scan of the docs and there are a couple of places it is inconsistent, if someone doesn't beat me to it, I'll PR fixes in the morning.

The history is there was a typo somewhere in the Bolt code base that lived for too long. That said, my testing was `default_status: publish` which definitely works, `default_status: published` I would imagine should fail.

**Comment by fredpo** [comment]
You'd think that `default_status: published` would fail but it's working. Since it's so prevalent in the docs you'd see reports if it didn't.  It was pretty strange to me since I used `default_status: publish` for years.

**Comment by GawainLynch** [comment]
But there's the killer, for me `default_status: publish` works perfectly (even tested on a site that started life as v1), so the question turns to why `default_status: publish` isn't working for you

**Comment by fredpo** [comment]
The strange thing is that when I edit the record in the backend it shows `Current (saved) status:  None` but when I look in Meta it's  `Status: Published` if I save the record without touching anything, it switches to `Current (saved) status:  Published`. Mysql has status as `publish`, updates to `published`.

I think I figured it out, this contenttype is being populated from **BoltForms** so it looks like it's inserting exactly what's in `contenttypes.yml` and not converting `publish` into `published`

**Comment by GawainLynch** [comment]
OK … PR #6738 is in :smile: 

I actually had it incorrect myself … so thank you for being patient with a busy person :+1: 

The use with the missing "ed" was the v1 typo that lived in a few places for a while allowing both to work, v4 will hover require the `published` value.
