### ISSUE TITLE
"Edit configuration" for extensions doesn't work

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6763]
In 3.3, the button to edit an extensions configuration doesn't work, even if you're logged in as a "root" user: 

![screen_shot_2017-06-19_at_16_05_00](https://user-images.githubusercontent.com/1833361/27289157-44358c4e-5509-11e7-864a-d16f110f8508.png)

![screen shot 2017-06-19 at 16 06 41](https://user-images.githubusercontent.com/1833361/27289169-4cf8e0d8-5509-11e7-9000-8bece22f18f9.png)

**Comment by GawainLynch** [comment]
Oh, you mean PR #6762?

**Comment by bobdenotter** [comment]
🤦‍♂️

**Comment by SahAssar** [comment]
Fixed in #6762 :)

**Comment by GawainLynch** [comment]
> Fixed in #6762 :)

By a Time Lord, apparently :wink:
