### ISSUE TITLE
Custom upload folder when using upload field 

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6777]
The possibility to create an upload field in a contenttype is a nice feature. Sadly I can't set a custom upload location for a specific field. I need this so I can organize my files with folders with a subject name instead of the month/year the files are uploaded in by default. Does Bolt get this in the (near) future?

**Comment by SahAssar** [comment]
It's not mentioned in the docs yet (https://github.com/bolt/docs/pull/754 has not been deployed yet), but the upload parameter mentioned in the cheatsheet here: https://docs.bolt.cm/3.2/cheatsheet#field-options-for-contenttypes-in-contenttypes-yml will do exactly that. 

I'll close this for now, and if you have any issues with it please open another issue!

**Comment by GawainLynch** [comment]
Interestingly, my TODO today is to bug a few people about some docs PRs and merge and deploy recent updates … stay tuned :smile:

**Comment by GawainLynch** [comment]
Here we go:
- https://docs.bolt.cm/fields/imagelist#options
- https://docs.bolt.cm/fields/file#options
- https://docs.bolt.cm/fields/filelist#options

**Comment by gwbonline** [comment]
Thanks!
