### ISSUE TITLE
[BUG] – Repeaters in Templatefields not allowing you to remove last set

### ISSUE THREAD

**Issue by stueybrock** [bolt/bolt#6790]
Details
-------

 - Relevant Bolt Version: [ 3.2.10 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ]

Reproduction
------------
 1. **Bug summary**: 
    * Upon trying to delete all sets of a repeater, the last one does not get removed upon save.

 2. **Specifics**:
    * Bolt version 3.2.10, using Chrome
    * Patch has been applied from issue #6518, using this commit: https://github.com/bolt/bolt/pull/6518/commits/12a65d599b56302f32e827673f18f30ba3421ecb

 3. **Steps to reproduce**:

Code for the repeater itself:
```
my_repeater:
            label: My repeater
            type: repeater
            fields:
                name:
                    label: Name
                    type: text
                libk:
                    label: Link
                    error: Please enter a valid URL
                    pattern: url
                    type: text
                logo:
                    label: Logo
                    type: image
```

- Add two sets of content into the repeater, then save
- Remove one of the sets and save, this should work as expected leaving one remaining
- Remove the remaining set, save, then refresh the page
- The last remaining set is not getting removed from the repeater

Have tried re-ordering and removing multiple sets at once, with the same result. If multiple items get removed at once (both items one and two are removed at the same time therefore emptying the repeater), upon refresh they will _both_ still be in the repeater.

 4. **Expected result**: 
    * When all items have been removed, no matter whether I delete one or many, this should save in the database and leave an empty repeater.

 5. **Actual result**: 
    * Repeater seems as if it has saved, but upon refresh the final set that was deleted to leave the repeater empty has not been removed.

**Comment by mrenigma** [comment]
I'd also like to add that this was specifically tested using a repeater as a template field. This hasn't been tested AFAIK with a repeater as a content type field.

**Comment by bobdenotter** [comment]
Please try it out with a "normal" repeater too. "repeaters in templates" are ever so more complex.

**Comment by jadwigo** [comment]
I've noticed that when you create a new record that may have repeaters there will always be at least one repeater. 

This looks like there is an "empty repeater" prepared if you have removed the last repeater.

It might be because there are some default values defined in the `contenttypes.yml` for the repeater fields, but I'm not sure about that yet.

**Comment by stueybrock** [comment]
Tested with a "normal" repeater inside `contenttypes.yml` and the result of removing the final set is that an empty array is produced, which is the expected result.

Therefore it does seem like a "repeaters in templates" issue.
