### ISSUE TITLE
[BUG] ContentType translations are not showing universally

### ISSUE THREAD

**Issue by bpmct** [bolt/bolt#6795]
In some places within the Bolt dashboard, the ContentType translations are not being displayed. Instead, the generic translation is shown.

For example: 
- "View all" and "Add new" in the menu are always the generic translations.
- In the edit page for a content type, the header, meta, actions, and save button are the generic translation instead of the one for the specific ContentType.

 
See: https://github.com/bolt/bolt/blob/master/.github/CONTRIBUTING.md

Details
-------

 - Relevant Bolt Version: 3.2
 - PHP version: 5.5
 - Used web server: Apache

Reproduction
------------
**messages.en_GB.yml:**
`contenttypes.generic.save: "Save %contenttype% generic"`

**contenttypes.en_GB.yml:**
`contenttypes.blocks.text.save: "Save this block"`

I then proceeded to fully flush Bolt's cache, then this is what the "edit block" page displayed...

![image](https://user-images.githubusercontent.com/22407953/27924931-f9cf11de-6250-11e7-86e2-cba722123b12.png)

This is just one example of this bug, I listed other places I noticed above.

**Comment by GawainLynch** [comment]
ContentType translations have been removed in #6802 that will land in 3.3.0 … due out very very soon :smile:
