### ISSUE TITLE
record.image has unexpected fallback

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#6798]
Case
--------
My contenttype 'page' has a main image, called `record.image`.

On my page, I check if this image field is empty:

```
{% if record.image is defined and record.image is not empty %}              
- do stuff with the image --
 {% endif %}
```

Result
--------

If the field `record.image` is empty, Bolt falls back on the `getImage()` function that looks for _any_ image in my page, and displays that.  So instead of the main image, or no main image (whatever the editors decide), it suddenly displays the `record.teaserimage` field. 

Expected result
--------

That no image is shown. 
I check if `record.image` is empty, and yes, it is indeed empty. So it should stop there, not look for fallbacks.

Details
-------

 - Relevant Bolt Version: 3.3 beta 11

( Mansplanation coming up below! ;)

**Comment by GawainLynch** [comment]
> Mansplanation coming up below! 

:rofl: :+1:

**Comment by xiaohutai** [comment]
Did you just assume my gender?

In Twig, `{{ record.image }}` has some fallbacks [1]:
- `record['image']`
- `record.getImage()`
- etc.

So if image is `null`, then (I believe) it will fall back to `getImage()` [2].

- [1] [Twig Template Variables](https://twig.sensiolabs.org/doc/2.x/templates.html#variables)
- [2] [getImage() function in ContentValuesTrait](https://github.com/bolt/bolt/blob/09d2821eb5bc388164aad5ac6ba0146789c42225/src/Storage/Entity/ContentValuesTrait.php#L533-L559)

**Comment by xiaohutai** [comment]
Addendum:
Actually unexpected results will ensue if you use field names for which a `get<something>`, `is<something>` or `has<something>` exists for the `record` instance.

So, a field with name `excerpt` might be troublesome too, because of `getExcerpt()`.

**Comment by GawainLynch** [comment]
Yes, [that is Twig](https://github.com/twigphp/Twig/blob/v1.34.4/lib/Twig/Template.php#L620-L628) … to help no less! :wink:

**Comment by bobdenotter** [comment]
I don't think we can fix this, without breaking a ton of other stuff. For example, the backend overview listing shows an image, if there's one. It relies on the same principle. As does `getTitle()` to get a sensible title. 

You could work around this, by using `record.values.image` instead. 

(spring cleaning closing.. Feel free to re-open if needed. Or bug me in person on monday)
