### ISSUE TITLE
maintenance mode and extension route

### ISSUE THREAD

**Issue by jemont** [bolt/bolt#6804]
when using registerFrontendRoutes "match" in an extension, and maintenance mode is true, the route gets served.
Bolt 3.2.14

**Comment by GawainLynch** [comment]
Ah, I missed the fact that this was in an extension when discussed on Slack.

Background. We've been in a long process of rewriting the controllers, and currently one of the remaining piece to be cleaned up is the ACL handling in controller middleware.

For now the best option is to either extend `Bolt\Controller\Frontend`, _or_ `Bolt\Controller\Base` and implement your own [middleware matching](https://github.com/bolt/bolt/blob/release/3.2/src/Controller/Frontend.php#L63-L71) `Frontend`

**Comment by jemont** [comment]
ok thanks

**Comment by GawainLynch** [comment]
Closing this as part of a spring clean in July. I have also updated the documentation to help people better understand (it was my derp in the first place there).

Happy Bolting! :smile:
