### ISSUE TITLE
Protected method in \Bolt\Controller\Backend\Users controller

### ISSUE THREAD

**Issue by duskohu** [bolt/bolt#6808]
Details
-------
 - Relevant Bolt Version: [ 3.2 ]
 - Install type: [ Composer install ]

Hi,
I extend \Bolt\Controller\Backend\Users controller for use custom functionality, for example more fields in user form.
Is possible use protected methods in controller? because I must copy all private pethods from \Bolt\Controller\Backend\Users.

**Comment by GawainLynch** [comment]
Hi @duskohu :wave: 

Yes, PHP provides the [`extends`](http://php.net/manual/kr/keyword.extends.php) keyword for this purpose, the child class has access to the parents `protected` methods and parameters.

I am closing this as it is a general question and better suited to either our [Slack](https://slack.bolt.cm) or IRC channel (#boltcms on Freenode). Head over there and there are usually people around the world that can help with questions like this :+1:
