### ISSUE TITLE
[RFC] Make Content class extendable via Extensions

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#6814]
The Content class contains small helper functions to generate teasers for the backend.

 - Content->getExcerpt() returns some teaser-text generated from text fields
 - Content->getImage() returns the first image from any image field

Some extensions introduce new fields for images or text variants, that either store their content in some more complex form and have use a different field type. 
For example: Some of our websites use Cloudinary for images. The getImage() function does not recognize the new fields and thus allways returns null. Also our text content is stored in JSON formats generated by the Sir-Trevor editor. The getExcerpt() method finds the text fields (they use type text internaly) but return unprocessed JSON.

If you could either override the Content class or the ContentValuesTrait, an extension could make the methods understand the special fields.

**TL;TD**
Make getImage() and getExcerpt() methods overridable for special fields.

**Comment by bobdenotter** [comment]
in your contenttypes you used to be able to to `class: \yournamespace\contentrecord` to override the class used for each individual record. I'm not sure if that still works in 3.3, because i haven't used it in a while, but that would solve your issue, right?

**Comment by ToBe998** [comment]
That would solve it. I'll check if it's still possible. Tnx!

**Comment by ToBe998** [comment]
Overriding the content class for a contenttype works as @bobdenotter said. Many thanks for that. But images and their display still is hardcoded into the system to use the `thumbnail` method. This means, we still can not use images that are not local (Like CDN stored assets).

A small solution would be to check if the returned image path is an absolute url. And if so, just output it without modification.

The "good" solution would be to allow overriding of the `_listing.twig` (Probably already possible but hacky) or better yet, provide a way for an extension to replace the default `thumbnail` method.

```
        {# COLUMN: Thumbnail #}
        <td class="listthumb">
            {% if content.getImage is not empty %}
                {# Hack to add alt attribute #}
                {#{ content.getImage|popup(thumbsize, thumbsize * 0.75, 'c') }#}
                {% set thumb_height = (thumbsize * 0.75)|round %}
                {% set thumb_small = content.getImage|thumbnail(thumbsize, thumb_height, 'c') %}
                {% set thumb_large = content.getImage|thumbnail(1000, 800, 'r') %}
                {% set thumb_title = __('Image') ~ ': ' ~ content.getImage %}
                <a href="{{ thumb_large }}" class="magnific" title="{{ thumb_title }}">
                    <img src="{{ thumb_small }}" width="{{ thumbsize }}" height="{{ thumb_height }}" alt="{{ __('general.phrase.thumbnail') }}">
                </a>
            {% endif %}
        </td>
```

**Comment by ToBe998** [comment]
I'll try overloading the twig function/filter, maybe that will solve this issue. If so, this RFC could probably be closed. I'll keep you posted!

**Comment by ToBe998** [comment]
Overriding the thumbnail filter works perfectly. I can see my images front and back!

Another option would have been to override the ImageHander class. So plenty of options already in place. No need for RFC.

Thanks!
