### ISSUE TITLE
[BUG] incorrect meta tags placed with spaceless

### ISSUE THREAD

**Issue by ruvasik** [bolt/bolt#6822]
This issue continues issue #3622 about not correct meta tags placing. 
When full page is wrapped in a spaceless, then the meta tags generated also after the closing html tag.

```
{% spaceless %}
<!DOCTYPE html>
<html class="no-js" lang="{{ htmllang() }}">
...
</html>
{% endspaceless %}
```
generated to
```
<!DOCTYPE html><html class="no-js" lang="ru-RU">...</html><link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml">
<meta name="generator" content="Bolt">
<link rel="canonical" href="canonical url">
```

Details
-------

 - Relevant Bolt Version: 3.2 
 - Install type: Composer install
 - PHP version:  7.0 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
 1. **Bug summary**: 
    * Spaceless break the order of the tags
 2. **Specifics**:
    * Used templates with extends _master.twig
 3. **Steps to reproduce**:
    * Wrap all html template to spaceless
 4. **Expected result**: 
    * All tags in the right order despite the use (or not) of spaceless

**Comment by lenvanessen** [comment]
@ruvasik, just to make sure, your HTML is valid and contains a closing </head>?

**Comment by ruvasik** [comment]
@lenvanessen Yes. And could this be the reason, if it all correctly then no using spaceless ?

**Comment by bobdenotter** [comment]
I'm afraid this is not something we can fix. The meta tags are inserted via regex on their own line. If you wrap the entire page in `{% spaceless %}`, it will be nearly impossible to do that. 

If you did this to save a few bytes, make sure your webserver is configured to gzip the pages. Then, the difference with `{% spaceless %}` is negligible.
