### ISSUE TITLE
[ BUG ] Enforce SSL doesn't work on 404 page.

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#6831]
When using enforce_ssl in config.yml, all routes neatly redirect to https. 

But when the route is not matched, Bolt doesn't automatically redirect to https and serves the 404-page in a http-version.

**Comment by GawainLynch** [comment]
What Bolt version mate?

**Comment by GawainLynch** [comment]
Oh, and if it is 3.2, could you do us a huge favour and try 3.3-RC1 as I have a sneaking suspicion we fixed this months ago in the 3.3 branch, hence the above question :smile:

**Comment by lenvanessen** [comment]
Haha:) Sorry, bit lazy when it comes to bug reports, probably the pain of your existence asking people for versions.

This is 3.2 indeed, will update to 3.3 and post results

**Comment by GawainLynch** [comment]
Nah, I even do it too, here on our own tracker :rofl:

**Comment by lenvanessen** [comment]
@GawainLynch yes, it was 3.2. 3.3 works like a charm!

**Comment by GawainLynch** [comment]
Awesome-sauce, thanks for the follow up
