### ISSUE TITLE
[BUG] Sortable select field type causes twig runtime error when the values are from a content type

### ISSUE THREAD

**Issue by smgdesign** [bolt/bolt#6832]
When creating a field of type `select` and setting `sortable` to `true` on a field where the values are from another content type it causes an undefined string offset error in the twig rendering.
The actual error is:
`An exception has been thrown during the rendering of a template ("Notice: Uninitialized string offset: 0") in "@bolt/editcontent/fields/_select.twig" at line 48.`

This is caused in the method to create a unique superset of items from the `leadingvalues` and `values` variables. Commenting this line out `{% set values = unique(leadingvalues, values) %}` on line 48 of `vendor/bolt/bolt/app/view/twig/editcontent/fields/_select.twig` allows for the page to display. Setting the `values` variable just `leadingvalues` allows the page to display but obviously only returns the selected items.

The unique function seems to be unable to handle key based arrays and causes this runtime error, I haven't been able to find where the unique function is defined yet but will keep looking and provide a suitable update to the method when I find it (maybe just detecting if the key is unique on non-indexed arrays could solve this). A temporary fix of commenting out line 48 in the _select file obviously isn't ideal when deploying to multiple environments but should at least get anyone else around this problem for now

Details
-------

 - Relevant Bolt Version: >3.2.11 and 3.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx version 1.10.2

**Comment by GawainLynch** [comment]
Great report … Thank you! :+1:

**Comment by GawainLynch** [comment]
Fixed in #6841 and tagged in 3.2.16 & 3.3.0-RC2
