### ISSUE TITLE
[RFC] Better Exceptions for non-excisting Bundled extension classes

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#6836]
Hi,

When using version 3.3. of Bolt, I ran into an issue autoload issue. The class I created for my bundled extension was not included, and did not exist.

After adding the class to bolt.yml to activate it, Bolt threw an exception.

`LogicException in Bootstrap.php line 163
Bolt\Extension\XXX needs to implement Bolt\Extension\ExtensionInterface`

This got me searching for an issue that wasn't really there. I was extending SimpleExtension, so I shouldn't have to implement the Interface (if i understood the docs correctly)

After a searching for the issue in the wrong places, I realized that there was something wrong in the composer.json and that my class wasn't really included. 

## Proposed solution
Check if the class exists and throw a more descriptive exception if it doesn't.

**Comment by GawainLynch** [comment]
Fixed in #6839
