### ISSUE TITLE
Doctrine 2.6.0 is out, and it gives the middle finger to semver. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6846]
Doctrine DBAL 2.6.0 is out, and it was just now pulled in by `composer update`. It looks great, but it supports only PHP 7.1. https://github.com/doctrine/dbal/releases/tag/v2.6.0

Will we need to lock our version at 2.5.x?

**Comment by GawainLynch** [comment]
Updating this here too, as the discussion ended up in a few places :smile: 

* Composer installs will install the Doctrine version applicable to the PHP version that Composer is run with
* Distribution builds are built with Composer, and we build those with PHP 5.5 … See above :wink: 
* Locking DBAL at 2.5.x will hurt any site(s) running Postgres >= 9.4 (such as the Marketplace) and require me to create a forked Packagist project
* While the move by Doctrine is extremely inappropriate, and flies in the face of the work on the broader PHP community over the last 5+ years, it is really a non-event at the end of the day as DBAL 2.5 was released on the 4th of December 2014 and has been maintained regularly for the last 3 years

@bobdenotter Your call on closing this mate, but I really feel there is "nothing to see here" with the exception of an example of what not to do … but even this project has been guilty of that (myself included)

**Comment by bobdenotter** [comment]
This is not sitting well with me, but I agree that locking it will _not_ make it any better. Closing the issue.
