### ISSUE TITLE
allowtwig not working as expected when used inside a repeater 

### ISSUE THREAD

**Issue by pcmdev** [bolt/bolt#6852]
When adding the "allowtwig: true" on a field inside a repeater Twig tags are rendered as text, instead of using Twig to render them.

Details
------------

 - Relevant Bolt Version: [ 3.2 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ]

Reproduction
------------

- Create a repeater field to a content type.
- Create a HTML field inside of the repeater with allowtwig: true.
- Add some Twig code (e.g. {{  'now'|date('Y') }}) inside of the field by creating a new record.
- When accessing the record the Twig code is rendered as text.

**Comment by GawainLynch** [comment]
@rossriley assinging to you mate, but if you think it is my way, just bump it back

**Comment by pcmdev** [comment]
I'm not completely sure if this is related to another issue I'm having. Repeaters are displaying all select fields without options:

`            type: repeater
            fields:
                title:
                    type: text
                body:
                    type: html
                    allowtwig: true
                    height: 300px
                design:
                    label: Design
                    type: select
                    values: {'gray': "Gray", 'green': "Green"}`

The only thing I did yesterday was running `composer update` so the version I'm using now is 3.2.16.

**Comment by bobdenotter** [comment]
@pcmdev The issue you're describing is fixed in 3.2.18 (which will be released today)

**Comment by SahAssar** [comment]
Closing since we released a fix today.

**Comment by SahAssar** [comment]
Derp, was going by bobs comment and didn't see that issue was something else...
