### ISSUE TITLE
DBAL 2.6 Problems

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6856]
Apart from the rest of the dramas a default install on 3.2 & 3.3 (probably all versions) give the following per platform:

Sqlite
```
Table bolt_pages is not the correct schema: invalid column template
Table bolt_showcases is not the correct schema: invalid column file
```

PostgreSQL:
```
Table bolt_blocks is not the correct schema: invalid column templatefields, invalid column image
Table bolt_entries is not the correct schema: invalid column templatefields, invalid column image, invalid column video
Table bolt_field_value is not the correct schema: invalid column value_json_array
Table bolt_log_change is not the correct schema: invalid column diff
Table bolt_log_system is not the correct schema: invalid column source
Table bolt_pages is not the correct schema: invalid column templatefields, invalid column image
Table bolt_showcases is not the correct schema: invalid column templatefields, invalid column geolocation, invalid column video, invalid column image, invalid column imagelist, invalid column  filelist, invalid column multiselect
Table bolt_users is not the correct schema: invalid column stack, invalid column roles
```

**Comment by bobdenotter** [comment]
I've only tried SQLite and MySQL myself, but i've not yet seen these warnings on 3.3RC. Would it help, if we set up some sort of matrix with PHP versions / DB engines to check them all?

**Comment by GawainLynch** [comment]
What I did notice was that it is new installs … I had my worktree that I initially tested on, after hitting it on a Composer install, and that didn't experience the table diff b0rk until I dropped tables.

Several rise-and-repeats on Sqlite, CrapSQL and PostgreSQL produced the same results … Funnily enough I am right now writing off MySQL but it is the only one not affected :rofl:

**Comment by GawainLynch** [comment]
Sqlite seems to be fixed with DBAL 2.6.1 but PostgreSQL still seeing the same problem.

**Comment by GawainLynch** [comment]
I spoke too soon! Still there :disappointed:

**Comment by tha80** [comment]
I have got the same on mariadb. But only for the current 10.2.7 mariadb release. Older releases (for example 10.1.35) doesn't produce these errors. It seems that this problems exist on the bolt 1.2 and 1.3 release tree.

The errors look like this:
* Table bolt_authtoken is not the correct schema: invalid column username, invalid column lastseen, invalid column ip, invalid column useragent, invalid column validity
* Table bolt_blocks is not the correct schema: invalid column username, invalid column ownerid, invalid column templatefields, invalid column title, invalid column contentlink, invalid column image
* Table bolt_entries is not the correct schema: invalid column username, invalid column ownerid, invalid column templatefields, invalid column title, invalid column image, invalid column video
* Table bolt_field_value is not the correct schema: invalid column contenttype, invalid column name, invalid column value_string, invalid column value_integer, invalid column value_float, invalid column value_decimal, invalid column value_date, invalid column value_datetime
* Table bolt_log_change is not the correct schema: invalid column ownerid, invalid column title, invalid column comment
* Table bolt_log_system is not the correct schema: invalid column ownerid, invalid column ip
* Table bolt_pages is not the correct schema: invalid column username, invalid column ownerid, invalid column templatefields, invalid column title, invalid column image, invalid column template
* Table bolt_showcases is not the correct schema: invalid column username, invalid column ownerid, invalid column templatefields, invalid column title, invalid column geolocation, invalid column video, invalid column image, invalid column imagelist, invalid column file, invalid column filelist, invalid column multiselect
* Table bolt_taxonomy is not the correct schema: invalid column name
* Table bolt_users is not the correct schema: invalid column lastseen, invalid column lastip, invalid column shadowpassword, invalid column shadowtoken, invalid column shadowvalidity, invalid column throttleduntil

**Comment by GawainLynch** [comment]
Yes, maria DB is a separate problem and due to a change in 10.2.27 itself.

**Comment by GawainLynch** [comment]
Reverting to 10.1.x works around it in the short term.

**Comment by bobdenotter** [comment]
> bolt 1.2 and 1.3 release tree

How old is your Bolt setup? Or is that just a typo? :-)

**Comment by GawainLynch** [comment]
Typo … Showcases was Kitchensink back then :wink:

**Comment by Galaaxy** [comment]
Same problem as tha80 & GawainLynch with MySQL 5.7.14

**Comment by l0rn** [comment]
Same problem running Postgres 9.6.3

Could someone clue me in what is causing the prob?

**Comment by GawainLynch** [comment]
> Could someone clue me in what is causing the prob?

DBAL 2.6. You can set the project platform to 7.0 and re-run `composer update` … See section titled ["Deploying to Different PHP Versions"](https://docs.bolt.cm/3.3/installation/composer-create-project/creating-a-new-project#deploying-to-different-php-versions) for details on updating `composer.json`

**Comment by miksir** [comment]
It's because `JsonArrayType` is depricated since SBAL 2.3. Bolt using `json_array` datatype which resolved to `json` RDBMS native type, but in opposite direction `json` native type will be resolved to `JsonType`.
Result - missmatch of `JsonType` and `JsonArrayType`:
```
    "stack" => ColumnDiff {#2114 ▼
      +oldColumnName: "stack"
      +column: Column {#2460 ▼
        #_type: JsonArrayType {#1698}
        #_length: null
        #_precision: 10
        #_scale: 0
        #_unsigned: false
        #_fixed: false
        #_notnull: true
        #_default: null
        #_autoincrement: false
        #_platformOptions: []
        #_columnDefinition: null
        #_comment: null
        #_customSchemaOptions: []
        #_name: "stack"
        #_namespace: null
        #_quoted: false
      }
      +changedProperties: array:1 [▼
        0 => "type"
      ]
      +fromColumn: Column {#2179 ▼
        #_type: JsonType {#1535}
        #_length: null
        #_precision: 10
        #_scale: 0
        #_unsigned: false
        #_fixed: false
        #_notnull: true
        #_default: null
        #_autoincrement: false
        #_platformOptions: array:1 [▶]
        #_columnDefinition: null
        #_comment: null
        #_customSchemaOptions: []
        #_name: "stack"
        #_namespace: null
        #_quoted: false
      }
    }
```

**Comment by GawainLynch** [comment]
Yeah, we're across that at a low-level … it's not easy to fix currently

**Comment by miksir** [comment]
Well, probably best way to fix it is to check that json type exists or not and if missed (DBAL<2.6) - add own `JsonType` . And replace all `json_array` to `json`. 

Second way is to extend `JsonArrayType` and turn on comment hinting.

 I'm really suprized why Taluu was not added commentHint fix to `JsonArrayType`. (but added it to `JsonType` https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/JsonType.php#L94)

**Comment by GawainLynch** [comment]
Yep, pretty close to what I have in a branch here … mostly what's holding back me finishing it off is testing 3 platforms across 2.5 & 2.6, and MariaDB 10.2 +/- … and staying sane while doing it :rofl: 

Thanks for the comments though, good to have some external confirmation that I was on the right track.

**Comment by GawainLynch** [comment]
Updates for all watching this thread. I now have #6940 in the queue for early testing, but I wouldn't currently recommend using the changes on any system you care about. That said, testing on systems you can afford to throw away would be appreciated.

The current _Works For Me™_ status:
  - Sqlite 3.20 :white_check_mark: 
  - PostgreSQL 9.1+  :white_check_mark: 
  - MySQL 5.5 & 5.7  :white_check_mark: 
  - MariaDB 10.1 :white_check_mark: 
  - MariaDB 10.2.6+ :red_circle: 

However! For MariaDB 10.2 I have put together an ugly little extension called [`bolt/compat-mariadb`](https://market.bolt.cm/view/bolt/compat-mariadb) and published it on the Marketplace, that will tell Bolt to ignore the changes that MariaDB 10.2 wants to make. 

**NOTE!**
- `bolt/compat-mariadb` is a **temporary** solution
- `bolt/compat-mariadb` is for MariaDB **10.2** only

**Comment by GawainLynch** [comment]
Update on the MariaDB 10.2 issue. The change to MariaDB is due to yet another SQL standards violation that for them became a critical bug in 10.2 development, see 
- https://jira.mariadb.org/browse/MDEV-13132
- https://jira.mariadb.org/browse/MDEV-13341

There is a [PR under review now for DBAL](https://goo.gl/a7VciL) that I can confirm in my testing resolves the MariaDB issue.

**Comment by Robonoob** [comment]
Hi, 
The same problem still bugs me.
I fleshly installed bolt v 3.6.2 using [quick install](https://docs.bolt.cm/3.6/installation/quick-install) and entered "composer update" just after the installation. 
After the composer update command, I have DBAL v2.9. 
I am using php 7.2, sqlite 3.22

**Comment by pivotx** [comment]
Hi,

I've written a post about this. Have you tried the suggestions from here?
https://bolt.cm/item/fixing-issues-after-the-recent-doctrine-2-6-update
