### ISSUE TITLE
Refactor Storage.php to separate concerns.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#687]
Perhaps use an ORM? Should we do this only for Storage.php? Or should we abstract out all database access?

**Comment by dominikzogg** [comment]
@bobdenotter it's not ready atm, but i am working on a model generator for doctrine orm. It's not meant for initial build only, its mean't to rebuild the entities on each configuration change. There are much to less tests, and a yaml to php configuration converter is missing, but this could be a possibility to use doctrine2 orm with nearly the same configuration as now.

https://github.com/saxulum/saxulum-model-generator

**Comment by dominikzogg** [comment]
@bobdenotter I refactored a few things, added some tests, doc still missing https://github.com/saxulum/saxulum-entity-generator
