### ISSUE TITLE
Exception thrown when title_format uses multiple select field

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#6870]
Well, actually I don't know what would be the normal behaviour, but sure I didn't expect it to be an error.

To sum up : thanks to recent improvements, I was able to use a select field in title_format... until I change "multiple" attribute of my select field.

Suggestion : instead of throwing an error, perhaps just don't use select field in title if ther is more thant one item selected.

Details
-------

 - Relevant Bolt Version:  3.3

Reproduction
------------

 1. **Bug summary**: 
    * title_format can use select field type
    * but if multiple attribute of this field type is set to true, an error is thrown in backend listing
 2. **Specifics**:
    * Here is the error message :
` Twig_Error_Runtime in Template.php line 447:
An exception has been thrown during the rendering of a template ("Warning: strip_tags() expects parameter 1 to be string, array given") in "@bolt/_nav/_secondary-content.twig" at line 28. `
 3. **Steps to reproduce**:
    * Create a new Contenttype
    * Add a field with type "select"
    * Add attribute "multiple: true" to this field
    * Add attribute "title_format: [selectfieldname] to contenttype
    * Update database ad go to backend listing of your new contenttype
 4. **Expected result**: 
    * If multiple is not set to true, listing throws no error and title format uses select field normally
 5. **Actual result**: 
    * When multiple is set to true, an error is thrown

**Comment by SahAssar** [comment]
> Suggestion : instead of throwing an error, perhaps just don't use select field in title if ther is more thant one item selected.

Wouldn't that just be even weirder? As in you configure something and bolt would just ignore it?

IMO this isn't a bug, it's just what happens when you try to print an array as a string.

**Comment by trigau** [comment]
Well it could sound weird. The other option is to display all the values stored in the select field.

I think it could be viewed as a bug, because this is allowed and doesn't work. So either it shouldn't be allowed, or it should work, isn't it ?

**Comment by GawainLynch** [comment]
#7067
