### ISSUE TITLE
Underscores in slugs

### ISSUE THREAD

**Issue by technicallyerik** [bolt/bolt#6871]
I am attempting to migrate my blog over from another blogging platform, where I have slugs like:  "my_travels_2012_-_part_3".  This results in a 404, but I would expect it to work.

This is happening because the 'record' method in 'Frontend.php' re-slugifies the value from the url, converting the underscores before querying the database ("my-travels-2012-part-3").  Removing this line addresses the problem, but I'm not necessarily privy to why it was added.

```
$slug = $this->app['slugify']->slugify($slug);
```

Details
-------
 - Relevant Bolt Version: 3.3.1
 - Install type: Composer install
 - PHP version: 5.5
 - Used web server: Apache

Reproduction
------------
 1. **Bug summary**: 
    * Creating an entry with a slug containing an underscore results in a 404.
 2. **Steps to reproduce**:
    * Create an entry with a slug containing an underscore.
    * On your listing page, create a link to the entry with ```<a href="{{ page.link }}">{{ page.title }}</a>```
 4. **Expected result**: 
    * The link should work.  I would expect either: (a) The ".link" method in twig to do the same transformation, or (b) The slug not be re-slugified before querying the database.
    * As an aside, if this is done purposefully, I would expect a server-side validation error in the UI when entering an underscore in a custom permalink.
 5. **Actual result**: 
    * 404 error.

<img width="706" alt="screen shot 2017-07-31 at 10 32 29 pm" src="https://user-images.githubusercontent.com/2567597/28808321-966ce77a-7640-11e7-8cf5-4296f8d90fa3.png">

**Comment by SahAssar** [comment]
#7140 Fixes the basic issue I think, and if you want to customize the slugifyer you can look at gawains example in there or the internationalslugs extension. Closing for now, feel free to reopen if I'm wrong :)

**Comment by technicallyerik** [comment]
I'm not sure the above is related.  The issue I am running into is inaccurate querying of the database of an entry with a manually entered slug containing underscores.

**Comment by SahAssar** [comment]
Sorry, I misread :)
