### ISSUE TITLE
[BUG] Linking uploaded file or image to content results in `#` rather than file url

### ISSUE THREAD

**Issue by trburgess** [bolt/bolt#6873]
When browsing the server to link to a file or image previously uploaded, the link is set to a `#` rather than `file.url`.
Issue is here:
[https://github.com/bolt/bolt/blob/3.3/app/view/twig/components/stack/list-item.twig#L4](https://github.com/bolt/bolt/blob/3.3/app/view/twig/components/stack/list-item.twig#L4)

Details
-------

 - Relevant Bolt Version: 3.3 
 - Install type: Composer install
 - PHP version: 7.1 
 - Used web server: Nginx
 - For UX/UI issues: Firefox 54.0.1

Reproduction
------------

 1. **Bug summary**: 
    * When browsing the server to link to a file or image previously uploaded, the link is set to a `#` rather than `file.url`
 2. **Steps to reproduce**:
    * Upload a file or image
    * Select text within WYSIWYG
    * Click link icon
    * Click `Browse Server`
    * Click uploaded file or image
 3. **Expected result**: 
    * `file.url` to end up in Link -> URL field
 4. **Actual result**: 
    * `#` is added to Link -> URL field

**Comment by GawainLynch** [comment]
Sorry this has taken so long @trburgess, summer vacations and sunshine.  :wink: 

A fix (your suggestion is correct) is in coming #6976
