### ISSUE TITLE
[BUG] Cant publish / change status in /bolt/overview/****

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#6874]
Details
-------

 - Relevant Bolt Version: [3.3.1]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache 2.4 ]
 - For UX/UI issues: [ Chrome 59.0.3071.115 ] 
 - Extensions [ Translate 4.0.9 ]

Reproduction
------------

1- I created multiple contentypes (pages). 
2- I went to the overview of the contenttype pages and chose `select all`.
3- I clicked the button `publish` and nothing happend (the ct's kept their status 'draft' )
4- I tried to change the status of a single page via the same overview.

Both times nothing happened. 

I looked inside the console and found this

```js
VM872:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.error (bolt.js:9)
    at l (lib.js:1)
    at Object.fireWith [as rejectWith] (lib.js:1)
    at r (lib.js:1)
    at XMLHttpRequest.<anonymous> (lib.js:1)
```
I can however publish a page when i'm in `/bolt/editcontent/pages/`

**Comment by GawainLynch** [comment]
Hey @melcarthus :wave: 

This is a 404 coming from Translate. I'll tag @SahAssar here he's aware, but could you open an issue on [their tracker](https://github.com/AnimalDesign/bolt-translate/issues) and one of the maintainers can look deeper in. A copy of the Translate config & `contenttypes.yml` would probably be useful for them as a starting point.
