### ISSUE TITLE
[BUG] Sorting on ContentType select fields does not work

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#6877]
I'm using this in my ContentType:

        contentlink:
            label: Link to
            type: select
            values: pages/title
            sort: title

But when I go to add/edit a item, the `sort` parameter has no effect. The items in the dropdown are always ordered by id. I've tried `title`, `-title`, `-datepublish`, `-id` and more but the order in the dropdown is always the same. I also tried `order` as the key (as that is used for relations) but no difference.

Bolt 3.3.1, PHP 5.5.38, Apache 2.4

**Comment by svivian** [comment]
Also semi-related, I cannot see how to generate a link to the page based on the ID. [This page](https://docs.bolt.cm/3.3/templating/linking-in-templates#using-path-and-url-to-link-to-named-routes) only shows using a page slug:

    {{ path('contentlink', {contenttypeslug: 'page', slug: panel.contentlink}) }}

Which gives `page/4` when I actually want e.g. `page/about`. Using `id:` in there gives an error saying the slug is missing.

**Comment by GawainLynch** [comment]
Fixed in #6878
