### ISSUE TITLE
[BUG] not found page doesn't show if the file name has a - character

### ISSUE THREAD

**Issue by lucasmontec** [bolt/bolt#6887]
In config.yml if you set the notfound page to a twig template in which the file name has a '-' character, bolt doesn't show the page.

config.yml:
notfound: not-found.twig

A report on the bolt discuss talks about the same behaviour happening with the file name 'error404.twig'.
https://discuss.bolt.cm/d/692-404-page-not-found/2

Details
-------

 - Relevant Bolt Version: 3.3.1
 - Install type: GitHub checkout
 - PHP version: 7.1.7
 - Used web server: Apache version 2.4

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. **Bug summary**: 
    * Files with the - character are not found for the notfound page.
 2. **Specifics**:
    * This happens with or without debug set to true.
 3. **Steps to reproduce**:
    * Turn of debug or open a private browsing window.
    * Set notfound to 'not-found.twig'
    * Navigate to a page that doesn't exist
 4. **Expected result**: 
    * The 404 page.
 5. **Actual result**: 
    * Bolt exception telling that debug needs to be activated and the user must be logged in.
    * The message that shows:
Uncaught Exception.

Debug is not available, and/or you are not logged on. To see a full backtrace of the Exception, do one of the following:

    Set debug: true in config.yml, and make sure you're logged in to the Bolt Backend.
    Set both debug: true and debug_show_loggedoff: true in config.yml.

**Comment by lucasmontec** [comment]
Also, checking again, seems like the only twig template it accepts is notfound.twig. This overrides anything set in the config.yml file.

**Comment by GawainLynch** [comment]
Confirmed this when reviewing with @lucasmontec on Slack yesterday.

**Comment by GawainLynch** [comment]
Ah, found what it is. The example theme `base-2016` has a file `theme.yml` that allows _certain_ parameters to be overridden, one of those being `notfound` and it is set by default. Caught me out too :wink: 

I'll talk over with the team what is the best approach going forward. But we do have a comment in the `theme.yml` file already.
