### ISSUE TITLE
[RFC] possibility for menu_local.yml? 

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#6890]
Heyaa Boldies!

Just thinking. Just the same way you would have a `config_local.yml`, could you also have a `menu_local.yml`? 

## What would this solve?
A lot of times, clients edit the menu (because they can, and sometimes should). These changes are often overwritten when a deploy script is used. Creating a local menu would make the risk of overwriting less.

## Content or template?

That's the obvious question here; The menu tends to be part of the content more and more, especially when you give the client a menu editor to edit the menu themselves. So it would make sense to have a `menu_local.yml` file of it on the production site.

### menu editor?

Yeah, well, that [marvellous extension](https://market.bolt.cm/view/bacboslab/menueditor) needs to look at the `menu_local.yml` first then, of course, and after that to the regular `menu_yml`. But that is probably fixable. :)

----
Let me know what you think!

**Comment by SahAssar** [comment]
hmm, isn't the problem here that the deploy script does not take versioning/changes into account?

I'm not criticising the overwrite-and-forget way of deployment in all cases, but if files can be edited by the client then it isn't the way to go right? Just like you wouldn't overwrite the files dir (which is also tightly coupled with content) on deploy?

**Comment by anketwokings** [comment]
@SahAssar True, true, that of course is a way to fix is as well, and we probably will in this case. But I was just wondering if there were more use cases or people seeing this as an advantage. You remark on the files folder is true, that is the same kind of content meets system.

**Comment by GawainLynch** [comment]
I've spent the last 20 hours pondering this on/off myself. I've tossed back & forth over time if those files should handle a `_local.yml` and still can't decide if it makes sense in the bigger picture.

Thinking out loud, but this starts to fall into the basket of "separation of concerns" … 

It is reasonable to think that the base file (`menu.yml` in this case) is a developer concern, as they are the one _designing_ the site & layout (generally speaking) … and as such go into version control, giving clear visibility of the "base" requirement of a site.

Where-as the `_local.yml` files are intended to _not_ go into version control, and can/could be edited by a site "admin" who has a job to do, but isn't responsible for the overall site design, but is concerned with content that is provided to consumers of the site. A perfectly valid use-case for Bolt.

The design intent of `_local.yml` files was a security SoC, but while this isn't a security topic (at all IMHO :sweat_smile:), it is a question about division of the developer & site user concerns so perfectly valid to think though and debate.

Good job, Gawain, a whole lot of text and more questions raised than answered. Meh, it's Friday … pub time! :rofl:

**Comment by zomars** [comment]
Wouldn't this be solved by the Menu Editor extension?

**Comment by GawainLynch** [comment]
Not really. @anketwokings's use-case is tied to deployments where things are "frozen" in git (think UAT sign-off etc), but there is a slight delta of the menu configuration in production that is perfectly valid in terms of production's state, just not tied to the deliverable.

**Comment by anketwokings** [comment]
As for our specific usecase, @jadwigo created a Deployer recipe that adds the `keep_files` parameter to copy certain files from the previous release. More on -> https://github.com/jadwigo/bolt-deployer-recipe

You can see it in working order at the Europeana Website http://pro.europeana.eu/, also on github 
https://github.com/europeana/EuropeanaCopeBolt

(just to be complete :), when someone needs more info )

Example screenshot for added prettiness and clarity:
![image](https://user-images.githubusercontent.com/5583671/30801675-47656ee8-a1e4-11e7-8f60-10fcf75c5752.png)

**Comment by bobdenotter** [comment]
Let's close this issue for now: The usecase is quite specific, and there's a workaround. (in the deploy process). 

If somebody feels that we should discuss this more, feel free to re-open.

**Comment by GawainLynch** [comment]
It also becomes a moot point very soon … @rossriley might tell you why, but I am staying quiet :wink\
