### ISSUE TITLE
[BUG] Incorrect date format for locale set in config.yml

### ISSUE THREAD

**Issue by tompato** [bolt/bolt#6891]
Bug
----

When choosing a locale in the config.yml file, it seems to be ignored for the purposes of setting the date format, possibly in the filter for Bolt's `localedatetime()` function. When setting it to `locale: 'en_GB'` the date format is returned on date fields for content types as 'm/d/y' and it should be 'd/m/y' for the 'en_GB' locale.

Details
-------

 - Bolt 3.3.1
 - Composer install
 - PHP 5.6 and 7.0
 - Apache 2.4

Reproduction
------------

Set the locale to 'en_GB' and then add a content type with a date field. The resulting date field will use the date format 'm/d/y' instead of the correct 'd/m/y' format.

Screenshots
-------------

<img width="522" alt="screen shot 2017-08-11 at 12 51 01" src="https://user-images.githubusercontent.com/1638465/29211911-ba9ee214-7e93-11e7-8099-53a2caa33ae5.png">

**Comment by gwbonline** [comment]
This also happens on the meta tab when viewing the publish date. When the locale is set to Dutch, the year and time format is wrong.

**Comment by GawainLynch** [comment]
Found it! Fix incoming in #6907 … oh and it is another single character boo-boo @gwbonline :smile:

**Comment by gwbonline** [comment]
Thanks again! Its frustrating that I don't know more about this. Why has one character such an important function? I need documentation, tutorials and more to understand why code works like code works. I mean from the beginning... How is it possible that computers know what to do with code like php, twig and many others? I can imagine that it offers many possibilities for those who can write code like normal sentences.
