### ISSUE TITLE
[BUG] add directives to the query layer

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#6894]
Hi, I have tried to add directives in my extension to the query layer following the documentation at https://docs.bolt.cm/3.3/extensions/storage/directives
```php
$this->app['query.parser']->addDirectiveHandler('custom', new CustomHandler());
```

I have found that it is not possible, because invoking `$app['query.parser']->addDirectiveHandler ('custom', new CustomHandler());` A new instance is created with the "factory" directives, should not a "shared service", ie a singleton, be `$app['query.parser']`?

 - Relevant Bolt Version: [ 3.2 ]
 - Install type: [  Zip/tarball install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ]

**Comment by GawainLynch** [comment]
Closed in https://github.com/bolt/docs/pull/803
