### ISSUE TITLE
Hidden files & directories show in file server file selector UI

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6899]
![image](https://user-images.githubusercontent.com/1427081/29310040-865d244a-81ac-11e7-96c9-93da30f30b15.png)

**Comment by bobdenotter** [comment]
I've had to edit the `.htaccess` through the files screen sometimes. I wouldn't mind dropping all other `.whatever`, though.

**Comment by GawainLynch** [comment]
That's … kinda … wrong … in so many ways :disappointed:

**Comment by bobdenotter** [comment]
I know, but sometimes you're in a pinch, and you just need to fix something.

**Comment by GawainLynch** [comment]
Or you don't know what you're doing and break parts of a site's functionality.

**Comment by GawainLynch** [comment]
I'm working on a revision to #6970 that I'll push soon to discuss, but it should be easy enough to give *everyone* what they need.

**Comment by bobdenotter** [comment]
Fixed by #6970.
