### ISSUE TITLE
[Bug] Timed publish and depublish not working

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6905]
When using timed publish or depublish, Bolt isn't doing what it should. It basically does nothing. An entry with timed published isn't published at the give day and time (isn't published at all). The same happens the other way: an entry isn't depublised when setting a depublication day and time.

Details
-------

 - Bolt Version: 3.3.0
 - PHP version: 7.0

**Comment by GawainLynch** [comment]
Thanks mate, it was literally a missing `!` … just that one character :laughing: 

Fix is in #6906 and will be tagged in 3.3.2 very shortly.

**Comment by gwbonline** [comment]
Thanks! I will install 3.3.2 immediately when it's released.

**Comment by gwbonline** [comment]
Yes, it works and I'm very pleased with it. Still have a question. When republishing an entry that had a depublish before with a new depublish, or an exsisting entry with a new depublish date/time, those aren't removed until I clear the cache. Does this have something to do with the default 10 minutes that is set for duration in the config file?
