### ISSUE TITLE
[BUG] http://bolt-x4nqfb.bolt.dockerfly.com/page/ok-i-forgot-the-title

### ISSUE THREAD

**Issue by seyfer** [bolt/bolt#6911]
-----------

Ok, I just have created new Bolt installation from your web site for testing. 
I was amazed that it's made with Symfony and that it has twig templates.

But later I was disappointed to see Symfony error page after I have published the very first page.

http://bolt-x4nqfb.bolt.dockerfly.com/page/ok-i-forgot-the-title

Details
-------

 - Relevant Bolt Version: I think it's latest
 - Install type: from a web site https://bolt.cm/ where I got bolt-x4nqfb.bolt.dockerfly.com
 - PHP version: your testing environment
 - Used web server: your testing environment
 - For UX/UI issues:  -

Reproduction
------------

 1. **Bug summary**: 
    See description and attachment.
https://www.dropbox.com/s/kefkh9iw0iki84k/crash?dl=0
 2. **Specifics**:
    Maybe it's because I have used some `index.html` instead of an image file for page image preview?
Why was it in the `Select from server` image list?
 3. **Steps to reproduce**:
    Go to https://bolt.cm/, install new Bolt with Try Bolt now, add a new page, select some `index.html` as page image preview, open page and see the error.
https://www.dropbox.com/s/kefkh9iw0iki84k/crash?dl=0
 4. **Expected result**: 
    Page which I have created
https://www.dropbox.com/s/xx89jkme7vyu8ax/Screenshot%20from%202017-08-17%2016-14-53.png
 5. **Actual result**: 
    Twig error trace back page.
https://www.dropbox.com/s/sujjlodbj4kt4v8/Screenshot%20from%202017-08-17%2016-15-38.png

**Comment by GawainLynch** [comment]
A, that would be the try.bolt.cm site playing up again … ping @rossriley

**Comment by GawainLynch** [comment]
@rossriley the runner is working, seems to be something quirky with the base theme though

**Comment by rossriley** [comment]
I found it, it's the missing _sub_fields partial.... I'll get it fixed.

**Comment by rossriley** [comment]
OK, this one is sorted now.

If you go to try.bolt.cm and generate a new test site based on the base-2016 theme then all should be good again.
