### ISSUE TITLE
[RFC] Notification for timed publish on list entries

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6914]
Entries that have an end date/time and entries that are timed for publication in the future aren't visible as such on the list with entries. Is it possible to do this with, for example, a clock icon? There is room for it below the green/blue/red circle in the meta column.

**Comment by lenvanessen** [comment]
@gwbonline there actually is a visual clue when an entry is set to timed publish

![schermafbeelding 2017-08-28 om 08 58 18](https://user-images.githubusercontent.com/23024452/29762541-39b0bb20-8bcf-11e7-9a5b-60f786a6de39.png)

**Comment by bobdenotter** [comment]
Hi @gwbonline, 

I agree with @lenvanessen. It already shows for "timed publish", just not "timed depublish". Adding that as well in the overview screen would make it really cluttered, I think. So, in this case we'll close this one. If someone has a good idea on how to _visually_ do this, without it making the UI more cluttered, we're open to suggestions. 

![screen shot 2017-08-28 at 08 58 35](https://user-images.githubusercontent.com/1833361/29763073-dd27fb9a-8bd1-11e7-8003-ddfbc6a347d5.png)

**Comment by gwbonline** [comment]
Does adding an extra line (only in the Meta tab) make the UI more cluttered? Most entries don't have a depublish date and it can be only shown when there is a depublish date, so you still have three lines when there isn't a depublish date. I really like a way to see on the overview which entry has a timed depublish/is depublished. Thinking of it: Maybe changing the three lines of text to red with a red clock and depublish(ed) date at the beginning of the first line of text or at the end of the text?
