### ISSUE TITLE
[3.4] Can't add more "lorem ipsum" records, if there are already records.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6917]
I get this result: 

![screen shot 2017-08-20 at 12 10 25](https://user-images.githubusercontent.com/1833361/29493953-b8f7836c-85a0-11e7-822e-98dcb41495a5.png)

Instead, it should just add some more records to the contenttype.

**Comment by bobdenotter** [comment]
Digging in.. This was introduced in #6550. Working on a fix.

**Comment by GawainLynch** [comment]
Yes, and I asked you at the time if this was the intended approach …

**Comment by GawainLynch** [comment]
Fixed in #6919
