### ISSUE TITLE
[3.4] "Attempted to load repository for invalid class or alias: block. Check that the class, alias or contenttype definition is correct."

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6922]
When updating an install from 3.3 to 3.4, I get the following exception when viewing pages in the frontend: 

![screen shot 2017-08-21 at 08 45 53](https://user-images.githubusercontent.com/1833361/29506694-5c8cc666-864d-11e7-8ccc-6ef245263dbc.png)

@rossriley Do you think this is something you could take a look at? 

Full stack trace:

![bolt-origin localhost- ipad 1](https://user-images.githubusercontent.com/1833361/29506946-5012cdb2-864e-11e7-9cee-eb8a6751c136.png)

**Comment by bobdenotter** [comment]
If i modify the file it complains about from: 

```
        {% setcontent block = "block/about-us" %}
```

to: 

```
        {% setcontent block = "blocks/about-us" %}
```

The exception changes to: 

![screen shot 2017-08-21 at 09 05 53](https://user-images.githubusercontent.com/1833361/29507357-f5946d62-864f-11e7-9585-0eb299ca6b41.png)

**Comment by GawainLynch** [comment]
:koala: logic

**Comment by GawainLynch** [comment]
Issues with the parser are covered in #6902
