### ISSUE TITLE
[BUG] Sytemlog does not filter by Context = extension

### ISSUE THREAD

**Issue by nestordedios** [bolt/bolt#6926]
**Short description:**
When I want to filter the Systemlog by Context = extensions I do not get filtered results even though there are logs made by extensions in the general list. 

Logs list with extension logs in it:

![capture](https://user-images.githubusercontent.com/6607455/29517150-f98883b2-8673-11e7-9463-5b39e653f3d3.PNG)

Logs filtered by Context = extension:

![capture2](https://user-images.githubusercontent.com/6607455/29517217-4eca7164-8674-11e7-9f58-8657dadc258f.PNG)

**Steps to reproduce**:
    - Log in to Bolt's backend.
    - Have some extensions installed. (i.e: Labels)
    - Add modify some labels and save changes.
    - Go to the Systemlog. URL: BoltBackendDomain/systemlog and Filter by Context = extension

**Expected result**: 
   List of the extensions logs.

**Actual result**: 
    I get an empty list.

Details
-------

 - Relevant Bolt Version: [ 3.2.16 , 3.3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6  ]
 - Used web server: [ Apache ]

**Comment by xiaohutai** [comment]
Related: https://github.com/bolt/bolt/pull/6384

It used to be not available, then `extension`, now `extensions`?

So for Bolt 3.2.16+ and 3.3+, we add an extra `s` ?

**Comment by GawainLynch** [comment]
I'm not sure … I don't know how closely I checked it when you PRed, but I have just cherry-picked it into `3.2` and as I mentioned to @nestordedios in Slack we'll do a final release of 3.2 extremely shortly. I've been holding off tagging it while waiting on a test-case for a bug that would be nice to fix.

But important note that 3.2 is scheduled to EoL on Thursday.

**Comment by xiaohutai** [comment]
Oh! I took it from here: https://docs.bolt.cm/3.3/internals/container-service-references#app-logger-system

But it seems that extensions can log their own events, so I believe labels and auth both log them under `extensions`, while I log them under the singular `extension`.

**Comment by GawainLynch** [comment]
Ah … yeah … I just checked our source, and we log them under the plural context … and given the person that did it in core also wrote that part of Labels & BoltAuth I think it is far to figure where the pattern comes from.

Interestingly, the same person wrote that docs section :wink:
