### ISSUE TITLE
[feature request] - oEmbed field type

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#6928]
Hi, 

Video field type is great but that's a shame it has been limited to video only. 

oEmbed isn't only meant for videos. oEmbed can also provide some data and HTML pieces for tweets, bandcamp players, google maps, and so many providers. 

Could a more global oEmbed field be available in core?

**Comment by GawainLynch** [comment]
The original implementation was due to Embed.ly changing their offering on short notice. However, I did my best at the time to ensure we had groundwork to build on … just needs "hands" :smile:

**Comment by bobdenotter** [comment]
@nlemoine For shits and giggles: Try what happens if you insert a link to a non-video source? I know i've used the "video" field for Soundcloud or Issuu embed's before.

**Comment by nlemoine** [comment]
Already tried with Bandcamp ;) Returns an empty array. 

You will be lucky if the provider keys match the ones requested by Bolt backend UI. By the way, I think Bolt should save the raw json response from oembed service, instead of saving its own array, changing some keys in the process (author_name => authorname, etc.). But it would mean a serious revamp of the current UI which is quite nice.

**Comment by GawainLynch** [comment]
> By the way, I think Bolt should save the raw json response from the oembed provider,

Not that easy, and would break BC as this comes down to persistence

**Comment by nlemoine** [comment]
> Not that easy, and would break BC as this comes down to persistence

Could you be more specific?

**Comment by SahAssar** [comment]
@

**Comment by nlemoine** [comment]
@SahAssar I get it. Sorry, I wasn't specific enough. For BC reasons, obviously, video field type is meant to stay as it is. I was only saying saving raw json would be the best option to save a global oembed field. 

> Perhaps an extension implementation of this would be a nice place to start?

Sure thing. I'm not having enough time right now to work on it but will try to do something when I can.

**Comment by SahAssar** [comment]
Closing this for now as it is a better fit for an extension (and then perhaps integrated into core?)

**Comment by GawainLynch** [comment]
I'm going to be brave and reopen this … I'm about to take a massive look at how we "do" fields in upcoming weeks for v4 … the stale bot will keep me on my toes I am guessing!

**Comment by bobdenotter** [comment]
Will be in 3.5. See: #7278

**Comment by nlemoine** [comment]
The embed field in Bolt only uses the `oembed` provider from the [Embed](https://github.com/oscarotero/Embed) library. 

This library provides other ways to get some data, even when oEmbed isn't officially supported. In my case, I tried to get some bandcamp.com iframes. Works on the demo here: https://oscarotero.com/embed3/demo/

But Bolt doesn't return any information. Would you consider supporting this by adding the same logic found [here](https://github.com/oscarotero/Embed/blob/master/src/Embed.php#L116-L150)? 

It would provide a wider range of services.
