### ISSUE TITLE
Do not overwrite previous "where" in Custom Query Directives

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#6929]
Hello Team, If on a custom query directive the clause "where()" is used, the directive will be overwritten
This is solved by modifying the storage layer, (src/Storage/Query/SelectQuery.php) change "where" for  "andWhere", since it seems to not have any collateral effects
and it should be retro-compatible
see:
https://github.com/serweb-labs/bolt/commit/71b7dc71769785ee2e2248f81d922884a1a2fc05?diff=unified#diff-b885d8477758de447d690a18c3f5a123

**Comment by serweb-labs** [comment]
any idea?, :D I have an extension that depends on this change

**Comment by serweb-labs** [comment]
Gentlemen, I would like the approval before doing a merge request, according to http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html (in the comments) says : 

> // NOTE: -> andWhere () can be used directly, without any -> where () before. 

It is important to me many thanks.

**Comment by GawainLynch** [comment]
@serweb-labs do you have a small test-case or a URL for the extension?

I am not very familiar with that code, but it "looks" correct because it is calling `$this->getWhereExpression()` to build the `WHERE`, so I would think that the intent is to add where parameters elsewhere.

I might be very wrong, however, and someone will need to write a unit tests to cover this :smile:

**Comment by bobdenotter** [comment]
@serweb-labs Is this still a problem? If so, can you provide more info for us?

**Comment by serweb-labs** [comment]
I regret responding so slowly, I really appreciate your commitment and the time you dedicate to this.
I'm going to do a PR.

**Comment by rossriley** [comment]
I've handled this in the latest storage PR so I think this should no longer be necessary. Feel free to reopen if it's an issue it will appear in Bolt 3.5 when released.
