### ISSUE TITLE
Remove home-baked logging, use Monolog

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#693]
Or at least something PSR-3 like: http://www.php-fig.org/psr/psr-3/

**Comment by GawainLynch** [comment]
@rarila I have added FirePHP support now, e.g:
 ```twig
{{ firebug(record.values) }}
```
or
 ```twig
{{ firebug(record.values, 'some text') }}
```

or
 ```php
$app['logger.firebug']->addInfo($msg, $var);
```

It all Works For Me&reg; but I still want to write up an RFC when I get back to the EU, and have a few of us discuss results against a solid proposal.

**Comment by rixbeck** [comment]
Karma for @GawainLynch

**Comment by rarila** [comment]
Karma^2 for @GawainLynch

**Comment by GawainLynch** [comment]
This is now in 2.1-alpha.
