### ISSUE TITLE
Custom field types without new FieldTypeInterface not working

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#6953]
The new Content loading mechanism used since Bolt 3.3 uses a different interface for custom field types, making all custom fields using the documented format be ignored.

This only affects the new mechanism, now used in the Backend. See #6952 for a similar error in the legacy stack used in the frontend.

Content objects are filled by the Repository classes in `Bolt\Storage\Entit\Builder->createFromDatabaseValues($data, $entity = null)`. This class uses a new interface **FieldTypeInterface** for custom field types. Any custom field type using the old interface (also in the docs) **FieldInterface** will be ignored on loading.

```
    public function createFromDatabaseValues($data, $entity = null)
    {
        $entity = $this->getEntity($entity);
        $fields = $this->getFields();

        // set fields
        foreach ((array) $fields as $key => $mapping) {
            $fieldType = $this->fieldManager->get($mapping['fieldtype'], $mapping);
            if ($fieldType instanceof FieldTypeInterface) {
                call_user_func_array([$fieldType, 'hydrate'], [$data, $entity]);
            }
        }

        return $entity;
    }
```

We can not simply use the new interface as it requires a lot of new methods that most current custom field types do not implement. So I'd suggest to either fall back to the **FieldInterface** or enforce people to either implement the new interface or extend the new FieldTypeBase which would break BC.

https://docs.bolt.cm/3.3/extensions/intermediate/customfields

**Warning**
This new interface shows up in a load of other places that will also break. Locations i found so far (but there may be more):
- `Bolt\Storage\Entit\Builder->create($data, $entity = null)`

Details
-------

 - Relevant Bolt Version: 3.3.3
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------
- Create a custom contenttype as shown in documentation for 3.3
- Enter a value (if needed via database)
- Dump the record in the backend edit screen

**Comment by GawainLynch** [comment]
Ah yeah, with this one you need to extend the base class or implement `persist()` … I suspect a :koala: derp when updating the docs

**Comment by JarJak** [comment]
Even if I extend FieldTypeBase, the value is still not being saved in DB. And what I have found is when field has custom type then it is missing from entity class metadata and thus is not saved in \Bolt\Storage\Repository::persist

**Comment by JarJak** [comment]
I don't think "BC Break" fits here as this is just a Bug and fix should not break BC

**Comment by JarJak** [comment]
Nvm, it was just my custom extension messing around, after disabling it everything works fine :)

**Comment by bobdenotter** [comment]
@JarJak If can be tricky to get it right, but I'm happy it works for you. 👍

**Comment by ToBe998** [comment]
Starting to get this tested again, now with 3.4. Im a bit confused however... what's the correct way for 3.4 to create a custom field? What to extend or which interface to implement?

**Comment by bobdenotter** [comment]
@ToBe998 This works for me: https://github.com/bobdenotter/seo/blob/master/src/SeoField.php#L9

**Comment by JarJak** [comment]
After messing around I have found out that the line in my Extension's Controller that was causing custom fields not being saved is:
```
$this->app['schema']->isUpdateRequired()
```
It has been called on every request, but I still haven't found why calling this method makes field impossible to save... I guess this method must be called only once to get DB updated? How about securing this method to be called only once?

**Comment by GawainLynch** [comment]
That is an internal method, you should not be calling it under any circumstances.

**Comment by JarJak** [comment]
Then it should be marked as `@internal` :)

**Comment by GawainLynch** [comment]
No, if it is not documented in on doc.bolt.cm it should not be considered public.

**Comment by ToBe998** [comment]
Documentation fixed in PR https://github.com/bolt/docs/pull/844

**Comment by ToBe998** [comment]
Im closing this as the proposed change in class signature corrects the problem.
So, it was a documentation bug and hopefully not a big BC.
