### ISSUE TITLE
[RFC] Add app/nut command to create empty extension

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#6961]
I've seen this in PyroCMS and I love the concept. You'd do something like:

`php app/nut extension:create`

And it would prompt you for:
- Extension type (Bundled or Marketplace)
- Extension name
- Author
- Licence
- Other stuff 

And then add the boilerplate with the correct modifications

**Comment by cdowdy** [comment]
There's a composer version https://github.com/guenther/guenther  from @PhillippOhlandt but I don't know how that works with 3.3+ 

could combine the extension starters with this too

**Comment by PhillippOhlandt** [comment]
Günther doesn't work with the current Bolt version. Haven't done any Bolt stuff for quite some time.

**Comment by lenvanessen** [comment]
@cdowdy oh cool, must have mist it due to my lack of German understanding:)

**Comment by lenvanessen** [comment]
@PhillippOhlandt ah that's a shame!

**Comment by GawainLynch** [comment]
This isn't something that should be in core itself, IMO

**Comment by lenvanessen** [comment]
Agreed! Closing!
