### ISSUE TITLE
Multiple broken and missing links in changelog.md

### ISSUE THREAD

**Issue by mborn319** [bolt/bolt#6974]
I first noticed that the link to commit #6787 link was broken in the changelog. I then noticed that multiple other links were broken. While we're at it, does anyone notice that most of the links before the 3.0 release are missing entirely? So we have lots of "See #2077", or "Fixes #2025", but each requires manual typing to find the link.

I think 15 minutes with a Vim regex could easily correct these links (PR coming!) with no source code regressions.

**Comment by GawainLynch** [comment]
Be very careful … changes like this have been known to trigger a #1555 event, unleashing swarms of drop bear zombie on the world :wink:
