### ISSUE TITLE
[BUG] Browser nags about loosing form data when saving page

### ISSUE THREAD

**Issue by RTowarek** [bolt/bolt#6991]
Details
-------

 - Relevant Bolt Version: [ 3.5 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.1 ]
 - Used web server: [ Internal PHP server ]
 - For UX/UI issues: [ Chrome 60 ]

Reproduction
------------
Install Bolt 3.5 alpha6 through composer and try to save a new page or a existing one.

### Bug summary
When saving a new page the browser will prompt you for the following confirmation.

![screen shot 2017-09-12 at 10 44 35](https://user-images.githubusercontent.com/20314166/30317344-27b290a6-97aa-11e7-9174-3b4542a76835.png)

**Comment by GawainLynch** [comment]
Legendary! :+1: 

I have been waiting for someone to notice this and open an issue, so I knew someone was testing :wink: 

For reference this in 3.4+

**Comment by GawainLynch** [comment]
Fixed in #6996
