### ISSUE TITLE
We need a new `base-2018` theme. [encore]

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7005]
As a continuation of #6002.

We need to have a nice new `base-2018`. It doesn't need to wait until it's actually 2018, but it will ship with the next `0.1` Bolt release, when it's done. Currently aiming at Bolt 3.5.

Below is my current list of bullet points of what it needs to entail. Comments / additions welcome. 

## Main points

* The new default theme serves as a first introduction to Theming with Bolt for most people.
* Needs to have an excellent “Out of the box” experience. Even though we don't really intend it that way, a lot of people will use this to get a first site up and running.
 * It should be visually appealing
 * Should be “Robust” -> don’t break if a content type doesn’t exist, or if fields are modified.
 * It should _not_ look like it’s too closely related to the Bolt backend, because that’d just enforce the misconception that Bolt “requires” a certain style.
 
## Implementation details

 * Should be based on an _established_ front-end framework. This could be Foundation 6.4, but not necessarily. Not Bootstrap 4, though
 * Should be valid HTML5
 * Should be written using Twig best practices and/or our Twig coding guidelines
 * Should showcase the common Bolt features
	 * Search
	 * Menu
	 * Pagination
	 * Different ContentTypes, including a Singleton one.
	 * Areas for Widgets
	 * An example template showing a page leaning towards more visual-heavy content
	 * An example template showing a more text-heavy content
	 * Images and popups
	 * Video and / or other embeds
         * Listing pages for contenttypes and taxonomies.
 * It should come with a proper “build” workflow: Leaning towards Yarn / Webpack, but that’s not decided yet.
* It should have a "three step" Sass -> CSS workflow. The workflow builds two CSS'es: `framework.css` and `theme.css`. The first one contains whatever we used from the framework, but yields an otherwise very bare-bones layout. The `theme.css` should have all the overrides, and specific theming to make it look nice.  

## included pages / templates

 * `index.twig` - Homepage
 * `page.twig` - Plain detail page for "Pages" ContentType
 * `showcase.twig` - Detail page for "Showcases" ContentType with bells and whistles.
 * `record.twig` - Default detail page for a record, if no specific one available for that ContentType.
 * `listing.twig` - Listing overview for records / taxonomy pages
 * `searchresults.twig` - Listing page showing search results.
 * `styleguide.twig` - A 'contentless' page that will show most HTML elements, for reference.

**Comment by bobdenotter** [comment]
Wireframes, version 1.0: 

<img width="848" alt="base-2018 homepage" src="https://user-images.githubusercontent.com/1833361/30521336-5250b0d2-9bbe-11e7-8f5d-950bf628cb7b.png">

<img width="848" alt="base-2018 homepage_widgets" src="https://user-images.githubusercontent.com/1833361/30521337-557f2ee6-9bbe-11e7-858f-0334b4a051b5.png">

<img width="834" alt="base-2018 detail" src="https://user-images.githubusercontent.com/1833361/30521340-5b92b73a-9bbe-11e7-9273-40b5969c5602.png">

<img width="841" alt="base-2018 showcase" src="https://user-images.githubusercontent.com/1833361/30521344-5f1f8946-9bbe-11e7-99c7-7e444a0c9343.png">

<img width="792" alt="base-2018 listing" src="https://user-images.githubusercontent.com/1833361/30521346-65d4acda-9bbe-11e7-913d-fcdfd12207d9.png">

<img width="799" alt="base-2018 search results" src="https://user-images.githubusercontent.com/1833361/30521348-69066358-9bbe-11e7-87df-72bef11e9a5f.png">

**Comment by zomars** [comment]
Is [InuitCSS](https://github.com/inuitcss/inuitcss) still out of the scope?

**Comment by bobdenotter** [comment]
@zomars In my opinion it is. AFAIK the quality of what's there is great, but the website has [nothing besides](http://inuitcss.com/) "coming soon" since a number of years,  and it lacks documentation.

**Comment by zomars** [comment]
I know it's not the same, but the point of this framework is that the [code](https://github.com/inuitcss/inuitcss/blob/master/example.main.scss) [itself](https://github.com/inuitcss/inuitcss/blob/master/components/_example.components.buttons.scss) becomes the documentation. IMHO if you need another page to explain how to use a CSS component, well is not a very friendly framework isn't it?

**Comment by GawainLynch** [comment]
Oh, I am the person that tells people in the #development channel constantly to "Read the source, Luke!" and get what you're saying and agree … problem is that people have enough problem reading documentation, let alone reading the code.

Don't take either of my comments as "blockers" BTW, just adding weight to the pro/con for this one.

**Comment by lenvanessen** [comment]
Would be a good addition to showcase the singleton-feature in the new theme

**Comment by bobdenotter** [comment]
> Would be a good addition to showcase the singleton-feature in the new theme

👍  on this for sure.

**Comment by bobdenotter** [comment]
@zomars "read the code" is a very good way to gain knowledge about something, but it's not appropriate for everyone. Not having any docs will undoubtedly mean more support requests for the core team. 
I am afraid that we really need something with proper docs. Until that time, inuitcss is not suitable.

**Comment by bobdenotter** [comment]
Made a tiny update to the initial post and wireframes, to add in a Singleton Contenttype.

**Comment by xiaohutai** [comment]
- Make the theme as accessible as possible (mostly standard `aria` stuff).
- Add a nice 404 template too, with one or more of the following:
  - A customizable message (taken from a resource/singleton or `theme.yml`).
  - A search bar.
  - A link to the homepage.
  - A "Did you mean one of these?" thing (with search results based on words in the current slug).

Two more (advanced) things:
- The use of `aliases` for thumbed images.
- Show off named repeaters for longform/matrix/... pages.

That singleton feature is going to be really nice! But the singleton is going to be theme-specific, right? We just add a new one in `contenttypes.yml` by default?

**Comment by You85** [comment]
In the topic, think about adding pages like:
 -Home
 - About us
 - Contact us, (avec une carte Google maps)
 - Our team, 
 - Our realizations, 
 - Our services, 
 - log in (member area), 
 - Portfolio, 
 - Our agency,
 - ...

**Comment by xiaohutai** [comment]
It's only a theme, so it should be as simple as possible, but still give the options for users to add those pages themselves. Those pages are content, and content is not (directly) part of a theme.

**Comment by SahAssar** [comment]
@You85 I think you are misunderstanding what the *theme* is and what the *content* is.

You can add *content* or contenttypes with all those things, but that is not what the *theme* is about.

**Comment by zomars** [comment]
As previously commented on Slack, maybe [Bulma](http://bulma.io/) is a good fit for this theme.

**Comment by bobdenotter** [comment]
@zomars It's active, documented and not too bulky. It's surely a contender.

**Comment by zomars** [comment]
Also a hand on hand [Bulma vs Bootstrap](http://bulma.io/alternative-to-bootstrap/) table.

**Comment by bobdenotter** [comment]
This is being worked on, stalebot.

**Comment by dvangimst** [comment]
**TODO**

- [x] Popup
- [x] Mobile menu toggle (incl. fix styling)
- [x] Fix imagelist
- [x] Choose new photos
- [x] Add skip link
- [x] Styling Singleton
- [x] 404 page

**Comment by bobdenotter** [comment]
Closing, cause wrapped up in bolt/themes 2.0.
