### ISSUE TITLE
[3.4] Pre-fill button still showing when records exist

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#7016]
![image](https://user-images.githubusercontent.com/1427081/30680580-b339a50e-9ea0-11e7-89bf-463b0e3a1dfd.png)

**Comment by bobdenotter** [comment]
That's how it should be, imho.

**Comment by GawainLynch** [comment]
Oh, not a regression?

**Comment by bobdenotter** [comment]
Nope. :-)

I often use it to add _more_ records, after using it before.

**Comment by GawainLynch** [comment]
M'kay … UI/UX … staying out of it then :rofl:
