### ISSUE TITLE
Migrating Local Extensions to Bundles for Bolt 3.3

### ISSUE THREAD

**Issue by hanzx** [bolt/bolt#7018]
Hi, I have problem with assets after local extension migration.

previous path - /extensions/local/xxxx/xxxxxx/js/jquery.validate.min.js
current path is only /js/jquery.validate.min.js

`    protected function registerAssets()
    {
        return [
            (new JavaScript('js/jquery.validate.min.js'))->setZone(Zone::FRONTEND)->setPriority(10)->setLate(true)
    ];
    }
`
what i must do for proper functionality ?

**Comment by bobdenotter** [comment]
Hi @hanzx, 

The documentation states that bundles don't work with assets.. Just put the file somewhere in your `public/` folder, and include it from there.
