### ISSUE TITLE
Multiple delete for images in imagelist / error when saving entry

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#7026]
I use imagelist to publish image list that can contain more than 150 images. When saving an entry with such a list, sometimes Bolt gives me an error (see screenshot) and I have to create that entry again to be able to save it. With a lot of images this is very annoying, because I also have to upload the images again.

A second issue is that I am not able to delete multiple images from withing Bolt. I can select multiple images from the list and choose to delete them. Bolt adds a red border and that's it. After saving the entry, those deleted images are back on the list.

Details
-------

 - Bolt version 3.3.3

![2017-09-26 1](https://user-images.githubusercontent.com/9332608/30846401-d23148a4-a297-11e7-82b5-cc5f0f25b2de.jpg)
![2017-09-26](https://user-images.githubusercontent.com/9332608/30846402-d23ab5ce-a297-11e7-950f-935d4fe370f8.jpg)

**Comment by bobdenotter** [comment]
I'd be interested to know _why_ it breaks in the first place.. Is it reproducible in a reliable manner? Does the same thing happen, if you do it in batches? Like, upload 10 or 20 images, save it, upload 10 or 20 more, save again, etc.

**Comment by gwbonline** [comment]
I just finished an entry and when I do it i batches, I get no error. First I had to upload 100 images and after that I uploaded another 100 images.

Sometimes I also get the error when the entry contains less images, like 40.

**Comment by bobdenotter** [comment]
I'm _guessing_ it has to do with an upload limit on your server. As far as i can tell, there's no practical limit in Bolt itself on how many images an imagelist can contain.

**Comment by gwbonline** [comment]
Ok. I will look in to that. Do you need some other part of the error page to make more sense of this problem?

The other thing... In my case it is not possible to delete multiple images from the image list at once. Is this option not available? Bolt shows a red border around deleted images and then does not delete those images. After saving the entry, those images are back.

**Comment by gwbonline** [comment]
It's a file upload limit that is set server side, so I need to get used to upload images in portions.

Is multiple deletion of images from a image list possible for Bolt 3.4.0? And something that is talked about before I think, is file upload. Does this process get any smoother in a near future release?

**Comment by gwbonline** [comment]
Does someone else also encounter the issue with deleting multiple images from an image list field?
