### ISSUE TITLE
Argument 2 passed to Edit::action()

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7029]
Type error: Argument 2 passed to Bolt\Storage\ContentRequest\Edit::action() must be an instance of Bolt\Storage\Mapping\ContentType, string given, called in vendor/bolt/bolt/src/Controller/Backend/Records.php on line 94

Content::getContenttype() may return a string but Edit::action() requires ContentType object.

Simple solution is to create this object and pass it through, but it is marked as @derecated so probably all usages of this object have to be converted to array (which might be simple since ContentType extends ArrayAccess).

**Comment by GawainLynch** [comment]
How are you hitting this?

```
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

<!-- 
    * Write a short summary of the bug
    * Try to pinpoint it as much as possible
    * Try to state the _actual problem_, and not just what you _think_ the 
      solution might be.
-->

### Specifics

<!-- 
    * Mention the URL where this bug occurs, if applicable
    * What version of Bolt are you using (down to the very last digit!)
    * What method did you use to install Bolt
    * What browser and version you are using
    * Please mention if you've checked it in other browsers as well 
    * Please include *full error messages* and *screenshots* if possible
-->

### Steps to reproduce

<!-- 
    * Clearly mention the steps to reproduce the bug
-->

### Expected result

<!-- 
    * What did you _expect_ that would happen on your Bolt site?
    * Describe the intended outcome after you did the steps mentioned before
-->

### Actual result

<!-- 
    * What is the actual result of the above steps? 
    * Describe the behaviour of the bug 
    * Please, please include **error messages** and screenshots. They might mean 
      nothing to you, but they are _very_ helpful to us.
-->
```

**Comment by JarJak** [comment]
@GawainLynch 

### Bug summary

Type error: Argument 2 passed to Bolt\Storage\ContentRequest\Edit::action() must be an instance of Bolt\Storage\Mapping\ContentType, string given, called in vendor/bolt/bolt/src/Controller/Backend/Records.php on line 94

Content::getContenttype() may return a string but Edit::action() requires ContentType object.

### Specifics

Bolt version 3.3.5 installed with composer

### Steps to reproduce

Define own Content Type Entity which extends \Bolt\Storage\Entity\Content, add some data, then try to edit it in Admin panel

### Expected result

Edit page

### Actual result

Error appears

### Solution

I’ve added line
```
$this->app['storage.legacy_service']->setupContenttype($content);
```
before this line https://github.com/bolt/bolt/blob/3.3/src/Controller/Backend/Records.php#L94 
 And it works for me.

**Comment by GawainLynch** [comment]
Ah, OK that makes far more sense. Thinking about it, your proposed solution, wrapped in an `instanceof` conditional, is probably a good approach.

The `ContentRequest` classes are supposed to be transitional, and intended to be marked `@internal`, the type hints were very deliberate too … but as we missed the `@internal` we're stuck with them in v3, but want to further fix shortcoming like this in v4 … time pressure to release 3.0.0 was the killer :wink: 

Anyway, I am taking the rest of today off, but as always please feel free to PR your proposed change :+1:

**Comment by JarJak** [comment]
It would be great to stuck with Semantic Versioning and remove all those confusing legacy things in 4.0 :)

**Comment by GawainLynch** [comment]
> It would be great to stuck with Semantic Versioning and remove all those confusing legacy things in 4.0 :)

Oh, that is more that just an idea, it is already heavily underway!
