### ISSUE TITLE
[RFC] Thoughts on making Front-end controller more open for extensions in 4.0

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#7031]
Coming from the current lay-of-the-land in Bolt Translate.

There is currently no way to modify or add properties to the `record`/ `records` objects before they are being passed into the Twig templates/front-end routes (if i'm correct?).

It would be great if we'd use something like a decorator pattern or another (better?) way to make changes to the `record` / `records` objects without overriding the front-end these large portions of code.

**Comment by SahAssar** [comment]
well, there is events for some of it, but there is no way to modify how bolt's controllers match the slug to a record (as far as I know), which is the real motivation for translate to override the controller

**Comment by GawainLynch** [comment]
Good news everyone … Ensure [this is set to `true`](https://github.com/bolt/bolt/blob/3.3/app/config/config.yml.dist#L459-L463), listen on the `\Symfony\Component\HttpKernel\KernelEvents::VIEW` event where you'll get passed a `\Bolt\Response\TemplateView` and buy a :beer: for your friends :wink:
