### ISSUE TITLE
add a management system FAQ

### ISSUE THREAD

**Issue by You85** [bolt/bolt#7034]
New Feature? | Yes

it would be wise to define from the admin the questions and the answers for a page faq
Like this : https://www.powr.io/plugins/faq/standalone

**Comment by bobdenotter** [comment]
I'm slightly confused as to what it is that you would want? It looks like you've opened similar issues before: https://github.com/octobercms/october/issues/3080

Anyways, in Bolt you can easily define a contenttype called "FAQ", to house questions like this. For an example, check out this site which is built with out-of-the-box contenttypes: https://socialhubdenhaag.nl/kennisbank
