### ISSUE TITLE
Backend save fails on multiple AJAX requests

### ISSUE THREAD

**Issue by soapboxcommunication** [bolt/bolt#7050]
We are currently experiencing a save problem in the backend of Bolt version 3.2.1 . As long as you fill the content edit form with the new data and hit the submit button, it saves as expected on a few initial attempts but it fails when you repeatedly click the submit button and you only see the spinning wheel endlessly and the page hangs at a point at the end. We couldn't find the potential cause for this as yet. 

During the tests we have carried out on this issue so far, we found our another issue. When you hit the submit button to save content on the edit form, until the AJAX is complete, the button changes to a disabled class and fades it colour but actually it doesn't get disabled. You can still click on the faded submit button no matter if the first triggered AJAX call is complete or not. This leads to multiple pending AJAX calls in the queue and repeated JS actions which also cause a CkEditor bug with undefined values. To stop this happening, we have added the following JS code snippet to our custom backend JS file.

       var $submitButtons = $('#sidebarsavecontinuebutton, #savecontinuebutton');

        if ($submitButtons.length) {
            $submitButtons.on('click', function () {
                if ($('#editcontent').data('valid')) {
                    $(this).prop('disabled', true);
                }
            });

            $(document).ajaxComplete(function (e, jqXHR, settings) {
                if (settings !== undefined && settings.type.toUpperCase() === 'POST' && settings.url === '?returnto=ajax') {
                    $submitButtons.prop("disabled", false);
                }
            });
        }

We didn't want to overwrite Bolt's core JS files but we think that the proposed fix should be added to **/vendor/bolt/bolt/app/src/js/editcontent.js** under the **indicateSavingAction()** and **initSaveContinue()** function where the css disabled class is toggled to the submit buttons. It would be great, if the fix could be added to the future release of Bolt.

Details
-------

- Bolt Version:  3.2.1

**Comment by bobdenotter** [comment]
Hi, @soapboxcommunication. Please update the site to either the latest Bolt 3.3.6, or (if you have created 'local extensions') Bolt 3.2.20. Many bugs were fixed in the meantime. 

If the issue persists after that, we'll dig deeper.

**Comment by bobdenotter** [comment]
We've not been able to reproduce, and no further information was provided.. I'll close this issue for now, but feel free to re-open if new information pops up! :-)
