### ISSUE TITLE
Pagination - held status ignored - custom taxonomy

### ISSUE THREAD

**Issue by hotovec** [bolt/bolt#7051]
I’m using default “listing.twig” template to list my custom taxonomy items (record in records). But it seems that is not ignoring items with “held” status. The template does not render items, but they are included for example in Pager (total count). 

Screencast
-----------

https://www.dropbox.com/s/y2s4mhfsxs1zbl2/bolt-held-pager.mp4?dl=0

Details
-------

 - Relevant Bolt Version: 3.3.4, 3.3.6
 - Install type: Zip/tarball install 
 - PHP version: 5.6.30,  7.1.1 (MAMP OSX) 
 - Used web server: Apache

content type:
https://www.dropbox.com/s/940zxs97njjpsw8/Screenshot%202017-10-03%2018.20.32.png?dl=0

taxonomy:
https://www.dropbox.com/s/j5pj0toosmnivqz/Screenshot%202017-10-03%2018.20.54.png?dl=0

taxonomy route (using default listing.twig):
```
http://domain.dev/knihy/cesta-srdce
```

Blog db table (Sqlite) - held vs published statuses
https://www.dropbox.com/s/j6z9zpnap3nkgpn/Screenshot%202017-10-03%2018.22.18.png?dl=0

Reproduction
------------

- I have custom content type, using default listing values (from config.yml)
- I have custom taxonomy (behaves as categories)
- I have 29 items, but only three have status published, the rest of items are held
- using default listing.twig template, without modifications
- open taxonomy route in the browser
- held items are not rendered but, Pager is counting all items to calculate the number of pages

### Bug summary

can't paginate thru custom taxonomy listing

### Expected result

pagination should ignore items which have the held status set on

### Actual result

**Comment by hotovec** [comment]
Short XDEBUG. Maybe it is an issue?

https://www.dropbox.com/s/jw1t1ofo01fazi6/Screenshot%202017-10-03%2023.33.15.png?dl=0
Storage.php: getContentByTaxonomy() line 1126
It seems it is fetching data only from taxonomy table, then put the rowcount[count] directly to Pager.
But it ignores any check of item status (which is in content type table, not taxonomy table).

**Comment by bobdenotter** [comment]
I've looked at this, and it's the same issue as with the "sorting" of taxonomies: We first fetch the taxonomies from the table, and then cross-reference that with the actual contenttype, and only _then_ do we know the status. With the Database layer in Bolt 3, this can not be fixed. 

We're planning a full cutover to the new storage layer in Bolt 4, though. Unfortunately, for now this applies: 

```
# Note 1: Sorting on TAXONOMY-pages will give unexpected results, if it has a
#         pager.
#         If you need sorting on those, make sure you display all the records on one
#         page.
```

**Comment by hotovec** [comment]
No workaround? Some tip? Which way to try?

**Comment by bobdenotter** [comment]
You can work around it, if you don't use the built-in listings, but compile your own:

```
{% setcontent pages = "pages" where { 'categories': 'foo' } allowpaging limit 10 %} 
```

Other than that, I'm not aware of a workaround. 

I'll close this issue now. Not because I don't think it has merit, but more because we can't really fix it for now.
