### ISSUE TITLE
Add ability to disable HTML sanitizer

### ISSUE THREAD

**Issue by pstephan1187** [bolt/bolt#7058]
I am trying to use Bolt for a blog as a developer. I am using the markdown content type for my post body. I use all html tag type and even non-typical ones. But whenever I save my posts, the tags get all cleaned out. I know I can add tags to the htmlcleaner/allowed_tags config, but many of my tags still get stripped, and I cannot add custom tags everytime I write a post. It would be nice if I could turn it off all together.

 

Details
-------

 - Relevant Bolt Version: 3.3.6
 - Install type: Zip/tarball install
 - PHP version: 7.1
 - Used web server: Nginx version 1.11.9
 - For UX/UI issues: 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

Add `html, body, head, title, link, style, ` to the `htmlcleaner/allowed_tags` array in the `config.yml` file. Then set the `entries.fields.body.type` config value to `markdown`. Then create a blog post with a body with the contents found here: https://gist.githubusercontent.com/pstephan1187/ac19eab9ded8421fa3d63f0ac88838e6/raw/50776dd70f6051a497c9da0ee2a0324fad583d5c/post.md. Then visit the post. Most of the code snippets are missing a lot of content.

**Comment by GawainLynch** [comment]
The sanitizer is just a service on the application container (`$app['storage.field_sanitiser']`), so one option for you is to override that and inject a class that implements `SanitiserInterface`.

Oh, and a great write up in that gist :+1:

**Comment by pstephan1187** [comment]
Thanks. I am trying to move over my old blog from a home-built system to a real blogging engine. Where would I go about overriding the container instance? I am not used to symfony applications :)

**Comment by bobdenotter** [comment]
@pstephan1187 It looks like we're adding a setting for this in Bolt core. I expect a PR for this to land any day now. :-)

**Comment by GawainLynch** [comment]
OK, humble apologies for the delay … this whole thing sparked quite the debate and was an instrument for some changes. :smile: 

It is rather simple with a Bundled Extension. Basically, start with the brand spanking new [Quick Start](https://docs.bolt.cm/3.3/extensions/bundled/quick-start) guide to implementing a simple site Bundled Extensions, then you just need to refer to the [Registering Services](https://docs.bolt.cm/3.3/extensions/intermediate/service-providers#registering-services) section in the extension docs. You'd just create a new entry for `$app['storage.field_sanitiser']`, e.g.
```php
$app['storage.field_sanitiser'] = $app->share(function ($app) {
    return new MyCustomSanitizer();
});
```

As mentioned above, the new sanitizer class just needs to implement the contract for `\Bolt\Storage\Field\Sanitiser\SanitiserInterface` and you're there! :+1:
