### ISSUE TITLE
Bolt fails to install on MySQL with utf8mb4 encoding

### ISSUE THREAD

**Issue by helix84** [bolt/bolt#7060]
Bolt fails to install on MySQL with utf8mb4 encoding.

Details
-------

 - Relevant Bolt Version: 3.3
 - Install type: Zip/tarball install
 - PHP version: 7.0
 - Used web server: Apache 2.4.18

Reproduction
------------

### Steps to reproduce

* prepare a MySQL database (MariaDB 10.0.32).
* extract Bolt
* in config.yml, use the following settings:
database:
     driver: mysql
     charset: utf8mb4
     collate: utf8mb4_general_ci
* install Bolt

### Expected result

Bolt is installed successfully.

### Actual result

Bolt is installed, all databases tables are created successfully except for bolt_users, which fails to create with the following error:
```Error in query (1071): Specified key was too long; max key length is 767 bytes```
The error pertains to the following column:
```
CREATE TABLE bolt_users (
...
  email varchar(254) COLLATE utf8mb4_czech_ci NOT NULL,
```

and is explained e.g. here:
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes
or here:
https://github.com/BoltTranslate/Translate/issues/56#issuecomment-237057436

### Limitations
One of the proposed solutions is to set a global mysql variable, which may not be allowed in a shared hosting setting like the one I'm using in production.
```SET @@global.innodb_large_prefix = 1;```

### Proposed solution
I propose to decrease the column length to fit the utf8mb4 limit, i.e. from varchar(254) to varchar(191).

And, yeah, nobody likes brown M&Ms.

**Comment by bobdenotter** [comment]
Have you perhaps seen #6430 ? I think it has a workaround for this problem.

**Comment by bobdenotter** [comment]
My apologies! Didn't see your PR, you've obviously seen the other one! 👍

**Comment by helix84** [comment]
@bobdenotter Which workaround do you mean specifically? 
Commenting out charset: and collate:, then re-running $ ./app/nut database:update ?

Or changing the limit via connection settings? (It's a global option, so no luck there on a shared hosting).
Also relevant might be that I can't create the DB as utf8mb4 as the it has already been created as utf8 on the shared hosting I use.

**Comment by helix84** [comment]
I actually glossed over this particular comment comment: "spec requires 254 characters" :(

https://github.com/bolt/bolt/issues/6430#issuecomment-285861773

**Comment by helix84** [comment]
Just a note: MySQL 8.0.1 changed the default charset from latin1 to utf8mb4:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-charset
