### ISSUE TITLE
Custom Datetime db type incompatible with Doctrine

### ISSUE THREAD

**Issue by cwoldt** [bolt/bolt#7065]
Bolt has it's own field types for it's database. One of those types is the `DateTimeType`. Now this type overrides the standard type that's supported by Doctrine and uses `Bolt\Storage\Mapping\Type\CarbonDateTimeType` instead.

So far so good. Since Doctrine no longer knows what this type is about, it fails to set the correct default values, for example if you want the CURRENT_DATETIME set as default value.
This crashes in Doctrines date time defaults:

**doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php**
```
    public function getDefaultValueDeclarationSQL($field)
    {
        $default = empty($field['notnull']) ? ' DEFAULT NULL' : '';

        if (isset($field['default'])) {
            $default = " DEFAULT '".$field['default']."'";
            if (isset($field['type'])) {
                if (in_array((string) $field['type'], array("Integer", "BigInt", "SmallInt"))) {
                    $default = " DEFAULT ".$field['default'];
                } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz')) && $field['default'] == $this->getCurrentTimestampSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimestampSQL();
                } elseif ((string) $field['type'] == 'Time' && $field['default'] == $this->getCurrentTimeSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimeSQL();
                } elseif ((string) $field['type'] == 'Date' && $field['default'] == $this->getCurrentDateSQL()) {
                    $default = " DEFAULT ".$this->getCurrentDateSQL();
                } elseif ((string) $field['type'] == 'Boolean') {
                    $default = " DEFAULT '" . $this->convertBooleans($field['default']) . "'";
                }
            }
        }

        return $default;
    }
```

Details
-------

 - Relevant Bolt Version: 3.2
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache 2.4
 - For UX/UI issues: Chrome

Reproduction
------------

Create your own schema class in your own custom extension and put these column definitions:

```
namespace Bolt\Extension\Something\Storage\Schema\Table;

use Bolt\Extension\CND\Versioning\Store\StoreInterface;
use Bolt\Storage\Database\Schema\Table\BaseTable;
use Doctrine\DBAL\Types\Type;

class MyTable extends BaseTable
{

    protected function addColumns()
    {
        // ...
        $this->table->addColumn(self::COLUMN_NAME_DATE,        Type::DATETIME, ['default' => 'CURRENT_TIMESTAMP', 'notnull' => false]);
        // ...
    }
}
```

**Comment by GawainLynch** [comment]
This is an old bug in DBAL, not Bolt. It will be fixed in the next release of DBAL via https://github.com/doctrine/dbal/pull/2835

**Comment by ToBe998** [comment]
Which Bolt version will include that DBAL fix?

**Comment by GawainLynch** [comment]
Whichever you pull in via a `composer update doctrine/dbal`, but upstream is pretty slow and not known for being able to make timely releases. 

Also worth noting that they've yet to backport the change to any branch except master, so it could be a DBAL 2.7 only change, and regardless they might only backport as far as 2.6 which is PHP 7.1+.

**Comment by ToBe998** [comment]
My current Bolt 3.2 requests doctrine/dbal `^2.5`. So this version will not be fixed?
What version of Bolt will require a version 2.7+?

**Comment by GawainLynch** [comment]
> My current Bolt 3.2 requests doctrine/dbal ^2.5.

`^2.5` means "any version greater than 2.5.0, that is less than 3.0.0"

> So this version will not be fixed?

I can't tell you what is in upstream's plans, we don't run the Doctrine project.

> What version of Bolt will require a version 2.7+?

Probably Bolt 5 will require Doctrine DBAL v3, but that is not a valid question in this context as if the constraint is `^2.5` and your system supports all the requirements, then you can install up to 2.999999999.x on Bolt 3.2

**Comment by ToBe998** [comment]
> ^2.5  means "any version greater than 2.5.0, that is less than 3.0.0
That's all i needed to hear. ;)
