### ISSUE TITLE
quick install command line

### ISSUE THREAD

**Issue by adriano-ghezzi** [bolt/bolt#7072]
under windows 10
app/nut is empty

vendor/bin/nut
got error bootstrap.php not found

under linux
Whoops, looks like something went wrong.

1/1 ClassNotFoundException in XmlUtils.php line 52: Attempted to load class "DOMDocument" from the global namespace.
Did you forget a "use" statement?

    1. in XmlUtils.php line 52

**Comment by bobdenotter** [comment]
Hi, could you give more details on what you're doing exactly? `nut` ought to work. Also, have you reviewed the requirements here: https://docs.bolt.cm/3.3/getting-started/requirements# ? 
You might be missing the `xml` extension.

**Comment by adriano-ghezzi** [comment]
quick install from command line steps:
windows 10
----------------
curl -O https://bolt.cm/distribution/bolt-latest.tar.gz ok

tar -xzf bolt-latest.tar.gz --strip-components=1 ok but app/nut is empty

try to run php vendor/bin/nut init
error require boostrap (not found)


linux
-----
curl -O https://bolt.cm/distribution/bolt-latest.tar.gz ok
tar -xzf bolt-latest.tar.gz --strip-components=1 ok

php app/nut init
got error :

Whoops, looks like something went wrong.

1/1 ClassNotFoundException in XmlUtils.php line 52: Attempted to load class
"DOMDocument" from the global namespace.

Did you forget a "use" statement?

   1. in XmlUtils.php line 52

however bolt is up and running I can create first user.

database configuration suggestions
it would be nice to ask confirmation before create sql lite db

in case of another database
in the documentation you could warn user they have to create
database before run firfirst user

TIA




2017-10-12 11:02 GMT+02:00 Bob den Otter <notifications@github.com>:

**Comment by milosa** [comment]
I  noticed the same problem. If you download the releases, such as [beta4](https://github.com/bolt/bolt/releases/download/v3.4.0-beta4/bolt-v3.4.0-beta4.tar.gz) or [3.3.6](https://github.com/bolt/bolt/releases/download/v3.3.6/bolt-v3.3.6-flat-structure.tar.gz), the /app/nut file is empty or it only contains `../vendor/bin/nut`. The nut file in /vendor/bin/nut contains `../bolt/bolt/app/nut`.

Not sure what's up with that. I fixed it by copying the content from github to the nut files.

**Comment by GawainLynch** [comment]
> I think i figured it out. The archives contain symbolic links to create the nut file and other files. This doesn't work on windows.

Just opened this to comment on exactly that :wink:

**Comment by bobdenotter** [comment]
Closing this one. Feel free to re-open if you want to discuss it further.

**Comment by humaxi** [comment]
When will this be fixed?
