### ISSUE TITLE
[3.4] Deleting folder produces two prompts

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#7079]
First:
![image](https://user-images.githubusercontent.com/1427081/31549866-bb4868ca-b02f-11e7-8afd-e91383fe31e7.png)
Second:
![image](https://user-images.githubusercontent.com/1427081/31549875-c3dccb98-b02f-11e7-9011-3ab2b7ac90ee.png)

**Comment by bobdenotter** [comment]
See also #5590.
