### ISSUE TITLE
`{{ image('foo.bar') }}` gives an error, should not do that. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7080]
For example: 

```
{{ image('foo.bar', 100, 100) }}
```

Outputs: `thumbs/100x100c/foo.bar`

```
{{ image('') }}
```

outputs nothing. 

Currently `{{ image('foo.bar') }}` gives an error like below. It should do either of the above two. 

![screen shot 2017-10-13 at 16 08 59](https://user-images.githubusercontent.com/1833361/31550238-f7089528-b030-11e7-81e6-2414b0d90aab.png)

**Comment by GawainLynch** [comment]
Well, it is Friday … so after 17h I really don't see the problem with Foo going to the bar, do you? I mean … :beers: !

**Comment by GawainLynch** [comment]
Quite seriously though, the exception and reasoning behind it is correct.

**Comment by bobdenotter** [comment]
@GawainLynch Yes, technically correct. Which is the best kind of correct.. I do think that it should be handled in a more user-friendly way, like we do with thumbnails. 

`{{ thumbnail('foo.bar') }}` => `thumbs/100x100c/foo.bar` which displays the configured "missing image"

**Comment by CarsonF** [comment]
I'm confused. Does `{{ image('') }}` output nothing or throw exception?

**Comment by bobdenotter** [comment]
@CarsonF It outputs nothing.

**Comment by bobdenotter** [comment]
Sorry, clarified in topic starter

**Comment by CarsonF** [comment]
Ok so in first example `foo.bar` is a valid file and the third example it is not. Correct?

**Comment by bobdenotter** [comment]
No, `'foo.bar'` is a literal string, that does not correspond to a file on the server in either case.

**Comment by SahAssar** [comment]
All these examples deal with non existent images, so shouldn't they all show the image 404?

**Comment by bobdenotter** [comment]
I think it'd make sense that thumbnailing or `|image()` of an empty string should return "nothing", but apart from that I agree: The case that produces an error now should return a the "image 404".

**Comment by GawainLynch** [comment]
> Why am I getting a 404?

- Using the wrong field to get data
- Using the wrong field property to get data
- File not found
- File name incorrect
- File name omitted
- General exception from a PHP error doing X
- General exception from a Twig error doing Y
- List … goes … on …

As opposed to …

> Why am I getting this exception

- Trace tells you the file isn't found, where and why.

**Comment by bobdenotter** [comment]
A client-facing website shouldn’t break on a misging image. Just like we don’t display a stack trace on a 404 page.

**Comment by GawainLynch** [comment]
> A client-facing website shouldn’t break on a misging image.

Haven't "misging images" been outlawed? My current understanding is that only "missing images" are tolerated … I could be wrong though.

Nonetheless, isn't this the point … this only happens when debug is on, and in that case, it most certainly should throw an exception

**Comment by bobdenotter** [comment]
> misging images

Phone typing. ;-)

Anyhow, this is what an editor gets in a production environment with `debug: false`: 

![screen shot 2017-10-14 at 11 24 06](https://user-images.githubusercontent.com/1833361/31574547-468aa0ea-b0d2-11e7-87a5-3dc2c786ff63.png)

That's _much_ less helpful than the 404-image.
