### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by adetheprince** [bolt/bolt#7083]
A brief description of the issue goes here.

 

Details
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 | 3.4 | 3.5 | master ]
 - Install type: [ Zip/tarball install | Composer install | GitHub checkout ]
 - PHP version: [ 5.5 | 5.6 | 7.0 | 7.1 | 7.2 ]
 - Used web server: [ Apache | Nginx ] version [ version ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Actual result

Hi there
I have installed bolt but then nothing is loading, I am getting teh above error.
Can you please help me as I cant find any reference with that error.
Also How do you edit the database as I couldn't understand your tutorial on database.
I have modified the config.yml and I am using mysql all set on that config but still no joy.
Thanks 

ParseException in ParseException.php line 33:
Unable to parse at line 1 (near "﻿# Database setup. The driver can be either 'sqlite', 'mysql' or 'postgres'.").

**Comment by bobdenotter** [comment]
Hi @adetheprince,

It looks like you made an error in your YML file. Did you put anything in front of the YML? 

Would you also be so kind to specify the versions of Bolt, PHP, etc that you're using, as is asked in the issue template.

The issue tracker is meant for actionable issues with Bolt itself, so i'm going to close this. I will read replies, though.
