### ISSUE TITLE
Embed button in WYSIWYG needs extra allowed tags/attributes

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7085]
See screenshot: 

![screen shot 2017-10-15 at 07 11 11](https://user-images.githubusercontent.com/1833361/31581985-180a535e-b178-11e7-9ead-4a23f0017b5d.png)

**Comment by bobdenotter** [comment]
Actually, we should _not_ fix this. Twitter's embed uses a `<script>` tag, and I'm not comfortable at all enabling that unknowingly for users. 

https://github.com/bolt/bolt/blob/3.3/src/Storage/Field/Sanitiser/Sanitiser.php#L145-L153

IMHO, If users want this, they'll have to explicitly disable the sanitiser. Because, if we're allowing `<script>`, we might as well allow _everything. 

See #7058

**Comment by SahAssar** [comment]
Yeah, IMO the "fix" for this is better docs.
