### ISSUE TITLE
bolt_field_value rows are not deleted when the item is deleted

### ISSUE THREAD

**Issue by Jyri-K** [bolt/bolt#7088]
When you delete an item that has values in a repeater field, the item's row is deleted from database but the repeater field rows are left behind in the bolt_field_value table. This causes weird situations when a new item with same id is created.

Details
-------

 - Relevant Bolt Version: 3.3.6 (flat structure)
 - Database: SQLite 
 - Install type: Zip
 - PHP version: 5.5.12
 - Used web server: WAMP, Apache 2.4.9

Reproduction
------------

    * Create a content type with one repeater field with 2 sub fields (image and textarea for example)
    * Save a new item, then delete it
    * Check database table bolt_field_value.

### Expected result
    * All rows in bolt_field_value related to the deleted item should be deleted as well

### Actual result
    * Deleted item's data is left behind in bolt_field_value

Before delete:
![before](https://user-images.githubusercontent.com/7044266/31587957-90c258d4-b1f3-11e7-8758-45429d8a7c5d.png)

After delete:
![after](https://user-images.githubusercontent.com/7044266/31587958-95010206-b1f3-11e7-96e4-64d6876e19de.png)

**Comment by rossriley** [comment]
Yes, this has been on my todo-list for a while. Assigned and I'll try and get a fix in soon.

**Comment by bobdenotter** [comment]
Fixed by #7109
