### ISSUE TITLE
Remove empty space above postfix fields contenttype

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#7089]
Why do some fields have more space below their buttons and above the postfix then other fields? I have added a screenshot to show the issue. This does not happen (2) with an imagelist field or a field for uploading a file. But there is unnecessary empty space below the buttons for an single image field (1). It looks better when a postfix has no empty space above it for all fields.

I use Bolt 3.3.6.
![space](https://user-images.githubusercontent.com/9332608/31601209-5d3b8718-b259-11e7-8c66-4f0859e1e485.jpg)

**Comment by SahAssar** [comment]
I think this is because the postfix comes after the actual field, and the preview box is part of the field. So the preview box pushes it down a bit.

**Comment by bobdenotter** [comment]
Yes, this is because of what @SahAssar described. I don't think it's wise to change this now, as we'll redo this part for 4.0.

I'm going to close this one, but feel free to re-open, if you'd like to discuss it further.
