### ISSUE TITLE
redirect to /bolt/users/edit/

### ISSUE THREAD

**Issue by cjuhong** [bolt/bolt#709]
Hi,

I followed the instruction to setup the bolt project;
http://docs.bolt.cm/installation

when all was done, I opened the browser to access localhost, but it redirected to localhost/bolt/users/edit

Anyone can help?

Thanks a lot.

**Comment by jamespsterling** [comment]
In my case, it was the rewrite module not loaded

**Comment by kikocastro** [comment]
This solution worked for me:

" I just had this same issue and, assuming you are using httpd, you will need to go to /etc/httpd/conf then open http.conf by running sudo vi httpd.conf and then change "AllowOverride" to:

<Directory />
    Options FollowSymLinks
    AllowOverride All
</Directory>
You may also need to change AllowOverride All here:

# AllowOverride controls what directives may be placed in .htaccess files.
# It can be "All", "None", or any combination of the keywords:
#   Options FileInfo AuthConfig Limit
#
    AllowOverride All
Then you need to restart httpd by running apachectl -k restart. Note, you may need to actually run sudo apachectl -k restart.

Let me know if that helps." 

from here: http://stackoverflow.com/questions/12292992/permalinks-on-wordpress-ec2

**Comment by Fedik** [comment]
nothing works, even if I leave just:
```
RewriteEngine on
RewriteBase /bolt-test/ # has no effect
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !=/favicon.ico
RewriteRule ^ ./index.php [L]
```

other CMS and Frameworks works on same server without problem

**Comment by bobdenotter** [comment]
@Fedik Are you running Bolt in the "root" of your server? If not, is there a `.htaccess` in a folder above it? 

Otherwise try creating a new vhost, so Bolt can be in the root of that.

**Comment by Fedik** [comment]
@bobdenotter thanks for quick answer, 

no, I tried make test in subfolder `test.h/bolt-test` ... 
make new vhost just for test is to much work :wink: 
but thanks for sugestion I will try later...

**Comment by Fedik** [comment]
ok, change link to `index.php/bolt/users/edit/` helps :smile:

**Comment by jadwigo** [comment]
@Fedik are you sure the `mod_rewrite` is loaded and working? see my comment a bit further up: https://github.com/bolt/bolt/issues/709#issuecomment-55281481 (based on the fact that if you add the `index.php/` and it's working then, it looks like the rewrites don't happen)
