### ISSUE TITLE
[3.4b4] icon_one on singleton definitions breaks backend

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7103]
`icon_many` does work (although not showing icon that was set) but `icon_one` breaks backend:

![2017-10-18 17-36-47](https://user-images.githubusercontent.com/1833020/31748875-fcd326dc-b42a-11e7-97a1-d0fc3ced71a4.png)

**Comment by eduardomart** [comment]
Never mind.... I think it's a space at the end, but strangely the error only gets triggered when I change `icon_,many` to `icon_one`

**Comment by bobdenotter** [comment]
The Yaml parses really shouldn't care about trailing whitespace.. I made mine look like this, and it worked fine:

![screen shot 2017-10-19 at 06 57 05](https://user-images.githubusercontent.com/1833361/31754844-b22e65d6-b49a-11e7-8791-88ff529ad5ec.png)

Are you sure the file wasn't corrupt in another way? Is line 372 the last line? What did the `[1/2]` error say?

**Comment by GawainLynch** [comment]
This is a parse error from your YAML file, due to an error you YAML … um … file :wink: 

The exception is thrown [here](https://github.com/bolt/filesystem/blob/2.4/src/Handler/YamlFile.php#L51) after being thrown by Symfony's YAML parser and rethrown as a consistent `bolt/filesystem` exception.
