### ISSUE TITLE
(Very very) minor text change for referencing a record in backend list view

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7104]
I have set this in my `contenttypes.yml`
`singular_name: page`

When in backend list view, and clicking the edit button for one of the records, I see this:
![2017-10-18 18-43-54](https://user-images.githubusercontent.com/1833020/31750353-58e0a676-b434-11e7-97f7-cbc48ed64407.png)

However, I believe the menu should say "Publish *page* / Duplicate *page* / Delete *page*", since these actions only apply to a single record.

**Comment by GawainLynch** [comment]
Fixed in #7105
