### ISSUE TITLE
[3.2] depublish not working

### ISSUE THREAD

**Issue by vidoq1** [bolt/bolt#7118]
Hi.
I'm Using Bolt 3.2.0 on Apache with php5.6
Can't setup depublish date for my news and other content types.
I checked repo for 3.2, 3.3 and 3.4 ver, no changes where made to file: bolt/src/Storage/EventProcessor/TimedRecord.php
https://github.com/bolt/bolt/blob/3.4/src/Storage/EventProcessor/TimedRecord.php

So there're two options, 
- I'm doing something wrong and forgot to add\apply some option.
- Problem persist for all users.

Could someone tell me how depublish date should work automatically?

**Comment by bobdenotter** [comment]
Hi vidoq1,

What have you done to try it out? Set a record to 'depublish' and then seeing if it goes away, after a while? Are you sure no caching is interrupting it? 

Also, 3.2.0 is _ancient_. You should at least update to 3.2.20, since _many_ bugs were fixed, and it should be a painless update.

**Comment by vidoq1** [comment]
> What have you done to try it out? Set a record to 'depublish' and then seeing if it goes away, after a while?
Yep, set a record with state: published and set a depublish date to a near future.

>  Are you sure no caching is interrupting it?
I don't cache content-types such news etc.

> You should at least update to 3.2.20
We're trying to run in 3.2.0 because I have so many changes and add my extension module, so I dunno if it will work on newer version ;))) 

Don't know if it's matters, but this file:
https://github.com/bolt/bolt/blob/3.4/src/Storage/EventProcessor/TimedRecord.php
is same for all versions, it's a controller for depublished and future publish states.

**Comment by vidoq1** [comment]
sorry, bolt ver 3.2.2

**Comment by bobdenotter** [comment]
> Yep, set a record with state: published and set a depublish date to a near future.

And did you refresh the website, a short while _after_ this depublish date has passed.

> We're trying to run on 3.2.0 because I have so many changes and add my extension module, so I dunno if it will work on newer version ;)))

Upgrading to 3.2.20 should be painless and easy.. there's 18 releases worth of fixes in it. 

> is same for all versions, it's a controller for depublished 

There's a lot more code, interacting :-)

**Comment by vidoq1** [comment]
> Upgrading to 3.2.20 should be painless and easy.. there's 18 releases worth of fixes in it.

Ok, I will try and then reply here

**Comment by GawainLynch** [comment]
As mentioned by @bobdenotter this was fixed in one of the many PRs to land for timed publishing during the 3.2 life cycle (and 3.2 is now end-of-life).

The reopen button is here if you need :+1:
