### ISSUE TITLE
No Search in "Repeater" FieldType

### ISSUE THREAD

**Issue by develth** [bolt/bolt#7126]
Would be nice if the search also shows results for the content in the "repeater" field type

**Comment by bobdenotter** [comment]
This is similar to #5829. Sometime, somewhere, we'll implement a module to properly index, cache and make searchable all content. Even the text in linked tables. 

So, we hear you, and it's on our list, but this is not "low hanging fruit". :-)

**Comment by develth** [comment]
Thanks for the quick reply. 

Not really nice to hear that giving the enduser a good experience is not a "low hanging fruit".

**Comment by bobdenotter** [comment]
Hi @develth, 

English is not my first language, so I may not have expressed myself properly. 

["Low hanging fruit"](https://www.urbandictionary.com/define.php?term=low-hanging%20fruit) is a "quick win" or "easy fix". I meant to say that this is a complicated thing to fix. It's important, and we _do_ try to give users a good experience, but it's not simple to implement.

**Comment by develth** [comment]
Hey @bobdenotter 

if my PR solves that, it wasn´t as complicated ;)

Cheers, 
Thomas
