### ISSUE TITLE
setcontent returns unpublished data on 404 pages

### ISSUE THREAD

**Issue by grandgeorg** [bolt/bolt#7132]
The setcontent bolt-twig function returns data other than 'published' on notfound pages.

 

Details
-------

 - Relevant Bolt Version: 3.3.6
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache 2.4

Reproduction
------------

We have configured notfound template in config.yml (notfound: error404.twig)
The error404.twig extends 'partials/main.twig'.
In main.twig we use setcontent (for navigation purposes on a contenttype like:
```
{% setcontent myvar= 'mycontenttype' %}
```
With other than the error404.twig only content with status 'published' is returned but with error404.twig also content with status 'held' is returned. This must be an error.
We can use a workaround, but it's only that, a workaround, which should not be necessary:
```
{% setcontent myvar= 'mycontenttype' where { status: 'published' } %}
```

**Comment by GawainLynch** [comment]
Thanks for reporting this, @grandgeorg … fix inbound :smile:
