### ISSUE TITLE
Password reset procedure is flawed

### ISSUE THREAD

**Issue by tobias2k** [bolt/bolt#714]
Currently, when you hit "forgot password", the system sends you an actual password by e-mail, and without user-administrator permissions, there is no way to change it.

This means that the password is easily compromised through a number of possible attack vectors:

* Monitoring the stream of outgoing e-mail from the Bolt server at the network level
* Compromising the SMTP server
* Compromising a user's mailbox

The usual way to go about this is to provide a one-time access token instead of an actual password, and have the users change their passwords themselves; this way, the actual password is never transported over an unsecured channel (provided the Bolt backend uses SSL), and the time window for a successful attack can be limited by invalidating the tokens after first use, or after a relatively short time period (say, 30 minutes).

Of course this is not a water-tight system either, but it requires an attacker to monitor the e-mail activity in near-real-time, making large-scale attacks less feasible.

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.

**Comment by DavidOliver** [comment]
I just tested the password reset and it's still the case that a new password is actually included in the email.

> The usual way to go about this is to provide a one-time access token instead of an actual password, and have the users change their passwords themselves; this way, the actual password is never transported over an unsecured channel (provided the Bolt backend uses SSL), and the time window for a successful attack can be limited by invalidating the tokens after first use, or after a relatively short time period (say, 30 minutes).

This sounds spot on to me.

**Comment by DavidOliver** [comment]
I suggest this issue is re-opened as passwords are still put in emails.

**Comment by bobdenotter** [comment]
@DavidOliver If you'd like to help out in implementing the improvements for this, you're more than welcome.. Feel free to join us on Slack, if you want to discuss potential approaches.

**Comment by DavidOliver** [comment]
Hi @bobdenotter. I'll take a look and see what I can do. I'm not yet very accomplished at this sort of thing, and may ask things here if that's okay.

**Comment by GawainLynch** [comment]
> I'm not yet very accomplished at this sort of thing, and may ask things here if that's okay.

Here is fine, but also we have our day-to-day discussions on things core development related in the #development channel on [our Slack](https://slack.bolt.cm/) if you're interested.

**Comment by zomars** [comment]
Is [this approach](https://www.smashingmagazine.com/2017/11/safe-password-resets-with-json-web-tokens/#password-reset-process-overview) acceptable?
