### ISSUE TITLE
[3.4] Distro has a new empty `var/` folder.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7148]
Which it shouldn't have, apparently.  :-)

**Comment by GawainLynch** [comment]
Copying the details of the Slack conversation to here …

@GawainLynch
> OK, so the `var/` one is what I thought … and I am not sure we should "fix" it … basically `\Bolt\Composer\Script\DirectoryConfigurator::updatePermissions()` does what the name suggests, and creates directories if they don't exist based on what PathResolver has defined
> `var/` itself is just Forward Compatibility for v4's layout
> So how do you feel about just having the directory removed in the compile script for the distro packages?

@bobdenotter 
> If we want to, we can just `rm` it, when making the distro…

**Comment by bobdenotter** [comment]
Fixed in https://github.com/bolt/bolt-distribution/commit/fab9a9bb6e2031dd64be259858020e8dc59eeab1
