### ISSUE TITLE
[3.4] Using more than one taxonomy makes overview lose grouping..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7149]
In a default setup, pages has: `taxonomy: [ groups ]`. Looks like this: 

![screen shot 2017-11-05 at 13 39 54](https://user-images.githubusercontent.com/1833361/32414795-f22434ee-c22e-11e7-85ce-0c20bc65ad19.png)

If you change that to `taxonomy: [ groups, tags ]`, the overview will look like this: 

![screen shot 2017-11-05 at 13 40 18](https://user-images.githubusercontent.com/1833361/32414796-f51a9af8-c22e-11e7-8162-9fe3f8f8d066.png)

Note: The _order_ is correct, just the headings are missing.. At first glance, it seems `$content['multiplecontent']` gets set, but is missing the `group` in each record.

**Comment by GawainLynch** [comment]
Fixed in #7155
