### ISSUE TITLE
[3.4] Records "Disappear" when adding "groups".

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7150]
If you add `taxonomy: [ groups ]` to a contenttype that didn't previously have it, and you then add a group to _one_ record, that will cause all other records to disappear from the overview.. 

Steps to reproduce: 

1) Change `taxonomy: [ groups ]` in the default 'Entries' contenttype.

2) See it work OK in the backend. (except for the missing "(no grouping)" subheading).

![screen shot 2017-11-05 at 13 50 51](https://user-images.githubusercontent.com/1833361/32414895-5d282a6a-c230-11e7-9d0f-07976ea0d925.png)

3) Then, when you edit any record, and assign a group to it, all other records will seemingly disappear.

![](http://g.recordit.co/aKgatPFeGw.gif)

**Comment by bobdenotter** [comment]
Fixed in #7158

**Comment by GawainLynch** [comment]
Fixed in #7158 by 3 :koala:
