### ISSUE TITLE
[3.4] After an 'action' on a record in overview, the ordering gets lost.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7151]
If you have a default 'pages' CT with a grouping ordering, it goes all wonky on the next pageview. Refresh the page again, and it's OK.. 

This happens on publish, unpublish and delete alike..

See screencast: 

![](http://g.recordit.co/tPKCucziol.gif)

**Comment by GawainLynch** [comment]
Fixed in #7157
