### ISSUE TITLE
CTRL-S / OPTION-S should save a page. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#717]

**Comment by kehugter** [comment]
@bobdenotter: this doesn't seem to be working in Bolt 2.2.19 for any kind of editable page.

**Comment by bobdenotter** [comment]
@kehugter It does, _except_ for when a CKeditor field has focus. The wysiwyg fields override this. If you first click outside of a CKeditor field, CTRL-S should work.

**Comment by kehugter** [comment]
Oh, right. Is that intended? IMO the most useful time to hit CTRL-S is while CKeditor is focused.

[Bypassing CKeditor key bindings](http://stackoverflow.com/questions/3245797/how-to-use-custom-keyboard-shortcuts-within-ckeditor-with-jquery) looks non-trivial but not impossible.

**Comment by bobdenotter** [comment]
@kehugter It's not intended, just a side-effect that we never took the time to fix. I'd love it if we could fix this.. 

I'm going to open a new bug issue for it. See #5074.
