### ISSUE TITLE
[bug]  error when missing 'preview' route 

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7175]
I'm getting an error if i'm missing `preview` route:
![image](https://user-images.githubusercontent.com/2145313/32851739-6da1f0ca-ca68-11e7-8f28-e68dc3e02a93.png)

When i add `preview: ...` to my routing.yml - all becomes fine.

> version is 3.4.0

**Comment by GawainLynch** [comment]
Did you notice [this comment](https://github.com/bolt/bolt/blob/3.4/app/config/routing.yml.dist#L11-L13)? :wink:

**Comment by bobdenotter** [comment]
This is one of those things: 

 - "Doctor, it hurts if i hit my toe with a hammer"
 - Doctor: "Then stop hitting your toe with a hammer."

Why would you remove the `preview` route?

**Comment by Boorj** [comment]
From version to version this list is silently growing! I appreciate your humor, but is there any notice like "required routes list"? Looks like if this notice is inside distrib, i won't see it when i update. And no info in "bolt 3.4.0 released" post.

**Comment by Boorj** [comment]
> Why would you remove the preview route?
i didn't remove it, my routing.yml is migrating from project to project, and previously it was ok. Actually, couple versions ago i had same problem with `homepage` route: i was using `home` to point `/` path

**Comment by bobdenotter** [comment]
It's not listed in the release notes, because I don't think anything relevant was changed in that area. The `preview: ` route has been in the config since before Bolt was called Bolt, and the only "breaking change" in it happened in Bolt 2.0. I'm sorry that this is an inconvenience to you, but please know that this is not a deliberate change on our part.

**Comment by Boorj** [comment]
I agree, maybe my setup is **too custom**. I'm using custom folders, but this deserves a line in docs, i suppose. Like warning _Don't erase unused preview folder, don't worry it's for logged users only_ or something else.

**Comment by Boorj** [comment]
Why it couldn't be also added as fallback to default if it's missing? And `routing.yml` will contain only user-defined routes. It will make route config neater. Also user will be able to override default routes and its params.

**Comment by bobdenotter** [comment]
I'm not trying to be obtuse, but I think it literally says that where it matters: Near the spot you delete it: 

> Changing these might give unexpected results or even break your website. 

Adding it to the docs won't do much good. It'll mainly mean the docs get more and more verbose, making it harder to find something, if we added all these edge cases. 

This warning has been in place for more than 4 years: https://github.com/bolt/bolt/commit/19d5978e862ca

> Why it couldn't be also added as fallback to default if it's missing? 

Users already _can_ do this. We just expect people to read (and heed) the warnings, or they are on their own.

**Comment by Boorj** [comment]
@bobdenotter @GawainLynch , anyway, what you think about the idea that system will have a file with only user defined routes? It 
- makes system more robust (like in my case)
- looks logically okay : you have _system routes_ and _user routes_ . 
- lets you to get rid of `# Place your own routes here, that have a LOWER priority than the default routes.`, because the order of file imports will be strict

Don't punch this idea. Of cours, all bolt users should read all warnings inside default configs, if they want a guarantee of stable work. But i wouldn't bet that people really do. And i'm suggesting nice solutions: fallback to hardcoded routes *or* import 2 files - with system routing and user-defined routing.

**Comment by SahAssar** [comment]
Well, in some cases you can modify the system routes (if you don't outright remove them), so it's nice to have them modifiable.

**Comment by Boorj** [comment]
Yes, then it could be inside your `routing.yml`. But all routes in that file are user defined.

**Comment by bobdenotter** [comment]
Looks like during the move to SF4, we'll also be adopting a new router component, which allows us to do exactly this thing. 
As such, I think we shouldn't spend too much time on it now, but rather focus efforts on moving forward. 

I'm going to mark this as "wontfix", unless somebody wants to work on it. In which case, i'll happily re-open it, and provide help on getting the issue fixed.
