### ISSUE TITLE
[bug] error when new field added to singleton

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7176]
### repro
- I have added new singleton "settings". 
- Edited that, saved. 
- Then added new field `motto`
- updated the page (F5). Address was `http://mysite.dev/bolt/editcontent/settings/1`

Error appeared, which was expected to be cought:
![image](https://user-images.githubusercontent.com/2145313/32858821-449c83fe-ca7f-11e7-97d2-8f9d13e67582.png)

**Comment by eduardomart** [comment]
I think you need to update the database before refreshing the page.

**Comment by Boorj** [comment]
yes, i know the way to solve that. But i'm not sure that bolt should throw an exception. It could be caught and shown as flash message

**Comment by bobdenotter** [comment]
The impact of this bug is not very high, because while it strictly is a bug, it's also something that can be remedied in a few ways. 

Nevertheless, it's not ideal, and it can be made to work better.. Klaus, if I help you pinpoint the issue, are you willing to help us fix it by making a PR for it?

**Comment by Boorj** [comment]
should it be done as a fix in panel, or should it be cought as an exception and shown as a message?

**Comment by Boorj** [comment]
should it be done as a fix in panel, or should it be caught as an exception and shown as a message?

**Comment by bobdenotter** [comment]
I haven't been able to reproduce this yet..

My settings are strict: 

```
debug: true
debug_show_loggedoff: false
debug_error_level: -1          
debug_error_use_symfony: true    
strict_variables: true
```

I've made a singleton, and added a field to it.. Getting the "red bar" as expected, but no exception is thrown: 

![screen shot 2017-11-28 at 14 59 22](https://user-images.githubusercontent.com/1833361/33323518-fd2226d2-d44c-11e7-9566-664c6814f442.png)

@Boorj Can you still reproduce this?

**Comment by Boorj** [comment]
@bobdenotter i'll report

**Comment by Boorj** [comment]
hm.. looks like it works
