### ISSUE TITLE
[RFC] Add support for using environment variables in theme.yml

### ISSUE THREAD

**Issue by romulo1984** [bolt/bolt#7177]
Currently the environment variables can only be used in the main config file (`config.yml` and `config_local.yml`). I think it might be interesting to support the same feature in the theme configuration file (`theme.yml`).

Something even more ambitious would be to give the same support to any config file, such as extensions and even routes and taxonomies (in the latter two cases I do not see any need).

**Comment by GawainLynch** [comment]
For v3 this is probably out of scope due to how the loading and config works currently. :disappointed: 

However, we're heavily underway with v4 work now and that is using Symfony 4 + Flex which brings us DotEnv so all of the above is *very* possible :smile:

**Comment by bobdenotter** [comment]
@romulo1984 It's not as nice, but you can access `config.yml` values in your theme: `{{ config.get('general/foo') }}` returns `foo: …` from it.
