### ISSUE TITLE
Installing 3.4 from Composer create-project fails

### ISSUE THREAD

**Issue by DamienChauvet** [bolt/bolt#7178]
PHP Fatal error:  Call to undefined function Bolt\Collection\is_iterable() in .../vendor/bolt/collection/src/Arr.php on line 67

Details
-------

 - Relevant Bolt Version: 3.4
 - Install type: Composer create-project
 - Composer: version 1.5.1
 - PHP version: 5.6.30
 - Used web server: Apache/2.4.27

Reproduction
------------

From terminal, on OSX 10.12
```composer create-project bolt/composer-install:^3.4 bolt-3-4 --prefer-dist```

### Bug summary

``
[...]
Would you like to enable the default site Bundle? (yes/no) [yes]: yes``
``PHP Fatal error:  Call to undefined function Bolt\Collection\is_iterable() in /Users/Dam/Sites/bolt-3-4/vendor/bolt/collection/src/Arr.php on line 67``

**Comment by GawainLynch** [comment]
See https://github.com/bolt/collection/issues/32 & https://github.com/bolt/collection/issues/33

**Comment by GawainLynch** [comment]
We'll tag a new release today. Thanks for the report! :+1:
