### ISSUE TITLE
Creating a bolt project using composer php classes

### ISSUE THREAD

**Issue by Stephen627** [bolt/bolt#7188]
I wanted to create a Bolt project using a PHP script but using exec / shell_exec was not working so I decided to require composer and use the code directly but this is causing issues in Bolts \Bolt\Composer\ScriptHandler class.

Details
-------

 - Relevant Bolt Version:  3.4
 - Install type:  Composer install
 - PHP version: 7.1
 - Used web server: Apache 2.4
 - For UX/UI issues: Firefox 57

Reproduction
------------
I am using the following code to attempt to create the project. This should get through to running the Bolt  `\Bolt\Composer\ScriptHandler::installAssets` and fail on line 34

```
use Composer\Command\CreateProjectCommand;
use Composer\IO\NullIO;
use Composer\Config as ComposerConfig;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputDefinition;
       
putenv('HOME=' . $projectDir . '../');
ComposerConfig::$defaultConfig['home'] = $projectDir . '../';
        
$io = new NullIO();
$config = new ComposerConfig();
$inputDefinition = new InputDefinition([
    new InputOption('prefer-source'),
    new InputOption('prefer-dist')
]);
$input = new ArrayInput([], $inputDefinition);
        
$input->setOption('prefer-source', false);
$input->setOption('prefer-dist', true);
        
$createCommand = new CreateProjectCommand();
$createCommand->installProject($io, $config, $input, 'bolt/composer-install', "{$projectDir}{$project}", '3.4');
```
Where $projectDir the directory to install the new Bolt project.

### Bug summary

The Bolt \Bolt\Composer\ScriptHandler function trys to use $argv to determine if the script was called using the 'composer create-project' command but in my case it was not. There is a comment on lines 30-32 of the \Bolt\Composer\ScriptHandler class saying the following:

```
/**
 *Ugly hack to prevent application from being booted before configureProject can be called.
*/
```

### Specifics

I am assuming that composer is grabbing the latest version of Bolt which at the time of writing this was 3.4.1. Here is the full error that I get when trying to create the project:

```
implode(): Invalid arguments passed (2)

#0 [internal function]: flight\Engine->handleError(2, 'implode(): Inva...', 'installDirectory', 34, Array)
#1 /home/sites/web6/web/bolt_test/vendor/bolt/bolt/src/Composer/ScriptHandler.php(34): implode(' ', NULL)
#2 /home/sites/web6/project-maker/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Bolt\Composer\ScriptHandler::installAssets(Object(Composer\Script\Event))
#3 /home/sites/web6/project-maker/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Bolt\\Composer\\S...', 'installAssets', Object(Composer\Script\Event))
#4 /home/sites/web6/project-maker/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 /home/sites/web6/project-maker/vendor/composer/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
#6 /home/sites/web6/project-maker/vendor/composer/composer/src/Composer/Command/CreateProjectCommand.php(188): Composer\Installer->run()
#7 /home/sites/web6/project-maker/src/Bolt/Manager.php(97): Composer\Command\CreateProjectCommand->installProject(Object(Composer\IO\NullIO), Object(Composer\Config), Object(Symfony\Component\Console\Input\ArrayInput), 'bolt/composer-i...', 'installDirectory', '3.4')
#8 /home/sites/web6/project-maker/src/Bolt/Manager.php(41): Bolt\Manager::runBoltCreate('bolt_test', 'password')
#9 /home/sites/web6/project-maker/src/App/Model.php(95): Bolt\Manager::create(Array)
#10 /home/sites/web6/project-maker/index.php(161): App\Model->createProject('Bolt', Array)
#11 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(165): {closure}()
#12 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#13 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/Engine.php(323): flight\core\Dispatcher::execute(Object(Closure), Array)
#14 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start()
#15 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#16 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#17 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('start', Array)
#18 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array)
#19 /home/sites/web6/project-maker/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#20 /home/sites/web6/project-maker/index.php(171): Flight::__callStatic('start', Array)
#21 {main}
```
As you can see it is trying to implode using NULL instead of an array. The variable is $argv which is understandably not set. 

### Expected result

Creates a Bolt project

### Actual result

It does not create the Bolt project

**Comment by bobdenotter** [comment]
Hi, 

What's the use case of doing it like this? We commonly recommend use the method described here:

https://docs.bolt.cm/3.4/installation/composer-create-project/creating-a-new-project#interactive-install
 
```
composer create-project bolt/composer-install:^3.4 <MYPROJECT> --prefer-dist
```

Why not simply use that?

**Comment by Stephen627** [comment]
Hello,

We want to do other things than just create the project. For example, creating the database and changing the config to have the database details. Also our designers tend to be the ones that create the projects and it is easier for them to interact with a browser and have a project ready than for them to run commands.

**Comment by bobdenotter** [comment]
Regardless, running `create-project` "just works". Why not do that, and _then_ do all the other things you need to do? 

Please read this: https://docs.bolt.cm/3.4/installation/composer-create-project/creating-a-new-project#automated-install

**Comment by GawainLynch** [comment]
Thanks for a really detailed report @Stephen627 … it is always helpful to have a good explanation of the experience.

The problem you are running into here is the approach. What is referred to as an ugly hack is the use of globals … They're just flat out bad.

While your approach isn't and won't be supported, you should be able to work around it by adding this to the beginning of your script:
```php
global $argv;
$argv = ['create-project'];
```

**Comment by Stephen627** [comment]
Thank you @GawainLynch that works. I can't believe I didn't think of doing it.
