### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by NuclearDog** [bolt/bolt#7192]
I've tried every which way, but can't get Bolt functional at all on Windows.

 

Details
-------

 - Relevant Bolt Version: 3.4.1
 - Install type: Zip, Tarball, Composer
 - PHP version: 7.0.9
 - Used web server: -
 - For UX/UI issues: -

Reproduction
------------

### Bug summary

Looks like public/index.php, app/nut, and other files are all symlinks and aren't really working on Windows. It would be nice if there was some solution to this. Or at the very least, a warning is added to the manual that Bolt does not work on Windows (or specifically what installation methods will work) to avoid people spending time on these dead ends.

### Steps to reproduce

On Windows 10:

1. Download bolt-latest.zip
2. Extract bolt-latest.zip with Explorer, 7zip, or another tool
3. Try and run app/nut or access public/index.php

Or:
1. Run `curl -O https://bolt.cm/distribution/bolt-latest.tar.gz; tar -xzf bolt-latest.tar.gz --strip-components=1` in bash.
2. Try and run app/nut or access public/index.php

Or:
1. Run `composer create-project bolt/composer-install:^3.4 mynewproject --prefer-dist`
2. Try and run app/nut

Or:
1. Install via any method above
2. Run `vendor/bolt/bolt/app/nut init`.
3. nut reports, as per the documentation, success.
4. `public/index.php` is missing, Bolt doesn't function.

### Expected result

Bolt should be accessible via web server serving from public/. Bolt should be accessible from app/nut on the command line.

Alternatively, if this is an unsupported configuration that should be stated somewhere.

### Actual result

Files necessary for Bolt to function are not in the correct places.
Via some methods app/nut is created, but simply contains the string '../vendor/bin/nut'.

**Comment by bobdenotter** [comment]
Hi @NuclearDog , 

> Looks like public/index.php, app/nut, and other files are all symlinks and aren't really working on Windows. 

We know that's an issue. Symlinks just aren't supported very well under windows, but as you mentioned, you can use ``vendor/bolt/bolt/app/nut` instead, or choose not to use nut at all, as it is an optional component. 

> a warning is added to the manual that Bolt does not work on Windows

It does work work on windows. 

> Try and run app/nut or access public/index.php

Why doesn't this work? What error messages are you getting?

**Comment by adriano-ghezzi** [comment]
problem persists I can't see any warning on documentation about windows
in addition to above issues in windows there is not  any *.yml in  config dir

**Comment by fredpo** [comment]
At the very least there should be documentation that you can't run app/nut on windows because it uses symlinks and that you have to use the full path: `vendor/bolt/bolt/app/nut` on windows

**Comment by fadoe** [comment]
Some projects create a .bat-file for windows users in vendor/bin. This file runs commands the windows way.

**Comment by joluga** [comment]
I just discovered Bolt, I was following the instructions to install via command line and had the same problem, some of the files inside the tar file can't be extracted, not even with winrar, or using Power Shell or command line in admin mode.

**Comment by joluga** [comment]
Weird. It installed ok using Windows Subsystem for Linux but throw me an error after running the "php app/nut init" coomand:
 [RuntimeException]
  Extension DOM is required.

init [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>

Then I run the same command in the same folder but with the windows command line and it returned:
 Welcome to Bolt! - version 3.6.2.

Hope this info helps you find a way to make Bolt work in Windows.

**Comment by bobdenotter** [comment]
@joluga That last one is not a Bolt error, but it’s PHP saying the DOM extension is not present. Make sure you configure PHP so that it has this extension.
