### ISSUE TITLE
Admin panel content type filters don't  work anymore. 

### ISSUE THREAD

**Issue by enkhtamir** [bolt/bolt#7195]
![untitled-1](https://user-images.githubusercontent.com/3343989/33109934-90210c5e-cf12-11e7-9b90-3df3aadd5d1f.jpg)

Admin panel content type filters don't work anymore.

**Comment by GawainLynch** [comment]
Which version are you running, @enkhtamir ? :wink:

**Comment by enkhtamir** [comment]
3.4.1

**Comment by rossriley** [comment]
Confirmed here, I'll work on a fix
