### ISSUE TITLE
[RFC] Improved file upload sanitizer

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7198]
### problem 
when you upload a file with non-alphanumeric name, bolt is currently sanitizing it, [according to config](https://github.com/bolt/bolt/blob/3.x/src/Provider/UploadServiceProvider.php#L30).
So, for example, cyrillic filename "новый-файл 1.jpg" becomes some kind of `_____-_____1.jpg`. Imagine the problem with collisions, on massive file upload.

### solution 
For my purposes i created sanitizer provider: [improved sanitizer gist](https://gist.github.com/Boorj/e602f95faf139a09f14cc8a802532993), which carefully converts `'ě' → 'e'`, and after that applies replacement pattern.
The code is lightweight, so it won't heavily affect performance.

### profit
This will impact all languages with upper and lower accents, and also Cyrillic symbols. People will get less mess in their folders. 

### rfc
Maybe it should be implemented in core, 'out of the box'?

**Comment by bobdenotter** [comment]
Closing, because this is fixed in #7198. Thanks, @Boorj and @GawainLynch 👍

**Comment by Boorj** [comment]
@bobdenotter @GawainLynch Problem came back again!
