### ISSUE TITLE
SVG Image Upload

### ISSUE THREAD

**Issue by danielgamage** [bolt/bolt#720]
When uploading an SVG file through the image field type, Bolt throws a "Oops! There was an error uploading the image. Make sure the image file is not corrupt, and that the 'files/'-folder is writable." error.

I have been able to upload files of type JPG before this.

Not sure how cropping and resizing should be handled here, though I'd expect Bolt to handle getting the image into the filesystem. Perhaps cropping and resizing should be done by just modifying the viewbox and w/h attributes.

**Comment by misteryyy** [comment]
Hello, Is there any update to this?

**Comment by bobdenotter** [comment]
@misteryyy This was fixed in https://github.com/bolt/thumbs/issues/38 , back in 2017.

**Comment by misteryyy** [comment]
> @misteryyy This was fixed in [bolt/thumbs#38](https://github.com/bolt/thumbs/pull/38) , back in 2017.

Aha. I just trying upload SVG for imagelist and seems there is no support for it :(
