### ISSUE TITLE
Session data didn't match

### ISSUE THREAD

**Issue by skiweather** [bolt/bolt#7207]
I get logged out automatically after 7 minutes:
Automatically logged out user 'skiweather': Session data didn't match.

 

Bolt version 3.5 flat structure, php 5.5. apache
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 | 3.4 | 3.5 | master ]
 - Install type: [ Zip/tarball install | Composer install | GitHub checkout ]
 - PHP version: [ 5.5 | 5.6 | 7.0 | 7.1 | 7.2 ]
 - Used web server: [ Apache | Nginx ] version [ version ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by bobdenotter** [comment]
Hi, @skiweather 

> Bolt version 3.5 flat structure

I Don't think that's correct. 🤔 

Anyways, what probably happens is that sessions are not stored / kept correctly on your server. The first step would be to look into that.
