### ISSUE TITLE
[bug] current session username is not displayed

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#7213]
The display for current session does not show the username - an empty column is displayed instead

![screenshot from 2017-11-27 15-14-43](https://user-images.githubusercontent.com/1488214/33271061-737a5de4-d386-11e7-83eb-f2a42ff0255e.png)

Details
-------
 - Relevant Bolt Version: 3.4.2
 - Install type: Zip/tarball install
 - PHP version:  Apache/2.2.22 - php 5.6 | nginx/1.10.3 - php 7.0.19 
 - Used web server: Apache and Nginx 
 - For UX/UI issues: any

Reproduction
------------
I installed bolt 3.4 beta and updated it to 3.4.1
The logged in sessions are displayed, but usernames are not visible. It occurs in the back-end on the url http://example.com/bolt/users

This is not solved after upgrading to 3.4.2

**Comment by GawainLynch** [comment]
For whoever is looking that this, it is now using `user_id` column and not `username` in the authtoken table
