### ISSUE TITLE
Error installing bolt 3.4.2

### ISSUE THREAD

**Issue by jameswill** [bolt/bolt#7231]
I have downloaded zip package from https://bolt.cm/distribution/bolt-latest.zip and have moved all the directories (except /public) to one level up from web accessible directory and public directory to web accessible directory and then was trying to install bolt by visiting http://domain.com/bolt342/index.php and getting following attached error. 

Details
-------

 - Relevant Bolt Version: 3.4.2
 - Install type: [ Zip install ]
 - PHP version: [ 5.5 ]
 - Used web server: [ Apache ] version [ 2.2 ]

Reproduction
------------
1) Extracted public directory to web accessible directory(say subdir) and all other to non web accessible directory (say "datadir").
2) Created .bolt.yml in root of [[datadir]] and filled with paths: web: {path}/{to}/{subdir}
3) Created config.yml in [[datadir]]/app/config and filled with mysql database details.
4) Edited index.php of [[subdir]] to $app = require '[[datadir]]/vendor/bolt/bolt/app/web.php';

After setting all these paths I visited {URL}/{to}/{subdir]/index.php where I am getting following attached warning on create user page

![bolt](https://user-images.githubusercontent.com/6368036/33547881-7e31cddc-d90b-11e7-830d-b886f4ca3738.png)

However post filling user details I am able to complete the installation successfully. Even it is working properly post login.

Also this is happening only when I try to install through zip package. This is not giving any error if I install it with composer. 

Can you please suggest what must we missing on ? or is this warnings are negligible as my installation is working properly?

**Comment by GawainLynch** [comment]
Hey @jameswill :wave: 

If you're flattening the directory structure it is much easier if you download the "Flat structure" zip as that has the required changes.

**Comment by jameswill** [comment]
Hi,

Thank you for the reply.

I am getting same error on flat stucture zip also.
