### ISSUE TITLE
[RFC] Allow non-themed site structure

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7236]
Now bolt is built like for simple usage like as a blogging platform. You have contentypes, some workaround with static pages. Since 3.3 - singletons.

It gives me some problems, that i have to solve with workarounds. 

**My goal is to store all custom data in one place, not to mix it with original bolt distributed files**

- **custom config folder** (partially solved)
Now (since .bolt.yml) we have ability to set custom location for `config` folder. But, anyway, it looks pretty illegal to use not `/app/config`. In documentation it's always used this way, not `config://menu.yml` or whatever.
Also, if i don't want to store contenttype i18n files in original location, i do have to extend bolt with some workarounds.  `$translator->addResource('yaml', $filename, ...)`

- I'm using bolt as a backend for my sites with custom design and controllers, not as simple blogging platform. I don't use "template" setting for each contenttype (listing.twig / record.twig in theme).  Actions in controllers execute some logic, before page is being rendered. So my routing is custom.
Problem: when i have custom path, like `about : {path : "/about", defaults: {...}, ... }`, this route (called "about") is overridden by bolt original route. Just because in core there's a hardcoded part like `$app->match()->...->bind('about')`

- **unused routes.** 
I don't need `/{contenttype}/{slug}` route. But in bolt instructions i'm being asked to leave original bolt's routes untouched. That gives collisions. When i have my custom path, like "/works"with custom controller and a contenttype `Work`, i have a collision. Because bolt's original route `/{contenttype}/{slug}` is left untouched

- **tricks and magic with custom path for templates**.
I **can't** easily redefine templates folder, only setup theme folder. 
But i don't use theme folder  (`root/theme/mytheme/js`),  I store my assets (css, js) in `root/web/js|css` (or `root/public/js|css`) already, i don't need theme folder at all.
I store all my _uncompiled sources_ (.jsx, .es, .less, .styl, .scss etc)  in  `/src/...` . _Templates_ - in another folder '/resources' .  So **if** my templates folder is `/resources/views`, **then** i have to lie to bolt and define in `.bolt.yml` : `themes : resources`. After that, i can use twigs folder in my custom controller. 
**But what if i don't want to use themes at all?**

Theme conception tells: you have js, css, views in one parent folder. And if i have templates in one place, js in another and css in the 3rd? I just only want bolt to know that assets are ok in by web folder. And render pages, using my templates. Symfony has separate approaches : `css|js|fonts` - are used for assets processing (or untoched at all). And template files (`twig|jade|haml|...`) are used by controllers. So no theme conception, feel free to do whatever you need.

I know the ways, which I am successfully applying in my projects: custom routing, `CustomizeExtension.php`, tweaking theme folder in `.bolt.yml` settings. 

If it's enough for me to use that simple hack with `themes: resources` , so why can't it be simply done in "legal" way?
If Bolt is now upgraded to the next major release, can't it be more friendly for such way of using?

For a start it could be satisfied by:
- use 100% decoupled folders configuration. Including i18n folder customization. And `bolt/docs` too.
- ability to setup "non-theme" usage, so bolt doesn't rely on theme at all. Only backend theme.
- separate bolt required routes and user routing. If bolt needs a route to be defined, let it be defined in inner files, not edited by user.
- Don't use unprefixed route names for inner usage, so any user defined route name in custom `routing.yml` will be applied.

**Comment by bobdenotter** [comment]
Hey @Boorj,

With Bolt we have this principle, where we not add a feature or make a change for the benefit of one usecase, it it means it detracts from the experience for other users/usecases. 

For example, if someone has a feature request to save them one click, but it means other people will have to make an extra click, it will not be accepted. 

The same applies to most of your feature requests. You have a very specific, unique workflow, that works for you. All of these proposed changes will make bolt _easier_ for you, but _harder_ for 99% of all bolt users. As such, they are a "no go". In specific: 

> use 100% decoupled folders configuration. Including i18n folder customization. 

It's pretty much. For so far it isn't, we're going with "sensible settings", according to us. 

> And bolt/docs too.

so far as it doesn't confuse the reader.

> ability to setup "non-theme" usage, so bolt doesn't rely on theme at all. Only backend theme.

I just don't see the point. If you don't want to have a theme, don't use it. 

> separate bolt required routes and user routing. If bolt needs a route to be defined, let it be defined in inner files, not edited by user.

Perhaps coming in bolt 4, using CMFRouter. For now, if you don't need a baked in route, just make it "not match" and ignore it: 

```
contentlink:
    path: /__not_used__/{contenttypeslug}/{slug}
    defaults:
        _controller: controller.frontend:record
    requirements:
        contenttypeslug: controller.requirement:anyContentType
```

> Don't use unprefixed route names for inner usage, so any user defined route name in custom routing.yml will be applied.

Prefix yours with `klaus_` if you want to name them the same.

This is a prime example of where we shouldn't make a changeto benefit a single case, and make it more complex for 99% of the other users.

**Comment by Boorj** [comment]
@bobdenotter thanks for the answer.

### Single case?
> benefit a single case, and make it more complex for 99% of the other users
1. I hope you don't forget, that if i'm the 1%, there's a probability, that many people just keep silence (don't post issues) and don't use bolt for same purposes as mine. 
2. My way is not a big deal, it doesn't take too much changes, it doesn't break typical behaviour.

My point is: 
- to make bolt more consistent (see below)
- to not ruin the way how it's used now for (as you say) _99% of users_ .
- make it more comfortable to use as a nice platform for websites with custom controllers and directory structure. For example, when a person wants to keep all custom files in `root/project`: config, controllers, templates, assets, translations. And when he migrates, or clones his project - he's assure that he doesn't need *to change here, to change here, then go to bolt vendor and change here, and then change here*.

My suggestions are leaving traditional workflows **untouched**. And also allows bolt to be more flexible, and used for more purposes (**profit**)

### Custom translations path
> It's pretty much

Speaking about translations. Why can't we add `translations: ...` path in `.bolt.yml` and if it's set, just run the code that i usually do to provide custom location. 
**Profit:** 
That will allow users to store their custom settings anywhere they want, without dancing with :man_dancing: tambourine. 
That will also affect all that contenttypes i18n qustions ( #6795, and all that questions being held [here](https://github.com/bolt/bolt/pull/6802)) 

### Mention custom paths in documentation
> so far as it doesn't confuse the reader.

- It's more consistent, if you choose the way how you setup your system, and follow that rule in documentation.
If you change
  - `app/config/menu.yml` to 
  - `{yourConfigPath}/menu.yml` OR
  - `config://menu.yml (usually it's 'app/config/menu.yml)` you'll show a user all the flexibility. Or at least you can mention that config is not predefined, it could be changed.

- For example, SF4 has [separate folder](http://fabien.potencier.org/symfony4-directory-structure-updates.html) for config. So, perhaps, my 1% could be more than just single case, it could be a common approach. 

That's why i'm asking to bear in mind in documentation, that you're use _custom_ directory structure, so it should me mentioned in docs.
**Profit:**
Bolt will become more consistent. Also it will be easier to understand for users.

### Prefix for routes, used for backend
> Prefix yours with `klaus_`

I can do that, but is it a proper thing? I doubt. I asked some guys in industry (to be more impersonal): "is it a normal approach?" - everybody told "of course, not. Inner used names should be changed, and they don't have side effects in user setup".
If bolt needs a route, and it's widely used in backend theme - then bolt should prefix, not a user. Used doesn't have to know about bolt's kitchen. 
**Profit:**
It will make bolt less dependent, more flexible. Minus one constraint/prohibition.

### No breaking changes
>but harder for 99% of all bolt users

I'm not sure, because i see no suggestions, changing traditional workflow.

Resuming
---

In general, few **safe** tweaks which don't affect any former pipelines can spread bolt's usage for more cases, not only theme+blog or whatever.

**Comment by GawainLynch** [comment]
I would say that you've missed a couple of important things mate, firstly that "blogs" are not even close to what Bolt is used for out there … we know, we deal with the implementors every day … nor is it "small" in terms of its reach and use :wink: 

We can and are improving … but being "everything to everyone" is the fastest way to Project Oblivion.

**Comment by panda-madness** [comment]
> We can and are improving … but being "everything to everyone" is the fastest way to Project Oblivion.
AKA Wordpress.

**Comment by Boorj** [comment]
I agree 100% ! I'm using bolt **not** as a blog platform, it's being used for huge variety of things. Also estimating number of extensions ( @GawainLynch you've got a huge amount of ones written) - of course it's a coolest backend i ever tried.

And i'm **not** suggesting to be "Everything to everyone". That's exaggeration.
I'm just asking if we can polish come sharp corners. A little work can give good profit (see above). Flexibility, consistency, easier understanding for users.
