### ISSUE TITLE
[BUG][3.4] HTML field's data inside a repeater field is not getting duplicated

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7241]
Details
-------

 - Relevant Bolt Version: 3.4 and up (it worked in 3.3)
 - Browser: Chrome

Reproduction
------------

### Bug summary

In repeater field when I have HTML field and click 'duplicate' then this field's data is not being copied.

### Specifics

You can check it in http://bolt-au46k8.bolt.dockerfly.com/bolt/editcontent/showcases/9#repeater

### Steps to reproduce

1. fill HTML field in repeater with some text
2. click duplicate

### Expected result

Field's data is getting copied.

### Actual result

Duplicated repeater has empty HTML field.

**Comment by GawainLynch** [comment]
Confirmed. It seems to be the CK event derping, as a saved HTML field will duplicate.
