### ISSUE TITLE
[BUG][3.4]filtering content type in overview page utf-8 problem

### ISSUE THREAD

**Issue by denis-gorin** [bolt/bolt#7246]
Details
-------

 - Relevant Bolt Version: [ 3.4 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0  ]
 - Used web server: [ Apache | Nginx ] version [ Apache/2.2.22 | nginx/1.11.10]

Reproduction
------------

### Bug summary

Trying to filtering contenttype in backend on  overview page cause problem when use utf-8 symbols such as `üöäß` or  `абырвалг`

### Specifics

there is an error

```
Uncaught Exception: QueryParseException.

QueryParseException in QueryParameterParser.php line 276: 
No matching value found for "%üöäß%"
```

### Steps to reproduce

- go to overview listing of contenttype in a backend
- type a search string (utf-8 chars,ex. üöäß) in a filter field
- press filter button

### Expected result

may be  to use **/u**  modifier for regexp pattern in `QueryParameterParser.php` `parseValue `method

**Comment by bobdenotter** [comment]
Hi, @denis-gorin.

I couldn't help but notice that you've deleted the [issue template](https://github.com/bolt/bolt/blob/3.4/.github/ISSUE_TEMPLATE.md) when opening the issue. Please provide the missing info.

**Comment by denis-gorin** [comment]
updated

**Comment by bobdenotter** [comment]
Which 3.4 is this? We fixed an issue in this recently, but for me it's working in 3.4.3.. See screenshot: 

![firefox](https://user-images.githubusercontent.com/1833361/33835100-b338c010-de85-11e7-8697-41213e19cfd6.png)

**Comment by denis-gorin** [comment]
same 3.4.3
strange case, here is ok, 

![image](https://user-images.githubusercontent.com/3963911/33848596-d087b2ba-dee0-11e7-9f7a-acd7759729d0.png)

but

![image](https://user-images.githubusercontent.com/3963911/33848650-f648f2d4-dee0-11e7-9684-470497abb80f.png)

so, you can close this issue I have workaround

**Comment by Raxta** [comment]
For me help this changes in vendor/bolt/bolt/src/Storage/Query/QueryParameterParser.php in function setupDefaults:
`$this->addValueMatcher('<([\p{L}\p{N}_]+)',            ['value' => '$1', 'operator' => 'lt']);
        $this->addValueMatcher('<=([\p{L}\p{N}_]+)',           ['value' => '$1', 'operator' => 'lte']);
        $this->addValueMatcher('>=([\p{L}\p{N}_]+)',           ['value' => '$1', 'operator' => 'gte']);
        $this->addValueMatcher('>([\p{L}\p{N}_]+)',            ['value' => '$1', 'operator' => 'gt']);
        $this->addValueMatcher('!$',                ['value' => '',   'operator' => 'isNotNull']);
        $this->addValueMatcher('!([\p{L}\p{N}_]+)',            ['value' => '$1', 'operator' => 'neq']);
        $this->addValueMatcher('!\[([\p{L}\p{N}_ ,]+)\]',    ['value' => function ($val) { return explode(',', $val); }, 'operator' => 'notIn']);
        $this->addValueMatcher('\[([\p{L}\p{N}_ ,]+)\]',     ['value' => function ($val) { return explode(',', $val); }, 'operator' => 'in']);
        $this->addValueMatcher('(%[\p{L}\p{N}_]+|[\p{L}\p{N}_]+%|%[\p{L}\p{N}_]+%)', ['value' => '$1', 'operator' => 'like']);
        $this->addValueMatcher('(\[\p{L}\p{N}_]+)',             ['value' => '$1', 'operator' => 'eq']);`

and in function parseValue change:
`$regex = sprintf('/%s/u', $matcher['token']);`

Because in preg_match '\w' not work for UTF-8 characters with or without '/u' key. Solution is change '\w' to '[\p{L}\p{N}_]'. Maybe in new version of PCRE it's fixed

**Comment by bobdenotter** [comment]
@rossriley Can you take a look to see it this is a sensible change to make, without having it break for other usecases?
