### ISSUE TITLE
Extension without ReadMe, gives json error on 'readme' button

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#7247]
On the extension page:
When clicking the 'View Readme' button on an extension that does not have a `ReadMe`, it gives a json error:

```
An unknown error occurred. This was the error message:
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Could this be changed into a friendly error, such as 'No ReadMe available' ? Or even better, hide the ReadMe button?

(And yes, I will ping / make a pull request for the developer of the extension to include a ReadMe, but there should be a good empty-state)

Thx!
Okbye!

Details
-------

 - Relevant Bolt Version: 3.4

**Comment by bobdenotter** [comment]
"Hiding the button" is really tricky, but i _have_ improved the message shown in PR #7267.

Closing this for now. Feel free to re-open, if it needs more tweaking.
