### ISSUE TITLE
Contenttype with "grouping" and sortorder doesn't use it in the backend.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7251]
In bolt 3.4, the backend listing doesn't properly use the sortorder. 

To reproduce, just use the default ContentType for Pages, and mash the 'prefill database' button a few times. You can see the bug in the listing overview: 

![screen_shot_2017-12-12_at_15_35_20](https://user-images.githubusercontent.com/1833361/33890099-843813ce-df52-11e7-9128-bb0025b7e131.png)

@rossriley, this is another one for you, i'm afraid.

**Comment by rossriley** [comment]
Yes I remember I didn't take account of sortorder when I fixed this last time. On it now.
