### ISSUE TITLE
YML files in nginx config

### ISSUE THREAD

**Issue by inadsan** [bolt/bolt#7270]
In the recommended configuration of Bolt CMS with nginx in the restrictions.conf file it adds deny for yml files but from the admin when accessing /adm/file/edit/config/menu.yml it gives an error 403

Details
-------

 - Relevant Bolt Version: 3.4
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx 1.10.3

**Comment by GawainLynch** [comment]
This is a question about documentation, so generally better off in https://github.com/bolt/docs

That aside, if you change the `/bolt` base URL to something else you need to adjust the Nginx rules as mentioned in the docs https://docs.bolt.cm/3.4/installation/webserver/nginx#bolt-conf

> # NOTE: If you set a custom branding path, change '/bolt' & '/bolt/' to match
