### ISSUE TITLE
Periodically logged out even with all security settings false

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#7280]
Bolt is by default pretty strict on maintaining sessions, but can be configured through the `cookies_use_*` settings. On websites that I've published recently

 

Details
-------

 - Relevant Bolt Version: 3.4.5
 - Install type: Composer install
 - PHP version: 7.x
 - Used web server: Apache

Reproduction
------------

### Bug summary

I cannot stay logged into the Bolt admin panel for a reasonable length of time (~3 hours). This happens consistently.

I've been hosting recently on Heroku (with settings to accommodate for proxies and caching of sessions) but have observed this on shared hosting as well.

### Steps to reproduce

Not 100% sure how to reproduce but this works for me:

Go into an environment where your IP changes semi-regularly (my IPv6 address at home seems to change every few hours). Log into Bolt dashboard with `cookies_use_remoteaddr` set to false. Wait some time and notice you are logged out. Clear your PHP sessions (leaving database entries in tact) for a faster effect.

### Expected result

That I remain logged in for the duration of the cookie

### Actual result

I do not remain logged in (I see "You have been logged out" on the Bolt login page)

I suspect this is because the [code for authentication](https://github.com/bolt/bolt/blob/3.5/src/AccessControl/AccessChecker.php#L213-L215) uses the IP address when it does a lookup for the auth token in the database regardless of the setting of `cookies_use_remoteaddr`.

```
if (!$authTokenEntity = $this->getRepositoryAuthtoken()->getToken($authCookie, $this->getClientIp(), $userAgent)) {
    return false;
}
```

If the IP address for a user changes, and the cache has dropped the saved result, this query will have no results and they will be subsequently logged out

NB: I am allowing all proxies with a `0.0.0.0/0` entry in my trusted proxies setting.

**Comment by GwendolenLynch** [comment]
I think either of #7333 and #7356 should cover this, and the bot has flagged it, so I might beat it too the task.

S.O.P. Justs re-open if needed :+1:

**Comment by Senne** [comment]
@Pinpickle Did #7333 or #7356 fix the issue in your case?
