### ISSUE TITLE
FRequest : Add option meta to taxonomies

### ISSUE THREAD

**Issue by Mikescops** [bolt/bolt#7281]
I suggest adding optional meta options to taxonomies.
It could be useful in case you want to associate a color to a category or a visibility option...

Here is how Xiao and I imagined how it could look like in the taxonomy.yml : 

```categories:
    name: categories
        options:
            foo: Foo
            bar: Bar
        options_meta:
            foo:
                attribute: value
                color: #ff0000 / rgba(1,2,3,4)```

**Comment by SvanteRichter** [comment]
Closing cause the above comment.
