### ISSUE TITLE
Line breaks in info:  text

### ISSUE THREAD

**Issue by cathgillespie** [bolt/bolt#7284]
I think it would be useful to be able to insert linebreaks in the info: text for fields.

 

Details
-------

 - Relevant Bolt Version:  3.4
 - Install type:  Zip
 - PHP version:  5.5.15
 - Used web server:  Apache

Reproduction
------------

I tried the following in contenttypes.yml:

```
info: |
    If you want to link to a page listed under "Pages" in the dashboard (for example, the bio page) enter page/bio.

    If the page is listed separately on the dashboard (for example, Events), simply enter events.
    
    Always use lower case
```

In view source, the text is broken as above, but in the dashboard there are no linebreaks when hovering over the info icon.

**Comment by xiaohutai** [comment]
Hm, Bootstrap popovers do have the `html` option set, but the `info` text field is already escaped. So that doesn't work.

In your case, you could make use of `postfix` instead, this field allows for any HTML. But it's not behind an info icon.
