### ISSUE TITLE
Weirdness with "flat distribution" 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7289]
Following instructions from here: 

https://docs.bolt.cm/3.4/howto/troubleshooting-outside-webroot#option-2-use-the-flat-structure-distribution

executing the first two commands: 

```
curl -O https://bolt.cm/distribution/bolt-latest-flat-structure.tar.gz
tar -xzf bolt-latest-flat-structure.tar.gz --strip-components=1
```

Gives us this: 

```
$ tree -L 1 -a
.
├── .bolt.yml.dist
├── .gitignore
├── .htaccess
├── README.md
├── app
├── bolt-latest-flat-structure.tar.gz
├── bolt-public
├── composer.json.dist
├── composer.lock.dist
├── extensions
├── files
├── index.php
├── src
├── theme
├── thumbs
├── var
└── vendor
```

I then run `php app/nut init`, and it shows me the correct "Welcome to Bolt! - version 3.4.6."

It runs, and there is now an extra folder `public/`: 

```
$ tree -L 1 -a
.
├── .bolt.yml
├── .gitignore
├── .htaccess
├── README.md
├── app
├── bolt-latest-flat-structure.tar.gz
├── bolt-public
├── composer.json
├── composer.lock
├── extensions
├── files
├── index.php
├── public .    <--- this one.
├── src
├── theme
├── thumbs
├── var
└── vendor
```

Now, i push on, by running `php app/nut server:run`. opening it in my browser, correctly redirects to "userfirst".

![screen shot 2018-01-08 at 16 01 09](https://user-images.githubusercontent.com/1833361/34676466-343a5d50-f48d-11e7-9b15-cc6e763fd962.png)

However, if I instead use a 'real' webserver to point to this folder, it breaks: 

![screen_shot_2018-01-08_at_16_02_37](https://user-images.githubusercontent.com/1833361/34676641-cd32779a-f48d-11e7-8745-10144d12a513.png)

![screen_shot_2018-01-08_at_16_03_20](https://user-images.githubusercontent.com/1833361/34676727-1b283cc8-f48e-11e7-9195-e482d47b7049.png)

I started looking into this, because Willem was stuck on this thing, but with yet another error: 

![screen_shot_2018-01-08_at_16_11_18](https://user-images.githubusercontent.com/1833361/34676906-b2d2356a-f48e-11e7-8cdd-fe35619845fe.png)

Note that it's trying to create a folder `/public`. So, in the root of the filesystem. Like the "root" path isn't set. Looking into `FilesystemServiceProvider.php`, I add this: 

```
dump($app['path_resolver']->resolve('root'));
```

I notice that the function register is ran twice, and the first `dump` shows me the right path, while the second just gives `/`. 

@GawainLynch My apologies for the huge issue. Let me know if I can provide more/better details.

**Comment by GawainLynch** [comment]
OK, so there are a couple of things happening here.

First is that the `init` command is running on the first install, and there is only a `.bolt.yml.dist` file and not a `.bolt.yml` file (that gets created at this point) but the boot process is trying to set up the environment and minus the `.bolt.yml` file assumes default paths … tries to be "helpful" and create the directories and copies in files … then gets to the stage of doing the "init" where it renames the `.dist` file.

Second part links to first … namely, to boot the application we boot the extensions … which initialises `Bolt\Config` which is still overloaded … and the Nut commands depend on a booted container … which depends on extensions … which initialises `Bolt\Config` … and so on

> I notice that the function register is ran twice, and the first dump shows me the right path, while the second just gives /.

This is the web profiler run

**Comment by bobdenotter** [comment]
Another user in #general bumped into the same issue, with the "regular" install. Turns out it's due to them not (being able to) run(ning) `php app/nut init`. Even when adding a `.bolt.yml` with the paths manually, i can't get it to work just yet.. Will keep digging. :-)

**Comment by GawainLynch** [comment]
Windows?

**Comment by bobdenotter** [comment]
Yes he was on windows. But I can reproduce easily on OSX and linux. See here: http://bob.biz.tm/

**Comment by bobdenotter** [comment]
Ok, there's a certain difference in how the "normal" and the "flat" distro behave.. 

When I do the following, according to instructions [here](https://docs.bolt.cm/3.4/installation/manual-download-and-extraction): 

```
curl -O https://bolt.cm/distribution/bolt-latest.tar.gz
tar -xzf bolt-latest.tar.gz --strip-components=1
mv .bolt.yml.dist .bolt.yml
mv src/Site/CustomisationExtension.php.dist src/Site/CustomisationExtension.php
php app/nut config:set debug_show_loggedoff true
```

I am greeted by the regular "First user" screen. 


However, if i do the same with the "flat" distro: 

```
curl -O https://bolt.cm/distribution/bolt-latest-flat-structure.tar.gz
tar -xzf bolt-latest-flat-structure.tar.gz --strip-components=1
mv .bolt.yml.dist .bolt.yml
mv src/Site/CustomisationExtension.php.dist src/Site/CustomisationExtension.php
php app/nut config:set debug_show_loggedoff true
```

The site's not working. 

Contents of `.bolt.yml` are: 

```
extensions:
    - Bundle\Site\CustomisationExtension
paths:
    web: '.'
```

I've tried modifiying this to something else, but it's not budging. I think there's a bug in how the paths are calculated, still..

When I add `dump($app['path_resolver']->resolve('root'));` in `FilesystemServiceProvider::register()`, I get the following error: 

```
Fatal error: Uncaught InvalidArgumentException: Root path must be absolute. in /Users/bobdenotter/Sites/test/public/vendor/bolt/bolt/src/Configuration/PathResolver.php:64 Stack trace: #0 /Users/bobdenotter/Sites/test/public/vendor/bolt/bolt/src/Configuration/PathResolverFactory.php(100): Bolt\Configuration\PathResolver->__construct('', Array) #1 /Users/bobdenotter/Sites/test/public/vendor/bolt/bolt/src/Provider/PathServiceProvider.php(36): Bolt\Configuration\PathResolverFactory->create() #2 /Users/bobdenotter/Sites/test/public/vendor/pimple/pimple/lib/Pimple.php(126): Bolt\Provider\PathServiceProvider->Bolt\Provider\{closure}(Object(Bolt\Application)) #3 /Users/bobdenotter/Sites/test/public/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Bolt\Application)) #4 /Users/bobdenotter/Sites/test/public/vendor/bolt/bolt/src/Provider/FilesystemServiceProvider.php(22): Pimple->offsetGet('path_resolver') #5 /Users/bobdenotter/Sites/test/public/vendor/silex/silex/src/Silex/Application.php(178): Bolt\Provider\Filesys in /Users/bobdenotter/Sites/test/public/vendor/bolt/bolt/src/Configuration/PathResolver.php on line 64
```

**Comment by GawainLynch** [comment]
> Ok, there's a certain difference in how the "normal" and the "flat" distro behave.

Yes, as explained here and Slack, the "normal" install is running on [defaults from PathResolver](https://github.com/bolt/bolt/blob/3.4/src/Configuration/PathResolver.php#L30-L46), so it "appears" to be working.

The "flat" distro needs to boot the application, and as the dependencies are heavily intertwined, configuration & extensions are (still) booted before we have a chance to modify the `.bolt.yml` file, or in this case, detect changes.

All *very* easy to observe in xdebug.

**Comment by GawainLynch** [comment]
OK, so this is an xdebug breakpoint set on the following condition:
![image](https://user-images.githubusercontent.com/1427081/34700081-44671cdc-f4e1-11e7-8ebf-2fde1d159df2.png)

To illustrate how much still goes on just to get to the point we can try to handle the paths …

1. Early boot of the extensions to allow them to register services
![image](https://user-images.githubusercontent.com/1427081/34699974-b91e4510-f4e0-11e7-9a85-002a504ff2bc.png)

2. Building the exception event listener
![image](https://user-images.githubusercontent.com/1427081/34699988-c72119e4-f4e0-11e7-89ba-176f8e7fb280.png)

3. Subscribing the exception listener to kernel exceptions 
![image](https://user-images.githubusercontent.com/1427081/34700005-dbc7562e-f4e0-11e7-94cd-b0d5e9d89ee1.png)

4. `ConfigurationNoticesListener` checking all registered paths are writable
![image](https://user-images.githubusercontent.com/1427081/34700021-f05582f0-f4e0-11e7-840c-ea306f151b08.png)

5. Installation requirements check
![image](https://user-images.githubusercontent.com/1427081/34700030-fe60f726-f4e0-11e7-829b-51b5c4163264.png)

6. Extensions service provider booting exceptions so they can change Bolt's behaviour
![image](https://user-images.githubusercontent.com/1427081/34700034-09ab2e12-f4e1-11e7-8232-69f5a2713168.png)

7. Our translation service kindly informing the user to set up paths … oh, wait …
![image](https://user-images.githubusercontent.com/1427081/34700052-15f1a282-f4e1-11e7-80bc-02ad7b257722.png)

**Comment by GawainLynch** [comment]
Also worth noting … we've gotten rid of most of what used to be invoking this early, we've come a long way, but the application needs to get itself to a "known state" before it can (re)configure itself … one of the many reasons so many people push back on supporting the archive installs. They're fine enough for a static first install, but providing a single zip to do either/or installs vs upgrades simply by unpacking is just not feasible … you need scripted logic, e.g. Composer :wink:

**Comment by GawainLynch** [comment]
> However, if i do the same with the "flat" distro:
> …
> The site's not working.

Oh, and I just accidentally hit this one too: `mv composer.json.dist composer.json` is also needed :smile_cat:

**Comment by GawainLynch** [comment]
The explanation [for above](https://github.com/bolt/requirements/blob/v1.0.2/src/BoltRequirements.php#L398)

**Comment by bobdenotter** [comment]
Closing this for now. It's a bit of a hassle, but if you [follow instructions](https://docs.bolt.cm/3.4/installation/manual-download-and-extraction) it works well.
