### ISSUE TITLE
Embed url in proxy https setup

### ISSUE THREAD

**Issue by inadsan** [bolt/bolt#7294]
In an instance with a proxy nginx ssl + nginx bolt http when a Video field is included the request "/ async / embed" is done via http and gives an error

Details
-------

 - Relevant Bolt Version: 3.4
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx
 - For UX/UI issues: chrome

Reproduction
------------

In <script src="/bolt-public/js/bolt.js?9c18d858bb" data-config="..."  data-jsdata="...:{&quot;embed&quot;:&quot;http:\/\/dpzmediadev.aranova.es\/async\/embed&quot;},&quot;field&quot;:...."

### Actual result

Mixed Content: The page at 'https://dpzmediadev.aranova.es/adm/editcontent/medias/1#media' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint

**Comment by inadsan** [comment]
Solved with correct canonical.

Thanks

**Comment by GawainLynch** [comment]
Thanks for following up, it's been a busy "real-life" start to the year for the team and we're glad you got it sorted out :+1:
