### ISSUE TITLE
Uncommenting the "oldpages" route example present in the stock routing.yml generates an error

### ISSUE THREAD

**Issue by padawan** [bolt/bolt#7296]
Uncommenting the "oldpages" route example present in the stock routing.yml generates the following error in the web UI:

`File 'routing.yml' could not be saved, because the form wasn't valid.`

Details
-------

 - Relevant Bolt Version: [ 3.4.5 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6.30 ]
 - Used web server: [ Apache/2.4.26 (Unix) ]
 - For UX/UI issues: [ Safari Version 11.0.2 ]

Reproduction
------------

### Bug summary

The following route example is present in the stock routing.yml file:

```
# Example to route old '.html' pages to pages genereated by bolt.

# oldpages:
#     path: /{slug}.html
#     defaults:
#         _controller: controller.frontend:record
#         contenttypeslug: page
#     requirements:
#         slug: [a-z0-9-_]+
```

If you uncomment it, the web UI will refuse to save the form, claiming it is invalid. This is, apparently, because of the last line: `slug: [a-z0-9-_]+` (replacing it with anything valid will get rid of the error, so I suspect it's where to search for the bug).

### Steps to reproduce

1. Go to Configuration > Routing setup
2. Uncomment the "oldpages" route example as is, like so:
```
oldpages:
    path: /{slug}.html
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: page
    requirements:
        slug: [a-z0-9-_]+
```
3. Save the form

### Expected result

The form should save just fine (i.e. the route examples given in the stock distribution should not generate an error :-).

### Actual result

An alert appears saying that `File 'routing.yml' could not be saved, because the form wasn't valid.`

**Comment by GawainLynch** [comment]
Thanks @padawan … Fix in the queue.
