### ISSUE TITLE
Select field: When populating a sortable select field with entries from a ContentType, it is always sorted by id

### ISSUE THREAD

**Issue by freddietilley** [bolt/bolt#7302]
When fetching values from ContentTypes even though the items can be reordered in the frontend, saving the page will store the items sorted by id in the database.

```
        select_entry
            label: Entries
            type: select
            values: entry/title
            autocomplete: true
            multiple: true
            sortable: true
```

Regular values are correctly stored in the order in which they are sorted.

- Confirmed on Bolt version 3.4.5 and 3.4.6
- PHP version 7.1.10
- Confirmed on Firefox, Chrome and Safari

**Comment by rossriley** [comment]
I am almost certain that this issue has been fixed already the PR was #7312 

That made it into the 3.4.7 release, but of there's still an  issue then feel free to reopen.
