### ISSUE TITLE
Integer or float field types have preset default=0 (NOT NULL)

### ISSUE THREAD

**Issue by tomas-zemres** [bolt/bolt#7304]
Integer (or float) field type has preset default=0
even if I do not set "default" in contenttypes.yml

There is also created column "DEFAULT 0 NOT NULL" in database,
but I need store two different cases:
 - NULL (empty field) as unset value
 - 0 (or any other number) as defined value

Related to issue https://github.com/bolt/bolt/issues/3295, but I think it was not solved.

Details
-------
 - Relevant Bolt Version: 3.4
 - Install type: Composer install
 - PHP version: 7.1

**Comment by tomas-zemres** [comment]
I use field "type: text" instead of "type: integer" as workaround,
because field type text can be empty(unset).

(but better would by using field type integer with min/max options)

**Comment by grandgeorg** [comment]
There is also a related issue with select fields.
If we have e.g. a field type select with the values
```
values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
```
Choosing 0 in the backend leads to NULL value in the db, so frontend Output is wrong.

Setting the values e.g. to
```
values: {'00': "00", '01': "01", '02': "02", '03': "03", '04': "04", '05': "05", '06': "06", '07': "07", '08': "08", '09': "09", '10': "10", '11': "11", '12': "12", '13': "13", '14': "14", '15': "15", '16': "16", '17': "17", '18': "18", '19': "19", '20': "20", '21': "21", '22': "22", '23': "23", '24': "24"}
```
is even worse, because the select options in the backend will compile to this:
```
<option value="00">00</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="0">10</option>
<option value="1">11</option>
<option value="2">12</option>
<option value="3">13</option>
<option value="4">14</option>
<option value="5">15</option>
<option value="6">16</option>
<option value="7">17</option>
<option value="8">18</option>
<option value="9">19</option>
<option value="10">20</option>
<option value="11">21</option>
<option value="12">22</option>
<option value="13">23</option>
<option value="14">24</option>
```
which is completely wrong.

Please make sure to check input values correctly (use triple equal signs and in check PHP check for isset and not only empty ...),

**Comment by GawainLynch** [comment]
> Please make sure to check input values correctly (use triple equal signs and in PHP check for isset and not only empty ...),

We do, if there is any left it is a bug. PRs welcome.
