### ISSUE TITLE
Retrieving Repeater empty

### ISSUE THREAD

**Issue by motivecodex** [bolt/bolt#7307]
I've created the repeater to store some additional data, but when requesting it the response for the repeater is empty. When I go to the corresponding item on the page, the repeater is filled with previously added data. So it's not empty, why is the response empty? Everything else seems to be working. 

Details
-------
- Relevant Bolt Version: [3.2.13]
- Installed Rest by Luciano Rodríguez: [1.1.2] requires Bolt > 3.0

* contenttypes.yml

` coupons:
    name: Coupons
    slug: coupons
    singular_name: Coupon
    fields: 
        ...
        contingent_validon:
            type: repeater
            label: Kontingent gültig auf
            fields:
                validon:
                    type: date
                    label: Gültig auf
                contingent:
                    type: integer
                    label: Kontingent
        ...
    show_on_dashboard: true
    default_status: publish
    searchable: true`

![capture](https://user-images.githubusercontent.com/2242015/35222258-9abed2cc-ff7d-11e7-9134-aa93ce7d842a.PNG)

In backend: 
`response.body().string()`

`{
    "data": [
        {
            "values": {
                "id": "1",
                "validfrom": "2018-01-01 00:00:00",
                "validto": "2018-01-31 00:00:00",
                "contingent_validon": {},
                "gallery": [
                    {
                        "filename": "2018-01/c5vynxswaaaghsu.jpg",
                        "title": "2018-01/c5vynxswaaaghsu"
                    },
                    {
                        "filename": "2018-01/1516623359_sat-1.jpg",
                        "title": "2018-01/1516623359_sat-1"
                    },
                    {
                        "filename": "2018-01/1516623359_sat-2.png",
                        "title": "2018-01/1516623359_sat-2"
                    }
                ],
                "ownerid": "1",
                "datepublish": "2018-01-22 11:42:52"
            },
            "relation": null
        }
    ]
}`

**Comment by bobdenotter** [comment]
> Relevant Bolt Version: [3.2.13]

That's pretty ancient.. I'd advise to update first, and then see if the problem persists. :-)

**Comment by motivecodex** [comment]
@bobdenotter Thanks for replying, I was forced to downgrade in the first place, because I had issues with Rest 1.2 and Bolt CMS 3.4.6..

**Comment by bobdenotter** [comment]
I'm not sure what "Rest 1.2" means, but why downgrade to 3.2.13, and not to 3.2.22 (or whatever is the latest 3.2.x)

Anyhow, I think you're bumping into an issue that was fixed in a later release, so it makes more sense to stick with 3.4.6, and look into whatever is causing the issue you have.

**Comment by motivecodex** [comment]
@bobdenotter I've installed 3.4.6, and this happened; https://github.com/bolt/bolt/issues/6707. Any fix on this issue?

**Comment by GawainLynch** [comment]
Refresh the page, it _should_ only happen the once.

**Comment by motivecodex** [comment]
@GawainLynch shift + f5, didn't work. Removed the bolt.db and removed cache, still not working. 

> Uncaught Exception: TableNotFoundException .
> TableNotFoundException in AbstractSQLiteDriver.php line 58: 
> An exception occurred while executing 'SELECT COUNT(log_system.id) as count FROM bolt_log_system log_system':
> 
> SQLSTATE[HY000]: General error: 1 no such table: bolt_log_system

**Comment by GawainLynch** [comment]
Weird, in that case you should be safe doing an `php app/nut database:update` on the command line

**Comment by motivecodex** [comment]
I just removed everything again just to be sure, installed 3.4.6, ran `/web/dir/public/` and it redirected to `/web/dir/public/bolt/userfirst` and the following error came up:

> Twig_Error_Runtime in Template.php line 230: 
> An exception has been thrown during the rendering of a template ("Failed to create directory: /public") in "@bolt/firstuser/firstuser.twig" at line 5.
> 
>                     $e->guess();
>                 }
> 
>                 throw $e;
>             } catch (Exception $e) {
>                 throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $template->getSourceContext(), $e);
>             }
>         } elseif (false !== $parent = $this->getParent($context)) {
>             $parent->displayBlock($name, $context, array_merge($this->blocks, $blocks), false);
>         } else {
>             @trigger_error(sprintf('Silent display of undefined block "%s" in template "%s" is deprecated since version 1.29 and will throw an exception in 2.0. Use the "block(\'%s\') is defined" expression to test for block existence.', $name, $this->getTemplateName(), $name), E_USER_DEPRECATED);

**Comment by bobdenotter** [comment]
@motivecodex I'm guessing you've missed a step in the set up somewhere. You mentioned you had it running earlier, right?

**Comment by motivecodex** [comment]
@bobdenotter You are completely right! I read the updating / upgrading bolt once, and thought I would just be extract and run also for fresh installs. Now I've read also the manual download and extract steps, and I've missed quit some steps. Had to rename 4 files, and add the .htaccess. I can now create new users. Now i'll go and test if the repeater has data with version 3.4.6. 

Thanks!

**Comment by bobdenotter** [comment]
@motivecodex Great! I will just close this issue then.. If you have further questions, feel free to join us, in our Slack channel! :-)

**Comment by ichr** [comment]
> @bobdenotter You are completely right! I read the updating / upgrading bolt once, and thought I would just be extract and run also for fresh installs. Now I've read also the manual download and extract steps, and I've missed quit some steps. Had to rename 4 files, and add the .htaccess. I can now create new users. Now i'll go and test if the repeater has data with version 3.4.6.
> 
> Thanks!

I had the same issue with a new blank install of Bolt 3.6.2 from the tar.gz pack.

The exact file renames are written here:
https://docs.bolt.cm/3.6/installation/manual-download-and-extraction
