### ISSUE TITLE
user level is changed when admin-level user edits own password

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#7309]
## Issue
If a user edits their own password, their user level changed. Thus making them no longer admin, but only editor. 

## Steps to reproduce

- create a new user (let's call him Frank)
- make this user an admin, chief-editor and editor 
- logout
- login as user Frank
- go to config > users and let Frank edit his own password. NOTE: the admin user-level is greyed out, with a disabled checkbox (see screenshot)
- Don't do anything with the user levels, and save the user.
- Tadaaa! no longer Admin.  (insert muffled cries)

![screenshot](https://user-images.githubusercontent.com/5583671/35277112-dcd3a8e0-0045-11e8-87bb-301b945fa990.png)

### what goes wrong? 
The disabled admin level is not saved

## Expected result
- When Frank edits his own password, the users levels should stay exactly as they were.

( He shouldn't have to call me to ask why he suddenly can't see the settings anymore, and make me have to file a bugreport :) )

## specs
Bolt 3.4.6

**Comment by GawainLynch** [comment]
In your `app/config/permissions.yml` you need to set:

```yaml
roles-hierarchy:
    manipulate:
        admin: [ admin ]
```

**Comment by anketwokings** [comment]
## what went wrong
Took a look with @bobdenotter , and we came to the conclusion that our user Frank should not be able to edit his own profile at all. He should not be able to edit any user with the role Admin, including himself.

## what _needs_ to be fixed
So basically, this issue could be fixed with showing the `you do not have the permissions to edit this user` after you click the edit button. This is the same text Hypothetical Frank sees when trying to edit a root-user, for instance. 

And Frank should learn to edit his password under the 'profile' button.

-----
### background:
What actually went wrong, is that a form was submitted with a checked checkbox that was set to `disabled`. And checkboxes that are set to `disabled` are not submitted in the form. Hence the role was removed from the user.

**Comment by GawainLynch** [comment]
> And Frank should learn to edit his password under the 'profile' button.

Well, covering this one first as I don't agree. If a user can edit their password from that screen, then they should be able to. I'd call this one a UX related bug in that case :smile: 

I think I have an idea on how to tackle this … I might need a couple of days (unless @bobdenotter has the time himself).

**Comment by anketwokings** [comment]
> Well, covering this one first as I don't agree. If a user can edit their password from that screen, then they should be able to. I'd call this one a UX related bug in that case

Yup, my thoughts exactly!
