### ISSUE TITLE
Selectfield: Not showing all fields when keys are numeric

### ISSUE THREAD

**Issue by cndforster** [bolt/bolt#7316]
When the keys of a selectfield consists of numeric values (eg. 0.666), the selectfield will not show all its fields in the backend.

Details
-------
 - Relevant Bolt Version: 3.4.6
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome 63

Reproduction
------------
1. Add a selectfield to a contenttype. The keys of the values needs to be numeric:
```
type: select
values:
    1.77777: "Landscape 16:9"
    0.66666: "Portrait 2:3" 
```
2. Log in to the backend and create/edit the contenttype you just changed.
3. Head to the dropdown menu and you will see that only "Landscape 16:9" is present.
4. Select "Landscape 16:9" and save it.
5. Reload the page.
6. Open the dropdown menu again and you see both entries are now present.
7. Remove the selected entry and save it again.
8. After reloading the page the dropdown contains only "Landscape 16:9" again

### Expected result

All values can be selected in the selectfield regardless of its datatypes

### Additional info

What I found so far:
The problem is of course the numeric key. Since the key isn't a string, the key will be used as a numeric array key, which will not work of course.
Go to `view/twig/editcontent/fields/_select.twig` to `line 35` and `line 38` and you can see the key will be used directly as the array key:
`{% if values[id]|default() %}`

By forcing the id as a string like this `values[id~""]` the selectfield works as expected.
I know the hack is not the way to go, but it shows it works with a string

**Comment by GawainLynch** [comment]
Thanks for a solid report :+1: … we'll look into a fix for this.
