### ISSUE TITLE
[3.4.6] Depublish date not work

### ISSUE THREAD

**Issue by Raxta** [bolt/bolt#7317]
Details
-------

 - Relevant Bolt Version: 3.4.6
 - Install type: Zip/tarball install
 - PHP version: 5.6
 - Used web server: Apache 2.2.22

Reproduction
------------
1. Set depublish date for record with status 'published'
2. Wait while depublish date is equal current time

### Expected result
Record status was changed to held

### Actual result
Record status is published

**Comment by Raxta** [comment]
Edit issue

**Comment by romulo1984** [comment]
The same happens to me, even when the state is timed publish, where the content is not published on the date chosen.

Note: When you clear the cache, the content is published

**Comment by Raxta** [comment]
Yep, after clear cache record state changes. It's normal? I think it's bag.

**Comment by bobdenotter** [comment]
Keeping this open, as something seems iffy with both "Timed publish" and "Timed depublish"

**Comment by sbonardt** [comment]
My two cents. If the timed publish only works precisely on the set time when a cronjob is added to check every minute, then this should be a prerequisite. So timed publish IMO shouldn't be a default functionality in Bolt, if it does not work as expected by a user.

I think it would be better to require a person to explicitly enable the timed publish functionality in the CMS when needed, and subsequently inform him/her a cronjob needs to be added as well for it to work on the specified time.

Now, if someone sets a time to publish/depublish, the actual time the content gets published does not reflect the set time. 
The ability to set a specific time, gives the expectation it will be done as so. 
People can start thinking the functionality is broken.

**Comment by ankedsgn** [comment]
Was just running into the same thing. I understand now that timed publish is not working as suggested by the user interface, maybe we can add / alter some things to make this more clear?

## problem
A user can add a exact date and time to have a record published. This suggests that the record will be published at exact that time and date. This is default out-of-the-box Bolt.

Current out-of-the-box configuration does, however, not publish the record at the exact given time. No matter the probably good reasons for this, this is confusing. 

## possible solutions
- Disable the timed publish option from the basic Bolt installation. Make it clear that if you want this, you have to do specific actions and add the cron job.

- Make another workaround that makes the default timed publish work as sugested by the user interface.

- update the docs, not only on the [task scheduler page](https://docs.bolt.cm/3.4/internals/task-scheduler), but also some other pages (will look into that) where users will be likely to search when they encounter this 'buggy' behaviour.  (that's what it feels like if you do not know what is going on)

**Comment by bobdenotter** [comment]
Sounds good. Looking forward to the Pull Requests. ;-)

**Comment by ankedsgn** [comment]
> Sounds good. Looking forward to the Pull Requests. ;-)

I will unleash my php skills :D

**Comment by GwendolenLynch** [comment]
:woman_astronaut: :battery: :fist_raised:

**Comment by develth** [comment]
Also have this issue, when setting a "depublish date" on a already published ContentType. 
Date was not depublished until i cleared the cache

Bolt 3.6.4
