### ISSUE TITLE
Redirect loop after AuthToken Cookie expires

### ISSUE THREAD

**Issue by SenatorSupes** [bolt/bolt#7320]
I am experiencing a problem with the Bolt CMS login page. Periodically, users are becoming caught in redirect loops resulting in their browser showing a 'Too Many Redirects' message. The issue manifests itself after the `bolt_authtoken_xxxx...` cookie stored in their browser expires. The current `cookies_lifetime` setting is set to the default value of 1209600 (2 weeks).

Details
-------
 - Relevant Bolt Version: 3.4.6
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx
 - Reproduced in Chrome 63.0.3239.132 & Firefox 58.0.1. 

Reproduction
------------
### Bug summary
Logged in users either using the site or returning after a previous login session get stuck in a redirect loop between the login page and the dashboard.

### Specifics
Using Redis for session storage. We have 8 web servers running bolt, but all admin traffic is routed to a single node. We do this by filtering based on the /admin path. 
All users affected have the correct permissions and can use the admin console without issue once successfully logged in.
The site is behind an AWS loadbalancer (ALB), SSL is terminated at the loadbalancer.
Clearing the browser cookies will fix the problem temporarily, for the life time of a `bolt_authtoken`.
Flushing Redis DB will fix problem temporarily. 
I have set my `cookies_lifetime` to `60` seconds in our dev environment, this makes it easy to demonstrate the problem without manual intervention.

### Steps to reproduce
- Login to Bolt CMS admin console with valid credentials
- Observe browser cookies for `bolt_session` and `bolt_authtoken`
- Observe expiry dates of cookies
- Navigate around admin console, observe that `bolt_session` cookie expiry advances so as to always be 2 weeks after the last interaction. The `bolt_authtoken` expiry remains unchanged from it's original value
- Wait for `bolt_authtoken` cookie to expire, or just remove it manually
- Next interaction with admin console (e.g. press F5) results in redirect loop

### Expected result
User is served with login page and asked to re-authenticate.

### Actual result
Redirect loop. HTTP 302 between /admin/login and /admin. Browser stops the loop automatically. 

### Additional Details / Things I've Tried
 - Setting `cookies_lifetime` to `0` appears to make this issue happen consistently and immediately. I had hoped that using Session cookie would have avoided the issue.
- It appears the loop is between `Controller/Backend/BackendBase.php:116` and `Controller\Backend\Authentication.php:58 (ish)`. Maybe.

**Comment by jvic** [comment]
Same issue with PHP5.6 .
