### ISSUE TITLE
Translation of ContentTypes #2

### ISSUE THREAD

**Issue by develth** [bolt/bolt#7322]
Hi,

continue of the unanswered autoclosed #7129

Details
-------

 - Relevant Bolt Version: [3.4 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache ] version [ Apache/2.4.10 ]

Reproduction
------------

### Bug summary

Since change / update from 3.3.x to 3.4.x the previously config within `app/translation/messages.de_DE.yml´where the translation was set is not working anymore.

### Specifics

In the Backend, where ContentTypes are used

### Steps to reproduce

Create a file

    app/translation/messages.de_DE.yml

Insert the following Content

     "Pages": "Seiten"
     "Page": "Seite"
     "pages": "Seiten"
     "page": "Seite"
     "contenttypes.pages.name.plural": "Seiten"
     "contenttypes.pages.name.singular": "Seite"

replace "pages / page" with a currently used content type

### Expected result

The word "Pages / Page" should be _translated / replaced_ to "Seiten / Seite"

### Actual result

No Translation / replacement works anymore, worked before upgrade.

**Comment by bobdenotter** [comment]
Hi @develth,

I'm sorry, i don't follow. You've removed the issue template, giving us no details.

Please add a comment, where you describe the relevant details from the [Issue template](https://github.com/bolt/bolt/blob/3.4/.github/ISSUE_TEMPLATE.md), which we wrote for this very purpose.

**Comment by develth** [comment]
HI @bobdenotter 

added your template.

**Comment by bobdenotter** [comment]
If you want to show "Page" as "Seite", why not just update your contenttypes.yml, to make it say that? 
IMHO, the _label_ or _name_ you give a contenttype is just what it should say. It shouldn't be translated.

**Comment by develth** [comment]
Ok, so i have to define one language for my backend? 
Thought bolt would be able to manage and show multiple languages in the backend.

**Comment by horus68** [comment]
> If you want to show "Page" as "Seite", why not just update your contenttypes.yml, to make it say that?
Because you can have 2 backend users using two different languages.

**Comment by bobdenotter** [comment]
> Thought bolt would be able to manage and show multiple languages in the backend.

It currently doesn't. 

> Because you can have 2 backend users using two different languages.

Nope. 

Also, even if you could, I wouldn't like to have this translated.. In short, if you define this: 

```
pages:
    slug: pages
    name: Okidoki2000
    …
    fields:
        …
```

I'd expect to see `Okidoki2000` in the backend. 

Also, if a user defines a _new_ contenttype: 

```
things:
    slug: things
    name: "My Things"
    …
    fields:
        …
```

They will expect it to say "My Things". If they'd have to go find out which translation file it uses, in order to add it there, it'll be very, very confusing.

**Comment by develth** [comment]
As i wrote, it worked in 3.3 with the given File (except of the missing parts i defined in #7129 )

> I'd expect to see Okidoki2000 in the backend.

I would to expect to see the defined translation for each user, if i defined a translation for this keyword.
A BackendUser / Editor does not care what the dev / admin defnied in contenttypes.yml - he want to edit Content and should be able to see in his language where to find the Content he want to edit.

**Comment by bobdenotter** [comment]
Sorry, but I firmly disagree with that. 

That said, there are a lot of quirks in the current translation engine, and it'll be completely  replaced for V4. But, i can tell you already that it'll work as I mentioned earlier: You will see in the Backend, what you define. 

Translation is for stuff like "Save" and "OK" buttons, not for _content_. The labels in Contenttypes and taxonomies are _content_. Just like a tag 'bike' will not get automagically translated to 'fahrrad'. Nope, it's set as 'bike', and it will show as 'bike'.

**Comment by develth** [comment]
OK, so bolt.cm is not applicable for multi-language websites.

Thanks for the clarification

**Comment by bobdenotter** [comment]
@develth Don't be obtuse. Yes it is, you can make perfectly fine multi-language sites using the Translate and Labels extensions. 

The only thing that you and I don't agree on is, that if you have a site in (say) English and German, and the developer built the site in one of those two languages as a 'base' language, that I think it's fair to assume that the editor is not a complete moron, and will recognize a "Page" as a "Seite". If you expect an editor to maintain a site in two languages, it's really not too much to expect of them to have a basic grasp of both those languages.

**Comment by develth** [comment]
@bobdenotter don´t be obtuse, if a contentType is named in one language and can´t be displayed in another, it is **not** multi-language. 
It could be suitable for a editor that speaks the pre-defined langauge, but then the editor is applicable for multi-language, but not the cms.

If the company has branches in e.g. france, spain, hungary, gb & germany and the guys that should edit the content are not able to read the pre-defined language, there is a problem.

**Comment by bobdenotter** [comment]
Sorry to hear Bolt doesn’t fit your needs. Good luck finding another Open Source solution that does meet your criteria.

**Comment by develth** [comment]
Pretty childish reaction!
I already work with cms that fits the stuff, just wanted to make a "issue" to help yours and give another point of view to build maybe a better product.

Good luck with your perfect multi-language solution ;)

**Comment by bobdenotter** [comment]
You call me childish, but I just chose not to spend anymore effort on a futile discussion. You, sir, are the reason people burn out on developing and maintaining Open Source software.

**Comment by develth** [comment]
HA! If you´re not able to discuss you shouldn´t start and share a project as open source that other people can contribute and help to bring a project to another step. Then just do your bodenotter cms and call stuff multilang where it isn´t

**Comment by GawainLynch** [comment]
Both of you please take a breather from this one. The discussion is not constructive.
