### ISSUE TITLE
Bundle configuration

### ISSUE THREAD

**Issue by thomasmedley** [bolt/bolt#7329]
Fresh install of Bolt 3.4.7 and getting the following error:
```
Whoops, looks like something went wrong.
1/1
LogicException in Bootstrap.php line 169:
Extension class name "Bundle\Site\CustomisationExtension" is defined in .bolt.yml or .bolt.php, but the class name is misspelled or not loadable by Composer.
in Bootstrap.php line 169
at Bootstrap::Bolt\{closure}(object(Manager), object(Application)) in Pimple.php line 201
at Pimple->{closure}(object(Application)) in Pimple.php line 126
at Pimple::{closure}(object(Application)) in Pimple.php line 83
at Pimple->offsetGet('extensions') in ExtensionServiceProvider.php line 150
at ExtensionServiceProvider->boot(object(Application)) in Application.php line 197
at Application->boot() in Application.php line 91
at Application->run() in index.php line 12
```

**Comment by GawainLynch** [comment]
As per the issue template you deleted:

 - Install type: [ Zip/tarball install | Composer install | GitHub checkout ]
 - PHP version: [ 5.5 | 5.6 | 7.0 | 7.1 | 7.2 ]
 - Clearly mention the steps to reproduce the bug

**Comment by sablonier** [comment]
Probably ~~reproducable~~ not reading the docs for 3.5 flat structure install and using Option 2 (https://docs.bolt.cm/3.4/howto/troubleshooting-outside-webroot), manual extraction and ignoring the note here about .dist files.

**Comment by bobdenotter** [comment]
But, If you don’t ignore the note on that it works, right? So, this is not really a “bug”, but something that poos up when people haven’t properly read the docs.

**Comment by sablonier** [comment]
Exactly, not a bug. Thought I'm just going to help the bot for the link :)

**Comment by atf2** [comment]
I've just got this message when following the instructions given at https://docs.bolt.cm/3.5/howto/troubleshooting-outside-webroot#option-2-use-the-flat-structure-distribution.  The error occurs at the point after typing 'php app/nut init'.
Further down the instructions there is mention of renaming .dist files, but only if I "extract the .zip manually, in order to upload via (S)FTP" but I didn't, I was following the "curl - tar - php" sequence given under "option 2".
So I'd say if it's not a bug in the code it's probably a bug in the documentation.

**Comment by GaneshKandu** [comment]
Hi,

Getting same issue in Bolt 3.5.7
getting this error after renaming .dist files
and i think its because ```.bolt.yml```
```ini
extensions:
    - Bundle\Site\CustomisationExtension
```
```Bundle\Site\CustomisationExtension``` is in ```.bolt.yml```
Bolt is looking for ```Bundle\Site\CustomisationExtension``` class which is not exist

i am configuring bolt.yml for custom bolt directory

```
paths:
    web: {{bolt_path}}
extensions:
    - Bundle\Site\CustomisationExtension
```

Install type: Zip
PHP Version : 5.5
Mysql Version : 5.5
Apache Version : 2.2

**Comment by bobdenotter** [comment]
@GaneshKandu I think you didn't read the installation instructions carefully. IF you follow this, it'll work: 

https://docs.bolt.cm/3.5/installation/quick-install

If you extracted the tgz or zip manually, it says: 

![screen shot 2018-08-16 at 12 46 46](https://user-images.githubusercontent.com/1833361/44204354-7bba5780-a152-11e8-9127-8ede283c9d16.png)

See here: https://docs.bolt.cm/3.5/installation/manual-download-and-extraction

**Comment by GaneshKandu** [comment]
@bobdenotter 
Oh! Thanks  :+1:  My mistake :smile: :smile:
