### ISSUE TITLE
Popup function with aliases

### ISSUE THREAD

**Issue by psanchezg** [bolt/bolt#7330]
Maybe it would be useful to have a pop-up branch with alias feature because if it is necessary to protect the creation of thumbnails with only_aliases: images are not real created.

What do you think?

**Comment by bobdenotter** [comment]
Hi, I'm not sure I understand what you're saying.. Could you elaborate on what you're trying to achieve, and what the problem is?

**Comment by psanchezg** [comment]
Popup function as defined in the cheatsheet
`popup(filename, w, h)`

With `only_aliases: true` in config.yml this image is never created (not logged)

**Comment by bobdenotter** [comment]
Isn't that what the `save_files` option is for? If set to false, thumbnails are generated "on the fly", and not as actual files.

**Comment by psanchezg** [comment]
It doesn't work with "on the fly" thumbnail generation.

In doc:
[https://docs.bolt.cm/3.4/configuration/thumbnails#thumbnail-aliases](https://docs.bolt.cm/3.4/configuration/thumbnails#thumbnail-aliases)

When using `only_aliases: false` as suggest in "Preventing non-alias Thumbnails" only the thumbnails with alias are generated (in filesystem or on the fly), so I can't use popup function because uses width and height, not alias.
