### ISSUE TITLE
Load growing content type configuration from multiple yml files

### ISSUE THREAD

**Issue by DaanBiesterbos** [bolt/bolt#7331]
Hi, 

I am wondering, is there a reason why there is no support to load multiple contenttype.yml files? 
It would be nice to be able to structure the content type configuration. One of the things I like about bolt is how the data is structured. This is my first project using Bolt, but as a seasoned Symfony developer it feels familiar. Also, I like how the data is structured.  It is kind of surprising that I would need to dump my complete configuration in one file. I guess it would be nice to support yml imports like Symfony does. But my second choice would be to load the configuration using a pattern rather than a hardcoded filename. This would be very easy to implement. Just a few lines code.

Is there a specific reason why you guys decided not to go this way? I will be happy to create a PR if you think this is a welcome improvement. I would need to figure out how to list the configuration files in the admin interface but that should not be a problem I suppose.

```
    /**
     * Read and parse the contenttypes.yml configuration file.
     *
     * @param array $generalConfig
     *
     * @return array
     */
    protected function parseContentTypes(array $generalConfig)
    {
        $contentTypes = [];
        foreach ($this->app['filesystem']->find()->name('contenttypes*.yml')->in('config://') as $ymlFile) {
            $tempContentTypes = $this->parseConfigYaml($ymlFile->getFilename());
            foreach ($tempContentTypes as $key => $contentType) {
                try {
                    $contentType = $this->parseContentType($key, $contentType, $generalConfig);
                    $contentTypes[$key] = $contentType;
                } catch (InvalidArgumentException $e) {
                    $this->exceptions[] = $e->getMessage();
                }
            }
        }

        return $contentTypes;
    }

```

**Comment by bobdenotter** [comment]
Hi @DaanBiesterbos, 

I think one of the reasons is "historical", but that doesn't mean we're not open to changing it. One thing to keep in mind that there's a little more to it than "just a few lines of code". We need to keep in mind what it might mean for the UX of end users. Will the change make sense to the ordinary user, or might it even be confusing? It'll also need to be documented, and we'd need to make sure this keeps working: 

![screen_shot_2018-02-10_at_10_12_42](https://user-images.githubusercontent.com/1833361/36060499-0c4bbc9e-0e4b-11e8-8705-01421bcdc764.png)

**Comment by DaanBiesterbos** [comment]
@bobdenotter  
Hmmm good point. I noticed this yesterday.  Do you have ideas on how this would work ideally? If I would pick this up it would be nice to have a good view on how this feature should work.

Perhaps when rendering this page we just check if multiple files exist. If not we can just display the editor right away. Otherwise we can display the configuration files and navigate to (-/or slide in) the editor view for a particular file. (or we can just display the editor underneath the listing,  although personally I hate scrolling)

Some questions that come to mind:
- Would this feature be optional? And perhaps only available from the command line. If the feature would work like this we can limit but also protect non technical users from adding too many configs. Or do we need a button to add a new config from the UI (somehow displaying the contenttype. prefix before the name) and expect the user to come up with a unique name and hit the save button.
- How about permissions? If users can add/remove files from the gui  than I assume we would need some fine grained access control for that stuff as well?
- I can imagine we might want some search controls to easily find the file in which some content type is defined. Would this we a nice to have, or a must?

**Comment by rossriley** [comment]
For the future once we've fully migrated to Symfony Config component we'd already talked about utilising the resource import feature so you'd be able to have:

```
imports:
    - { resource: another_contenttype.yaml }
```

within the main contenttypes.yaml file and this would get included. Obviously this won't be available until the 4.x release series, personally I wouldn't be against having something simple in the 3.x branch now but I don't think we should spend too much effort on getting UI/perms for something that will probably be obsolete once 4.0 comes about.

**Comment by rossriley** [comment]
I had another thought, we already support dynamic replacement in the config.yml file, would it be feasible to pass contenttypes through this so the value is provided by a service, eg:

```
pages: %contenttype.loader:contenttype_pages.yaml%
```

Reference for the config vars: https://docs.bolt.cm/3.4/configuration/reading#providing-variables-with-a-service

**Comment by DaanBiesterbos** [comment]
Hi rossriley,

I agree, there is no point in putting too much work in it. For now I will just go for a hacky solution. I modified the source.  Not so pretty, but it makes sense for the time being. 

Thanks.
