### ISSUE TITLE
Broken admin panel

### ISSUE THREAD

**Issue by Raxta** [bolt/bolt#7334]
If logged in user goes to /bolt/login admin panel is broken and not opened

 

Details
-------

 - Relevant Bolt Version: 3.4
 - Install type: Zip/tarball install
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

1. Log in to admin panel
2. Go to site
3. Go to /bolt/login
4. Go to /bolt

**Comment by bobdenotter** [comment]
Based on the sparse information you gave, I think this is a duplicate of #7320, and should be fixed in the forthcoming Bolt 3.4.8.

If this is not the case, feel free to re-open this issue with more information. :-)

**Comment by rossriley** [comment]
Just to confirm that the update in #7333 does fix this issue.
