### ISSUE TITLE
In the list by taxonomy doesn't match the number of results when there are any "Timed publish" record

### ISSUE THREAD

**Issue by psanchezg** [bolt/bolt#7337]
With the `controller.frontend:taxonomy` the number of result doesn't match the `listing_records` value if there are any future publication.

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Nginx
 - For UX/UI issues: any browser

Reproduction
------------

In a clean composer installation, add two pages with published status and a "Timed publish" one. Set `listing_records: 1` in `taxonomies.yml` and check the taxonomy route ([http://localhost:8000/groups/main](http://localhost:8000/groups/main))

**Comment by bobdenotter** [comment]
According to Ross, this is also fixed in #7291
