### ISSUE TITLE
Preview page on site after changing slug (and saving) gives error

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#7338]
## How to reproduce
- Go to an existing page / entry
- Change the slug, for instance from `/page/this-is-mi-page` to `/page/this-is-my-page`
- Save your page
- Preview the saved page on your website (under the arrow after the preview button)
- ERROR! The site attempts to find the page at the old slug.

## Logical, huh?
Yeas, it's a logical error, since the slug in the link under the 'preview button-arrow' is not updated when the slug is updated. Probably is not happening very often. After a refresh the slug is updated and all is well again.

## Fix?
Maybe a check if the slug has changed when the page is saved? And then ajaxy changing the link under the button.

### Oh man, Anke, What button is that 'arrow-after-preview'-button?
This one!
![screenshot-offertes twokings eu-2018-02-14-10-22-55](https://user-images.githubusercontent.com/5583671/36196533-585f38c6-1171-11e8-88d1-27e4aa6c0b1e.png)

No biggie, but thank you in advance for fixing.

**Comment by bobdenotter** [comment]
This has been a bug since _at least_ Pilex 0.1 ;-)

**Comment by GawainLynch** [comment]
> This has been a bug since at least Pilex 0.1 ;-)

Making it a real pain in the arse
