### ISSUE TITLE
Markdown field should not strip HTML inside code blocks

### ISSUE THREAD

**Issue by aresdr** [bolt/bolt#7343]
Using the Markdown Field allows the usage of code blocks, but only if the tags are allowed in the htmlcleaner.allowed_tags setting.

The documentation says:

> All content in this field type will be sanitised before it gets inserted into the database.

So if I'm writing an entry about some scripts, the next will not work.

```
    <script>var x = 5;</script>
```

It will simply print an empty block.

The expected result would be those characters converted to html entities. If we disallow the Input Sanitisation for the Markdown Field it will be sanitized on the template output too.
Then my recommendation would be to implement an option to deactivate the Input Sanitisation before saving it in the database, or a rule, or filter, that ignores the code inside valid markdown code blocks.

I think is overkill to add all HTML tags that exists if I write about HTML (example).

Details
-------

 - Relevant Bolt Version: 3.4
 - Install type: Composer install
 - Used web server: Nginx

**Comment by bobdenotter** [comment]
As you might know, "Markdown" does not come with something like an AST. This means that there literally is no way to discern between "javascript that should be executed" and "javascript that is meant to be displayed" in the content. 

Some alternative suggestions, for you to try: 

 - Replace `<` with `&lt;` in your code snippet.
 - Embed Github gists
 - Try wrapping it with `{% verbatim %} … {% endverbatim %}`

**Comment by aresdr** [comment]
Thank you, but I tested your suggestions.

- Replacing `<` with `&lt;`: Outputs `<` if I put it as a plain text, inside a code block or inline code it will show `&lt;`.
- I think is not the best solution.
- The code is striped and tags got printed.

**Comment by aresdr** [comment]
As a work around I followed the execution of the Controller, and found that the class "MarkdownType" implements "SanitiserAwareInterface", so I removed it, now my code works great, and if I put a tag for example `<script>` without a code block, it got saved to database but it is striped on the record template.

**Comment by bobdenotter** [comment]
> "MarkdownType" implements "SanitiserAwareInterface", so I removed it, now my code works great, 

Yes, but that means you've effectively _removed_ input sanitation from that field. Perhaps it's what you want, but it's not a good solution in general.

**Comment by aresdr** [comment]
But would be a good solution if we have choices (configuration) instead of a "you can't" (without modifying the core). Actually we can break many things with a bad configuration, but that's an user problem, not a Bolt problem. Just an opinion.

**Comment by james-jlo-long** [comment]
I really hate this, but there is a simple work-around. You can add HTML directly into your markdown so you can manually encode the HTML entities.

```html
<pre><code class="language-html">&lt;script&gt;var x = 5;&lt;/script&gt;</code></pre>
```

This assumes you're using Prism to render your markup and you're not going to change that.
Also be aware that you need to manually trim the content or you'll end up with a mysterious empty leading line.

I've also found that in the Twig file, you need to output raw content.
```twig
{% if record.markdown %}
    {{ record.markdown|raw }}
{% endif %}
```

This gets around the white-listed code and ensures that the markup won't execute, so no security issue. :smile:
