### ISSUE TITLE
Button "Save & create new record" on new entries is not working

### ISSUE THREAD

**Issue by aresdr** [bolt/bolt#7344]
Using the Entry content type, with an almost new site, if I add a new entry and then click on **"Save & create new record"** in **"Save Entry"** submenu, the entry will be saved but instead of redirect to a new form it return the saved entry, but if again I click the same button, it will redirect to te correct action.

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 5.6.12
 - Used web server: Nginx 1.9.4
 - For UX/UI issues: Chrome 63.0.3239.132 & Firefox Developer Edition 59.0b8

### Steps to reproduce

Create a new entry, then save it with the action "Save & create new record" on the submenu of "Save Entry".

### Expected result

A new form need to be returned.

### Actual result

The saved record form is returned.

**Comment by gwbonline** [comment]
I'd like to add an other issue that I encountered using that button. When I use the option 'Save & go to overview', Bolt doesn't go to the overview. It only saves the record. This does only happen when creating a new record. When I use the same option again (or with existing records) it does go to the overview.

**Comment by SahAssar** [comment]
@gwbonline Any errors in the console?
