### ISSUE TITLE
if config notfound is incorrect - no explaining message on error

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7345]
1. make incorrect `notfound: ...` field in config
2. log out and (or) turn off debug.
3. navigate to not existing page OR put `throw new NotFoundHttpException();` somewhere in controller

You'll get an error that doesn't tell you to fix notfound field.

Here's the code for that:
```php
        try {
            $html = $this->twig->resolveTemplate($template)->render($context);
            $event->setResponse(new Response($html, Response::HTTP_NOT_FOUND));
        } catch (RuntimeError $e) {
            throw new RuntimeException('Unable to render 404 page!', null, $e);
        }
```
but if notfound field is set to the template that is not found by twig (maybe twig path is not registered) `RuntimeError` will not fire.

**Comment by Boorj** [comment]
Guys, @bobdenotter @GawainLynch @rossriley , this time my pull request was a hotfix.
I clearly see that other errors could be thrown:
![image](https://user-images.githubusercontent.com/2145313/36316595-4d7bee88-136d-11e8-9d94-7d4f05c7ba26.png)
I agree that specified distinct exception is the best practice. I expected you tell me what is the correct way to fix that. Unexpected behavior is still here: when you have a problem with `notfound` field, then `RuntimeException('Unable to render 404 page!', null, $e)` is never  fired. So you have not chance to get that.
Maybe we can catch all errors there and show it to user? Or solve that problem somehow?

**Comment by GawainLynch** [comment]
> I clearly see that other errors could be thrown:

As I mention in https://github.com/bolt/bolt/pull/7346#issuecomment-366183672

> Yes, it throws:
> -  `Twig\Error\Loader` when the template can't be found (should not change or be caught here)
> -  `Twig\Error\Syntax` when the template has a Twig syntax error (should not change or be caught here)

> I expected you tell me what is the correct way to fix that. 

Given time fair enough, but I have a full time job running a company. Nonetheless, the bulk of what you ask for is here https://github.com/bolt/bolt/pull/7346#issuecomment-366205474

> Unexpected behavior is still here: when you have a problem with notfound field, then `RuntimeException('Unable to render 404 page!', null, $e)` is never fired.

The exception is not for that ocurrence though. As mentioned in Slack, we can probably tweak what's going on in that block, and chain another exception, but throwing away all exceptions is just not gonig to happen as it reduced the DX to zero.

**Comment by Boorj** [comment]
@GawainLynch @bobdenotter thanks for solving that!
