### ISSUE TITLE
Google Maps Map not showing in Bolt 3.4.8 - Google Maps Plugin

### ISSUE THREAD

**Issue by AlexL777** [bolt/bolt#7351]
I'm just trying to get the google maps plugin in Bolt 3.4.8 up and running, but the map is not showing in the frontend. What am I doing wrong?

Details
-------
I upgraded from Bolt 2.2 to 3.4.8 and installed the google maps in the last version. In the config.yml I have also deposited the API key.

In the template project.twig I included this code for the map.

        {{map(
      latitude = record.geolocation.latitude,
      longitude = record.geolocation.longitude,
      html = record.body,
      icon = "fa-map-marker",
      record = record,
      google_options = {
        scrollwheel: true,
        navigationControl: true,
        mapTypeControl: true,
        scaleControl: true,
        draggable: true,
        disableDefaultUI: false
     }
     )}}

In the frontend under http://immobilien.gr/project/ferienanlage-in-griechenland only that of Google is displayed, but not the map itself.

I created the field geolocation in the content types and added it to the config. This way I can work with geolocation when creating the entries.

But I was told in Slack that it's a CSS issue, but unfortunately I can not go on.

In the style.css I have the stand for the map.

    .map-canvas {
    height:50vh, width:150vh
    }

Can someone help me? Thanks in advance.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by xiaohutai** [comment]
The map is showing on the bottom, the latitude and longitude are probably set (defaulted) to (0, 0). If you zoom out, you'll start seeing Africa.

You want to double check whether the data in the database is in the appropriate format.  From Bolt 2.2 to 3.4.8, it might be JSON instead serialized arrays now.

Hope this helps.

**Comment by AlexL777** [comment]
I have the geolocation field in the backend when creating an entry. I then search out the address and it does not have to be displayed in the frontend at the correct address.

In fact, just zoomed out and I see Africa. Somehow, no connection is made between the geolocation field and the map. That's probably what it's all about.

**Comment by xiaohutai** [comment]
Your page shows me:
```
[{"latitude":null,"longitude":null,"html":{},"icon":"fa-map-marker","color":"rgba(0,0,0,1)"}]
```

So you want to make sure you get the correct values from your geolocation field. You can always try a `dump` to see what's inside, with:
```
{{ dump(record.geolocation) }}
```

See also: https://docs.bolt.cm/3.4/fields/geolocation

**Comment by AlexL777** [comment]
![immobilien-gr-geolocation-field](https://user-images.githubusercontent.com/7885632/36380434-8c718ad2-1582-11e8-9ff5-1f601c2915b3.png)

I have that in the Bolt Backend in this entry. But the map does not show this address and the only problem with me today.

With "dump" it does not seem to work. I embed the code, but it shows no impact and nothing else.

**Comment by SahAssar** [comment]
@AlexL777 You need to turn on debug to dump it. Turn it on in your config.yml

**Comment by AlexL777** [comment]
I see this with Debug:

![immobilien-gr-debug-geolocation-field](https://user-images.githubusercontent.com/7885632/36381375-a735ea40-1585-11e8-9ee5-7b3fb8eb843a.png)

**Comment by xiaohutai** [comment]
What's the field called? `location`, `geolocation`, or what?

**Comment by AlexL777** [comment]
In Configs i have this:

```
location:
     type: geolocation
```

**Comment by SahAssar** [comment]
Then do ```
    {{map(
  latitude = record.location.latitude,
  longitude = record.location.longitude,
  html = record.body,
  icon = "fa-map-marker",
  record = record,
  google_options = {
    scrollwheel: true,
    navigationControl: true,
    mapTypeControl: true,
    scaleControl: true,
    draggable: true,
    disableDefaultUI: false
 }
 )}}
```

**Comment by AlexL777** [comment]
Thanks, this worked 👍

**Comment by ghost** [comment]
Hello Developers,

Something has changed in Bolt or Maps, so unfortunately the map view only shows the world map including the equator.

I have this Maps code.

     {{ dump(record.geolocation) }}
     {{map(
     latitude = record.location.latitude,
     longitude = record.location.longitude,
     html = record.body,
     icon = "fa-map-marker",
     record = record,
     google_options = {
        scrollwheel: true,
        navigationControl: true,
        mapTypeControl: true,
        scaleControl: true,
        draggable: true,
        disableDefaultUI: false
    }
    )}}

What must the code be so that the website visitor finds the maps so that they are zoomed into the map when they first access the page. The map view should show a zoomed-in view of where you can possibly use Google Street View.

I have already compared several maps codes and the Bolt 3.5.3 in the theme Hobart (a very old theme) does not work anymore the code from here out of Github.

I usually put it in the template project.twig.

So what am I doing wrong and what do I have to consider?

Thank you again for the time.

**Comment by ghost** [comment]
Ok, my Problem is solved!!
