### ISSUE TITLE
[BUG] Memcachd Handler sets invalid Option and crashes Bolt

### ISSUE THREAD

**Issue by cndforster** [bolt/bolt#7357]
When setting `memcachd` as session handler, Bolt's `MemcachdFactory.php` tries to set the option **Memcached::OPT_SERVER_FAILURE_LIMIT** to the default of 0. This results in a critical exception:

```
ContextErrorException in MemcachedFactory.php line 110:
Warning: Memcached::setOptions(): error setting memcached option: INVALID ARGUMENTS
```

Removing the following line 110 resolves the issue. The session work fine after removing it.
```
Memcached::OPT_SERVER_FAILURE_LIMIT => $option->getInt('server_failure_limit'),
```

This is the configuration used for this case:
```
session:
  save_handler: memcached
  connections:
    - host: 1.2.3.4
    - host: 1.2.3.5
```

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer
 - PHP version: 5.6.32
 - PHP Memcachd Extension: 2.2.0 (libmemcachd 1.0.16)
- Memcachd server version: 1.4.15
 - Used web server: Apache 2.4

Reproduction
------------
Add above configuration (replace ips with something real!) and open any bolt page.

**Comment by bobdenotter** [comment]
Instead of _removing_ that line, could you try setting it to: 

```
Memcached::OPT_SERVER_FAILURE_LIMIT => $option->getInt('server_failure_limit', 0),
```

And then try again?

**Comment by GwendolenLynch** [comment]
@cndforster I've tagged `bolt/session` v1.1.1 with the fix from @rossriley to the default value.
