### ISSUE TITLE
Displayed name of group in overview doesn't match set value

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7366]
See screenshot: 
![screen_shot_2018-03-07_at_09_20_53](https://user-images.githubusercontent.com/1833361/37081219-05819396-21e9-11e8-9726-8fe118fa66a4.png)

**Comment by xiaohutai** [comment]
Looks like it used to be
```
"info" => "Info"
```
and then it got changed to
```
"info" => "Praktische informatie"
```
and the group gets its (label) data from the database, without looking at the `taxonomy.yml`.

Does it go away when triggering a save on record no. 2 again?

**Comment by bobdenotter** [comment]
Kinda, if i do that, and _filter_ on "Praktische Info", i get this amusing result: 

![screen shot 2018-03-07 at 09 56 38](https://user-images.githubusercontent.com/1833361/37082864-f86db324-21ed-11e8-8a20-18dcddd2652d.png)

So, you're right about why it happens, and it doesn't really _break_ anything ("old" filtering in the frontend on `info` still works), but I think I can make it behave a bit more consistent in the backend.
