### ISSUE TITLE
Leave filenames as is in file upload

### ISSUE THREAD

**Issue by Jogai** [bolt/bolt#7370]
Uploading a file like "2018 UpperCase.mp3" results in an uploaded file named "2018_uppercase.mp3". Can this be configured to just use the provided file name?

**Comment by rossriley** [comment]
Have a look in your `config.yml` and adjust these options.

https://github.com/bolt/bolt/blob/3.4/app/config/config.yml.dist#L233-L236

**Comment by Jogai** [comment]
Perfect! Awesome!
