### ISSUE TITLE
[RFC] Chronological notifications for extensions updates.

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#7373]
I would like to know if this could be an useful feature. I'm willing to help if anyone can point me in the right direction.

Basically I would run a cron job that would check on predefined time intervals and pop a notification letting me know that there are updates available for installed extensions.

**Comment by GwendolenLynch** [comment]
Probably very doable! Start by looking in the Composer namespace at the action commands, they talk directly to the Composer API for similar reasons.

**Comment by zomars** [comment]
I'm still doing this
