### ISSUE TITLE
[RFC] Update Bolt's minor versions via GUI

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#7374]
We already have a GUI for installing and updating bolt's extensions, but... I think it would be useful to be able to run the same `composer update` command for the overall bolt's installation. 

I'm willing to help if pointed to the right direction also.

**Comment by SvanteRichter** [comment]
This has been discussed a few times, and it requires some pretty bad practices: #6239

**Comment by zomars** [comment]
@SahAssar could be this the job for a "semi-official " extension? I'm aware that it could open the pandora's box but for some well behaved clients this could be a huge relief for both them and myself as a dev.

**Comment by GwendolenLynch** [comment]
It isn't a problem of (or not) well behaved … it is partially a problem that even well-behaved devs with PhDs in comp-sci don't fully understand the problems they can create.

I'd like us to see us take a look at this for v4, but for v3 it is for all intents impossible to do in any way that is worth the effort :disappointed:

**Comment by zomars** [comment]
I don't want to bring the "but worddepress does it" to the table, but it is a constant question I get from clients and I just want to be able to respond with other than: ¯\_(ツ)_/¯

**Comment by GwendolenLynch** [comment]
> I don't want to bring the "but worddepress does it" to the table

Sure, I hear that a bit too. But I also hear endlessly about WordPress sites being compromised as a result of them doing things like this.

Everyone is moving away from this thinking now (fortunately), much in the same way jQuery is a thing of the past :wink:

**Comment by SvanteRichter** [comment]
Also, just saying that if you trust the updates enough to let your client do them via a HTTP request it'd be trivial to create a cronjob that autoupdates without requiring many of the bad practices. I'm not at all saying you should do that, but it's very easy.
