### ISSUE TITLE
Update SQLite DB leads to modifications with notice of invalid columns

### ISSUE THREAD

**Issue by tkeil69575** [bolt/bolt#7382]
Details
-------

 - Relevant Bolt Version: 3.4.9
 - Install type: Composer install
 - PHP version: 5.5.9 (on Debian Stretch)
 - Used web server: Nginx 1.12.2
 - For UX/UI issues: Chrome 64.0.3282.186

Reproduction
------------

After editing the contenttypes.yml a little, I got a message to update the DB (using SQLite here). However, I ignored this and changed the contenttypes.yml back to the original. I still got a message to update the DB (but this time no notice of any changes). Since then, if I update the DB, I get the messages below stating that apparently there are invalid columns. However, all seems to be working and I can't identify any side effects. I've checked the DB and these columns exist. Not sure if it relates to this issue (https://github.com/bolt/bolt/issues/6856)? Sorry if this isn't very helpful or detailed enough ... just starting out on Bolt.

### Bug summary

```
Modifications made to the database:
Updated bolt_blocks table to match current schema. invalid column templatefields, invalid column image
Updated bolt_entries table to match current schema. invalid column templatefields, invalid column image, invalid column video
Updated bolt_field_value table to match current schema. invalid column value_json_array
Updated bolt_log_change table to match current schema. invalid column diff
Updated bolt_log_system table to match current schema. invalid column source
Updated bolt_pages table to match current schema. invalid column templatefields, invalid column image
Updated bolt_users table to match current schema. invalid column stack, invalid column roles
```

**Comment by bobdenotter** [comment]
This _will_ be somewhat better on PHP 7.1, after a `composer update`, because it will then have newer versions of Doctrine available. 

If it persists, it might require manual modification of the tables.

**Comment by bobdenotter** [comment]
Doctrine DBAL 2.7.1 has been released, and it seems like this is much less of a problem than it was before. See if you van upgrade to PHP 7.1, and then run a `composer update`.

**Comment by chungf** [comment]
I have the same problem, using DBAL 2.7.1 and Bolt 3.5.0. The root of the problem seems to be in either the way of emulating column comments in SQLite or how the database check looks them up from the schema.

Edit: Managed to download a copy of bolt.db to examine elsewhere. The DC2Type comments are stored as intended in the schema. So the problem is probably more likely at the point of database check?

**Comment by zomars** [comment]
I'm having a similar issue using SQLite in PHP 7.1 also. The site is returning `Type error: Return value of Doctrine\DBAL\DriverManager::_checkParams() must be an instance of Doctrine\DBAL\void, none returned`.

On my localhost works fine tho.

**Comment by chungf** [comment]
Tested in Bolt 3.5.6 and found to be by: https://github.com/bolt/bolt/pull/7570

**Comment by GwendolenLynch** [comment]
Oh, good point @chungf … I've not been doing my housekeeping properly :innocent:
