### ISSUE TITLE
Invalid text in button "Delete <content-type-name>" in admin

### ISSUE THREAD

**Issue by tomas-zemres** [bolt/bolt#7392]
Button contains by mistake text "Delete {content-type-slug}" instead of "Delete {content-type-name}"

I use bolt Version: 3.4.10

--
If I look into file "vendor/bolt/bolt/app/view/twig/editcontent/_aside-delete.twig",
I see:
```
 ... {'%contenttype%':` context.contenttype.singular_slug}) } ...
```
But I think there should be ".contenttype.singular_name" instead of ".contenttype.singular_slug"

**Comment by bobdenotter** [comment]
Could very well be the case. Want to make a Pull Request to fix it? Strictly for the karma points, of course!
