### ISSUE TITLE
[bug] rare jquery serialization error, when saving record

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7395]
repro
---
1. create field called `elements:` in any contenttype. In my case it's a selectbox input.
2. goto edit content and try to save from editcontent page
3. ajax post is not working

#### reason
We are serializing form data by jquery's native `serialize` 
https://github.com/bolt/bolt/blob/3.4/app/src/js/modules/editcontent.js#L381 : 
It calls `serializeArray`, and that one calls `this.prop('elements')`. 
Which unfortunately, relies on to getting `formDomNode.elements` - a special DOM-node property for getting all child inputs. Which is overwritten by browser behaviour. 
It's a known bug of jquery. See below.

So let's find out.

repro2
---
1. create field called `elements:` in any contenttype. In my case it's a selectbox input.
2. goto edit content
3. run in console `$f = $('form[name="content_edit"]')`.  `$f` represents a form.
4. run `$f.serialize()`. It returns `""`.  
Why? Because **Jquery** uses .props('elements') [here](https://github.com/jquery/jquery/blob/master/src/serialize.js#L102):
```js
//...
serializeArray: function() {
		return this.map( function() {
			// Can add propHook for "elements" to filter or add form elements
			var elements = jQuery.prop( this, "elements" );
			return elements ? jQuery.makeArray( elements ) : this;
		} )
//...
```
here's the bug report: https://bugs.jquery.com/ticket/13651
5. run `$f.prop('elements')`. It returns (prints in console) our `<select ..>` element.  And it's expected, that it will return the list of all inputs in form.
6. Now remove our select element  `$f.prop('elements').remove()`. And try `$f.prop('elements')` again. Works like a charm.

### Possible solution
I know, that it's a jquery/DOM problem. But maybe we can add some prefixes, or name modifiers to inputs — and then remove them after serialization. To be sure that we will not overwrite any node's original property.

**Comment by Boorj** [comment]
According to http://jibbering.com/faq/names/ , browsers turn named children to properties of form. 
So, there are also some other unsafe properties, which could interfere with our contenttype field names.

# solution 1
Add prefixes and remove them after serialization. This will allow to avoid _any_ side effects, related to that unsafe DOM properties.
I assume that this hack smells a little, but this case is about browser behavior, which can't be avoided.
So, prefixing will guarantee safety.

Here:  https://github.com/bolt/bolt/blob/3.4/app/view/twig/editcontent/_field.twig#L21 (and in some other places)
```twig
{% set prefix = 'BOLT_FIELD_PREFIX_' %}
 {% include templatename with {
        'key': key,
        'name':  prefix ~ key,
        'contentkey': key
    } %}
```

And then replace simple serialization [here](https://github.com/bolt/bolt/blob/3.4/app/src/js/modules/editcontent.js#L381)
```js
var postData = editForm.serialize()
    + '&' + encodeURI(button.attr('name'))
    + '=' + encodeURI(button.attr('value'))
```
to 
```js
var rawPostData = editForm.serializeArray()
// by the way, jquery Serialize is 
$.serialize === function () {
 return $.param(this.serializeArray());
},
```
which gives
  ![image](https://user-images.githubusercontent.com/2145313/37892987-e0366aec-3103-11e8-8573-6176955d500e.png)
And then replace all prefixed fields
```js
rawPostData.forEach(function(item){ //or any crossbrowser iterator (for()/$.each) if we support oldies
    if (item.name.indexOf('BOLT_FIELD_PREFIX_') === 0) {
        item.name = item.name.replace('BOLT_FIELD_PREFIX_', ''); //or substr/slice
    }
})
var postData = $.param(rawPostData)
    + '&' + encodeURI(button.attr('name'))
    + '=' + encodeURI(button.attr('value'));
```

# solution 2
Use custom serialization method. Some kind of `editForm.find('[name]').each(...)`.

**Comment by bobdenotter** [comment]
Seems like a valid point at first sight. Not sure if it's feasible to fix properly, though.. 

🤔 💭

**Comment by Boorj** [comment]
Another solution : add some data attribute (`[data-js-field-value]`) to each generated input. 
But if `name` attribute generation _can_ be prefixed in one place, the additional attribute will take lots of injection points.

**Comment by Boorj** [comment]
hey

**Comment by Boorj** [comment]
not this time, not this time, Stale bot...

**Comment by Boorj** [comment]
@bobdenotter  i think prefixing names is a good solution. And removing prefixes after serialization, before sending to server

**Comment by Boorj** [comment]
Also we can put `elemets: ...` to restricted contenttype field names.

**Comment by Boorj** [comment]
nope

**Comment by Boorj** [comment]
@bobdenotter this is a bug that doesn't allow to use a field named "elements" in content types. So can you please put "keep" tag?

**Comment by bobdenotter** [comment]
For this one I also think it's more feasible to fix in Bolt v4. I've just verified, and so far there's no problem naming fields using restricted names. See `where`, `select` and `elements` in screenshot below: 

![screenshot 2018-11-03 at 13 00 17](https://user-images.githubusercontent.com/1833361/47951959-8a055c00-df68-11e8-87e9-6cc769518b52.png)

**Comment by jadwigo** [comment]
@Boorj It's probably easier to just name the field `sidebar_elements` or something similarly specific and avoid the problem.

----
@bobdenotter  - the test you did is not representative.

A **text field** called **elements** will not trigger this, a **select field** called **elements** will add javascript events to that field.. and the name **elements** apparently has collisions in the jQuery library - which is a problem in the client browser.

**where** and **select** are reserved words in SQL, which is a completely different language, and handled on a completely different area, namely in the data layer of the CMS on the server.

**Comment by bobdenotter** [comment]
I was merely pointing out that the issue @Boorj was bringing up ("Reserved terms in SQL and/or jquery") is no longer an issue in Bolt 4, so far.

**Comment by Boorj** [comment]
> @Boorj It's probably easier to just name the field sidebar_elements
yeah, sure, merrily i know the solution

Problem is that i'm the one who faces the problem && _is able to report_ it, when there are plenty of people that are just getting the error silently. And still counting with Bolt's growth. But if @bobdenotter  tells that it's ok and it will be fixed in new bolt - cool

@bobdenotter  by the way, from my point of view, the best and clean solution is to prefix all field names for javascript frontend.

P.s. _offtopic_ Also it would be nice to prefix **all** route names in twig templates for a case if someone decides to create `about` route (and it's reserved by bolt default route)
