### ISSUE TITLE
Show maximum file upload size in interface.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7401]
Suggestion
---
It's not hard to show people, what is the maximum size for file upload. On my experience, users often don't know what is the limit size of file. For example, they are trying to upload 4MB photo from  digital camera, while limit is 2MB. 
So it would be convenient to show max size _before_ user attempts to upload.

Design
---
![image](https://user-images.githubusercontent.com/2145313/37956919-d4643284-31d6-11e8-80fb-554ed0b7af94.png)

Also i assume that it will require translations, so message could be changed to **`<2MB`**

Solution
---
Some lines should be added to [/app/view/twig/editcontent/fields/_imagelist.twig](https://github.com/bolt/bolt/blob/3.4/app/view/twig/editcontent/fields/_imagelist.twig). Like this:
```twig
<div class="buic-proper-file-warning">Maximum file size is {{ app['filepermissions'].getMaxUploadSizeNice() }}</div>
```
and here: [/app/src/sass/editcontent/fields/_imagelist.scss](https://github.com/bolt/bolt/blob/3.4/app/src/sass/editcontent/fields/_imagelist.scss) to style the markup.

**Comment by bobdenotter** [comment]
@Boorj Good point. I recall that there once was a good reason why i had to hardcode that. Back in the day.. We might want to revisit that, and see if we can make it display the correct value now.

**Comment by Boorj** [comment]
File upload is performed by 2 different plugins, (`dropzone` in file manager and `blueimps` in buic). 
Its configuration uses 2 different file sizes - one with fallback to size, and one - without any filesize limit. That's a problem too, by the way. 

Config for blueimp
---

https://github.com/bolt/bolt/blob/3.4/src/Filesystem/FilePermissions.php#L132
```php
    public function getMaxUploadSize()
    {
        if (!isset($this->maxUploadSize)) {
            $size = Ini::getBytes('post_max_size');

            $uploadMax = Ini::getBytes('upload_max_filesize');
            if (($uploadMax > 0) && ($uploadMax < $size)) {
                $size = $uploadMax;
            } else {
                // This reduces the reported max size by a small amount to take account of the difference between
                // the uploaded file size and the size of the eventual post including other data.
                $size *= 0.995;
            }

            $this->maxUploadSize = $size;
        }

        return $this->maxUploadSize;
    }
```

https://github.com/bolt/bolt/blob/3.4/app/view/twig/_base/_page.twig#L91-L96
```twig
    uploadConfig: {
        //...
        maxSize: app['filepermissions'].getMaxUploadSize(),
        maxSizeNice: app['filepermissions'].getMaxUploadSizeNice(),
    },
```

and https://github.com/bolt/bolt/blob/3.4/app/src/js/widgets/buic/buicUpload.js#L64
```js
        _create: function () {
        
            // ...
            if (this.options.maxSize === null) {
                var tempSize = Math.floor(bolt.conf('uploadConfig.maxSize'));
                this.options.maxSize = bolt.utils.filterInt(tempSize, 2000000);
            }

            //...

            $fileInput.fileupload({
                //...
                maxFileSize: this.options.maxSize > 0 ? this.options.maxSize : undefined,
                minFileSize: undefined,
               //...
            });
      }
```

Config for filemanager dropzone:
---
https://github.com/bolt/bolt/blob/3.4/app/src/js/modules/filemanager.js#L152-L168
```js
function bindDropzone() {
      //...
        var DropzoneTarget = new Dropzone(document.body, {
            url: bolt.conf('uploadConfig.url'),
            previewsContainer: "#dropzone-preview",
            acceptedFiles: '.' + bolt.conf('uploadConfig.acceptFilesTypes').join(',.'),
            uploadMultiple: 'true',
            enqueueForUpload: 'true',
            hiddenInputContainer: '.form-horizontal',
            paramName: 'file_upload[select]',
            clickable: false,
            autoProcessQueue: true,
            params: {
                'file_upload[_token]': csrf
            },
            init: function () {
                dragOver(this);
            }
        });
```
Don't know, why file size limit. There should be `maxFilesize` (http://www.dropzonejs.com/#config-maxFilesize)
We could use the same as buicUpload implementation (see above). Like `Math.floor(bolt.conf('uploadConfig.maxSize'));`

**Comment by Boorj** [comment]
By the way, i think file size limit should relate only to `upload` button, not to `"select from server"`

**Comment by Boorj** [comment]
up

**Comment by Boorj** [comment]
no way bot!

**Comment by Boorj** [comment]
hey, this is not fair! ) i can do a PR!

**Comment by bobdenotter** [comment]
@Boorj In that case, please do the PR. ;-)

**Comment by Boorj** [comment]
copy that
@bobdenotter 
1. where should i put text message (in messages.yml) ? How should i call it ? 
2. should i only add message or fix usage?
3. should i make filesize variable consistent (see above)?
