### ISSUE TITLE
Can't upload 'foo.JPG' because of uppercase extension

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7405]
Repro:
---
* goto file manager
* try to upload file with 'JPG' extension.
* it gives the error "can't upload because of extension" 👎 

## solutions
* check in one case (uppercase/lowercase)
* allow upload uppercase files .JPG
* rename file to lowercase extension after upload

**Comment by GwendolenLynch** [comment]
`jpg` !== `JPG` 

Files names — ergo their extensions — are case sensitive. Add JPG to the allowed extension list.

**Comment by Boorj** [comment]
So this is an option #2 from the list above. 

But.. we both know that `jpg` and `JPG` are the same file formats. So, wouldn't it be nice to allow webmasters not to worry about this interesting problem? Or that should be pointed in documentation somehow. Because this is not a one-per-million case. Often digital camera just names files that way. Often users even don't see the extension in their windows explorer.

Or @GawainLynch can you tell in couple words, what is the case, where we need uppercase extension? I understand that in *nix these files are different, but this will be quite confusing for typical users/webmasters. So shouldn't it be handled by Bolt 🔩 ?

**Comment by Boorj** [comment]
we are sanitizing filenames on upload. So it's a priory possibly modified. So, why can't we accept uppercase extensions, and then `mb_strtolower()` extension during UploadHandler processing? That will heal headache of many webmasters

**Comment by GwendolenLynch** [comment]
Well, in some ways it is pretty simple and we could just lowercase the extension value before comparing it in against config.

On the other hand, and to give a couple of words where this matters. On my sites I've had a lot of problems where editors have uploaded files directly from cameras averaging +8 MiB in size. So blocking `JPG` allows me to keep some control over that. When they come complaining to me I ask if they've been through an image processor … of course they haven't, and when they do the 8 MiB file is 100 or 200 **KiB** :wink: 

As for renaming, that is already handled and configurable.

**Comment by GwendolenLynch** [comment]
Plus changing this behaviour would be a BC break

**Comment by Boorj** [comment]
1. You have very lame (meant: weak) example;) In your case: you solved *size* problem with *extension* solution. There should be file size limitation, and not solving that size issue with just limiting extensions. They still can rename file and that will still won't be processed. So i refuse to accept your example. But, it's still only my opinion.
2. Why is it BC break?
3. If you leave it as it, does it deserve to be mentioned in documentation and config.yml.dist ? Like `"Beware: extension filter is case sensitive. So 'jpg' and 'JPG' are different extensions"`
4. Also, even error message is confusing:
    ![image](https://user-images.githubusercontent.com/2145313/37976974-ffd92c36-320c-11e8-92f1-0049f46013f4.png)
    Note, that all extensions are uppercase (‼️)
5. Also , you have `config.upload.lowercase` 


So
1. What to other guys think about that? @bobdenotter @SahAssar ?
2. Maybe we should add an option, like 
```yml
upload:
  # pattern: '[^A-Za-z0-9\.]+'
  # replacement: '-'
  # lowercase: true
  allow_uppercase_extensions : false #by default
# OR
accept_file_types_extensions_case_insensitive: false # should create a better name 🤕 
```
which will allow also all those 'JPG, PNG, ...' ? 

#### upd:
this also could be solved in _mega-config-for-upload_, mentioned in #7408

**Comment by GwendolenLynch** [comment]
> You have very lame example

That is enough for me to close this without further comment. Please keep it on topic.

**Comment by GwendolenLynch** [comment]
> Why is it BC break?

Because anyone realistically expecting current behaviour will have their site's back-end break. Don't underestimate the number of people that will be

**Comment by Boorj** [comment]
Excuse my english, @GawainLynch, meant weak, not pure

**Comment by GwendolenLynch** [comment]
> If you leave it as it, does it deserve to be mentioned in documentation and config.yml.dist 
> Also, even error message is confusing:

Agreed!

**Comment by GwendolenLynch** [comment]
> Also , you have config.upload.lowercase

Yes, but that is a different paradigm

**Comment by GwendolenLynch** [comment]
> Sorry my english, @GawainLynch, meant weak, not pure

My friend, zero stress! Just trying to communicate back to another friend! :+1:

**Comment by Boorj** [comment]
> Don't underestimate the number of people that will be

i don't , but (!) if you have an option in sanitizer `config.upload.lowercase: true` by default. Won't it guarantee that all files will be kept? Or can't we use `config.upload.lowercase` as a flag to make extension check case insensitive ?

**Comment by Boorj** [comment]
1. Or you mean that .. khm 😊 .. akward 🙄  situations when people did set up, relying on 'JPG' filtration as maximum filesize filtration? And then you remove that rule and people start uploading big .JPG files? 

2. also, maybe that should be planned as part of major releases?

**Comment by Boorj** [comment]
hey hey)

**Comment by Boorj** [comment]
This case looks like one of those small tiny things, that are easy to loose.
@GawainLynch @bobdenotter i think this issue should be revised again, i read it again and found many good arguments.

**Comment by bobdenotter** [comment]
Let's see if we can do something about this.

**Comment by cmehta82** [comment]
I believe the method checking file extensions can be changes simply to : 

`
        const filesNotMatchExtensions = filesArray.filter((file: File) => {
            const extensionsList = (acceptExtensions as string)
                .split(', ')
                .map(extension => extension.slice(1).toLowerCase())
                .join('|');

            const regexp = Ng4FilesUtilsService.getRegExp(extensionsList);

          let fileName = file.name;
          if(fileName) {
            fileName = fileName.toLowerCase();
          }
          return !regexp.test(fileName);
        });
`

This should solve the problem

**Comment by JarJak** [comment]
Fixed :)
