### ISSUE TITLE
[RFC] Can we have checkboxes over files in filemanager?

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7410]
Suggestion
---
Wouldn't it be nice, if we have some functions for file group operations in file manager?
As we have in records listing
![image](https://user-images.githubusercontent.com/2145313/37980992-adc2c3da-3216-11e8-8dc2-99a5181bc0b7.png)

how it could look
---
![image](https://user-images.githubusercontent.com/2145313/37981426-dff4ec7e-3217-11e8-8495-e62acf5cf898.png)

#### in motion:
![2018-03-27_23-39-10](https://user-images.githubusercontent.com/2145313/37981516-12a0da8e-3218-11e8-9f21-76c52d334399.gif)

**Comment by cdowdy** [comment]
What would the checkbox do?  

Edit: I actually looked instead of just commenting.. it triggers a delete option :) there's already a delete button under the options button dropdown

**Comment by Boorj** [comment]
Yes, but i mentioned **group** operations. Delete, move, rename. Would open doors to killer features like image bulk editing (resize, re-save with lower jpg quality, watermark)

**Comment by Boorj** [comment]
looks like  #3984 , but not implemented in file manager

**Comment by Boorj** [comment]
hey

**Comment by GwendolenLynch** [comment]
Closing as there is nobody stepping up to work on this. Usual stuff, if someone wants to that is welcomed.

**Comment by Boorj** [comment]
@GawainLynch i can do that, but i thought that there's only one person, who is responsible for JS part.
Anyway.. if there's one table editor wih extra functions, can we use the same to that list?
I'd could do this task, and i need some directions, what to use. Couple advises should be enough.

**Comment by Boorj** [comment]
@GawainLynch @bobdenotter  Do we have any label, like "high hanging fruit" that could be assigned to useful but non-urgent task? So you can assign that to an issue and close it. And if someone wants to spend time on improving bolt, he (or she) can filter closed issues by that tag and do the job.
