### ISSUE TITLE
Categories / Tags hierarchy feature?

### ISSUE THREAD

**Issue by mnicolas80** [bolt/bolt#7414]
Are you planning to add the hierarchy feature in categories or tags?
Especially in cases of products presentation, it would be nice to organize the products under multiple level categories.

e.g /category1/category1.1/product-url.html

**Comment by bobdenotter** [comment]
It's not currently planned, i'm afraid. 

You can - to some extent - workaround this by using either multiple taxonomies, or adding a bunch of them like `movies-action`, `movies-romcom`, `movies-documentary`, creating a fake hierarchy.

**Comment by GwendolenLynch** [comment]
This would also be very hard to do properly in 3.x, when we have a better idea of the 4.x model it might be an easier thing.

What I will say is the hierarchical "everything" is a pretty common request, so is at the front of my mind for what will be done in v4 :smile_cat:

**Comment by mnicolas80** [comment]
Thank you for your quick responses!
