### ISSUE TITLE
Problems with conversion of select-type field values

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7422]
repro
---
- create contenttype field with type `select`
- add **hash-style values**. like
    ```yml
    values: {foo: FOOO, bar: BAAAR}
    ```
- select some options and save record
- convert values to **list-style values**
    ```yml
    values:
      - bombastic
      - fantastic
    ```

- get an error:
![image](https://user-images.githubusercontent.com/2145313/38140034-462b6d60-345c-11e8-9ec3-598abaf78db7.png)

I suppose, this thing should be caught somehow.

**Comment by Boorj** [comment]
hey

**Comment by Boorj** [comment]
this is still actual

**Comment by bobdenotter** [comment]
This will most likely be fixed by #7489

**Comment by Boorj** [comment]
@bob it could be stored as `[ ['value', 'label'], ...]` , by the way.
I mean, options could be stored as a nested array , or `[{key: 1, value: 'red'}, ...]`

**Comment by Boorj** [comment]
nope

**Comment by Boorj** [comment]
😿

**Comment by bobdenotter** [comment]
We're working as hard as we can to get Bolt 4 into shape! ;-)

**Comment by Boorj** [comment]
Problem with select fields is one of the biggest problems on my sites now, because it really breaks behavior  for final users and spoils some data. 
To fix that we need to break BC - store data in other way. 
1 Can all issues about select field be grouped to one group?
2 If solution includes BC break, can we do this in v4 ?

**Comment by bobdenotter** [comment]
It's basically rebuilt in v4, so we shouldn't introduce new breakage here. Instead, focus on getting it right in v4.

**Comment by Boorj** [comment]
@bobdenotter  - glad to hear that it will be rebuilt, wonderful. Think if (when) this will be fixed, we can close this issue again. Open and close 😸
