### ISSUE TITLE
[RFC] Thumbnails pre/post processing

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7423]
Idea: make some image processing available for thumbnails.
---
Sometimes you need to watermark an image. Often it's necessary not for small thumbs, but for big images (`thumbnail(image, 1200, 600, resize)`).  

So i found the way to do it in bundle/extension.

It's initialized this way
<details><summary>MyThumbsExtension.php</summary>

```php
// Somewhere deep in extension

    public function getServiceProviders()
    {
        $app = $this->getContainer();

        $app['thumbnails.creator'] = $app->share($app->extend('thumbnails.creator', function ($creator, $app) {
            $webPath = $app['resources']->getPath('web');
             // my way for current project. It watermarks file it has img_ inside. 
            $options = [
                "watermark" => [
                    "filePath" =>  $webPath . '/i/watermark1.png',
                    "conditions" => [
                        "pattern" => '/img_/i',
                        "parameters" => [
                            "filePath" => $webPath . '/i/watermark1.png',
                        ],
                    ],
                ],
            ];
            return new Creator2($app['thumbnails.limit_upscaling'], $app['imagine.svg'], null, $options);
        }));

```
</details>

And here's the code itself
<details><summary>Creator2.php</summary>

```php
<?php

namespace Mapple\Boltstrap;

use Bolt\Thumbs\Color;
use Bolt\Thumbs\Creator;
use Bolt\Thumbs\ImageResource;
use Bolt\Thumbs\Transaction;
use Contao\ImagineSvg\Imagine as SvgImagine;

class Creator2 extends Creator
{
    /** @var  $options */
    protected $options;

    public function __construct($limitUpscaling = true, SvgImagine $svgImagine = null, Color $background = null, $options) {
        parent::__construct($limitUpscaling, $svgImagine, $background);
        $this->options = $options;
    }

    /**
     * {@inheritdoc}
     */
    public function create(Transaction $transaction) {
        $imageData = parent::create($transaction);

        $im = ImageResource::createFromString($imageData);

        try {
            $stamp = ImageResource::createFromFile( $this->options['watermark']['filePath'] );
        }
        catch (Exception $e) {
            return $imageData;
        }

        $this->watermark($im, $stamp);

        return $im->toString();
    }

    /**
     * watermark - mutates first resource (!)
     *
     * @param ImageResource $destImg    -
     * @param ImageResource $stampImg   -
     * @param int           $margeX     - horizontal margin (inactive for position === 'center')
     * @param int           $margeY     - vertical margin (inactive for position === 'center')
     * @param string        $position   -
     * @return ImageResource
     */
    public function watermark(ImageResource $destImg, ImageResource $stampImg, $margeX = 10, $margeY = 10, $position = 'right bottom'){
        /* @see http://php.net/manual/en/image.examples-watermark.php */

        $stampW = $stampImg->getDimensions()->getWidth();
        $stampH = $stampImg->getDimensions()->getHeight();

        $imageW = $destImg->getDimensions()->getWidth();
        $imageH = $destImg->getDimensions()->getHeight();

        switch ($position){
            case "bottom right" :
            case "right bottom" :
                $watermarkX = $imageW - $stampW - $margeX;
                $watermarkY = $imageH - $stampH - $margeY;
                break;

            case "top right" :
            case "right top" :
                $watermarkX = $imageW - $stampW - $margeX;
                $watermarkY = $margeY;
                break;

            case "bottom left" :
            case "left bottom" :
                $watermarkX = $margeX;
                $watermarkY = $imageH - $stampH - $margeY;
                break;

            case "top left" :
            case "left top" :
                $watermarkX = $margeX;
                $watermarkY = $margeY;
                break;

            default:
                $watermarkX = 0;
                $watermarkY = 0;
        }

        imagecopy(
            $destImg->getResource(),
            $stampImg->getResource(),
            $watermarkX, $watermarkY,
            0, 0, $stampW, $stampH
        );
        return $destImg;
    }
}


```
</details>

This code changes `Bolt\Thumbs\Creator.php`, but there's a better idea. Let people use additional plugins for that.

For example, we modify original `Creator::create`
```php
   public function create(Transaction $transaction)
    {
        $this->verifyInfo($transaction);
        $this->autoscale($transaction);
        $this->checkForUpscale($transaction);
        $data = $this->resize($transaction);
        return $data;
    }
```
to this
```php
   // adding $this->preprocessor and $this->postprocessor in __construct, and then:
   public function create(Transaction $transaction)
    {
        $this->verifyInfo($transaction);
        $this->autoscale($transaction);
        $this->checkForUpscale($transaction);

        if ($this->preprocessor) {
            $data = $this->preprocessor($transaction);
            $data = $this->resize( $data ) ;
            // resize is polymorphic and accepts $data and $transaction, or 
            // we can split it
        }
        else {
            $data = $this->resize($transaction);
        }

        if ($this->postprocessor) {
            // if we have postprocessor - apply to resized image
            $data = $this->postprocessor($data); 
        }

        return $data;
    }

```
(read comments in code).

If we will have processor options and we can $app->share($app['thumbnails.creator'],...) by adding pre/post processing options - it will allow us to extend Thumbnails.

### Case
Let's assume we want to add watermarks.
Preprocessors is useful if you know the _original size_ and you have one size watermark. You add watermark to original, then resize, then return resized image in `Bolt\Thumb\Controller` response.
Postprocessors if you know the _final size_ of image and you don't want to resize the watermark stamp. So you know final resolution (1200×800px) and just stamp your image on photo and return.

#### problem
Access to original files is not restricted in current setup.
So you can
1. **restrict it in server setup (apache http.conf, apache htaccess, nginf config)**
2. **upload outside web root (`/public/`)**
  this needs a special controller to upload, set permissions for editors, add backend pages. 
3. **make secret path**
  like `/public/very_secret_path12378923/secret_folder` and then provide all processed thumbnails from that path. This is not bullitproof option, for an example: if you send a link to one of those files via skype or other messagers, bingbot will parse that image and put to index. Anyway, access will not be 100% secure. 

Feel free to suggest something else.

#### problem solution
Option 2 Looks good to me. Any way we'll need a distinct controller, which allows us to upload to secret folder. And then, we can safely upload anything we want. Here's the [example in Boltforms](https://github.com/bolt/boltforms/blob/4.2/src/Controller/UploadManagement.php) (thanks to @rossriley for referencing it).

So .. the easiest way to me is:

Suggestion
---
#### provide a runway for processors:
- create `$app['thumbnails.preprocessors']` and $app['thumbnails.postprocessors']. Too queues for processing. Probably with priority. Or we can join that to one queue and have positive and negative priorities (10, -10). Thumb resize will have 0 priority
- initialize `Bolt\Thumbs\Response` inside `ThumbnailsServiceProvider` with those pre/postprocessor queues. `[ { priority : -10 /*default, optional*/ ,   function processor1  } ]
- Here's an idea for processor interface:
    ```php
    function processor1(ImageResource $im, Transaction $transaction) {
        if (preg_match(..., $transaction->requestPath, ...)) {
          // watermark here, change colors.
        }
       return $im;
    }

    ```
    It gets original file data (in transaction), and it gets an image resource in bolt's `ImageResource` format. 
    Notice, that it gets file data from original `Creator`, it doesn't read file from disk.

This explains how it could work _without_ security restrictions.

#### security
If user did set up an option for _secure storage_ in `config.yml`, for example `config.thumbnails.secure_storage: 'root/secure_files'` we can add SecureStorageProvider, which
- creates backend route+page with filemanager (or adds folder to current filemanager)
- In `ThumbnailsProvider` we tell `Bolt\Thumb\Response`, that "if we have request for this pattern (like `/thumbs\/.*\/secure_file/` " - take data from secured folder.

Bonus
---
- We can make watermarking as default function in `Bolt\Thumbs` . And turn it to queue by string options (not passing a function parameter). For example in `config.yml`
```yml
thumbnails:
    alias:
        wtrmrk: {resize: '800x600', stamp_image: 'files/123.png' }
# OR 
    # first we add watermark to original (priority 100 goes BEFORE resizing)
   processors: 
    - builtin_processor_name: 'watermark'
      prority: 100
      options:
          stamp_image: 'files/123.png'
          margin: [10, 10]
          position: 'bottom left'

    # then we desaturate resized image (prority -100 goes AFTER resizing)
    - builtin_processor_name: 'blackandwhite'
      prority: 100
      options: ~
# or 
    # syntactic sugar with string parameters
    processors: ['blackandwhite', {name: watermark, file: 'files/123.png'}] 

```

- Also, we can make aliases for special secured folders. Like `/thumbs/photos/image123.jpg` will give you watermarked *resized* to 1000×800 image from `/web/files/special_folder/image123.jpg` or `/secure_files_not_inside_web/image123.jpg/`
    
Bonus 2
---
Secure storage in core could be a big bonus for Bolt (if server allows). If `/thumbs` are not 1-to-1 connected to `/files` - It allows later 
- to create unique filenames, for example `/thumbs/secure/1000x800r/image-fd1c2a4b6e.jpg` - if you have a controller, of course

**Comment by Boorj** [comment]
hey

**Comment by GwendolenLynch** [comment]
Closing as there is nobody stepping up to work on this. Usual stuff, if someone wants to that is welcomed.

**Comment by Boorj** [comment]
@GawainLynch - again, i was waiting for comments (!). I've done that on my local project, so i can repeat it for core.
