### ISSUE TITLE
Suggest slugify, when creating folder with filemanager

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7425]
Sometimes clients create own folders inside `/files/`. And they get used to create spaces. This will uglify its name in paths, like `/files/custom%20folder/uploaded-file.jpg`.

Suggestion
---
Maybe we can warn user (optionally, configurable in `config.yml`) about that. Modal window could be:
- ----------------------------

> You're trying to create folder with spaces. This will make urls non-friendly. We can rename the folder and all file urls will look better. `your folder` → `your-folder` 
[create with original name] [create renamed]

- ----------------------------

And this could be configured as 
- auto-rename (forced renaming without warning)
- warning
- don't annoy user

**Comment by Boorj** [comment]
@bob @GawainLynch  If you tell that it's ok - i can do that

**Comment by bobdenotter** [comment]
I would prefer - instead of an option - to just `slugify` the folder name instead. Options are "another choice that has to be made" for the user. 

I think i remember you overriding the slugify anyways, so for you it would also remain consistent.

**Comment by Boorj** [comment]
> i remember you overriding the slugify anyways

not exactly, that was about **file** upload. And this one is creating public folders that will become a chunk of full file part. like `site.com/files/folder%20name/neat-slugified-filename.jpg` . Filename is slugified without a prompt, and folder name is currently left as is, only url encoded.
So slugifying filename is easy, and slugifying new folder takes another php methods. So it's different.

But i got your answer.

### little question.
Probably, we should compare initial and final names, if the folder is renamed - **show flash message** to user, kind of "your folder was renamed". 
I imagine possible situation, when user has 50 folders in cyrillic alphabet, and creates a folder, starting with `Ш` letter. And it's slugifyed to `Sh`.  Hence it's being sorted to the top of list, and user seeks for that folder and doesn't find

**Comment by Boorj** [comment]
@GawainLynch please, don't close that, until pull request is merged 😊

**Comment by Boorj** [comment]
@bobdenotter - this topic needs several tests  to be rewritten. but it works like a charm, see the PR #7532

**Comment by Boorj** [comment]
@bobdenotter - this topic needs several tests to be rewritten. but it works like a charm, see the PR #7532

**Comment by bobdenotter** [comment]
You've mentioned the tests before.. I don't think I have time to do this for v3, as i'm focusing most of my time on v4. If you write tests, and they're working, i'll happily merge them in, but I think there's a slim chance that somebody else will write the tests for you.

**Comment by Boorj** [comment]
can you put keep tag?
