### ISSUE TITLE
Officially "unsupport" IE

### ISSUE THREAD

**Issue by SvanteRichter** [bolt/bolt#7432]
Currently we have IE support "officially", but it does not really work, at least the search and tag select fields are broken since we bumped up select2 to 4.0.6-rc2 (and before that we broke it for a few months too), and since that project has not had any real activity since Nov 11 I think it is time to accept that we do not support IE(10/11) and will not be able to in any foreseeable future.

The only changes (git-wise) we will need to be for https://docs.bolt.cm/3.4/getting-started/requirements#browser-requirements

If we do instead decide to support IE10/11 as was discussed in #5676 we will probably need to do the work ourselves to fix select2 for those legacy browsers.

*NOTE: This does not apply to Edge, only to IE. IE is considered legacy even by microsoft. It also only applies to the backend, the frontend can support IE 6 if it wants.*

**Comment by SvanteRichter** [comment]
Also, just to add, IE support was intentionally removed in #7048, so this is just an issue to make it "official".

**Comment by bobdenotter** [comment]
We bumped it to 4.0.6 because in my tests it worked on IE. if it doesn’t, we should fix that.

I am very against dropping IE support in Bolt 3.x

**Comment by bobdenotter** [comment]
This is where I bumped it from 4.0.0 to 4.0.6-RC: #7199

Yes, I know select2 is crappy, and we'll certainly get rid of it in Bolt 4. And I suppose we'll drop support for IE in v4 as well.

**Comment by SvanteRichter** [comment]
Alright, I just tested on 3.4.7 which includes 4.0.6-rc.1, and neither tags nor omnisearch works, so I guess we'll have to revert to 4.0.0 again.

EDIT: Oh, and the "IE support was intentionally removed in #7048" comment was just me misreading that as merged and misunderstanding the "C'est la vie" comment

**Comment by bobdenotter** [comment]
Hmm, maybe we _should_ indeed revert back to 4.0.0 then. :-/

**Comment by bobdenotter** [comment]
Note to self: make sure downgrading Select2 doesn't break #7272.
