### ISSUE TITLE
Image uploading error

### ISSUE THREAD

**Issue by linc01** [bolt/bolt#7450]
Fresh installation with postgresql10. When the first time I uploaded an image in the home page section, I saw this exception.

Uncaught Exception: InvalidFieldNameException .
InvalidFieldNameException in AbstractPostgreSQLDriver.php line 72: 
An exception occurred while executing 'SELECT min_value, increment_by FROM "bolt_authtoken_id_seq"':

SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "bolt_authtoken_id_seq"
^
Reload page not work. Go back and login again you can find the image already there. Then you can't upload another image.

Actually, it happens everywhere when you upload images.
 

Details
-------

 - Relevant Bolt Version: [3.5]
 - Install type: [ Zip/tarball install]
 - PHP version: [7.0]
 - Used web server: [ Apache]
 - For UX/UI issues: [ chrome 65.0.3325.209(64bit)]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by bobdenotter** [comment]
Hi, Postgres 10 is fairly new, and support for it was only added in Doctrine DBAL 2.7. See here: https://github.com/doctrine/dbal/releases/tag/v2.7.0

DBAL 2.7 requires php7.1, so to fix this, you can update PHP to 7.1 or 7.2, and then run `composer update`. This will then pull in `doctrine/dbal` 2.7, and it should work.

**Comment by linc01** [comment]
Thank you!
