### ISSUE TITLE
Browse Server button always shows the 'Stack'

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7452]
Even when `config.yml` has the stack turned off, when you use the 'Browse Server' button inside an HTML field (CKEditor) you get the 'Stack' tab, as seen here:

![2018-04-28 19-38-07](https://user-images.githubusercontent.com/1833020/39402700-c102bed2-4b1b-11e8-94b4-37113683b9e7.png)

 

Details
-------

 - Relevant Bolt Version: [ 3.5 ]
 - Install type: [ Zip/tarball install | Composer install | GitHub checkout ]
 - PHP version: [ 7.2 ]
 - Used web server: [ Apache ]

**Comment by GwendolenLynch** [comment]
Fixed in #7454
