### ISSUE TITLE
Field name is embed but there is also one as oembed

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#7460]
Field name 'oembed' was renamed to 'embed' here:

- Rename use of 'oembed' to 'embed'
https://github.com/bolt/bolt/commit/f987db921007f13ac2077bd62859b0fea3384823#diff-57925474ed287183120373e5e8c7a024

It involved language files too. All fine!

But there has been a regression or a bad merge and now the 3.5 branch has ` oembed: |` in infos.en_GB.yml from 
- Added translation strings for OEmbed field
https://github.com/bolt/bolt/commit/dcd2d690552477855485808c0fb0b4497cfc269b

So now the name from 3.5 is `oembed` in infos.en_GB.yml and `embed` in messages.en_GB.yml
https://github.com/bolt/bolt/blob/3.5/app/resources/translations/en_GB/infos.en_GB.yml#L28
Note: using 3.5 bolt config/translation it seems that `oembed` is in use for infos.en_GB.yml

Details
-------
 - Relevant Bolt Version: [ 3.5 ]

**Comment by GwendolenLynch** [comment]
> But there has been a regression or a bad merge

Neither. The file was not included in that commit.

**Comment by horus68** [comment]
Sorry, the oembed was from this commit (edited above) https://github.com/bolt/bolt/commit/dcd2d690552477855485808c0fb0b4497cfc269b

The question is: the field name in infos.en_GB.yml is to be `oembed`?

**Comment by GwendolenLynch** [comment]
No, `oembed` is wrong. Feel free to PR
