### ISSUE TITLE
[RFC] rfc7762 CSP inline script nonce

### ISSUE THREAD

**Issue by dhalucario** [bolt/bolt#7469]
I have following Issue: When I wanna access the site logged in I get CSP related errors because the inline-scripts do not have a nonce I could include in my headers on my NGINX server.

Details
-------

 - Relevant Bolt Version:[ Composer says 3.5 ]
 - Install type: [ Zip/tarball install (original install)| Composer install (moved onto new server) ]
 - PHP version: [ 7.2 ]
 - Used web server: [ Nginx ] version [ nginx/1.14.0 (Ubuntu) ]
 - For UX/UI issues: [ 59.0.2 ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

If you install Bolt on an server and the server is using CSP Headers you are not able to allow the inline scripts Bolt is using while you are logged in in the front-end. The problem is that a nonce is needed to allow these in the headers.

### Specifics

You can go to any page using Bolt 3.5 on the front-end while being logged in.
The Server is installed as ZiP Install/Composer as explained above.
Im running the currently newest version of Firefox (59.0.2) and havent check in other browsers since this should be happening on any browser supporting CSP-Headers.

The error messages are in german but I guess everything is properly explained.
```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: /*<![CDATA[*/        Sfjs = (function() ....
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: /*<![CDATA[*/    (function () {         ....
```

### Steps to reproduce

1. Install Nginx on Linux.
2. Create a Bolt installation and add CSP-Headers to the headers in nginx.
```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self'; frame-src 'none'; font-src 'self'; connect-src 'self'";
	add_header X-Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self'; frame-src 'none'; font-src 'self'; connect-src 'self'";
	add_header X-WebKit-CSP "default-src 'self'; script-src 'self' 'unsafe-eval'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: ; media-src 'self'; frame-src 'none'; font-src 'self'; connect-src 'self'";
```
3. Set everything up, log in, check the starting page (while being logged in)
4. Check browser console for errors.

### Expected result

The script tag should include a nounce attribute as follows:

```
<script nonce="2726c7f26c">...</script>
```

### Actual result

```
<script>...</script>
```

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: /*<![CDATA[*/        Sfjs = (function() ....
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: /*<![CDATA[*/    (function () {         ....
```

**Comment by GwendolenLynch** [comment]
What happens when you set `debug: false` in your `config.yml`?

That looks very much like the Symfony Debug Toolbar that is causing that.

**Comment by dhalucario** [comment]
Did that, now the error is gone. Is there a way we can get the nonce though?

**Comment by GwendolenLynch** [comment]
Yes, but it was a PITA the last time I looked and to be honest I can't remember without digging how I did it with that.

**Comment by dhalucario** [comment]
I think they implemented it since then. When I find some time in near future I will try to add this myself and create a pull request.

**Comment by GwendolenLynch** [comment]
That would be great if you can.
