### ISSUE TITLE
allowtwig: true has no effect when html is saved

### ISSUE THREAD

**Issue by jhwsys** [bolt/bolt#7481]
Using allowtwig: true to allow embedding twig tags in html source via ckeditor works when the page is previewed but not when it is saved and viewed normally. In the latter case the tags are escaped; i.e ```{{``` becomes ```%7B%7B```. 

Details
-------

 - Relevant Bolt Version: 3.5.0
 - Install type: Zip/tarball install
 - PHP version: 7.2.3
 - Used web server:  Apache
 - For UX/UI issues: n/a
 - Database: SQLite

Reproduction
------------

### Bug summary
Twig tags inserted into html using ckeditor in source mode are escaped when the code is saved in the database. Even when **allowtwig: true** set in relevant html field definition.

### Specifics
Bolt version 3.5.0 using SQLite database.
Browser not relevant.
No extensions created or installed.
On direct inspection of database contents it is seen that ```{{``` has been stored as ```%7B%7B```

### Steps to reproduce
1. Set ```allowtwig: true``` on ```pages.fields.body``` in contenttypes.
2. Create/edit a page source in ckeditor containing .e.g. 
```<img alt="Sacred Monogram of the Blessed Virgin, symbol of Saint Mary's Church Woodbridge Suffolk" src="{{asset('2018-05/monogram.jpg','files')}}" style="float: left; margin-right: 1em; width: 87px; height: 108px;"/>```
3. Preview page - gives expected (correct) result below.
4. Save page then view via normal url - gives actual result below.

### Expected result
```<img alt="Sacred Monogram of the Blessed Virgin, symbol of Saint Mary's Church Woodbridge Suffolk" src="{{asset('2018-05/monogram.jpg','files')}}" style="float: left; margin-right: 1em; width: 87px; height: 108px;" />```
### Actual result
```<img alt="Sacred Monogram of the Blessed Virgin, symbol of Saint Mary's Church Woodbridge Suffolk" src="%7B%7Basset('2018-05/monogram.jpg','files')%7D%7D" style="float: left; margin-right: 1em; width: 87px; height: 108px;" />```

**Comment by jhwsys** [comment]
# Update
Further tests reveal that this problem occurs when twig tags are embedded in html url-type attributes such as ```src``` and ```href```. Twig tags embedded elsewhere in html work fine. Also, although ```{``` and ```}``` are encoded, ```#``` and ```%``` are left untouched.

This still leaves a problem because it prevents the use of e.g. the automatic cache-busting of the ```asset()``` function.

# Workaround
In twig template file
Define macro:
```{% macro tags(string) %}```
```{{include(template_from_string(string|replace({'%7B%7B': "{{", "%7D%7D" : "}}"})))}}```
```{% endmacro tags %}```

Use macro (example):
```{{ macros.tags(record.body)}}```

**Comment by cdowdy** [comment]
I posted a similar question to slack on July 13, 2017 ...

here is a gif I posted https://boltcms.slack.com/files/U0P1V3CE7/F68HGKDT7/pastedcode-3.gif

this was the contenttype setup with the options that @bobdenotter told me too add https://boltcms.slack.com/files/U0P1V3CE7/F68CH5HRR/ct-allow-twig.png

Mine was "breaking" in code blocks with encoded or non encoded entities but this was also a different version of bolt
