### ISSUE TITLE
Problems with translations

### ISSUE THREAD

**Issue by RodrigoBalest** [bolt/bolt#7484]
When using Bolt with my language (pt_BR), there are some issues on the buttons/links translations related to content types. The problem can be better understood at the _Expected results_ section below.

 

Details
-------

 - Relevant Bolt Version: 3.5
 - Install type: Composer install
 - PHP version: 7.2
 - Used web server: Apache version 2.4.33 (Ubuntu)

Reproduction
------------

### Steps to reproduce

Edit _contenttypes.yml_, translating some content types' names. Eg. change:
```
pages:
    name: Pages
    singular_name: Page
```
to
```
pages:
    name: Páginas
    singular_name: Página
```
and 
```
blocks:
    name: Blocks
    singular_name: Block
```
to
```
blocks:
    name: Blocos
    singular_name: Blocos
```

Also, change `locale` to `pt_BR` in `config.yml`

### Expected result

In the dashboard, hover over *Páginas* at the content menu. The shown options are:
* Visualizar Páginas
* Nova Página

Click *Nova Página*. The page title is also *Nova Página*.

### Actual result

Instead of _Nova Página_, _Novo Página_ is shown.

Note that editing ```contenttypes.generic.new:``` to _Nova %contenttype%_ won't solve the problem, because other content types would then be wrong (_Novo Bloco_ is right, but _Nova bloco_ is wrong).

This happens because in portuguese grammar those words differ in gender: _Página_ is a female word, while _Bloco_ is a male word.

What should be done to circumvent this problem?

**Comment by bobdenotter** [comment]
This is not something that we can feasibly fix, i'm afraid. It has to do with the fact that english doesn't have genders for nouns, so we can't distinguish between them (same goes for Dutch, French or German). In Bolt 4, we'll re-do the translation engine, and hopefully we can fix it then.

**Comment by RodrigoBalest** [comment]
Ok.
I'll change *Novo* to *Criar* (Create) on the translations, since verbs doesn't have genders in portuguese.
I think it will suffice.
Thanks!!
