### ISSUE TITLE
Bolt 3.4.9 page layout goes rough with inner block

### ISSUE THREAD

**Issue by motivecodex** [bolt/bolt#7492]
On Bolt 3.4.9 the page layout goes rough when using blocks inside of another block or blocks inside of a repeater. 

![screenshot-2018-5-22 idea erstellen bolt](https://user-images.githubusercontent.com/2242015/40354445-2d7b9d5e-5db4-11e8-99bd-9d4e57e462b5.png)

**Comment by GwendolenLynch** [comment]
That is due to blocks and/or repeaters not being supported for use inside other blocks/repeaters.

See https://docs.bolt.cm/fields/block

**Comment by bobdenotter** [comment]
https://media.giphy.com/media/RgaVJ150nYExi/giphy.gif

**Comment by bobdenotter** [comment]
![](https://media.giphy.com/media/RgaVJ150nYExi/giphy.gif)

**Comment by motivecodex** [comment]
Is this reality, or is this fantasy?
