### ISSUE TITLE
[RFC] Extended theme configurations

### ISSUE THREAD

**Issue by curtchan** [bolt/bolt#7499]
Won't it be good to have... more tailored, ready-to-use out of the box themes?
As someone who is still learning about Bolt, but has a lot of experience in WP, i was actually suprised that the themes in Bolt feel quite limited.

But what all the fuss about? I was searching through available Bolt Themes to see how they solved their own problems, and came to conclusion that a lot of them... solve them on their own - randomly, each inventing wheel by themselves.

Simple example: Header/Banner image. There is tons of themes that come up with it, but the real issue is that they are very uncomfortable to configure (from a basic User side, we devs can just open code and edit anything without worrying about breaking the whole website). And how could we make it easier? Well, there comes time for discussion.

In WP we have (let's call it) Personalisation configurations. Where we can edit basic things, or even allow end-users to have textareas for their own CSS, JS scripts, all definiable from-inside theme.
How we could add it into Bolt? Well, we can already define basic things in theme.yml, which in my opinion needs more rework. But how about allowing Developers to define their own customtypes inside theme? To limit unnecessary havoc, we could limit it to just singleton types that would allow for defining basic configuration options like - let's say - banner image.
More pros of such solution? For example the images defined (uploaded) that way could make use of twig and other extensions manipulation instead of being left there hardcoded inside themes...

Looking forward for your opinions and comments.

And yes, i already considered adding such functionality with extra extension but... That totally doesn't solve the problem - Theme still won't be usable out-of-the-box with that methodology.

**Comment by SvanteRichter** [comment]
Bundling contenttypes in themes has been discussed, and IIRC nobody was really against it, but it has never been implemented.
