### ISSUE TITLE
[RFC] haveibeenpwned integration for backend login / user admin pages

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#7500]
It seems it is possible to add a simple query to the api of haveibeenpwned on login forms. 
https://github.com/OktaSecurityLabs/passprotect-js - Use of previously pwned passwords will then be discouraged.

More information on what happens: https://www.troyhunt.com/pwned-passwords-in-practice-real-world-examples-of-blocking-the-worst-passwords/

Do we want it in Bolt too?

Details
-------
 - Relevant Bolt Version: 3.5 | master

**Comment by bobdenotter** [comment]
We already have this: https://github.com/bolt/bolt/blob/3.6/app/view/twig/firstuser/firstuser.twig#L88-L94

They say `passprotect-js` is secure, but regardless of whether that is true, I assume a ton of people will object to adding a functionality to password fields that's basically a benign keylogger.

**Comment by jadwigo** [comment]
This script does not send the password anywhere - it only sends the first 5 or 6 charaters of the sha-1 hash. Locally the full sha-1 hash is compared to the api result.

Yup, you could call it's a _benign_ keylogger, and the same goes for the bolt back-end itself, because that uses the hashed password too.

The API is very simple, we could also make a custom script to do that if we don't want to use a third party script for this.

**Comment by curtchan** [comment]
IMO good idea, but seems more suitable for extension rather than core element of bolt.

**Comment by scotteuser** [comment]
FYI, I've created this as an extension, extending the default Bolt login class to add this additional password policy option:
https://market.bolt.cm/view/scotteuser/passwordhaveibeenpwned

**Comment by scotteuser** [comment]
It's worth noting that with V2 of the API, the code doesn't actually send the password: just the first 5 characters of a hash (not the bolt hash) and it returns hundreds of possible hashes which it then compare against server side.
