### ISSUE TITLE
Save button does not work sometimes

### ISSUE THREAD

**Issue by nestordedios** [bolt/bolt#7512]
Hi everyone!

It seems the Save button sometimes does not work when saving a record.

It is not easy to reproduce but I have managed several times. The way I have done it is: 

- Install a fresh Bolt v3.5.3.
- Prefill Database with 10 record of each default Contenttype.
- Open the prefilled record in several Tabs and wait for some time.
- After a minute or 2 start pressing the Save button of each opened Record. Most of the times the save action goes through but sometimes it does fail and the "Saved on" datetime message is not updated anymore.
![capture](https://user-images.githubusercontent.com/6607455/41109861-4eb6907a-6a78-11e8-9a8b-37e5abc31e8f.PNG)

I have noticed that when the Record is not saved the `Content-Type` Response Header is: `text/html` and when it works the Response Header is `Content-Type: application/json`.

Here the preview when it doesn't work:

![capture2](https://user-images.githubusercontent.com/6607455/41110351-73a0db74-6a79-11e8-9c07-f638c108dd93.PNG)

Here the preview when it works:

![capture3](https://user-images.githubusercontent.com/6607455/41110389-8300c066-6a79-11e8-888e-039b60cbcdb6.PNG)

Details
-------

 - Relevant Bolt Version: 3.5.3
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache

**Comment by GwendolenLynch** [comment]
OK, so this is just a race.

Basically, if you open the tabs **slowly** (i.e. let it finish load/render) and then open the next — or, refresh an existing one — everything repeatedly works fine:
- Initially: Tabs 1 to 9 fail, tab 10 works
- Refresh/reload: Tabs 1-10 work

It is all to do with the CSRF token.

So, if the form token exists in the current persistent session data, all 10 tabs can be open at the same time and will get the correct token value … Duh!

However, if there is no current valid token it is **created during the request** … and **saved in the terminate event** … 'cause performance.

What we have is _n_ number of requests all creating new form tokens in session, and the last request to terminate event is almost certainly always going to be the one to save the token.

**Comment by GwendolenLynch** [comment]
Oh, and in case the "obvious" is just in my own head, the invalid token means the form fails validation — as it should — and a full page render is returned instead of the JSON, as further POST handling is skipped at that point, also a wanted outcome.

**Comment by bobdenotter** [comment]
> However, if there is no current valid token it is created during the request … and saved in the terminate event … 'cause performance.

Sounds plausible. 

Is it something we can improve? (ie. creating and saving it immediately?)

**Comment by GwendolenLynch** [comment]
I'm out of ideas myself. But … It is an edge-case, and doing the save during the request will hurt everyone.

For those really bothered by it, they can take their site in their own hands and disable CSRF protection :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
Could we have the 'overview' controller/page trigger the generation of a valid token, if there isn't one?  If we can do that, it'll most likely circumvent this issue.

**Comment by GwendolenLynch** [comment]
Yes, make the overview Form based :stuck_out_tongue_winking_eye: 

It might work for most of the time this is hit, but not all.

**Comment by bobdenotter** [comment]
“Most” would make the case much edgier, and we all strive to be edgy, right? 😉

**Comment by GwendolenLynch** [comment]
Well given this is the first report of it in 6 years, I'd say it is already pretty edge case :wink:
