### ISSUE TITLE
Missing "View (saved version) on site"

### ISSUE THREAD

**Issue by hannesl** [bolt/bolt#7535]
In Bolt 2.x there was the option to view the saved version of a post by clicking the arrow next to the Preview button (there's an image in [this old issue](https://github.com/bolt/bolt/issues/4342)).

In 3.5 the button only does "Preview", and there is no way that I can find of jumping to the saved version of the post in the frontend. Users complain that they have to search for content in the frontend because of this while they used to be able to just follow the link.

Is this a change that was made on purpose?

Details
-------

 - Relevant Bolt Version: 3.5
 - Install type: Composer install
 - PHP version: 7.2
 - Used web server: Apache 2.4.18
 - For UX/UI issues: Chrome 66 (prolly not relevant)

**Comment by GwendolenLynch** [comment]
Do you mean like this one?
![screenshot from 2018-06-18 14-33-18](https://user-images.githubusercontent.com/1427081/41536005-9004d14c-7304-11e8-8474-04291685d789.png)

Just a quick sanity check, the record is published?

**Comment by bobdenotter** [comment]
@hannesl The button for 'view saved version' is not shown if the contenttype is `viewless`.

**Comment by hannesl** [comment]
Thanks for responding so quickly! I'll look into it more deeply then – I was too quick to assume that it was just missing functionality. I've done some custom stuff with routing/controllers so maybe there's something going on there. The content type is not viewless.

**Comment by hannesl** [comment]
OK, so in `_aside-preview.twig` there are references to the `contentlink` route in `routing.yml`. I have disabled this route and instead rely on custom routes for different content types.

If I change this:

    {% if context.content.status == "published" and context.content.link is defined and 'contentlink' in config.get('routing')|keys %}

to this:

    {% if context.content.status == "published" and context.content.link is defined %}

and remove this:

    {% set placeholder = path('contentlink', {'contenttypeslug': context.contenttype.singular_slug, 'slug': '__replaceme'}) %}

– then it works, but the `data-href-placeholder` attribute on the link will be empty. I figured out that this breaks the link when editing posts, since there is JS code that tries to regenerate `href` based on `data-href-placeholder` after each save. I guess the real solution to this is to include the href to the post from the backend when saving so that the JS code can use that instead.

Does this sound reasonable?

**Comment by bobdenotter** [comment]
~@hannesl Did you remove the `contentlink` route from `routing.yml`?~ 

 Edit: Ah, yes.. You did. Short answer: You shouldn't. Removing _other_ code from the Bolt core to make your specific workflow work, won't be good for other users. 

The easiest "fix" is to not remove the `contentlink` route, because there shouldn't be any drawbacks to keeping it intact. Just move it _down_ a bit, if you want to make it low priority.

**Comment by hannesl** [comment]
That seems to work, thanks!

The only downside is that there are now two active URLs for the same posts, but I can live with that. The Canonical meta tag should prevent any SEO issues.
