### ISSUE TITLE
Nested arrays in RequestSanitiser cause ContextErrorException

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7540]
When you suddenly delete any required route from `routing.yml` (like `'homepage'`), on the login page you get a non-informative error:
![image](https://user-images.githubusercontent.com/2145313/41989404-674a1a5c-7a69-11e8-91cb-5f2c6fa44017.png)
When you put routes back - it works ok. This refers to #7175 . 

1. Can we detect those missing required routes and show more informative error?
2. Can we make a fallback for `homepage`, if those pages are missing? And, probably, show warning. Actually, those routes are necessary only for generating urls. It even doesn't need for controller action to exist. Only mapping `routeName => path`. Sooooo... we can make fallbacks to allow people to exist without those unused routes.

**Comment by Boorj** [comment]
Also the same problem appeared, when i was trying to access database folder without permissions.
![image](https://user-images.githubusercontent.com/2145313/42081001-82f2590e-7bae-11e8-81a7-2dc89ba70f66.png)


## Where the problem is
in incorrect implode of associative array.
![image](https://user-images.githubusercontent.com/2145313/42081871-c98f87c2-7bb0-11e8-81da-ad42905a391e.png)

In [`RequestSanitiser.php`](https://github.com/bolt/bolt/blob/3.5/src/Helpers/RequestSanitiser.php#L49) we're trying to implode several parameters, and one of them is not a string but a nested array.

I don't know usage cases, so i can't fix that properly. What will @GawainLynch (an author if that class) say?

**Comment by bobdenotter** [comment]
If I remove the `homepage` route, I get the following error: 

![screen shot 2018-07-14 at 12 53 10](https://user-images.githubusercontent.com/1833361/42723768-e132d798-8764-11e8-8320-00d03beec50b.png)

This is different from what you've posted, and it does explain what the issue is, right? (ie. "don't remove the homepage route"). 

Can you still reproduce this?

**Comment by Boorj** [comment]
@bobdenotter i think that was because of several reasons, one of them was missing route. BUT problem that caused error shown on screenshot was incorrect `chmod` access rights on linux folder. So this is still a bug.  See the 2nd comment with screenshot.

### repro:
Try to lock database folder, and you'll get that `RequestSanitiser` problem. Stack trace is on the 2nd screenshot above.

---

Anyway, i made a PR which fixes that. Looks like it's ok.

**Comment by Boorj** [comment]
try to remove access to database folder, maybe that helps to reproduce?
