### ISSUE TITLE
Incorrect replace in excerpt

### ISSUE THREAD

**Issue by psanchezg** [bolt/bolt#7541]
When entering multiple space characters or adding it to the end in searching, the replacement of terms is incorrect for excerpt function.

Details
-------

 - Relevant Bolt Version: 3.x
 - PHP version: 7.0 | 7.1
 - Used web server: Apache | Nginx

Reproduction
------------

Add and space at the end of a search.

### Patch
```
diff --git a/src/Helpers/Excerpt.php b/src/Helpers/Excerpt.php
index 18f3fcffe..d49c58c55 100644
--- a/src/Helpers/Excerpt.php
+++ b/src/Helpers/Excerpt.php
@@ -253,7 +253,9 @@ class Excerpt
 
         // Highlight the words, using the `<mark>` tag.
         foreach ($words as $word) {
-            $relText = preg_replace('/\b(' . preg_quote($word, '/') . ')\b/i', '<mark>$1</mark>', $relText);
+            if ($word) {
+              $relText = preg_replace('/\b(' . preg_quote($word, '/') . ')\b/i', '<mark>$1</mark>', $relText);
+            }
         }
 
         return $relText;

```

**Comment by bobdenotter** [comment]
Hi, 

Can you give an example of how it goes wrong? I assume it'll introduce a bunch of "empty" `<mark>` tags, but that shouldn't give a visual malfunction, right? 

Other than that: Feel free to make a PR for this fix, so we can merge it in. 👍

**Comment by psanchezg** [comment]
This is the html output of a new 3.5.4 site with Dummy Content generated
Just add a final space in your search.

`<p><mark></mark>�<mark></mark>��<mark></mark>est<mark></mark>, <mark></mark>et<mark></mark> <mark></mark>quod<mark></mark> <mark></mark>externum<mark></mark>, <mark></mark>id<mark></mark> <mark></mark>in<mark></mark> <mark></mark>casu<mark></mark> <mark></mark>est<mark></mark>.    &lt;<mark></mark>mark<mark></mark>&gt;<mark></mark>Lorem<mark></mark><!--<mark-->mark<mark></mark>&gt; &lt;<mark></mark>mark<mark></mark>&gt;<mark></mark>ipsum<mark></mark><!--<mark-->mark<mark></mark>&gt; <mark></mark>dolor<mark></mark> <mark></mark>sit<mark></mark> <mark></mark>amet<mark></mark>, <mark></mark>consectetur<mark></mark> <mark></mark>adipiscing<mark></mark> <mark></mark>elit<mark></mark>. <mark></mark>An<mark></mark> <mark></mark>tu<mark></mark> <mark></mark>me<mark></mark> <mark></mark>de<mark></mark> <mark></mark>L<mark></mark>. <mark></mark>Quae<mark></mark> <mark></mark>animi<mark></mark> <mark></mark>affectio<mark></mark> <mark></mark>suum<mark></mark> <mark></mark>cuique<mark></mark> <mark></mark>tribuens<mark></mark> <mark></mark>atque<mark></mark> <mark></mark>hanc<mark></mark>, <mark></mark>quam<mark></mark> <mark></mark>dico<mark></mark>. <mark></mark>An<mark></mark> <mark></mark>eiusdem<mark></mark> <mark></mark>modi<mark></mark>? <mark></mark>Ex<mark></mark> <mark></mark>quo<mark></mark>, <mark></mark>id<mark></mark> <mark></mark>quod<mark></mark> <mark></mark>omnes<mark></mark> <mark></mark>expetunt<mark></mark>, <mark></mark>beate<mark></mark> <mark></mark>vivendi<mark></mark> <mark></mark>ratio<mark></mark> <mark></mark>inveniri<mark></mark> <mark></mark>et<mark></mark> <mark></mark>comparari<mark></mark> <mark></mark>potest<mark></mark>. <mark></mark>Non<mark></mark> <mark></mark>est<mark></mark> <mark></mark>enim�<mark></mark>��</p>`
