### ISSUE TITLE
Search does not close `<mark>` tags properly when ending in trailing space

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7546]
When you search for keywords, and have a trailing space, the `<mark>` does not perform correctly.

Details
-------

 - Relevant Bolt Version: [ 3.3 | 3.4 | 3.5 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 | 7.x ]
 - Used web server: [ Apache | Nginx ] version [ version ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

- Install Bolt
- Pre-fill content
- On the front-end, search for `"lorem "` (with a space at the end)
  - In the URL, you should see `/search?search=lorem+` (with a `+` at the end)

### Bug summary

A trailing space messes up the search results. `<mark>` is not closed properly because it attempts to `<mark>` a space.

### Expected result

When searching `"lorem"`:

![lorem](https://user-images.githubusercontent.com/4630335/42156508-89af74d6-7deb-11e8-9765-e2c6beab0f0b.png)

### Actual result

When searching `"lorem "`:

![lorem+](https://user-images.githubusercontent.com/4630335/42156505-87a2682e-7deb-11e8-862a-c04b3407721d.png)

See the generated HTML source:

![mark](https://user-images.githubusercontent.com/4630335/42156888-8829e6a4-7dec-11e8-9654-913edbc07575.png)

**Comment by GwendolenLynch** [comment]
Can you test with `3.5-HEAD` as there was #7542  merged yesterday-ish

**Comment by xiaohutai** [comment]
Oh, totally missed that one. I think that's the same issue.

Yeah, I'll test it with HEAD 👍

**Comment by xiaohutai** [comment]
@GawainLynch Indeed. Fixed in `3.5-HEAD`.
