### ISSUE TITLE
[BUG] title_format not working (possibly a regression)

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7548]
Details
-------

 - Relevant Bolt Version: [ 3.5.3, 3.5.4 ]
 - PHP version: [ 7.2 ]
 - Used web server: [ Apache ]

### Bug summary

`title_format` has no effect

### Steps to reproduce

Add `title_format: [ title, description ]` or `title_format: [ description ]` or `title_format: [ description, title ]` and go the the backend list view of record, the display won't change

### Expected result

Fields displayed according to `title_format`

### Actual result

Fields are always displayed using Bolt's defaults

**Comment by eduardomart** [comment]
It does appear that this is related to the field explicitly being named `title` as you mentioned in Slack, @bobdenotter. It does work with other fields as expected.

However, as long as the field named `title` exists in the contenttype defs, `title_format` will not work at all, renaming the field is not an ideal solution because if you have records already saved under this contenttype you have to edit the database directly, or start over with a new contenttype that doesn't have a field named `title`.

**Comment by eduardomart** [comment]
Also (I hate to be the nitpicker) expanding on this a little bit, it'd be nice if the fields that are being used in the title are skipped in the 'excerpt' portion of the backend list view.

For example if I have a contenttype with 'year', 'tagline', 'about' fields and  do this:
`title_format: [ tagline ]`

The backend list will display something like this:
[id] [ **<u>this is my tagline</u>** 2017 this is my tagline this is my about box ]

**Comment by enthus1ast** [comment]
still an issue with 3.6.9
as eduardomart stated out it seems to work only when `title` is not present
