### ISSUE TITLE
[Symfony\Component\Debug\Exception\UndefinedFunctionException]   

### ISSUE THREAD

**Issue by GitHubinat0r** [bolt/bolt#7556]
A brief description of the issue goes here.
  Installation fails with the below error:

  [Symfony\Component\Debug\Exception\UndefinedFunctionException]                               
  Attempted to call function "filter_list" from namespace "Symfony\Component\HttpFoundation".  

Details
-------
 - OS: [FreeBSD 11.2]
 - Relevant Bolt Version: [ 3.5.0 | 3.5.1 | 3.5.2 | 3.5.3 | 3.5.4 | master ]
 - Install type: [ tarball install ]
 - PHP version: [ 5.6 | 7.2 ]
 - Used web server: [ Nginx ] version [1.14]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

Installed either php 5.6 or php 7.2 (with all php extensions as noted in: https://docs.bolt.cm/3.5/getting-started/requirements)
tar -xzf bolt-latest.tar.gz --strip-components=1
php app/nut init

### Specifics

Relevant Bolt Versions: [ 3.5.0 | 3.5.1 | 3.5.2 | 3.5.3 | 3.5.4 | master ]
 - Install type: [ tarball install ]

$ php app/nut init

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /usr/home/www/vendor/bolt/bolt/src/Provider/TranslationServiceProvider.php on line 87

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /usr/home/www/vendor/bolt/bolt/src/Provider/UploadServiceProvider.php on line 64

                                                                                               
  [Symfony\Component\Debug\Exception\UndefinedFunctionException]                               
  Attempted to call function "filter_list" from namespace "Symfony\Component\HttpFoundation".  
                                                                                               

Exception trace:
 () at /usr/home/www/vendor/symfony/http-foundation/ParameterBag.php:262
		
        Try to pinpoint it as much a possible
		
    /**
     * Filter key.
     *
     * @param string $key     Key
     * @param mixed  $default Default = null
     * @param int    $filter  FILTER_* constant
     * @param mixed  $options Filter options
     * @param bool   $deep    Default = false
     *
     * @see http://php.net/manual/en/function.filter-var.php
     *
     * @return mixed
     */
    public function filter($key, $default = null, $filter = FILTER_DEFAULT, $options = array(), $deep = false)
    {
        static $filters = null;
        if (null === $filters) {                                                                                                                                          
            foreach (filter_list() as $tmp) { <----- Error is here.
                $filters[filter_id($tmp)] = 1;
        }                                                                                                                                                                     } 
		if (is_bool($filter) || !isset($filters[$filter]) || is_array($deep)) {
            @trigger_error('Passing the $deep boolean as 3rd argument to the '.__METHOD__.' method is deprecated since Symfony 2.8 and will be removed in 3.0. Remove it a
            $tmp = $deep;
            $deep = $filter;
            $filter = $options;
            $options = $tmp;
        }   

### Steps to reproduce

Installed either php 5.6 or php 7.2 (with all php extensions as noted in: https://docs.bolt.cm/3.5/getting-started/requirements) Attempted to install with local as well as root account.

tar -xzf bolt-latest.tar.gz --strip-components=1
php app/nut init
(Above error appears on installation)

### Expected result

I expected to make it past the installation stage.

### Actual result

Installation failed.

**Comment by bobdenotter** [comment]
Hi @GitHubinat0r, 

`filter_list` is a built-in PHP function. See here: http://php.net/manual/en/function.filter-list.php
My firm guess is that your PHP setup is not correct, because it's missing one or more of the built-in functions.

**Comment by GitHubinat0r** [comment]
Hello @bobdenotter 

You are correct, it's my PHP installation. I should have done a simple 'hello world' php test earlier. 

Thanks for such a prompt response!

**Comment by bobdenotter** [comment]
@GitHubinat0r Glad you found it! 👍
