### ISSUE TITLE
Timed publish is triggered only once per hour. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7561]
A while ago, this popped up. I'm now adding it as a bug, so we don't forget about it: 

Setup:

 * Set up a Bolt install, with default contentypes and some dummy content. 
 * Set one item to be “timed publish”:

```sql
UPDATE `bolt_entries` SET `datechanged` = '2018-06-20 20:05:26', `datepublish` = '2018-06-20 20:05:26', `status` = 'timed' WHERE `id` = '1';
```

* Verify it’s set to timed: 

![screen shot 2018-06-20 at 20 14 44](https://user-images.githubusercontent.com/1833361/41677142-c9e0e15c-74c7-11e8-92bd-2b5afcbcc1b6.png)

* Run the cron:  `php app/nut cron --run=cron.Hourly`

![screen shot 2018-06-20 at 20 19 15](https://user-images.githubusercontent.com/1833361/41677146-ce26e298-74c7-11e8-9c53-82d859e37202.png)

* See item being published now:
 
![screen shot 2018-06-20 at 20 19 35](https://user-images.githubusercontent.com/1833361/41677151-d0db9218-74c7-11e8-8c4a-2af552b1292c.png)

* Re-set it to timed, by running that same SQL query.
* Re-run the cron:  `php app/nut cron --run=cron.Hourly`

![screen shot 2018-06-20 at 20 21 07](https://user-images.githubusercontent.com/1833361/41677156-d36ea894-74c7-11e8-8f5c-4974db7cafab.png)

* Entry will not get published, until one hour passes: 

![screen shot 2018-06-20 at 20 21 42](https://user-images.githubusercontent.com/1833361/41677167-d6a38eda-74c7-11e8-9c40-428e301444d7.png)

**Comment by GwendolenLynch** [comment]
NOTABUG, working as expected, as we discussed.

**Comment by bobdenotter** [comment]
@GawainLynch No, it's not. I showed you and you said you saw the issue, but it'd need to go into 3.6. It most certainly is not working.

**Comment by GwendolenLynch** [comment]
So, form the [event subscriber](https://github.com/bolt/bolt/blob/3.6/src/Events/CronEvent.php#L74-L81) you can see the following:

```php
    private function cronHourly()
    {
        $timedRecords = $this->app['storage.event_processor.timed'];
        if ($timedRecords->isDuePublish()) {
            $this->notify('Publishing timed records');
            $timedRecords->publishTimedRecords();
        }
        if ($timedRecords->isDueHold()) {
            $this->notify('De-publishing timed records');
            $timedRecords->holdExpiredRecords();
        }
    }
```

This means that if [`isDuePublish`](https://github.com/bolt/bolt/blob/3.6/src/Storage/EventProcessor/TimedRecord.php#L72-L75) or [`isDueHold`](https://github.com/bolt/bolt/blob/3.6/src/Storage/EventProcessor/TimedRecord.php#L80-L83) return `true` then timed publishing of that class of item is skiped

```php
    public function isDuePublish()
    {
        return !$this->cache->contains(self::CACHE_KEY_PUBLISH);
    }

    public function isDueHold()
    {
        return !$this->cache->contains(self::CACHE_KEY_HOLD);
    }
```
You can also note that during [`publishTimedRecords`](https://github.com/bolt/bolt/blob/3.6/src/Storage/EventProcessor/TimedRecord.php#L88-L94) & [`holdExpiredRecords`](https://github.com/bolt/bolt/blob/3.6/src/Storage/EventProcessor/TimedRecord.php#L99-L105) that a value of `true` is saved to cache after record publish/unpublish. 
```php
    public function publishTimedRecords()
    {
        foreach ($this->contentTypeNames as $contentTypeName) {
            $this->timedHandleRecords($contentTypeName, 'timed');
        }
        $this->cache->save(self::CACHE_KEY_PUBLISH, true, $this->interval);
    }

    public function holdExpiredRecords()
    {
        foreach ($this->contentTypeNames as $contentTypeName) {
            $this->timedHandleRecords($contentTypeName, 'hold');
        }
        $this->cache->save(self::CACHE_KEY_HOLD, true, $this->interval);
    }
```

The cache item is time limited to the config setting of [`general/performance/timed_records/interval`](https://github.com/bolt/bolt/blob/3.6/src/Provider/StorageServiceProvider.php#L300-L314) in the service provider.

Simply forcing `return true;` in either of the `isDue*()` methods will always cause the records to publish/unpublish.

Thank you for wasting my time yet again.

**Comment by bobdenotter** [comment]
The following fixes the problem on my end. Let's discuss when you're available. 

https://github.com/bolt/bolt/compare/3.6...bobdenotter:feature/add-cron-minutely-for-timed-publish?expand=1

**Comment by SvanteRichter** [comment]
Can I just what is expected in these scenarios if we assume that the cron has never run before in each of these scenarios?

---

**Scenario 1:**
 * 00:01: page/1 is set to timed publish at 00:02.
 * 00:03: The hourly cron is run, so page/1 is published.
 * 00:04: page/1 is set to timed publish at 00:05. 
 * 00:06: The hourly cron is rerun.

Outcome: Is/should page/1 published at 00:07?

---

**Scenario 2:**
 * 00:01: page/1 is set to timed publish at 00:02.
 * 00:03: The hourly cron is run, so page/1 is published.
 * 00:04: page/2 is created and set to timed publish at 00:05. 
 * 00:06: The hourly cron is rerun.

Outcome: Is/should page/2 published at 00:07?

---

**Scenario 3:**
 * 00:01: The hourly cron is run and no record is set to timed publish, so nothing is changed.
 * 00:02: page/1 is set to timed publish at 00:03. 
 * 00:04: The hourly cron is rerun.

Outcome: Is/should page/1 published at 00:05?

**Comment by bobdenotter** [comment]
In my opinion: 

Scenario 1, current outcome: Page/1 is set back to "timed" at 00:04. At 00:06 the cron 'skips' because it already ran. At 00:07, it's still set to "timed"

Scenario 1, desirable outcome: Page/1 is set back to "timed" at 00:04. At 00:06 the cron runs again, publishing the record. At 00:07, it's set to "published"

Scenario 2, current outcome: Page/2 is set to "timed" at 00:04. At 00:06 the cron 'skips' because it already ran. At 00:07, it's still set to "timed"

Scenario 2, desirable outcome: Page/2 is set to "timed" at 00:04. At 00:06 the cron runs again, publishing the record. At 00:07, it's set to "published"

Scenario 3, current outcome: At 00:04 the cron 'skips' because it already ran. At 00:05, it's still set to "timed"

Scenario 3, desirable outcome: At 00:04 the cron runs again, publishing the record. At 00:05, it's set to "published"

As far as I can tell, my suggested fix, fixes it for these three situations.

**Comment by SvanteRichter** [comment]
So currently the cron is hourly *in bolt* then, and running it multiple times in an hour does not change the outcome. In that case perhaps instead of (or as a complement to) the minutely cron we should add a --all/--now or similar cron that actually runs all checks regardless of bolts scheduling?

**Comment by bobdenotter** [comment]
Yes, it runs once per hour.. Unless, as Gawain describes above, you flush the cache, and set `general/performance/timed_records/interval`. However, that does not seem like a good workarond, since it would require one to flush the cache at a time when you're likely not around (hence why you set it to "timed"). 

Using a `--all` or `--now` flag might work, but is probably pretty bad for performance.

**Comment by SvanteRichter** [comment]
> Using a --all or --now flag might work, but is probably pretty bad for performance.

The point of that flag would be to be able to schedule it as you want and which fits your site. If we move the scheduling out of the bolt cache it can be scheduled as often as is needed. Since cron jobs are already scheduled I don't see the point of having another scheduler in bolt, but I'm probably missing some point here.

**Comment by SvanteRichter** [comment]
Oh, and the point by saying 

> So currently the cron is hourly *in bolt*  then

Was mostly just because I wasn't sure if the hourly/daily/weekly units in bolt actually scheduled tasks or only did different tasks.

I would assume the latter, that `hourly` is a group of tasks that are recommended to run hourly, not that bolt didn't run them if they had been run in the last hour.

**Comment by bobdenotter** [comment]
I think a "minutely" scheduler is a good idea, because it (like you say) allows the user to set it up as often as they wish. Well, as often as once a minute, that is.

**Comment by GwendolenLynch** [comment]
It would be "minute" not "minutely" and have fun with Bolt, I'm out! Fuck you!

**Comment by bobdenotter** [comment]
See #7598
