### ISSUE TITLE
Slug numbers will not increase？

### ISSUE THREAD

**Issue by ziselive** [bolt/bolt#7568]
Details
-------

 - Relevant Bolt Version: [  3.5  ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 7.1.15 ]
 - Used web server: [ Apache  ] version [ 2.4 ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------
Slug numbers will not increase
Sending several articles in a row, Slug numbers has always been 1
/entry/
/entry/1
/entry/1
/entry/1
/entry/1

**Comment by bobdenotter** [comment]
Seems like this is correct.. If you leave the title (or other field to fill the slug) empty, it doesn't properly generate a good slug.. If you input even a single character in the title field, it will work correctly:

![screen shot 2018-07-29 at 15 08 45](https://user-images.githubusercontent.com/1833361/43366638-77f6af0a-9341-11e8-83d3-f154992e50ad.png)

**Comment by ziselive** [comment]
@bobdenotter  Slugs can be generated automatically if the title is in English or numbers.However, if the title text is a multi-character font, it will not automatically generate slug.

**Comment by xiaohutai** [comment]
It seems it doesn't slugify those characters by default (probably assumes English).

You could make your own extension, or something like https://github.com/SahAssar/internationalslugs 
that handles your language/locale, and for example, for Chinese: https://github.com/cocur/slugify/pull/195

Edit: It seems we're still on v1.4.1 for `cocur/slugify`. Maybe that can be updated.

**Comment by bobdenotter** [comment]
Seems like `cocur/slugify` is at 3.1 already, but it seems like it's still compatible with PHP `5.5.9`. So yes, let's see if we can update this
