### ISSUE TITLE
Changelog can't handle changed contenttypes with repeater fields

### ISSUE THREAD

**Issue by doenietzomoeilijk** [bolt/bolt#7573]
If you enable the changelog and change a contenttype that has a repeater field, displaying that changelog entry will throw an error (array to string conversion) from twig.

Details
-------

 - Relevant Bolt Version: 3.5
 - Install type: Composer install
 - PHP version: 7.1
 - Used web server: built-in dev server
 - For UX/UI issues: -

Reproduction
------------

* Install Bolt as per usual
* Enable the changelog by setting `changelog: enabled:` to `true`
* Add a contenttype with a repeater field. The default install has showcases, which work.
* Add a record for the contenttype
* Go to the changelog, find your change, try to view it
* Boom headshot

### Bug summary

The changelog view receives an array, where it actually expects a string. This makes sense, since repeaters are array-like things. Unfortunately, the array is empty, no matter what I changed in my repeater field. I'd have to dive into it to see if it's possible to get something to display there, but in the mean time, it'd be beneficial if at least the system wouldn't break at this. :)

For completeness' sake, the error is thrown at `vendor/bolt/bolt/app/view/twig/changelog/_blocks.twig` line 191 / 194, where the rendered changed fields are displayed.

**Comment by xiaohutai** [comment]
Might be related to https://github.com/bolt/bolt/pull/7336

**Comment by doenietzomoeilijk** [comment]
Oh, that certainly seems to be related - in fact, I'm fairly certain that issue will fix this one. 

@bobdenotter any thought about getting #7336 moving again, now that #7291 seems to, in fact, have landed? :) And do you agree that this specific bug would be fixed by that, as well?

**Comment by bobdenotter** [comment]
Yes, certainly the same issue.. I'll continue working on that one.
