### ISSUE TITLE
[UX] Expired CSRF tokens message is causing confusion

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#7576]
If you are editing a page sometimes there is a message to warn you that your changes could not be saved as per #7529.

Unfortunately this does not fix the problem in #7550 because even though users are informed some users don't understand the message and there is no helpful message about how to proceed.

This happens a lot for sites where content editors are creating long form content, or are making time consuming changes to records.

Details
-------

 - Relevant Bolt Version: 3.5.5
 - Install type: composer install
 - PHP version: *
 - Used web server: *
 - For UX/UI issues: *

Reproduction
------------

### Bug summary

When your CSRF token is expired you are informed that the record can not be saved due to a CSRF token that is not valid. There is a technical explanation of how to proceed that is not helpful to many people.

### Steps to reproduce

See #7529 and or #7550 

 - login to the bolt back-end
 - start editing a page
 - wait a long time (30+ minutes, maybe even a day)
 - try to save the page and the error message appears
 - after refreshing the page you can save again

### Actual result

Users are not sure how to proceed. Sometimes they lose data.

 - clicking the save page button does not work
 - re-submitting the form is impossible without refreshing the page, this means losing your changes

### Expected result

We need to fix the page so the save button works again and users can submit the form without losing any changes. 

Alternatively the message should tell  end-users / laypersons what they can do to continue, without losing their work. Maybe this goes as far as copy their changes to a text editor and refreshing the page afterwards.

### Possible solutions

 - On submission we could generate a new token and inject it into the form.
 - We could show a confirmation dialog with a message like "You have been editing this page for a long time, other people might have made changes during this time. Please confirm that you want to save anyway." that generates a new token and submits the form.
 - If a CSRF token expires show a popup dialog with "You have been editing this page for a long time, other people might have made changes during this time. Please confirm that you want to continue editing this version." and on confirmation inject a regenerated token into the form.

**Comment by bobdenotter** [comment]
If this were feasible to fix, we would've.

**Comment by jadwigo** [comment]
A way to test this more easily is by adding the following key for session cookie lifetime to `config.yml`

```yml
session:
    cookie_lifetime: 120
```

This will decrease the session cookie lifetime to 120 seconds - so after two minutes the CSRF token will expire.

If you set the session cookie lifetime to zero, the session should last until the browser is closed.
```yml
session:
    cookie_lifetime: 0
```

This does not seem to have any effect on the authentication cookie.

**Comment by jadwigo** [comment]
And some more testing - Firefox makes it even more complicated.

### Steps to reproduce

 - Set session.cookie_lifetime to 120
 - Start firefox, start editing a page
 - Wait for 2 minutes
 - Try to save the page
 - Get CSRF expired message
 - Refresh page
 - Try to save the page
 - Get CSRF expired message

### What happens

If you do not close your browser firefox will *keep* the changed form data *including* the CSRF token... You will need to close and reopen the browser before being able to save the record.

**Comment by GwendolenLynch** [comment]
NOTABUG

**Comment by bobdenotter** [comment]
Sorry @GawainLynch, but it _is_ a problem people are bumping into. It might not be easy to fix or resolve, but it warrants an issue on the tracker.

**Comment by jadwigo** [comment]
@GawainLynch Do you know if the `config.yml` setting has any unwanted side effects?

```yml
session:
    cookie_lifetime: 0
```

Otherwise making that setting the default would probably solve the problem.
