### ISSUE TITLE
Crash in TimedRecords

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7579]
**norepro 😢  **

I'm having a crash in prod environment (linux centos).
![image](https://user-images.githubusercontent.com/2145313/43585849-4e592d9c-9690-11e8-97b7-cc353b611127.png)
When i copy that same base to dev environment (windows) - and everything works ok.

#### callstack
![image](https://user-images.githubusercontent.com/2145313/43585877-5e08b1d6-9690-11e8-9287-0fde6392d11b.png)

<details><summary><strong>dump() in text mode {...}</strong></summary>
array:3 [▼
  0 => "SELECT t.*, GROUP_CONCAT(developers.id) as _developers_id, GROUP_CONCAT(developers.to_id) as _developers_toid, GROUP_CONCAT(incomingrelation.id) as _incomingrelation_id, GROUP_CONCAT(incomingrelation.from_id) as _incomingrelation_fromid, GROUP_CONCAT(incomingrelation.from_contenttype) as _incomingrelation_fromcontenttype FROM bolt_residentials t LEFT JOIN bolt_relations developers ON t.id = developers.from_id AND developers.from_contenttype='residentials' AND developers.to_contenttype='developers' LEFT JOIN bolt_relations incomingrelation ON t.id = incomingrelation.to_id AND incomingrelation.to_contenttype='residentials' WHERE (t.status = :status) AND (status = :status) AND (datepublish < :currenttime) GROUP BY t.id, t.id"
  1 => array:2 [▼
    "currenttime" => Carbon {#2798 ▼
      +"date": "2018-08-02 12:59:41.700550"
      +"timezone_type": 3
      +"timezone": "UTC"
    }
    "status" => "timed"
  ]
  2 => array:1 [▼
    "currenttime" => "datetime"
  ]
]
</details><br>

When i comment these lines:
https://github.com/bolt/bolt/blob/3.5/src/EventListener/StorageEventListener.php#L158-L163
everything works perfectly on production too.

So password is okay, connection is ok. It only breaks in `getTimedRecords`

_(Database was created in nov 2015)_

**Comment by GwendolenLynch** [comment]
This is your database connection parameters, or the DB instance not being online at the time.

**Comment by Boorj** [comment]
hm.. looks like it reads all data from DB, so it's on air
