### ISSUE TITLE
[3.6] Saving with New Storage gives error

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7590]
Editing a Record with `setcontent_legacy: false` throws an error, when trying to save: 

![screen shot 2018-08-08 at 16 18 13](https://user-images.githubusercontent.com/1833361/43842969-bcd062e6-9b26-11e8-9e99-c9953d14129f.png)

Looks like this is because `$contenttype` is an Object now, instead of an Array. @rossriley, could you look into this?

**Comment by rossriley** [comment]
sure, checking

**Comment by bobdenotter** [comment]
Fixed in #7599
