### ISSUE TITLE
[Tracker] Bolt 4.0 backend design

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7594]
Steps:

 * [x] Bolt 3.X wireframes (#7595)
 * [x] Discuss design changes 
 * [x] Bolt 4.X wireframes
 * [ ] Bolt 4.X implementation

**Comment by SvanteRichter** [comment]
Added basic steps, please expand/change as needed

**Comment by sbonardt** [comment]
Added ref to issue #7595, Bolt 3.x wireframes

**Comment by sbonardt** [comment]
Bolt 3.x wireframes for the screens specified in #7595 are defined. I've created separate trackers for every screen. These will be the working tracking issues for the Bolt 4 wireframes

See the Milestone page for all issues: https://github.com/bolt/bolt/milestone/26
