### ISSUE TITLE
option for selecting which group to show in the overview sectioin

### ISSUE THREAD

**Issue by webching** [bolt/bolt#7596]
In the overview section, when there are multiple taxonomy types in grouping for one contenttype,  
only one of the taxonomy is grouped and showed.
So, how to configure it to select which taxonomy is grouped?
(refer to: the twig file: _sub/_record_list.twig  --  content.group  )

**Comment by bobdenotter** [comment]
Do you have more than one taxonomy that has "grouping"?

**Comment by webching** [comment]
yes more than one

**Comment by bobdenotter** [comment]
> yes more than one

That doesn't really work. You should have only one, which will then automatically be the one that's grouped on. You can use others as "regular" categories, and filter on them if needed.
