### ISSUE TITLE
[tracker] Bolt 4.0 Wireframes - Main navigation

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#7607]
The Bolt 4.0 Main Navigation Wireframe(s)

Starting point will be what's set up as wireframe for the Main navigational elements from Bolt 3.x.

For now:

- Are the main navigational elements (main menu, header nav links) good as is, or do we need improving for B4

## Navigation Overlays - 01 small screens - popups ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964401-12626744-9cbd-11e8-935d-1fe0b55ff8b8.jpg">
</p>
<br><br>

## Navigation Overlays - 02 main navigation - small screens ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964402-127bf1c8-9cbd-11e8-9b56-e6acf114f7a2.jpg">
</p>
<br><br>

## Navigation Overlays - 03 main navigation - large screens ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964403-129a82c8-9cbd-11e8-8e17-1530babe6675.jpg">
</p>
<br><br>

**Comment by martinsotirov** [comment]
@sbonardt I'm not so sure about the sidebar with news and notifications where I edit my content. Maybe it makes sense on the Dashboard (like in WordPress) but on content admin pages it's a bit unnecessary.

**Comment by sbonardt** [comment]
@martinsotirov Thanks for your comment! If you check the wireframe issue for the Edit content page #7609 there is no news and notification there now, and not suggested. This issue is about the Main navigation wireframes in Bolt by the way. Did you maybe mix up where you intended to put this comment?

**Comment by martinsotirov** [comment]
@sbonardt ah, yes. I got confused by the "content type" menu item that looks active but I guess that's just the hover state. Never mind my comment.

**Comment by sbonardt** [comment]
- For the main navigation in the Bolt backend I like how it's in place now and how it behaves on small screens and larger screens. On small the extra actions appear on click, and on larger screens it's a popup. The "collapse feature" on larger screens is not something I use a lot but it works. Would be nice to know if others use it a lot and like it...

- The user menu on the top right is proven and should stay. 

- The site title on top left next to the Bolt logo links to the bolt backend root again, just like the logo. That's a bit unnecessary/double. Also, for me it would be more logical this website name links to the frontend of the website, if it should link to something at all... (better to remove link?)

- But we also have a "view site" button top right. I think this one would be more in place top left next to the Bolt logo. Then what to do with the website title?

- At the bottom of the Main Nav "sidebar" on larger screens we have the Bolt version and an About link. The Bolt version link links to the Bolt.cm website and the About link links to information about the Bolt (version) CMS. That seems a bit odd to me. More logically would be the version number link (Bolt 3.5.2) links to the about page in the backend (with the version info and more) and the About page links to Bolt.cm or something... ("About Bolt")

Apart from the placement of the "View site" button and some tweaks I don't feel we can gain a lot here changing stuff. It seems robust as it is to me. 

I like to hear your thoughts/ideas.

**Comment by Boorj** [comment]
My #7235  suggest:

- add **website avatar**
  ![](https://user-images.githubusercontent.com/2145313/33584237-038a3dfe-d991-11e7-848b-9899d24cecec.png)

- Allow to customize / totally **rearrange main menu**
