### ISSUE TITLE
[tracker] Bolt 4.0 Wireframes - Content Type overview page

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#7608]
The Bolt 4.0 Content type overview page wireframe(s)

Starting point will be what's set up as wireframe for the Content Type overview page from Bolt 3.x.

For now:

- What improvements can be made?
- Are there items/functionalities missing or useful to add?
- ...

## Content type overview - 01 small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964391-11910870-9cbd-11e8-8927-4745cf58e2f9.jpg">
</p>
<br><br>

## Content type overview - 02 large screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964393-11acb930-9cbd-11e8-86cf-9102235d29ee.jpg">
</p>
<br><br>

**Comment by sbonardt** [comment]
OK. For your info, the grouped view for this is left out for now. Maybe that's better for a separate task/process. There are some things with it and how it behaves. There is an issue referenced, see comment above this one

**Comment by sbonardt** [comment]
This page does what it should and I believe it could use some minor tweaks.

- The "Actions for [content type]" block feels a bit weird to me. I would suspect it in the place where it is, but the functionality in it needs some work. The "(Add) New [content type] " button is fine off course, and in a logical place. It could also work top page. On small screens the (Add) New" btn is all the way down. That should be at the top IMO
- The "Filter this overview" option seems a bit weird to me where it is. It's grouped/paired with the (Add) New" button. I think it would work above the listed content, or separate it from the Actions block.
- The info about the content type (default) settings works! But the placement after the filter feels wrong. I believe it should be right next/below to the "(Add) New" button. Something that happens automagically when placing the filters for the overview/list at top page
- The "bulk actions" is also a feature that works well. I feel it's kind of hidden though. You only see it when you check certain items checkboxes. Maybe make it visible but greyed out/not active in the design, and add some more pointers to enable it by selecting some item checkboxes.? A title above the bulk action buttons like "Bulk edit actions" and the actions a bit greyed out/not actionable but always visible in the design in the UI could work and help the user understand all interface options.
- The "Last edited" block seems fine to me. Should be at bottom on small screens and sidebar bottom on largers screens.

Any other ideas on what we can add/tweak on this page with regards to content editing?

**Comment by Boorj** [comment]
Have you forgot status icon on wireframe or am i getting something wrong?
![image](https://user-images.githubusercontent.com/2145313/46339393-df460900-c65c-11e8-8140-9d4d3bfc0694.png)

**Comment by sbonardt** [comment]
In the Bolt 3 wireframe it's the icon next to the date I think. But it wouldn't harm to have it functionally and explicitly named. Thx 👍

**Comment by Boorj** [comment]
Actually, Bolt lacks ability to easily customize the overview list. 
I had issue for that previously:
**[RFC- custom formatting of listing item](../issues/4816)**   #4816 
Please, have a minute and take a look there.
