### ISSUE TITLE
[tracker] Bolt 4.0 Wireframes - Edit content page

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#7609]
The Bolt 4.0 Edit Content page wireframe(s)

Starting point will be what's set up as wireframe for the Edit Content page from Bolt 3.x. I suggest we leave the tabbed/grouped fields version out of the equasion. Default the no tabs/groups CT is in place. And Grouping only divides fields into tabs, does not change field layout or influence field functionality

For now:

- What improvements can be made?
- Are there items/functionalities missing or useful to add?
- ...

## Edit Content - 01 no tabs - small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964396-11f7143a-9cbd-11e8-87f7-b27a55a3d403.jpg">
</p>
<br><br>

## Edit Content - 02 no tabs - large screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964398-120f2ab6-9cbd-11e8-8c10-dfc1e3735671.jpg">
</p>
<br><br>

**Comment by sbonardt** [comment]
One thing for this page is I feel when there is a template select field, it should be on the Meta info part of the content type. Not between fields.

**Comment by sbonardt** [comment]
Also the preview functionality is something to check. When you haven't saved the page you get a preview option that uses the default template on 'the fly'. When you 'preview' saved version (unpublished) I believe you do see the item with the correct template and ont a rpeview default template. (Hope this is still the case... :) )

**Comment by Boorj** [comment]
#### Sticky footer
Often users come to editcontent page just to fix some data. Later they need to scroll to save button.
Probably, we can add sticky footer, which holds save and other action buttons, also, probable some useful text.

Reposting [this suggestion](https://github.com/bolt/bolt/issues/6229#issuecomment-348755912) 
![image](https://user-images.githubusercontent.com/2145313/33582492-0e8eee4c-d988-11e7-8520-b94ec6753b33.png)

**Comment by SvanteRichter** [comment]
@Boorj Isn't that why there is a save button in the left column?

**Comment by Boorj** [comment]
@SahAssar , imagine 5 textarea fields and 20 more fields. Maybe also on mobile or something. you need to scroll to save button.
Probably, that could be solved by "go to top"  button. But in 2 clicks.

**Comment by Boorj** [comment]
#### Add ability to move description
Can we move description to the place beneath header? OR add a flag `show_description_below_header`? sometimes i need to give more information, leave _some instructions_ to clients or editors. 
![image](https://user-images.githubusercontent.com/2145313/44701123-5533df00-aab7-11e8-99f0-a3ddbfe738be.png)

**Comment by sbonardt** [comment]
@Boorj A sticky footer or something in that respect might seem like a good addition. I would opt to only implement this for larger screens. Scrolling on mobile/tabs does not seem a issue to me, and we need the screen real estate. But on larger/desktop screens in stead of a sticky footer we could also let the sidebar sticky upon scrolling, so it always stays in place and does not scroll out of view (sticky scroll)

As @SahAssar also said, the side save and publish actions are in the sidebar/right column because they are at page bottom as well...

So I think adding a sticky footer might make the UI a bit too intimidating/cluttered, but sticky-ing the sidebar action buttons in stead of the footer might work, on larger/desktop screens

**Comment by sbonardt** [comment]
@boorj a description is present in the actions field now. It would be an idea to add that to the top. But adding another flag option show_description_below_header would seem a bit too much I think. That would give another config option and not make it more simple.
I think we would just need to place the description and info thats's now in the actions block, in a more robust and fitting place. If it has a good place in the UI, we would not need a extra show_description_below_header option. Let's keep it as simple as possible

**Comment by Boorj** [comment]
#### Description
>we .. need to place the description ... in ... fitting place

i agree 100%. 

- there could be a block below header
- it could have ✖️ button . Which will close the block and remember the choice, so experienced users will be not getting this text each time. BUT, to explain user that "close" action is reversable, we can collapse text block, not close.
- when the block is collapsed - header could have _dimmed_ button `❔ help` or   `ℹ️ instructions` or 
  ![image](https://user-images.githubusercontent.com/2145313/44777561-27c55f00-aba5-11e8-9b5e-a3a82e8bed1f.png) help
  ![image](https://user-images.githubusercontent.com/2145313/44777387-b7b6d900-aba4-11e8-82fd-697fbf074825.png)
  So if webmaster decided to put leave instructions to clients - that will be the place to do that.
- We  even can have an option of setting up the name to this button (i.e. readme/help/instruction/manual). By default it could be empty — leaving only icon.


#### Sticky panel
> would opt to only implement this for larger screens. Scrolling on mobile/tabs does not seem a issue to me
maybe, on mobile screens that could be useful too. Often my clients decide to make routing operations with many blocks. Until we have "mass editor" like this: #3714 - it's a very hard work. And scroll each time to top or bottom could be exhausting (i.e. manually changing prices for 100 products)

Can we leave it optional? 

---

Btw, can we make **„admin“ branch in `config.yml`**, where we could set that up? That could also include many flags/preferences for admin backend design. Or even have `admin.yml` with config for backend admin design? @sbonardt  @bobdenotter @SahAssar  what do you think?

**Comment by Boorj** [comment]
Taken from #7637 👍 

Mark WIP contenttypes (not synced with DB):
![image](https://user-images.githubusercontent.com/2145313/44700953-4f89c980-aab6-11e8-9508-0d3706e12ae8.png)


Mark unsaved fields:
![image](https://user-images.githubusercontent.com/2145313/44701019-ad1e1600-aab6-11e8-9d48-a9bcceadec30.png)
