### ISSUE TITLE
[tracker] Bolt 4.0 Wireframes - Content Fields

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#7610]
The Bolt 4.0 Content fields page Wireframe(s)

Starting point will be what's set up as wireframe for the Content Fields page from Bolt 3.x.

For now:

- What improvements can be made?
- Are there items/functionalities missing or useful to add?
- ...

<h2>All content type fields - 01 small screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097051-22e166ba-9fdd-11e8-8fbe-9f55a7ee463e.jpg">
<br><br>

<h2>All content type fields - 02 large screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097050-22c86d22-9fdd-11e8-9a74-69e4ecd574fd.jpg">
<br><br>

**Comment by Boorj** [comment]
Should we number suggestions here?

1. cool feature: ability to dragndrop image anywhere on the screen => overlay appears, which suggests " here are image fields, where do you want to drop dragged image ?" 

**upd:**
For example you have 3 image fields (meeting poster / facebook share image / speaker avatar ) . And it asks you where you want to drop image.

**Comment by Boorj** [comment]
2. suggestion: emphasize field titles. After my research i decided for myself that bullets + bold font is the best option to do that.
![image](https://user-images.githubusercontent.com/2145313/44206919-8c37f580-a185-11e8-8ed6-1559c8ec10b2.png)


![](https://user-images.githubusercontent.com/2145313/33704397-e676bd76-db5e-11e7-9dad-1eefdf32bd8e.png)

**Comment by sbonardt** [comment]
@Boorj 

Good idea to number the options 👍 

1. Isn't there a sort of drag and drop in place already? Per field? I'm not a fan of the drag and drop that highlights the whole screen. More in favor of ability to drag and hover on the area and see visual clues about ability to drop on that specific field. Adding a extra UI layer with all options highlighting seems too much. Also, with allowed file types, I think you'll make it less intuitive when for instance png's or pdf's are not allowed ia specific fields...

2. Emphasizing field titles feels like a solution for a now not well working UI. The new UI should make field labels/titles obvious because of the design enhancements we've made. I believe we should not add a bullet now. Also we're in the Wireframe phase. This feels more like a UI design thing...

**Comment by Boorj** [comment]
2. okay, that will depend on context. But now i suppose there will be tons of text, and we will several levels of hierarchy. So probably interface will need bullets.

**Comment by Boorj** [comment]
### Show maximum upload size
Details here: #7401
