### ISSUE TITLE
Crash on adding a videofield with youtube link having extended characters

### ISSUE THREAD

**Issue by hrjt** [bolt/bolt#7622]

**Comment by hrjt** [comment]
A quick work around would be to manually edit the youtube title before saving record. Currently video title appears under "Matched Video" below youtube preview, after the details are fetched from youtube.
Proble is thie title input box is "READONLY" by default. Just make the title input field EDITABLE and change title before saving such videos.
To make title field editable:

1. open file:   app/view/twig/editcontent/fields/_video.twig
2. find the array "hid_title" at around line # 48 (bolt v3.4)
3. remove this line from this array:
      readonly:  true

Problem sovled. But this is just a workaround. This bug needs to be resolved.

**Comment by bobdenotter** [comment]
Hi @hrjt, 

Why did you close this one? Did it turn out it wasn't a bug after all?
