### ISSUE TITLE
failed to save tags in editcontent

### ISSUE THREAD

**Issue by webching** [bolt/bolt#7626]
it is ok to save tags in English words, but not for non-english words.

i can fix the display bug for tags, by modifying this file:
vendor/bolt/bolt/src/Storage/Entity/ContentTaxonomyTrait.php
Line 85, added: if(empty($slug)) $slug = $name;

How to fix it for the editcontent part?

**Comment by bobdenotter** [comment]
That'd mean the 'slug' of the taf becomes the non-slugged version, like the name, which is not good. There should be an issue on the tracker somewhere, that deals with allowing non western-european characters in slugs.
