### ISSUE TITLE
Improvement of internal service structure

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#7629]
I'd like to propose a change in the current service infrastructure of bolt. In my oppinion, there currently is a rather large problem with **close coupling** and **unclear concerns**.

# The Problem
Currently, most logic for a single component is not done within the service (or at least a entry point to a group of services) but wherever it is needed. For example, let's check the user component. When a service needs to load or even save/update a user, it is directly requesting the storage layer, chanhing values in the user and storing it again. The locationsfor code accessing user data are spread across a multitude of services.

This makes the logic very hard to replace. If someone wanted to replace the user database or switch to some remote store like a SSO or an LDAP service, he would have to refacture many services completely unrelated to the user service. The same would apply, if someone would need to add additional logic to the object loading/saving process like syncing other data sources. It's currently simply impossible.

Wouldn't it be perfect if someone could simply replace the user service with a proprietary ldap service, simply by replacing the user service with class providing the same methods?
Or replace the record service with something better suited to certain edge cases like large ammounts of records with many relations? (eg: mongo?)
Or replace the search service with something using a fast indexer like Solr?

Why not simply adhere to the principles of **loose coupling**, **seperation of concerns** and **single point of entry**?

Why not define a simple CRUD like group of methods and route every user concerned logic through a central service to it's sub components/services?

# Proposal
The solution is actually quiet simple afaik. Someone (yes, i volunteer) just needs to create the missing crud methods in the user service and replace each and every access to something user related with a respective call to the user service (containing the same logic but centralized).
This change is completely backwards compatible. Custom code would still be able to access stores directly. Just bolt's own code (and hopefully later extensions too) would use the service.

This of course can and should be applied to all services of bolt, but let's do it step by step.

In theory, it could also make sense to group services together and create proxy services that route calls to their sub services. This would further decouple everything and take the "make everything adaptable" a big step farther. But that's a quiet deep change in your structure and of course completely up to your style fo code.

So? Thoughts? If someone (eg me ;) ) would provide a PR for it, is there a chance for acceptance?
We could also do this in small conceptual steps. I could create an empty class with method signatures first to fit your style before recodeing it?

**Current**
```
Service A -> User Repository
Service B -> User Repository
Controller C -> User Repository
User Service -> User Repository
```

**New**
```
Service A                        \ 
Service B                        -> User Service -> User Repository
Controller C -> Service C        /
```

**Comment by bobdenotter** [comment]
Is this something you'd like to do for 3.x? Or when we have a scaffold for 4.0, and then move over the components one by one, and tidy them up?

**Comment by ToBe998** [comment]
Not sure how far away 4.0 is so i was rather aiming at 3.x. Im also not sure if the changes to sf4 could also already include these changes.

On the other hand, if you do it in 3.x and then move the changed services to 4.0, it could make refactoring the services so much easier. You would have to refactor a mach smaller number of exposed methods of the services.

**Comment by bobdenotter** [comment]
4.0 _is_ quite far away, but I'm not sure it it's wise to invest this effort into the 3.x branch now. If it's up to me, 3.6 and potential other 3.x releases will focus mainly on stuff that prepares a transition to the 4 branch. 

So, in that vain, it _might_ be useful. At the same time, I think the User repository might not be a good example, because i'm pretty sure i'd like to replace most of the code we have for that now for an out-of-the-box SF 4 implementation.

**Comment by ToBe998** [comment]
Well, the proposition to use the user service isnt random of course. I actually needed to replace the login with our sso solution for quiet some time now and was simply unable to without refactoring many parts of the code.
So, I'd still rather use that one and for the closer future. It could also help replacing the code with a sf4 standard easier. (Even if i hope that doesnt finally make the component completely irreplacable ;) )

And then, if it's fine for your plans and there is no real objection ... why not just go with it. It's only my time ;)

**Comment by bobdenotter** [comment]
In that case: By my guest! Just so you know, it might break when it's time to move to 4.0. :-)

**Comment by rossriley** [comment]
big :+1:  from me

**Comment by ToBe998** [comment]
As discussed. Atm not possible without a huge amount of effort as the current logic and it's distribution into components is a bit to unstructured for this. As 4.0 will bring a major service restructuring anyways, we'll wait for that. Sry
