### ISSUE TITLE
[RFC] Repository mappings on existing content types

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#7635]
I recently used repository mappings (as described [here in docs](https://docs.bolt.cm/3.5/extensions/advanced/storage-repositories)). This feature is great when using custom controllers. But I would be even better if mapped entity were also called in Bolt controllers. 

When using a custom controller with my custom repo, I get an entity of `Namespace\Entity\MyEntity`, perfect, I can take advantage of methods defined in that class.
When requesting a content type from Bolt's routes, unfortunately, I get an entity of `Bolt\Storage\Entity\Content`. 

It would be nice to check if some mapping exists and then use that mapped entity.

**Comment by rossriley** [comment]
We just merged this feature into the 3.6 branch so it will be available in the next release.

It's configurable via contenttypes.yml via the `class` setting.

Here's the PR for more details: https://github.com/bolt/bolt/pull/7571

**Comment by nlemoine** [comment]
Great news! Thanks for your feedback.
