### ISSUE TITLE
Update to fontawesome 5+ ?

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7639]
![image](https://user-images.githubusercontent.com/2145313/44701828-c032e500-aaba-11e8-94d3-d6f91763aa98.png)

Several icons should be renamed, according to [4→5 upgrade manual](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)
including dashboard:
![image](https://user-images.githubusercontent.com/2145313/44701926-27509980-aabb-11e8-816a-4fd1b2c09220.png)

**Comment by bobdenotter** [comment]
For Bolt 4, i'm considering to go with Material Design Icons: https://materialdesignicons.com/ 

There's a ton of them, and the license makes it a much better fit for an Open Source project than Font Awesome does. A minimal working set is comparible, filesize-wise: 

<img width="566" alt="screen shot 2018-09-17 at 06 54 34" src="https://user-images.githubusercontent.com/1833361/45606689-7e58e700-ba47-11e8-9bfe-60ab75f11d92.png">

**Comment by Boorj** [comment]
What a dramatic economy :)

Chech this link out: https://getbootstrap.com/docs/4.1/extend/icons/
List of icon sets. 

And beside that all - Bv4 is far away, and we can switch to new icons right now ;)

**Comment by laurens94** [comment]
This could be implemented in the meantime while we wait on Bolt 4 right? Right now it's sad to look for a nice icon on fontawesome.com, applying it to a contenttype and then come to the conclusion that it's a fontawesome 5 icon..
