### ISSUE TITLE
Let's shorten <title/> of contentedit page

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7641]
When localized, phrase `"Edit %contenttype%"` in contenttedit page's <title/> could take whole space of browser tab, being truncated at right with ellipsis/fadeout. Take a look:
![image](https://user-images.githubusercontent.com/2145313/44852851-831f4c00-ac8e-11e8-8221-7819208dc20a.png)

## Example
Imageine, you're editing  *5 pages*, of contenttype `Article`. Localized it will be:
```html
<title>Редактирование Article » Name of article here</title>
```
But in browser tab you'll see only `Редактирование Article…`. 
So you will have *5 similar tabs* , and no _meaningful_ information is seen. You have to click each tab to find what you need.

## suggestion 1

**Let's change word "editing..." (`contenttypes.generic.edit: "Edit %contenttype%"`) to emoji ✏ !** 

![image](https://user-images.githubusercontent.com/2145313/44852528-aac1e480-ac8d-11e8-9b43-19d82c1faec2.png)
![image](https://user-images.githubusercontent.com/2145313/44852978-e4dfb600-ac8e-11e8-8609-4cab9c2ef2ed.png)
↑ Now you see specific part of each tab's name.

And emoji, by the way, has unicode fallback.

## suggestion 2 
If we have emoji , we can change pattern 
from 
`Edit %contenttype% » %title% - %site_name%`
to
`✏ %title% - Editing %contenttype% « %site_name%` 
Note the difference: title (as most important information for tab recognition) goes BEFORE edit contenttype.

**Comment by Boorj** [comment]
Same idea is in #7024 . But my idea is still : shorten titles. Not only insert emoji.

**Comment by Boorj** [comment]
## Suggestion 3
We can even make a set of favicons for different actions (creating record, editing record)
![image](https://user-images.githubusercontent.com/2145313/44854897-02fbe500-ac94-11e8-8672-eee487c3ee26.png)
It's really easy to do;) I can do that ;)

**Comment by bobdenotter** [comment]
See also #7024

**Comment by Boorj** [comment]
Suggestion 4
---
We can lay emoji / fontawesome contettype icon  onto  the bolt's icon.
So if you have emoji in your contenttype, when you'll be editing that - you will see the contenttype icon on browser tab.
