### ISSUE TITLE
[rfc] Use emoji with (or instead) fontawesome icons in contenttypes?

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7642]
How do you think, if we will allow webmasters to use emoji instead of fontawesome as icons in contenttypes? We can use **both**. 

- Many users have emoji support in their mobile/desktop browsers
- Big [variety](https://www.webfx.com/tools/emoji-cheat-sheet/) 
- People got used to emoji, **understand their meanings**
- We can use it in page titles: `<title>Editing  📑 Article "Learning Javascript is pain" </title>`. This will give better and faster recognition of tabs with different edited contenttypes.
  ![image](https://user-images.githubusercontent.com/2145313/44855272-e44a1e00-ac94-11e8-8257-e395866831b2.png)  or   ![image](https://user-images.githubusercontent.com/2145313/44855314-f6c45780-ac94-11e8-91da-19be53a3d46b.png)

- If used WITH font awesome, it doesn't break any behaviour
- It looks quite friendly

It is even *not inconsistent*, using with font awesome icons:

![image](https://user-images.githubusercontent.com/2145313/44854267-481f1780-ac92-11e8-80c9-a19a082b2dcf.png)

**Comment by jadwigo** [comment]
Emoji are very nice, but they have drawbacks that make them unsuitable for this purpose:
- They are displayed differently on all major platforms: https://emojipedia.org/black-square-for-stop/ https://emojipedia.org/black-rightwards-arrow/
- They are missing important icons that are used in interfaces like CMS systems - some examples: https://emojipedia.org/search/?q=blog https://emojipedia.org/search/?q=history
- Using both will be visually chaotic, because different styles will be mixed

**Comment by Boorj** [comment]
We can use predefined set of icons (as png spritesheet) for sidebar, and title icons will be shown with system font, no problem. Idea is to give people metaphors, that they got used to use. And we can help them. 

 Visual chaos is debatable. On picture above it's ok for me. Also, people are allowed to use strictly one of those options, if they prefer..
Webmaster could set up their icons, being oriented to their customers preferences. If you make a website for a blogger, or young lady designer - that won't be a problem to use emojis.

p.s. applicable replacements:  
**blog** -> https://emojipedia.org/search/?q=notebook 📓 
**history** -> https://emojipedia.org/search/?q=time ⏱

**Comment by sbonardt** [comment]
I don't know. I think the Fontawesome icons thing is a nice solution as is. It might need some polishing. But not custom emoji's... If a dev really wants that, they can override it themselves I guess. Also, IMO the idea kind of goes against:

> Bolt is an open source Content Management Tool, which strives to be as simple and straightforward as possible. It is quick to set up, easy to configure, uses elegant templates, and above all: It’s a joy to use.

**Comment by bobdenotter** [comment]
If it's totally optional, it's up to the implementor to use as they see fit. As such, i'm not against this idea, but IMHO i think the effort to make this work should be invested on Bolt 4, and leave it for Bolt 3 as-is.

**Comment by Boorj** [comment]
@bobdenotter I agree, Bolt 4 could have this as a new "visible" feature. 

@sbonardt 
>if a dev really wants that, they can override it themselves I guess

No simple way to do that.

And also emojis don't make bolt more complex, since they are 100% optional

**Comment by bobdenotter** [comment]
> emojis don't make bolt more complex, since they are 100% optional

I'm not sure I agree with that.. "options" are not 'free'. Every option makes a product sligtly more complex, because the user has to make a mental choice on whether ot not the option in question is relevant to them. :-)

**Comment by Boorj** [comment]
@bobdenotter i think, that won't create a new Entity in user's head. That could be accepted as unified field of icons. Just different prefixes. `fa-*` for fontawesome and `emoji-*` for emojis. So adding emojis won't increase amount of new information (almost at all). So this case, i think is not making Bolt more complex.

**Comment by Boorj** [comment]
EmojiOne is nice:
![image](https://user-images.githubusercontent.com/2145313/45760750-fea06780-bc54-11e8-9b06-1ce16b86f4f2.png)

Even having a free license:
https://www.emojione.com/licenses/free

**Comment by SvanteRichter** [comment]
Wouldn't using a font like EmojiOne remove the biggest plus of this (that they are shown in page titles)?

**Comment by rixbeck** [comment]
I really like our backend's simple, minimal design. I'm afraid also of - mentioned above - "visual chaos"...

**Comment by Boorj** [comment]
@SahAssar 
> remove the biggest plus of this 

Title font depends on system installed fonts. Anyway, we can't get 100% consistency for all users. But there are workarounds: 
- for **titles** on modern systems : default font
- for **titles** on old systems (Win7 and below) - fallback to unicode. Btw, we can also guess http agent in PHP or client's OS on the fly, and modify `<title/>` with small js code.  That will minify possibility to show user a _tofu_ (▯)
- for **page content** - emoji pack for page content , which will provide consistency. To minify requests - we can select emoji pack, and then compile a spritesheet (+css):
  ![image](https://user-images.githubusercontent.com/2145313/45795359-92118100-bcc5-11e8-92e7-0a3c7d9188e4.png)


#### The primary benefit of that, is:
Emojis in _system font_ (for titles) and in and _emojis packs_ (for page content) are synced. 
That means if you have 🦀 `:crab:` in emoji pack (in your backend content), it will look very close to the crab in title. Even if you have another font for titles.

---

@rixbeck 
> I really like our backend's simple

Idea is to help _webmasters_ customize their websites for their clients. So if you prefer to keep it minimal - just keep that. But, again, for instance, if a webmaster is making a website for a blogger girl, he can use emojis. And that will make them both happy.

**Comment by doenietzomoeilijk** [comment]
Personally, I'm not a fan. If this could be done as an extension, making it 100% optional, sure, but otherwise it is, as Bob already noted, added complexity. Especially since you can't 100% rely on the default working, so you have to add packs and workarounds and whatnot.

**Comment by Boorj** [comment]
It's optional and doesn't make anyone re-config anything. If a user uses `emoji-*` instead of `fa-*`, he accepts a virtual agreement, that something could go not as he expected. All other users won't get any discomfort or complexity. Can @doenietzomoeilijk you explain, what is the complexity in this case? no extra keys in `config.yml`, no fallbacks, no default values, no extra code in core. What is the problem here? I really can't see any at all.

**Comment by jadwigo** [comment]
The extra complexity is in the area of extra options, as @bobdenotter stated
>  "options" are not 'free'. 

- Every option needs to be maintained by developers
- Every option needs to be tested for compatibility (does an emoji work in a tab or window title)
- Every option needs to be tested for usability (Do the emoji work on you mobile and on MSIE 11)
- Every option needs to be explained in the documentation

The effort these things cost are too much at the moment, because we also have a lot of other things in Bolt at the moment where we need to do all these things, and we unfortunately do not have unlimited hours to work on all of them.

**Comment by Boorj** [comment]
Mates, i supposed we were speaking about usage complexity, not development complexity.

**Comment by Daryadi-S** [comment]
Hi guys, I'm a newbies. I know this is Out of topic, but it's still related to emoji :D Anyone can tell why every time I insert html emoji, it's always get converted to ???? after I see the live page? It's not all, only partials...

I am using tinymce 5 to write, get the raw content, then I paste the content in bolt by switching to "source" mode in the editor.

Example this emoji: ✔️ , which has raw input: &amp;#x2714;&amp;#xFE0F; is displayed normally.
Meanwhile this emoji: 😀, which has raw input: &amp;#x1F600; will converted to ????

Sorry for the out of topic, thanks in Advance. Bolt is a great CMS :+1:
