### ISSUE TITLE
[3.6] Preview doesn't work with new storage.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7645]
See screenshots:

![screen_shot_2018-09-06_at_17_33_08](https://user-images.githubusercontent.com/1833361/45168195-fda21b80-b1fa-11e8-82a8-c7e29cda23b3.png)

![screen shot 2018-09-06 at 17 31 31](https://user-images.githubusercontent.com/1833361/45168134-e2371080-b1fa-11e8-8056-d1664504467a.png)

**Comment by bobdenotter** [comment]
@rossriley I think this is also one for you..

**Comment by JarJak** [comment]
@bobdenotter this should be fixed by https://github.com/bolt/bolt/pull/7567

**Comment by bobdenotter** [comment]
@JarJak Nope, not fixed by #7567, although the error message is slightly different. ^_^ 

![screen shot 2018-09-10 at 15 19 21](https://user-images.githubusercontent.com/1833361/45299795-e91c9680-b50c-11e8-94b7-8ee1322d12e9.png)

**Comment by bobdenotter** [comment]
Fixed by #7564

**Comment by JarJak** [comment]
Actually Preview does not fully work yet, eg. Content does not have relations filled. @rossriley could you look at it later?

**Comment by JarJak** [comment]
FIxed in newest 3.6 :)
