### ISSUE TITLE
[RFC] Put wordforms for contenttypes in translations

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7650]
## Problem
When you create a contenttype, it's name in some languages is placed in incorrect word forms on many headings, signs and button captions. So it sounds like "I go Job".

But in each language there's different number or wordforms (plural, case, decline etc). So...

### 1. Let translators make a list of all possible word forms for a language
So that will be in a file named `contenttype-forms.**.yml` (or `wordforms.**.yml`)
```yml
- genitive_singular
- genitive_plural
...
```
That is done once, and accepted as PR on Github. Maybe this list should be filtered and reduced to a list of _used_ word forms only.

### 2. Let translators declare FORM of contenttype name in each instance in messages

For example in `messages.**.yml` in `contenttypes.generic.not-existing` key:
    **%contenttype% которое вы искали не существует.**
we change to
    **%contenttype|`genitive_singular`% которое вы искали не существует.**

This PR is also could be reviewed by community members, so we avoid errors.

### 3. Let _webmasters_ fill translation of contettype
That could be done  in `contenttypes-translations.**.yml` according to `wordforms.**.yml`. 

For example, when webmaster decides to create contenttype `Cat`, he (or she) adds next branch to `contenttypes-translations.**.yml` :
```yml
cats:
    genitive_singular : Кошки
    genitive_plural : Кошек
    ...
```
Then this file should be put in memory during initialization. 

### 4. Change [Translator.php](https://github.com/bolt/bolt/blob/3.5/src/Translation/Translator.php#L46) a little bit
Logic will be:
If we translate "%contenttype%" word and it has a suffix like `%contenttype|WORDFORM%` , then we do lookup in list of existing wordforms in current language.  If we found - we translate in correct form. If not - **fallback** to contenttype's name

## Conclusion
That could easily done without breaking BC. Change translator a little bit and let users create their translations.
**I can make a PR for that**

**Comment by bobdenotter** [comment]
I'm not against doing it like this, but please be aware that the translation layer will be quite different in v4, so any effort you invest into this at this moment, might have to be re-done when we're working on v4 properly. :-)

**Comment by Boorj** [comment]
@bobdenotter that solution seems to be atomic, you can't reduce that. Or avoid declaring forms. Syntax could change, but you need to point somehow , which form you're using in your sentence. So anyway, we can take all my "investments" and just transform that to new system. 
so..
1. should i do PR for that?
2. let's make a convention about file names and location
3. can you point me, which system will be used. v4 is close, so tools could be obvious already

**Comment by bobdenotter** [comment]
> should i do PR for that? 

That depends.. How much work will it be to do? Are we certain it'll have no sideeffects? 

> let's make a convention about file names and location

Let's follow what Symfony does: https://symfony.com/doc/current/translation.html

> v4 is close, so tools could be obvious already 

Well, I wouldn't call it close. I hope we're close to _actually_ getting _started_. :-)
That said, I've done some cursory comparison between Crowdin and Transifex, and I think I'd prefer Crowdin.

**Comment by Boorj** [comment]
i want to avoid rewriting all `Trans::__(...)` call. So i will add little check in function. If it's "contenttype" and if it has suffix. Changes will affect only translation tables (yamls). In other cases it will skip any processing and do the same flow that it does now. So i suppose that will allow to avoid any side effects.

In crowdin or transifex - we will need to define variables injections somehow. I suppose that will be a string, surrounded with some symbols (`%` now). So if i put all forms in russian translation, that could be easily converted. That means that i shouldn't hesitate and just do the PR 🤴

**Comment by SvanteRichter** [comment]
A question: How would you handle languages that don't just have singular and plural? How would you know the gender of the contenttype? How would you handle 0-singular like in french? How would you handle 2-3-4 plural being different than all other plural (Polish)? How would you handle any plural greater than 20 being different than another plural (Romanian)? How would you handle contextual possessives in icelandic? How would we contextualize the german ß correctly? Then we get into RTL vs LTR and excerptation in arabic.

And yes this comment is just a simplified version of https://www.youtube.com/watch?v=0j74jcxSunY

**Comment by Boorj** [comment]
There's a good site for different (i suppose all) possible word forms for all languages (CLDR):
http://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html
And it looks quite scary:
![image](https://user-images.githubusercontent.com/2145313/45595599-d573a300-b9d8-11e8-8beb-b2002e9fba9c.png)

So my idea is quite universal: you **allow native-language-speakers-translators 👫  make their own list** of forms.

##### Complete backend translation consists of : 
1. Messages (phrases) **not related** with contenttypes.
2. Messages **related** to contenttypes. And they consist of _words:_ 
    2-A. contettype names (CN) 
    2-B. all words, that are changed in dependency of CN
    2-C. other words not related to CN

That's it. In any language (maybe plural form that depend on some numbers, but i haven't met messages with such words)

So how that could work:
1. Type1 messages are translated as usual (`messages.xx.yml`)
```yml
message: Fat brown foo jumps over the bar
```

2. Type2 messages are translated with a postfix, defining a form.  In my examples i use abstract postfixes

So previously, a Type2 message for english language could look like:
```yml
message: Something about those %contenttype%
```

Let's find out, which type words of this phrase have:
- `Something about` - **Type2-C**
- `those` - **Type2-B** - because depends on _form of contenttype name (CN)_
- `%contettype%` - **Type2-A** - because it's a CN.

### And how can we translate that?
Now translators can write next in `messages.xx.yml` (mention that `those` and `contettype` are postfixed):
```yml
message: Something about %those|plural_form1% %contenttype|plural_form1%
```

Then **translators** go to the file `messages-forms.yml` and define *translation to their language for all possible postfixes* for `2-B` words . In our example we have to define dependent words forms for `plural_form1`

Then **webmasters** when developingtheir Bolt site,  go to the file `contettypes-translations.yml` and define *translation to their language for all possible postfixes* for `2-A` words (that you can find in `messages.xx.yml`):
```yml
# let's  assume name of contenttype is Cats.
Cats: 
    plural_form1: Cats
    singular_form1: Cat # this could be also used.
```

So, Type1 and Type2-C don't need to be transformed. Type2-B word transformations are made by translators (as messages too). And contettype name transformations are made by webmasters.

**That could cover any language**
