### ISSUE TITLE
[BUG][3.6][New Storage] Can't enter admin area

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7653]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.0 beta 4

Reproduction
------------

### Bug summary

Admin area does not work. Setting setcontent_legacy to true or false does not change error message.

### Specifics

Error message:
Type error: Too few arguments to function Bolt\Legacy\Content::__construct(), 0 passed in vendor/bolt/bolt/src/Storage/Entity/Builder.php on line 101 and at least 1 expected

### Steps to reproduce

Enter admin area

### Expected result

200

### Actual result

500

**Comment by JarJak** [comment]
@rossriley ^

**Comment by JarJak** [comment]
Ok, this was caused by my contenttype's custom class extending Legacy Content class. But it worked previously with `setcontent_legacy: true` so looks like this config option does not work anymore?

**Comment by JarJak** [comment]
OK, after I fixed my classes to not extend Legacy Content, when I try to edit any content in admin, I get (with setcontent_legacy: false):

FatalThrowableError in EntityManager.php line 490:
Call to a member function getContent() on null
in EntityManager.php line 490
at EntityManager->getContent('articles/1') in Edit.php line 139

**Comment by bobdenotter** [comment]
@JarJak That sounds like a duplicate of #7645. 😇

**Comment by JarJak** [comment]
@bobdenotter not really, that issue is about preview page, here I can't even enter edit page.

**Comment by bobdenotter** [comment]
It's breaking on the exact same line, at `EntityManager.php line 490`, though.

**Comment by JarJak** [comment]
@bobdenotter found a fix to my issue and now I see the same error in preview page as in #7645 :)

**Comment by bobdenotter** [comment]
Fixed by #7564
