### ISSUE TITLE
Adding BOLT to an existing project - problem installation

### ISSUE THREAD

**Issue by Infactis** [bolt/bolt#7669]
Hello,
I was looking for a lights CMS easily configurable with symfony. And when I check out BOLTCMS, it looks perfect to me to what i want to do. (Just some very light CMS on my website)

My project is a symfony 3.4.15 - PHP 7.2, (not linked to any database yet)

I'm having trouble in the installation.
So basically when I'm running  _php composer.phar require bolt/bolt 3.5_
They ask me to install symfony/routing or symfony/httpd or symfony/twig-bridge...
So I follow all the steps
Then i'm doing having  _php composer.phar require bolt/bolt 3.5_ again, and here the error message : 

Package silex/silex is abandoned, you should avoid using it. Use symfony/flex instead.
Package symfony/icu is abandoned, you should avoid using it. Use symfony/intl instead.
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class Symfony\Component\Config\Resource\ComposerResource contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Config\Resource\ResourceInterface::getResource) in /samba/anonymous/dph/spirtech/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ComposerResource.php on line 19
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

  PHP Fatal error:  Class Symfony\Component\Config\Resource\ComposerResource contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Config\Resource
  \ResourceInterface::getResource) in /samba/anonymous/dph/spirtech/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ComposerResource.php on line 19

Maybe my composer.json can help you to understand my issue : 
          "require": {
        "php": ">=5.5.9",
        "bolt/bolt": "3.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "passwordlib/passwordlib": "1.0.x-dev",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "3.0.29",
        "symfony/asset": "2.8",
        "symfony/config": "2.8",
        "symfony/console": "2.8",
        "symfony/debug": "2.8.9",
        "symfony/event-dispatcher": "2.8",
        "symfony/filesystem": "2.8",
        "symfony/finder": "2.8",
        "symfony/form": "2.8",
        "symfony/http-foundation": "2.8",
        "symfony/http-kernel": "2.8",
        "symfony/intl": "2.8.18",
        "symfony/monolog-bridge": "2.8",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/options-resolver": "2.8.*",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/process": "2.8",
        "symfony/property-access": "2.8",
        "symfony/routing": "2.8",
        "symfony/security": "2.8",
        "symfony/security-core": "2.4.*",
        "symfony/stopwatch": "2.8",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.15",
        "symfony/translation": "2.8",
        "symfony/twig-bridge": "2.8",
        "symfony/validator": "2.8",
        "symfony/var-dumper": "2.8.9",
        "symfony/web-profiler-bundle": "2.*.*",
        "symfony/yaml": "2.8",
        "twig/twig": "^1.0||^2.0"
    },

Thanks!

**Comment by bobdenotter** [comment]
You can't really use Bolt _inside_ a another symfony project. What's going wrong here, is that Bolt uses Symfony 2.8 components, and you have Symfony 3.4. That's bound to clash.

**Comment by Infactis** [comment]
Oh really ? argh

Worth a try to downgrade sf to sf 2.8 ?
Or Do you recommand me to look somewhere else

**Comment by bobdenotter** [comment]
We usually treat bolt as "the platform".. If you need a CMS, you can use Bolt, and maybe put it on `news.yousitename.com`, or somesuch.

**Comment by Infactis** [comment]
Yes I think I should change how I implemant BOLT in my project

I'm actually doing this part of the documentation : https://docs.bolt.cm/3.5/installation/composer-create-project/adding-to-an-existing-project

Thank for your help
