### ISSUE TITLE
[3.6][BUG][New Storage] Setcontent returns single record even without returnsingle

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7679]
Setcontent returns single record even without returnsingle **if run without params and after some returnsingle query**.
The record is not a singleton.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6 with new storage enabled

Looks like ContentQueryParser remembers directives between queries.

Reproduction
------------

### Steps to reproduce

There is more than zero Record entries in database.

{% setcontent record = 'records/1' returnsingle %}
{% setcontent records = 'records' %}
{{ dump(records) }}

### Expected result

QueryResultset (or any other iterable) with single record inside

### Actual result

Single record object

**Comment by rossriley** [comment]
Can't reproduce any issue here.

On latest 3.6 `setcontent` always returns a `QueryResultset` that is counted at the correct number. eg. `{% setcontent pages = 'pages' %} {{ dump(pages|length) }}` shows `6` which is the default pagination number similarly for records with only one row in the database I'm seeing the same result with one record, but still coming out as a QueryResultset with a `|length` of `1`

**Comment by JarJak** [comment]
@rossriley 

I have corrected bug description and steps to reproduce.

If you look here:
https://github.com/bolt/bolt/blob/3.6/src/Storage/Query/ContentQueryParser.php#L209
Directives are reset between queries only if the second query has any params.
Forcing it to clear fixes the bug.

**Comment by rossriley** [comment]
Nice, got it reproduced now. Fix coming up. thanks @JarJak
