### ISSUE TITLE
Exception in market.bolt.cm

### ISSUE THREAD

**Issue by opotemkin** [bolt/bolt#7682]
I open some page in the market.bolt.cm and saw error:
![image](https://user-images.githubusercontent.com/1541100/46311236-f2b09000-c5da-11e8-99bb-1d16f039c51b.png)

I do not know how serious this problem is. I wrote on the security@bolt.sm description of the problem, but the letter does not go away.
Can I show a full stack of exception?

**Comment by rossriley** [comment]
It's more than likely that this is just an extension listed on market.bolt.cm where the git repository has since been deleted. If you let us know what it is we'll mark the extension as unavailable.
