### ISSUE TITLE
After Upgrade 3.5.7 --> 3.6: [Symfony\Component\Debug\Exception\ContextErrorException]

### ISSUE THREAD

**Issue by yawicz** [bolt/bolt#7688]
Hi all!
Maybe a short disclaimer upfront:
I'm not the best coder on this planet, but I try my best and absolutely love Bolt and its community for making it possible for people like me to start their own projects and websites with the opportunity to customize every single detail and learn a lot by doing so! Thanks a lot for your great work! :-)

**Problem:**
I just upgraded via composer update from Bolt 3.5.7 to 3.6 and wasn't able to do anything afterwards anymore. When opening my website, I received a "ContextErrorException in Legacy.php line 0".

I could see the error stems from the extension "Translate" by SahAssar, Animal Design OG (animal/translate). The problem now was:
There was no way/I could not find any way to update or uninstall the extension, because whatever I tried via command line (app/nut extensions:update animal/translate; app/nut extensions:uninstall animal/translate), the error popped up again. So I was trapped with a broken Bolt installation without seeing a possibility to revert/mitigate the error.

Fortunately, I looked a bit closer into the error message and started to investigate the relevant files. Through this, I found a solution that seems to work just fine.

**Solution:**
I opened "/var/www/bolt/.../extensions/vendor/animal/translate/src/Storage/Legacy.php" and added the obviously newly introduced argument in Bolt 3.6 to the public function "getContentObject".

Old function:
public function getContentObject($contenttype, $values = [])

New and working function:
public function getContentObject($contenttype, $values = [], $isRootType = true)

Afterwards, everything seems to work just fine.
Thus, I guess this would be a required adjustment for the extension Translate (animal/translate) to be compatible with Bolt 3.6. The point why I post this here at Bolt is, that I feel there should be some sort of warning or check by the Bolt-setup in advance to prevent breaking the installation, at least if crucial functions of the Bolt-Storage-function have been changed compared to the prior version.

I hope this is helpful for someone who might encounter the same problem.

In case of any questions, please feel free to contact me anytime.

Best regards,
yawicz

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.5.7 / 3.6
| Install type                   |  Composer install
| BC Break                     | yes
| PHP version                 | 7.1
| Web server                  | Apache
| For UX/UI issues        | Mozilla Firefox 62.0.3 (64-bit)

Reproduction
------------

### Bug summary

Extension animal/translate causes ContextErrorException after upgrade (composer update) from Bolt 3.5.7 to Bolt 3.6.

### Specifics

Full error message:

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Declaration of Bolt\Extension\Animal\Translate\Storage\Legacy::getContentObject($contenttype,  $values = Array) should be compatible with Bolt\Legacy\Storage::getContentObject($contenttype, $values = Array, $isRootType = true)

### Steps to reproduce

- Install Bolt 3.5.7
- Install extension animal/translate
- Upgrade to Bolt 3.6.0
- Open website

### Expected result

Upgrade from 3.5.7 to 3.6 finishes without any error and I am able to open the website/administration-website without any problems.

OR

Upgrade from 3.5.7 to 3.6 already advises, that an extension is possibly incompatible and offers the option to deactivate it/deactivates it automatically.

### Actual result

Upgrade finished without any errors, but afterwards, I wasn't able to open any website and/or uninstall the problematic extension.

### Solution

Adjust public function getContentObject in /var/www/bolt/.../extensions/vendor/animal/translate/src/Storage/Legacy.php to:
public function getContentObject($contenttype, $values = [], $isRootType = true)

**Comment by bobdenotter** [comment]
Hi @yawicz, 

Looks like you're right at first glance! Hopefully i'll have some time today to verify your findings and put out a small update for the translate extension to get it working again. 

Thanks for the extensive report! 👍

**Comment by bobdenotter** [comment]
See https://github.com/BoltTranslate/Translate/pull/178 

I've tagged BoltTranslate 4.1.3. It will take a few hours to show up in the market, and then it should work again. Thank you again!

**Comment by yawicz** [comment]
Hi @bobdenotter ,

Great, thanks for the fast response and implementation, I'm happy I could help and will try to continue contributing whenever I should find something else.
Keep up the great work!

Best,
yawicz
