### ISSUE TITLE
Allow image upload by default in the wysiwyg

### ISSUE THREAD

**Issue by gagarine** [bolt/bolt#7690]
After install it's not possible to add an image in an HTML field without editing the config.yml like that:

```
wysiwyg:
    images: true            # Allow users to insert images in the content.
```

This is quiet confusing as a new user. I tried to drag&drop image from the stack (but only the thumbnail was added). I try to edit the field config. Etc..

I'm not alone https://stackoverflow.com/questions/29239651/what-does-the-stack-do-in-bolt-cms

I think changing this settings to true would help new user.

At least the stack and how to add image in HTML field should be documented.

**Comment by SvanteRichter** [comment]
In my experience most users should not be given this option, they try to upload 10+MB images and those don't get resized if they are not in an image field. Add a separate image field instead, or turn this on if your users can handle it and need it.
