### ISSUE TITLE
Creating a custom field that works as a block and a content type field

### ISSUE THREAD

**Issue by Spomsoree** [bolt/bolt#7694]
I've made an extension which can save multiple links to different social media sites.

I add the field to my block, underneath the `type: block` fields:
```yaml
social_media:
    type: socialmedia
    label: Social-Media
```
It does the same as the seo extension, which collects all field values via javascript and stores them as a json string.

This works pretty good so far.

As soon as I add my field to an contenttype, like the seo extension does, I get the following error:

`Type error: Too few arguments to function Bolt\Storage\Entity\Entity::get(), 0 passed in [...]/vendor/bolt/bolt/src/Storage/Entity/Entity.php on line 45 and exactly 1 expected`

If i check the database, the following error appears: 
`Table bolt_coredata is not the correct schema: invalid column social_media`

The field is added to the Database, but the system thinks it's not been updated yet.

![image](https://user-images.githubusercontent.com/14187981/47301889-51888880-d620-11e8-8f14-9f59b357d30b.png)

My extension looks like this:
```php
class SocialMediaFieldTypeExtension extends SimpleExtension
{
    /**
     * {@inheritdoc}
     */
    public function registerFields()
    {
        return [
            new SocialMediaField(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function registerTwigPaths()
    {
        return [
            'templates',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function registerAssets()
    {
        return [
            JavaScript::create('js/social-media-field.js')->setZone(Zone::BACKEND),
            Stylesheet::create('css/social-media-field.css')->setZone(Zone::BACKEND),
        ];
    }
}
```

And thats the field I'm trying to add:
```php
class SocialMediaField extends FieldTypeBase
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'socialmedia';
    }

    /**
     * {@inheritdoc}
     */
    public function getStorageType()
    {
        return Type::getType('text');
    }

    /**
     * {@inheritdoc}
     */
    public function getTemplate()
    {
        return 'social_media_fields.twig';
    }

    /**
     * {@inheritdoc}
     */
    public function getStorageOptions()
    {
        return [
            'default' => '',
        ];
    }
}
```

**Comment by nestordedios** [comment]
Hi @Spomsoree, you are saying that you want to store the data as `json` but I have the feeling that here 
you are saving it as `text` instead. 

```
    public function getStorageType()
    {
        return Type::getType('text');
    }
```

If you change `text` for `json` does it still break?

**Comment by Spomsoree** [comment]
@nestordedios Thank you for your answer, sadly this does not fix my problem. I've decided to store the json as text, because I'm encoding it to a string before saving it.

**Comment by nestordedios** [comment]
You are welcome @Spomsoree. I'm sorry to hear that didn't work. 

Have you check some Documentation on how to provide new Filed Types? https://docs.bolt.cm/3.6/extensions/advanced/fieldtypes#writing-the-field-type-class 

Maybe you find your answer in there. I had quick look and it seems there might be missing some `hydrate` and `persist` methods.

I hope this helps you.

**Comment by Spomsoree** [comment]
These `hydrate` and `persist` methods are not required as far as I understood. I still tried, but could not get it running.

`Table bolt_pages is not the correct schema: invalid column social` is the error I get after updating the database, which lets me think that the error occurs while updating or reading the updated database.

But thats just a guess.

Here are the changes bolt is trying to commit:
![image](https://user-images.githubusercontent.com/14187981/47576484-e521c800-d944-11e8-93d2-cadde4248f67.png)

**Comment by nestordedios** [comment]
@Spomsoree I just tried your code and it is working for me in Bolt 3.5.7. If you add more info how to reproduce the issue that would be very helpful.

You can always use Bolt's guideline for opening Bug Reports. 

```
A brief description of the issue goes here.

<!--

If you haven't yet done so, please read the "contributing guidelines"
thoroughly. Then, proceed by filling out the rest of the details in the issue
template below. The more details you can give us, the easier it will be for us
to determine the cause of a problem.

See: https://github.com/bolt/bolt/blob/master/.github/CONTRIBUTING.md

-->

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | legacy / 3.5 / 3.6 / master
| Install type                   |  Zip or tar install / Composer install / GitHub checkout
| BC Break                     | yes/no
| PHP version                 | 5.5 / 5.6 / 7.0 / 7.1 / 7.2
| Web server                  | Apache / Nginx / Built-in, version [ version ]
| For UX/UI issues        | Browser name and version


Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

<!--
    * Write a short summary of the bug
    * Try to pinpoint it as much as possible
    * Try to state the _actual problem_, and not just what you _think_ the
      solution might be.
-->

### Specifics

<!--
    * Mention the URL where this bug occurs, if applicable
    * What version of Bolt are you using (down to the very last digit!)
    * What method did you use to install Bolt
    * What browser and version you are using
    * Please mention if you've checked it in other browsers as well
    * Please include *full error messages* and *screenshots* if possible
-->

### Steps to reproduce

<!--
    * Clearly mention the steps to reproduce the bug
-->

### Expected result

<!--
    * What did you _expect_ that would happen on your Bolt site?
    * Describe the intended/desired outcome after you did the steps mentioned.
-->

### Actual result

<!--
    * What is the actual result of the above steps?
    * Describe the behaviour of the bug
    * Please, please include **error messages** and screenshots. They might mean
      nothing to you, but they are _very_ helpful to us.
-->
```

**Comment by rossriley** [comment]
It looks like the issue is with the default field definition, may be running into issues with `null` vs `""` in mysql values. Could you perhaps try manually editing the database column to set the default as an empty string.?

**Comment by Spomsoree** [comment]
To this date, I could not change the database value, because i was not able to create one, because of the error.

Today I fixed the database error, which caused the 
`Table bolt_coredata is not the correct schema: invalid column social_media` message.
I added the `'notnull' => false` option, which fixed it.

The second error still appears. 
`Type error: Too few arguments to function Bolt\Storage\Entity\Entity::get(), 0 passed in [...]/vendor/bolt/bolt/src/Storage/Entity/Entity.php on line 45 and exactly 1 expected`
Somehow the parameter is missing there.

As far as I understand, the field name is required at this point. 
I temporarily added a default parameter to the function, which fixed the problem. But I still have no idea why this parameter is missing and where it should come from.

Thank you all for your help so far!

**Comment by Spomsoree** [comment]
A description can be found at the top.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   |  composer install
| PHP version                 | 7.1
| Web server                  | Laravel Valet


Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The Entity-Class is not able to run "getSocialmedia()" which is tried at line 45 in Bolt\Storage\Entity\Entity

### Specifics

Screenshots can be found at the top.

### Steps to reproduce

* Create a new Extension
* Try to add the new fields to a contenttype

### Expected result

Should add the Socialmedia field/fields

### Actual result

"Type error: Too few arguments to function Bolt\Storage\Entity\Entity::get(), 0 passed in /[..]/vendor/bolt/bolt/src/Storage/Entity/Entity.php on line 45 and exactly 1 expected"

**Comment by Spomsoree** [comment]
I still couldn't solve this problem to this day.

**Comment by Spomsoree** [comment]
### It works!

Apparently the field template needs to start with an underscore.

Does not work:
`public function getTemplate()
    {
        return 'button_fields.twig';
    }`

Does work:
`public function getTemplate()
    {
        return '_button_fields.twig';
    }`

The template itself needs to be renamed too, of course.

**Comment by Spomsoree** [comment]
Ok so now I've found the error:

`context.content.get(rkey)`

I've tried to get the database value thought this. This works fine in blocks but not in the contenttypes.

I'm now using `context.content.get(contentkey)` which returns the values in both cases.
