### ISSUE TITLE
[3.6] Extensions report error with private method

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#7696]
I just updated a Bolt website from 3.5.7 to 3.6 and now get an error in my custom extensions.

```
FatalErrorException in Extension.php line 16:
Compile Error: Cannot override final method Bolt\Extension\SimpleExtension::extendRepositoryMapping()
```

Line 16 is the class header and it extends `Bolt\Extension\SimpleExtension`
Here are some possibly relevant parts of the file (not a complete file!)
```
class Extension extends SimpleExtension
{
    use StorageTrait;
    use DatabaseSchemaTrait;

...

    protected function registerServices(Application $app)
    {
        $this->extendDatabaseSchemaServices();
        $this->extendRepositoryMapping();

...

    }

    protected function registerExtensionTables()
    {
        return [
            Schema\Table\AuthLog::TABLENAME => Schema\Table\AuthLog::class,
        ];
    }

}
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.0
| Install type                   |  Composer install
| BC Break                     | yes
| PHP version                 | 7.2
| Web server                  | Apache

**Comment by rossriley** [comment]
Try taking out the `use StorageTrait` this is already included on the base class so it could be that that's causing the issue.

**Comment by ToBe998** [comment]
This seems to resolve the problem, but i need further testing. I'll get back to you. tnx.

**Comment by ToBe998** [comment]
Solution is working!

**Comment by ToBe998** [comment]
@rossriley Sidenote: This change introduced a difficult BC break. Before 3.6 you needed to include the StorageTrait, after 3.6 must not use it because of the "private" change. Please do not do such changes on minor version in the future. It's quiet hard to resolve now when an extension is used in multiple bolr instances.
