### ISSUE TITLE
select field values in repeaters

### ISSUE THREAD

**Issue by tiito78** [bolt/bolt#7697]
Looks like this commit made by rossriley https://github.com/bolt/bolt/commit/c4cae8b on the file app/view/twig/editcontent/fields/_repeater-group.twig have not been merged on bolt 3.6. 

I can verify that when updating this file on bolt 3.6, values from select field in repeaters will work.

**Comment by SvanteRichter** [comment]
Fixed in #7701

**Comment by niclashoyer** [comment]
Is this bug still present on 3.6.3? I'm using select fields in a repeater for the first time and if I try to get the value of the selected option I just get the ids, not the actual text values.
