### ISSUE TITLE
[3.6] Composer install problem without dev deps

### ISSUE THREAD

**Issue by lardyNiji** [bolt/bolt#7702]
When installing Bolt with ```composer install``` all work as expected.
If i use ```composer install --no-dev``` this break app/nut cmd line for database:* actions

```
./app/nut database:update -vvv
                                                              
  [Symfony\Component\Debug\Exception\ClassNotFoundException]  
  Attempted to load class "Carbon" from namespace "Carbon".   
  Did you forget a "use" statement for another namespace?     
                                                              
Exception trace:
 () at /var/www/html/vendor/bolt/bolt/src/Storage/Database/Schema/Timer.php:86
 Bolt\Storage\Database\Schema\Timer->setCheckExpiry() at /var/www/html/vendor/bolt/bolt/src/Storage/Database/Schema/Manager.php:130
 Bolt\Storage\Database\Schema\Manager->check() at /var/www/html/vendor/bolt/bolt/src/Nut/DatabaseRepair.php:38
 Bolt\Nut\DatabaseRepair->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/bolt/bolt/app/nut:19
```

Timer.php need Carbon Class and with the installation without dev dependencies (--no-dev) the autoloader does not load the Carbon Class.

```
composer install

grep -ir "carbondate/carbon" *

vendor/composer/autoload_psr4.php:    'Carbon\\' => array($vendorDir . '/carbondate/carbon/src/Carbon'),
vendor/composer/autoload_static.php:            0 => __DIR__ . '/..' . '/carbondate/carbon/src/Carbon',
```

The same grep with ```composer install --no-dev``` give no result

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   | Composer install
| BC Break                     | yes
| PHP version                 | 7.2
| Web server                  | Nginx 
| For UX/UI issues        | Browser name and version

**Comment by bobdenotter** [comment]
Try `rm -rf vendor/; composer install`, and it should work.

**Comment by lardyNiji** [comment]
Hello @bobdenotter 

It was a composer.lock problem from my side, when i've updated bolt to 3.6 my composer.lock still had carbondate/carbon. Now i've deleted it and it have the correct dependency.

Thank you and sorry for the disturbance.

**Comment by bobdenotter** [comment]
@lardyNiji Thanks for the followup, glad it works now! 👍
