### ISSUE TITLE
contenttype/slug notation in menu.yml (was: Minor menu thing)

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#771]
http://docs.bolt.cm/menus says "each item has access to the entire record" (extremely handy btw) but this only seems to work for relative urls, and not for /absolute urls. 

Since the standard slug is shown as /absolute url in the back end, I tended to copy-paste these to the menu file, but I quickly found out that accessing the record does not work then.

Maybe this can be mentioned on http://docs.bolt.cm/menus , or (if it's actually a bug) fixed.

**Comment by GawainLynch** [comment]
@evertalbers I just came across this randomly...  but I think I may have implemented this yesterday in #2708

Could you do me a favour and have a look at what I documented in the PR and let me know if that addresses/closes this one?

**Comment by evertalbers** [comment]
It does. If I understand all the options that you listed well, the chance of 'people like me' screwing up links in menu.yml would go down by at least 95%.

BTW the separation between paths, contenttypes etc. is already a lot clearer in the docs now than it was over a year ago.

**Comment by GawainLynch** [comment]
> BTW the separation between paths, contenttypes etc. is already a lot clearer in the docs now than it was over a year ago.

Ha!  Yeah, I almost fell over when I saw how old this one was.  

Glad it looks to address your problem though :smile_cat:. I'll close this then, but feel free to reopen it when you move to 2.1 and find it doesn't work as expected.
