### ISSUE TITLE
Inserting time in datetime field

### ISSUE THREAD

**Issue by rainpoiss** [bolt/bolt#7715]
When entering a time in time field like 1515 then it will change to 00:00

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.5  3.6 
| Install type                   | Zip or tar install / GitHub checkout
| BC Break                     | no
| PHP version                 |7.2
| Web server                  Nginx 
| For UX/UI issues        | Chrome 61 , Firefox 60

Reproduction
------------

create datetime field in ct.
Insert data in the time field example: 1414 

### Steps to reproduce

create datetime field in ct.
insert some data like: 1414

### Expected result
 the time field will be filled with 14:14

### Actual result
00:00

**Comment by bobdenotter** [comment]
And if you input it as `15:15`.. Does it work as expected then?

**Comment by rainpoiss** [comment]
yes, when i manually insert : then, it will work

**Comment by bobdenotter** [comment]
In that case, i'm not sure if it's something that's feasible to fix.. it looks like this is the behaviour of the Javascript thingy we used for this.

**Comment by JarJak** [comment]
We can't make implicit conversion from 1414 to 14:14. 1414 is an invalid field value.
