### ISSUE TITLE
Error image field on preview page

### ISSUE THREAD

**Issue by otrelin** [bolt/bolt#7718]
I have field `banner` with type `image`.
![default](https://user-images.githubusercontent.com/15085327/49220987-6ce57100-f3e0-11e8-8620-53ffc1f47bbf.png)

On my page template `page.twig` I use this field:
![default](https://user-images.githubusercontent.com/15085327/49221102-cc438100-f3e0-11e8-99fe-00b9f1fcf72c.png)

In front site everything is ok. But when I click "Preview" button in backend
![default](https://user-images.githubusercontent.com/15085327/49221406-b1254100-f3e1-11e8-9d32-162f887b3c27.png)
I get this error:
![default](https://user-images.githubusercontent.com/15085327/49221433-cc904c00-f3e1-11e8-8a93-01c9fcd0465b.png)

The problem is that the `image` type field is obtained in different ways.
When I do
`{{ dump(record.banner) }}`
in frontend I see
![default](https://user-images.githubusercontent.com/15085327/49221601-458fa380-f3e2-11e8-8701-53a0d60bd101.png)
and in preview I see
![default](https://user-images.githubusercontent.com/15085327/49221637-6526cc00-f3e2-11e8-8648-f242a3698ec6.png)

This error began to manifest itself with version 3.6.0 and is present in 3.6.1 and 3.6.2.
In version 3.5.7 there was no such error - in both cases the field was returned as a string.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   |  Composer install
| PHP version                 | 7.2
| Web server                  | Apache

**Comment by JarJak** [comment]
This happens because Record for preview is created differently than for normal view and this is not the only difference. 
Anyway it is a bug but needs some code rewrite to fix.

You can fix it for now by using:
`{{ asset(record.banner.file | default(record.banner), 'files') }}`

**Comment by otrelin** [comment]
Will it be fixed? Now the only stable version is 3.5.7 as I see.

**Comment by JarJak** [comment]
I don't think we can fix this without BC break. However we could fix this in version 3.7 (Bolt 3.x does not guarantee backwards compatibility but Bolt 4.x will) but Bolt 3.7 is not planned yet.

Doesn't my solution above satisfy you?

**Comment by otrelin** [comment]
In your solution, I need to add this "crutch" to all templates in all places where images are used. I would not want to do that.

**Comment by JarJak** [comment]
Do you use legacy storage or the new one?

**Comment by otrelin** [comment]
What do you mean? I use version 3.5.7.

**Comment by JarJak** [comment]
https://github.com/bolt/bolt/blob/3.6/app/config/config.yml.dist#L463
Do you have this option set as true of false?

**Comment by otrelin** [comment]
It's set to `true`

**Comment by JarJak** [comment]
So if you are using legacy storage we can't fix this without breaking. You can try to switch the setting to `false` but this could not be stable enough.

**Comment by bobdenotter** [comment]
Fixed as a workaround in #7753.
