### ISSUE TITLE
[RFC] Option for other attr on imagefields

### ISSUE THREAD

**Issue by ankedsgn** [bolt/bolt#7741]
Right now, the options for attributes on the imagefield are limited to `alt` and `title`.
I sometimes run into situations where I'd like more or other attributes. 

If I'm correct, the value of the imagefield is stored as JSON on the db, and the attributes are retrieved with `record.values.image.title` and `record.values.image.alt`.
 
So other then that it's not actually working at the moment, I don't think there would be a technical problem with implementing something like `record.values.image.customvalue` ?

Some thoughts on that?

**Comment by sbonardt** [comment]
:+1: from me. I would like the option to add a 'caption' for instance
