### ISSUE TITLE
[RFC] Exerpt runtime strip keys

### ISSUE THREAD

**Issue by artggd** [bolt/bolt#7758]
Hello,

`Bolt\Helpers\Excerpt` is great but it could be improved by adding `$stripKeys` as a fourth argument. This way, one could easily remove unwanted fields from a search result.

At the moment, the `$stripKeys` array is hardcoded [here](https://github.com/bolt/bolt/blob/3.6/src/Helpers/Excerpt.php#L58), a simple `array_merge` would do the job. An optional fourth argument wouldn't break any BC.

Keen on PR if this is approved 🙂

**Comment by bobdenotter** [comment]
Hi @artggd, 

Seems like it would break no existing usecases, so feel free to make a PR for it! Thanks! 👍

**Comment by artggd** [comment]
\o/ Working on it
