### ISSUE TITLE
Issues loading thumbnails from a directory that starts with a whitespace.

### ISSUE THREAD

**Issue by Spomsoree** [bolt/bolt#7761]
Issues loading thumbnails from a directory that starts with a whitespace.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   | Composer install
| BC Break                     | no
| PHP version                 | 7.2
| Web server                  | Nginx
| For UX/UI issues        | All browsers

Reproduction
------------

### Bug summary

I'm getting a 404-Image as soon as I try to load a thumbnail which is located in a directory that starts with a whitespace.

### Steps to reproduce

If I create a directory that starts with a whitespace I'm not able to generate thumbnails.
Needed settings are:

You have to save generated thumbnails:
```
thumbnails:
    save_files: true
```

Then you have to create a thumbnail-alias which could looks like this:
```
thumbnails:
    aliases:
        test_thumbs:
            size: [400, 230]
            cropping: crop
```

As the last step we need to create a directory in here '/bolt/files' that starts with a whitespace.

If we now try to load the thumbnail in the frontend `image|thumbnail('test_thumbs')` we get an 404-Image.

### Expected result

I'd expect the image to load.

### Actual result

I'm getting the 404-Image:
![image](https://user-images.githubusercontent.com/14187981/54670296-a2c77600-4af3-11e9-9ce0-28e361fcd4aa.png)

This is the path the site tries to load the image from:
`/thumbs/test_thumbs/Test2/3.jpg`
But this path is not correct.

The image is located at: 
`/thumbs/test_thumbs/%20Test2/3.jpg`

As far as I understand the directory name of the thumbnails should **not** be trimmed or the location the image is loaded from should be adjusted to the directory name change.

**Comment by bobdenotter** [comment]
Isn't it much, much less confusing for everyone to just not have foldernames starting with whitespaces? 
I mean, even if we fixed this, i can see this being pretty hard to debug when somebody else looks at what's happening.

**Comment by Spomsoree** [comment]
I agree that this is not the best thing to to, but In our case we had a customer which wanted to have a specific directory at the top of the list. Their solution was doing exactly this, which caused this problem.

**Comment by bobdenotter** [comment]
How about starting it with a `_` instead?

**Comment by Spomsoree** [comment]
We found another solution for this case, but In my opinion this is still a bug.
