### ISSUE TITLE
Bolt 3.6.6 fresh install same symptoms as #6856 with PHP 7.0

### ISSUE THREAD

**Issue by sebtombs** [bolt/bolt#7766]
After a fresh install of Bolt 3.6.6 using MySQL as the database, all appears to be well initially. However, check database fails repeatedly.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.6
| Install type                   |  Zip or tar install
| PHP version                 | 7.0
| Web server                  | Apache

Reproduction
------------

Install Bolt 3.6.6 from the tarball.
php app/nut init

edit config.yml to change the database to mysql
Fill in the initial user page

All seems to be well, but the "Check database" warning comes up on the dashboard.

Database check yields the below. Updating the database gives no changes.

This seems to be similar in symptoms to #6856, but presumably can't be the same cause because that is long since merged.

Modifications needed:
    Table bolt_authtoken is not the correct schema: invalid column user_id, invalid column username, invalid column lastseen, invalid column ip, invalid column useragent, invalid column validity
    Table bolt_blocks is not the correct schema: invalid column datepublish, invalid column datedepublish, invalid column ownerid, invalid column templatefields, invalid column title, invalid column contentlink, invalid column image
    Table bolt_entries is not the correct schema: invalid column datepublish, invalid column datedepublish, invalid column ownerid, invalid column templatefields, invalid column title, invalid column image, invalid column video
    Table bolt_field_value is not the correct schema: invalid column block, invalid column value_string, invalid column value_integer, invalid column value_float, invalid column value_decimal, invalid column value_date, invalid column value_datetime
    Table bolt_homepage is not the correct schema: invalid column datepublish, invalid column datedepublish, invalid column ownerid, invalid column templatefields, invalid column title, invalid column image, invalid column contentlink
    Table bolt_log_change is not the correct schema: invalid column ownerid, invalid column comment
    Table bolt_log_system is not the correct schema: invalid column ownerid
    Table bolt_pages is not the correct schema: invalid column datepublish, invalid column datedepublish, invalid column ownerid, invalid column templatefields, invalid column title, invalid column image, invalid column template
    Table bolt_showcases is not the correct schema: invalid column datepublish, invalid column datedepublish, invalid column ownerid, invalid column templatefields, invalid column title, invalid column geolocation, invalid column embed, invalid column video, invalid column image, invalid column imagelist, invalid column file, invalid column filelist, invalid column datetime, invalid column date, invalid column multiselect
    Table bolt_users is not the correct schema: invalid column lastseen, invalid column lastip, invalid column shadowpassword, invalid column shadowtoken, invalid column shadowvalidity, invalid column throttleduntil

**Comment by bobdenotter** [comment]
Have you tried updating your PHP version, and running `composer update`?

**Comment by sebtombs** [comment]
I'm on PHP 7.0.33 - Bolt doesn't support 7.1 onwards yet does it? This is a new host and there is something preventing me running composer update - I have tried but it gets killed. I can run composer install.

**Comment by bobdenotter** [comment]
@sebtombs Bolt 3 supports everything between PHP 5.5.9 and PHP 7.3.x.

> I have tried but it gets killed

Look into why that happens, because that'll allow you to fix it.

**Comment by sebtombs** [comment]
Sorry about that. I'd put 2+2 together to make 5 there - When trying composer install with PHP 7.1 selected it complained, but I guess that's because I hadn't run update.

I'm trying the same process now on another host.

**Comment by sebtombs** [comment]
Confirmed using another host that the problem goes away with PHP 7.2 then running composer update. I'll now try PHP 7.1.

**Comment by sebtombs** [comment]
Confirmed problem occurs on PHP 7.0 but not 7.1 onwards.
Used different php-cli versions with composer update and app/nut database:check.

Solution is as Bob said - switch to later PHP and then composer upgrade.

**Comment by bobdenotter** [comment]
@sebtombs Thanks for confirming! I'll close this issue for now. :-)

**Comment by JarJak** [comment]
@bobdenotter issue is closed, so PHP 7.0 won't be supported anymore?
