### ISSUE TITLE
Can't upload files after upgrade to 3.6.6

### ISSUE THREAD

**Issue by otrelin** [bolt/bolt#7770]
After upgrade Bolt to 3.6.6 can't upload any file via File Management in backend.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.6
| Install type                   | Composer install
| PHP version                 | 7.2
| Web server                  | Apache
| For UX/UI issues        | Any browser

Reproduction
------------

Click to "Select files" button, select image file - button "Upload file" is inactive. I've tried different files with different extensions. In previous versions everything worked.
Also I've installed clear Bolt installation - the problem is actual.

![Clipboard - 8 апреля 2019 г , 11-51](https://user-images.githubusercontent.com/15085327/55716749-6f944a80-5a00-11e9-9c42-b6df702f5f27.png)

**Comment by xiaohutai** [comment]
See #7765 for a temporary solution. A PR #7768 is in the works.

**Comment by otrelin** [comment]
Thnx, quick fix is works!

**Comment by bobdenotter** [comment]
Closing as duplicate. :-)
