### ISSUE TITLE
Drag and drop image from stack into (html | teaxtarea | markdown) editors fails

### ISSUE THREAD

**Issue by gpothier** [bolt/bolt#7773]
When dragging an image from the stack and dropping it into an editor, the following happens:
- In HTML editor, the image thumbnail appears instead of the full image
- In Textarea editor, the URL to the thumbnail appears
- In Markdown editor, nothing happens

I would expect the full image to appear in the HTML editor, and a Markdown image tag (also to the full image) in the Markdown editor. In the Textarea editor, I guess it should not be possible to drop an image.

I am in the process of fixing this in the Markdown case, so I'll be sending a PR soon, unless someone is already working on the issue.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   |  both Zip or tar install (quick install) and GitHub checkout
| BC Break                     | yes/no
| PHP version                 | 7.2
| Web server                  | Apache [2.4.38]
| For UX/UI issues        | Firefox 66 & Chromium 73 (both on Linux)

Reproduction
------------

Install from git, setup initial user, create a new Showcase entry (as it has the 3 editor types). Upload an image into the stack, then drag the image from the stack and into each of the editors. The results are as described above.

**Comment by eduardomart** [comment]
The stack is not meant to drag and drop images into content, I am not sure actually of what its purpose is, so I just disable it in `config.yml`

**Comment by gpothier** [comment]
Hmm it seems at some point it was possible, see these issues:
https://github.com/bolt/bolt/issues/7691
https://github.com/bolt/bolt/issues/2947

**Comment by gpothier** [comment]
So I have a solution for the Markdown editor case; it inserts the image tag at the current cursor position when an image is dropped from the stack. 

Below is the `app/src/js/widgets/fields/fieldMarkdown.js` file with a first draft of the fix. If this is of interest, I can improve it and send a PR. Otherwise, I'll make an extension out of it.

```js
/**
 * @param {Object} $     - Global jQuery object
 * @param {Object} uiKit - Global UIkit object
 */
(function ($, uiKit) {
    'use strict';

    /**
     * Markdown field widget.
     *
     * @license http://opensource.org/licenses/mit-license.php MIT License
     * @author rarila
     *
     * @class fieldMarkdown
     * @memberOf jQuery.widget.bolt
     * @extends jQuery.widget.bolt.baseField
     */
    $.widget('bolt.fieldMarkdown', $.bolt.baseField, /** @lends jQuery.widget.bolt.fieldMarkdown.prototype */ {
        /**
         * The constructor of the markdown field widget.
         *
         * @private
         */
        _create: function () {
            uiKit.$('textarea[data-uk-htmleditor]', this.element).each(function () {
                var editor = uiKit.$(this);

                if (!editor.data('htmleditor')) {
                    uiKit.htmleditor(editor, uiKit.Utils.options(editor.attr('data-uk-htmleditor')));
                    
                    // Get the .uk-htmleditor element
                    var $uked = editor.closest('.uk-htmleditor');

                    console.log('_create', this, $uked);
                    
                    var enterCounter = 0; // Needed to avoid flickering of droppable hint. See https://stackoverflow.com/a/21002544/421798

                    $uked.on('drop dragdrop', function (event){
                        event.preventDefault();
                        enterCounter = 0;
                        $(this).css('border', '');
                        
                        // Get dragged object data
                        var $stackItem = $(event.originalEvent.dataTransfer.getData('text/html'));
                        var data = JSON.parse($stackItem.attr('data-file'));
                        console.log(data);

                        // Build image link
                        var str = '![' + data.filename + '](' + data.url + ')';

                        // Insert image link
                        var cm = $('.CodeMirror', $(event.currentTarget))[0].CodeMirror;
                        var doc = cm.getDoc();
                        var cursor = doc.getCursor();
                        doc.replaceRange(str, {line: cursor.line, ch: cursor.ch});
                    });

                    $uked.on('dragenter',function (event){
                        event.preventDefault();
                        enterCounter++;
                        $(this).css('border', '2px solid green');
                    });

                    $uked.on('dragover',function (event){
                        event.preventDefault();
                    });

                    $uked.on('dragleave',function (){
                        enterCounter--;
                        if (enterCounter === 0) {
                            $(this).css('border', '');
                        }
                    });
                }
            });
        }
    });
})(jQuery, typeof UIkit !== 'undefined' ? UIkit : undefined);
```

**Comment by bobdenotter** [comment]
@gpothier Eduardo is correct in that it never was meant to do that.. It's just a browser side-effect (try dragging any of the user-avatars on the page. You can, but it doesn't do anything. 

If you want to make this into a PR, you're more than welcome. 

@eduardomart I'm not sure why people don't get what an amazingly simple utility the stack is, in order to keep track of "latest files".. You're not the first and only to not get the purpose, so in v4, it'll need to get a big do-over to make it clear.

**Comment by gpothier** [comment]
Ok, then I'll try to make drag and drop work consistently in HTML and Textarea editors as well, and send a PR. What do you think the behavior should be for Textarea? Don't accept drops, or insert the file's url?

What is the original purpose of the `data-file` and other `data-...` attributes on the stackitems? That's where I get the original file's url, so I thought it was for drag and drop.
