### ISSUE TITLE
Bolt 3.6 will break with PHP 7.1.28 and higher

### ISSUE THREAD

**Issue by eXistenZNL** [bolt/bolt#7775]
BoltCMS 3.6 will break once people update their PHP version to 7.1.28 because of changes in the intl extension between PHP 7.1.27 and 7.1.28.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | legacy / 3.5 / 3.6 / master
| Install type                   |  Zip or tar install / Composer install / GitHub checkout
| BC Break                     | no
| PHP version                 | 7.1
| Web server                  | Nginx / CLI
| For UX/UI issues        | not relevant

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The php-intl extension version 7.1.28 returns an empty array when using locale_parse('root') whereas php-intl version 7.1.27 returns an array with the key language and value 'root'.

We run Ubuntu 18.04 with Ondřej Surý's PHP repository, which just updated from PHP 7.1.27 to PHP 7.1.28, which causes this issue.

### Specifics

Updating php-intl causes a change in the data returned from locale_compose(), which causes Symfony 2.8's Symfony\Component\Intl\Locale::getFallback('root') to return an empty array. This in turn causes Symfony\Component\Intl\Data\Bundle\Reader::readEntry to never exit the while loop. Finally, this in turn causes Bolt to not load it's web interface anymore (both frontend and backend) but instead fill up all memory available to PHP , and subsequently exit with an internal server error.

Also `composer install` when running PHP 7.1.28 will hang until the memory is eaten up and then throw an out of memory exception.

The underlying issue is explained more in-depth here: https://github.com/symfony/symfony/issues/31089

### Steps to reproduce

Run the following command on PHP 7.1.27 that has php-intl installed:

`$ php -r "var_dump(locale_parse('root'));"`
See the output is:
```
Command line code:1:
array(1) {
  'language' =>
  string(4) "root"
}

```

Now run the same on PHP 7.1.28 with php-intl installed:

`$ php -r "var_dump(locale_parse('root'));"`
See the output is:
```
Command line code:1:
array(0) {
}
```

### Expected result

I would suspect php-intl does the same thing between patch versions but apparently not...

### Actual result

As explained above

### The workaround we applied to have a working BoltCMS:

We traced https://github.com/symfony/symfony/issues/31089#issuecomment-482542636 and found the change is not in Location.php as suggested, but in Locale.php:
https://github.com/symfony/symfony/pull/30781/files?file-filters%5B%5D=.php

We then copied over Symfony's Locale.php to a different location in our project (we chose src/SymfonyOverrides), applied the patch from the PR above, and added this Locale.php to 
Composer's autoload:

```
        "classmap": [
            "src/SymfonyOverrides"
        ],
        "exclude-from-classmap": [
            "vendor/symfony/intl/Locale.php"
        ],
```
_Update: my colleague @StevendeVries found that we must exclude the original Locale.php to prevent having two classes with the same class name, which is [not supported by Composer](https://github.com/composer/composer/issues/5849#issuecomment-258768647)._

This effectively applies the patch from the PR to Symfony 2.8, so all is good again. However, the real fix would of course be to upgrade to Symfony Flex, which is scheduled for BoltCMS 4.

**Comment by JarJak** [comment]
@eXistenZNL thanks for reporting. Could you create a PR that applies the workaround?

**Comment by bobdenotter** [comment]
I was not yet aware of this issue. Thanks for the extensive report. 

You mention PHP 7.1.28, but I assume the same will apply to the latest 7.2.x and 7.3.x versions, right? 

Would you like a PR to fix this for Bolt? I'll happily get it merged quickly and put out a new release! :-)

> which is scheduled for BoltCMS 4.

![](https://media3.giphy.com/media/mlpCWv8dVK2Ji/giphy.gif?cid=790b76115cc182a15257524e4179509e)

**Comment by StevendeVries** [comment]
Also counts for Symfony <= 4.2.4  with php > 7.2.17

**Comment by bobdenotter** [comment]
I've updated my local environment to PHP 7.2.17, but didn't notice any apparent breakage.. After `composer update` i did get these, though: 

```
  - Updating symfony/intl (v2.8.49 => v2.8.50): Loading from cache
  - Updating symfony/polyfill-intl-icu (v1.10.0 => v1.11.0): Loading from cache
```

Could that make a difference with what you're getting? 

And when you said "it breaks", what exactly breaks and how?

**Comment by alexander-schranz** [comment]
We at sulu had the same problem with some old projects so we created this package: https://github.com/sulu/symfony-intl-fix to overwrite the Locale.php.

**Comment by bobdenotter** [comment]
@alexander-schranz Thanks, that looks very usable for us as well! :-)

When I can reproduce the issue locally, i'll incorporate it.

**Comment by eXistenZNL** [comment]
Nice work by @alexander-schranz , so no need for me to create a custom patch for it anymore :)

The original issue is BTW this: https://bugs.php.net/bug.php?id=77884

**Comment by alexander-schranz** [comment]
@bobdenotter the following code was enough for me to reproduce the issue on current php version:

```php
php -r "require('vendor/autoload.php');var_dump(\Symfony\Component\Intl\Intl::getRegionBundle()->getCountryNames());"
```

@eXistenZNL thx, open source for the win :)

**Comment by bobdenotter** [comment]
@alexander-schranz Ah, yes. That does break for me too. Still looking into how to reproduce it inside Bolt. 

@eXistenZNL, @StevendeVries : For me the question still is valid: What and how does it break in Bolt itself? For me it works as it should: 

![Schermafbeelding 2019-04-26 om 16 50 19](https://user-images.githubusercontent.com/1833361/56816233-66e6a580-6843-11e9-8d7b-00466dbc9668.png)

**Comment by StevendeVries** [comment]
@bobdenotter `composer install` will fail with a memory exhaust

**Comment by eXistenZNL** [comment]
@bobdenotter doublecheck if you have php-intl installed :) Apart from the memory exhaustion when running `composer install`, the page isn't able to load as well because of the same memory exhaustion.

**Comment by eXistenZNL** [comment]
Oh noes, keeping the bots away and poking @bobdenotter with this wonderful Friday afternoon reply :P

**Comment by bobdenotter** [comment]
I haven't acted on this, because i'm still not able to reproduce this. If anybody who's having this problem can PR a fix, i'd happily merge it in. Until that time, I'm afraid I can't do much. 

For reference:

> Now run the same on PHP 7.1.28 with php-intl installed:
> 
> $ php -r "var_dump(locale_parse('root'));"
> See the output is:
> 
> Command line code:1:
> array(0) {
> }

I currently have 7.2.19 running, and it gives that exact output, but no problems running the Bolt backend. And also: 

> @bobdenotter the following code was enough for me to reproduce the issue on current php version:

I can run that snippet just fine.. I'm afraid I really don't know yet how to fix this.

**Comment by JarJak** [comment]
https://3v4l.org/LDvLV

**Comment by bobdenotter** [comment]
Keeping this open for now.. I still haven't bumped into this myself. 

If someone who has this issue _in Bolt_ can provide a fix, i'll happily merge it.
