### ISSUE TITLE
php app/nut not working windows 10

### ISSUE THREAD

**Issue by humaxi** [bolt/bolt#7780]
A brief description of the issue goes here.
I use php app/nut and this is what happends:
`../vendor/bin/nut`

Reproduction
------------
Search on google for how to install bolt.cm and find nothing. Go to bolt.cm and click on quick install. Follow instructions. Next type php app/nut user:add and get the error: 
../vendor/bin/nut

### Expected result
Create account

### Actual result
Path returned in console

**Comment by doenietzomoeilijk** [comment]
This might be caused by app/nut being a symlink to vendor/bin/nut, which is a Unix thing, not a Windows thing. What happens if you run `php vendor\bin\nut` directly?

That's about as far as my Windows knowledge goes, I know things theoretically work there, but I don't touch it myself. ;)

**Comment by humaxi** [comment]
Yeah I am also having that symlink issue I guess. Because running that does work.

**Comment by doenietzomoeilijk** [comment]
Yeah, that's one of the downsides of developing under Windows - a _lot_ of web projects assume Linux or OSX (which usually work similar enough on the command line), you might run into some other weirdnesses too. But good to know running the script directly works!

**Comment by SvanteRichter** [comment]
@vacoup95 Might I recommend you use WSL if you want to develop on windows?
