### ISSUE TITLE
I can not send an email to security@bolt.cm.

### ISSUE THREAD

**Issue by ghost** [bolt/bolt#7787]
Nice to meet you.
I found a security vulnerability. 
So I sent a report to security@bolt.cm in "Contributing to Bolt".
However, the email address can not be sent because the address is returned as unknown．
Where should I send it?
I am using gmail.

**Comment by bobdenotter** [comment]
I'll look into why that address isn't working. For now, feel free to mail me directly at bob@twokings.nl.

**Comment by ghost** [comment]
Thank you for your response.
I will send my report to that email address.
