### ISSUE TITLE
< in markdown is over-sanitized.

### ISSUE THREAD

**Issue by patarapolw** [bolt/bolt#7789]
\< in markdown is over-sanitized, for

ut certain markdown specification requires this, e.g.
- \<URL>  as a shorthand for \[URL](URL)
- `<?php` in code blocks

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   |  Composer install
| PHP version                 | 7.3
| Web server                  | Apache / Nginx / Built-in

Reproduction
------------

Anything after `<` is stripped, no matter where.

As a matter of fact, I have already fixed this, <https://github.com/patarapolw/bolt-markup>, and <http://polvcode.herokuapp.com/entry/learning-php-from-other-programming-languages>

![Screen Shot 2019-07-09 at 19 13 26](https://user-images.githubusercontent.com/21255931/60887066-aab34d80-a27d-11e9-8956-74eb019d4bd7.png)

**Comment by bobdenotter** [comment]
Hi @patarapolw , 

If you have made a patch for this, you're more than welcome to make a PR, so I can get it. :-)
