### ISSUE TITLE
Order nr. link to open tab in backend does not work properly in non-English local.

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#7790]
Relevant Bolt Version | 3.6 / master

Clicking on an order nummer in the listing view in the Bolt the backend takes you to e.g.
`/bolt/editcontent/personen/9#taxonomy`
In e.g. a Dutch install however, this link should go to 
`/bolt/editcontent/personen/9#taxonomie`

I think you catch my drift.

**Comment by bobdenotter** [comment]
> I think you catch my drift.

Nope, sorry.. :-)

Screenshot?

**Comment by evertalbers** [comment]
_Drifts don't come any catchier than this :-)_

Click on **Volgorde** in  
![afbeelding](https://user-images.githubusercontent.com/3974120/60978099-e9eea680-a330-11e9-95b7-5f3315dba422.png)
and you go to 
`(...)/bolt/editcontent/personen/9#taxonomy`
but that's a non-existing tab id so you default to 
![afbeelding](https://user-images.githubusercontent.com/3974120/60978340-4356d580-a331-11e9-8d0e-4dc0fedbfddc.png)
If the link would have gone to 
`(...)/bolt/editcontent/personen/9#taxonomie` (in this Dutch example)
you would land directly in the right tab for **Order/Volgorde**
![afbeelding](https://user-images.githubusercontent.com/3974120/60978524-94ff6000-a331-11e9-9f7c-230924043e63.png)
