### ISSUE TITLE
safe to use bolt3

### ISSUE THREAD

**Issue by smpcasgit** [bolt/bolt#7791]
hi there,
is it safe to use bolt3 the next few years?
just asking because bolt4 is on the way.
thank you

**Comment by bobdenotter** [comment]
Hi  @smpcasgit  

Bolt 3 will be maintained for the forseaable future. It's not going to "stop working" when 4 is stable. :-)

Meanwhile you can follow the development of Bolt 4 here: 

- https://github.com/bolt/bolt
- https://roadmap.boltcms.io

**Comment by SvanteRichter** [comment]
Closing, but will also say that the repo for bolt 4 is no longer bolt/bolt but rather https://github.com/bolt/core.
