### ISSUE TITLE
"Find" function broken in code editor

### ISSUE THREAD

**Issue by benbriedis** [bolt/bolt#7793]
The "Ctrl-F" find function in the code editor has a JS error and the find box fails to display in the code editor.

Details
-------

Relevant Bolt Version |  3.6.9
Install type                   |  Zip or tar install, but with a fair bit of customization
PHP version                 |7.0.33
Web server                  | Apache
For UX/UI issues        |  FF and Chrome on Linux

Reproduction
------------
1. Open up the theme file
2. Click into it and press "Ctrl-F"

The editor find box doesn't open up although the browser one find box does. Note that the browser one only searches the code that is currently visible on the page and is not useful for longer files.

There is a Javascript error and stack trace in the JS console:

codemirror.addons.search.min.js:22 Uncaught TypeError: a.phrase is not a function
    at a (codemirror.addons.search.min.js:22)
    at A (codemirror.addons.search.min.js:21)
    at b.commands.find (codemirror.addons.search.min.js:26)
    at Gc (codemirror.js:162)
    at codemirror.js:163
    at nb (codemirror.js:155)
    at Lf (codemirror.js:162)
    at Tb (codemirror.js:162)
    at Mf (codemirror.js:163)
    at E.Nf (codemirror.js:164)
a	@	codemirror.addons.search.min.js:22
A	@	codemirror.addons.search.min.js:21
b.commands.find	@	codemirror.addons.search.min.js:26
Gc	@	codemirror.js:162
(anonymous)	@	codemirror.js:163
nb	@	codemirror.js:155
Lf	@	codemirror.js:162
Tb	@	codemirror.js:162
Mf	@	codemirror.js:163
Nf	@	codemirror.js:164
(anonymous)	@	codemirror.js:103

PS: It would be very handy to have "maximize code window" option.

**Comment by benbriedis** [comment]
The issue is relevant for me and preventing me from moving to version 3.6.9 as my users require it.   The problem doesn't occur in 3.6.8 so  presumably that's where it was introduced.

**Comment by bobdenotter** [comment]
I'm not aware of any recent changes we made to the code viewer. I'll leave this open, but i'm not sure if this is ours to fix.

**Comment by benbriedis** [comment]
I was guessing it was issue #7783 - see https://github.com/bolt/bolt/blob/v3.6.9/changelog.md  Updating ckeditor may have a broken it.  v3.6.9 fails after a clean install, but v3.6.8 is fine.  Maybe a change to the ckeditor initialisation settings or something?  I had a quick look at the code but didn't figure it out.
