### ISSUE TITLE
'Read More' button for pages on homepage rendering issue on Chrome/Chromium.

### ISSUE THREAD

**Issue by GitHubinat0r** [bolt/bolt#7810]
The 'Read More' button for the page summary of the default theme on Bolt appears to have rendering issues for Chrome/Chromium. 

This applies to the latest version as well as the 'Try Now' site version. Please see attached image.

If I can get guidance on how to tweak / fix it. I can attempt at assisting, but most of my expertise is backend development.

![Default_Theme_Rendering_Error](https://user-images.githubusercontent.com/41084415/65395004-baedab80-dd49-11e9-8ec8-eccad5bc9f9e.png)

**Comment by bobdenotter** [comment]
Hi @GitHubinat0r, 

this should be in the themes repo, in the 2.0 branch somewhere. About here: https://github.com/bolt/themes/tree/2.x/base-2018 , in `/source/scss/theme.scss`, i'd guess. 

I haven't been able to reproduce this on Chrome (macOs) yet, btw..

**Comment by GitHubinat0r** [comment]
I’ll see if I can find / tweak it.

It appears on Chromium(76.0.3809.143) for FreeBSD 12.0 and Chrome(76.0.3809.132) Windows 7.

It’s more apparent at higher resolutions.

**Comment by bobdenotter** [comment]
Actually, I'm seeing it too, now. I'm quite certain that has worked properly before? Maybe a subtle change in Chrome's handling of Flexbox? 

![Screenshot 2019-09-25 at 07 28 26](https://user-images.githubusercontent.com/1833361/65571827-4f345a00-df66-11e9-8413-ed30a320994f.png)

**Comment by bobdenotter** [comment]
The actual fix was this: https://github.com/bolt/themes/commit/8958e04efdb585c496484fd0b24f0eba482f5cc1

I'll need to merge that into the `2.0` branch for Bolt 3, though.. Unfortunately there the build process is a bit broken, so i'll need to spend some more time on that.

**Comment by GitHubinat0r** [comment]
I manually applied the patch and that fixed the issue for me. Hopefully, this won't stay stale as this directly impacts the default theme! If you need me to test anything else, please let me know.

**Comment by bobdenotter** [comment]
Thanks! 

I think the version that ships with Bolt 3.7 has it fixed "out of the box", by now.

**Comment by bobdenotter** [comment]
Apologies, wasn't fixed properly yet. It is now actually fixed, here: https://github.com/bolt/themes/releases/tag/2.0.11
