### ISSUE TITLE
Field labels starting or ending with a %-character

### ISSUE THREAD

**Issue by Spomsoree** [bolt/bolt#7819]
It is not possible to define a label starting or ending with a %, for example: **'Image-Width as %'**

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   |  Composer install
| PHP version                 | 7.2
| Web server                  | Nginx

Reproduction
------------

### Bug summary

Labels ending or starting with **%** cannot be parsed so the fallback is displayed (field name, first letter uppercase).

### Specifics

This happens inside blocks and in fields directly added to contenttypes.
I'm not able to escape it in any way.
It doesn't matter if I use double quotes, single quotes or no quotes at all.

### Steps to reproduce

* Add a field to any contenttype or block.
* Set a label starting or ending with a %-character (e.g. "Image-Width as %")

```
image_width:
    type: integer
    label: 'Image-Width in​ %'
```

* Check the rendered label

### Expected result

The given example should output: **Image-Width in​ %:**

### Actual result

The actual output is: **Image_width:**

### Workaround

As soon as the %-character is not the first or last character, it works as expected.
I added a **zero-width space** after the %-character.

**Comment by bobdenotter** [comment]
This probably has to do with `%` being a marker for placeholders in labels. Could you try `&#37;` instead?

**Comment by Spomsoree** [comment]
Do I have to escape the `&#37;` in any way?

This does not work if I just paste it in as it is.
Is there a documentation on labels and placeholders? I didn't know thats a thing.

**Comment by bobdenotter** [comment]
It's internal stuff, so not really documented other than in the the code.. 

> This does not work if I just paste it in as it is.

So, what _does_ it do?

**Comment by Spomsoree** [comment]
It results in `Width in &#37;:`

**Comment by Spomsoree** [comment]
FYI: This is still an issue to me

**Comment by Spomsoree** [comment]
For everyone running into this issue:

If you add a special space character after the %, it works.
`%​` <- Just copy this. I don't know what character this exactly is:

![image](https://user-images.githubusercontent.com/14187981/104294689-c7a68d80-54bf-11eb-90e9-59a4f08bfa7f.png)

But it works. Seems like a invisible space or something.
