### ISSUE TITLE
SyntaxErrorException with MySQL 8 when storing Repeater fields

### ISSUE THREAD

**Issue by pulciux** [bolt/bolt#7820]
Unable to store records with Repeater or Group fields when using MySLQ 8 as backend.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.10
| Install type                   |  Composer install
| BC Break                     | yes
| PHP version                 | 7.3
| Web server                  | Apache
| For UX/UI issues         | All
| DBMS                          | MySQL >= 8.0.1

Reproduction
------------

Install MySQL >= 8.0.1 and try to create a record of a content type including a repeater or group field.

### Bug summary

Starting with MySQL 8.0.1, the server supports the SQL GROUPING function.
When Bolt performs a store of a record with Repeater or Group fields, it submits a query with unquoted filed names and it ends up raising an SyntaxErrorException because in MySQL 8.0.1 and above, the name of the filed "grouping" is instead a function.

It can be fixed by quoting the name of the fields.

### Specifics
```

SyntaxErrorException in AbstractMySQLDriver.php line 79:
An exception occurred while executing 'SELECT grouping, id, name FROM bolt_field_value field_value WHERE (content_id = ?) AND (contenttype = ?) AND (name = ?) ORDER BY grouping ASC' with params [null, {}, "sections"]
```

### Expected result

Record successfully stored

### Actual result

it breaks the execution

**Comment by bobdenotter** [comment]
Hi @pulciux, 

I'm not using MySQL 8 myself, yet.. Do you think you could make a PR for the fix?

**Comment by pulciux** [comment]
> Hi @pulciux,
> 
> I'm not using MySQL 8 myself, yet.. Do you think you could make a PR for the fix?

I don't know enough about Bolt internals, I was just trying it, but it seems a first step can be done modifying the queryExistingFields function in **bolt/src/Storage/Repository/FieldValueRepository.php** quoting "grouping".

```
    public function queryExistingFields($id, $contentType, $field)
    {
        $query = $this->createQueryBuilder()
            ->select('`grouping`, id', 'name')
            ->where('content_id = :id')
            ->andWhere('contenttype = :contenttype')
            ->andWhere('name = :name')
            ->orderBy('`grouping`', 'ASC')
            ->setParameters([
                'id'          => $id,
                'contenttype' => $contentType,
                'name'        => $field,
            ]);

        return $query;
    }
```
After that the SELECT works but the successive INSERT breaks for the same reason.
If you can pinpoint me where to look where the INSERT is composed I can try to fix it and go ahead experimenting with the last MySQL version.

**Comment by billytd** [comment]
I'm seeing the same issue using mysql 8.

**Comment by sagarguhe** [comment]
I am as well facing this issue using mysql 8

**Comment by pulciux** [comment]
In my opinion, the better way to solve this issue and possibly similar ones
is to add the table name, not just fields name, in each query the system
performs. In this way, there will be no ambiguity between reserverd names
and fileds name.

Il giorno lun 16 mar 2020 alle ore 10:22 sagarguhe <notifications@github.com>
ha scritto:

**Comment by HeinDR** [comment]
I have the same issue. After an upgrade to ubuntu 20.04 which by default comes with mysql 8 I'm no longer able to save contenttypes with repeater fields. We are now downgrading to mysql 5. It would be nice to fix this issue though. I dont think @pulciux solution, adding table names, will work, because it still will break on the inserts for that part is generated by the doctrine library I think.
So the best solution would be to change the name of the field.

**Comment by mrl22** [comment]
Sorry to bring up an old thread @bobdenotter  but I am trying to resolve this myself.

What I have found is that BoltCMS 3.7 (in my case) does not add quotes around column names. for example "SELECT grouping, id, name FROM..." instead of "SELECT \`grouping\`, \`id\`, \`name\` FROM...". MySQL 8.0 released a new function called grouping(). So now when running "SELECT grouping", the query is trying to call the method and not the column name.

I will continue to try and resolve this issue and post of I find anything.

**Comment by mrl22** [comment]
Following on from my previous post, I have managed to create a hack which fixes this. I do not know a huge amount about Symfony and BoltCMS to fix it the correct way. It is not an issue with BoltCMS but an issue with older versions of Doctrine DBAL not supporting reserved words. 

How to fix:

As @pulciux suggests. Open `bolt/src/Storage/Repository/FieldValueRepository.php` and edit the function `queryExistingFields` and add quotes around grouping.

    public function queryExistingFields($id, $contentType, $field)
    {
        $query = $this->createQueryBuilder()
            ->select('`grouping`, id', 'name')
            ->where('content_id = :id')
            ->andWhere('contenttype = :contenttype')
            ->andWhere('name = :name')
            ->orderBy('`grouping`', 'ASC')
            ->setParameters([
                'id'          => $id,
                'contenttype' => $contentType,
                'name'        => $field,
            ]);

        return $query;
    }

I also had to hack the query builder as I could not find where grouping is being set on insert and update.

Open `vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php` and edit the function `add`

alter the `foreach ($sqlPart as $part)` to read the following:

    foreach ($sqlPart as $part) {
        if ($part === 'grouping = :grouping') $part = '`grouping` = :grouping';
        $this->sqlParts[$sqlPartName][] = $part;
    }

find the function `setValue` and add the following at the top of the function:

    if ($column === 'grouping') $column = '`grouping`';

After this, it should work as expected on MySQL 8 and above.

**Comment by maakfischer** [comment]
@mrl22 Unfortunately your solution does not work for me. Whenever I use a data field of the new type 'repeater', I get the following syntax error:

```
An exception occurred while executing
'SELECT `grouping`, id, name
FROM bolt_field_value field_value
WHERE (content_id = ?) AND (contenttype = ?)
AND (name = ?)
ORDER BY grouping ASC' with params [null, {}, "subjects"]:
```

I fixed it by additionally changing the functions `orderBy()` and `addOrderBy()` in `QueryBuilder.php`:

```
    public function orderBy($sort, $order = null)
    {
        return $this->add('orderBy', '`' . $sort . '` ' . (! $order ? 'ASC' : $order), false);
    }

    public function addOrderBy($sort, $order = null)
    {
        return $this->add('orderBy', '`' . $sort . '` ' . (! $order ? 'ASC' : $order), false);
    }
```

I am using **Bolt version 3.7.5**.
