### ISSUE TITLE
Can't iterate a filelist

### ISSUE THREAD

**Issue by UbioZur** [bolt/bolt#7821]
"This issue tracker is NOT meant for support questions. If you have a question,
please join us in the community, on one of our social platforms like Slack or
the forum: http://bolt.cm/community."
-> Let's talk about that community after I post my problem, shall we?

I have a filelist 'files' in my contenttype.
`{{ dump(record.files) }}`
give 
"[{"filename":"posts-files/file1.pdf","title":"posts-files/file1"},{"filename":"posts-files/file2.pdf","title":"file2"}]"
-> So far so good

```
{% for file in record.files %}
    <a href="/media/{{ file.filename }}">{{ file.title }}</a>
{% endfor %}
```
Code taken from the [documentation ](https://docs.bolt.cm/3.6/fields/filelist)-> Display nothing at all!

```
{% for file in record.files %}
    <a href="/media/{{ file.filename }}">{{ file.title }}</a>
{% else %}
   Empty?!
{% endfor %}
```
Display Empty! But it's not empty as the dump show?
How do I access my filelist?

Now let's talk about that 'community' 
[Community [IRC/Slack/Forum]](https://bolt.cm/community)
Slack -> [invite link](https://boltcms.slack.com/join/shared_invite/enQtNzc5ODc3NzcyMTE5LTFjN2ZmNGUwNDk3NTVjMTdmZjQ3MWMwODdjNDMzN2UyMDk3NDRlZGYwMjEyYjQ1NmY2NjViOGVmODM3ZDgwNDU) is useless, can't go there
IRC -> Was super slow to load, I gave up after 1min
Twitter -> [@BoltCM](@BoltCM) Really? can't even put a link to your twitter handle? it doesn't matter I don't use twitter!
Forum -> Best joke of all, it doesn't exist!

So I only have the issue tracker of Github to try to get info!

**Comment by bobdenotter** [comment]
Hi @UbioZur 

so, what do you get if you do this? 

```
{% for file in record.files %}
    {{ dump(file) }}
{% endfor %}
```


> Now let's talk about that 'community'

Sheesh, you don't have to be a dick about it. Slack works fine, and it's not my fault that you don't use twitter.

**Comment by SvanteRichter** [comment]
Seems like this is the classic thing about file/image lists not working in preview. They work fine if you save them though

**Comment by UbioZur** [comment]
> so, what do you get if you do this?
> 
> ```
> {% for file in record.files %}
>     {{ dump(file) }}
> {% endfor %}
> ```
Same, doesn't go through the loop

> Seems like this is the classic thing about file/image lists not working in preview. They work fine if you save them though

I tried to go through to the post with the permalink (and not preview) and yes, it is working correctly!
Thanks for the info, it sad to lose the preview option but, at least I can keep working on the template for now.

 
> Sheesh, you don't have to be a dick about it. Slack works fine, and it's not my fault that you don't use twitter.

Sorry if it sounds like being a dick.
How about you play a bit of a role play for me, 
Imagine you like to tinker around come coding and web dev in your free time (it's not your job nor your trade). and you would like to seek help with the tool you are using.

On the website, there is no 'support' link but there is that IRC/Slack/Forum link, sound good, there is usually some support in a forum: https://bolt.cm/community

So News: Not what you are looking for when you want to support.
Slack: Sure why not, 'invite link no longer active' -> So maybe not slack
IRC: Didn't work
Twitter: wrong handle -> So maybe not
Manifesto: Not support

Documentation: No
Github bug tracker: here we are, with a disclaimer stating it is not for support

Company support: for commercial, not for my case.

Forum???? Nope nowhere to be linked!

Can you understand a bit of frustration? You want to get something done, it's not working as expected, and as the documentation says...


Now, I appreciate highly and it makes me feel better about the bolt choice that the page has now be modified for proper links in slack and twitter, the irc has been removed, (could still just remove that forum from the menu name.

I still highly prefer bolt to WordPress, it's so much more fun to tinker with it. But some things don't work as intended and not everyone fancies going into the code to see why the doc is wrong and doesn't give correct information (for that case just the midding information that it doesn't work during the preview (published or draft)
