### ISSUE TITLE
[Bug] incorrect sorting order of extensions in back-end

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7829]
When you install an extension from the backend. You'll see the earliest version on top:

![image](https://user-images.githubusercontent.com/4630335/69708391-d1263800-10fb-11ea-99f2-c4eaa66fa205.png)

However, the most relevant version is on bottom (when you expand the list):

![image](https://user-images.githubusercontent.com/4630335/69708600-2eba8480-10fc-11ea-89a3-0711abed2ab7.png)

The sorting is reversed.

Details
-------

| Question              | Answer
|---------------------- | ------
| Relevant Bolt Version | 3.5.x and 3.6.x (probably irrelevant)
| Install type          | probably irrelevant
| PHP version           | probably irrelevant
| Web server            | probably irrelevant

Reproduction
------------

- Go to back-end
- Go to extensions
- Install any extension that has multiple versions.

### Expected result

Reversed sort order, with the most relevant (recent) version on top.

Not sure which part is exactly responsible:
- Front-end (sort the results when generating the rows)
- JSON response of Bolt e.g.: `/bolt/extensions/installInfo?package=bobdenotter/seo`
- Some response from the Marketplace (Satis)

**Comment by ankedsgn** [comment]
+1.
Cost me a night figuring out why my stuff wasn't working, and why I had an older version.
Pls fix! thx!

**Comment by bobdenotter** [comment]
Fixed in: https://github.com/bolt/site-market-bolt-cm/pull/81
