### ISSUE TITLE
Request to support KaTeX in Bolt

### ISSUE THREAD

**Issue by s1-ranjan** [bolt/bolt#7834]
It becomes very difficult to write mathematical notations in Bolt, it would be nice if bolt have a plug-in to support beautiful maths by using KaTeX, because the output is of good quality and moreover it's fast.

How can you help?
-------------------------------
I can test the plug-in and provide feedback.

**Comment by SvanteRichter** [comment]
You can probably add this plugin https://ckeditor.com/cke4/addon/katex in the same way as the a11y plugin is done: https://github.com/bolt-looking-for-maintainers/bolt-a11ychecker
