### ISSUE TITLE
Unable to make Bolt work in subdirectory

### ISSUE THREAD

**Issue by servusdei2018** [bolt/bolt#7837]
I have a folder structure like this:

`/srv/mysite.com/public_html` is the web root, and under `/srv/mysite.com/public_html/bolt` I've used Composer to install bolt. That created a directory that matched the name of my project, and when I opened it in my browser ("mysite.com/bolt/myproject"), I got the page for "Bolt - Installation error" which says "You've (probably) installed Bolt in the wrong folder." After reading it, I moved everything from the subdirectory `/srv/mysite.com/public_html/bolt/myproject` one level up (to `/srv/mysite.com/public_html/bolt`, but I still get the same error message.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | master
| Install type                   | Composer install
| BC Break                     | (I don't know)
| PHP version                | 7.4
| Web server                  | Apache

### Expected result

I expect Bolt to run under the subdirectory, accessible by "mysite.com/bolt`

### Actual result

I get an error message "Bolt - Installation error"

**Comment by bobdenotter** [comment]
You should make a subdomain on your hosting, like 'bolt.mysite.com'. It'll cause you much, much less grief. If the instructions in the documentation don't make it work for your hosting environment, I'm even more strongly advising to just do the subdomain.
