### ISSUE TITLE
Trying to access array offset on value of type null with PHP 7.4

### ISSUE THREAD

**Issue by andersonamuller** [bolt/bolt#7843]
With a fresh installation of Bolt 3.7, I'm getting the following message after enabling the symfony debug:
`"Notice: Trying to access array offset on value of type null" `
This is because a variable `user` is null (not logged in), and in PHP 7.4 this is not allowed anymore, to access as an array.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7 / master and maybe others, I haven't check
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4
| Web server                  | Nginx

Reproduction
------------

Just a new install of Bolt 3.7 on PHP 7.4

### Bug summary

The error happens here:

https://github.com/bolt/bolt/blob/da7fb0bf7a729c83f8060c6e17c039fab58050ae/src/AccessControl/Permissions.php#L550

### Screenshot
![Screenshot from 2020-03-27 16-32-10](https://user-images.githubusercontent.com/1681800/77778052-b71c4800-7050-11ea-80bb-8d39bf93f23c.png)

**Comment by commonquail** [comment]
Same thing happens with `editlink()` for anonymous users in any template: https://github.com/bolt/bolt/blob/3.7/src/Twig/Runtime/RoutingRuntime.php#L73 doesn't check for null `users` first.

**Comment by bobdenotter** [comment]
@commonquail Which version of Bolt? Php?

**Comment by commonquail** [comment]
3.7.1 and 7.4. No trouble with signed in users, and checking `user` for truthiness before invoking `editlink()` on a record is also safe.

**Comment by chungf** [comment]
> Same thing happens with `editlink()` for anonymous users in any template: https://github.com/bolt/bolt/blob/3.7/src/Twig/Runtime/RoutingRuntime.php#L73 doesn't check for null `users` first.

Changing that line from:
`if ($this->users->isAllowed($perm)) {`
to:
`if ($this->users->getCurrentUser() && $this->users->isAllowed($perm)) {`
did the job for me.

(Bolt 3.7.1; PHP 7.4.5)

**Comment by bobdenotter** [comment]
@chungf Thanks! Additional PR for this is in #7869
