### ISSUE TITLE
Tags suggestion list is broken

### ISSUE THREAD

**Issue by marcingajda** [bolt/bolt#7845]
Adding existing tags makes them display as slugs instead of names. 
Probably a regression after https://github.com/bolt/bolt/pull/7822.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7
| Install type                   |  Composer install
| BC Break                     | yes?
| PHP version                 | 7.3
| Web server                  | Nginx (latest)
| For UX/UI issues        | Chrome

Reproduction
------------

### Bug summary

After selecting an existing tag from the select suggestion list it is saved in the database with the slug in the place of name. After that Bolt displays tags slugs instead of full names. Adding new tags works fine.

### Steps to reproduce

1. Create a content type eg.: `articles` with tags taxonomy like this
```
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: true
    listing_template: "tags.twig"
    options: {}
```
2. Edit a record of this content type eg.: http://example.com/bolt/editcontent/articles/123
3. Go to the tags selector and add a brand new tag like "Foo Bar"
![image](https://user-images.githubusercontent.com/6128754/78300917-98c6b880-7538-11ea-92fb-b76b1c2283fe.png)
4. Save the article and observe the Network tab in Chrome inspector to see that the tag is send properly
![image](https://user-images.githubusercontent.com/6128754/78301009-be53c200-7538-11ea-8bb6-597ab0799201.png)
5. Refresh the editor and see that the tag looks good:
![image](https://user-images.githubusercontent.com/6128754/78301043-cf9cce80-7538-11ea-8f00-040667b5687c.png)
6. Edit a second article eg.: http://example.com/bolt/editcontent/articles/789
7. Go to tags select and choose the same tag but from suggestion list
![image](https://user-images.githubusercontent.com/6128754/78301212-0f63b600-7539-11ea-8213-f8734d1bbc8e.png)
8. Save the article and see in the Network inspector that this time the tag is send as a slug:
![image](https://user-images.githubusercontent.com/6128754/78301413-4fc33400-7539-11ea-8f5e-045691252e7b.png)
9. Refresh the editor to discover that the tag displays in the select as slug
![image](https://user-images.githubusercontent.com/6128754/78301493-708b8980-7539-11ea-9b0f-747bd9fea978.png)
10. The same happens on the frontend
![image](https://user-images.githubusercontent.com/6128754/78301569-92850c00-7539-11ea-8ecf-a6feb9832798.png)

### Expected result

Tags should be always displayed with the original name

### Actual result

After selecting a suggested tag it displays as a slug.
In the database it's also saved with incorrect name:
![image](https://user-images.githubusercontent.com/6128754/78301741-d415b700-7539-11ea-8469-61d66aa1a216.png)

**Comment by decemberly** [comment]
I'm also having this issue in Bolt 3.7.

**Comment by hannesl** [comment]
Same issue here.

Yes, #7822 is probably the culprit. That PR changed the article form to identify tags using their slugs rather than their names, which is probably a good idea, but somewhere there is some code that wasn't updated to reflect this. Another challenge is that new tags don't have a slug until they're saved, which is probably the reason why names were used instead of slugs to begin with.
