### ISSUE TITLE
BOLT REST API?

### ISSUE THREAD

**Issue by lautiamkok** [bolt/bolt#7847]
I wonder there is any API feature in Bolt just like in [WordPress](https://developer.wordpress.org/rest-api/) in which the developer can create their [custom endpoints](https://developer.wordpress.org/rest-api/extending-the-rest-api/), etc?

Can't find any info on the Bolt doc so I think there is no such feature. It would be great to have, I think!

Thanks.

**Comment by bobdenotter** [comment]
There's the JSON API extension for bolt 3, and Bolt 4 will ship with [API platform](https://api-platform.com) built in.

**Comment by ChangePlaces** [comment]
This is sad to hear as the API platform is very complicated. I understand there are no suitable alternatives though.
