### ISSUE TITLE
[RFC] Incorporating symfony/workflow

### ISSUE THREAD

**Issue by ChangePlaces** [bolt/bolt#7851]
A workflow belongs to a content type(/s) and allows an object to be in one state and can move from one state to another state via transitions, e.g. draft --- _checked_---> reviewed ---- _editor publishes_ ---> published.  (italics are transition names). In code, an object could be put into any state, but in the UI, the user will generally use transitions to move from one state to another.

Some workflows allow an object to be in more than one state at a time, e.g. taking the draft/reviewed/published workflow and extending it, we could replace published with published_on_site1 / published_on_site2 etc. An object may be published on site1 and be in that state, but may not be published on site2 so won't be in that state.

Workflows are defined in a yaml file in symfony/workflow and so once defined in bolt, Content types could have a fieldtype that's for allowing the user to set the workflow,

(This would also pave the way for actions to take place when an object moves into a certain state, e.g. to email the editor that an article has been reviewed and is ready for publishing etc)

How can you help?
-------------------------------

I can code. a bit. well, quite a bit.

**Comment by bobdenotter** [comment]
In Bolt 4 (github.com/bolt/core), we're using Symfony 4, and it could be incorporated. If this is something that you'd like to help flesh out, I'll happily discuss how to integrate it there. I don't think it'd make sense to do it for the v3 version, still. :-)

**Comment by ChangePlaces** [comment]
I'll start a new issue on the other repo then. Why symfony 4 and not 5? There are some awesome changes in 5.

**Comment by bobdenotter** [comment]
> Why symfony 4 and not 5? There are some awesome changes in 5.

I know! 

See https://github.com/bolt/core/issues/1182 ;-)

**Comment by ChangePlaces** [comment]
awesome, because i was not looking forward to having to write bundles to add my custom code.

Could we get this relation issue into bolt 4?

**Comment by rixbeck** [comment]
I love workflows and worth to use regarding in programming almost everything is a finite state machine. :) Moreover the SF solution is quite simple and comfortable.
