### ISSUE TITLE
"Uncaught Exception: ContextErrorException" when in Maintenance Mode

### ISSUE THREAD

**Issue by crim3hound** [bolt/bolt#7858]
Trying to access the website in maintenance mode throws a context error with the notice `Trying to access array offset on value of type null`. The error seems to be a permissions bug in `\vendor\bolt\bolt\src\AccessControl\Permissions.php` at line 550 as shown below:

`$rqCacheKey = $user['id'] . '//' . $what . '//' . $contenttypeSlug . '//' . $contentId;`

It appears that trying to access the user ID is what is causing the error when logged off from the back-end, rendering the maintenance page inaccessible. Changing `$user['id']` to `$user` or deleting `$user['id']` altogether seems to solve the problem, but because this is core code, perhaps it should be merged into the master repository?

Details
--------
**Environment:**                Development (local machine)
**Bolt Version:**                 3.7.0
**Install type:**                   Zip install
**BC Break:**                      Unsure
**PHP version:**                 7.4.4
**Web Server:**                  Apache, version 2.4.41 (Win64)
**Browser:**                       Firefox, version 76.0.1

### Bug summary
Context error thrown in PHP 7.4.4 instead of displaying maintenance page in the front-end, possibly due to permissions errors.

### Error Screenshot
![maintenance_mode_exception](https://user-images.githubusercontent.com/29301735/81657498-982b1700-9440-11ea-9a8a-721d491f40f2.jpg)

### Steps to reproduce
1. Install XAMPP version 7.4.4 on Windows environment.
2. Download and install Bolt version 3.7.0 (flat structure) in `xampp/htdocs/site`
3. In `config.yml` set maintenance mode on, i.e. `maintenance_mode: true`
4. In `config.yml` turn on debug modes, i.e. `debug: true` and `debug_show_loggedoff: true`
5. Log off from the back-end and access the site in the front-end by visiting the respective URL, e.g. `http://localhost/site`

### Expected result
Maintenance page should be displayed on the front-end to users when `maintenance_mode` is set to `true`.

### Actual result
An context error is thrown at line 550 in `\vendor\bolt\bolt\src\AccessControl\Permissions.php` with the notice `Trying to access array offset on value of type null`.

**Comment by simonmnt** [comment]
Same error with `php 7.4.2` but not with `7.3.9`

<img width="947" alt="Capture d’écran 2020-06-25 à 14 20 44" src="https://user-images.githubusercontent.com/1232756/85719070-610e7d80-b6ef-11ea-839b-ef565d788851.png">

**Comment by crim3hound** [comment]
> 
> 
> Same error with `php 7.4.2` but not with `7.3.9`
> 
> <img alt="Capture d’écran 2020-06-25 à 14 20 44" width="947" src="https://user-images.githubusercontent.com/1232756/85719070-610e7d80-b6ef-11ea-839b-ef565d788851.png">

After further tests, it seems that the issue is a PHP related, but I was able to at least customise my Maintenance and 404 pages by modifying `\vendor\bolt\bolt\src\AccessControl\Permissions.php` temporarily. My production environment is on PHP 7.2 and the error does not come up. However, I believe this should be looked at in the source code otherwise people will still run into problems in the future.

**Comment by xiaohutai** [comment]
Hi! Can you try updating to Bolt 3.7.1 and see if it works?
I can't seem to reproduce this on Bolt 3.7.1 and PHP 7.4.8. But it does fail on 3.7.0.

**Comment by crim3hound** [comment]
@xiaohutai I typically download Bolt as a flat structure to counter server issues, and it appears that Bolt 3.7.1 is not yet officially available for download.

**Comment by xiaohutai** [comment]
It should be available:
- https://bolt.cm/pages/download (it says 3.7.0, but the files are 3.7.1)
- https://bolt.cm/distribution/archive/3.7

See also: https://github.com/bolt/bolt/issues/7843

**Comment by crim3hound** [comment]
@xiaohutai I can confirm the error is gone in `Bolt 3.7.1` and `PHP 7.4.4`, and the maintenance page displays as expected. I have also tested with `PHP 7.4.8` and everything is A-OK! Thanks.

![bolt-3 7 1_php-7 4 4_maintenance](https://user-images.githubusercontent.com/29301735/88828243-9ec16300-d1d3-11ea-8b4c-9becc4abdcdd.PNG)

**Comment by xiaohutai** [comment]
That's great! Thanks for the update.
