### ISSUE TITLE
"Imagelist" returns JSON-string instead of array in preview

### ISSUE THREAD

**Issue by lrilling** [bolt/bolt#7861]
Hi there, 

I currently walked into a bug, using the content type _imagelist_ inside a _block_. When I edit a page adding an imagelist inside a new block and open the page in preview mode, there are now images loaded. I found out that the value returned by the imagelist is not as expected an array, but a string containing a JSON-representation of that array. Therefore twig cannot iterate over it and no image can be displayed. Since twig has no _json_decode_ build in (yet), my current fix is to use the bolt extension for _json-decode_ and convert the content of the imagelist in case it is not iterable.

I am using the Bolt Extensions "_animal/translate_" and "_bolt/labels_", which may interfere with the preview functionality, since it slighty changes the way things are written to database, right?

I will try to test on my own in a clean project, so maybe I can figure out where the bug is myself, but just in case someone is faster than me, I wanted to share it with you. Maybe it is already known, and I just oversaw it on my search through the issues. In that case, sorry.

**Comment by bobdenotter** [comment]
This is a known issue. For blocks and repeaters, the preview isn't always representative.. This is not feasible to fix in Bolt 3, unfortunately. 

(Bolt 4 no longer has this problem)
