### ISSUE TITLE
[3.7] Bolt CMS 3 Incompatible with PHP 7.4 - ContextErrorException in ExceptionListener.php line 285

### ISSUE THREAD

**Issue by Steve-MP** [bolt/bolt#7864]
A brief description of the issue goes here.

Details
-------
A recent upgrade of Bolt from 3.6 to 3.7 required me to update my server's version of PHP from 7.0 to meet the requirements of all the Composer packages. I decided to go straight to PHP 7.4. After installing PHP 7.4 and running composer update, I got the following error on my homepage:

![Screenshot 2020-07-24 at 11 26 06](https://user-images.githubusercontent.com/13947767/88378828-09bd0500-cda2-11ea-99aa-dd5f956ca742.png)

Thanks to NGINX allowing you to easily specify a PHP version per application, I was able to try PHP 7.3, which then allowed the application to work without this exception occurring.

However, as everyone will be moving to PHP 7.4, I hope it's possible to make Bolt 3 work with PHP 7.4

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7.1
| Install type                   |  Composer install
| BC Break                     | yes
| PHP version                 | 7.4
| Web server                  | Nginx
| For UX/UI issues        | N/A

Reproduction
------------

### Bug summary

Bolt CMS version 3.7 throws a fatal exception when running under PHP 7.4

### Steps to reproduce

* Modify nginx to use php7.4-fpm instead of php7.3-fpm - error occurs
* Modify nginx to use php7.3-fpm - error does not occur

**Comment by xiaohutai** [comment]
Is this a clean Bolt install?

If not, then this is most likely an issue with one or more extensions. Do you have a list of installed/bundled extensions (with their versions)?

**Comment by Steve-MP** [comment]
It's not a clean install, but an upgrade from a previous version. There are a few custom bundles created in-house, but the stack trace there is only showing that the Error Handler class has failed isn't it? There might be an underlying problem with one of the bundles - certainly possible - but it's difficult to diagnose if the core Error Handler class isn't working.

Is vendor/bolt/bolt/src/EventListener/ExceptionListener.php definitely compatible with PHP 7.4?

I seem to not be the only person experiencing this: [https://stackoverflow.com/questions/59888972/notice-undefined-index-args](https://stackoverflow.com/questions/59888972/notice-undefined-index-args)

**Comment by xiaohutai** [comment]
Yeah, it was the point of re-producing the error. It took me quite a bit, but eventually it was simple. I've made a pull request which should resolve this issue.
