### ISSUE TITLE
Fatal Error when file uses namespaces

### ISSUE THREAD

**Issue by cicerogeorge** [bolt/bolt#7865]
My classes are linked together with namespaces, but the very first class called by the framework throws a fatal error as such:

**Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in C:\xampp\htdocs\encrypted\core\Database.php on line 2**

The original file goes like this:

```
<?php
namespace Core;

use \PDO as PDO;

class Database {

	protected $_db_host;
	protected $_db_login;
	protected $_db_pswd;
-------
```

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7
| Install type                   |  Zip or tar install
| BC Break                     | on
| PHP version                 | 7.3.20 ts
| Web server                  | Apache
| For UX/UI issues        | Chrome

Reproduction
------------

Just encrypted my folder. All went well except for this.

Maybe try to create a class that starts with a namespace and run it after encryption.

**Comment by bobdenotter** [comment]
Hi, 

Are you sure this is a Bolt issue? What are you trying to achieve?

**Comment by cicerogeorge** [comment]
Pretty sure,

I'm trying to obfuscate a small php system, that works fine as it is, but when I try to run it after obfuscation I get this error on the first file. I will test more to make sure I'm not doing anything wrong.

**Comment by adetheprince** [comment]
me too
