### ISSUE TITLE
Error when trying to preview an unsaved page

### ISSUE THREAD

**Issue by j4-m** [bolt/bolt#7870]
Hi, first time I've used Bolt and I really like what I see but I'm afraid I've encountered an error.

Using the default site bundle, I have gone to create a new page and, without saving, I clicked the preview button which gave me: 

```
An exception has been thrown during the rendering of a template ("No matching value found for "<"") in "partials/_recordfooter.twig" at line 8.
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7.1
| Install type                   | Composer install
| BC Break                     | yes/no (erm?)
| PHP version                 | 7.3.19
| Web server                  | Apache

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Specifics

* Using MySQL

### Steps to reproduce

1. Install Bolt using the default site bundle
1. Create the first user
1. Create a new 'Page'
1. Fill the Title field
1. Click 'Preview'

### Expected result

To see the preview

### Actual result

An error:

```
An exception has been thrown during the rendering of a template ("No matching value found for "<"") in "partials/_recordfooter.twig" at line 8.
```

**Comment by bobdenotter** [comment]
I've never seen this particular issue before. Could you: 

1) Post a _full_ screenshot of the error?
2) Post what's in `partials/_recordfooter.twig` ?

**Comment by j4-m** [comment]
Hi @bobdenotter 

Thanks for getting back to me so quickly.

Here is the error screenshot: 

https://imgur.com/a/U2Enin7

This is the contents of `public/theme/base-2018/partials/_recordfooter.twig`

```
{# This file is inserted as the 'footer' of each listed record. #}
{% if extended|default() %}

    {# include the 'default' links to taxonomies. Check the documentation for ways to modify and customize
        what is output to the browser: https://docs.bolt.cm/contenttypes/taxonomies#displaying-taxonomies-in-templates #}
    {{ include('partials/_sub_taxonomylinks.twig', { record: record }) }}

    {% set previous = record.previous('id') %}
    {% set next = record.next('id') %}
    {% if previous or next %}
        <nav class="pagination" role="navigation" aria-label="pagination">
            {% if previous %}
                <a href="{{ previous.link }}" class="pagination-previous">&laquo; {{ previous.title|excerpt(44) }}</a>
            {% endif %}
            {% if next %}
                <a href="{{ next.link }}" class="pagination-next">{{ next.title|excerpt(44) }} &raquo;</a>
            {% endif %}
        </nav>
    {% endif %}

    {% set relatedrecords = record.related() %}
    {% if relatedrecords is not empty %}
        <p class="meta">
            <h2 class="is-size-4">{{ __('general.phrase.related-content') }}</h2>
            <ul>
                {% for related in relatedrecords %}
                    <li><a href="{{ related.link }}">{{ related.title }}</a></li>
                {%  endfor %}
            </ul>
        </p>
    {% endif %}

{% endif %}
```
