### ISSUE TITLE
Reporting security issues

### ISSUE THREAD

**Issue by cfreal** [bolt/bolt#7873]
Hello,

The email address you indicate to report security vulnerabilities (security@bolt.cm) does not exist. Do you have another email address I can use ?

Best regards,

**Comment by I-Valchev** [comment]
hi @cfreal , can you try info@bolt.cm ?
Thanks

**Comment by cfreal** [comment]
Sent! Thanks.

**Comment by cfreal** [comment]
Well, it does not work either.

`<info@bolt.cm>: host mail.bolt.cm[109.70.1.226] said: 550 No such recipient`

**Comment by UtechtDustin** [comment]
https://securitytxt.org/ should be used :-)

**Comment by cfreal** [comment]
Issue was solved by sending a Twitter DM to the main developer. Closing.
