### ISSUE TITLE
Setcontent with select field returns exception

### ISSUE THREAD

**Issue by DorienD** [bolt/bolt#7876]
While updating from php 7.1 to php 7.4.11 i've come across an exception error when using `setcontent` with the value of a select field.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7.1
| Install type                   |  Composer install
| BC Break                     | i think so?
| PHP version                 | 7.4.11

Reproduction
------------

### Bug summary

When using code as described below (steps to reproduce) an exception occurs, displaying a notice: _Trying to access array offset on value of type bool_. This used to work with php 7.1.

### Steps to reproduce

Using a select field with multiple contenttypes:

```
home_items_relation:
    type: select
    label: Relatie
    values: (nieuws,voorstellingen)/title,id
```
Use setcontent to get the record:

```{% setcontent relation = r.home_items_relation %}```

### Expected result

Expected result was I could acces the record using setcontent with the value provided from the select field.

### Actual result

Actual result is an thrown exception.

![screencapture-0-0-0-0-8000-2020-10-07-20_50_17](https://user-images.githubusercontent.com/5102362/95375048-5f07ad80-08df-11eb-8e32-dc1b89c9f87f.png)

**Comment by DorienD** [comment]
Hi! Could someone help me with this?

**Comment by niclashoyer** [comment]
we also ran into this using PHP 7.4. I created a patch for bolt 3.7.2 that seems to work for us using PHP 7.4:

https://gist.github.com/niclashoyer/d54596d8c92a5816a2407da587532f2d

You can apply this e.g. using [vaimo/composer-patches](https://github.com/vaimo/composer-patches)
