### ISSUE TITLE
SQL error when accessing certain pages regarding the content-types in the backend

### ISSUE THREAD

**Issue by antiftw** [bolt/bolt#7878]
When trying to view or new content-type it doesn't work correctly for all of the options

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | master
| Install type          | Composer install
| BC Break              | yes/no
| PHP version           | 7.4.3 |
| Web server            | Apache, version [ 2.4.41 (Ubuntu) ]
| For UX/UI issues      | Firefox 81.0 (64-bit) Ubuntu

Reproduction
------------

### Bug summary

I have setup a clean bolt-project using composer install, and when I try some of the new/view content-types in the left menu, it gives me the following error:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TEXT)) ASC) dctrn_result) dctrn_table' at line 1

### Specifics

URLs:  
- http://bolt.localhost/bolt/content/products
- http://bolt.localhost/bolt/content/blocks
- http://bolt.localhost/bolt/new/entries

VERSION: 4.0 (I think, just the one that installs using composer create-project bolt/project on 08 Oktober 2020)
METHOD: Composer install
BROWSER: Firefox 81.0 (64-bit) Ubuntu
CHECKED OTHERS: YES
ERROR MESSAGE: Syntax error or access violation: 1064 You have an error in your SQL syntax;

### Steps to reproduce
- composer create-project bolt/project antiftw/
- change database url in .env file
- bin/console bolt:setup -> follow steps
- Say either yes or no to the fixtures, does not affect the error, I've tried both setups
- login to backend -> bolt.localhost/bolt/
- click on the following menu items:

The errors occur with:

- entries -> new 
- blocks -> view Blocks
- products -> view Products

However when trying to view the following, it does not give me an error, and seems to work correctly:

- pages -> both view pages and new 
- entries -> view
- people -> both view people and new 
- blocks -> new 
- products -> new 

Like mentioned, since I suspected this might have something to do with the fixtures not being there, I tried another fresh install with the fixtures inserted into the database, but this did not fix the error unfortunately.

### Expected result

Expected to see either the new content-type page or overview page of the corresponding content-types

### Actual result

Since the queries differ a bit per content-type, I will post one of each, since the error part is exactly the same for each error.

#### Specific error for new Entry:

`An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_0 FROM (SELECT b0_.id AS id_0, b0_.content_type AS content_type_1, b0_.status AS status_2, b0_.created_at AS created_at_3, b0_.modified_at AS modified_at_4, b0_.published_at AS published_at_5, b0_.depublished_at AS depublished_at_6 FROM bolt_content b0_ LEFT JOIN bolt_field b1_ ON b0_.id = b1_.content_id AND b1_.type IN ('generic', 'templateselect', 'checkbox', 'date', 'slug', 'number', 'email', 'set', 'markdown', 'data', 'imagelist', 'text', 'block', 'collection', 'html', 'image', 'textarea', 'file', 'filelist', 'hidden', 'select', 'embed', 'article', 'redactor') LEFT JOIN bolt_field_translation b2_ ON b1_.id = b2_.translatable_id WHERE b0_.content_type = ? AND b1_.name = ? ORDER BY LOWER(CAST(b2_.value AS TEXT)) ASC) dctrn_result) dctrn_table' with params ["pages", "title"]:`

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TEXT)) ASC) dctrn_result) dctrn_table' at line 1").`

#### Specific error for View Products:

`An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_0 FROM (SELECT b0_.id AS id_0, b0_.content_type AS content_type_1, b0_.status AS status_2, b0_.created_at AS created_at_3, b0_.modified_at AS modified_at_4, b0_.published_at AS published_at_5, b0_.depublished_at AS depublished_at_6 FROM bolt_content b0_ LEFT JOIN bolt_field b1_ ON b0_.id = b1_.content_id AND b1_.type IN ('generic', 'templateselect', 'checkbox', 'date', 'slug', 'number', 'email', 'set', 'markdown', 'data', 'imagelist', 'text', 'block', 'collection', 'html', 'image', 'textarea', 'file', 'filelist', 'hidden', 'select', 'embed', 'article', 'redactor') LEFT JOIN bolt_field_translation b2_ ON b1_.id = b2_.translatable_id WHERE b0_.content_type = ? AND b0_.status <> ? AND b1_.name = ? ORDER BY LOWER(CAST(b2_.value AS TEXT)) ASC) dctrn_result) dctrn_table' with params ["products", "unknown", "title"]:`

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TEXT)) ASC) dctrn_result) dctrn_table' at line 1`

![image](https://user-images.githubusercontent.com/21287634/95658027-2acb0180-0b18-11eb-9ed2-2f2afc56d9d2.png)

**Comment by LordSimal** [comment]
Duplicate of https://github.com/bolt/core/issues/1971
See https://github.com/bolt/core/pull/1977 for proposed solution

**Comment by LordSimal** [comment]
And FYI: this repository  (https://github.com/bolt/bolt) is for the older BoltCMS versions like 3.7 and lower.
BoltCMS 4.0 has its own new repository https://github.com/bolt/core

**Comment by antiftw** [comment]
Ok, I had looked around but I had not found that issue, possibly because I wasn't looking in the right repository ;)

Thanks for the FYI, I will keep that in mind for any other issues I might find.

You can close this issue due to being a duplicate. (I haven't done it myself since I noticed you also linked to it in the other issue)

**Comment by LordSimal** [comment]
I can't close this issue. Either bob (or any other repo maintainer) has to do that or you yourself.

**Comment by antiftw** [comment]
Oki, then I'll close it now
