### ISSUE TITLE
Installation Step of boltcms on linux server (ubuntu 18.04)

### ISSUE THREAD

**Issue by abhaygupta2** [bolt/bolt#7887]
Hi Team,

Please share me the installations steps on linux ubuntu 18.04.

Thanks

**Comment by bobdenotter** [comment]
See here: https://docs.bolt.cm/4.0/installation/installation

**Comment by abhaygupta2** [comment]
Hey bob,

When I am installing version from here:  https://github.com/bolt/bolt/releases

I am getting this error please suggest me.

![Screenshot (100)](https://user-images.githubusercontent.com/73828465/97864424-94f94f80-1d2e-11eb-9733-73f1079b5853.png)

![Screenshot (101)](https://user-images.githubusercontent.com/73828465/97864453-9dea2100-1d2e-11eb-9f85-d96d76dbdc3c.png)



Thanks,

**Comment by bobdenotter** [comment]
The error message is telling you what is wrong: You're installing Bolt in the wrong folder. 

Also, now that Bolt 4 is out, i'd advise to use that, because it has many improvements over v3. See here: https://docs.bolt.cm/4.0/installation/installation
