### ISSUE TITLE
Installation Step of boltcms on linux server (ubuntu 18.04)

### ISSUE THREAD

**Issue by abhaygupta2** [bolt/bolt#7888]
Hey bob,

When I am installing version from here: https://github.com/bolt/bolt/releases

I am getting this error please suggest me.

![Screenshot (100)](https://user-images.githubusercontent.com/73828465/97868028-f6bcb800-1d34-11eb-96e4-f0ab9d375237.png)

![Screenshot (101)](https://user-images.githubusercontent.com/73828465/97868046-00deb680-1d35-11eb-81b4-968fc9a302c6.png)

Thanks,

**Comment by bobdenotter** [comment]
Please don't open duplicate issues for something that doesn't even belong on the github tracker in the first place. I've responded here: #7887
