### ISSUE TITLE
Search when querystring empty throws error on PHP 7.4

### ISSUE THREAD

**Issue by tompato** [bolt/bolt#7902]
When trying to access the /search page on a Bolt install and not providing no search query string or an empty one, ie `/search?search=` or just `/search` it throws an 'ContextErrorException' on line 548 of Frontend.php and states `Trying to access array offset on value of type bool.`

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.7.2
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4.16
| Web server                  | Apache 2.4.41

Reproduction
------------

Setup a Bolt install and visit /search without providing a search query string and on < PHP 7.4 it shows the no results found page, switch to PHP 7.4 and instead it throws the following error.

### Bug summary

When trying to access the /search page on a Bolt install and not providing no search query string or an empty one, ie `/search?search=` or just `/search` it throws the below error.

```
Uncaught Exception: ContextErrorException .

ContextErrorException in Frontend.php line 548:
Notice: Trying to access array offset on value of type bool
```

Issue shows as line 548 of Frontend.php where it sets `->setCount($result['no_of_results'])`

### Steps to reproduce

Setup a Bolt install and visit /search without providing a search query string and on < PHP 7.4 it shows the no results found page, switch to PHP 7.4 and instead it throws the above error.

### Expected result

The search page renders and shows the message for no search results.

### Actual result

Screenshot attached. Only seems to be an issue in PHP 7.4. Have not tried anything higher as I'm not sure Bolt v3 supports anything higher than 7.4.

<img width="977" alt="Screenshot 2021-03-12 at 10 36 43" src="https://user-images.githubusercontent.com/1638465/110929262-b04d1a80-831f-11eb-8f0a-bf89d9762928.png">

**Comment by niclashoyer** [comment]
I provided a patch for this in #7876 which also fixes this issue. Please be aware that this is just a quick fix and may break unconditionally: https://github.com/bolt/bolt/issues/7876#issuecomment-812577329

**Comment by Steve-MP** [comment]
This is not a stale issue - it still occurs in the latest 3.7.4 release.
