### ISSUE TITLE
exposing an endpoint in socket mode

### ISSUE THREAD

**Issue by smoneta** [bolt/bolt#7909]
Hello there, this is *not* an issue but more of a simple guidance question. I enabled socket mode and work just fine but nI need to export to POST endpoints in my app. I see in the bolt [website](https://slack.dev/bolt-js/concepts#socket-mode) that I need to import and use `SocketModeReceiver`.. I see the example and I was wondering if you can share a simple base example of an endpoint config that I can use as a starting point, something simple as `/api` (POST).

Thanks.

**Comment by bobdenotter** [comment]
As pointed out on Slack, I think you're looking for help with a different product that's also named Bolt. :-)
