### ISSUE TITLE
Problems Run bolt.so on M1 Mac

### ISSUE THREAD

**Issue by vieramason** [bolt/bolt#7963]
Hi 
i have problem to load bolt.so ext in php.ini
i have error with this message (incompatible architecture ,have 'x86_64', need 'arm64e')
PHP Startup: Unable to load dynamic library 'bolt'
tried: '....../php/7.4/bolt.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
m1 mac 
mac os montery
php 7.4

**Comment by eduardomart** [comment]
Sounds like you're in the wrong repo, this is for Bolt CMS:
[https://boltcms.io](https://boltcms.io)
