### ISSUE TITLE
Doctrine ORM / ODM for entries

### ISSUE THREAD

**Issue by dominikzogg** [bolt/bolt#817]
Hello

I would prefere those contenttypes would base on doctrine orm/odm entities/documents generated on the base of the contenttypes.yml: This would bolt make a good choice for bigger projects (e-commerce for example). The contenttype could implement interfaces for a product within a cart.

If this is an option, i would make a proposal within the next months.

Regards dominik

**Comment by bobdenotter** [comment]
See #687 for ongoing discussion about refactoring `storage.php`.

Closing this. If this remains an issue, feel free to re-open it.

**Comment by dominikzogg** [comment]
@bobdenotter well, as you mentioned in https://github.com/bolt/bolt/issues/1913 there is no chance for Doctrine ORM and code generation, which makes this issue useless

**Comment by onlinesid** [comment]
Static method is a bad OO practice and is the main reason I don't use Laravel. Static is the opposite of DI since you have to use the class name (you might be able to use some PHP magic to get around it but using PHP magic stuff is also a bad idea). A static method is really not much better than a global function.

**Comment by Dragory** [comment]
@onlinesid This is a bit off topic, but you don't have to use static methods in Laravel; the same methods also available as regular instance methods. The static methods (through what Laravel calls "facades") are only shortcuts for convenience and many devs, including me, choose not to use them.

**Comment by gitllermopalafox** [comment]
@onlinesid Laravel has the "benefits" of the 2 worlds... The static world (I agree with you, I do not like it) and the DI world, of course if you use a good practices of "contracts" (interfaces) and service providers (they are awesome).
