### ISSUE TITLE
AJAX request

### ISSUE THREAD

**Issue by joeygartin** [bolt/bolt#845]
noob question, but trying to wrap my head around how best to build a response for an AJAX request.  Looking at the Async.php file and I get how I can construct the response (expose data from a given table for an autocomplete textbox), but not sure how best to "expose" that in Bolt.  I have built an extension for custom forms, but not familiar enough with how to expose a URL in Bolt.

Sorry for noob question, perhaps not the right forum, but...

**Comment by maxmumford** [comment]
Here's another approach for those searching for an example:

```
<?php

namespace Bundle\Site;

use Bolt\Extension\SimpleExtension;
use Silex\Application;
use Silex\ControllerCollection;
use Silex\ControllerProviderInterface;
use Symfony\Component\HttpFoundation\Request;

class CustomisationExtension extends SimpleExtension implements ControllerProviderInterface
{

  private $app;

  protected function registerFrontendControllers()
  {
      return [
          '/' =>  $this,
      ];
  }

  public function connect(Application $app)
  {
      $this->app = $app;
      $ctr = $app['controllers_factory'];
      $ctr->match('/ajax/ip', [$this, 'ip'])
          ->method('GET');
      return $ctr;
  }


  public function ip(Request $request)
  {
    return 'string-result';
  }
  

}

```

ajax/ip is the path, and ip is the function that should be called when someone visits it.
