### ISSUE TITLE
Try out Silex module for Codeception

### ISSUE THREAD

**Issue by DavertMik** [bolt/bolt#860]
Hi there! Great to see that bolt already have some of Codeception tests. I was planning to develop a Silex module for writing functional tests in Codeception and was looking for a Silex app I can try them on. 

Are interested in this? I could try some basic tests within new module and send you a PR. I will need some feedback from you and maybe some help with Silex.

Thanks.

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
