### ISSUE TITLE
Fetching content related to content

### ISSUE THREAD

**Issue by frostymarvelous** [bolt/bolt#865]
I know we can currently use

    related('relation')

to fetch relations. 
In this case, I want to fetch content that are related to two different content.

Scenario
I have cinemas, movies and showing times
Showing times are related to a cinema and movie.

I want to be able to search for times that are related to a particular movie and cinema. I have both content in the page.
Also, can I search for say, related times that have a date greater than now?

If this is not possible, how can I check if two items are related without an extra call to the database?

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
