### ISSUE TITLE
Docs for multiple "|order()" behaviour wanted (was "Multiple sort")

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#912]
Sometimes there can be a need for multiple sorting for custom contentypes (eg : sort by state, then by town).
Currently, for a new contenttype it is possible to define only one sorting field.

So may I suggest to add this feature to Bolt.cm ?

Thanks

**Comment by dadaxr** [comment]
I think the twig filter trick ( super usefull ) should be mentioned in the doc, in the fetching content section : 

https://docs.bolt.cm/content-fetching#ordering-results

**Comment by SahAssar** [comment]
Reopening since docs would be nice for the multiple `|order()` filter as @dadaxr stated.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
> And @bobdenotter you said that we can in the {% setcontent %} order by multiple columns, but my attempts failed so ... have you some example ? :)

There was never a response to this, and Im having the same trouble. Using orderby two columns in the setcontent function ignores the second parameter (verified by printquery). How is it done? I cant find any documentation about this.

**Comment by xiaohutai** [comment]
Hi @baronvertigovongrahamthesecondofsealand,

A string with comma-seperated values seems to work for me:
```
{% setcontent foobar = 'pages' orderby '-foo,-id' limit 10 printquery %}
```
