### ISSUE TITLE
Implementing AJAX pagination

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#917]
I wish to implement pagination via the use of AJAX in the form of either an 'endless-scroll' or 'load more' button. With native PHP I would usually create an endpoint and view for just the content that I need to show more of, i.e. a list of records.

How can I achieve the same result with Bolt? Do I need to create a contenttype similar to pages which I can throw parameters at (via AJAX) and then get the desired records back within a specified range?

**Comment by zomars** [comment]
@bobdenotter That writeup you mentioned would be awesome to read, I'm looking to implement that same functionality in this site: http://sinuhe.anclastudio.com/en/arts
