### ISSUE TITLE
.htaccess FilesMatch section: Order directive deprecated in Apache 2.4

### ISSUE THREAD

**Issue by may** [bolt/bolt#926]
Steps to reproduce: 
1. Follow Bolt install directions on Apache 2.4.
2. Navigate to site, receive 500 error.
3.  Read error log:
/public/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration

If you switch to Apache 2.2, the same exact file works fine:
http://systembash.com/content/apache-2-4-upgrade-and-the-invalid-command-order-error/

Possible fix: 
Remove:
    Order deny,allow
    Deny from all
And replace with:
    Require all denied

**Comment by swampopus** [comment]
Old thread, I know, but I was able to put out my software not knowing if the user has 2.2 or 2.4 like this:

```
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
  </IfModule>
```


Example for FilesMatch:
```
# Protect files and directories from prying eyes.
<FilesMatch "\.(engine|inc|info|install|module|profile|test|sh|.*sql|theme|tpl(\.php)?|xtmpl|svn-base)$|^(code-style\.pl|Entries.*|Repository|Root|Tag|Template|all-wcprops|entries|format)$">
  # Apache 2.4 now gives a 500 error if you try to use "Order", so we need
  # to do this if statement to check if its allowed or not.
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
  </IfModule>
</FilesMatch>

```

Got from Drupal8 .htaccess file.  Hope this helps!
