### ISSUE TITLE
Extending user contenttype (was "Feature request: user photo's")

### ISSUE THREAD

**Issue by maaike** [bolt/bolt#927]
We're using {{ blog.user.displayname }} in our templates to show the author of a blogpost. Now we'd also like to show their photo. It would be great if each user could upload a photo in the Bolt backend, to be used in templates as, for example, {{ blog.user.portrait }}. Perhaps even other fields as well, like a url. How about that?

**Comment by SahAssar** [comment]
This issue should probably be the "canonical" one for extending users with additional fields. Perhaps something to add to the wishlist for 3.0?

**Comment by PhillippOhlandt** [comment]
Hey @maaike,

I have made an extension to extend the user profiles and it has also an avatar helper (user can type in an avatar url or it uses a fallback url or gravatar). You can also add public user/author profiles to your site.

Check it out here:
http://extensions.bolt.cm/view/eaf970b8-deca-11e5-bf25-14cdca8e654f

**Comment by SahAssar** [comment]
I'm closing this one since we now have an extension that does basically everything that has been asked here and in related issues. Please feel free to reopen if this needs work in core :)
