### ISSUE TITLE
Use routing when parsing menu.yml

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#934]
Not sure if this is the same issue as #771.

I enabled route example "pagebinding" in routing.yml, as I prefer to have direct paths to pages like /{slug} than /{contenttype}/{slug} 

Then I use this route in menu.yml :
```
      - label: Item 1
        path: page1
      - label: Item 2
        path: page2
```
Actually, links in this menu are OK (I mean urls), but here is the point : in the menu twig I use, I can't access the item record which seems empty. The only way to access it is to use the standard path  /{contenttype}/{slug} in menu.yml

Is it possible to use routings when parsing menu.yml ?

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
