### ISSUE TITLE
Extending Bolt Controllers

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#943]
I'm looking to extend the Bolt controller for `Backend`. Basically what I'm trying to do is add additional attributes to the user record. I have found the method which creates the form and have found the method which saves the user in `Users`.

Obviously I don't want to modify the system files as that would cause problems with updates later down the line. I'll also be looking to change the login to use email address rather than username and possibly modify the hashing algorithm.

What is the best approach for extending the above classes?

**Comment by simonbertonsugasti** [comment]
Hi.
I created my FrontendK.php in the Controller Folder.
Extended Frontend. 
And in the routing added:
`homepage:
    path: /
    defaults:
        _controller: controller.frontendk:loginK`

bolt.CRITICAL: InvalidArgumentException: Service "controller.frontendk" does not exist

Anyone can help ?
Thanks in advance

**Comment by GawainLynch** [comment]
You would need to register it as a service on the application container called `controller.frontendk`

Depending on your comfort with Pimple & Silex, I would might be a lot easier to do this as a [Bolt extension](https://docs.bolt.cm/extensions/intermediate/controllers-routes) as that does most of the "magic" for you :smile:
