### ISSUE TITLE
 order request doesn't work in custom listing.twig when using function "related"

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#945]
I use a custom template in dashboard for some contenttype (lets' call it "customtype1). It works fine, except when I click on sorting link in listing_header.

Actually, my template displays relations of a second customtype (let's call it "customtype2") by using "related" function, and problem seems to come from this function.

Here is the error :
>An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT bolt_customtype2.* FROM bolt_customtype2 WHERE ( `bolt_customtype2`.`id` = '8' ) ORDER BY customfield ASC LIMIT 100 OFFSET 0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customfield' in 'order clause'") in "custom/listing/customtype1.twig" at line 70.

Actually, "customfield" is the column I tried to order in customtype1 and doesn't exist in customtype2, but for some reason, the "related()" function seems to propagate the "order" instruction when fetching customtype2 table

For information, here is the column I use in my custom twig at line 70 (it's the line with "related") :
```
        {% for related_record in (content.related("customtype2")) %}
            {{ related_record.values.title }}
        {% if not loop.first %}, {% endif %}
        {% endfor %}#}
```

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
