### ISSUE TITLE
Using Bolt for a community site?

### ISSUE THREAD

**Issue by GermanicWarWulf** [bolt/bolt#953]
Hello, firstly can I congratulate you on Bolt. It's a joy to work with.

I know Bolt is all about being simple and lightweight, and that's why I love it, but I'd also like to expand to create a basic community site that's fully responsive and lightweight.

So my question is, will this be possible, and will there be any extensions created in the future to aid with this process? I'm not a fan of Disqus as an example and would love to use bolt to handle my comments. I'd like members to be able to sign up on their own and then when validated, have access to post comments, upload images to a gallery and configure a profile etc. Eventually I'd also like an integrated forum. I noticed that the Code Consortium has a collection of Symphony2 components to create a forum etc, so I imagine it's something that can be included via a Bolt extension, although I'm not a programmer, hence all these questions. 

https://github.com/codeconsortium

So is this, or will this be something I can achieve with Bolt, or am I asking too much? I really want to stick with Bolt, so I'm hoping this can be achieved. I've tried every CMS you can think of, but I always come back to Bolt as I just feel comfy with it.

Also, what's the best place to talk about Bolt in general? I know you have a forum, but it's not very active. Your IRC channel is very quiet, so that's why I came here to post my questions.

Anyway thanks for reading and I hope you can answer some of my questions.

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
