### ISSUE TITLE
Enhancements for slug-building

### ISSUE THREAD

**Issue by mike-anthony** [bolt/bolt#964]
1. When editing the title, the slug updates just fine. But, if a content type's slug `uses` another field as well, that field should call the necessary JS to update the slug as well.

2. When using the `datepublish` field within a slug, trim out the time. Why do we need the time there? `2014-03-03-164319` doesn't look so great.

3. What are we going to do about using the `id` field within a slug? I think it's only an issue because the ID of a record is not known until such time as it is published for the first time, yes? Perhaps the slug could simply be shown to the end-user as `/post/{id}/something` until such time as the record is published. What do you think?

**Comment by bobdenotter** [comment]
Closing this. If this remains an issue, feel free to re-open it.
