### ISSUE TITLE
Accessing taxonomy contents in templates

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#974]
Question has already been submitted, but to my point of view it's closed without simple answer.

So here I submit a feature request : in templates, we can access almost everything except taxonomy contents.

Actually, there's a way to access taxonomy options listing but it doesn't cover all possible needs :
1) Have a link to taxonomy listing
2) Tag type taxonomy can not be listed

So I would suggest to provide a way to access content of table "bolt_taxonomy" in order to :
1) List all options of a defined taxonomytype
2) Count content records that are linked to this list
3) Provide a link to access each "taxonomylink" route for items of this list

This would allow to display things that are classical in every blog : tag cloud, category list

**Comment by jenSadler** [comment]
I am also really interested in this functionality. The link provided as a partial solution now leads to a 404 error. Does anyone know what it said?
